### ISSUE TITLE
Cannot access elements of list of categorical values

### ISSUE THREAD

**Issue by polikutinevgeny** [pola-rs/polars#10046]
### Checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pypi.org/project/polars/) of Polars.

### Reproducible example

```python
import polars as pl

df = pl.DataFrame({
    'actions': pl.Series([['a'], ['b'], ['c']], dtype=pl.List(pl.Categorical)),
})
df['actions'].list.get(0)
```

<details><summary>Traceback</summary>
<p>

```
Traceback (most recent call last):
  File "/opt/venv/lib/python3.9/site-packages/IPython/core/interactiveshell.py", line 3505, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-12-4709008700ce>", line 1, in <module>
    df['actions'].list.get(0)
  File "/opt/venv/lib/python3.9/site-packages/polars/series/utils.py", line 102, in wrapper
    return s.to_frame().select(f(*args, **kwargs)).to_series()
  File "/opt/venv/lib/python3.9/site-packages/polars/dataframe/frame.py", line 7301, in select
    return self.lazy().select(*exprs, **named_exprs).collect(no_optimization=True)
  File "/opt/venv/lib/python3.9/site-packages/polars/lazyframe/frame.py", line 1530, in collect
    return wrap_df(ldf.collect())
exceptions.ComputeError: cannot construct Categorical from these categories, at least on of them is out of bounds
```

</p>
</details> 

This works:

```python
import polars as pl
df = pl.DataFrame({
    'actions': pl.Series([['a'], ['b'], ['c']], dtype=pl.List(str)),
})
df['actions'].list.get(0)
```

### Issue description

I get an error when trying to access elements of list column that contains categorical elements.

I also get the same message when elements are structs that contain categorical elements (this was my original use-case, so it is a bit more verbose)

```python
import polars as pl
df = pl.DataFrame({
    'user': pl.Series([1, 2, 3]),
    'action': pl.Series(['a', 'b', 'c'], dtype=pl.Categorical),
})
df_agg = df.groupby("user").agg(pl.struct(action='action').alias('events'))
df_agg['events'].list.get(0)
```

### Expected behavior

I expect it to work the same as `str` version, something along the lines of

```
shape: (3,)
Series: 'action' [cat]
[
	"a"
	"b"
	"c"
]
```

### Installed versions

<details>

```
pl.show_versions()
--------Version info---------
Polars:              0.18.8
Index type:          UInt32
Platform:            Linux-6.4.4-arch1-1-x86_64-with-glibc2.31
Python:              3.9.16 (main, Mar 23 2023, 04:33:57) 
[GCC 10.2.1 20210110]
----Optional dependencies----
adbc_driver_sqlite:  <not installed>
cloudpickle:         2.2.1
connectorx:          <not installed>
deltalake:           <not installed>
fsspec:              2023.4.0
matplotlib:          3.7.1
numpy:               1.23.2
pandas:              1.5.3
pyarrow:             11.0.0
pydantic:            1.10.7
sqlalchemy:          1.4.47
xlsx2csv:            <not installed>
xlsxwriter:          <not installed>
```

</details>

**Comment by cmdlineluser** [comment]
It seems to be related to the `StringCache`

```python
pl.enable_string_cache(True)

df = pl.DataFrame({
    'actions': pl.Series([['a'], ['b'], ['c']], dtype=pl.List(pl.Categorical)),
})
    
df['actions'].list.get(0)

# shape: (3,)
# Series: 'actions' [cat]
# [
# 	"a"
# 	"b"
# 	"c"
# ]
```

https://github.com/pola-rs/polars/blob/bb413034890fced83e203110f8da7cf115e55479/polars/polars-core/src/chunked_array/logical/categorical/builder.rs#L460-L468

(The error message also contains a small typo, `at least on of them` -> `at least one of them`)
