### ISSUE TITLE
`pl.format()` fails inside of `.list.eval(...)` when including literal prefix in format string

### ISSUE THREAD

**Issue by Nathan-Fenner** [pola-rs/polars#10080]
### Checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pypi.org/project/polars/) of Polars.

### Reproducible example

```python
import polars as pl

table_with_array_col = pl.from_dict({
  "items": [ ["a", "b", "c"] ],
})

# Print (1)
print(table_with_array_col)


# Print (2)
# Runs as expected:
print(
  table_with_array_col.select(
    pl.col("items").list.eval(pl.format("{}_suffix", pl.element())),
  ),
)

# Print (3)
# Crashes with unexpected error:
print(
  table_with_array_col.select(
    pl.col("items").list.eval(pl.format("prefix_{}", pl.element())),
  ),
)

"""
Print (1)
shape: (1, 1)
┌─────────────────┐
│ items           │
│ ---             │
│ list[str]       │
╞═════════════════╡
│ ["a", "b", "c"] │
└─────────────────┘
"""

"""
Print (2)
shape: (1, 1)
┌───────────────────────────────────┐
│ items                             │
│ ---                               │
│ list[str]                         │
╞═══════════════════════════════════╡
│ ["a_suffix", "b_suffix", "c_suff… │
└───────────────────────────────────┘
"""

"""
Print (3)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File ".../.venv/lib/python3.10/site-packages/polars/dataframe/frame.py", line 7301, in select
    return self.lazy().select(*exprs, **named_exprs).collect(no_optimization=True)
  File ".../.venv/lib/python3.10/site-packages/polars/lazyframe/frame.py", line 1530, in collect
    return wrap_df(ldf.collect())
exceptions.InvalidOperationError: output length of `map` (1) must be equal to the input length (3); consider using `apply` instead

Error originated in expression: 'Utf8(prefix_).str.concat_horizontal([col("")])'
"""

```

### Issue description

I encountered this when upgrading from `0.17.2` to `0.18.8`. It appears to be some kind of unexpected interaction between `pl.eval` and `pl.format` and string literals.

The following also crashes in an identical way:

```py
print(
  table_with_array_col.select(
      pl.col("items").list.eval(pl.format("{}_{}", pl.lit('prefix'), pl.element())),
  ),
)
```

in this case, the "prefix" is interpolated as an `Expr` argument instead of being a part of the format string, but the error is the same.

### Expected behavior

The prefix case should run correctly, just like the suffix case, producing
```py

print(
  table_with_array_col.select(
    pl.col("items").list.eval(pl.format("prefix_{}", pl.element())),
  ),
)
"""
Expected ouput:
shape: (1, 1)
┌───────────────────────────────────┐
│ items                             │
│ ---                               │
│ list[str]                         │
╞═══════════════════════════════════╡
│ ["prefix_a", "prefix_b", "prefix… │
└───────────────────────────────────┘
"""
```

### Installed versions

<details>

```
--------Version info---------
Polars:              0.18.8
Index type:          UInt32
Platform:            macOS-13.4.1-arm64-arm-64bit
Python:              3.10.12 (main, Jun 15 2023, 07:49:25) [Clang 14.0.3 (clang-1403.0.22.14.1)]

----Optional dependencies----
adbc_driver_sqlite:  <not installed>
cloudpickle:         2.2.1
connectorx:          0.3.2a5
deltalake:           <not installed>
fsspec:              2023.4.0
matplotlib:          <not installed>
numpy:               1.24.2
pandas:              1.5.3
pyarrow:             10.0.1
pydantic:            1.10.7
sqlalchemy:          1.4.48
xlsx2csv:            <not installed>
xlsxwriter:          <not installed>
```

</details>

**Comment by cmdlineluser** [comment]
I'm assuming this is a result of #8199 which enabled `.eval()` to run on the groupby engine.
```python
table_with_array_col.select(
    pl.col("items").list.eval(pl.element() + "_bar")
)

# shape: (1, 1)
# ┌─────────────────────────────┐
# │ items                       │
# │ ---                         │
# │ list[str]                   │
# ╞═════════════════════════════╡
# │ ["a_bar", "b_bar", "c_bar"] │
# └─────────────────────────────┘
```
With a literal on the LHS, there is a length mismatch as there is no "broadcasting".
```python
table_with_array_col.select(
    pl.col("items").list.eval("foo_" + pl.element())
)

# InvalidOperationError: output length of `map` (1) must be equal to the input length (3); consider using `apply` instead
# Error originated in expression: 'Utf8(foo_).str.concat_horizontal([col("")])'
```
```python
table_with_array_col.select(
    pl.col("items").list.eval(pl.repeat("foo_", pl.count()) + pl.element())
)

# shape: (1, 1)
# ┌─────────────────────────────┐
# │ items                       │
# │ ---                         │
# │ list[str]                   │
# ╞═════════════════════════════╡
# │ ["foo_a", "foo_b", "foo_c"] │
# └─────────────────────────────┘
```

**Comment by coastalwhite** [comment]
This appears to be fixed. Closing.
