### ISSUE TITLE
Python scan_csv doesn't work for files with square brackets in filename

### ISSUE THREAD

**Issue by petern3** [pola-rs/polars#10106]
### Checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pypi.org/project/polars/) of Polars.

### Reproducible example

```python
>>> import polars as pl
>>> p1 = r"C:\Users\p.nicholls\a normal filename.csv"
>>> p2 = r"C:\Users\p.nicholls\a [weird] filename.csv"
>>> pl.scan_csv(p1)
<LazyFrame [2 cols, {"heading 1": Int64, " heading 2": Int64}] at 0x2B045658E80>
>>> pl.scan_csv(p2)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\p.nicholls\.virtualenvs\rlavionicsatp-ZPWLgrmq\lib\site-packages\polars\io\csv\functions.py", line 875, in scan_csv
    return pl.LazyFrame._scan_csv(
  File "C:\Users\p.nicholls\.virtualenvs\rlavionicsatp-ZPWLgrmq\lib\site-packages\polars\lazyframe\frame.py", line 346, in _scan_csv
    self._ldf = PyLazyFrame.new_from_csv(
exceptions.ComputeError: no matching files found in C:\Users\p.nicholls\a [weird] filename.csv
```

### Issue description

`pl.scan_csv` doesn't work when reading filenames with square brackets in the filename in Windows 10. This previously worked, and continues to work on python polars 0.18.4, but fails on 0.18.5.

There doesn't appear to be anything relevant in the changelog, but after a brief look, I think it's feasible the issue was introduced in this commit: https://github.com/pola-rs/polars/commit/85b9b8912b7f9d1cd1fa0f3349c470d8d1c25b32

Thanks for the fantistic library!

### Expected behavior

```
>>> import polars as pl
>>> p2 = r"C:\Users\p.nicholls\a [weird] filename.csv"
>>> pl.scan_csv(p2)
<LazyFrame [2 cols, {"heading 1": Int64, " heading 2": Int64}] at 0x2B045658E80>
```

### Installed versions

<details>

```
--------Version info---------
Polars:              0.18.8
Index type:          UInt32
Platform:            Windows-10-10.0.19045-SP0
Python:              3.9.7 (tags/v3.9.7:1016ef3, Aug 30 2021, 20:19:38) [MSC v.1929 64 bit (AMD64)]

----Optional dependencies----
adbc_driver_sqlite:  <not installed>
cloudpickle:         <not installed>
connectorx:          0.3.1
deltalake:           0.10.0
fsspec:              2023.6.0
matplotlib:          3.7.2
numpy:               1.24.4
pandas:              1.5.3
pyarrow:             12.0.1
pydantic:            1.8.2
sqlalchemy:          <not installed>
xlsx2csv:            0.8.1
xlsxwriter:          <not installed>
```

</details>

**Comment by cmdlineluser** [comment]
I guess it's from #9721 as `[]` is causing it to be detected as a glob pattern.

`a [weird] filename.csv` ends up trying to match
```
a w filename.csv
a e filename.csv
a i filename.csv
a r filename.csv
a d filename.csv
```
Question marks should work
```
p2 = r"C:\Users\p.nicholls\a ?weird? filename.csv"
```
But that also brings up the issue of wanting to match literal question marks in filenames.

It seems like perhaps there may need to be an option to explictly enable/disable globbing?

**Comment by cjackal** [comment]
I'm also +1 on switch on globbing in scan_* functions. While it is generally not a good idea to have glob characters in a path in filesystem-like system, AWS even [claims](https://docs.aws.amazon.com/AmazonS3/latest/userguide/object-keys.html) that asterisk is safe as an S3 object key.

**Comment by jeroenjanssens** [comment]
Another solution is to remove all globbing functionality from Polars and instead let the `read_*()` and `scan_*()` functions also accept `list[str | TextIO | BytesIO | Path | BinaryIO | bytes]` as a source. That way, the user can use, e.g., `glob.glob()` to pass a list of files to read. I imagine the necessary code for this to be simpler than having to support all the globbing functionality (especially when having a boolean parameter to enable globbing). 

Of course this is just syntactic sugar over `pl.concat()` with, say, a list comprehension. So if we want to keep Polars even leaner, we could always advise users to use that approach. 

In any case, I would advise to have all `read_*()` and `scan_*()` functions the same behavior as much as possible; not having globbing functionality for only some of them.

**Comment by Mickychen00** [comment]
Same phenomenon for me. Pandas' read_csv() treat "[]" well.

**Comment by Wainberg** [comment]
It's cause `[]` are glob characters. This issue can be closed as a duplicate of https://github.com/pola-rs/polars/issues/12876.
