### ISSUE TITLE
Invalid or out-of-range datetime error when using .dt attribute on polars.DataFrame from duckdb

### ISSUE THREAD

**Issue by jaron-lee** [pola-rs/polars#10107]
### Checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pypi.org/project/polars/) of Polars.

### Reproducible example

```python
import polars as pl
import datetime
import duckdb

df1 = pl.DataFrame({'tsp': [datetime.datetime(2000, 1, 1), None]})
print(df1.with_columns(**{'test': pl.col('tsp').dt.year()}))

duckdb.sql('create table data(tsp date)')
duckdb.sql("insert into data values ('2000-01-01'), (null)")

df2 = duckdb.execute('select * from data').pl()
print(df2.with_columns(**{'test': pl.col('tsp').dt.year()}))
```

### Issue description

As far as I can tell this is a polars issue, but I could be wrong. Please let me know if I should post in the duckdb github instead. 

### Expected behavior

In the first print statement I obtain the result that I expect, in which the 'test' column has values [2000, null].

However the second print statement fails with the following error, for which I have provided the RUST_BACKTRACE='full' output:

```
thread '<unnamed>' panicked at 'invalid or out-of-range datetime', /root/.cargo/git/checkouts/arrow2-945af624853845da/e71d666/src/temporal_conversions.rs:36:10
  stack backtrace:
     0:     0x7f394edf97dc - <unknown>
     1:     0x7f394d417c8f - <unknown>
     2:     0x7f394edca6a4 - <unknown>
     3:     0x7f394edfb20f - <unknown>
     4:     0x7f394edfadb4 - <unknown>
     5:     0x7f394edfbe0e - <unknown>
     6:     0x7f394edfb8d2 - <unknown>
     7:     0x7f394edfb836 - <unknown>
     8:     0x7f394edfb821 - <unknown>
     9:     0x7f394c439022 - <unknown>
    10:     0x7f394c439562 - <unknown>
    11:     0x7f394ec93b0f - <unknown>
    12:     0x7f394ea1d3cf - <unknown>
    13:     0x7f394ea1cd46 - <unknown>
    14:     0x7f394ea1c670 - <unknown>
    15:     0x7f394e5152c4 - <unknown>
    16:     0x7f394e50c757 - <unknown>
    17:     0x7f394e50b794 - <unknown>
    18:     0x7f394e5b1caa - <unknown>
    19:     0x7f394e5b1440 - <unknown>
    20:     0x7f394e5b2bdb - <unknown>
    21:     0x7f394c5e5367 - <unknown>
    22:     0x7f394eca8ada - <unknown>
    23:     0x7f394eca8840 - <unknown>
    24:     0x7f394edfdcb6 - <unknown>
    25:     0x7f3950108ea7 - start_thread
    26:     0x7f394fecfa2f - clone
    27:                0x0 - <unknown>
  shape: (2, 2)
shape: (2, 2)
  ┌─────────────────────┬──────┐
  │ tsp                 ┆ test │
  │ ---                 ┆ ---  │
  │ datetime[μs]        ┆ i32  │
  ╞═════════════════════╪══════╡
  │ 2000-01-01 00:00:00 ┆ 2000 │
  │ null                ┆ null │
  └─────────────────────┴──────┘
  Traceback (most recent call last):
    File "/root/**<redacted path to file>**/test_bug.py", line 12, in <module>
      print(df2.with_columns(**{'test': pl.col('tsp').dt.year()}))
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    File "/opt/conda/lib/python3.11/site-packages/polars/dataframe/frame.py", line 7335, in with_columns
      .collect(no_optimization=True)
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    File "/opt/conda/lib/python3.11/site-packages/polars/lazyframe/frame.py", line 1531, in collect
      return wrap_df(ldf.collect())
                     ^^^^^^^^^^^^^
  pyo3_runtime.PanicException: invalid or out-of-range datetime
```

### Installed versions

<details>

```
  --------Version info---------
  Polars:              0.18.7
  Index type:          UInt32
  Platform:            Linux-5.10.0-23-cloud-amd64-x86_64-with-glibc2.31
  Python:              3.11.3 | packaged by conda-forge | (main, Apr  6 2023, 08:57:19) [GCC 11.3.0]

  ----Optional dependencies----
  adbc_driver_sqlite:  <not installed>
  connectorx:          <not installed>
  deltalake:           <not installed>
  fsspec:              2023.6.0
  matplotlib:          3.7.2
  numpy:               1.25.1
  pandas:              1.5.3
  pyarrow:             12.0.1
  pydantic:            1.10.12
  sqlalchemy:          1.4.49
  xlsx2csv:            <not installed>
  xlsxwriter:          <not installed>
```

</details>

**Comment by ritchie46** [comment]
Can you produce this without duckdb? I am not sure that it is an polars issue if you cannot.

**Comment by cmdlineluser** [comment]
I tried creating the arrow table manually which doesn't replicate the issue:
```python
import datetime
import duckdb
import polars as pl
import pyarrow as pa
import pyarrow.compute as pc

df1 = pl.DataFrame({'tsp': [datetime.datetime(2000, 1, 1), None]})
print(df1.with_columns(**{'test': pl.col('tsp').dt.year()}))

duckdb.sql('create table data(tsp date)')
duckdb.sql("insert into data values ('2000-01-01'), (null)")

tbl = pa.table({"tsp": ["2000-01-01", None]})

from_pyarrow = tbl.set_column(
    tbl.schema.get_field_index("tsp"),
    "tsp",
    pc.strptime(tbl["tsp"], format="%Y-%m-%d", unit="s").cast(pa.date32())
)

from_duckdb = duckdb.execute('select * from data').arrow()
# pyarrow.Table
# tsp: date32[day]
# ----
# tsp: [[2000-01-01,null]]

from_duckdb == from_pyarrow
# True

pl.from_arrow(from_duckdb)
# shape: (2, 1)
# ┌────────────┐
# │ tsp        │
# │ ---        │
# │ date       │
# ╞════════════╡
# │ 2000-01-01 │
# │ null       │
# └────────────┘

pl.from_arrow(from_duckdb).frame_equal(pl.from_arrow(from_pyarrow))
# True

pl.from_arrow(from_pyarrow).select(pl.all().dt.year())
# shape: (2, 1)
# ┌──────┐
# │ tsp  │
# │ ---  │
# │ i32  │
# ╞══════╡
# │ 2000 │
# │ null │
# └──────┘

pl.from_arrow(from_duckdb).select(pl.all().dt.year())
# PanicException: invalid or out-of-range datetime
```

**Comment by jaron-lee** [comment]
I can confirm @cmdlineluser 's findings, was unable to replicate the issue running their script. I will take this over to the duckdb folks. Thanks all!

**Comment by ritchie46** [comment]
No, the issue is here, already have a fix. :)
