### ISSUE TITLE
Lazy API CommSubExpr window function breaking change in 0.18.9

### ISSUE THREAD

**Issue by dsillman2000** [pola-rs/polars#10152]
### Checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pypi.org/project/polars/) of Polars.

### Reproducible example

In the below example, I produce a synthetic CSV dataset of the required format / structure of the polars ops I'm tyring to use (see `generate_example_data`), then run the resulting CSV file through the `compute_metrics` function (which applies the polars ops). Running the code in 0.18.8 produces an output with no problem in eager + lazy APIs (switch out `scan_csv` for `read_csv` to test eager). After updating to 0.18.9, the eager API still works but the lazy API produces a PoisonError in the underlying Rust runtime.

**EDIT**: I've removed a sequence of "with_columns" and groupby-agg operations which didn't affect the error - the last "with_columns" op is responsible for the error. When I comment out any one of the three columns I'm assigning in that clause, the code works. No idea why.

```python
import random
import time
from typing import NamedTuple

import polars as pl

PointState = NamedTuple('PointState', [
    ('pos_x', float), ('pos_y', float), ('pos_z', float), ('bend_x', float), ('bend_y', float)
])

def generate_example_data(out_csv: str, seed: int = 20230729):

    random.seed(seed)

    min_frame_idx: int = 20000
    max_frame_idx: int = 20100
    num_frames: int = max_frame_idx - min_frame_idx + 1

    min_point_idx: int = 400
    max_point_idx: int = 812
    num_points: int = max_point_idx - min_point_idx + 1

    point_states: list[PointState] = [PointState(0., 0., 0. - 1.25 * i, 0., 0.) for i in range(num_points)]

    time_column: list[int] = [int(time.time_ns() // 1000) for _ in range(num_points)]
    frame_column: list[int] = [min_frame_idx for _ in range(num_points)]
    point_column: list[int] = [min_point_idx + i for i in range(num_points)]
    insertion_column: list[float] = [0.] * num_points
    pos_x_column: list[float] = [ps.pos_x for ps in point_states]
    pos_y_column: list[float] = [ps.pos_y for ps in point_states]
    pos_z_column: list[float] = [ps.pos_z for ps in point_states]
    bend_x_column: list[float] = [ps.bend_x for ps in point_states]
    bend_y_column: list[float] = [ps.bend_y for ps in point_states]
    for fi in range(num_frames - 1):

        print(f'{fi:3d} / {num_frames:3d}', end='\r')

        d_time: int = int(random.normalvariate(10000, 10))
        time_column += [time_column[-1] + d_time for _ in range(num_points)]
        frame_column += [min_frame_idx + fi + 1 for _ in range(num_points)]
        point_column += [min_point_idx + i for i in range(num_points)]

        d_insertion: float = random.normalvariate(0.1, 0.1)
        insertion_column += [insertion_column[-1] + d_insertion] * num_points

        d_pos_xs: list[float] = [random.normalvariate(0.0, 0.1) for _ in range(num_points)]
        d_pos_ys: list[float] = [random.normalvariate(0.0, 0.05) for _ in range(num_points)]
        d_pos_zs: list[float] = [random.normalvariate(0.0, 0.075) for _ in range(num_points)]
        d_bend_xs: list[float] = [random.normalvariate(0.0, 0.005) for _ in range(num_points)]
        d_bend_ys: list[float] = [random.normalvariate(0.0, 0.005) for _ in range(num_points)]
        
        point_states = [
            PointState(
                point_states[i].pos_x + d_pos_xs[i],
                point_states[i].pos_y + d_pos_ys[i],
                point_states[i].pos_z + d_pos_zs[i],
                point_states[i].bend_x + d_bend_xs[i],
                point_states[i].bend_y + d_bend_ys[i]
            )
            for i in range(num_points)
        ]

        pos_x_column += [ps.pos_x for ps in point_states]
        pos_y_column += [ps.pos_y for ps in point_states]
        pos_z_column += [ps.pos_z for ps in point_states]
        bend_x_column += [ps.bend_x for ps in point_states]
        bend_y_column += [ps.bend_y for ps in point_states]

    print()
    df = pl.LazyFrame(
        dict(
            timestamp = pl.Series(time_column),
            frame_idx = pl.Series(frame_column),
            point_idx = pl.Series(point_column),
            pos_x = pl.Series(pos_x_column),
            pos_y = pl.Series(pos_y_column),
            pos_z = pl.Series(pos_z_column),
            bend_x = pl.Series(bend_x_column),
            bend_y = pl.Series(bend_y_column),
            insertion = pl.Series(insertion_column),
        )
    )

    df.collect().write_csv(out_csv)

def compute_metrics(dataset_path: str) -> pl.DataFrame:

    if dataset_path.endswith('.csv'):
        df = pl.scan_csv(dataset_path)
    else:
        df = pl.scan_parquet(dataset_path) 

    df = df.set_sorted('timestamp', 'frame_idx')

    df = df \
        .with_columns(
            # Compute delta-time between frames
            delta_seconds = pl.col('timestamp').diff().over('point_idx') / 1e6,
        ) \
        .with_columns(
            # Compute insertion velocity (mm/s)
            insertion_vel = pl.col('insertion').diff().over('point_idx') / pl.col('delta_seconds')
        ) \
        .with_columns(
            # Compute velocity vector components for each point (mm/s)
            vel_x = pl.col('pos_x').diff().over('point_idx') / pl.col('delta_seconds'),
            vel_y = pl.col('pos_y').diff().over('point_idx') / pl.col('delta_seconds'),
            # Apply insertion-velocity correction to Z velocity component
            vel_z = pl.col('pos_z').diff().over('point_idx') / pl.col('delta_seconds') - pl.col('insertion_vel'),
        )
    
    return df.lazy().collect()

if __name__ == '__main__':

    generate_example_data('ex.csv')
    df = compute_metrics('ex.csv').fill_nan(None).drop_nulls()

    print(df)
```

### Issue description

Running the above code is successful and correct (unit-tested) using Polars 0.18.8 using both the lazy and eager API. After upgrading to Polars 0.18.9, the code still works using the eager API, but produces a cryptic error with the lazy API:

```
thread '<unnamed>' panicked at 'assertion failed: !gt.is_empty()', /Users/runner/work/polars/polars/polars/polars-lazy/src/physical_plan/expressions/window.rs:463:21
stack backtrace:
   0:        0x121f983e0 - _ffi_select_with_compiled_path
   1:        0x120b9c20c - _BrotliDecoderVersion
   2:        0x121f747c4 - _ffi_select_with_compiled_path
   3:        0x121f9bfb4 - _ffi_select_with_compiled_path
   4:        0x121f9b5f8 - _ffi_select_with_compiled_path
   5:        0x121f9c5dc - _ffi_select_with_compiled_path
   6:        0x121f9c11c - _ffi_select_with_compiled_path
   7:        0x121f9c0b0 - _ffi_select_with_compiled_path
   8:        0x121f9c0a4 - _ffi_select_with_compiled_path
   9:        0x1220b6470 - _ffi_select_with_compiled_path
  10:        0x1220b6598 - _ffi_select_with_compiled_path
  11:        0x121807ba8 - _ffi_select_with_compiled_path
  12:        0x12188b320 - _ffi_select_with_compiled_path
  13:        0x121883f00 - _ffi_select_with_compiled_path
  14:        0x12188e2b8 - _ffi_select_with_compiled_path
  15:        0x1218f73e0 - _ffi_select_with_compiled_path
  16:        0x1218f77e8 - _ffi_select_with_compiled_path
  17:        0x1218f754c - _ffi_select_with_compiled_path
  18:        0x1218f7c30 - _ffi_select_with_compiled_path
  19:        0x122230208 - _ffi_select_with_compiled_path
  20:        0x121e627ec - _ffi_select_with_compiled_path
  21:        0x121e62384 - _ffi_select_with_compiled_path
  22:        0x121f9df48 - _ffi_select_with_compiled_path
  23:        0x1a1d7ffa8 - __pthread_joiner_wake
thread '<unnamed>' panicked at 'called `Result::unwrap()` on an `Err` value: PoisonError { .. }', /Users/runner/work/polars/polars/polars/polars-lazy/src/physical_plan/expressions/window.rs:657:52
stack backtrace:
   0:        0x121f983e0 - _ffi_select_with_compiled_path
   1:        0x120b9c20c - _BrotliDecoderVersion
   2:        0x121f747c4 - _ffi_select_with_compiled_path
   3:        0x121f9bfb4 - _ffi_select_with_compiled_path
   4:        0x121f9b5f8 - _ffi_select_with_compiled_path
   5:        0x121f9c5dc - _ffi_select_with_compiled_path
   6:        0x121f9c13c - _ffi_select_with_compiled_path
   7:        0x121f9c0b0 - _ffi_select_with_compiled_path
   8:        0x121f9c0a4 - _ffi_select_with_compiled_path
   9:        0x1220b6470 - _ffi_select_with_compiled_path
  10:        0x1220b677c - _ffi_select_with_compiled_path
  11:        0x121818324 - _ffi_select_with_compiled_path
  12:        0x121819ab0 - _ffi_select_with_compiled_path
  13:        0x1218077ac - _ffi_select_with_compiled_path
  14:        0x12188b320 - _ffi_select_with_compiled_path
  15:        0x121883f00 - _ffi_select_with_compiled_path
  16:        0x12188b320 - _ffi_select_with_compiled_path
  17:        0x121883f00 - _ffi_select_with_compiled_path
  18:        0x12188e2b8 - _ffi_select_with_compiled_path
  19:        0x1218f73e0 - _ffi_select_with_compiled_path
  20:        0x1218f7c30 - _ffi_select_with_compiled_path
  21:        0x122230208 - _ffi_select_with_compiled_path
  22:        0x121e627ec - _ffi_select_with_compiled_path
  23:        0x121e62384 - _ffi_select_with_compiled_path
  24:        0x121f9df48 - _ffi_select_with_compiled_path
  25:        0x1a1d7ffa8 - __pthread_joiner_wake
```

The test case, in this instance, is a CSV file, and I see no apparent problems with the contents of the file. My only guess is that this must be produced in the execution of the query plan of a window function expression, judging from this source line citation:

```
/Users/runner/work/polars/polars/polars/polars-lazy/src/physical_plan/expressions/window.rs:463:21
```

### Expected behavior

The code runs and my unit tests pass. Example inputs are provided from a CSV dataset, and the expected values of the final metrics in the `select` clause are hand-calculated for a handful of instances and validated.

Note that the 0.18.9 eager API still passes the tests, so the logic in the eager API is still functional. However, the same query plan was supported for the 0.18.8 lazy API but now appears not to be.

### Installed versions

<details>

```
--------Version info---------
Polars:              0.18.9
Index type:          UInt32
Platform:            macOS-13.4.1-arm64-arm-64bit
Python:              3.11.2 (main, May  4 2023, 15:20:52) [Clang 14.0.3 (clang-1403.0.22.14.1)]

----Optional dependencies----
adbc_driver_sqlite:  <not installed>
cloudpickle:         <not installed>
connectorx:          <not installed>
deltalake:           <not installed>
fsspec:              <not installed>
matplotlib:          <not installed>
numpy:               1.25.1
pandas:              2.0.3
pyarrow:             12.0.1
pydantic:            <not installed>
sqlalchemy:          <not installed>
xlsx2csv:            <not installed>
xlsxwriter:          <not installed>
```

</details>

**Comment by stinodego** [comment]
I cannot reproduce this without the dataset, but @ritchie46 might know what's going on by looking at that error message.

**Comment by ritchie46** [comment]
Can you try making a minimal example? Recreate the problem with minimal data and remove all code tgat doesn't influence the bug.

**Comment by dsillman2000** [comment]
@ritchie46 apologies for not initially including the test dataset, as it's a 3 MB CSV file. I've updated the "reproducible example" section above to include a section which generates a synthetic dataset of comparable size. Try running the code in both versions of Polars, let me know if you run into the same PoisonError! (I do, at least when running _first_ using 0.18.8, then updating, then trying _again_ with 0.18.9).

**Comment by dsillman2000** [comment]
Update: `collect`ing with `comm_subexpr_elim = False` succeeds. Was a breaking change introduced regarding the `comm_subexpr_elim` optimization?

**Comment by avimallu** [comment]
CSE makes sure that computation of identical parts of "subexpressions" are done only once. This wasn't meant to be a breaking change, but it does look like it is a culprit here.

**Comment by ritchie46** [comment]
A more minimal example:

```python
q = pl.LazyFrame({
 'a': [0.0],
 'b': [0.0],
})

q = (q 
     .with_columns(
        a = pl.col('a').diff().over('a') / pl.col('a'),
        b = pl.col('b').diff().over('a') / pl.col('a'),
        c = pl.col('a').diff().over('a') 
    )
)


q.collect()
```
