### ISSUE TITLE
Support debugger breakpoints in pl.map and pl.apply functions

### ISSUE THREAD

**Issue by daddywantssugar** [pola-rs/polars#10151]
### Problem description

tested with polars 0.18.4, using pycharm 2023 and VSCode. debugger doesn't stop at the breakpoint presumably because it's wrapped inside a rust call?

```
import polars as pl

def myfunc(x):
    return pl.Series([1, 2, 3]) # !!! I would like breakpoints to work within this function !!!

df = pl.DataFrame({'a': [1, 2, 3]})
res = df.with_columns(
    pl.map(['a'], myfunc)
)
```

**Comment by mcrumiller** [comment]
We have an open PR that enabled debugging in both Rust and Python. You should be able to break at that line and at least jump inside the pl.Series constrictor. Are you saying you can't even do that?

**Comment by daddywantssugar** [comment]
hoping you meant "constructor" in which case that's right I can't even get a breakpoint on that line which I commented in the example code above. I don't have a need to debug in rust, only need to debug the user defined python functions passed into pl.map and pl.apply.

**Comment by mcrumiller** [comment]
Hi @daddywantssugar--yes, the issue is that `myfunc` gets sent to pyo3 and is churned through the rust machinery, which prevents the debugger from stopping there. However, all is not lost. Let me know if this solution is enough to close this issue:

```python
def myfunc(x):
    breakpoint()
    return pl.Series([1, 2, 3])
```

**Comment by daddywantssugar** [comment]
it helps thanks, however I have to run it in PyCharm without the debugger, which means I don't get the convenience of the variable explorer and other UI navigation.

If I try to run it with the debugger I get this error:

```

thread '<unnamed>' panicked at 'python apply failed: '_DummyThread' object has no attribute 'additional_info'', src\apply\lazy.rs:160:19
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
Traceback (most recent call last):
  File "C:\Program Files\JetBrains\PyCharm Community Edition 2023.1\plugins\python-ce\helpers\pydev\pydevd.py", line 1496, in _exec
    pydev_imports.execfile(file, globals, locals)  # execute the script
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Program Files\JetBrains\PyCharm Community Edition 2023.1\plugins\python-ce\helpers\pydev\_pydev_imps\_pydev_execfile.py", line 18, in execfile
    exec(compile(contents+"\n", file, 'exec'), glob, loc)
  File "C:\Users\user\PycharmProjects\parquet_perf\debugger.py", line 8, in <module>
    res = df.with_columns(
          ^^^^^^^^^^^^^^^^
  File "C:\Users\user\anaconda3\envs\py311\Lib\site-packages\polars\dataframe\frame.py", line 7453, in with_columns
    .collect(no_optimization=True)
     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\anaconda3\envs\py311\Lib\site-packages\polars\lazyframe\frame.py", line 1530, in collect
    return wrap_df(ldf.collect())
                   ^^^^^^^^^^^^^
pyo3_runtime.PanicException: python apply failed: '_DummyThread' object has no attribute 'additional_info'
```

```

thread '<unnamed>' panicked at 'python apply failed: '_DummyThread' object has no attribute 'additional_info'', src\apply\lazy.rs:160:19
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
Traceback (most recent call last):
  File "C:\Program Files\JetBrains\PyCharm Community Edition 2023.1\plugins\python-ce\helpers\pydev\pydevd.py", line 1496, in _exec
    pydev_imports.execfile(file, globals, locals)  # execute the script
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Program Files\JetBrains\PyCharm Community Edition 2023.1\plugins\python-ce\helpers\pydev\_pydev_imps\_pydev_execfile.py", line 18, in execfile
    exec(compile(contents+"\n", file, 'exec'), glob, loc)
  File "C:\Users\user\PycharmProjects\parquet_perf\debugger.py", line 8, in <module>
    res = df.with_columns(
          ^^^^^^^^^^^^^^^^
  File "C:\Users\user\anaconda3\envs\py311\Lib\site-packages\polars\dataframe\frame.py", line 7453, in with_columns
    .collect(no_optimization=True)
     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\anaconda3\envs\py311\Lib\site-packages\polars\lazyframe\frame.py", line 1530, in collect
    return wrap_df(ldf.collect())
                   ^^^^^^^^^^^^^
pyo3_runtime.PanicException: python apply failed: '_DummyThread' object has no attribute 'additional_info'
```
