### ISSUE TITLE
polars.Expr.str.to_datetime() rejects certain format strings

### ISSUE THREAD

**Issue by jsarbach** [pola-rs/polars#10178]
### Checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pypi.org/project/polars/) of Polars.

### Reproducible example

```python
df = pl.LazyFrame({'datetime': ['2023-07-30 06', '2023-07-30 13']})

df.collect()
shape: (2, 1)
┌───────────────┐
│ datetime      │
│ ---           │
│ str           │
╞═══════════════╡
│ 2023-07-30 06 │
│ 2023-07-30 13 │
└───────────────┘

df.with_columns(pl.col('datetime').str.to_datetime(format='%Y-%m-%d %H')).collect()
Traceback (most recent call last):
  File "/home/juri/PyCharm/pycharm-community/plugins/python-ce/helpers/pydev/pydevconsole.py", line 364, in runcode
    coro = func()
  File "<input>", line 1, in <module>
  File "/home/juri/.miniconda3/envs/dataprep/lib/python3.10/site-packages/polars/utils/decorators.py", line 37, in wrapper
    return function(*args, **kwargs)
  File "/home/juri/.miniconda3/envs/dataprep/lib/python3.10/site-packages/polars/lazyframe/frame.py", line 1552, in collect
    return wrap_df(ldf.collect())
exceptions.ComputeError: Invalid format string: Please either specify both hour and minute, or neither.
```

Same for
```python
df.with_columns(pl.col('datetime').str.strptime(pl.Datetime, format='%Y-%m-%d %H')).collect()
Traceback (most recent call last):
  File "/home/juri/PyCharm/pycharm-community/plugins/python-ce/helpers/pydev/pydevconsole.py", line 364, in runcode
    coro = func()
  File "<input>", line 1, in <module>
  File "/home/juri/.miniconda3/envs/dataprep/lib/python3.10/site-packages/polars/utils/decorators.py", line 37, in wrapper
    return function(*args, **kwargs)
  File "/home/juri/.miniconda3/envs/dataprep/lib/python3.10/site-packages/polars/lazyframe/frame.py", line 1552, in collect
    return wrap_df(ldf.collect())
exceptions.ComputeError: Invalid format string: Please either specify both hour and minute, or neither.
```

### Issue description

I don't see any invalid format here and I don't understand the constraint `specify both hour and minute, or neither`. `%Y-%m-%d %H` is a perfectly valid format for parsing IMO:
```python
datetime.strptime('2023-07-30 06', '%Y-%m-%d %H')
datetime.datetime(2023, 7, 30, 6, 0)
```

### Expected behavior

I'd expect this to return
```
shape: (2, 1)
┌─────────────────────┐
│ datetime            │
│ ---                 │
│ datetime[μs]        │
╞═════════════════════╡
│ 2023-07-30 06:00:00 │
│ 2023-07-30 13:00:00 │
└─────────────────────┘
```

### Installed versions

<details>

```
--------Version info---------
Polars:              0.18.9
Index type:          UInt32
Platform:            Linux-6.2.0-26-generic-x86_64-with-glibc2.37
Python:              3.10.6 (main, Oct  7 2022, 20:19:58) [GCC 11.2.0]
----Optional dependencies----
adbc_driver_sqlite:  <not installed>
cloudpickle:         2.2.0
connectorx:          <not installed>
deltalake:           <not installed>
fsspec:              2022.8.2
matplotlib:          <not installed>
numpy:               1.23.4
pandas:              2.0.3
pyarrow:             9.0.0
pydantic:            1.10.2
sqlalchemy:          <not installed>
xlsx2csv:            <not installed>
xlsxwriter:          <not installed>
```

</details>

**Comment by MarcoGorelli** [comment]
thanks @jsarbach for the report

this comes from [chrono ](https://docs.rs/chrono/latest/chrono/) I'm afraid:
```rust
use chrono::NaiveDateTime;

fn main() {
    println!("parsed: {:?}", NaiveDateTime::parse_from_str("2023-07-30 06", "%Y-%m-%d %H"))
}
```

```
parsed: Err(ParseError(NotEnough))
```

I'd suggest you append `:00` and add `:%M` to your format string

**Comment by jsarbach** [comment]
Thanks @MarcoGorelli for the quick reply. I think I'll go for `pl.col(k).apply(lambda s: datetime.strptime(s, fmt)).cast(pl.Datetime)` then b/c both date string and format string are defined by the user in my case and can be basically anything.

Kudos for the great work btw! Polars is amazing :heart:

**Comment by MarcoGorelli** [comment]
`apply` would be significantly slower, and is only really intended as a last-resort

if you really need to support `%Y-%m-%d %H` and can depend on pyarrow, you may want to do
```python
In [27]: arr = pa.array(['2023-07-30 06', '2023-07-30 13'])

In [28]: pl.from_arrow(pc.strptime(arr, format='%Y-%m-%d %H', unit='us'))
Out[28]:
shape: (2,)
Series: '' [datetime[μs]]
[
        2023-07-30 06:00:00
        2023-07-30 13:00:00
]
```
instead

> Kudos for the great work btw! Polars is amazing ❤️

I've only contributed to a tiny part, but still, thanks for your kind words!
