### ISSUE TITLE
scan + collect on empty dataframe results in `called Option::unwrap() on a None value`

### ISSUE THREAD

**Issue by svaningelgem** [pola-rs/polars#10208]
### Checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pypi.org/project/polars/) of Polars.

### Reproducible example

```python
from pathlib import Path
from tempfile import TemporaryDirectory

import polars as pl

with TemporaryDirectory() as tmp_dir:
    tmp_path = Path(tmp_dir)
    parquet_file = tmp_path / "out.parquet"

    schema = {
        "KLN_NR": pl.Utf8,
    }

    df = pl.DataFrame(
        {
            "KLN_NR": [],
        },
        schema=schema,
    )
    df.write_parquet(parquet_file)
    lazy_df = pl.scan_parquet(parquet_file)

    pl.concat([lazy_df]).collect(streaming=True)
```

### Issue description

The code creates an empty dataframe (in this case with 1 column).

What I would expect is an empty dataframe with a certain schema.

### Expected behavior

I'm expecting an empty dataframe with a certain schema applied on it.

### Installed versions

<details>

```
--------Version info---------
Polars:              0.18.9
Index type:          UInt32
Platform:            Windows-10-10.0.19044-SP0
Python:              3.11.3 | packaged by Anaconda, Inc. | (main, May 15 2023, 15:41:31) [MSC v.1916 64 bit (AMD64)]

----Optional dependencies----
adbc_driver_sqlite:  <not installed>
cloudpickle:         <not installed>
connectorx:          <not installed>
deltalake:           <not installed>
fsspec:              2023.4.0
matplotlib:          <not installed>
numpy:               1.25.0
pandas:              1.5.3
pyarrow:             11.0.0
pydantic:            1.10.8
sqlalchemy:          <not installed>
xlsx2csv:            <not installed>
xlsxwriter:          <not installed>
```

</details>

**Comment by cjackal** [comment]
It works with `use_pyarrow=True`, must have something to do with arrow2 parquet writer.

**Comment by svaningelgem** [comment]
re-verified with `0.18.11`.

I tried now to write the dataframe via spark, just in case there was something wrong with the writer:

```python
from pathlib import Path
from tempfile import TemporaryDirectory

import polars as pl
from pyspark.sql import SparkSession



with TemporaryDirectory() as tmp_dir:
    tmp_path = Path(tmp_dir)
    parquet_file = tmp_path / "out.parquet"

    spark = SparkSession.builder.appName("Local Session").master("local[*]").getOrCreate()
    df = spark.createDataFrame([], schema="KLN_NR: string")
    print("After creation:")
    df.show()
    df.write.parquet(str(parquet_file))
    print("After re-reading the file:")
    spark.read.parquet(str(parquet_file)).show()
    spark.stop()


    lazy_df = pl.scan_parquet(f'{parquet_file}/*.parquet')

    pl.concat([lazy_df]).collect(streaming=True)
```

But it gives still the `PanicException`:
```text
thread '<unnamed>' panicked at 'called `Option::unwrap()` on a `None` value', /home/runner/work/polars/polars/crates/polars-core/src/utils/mod.rs:557:34
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
Traceback (most recent call last):
  File "/home/jovyan/code/test.py", line 42, in <module>
    pl.concat([lazy_df]).collect(streaming=True)
  File "../python3.11/site-packages/polars/utils/deprecation.py", line 93, in wrapper
    return function(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "../python3.11/site-packages/polars/lazyframe/frame.py", line 1561, in collect
    return wrap_df(ldf.collect())
                   ^^^^^^^^^^^^^
pyo3_runtime.PanicException: called `Option::unwrap()` on a `None` value
```

**Comment by cmdlineluser** [comment]
It seems to be specific to `streaming=True`
```python
pl.read_parquet("out.parquet")

# shape: (0, 1)
# ┌────────┐
# │ KLN_NR │
# │ ---    │
# │ str    │
# ╞════════╡
# └────────┘

pl.scan_parquet("out.parquet").collect()

# shape: (0, 1)
# ┌────────┐
# │ KLN_NR │
# │ ---    │
# │ str    │
# ╞════════╡
# └────────┘
```
