### ISSUE TITLE
Internal error when sorting LazyFrame by datetime and something else, then sinking into Parquet file.

### ISSUE THREAD

**Issue by Simon-Will** [pola-rs/polars#10245]
### Checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pypi.org/project/polars/) of Polars.

### Reproducible example

```python
from datetime import datetime

import polars as pl

data = {
    "foo": [3, 2, 1],
    "bar": ["a", "b", "c"],
    "baz": [
        datetime(2023, 5, 1, 15, 45),
        datetime(2023, 5, 1, 13, 45),
        datetime(2023, 5, 1, 14, 45),
    ],
}
df = pl.DataFrame(data)

# These three work.
df.lazy().sort("foo", "bar").sink_parquet("foo_bar.parquet")
df.lazy().sort("baz").sink_parquet("baz.parquet")
print(df.lazy().sort("foo", "baz").collect())

# This one fails.
df.lazy().sort("foo", "baz").sink_parquet("foo_baz.parquet")
```

Traceback:

```
thread '<unnamed>' panicked at 'internal error: entered unreachable code', /home/runner/work/polars/polars/crates/polars-row/src/decode.rs:67:13
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
Traceback (most recent call last):
  File "/dir/panic.py", line 24, in <module>
    df.lazy().sort("foo", "baz").sink_parquet("foo_baz.parquet")
  File "/usr/local/lib/python3.11/site-packages/polars/lazyframe/frame.py", line 1654, in sink_parquet
    return lf.sink_parquet(
           ^^^^^^^^^^^^^^^^
pyo3_runtime.PanicException: internal error: entered unreachable code
```

### Issue description

I tried this with Python 3.9 and 3.11.

### Expected behavior

I expected the sorting to work like usual. I understand that the streaming API is still under development and hope this report is helpful.

### Installed versions

<details>

```
--------Version info---------
Polars:              0.18.11
Index type:          UInt32
Platform:            Linux-5.15.90.1-microsoft-standard-WSL2-x86_64-with-glibc2.36
Python:              3.11.4 (main, Jul  4 2023, 05:35:05) [GCC 12.2.0]

----Optional dependencies----
adbc_driver_sqlite:  <not installed>
cloudpickle:         <not installed>
connectorx:          <not installed>
deltalake:           <not installed>
fsspec:              <not installed>
matplotlib:          <not installed>
numpy:               <not installed>
pandas:              <not installed>
pyarrow:             <not installed>
pydantic:            <not installed>
sqlalchemy:          <not installed>
xlsx2csv:            <not installed>
xlsxwriter:          <not installed>
```

</details>

**Comment by Simon-Will** [comment]
Great, thanks!
