### ISSUE TITLE
 scan_ipc -> sink_ipc does not work and give incorrect error

### ISSUE THREAD

**Issue by sorhawell** [pola-rs/polars#10406]
### Checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pypi.org/project/polars/) of Polars.

### Reproducible example

```python
import polars as pl
pl.DataFrame({"a":[1,2,3]}).lazy().sink_ipc("deleteme")
pl.scan_ipc("deleteme").sink_ipc("deletealsome")

thread '<unnamed>' panicked at 'sink_parquet not yet supported in standard engine. Use 'collect().write_parquet()'', /Users/runner/work/polars/polars/crates/polars-lazy/src/physical_plan/planner/lp.rs:153:28
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/sorenwelling/Documents/projs/r-polars/.venv/lib/python3.9/site-packages/polars/lazyframe/frame.py", line 1858, in sink_ipc
    return lf.sink_ipc(
pyo3_runtime.PanicException: sink_parquet not yet supported in standard engine. Use 'collect().write_parquet()'
```

### Issue description

using sink_ipc from a LazyFrom created from pl.scan_ipc gives an error that sink_parquet not yet supported in standard engine.

However sink_parquet does work like 
import polars as pl
pl.DataFrame({"a":[1,2,3]}).lazy().sink_parquet("deleteme")
pl.scan_parquet("deleteme").sink_parquet("deletealsome")

### Expected behavior

sink_ipc writes to file or gives error message that sink_ipc is not fully supported yet, not sink_parquet which works fine.

### Installed versions

<details>

```
>>> pl.show_versions()
--------Version info---------
Polars:              0.18.13
Index type:          UInt32
Platform:            macOS-12.6.6-x86_64-i386-64bit
Python:              3.9.17 (main, Jun 20 2023, 17:04:52) 
[Clang 14.0.0 (clang-1400.0.29.202)]

----Optional dependencies----
adbc_driver_sqlite:  <not installed>
cloudpickle:         <not installed>
connectorx:          <not installed>
deltalake:           <not installed>
fsspec:              <not installed>
matplotlib:          <not installed>
numpy:               <not installed>
pandas:              <not installed>
pyarrow:             <not installed>
pydantic:            <not installed>
sqlalchemy:          <not installed>
xlsx2csv:            <not installed>
xlsxwriter:          <not installed>
```

</details>

**Comment by ritchie46** [comment]
We don't support scan_ipc as streaming source yet.

**Comment by sorhawell** [comment]
Many thx :) I will close this one

**Comment by LeitnerMi** [comment]
Is this feature/enhancement already planned?
