### ISSUE TITLE
Lazy evaluation errors out with multiple window expressions

### ISSUE THREAD

**Issue by paladin158** [pola-rs/polars#10417]
### Checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pypi.org/project/polars/) of Polars.

### Reproducible example

```python
import polars as pl

df = pl.DataFrame({"a": [1], "b": [1.2], "c": [2.1]})

df.lazy().with_columns(
    [
        pl.col("b") - pl.col("b").mean().over("a"),
        pl.col("c") - pl.col("c").mean().over("a"),
    ]
).collect()
```

### Issue description

Get the following error:
```
pyo3_runtime.PanicException: called `Option::unwrap()` on a `None` value
```

### Expected behavior

No error with the following result:
```
a    b      c
---  ---   ---
i64  f64  f64
---  ---   ---
1     0.0  0.0
```

### Installed versions

<details>

```
0.18.13
```

</details>

**Comment by reswqa** [comment]
I test both rust and python while rust version is working fine but python version does not.

rust:
```rust
let df = df!("a" => [1i64], "b" => [1.2], "c" => [2.1])?;
        let result = df.lazy().with_columns([
            col("b") - col("b").mean().over([col("a")]),
            col("c") - col("c").mean().over([col("a")]),
        ]).collect()?;


┌─────┬─────┬─────┐
│ a   ┆ b   ┆ c   │
│ --- ┆ --- ┆ --- │
│ i64 ┆ f64 ┆ f64 │
╞═════╪═════╪═════╡
│ 1   ┆ 0.0 ┆ 0.0 │
└─────┴─────┴─────┘

```

pyton:
```python
df = pl.DataFrame({"a": [1], "b": [1.2], "c": [2.1]})

    r = df.lazy().with_columns(
            [pl.col("c") - pl.col("c").mean().over("a"),
            pl.col("b") - pl.col("b").mean().over("a"),
             ]
    ).collect()
```
```
FAILED                                             [100%]thread '<unnamed>' panicked at 'called `Option::unwrap()` on a `None` value', /Users/guoweijie/Coding/rust/polars/crates/polars-plan/src/utils.rs:426:38
stack backtrace:
   0: rust_begin_unwind
             at /rustc/0d95f9132909ae7c5f2456748d0ffd1c3ba4a8e8/library/std/src/panicking.rs:617:5
   1: core::panicking::panic_fmt
             at /rustc/0d95f9132909ae7c5f2456748d0ffd1c3ba4a8e8/library/core/src/panicking.rs:67:14
   2: core::panicking::panic
             at /rustc/0d95f9132909ae7c5f2456748d0ffd1c3ba4a8e8/library/core/src/panicking.rs:117:5
   3: core::option::Option<T>::unwrap
             at /rustc/0d95f9132909ae7c5f2456748d0ffd1c3ba4a8e8/library/core/src/option.rs:935:21
   4: polars_plan::utils::rename_cse_tmp_series
             at /Users/guoweijie/Coding/rust/polars/crates/polars-plan/src/utils.rs:426:22
   5: polars_lazy::physical_plan::executors::projection_utils::evaluate_physical_expressions
             at /Users/guoweijie/Coding/rust/polars/crates/polars-lazy/src/physical_plan/executors/projection_utils.rs:175:13
   6: polars_lazy::physical_plan::executors::stack::StackExec::execute_impl
             at /Users/guoweijie/Coding/rust/polars/crates/polars-lazy/src/physical_plan/executors/stack.rs:18:19
   7: <polars_lazy::physical_plan::executors::stack::StackExec as polars_lazy::physical_plan::executors::executor::Executor>::execute
             at /Users/guoweijie/Coding/rust/polars/crates/polars-lazy/src/physical_plan/executors/stack.rs:71:13
   8: polars_lazy::frame::LazyFrame::collect
             at /Users/guoweijie/Coding/rust/polars/crates/polars-lazy/src/frame/mod.rs:588:19
   9: polars::lazyframe::PyLazyFrame::collect::{{closure}}

```

**Comment by ritchie46** [comment]
fixed in main.
