### ISSUE TITLE
polars.testing.assert_series_equal() may throw OverflowError if used with UInt

### ISSUE THREAD

**Issue by momijiame** [pola-rs/polars#10436]
### Checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pypi.org/project/polars/) of Polars.

### Reproducible example

```python
>>> import polars as pl
>>> left = pl.Series(
...     values=[2810428175213635359],
...     dtype=pl.UInt64,
... )
>>> right = pl.Series(
...     values=[15807433754238349345],
...     dtype=pl.UInt64,
... )
>>> 
>>> from polars.testing import assert_series_equal
>>> assert_series_equal(left, right)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/amedama/.virtualenvs/py310/lib/python3.10/site-packages/polars/testing/asserts.py", line 260, in assert_series_equal
    _assert_series_inner(
  File "/Users/amedama/.virtualenvs/py310/lib/python3.10/site-packages/polars/testing/asserts.py", line 410, in _assert_series_inner
    s_diff = Series("diff", [abs(v1 - v2) for v1, v2 in zip(left, right)])
  File "/Users/amedama/.virtualenvs/py310/lib/python3.10/site-packages/polars/series/series.py", line 278, in __init__
    self._s = sequence_to_pyseries(
  File "/Users/amedama/.virtualenvs/py310/lib/python3.10/site-packages/polars/utils/_construction.py", line 517, in sequence_to_pyseries
    return _construct_series_with_fallbacks(
  File "/Users/amedama/.virtualenvs/py310/lib/python3.10/site-packages/polars/utils/_construction.py", line 312, in _construct_series_with_fallbacks
    return constructor(name, values, strict)
OverflowError: Python int too large to convert to C long
```

### Issue description

``polars.testing.assert_series_equal()`` throws OverflowError when called with a large number of unsigned integer.
I examined the source code and realized that the following line was causing the issue.

https://github.com/pola-rs/polars/blob/py-0.17.5/py-polars/polars/testing/asserts.py#L350

The essential operations giving rise to the issue are:

```python
>>> pl.Series([abs(2810428175213635359 - 15807433754238349345)])
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/ubuntu/.local/lib/python3.10/site-packages/polars/series/series.py", line 258, in __init__
    self._s = sequence_to_pyseries(
  File "/home/ubuntu/.local/lib/python3.10/site-packages/polars/utils/_construction.py", line 472, in sequence_to_pyseries
    return _construct_series_with_fallbacks(constructor, name, values, strict)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/polars/utils/_construction.py", line 296, in _construct_series_with_fallbacks
    return constructor(name, values, strict)
OverflowError: Python int too large to convert to C long
```

FYI: If UInt64 is specified as the data type, no exception seems to be raised.

```python
>>> pl.Series([abs(2810428175213635359 - 15807433754238349345)], dtype=pl.UInt64)
shape: (1,)
Series: '' [u64]
[
	12997005579024713986
]
```

### Appendix

I noticed this issue in the following snippet.
Note that the hashes generated vary from platform to platform.
Therefore, this snippet does not necessarily raise an exception.

```python
import polars as pl
df1 = pl.DataFrame(
    {
        "fruits": ["banana"],
    }
)
df2 = pl.DataFrame(
    {
        "fruits": ["cherry"],
    }
)
from polars.testing import assert_series_equal
assert_series_equal(
    df1.hash_rows(seed=42),
    df2.hash_rows(seed=42),
)
```

### Expected behavior

It is desirable to return the function without throwing the exception (= behavior of versions prior to v0.17.4).

### Installed versions

The version affected by the issue is 0.17.5 or later.
This is due to the fact that the function implementation was modified in that version.

**Comment by alexander-beedie** [comment]
Thanks! Good find :)
