### ISSUE TITLE
pl.read_csv() fails on gzipped files with a question mark in the filename

### ISSUE THREAD

**Issue by Wainberg** [pola-rs/polars#10580]
### Checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pypi.org/project/polars/) of Polars.

### Reproducible example

```python
import polars as pl
from subprocess import run

run('wget "http://ec.europa.eu/eurostat/estat-navtree-portlet-prod/BulkDownloadListing?sort=1&file=data%2Fdemo_gind.tsv.gz"', shell=True)
pl.read_csv('BulkDownloadListing?sort=1&file=data%2Fdemo_gind.tsv.gz', separator='\t')  # error: cannot scan compressed csv; use `read_csv` for compressed data
```

### Issue description

`pl.read_csv()` gives the error:

```python
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/w/wainberg/wainberg/mambaforge/lib/python3.11/site-packages/polars/io/csv/functions.py", line 364, in read_csv
    df = pl.DataFrame._read_csv(
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/w/wainberg/wainberg/mambaforge/lib/python3.11/site-packages/polars/dataframe/frame.py", line 730, in _read_csv
    scan = scan_csv(
           ^^^^^^^^^
  File "/home/w/wainberg/wainberg/mambaforge/lib/python3.11/site-packages/polars/io/csv/functions.py", line 890, in scan_csv
    return pl.LazyFrame._scan_csv(
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/w/wainberg/wainberg/mambaforge/lib/python3.11/site-packages/polars/lazyframe/frame.py", line 387, in _scan_csv
    self._ldf = PyLazyFrame.new_from_csv(
                ^^^^^^^^^^^^^^^^^^^^^^^^^
exceptions.ComputeError: error while reading BulkDownloadListing?sort=1&file=data%2Fdemo_gind.tsv.gz: cannot scan compressed csv; use `read_csv` for compressed data
```

### Expected behavior

Renaming the file to remove the question mark fixes the problem:

```python
run('mv "BulkDownloadListing?sort=1&file=data%2Fdemo_gind.tsv.gz" "BulkDownloadListingsort=1&file=data%2Fdemo_gind.tsv.gz"', shell=True)
pl.read_csv('BulkDownloadListingsort=1&file=data%2Fdemo_gind.tsv.gz', separator='\t')
```

As does ungzipping the file first.

### Installed versions

<details>

```
--------Version info---------
Polars:              0.18.15
Index type:          UInt32
Platform:            Linux-3.10.0-1160.88.1.el7.x86_64-x86_64-with-glibc2.17
Python:              3.11.4 | packaged by conda-forge | (main, Jun 10 2023, 18:08:17) [GCC 12.2.0]

----Optional dependencies----
adbc_driver_sqlite:  <not installed>
cloudpickle:         <not installed>
connectorx:          <not installed>
deltalake:           <not installed>
fsspec:              <not installed>
matplotlib:          3.7.2
numpy:               1.25.2
pandas:              2.0.3
pyarrow:             12.0.1
pydantic:            <not installed>
sqlalchemy:          <not installed>
xlsx2csv:            0.8.1
xlsxwriter:          3.1.2
```

</details>

**Comment by Wainberg** [comment]
Closing as a duplicate of https://github.com/pola-rs/polars/issues/12876.
