### ISSUE TITLE
Implement dunder methods present in `Series` but not `DataFrame`

### ISSUE THREAD

**Issue by Wainberg** [pola-rs/polars#10608]
### Problem description

`Series` has 19 dunder methods that `DataFrame` doesn't (not counting `__column_consortium_standard__`):

```python
__abs__
__and__
__array_ufunc__
__invert__
__matmul__
__neg__
__or__
__pos__
__pow__
__rand__
__rfloordiv__
__rmatmul__
__rmod__
__ror__
__rpow__
__rsub__
__rtruediv__
__rxor__
__xor__
```

Some of these implement basic behavior that new users coming from pandas/NumPy would expect to be supported:

```
>>> df ** 2
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: unsupported operand type(s) for ** or pow(): 'DataFrame' and 'int'
>>> -df
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: bad operand type for unary -: 'DataFrame'
>>> 1 - df
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: unsupported operand type(s) for -: 'int' and 'DataFrame'
```

**Comment by ritchie46** [comment]
A DataFrame is not a tensor.

**Comment by Wainberg** [comment]
I get the desire to not be pandas and have 5 different ways of doing everything, but DataFrames already support +, -, *, /, //, %, ==, !=, <, >, <=, >=, so I figure it's better to either deprecate all of those or support the remaining ones. If someone comes from pandas and tries `1 + df` and it works and `1 - df` and it's not implemented, they may naively say polars isn't ready for prime time yet and jump ship. The consistency is more important than anything.

**Comment by ritchie46** [comment]
Yes, go all or go home. But I think we should remove the others as well. 

We now have an API to support it more granulary and just more safe.

**Comment by stinodego** [comment]
There is some DataFrame arithmetic implemented in Rust:
https://github.com/pola-rs/polars/blob/main/crates/polars-core/src/frame/arithmetic.rs

If we can have a proper architecture for how DataFrame arithmetic works (e.g. how to deal with non-numeric columns, different column names, different shapes), and this is implemented in Rust, I would be in favor of extending the existing arithmetic operations.

**Comment by mitstake** [comment]
> If we can have a proper architecture for how DataFrame arithmetic works 

You might find this idea interesting. I know @ritchie46 stated above that a dataframe is not a tensor. But I’m thinking that with this minimally invasive approach and the fact that under the hood everything is implemented as standard polars operations it might make the idea more palatable.

https://github.com/pola-rs/polars/issues/23938
