### ISSUE TITLE
join_asof: Check that left_on/right_on are strings

### ISSUE THREAD

**Issue by florianlaws** [pola-rs/polars#10687]
### Problem description

If you accidentally use single-item lists of column names for the `left_on` or `right_on` arguments of `DataFrame.join_asof`, you get a cryptic 
``PanicException: no `columns` expected at this point``.  (see below)

It might be nicer to check that left_on and right_on are string column names and raise an appropriately worded ValueError.
(similar to what happens if you pass a list of column names to the `on` argument.)

#### Code example 
```
import polars as pl
from datetime import datetime

gdp = pl.DataFrame(
    {
        "date": [
            datetime(2016, 1, 1), datetime(2017, 1, 1), datetime(2018, 1, 1), datetime(2019, 1, 1),
        ],  # note record date: Jan 1st (sorted!)
        "gdp": [4164, 4411, 4566, 4696],
    }
).set_sorted("date")
population = pl.DataFrame(
    {
        "date": [
            datetime(2016, 5, 12),  datetime(2017, 5, 12), datetime(2018, 5, 12), datetime(2019, 5, 12),
        ],  # note record date: May 12th (sorted!)
        "population": [82.19, 82.66, 83.12, 83.52],
    }
).set_sorted("date")

# Note the list brackets on left_on and right_on (bad!)
population.join_asof(gdp, left_on=["date"], right_on=["date"], strategy="backward")
```

#### Resulting backtrace:
```
thread '<unnamed>' panicked at 'no `columns` expected at this point', /home/runner/work/polars/polars/crates/polars-plan/src/logical_plan/conversion.rs:154:33
stack backtrace:
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
Traceback (most recent call last):
  File "polars_crash_example2.py", line 21, in <module>
    population.join_asof(gdp, left_on=["date"], right_on=["date"], strategy="backward")
  File "/home/sagemaker-user/.local/lib/python3.8/site-packages/polars/dataframe/frame.py", line 5659, in join_asof
    self.lazy()
  File "/home/sagemaker-user/.local/lib/python3.8/site-packages/polars/lazyframe/frame.py", line 3037, in join_asof
    self._ldf.join_asof(
pyo3_runtime.PanicException: no `columns` expected at this point
```

**Comment by mcrumiller** [comment]
Definitely a bad error message. `join_asof` only works with a single `on` column, so we should not accept lists. This should be a type check on the Python side before we even call the underlying join.
