### ISSUE TITLE
index can not use negative number

### ISSUE THREAD

**Issue by wukan1986** [pola-rs/polars#10872]
### Checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pypi.org/project/polars/) of Polars.

### Reproducible example

```python
import polars as pl

b = pl.Series(range(100))
print(b[1], b[99], b[-2])
"""
1.0 99.0 98.0
"""

b[1] = None
b[99] = None
print(b[1], b[99], b[-2])
"""
None None 98.0
"""


b[-2] = None
r"""
Traceback (most recent call last):
  File "D:\GitHub\my_quant\tests\tt1.py", line 7, in <module>
    b[-2] = None
    ~^^^^
  File "D:\Users\Kan\miniconda3\envs\py311_1\Lib\site-packages\polars\series\series.py", line 1060, in __setitem__
    self.set_at_idx(key, value)
  File "D:\Users\Kan\miniconda3\envs\py311_1\Lib\site-packages\polars\series\series.py", line 4326, in set_at_idx
    self._s.set_at_idx(idx._s, value._s)
exceptions.ComputeError: index values should not be null
"""
```

### Issue description

index can not use negative number

### Expected behavior

do not throw error

### Installed versions

<details>

```
--------Version info---------
Polars:              0.19.0
Index type:          UInt32
Platform:            Windows-10-10.0.22621-SP0
Python:              3.11.3 | packaged by Anaconda, Inc. | (main, Apr 19 2023, 23:46:34) [MSC v.1916 64 bit (AMD64)]

----Optional dependencies----
adbc_driver_sqlite:  <not installed>
cloudpickle:         <not installed>
connectorx:          <not installed>
deltalake:           <not installed>
fsspec:              <not installed>
matplotlib:          3.7.1
numpy:               1.24.3
pandas:              2.0.1
pyarrow:             12.0.0
pydantic:            1.10.7
sqlalchemy:          2.0.13
xlsx2csv:            <not installed>
xlsxwriter:          <not installed>
```

</details>

**Comment by ritchie46** [comment]
It is not meant to work with negative indices. We should probably document that.

**Comment by wukan1986** [comment]
`print(b[-1])` work
`b[-1] = None`  not work

 it not make sense

**Comment by cjackal** [comment]
I'm also +1 to make the setter and getter accept the same index range, not to just furnish the documentation. It indeed consumes too much mental memory to just remember `v = series[-1]` works and `series[-1]` does not work each time accessing the series values.

**Comment by ritchie46** [comment]
Alright. Will fix the inconsistency.
