### ISSUE TITLE
merge_sorted with null collumns raises PanicException: not implemented

### ISSUE THREAD

**Issue by cmadlener** [pola-rs/polars#10921]
### Checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pypi.org/project/polars/) of Polars.

### Reproducible example

```python
import polars as pl

df1 = pl.DataFrame({"key": 1, "null": [None]}, schema={"key": int, "null": pl.Null})
df2 = pl.DataFrame({"key": 2, "null": [None]}, schema={"key": int, "null": pl.Null})
df1.merge_sorted(df2, "key")
```

### Log output

```shell
UNION: union is run in parallel
thread '<unnamed>' panicked at crates/polars-ops/src/frame/join/merge_sorted.rs:94:13:
not implemented for dtype Null
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
Traceback (most recent call last):
  File "/snap/pycharm-community/407/plugins/python-ce/helpers/pydev/pydevconsole.py", line 364, in runcode
    coro = func()
           ^^^^^^
  File "<input>", line 3, in <module>
  File "/home/christoph/utah/.venv/lib/python3.11/site-packages/polars/dataframe/frame.py", line 10718, in merge_sorted
    return self.lazy().merge_sorted(other.lazy(), key).collect(_eager=True)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/christoph/utah/.venv/lib/python3.11/site-packages/polars/lazyframe/frame.py", line 2027, in collect
    return wrap_df(ldf.collect(callback))
                   ^^^^^^^^^^^^^^^^^^^^^
pyo3_runtime.PanicException: not implemented for dtype Null
```

### Issue description

I'm trying to use `DataFrame.merge_sorted` to merge two dataframes that contain null columns. When doing so, the above exception is raised.

### Expected behavior

I get a merged dataframe with a null column.

### Installed versions

<details>

```
--------Version info---------
Polars:               1.5.0
Index type:           UInt32
Platform:             Linux-6.8.0-40-generic-x86_64-with-glibc2.35
Python:               3.11.3 (main, May  8 2023, 10:18:23) [GCC 11.3.0]

----Optional dependencies----
adbc_driver_manager:  <not installed>
cloudpickle:          <not installed>
connectorx:           <not installed>
deltalake:            <not installed>
fastexcel:            <not installed>
fsspec:               <not installed>
gevent:               <not installed>
great_tables:         <not installed>
hvplot:               <not installed>
matplotlib:           <not installed>
nest_asyncio:         <not installed>
numpy:                2.1.0
openpyxl:             <not installed>
pandas:               <not installed>
pyarrow:              17.0.0
pydantic:             2.7.1
pyiceberg:            <not installed>
sqlalchemy:           <not installed>
torch:                <not installed>
xlsx2csv:             <not installed>
xlsxwriter:           <not installed>
```

</details>

**Comment by coastalwhite** [comment]
Fixed.
