### ISSUE TITLE
Fail projection after select + exclude

### ISSUE THREAD

**Issue by gab23r** [pola-rs/polars#10982]
### Checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pypi.org/project/polars/) of Polars.

### Reproducible example

```python
import polars as pl
(
    pl.LazyFrame({'a': [0], 'b': [1]})
    .select([
        pl.col('a').name.suffix('_suffix'),
        pl.col('b').alias('a')
    ])
    # .collect().lazy() # uncomment to fix the bug
    .select(pl.exclude('c')) # c doesn't exist but but should work anyway
    .collect()
)

```

### Log output

```shell
thread '<unnamed>' panicked at /home/runner/work/polars/polars/crates/polars-plan/src/utils.rs:386:68:
called `Result::unwrap()` on an `Err` value: ColumnNotFound(ErrString("a"))
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
Traceback (most recent call last):
  File "<stdin>", line 9, in <module>
  File "/local/home/robin_ga/.local/lib/python3.10/site-packages/polars/utils/deprecation.py", line 95, in wrapper
    return function(*args, **kwargs)
  File "/local/home/robin_ga/.local/lib/python3.10/site-packages/polars/lazyframe/frame.py", line 1695, in collect
    return wrap_df(ldf.collect())
pyo3_runtime.PanicException: called `Result::unwrap()` on an `Err` value: ColumnNotFound(ErrString("a"))
```

### Issue description

The snippet should work, it works in eager

### Expected behavior

No error

### Installed versions

<details>

```
--------Version info---------
Polars:              0.19.2
Index type:          UInt32
Platform:            Linux-3.10.0-862.el7.x86_64-x86_64-with-glibc2.17
Python:              3.10.9 | packaged by conda-forge | (main, Feb  2 2023, 20:20:04) [GCC 11.3.0]

----Optional dependencies----
adbc_driver_sqlite:  <not installed>
cloudpickle:         2.2.1
connectorx:          0.3.1
deltalake:           <not installed>
fsspec:              2023.1.0
matplotlib:          <not installed>
numpy:               1.24.1
pandas:              1.5.3
pyarrow:             11.0.0
pydantic:            1.10.8
sqlalchemy:          2.0.1
xlsx2csv:            <not installed>
xlsxwriter:          <not installed>
```

</details>

**Comment by reswqa** [comment]
This should be a bug of `project pushdown`. Didn't take a closer look, but I guess we should first process all `alias` before add `expr` to accumulated.

The temporary workaround is collect without `project pushdown`.
```python
collect(projection_pushdown=False)
```

**Comment by henryharbeck** [comment]
Hi @stinodego, this issue can be closed as the reproducible example no longer raises.
