### ISSUE TITLE
`date + duration` is supported while `duration + date` is not

### ISSUE THREAD

**Issue by billylanchantin** [pola-rs/polars#11034]
### Checks

- [X] I have checked that this issue has not already been reported.
- [X] I have confirmed this bug exists on the [latest version](https://crates.io/crates/polars) of Polars.

### Reproducible example

Run online here: https://www.rustexplorer.com/b/szxxv4

```rust
use polars::export::chrono::NaiveDate;
use polars::prelude::*;

fn main() {
    std::env::set_var("POLARS_VERBOSE", "1");
    std::env::set_var("RUST_BACKTRACE", "1");

    let d1 = Series::new("date1", [NaiveDate::from_ymd_opt(2023, 09, 09)]);
    let d2 = Series::new("date2", [NaiveDate::from_ymd_opt(2023, 09, 10)]);
    let diff = Series::new("diff", &d2 - &d1);

    println!("{:?}", &d1 + &diff); // => 2023-09-10 [date]
    println!("{:?}", &diff + &d1); // => panics
}
```

### Log output

```shell
thread 'main' panicked at /home/explorer/.cargo/registry/src/index.crates.io-6f17d22bba15001f/polars-core-0.32.1/src/series/arithmetic/borrowed.rs:483:27:
called `Result::unwrap()` on an `Err` value: InvalidOperation(ErrString("add operation not supported for dtypes `duration[ms]` and `date`"))
stack backtrace:
   0: rust_begin_unwind
             at /rustc/9f5fc1bd443f59583e7af0d94d289f95fe1e20c4/library/std/src/panicking.rs:619:5
   1: core::panicking::panic_fmt
             at /rustc/9f5fc1bd443f59583e7af0d94d289f95fe1e20c4/library/core/src/panicking.rs:72:14
   2: core::result::unwrap_failed
             at /rustc/9f5fc1bd443f59583e7af0d94d289f95fe1e20c4/library/core/src/result.rs:1652:5
   3: core::result::Result<T,E>::unwrap
             at /rustc/9f5fc1bd443f59583e7af0d94d289f95fe1e20c4/library/core/src/result.rs:1077:23
   4: polars_core::series::arithmetic::borrowed::<impl core::ops::arith::Add for &polars_core::series::Series>::add
             at ./.cargo/registry/src/index.crates.io-6f17d22bba15001f/polars-core-0.32.1/src/series/arithmetic/borrowed.rs:483:9
   5: playground::main
             at ./playground/src/main.rs:17:22
   6: core::ops::function::FnOnce::call_once
             at /rustc/9f5fc1bd443f59583e7af0d94d289f95fe1e20c4/library/core/src/ops/function.rs:250:5
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```

### Issue description

Despite `date + duration` returning the correct value and dtype, `duration + date` panics.

### Expected behavior

Addition should be a commutative operation. Since `date + duration` is supported, `duration + date` should be as well.

### Installed versions

I'm not sure exactly what was expected for this section. Please LMK if more info is needed!

<details>

```
   Compiling libc v0.2.147
   Compiling autocfg v1.1.0
   Compiling proc-macro2 v1.0.66
   Compiling version_check v0.9.4
   Compiling unicode-ident v1.0.11
   Compiling cfg-if v1.0.0
   Compiling static_assertions v1.1.0
   Compiling libm v0.2.7
   Compiling scopeguard v1.2.0
   Compiling crossbeam-utils v0.8.16
   Compiling memchr v2.6.3
   Compiling syn v1.0.109
   Compiling pkg-config v0.3.27
   Compiling lexical-util v0.8.5
   Compiling futures-core v0.3.28
   Compiling futures-channel v0.3.28
   Compiling futures-task v0.3.28
   Compiling semver v1.0.18
   Compiling num-traits v0.2.16
   Compiling memoffset v0.9.0
   Compiling crossbeam-epoch v0.9.15
   Compiling slab v0.4.9
   Compiling ahash v0.8.3
   Compiling futures-sink v0.3.28
   Compiling target-features v0.1.4
   Compiling once_cell v1.18.0
   Compiling serde v1.0.188
   Compiling pin-project-lite v0.2.13
   Compiling quote v1.0.33
   Compiling futures-util v0.3.28
   Compiling syn v2.0.30
   Compiling jobserver v0.1.26
   Compiling getrandom v0.2.10
   Compiling lexical-parse-integer v0.8.6
   Compiling lexical-write-integer v0.8.5
   Compiling cc v1.0.83
   Compiling zstd-safe v6.0.6
   Compiling futures-io v0.3.28
   Compiling rayon-core v1.11.0
   Compiling either v1.9.0
   Compiling pin-utils v0.1.0
   Compiling lexical-parse-float v0.8.5
   Compiling lexical-write-float v0.8.5
   Compiling rustc_version v0.4.0
   Compiling crossbeam-deque v0.8.3
   Compiling num_cpus v1.16.0
   Compiling crossbeam-channel v0.5.8
   Compiling aho-corasick v1.0.5
   Compiling regex-syntax v0.7.5
   Compiling iana-time-zone v0.1.57
   Compiling array-init-cursor v0.2.0
   Compiling arrow2 v0.17.4
   Compiling chrono v0.4.28
   Compiling lexical-core v0.8.5
   Compiling planus v0.3.1
   Compiling log v0.4.20
   Compiling thiserror v1.0.48
   Compiling lock_api v0.4.10
   Compiling allocator-api2 v0.2.16
   Compiling signal-hook v0.3.17
   Compiling parking_lot_core v0.9.8
   Compiling hash_hasher v2.0.3
   Compiling rustversion v1.0.14
   Compiling foreign_vec v0.1.0
   Compiling strength_reduce v0.2.4
   Compiling simdutf8 v0.1.4
   Compiling rayon v1.7.0
   Compiling regex-syntax v0.6.29
   Compiling dyn-clone v1.0.13
   Compiling zstd-sys v2.0.8+zstd.1.5.5
   Compiling lz4-sys v1.9.4
   Compiling ethnum v1.4.0
   Compiling mio v0.8.8
   Compiling signal-hook-registry v1.4.1
   Compiling smartstring v1.0.1
   Compiling smallvec v1.11.0
   Compiling regex-automata v0.3.8
   Compiling rand_core v0.6.4
   Compiling polars-utils v0.32.1
   Compiling heck v0.4.1
   Compiling ppv-lite86 v0.2.17
   Compiling parking_lot v0.12.1
   Compiling signal-hook-mio v0.2.3
   Compiling sysinfo v0.29.9
   Compiling polars-arrow v0.32.1
   Compiling bitflags v1.3.2
   Compiling rand_chacha v0.3.1
   Compiling crossterm v0.26.1
   Compiling polars-core v0.32.1
   Compiling hashbrown v0.14.0
   Compiling rand v0.8.5
   Compiling strum v0.24.1
   Compiling unicode-width v0.1.10
   Compiling equivalent v1.0.1
   Compiling polars-ops v0.32.1
   Compiling bitflags v2.4.0
   Compiling xxhash-rust v0.8.6
   Compiling argminmax v0.6.1
   Compiling indexmap v2.0.0
   Compiling async-trait v0.1.73
   Compiling rand_distr v0.4.3
   Compiling now v0.1.3
   Compiling atoi v2.0.0
   Compiling socket2 v0.5.3
   Compiling lexical v6.1.1
   Compiling memmap2 v0.7.1
   Compiling polars-plan v0.32.1
   Compiling home v0.5.5
   Compiling regex v1.9.5
   Compiling fast-float v0.2.0
   Compiling bytes v1.4.0
   Compiling polars-pipe v0.32.1
   Compiling tokio v1.32.0
   Compiling polars-lazy v0.32.1
   Compiling serde_json v1.0.105
   Compiling glob v0.3.1
   Compiling itoa v1.0.9
   Compiling ryu v1.0.15
   Compiling sqlparser v0.36.1
   Compiling polars v0.32.1
   Compiling futures-macro v0.3.28
   Compiling serde_derive v1.0.188
   Compiling multiversion-macros v0.7.3
   Compiling bytemuck_derive v1.4.1
   Compiling thiserror-impl v1.0.48
   Compiling strum_macros v0.24.3
   Compiling bytemuck v1.13.1
   Compiling strum_macros v0.25.2
   Compiling enum_dispatch v0.3.12
   Compiling multiversion v0.7.3
   Compiling comfy-table v7.0.1
   Compiling futures-executor v0.3.28
   Compiling futures v0.3.28
   Compiling arrow-format v0.8.1
   Compiling zstd v0.12.4
   Compiling lz4 v1.24.0
   Compiling polars-error v0.32.1
   Compiling polars-row v0.32.1
   Compiling polars-time v0.32.1
   Compiling polars-io v0.32.1
   Compiling polars-sql v0.32.1
```

</details>

**Comment by billylanchantin** [comment]
If this behavior is not intentional, I'm happy to try and submit PR.

**Comment by mcrumiller** [comment]
I don't think this makes sense--adding a duration to a point in time makes sense, but adding a point in time to a duration doesn't. It could obviously be trivially implemented as commutative but I'm not sure we want that. @MarcoGorelli is our local time expert so he should probably be the one to decide on this.

**Comment by billylanchantin** [comment]
Sorry, I'm not sure I follow. Why would a duration being involved make addition not commutative?

For additional context, `+` is commutative for `datetime` and I think that's correct.

**Comment by alexander-beedie** [comment]
> Why would a duration being involved make addition not commutative?

Well, `chrono` isn't in favour of `duration + date` either (despite `duration + date` obviously working fine)  ;)

```rust
extern crate chrono;
use chrono::{Duration, Utc};

fn main() {
	let dt = Duration::days(100) + Utc::now();
	println!("{}", dt);
}

//  --> src/main.rs:5:33
//   |
// 5 |     let dt = Duration::days(100) + Utc::now();
//   |              -------------------   ^^^^^^^^^^ expected `Duration`, found `DateTime<Utc>`
//   |              |
//   |              expected because this is `chrono::Duration`
//   |
//   = note: expected struct `chrono::Duration`
//              found struct `DateTime<Utc>`
```

However, it turns out that the equivalent Python _is_ supported...
```python
datetime(2020,1,1) + timedelta(hours=23)
# datetime(2020, 1, 1, 23, 0)

timedelta(hours=23) + datetime(2020,1,1)
# datetime(2020, 1, 1, 23, 0)
```

..._and_ we already have `Series` support for this on the Python side:
```python
from datetime import datetime, timedelta
import polars as pl

df = pl.DataFrame({
    "dt": [datetime(2020,1,1), datetime(2000,12,31)], 
    "td": [timedelta(hours=23, minutes=59), timedelta(hours=11, minutes=22, seconds=33)]
})

df["dt"] + df["td"]
# shape: (2,)
# Series: 'dt' [datetime[μs]]
# [
# 	2020-01-01 23:59:00
# 	2000-12-31 11:22:33
# ]

df["td"] + df["dt"] 
# shape: (2,)
# Series: 'td' [datetime[μs]]
# [
# 	2020-01-01 23:59:00
# 	2000-12-31 11:22:33
# ]
```
Given that we already support this on one side of the API (Python) I think we should probably have consistency/parity in behaviour on the Rust side. I'd consider it reasonable to address the issue accordingly.

**Comment by mcrumiller** [comment]
> Why would a duration being involved make addition not commutative?

I view time + duration as the equivalent of time.offset_by(duration), which is not commutative obviously--you cannot offset a duration by a time. A date/datetime is a position on the time axis and a duration is a movement along the time axis.

**Comment by slonik-az** [comment]
As per @alexander-beedie comment, the python side is already commutative. So it makes sense to have Rust and Python behavior be the same. And according to the "principle of least surprise" keeping addition commutative makes sense even though `duration + date` is yucky.
