### ISSUE TITLE
PanicException when converting non-Utf8 column to Catergorical.

### ISSUE THREAD

**Issue by ghuls** [pola-rs/polars#1107]
#### Are you using Python or Rust?

**Python**.

#### What version of polars are you using?

0.8.17

#### What operating system are you using polars on?

CentOS 7

#### Describe your bug.

Accidentally converting a int column to a catergorical gives a panic exception instead of "Unsupported operation" or something similar.

#### What are the steps to reproduce the behavior?

```
In [74]: pd_df_with_categorical = pd.DataFrame({'a': pd.Categorical(['a', 'b', 'c', 'c', 'a', 'b']), 'b': [2, 6, 8, 1, 3, 6]})

In [75]: pl.DataFrame(pd_df_with_categorical)
Out[75]: 
shape: (6, 2)
╭─────┬─────╮
│ a   ┆ b   │
│ --- ┆ --- │
│ i8  ┆ i64 │
╞═════╪═════╡
│ 0   ┆ 2   │
├╌╌╌╌╌┼╌╌╌╌╌┤
│ 1   ┆ 6   │
├╌╌╌╌╌┼╌╌╌╌╌┤
│ 2   ┆ 8   │
├╌╌╌╌╌┼╌╌╌╌╌┤
│ 2   ┆ 1   │
├╌╌╌╌╌┼╌╌╌╌╌┤
│ 0   ┆ 3   │
├╌╌╌╌╌┼╌╌╌╌╌┤
│ 1   ┆ 6   │
╰─────┴─────╯

In [77]: pl.DataFrame(pd_df_with_categorical).with_column(pl.col('a').cast(pl.Categorical))
Out[77]: thread '<unnamed>' panicked at 'should be set', /lustre1/project/stg_00002/lcb/ghuls/software/polars/polars/polars-core/src/chunked_array/mod.rs:583:62
---------------------------------------------------------------------------
PanicException                            Traceback (most recent call last)
<ipython-input-77-b2ca6ce88d30> in <module>
----> 1 pl.DataFrame(pd_df_with_categorical).with_column(pl.col('a').cast(pl.Categorical))

/software/miniconda3/envs/cisTopic/lib/python3.7/site-packages/IPython/core/displayhook.py in __call__(self, result)
    260             self.start_displayhook()
    261             self.write_output_prompt()
--> 262             format_dict, md_dict = self.compute_format_data(result)
    263             self.update_user_ns(result)
    264             self.fill_exec_result(result)
/software/miniconda3/envs/cisTopic/lib/python3.7/site-packages/IPython/core/displayhook.py in compute_format_data(self, result)
    149 
    150         """
--> 151         return self.shell.display_formatter.format(result)
    152 
    153     # This can be set to True by the write_output_prompt method in a subclass

/software/miniconda3/envs/cisTopic/lib/python3.7/site-packages/IPython/core/formatters.py in format(self, obj, include, exclude)
    178             md = None
    179             try:
--> 180                 data = formatter(obj)
    181             except:
    182                 # FIXME: log the exception
/software/miniconda3/envs/cisTopic/lib/python3.7/site-packages/decorator.py in fun(*args, **kw)
    230             if not kwsyntax:
    231                 args, kw = fix(args, kw, sig)
--> 232             return caller(func, *(extras + args), **kw)
    233     fun.__name__ = func.__name__
    234     fun.__doc__ = func.__doc__

/software/miniconda3/envs/cisTopic/lib/python3.7/site-packages/IPython/core/formatters.py in catch_format_error(method, self, *args, **kwargs)
    222     """show traceback on failed format call"""
    223     try:
--> 224         r = method(self, *args, **kwargs)
    225     except NotImplementedError:
    226         # don't warn on NotImplementedErrors

/software/miniconda3/envs/cisTopic/lib/python3.7/site-packages/IPython/core/formatters.py in __call__(self, obj)
    700                 type_pprinters=self.type_printers,
    701                 deferred_pprinters=self.deferred_printers)
--> 702             printer.pretty(obj)
    703             printer.flush()
    704             return stream.getvalue()

/software/miniconda3/envs/cisTopic/lib/python3.7/site-packages/IPython/lib/pretty.py in pretty(self, obj)
    392                         if cls is not object \
    393                                 and callable(cls.__dict__.get('__repr__')):
--> 394                             return _repr_pprint(obj, self, cycle)
    395 
    396             return _default_pprint(obj, self, cycle)

/software/miniconda3/envs/cisTopic/lib/python3.7/site-packages/IPython/lib/pretty.py in _repr_pprint(obj, p, cycle)
    698     """A pprint that just redirects to the normal repr function."""
    699     # Find newlines and replace them with p.break_()
--> 700     output = repr(obj)
    701     lines = output.splitlines()
    702     with p.group():

/software/miniconda3/envs/cisTopic/lib/python3.7/site-packages/polars/eager/frame.py in __repr__(self)
    820 
    821     def __repr__(self) -> str:
--> 822         return self.__str__()
    823 
    824     def __getattr__(self, item: Any) -> "PySeries":
/software/miniconda3/envs/cisTopic/lib/python3.7/site-packages/polars/eager/frame.py in __str__(self)
    817 
    818     def __str__(self) -> str:
--> 819         return self._df.as_str()
    820 
    821     def __repr__(self) -> str:

PanicException: should be set

In [78]: pl.DataFrame(pd_df_with_categorical).with_column(pl.col('b').cast(pl.Categorical))
Out[78]: thread '<unnamed>' panicked at 'should be set', /lustre1/project/stg_00002/lcb/ghuls/software/polars/polars/polars-core/src/chunked_array/mod.rs:583:62
---------------------------------------------------------------------------
PanicException                            Traceback (most recent call last)
<ipython-input-78-6fe67beba6e1> in <module>
----> 1 pl.DataFrame(pd_df_with_categorical).with_column(pl.col('b').cast(pl.Categorical))

/software/miniconda3/envs/cisTopic/lib/python3.7/site-packages/IPython/core/displayhook.py in __call__(self, result)
    260             self.start_displayhook()
    261             self.write_output_prompt()
--> 262             format_dict, md_dict = self.compute_format_data(result)
    263             self.update_user_ns(result)
    264             self.fill_exec_result(result)

/software/miniconda3/envs/cisTopic/lib/python3.7/site-packages/IPython/core/displayhook.py in compute_format_data(self, result)
    149 
    150         """
--> 151         return self.shell.display_formatter.format(result)
    152 
    153     # This can be set to True by the write_output_prompt method in a subclass

/software/miniconda3/envs/cisTopic/lib/python3.7/site-packages/IPython/core/formatters.py in format(self, obj, include, exclude)
    178             md = None
    179             try:
--> 180                 data = formatter(obj)
    181             except:
    182                 # FIXME: log the exception

/software/miniconda3/envs/cisTopic/lib/python3.7/site-packages/decorator.py in fun(*args, **kw)
    230             if not kwsyntax:
    231                 args, kw = fix(args, kw, sig)
--> 232             return caller(func, *(extras + args), **kw)
    233     fun.__name__ = func.__name__
    234     fun.__doc__ = func.__doc__

/software/miniconda3/envs/cisTopic/lib/python3.7/site-packages/IPython/core/formatters.py in catch_format_error(method, self, *args, **kwargs)
    222     """show traceback on failed format call"""
    223     try:
--> 224         r = method(self, *args, **kwargs)
    225     except NotImplementedError:
    226         # don't warn on NotImplementedErrors

/software/miniconda3/envs/cisTopic/lib/python3.7/site-packages/IPython/core/formatters.py in __call__(self, obj)
    700                 type_pprinters=self.type_printers,
    701                 deferred_pprinters=self.deferred_printers)
--> 702             printer.pretty(obj)
    703             printer.flush()
    704             return stream.getvalue()

/software/miniconda3/envs/cisTopic/lib/python3.7/site-packages/IPython/lib/pretty.py in pretty(self, obj)
    392                         if cls is not object \
    393                                 and callable(cls.__dict__.get('__repr__')):
--> 394                             return _repr_pprint(obj, self, cycle)
    395 
    396             return _default_pprint(obj, self, cycle)

/software/miniconda3/envs/cisTopic/lib/python3.7/site-packages/IPython/lib/pretty.py in _repr_pprint(obj, p, cycle)
    698     """A pprint that just redirects to the normal repr function."""
    699     # Find newlines and replace them with p.break_()
--> 700     output = repr(obj)
    701     lines = output.splitlines()
    702     with p.group():

/software/miniconda3/envs/cisTopic/lib/python3.7/site-packages/polars/eager/frame.py in __repr__(self)
    820 
    821     def __repr__(self) -> str:
--> 822         return self.__str__()
    823 
    824     def __getattr__(self, item: Any) -> "PySeries":

/software/miniconda3/envs/cisTopic/lib/python3.7/site-packages/polars/eager/frame.py in __str__(self)
    817 
    818     def __str__(self) -> str:
--> 819         return self._df.as_str()
    820 
    821     def __repr__(self) -> str:

PanicException: should be set

```

**Comment by ghuls** [comment]
pandas Catergorical (pyarrow Dictionary) to polars string auto conversion seems to be broken.

Fixed here: https://github.com/pola-rs/polars/pull/1108

**Comment by ritchie46** [comment]
fixed and released. Thanks again @ghuls
