### ISSUE TITLE
`when/then` fails during `with_context` if predicate is re-used

### ISSUE THREAD

**Issue by mcrumiller** [pola-rs/polars#11071]
### Checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pypi.org/project/polars/) of Polars.

### Reproducible example

```python
import polars as pl
from polars import col, when

df1 = pl.LazyFrame({
    "a": [1, 2, 3],
})

df2 = pl.LazyFrame({
    "b": [True, False, False],
    "c": [False, False, False],
})

df1.with_context(df2).select(
    when((col("a") == 1) & col("b")).then("ab"),
    when((col("a") == 1) & col("c")).then("ac")  # col("a") == 1 is re-used, causes panic
    .alias("c")
).collect()
```

### Log output

```shell
thread 'thread '<unnamed><unnamed>' panicked at ' panicked at D:\a\polars\polars\crates\polars-lazy\src\physical_plan\expressions\column.rsD:\a\polars\polars\crates\polars-lazy\src\physical_plan\expressions\column.rs::124124::4040:
:
range start index 3 out of range for slice of length 2range start index 3 out of range for slice of length 2

Traceback (most recent call last):
  File "<stdin>", line 5, in <module>
  File "C:\Projects\project-brr\.venv_brr\Lib\site-packages\polars\utils\deprecation.py", line 95, in wrapper
    return function(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Projects\project-brr\.venv_brr\Lib\site-packages\polars\lazyframe\frame.py", line 1695, in collect
    return wrap_df(ldf.collect())
                   ^^^^^^^^^^^^^
pyo3_runtime.PanicException: range start index 3 out of range for slice of length 2
```

### Issue description

When `pl.with_context()` is used on two lazy frames, then if the `when/then` sequence includes the same predicate twice (in this case, `col(a) == 1)`), a panic occurs.

### Expected behavior

Should evaluate properly.

### Installed versions

<details>

```
--------Version info---------
Polars:              0.19.2
Index type:          UInt32
Platform:            Windows-10-10.0.19045-SP0
Python:              3.11.2 (tags/v3.11.2:878ead1, Feb  7 2023, 16:38:35) [MSC v.1934 64 bit (AMD64)]

----Optional dependencies----
adbc_driver_sqlite:  <not installed>
cloudpickle:         <not installed>
connectorx:          0.3.2
deltalake:           <not installed>
fsspec:              <not installed>
matplotlib:          3.7.1
numpy:               1.25.2
pandas:              2.0.3
pyarrow:             11.0.0
pydantic:            <not installed>
sqlalchemy:          2.0.7
xlsx2csv:            0.8.1
xlsxwriter:          3.0.9
```

</details>

**Comment by mcrumiller** [comment]
A bit simpler example, but less obvious:

```python
pl.LazyFrame({"a": [1]}).with_context(pl.LazyFrame({"b": [2]})).select(
    when(col("a") == 1).then(1)
    .when(col("a") == 1).then(2)
).collect()
```
```
pyo3_runtime.PanicException: called `Option::unwrap()` on a `None` value
```

**Comment by cmdlineluser** [comment]
This was fixed on main by https://github.com/pola-rs/polars/pull/11051
