### ISSUE TITLE
Confusing error message when using `min` instead of `min_horizontal`

### ISSUE THREAD

**Issue by daniel-vainsencher** [pola-rs/polars#11139]
### Checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pypi.org/project/polars/) of Polars.

### Reproducible example

On 0.19.2:
```python
import polars as pl

df = pl.DataFrame(pd.DataFrame(
    {
        "A": [None, 1.],
        "B": [2, 3.],
    }))

df.with_columns([
     pl.when(pl.col("A").is_null())
     .then(pl.col("B"))
#     .otherwise(pl.min_horizontal(["A", "B"]))
     .otherwise(pl.min(["A", "B"]))
     .alias("C"),
])```
raises "ComputeError: The name: 'C' passed to `LazyFrame.with_columns` is duplicate"

### Log output

```shell
$ POLARS_VERBOSE=1 python bug_demo.py
Traceback (most recent call last):
  File "/home/danielv/InsurePayWork/IPDS2/nbs/API/bug_demo.py", line 9, in <module>
    df.with_columns([
  File "/home/danielv/InsurePayWork/venv1/lib/python3.10/site-packages/polars/dataframe/frame.py", line 7859, in with_columns
    self.lazy()
  File "/home/danielv/InsurePayWork/venv1/lib/python3.10/site-packages/polars/utils/deprecation.py", line 95, in wrapper
    return function(*args, **kwargs)
  File "/home/danielv/InsurePayWork/venv1/lib/python3.10/site-packages/polars/lazyframe/frame.py", line 1695, in collect
    return wrap_df(ldf.collect())
exceptions.ComputeError: The name: 'C' passed to `LazyFrame.with_columns` is duplicate

Error originated just after this operation:
DF ["A", "B"]; PROJECT */2 COLUMNS; SELECTION: "None"
```

### Issue description

On 0.18.15 this problem did not arise, because `min` supported horizontal operation, but it can also arise out  of other types of user error.

### Expected behavior

The ideal error message would let me know that the number of columns in one of the branches of the conditional is 2 and should be 1. Unless that is actually somehow allowed, and then it should say the number of columns is inconsistent across branches.

The fact that downstream, that seems to cause there to be 2 "C" columns is an implementation detail, and didn't help me understand my (now) misuse of `min` .

### Installed versions

<details>

```
--------Version info---------
Polars:              0.19.2
Index type:          UInt32
Platform:            Linux-5.15.90.1-microsoft-standard-WSL2-x86_64-with-glibc2.35
Python:              3.10.6 (main, Mar 10 2023, 10:55:28) [GCC 11.3.0]

----Optional dependencies----
adbc_driver_sqlite:  <not installed>
cloudpickle:         <not installed>
connectorx:          0.3.2_alpha.2
deltalake:           <not installed>
fsspec:              <not installed>
matplotlib:          3.7.1
numpy:               1.24.2
pandas:              2.0.0
pyarrow:             11.0.0
pydantic:            <not installed>
sqlalchemy:          <not installed>
xlsx2csv:            <not installed>
xlsxwriter:          <not installed>
None
```

</details>

**Comment by cmdlineluser** [comment]
Related: https://github.com/pola-rs/polars/issues/11060

**Comment by daniel-vainsencher** [comment]
Having thought about it a bit more, a different expected behavior would be that simply calling alias on an expression of multiple columns should cause an error about that.
