### ISSUE TITLE
LazyFrame get struct element after aggregation fails to see struct field

### ISSUE THREAD

**Issue by dkumor** [pola-rs/polars#11136]
### Checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pypi.org/project/polars/) of Polars.

### Reproducible example

```python
pl.DataFrame([{
    "a":1,
    "b":2
}]).lazy().group_by('a').agg(
    pl.struct([col('b')]).alias('s')
).with_columns(
    col("s").list.first().struct.field('b').alias('b_val')
).collect()
```
Output:
```
Traceback (most recent call last):
  File "/Users/dkumor/pl_reproduce.py", line 9, in <module>
    ).collect()
  File "/opt/homebrew/lib/python3.10/site-packages/polars/utils/deprecation.py", line 95, in wrapper
    return function(*args, **kwargs)
  File "/opt/homebrew/lib/python3.10/site-packages/polars/lazyframe/frame.py", line 1695, in collect
    return wrap_df(ldf.collect())
exceptions.StructFieldNotFoundError: b

Error originated just after this operation:
AGGREGATE
	[col("b").as_struct().alias("s")] BY [col("a")] FROM
  DF ["a", "b"]; PROJECT */2 COLUMNS; SELECTION: "None"
```

### Log output

```shell
no output
```

### Issue description

Doing an aggregation that creates a list of structs, then getting a field from the first list element fails in LazyFrame. Running collect before getting the struct field succeeds.

### Expected behavior

```python
pl.DataFrame([{
    "a":1,
    "b":2
}]).lazy().group_by('a').agg(
    pl.struct([col('b')]).alias('s')
).collect().with_columns(
    col("s").list.first().struct.field('b').alias('b_val')
)
```
Output:
```
shape: (1, 3)
┌─────┬─────────────────┬───────┐
│ a   ┆ s               ┆ b_val │
│ --- ┆ ---             ┆ ---   │
│ i64 ┆ list[struct[1]] ┆ i64   │
╞═════╪═════════════════╪═══════╡
│ 1   ┆ [{2}]           ┆ 2     │
└─────┴─────────────────┴───────┘
```

### Installed versions

<details>

```

--------Version info---------
Polars:              0.19.2
Index type:          UInt32
Platform:            macOS-13.5.2-arm64-arm-64bit
Python:              3.10.9 (main, Dec 15 2022, 17:11:09) [Clang 14.0.0 (clang-1400.0.29.202)]

----Optional dependencies----
adbc_driver_sqlite:  <not installed>
cloudpickle:         <not installed>
connectorx:          <not installed>
deltalake:           <not installed>
fsspec:              2022.11.0
matplotlib:          3.6.3
numpy:               1.25.2
pandas:              2.1.0
pyarrow:             12.0.0
pydantic:            <not installed>
sqlalchemy:          <not installed>
xlsx2csv:            0.8.1
xlsxwriter:          <not installed>

```

</details>

**Comment by dkumor** [comment]
This has been fixed. Closing.
