### ISSUE TITLE
Can't use `dtypes` options in `read_excel` function.

### ISSUE THREAD

**Issue by Nikhil216** [pola-rs/polars#11161]
### Checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pypi.org/project/polars/) of Polars.

### Reproducible example

```python
import polars as pl

schema = {
    "No": str,
    "Name": str,
}
df = pl.read_excel("names.xlsx", read_csv_options={"dtypes": schema})
print(df)
```

### Log output

```shell
Traceback (most recent call last):
  File "D:\projects\sandbox\polars_read_excel_dtypes_bug.py", line 7, in <module>
    df = pl.read_excel("names.xlsx", read_csv_options={"dtypes": schema})
  File "D:\projects\sandbox\venv\lib\site-packages\polars\io\spreadsheet\functions.py", line 232, in read_excel
    return _read_spreadsheet(
  File "D:\projects\sandbox\venv\lib\site-packages\polars\io\spreadsheet\functions.py", line 432, in _read_spreadsheet
    return reader_fn(
  File "D:\projects\sandbox\venv\lib\site-packages\polars\io\spreadsheet\functions.py", line 671, in _read_spreadsheet_xlsx2csv
    return _csv_buffer_to_frame(
  File "D:\projects\sandbox\venv\lib\site-packages\polars\io\spreadsheet\functions.py", line 511, in _csv_buffer_to_frame
    df = read_csv(
TypeError: polars.io.csv.functions.read_csv() got multiple values for keyword argument 'dtypes'
```

## Context

Today, I was working with polars, using the `read_excel` function. Surprisingly, my code worked for version `0.19.2` but throws an error for version `0.19.3`. The offending line in my code was

```python
df = pl.read_excel(excel_path, read_csv_options={"dtypes": import_schema})
```

Here's the error I saw

```
TypeError: polars.io.csv.functions.read_csv() got multiple values for keyword argument 'dtypes'
```

I did some digging and stumbled on these lines of code

https://github.com/pola-rs/polars/blob/b08bc7d533e1c860bff2a8cec5d891474e67611f/py-polars/polars/io/spreadsheet/functions.py#L511-L516

Now the error makes sense. `read_csv_options` also passes the `dtype` kwarg. This raises the question " Is it okay to pass `dtypes` as `schema_overrides` and `read_csv_options` in `read_excel`?"

@alexander-beedie your inputs are appreciated.

### Expected behavior

It should accept `dtypes` as `schema_overrides` is not passed.

### Installed versions

<details>

```
--------Version info---------
Polars:              0.19.3
Index type:          UInt32
Platform:            Windows-10-10.0.22621-SP0
Python:              3.10.7 (tags/v3.10.7:6cc6b13, Sep  5 2022, 14:08:36) [MSC v.1933 64 bit (AMD64)]

----Optional dependencies----
adbc_driver_sqlite:  <not installed>
cloudpickle:         <not installed>
connectorx:          <not installed>
deltalake:           <not installed>
fsspec:              <not installed>
gevent:              <not installed>
matplotlib:          3.7.2
numpy:               1.22.2
pandas:              1.4.1
pyarrow:             <not installed>
pydantic:            <not installed>
sqlalchemy:          <not installed>
xlsx2csv:            0.8.1
xlsxwriter:          <not installed>
```

</details>

**Comment by alexander-beedie** [comment]
It definitely shouldn't be an error - fix coming up ;)
(The `schema_overrides` method is more generic though).
