### ISSUE TITLE
`read_csv` `schema` argument doesn't work with `new_columns`

### ISSUE THREAD

**Issue by mcrumiller** [pola-rs/polars#11186]
### Reproducible example

```python
from io import StringIO

import polars as pl

csv = StringIO(
    "Name,Age,ID\n"
    "Mark,48,AAA1234\n"
    "Beth,26,BBB1234\n"
    "Steve,19,CCC1234\n"
)

df = pl.read_csv(
    csv,
    columns=["Name", "Age", "ID"],
    new_columns=["Name2", "Age2", "ID2"],
    schema={
        "Name2": pl.Utf8,
        "Age2": pl.UInt8,
        "ID2": pl.Utf8,
    }
)
```

### Log output

```shell
Traceback (most recent call last):
  File "C:\Projects\project-brr\scripts\check_read_csv.py", line 31, in <module>
    df = pl.read_csv(
         ^^^^^^^^^^^^
  File "C:\Projects\project-brr\.venv_brr\Lib\site-packages\polars\io\csv\functions.py", line 364, in read_csv
    df = pl.DataFrame._read_csv(
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Projects\project-brr\.venv_brr\Lib\site-packages\polars\dataframe\frame.py", line 768, in _read_csv
    self._df = PyDataFrame.read_csv(
               ^^^^^^^^^^^^^^^^^^^^^
exceptions.ColumnNotFoundError: unable to find column "Name"; valid columns: ["Name2", "Age2", "ID2"]
```

### Issue description

When `new_columns` is provided along with `schema`, the schema requires the original column names instead of the new columns. If new columns are provided in the schema dictionary, the error still references the old column name, which is confusing. In the example provided, `unable to find column "Name"` is confusing since `Name` is never provided in the schema. The error then also tells us valid column names, but none of those column names are actually usable in the schema.

I think the `schema` should use the new column names if, if provided, and we should probably make that clear in the documentation.

### Installed versions

<details>

```
--------Version info---------
Polars:              0.19.3
Index type:          UInt32
Platform:            Windows-10-10.0.19045-SP0
Python:              3.11.2 (tags/v3.11.2:878ead1, Feb  7 2023, 16:38:35) [MSC v.1934 64 bit (AMD64)]

----Optional dependencies----
adbc_driver_sqlite:  <not installed>
cloudpickle:         <not installed>
connectorx:          0.3.2
deltalake:           <not installed>
fsspec:              <not installed>
gevent:              <not installed>
matplotlib:          3.7.1
numpy:               1.25.2
pandas:              2.0.3
pyarrow:             11.0.0
pydantic:            <not installed>
sqlalchemy:          2.0.7
xlsx2csv:            0.8.1
xlsxwriter:          3.0.9
```

</details>

**Comment by nickolasclarke** [comment]
I am also experiencing this with 

```
to_lower = lambda header_list: [x.lower() for x in header_list]

ldf = pl.scan_csv(
    csv_path,
    with_column_names=to_lower,

)
```

**Comment by stinodego** [comment]
There is no bug here. `columns` operates at the very end, and the columns you're trying to select do not exist. The `schema` defines the columns you can select from.
