### ISSUE TITLE
Unpickling null list fails since 0.19.2

### ISSUE THREAD

**Issue by dkumor** [pola-rs/polars#11187]
### Checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pypi.org/project/polars/) of Polars.

### Reproducible example

```python
import pickle
df = pl.DataFrame([
    {"a": None},
],schema={'a': pl.List(pl.Int64)})
print(df)
print(pickle.loads(pickle.dumps(df)))
```
Output:
```

shape: (1, 1)
┌───────────┐
│ a         │
│ ---       │
│ list[i64] │
╞═══════════╡
│ null      │
└───────────┘
shape: (0, 1)
┌───────────┐
│ a         │
│ ---       │
│ list[i64] │
╞═══════════╡
└───────────┘

```

### Issue description

A dataframe with a list column where all elements are null will be empty on unpickle. It looks like the series is unpickled as empty, since having multiple columns in the dataframe causes a crash:

```python
import pickle
df = pl.DataFrame([
    {"a": None,"b":1},
],schema={'a': pl.List(pl.Int64),'b': pl.Int64})
pickle.loads(pickle.dumps(df))
```
```
Traceback (most recent call last):
  File "/opt/homebrew/lib/python3.10/site-packages/IPython/core/interactiveshell.py", line 3378, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "/var/folders/h0/frpvpbpj2hl34n_277q_tl780000gr/T/ipykernel_62070/2608574199.py", line 5, in <module>
    pickle.loads(pickle.dumps(df))
  File "/opt/homebrew/lib/python3.10/site-packages/polars/dataframe/frame.py", line 1463, in __setstate__
  File "/opt/homebrew/lib/python3.10/site-packages/polars/dataframe/frame.py", line 361, in __init__
  File "/opt/homebrew/lib/python3.10/site-packages/polars/utils/_construction.py", line 855, in sequence_to_pydf
    [(k, v) for k, v in data.items()],
  File "/opt/homebrew/Cellar/python@3.10/3.10.9/Frameworks/Python.framework/Versions/3.10/lib/python3.10/functools.py", line 889, in wrapper
    return dispatch(args[0].__class__)(*args, **kw)
  File "/opt/homebrew/lib/python3.10/site-packages/polars/utils/_construction.py", line 888, in _sequence_of_series_to_pydf
    schema_overrides: SchemaDict | None = None,
exceptions.ShapeError: could not create a new dataframe: series "a" has length 0 while series "b" has length 1
```

### Expected behavior

The two dataframes above should be the same, and unpickling a dataframe shouldn't crash.

### Installed versions

<details>

```
--------Version info---------
Polars:              0.19.3
Index type:          UInt32
Platform:            macOS-13.5.2-arm64-arm-64bit
Python:              3.10.9 (main, Dec 15 2022, 17:11:09) [Clang 14.0.0 (clang-1400.0.29.202)]

----Optional dependencies----
adbc_driver_sqlite:  <not installed>
cloudpickle:         <not installed>
connectorx:          <not installed>
deltalake:           <not installed>
fsspec:              2022.11.0
gevent:              <not installed>
matplotlib:          3.6.3
numpy:               1.25.2
pandas:              2.1.0
pyarrow:             12.0.0
pydantic:            <not installed>
sqlalchemy:          <not installed>
xlsx2csv:            0.8.1
xlsxwriter:          <not installed>
```

</details>

**Comment by ritchie46** [comment]
@c-peters, I defer this one to you. :)
