### ISSUE TITLE
floats are treated as unknown

### ISSUE THREAD

**Issue by stillmatic** [pola-rs/polars#11239]
### Checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pypi.org/project/polars/) of Polars.

### Reproducible example

```python
import polars as pl

df = pl.DataFrame(
    [
        pl.Series("a", [14, 13.8, 18.2], dtype=pl.Float64),
        pl.Series("b", [12.5, 17.3, 21.4], dtype=pl.Float64),
    ]
)
df.with_columns(
    (
        pl.min(pl.col("b"), float(0.14))
        - pl.max(pl.col("a"), float(12.5))
    ).alias("c")
)
```

### Log output

```shell
Traceback (most recent call last):
  File "<stdin>", line 3, in <module>
  File "python/lib/python3.10/site-packages/polars/functions/aggregation/vertical.py", line 238, in min
    return F.col(*names).min()
  File "python/lib/python3.10/site-packages/polars/functions/col.py", line 189, in __call__
    elif is_polars_dtype(name):
  File "python/lib/python3.10/site-packages/polars/datatypes/convert.py", line 156, in is_polars_dtype
    if dtype == Unknown:
  File "python/lib/python3.10/site-packages/polars/expr/expr.py", line 159, in __eq__
    return self._from_pyexpr(self._pyexpr.eq(self._to_expr(other)._pyexpr))
  File "python/lib/python3.10/site-packages/polars/expr/expr.py", line 127, in _to_expr
    return F.lit(other)
  File "python/lib/python3.10/site-packages/polars/functions/lit.py", line 157, in lit
    return wrap_expr(plr.lit(item, allow_object))
ValueError: could not convert value 'Unknown' as a Literal
```

### Issue description

There appears to be a regression between 0.17.3 and 0.19.3 that results in this error.

### Expected behavior

I expect to see 

```
pl.DataFrame(
    [
        pl.Series("a", [14.0, 13.8, 18.2], dtype=pl.Float64),
        pl.Series("b", [12.5, 17.3, 21.4], dtype=pl.Float64),
        pl.Series("c", [-13.86, -13.66, -18.06], dtype=pl.Float64),
    ]
)
```

this output is correct on 0.17.3 but not on 0.19.3

### Installed versions

<details>

```
--------Version info---------
Polars:              0.19.3
Index type:          UInt32
Platform:            Linux-5.15.90.1-microsoft-standard-WSL2-x86_64-with-glibc2.35
Python:              3.10.12 (main, Jul 26 2023, 13:20:36) [Clang 16.0.3 ]

----Optional dependencies----
adbc_driver_sqlite:  <not installed>
cloudpickle:         <not installed>
connectorx:          <not installed>
deltalake:           <not installed>
fsspec:              2023.9.1
gevent:              <not installed>
matplotlib:          3.8.0
numpy:               1.25.2
pandas:              2.1.1
pyarrow:             <not installed>
pydantic:            2.1.1
sqlalchemy:          2.0.21
xlsx2csv:            <not installed>
xlsxwriter:          <not installed>
```

A working install (colab)
```
---Version info---
Polars: 0.17.3
Index type: UInt32
Platform: Linux-5.15.120+-x86_64-with-glibc2.35
Python: 3.10.12 (main, Jun 11 2023, 05:26:28) [GCC 11.4.0]
---Optional dependencies---
numpy: 1.23.5
pandas: 1.5.3
pyarrow: 9.0.0
connectorx: <not installed>
deltalake: <not installed>
fsspec: 2023.6.0
matplotlib: 3.7.1
xlsx2csv: <not installed>
xlsxwriter: <not installed>
```

</details>

**Comment by alexander-beedie** [comment]
Yes, there was a deprecation period for row-wise/horizontal aggregates; rather than implying it from context (which has a few edge-cases) you can now use the specific horizontal versions of the aggregate functions, like so:

```python
df.with_columns(
    (
        pl.min_horizontal(pl.col("b"), 0.14)
        - pl.max_horizontal(pl.col("a"), 12.5)
    ).alias("c")
)
```
Also, as an aside: there is no need to wrap your floats with an explicit `float` ;)

**Comment by stillmatic** [comment]
thanks! was it deprecated in the 0.17.x releases? I didn't see any warnings there
