### ISSUE TITLE
Got here from a function which doesn't have a `ambiguous` argument (dt.round)

### ISSUE THREAD

**Issue by RodrigoZepeda** [pola-rs/polars#11236]
### Checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pypi.org/project/polars/) of Polars.

### Reproducible example

I'm trying to `dt.round` a `datetime` the exact moment Daylight Saving time ended and am getting an error telling me to open an issue because the function doesn't have an ambiguous argument: 

```python
import polars as pl
from datetime import datetime

# Create the Polars DataFrame
df = pl.DataFrame({'event_time': datetime(2022, 11, 6, 1, 0)})

# Convert the 'event_time' column back to datetime objects
df = df.select(
    pl.col("event_time").dt.replace_time_zone('America/New_York', ambiguous='earliest')
)

#GIVES THE ERROR
df = df.select(pl.col("event_time").dt.round("5m"))
```

### Log output

```shell
Traceback (most recent call last):
  File "/usr/local/Caskroom/miniconda/base/envs/polars tutorial/lib/python3.10/site-packages/IPython/core/interactiveshell.py", line 3508, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-4-3a9180dcbab0>", line 13, in <module>
    df = df.select(pl.col("event_time").dt.round("5m"))
  File "/usr/local/Caskroom/miniconda/base/envs/polars tutorial/lib/python3.10/site-packages/polars/dataframe/frame.py", line 7700, in select
    return self.lazy().select(*exprs, **named_exprs).collect(eager=True)
  File "/usr/local/Caskroom/miniconda/base/envs/polars tutorial/lib/python3.10/site-packages/polars/utils/deprecation.py", line 95, in wrapper
    return function(*args, **kwargs)
  File "/usr/local/Caskroom/miniconda/base/envs/polars tutorial/lib/python3.10/site-packages/polars/lazyframe/frame.py", line 1703, in collect
    return wrap_df(ldf.collect())
exceptions.ComputeError: datetime '2022-11-06 01:00:00' is ambiguous in time zone 'America/New_York'. Please use `ambiguous` to tell how it should be localized. If you got here from a function which doesn't have a `ambiguous` argument, please open an issue at https://github.com/pola-rs/polars/issues.
```

### Issue description

At that exact moment its daylight savings time:

https://www.freep.com/story/news/local/michigan/2022/11/02/daylight-saving-time/69612849007/

### Expected behavior

Round not crashing

### Installed versions

<details>

```
--------Version info---------
Polars:              0.19.3
Index type:          UInt32
Platform:            macOS-13.5.2-x86_64-i386-64bit
Python:              3.10.12 | packaged by conda-forge | (main, Jun 23 2023, 22:39:40) [Clang 15.0.7 ]
----Optional dependencies----
adbc_driver_sqlite:  <not installed>
cloudpickle:         <not installed>
connectorx:          <not installed>
deltalake:           <not installed>
fsspec:              <not installed>
gevent:              <not installed>
matplotlib:          3.7.2
numpy:               1.25.2
pandas:              2.0.3
pyarrow:             12.0.1
pydantic:            <not installed>
sqlalchemy:          <not installed>
xlsx2csv:            0.8.1
xlsxwriter:          <not installed>
```

</details>

**Comment by MarcoGorelli** [comment]
Thanks for the report, this probably needs an `ambiguous` argument too
