### ISSUE TITLE
Arithmetic operations involving decimal columns in Polars may panic, even when using release mode

### ISSUE THREAD

**Issue by joe-stifler** [pola-rs/polars#11333]
### Checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://crates.io/crates/polars) of Polars.

### Reproducible example

```rust
use polars::prelude::*;

fn to_decimal_series(data: &[i128]) -> Series {
    Int128Chunked::from_vec("", data.to_vec())
        .into_decimal_unchecked(Some(38), 0)
        .into_series()
}

fn main() {
    let df = df!(
        "d_zero" => to_decimal_series(&[0]),
        "d_one" => to_decimal_series(&[1]),
        "d_ten" => to_decimal_series(&[10]),
        "d_hundred" => to_decimal_series(&[100]),
        "d_max" => to_decimal_series(&[10_i128.pow(38) - 1]),
        "d_min" => to_decimal_series(&[-(10_i128.pow(38) - 1)]),
    ).unwrap();

    // for consistency, this should yield an overflow error
    df.clone().lazy().select(&[col("d_max") * col("d_ten")]).collect().unwrap();

    // for consistency, this should yield an overflow error
    df.clone().lazy().select(&[col("d_min") - col("d_one")]).collect().unwrap();

    // This panics (even in release mode) with:
    // 
    // ```text
    // thread 'main' panicked at 'data types don't match: ComputeError(ErrString("Decimal overflowed the allowed precision: 38"))',
    // /home/joe/.cargo/registry/src/index.crates.io-6f17d22bba15001f/polars-core-0.33.2/src/series/arithmetic/borrowed.rs:476:44
    // ```
    df.clone().lazy().select(&[col("d_max") * col("d_hundred")]).collect().unwrap();

    // This panics (even in release mode) with:
    // 
    // ```text
    // thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: ComputeError(ErrString("Decimal overflowed the allowed precision: 38"))',
    // /home/joe/.cargo/registry/src/index.crates.io-6f17d22bba15001f/polars-core-0.33.2/src/series/arithmetic/borrowed.rs:456:27
    // ```
    df.clone().lazy().select(&[col("d_max") + col("d_one")]).collect().unwrap();

    // This panics (even in release mode) with:
    //
    // ```text
    // thread 'main' panicked at 'attempt to divide by zero', /home/joe/.cargo/registry/src/index.crates.io-6f17d22bba15001f/ethnum-1.4.0/src/int/ops.rs:17:1
    // ```
    df.clone().lazy().select(&[col("d_one") / col("d_zero")]).collect().unwrap();
}
```

### Log output

```shell
Using just `df.clone().lazy().select(&[col("d_max") * col("d_hundred")]).collect().unwrap();` as an example, I get the following log:

joe@system76-pc:~/Documents/polars/polars-test$ POLARS_VERBOSE=1 cargo run --release
    Finished release [optimized] target(s) in 0.04s
     Running `target/release/polars-test`
thread 'main' panicked at 'data types don't match: ComputeError(ErrString("Decimal overflowed the allowed precision: 38"))', /home/joe/.cargo/registry/src/index.crates.io-6f17d22bba15001f/polars-core-0.33.2/src/series/arithmetic/borrowed.rs:476:44
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

### Issue description

Arithmetic operations between decimal columns in Polars may lead to panics even when running in release mode. Here's a breakdown:

* Addition: If overflow occurs, the code will trigger a panic.
* Subtraction: It appears to be resilient and does not typically panic or generate errors, even with overflowed results.
* Multiplication: For certain values, it may not panic when the result overflows, but for others, it may cause a panic.
* Division: An attempt to divide by zero will invariably lead to a panic.

The core issue is the absence of a safer alternative within Polars to handle these operations. Consequently, client code using Polars is also prone to panic, without the ability to check results. As a workaround, the [map_many](https://docs.rs/polars/latest/polars/prelude/enum.Expr.html#method.map_many) method can be used, manually introducing checks. However, this approach sidesteps Polars' built-in functionality and complicates the testing process, as `map_many` accepts a closure that cannot be directly compared for equality (e.g., using assert_eq!) if some struct encapsulates the Polars Expr with `map_many`.

### Expected behavior

Instead of triggering panics, consider returning specific error types for overflow and division by zero scenarios. Alternatively, introduce safer alternatives like using functions such as checked_div, checked_sub, checked_add, and checked_mul for performing arithmetic operations.

### Installed versions

<details>

polars = { version = "0.33.1", features = ["lazy", "dtype-decimal"]}

</details>

**Comment by kdn36** [comment]
With the recent work on Decimals, using 0.51.0, the panic's have been resolved.

Respective results do not look as expected, perhaps @orlp can weigh in on the triage.
```
[src/main.rs:27:5] &out = shape: (1, 1)
┌─────────────────────────────────┐
│ d_max                           │
│ ---                             │
│ decimal[*,0]                    │
╞═════════════════════════════════╡
│ -20847100762815390390123822295… │
└─────────────────────────────────┘
[src/main.rs:35:5] &out = shape: (1, 1)
┌─────────────────────────────────┐
│ d_min                           │
│ ---                             │
│ decimal[*,0]                    │
╞═════════════════════════════════╡
│ -10000000000000000000000000000… │
└─────────────────────────────────┘
[src/main.rs:48:5] &out = shape: (1, 1)
┌─────────────────────────────────┐
│ d_max                           │
│ ---                             │
│ decimal[*,0]                    │
╞═════════════════════════════════╡
│ 131811359292784559562136384478… │
└─────────────────────────────────┘
[src/main.rs:61:5] &out = shape: (1, 1)
┌─────────────────────────────────┐
│ d_max                           │
│ ---                             │
│ decimal[*,0]                    │
╞═════════════════════════════════╡
│ 100000000000000000000000000000… │
└─────────────────────────────────┘
[src/main.rs:73:5] &out = shape: (1, 1)
┌──────────────┐
│ d_one        │
│ ---          │
│ decimal[*,4] │
╞══════════════╡
│ null         │
└──────────────┘
```
