### ISSUE TITLE
Lazy schema for `group_by_dynamic` is incorrect

### ISSUE THREAD

**Issue by sarvothaman** [pola-rs/polars#11339]
### Checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pypi.org/project/polars/) of Polars.

### Reproducible example

Here is a reproducible example (Note the `include_boundaries=True`):
```python
from datetime import datetime
import polars as pl

lf = pl.LazyFrame(
    {
        "time": pl.datetime_range(
            start=datetime(2021, 12, 16),
            end=datetime(2021, 12, 16, 3),
            interval="30m",
            eager=True,
        ),
        "n": range(7),
    }
)
lf_uncollected_gpd = lf.group_by_dynamic(
    "time", every="1h", closed="right", include_boundaries=True
).agg(
    [
        pl.col("time").min().alias("time_min"),
        pl.col("time").max().alias("time_max"),
    ]
)
```
The below line succeeds:
```python
print(lf_uncollected_gpd.collect().with_columns(x=pl.col("_upper_boundary").dt.time()))
```
but the below line fails:
```python
print(lf_uncollected_gpd.with_columns(x=pl.col("_upper_boundary").dt.time()).collect())
```

### Log output

```shell
Error
Traceback (most recent call last):
  File "/some/path/test_polars_operations.py", line 28, in test_lazy_boundary_with_columns
    print(lf_uncollected_gpd.with_columns(x=pl.col("_upper_boundary").dt.time()).collect())
  File "/python/package/path/lib/python3.9/site-packages/polars/utils/deprecation.py", line 95, in wrapper
    return function(*args, **kwargs)
  File "/python/package/path/lib/python3.9/site-packages/polars/lazyframe/frame.py", line 1703, in collect
    return wrap_df(ldf.collect())
exceptions.ColumnNotFoundError: _upper_boundary

Error originated just after this operation:
AGGREGATE
	[col("time").min().alias("time_min"), col("time").max().alias("time_max")] BY [] FROM
  DF ["time", "n"]; PROJECT */2 COLUMNS; SELECTION: "None"
```

### Issue description

When using lazy frame, it seems like its not possible to operate on the `_upper_boundary`/`_lower_boundary` columns generated by `group_by_dynamic`. 

### Expected behavior

Operations on the boundary columns succeed

### Installed versions

<details>

```
--------Version info---------
Polars:              0.19.3
Index type:          UInt32
Platform:            macOS-13.5.2-arm64-arm-64bit
Python:              3.9.17 (main, Jul  5 2023, 15:35:09) 
[Clang 14.0.6 ]

----Optional dependencies----
adbc_driver_sqlite:  <not installed>
cloudpickle:         <not installed>
connectorx:          0.3.1
deltalake:           <not installed>
fsspec:              2022.3.0
gevent:              <not installed>
matplotlib:          <not installed>
numpy:               1.22.1
pandas:              1.3.4
pyarrow:             5.0.0
pydantic:            <not installed>
sqlalchemy:          1.3.22
xlsx2csv:            <not installed>
xlsxwriter:          1.4.5

```

</details>

**Comment by stinodego** [comment]
The lazy schema of `group_by_dynamic` is incorrect. I'll see if I can fix this.

**Comment by stinodego** [comment]
I added a test (skipped for now) for this issue:

https://github.com/pola-rs/polars/blob/c5f8aadc70ed4c5479cac7691d6d19574784d91e/py-polars/tests/unit/operations/test_group_by_dynamic.py#L913-L933

The issue seems to be in this function, but my brain is too fried right now to find the fix:

https://github.com/pola-rs/polars/blob/c5f8aadc70ed4c5479cac7691d6d19574784d91e/crates/polars-plan/src/logical_plan/builder.rs#L614
