### ISSUE TITLE
Misleading error message when glob-reading compressed CSV files

### ISSUE THREAD

**Issue by nkoep** [pola-rs/polars#11347]
### Checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pypi.org/project/polars/) of Polars.

### Reproducible example

```python
import pandas as pd
import polars as pl

[pd.DataFrame({"x": range(10)}).to_csv(f"/tmp/df{i}.csv.gz") for i in range(3)]
pl.read_csv("/tmp/df*.csv.gz")
```

### Log output

```shell
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/n.koep/.pyenv/versions/3.10.12/lib/python3.10/site-packages/polars/io/csv/functions.py", line 364, in read_csv
    df = pl.DataFrame._read_csv(
  File "/Users/n.koep/.pyenv/versions/3.10.12/lib/python3.10/site-packages/polars/dataframe/frame.py", line 733, in _read_csv
    scan = scan_csv(
  File "/Users/n.koep/.pyenv/versions/3.10.12/lib/python3.10/site-packages/polars/io/csv/functions.py", line 898, in scan_csv
    return pl.LazyFrame._scan_csv(
  File "/Users/n.koep/.pyenv/versions/3.10.12/lib/python3.10/site-packages/polars/lazyframe/frame.py", line 356, in _scan_csv
    self._ldf = PyLazyFrame.new_from_csv(
exceptions.ComputeError: error while reading /tmp/df0.csv.gz: cannot scan compressed csv; use `read_csv` for compressed data
```

### Issue description

Trying to read gzip-compressed CSV files via `pl.read_csv("*.csv.gz")` fails with a misleading error message. From the backtrace it seems that polars calls `scan_csv` under the hood which is known to fail for compressed CSV files. This results in a misleading error message telling the user to use `read_csv` which was already invoked in the first place.

### Expected behavior

Polars should either read each file via `read_csv` under the hood or make the error message more explicit.

### Installed versions

<details>

```
--------Version info---------
Polars:              0.19.3
Index type:          UInt32
Platform:            macOS-12.6.2-x86_64-i386-64bit
Python:              3.10.12 (main, Aug  3 2023, 11:45:21) [Clang 14.0.0 (clang-1400.0.29.202)]

----Optional dependencies----
adbc_driver_sqlite:  <not installed>
cloudpickle:         2.2.1
connectorx:          <not installed>
deltalake:           <not installed>
fsspec:              <not installed>
gevent:              <not installed>
matplotlib:          3.7.2
numpy:               1.25.2
pandas:              2.1.0
pyarrow:             13.0.0
pydantic:            <not installed>
sqlalchemy:          <not installed>
xlsx2csv:            <not installed>
xlsxwriter:          <not installed>
```

</details>

**Comment by kumar-abhishek** [comment]
I can confirm this error. The workaround I found was to iterate over all the files individually and then concat the individual dataframes into one, which was quite time consuming. 

Do we have a fix?

**Comment by Voultapher** [comment]
```py
pl.read_csv("/tmp/df*.csv.gz")
```

Works with Polars 1.36
