### ISSUE TITLE
Ambiguous time on slice extraction

### ISSUE THREAD

**Issue by tim-habitat** [pola-rs/polars#11379]
### Checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pypi.org/project/polars/) of Polars.

### Reproducible example

```python
>>> from datetime import datetime
>>> import polars as pl
>>> 
>>> # Set up first_indicative to be during daylight savings change.
>>> first_indicative = pl.DataFrame({"delivery_datetime": datetime(2023, 11, 5, 6, 30)}).with_columns(
...     pl.col("delivery_datetime").dt.replace_time_zone("UTC").dt.convert_time_zone("US/Central")
... )
>>> 
>>> # Duplicate just for simplicity.
>>> indicative_downsampled = first_indicative
>>> 
>>> # This doesn't produce an error:
>>> foo = (
...     indicative_downsampled.join(
...         first_indicative.select(first_indicative_delivery_datetime=pl.col("delivery_datetime")), how="cross"
...     )
...     .filter(pl.col("delivery_datetime") >= pl.col("first_indicative_delivery_datetime"))
...     .drop("first_indicative_delivery_datetime")
... )
>>> 
>>> # This produces an error:
>>> foo = indicative_downsampled.filter(pl.col("delivery_datetime") >= first_indicative["delivery_datetime"][0])
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/tim/.poetry/lib/python3.10/site-packages/polars/dataframe/frame.py", line 3966, in filter
    self.lazy().filter(predicate).collect(eager=True)  # type: ignore[arg-type]
  File "/Users/tim/.poetry/lib/python3.10/site-packages/polars/utils/deprecation.py", line 95, in wrapper
    return function(*args, **kwargs)
  File "/Users/tim/.poetry/lib/python3.10/site-packages/polars/lazyframe/frame.py", line 1711, in collect
    return wrap_df(ldf.collect())
exceptions.ArrowErrorException: InvalidArgumentError("datetime '2023-11-05 01:30:00' is ambiguous in time zone 'US/Central'. Please use `ambiguous` to tell how it should be localized.")
>>>  # this doesn't produce an error
>>> foo2 = indicative_downsampled.with_columns(comps=pl.col("delivery_datetime").slice(0)).filter(pl.col("delivery_datetime") >= pl.col("comps"))
>>> foo2
shape: (1, 2)
┌──────────────────────────┬──────────────────────────┐
│ delivery_datetime        ┆ comps                    │
│ ---                      ┆ ---                      │
│ datetime[μs, US/Central] ┆ datetime[μs, US/Central] │
╞══════════════════════════╪══════════════════════════╡
│ 2023-11-05 01:30:00 CDT  ┆ 2023-11-05 01:30:00 CDT  │
└──────────────────────────┴──────────────────────────┘
>>>first_indicative["delivery_datetime"][0]
datetime.datetime(2023, 11, 5, 1, 30, tzinfo=zoneinfo.ZoneInfo(key='US/Central'))
```

### Issue description

The issue is that when extract a row of a `datetime` dataframe at an ambiguous timezone, `polars` doesn't attach the `fold` attribute thus the timezone is ambigous.
However when in the dataframe, it is not i.e it knows it is in `CDT` and not `CST`. 
Based on whether which one it is, i believe it should attach the correct `fold` value, that would make it unambiguous.

Maybe for another issue but this too should not be `ambiguous`:
```python
>>> dt2 = datetime(2023, 11, 5, 1, 30, tzinfo=zoneinfo.ZoneInfo(key='US/Central'), fold=1)
>>> foo = indicative_downsampled.filter(pl.col("delivery_datetime") >= dt2)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/tim/.poetry/lib/python3.10/site-packages/polars/dataframe/frame.py", line 3966, in filter
    self.lazy().filter(predicate).collect(eager=True)  # type: ignore[arg-type]
  File "/Users/tim/.poetry/lib/python3.10/site-packages/polars/utils/deprecation.py", line 95, in wrapper
    return function(*args, **kwargs)
  File "/Users/tim/.poetry/lib/python3.10/site-packages/polars/lazyframe/frame.py", line 1711, in collect
    return wrap_df(ldf.collect())
exceptions.ArrowErrorException: InvalidArgumentError("datetime '2023-11-05 01:30:00' is ambiguous in time zone 'US/Central'. Please use `ambiguous` to tell how it should be localized.")
>>> dt2
datetime.datetime(2023, 11, 5, 1, 30, fold=1, tzinfo=zoneinfo.ZoneInfo(key='US/Central'))
```

### Expected behavior

Works as it does in the dataframe.

### Installed versions

<details>

```
>>> pl.show_versions()
--------Version info---------
Polars:              0.19.5
Index type:          UInt32
Platform:            macOS-13.6-x86_64-i386-64bit
Python:              3.10.13 (main, Aug 24 2023, 22:48:59) [Clang 14.0.3 (clang-1403.0.22.14.1)]

----Optional dependencies----
adbc_driver_sqlite:  <not installed>
cloudpickle:         <not installed>
connectorx:          0.3.1
deltalake:           <not installed>
fsspec:              <not installed>
gevent:              <not installed>
matplotlib:          3.7.0
numpy:               1.23.3
openpyxl:            3.0.10
pandas:              <not installed>
pyarrow:             10.0.1
pydantic:            <not installed>
pyiceberg:           <not installed>
pyxlsb:              <not installed>
sqlalchemy:          <not installed>
xlsx2csv:            <not installed>
xlsxwriter:          <not installed>
```

</details>

**Comment by MarcoGorelli** [comment]
thanks @tim-habitat for the report, agree that this is a bug, the `fold` attribute should be respected
```python
In [17]: df = pl.DataFrame({'ts': pl.datetime_range(date(2020, 10, 25), datetime(2020, 10, 25, 2), '1h', time_zone='Europe
    ...: /London', eager=True)})

In [18]: df['ts'][1].fold
Out[18]: 0

In [19]: df['ts'][2].fold
Out[19]: 1
```
