### ISSUE TITLE
pl.scan_parquet panics on S3 URL with "`async fn` resumed after completion"

### ISSUE THREAD

**Issue by nameexhaustion** [pola-rs/polars#11389]
### Checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pypi.org/project/polars/) of Polars.

### Reproducible example

Reading a parquet file containing a large metadata size from a cloud location (I tested on S3). E.g. the dataframe created by the following code:

```python
import polars as pl

pl.select(pl.lit(1).alias(20_000 * "A"))
```

This will cause `scan_parquet` to immediately fail even without collecting:
```python
lf = pl.scan_parquet(..., storage_options=dict(aws_region=...))
# pyo3_runtime.PanicException: `async fn` resumed after completion
```

### Log output

```shell
thread '<unnamed>' panicked at /home/ubuntu/git/polars/crates/polars-io/src/cloud/adaptors.rs:67:13:
`async fn` resumed after completion
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
Traceback (most recent call last):
  File "/home/ubuntu/git/polars/.env/x.py", line 6, in <module>
    lf = pl.scan_parquet(
         ^^^^^^^^^^^^^^^^
  File "/home/ubuntu/git/polars/py-polars/polars/io/parquet/functions.py", line 258, in scan_parquet
    return pl.LazyFrame._scan_parquet(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/git/polars/py-polars/polars/lazyframe/frame.py", line 427, in _scan_parquet
    self._ldf = PyLazyFrame.new_from_parquet(
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
pyo3_runtime.PanicException: `async fn` resumed after completion
```

```rust
thread '<unnamed>' panicked at /home/ubuntu/git/polars/crates/polars-io/src/cloud/adaptors.rs:67:13:
`async fn` resumed after completion
stack backtrace:
   0: rust_begin_unwind
             at /rustc/734a0d0aa0d5cab60f94f6d0c6a014dae12915f1/library/std/src/panicking.rs:617:5
   1: core::panicking::panic_fmt
             at /rustc/734a0d0aa0d5cab60f94f6d0c6a014dae12915f1/library/core/src/panicking.rs:67:14
   2: core::panicking::panic
             at /rustc/734a0d0aa0d5cab60f94f6d0c6a014dae12915f1/library/core/src/panicking.rs:117:5
   3: polars_io::cloud::adaptors::CloudReader::read_operation::{{closure}}::{{closure}}
             at ./crates/polars-io/src/cloud/adaptors.rs:67:13
   4: polars_io::cloud::adaptors::CloudReader::read_operation::{{closure}}
             at ./crates/polars-io/src/cloud/adaptors.rs:59:20
   5: futures_executor::local_pool::block_on::{{closure}}
             at /home/ubuntu/.cargo/registry/src/index.crates.io-6f17d22bba15001f/futures-executor-0.3.28/src/local_pool.rs:317:23
   6: futures_executor::local_pool::run_executor::{{closure}}
             at /home/ubuntu/.cargo/registry/src/index.crates.io-6f17d22bba15001f/futures-executor-0.3.28/src/local_pool.rs:90:37
   7: std::thread::local::LocalKey<T>::try_with
             at /rustc/734a0d0aa0d5cab60f94f6d0c6a014dae12915f1/library/std/src/thread/local.rs:270:16
   8: std::thread::local::LocalKey<T>::with
             at /rustc/734a0d0aa0d5cab60f94f6d0c6a014dae12915f1/library/std/src/thread/local.rs:246:9
   9: futures_executor::local_pool::run_executor
             at /home/ubuntu/.cargo/registry/src/index.crates.io-6f17d22bba15001f/futures-executor-0.3.28/src/local_pool.rs:86:5
  10: futures_executor::local_pool::block_on
             at /home/ubuntu/.cargo/registry/src/index.crates.io-6f17d22bba15001f/futures-executor-0.3.28/src/local_pool.rs:317:5
  11: <polars_io::cloud::adaptors::CloudReader as futures_io::if_std::AsyncRead>::poll_read
             at ./crates/polars-io/src/cloud/adaptors.rs:102:15
  12: <&mut T as futures_io::if_std::AsyncRead>::poll_read
             at /home/ubuntu/.cargo/registry/src/index.crates.io-6f17d22bba15001f/futures-io-0.3.28/src/lib.rs:307:17
  13: <futures_util::io::take::Take<R> as futures_io::if_std::AsyncRead>::poll_read
             at /home/ubuntu/.cargo/registry/src/index.crates.io-6f17d22bba15001f/futures-util-0.3.28/src/io/take.rs:97:24
  14: <&mut T as futures_io::if_std::AsyncRead>::poll_read
             at /home/ubuntu/.cargo/registry/src/index.crates.io-6f17d22bba15001f/futures-io-0.3.28/src/lib.rs:307:17
  15: futures_util::io::read_to_end::read_to_end_internal
             at /home/ubuntu/.cargo/registry/src/index.crates.io-6f17d22bba15001f/futures-util-0.3.28/src/io/read_to_end.rs:67:22
  16: <futures_util::io::read_to_end::ReadToEnd<A> as core::future::future::Future>::poll
             at /home/ubuntu/.cargo/registry/src/index.crates.io-6f17d22bba15001f/futures-util-0.3.28/src/io/read_to_end.rs:89:9
  17: parquet2::read::stream::read_metadata::{{closure}}
             at /home/ubuntu/.cargo/registry/src/index.crates.io-6f17d22bba15001f/parquet2-0.17.2/src/read/stream.rs:78:14
  18: nano_arrow::io::parquet::read::read_metadata_async::{{closure}}
             at ./crates/nano-arrow/src/io/parquet/read/mod.rs:65:37
  19: polars_io::parquet::async_impl::ParquetObjectStore::fetch_metadata::{{closure}}
             at ./crates/polars-io/src/parquet/async_impl.rs:81:14
  20: polars_io::parquet::async_impl::ParquetObjectStore::get_metadata::{{closure}}
             at ./crates/polars-io/src/parquet/async_impl.rs:89:56
  21: polars_io::parquet::async_impl::ParquetObjectStore::schema::{{closure}}
             at ./crates/polars-io/src/parquet/async_impl.rs:60:44
  22: polars_io::parquet::read::ParquetAsyncReader::schema::{{closure}}
             at ./crates/polars-io/src/parquet/read.rs:276:30
  23: polars_io::parquet::read::ParquetAsyncReader::file_info::{{closure}}
             at ./crates/polars-io/src/parquet/read.rs:270:38
  24: <core::pin::Pin<P> as core::future::future::Future>::poll
             at /rustc/734a0d0aa0d5cab60f94f6d0c6a014dae12915f1/library/core/src/future/future.rs:125:9
  25: tokio::runtime::scheduler::current_thread::CoreGuard::block_on::{{closure}}::{{closure}}::{{closure}}
             at /home/ubuntu/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.32.0/src/runtime/scheduler/current_thread/mod.rs:665:57
  26: tokio::runtime::coop::with_budget
             at /home/ubuntu/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.32.0/src/runtime/coop.rs:107:5
  27: tokio::runtime::coop::budget
             at /home/ubuntu/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.32.0/src/runtime/coop.rs:73:5
  28: tokio::runtime::scheduler::current_thread::CoreGuard::block_on::{{closure}}::{{closure}}
             at /home/ubuntu/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.32.0/src/runtime/scheduler/current_thread/mod.rs:665:25
  29: tokio::runtime::scheduler::current_thread::Context::enter
             at /home/ubuntu/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.32.0/src/runtime/scheduler/current_thread/mod.rs:410:19
  30: tokio::runtime::scheduler::current_thread::CoreGuard::block_on::{{closure}}
             at /home/ubuntu/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.32.0/src/runtime/scheduler/current_thread/mod.rs:664:36
  31: tokio::runtime::scheduler::current_thread::CoreGuard::enter::{{closure}}
             at /home/ubuntu/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.32.0/src/runtime/scheduler/current_thread/mod.rs:743:68
  32: tokio::runtime::context::scoped::Scoped<T>::set
             at /home/ubuntu/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.32.0/src/runtime/context/scoped.rs:40:9
  33: tokio::runtime::context::set_scheduler::{{closure}}
             at /home/ubuntu/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.32.0/src/runtime/context.rs:176:26
  34: std::thread::local::LocalKey<T>::try_with
             at /rustc/734a0d0aa0d5cab60f94f6d0c6a014dae12915f1/library/std/src/thread/local.rs:270:16
  35: std::thread::local::LocalKey<T>::with
             at /rustc/734a0d0aa0d5cab60f94f6d0c6a014dae12915f1/library/std/src/thread/local.rs:246:9
  36: tokio::runtime::context::set_scheduler
             at /home/ubuntu/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.32.0/src/runtime/context.rs:176:9
  37: tokio::runtime::scheduler::current_thread::CoreGuard::enter
             at /home/ubuntu/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.32.0/src/runtime/scheduler/current_thread/mod.rs:743:27
  38: tokio::runtime::scheduler::current_thread::CoreGuard::block_on
             at /home/ubuntu/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.32.0/src/runtime/scheduler/current_thread/mod.rs:652:19
  39: tokio::runtime::scheduler::current_thread::CurrentThread::block_on::{{closure}}
             at /home/ubuntu/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.32.0/src/runtime/scheduler/current_thread/mod.rs:175:28
  40: tokio::runtime::context::runtime::enter_runtime
             at /home/ubuntu/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.32.0/src/runtime/context/runtime.rs:65:16
  41: tokio::runtime::scheduler::current_thread::CurrentThread::block_on
             at /home/ubuntu/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.32.0/src/runtime/scheduler/current_thread/mod.rs:167:9
  42: tokio::runtime::runtime::Runtime::block_on
             at /home/ubuntu/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.32.0/src/runtime/runtime.rs:347:47
  43: polars_io::parquet::read::ParquetAsyncReader::file_info
             at ./crates/polars-io/src/parquet/read.rs:272:9
  44: polars_plan::logical_plan::builder::LogicalPlanBuilder::scan_parquet
             at ./crates/polars-plan/src/logical_plan/builder.rs:143:17
  45: <polars_lazy::scan::parquet::LazyParquetReader as polars_lazy::scan::file_list_reader::LazyFileListReader>::finish_no_glob
             at ./crates/polars-lazy/src/scan/parquet.rs:55:33
  46: polars_lazy::scan::file_list_reader::LazyFileListReader::finish
             at ./crates/polars-lazy/src/scan/file_list_reader.rs:69:13
  47: polars_lazy::scan::parquet::<impl polars_lazy::frame::LazyFrame>::scan_parquet
             at ./crates/polars-lazy/src/scan/parquet.rs:113:9
  48: polars::lazyframe::PyLazyFrame::new_from_parquet
             at ./py-polars/src/lazyframe.rs:278:18
  49: polars::lazyframe::_::<impl polars::lazyframe::PyLazyFrame>::__pymethod_new_from_parquet__
             at ./py-polars/src/lazyframe.rs:55:1
  50: pyo3::impl_::trampoline::cfunction_with_keywords::{{closure}}
             at /home/ubuntu/.cargo/registry/src/index.crates.io-6f17d22bba15001f/pyo3-0.19.2/src/impl_/trampoline.rs:41:29
  51: pyo3::impl_::trampoline::trampoline::{{closure}}
             at /home/ubuntu/.cargo/registry/src/index.crates.io-6f17d22bba15001f/pyo3-0.19.2/src/impl_/trampoline.rs:181:54
  52: std::panicking::try::do_call
             at /rustc/734a0d0aa0d5cab60f94f6d0c6a014dae12915f1/library/std/src/panicking.rs:524:40
  53: __rust_try
  54: std::panicking::try
             at /rustc/734a0d0aa0d5cab60f94f6d0c6a014dae12915f1/library/std/src/panicking.rs:488:19
  55: std::panic::catch_unwind
             at /rustc/734a0d0aa0d5cab60f94f6d0c6a014dae12915f1/library/std/src/panic.rs:142:14
  56: pyo3::impl_::trampoline::trampoline
             at /home/ubuntu/.cargo/registry/src/index.crates.io-6f17d22bba15001f/pyo3-0.19.2/src/impl_/trampoline.rs:181:9
  57: pyo3::impl_::trampoline::cfunction_with_keywords
             at /home/ubuntu/.cargo/registry/src/index.crates.io-6f17d22bba15001f/pyo3-0.19.2/src/impl_/trampoline.rs:41:13
  58: polars::lazyframe::_::_::__INVENTORY::trampoline
             at ./py-polars/src/lazyframe.rs:55:1
  59: cfunction_call
             at /tmp/python-build.20230814231932.12053/Python-3.11.4/Objects/methodobject.c:542:18
  60: _PyObject_MakeTpCall
             at /tmp/python-build.20230814231932.12053/Python-3.11.4/Objects/call.c:214:18
  61: _PyEval_EvalFrameDefault
             at /tmp/python-build.20230814231932.12053/Python-3.11.4/Python/ceval.c:4774:23
  62: _PyEval_EvalFrame
             at /tmp/python-build.20230814231932.12053/Python-3.11.4/./Include/internal/pycore_ceval.h:73:16
  63: _PyEval_Vector
             at /tmp/python-build.20230814231932.12053/Python-3.11.4/Python/ceval.c:6439:24
  64: PyEval_EvalCode
             at /tmp/python-build.20230814231932.12053/Python-3.11.4/Python/ceval.c:1154:21
  65: run_eval_code_obj
             at /tmp/python-build.20230814231932.12053/Python-3.11.4/Python/pythonrun.c:1714:9
  66: run_mod
             at /tmp/python-build.20230814231932.12053/Python-3.11.4/Python/pythonrun.c:1735:19
  67: pyrun_file
             at /tmp/python-build.20230814231932.12053/Python-3.11.4/Python/pythonrun.c:1630:15
  68: _PyRun_SimpleFileObject
             at /tmp/python-build.20230814231932.12053/Python-3.11.4/Python/pythonrun.c:440:13
  69: _PyRun_AnyFileObject
             at /tmp/python-build.20230814231932.12053/Python-3.11.4/Python/pythonrun.c:79:15
  70: pymain_run_file_obj
             at /tmp/python-build.20230814231932.12053/Python-3.11.4/Modules/main.c:360:15
  71: pymain_run_file
             at /tmp/python-build.20230814231932.12053/Python-3.11.4/Modules/main.c:379:15
  72: pymain_run_python
             at /tmp/python-build.20230814231932.12053/Python-3.11.4/Modules/main.c:601:21
  73: Py_RunMain
             at /tmp/python-build.20230814231932.12053/Python-3.11.4/Modules/main.c:680:5
  74: pymain_main
             at /tmp/python-build.20230814231932.12053/Python-3.11.4/Modules/main.c:710:12
  75: Py_BytesMain
             at /tmp/python-build.20230814231932.12053/Python-3.11.4/Modules/main.c:734:12
  76: __libc_start_main
  77: _start
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```

### Issue description

Appears to be due to `read_operation` in `CloudReader`, which expects to only be called to read the data once, so it caches the future:

```rust
   4: polars_io::cloud::adaptors::CloudReader::read_operation::{{closure}}
             at ./crates/polars-io/src/cloud/adaptors.rs:59:20

// If we already have a future just poll it.
        if let Some(fut) = self.active.lock().await.as_mut() {
            return Future::poll(fut.as_mut(), cx);
        }
```

So anything that reads from it more than once will cause an error as it will poll the cached future that has already completed, e.g. in `scan_parquet` because `parquet2` will read multiple times from the reader it is passed if the size of the parquet metadata exceeds some threshold:

```rust
  17: parquet2::read::stream::read_metadata::{{closure}}
             at /home/ubuntu/.cargo/registry/src/index.crates.io-6f17d22bba15001f/parquet2-0.17.2/src/read/stream.rs:78:14

// the end of file read by default is not long enough, read again including the metadata.
        reader.seek(SeekFrom::End(-(footer_len as i64))).await?;

        buffer.clear();
        buffer.try_reserve(footer_len as usize)?;
        reader
            .take(footer_len as u64)
            .read_to_end(&mut buffer)
            .await?;
```

### Expected behavior

`scan_parquet` from a cloud location successfully creates the `LazyFrame`

### Installed versions

Compiled from `main` at `e30aac670`

```
--------Version info---------
Polars:              0.19.5
Index type:          UInt32
Platform:            Linux-5.15.90.1-microsoft-standard-WSL2-x86_64-with-glibc2.31
Python:              3.11.4 (main, Aug 14 2023, 23:21:01) [GCC 9.4.0]

----Optional dependencies----
adbc_driver_sqlite:  0.7.0
cloudpickle:         2.2.1
connectorx:          0.3.2
deltalake:           0.10.1
fsspec:              2023.9.2
gevent:              23.9.1
matplotlib:          3.8.0
numpy:               1.26.0
openpyxl:            3.1.2
pandas:              2.1.1
pyarrow:             13.0.0
pydantic:            2.3.0
pyiceberg:           0.5.0
pyxlsb:              1.0.10
sqlalchemy:          2.0.21
xlsx2csv:            0.8.1
xlsxwriter:          3.1.5
```

</details>

**Comment by zippeurfou** [comment]
I confirm I have the same issue.
