### ISSUE TITLE
object_store error when using Azure Key; works with sas token

### ISSUE THREAD

**Issue by deanm0000** [pola-rs/polars#11392]
### Checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pypi.org/project/polars/) of Polars.

### Reproducible example

```python
df=pl.scan_parquet("abfs://container/somefile.parquet", storage_options={
    'azure_storage_account_name': 'ssp',
    'azure_storage_account_key': '8Myz7ZysHQ',
})
```

The credentials I listed here are truncated so they won't validate to anything but the error is before it validates so it shouldn't matter for the purpose of the bug.

The error is:
```
thread '<unnamed>' panicked at /root/.cargo/registry/src/index.crates.io-6f17d22bba15001f/object_store-0.7.0/src/azure/credential.rs:189:56:
called `Result::unwrap()` on an `Err` value: InvalidPadding
```

### Log output

<details>

```
thread '<unnamed>' panicked at /root/.cargo/registry/src/index.crates.io-6f17d22bba15001f/object_store-0.7.0/src/azure/credential.rs:189:56:
called `Result::unwrap()` on an `Err` value: InvalidPadding
stack backtrace:
   0:     0x7f477308a5c5 - <unknown>
   1:     0x7f4770e9038c - <unknown>
   2:     0x7f4773050efd - <unknown>
   3:     0x7f477308c4ae - <unknown>
   4:     0x7f477308ba8f - <unknown>
   5:     0x7f477308cbde - <unknown>
   6:     0x7f477308c662 - <unknown>
   7:     0x7f477308c5c6 - <unknown>
   8:     0x7f477308c5b1 - <unknown>
   9:     0x7f47700de622 - <unknown>
  10:     0x7f47700dea99 - <unknown>
  11:     0x7f47712eef3f - <unknown>
  12:     0x7f47713a337d - <unknown>
  13:     0x7f47713a2a5a - <unknown>
  14:     0x7f47713a281c - <unknown>
  15:     0x7f47713ab015 - <unknown>
  16:     0x7f47721bae79 - <unknown>
  17:     0x7f47721b6c73 - <unknown>
  18:     0x7f47721d7e90 - <unknown>
  19:     0x7f4772502637 - <unknown>
  20:     0x7f4770c92b70 - <unknown>
  21:     0x7f4770c9cb63 - <unknown>
  22:     0x7f47706bbab6 - <unknown>
  23:     0x7f4770d51631 - <unknown>
  24:     0x55d1af57899e - <unknown>
  25:     0x55d1af56f4ab - _PyObject_MakeTpCall
  26:     0x55d1af568683 - _PyEval_EvalFrameDefault
  27:     0x55d1af586c31 - <unknown>
  28:     0x55d1af562adf - _PyEval_EvalFrameDefault
  29:     0x55d1af5791ec - _PyFunction_Vectorcall
  30:     0x55d1af562adf - _PyEval_EvalFrameDefault
  31:     0x55d1af55ded6 - <unknown>
  32:     0x55d1af654366 - PyEval_EvalCode
  33:     0x55d1af65a04d - <unknown>
  34:     0x55d1af579449 - <unknown>
  35:     0x55d1af561785 - _PyEval_EvalFrameDefault
  36:     0x55d1af596150 - <unknown>
  37:     0x55d1af563923 - _PyEval_EvalFrameDefault
  38:     0x55d1af596150 - <unknown>
  39:     0x55d1af563923 - _PyEval_EvalFrameDefault
  40:     0x55d1af596150 - <unknown>
  41:     0x55d1af675ecf - <unknown>
  42:     0x55d1af58471a - <unknown>
  43:     0x55d1af5618cb - _PyEval_EvalFrameDefault
  44:     0x55d1af5791ec - _PyFunction_Vectorcall
  45:     0x55d1af561785 - _PyEval_EvalFrameDefault
  46:     0x55d1af5791ec - _PyFunction_Vectorcall
  47:     0x55d1af5618cb - _PyEval_EvalFrameDefault
  48:     0x55d1af586c31 - <unknown>
  49:     0x55d1af5878e2 - PyObject_Call
  50:     0x55d1af563af0 - _PyEval_EvalFrameDefault
  51:     0x55d1af5791ec - _PyFunction_Vectorcall
  52:     0x55d1af5878e2 - PyObject_Call
  53:     0x55d1af563af0 - _PyEval_EvalFrameDefault
  54:     0x55d1af586c31 - <unknown>
  55:     0x55d1af562adf - _PyEval_EvalFrameDefault
  56:     0x55d1af596150 - <unknown>
  57:     0x55d1af563923 - _PyEval_EvalFrameDefault
  58:     0x55d1af596150 - <unknown>
  59:     0x55d1af563923 - _PyEval_EvalFrameDefault
  60:     0x55d1af596150 - <unknown>
  61:     0x55d1af563923 - _PyEval_EvalFrameDefault
  62:     0x55d1af596150 - <unknown>
  63:     0x55d1af563923 - _PyEval_EvalFrameDefault
  64:     0x55d1af596150 - <unknown>
  65:     0x7f479c62962e - <unknown>
  66:     0x7f479c62af6b - <unknown>
  67:     0x55d1af5783a4 - <unknown>
  68:     0x55d1af655f55 - <unknown>
  69:     0x55d1af706ab2 - <unknown>
  70:     0x55d1af56c3bb - <unknown>
  71:     0x55d1af563af0 - _PyEval_EvalFrameDefault
  72:     0x55d1af5791ec - _PyFunction_Vectorcall
  73:     0x55d1af5618cb - _PyEval_EvalFrameDefault
  74:     0x55d1af5791ec - _PyFunction_Vectorcall
  75:     0x55d1af5618cb - _PyEval_EvalFrameDefault
  76:     0x55d1af5791ec - _PyFunction_Vectorcall
  77:     0x55d1af5618cb - _PyEval_EvalFrameDefault
  78:     0x55d1af5791ec - _PyFunction_Vectorcall
  79:     0x55d1af5618cb - _PyEval_EvalFrameDefault
  80:     0x55d1af5791ec - _PyFunction_Vectorcall
  81:     0x55d1af5618cb - _PyEval_EvalFrameDefault
  82:     0x55d1af586c31 - <unknown>
  83:     0x55d1af567462 - _PyEval_EvalFrameDefault
  84:     0x55d1af55ded6 - <unknown>
  85:     0x55d1af654366 - PyEval_EvalCode
  86:     0x55d1af65a04d - <unknown>
  87:     0x55d1af579449 - <unknown>
  88:     0x55d1af561785 - _PyEval_EvalFrameDefault
  89:     0x55d1af5791ec - _PyFunction_Vectorcall
  90:     0x55d1af561785 - _PyEval_EvalFrameDefault
  91:     0x55d1af5791ec - _PyFunction_Vectorcall
  92:     0x55d1af672729 - <unknown>
  93:     0x55d1af671148 - Py_RunMain
  94:     0x55d1af64732d - Py_BytesMain
  95:     0x7f479d7f6d90 - <unknown>
  96:     0x7f479d7f6e40 - __libc_start_main
  97:     0x55d1af647225 - _start
  98:                0x0 - <unknown>
```

</details>

### Issue description

I tracked that back to [here](https://docs.rs/object_store/latest/src/object_store/azure/credential.rs.html)

```
fn generate_authorization(
    h: &HeaderMap,
    u: &Url,
    method: &Method,
    account: &str,
    key: &str,
) -> String {
    let str_to_sign = string_to_sign(h, u, method, account);
    let auth = hmac_sha256(BASE64_STANDARD.decode(key).unwrap(), str_to_sign);
    format!("SharedKey {}:{}", account, BASE64_STANDARD.encode(auth))
}
```

it looks like it's failing when it runs `BASE64_STANDARD.decode(key)`

Is there padding added somewhere before we get here?

In contrast, I can use a SAS token to open files, for example, this works (it won't work as a copy paste because those are fake credentials):

```python
df=pl.scan_parquet("abfs://container/somefile.parquet", storage_options={
    'azure_storage_account_name': 'ssp',
    'sas_token': 'sdflkj432908fslfkjf90wu08',
})
```
 
Using a SAS token doesn't require that `generate_authorization` to run so that's seemingly why it works. 

### Expected behavior

have it work when given a key not just a sas token.

### Installed versions

<details>

```
--------Version info---------
Polars:              0.19.5
Index type:          UInt32
Platform:            Linux-5.10.102.1-microsoft-standard-WSL2-x86_64-with-glibc2.35
Python:              3.10.6 (main, Mar 10 2023, 10:55:28) [GCC 11.3.0]

----Optional dependencies----
adbc_driver_sqlite:  <not installed>
cloudpickle:         2.2.1
connectorx:          0.3.1
deltalake:           <not installed>
fsspec:              2023.5.0
gevent:              <not installed>
matplotlib:          3.7.1
numpy:               1.24.3
openpyxl:            3.1.2
pandas:              2.0.1
pyarrow:             12.0.0
pydantic:            2.1.1
pyiceberg:           <not installed>
pyxlsb:              1.0.10
sqlalchemy:          2.0.13
xlsx2csv:            0.8.1
xlsxwriter:          3.1.3
```

</details>

**Comment by ritchie46** [comment]
Thanks. Could you create this issue upstream. Object-store is maintained by apache arrow, so they have a better understanding how to fix this than we do.

https://github.com/apache/arrow-rs

**Comment by deanm0000** [comment]
@ritchie46 I don't think the issue is on their end. I tested your [PR 11357](https://github.com/pola-rs/polars/pull/11357) and it worked. So I think the problem might be [here](https://github.com/pola-rs/polars/commit/7f8614eb0e2825b3887f8455397f6460c19d07e3) where the key is getting percent encoded.

**Comment by Bidek56** [comment]
I am getting Azure read error using this code: `df = pl.scan_parquet(parquet_path, storage_options=storage_options)`
But it works fine with Delta: `df = pl.scan_delta(delta_path, storage_options=storage_options)`

**Comment by ritchie46** [comment]
> @ritchie46 I don't think the issue is on their end. I tested your [PR 11357](https://github.com/pola-rs/polars/pull/11357) and it worked. So I think the problem might be [here](https://github.com/pola-rs/polars/commit/7f8614eb0e2825b3887f8455397f6460c19d07e3) where the key is getting percent encoded.

But that percent decodes the url, not the secret? Or am I mistaking something?

**Comment by deanm0000** [comment]
Tbh I'm just looking at the variable name in the diff here

`let key = percent_encoding::percent_decode_str(key)`

**Comment by ritchie46** [comment]
Yes, but the scope is important. :D

**Comment by deanm0000** [comment]
Well now I look silly. Like I said using sas tokens works so this can be safely thought of as low priority.

@Bidek the reason it works for delta is that it reads those files using a python library which uses fsspec while scan_parquet uses rust. The new feature is that it will use the rust object_store library instead of fsspec which gives rust readers more direct access. Anyways the format of storage_options when it goes to fsspec is different than when it goes to object_store. Use the appropriate link from [here](https://pola-rs.github.io/polars/py-polars/html/reference/api/polars.scan_parquet.html#polars.scan_parquet) to get the key pairs you're looking for.

@ritchie46 I wonder if it makes sense to have a new parameter name for when the intention is to use fsspec and another for object_store so that this confusion can't happen.

**Comment by deanm0000** [comment]
This is working with new version. Not sure what happened
