### ISSUE TITLE
.select() on LazyFrame panic after upgrading to 0.19.4

### ISSUE THREAD

**Issue by duvenagep** [pola-rs/polars#11396]
### Checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pypi.org/project/polars/) of Polars.

### Reproducible example

```python
import s3fs
import polars as pl
import pyarrow.dataset as ds
import pyarrow.parquet as pq
from datetime import timedelta, datetime, date
import uuid
import h3

THRESHOLD = timedelta(minutes=15)
COLUMNS_INAPPS = {
    "id": "string",
    "user_id": "string",
    "event_name": "string",
    "occurred_at": "timestamp",
    "latitude": "float",
    "longitude": "float",
    "session_id": "string",
    "af_h3_id": "string",
}

def get_h3_id(row):
    latitude = row["latitude"]
    longitude = row["longitude"]
    if latitude is None or longitude is None:
        return None
    else:
        return h3.geo_to_h3(latitude, longitude, 9)

fs = s3fs.S3FileSystem()
s3_endpoint = f"s3://polars-error/test/*"

myds = ds.dataset([y for y in fs.glob(s3_endpoint) if ".parquet" in y], filesystem=fs)
lazy_df = pl.scan_pyarrow_dataset(myds)

df = (
    lazy_df.with_columns(
        [
            pl.col("event_value")
                .str.json_path_match(r"$.latitude")
                .cast(pl.Float64, strict=False)
                .alias("latitude"),
            pl.col("event_value")
                .str.json_path_match(r"$.longitude")
                .cast(pl.Float64, strict=False)
                .alias("longitude"),
            pl.when((pl.col("event_value")=="").or_(pl.col("event_value").is_null()))
            .then(
                pl.col("event_time")
                .str.strptime(pl.Datetime, format="%Y-%m-%d %H:%M:%S")
                .cast(pl.Datetime)
            )
            .otherwise(
                pl.when(
                    pl.col("event_value")
                    .str.json_path_match(r"$.timestamp")
                    .str.strptime(pl.Datetime, format="%Y-%m-%dT%H:%M:%S%Z")
                    .cast(pl.Datetime)
                    < pl.col("event_time")
                    .str.strptime(pl.Datetime, format="%Y-%m-%d %H:%M:%S")
                    .cast(pl.Datetime)
                    .dt.offset_by("-1h")
                )
                .then(
                    pl.col("event_time")
                    .str.strptime(pl.Datetime, format="%Y-%m-%d %H:%M:%S")
                    .cast(pl.Datetime)
                )
                .otherwise(
                    pl.col("event_value")
                    .str.json_path_match(r"$.timestamp")
                    .str.strptime(pl.Datetime, format="%Y-%m-%dT%H:%M:%S%Z")
                    .cast(pl.Datetime)
                )
            )
                .alias("occurred_at")
        ]
    )
    .sort("occurred_at")
    .with_columns([
        pl.col("occurred_at").diff().gt(THRESHOLD)
        .fill_null(False).over("customer_user_id").alias("t_diff")
    ])
    .with_columns([
        pl.col("t_diff").cumsum().alias("session_id")
    ])
    .with_columns([
        pl.col("session_id").map_elements(lambda _: str(uuid.uuid4())).over(["customer_user_id","session_id"])
     ])
    .with_columns([
         pl.struct(["latitude","longitude"]).map_elements(lambda row: get_h3_id(row)).alias("af_h3_id")
     ])
    .rename({"customer_user_id": "user_id"})
    .select(list(COLUMNS_INAPPS.keys())) 
    .unique(subset=["id","user_id", "event_name","occurred_at"], maintain_order=True)
    .sort("occurred_at")
    .collect()
)

df.head()
```

### Log output

```shell
thread '<unnamed>' panicked at /Users/runner/work/polars/polars/crates/polars-lazy/src/physical_plan/expressions/column.rs:124:40:
range start index 100 out of range for slice of length 6
thread '<unnamed>' panicked at /Users/runner/work/polars/polars/crates/polars-lazy/src/physical_plan/expressions/column.rs:124:40:
range start index 100 out of range for slice of length 6
---------------------------------------------------------------------------
PanicException                            Traceback (most recent call last)
Cell In [4], line 38
     34 myds = ds.dataset([y for y in fs.glob(s3_endpoint) if ".parquet" in y], filesystem=fs)
     35 lazy_df = pl.scan_pyarrow_dataset(myds)
     37 df = (
---> 38     lazy_df.with_columns(
     39         [
     40             pl.col("event_value")
     41                 .str.json_path_match(r"$.latitude")
     42                 .cast(pl.Float64, strict=False)
     43                 .alias("latitude"),
     44             pl.col("event_value")
     45                 .str.json_path_match(r"$.longitude")
     46                 .cast(pl.Float64, strict=False)
     47                 .alias("longitude"),
     48             pl.when((pl.col("event_value")=="").or_(pl.col("event_value").is_null()))
     49             .then(
     50                 pl.col("event_time")
     51                 .str.strptime(pl.Datetime, format="%Y-%m-%d %H:%M:%S")
     52                 .cast(pl.Datetime)
     53             )
     54             .otherwise(
     55                 pl.when(
     56                     pl.col("event_value")
     57                     .str.json_path_match(r"$.timestamp")
     58                     .str.strptime(pl.Datetime, format="%Y-%m-%dT%H:%M:%S%Z")
     59                     .cast(pl.Datetime)
     60                     < pl.col("event_time")
     61                     .str.strptime(pl.Datetime, format="%Y-%m-%d %H:%M:%S")
     62                     .cast(pl.Datetime)
     63                     .dt.offset_by("-1h")
     64                 )
     65                 .then(
     66                     pl.col("event_time")
     67                     .str.strptime(pl.Datetime, format="%Y-%m-%d %H:%M:%S")
     68                     .cast(pl.Datetime)
     69                 )
     70                 .otherwise(
     71                     pl.col("event_value")
     72                     .str.json_path_match(r"$.timestamp")
     73                     .str.strptime(pl.Datetime, format="%Y-%m-%dT%H:%M:%S%Z")
     74                     .cast(pl.Datetime)
     75                 )
     76             )
     77                 .alias("occurred_at")
     78         ]
     79     )
     80     .sort("occurred_at")
     81     .with_columns([
     82         pl.col("occurred_at").diff().gt(THRESHOLD)
     83         .fill_null(False).over("customer_user_id").alias("t_diff")
     84     ])
     85     .with_columns([
     86         pl.col("t_diff").cumsum().alias("session_id")
     87     ])
     88     .with_columns([
     89         pl.col("session_id").map_elements(lambda _: str(uuid.uuid4())).over(["customer_user_id","session_id"])
     90      ])
     91     .with_columns([
     92          pl.struct(["latitude","longitude"]).map_elements(lambda row: get_h3_id(row)).alias("af_h3_id")
     93      ])
     94     .rename({"customer_user_id": "user_id"})
     95     .select(list(COLUMNS_INAPPS.keys()))
     96     .unique(subset=["id","user_id", "event_name","occurred_at"], maintain_order=True)
     97     .sort("occurred_at")
     98 #     .collect(comm_subexpr_elim=False)
     99     .collect()
    100 )
    102 df.head()

File ~/opt/anaconda3/lib/python3.9/site-packages/polars/utils/deprecation.py:95, in deprecate_renamed_parameter.<locals>.decorate.<locals>.wrapper(*args, **kwargs)
     90 @wraps(function)
     91 def wrapper(*args: P.args, **kwargs: P.kwargs) -> T:
     92     _rename_keyword_argument(
     93         old_name, new_name, kwargs, function.__name__, version
     94     )
---> 95     return function(*args, **kwargs)

File ~/opt/anaconda3/lib/python3.9/site-packages/polars/lazyframe/frame.py:1711, in LazyFrame.collect(self, type_coercion, predicate_pushdown, projection_pushdown, simplify_expression, no_optimization, slice_pushdown, comm_subplan_elim, comm_subexpr_elim, streaming, **kwargs)
   1698     comm_subplan_elim = False
   1700 ldf = self._ldf.optimization_toggle(
   1701     type_coercion,
   1702     predicate_pushdown,
   (...)
   1709     eager,
   1710 )
-> 1711 return wrap_df(ldf.collect())

PanicException: range start index 100 out of range for slice of length 6
```

### Issue description

Firstly apologies for the huge code snippet, this was the smallest I could get it while still reproducing the panic. Original code runs in a Airflow dag. This sample ran in a Jupyter Notebook

Before `polars 0.19.4` this above code worked normally for about 2 month. Then after upgrading yesterday I started getting this error. If I comment out the `.select(list(COLUMNS_INAPPS.keys()))` see below, then the error is resolved, however then I needlessly materialise 100 columns I don't need.

```python
    .rename({"customer_user_id": "user_id"})
    #.select(list(COLUMNS_INAPPS.keys())) 
    .unique(subset=["id","user_id", "event_name","occurred_at"], maintain_order=True)
    .sort("occurred_at")
    .collect()
```

After consulting the #python-polars discord channel, @ritchie46 suggested using the below snippet as a solution. 

`.collect(comm_subexpr_elim=False)`

While this did resolve my issue I am creating this repro to try and find the cause of the issue.

**Note:** I have checked and this error seems to still be present in `0.19.5`

### Expected behavior

When running the above code without  I would expect the lazy_df to materialise to
![Screenshot 2023-09-28 at 19 39 37](https://github.com/pola-rs/polars/assets/13404204/69918f00-9a23-4aca-baf1-ff1e97b3b72d)

### Installed versions

<details>

```
--------Version info---------
Polars:              0.19.4
Index type:          UInt32
Platform:            macOS-10.16-x86_64-i386-64bit
Python:              3.9.15 (main, Nov 24 2022, 08:29:02) 
[Clang 14.0.6 ]

----Optional dependencies----
adbc_driver_sqlite:  <not installed>
cloudpickle:         2.0.0
connectorx:          0.3.2
deltalake:           <not installed>
fsspec:              2022.11.0
gevent:              <not installed>
matplotlib:          3.6.2
numpy:               1.22.4
openpyxl:            3.0.10
pandas:              1.4.4
pyarrow:             13.0.0
pydantic:            <not installed>
pyiceberg:           <not installed>
pyxlsb:              <not installed>
sqlalchemy:          1.4.39
xlsx2csv:            0.8
xlsxwriter:          3.0.3
```

</details>

**Comment by cmdlineluser** [comment]
I managed to reduce it down a bit:
```python
import tempfile
import polars as pl
import pyarrow.dataset as ds

json = tempfile.NamedTemporaryFile()
parquet = tempfile.NamedTemporaryFile()

json.write((
b'{"id":0,"customer_user_id":1,"event_name":"my_event",'
b'"event_value":"{\\"latitude\\": 1.0, \\"longitude\\": 2.0, '
b'\\"timestamp\\": \\"2023-12-24T09:00:01Z\\"}","event_time":'
b'"2023-12-24 09:00:01","uuid":"{12345678-1234-5678-1234-567812345678}"}'
))
json.seek(0)

pl.scan_ndjson(json.name).collect().write_parquet(parquet.name)
parquet.seek(0)

event_time = (
   pl.col("event_time").str.to_datetime()
)

event_value = (
   pl.col("event_value")
     .str.json_path_match(r"$.timestamp")
     .str.to_datetime()
     .dt.replace_time_zone(None)
) 

(
   pl.scan_pyarrow_dataset(ds.dataset(parquet.name))
     .with_columns(occurred_at =
        pl.when(event_value < event_time.dt.offset_by("-1h"))
          .then(event_time)
    )
    .select("occurred_at")
    .collect()
)
```
It seems to be the double use of `event_time` which triggers it, if it's used once the error does not happen.

It also seems to be specific to `pl.scan_pyarrow_dataset` - creating the dataframe/lazyframe directly or using `.scan_parquet` doesn't seem to replicate the issue.

**Comment by duvenagep** [comment]
@cmdlineluser, Thanks for the help, my snippet was a bit big.
