### ISSUE TITLE
Panic on aggregation of categorical columns

### ISSUE THREAD

**Issue by Chaozfly** [pola-rs/polars#11408]
### Checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pypi.org/project/polars/) of Polars.

### Reproducible example

```python
import polars
df = pl.DataFrame(data={"groups": ["a", "b", "c"], "cats": ["a", "b", "c"], "amount": [1, 2, 3]},
                  schema={"groups": pl.Utf8, "cats": pl.Categorical, "amount": pl.Int8})

# panics
df.groupby("groups").agg(pl.col("cats").filter(pl.col("amount") == pl.col("amount").min()).first())

# no panic
df.with_columns(pl.col("cats").cast(pl.Utf8)).groupby("groups").agg(pl.col("cats").filter(pl.col("amount") == pl.col("amount").min()).first())

# no panic
df.groupby("groups").agg(pl.col("cats").filter(pl.col("amount") == 1).first())
```

### Log output

```shell
thread '<unnamed>' panicked at /home/runner/work/polars/polars/crates/polars-core/src/chunked_array/logical/categorical/merge.rs:52:13:
impl error
stack backtrace:
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
41.00s - Error processing internal command.
Traceback (most recent call last):
  File "/home/111111/.vscode-server/extensions/ms-python.python-2023.16.0/pythonFiles/lib/python/debugpy/_vendored/pydevd/pydevd.py", line 1783, in process_internal_commands
    int_cmd.do_it(self)
  File "/home/111111/.vscode-server/extensions/ms-python.python-2023.16.0/pythonFiles/lib/python/debugpy/_vendored/pydevd/_pydevd_bundle/pydevd_comm.py", line 528, in do_it
    self.method(dbg, *self.args, **self.kwargs)
  File "/home/111111/.vscode-server/extensions/ms-python.python-2023.16.0/pythonFiles/lib/python/debugpy/_vendored/pydevd/_pydevd_bundle/pydevd_comm.py", line 1166, in internal_evaluate_expression_json
    eval_result = pydevd_vars.evaluate_expression(py_db, frame, expression, is_exec=False)
  File "/home/111111/.vscode-server/extensions/ms-python.python-2023.16.0/pythonFiles/lib/python/debugpy/_vendored/pydevd/_pydevd_bundle/pydevd_vars.py", line 370, in new_func
    return _run_with_unblock_threads(original_func, py_db, curr_thread, frame, expression, is_exec)
  File "/home/111111/.vscode-server/extensions/ms-python.python-2023.16.0/pythonFiles/lib/python/debugpy/_vendored/pydevd/_pydevd_bundle/pydevd_vars.py", line 334, in _run_with_unblock_threads
    return _run_with_interrupt_thread(original_func, py_db, curr_thread, frame, expression, is_exec)
  File "/home/111111/.vscode-server/extensions/ms-python.python-2023.16.0/pythonFiles/lib/python/debugpy/_vendored/pydevd/_pydevd_bundle/pydevd_vars.py", line 305, in _run_with_interrupt_thread
    return original_func(py_db, frame, expression, is_exec)
  File "/home/111111/.vscode-server/extensions/ms-python.python-2023.16.0/pythonFiles/lib/python/debugpy/_vendored/pydevd/_pydevd_bundle/pydevd_vars.py", line 580, in evaluate_expression
    ret = eval_in_context(expression, updated_globals, updated_locals, py_db)
  File "/home/111111/.vscode-server/extensions/ms-python.python-2023.16.0/pythonFiles/lib/python/debugpy/_vendored/pydevd/_pydevd_bundle/pydevd_vars.py", line 268, in eval_in_context
    result = eval(compiled, global_vars, local_vars)
  File "<string>", line 1, in <module>
  File "/home/111111/.conda/envs/env/lib/python3.9/site-packages/polars/dataframe/group_by.py", line 241, in agg
    self.df.lazy()
  File "/home/111111/.conda/envs/env/lib/python3.9/site-packages/polars/utils/deprecation.py", line 95, in wrapper
    return function(*args, **kwargs)
  File "/home/111111/.conda/envs/env/lib/python3.9/site-packages/polars/lazyframe/frame.py", line 1711, in collect
    return wrap_df(ldf.collect())
pyo3_runtime.PanicException: impl error
```

### Issue description

I groupby and aggregate to get the first entry of a categorical column where the amount is equal to the minimal amount in that group (among other aggregations).

- The example worked fine in polars==0.16.12, now the code panics.
- Same result for lazy and eager execution

### Expected behavior

No panic.

### Installed versions

<details>

```
--------Version info---------
Polars:              0.19.5
Index type:          UInt32
Platform:            Linux-3.10.0-1160.92.1.el7.x86_64-x86_64-with-glibc2.17
Python:              3.9.13 | packaged by conda-forge | (main, May 27 2022, 16:58:50) 
[GCC 10.3.0]

----Optional dependencies----
adbc_driver_sqlite:  <not installed>
cloudpickle:         2.2.1
connectorx:          <not installed>
deltalake:           <not installed>
fsspec:              2023.9.2
gevent:              <not installed>
matplotlib:          3.8.0
numpy:               1.21.6
openpyxl:            <not installed>
pandas:              1.4.4
pyarrow:             12.0.0
pydantic:            <not installed>
pyiceberg:           <not installed>
pyxlsb:              <not installed>
sqlalchemy:          1.4.44
xlsx2csv:            <not installed>
xlsxwriter:          <not installed>
```
</details>

**Comment by mcrumiller** [comment]
This works in `0.19.3`, so it's fairly recent. I can't install 19.4 on this machine so haven't tested on that.

**Comment by cmdlineluser** [comment]
If it helps debugging: they work with an explicit StringCache:
```python
with pl.StringCache():
    df = pl.DataFrame(data={"groups": ["a", "b", "c"], "cats": ["a", "b", "c"], "amount": [1, 2, 3]},
                      schema={"groups": pl.Utf8, "cats": pl.Categorical, "amount": pl.Int8})

    # panics
    df.group_by("groups").agg(pl.col("cats").filter(pl.col("amount") == pl.col("amount").min()).first())

    # no panic
    df.with_columns(pl.col("cats").cast(pl.Utf8)).group_by("groups").agg(pl.col("cats").filter(pl.col("amount") == pl.col("amount").min()).first())

    # no panic
    df.group_by("groups").agg(pl.col("cats").filter(pl.col("amount") == 1).first())

# shape: (3, 2)
# ┌────────┬──────┐
# │ groups ┆ cats │
# │ ---    ┆ ---  │
# │ str    ┆ cat  │
# ╞════════╪══════╡
# │ b      ┆ b    │
# │ c      ┆ c    │
# │ a      ┆ a    │
# └────────┴──────┘
# shape: (3, 2)
# ┌────────┬──────┐
# │ groups ┆ cats │
# │ ---    ┆ ---  │
# │ str    ┆ str  │
# ╞════════╪══════╡
# │ c      ┆ c    │
# │ b      ┆ b    │
# │ a      ┆ a    │
# └────────┴──────┘
# shape: (3, 2)
# ┌────────┬──────┐
# │ groups ┆ cats │
# │ ---    ┆ ---  │
# │ str    ┆ cat  │
# ╞════════╪══════╡
# │ c      ┆ null │
# │ a      ┆ a    │
# │ b      ┆ null │
# └────────┴──────┘
```

**Comment by ritchie46** [comment]
Anybody know where this started failing?

**Comment by ritchie46** [comment]
> This works in `0.19.3`, so it's fairly recent. I can't install 19.4 on this machine so haven't tested on that.

It doesn't?

**Comment by mcrumiller** [comment]
You're right, not sure why I thought that. My bad.

**Comment by mcrumiller** [comment]
Does not panic in `0.18.5`, panics in `0.18.6`.
