### ISSUE TITLE
Unable to read SQL Table with _date array, via read_database: thread '<unnamed>' panicked at 'not implemented: _date',

### ISSUE THREAD

**Issue by Buedenbender** [pola-rs/polars#11400]
### Checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pypi.org/project/polars/) of Polars.

### Reproducible example

Create exemplary data in SQL (postgres)
```sql
create table test_polars (
		arr_date _date
);

insert into test_polars 
values
		(array ['2023-01-01'::date,'2023-03-01'::date])
;

select * from test_polars;
```

Try to read data with [read_database](https://pola-rs.github.io/polars/py-polars/html/reference/api/polars.read_database.html)

```python
import polars as pl

pl.read_database("select * FROM test_polars",url)
```

### Log output

```shell
thread '<unnamed>' panicked at 'not implemented: _date', /__w/connector-x/connector-x/connectorx/src/sources/postgres/typesystem.rs:108:22
stack backtrace:
   0: rust_begin_unwind
             at /rustc/eb26296b556cef10fb713a38f3d16b9886080f26/library/std/src/panicking.rs:593:5
   1: core::panicking::panic_fmt
             at /rustc/eb26296b556cef10fb713a38f3d16b9886080f26/library/core/src/panicking.rs:67:14
   2: <connectorx::sources::postgres::typesystem::PostgresTypeSystem as core::convert::From<&postgres_types::Type>>::from
   3: <alloc::vec::Vec<T> as alloc::vec::spec_from_iter::SpecFromIter<T,I>>::from_iter
   4: <connectorx::sources::postgres::PostgresSource<P,C> as connectorx::sources::Source>::fetch_metadata
   5: connectorx::dispatcher::Dispatcher<S,D,TP>::run
   6: connectorx::get_arrow2::get_arrow2
   7: connectorx::arrow2::write_arrow
   8: connectorx::read_sql::read_sql
   9: std::panicking::try
  10: connectorx::__pyo3_raw_read_sql
  11: <unknown>
  12: _PyEval_EvalFrameDefault
  13: _PyFunction_Vectorcall
  14: _PyEval_EvalFrameDefault
  15: _PyFunction_Vectorcall
  16: _PyEval_EvalFrameDefault
  17: _PyFunction_Vectorcall
  18: PyObject_Call
  19: _PyEval_EvalFrameDefault
  20: _PyFunction_Vectorcall
  21: _PyEval_EvalFrameDefault
  22: _PyFunction_Vectorcall
  23: _PyEval_EvalFrameDefault
  24: <unknown>
  25: PyEval_EvalCode
  26: <unknown>
  27: <unknown>
  28: <unknown>
  29: _PyRun_SimpleFileObject
  30: _PyRun_AnyFileObject
  31: Py_RunMain
  32: Py_BytesMain
  33: <unknown>
  34: __libc_start_main
  35: _start
```

### Issue description

I would like to query an SQL (Postgres) table that contains a _date columns (array of dates).
Not quite sure if this is the right place here or if this is better placed at connectorx

### Expected behavior

return a polars dataframe of the table 

### Installed versions

<details>

```
--------Version info---------
Polars:              0.19.5
Index type:          UInt32
Platform:            Linux-4.14.314-1684020202-x86_64-with-glibc2.35
Python:              3.10.6 (main, May 29 2023, 11:10:38) [GCC 11.3.0]

----Optional dependencies----
adbc_driver_sqlite:  <not installed>
cloudpickle:         2.2.1
connectorx:          0.3.2
deltalake:           <not installed>
fsspec:              2023.6.0
gevent:              23.7.0
matplotlib:          3.7.2
numpy:               1.23.5
openpyxl:            3.1.2
pandas:              2.0.3
pyarrow:             13.0.0
pydantic:            1.10.12
pyiceberg:           <not installed>
pyxlsb:              <not installed>
sqlalchemy:          1.4.49
xlsx2csv:            <not installed>
xlsxwriter:          <not installed>
```

</details>

**Comment by alexander-beedie** [comment]
Yup, this looks like one for `connectorx` rather than us (we just pass-through to them here).
