### ISSUE TITLE
`Expr.str.strptime` fails for %W and %U

### ISSUE THREAD

**Issue by dominictarro** [pola-rs/polars#11416]
### Checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pypi.org/project/polars/) of Polars.

### Reproducible example

```python
pl.DataFrame([]).with_columns(pl.lit("202122").str.strptime(pl.Date, format="%Y%W").alias("date"))
pl.DataFrame([]).with_columns(pl.lit("2021-22").str.strptime(pl.Date, format="%Y-%W").alias("date"))

pl.DataFrame([]).with_columns(pl.lit("202122").str.strptime(pl.Date, format="%Y%U").alias("date"))
pl.DataFrame([]).with_columns(pl.lit("2021-22").str.strptime(pl.Date, format="%Y-%U").alias("date"))
```

### Log output

```shell
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\dtarro\.virtualenvs\GoogleAnalyticsETL-rjp9XWgD\Lib\site-packages\polars\dataframe\frame.py", line 7903, in with_columns
    return self.lazy().with_columns(*exprs, **named_exprs).collect(eager=True)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\dtarro\.virtualenvs\GoogleAnalyticsETL-rjp9XWgD\Lib\site-packages\polars\utils\deprecation.py", line 95, in wrapper
    return function(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\dtarro\.virtualenvs\GoogleAnalyticsETL-rjp9XWgD\Lib\site-packages\polars\lazyframe\frame.py", line 1711, in collect
    return wrap_df(ldf.collect())
                   ^^^^^^^^^^^^^
exceptions.ComputeError: strict date parsing failed for 1 value(s) (1 unique): ["2021-22"]

You might want to try:
- setting `strict=False`
- setting `exact=False` (note: this is much slower!)
- checking whether the format provided ('%Y-%W') is correct
```

### Issue description

The week-of-year date formats, `%W` and `%U`, cause `Expr.str.strptime` to fail.

https://docs.rs/chrono/latest/chrono/format/strftime/index.html

### Expected behavior

Produces a date whose day-of-month is a Monday (`%W`) or a Sunday (`%U`).

```python
# May 31, 2021
pl.DataFrame([]).with_columns(pl.lit("202122").str.strptime(pl.Date, format="%Y%W").alias("date"))
```
```
shape: (1, 1)
┌────────────┐
│ date       │
│ ---        │
│ date       │
╞════════════╡
│ 2021-05-31 │
└────────────┘
```

### Installed versions

<details>

```
--------Version info---------
Polars:              0.19.5
Index type:          UInt32
Platform:            Windows-10-10.0.19045-SP0
Python:              3.11.0 (main, Oct 24 2022, 18:26:48) [MSC v.1933 64 bit (AMD64)]

----Optional dependencies----
adbc_driver_sqlite:  <not installed>
cloudpickle:         2.2.1
connectorx:          <not installed>
deltalake:           <not installed>
fsspec:              2023.9.2
gevent:              <not installed>
matplotlib:          <not installed>
numpy:               <not installed>
openpyxl:            <not installed>
pandas:              <not installed>
pyarrow:             <not installed>
pydantic:            1.10.13
pyiceberg:           <not installed>
pyxlsb:              <not installed>
sqlalchemy:          2.0.21
xlsx2csv:            <not installed>
xlsxwriter:          <not installed>
```

</details>

**Comment by MarcoGorelli** [comment]
thanks @dominictarro - you're going to have to specify the day of the week as well if you want to use `'%W'`:
```python
In [13]: pl.DataFrame([]).with_columns(pl.lit("202122Mon").str.strptime(pl.Date, format="%Y%W%a").alias("date"))
Out[13]:
shape: (1, 1)
┌────────────┐
│ date       │
│ ---        │
│ date       │
╞════════════╡
│ 2021-05-31 │
└────────────┘
```

**Comment by MarcoGorelli** [comment]
the error comes from chrono:
```Rust
(.venv) marcogorelli@DESKTOP-U8OKFP3:~/tmp$ cat src/main.rs
use chrono::NaiveDate;

fn main() {
    println!("res: {:?}", NaiveDate::parse_from_str("202211Mon", "%Y%W%a"));
    println!("res: {:?}", NaiveDate::parse_from_str("202211", "%Y%W"));
}
(.venv) marcogorelli@DESKTOP-U8OKFP3:~/tmp$ cargo run
    Finished dev [unoptimized + debuginfo] target(s) in 0.01s
     Running `target/debug/tmp`
res: Ok(2022-03-14)
res: Err(ParseError(NotEnough))
```

But I think they do have a PR open about defaulting on unspecified fields, so maybe this will change in the future
