### ISSUE TITLE
Selecting a subset of columns before collect() on lazyframe with hive_partitioning causes a panic

### ISSUE THREAD

**Issue by ddutt** [pola-rs/polars#11466]
### Checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pypi.org/project/polars/) of Polars.

### Reproducible example

Unfortunately cannot provide a complete working example as I have to provide a parquet written file with hive_partitioning first.

But once you have a hive-partitioned data with say columns colA, colB, colC, this fails:
```python
import polars as pl

lf = pl.scan_parquet('/path/to/parquet/**/*.parquet', hive_partitioning=True).select(['colA', 'colB']).collect()
```

But this works:

```python
lf = pl.scan_parquet('/path/to/parquet/**/*.parquet', hive_partitioning=True).collect()
```

### Log output

```shell
thread '<unnamed>' panicked at /home/runner/work/polars/polars/crates/polars-io/src/parquet/read_impl.rs:36:34:
index out of bounds: the len is 21 but the index is 22
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
thread '<unnamed>' panicked at /home/runner/work/polars/polars/crates/polars-io/src/parquet/read_impl.rs:36:thread '34<unnamed>:
' panicked at index out of bounds: the len is 21 but the index is 22/home/runner/work/polars/polars/crates/polars-io/src/parquet/read_impl.rs
:36:34:
index out of bounds: the len is 21 but the index is 22
thread '<unnamed>' panicked at /home/runner/work/polars/polars/crates/polars-io/src/parquet/read_impl.rs:36:34:
index out of bounds: the len is 21 but the index is 22
thread '<unnamed>' panicked at /home/runner/work/polars/polars/crates/polars-io/src/parquet/read_impl.rs:36:34:
index out of bounds: the len is 21 but the index is 22
thread '<unnamed>' panicked at thread '/home/runner/work/polars/polars/crates/polars-io/src/parquet/read_impl.rs<unnamed>:' panicked at 36/home/runner/work/polars/polars/crates/polars-io/src/parquet/read_impl.rs::3436:
:index out of bounds: the len is 21 but the index is 2234
:
index out of bounds: the len is 21 but the index is 22
thread '<unnamed>' panicked at /home/runner/work/polars/polars/crates/polars-io/src/parquet/read_impl.rs:36:34:
index out of bounds: the len is 21 but the index is 22
thread '<unnamed>' panicked at /home/runner/work/polars/polars/crates/polars-io/src/parquet/read_impl.rs:36:34:
index out of bounds: the len is 21 but the index is 22
thread '<unnamed>' panicked at /home/runner/work/polars/polars/crates/polars-io/src/parquet/read_impl.rs:36:34:
index out of bounds: the len is 21 but the index is 22
thread '<unnamed>' panicked at /home/runner/work/polars/polars/crates/polars-io/src/parquet/read_impl.rs:36:34:
index out of bounds: the len is 21 but the index is 22
thread '<unnamed>' panicked at /home/runner/work/polars/polars/crates/polars-io/src/parquet/read_impl.rs:36:34:
index out of bounds: the len is 21 but the index is 22
---------------------------------------------------------------------------
```

### Issue description

Nothing more to add

### Expected behavior

A dataframe with the selected columns without panic

### Installed versions

<details>
--------Version info---------
Polars:              0.19.6
Index type:          UInt32
Platform:            Linux-6.2.0-33-generic-x86_64-with-glibc2.35
Python:              3.11.3 (main, Apr 27 2023, 19:02:17) [GCC 11.3.0]

----Optional dependencies----
adbc_driver_sqlite:  <not installed>
cloudpickle:         <not installed>
connectorx:          <not installed>
deltalake:           <not installed>
fsspec:              <not installed>
gevent:              <not installed>
matplotlib:          <not installed>
numpy:               1.26.0
openpyxl:            <not installed>
pandas:              2.1.1
pyarrow:             13.0.0
pydantic:            1.10.13
pyiceberg:           <not installed>
pyxlsb:              <not installed>
sqlalchemy:          2.0.21
xlsx2csv:            <not installed>
xlsxwriter:          <not installed>
</details>

**Comment by cmdlineluser** [comment]
There is an existing test that a MRE could perhaps be based on: https://github.com/pola-rs/polars/blob/main/py-polars/tests/unit/io/test_hive.py

It seems it could be `projection_pushdown` related as it runs without error when disabled.
```python
import polars as pl
import pyarrow.parquet as pq

df = pl.DataFrame({"group": ["A", "A", "B", "C", "B"], "value": [1, 2, 3, 4, 5]})

pq.write_to_dataset(df.to_arrow(), root_path="tmp/", partition_cols=["group"])

(pl.scan_parquet("tmp/**/*.parquet", hive_partitioning=True)
   .select("group")
   .collect(projection_pushdown=False)
)

# shape: (5, 1)
# ┌───────┐
# │ group │
# │ ---   │
# │ str   │
# ╞═══════╡
# │ [     │
# │   "A" │
# │ ]     │
# │ [     │
# │   "A" │
# │ ]     │
# │ [     │
# │   "B" │
# │ ]     │
# │ [     │
# │   "B" │
# │ ]     │
# │ [     │
# │   "C" │
# │ ]     │
# └───────┘
```
