### ISSUE TITLE
Exception when sorting a Dataframe with a complex datatype involving dates.

### ISSUE THREAD

**Issue by aussetg** [pola-rs/polars#11513]
### Checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pypi.org/project/polars/) of Polars.

### Reproducible example

```python
# %%
import zoneinfo

import polars as pl
import datetime
from polars.datatypes import Utf8, List, Struct, Field, Datetime, Date

# %%
df = pl.DataFrame(
    [
        pl.Series(
            "date",
            [
                datetime.datetime(
                    2012, 7, 13, 7, 32, 55, 307000, tzinfo=zoneinfo.ZoneInfo(key="UTC")
                ),
                datetime.datetime(
                    2012, 8, 1, 13, 3, 21, 7000, tzinfo=zoneinfo.ZoneInfo(key="UTC")
                ),
                datetime.datetime(
                    2014,
                    11,
                    16,
                    18,
                    34,
                    52,
                    447000,
                    tzinfo=zoneinfo.ZoneInfo(key="UTC"),
                ),
                datetime.datetime(
                    2014, 10, 7, 22, 58, 59, 703000, tzinfo=zoneinfo.ZoneInfo(key="UTC")
                ),
                datetime.datetime(
                    2014,
                    10,
                    15,
                    20,
                    57,
                    26,
                    937000,
                    tzinfo=zoneinfo.ZoneInfo(key="UTC"),
                ),
            ],
            dtype=pl.Datetime(time_unit="us", time_zone="UTC"),
        ),
        pl.Series(
            "struct",
            [[], [], [], [], []],
            dtype=pl.List(
                Struct(
                    [
                        Field("a", Utf8),
                        Field("b", Utf8),
                        Field("c", List(Utf8)),
                        Field(
                            "d",
                            Datetime(time_unit="us", time_zone="UTC"),
                        ),
                        Field(
                            "e",
                            Struct(
                                [
                                    Field(
                                        "f",
                                        Struct([Field("g", Utf8)]),
                                    )
                                ]
                            ),
                        ),
                        Field(
                            "h",
                            Struct(
                                [
                                    Field(
                                        "i",
                                        List(
                                            Struct(
                                                [Field("j", Date)]
                                            )
                                        ),
                                    )
                                ]
                            ),
                        ),
                    ]
                )
            ),
        ),
    ]
)

# %%
df.sort('date')
```

### Log output

```shell
thread '<unnamed>' panicked at /home/runner/work/polars/polars/crates/nano-arrow/src/array/list/mod.rs:86:61:
called `Result::unwrap()` on an `Err` value: OutOfSpec("ListArray's child's DataType must match. However, the expected DataType is Struct([Field { name: \"a\", data_type: LargeUtf8, is_nullable: true, metadata: {} }, Field { name: \"b\", data_type: LargeUtf8, is_nullable: true, metadata: {} }, Field { name: \"c\", data_type: LargeList(Field { name: \"item\", data_type: LargeUtf8, is_nullable: true, metadata: {} }), is_nullable: true, metadata: {} }, Field { name: \"d\", data_type: Int64, is_nullable: true, metadata: {} }, Field { name: \"e\", data_type: Struct([Field { name: \"f\", data_type: Struct([Field { name: \"g\", data_type: LargeUtf8, is_nullable: true, metadata: {} }]), is_nullable: true, metadata: {} }]), is_nullable: true, metadata: {} }, Field { name: \"h\", data_type: Struct([Field { name: \"i\", data_type: LargeList(Field { name: \"item\", data_type: Struct([Field { name: \"j\", data_type: Int32, is_nullable: true, metadata: {} }]), is_nullable: true, metadata: {} }), is_nullable: true, metadata: {} }]), is_nullable: true, metadata: {} }]) while it got Struct([Field { name: \"a\", data_type: LargeUtf8, is_nullable: true, metadata: {} }, Field { name: \"b\", data_type: LargeUtf8, is_nullable: true, metadata: {} }, Field { name: \"c\", data_type: LargeList(Field { name: \"item\", data_type: LargeUtf8, is_nullable: true, metadata: {} }), is_nullable: true, metadata: {} }, Field { name: \"d\", data_type: Int64, is_nullable: true, metadata: {} }, Field { name: \"e\", data_type: Struct([Field { name: \"f\", data_type: Struct([Field { name: \"g\", data_type: LargeUtf8, is_nullable: true, metadata: {} }]), is_nullable: true, metadata: {} }]), is_nullable: true, metadata: {} }, Field { name: \"h\", data_type: Struct([Field { name: \"i\", data_type: LargeList(Field { name: \"item\", data_type: Struct([Field { name: \"j\", data_type: Date32, is_nullable: true, metadata: {} }]), is_nullable: true, metadata: {} }), is_nullable: true, metadata: {} }]), is_nullable: true, metadata: {} }]).")
stack backtrace:
   0: rust_begin_unwind
             at /rustc/734a0d0aa0d5cab60f94f6d0c6a014dae12915f1/library/std/src/panicking.rs:617:5
   1: core::panicking::panic_fmt
             at /rustc/734a0d0aa0d5cab60f94f6d0c6a014dae12915f1/library/core/src/panicking.rs:67:14
   2: core::result::unwrap_failed
             at /rustc/734a0d0aa0d5cab60f94f6d0c6a014dae12915f1/library/core/src/result.rs:1652:5
   3: polars_arrow::array::list::AnonymousBuilder::finish
   4: polars_core::chunked_array::ops::gather::gather_idx_array_unchecked
   5: polars_core::chunked_array::ops::gather::<impl polars_core::chunked_array::ops::ChunkTakeUnchecked<polars_core::chunked_array::ChunkedArray<polars_core::datatypes::UInt32Type>> for polars_core::chunked_array::ChunkedArray<T>>::take_unchecked
   6: polars_core::series::implementations::list::<impl polars_core::series::series_trait::SeriesTrait for polars_core::series::implementations::SeriesWrap<polars_core::chunked_array::ChunkedArray<polars_core::datatypes::ListType>>>::take_unchecked
   7: rayon::iter::plumbing::bridge_producer_consumer::helper
   8: <rayon_core::job::StackJob<L,F,R> as rayon_core::job::Job>::execute
   9: rayon_core::registry::WorkerThread::wait_until_cold
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/guillaume/.../.venv/lib64/python3.11/site-packages/polars/dataframe/frame.py", line 4320, in sort
    .collect(eager=True)
     ^^^^^^^^^^^^^^^^^^^
  File "/home/guillaume/.../.venv/lib64/python3.11/site-packages/polars/utils/deprecation.py", line 95, in wrapper
    return function(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/guillaume/.../.venv/lib64/python3.11/site-packages/polars/lazyframe/frame.py", line 1713, in collect
    return wrap_df(ldf.collect())
                   ^^^^^^^^^^^^^
pyo3_runtime.PanicException: called `Result::unwrap()` on an `Err` value: OutOfSpec("ListArray's child's DataType must match. However, the expected DataType is Struct([Field { name: \"a\", data_type: LargeUtf8, is_nullable: true, metadata: {} }, Field { name: \"b\", data_type: LargeUtf8, is_nullable: true, metadata: {} }, Field { name: \"c\", data_type: LargeList(Field { name: \"item\", data_type: LargeUtf8, is_nullable: true, metadata: {} }), is_nullable: true, metadata: {} }, Field { name: \"d\", data_type: Int64, is_nullable: true, metadata: {} }, Field { name: \"e\", data_type: Struct([Field { name: \"f\", data_type: Struct([Field { name: \"g\", data_type: LargeUtf8, is_nullable: true, metadata: {} }]), is_nullable: true, metadata: {} }]), is_nullable: true, metadata: {} }, Field { name: \"h\", data_type: Struct([Field { name: \"i\", data_type: LargeList(Field { name: \"item\", data_type: Struct([Field { name: \"j\", data_type: Int32, is_nullable: true, metadata: {} }]), is_nullable: true, metadata: {} }), is_nullable: true, metadata: {} }]), is_nullable: true, metadata: {} }]) while it got Struct([Field { name: \"a\", data_type: LargeUtf8, is_nullable: true, metadata: {} }, Field { name: \"b\", data_type: LargeUtf8, is_nullable: true, metadata: {} }, Field { name: \"c\", data_type: LargeList(Field { name: \"item\", data_type: LargeUtf8, is_nullable: true, metadata: {} }), is_nullable: true, metadata: {} }, Field { name: \"d\", data_type: Int64, is_nullable: true, metadata: {} }, Field { name: \"e\", data_type: Struct([Field { name: \"f\", data_type: Struct([Field { name: \"g\", data_type: LargeUtf8, is_nullable: true, metadata: {} }]), is_nullable: true, metadata: {} }]), is_nullable: true, metadata: {} }, Field { name: \"h\", data_type: Struct([Field { name: \"i\", data_type: LargeList(Field { name: \"item\", data_type: Struct([Field { name: \"j\", data_type: Date32, is_nullable: true, metadata: {} }]), is_nullable: true, metadata: {} }), is_nullable: true, metadata: {} }]), is_nullable: true, metadata: {} }]).")

```

### Issue description

When sorting a DataFrame with a field being a complex datatype that comprises of a date, the schema seems to be invalid and Polars panick

### Expected behavior

On Polars<=0.19.3 the code works as expected.
Polars>=0.19.4 doesn't work.

### Installed versions

<details>

```
pl.show_versions()
--------Version info---------
Polars:              0.19.6
Index type:          UInt32
Platform:            Linux-6.5.5-200.fc38.x86_64-x86_64-with-glibc2.37
Python:              3.11.5 (main, Aug 28 2023, 00:00:00) [GCC 13.2.1 20230728 (Red Hat 13.2.1-1)]
----Optional dependencies----
adbc_driver_sqlite:  <not installed>
cloudpickle:         2.2.1
connectorx:          <not installed>
deltalake:           <not installed>
fsspec:              2023.9.2
gevent:              <not installed>
matplotlib:          3.8.0
numpy:               1.25.2
openpyxl:            <not installed>
pandas:              1.5.3
pyarrow:             13.0.0
pydantic:            1.10.10
pyiceberg:           <not installed>
pyxlsb:              <not installed>
sqlalchemy:          2.0.21
xlsx2csv:            <not installed>
xlsxwriter:          <not installed>
```

</details>

**Comment by aussetg** [comment]
The example struct can actually be simplified to:

```python
df = pl.DataFrame(
    [
        pl.Series(
            "date",
            [
                datetime.datetime(
                    2012, 7, 13, 7, 32, 55, 307000, tzinfo=zoneinfo.ZoneInfo(key="UTC")
                ),
                datetime.datetime(
                    2012, 8, 1, 13, 3, 21, 7000, tzinfo=zoneinfo.ZoneInfo(key="UTC")
                ),
                datetime.datetime(
                    2014,
                    11,
                    16,
                    18,
                    34,
                    52,
                    447000,
                    tzinfo=zoneinfo.ZoneInfo(key="UTC"),
                ),
                datetime.datetime(
                    2014, 10, 7, 22, 58, 59, 703000, tzinfo=zoneinfo.ZoneInfo(key="UTC")
                ),
                datetime.datetime(
                    2014,
                    10,
                    15,
                    20,
                    57,
                    26,
                    937000,
                    tzinfo=zoneinfo.ZoneInfo(key="UTC"),
                ),
            ],
            dtype=pl.Datetime(time_unit="us", time_zone="UTC"),
        ),
        pl.Series(
            "struct",
            [[], [], [], [], []],
            dtype=pl.List(
                Struct(
                    [
                        Field(
                            "field",
                            Struct(
                                [
                                    Field(
                                        "subfield",
                                        List(
                                            Struct(
                                                [Field("subsubfield", Date)]
                                            )
                                        ),
                                    )
                                ]
                            ),
                        ),
                    ]
                )
            ),
        ),
    ]
)
```

If you remove the `subfield` nesting it works.

**Comment by cmdlineluser** [comment]
Perhaps a simpler repro:
```python
import polars as pl

df = pl.DataFrame(
    {
       "date": ["foo"],
       "struct": [[]],
    }, 
    schema_overrides={
        "struct": pl.List(pl.Struct({"field": pl.Struct({"subfield": pl.List(pl.Struct({"subsubfield": pl.Date}))})}))
    }
)

df.sort("date")

# PanicException: called `Result::unwrap()` on an `Err` value: 
# OutOfSpec("ListArray's child's DataType must match. However, the expected DataType is 
# Struct([Field { name: \"field\", data_type: Struct([Field { name: \"subfield\", data_type: LargeList(Field { name: \"item\", data_type: Struct([Field { name: \"subsubfield\", data_type: Int32, is_nullable: true, metadata: {} }]), is_nullable: true, metadata: {} }), is_nullable: true, metadata: {} }]), is_nullable: true, metadata: {} }]) 
#
# while it got 
#
# Struct([Field { name: \"field\", data_type: Struct([Field { name: \"subfield\", data_type: LargeList(Field { name: \"item\", data_type: Struct([Field { name: \"subsubfield\", data_type: Date32, is_nullable: true, metadata: {} }]), is_nullable: true, metadata: {} }), is_nullable: true, metadata: {} }]), is_nullable: true, metadata: {} }]).")
```
The differerence seems to be:
```
Expected: Field { name: \"subsubfield\", data_type: Int32
Got: Field { name: \"subsubfield\", data_type: Date32
```

**Comment by cmdlineluser** [comment]
@jakubkovac I think so - doesn't seem to be specific to `.sort()`

```python
import polars as pl

df = pl.DataFrame(
    {
       "date": ["foo"],
       "struct": [[]],
    }, 
    schema_overrides={
        "struct": pl.List(pl.Struct({"field": pl.Struct({"subfield": pl.List(pl.Struct({"subsubfield": pl.Date}))})}))
    }
)

df.group_by("date").head(1)

# PanicException: called `Result::unwrap()` on an `Err` value: 
# ...
```

**Comment by aussetg** [comment]
Seems to happen whenever there is some reordering of the frame involved with deeply ~~weird~~ nested datatypes with dates. 
I can actually also make it happen on <=0.19.3 by exploding the "struct" column, and then doing a pl.when().then().otherwise() ( it complains about the dtypes being different with the same Date -> Int32 strange conversion as in my original error and in @jakubkovac 's error )
