### ISSUE TITLE
Uncaught PanicException from `scan_csv` when `new_columns` length doesn't equal file columns length

### ISSUE THREAD

**Issue by foster999** [pola-rs/polars#11542]
### Checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pypi.org/project/polars/) of Polars.

### Reproducible example

```python
import polars as pl

with open("test.csv","w") as csv:
    csv.write(
        "column_1,column_2,other_column\n"
        "1,2,3\n"
    )

df = pl.scan_csv("test.csv", new_columns=["A", "B"])
```

### Log output

```shell
thread '<unnamed>' panicked at src/lazyframe.rs:220:21:
assertion `left == right` failed: The length of the new names list should be equal to the original column length
  left: 2
 right: 3
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "venv/lib/python3.11/site-packages/polars/io/csv/functions.py", line 898, in scan_csv
    return pl.LazyFrame._scan_csv(
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "venv/lib/python3.11/site-packages/polars/lazyframe/frame.py", line 359, in _scan_csv
    self._ldf = PyLazyFrame.new_from_csv(
                ^^^^^^^^^^^^^^^^^^^^^^^^^
pyo3_runtime.PanicException: assertion `left == right` failed: The length of the new names list should be equal to the original column length
  left: 2
 right: 3
```

### Issue description

Uncaught rust exception when length of CSV header is different to list passed to `new_columns`. This is an issue when iterating through multiple files, but some do not meet the expected format

### Expected behavior

Expect this to throw a Python error, so that exceptions can be handled by users

### Installed versions

<details>

```
--------Version info---------
Polars:              0.19.7
Index type:          UInt32
Platform:            macOS-14.0-arm64-arm-64bit
Python:              3.11.4 (main, Jul 18 2023, 13:23:55) [Clang 14.0.3 (clang-1403.0.22.14.1)]

----Optional dependencies----
adbc_driver_sqlite:  <not installed>
cloudpickle:         <not installed>
connectorx:          <not installed>
deltalake:           <not installed>
fsspec:              2023.9.2
gevent:              <not installed>
matplotlib:          <not installed>
numpy:               <not installed>
openpyxl:            <not installed>
pandas:              <not installed>
pyarrow:             <not installed>
pydantic:            <not installed>
pyiceberg:           <not installed>
pyxlsb:              <not installed>
sqlalchemy:          <not installed>
xlsx2csv:            <not installed>
xlsxwriter:          <not installed>
```

</details>

**Comment by alexander-beedie** [comment]
Can you update the example so that it works? Thanks 👍

**Comment by foster999** [comment]
Thanks for taking a look 😄 

Is there a reason why the normal functionality assumes the different lengths are intentional? I think I'd prefer an error or warning, as I would usually be explicitly providing a name and/or dtypes for all columns. From the docs looks like the `schema` argument might be intended for this, but as with `dtypes` it allows you to partially overwrite the schema
