### ISSUE TITLE
ValueError when converting `np.timedelta64`

### ISSUE THREAD

**Issue by jeromedockes** [pola-rs/polars#11571]
### Checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pypi.org/project/polars/) of Polars.

### Reproducible example

```python
import numpy as np
import polars as pl

pl.lit(np.timedelta64(1, "ns"))
```

### Log output

```shell
Traceback (most recent call last):
  File "/tmp/timedelta.py", line 4, in <module>
    pl.lit(np.timedelta64(1, "ns"))
  File "/home/jerome/.virtualenvs/df/lib/python3.11/site-packages/polars/functions/lit.py", line 153, in lit
    else Duration(time_unit)
         ^^^^^^^^^^^^^^^^^^^
  File "/home/jerome/.virtualenvs/df/lib/python3.11/site-packages/polars/datatypes/classes.py", line 392, in __init__
    raise ValueError(
ValueError: invalid time_unit; expected one of {'ns','us','ms'}, got '[ns'
```

### Issue description

When trying to extract the unit from the Numpy dtype `name`, polars slices the string between positions 11 and -1:

https://github.com/pola-rs/polars/blob/7aeccacd0737e500cc06449ccb106eba6cffc52d/py-polars/polars/functions/lit.py#L151

This works for `'datetime64[ns]'` but not for `'timedelta64[ns]'` ("timedelta" is 1 character longer).
As a result the extracted unit is `'[ns'` instead of `'ns'` and not recognized by `Duration` which raises a ValueError

### Expected behavior

No error

### Installed versions

<details>

```
--------Version info---------
Polars:              0.19.7
Index type:          UInt32
Platform:            Linux-6.2.0-33-generic-x86_64-with-glibc2.35
Python:              3.11.5 (main, Aug 25 2023, 13:19:50) [GCC 11.4.0]

----Optional dependencies----
adbc_driver_sqlite:  <not installed>
cloudpickle:         2.2.1
connectorx:          <not installed>
deltalake:           <not installed>
fsspec:              <not installed>
gevent:              <not installed>
matplotlib:          3.7.3
numpy:               1.25.2
openpyxl:            <not installed>
pandas:              2.1.0
pyarrow:             13.0.0
pydantic:            <not installed>
pyiceberg:           <not installed>
pyxlsb:              <not installed>
sqlalchemy:          <not installed>
xlsx2csv:            <not installed>
xlsxwriter:          <not installed>

```

</details>

**Comment by orlp** [comment]
That's pretty silly, let me fix that.
