### ISSUE TITLE
Unable to immediately retrieve struct field produced by `json_extract`

### ISSUE THREAD

**Issue by henryharbeck** [pola-rs/polars#11591]
### Checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pypi.org/project/polars/) of Polars.

### Reproducible example

```python
df = pl.DataFrame({'a': ['{"b": 1}']})
df.select(pl.col("a").str.json_extract().struct.field("b"))
```

### Log output

```shell
Traceback (most recent call last):
  File "/home/henry/development/polars_help/test.py", line 4, in <module>
    df.select(pl.col("a").str.json_extract().struct.field("b"))
  File "/home/henry/development/polars_help/venv/lib/python3.11/site-packages/polars/dataframe/frame.py", line 7727, in select
    return self.lazy().select(*exprs, **named_exprs).collect(eager=True)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/henry/development/polars_help/venv/lib/python3.11/site-packages/polars/utils/deprecation.py", line 96, in wrapper
    return function(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/henry/development/polars_help/venv/lib/python3.11/site-packages/polars/lazyframe/frame.py", line 1713, in collect
    return wrap_df(ldf.collect())
                   ^^^^^^^^^^^^^
exceptions.StructFieldNotFoundError: b

Error originated just after this operation:
DF ["a"]; PROJECT */1 COLUMNS; SELECTION: "None"
```
```


### Issue description

I'm unable to immediately retrieve a struct field produced by `json_extract`, even though the function returns an expression and the field does indeed exist.

I'm guessing that this is likely due to the fact that the restulting struct schema from `json_extract` is not yet known until the entire select context is executed. It would be great however if there was a way that this did work when processing the expression.

This does seem semi-related to the discussions around `json_extract` in https://github.com/pola-rs/polars/issues/9871, but I'm referring primarily to eager frames here.

I'm aware that workarounds to this issue could be to:
- pull the field out in a new context - `df.select(pl.col("a").str.json_extract()).select(pl.col("a").struct.field("b"))`
- supply the schema - `df.select(pl.col("a").str.json_extract(pl.Struct([pl.Field("b", pl.Int64)])).struct.field("b"))`

But, being able to parse and retrieve the field in a single select context would be convenient.
Unfortuantely, in my case the 2nd option is not possible as schema of the JSON data is not known ahead of time.

If you (maintainers) think that the current behaviour is reasonable/intended and this is not a bug, please let me know and feel free to close this issue. Thanks

### Expected behavior

`df.select(pl.col("a").str.json_extract().struct.field("b"))` does not raise if the `b` field/key does exist in the JSON

### Installed versions

<details>

```
--------Version info---------
Polars:              0.19.7
Index type:          UInt32
Platform:            Linux-5.15.90.1-microsoft-standard-WSL2-x86_64-with-glibc2.31
Python:              3.11.4 (main, Jun  8 2023, 17:02:11) [GCC 9.4.0]

----Optional dependencies----
adbc_driver_sqlite:  <not installed>
cloudpickle:         <not installed>
connectorx:          <not installed>
deltalake:           <not installed>
fsspec:              <not installed>
gevent:              <not installed>
matplotlib:          <not installed>
numpy:               <not installed>
openpyxl:            <not installed>
pandas:              <not installed>
pyarrow:             <not installed>
pydantic:            <not installed>
pyiceberg:           <not installed>
pyxlsb:              <not installed>
sqlalchemy:          <not installed>
xlsx2csv:            <not installed>
xlsxwriter:          <not installed>
```

</details>

**Comment by cmdlineluser** [comment]
Just an interested Polars user here: 

I think this may be similar to why you cannot do
```python
pl.DataFrame().with_columns(a = pl.lit(1), b = pl.col("a") + 1)
# ColumnNotFoundError: a
```
If `.json_extract()` is called without a `dtype` - `json_infer()` needs to run.
https://github.com/pola-rs/polars/blob/9d40f0a828a0d5a19a074cc3455c05b509b60489/crates/polars-ops/src/chunked_array/strings/json_path.rs#L54-L64
But the `.struct.field()` happens first, hence the need for a separate context.

If this is the case, I think it would be useful information to add to the docs.

**Comment by ion-elgreco** [comment]
> Just an interested Polars user here: 
> 
> I think this may be similar to why you cannot do
> ```python
> pl.DataFrame().with_columns(a = pl.lit(1), b = pl.col("a") + 1)
> # ColumnNotFoundError: a
> ```
> If `.json_extract()` is called without a `dtype` - `json_infer()` needs to run.
> https://github.com/pola-rs/polars/blob/9d40f0a828a0d5a19a074cc3455c05b509b60489/crates/polars-ops/src/chunked_array/strings/json_path.rs#L54-L64
> But the `.struct.field()` happens first, hence the need for a separate context.
> 
> If this is the case, I think it would be useful information to add to the docs.

In general if you want consistent results, it's best to supply a struct schema. Since inferring doesn't always result in the same output when you have slightly mixed schemas

**Comment by cmdlineluser** [comment]
I think it is now confirmed that a single select context is not possible:
 
- https://github.com/pola-rs/polars/pull/24027

[`.map_columns()`](https://docs.pola.rs/api/python/dev/reference/dataframe/api/polars.DataFrame.map_columns.html) exists for eager - otherwise a schema/dtype is required.
