### ISSUE TITLE
`read_csv` parses header as data if schema and comment_char passed

### ISSUE THREAD

**Issue by julianroth** [pola-rs/polars#11667]
### Checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pypi.org/project/polars/) of Polars.

### Reproducible example

```python
import io
import polars as pl

csv = '''
# This is a comment
A,B
1,Hello
2,World
'''.strip()

schema = {
    'A': pl.Int32(),
    'B': pl.Utf8(),
}
df = pl.read_csv(io.StringIO(csv), comment_char='#', schema=schema)
```

### Log output

```shell
file < 128 rows, no statistics determined
no. of chunks: 1 processed by: 1 threads.
Traceback (most recent call last):
  File "/home/read_csv_test.py", line 15, in <module>
    df = pl.read_csv(io.StringIO(csv), comment_char='#', schema=schema)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/mambaforge/envs/pl/lib/python3.11/site-packages/polars/io/csv/functions.py", line 366, in read_csv                                                                                                             
    df = pl.DataFrame._read_csv(
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/mambaforge/envs/pl/lib/python3.11/site-packages/polars/dataframe/frame.py", line 770, in _read_csv                                                                                                             
    self._df = PyDataFrame.read_csv(
               ^^^^^^^^^^^^^^^^^^^^^
exceptions.ComputeError: Could not parse `A` as dtype `i32` at column 'A' (column number 1).
The current offset in the file is 20 bytes.

You might want to try:
- increasing `infer_schema_length` (e.g. `infer_schema_length=10000`),
- specifying correct dtype with the `dtypes` argument
- setting `ignore_errors` to `True`,
- adding `A` to the `null_values` list.
```

### Issue description

Trying to parse CSV files with comments fails if `schema` is passed because polars tries to parse the header using the passed schema. Setting `has_header=True` has no effect. When changing all data types in the schema to `pl.Utf8()`, the query works but the header will be present as the first row in the resulting DataFrame.

### Expected behavior

```
Expected parsed DataFrame:
┌─────┬───────┐
│ A   ┆ B     │
│ --- ┆ ---   │
│ i32 ┆ str   │
╞═════╪═══════╡
│ 1   ┆ Hello │
│ 2   ┆ World │
└─────┴───────┘
```

### Installed versions

<details>

```
--------Version info---------
Polars:              0.19.8
Index type:          UInt32
Platform:            Linux-4.18.0-372.13.1.el8_6.x86_64-x86_64-with-glibc2.28
Python:              3.11.6 | packaged by conda-forge | (main, Oct  3 2023, 10:40:35) [GCC 12.3.0]

----Optional dependencies----
adbc_driver_sqlite:  <not installed>
cloudpickle:         <not installed>
connectorx:          <not installed>
deltalake:           <not installed>
fsspec:              <not installed>
gevent:              <not installed>
matplotlib:          <not installed>
numpy:               1.26.0
openpyxl:            <not installed>
pandas:              <not installed>
pyarrow:             <not installed>
pydantic:            <not installed>
pyiceberg:           <not installed>
pyxlsb:              <not installed>
sqlalchemy:          <not installed>
xlsx2csv:            <not installed>
xlsxwriter:          <not installed>
```

</details>

**Comment by uchiiii** [comment]
How about adding `skip_rows=1` as args.

```
import io
import polars as pl

csv = '''
# This is a comment
A,B
1,Hello
2,World
'''.strip()

schema = {
    'A': pl.Int32(),
    'B': pl.Utf8(),
}
df = pl.read_csv(io.StringIO(csv), comment_char='#', schema=schema, skip_rows=1)
```

**Comment by stinodego** [comment]
> How about adding `skip_rows=1` as args?

That is a good workaround until this issue is fixed.
