### ISSUE TITLE
ComputeError from pl.scan_parquet on s3

### ISSUE THREAD

**Issue by erikcw** [pola-rs/polars#11672]
### Checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pypi.org/project/polars/) of Polars.

### Reproducible example

```python

In [1]: import polars as pl

In [2]: pl.__version__
Out[2]: '0.19.8'

In [3]: df = pl.read_parquet('s3://BUCKET/path/to/file.parquet')

In [4]: df.shape
Out[4]:
shape: (602_112, 47)

In [5]: df = pl.scan_parquet('s3://BUCKET/path/to/file.parquet')
---------------------------------------------------------------------------
ComputeError                              Traceback (most recent call last)
Cell In[5], line 1
----> 1 df = pl.scan_parquet('s3://BUCKET/path/to/file.parquet')

File /opt/app/.venv/lib/python3.11/site-packages/polars/io/parquet/functions.py:265, in scan_parquet(source, n_rows, cache, parallel, rechunk, row_count_name, row_count_offset, storage_options, low_memory, use_statistics, hive_partitioning, retries)
    262 if isinstance(source, (str, Path)):
    263     source = normalize_filepath(source)
--> 265 return pl.LazyFrame._scan_parquet(
    266     source,
    267     n_rows=n_rows,
    268     cache=cache,
    269     parallel=parallel,
    270     rechunk=rechunk,
    271     row_count_name=row_count_name,
    272     row_count_offset=row_count_offset,
    273     storage_options=storage_options,
    274     low_memory=low_memory,
    275     use_statistics=use_statistics,
    276     hive_partitioning=hive_partitioning,
    277     retries=retries,
    278 )

File /opt/app/.venv/lib/python3.11/site-packages/polars/lazyframe/frame.py:428, in LazyFrame._scan_parquet(cls, source, n_rows, cache, parallel, rechunk, row_count_name, row_count_offset, storage_options, low_memory, use_statistics, hive_partitioning, retries)
    425     storage_options = list(storage_options.items())  #  type: ignore[assignment]
    427 self = cls.__new__(cls)
--> 428 self._ldf = PyLazyFrame.new_from_parquet(
    429     source,
    430     n_rows,
    431     cache,
    432     parallel,
    433     rechunk,
    434     _prepare_row_count_args(row_count_name, row_count_offset),
    435     low_memory,
    436     cloud_options=storage_options,
    437     use_statistics=use_statistics,
    438     hive_partitioning=hive_partitioning,
    439     retries=retries,
    440 )
    441 return self

ComputeError: Generic S3 error: response error "request error", after 0 retries: error sending request for url (https://sts.us-east-1.amazonaws.com/?Action=AssumeRoleWithWebIdentity&DurationSeconds=3600&RoleArn=arn%3Aaws%3Aiam%3A%3A1*********52%3Arole%2Feksctl-jde-cluster-addon-iamserviceaccount-l-Role1-Q*********K3&RoleSessionName=WebIdentitySession&Version=2011-06-15&WebIdentityToken=eyJhbGci**************************Y0OGYwOThkYzgwZDk0YTk0MDYzMWRlN2U3Mjc4ND*****************************************************ZXhwIjoxNjk3MTM3NTQ2LCJpYXQiOjE2OTcwNTExNDYsImlzcyI6Imh0dHBzOi8vb2lkYy5la3MudXMtZWFzdC0xLmFtYXpvbmF3cy5jb20vaWQvRDg3OUQ2OEFDQTU0NzFCMjRFMENBRkVDQjMzREQxMjkiLCJrdWJlcm5ldGVzLmlvIjp7Im5hbWVzcGFjZSI6ImxlYWRmaWxlIiwicG9kIjp7Im5hbWUiOiJjbGlja2NlcnRhaW4tbGVhZGZpbGUtN2xjZzgtZmZsMmMiLCJ1aWQiOiI3ZTQ2ZDQ4Ny01YmEzLTQzNTEtOTNkOS0zMDNjY2UwN2UxYTMifSwic2VydmljZWFjY291bnQiOnsibmFtZSI6ImxlYWRmaWxlIiwidWlkIjoiZDU3NTFiOWUtYzA0YS00MzhlLWEzNjMtYmJjMzVkZGJlMzNhIn19LCJuYmYiOjE2OTcwNTExNDYsInN1YiI6InN5c3RlbTpzZXJ2aWNlYWNjb3VudDpsZWFkZmlsZTpsZWFkZmlsZSJ9.K3Ik1tY01JZawtR8Tzz85d8yTPxKCFOLo9_hJNZmLgK0uyBJtOV10B9XwBYH92Ak4LFqmdZ5EB-sMJDvFZNV4ASuqzdjaGBebosAwv0EPwvfysUD9b9Q7Xh1ys3IVVw19m0kcK3yeXSAVywBDEgtFBnEmP5FbZFxMijfop4onEyDkbdDSov1KJzhof6rEDEhi8mBaBryi-c3an_zXszrqk9OF3e0KXYZHCQaKuzvejy_H74iracJ21d4zSA8GG4MlnWp6aWaRcj4wfpG7psrHvLl73mmLlewle6rzAB_tOwyKdOyaN214d0IA1yadJBXRmzpYL4zMXeUTtqgbQFVJg): error trying to connect: invalid peer certificate: BadSignature


```

I also tried using credentials through `storage_options` with a similar error:

```python
In [3]: import boto3

In [4]: session = boto3.Session()

In [5]: credentials = session.get_credentials()
   ...: credentials = credentials.get_frozen_credentials()
   ...: access_key = credentials.access_key
   ...: secret_key = credentials.secret_key

In [7]: session.region_name
Out[7]: 'us-east-1'

In [8]: storage_options = {
   ...:
   ...:     "aws_access_key_id": access_key,
   ...:
   ...:     "aws_secret_access_key": secret_key,
   ...:
   ...:     "aws_region": "us-east-1",
   ...:
   ...: }

In [9]: df = pl.scan_parquet('s3://BUCKET/path/to/file.parquet', storage_options=storage_options)
---------------------------------------------------------------------------
ComputeError                              Traceback (most recent call last)
Cell In[9], line 1
----> 1 df = pl.scan_parquet('s3://BUCKET/path/to/file.parquet', storage_options=storage_options)

File /opt/app/.venv/lib/python3.11/site-packages/polars/io/parquet/functions.py:265, in scan_parquet(source, n_rows, cache, parallel, rechunk, row_count_name, row_count_offset, storage_options, low_memory, use_statistics, hive_partitioning, retries)
    262 if isinstance(source, (str, Path)):
    263     source = normalize_filepath(source)
--> 265 return pl.LazyFrame._scan_parquet(
    266     source,
    267     n_rows=n_rows,
    268     cache=cache,
    269     parallel=parallel,
    270     rechunk=rechunk,
    271     row_count_name=row_count_name,
    272     row_count_offset=row_count_offset,
    273     storage_options=storage_options,
    274     low_memory=low_memory,
    275     use_statistics=use_statistics,
    276     hive_partitioning=hive_partitioning,
    277     retries=retries,
    278 )

File /opt/app/.venv/lib/python3.11/site-packages/polars/lazyframe/frame.py:428, in LazyFrame._scan_parquet(cls, source, n_rows, cache, parallel, rechunk, row_count_name, row_count_offset, storage_options, low_memory, use_statistics, hive_partitioning, retries)
    425     storage_options = list(storage_options.items())  #  type: ignore[assignment]
    427 self = cls.__new__(cls)
--> 428 self._ldf = PyLazyFrame.new_from_parquet(
    429     source,
    430     n_rows,
    431     cache,
    432     parallel,
    433     rechunk,
    434     _prepare_row_count_args(row_count_name, row_count_offset),
    435     low_memory,
    436     cloud_options=storage_options,
    437     use_statistics=use_statistics,
    438     hive_partitioning=hive_partitioning,
    439     retries=retries,
    440 )
    441 return self

ComputeError: Generic S3 error: response error "request error", after 0 retries: error sending request for url (https://s3.us-east-1.amazonaws.com/BUCKET/path/to/file.parquet'): error trying to connect: invalid peer certificate: BadSignature


```

### Issue description

I'm getting the following error since upgrading to polars 0.19.8 from 0.19.2 when trying to `scan_parquet` from s3.

In my case I'm use an AWS Role to provide authentication, however a very similar error occurs if I try to pass in credentials via `storage_options`:
```bash
# env | grep AWS
AWS_DEFAULT_REGION=us-east-1
AWS_REGION=us-east-1
AWS_ROLE_ARN=arn:aws:iam::17************:role/eksctl-jde-cluster-addon-iamserviceaccount-l-Role1-*************
AWS_WEB_IDENTITY_TOKEN_FILE=/var/run/secrets/eks.amazonaws.com/serviceaccount/token
AWS_STS_REGIONAL_ENDPOINTS=regional
```

```python
  File "/opt/app/utils.py", line 83, in already_processed
    df = pl.scan_parquet(s3_path)
         ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/app/.venv/lib/python3.11/site-packages/polars/io/parquet/functions.py", line 258, in scan_parquet
    return pl.LazyFrame._scan_parquet(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/app/.venv/lib/python3.11/site-packages/polars/lazyframe/frame.py", line 427, in _scan_parquet
    self._ldf = PyLazyFrame.new_from_parquet(
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
exceptions.ComputeError: Generic S3 error: response error "request error", after 0 retries: error sending request for url (https://sts.us-east-1.amazonaws.com/?Action=AssumeRoleWithWebIdentity&DurationSeconds=3600&RoleArn=arn%3Aaws%3Aiam%3A%3A17691******2%3Arole%2Feksctl-jde-cluster-addon-iamserviceaccount-l-Role1-***********3&RoleSessionName=WebIdentitySession&Version=2011-06-15&WebIdentityToken=**********************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************): error trying to connect: invalid peer certificate: BadSignature
```

Rolled back to 0.19.2 and it started working again.

### Expected behavior

In 0.19.2 and prior, this worked as expected.  As you can see in my example, `read_parquet` still works just fine in the same environment.

### Installed versions

<details>

```
--------Version info---------
Polars:              0.19.8
Index type:          UInt32
Platform:            Linux-5.10.192-183.736.amzn2.aarch64-aarch64-with-glibc2.36
Python:              3.11.6 (main, Oct  3 2023, 03:10:53) [GCC 12.2.0]

----Optional dependencies----
adbc_driver_sqlite:  <not installed>
cloudpickle:         <not installed>
connectorx:          <not installed>
deltalake:           <not installed>
fsspec:              2022.11.0
gevent:              <not installed>
matplotlib:          <not installed>
numpy:               1.25.2
openpyxl:            <not installed>
pandas:              2.1.1
pyarrow:             13.0.0
pydantic:            <not installed>
pyiceberg:           <not installed>
pyxlsb:              <not installed>
sqlalchemy:          <not installed>
xlsx2csv:            <not installed>
xlsxwriter:          <not installed>

```

</details>

**Comment by ritchie46** [comment]
We changed scan_parquet to dispatch to our native cloud readers. There seems to be something in your credentials object-store doesn't support.

I do wonder what is different on your side as I can confirm many users who are able to connect with our new backend.

**Comment by abstractqqq** [comment]
Same error. It is strange that read_parquet works but lazy doesn't.

**Comment by kfreisen** [comment]
Seeing similar errors. Had been working fine in `0.19.2` but broke afterwards.

When I run on my laptop with an explicit `AWS_PROFILE` specified (one that I can read the file from via the `aws` cli):

```python
pl.scan_parquet('s3://....')
```

I get the following error:

```
polars.exceptions.ComputeError: Generic S3 error: Error after 2 retries in 2.237778792s, max_retries:2, retry_timeout:10s, source:error sending request for url (http://169.254.169.254/latest/api/token): error trying to connect: tcp connect error: Host is down (os error 64)
```

When I run it on a hosted notebook server (something that _does_ use an iam role for access) it works totally fine.

`read_parquet` and `pandas` work fine, but I need to take advantage of lazyness because of the size of data.

**Comment by ritchie46** [comment]
You must explicitly authenticate. Either set env vars, or provide the needed info in `storage_options`

**Comment by kfreisen** [comment]
I am setting `AWS_PROFILE` with a profile that has access to the resource.

**Comment by erikcw** [comment]
I just re-tested on version `0.20.3` and the issue appears to be resolved.  I'll go ahead and close this issue out.
