### ISSUE TITLE
`.drop()` with a non-existent column raises `PanicException: Hash table capacity overflow`

### ISSUE THREAD

**Issue by cmdlineluser** [pola-rs/polars#11697]
### Checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pypi.org/project/polars/) of Polars.

### Reproducible example

```python
import polars as pl

df = pl.DataFrame({"foo": [1]})
df.drop('foo', 'bar')
```

### Log output

```shell
thread '<unnamed>' panicked at /Users/runner/.cargo/registry/src/index.crates.io-6f17d22bba15001f/hashbrown-0.14.0/src/raw/mod.rs:82:40:
Hash table capacity overflow
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
Traceback (most recent call last):
  File "/Users/user/a.py", line 4, in <module>
    df.drop('foo', 'bar')
  File "/opt/homebrew/lib/python3.11/site-packages/polars/dataframe/frame.py", line 6362, in drop
    return self.lazy().drop(columns, *more_columns).collect(_eager=True)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/polars/lazyframe/frame.py", line 4011, in drop
    return self._from_pyldf(self._ldf.drop(drop_cols))
                            ^^^^^^^^^^^^^^^^^^^^^^^^^
pyo3_runtime.PanicException: Hash table capacity overflow
```

### Issue description

Trying to `.drop` a column that does not exist seems to produce an odd exception.

### Expected behavior

I'm not sure if drop is supposed to silently ignore non-existent columns or not, but this particular exception should not probably not happen.

### Installed versions

<details>

```
--------Version info---------
Polars:              0.19.8
Index type:          UInt32
Platform:            macOS-12.6.7-arm64-arm-64bit
Python:              3.11.4 (main, Jun 20 2023, 17:37:48) [Clang 14.0.0 (clang-1400.0.29.202)]

----Optional dependencies----
adbc_driver_sqlite:  <not installed>
cloudpickle:         <not installed>
connectorx:          <not installed>
deltalake:           <not installed>
fsspec:              2023.6.0
gevent:              <not installed>
matplotlib:          <not installed>
numpy:               1.25.0
openpyxl:            <not installed>
pandas:              2.0.3
pyarrow:             12.0.1
pydantic:            <not installed>
pyiceberg:           <not installed>
pyxlsb:              <not installed>
sqlalchemy:          <not installed>
xlsx2csv:            <not installed>
xlsxwriter:          <not installed>
```

</details>

**Comment by orlp** [comment]
I think this would be a good issue for a Rust programmer relatively new to the project.

**Comment by rancomp** [comment]
Hi @orlp, I see that both DataFrame and LazyFrame in the polars size point to `fn drop_columns` in `polars-lazy/src/frame/mod.rs`. The PanicException rises when taking the difference of two `usize` with the first being lesser than the second (it overflows).

It's a 1-liner fix which I would be happy to push :)
But it can also be more elaborate. Right now there's no Error when dropping the a non-existent column. Is this the intended behavior?
