### ISSUE TITLE
panic when manipulating categorical lists: `Option::unwrap() on a None value`

### ISSUE THREAD

**Issue by shenker** [pola-rs/polars#11735]
### Checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pypi.org/project/polars/) of Polars.

### Issue description

Possibly related to https://github.com/pola-rs/polars/issues/11730, https://github.com/pola-rs/polars/issues/11731, https://github.com/pola-rs/polars/issues/11732, or https://github.com/pola-rs/polars/issues/11734.

```python
with pl.StringCache():
    df = pl.DataFrame(
        {
            "col1": [
                np.random.choice(["a", "b", "c", "d"], np.random.randint(1, 5))
                for _ in range(10)
            ],
            "col2": np.random.randint(0, 2, size=10),
        },
        schema={"col1": pl.List(pl.Categorical), "col2": pl.Int64},
    )
    res = (
        df.select(pl.col("col1", "col2"))
        .with_columns(
            pl.col("col1")
            .list.set_intersection(["a", "b", "c"])
            .cast(pl.List(pl.Categorical)) # necessary because https://github.com/pola-rs/polars/issues/11730
            .alias("col1_alt"),
        )
        .with_columns(
            pl.when(pl.col("col2") == 1)
            .then(pl.col("col1_alt"))
            .when(pl.col("col2") == 0)
            .then(pl.col("col1"))
            .alias("col1_combined")
        )
    )
    print(res)
```
produces a `PanicException: called Option::unwrap() on a None value`

<details>

```shell
thread '<unnamed>' panicked at /home/conda/feedstock_root/build_artifacts/polars_1697023604136/work/crates/polars-core/src/chunked_array/logical/categorical/builder.rs:114:42:
called `Option::unwrap()` on a `None` value
stack backtrace:
   0: rust_begin_unwind
             at /rustc/59edd67056919c83c59001a8b4f2d8749359377a/library/std/src/panicking.rs:597:5
   1: core::panicking::panic_fmt
             at /rustc/59edd67056919c83c59001a8b4f2d8749359377a/library/core/src/panicking.rs:72:14
   2: core::panicking::panic
             at /rustc/59edd67056919c83c59001a8b4f2d8749359377a/library/core/src/panicking.rs:127:5
   3: polars_core::chunked_array::logical::categorical::builder::RevMapping::get
   4: polars_core::datatypes::any_value::AnyValue::get_str
   5: polars_core::fmt::<impl core::fmt::Display for polars_core::datatypes::any_value::AnyValue>::fmt
   6: core::fmt::rt::Argument::fmt
             at /rustc/59edd67056919c83c59001a8b4f2d8749359377a/library/core/src/fmt/rt.rs:142:9
   7: core::fmt::write
             at /rustc/59edd67056919c83c59001a8b4f2d8749359377a/library/core/src/fmt/mod.rs:1117:17
   8: <&mut W as core::fmt::Write::write_fmt::SpecWriteFmt>::spec_write_fmt
             at /rustc/59edd67056919c83c59001a8b4f2d8749359377a/library/core/src/fmt/mod.rs:208:17
   9: core::fmt::Write::write_fmt
             at /rustc/59edd67056919c83c59001a8b4f2d8749359377a/library/core/src/fmt/mod.rs:212:14
  10: alloc::fmt::format::format_inner
             at /rustc/59edd67056919c83c59001a8b4f2d8749359377a/library/alloc/src/fmt.rs:610:16
  11: polars_core::fmt::<impl polars_core::series::Series>::fmt_list
  12: polars_core::fmt::<impl core::fmt::Display for polars_core::datatypes::any_value::AnyValue>::fmt
  13: core::fmt::rt::Argument::fmt
             at /rustc/59edd67056919c83c59001a8b4f2d8749359377a/library/core/src/fmt/rt.rs:142:9
  14: core::fmt::write
             at /rustc/59edd67056919c83c59001a8b4f2d8749359377a/library/core/src/fmt/mod.rs:1117:17
  15: <&mut W as core::fmt::Write::write_fmt::SpecWriteFmt>::spec_write_fmt
             at /rustc/59edd67056919c83c59001a8b4f2d8749359377a/library/core/src/fmt/mod.rs:208:17
  16: core::fmt::Write::write_fmt
             at /rustc/59edd67056919c83c59001a8b4f2d8749359377a/library/core/src/fmt/mod.rs:212:14
  17: alloc::fmt::format::format_inner
             at /rustc/59edd67056919c83c59001a8b4f2d8749359377a/library/alloc/src/fmt.rs:610:16
  18: polars_core::series::Series::str_value
  19: polars_core::fmt::<impl core::fmt::Display for polars_core::frame::DataFrame>::fmt
  20: core::fmt::rt::Argument::fmt
             at /rustc/59edd67056919c83c59001a8b4f2d8749359377a/library/core/src/fmt/rt.rs:142:9
  21: core::fmt::write
             at /rustc/59edd67056919c83c59001a8b4f2d8749359377a/library/core/src/fmt/mod.rs:1117:17
  22: <&mut W as core::fmt::Write::write_fmt::SpecWriteFmt>::spec_write_fmt
             at /rustc/59edd67056919c83c59001a8b4f2d8749359377a/library/core/src/fmt/mod.rs:208:17
  23: core::fmt::Write::write_fmt
             at /rustc/59edd67056919c83c59001a8b4f2d8749359377a/library/core/src/fmt/mod.rs:212:14
  24: alloc::fmt::format::format_inner
             at /rustc/59edd67056919c83c59001a8b4f2d8749359377a/library/alloc/src/fmt.rs:610:16
  25: polars::dataframe::_::<impl polars::dataframe::PyDataFrame>::__pymethod_as_str__
  26: pyo3::impl_::trampoline::trampoline
  27: method_vectorcall_NOARGS
             at /usr/local/src/conda/python-3.10.12/Objects/descrobject.c:432:24
  28: _PyObject_VectorcallTstate
             at /usr/local/src/conda/python-3.10.12/Include/cpython/abstract.h:114:11
  29: PyObject_Vectorcall
             at /usr/local/src/conda/python-3.10.12/Include/cpython/abstract.h:123:12
  30: call_function
             at /usr/local/src/conda/python-3.10.12/Python/ceval.c:5893:13
  31: _PyEval_EvalFrameDefault
             at /usr/local/src/conda/python-3.10.12/Python/ceval.c:4198:23
  32: _PyEval_EvalFrame
             at /usr/local/src/conda/python-3.10.12/Include/internal/pycore_ceval.h:46:12
  33: _PyEval_Vector
             at /usr/local/src/conda/python-3.10.12/Python/ceval.c:5067:24
  34: _PyFunction_Vectorcall
             at /usr/local/src/conda/python-3.10.12/Objects/call.c:342:16
  35: _PyObject_VectorcallTstate
             at /usr/local/src/conda/python-3.10.12/Include/cpython/abstract.h:114:11
  36: vectorcall_unbound
             at /usr/local/src/conda/python-3.10.12/Objects/typeobject.c:1629:12
  37: vectorcall_method
             at /usr/local/src/conda/python-3.10.12/Objects/typeobject.c:1661:24
  38: slot_tp_str
             at /usr/local/src/conda/python-3.10.12/Objects/typeobject.c:7430:1
  39: PyObject_Str
             at /usr/local/src/conda/python-3.10.12/Objects/object.c:499:12
  40: PyFile_WriteObject
             at /usr/local/src/conda/python-3.10.12/Objects/fileobject.c:132:17
  41: builtin_print
             at /usr/local/src/conda/python-3.10.12/Python/bltinmodule.c:2003:15
  42: cfunction_vectorcall_FASTCALL_KEYWORDS
             at /usr/local/src/conda/python-3.10.12/Objects/methodobject.c:446:24
  43: _PyObject_VectorcallTstate
             at /usr/local/src/conda/python-3.10.12/Include/cpython/abstract.h:114:11
  44: PyObject_Vectorcall
             at /usr/local/src/conda/python-3.10.12/Include/cpython/abstract.h:123:12
  45: call_function
             at /usr/local/src/conda/python-3.10.12/Python/ceval.c:5893:13
  46: _PyEval_EvalFrameDefault
             at /usr/local/src/conda/python-3.10.12/Python/ceval.c:4213:19
  47: _PyEval_EvalFrame
             at /usr/local/src/conda/python-3.10.12/Include/internal/pycore_ceval.h:46:12
  48: _PyEval_Vector
             at /usr/local/src/conda/python-3.10.12/Python/ceval.c:5067:24
  49: PyEval_EvalCode
             at /usr/local/src/conda/python-3.10.12/Python/ceval.c:1134:12
  50: builtin_exec_impl
             at /usr/local/src/conda/python-3.10.12/Python/bltinmodule.c:1058:13
  51: builtin_exec
             at /usr/local/src/conda/python-3.10.12/Python/clinic/bltinmodule.c.h:371:20
  52: cfunction_vectorcall_FASTCALL
             at /usr/local/src/conda/python-3.10.12/Objects/methodobject.c:430:24
  53: _PyObject_VectorcallTstate
             at /usr/local/src/conda/python-3.10.12/Include/cpython/abstract.h:114:11
  54: PyObject_Vectorcall
             at /usr/local/src/conda/python-3.10.12/Include/cpython/abstract.h:123:12
  55: call_function
             at /usr/local/src/conda/python-3.10.12/Python/ceval.c:5893:13
  56: _PyEval_EvalFrameDefault
             at /usr/local/src/conda/python-3.10.12/Python/ceval.c:4213:19
  57: _PyEval_EvalFrame
             at /usr/local/src/conda/python-3.10.12/Include/internal/pycore_ceval.h:46:12
  58: gen_send_ex2
             at /usr/local/src/conda/python-3.10.12/Objects/genobject.c:213:14
  59: _PyEval_EvalFrameDefault
             at /usr/local/src/conda/python-3.10.12/Python/ceval.c:2586:30
  60: _PyEval_EvalFrame
             at /usr/local/src/conda/python-3.10.12/Include/internal/pycore_ceval.h:46:12
  61: gen_send_ex2
             at /usr/local/src/conda/python-3.10.12/Objects/genobject.c:213:14
  62: _PyEval_EvalFrameDefault
             at /usr/local/src/conda/python-3.10.12/Python/ceval.c:2586:30
  63: _PyEval_EvalFrame
             at /usr/local/src/conda/python-3.10.12/Include/internal/pycore_ceval.h:46:12
  64: gen_send_ex2
             at /usr/local/src/conda/python-3.10.12/Objects/genobject.c:213:14
  65: gen_send_ex
             at /usr/local/src/conda/python-3.10.12/Objects/genobject.c:279:9
  66: method_vectorcall_O
             at /usr/local/src/conda/python-3.10.12/Objects/descrobject.c:460:24
  67: _PyObject_VectorcallTstate
             at /usr/local/src/conda/python-3.10.12/Include/cpython/abstract.h:114:11
  68: PyObject_Vectorcall
             at /usr/local/src/conda/python-3.10.12/Include/cpython/abstract.h:123:12
  69: call_function
             at /usr/local/src/conda/python-3.10.12/Python/ceval.c:5893:13
  70: _PyEval_EvalFrameDefault
             at /usr/local/src/conda/python-3.10.12/Python/ceval.c:4198:23
  71: _PyEval_EvalFrame
             at /usr/local/src/conda/python-3.10.12/Include/internal/pycore_ceval.h:46:12
  72: _PyEval_Vector
             at /usr/local/src/conda/python-3.10.12/Python/ceval.c:5067:24
  73: _PyFunction_Vectorcall
             at /usr/local/src/conda/python-3.10.12/Objects/call.c:342:16
  74: _PyObject_VectorcallTstate
             at /usr/local/src/conda/python-3.10.12/Include/cpython/abstract.h:114:11
  75: PyObject_Vectorcall
             at /usr/local/src/conda/python-3.10.12/Include/cpython/abstract.h:123:12
  76: call_function
             at /usr/local/src/conda/python-3.10.12/Python/ceval.c:5893:13
  77: _PyEval_EvalFrameDefault
             at /usr/local/src/conda/python-3.10.12/Python/ceval.c:4213:19
  78: _PyEval_EvalFrame
             at /usr/local/src/conda/python-3.10.12/Include/internal/pycore_ceval.h:46:12
  79: _PyEval_Vector
             at /usr/local/src/conda/python-3.10.12/Python/ceval.c:5067:24
  80: _PyFunction_Vectorcall
             at /usr/local/src/conda/python-3.10.12/Objects/call.c:342:16
  81: _PyObject_VectorcallTstate
             at /usr/local/src/conda/python-3.10.12/Include/cpython/abstract.h:114:11
  82: PyObject_Vectorcall
             at /usr/local/src/conda/python-3.10.12/Include/cpython/abstract.h:123:12
  83: call_function
             at /usr/local/src/conda/python-3.10.12/Python/ceval.c:5893:13
  84: _PyEval_EvalFrameDefault
             at /usr/local/src/conda/python-3.10.12/Python/ceval.c:4198:23
  85: _PyEval_EvalFrame
             at /usr/local/src/conda/python-3.10.12/Include/internal/pycore_ceval.h:46:12
  86: _PyEval_Vector
             at /usr/local/src/conda/python-3.10.12/Python/ceval.c:5067:24
  87: _PyFunction_Vectorcall
             at /usr/local/src/conda/python-3.10.12/Objects/call.c:342:16
  88: _PyObject_VectorcallTstate
             at /usr/local/src/conda/python-3.10.12/Include/cpython/abstract.h:114:11
  89: method_vectorcall
             at /usr/local/src/conda/python-3.10.12/Objects/classobject.c:53:18
  90: PyVectorcall_Call
             at /usr/local/src/conda/python-3.10.12/Objects/call.c:267:24
  91: _PyObject_Call
             at /usr/local/src/conda/python-3.10.12/Objects/call.c:290:16
  92: PyObject_Call
             at /usr/local/src/conda/python-3.10.12/Objects/call.c:317:12
  93: do_call_core
             at /usr/local/src/conda/python-3.10.12/Python/ceval.c:5945:12
  94: _PyEval_EvalFrameDefault
             at /usr/local/src/conda/python-3.10.12/Python/ceval.c:4277:22
  95: _PyEval_EvalFrame
             at /usr/local/src/conda/python-3.10.12/Include/internal/pycore_ceval.h:46:12
  96: _PyEval_Vector
             at /usr/local/src/conda/python-3.10.12/Python/ceval.c:5067:24
  97: _PyFunction_Vectorcall
             at /usr/local/src/conda/python-3.10.12/Objects/call.c:342:16
  98: _PyObject_VectorcallTstate
             at /usr/local/src/conda/python-3.10.12/Include/cpython/abstract.h:114:11
  99: method_vectorcall
             at /usr/local/src/conda/python-3.10.12/Objects/classobject.c:53:18
 100: _PyObject_VectorcallTstate
             at /usr/local/src/conda/python-3.10.12/Include/cpython/abstract.h:114:11
 101: PyObject_Vectorcall
             at /usr/local/src/conda/python-3.10.12/Include/cpython/abstract.h:123:12
 102: call_function
             at /usr/local/src/conda/python-3.10.12/Python/ceval.c:5893:13
 103: _PyEval_EvalFrameDefault
             at /usr/local/src/conda/python-3.10.12/Python/ceval.c:4231:19
 104: _PyEval_EvalFrame
             at /usr/local/src/conda/python-3.10.12/Include/internal/pycore_ceval.h:46:12
 105: gen_send_ex2
             at /usr/local/src/conda/python-3.10.12/Objects/genobject.c:213:14
 106: _PyEval_EvalFrameDefault
             at /usr/local/src/conda/python-3.10.12/Python/ceval.c:2586:30
 107: _PyEval_EvalFrame
             at /usr/local/src/conda/python-3.10.12/Include/internal/pycore_ceval.h:46:12
 108: gen_send_ex2
             at /usr/local/src/conda/python-3.10.12/Objects/genobject.c:213:14
 109: _PyEval_EvalFrameDefault
             at /usr/local/src/conda/python-3.10.12/Python/ceval.c:2586:30
 110: _PyEval_EvalFrame
             at /usr/local/src/conda/python-3.10.12/Include/internal/pycore_ceval.h:46:12
 111: gen_send_ex2
             at /usr/local/src/conda/python-3.10.12/Objects/genobject.c:213:14
 112: _PyEval_EvalFrameDefault
             at /usr/local/src/conda/python-3.10.12/Python/ceval.c:2586:30
 113: _PyEval_EvalFrame
             at /usr/local/src/conda/python-3.10.12/Include/internal/pycore_ceval.h:46:12
 114: gen_send_ex2
             at /usr/local/src/conda/python-3.10.12/Objects/genobject.c:213:14
 115: _PyEval_EvalFrameDefault
             at /usr/local/src/conda/python-3.10.12/Python/ceval.c:2586:30
 116: _PyEval_EvalFrame
             at /usr/local/src/conda/python-3.10.12/Include/internal/pycore_ceval.h:46:12
 117: gen_send_ex2
             at /usr/local/src/conda/python-3.10.12/Objects/genobject.c:213:14
 118: task_step_impl
             at /usr/local/src/conda/python-3.10.12/Modules/_asynciomodule.c:2653:22
 119: task_step
             at /usr/local/src/conda/python-3.10.12/Modules/_asynciomodule.c:2950:11
 120: cfunction_vectorcall_O
             at /usr/local/src/conda/python-3.10.12/Objects/methodobject.c:516:24
 121: _PyObject_VectorcallTstate
             at /usr/local/src/conda/python-3.10.12/Include/cpython/abstract.h:114:11
 122: context_run
             at /usr/local/src/conda/python-3.10.12/Python/context.c:665
 123: cfunction_vectorcall_FASTCALL_KEYWORDS
             at /usr/local/src/conda/python-3.10.12/Objects/methodobject.c:446:24
 124: do_call_core
             at /usr/local/src/conda/python-3.10.12/Python/ceval.c:5917:9
 125: _PyEval_EvalFrameDefault
             at /usr/local/src/conda/python-3.10.12/Python/ceval.c:4277:22
 126: _PyEval_EvalFrame
             at /usr/local/src/conda/python-3.10.12/Include/internal/pycore_ceval.h:46:12
 127: _PyEval_Vector
             at /usr/local/src/conda/python-3.10.12/Python/ceval.c:5067:24
 128: _PyFunction_Vectorcall
             at /usr/local/src/conda/python-3.10.12/Objects/call.c:342:16
 129: _PyObject_VectorcallTstate
             at /usr/local/src/conda/python-3.10.12/Include/cpython/abstract.h:114:11
 130: PyObject_Vectorcall
             at /usr/local/src/conda/python-3.10.12/Include/cpython/abstract.h:123:12
 131: call_function
             at /usr/local/src/conda/python-3.10.12/Python/ceval.c:5893:13
 132: _PyEval_EvalFrameDefault
             at /usr/local/src/conda/python-3.10.12/Python/ceval.c:4198:23
 133: _PyEval_EvalFrame
             at /usr/local/src/conda/python-3.10.12/Include/internal/pycore_ceval.h:46:12
 134: _PyEval_Vector
             at /usr/local/src/conda/python-3.10.12/Python/ceval.c:5067:24
 135: _PyFunction_Vectorcall
             at /usr/local/src/conda/python-3.10.12/Objects/call.c:342:16
 136: _PyObject_VectorcallTstate
             at /usr/local/src/conda/python-3.10.12/Include/cpython/abstract.h:114:11
 137: PyObject_Vectorcall
             at /usr/local/src/conda/python-3.10.12/Include/cpython/abstract.h:123:12
 138: call_function
             at /usr/local/src/conda/python-3.10.12/Python/ceval.c:5893:13
 139: _PyEval_EvalFrameDefault
             at /usr/local/src/conda/python-3.10.12/Python/ceval.c:4198:23
 140: _PyEval_EvalFrame
             at /usr/local/src/conda/python-3.10.12/Include/internal/pycore_ceval.h:46:12
 141: _PyEval_Vector
             at /usr/local/src/conda/python-3.10.12/Python/ceval.c:5067:24
 142: _PyFunction_Vectorcall
             at /usr/local/src/conda/python-3.10.12/Objects/call.c:342:16
 143: _PyObject_VectorcallTstate
             at /usr/local/src/conda/python-3.10.12/Include/cpython/abstract.h:114:11
 144: PyObject_Vectorcall
             at /usr/local/src/conda/python-3.10.12/Include/cpython/abstract.h:123:12
 145: call_function
             at /usr/local/src/conda/python-3.10.12/Python/ceval.c:5893:13
 146: _PyEval_EvalFrameDefault
             at /usr/local/src/conda/python-3.10.12/Python/ceval.c:4198:23
 147: _PyEval_EvalFrame
             at /usr/local/src/conda/python-3.10.12/Include/internal/pycore_ceval.h:46:12
 148: _PyEval_Vector
             at /usr/local/src/conda/python-3.10.12/Python/ceval.c:5067:24
 149: _PyFunction_Vectorcall
             at /usr/local/src/conda/python-3.10.12/Objects/call.c:342:16
 150: _PyObject_VectorcallTstate
             at /usr/local/src/conda/python-3.10.12/Include/cpython/abstract.h:114:11
 151: PyObject_Vectorcall
             at /usr/local/src/conda/python-3.10.12/Include/cpython/abstract.h:123:12
 152: call_function
             at /usr/local/src/conda/python-3.10.12/Python/ceval.c:5893:13
 153: _PyEval_EvalFrameDefault
             at /usr/local/src/conda/python-3.10.12/Python/ceval.c:4198:23
 154: _PyEval_EvalFrame
             at /usr/local/src/conda/python-3.10.12/Include/internal/pycore_ceval.h:46:12
 155: _PyEval_Vector
             at /usr/local/src/conda/python-3.10.12/Python/ceval.c:5067:24
 156: _PyFunction_Vectorcall
             at /usr/local/src/conda/python-3.10.12/Objects/call.c:342:16
 157: _PyObject_VectorcallTstate
             at /usr/local/src/conda/python-3.10.12/Include/cpython/abstract.h:114:11
 158: PyObject_Vectorcall
             at /usr/local/src/conda/python-3.10.12/Include/cpython/abstract.h:123:12
 159: call_function
             at /usr/local/src/conda/python-3.10.12/Python/ceval.c:5893:13
 160: _PyEval_EvalFrameDefault
             at /usr/local/src/conda/python-3.10.12/Python/ceval.c:4198:23
 161: _PyEval_EvalFrame
             at /usr/local/src/conda/python-3.10.12/Include/internal/pycore_ceval.h:46:12
 162: _PyEval_Vector
             at /usr/local/src/conda/python-3.10.12/Python/ceval.c:5067:24
 163: _PyFunction_Vectorcall
             at /usr/local/src/conda/python-3.10.12/Objects/call.c:342:16
 164: _PyObject_VectorcallTstate
             at /usr/local/src/conda/python-3.10.12/Include/cpython/abstract.h:114:11
 165: method_vectorcall
             at /usr/local/src/conda/python-3.10.12/Objects/classobject.c:53:18
 166: _PyObject_VectorcallTstate
             at /usr/local/src/conda/python-3.10.12/Include/cpython/abstract.h:114:11
 167: PyObject_Vectorcall
             at /usr/local/src/conda/python-3.10.12/Include/cpython/abstract.h:123:12
 168: call_function
             at /usr/local/src/conda/python-3.10.12/Python/ceval.c:5893:13
 169: _PyEval_EvalFrameDefault
             at /usr/local/src/conda/python-3.10.12/Python/ceval.c:4181:23
 170: _PyEval_EvalFrame
             at /usr/local/src/conda/python-3.10.12/Include/internal/pycore_ceval.h:46:12
 171: _PyEval_Vector
             at /usr/local/src/conda/python-3.10.12/Python/ceval.c:5067:24
 172: PyEval_EvalCode
             at /usr/local/src/conda/python-3.10.12/Python/ceval.c:1134:12
 173: builtin_exec_impl
             at /usr/local/src/conda/python-3.10.12/Python/bltinmodule.c:1058:13
 174: builtin_exec
             at /usr/local/src/conda/python-3.10.12/Python/clinic/bltinmodule.c.h:371:20
 175: cfunction_vectorcall_FASTCALL
             at /usr/local/src/conda/python-3.10.12/Objects/methodobject.c:430:24
 176: _PyObject_VectorcallTstate
             at /usr/local/src/conda/python-3.10.12/Include/cpython/abstract.h:114:11
 177: PyObject_Vectorcall
             at /usr/local/src/conda/python-3.10.12/Include/cpython/abstract.h:123:12
 178: call_function
             at /usr/local/src/conda/python-3.10.12/Python/ceval.c:5893:13
 179: _PyEval_EvalFrameDefault
             at /usr/local/src/conda/python-3.10.12/Python/ceval.c:4213:19
 180: _PyEval_EvalFrame
             at /usr/local/src/conda/python-3.10.12/Include/internal/pycore_ceval.h:46:12
 181: _PyEval_Vector
             at /usr/local/src/conda/python-3.10.12/Python/ceval.c:5067:24
 182: _PyFunction_Vectorcall
             at /usr/local/src/conda/python-3.10.12/Objects/call.c:342:16
 183: _PyObject_VectorcallTstate
             at /usr/local/src/conda/python-3.10.12/Include/cpython/abstract.h:114:11
 184: PyObject_Vectorcall
             at /usr/local/src/conda/python-3.10.12/Include/cpython/abstract.h:123:12
 185: call_function
             at /usr/local/src/conda/python-3.10.12/Python/ceval.c:5893:13
 186: _PyEval_EvalFrameDefault
             at /usr/local/src/conda/python-3.10.12/Python/ceval.c:4213:19
 187: _PyEval_EvalFrame
             at /usr/local/src/conda/python-3.10.12/Include/internal/pycore_ceval.h:46:12
 188: _PyEval_Vector
             at /usr/local/src/conda/python-3.10.12/Python/ceval.c:5067:24
 189: _PyFunction_Vectorcall
             at /usr/local/src/conda/python-3.10.12/Objects/call.c:342:16
 190: pymain_run_module
             at /usr/local/src/conda/python-3.10.12/Modules/main.c:297:14
 191: pymain_run_python
             at /usr/local/src/conda/python-3.10.12/Modules/main.c:585:21
 192: Py_RunMain
             at /usr/local/src/conda/python-3.10.12/Modules/main.c:670:5
 193: Py_BytesMain
             at /usr/local/src/conda/python-3.10.12/Modules/main.c:1090:12
 194: __libc_start_main
 195: <unknown>
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
---------------------------------------------------------------------------
PanicException                            Traceback (most recent call last)
/tmp/ipykernel_10239/2351293619.py in ?()
     24             .then(pl.col("col1"))
     25             .alias("col1_combined")
     26         )
     27     )
---> 28     print(res)

~/micromamba/envs/medaka/lib/python3.10/site-packages/polars/dataframe/frame.py in ?(self)
   1502     def __str__(self) -> str:
-> 1503         return self._df.as_str()

PanicException: called `Option::unwrap()` on a `None` value
```

</details>

If I remove the definition of the "col1_combined" column, it seems to work correctly:
```python
with pl.StringCache():
    df = pl.DataFrame(
        {
            "col1": [
                np.random.choice(["a", "b", "c", "d"], np.random.randint(1, 5))
                for _ in range(10)
            ],
            "col2": np.random.randint(0, 2, size=10),
        },
        schema={"col1": pl.List(pl.Categorical), "col2": pl.Int64},
    )
    res = (
        df.select(pl.col("col1", "col2"))
        .with_columns(
            pl.col("col1")
            .list.set_intersection(["a", "b", "c"])
            .cast(pl.List(pl.Categorical)) # necessary because https://github.com/pola-rs/polars/issues/11730
            .alias("col1_alt"),
        )
        # .with_columns(
        #     pl.when(pl.col("col2") == 1)
        #     .then(pl.col("col1_alt"))
        #     .when(pl.col("col2") == 0)
        #     .then(pl.col("col1"))
        #     .alias("col1_combined")
        # )
    )
    print(res)
```

### Expected behavior

n/a

### Installed versions

<details>

```
--------Version info---------
Polars:              0.19.8
Index type:          UInt32
Platform:            Linux-3.10.0-1160.95.1.el7.x86_64-x86_64-with-glibc2.17
Python:              3.10.12 | packaged by conda-forge | (main, Jun 23 2023, 22:40:32) [GCC 12.3.0]

----Optional dependencies----
adbc_driver_sqlite:  <not installed>
cloudpickle:         <not installed>
connectorx:          <not installed>
deltalake:           <not installed>
fsspec:              2023.6.0
gevent:              <not installed>
matplotlib:          3.8.0
numpy:               1.26.0
openpyxl:            <not installed>
pandas:              2.1.1
pyarrow:             13.0.0
pydantic:            <not installed>
pyiceberg:           <not installed>
pyxlsb:              <not installed>
sqlalchemy:          2.0.21
xlsx2csv:            <not installed>
xlsxwriter:          <not installed>
```

</details>

**Comment by shenker** [comment]
On polars-u64-idx 0.20.5, I now get a `InvalidOperationError: casting to a non-enum variant with rev map is not supported for the user` error. https://github.com/pola-rs/polars/issues/11730 is still relevant.

**Comment by shenker** [comment]
Closing in favor of a new issue https://github.com/pola-rs/polars/issues/13912
