### ISSUE TITLE
Can't replace list elements with a constant literal using `list.eval(pl.lit(...))`

### ISSUE THREAD

**Issue by shenker** [pola-rs/polars#11739]
### Checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pypi.org/project/polars/) of Polars.

### Reproducible example

```python
import polars as pl
df = pl.DataFrame(
    {
        "col1": [["a", "b", "c"], [], ["a", "d"]],

    },
)
res = (
    df.select(pl.col("col1"))
    .with_columns(
        pl.col("col1")
        .list.eval(pl.lit("c"))
        .alias("col1_alt"),
    )
)
print(res)
```
prints
```
shape: (3, 2)
┌─────────────────┬─────────────────┐
│ col1            ┆ col1_alt        │
│ ---             ┆ ---             │
│ list[str]       ┆ list[list[str]] │
╞═════════════════╪═════════════════╡
│ ["a", "b", "c"] ┆ [["c"]]         │
│ []              ┆ [["c"]]         │
│ ["a", "d"]      ┆ [["c"]]         │
└─────────────────┴─────────────────┘
```

### Issue description

If I want to replace every element of a list by a constant, I thought I could accomplish this using `.list.eval(pl.lit("c"))`. This instead gives me a nested list `[["c"]]` instead. Am I misunderstanding how `list.eval` or `pl.lit` work? 

### Expected behavior

I'm expecting the output
```
shape: (3, 2)
┌─────────────────┬───────────────────┐
│ col1            ┆ col1_alt          │ 
│ ---             ┆ ---               │  
│ list[str]       ┆ list[str]   │  
╞═════════════════╪═══════════════════╡
│ ["a", "b", "c"] ┆ ["c", "c", "c"]   │
│ []              ┆ []                │
│ ["a", "d"]      ┆ ["c", "c"]        │
└─────────────────┴───────────────────┘
```

### Installed versions

<details>

```
--------Version info---------
Polars:              0.19.8
Index type:          UInt32
Platform:            Linux-3.10.0-1160.95.1.el7.x86_64-x86_64-with-glibc2.17
Python:              3.10.12 | packaged by conda-forge | (main, Jun 23 2023, 22:40:32) [GCC 12.3.0]

----Optional dependencies----
adbc_driver_sqlite:  <not installed>
cloudpickle:         <not installed>
connectorx:          <not installed>
deltalake:           <not installed>
fsspec:              2023.6.0
gevent:              <not installed>
matplotlib:          3.8.0
numpy:               1.26.0
openpyxl:            <not installed>
pandas:              2.1.1
pyarrow:             13.0.0
pydantic:            <not installed>
pyiceberg:           <not installed>
pyxlsb:              <not installed>
sqlalchemy:          2.0.21
xlsx2csv:            <not installed>
xlsxwriter:          <not installed>
```

</details>

**Comment by shenker** [comment]
For what it's worth, the above is with the conda-forge build of polars 0.19.8. With the polars-u64-idx (bigidx) 0.19.8 build from pypi, I get the following panic.

<details>

```shell
thread '<unnamed>' panicked at /home/runner/work/polars/polars/crates/polars-lazy/src/dsl/list.rs:119:51:
called `Option::unwrap()` on a `None` value
stack backtrace:
   0: rust_begin_unwind
             at /rustc/e0d7ed1f453fb54578cc96dfea859b0e7be15016/library/std/src/panicking.rs:597:5
   1: core::panicking::panic_fmt
             at /rustc/e0d7ed1f453fb54578cc96dfea859b0e7be15016/library/core/src/panicking.rs:72:14
   2: core::panicking::panic
             at /rustc/e0d7ed1f453fb54578cc96dfea859b0e7be15016/library/core/src/panicking.rs:127:5
   3: polars_lazy::dsl::list::run_on_group_by_engine
   4: <F as polars_plan::dsl::expr_dyn_fn::SeriesUdf>::call_udf
   5: polars_lazy::physical_plan::expressions::apply::ApplyExpr::eval_and_flatten
   6: <polars_lazy::physical_plan::expressions::apply::ApplyExpr as polars_lazy::physical_plan::expressions::PhysicalExpr>::evaluate
   7: <polars_lazy::physical_plan::expressions::alias::AliasExpr as polars_lazy::physical_plan::expressions::PhysicalExpr>::evaluate
   8: polars_lazy::physical_plan::executors::projection_utils::run_exprs_seq
   9: polars_lazy::physical_plan::executors::projection_utils::evaluate_physical_expressions
  10: polars_lazy::physical_plan::executors::stack::StackExec::execute_impl
  11: <polars_lazy::physical_plan::executors::stack::StackExec as polars_lazy::physical_plan::executors::executor::Executor>::execute
  12: polars_lazy::frame::LazyFrame::collect
  13: polars::lazyframe::_::<impl polars::lazyframe::PyLazyFrame>::__pymethod_collect__
  14: pyo3::impl_::trampoline::trampoline
  15: method_vectorcall_NOARGS
             at /usr/local/src/conda/python-3.10.12/Objects/descrobject.c:432:24
  16: _PyObject_VectorcallTstate
             at /usr/local/src/conda/python-3.10.12/Include/cpython/abstract.h:114:11
  17: PyObject_Vectorcall
             at /usr/local/src/conda/python-3.10.12/Include/cpython/abstract.h:123:12
  18: call_function
             at /usr/local/src/conda/python-3.10.12/Python/ceval.c:5893:13
  19: _PyEval_EvalFrameDefault
             at /usr/local/src/conda/python-3.10.12/Python/ceval.c:4198:23
  20: _PyEval_EvalFrame
             at /usr/local/src/conda/python-3.10.12/Include/internal/pycore_ceval.h:46:12
  21: _PyEval_Vector
             at /usr/local/src/conda/python-3.10.12/Python/ceval.c:5067:24
  22: _PyFunction_Vectorcall
             at /usr/local/src/conda/python-3.10.12/Objects/call.c:342:16
  23: PyVectorcall_Call
             at /usr/local/src/conda/python-3.10.12/Objects/call.c:267:24
  24: _PyObject_Call
             at /usr/local/src/conda/python-3.10.12/Objects/call.c:290:16
  25: PyObject_Call
             at /usr/local/src/conda/python-3.10.12/Objects/call.c:317:12
  26: do_call_core
             at /usr/local/src/conda/python-3.10.12/Python/ceval.c:5945:12
  27: _PyEval_EvalFrameDefault
             at /usr/local/src/conda/python-3.10.12/Python/ceval.c:4277:22
  28: _PyEval_EvalFrame
             at /usr/local/src/conda/python-3.10.12/Include/internal/pycore_ceval.h:46:12
  29: _PyEval_Vector
             at /usr/local/src/conda/python-3.10.12/Python/ceval.c:5067:24
  30: _PyFunction_Vectorcall
             at /usr/local/src/conda/python-3.10.12/Objects/call.c:342:16
  31: _PyObject_VectorcallTstate
             at /usr/local/src/conda/python-3.10.12/Include/cpython/abstract.h:114:11
  32: method_vectorcall
             at /usr/local/src/conda/python-3.10.12/Objects/classobject.c:53:18
  33: _PyObject_VectorcallTstate
             at /usr/local/src/conda/python-3.10.12/Include/cpython/abstract.h:114:11
  34: PyObject_Vectorcall
             at /usr/local/src/conda/python-3.10.12/Include/cpython/abstract.h:123:12
  35: call_function
             at /usr/local/src/conda/python-3.10.12/Python/ceval.c:5893:13
  36: _PyEval_EvalFrameDefault
             at /usr/local/src/conda/python-3.10.12/Python/ceval.c:4231:19
  37: _PyEval_EvalFrame
             at /usr/local/src/conda/python-3.10.12/Include/internal/pycore_ceval.h:46:12
  38: _PyEval_Vector
             at /usr/local/src/conda/python-3.10.12/Python/ceval.c:5067:24
  39: _PyFunction_Vectorcall
             at /usr/local/src/conda/python-3.10.12/Objects/call.c:342:16
  40: _PyObject_VectorcallTstate
             at /usr/local/src/conda/python-3.10.12/Include/cpython/abstract.h:114:11
  41: PyObject_Vectorcall
             at /usr/local/src/conda/python-3.10.12/Include/cpython/abstract.h:123:12
  42: call_function
             at /usr/local/src/conda/python-3.10.12/Python/ceval.c:5893:13
  43: _PyEval_EvalFrameDefault
             at /usr/local/src/conda/python-3.10.12/Python/ceval.c:4198:23
  44: _PyEval_EvalFrame
             at /usr/local/src/conda/python-3.10.12/Include/internal/pycore_ceval.h:46:12
  45: _PyEval_Vector
             at /usr/local/src/conda/python-3.10.12/Python/ceval.c:5067:24
  46: PyEval_EvalCode
             at /usr/local/src/conda/python-3.10.12/Python/ceval.c:1134:12
  47: builtin_exec_impl
             at /usr/local/src/conda/python-3.10.12/Python/bltinmodule.c:1058:13
  48: builtin_exec
             at /usr/local/src/conda/python-3.10.12/Python/clinic/bltinmodule.c.h:371:20
  49: cfunction_vectorcall_FASTCALL
             at /usr/local/src/conda/python-3.10.12/Objects/methodobject.c:430:24
  50: _PyObject_VectorcallTstate
             at /usr/local/src/conda/python-3.10.12/Include/cpython/abstract.h:114:11
  51: PyObject_Vectorcall
             at /usr/local/src/conda/python-3.10.12/Include/cpython/abstract.h:123:12
  52: call_function
             at /usr/local/src/conda/python-3.10.12/Python/ceval.c:5893:13
  53: _PyEval_EvalFrameDefault
             at /usr/local/src/conda/python-3.10.12/Python/ceval.c:4213:19
  54: _PyEval_EvalFrame
             at /usr/local/src/conda/python-3.10.12/Include/internal/pycore_ceval.h:46:12
  55: gen_send_ex2
             at /usr/local/src/conda/python-3.10.12/Objects/genobject.c:213:14
  56: _PyEval_EvalFrameDefault
             at /usr/local/src/conda/python-3.10.12/Python/ceval.c:2586:30
  57: _PyEval_EvalFrame
             at /usr/local/src/conda/python-3.10.12/Include/internal/pycore_ceval.h:46:12
  58: gen_send_ex2
             at /usr/local/src/conda/python-3.10.12/Objects/genobject.c:213:14
  59: _PyEval_EvalFrameDefault
             at /usr/local/src/conda/python-3.10.12/Python/ceval.c:2586:30
  60: _PyEval_EvalFrame
             at /usr/local/src/conda/python-3.10.12/Include/internal/pycore_ceval.h:46:12
  61: gen_send_ex2
             at /usr/local/src/conda/python-3.10.12/Objects/genobject.c:213:14
  62: gen_send_ex
             at /usr/local/src/conda/python-3.10.12/Objects/genobject.c:279:9
  63: method_vectorcall_O
             at /usr/local/src/conda/python-3.10.12/Objects/descrobject.c:460:24
  64: _PyObject_VectorcallTstate
             at /usr/local/src/conda/python-3.10.12/Include/cpython/abstract.h:114:11
  65: PyObject_Vectorcall
             at /usr/local/src/conda/python-3.10.12/Include/cpython/abstract.h:123:12
  66: call_function
             at /usr/local/src/conda/python-3.10.12/Python/ceval.c:5893:13
  67: _PyEval_EvalFrameDefault
             at /usr/local/src/conda/python-3.10.12/Python/ceval.c:4198:23
  68: _PyEval_EvalFrame
             at /usr/local/src/conda/python-3.10.12/Include/internal/pycore_ceval.h:46:12
  69: _PyEval_Vector
             at /usr/local/src/conda/python-3.10.12/Python/ceval.c:5067:24
  70: _PyFunction_Vectorcall
             at /usr/local/src/conda/python-3.10.12/Objects/call.c:342:16
  71: _PyObject_VectorcallTstate
             at /usr/local/src/conda/python-3.10.12/Include/cpython/abstract.h:114:11
  72: PyObject_Vectorcall
             at /usr/local/src/conda/python-3.10.12/Include/cpython/abstract.h:123:12
  73: call_function
             at /usr/local/src/conda/python-3.10.12/Python/ceval.c:5893:13
  74: _PyEval_EvalFrameDefault
             at /usr/local/src/conda/python-3.10.12/Python/ceval.c:4213:19
  75: _PyEval_EvalFrame
             at /usr/local/src/conda/python-3.10.12/Include/internal/pycore_ceval.h:46:12
  76: _PyEval_Vector
             at /usr/local/src/conda/python-3.10.12/Python/ceval.c:5067:24
  77: _PyFunction_Vectorcall
             at /usr/local/src/conda/python-3.10.12/Objects/call.c:342:16
  78: _PyObject_VectorcallTstate
             at /usr/local/src/conda/python-3.10.12/Include/cpython/abstract.h:114:11
  79: PyObject_Vectorcall
             at /usr/local/src/conda/python-3.10.12/Include/cpython/abstract.h:123:12
  80: call_function
             at /usr/local/src/conda/python-3.10.12/Python/ceval.c:5893:13
  81: _PyEval_EvalFrameDefault
             at /usr/local/src/conda/python-3.10.12/Python/ceval.c:4198:23
  82: _PyEval_EvalFrame
             at /usr/local/src/conda/python-3.10.12/Include/internal/pycore_ceval.h:46:12
  83: _PyEval_Vector
             at /usr/local/src/conda/python-3.10.12/Python/ceval.c:5067:24
  84: _PyFunction_Vectorcall
             at /usr/local/src/conda/python-3.10.12/Objects/call.c:342:16
  85: _PyObject_VectorcallTstate
             at /usr/local/src/conda/python-3.10.12/Include/cpython/abstract.h:114:11
  86: method_vectorcall
             at /usr/local/src/conda/python-3.10.12/Objects/classobject.c:53:18
  87: PyVectorcall_Call
             at /usr/local/src/conda/python-3.10.12/Objects/call.c:267:24
  88: _PyObject_Call
             at /usr/local/src/conda/python-3.10.12/Objects/call.c:290:16
  89: PyObject_Call
             at /usr/local/src/conda/python-3.10.12/Objects/call.c:317:12
  90: do_call_core
             at /usr/local/src/conda/python-3.10.12/Python/ceval.c:5945:12
  91: _PyEval_EvalFrameDefault
             at /usr/local/src/conda/python-3.10.12/Python/ceval.c:4277:22
  92: _PyEval_EvalFrame
             at /usr/local/src/conda/python-3.10.12/Include/internal/pycore_ceval.h:46:12
  93: _PyEval_Vector
             at /usr/local/src/conda/python-3.10.12/Python/ceval.c:5067:24
  94: _PyFunction_Vectorcall
             at /usr/local/src/conda/python-3.10.12/Objects/call.c:342:16
  95: _PyObject_VectorcallTstate
             at /usr/local/src/conda/python-3.10.12/Include/cpython/abstract.h:114:11
  96: method_vectorcall
             at /usr/local/src/conda/python-3.10.12/Objects/classobject.c:53:18
  97: _PyObject_VectorcallTstate
             at /usr/local/src/conda/python-3.10.12/Include/cpython/abstract.h:114:11
  98: PyObject_Vectorcall
             at /usr/local/src/conda/python-3.10.12/Include/cpython/abstract.h:123:12
  99: call_function
             at /usr/local/src/conda/python-3.10.12/Python/ceval.c:5893:13
 100: _PyEval_EvalFrameDefault
             at /usr/local/src/conda/python-3.10.12/Python/ceval.c:4231:19
 101: _PyEval_EvalFrame
             at /usr/local/src/conda/python-3.10.12/Include/internal/pycore_ceval.h:46:12
 102: gen_send_ex2
             at /usr/local/src/conda/python-3.10.12/Objects/genobject.c:213:14
 103: _PyEval_EvalFrameDefault
             at /usr/local/src/conda/python-3.10.12/Python/ceval.c:2586:30
 104: _PyEval_EvalFrame
             at /usr/local/src/conda/python-3.10.12/Include/internal/pycore_ceval.h:46:12
 105: gen_send_ex2
             at /usr/local/src/conda/python-3.10.12/Objects/genobject.c:213:14
 106: _PyEval_EvalFrameDefault
             at /usr/local/src/conda/python-3.10.12/Python/ceval.c:2586:30
 107: _PyEval_EvalFrame
             at /usr/local/src/conda/python-3.10.12/Include/internal/pycore_ceval.h:46:12
 108: gen_send_ex2
             at /usr/local/src/conda/python-3.10.12/Objects/genobject.c:213:14
 109: _PyEval_EvalFrameDefault
             at /usr/local/src/conda/python-3.10.12/Python/ceval.c:2586:30
 110: _PyEval_EvalFrame
             at /usr/local/src/conda/python-3.10.12/Include/internal/pycore_ceval.h:46:12
 111: gen_send_ex2
             at /usr/local/src/conda/python-3.10.12/Objects/genobject.c:213:14
 112: _PyEval_EvalFrameDefault
             at /usr/local/src/conda/python-3.10.12/Python/ceval.c:2586:30
 113: _PyEval_EvalFrame
             at /usr/local/src/conda/python-3.10.12/Include/internal/pycore_ceval.h:46:12
 114: gen_send_ex2
             at /usr/local/src/conda/python-3.10.12/Objects/genobject.c:213:14
 115: task_step_impl
             at /usr/local/src/conda/python-3.10.12/Modules/_asynciomodule.c:2653:22
 116: task_step
             at /usr/local/src/conda/python-3.10.12/Modules/_asynciomodule.c:2950:11
 117: cfunction_vectorcall_O
             at /usr/local/src/conda/python-3.10.12/Objects/methodobject.c:516:24
 118: _PyObject_VectorcallTstate
             at /usr/local/src/conda/python-3.10.12/Include/cpython/abstract.h:114:11
 119: context_run
             at /usr/local/src/conda/python-3.10.12/Python/context.c:665
 120: cfunction_vectorcall_FASTCALL_KEYWORDS
             at /usr/local/src/conda/python-3.10.12/Objects/methodobject.c:446:24
 121: do_call_core
             at /usr/local/src/conda/python-3.10.12/Python/ceval.c:5917:9
 122: _PyEval_EvalFrameDefault
             at /usr/local/src/conda/python-3.10.12/Python/ceval.c:4277:22
 123: _PyEval_EvalFrame
             at /usr/local/src/conda/python-3.10.12/Include/internal/pycore_ceval.h:46:12
 124: _PyEval_Vector
             at /usr/local/src/conda/python-3.10.12/Python/ceval.c:5067:24
 125: _PyFunction_Vectorcall
             at /usr/local/src/conda/python-3.10.12/Objects/call.c:342:16
 126: _PyObject_VectorcallTstate
             at /usr/local/src/conda/python-3.10.12/Include/cpython/abstract.h:114:11
 127: PyObject_Vectorcall
             at /usr/local/src/conda/python-3.10.12/Include/cpython/abstract.h:123:12
 128: call_function
             at /usr/local/src/conda/python-3.10.12/Python/ceval.c:5893:13
 129: _PyEval_EvalFrameDefault
             at /usr/local/src/conda/python-3.10.12/Python/ceval.c:4198:23
 130: _PyEval_EvalFrame
             at /usr/local/src/conda/python-3.10.12/Include/internal/pycore_ceval.h:46:12
 131: _PyEval_Vector
             at /usr/local/src/conda/python-3.10.12/Python/ceval.c:5067:24
 132: _PyFunction_Vectorcall
             at /usr/local/src/conda/python-3.10.12/Objects/call.c:342:16
 133: _PyObject_VectorcallTstate
             at /usr/local/src/conda/python-3.10.12/Include/cpython/abstract.h:114:11
 134: PyObject_Vectorcall
             at /usr/local/src/conda/python-3.10.12/Include/cpython/abstract.h:123:12
 135: call_function
             at /usr/local/src/conda/python-3.10.12/Python/ceval.c:5893:13
 136: _PyEval_EvalFrameDefault
             at /usr/local/src/conda/python-3.10.12/Python/ceval.c:4198:23
 137: _PyEval_EvalFrame
             at /usr/local/src/conda/python-3.10.12/Include/internal/pycore_ceval.h:46:12
 138: _PyEval_Vector
             at /usr/local/src/conda/python-3.10.12/Python/ceval.c:5067:24
 139: _PyFunction_Vectorcall
             at /usr/local/src/conda/python-3.10.12/Objects/call.c:342:16
 140: _PyObject_VectorcallTstate
             at /usr/local/src/conda/python-3.10.12/Include/cpython/abstract.h:114:11
 141: PyObject_Vectorcall
             at /usr/local/src/conda/python-3.10.12/Include/cpython/abstract.h:123:12
 142: call_function
             at /usr/local/src/conda/python-3.10.12/Python/ceval.c:5893:13
 143: _PyEval_EvalFrameDefault
             at /usr/local/src/conda/python-3.10.12/Python/ceval.c:4198:23
 144: _PyEval_EvalFrame
             at /usr/local/src/conda/python-3.10.12/Include/internal/pycore_ceval.h:46:12
 145: _PyEval_Vector
             at /usr/local/src/conda/python-3.10.12/Python/ceval.c:5067:24
 146: _PyFunction_Vectorcall
             at /usr/local/src/conda/python-3.10.12/Objects/call.c:342:16
 147: _PyObject_VectorcallTstate
             at /usr/local/src/conda/python-3.10.12/Include/cpython/abstract.h:114:11
 148: PyObject_Vectorcall
             at /usr/local/src/conda/python-3.10.12/Include/cpython/abstract.h:123:12
 149: call_function
             at /usr/local/src/conda/python-3.10.12/Python/ceval.c:5893:13
 150: _PyEval_EvalFrameDefault
             at /usr/local/src/conda/python-3.10.12/Python/ceval.c:4198:23
 151: _PyEval_EvalFrame
             at /usr/local/src/conda/python-3.10.12/Include/internal/pycore_ceval.h:46:12
 152: _PyEval_Vector
             at /usr/local/src/conda/python-3.10.12/Python/ceval.c:5067:24
 153: _PyFunction_Vectorcall
             at /usr/local/src/conda/python-3.10.12/Objects/call.c:342:16
 154: _PyObject_VectorcallTstate
             at /usr/local/src/conda/python-3.10.12/Include/cpython/abstract.h:114:11
 155: PyObject_Vectorcall
             at /usr/local/src/conda/python-3.10.12/Include/cpython/abstract.h:123:12
 156: call_function
             at /usr/local/src/conda/python-3.10.12/Python/ceval.c:5893:13
 157: _PyEval_EvalFrameDefault
             at /usr/local/src/conda/python-3.10.12/Python/ceval.c:4198:23
 158: _PyEval_EvalFrame
             at /usr/local/src/conda/python-3.10.12/Include/internal/pycore_ceval.h:46:12
 159: _PyEval_Vector
             at /usr/local/src/conda/python-3.10.12/Python/ceval.c:5067:24
 160: _PyFunction_Vectorcall
             at /usr/local/src/conda/python-3.10.12/Objects/call.c:342:16
 161: _PyObject_VectorcallTstate
             at /usr/local/src/conda/python-3.10.12/Include/cpython/abstract.h:114:11
 162: method_vectorcall
             at /usr/local/src/conda/python-3.10.12/Objects/classobject.c:53:18
 163: _PyObject_VectorcallTstate
             at /usr/local/src/conda/python-3.10.12/Include/cpython/abstract.h:114:11
 164: PyObject_Vectorcall
             at /usr/local/src/conda/python-3.10.12/Include/cpython/abstract.h:123:12
 165: call_function
             at /usr/local/src/conda/python-3.10.12/Python/ceval.c:5893:13
 166: _PyEval_EvalFrameDefault
             at /usr/local/src/conda/python-3.10.12/Python/ceval.c:4181:23
 167: _PyEval_EvalFrame
             at /usr/local/src/conda/python-3.10.12/Include/internal/pycore_ceval.h:46:12
 168: _PyEval_Vector
             at /usr/local/src/conda/python-3.10.12/Python/ceval.c:5067:24
 169: PyEval_EvalCode
             at /usr/local/src/conda/python-3.10.12/Python/ceval.c:1134:12
 170: builtin_exec_impl
             at /usr/local/src/conda/python-3.10.12/Python/bltinmodule.c:1058:13
 171: builtin_exec
             at /usr/local/src/conda/python-3.10.12/Python/clinic/bltinmodule.c.h:371:20
 172: cfunction_vectorcall_FASTCALL
             at /usr/local/src/conda/python-3.10.12/Objects/methodobject.c:430:24
 173: _PyObject_VectorcallTstate
             at /usr/local/src/conda/python-3.10.12/Include/cpython/abstract.h:114:11
 174: PyObject_Vectorcall
             at /usr/local/src/conda/python-3.10.12/Include/cpython/abstract.h:123:12
 175: call_function
             at /usr/local/src/conda/python-3.10.12/Python/ceval.c:5893:13
 176: _PyEval_EvalFrameDefault
             at /usr/local/src/conda/python-3.10.12/Python/ceval.c:4213:19
 177: _PyEval_EvalFrame
             at /usr/local/src/conda/python-3.10.12/Include/internal/pycore_ceval.h:46:12
 178: _PyEval_Vector
             at /usr/local/src/conda/python-3.10.12/Python/ceval.c:5067:24
 179: _PyFunction_Vectorcall
             at /usr/local/src/conda/python-3.10.12/Objects/call.c:342:16
 180: _PyObject_VectorcallTstate
             at /usr/local/src/conda/python-3.10.12/Include/cpython/abstract.h:114:11
 181: PyObject_Vectorcall
             at /usr/local/src/conda/python-3.10.12/Include/cpython/abstract.h:123:12
 182: call_function
             at /usr/local/src/conda/python-3.10.12/Python/ceval.c:5893:13
 183: _PyEval_EvalFrameDefault
             at /usr/local/src/conda/python-3.10.12/Python/ceval.c:4213:19
 184: _PyEval_EvalFrame
             at /usr/local/src/conda/python-3.10.12/Include/internal/pycore_ceval.h:46:12
 185: _PyEval_Vector
             at /usr/local/src/conda/python-3.10.12/Python/ceval.c:5067:24
 186: _PyFunction_Vectorcall
             at /usr/local/src/conda/python-3.10.12/Objects/call.c:342:16
 187: pymain_run_module
             at /usr/local/src/conda/python-3.10.12/Modules/main.c:297:14
 188: pymain_run_python
             at /usr/local/src/conda/python-3.10.12/Modules/main.c:585:21
 189: Py_RunMain
             at /usr/local/src/conda/python-3.10.12/Modules/main.c:670:5
 190: Py_BytesMain
             at /usr/local/src/conda/python-3.10.12/Modules/main.c:1090:12
 191: __libc_start_main
 192: <unknown>
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
---------------------------------------------------------------------------
PanicException                            Traceback (most recent call last)
Cell In[3], line 9
      1 df = pl.DataFrame(
      2     {
      3         "col1": [["a", "b", "c"], [], ["a", "d"]],
      4 
      5     },
      6 )
      7 res = (
      8     df.select(pl.col("col1"))
----> 9     .with_columns(
     10         pl.col("col1")
     11         .list.eval(pl.lit("c"))
     12         .alias("col1_alt"),
     13     )
     14 )
     15 print(res)

File ~/micromamba/envs/medaka/lib/python3.10/site-packages/polars/dataframe/frame.py:7915, in DataFrame.with_columns(self, *exprs, **named_exprs)
   7767 def with_columns(
   7768     self,
   7769     *exprs: IntoExpr | Iterable[IntoExpr],
   7770     **named_exprs: IntoExpr,
   7771 ) -> DataFrame:
   7772     """
   7773     Add columns to this DataFrame.
   7774 
   (...)
   7913 
   7914     """
-> 7915     return self.lazy().with_columns(*exprs, **named_exprs).collect(_eager=True)

File ~/micromamba/envs/medaka/lib/python3.10/site-packages/polars/utils/deprecation.py:96, in deprecate_renamed_parameter.<locals>.decorate.<locals>.wrapper(*args, **kwargs)
     91 @wraps(function)
     92 def wrapper(*args: P.args, **kwargs: P.kwargs) -> T:
     93     _rename_keyword_argument(
     94         old_name, new_name, kwargs, function.__name__, version
     95     )
---> 96     return function(*args, **kwargs)

File ~/micromamba/envs/medaka/lib/python3.10/site-packages/polars/lazyframe/frame.py:1744, in LazyFrame.collect(self, type_coercion, predicate_pushdown, projection_pushdown, simplify_expression, slice_pushdown, comm_subplan_elim, comm_subexpr_elim, no_optimization, streaming, _eager)
   1731     comm_subplan_elim = False
   1733 ldf = self._ldf.optimization_toggle(
   1734     type_coercion,
   1735     predicate_pushdown,
   (...)
   1742     _eager,
   1743 )
-> 1744 return wrap_df(ldf.collect())

PanicException: called `Option::unwrap()` on a `None` value
```

</details>

**Comment by cmdlineluser** [comment]
It's kind of similar to how this only produces a single value:
```python
df.select(pl.lit("foo"))
# shape: (1, 1)
# ┌─────────┐
# │ literal │
# │ ---     │
# │ str     │
# ╞═════════╡
# │ foo     │
# └─────────┘
```
[`.repeat_by()`](https://pola-rs.github.io/polars/py-polars/html/reference/expressions/api/polars.Expr.repeat_by.html#polars.Expr.repeat_by) is one way to do it.
```python
df.with_columns(col1_alt = 
   pl.lit("c").repeat_by(pl.col("col1").list.len())
)
# shape: (3, 2)
# ┌─────────────────┬─────────────────┐
# │ col1            ┆ col1_alt        │
# │ ---             ┆ ---             │
# │ list[str]       ┆ list[str]       │
# ╞═════════════════╪═════════════════╡
# │ ["a", "b", "c"] ┆ ["c", "c", "c"] │
# │ []              ┆ []              │
# │ ["a", "d"]      ┆ ["c", "c"]      │
# └─────────────────┴─────────────────┘
```

**Comment by shenker** [comment]
Thank you for the explanation!
