### ISSUE TITLE
`pl.from_records` doesn't work with records of type `pyodbc.Row`

### ISSUE THREAD

**Issue by neonlogic** [pola-rs/polars#11772]
### Checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pypi.org/project/polars/) of Polars.

### Reproducible example

```python
import pyodbc
import polars as pl

cnxn = pyodbc.connect(
    driver="{SQL Server}",
    server='127.0.0.1'  # address of an existing SQL server
)
cursor = cnxn.cursor()
rows = cursor.execute('SELECT 1 AS ColA, 2 AS ColB').fetchall()

# if this is uncommented, everything works
#rows = [tuple(row) for row in rows]

df = pl.from_records(rows, [col[0] for col in cursor.description])
print(df)

cnxn.close()
```

### Log output

```shell
Traceback (most recent call last):
  File "C:\Users\Xxx\test\test.py", line 14, in <module>
    df = pl.from_records(rows, [col[0] for col in cursor.description])
  File "C:\Users\Xxx\test\.venv\lib\site-packages\polars\convert.py", line 238, in from_records
    return pl.DataFrame._from_records(
  File "C:\Users\Xxx\test\.venv\lib\site-packages\polars\dataframe\frame.py", line 507, in _from_records
    sequence_to_pydf(
  File "C:\Users\Xxx\test\.venv\lib\site-packages\polars\utils\_construction.py", line 902, in sequence_to_pydf
    return _sequence_to_pydf_dispatcher(
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.3056.0_x64__qbz5n2kfra8p0\lib\functools.py", line 889, in wrapper
    return dispatch(args[0].__class__)(*args, **kw)
  File "C:\Users\Xxx\test\.venv\lib\site-packages\polars\utils\_construction.py", line 992, in _sequence_to_pydf_dispatcher
    return to_pydf(**common_params)
  File "C:\Users\Xxx\test\.venv\lib\site-packages\polars\utils\_construction.py", line 1144, in _sequence_of_elements_to_pydf
    data_series = _handle_columns_arg(data_series, columns=column_names)
  File "C:\Users\Xxx\test\.venv\lib\site-packages\polars\utils\_construction.py", line 629, in _handle_columns_arg
    raise ValueError("dimensions of columns arg must match data dimensions")
ValueError: dimensions of columns arg must match data dimensions
```

### Issue description

The `fetchall()` method in pyodbc returns a list of objects of type `pyodbc.Row`.
This type implements the tuple interface, i.e. access by index and the `len()` method.
For more information: https://github.com/mkleehammer/pyodbc/wiki/Row

### Expected behavior

Pandas provides a `pd.DataFrame.from_records()` function that works just fine with `pyodbc.Row`s.

### Installed versions

<details>

```
--------Version info---------
Polars:              0.19.8
Index type:          UInt32
Platform:            Windows-10-10.0.19045-SP0
Python:              3.10.11 (tags/v3.10.11:7d4cc5a, Apr  5 2023, 00:38:17) [MSC v.1929 64 bit (AMD64)]

----Optional dependencies----
adbc_driver_sqlite:  <not installed>
cloudpickle:         <not installed>
connectorx:          <not installed>
deltalake:           <not installed>
fsspec:              <not installed>
gevent:              <not installed>
matplotlib:          <not installed>
numpy:               1.26.0
openpyxl:            <not installed>
pandas:              <not installed>
pyarrow:             <not installed>
pydantic:            <not installed>
pyiceberg:           <not installed>
pyxlsb:              <not installed>
sqlalchemy:          <not installed>
xlsx2csv:            <not installed>
xlsxwriter:          <not installed>
```

</details>

**Comment by deanm0000** [comment]
Why not just use read_database?

**Comment by deanm0000** [comment]
@stinodego given support for databases through `read_database` it seems this could be closed as left to user to convert pyodbc rows to records if they don't want to use native methods.
