### ISSUE TITLE
Thread panic occurs when hive_partitioning is set to true in [feature] cloud.

### ISSUE THREAD

**Issue by allinux** [pola-rs/polars#11809]
### Checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://crates.io/crates/polars) of Polars.

### Reproducible example

```rust
let args = ScanArgsParquet{ hive_partitioning: true, cloud_options: Some(ops), parallel: ParallelStrategy::Auto, ..Default::default() };
let df = LazyFrame::scan_parquet("s3://.../DATE_PARTITION=20220225/*.parquet", args)?
        .collect();
```

### Issue description

#11709 

After applying rev #11709, if you set hive_partitioning to true and build, the following error occurs. This error does not occur on local filesystems.
```
thread '<unnamed>' panicked at /data001/datagov/.cargo/git/checkouts/polars-b0d90607192fd414/2e83540/crates/nano-arrow/src/io/parquet/read/deserialize/mod.rs:142:31:
called `Option::unwrap()` on a `None` value
stack backtrace:
thread '<unnamed>' panicked at /data001/datagov/.cargo/git/checkouts/polars-b0d90607192fd414/2e83540/crates/nano-arrow/src/io/parquet/read/deserialize/mod.rs:142:31:
called `Option::unwrap()` on a `None` value
   0: rust_begin_unwind
             at /rustc/9326de8faf0305dd905b266b4ea0a3b990123a5b/library/std/src/panicking.rs:597:5
   1: core::panicking::panic_fmt
             at /rustc/9326de8faf0305dd905b266b4ea0a3b990123a5b/library/core/src/panicking.rs:72:14
   2: core::panicking::panic
             at /rustc/9326de8faf0305dd905b266b4ea0a3b990123a5b/library/core/src/panicking.rs:127:5
   3: core::option::Option<T>::unwrap
             at /rustc/9326de8faf0305dd905b266b4ea0a3b990123a5b/library/core/src/option.rs:935:21
   4: nano_arrow::io::parquet::read::deserialize::columns_to_iter_recursive
             at /data001/datagov/.cargo/git/checkouts/polars-b0d90607192fd414/2e83540/crates/nano-arrow/src/io/parquet/read/deserialize/mod.rs:142:17
   5: nano_arrow::io::parquet::read::deserialize::column_iter_to_arrays
             at /data001/datagov/.cargo/git/checkouts/polars-b0d90607192fd414/2e83540/crates/nano-arrow/src/io/parquet/read/deserialize/mod.rs:209:9
   6: polars_io::parquet::mmap::to_deserializer
             at /data001/datagov/.cargo/git/checkouts/polars-b0d90607192fd414/2e83540/crates/polars-io/src/parquet/mmap.rs:89:5
   7: polars_io::parquet::read_impl::column_idx_to_series
             at /data001/datagov/.cargo/git/checkouts/polars-b0d90607192fd414/2e83540/crates/polars-io/src/parquet/read_impl.rs:57:16
   8: polars_io::parquet::read_impl::rg_to_dfs_optionally_par_over_columns::{{closure}}::{{closure}}
             at /data001/datagov/.cargo/git/checkouts/polars-b0d90607192fd414/2e83540/crates/polars-io/src/parquet/read_impl.rs:200:25
   9: core::ops::function::impls::<impl core::ops::function::FnMut<A> for &F>::call_mut
             at /rustc/9326de8faf0305dd905b266b4ea0a3b990123a5b/library/core/src/ops/function.rs:272:13
  10: core::ops::function::impls::<impl core::ops::function::FnOnce<A> for &mut F>::call_once
             at /rustc/9326de8faf0305dd905b266b4ea0a3b990123a5b/library/core/src/ops/function.rs:305:13
  11: core::option::Option<T>::map
             at /rustc/9326de8faf0305dd905b266b4ea0a3b990123a5b/library/core/src/option.rs:1075:29
  12: <core::iter::adapters::map::Map<I,F> as core::iter::traits::iterator::Iterator>::next
             at /rustc/9326de8faf0305dd905b266b4ea0a3b990123a5b/library/core/src/iter/adapters/map.rs:103:26
  13: <core::iter::adapters::map::Map<I,F> as core::iter::traits::iterator::Iterator>::next
             at /rustc/9326de8faf0305dd905b266b4ea0a3b990123a5b/library/core/src/iter/adapters/map.rs:103:9
  14: <core::iter::adapters::take_while::TakeWhile<I,P> as core::iter::traits::iterator::Iterator>::next
             at /rustc/9326de8faf0305dd905b266b4ea0a3b990123a5b/library/core/src/iter/adapters/take_while.rs:46:21
  15: <core::iter::adapters::map::Map<I,F> as core::iter::traits::iterator::Iterator>::next
             at /rustc/9326de8faf0305dd905b266b4ea0a3b990123a5b/library/core/src/iter/adapters/map.rs:103:9
  16: alloc::vec::Vec<T,A>::extend_desugared
             at /rustc/9326de8faf0305dd905b266b4ea0a3b990123a5b/library/alloc/src/vec/mod.rs:2849:35
  17: <alloc::vec::Vec<T,A> as alloc::vec::spec_extend::SpecExtend<T,I>>::spec_extend
             at /rustc/9326de8faf0305dd905b266b4ea0a3b990123a5b/library/alloc/src/vec/spec_extend.rs:17:9
  18: <alloc::vec::Vec<T,A> as core::iter::traits::collect::Extend<T>>::extend
             at /rustc/9326de8faf0305dd905b266b4ea0a3b990123a5b/library/alloc/src/vec/mod.rs:2823:9
  19: <rayon::iter::extend::ListVecFolder<T> as rayon::iter::plumbing::Folder<T>>::consume_iter
             at /data001/datagov/.cargo/registry/src/index.crates.io-6f17d22bba15001f/rayon-1.8.0/src/iter/extend.rs:73:9
  20: <rayon::iter::while_some::WhileSomeFolder<C> as rayon::iter::plumbing::Folder<core::option::Option<T>>>::consume_iter
             at /data001/datagov/.cargo/registry/src/index.crates.io-6f17d22bba15001f/rayon-1.8.0/src/iter/while_some.rs:139:21
  21: <rayon::iter::map::MapFolder<C,F> as rayon::iter::plumbing::Folder<T>>::consume_iter
             at /data001/datagov/.cargo/registry/src/index.crates.io-6f17d22bba15001f/rayon-1.8.0/src/iter/map.rs:248:21
  22: <rayon::iter::map::MapFolder<C,F> as rayon::iter::plumbing::Folder<T>>::consume_iter
             at /data001/datagov/.cargo/registry/src/index.crates.io-6f17d22bba15001f/rayon-1.8.0/src/iter/map.rs:248:21
  23: rayon::iter::plumbing::Producer::fold_with
             at /data001/datagov/.cargo/registry/src/index.crates.io-6f17d22bba15001f/rayon-1.8.0/src/iter/plumbing/mod.rs:110:9
  24: rayon::iter::plumbing::bridge_producer_consumer::helper
             at /data001/datagov/.cargo/registry/src/index.crates.io-6f17d22bba15001f/rayon-1.8.0/src/iter/plumbing/mod.rs:438:13
  25: rayon::iter::plumbing::bridge_producer_consumer::helper::{{closure}}
             at /data001/datagov/.cargo/registry/src/index.crates.io-6f17d22bba15001f/rayon-1.8.0/src/iter/plumbing/mod.rs:427:21
  26: rayon_core::join::join_context::call_b::{{closure}}
             at /data001/datagov/.cargo/registry/src/index.crates.io-6f17d22bba15001f/rayon-core-1.12.0/src/join/mod.rs:129:25
  27: rayon_core::job::JobResult<T>::call::{{closure}}
             at /data001/datagov/.cargo/registry/src/index.crates.io-6f17d22bba15001f/rayon-core-1.12.0/src/job.rs:218:41
  28: <core::panic::unwind_safe::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once
```

### Expected behavior

.

### Installed versions

<details>
rustc 1.74.0-beta.2 (9326de8fa 2023-10-13)

[dependencies]
polars = { git = "https://github.com/pola-rs/polars.git", rev = "2e835401895e3916c33395840cb41021f26f7a04", features = ["async", "lazy", "async", "aws", "parquet"] }
</details>

**Comment by ritchie46** [comment]
Can you reproduce this in python? Or have you got some public dataset to reproduce this? This looks very suspect as I don't expect a panic on that point.

**Comment by allinux** [comment]
The error is reproducible in python.
These are the result images of 0.19.8 and 0.19.9 in python.
- 0.19.8 
![polars_1](https://github.com/pola-rs/polars/assets/12976157/856c40db-5baa-4cf1-be3f-27fde73b5257)

- 019.9 (panic occurs)
![polars_2](https://github.com/pola-rs/polars/assets/12976157/a0b8c74a-181a-4c89-bf00-ec643d9cace5)

**Comment by nameexhaustion** [comment]
I think polars tried to read a hive partition column from the row group leading to overflow. There's a chance the current release is broken for hive scans from cloud storage.

```python
>>> lf.schema
OrderedDict([('x', Int32), ('k', Int64)])  # hive column is `k`
>>> lf.select('k').collect()  # select only hive column
shape: (1, 1)
┌─────┐
│ k   │
│ --- │
│ i64 │
╞═════╡
│ 1   │
└─────┘
>>> lf.select('x').collect()  # select only parquet column
shape: (1, 1)
┌─────┐
│ x   │
│ --- │
│ i32 │
╞═════╡
│ 1   │
└─────┘
>>> lf.select('k', 'x').collect()  # select both
thread '<unnamed>' panicked at /home/runner/work/polars/polars/crates/polars-arrow/src/io/parquet/read/deserialize/mod.rs:141:31:
```
