### ISSUE TITLE
Unable to vstack null typed column with typed column

### ISSUE THREAD

**Issue by orlp** [pola-rs/polars#11824]
### Checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pypi.org/project/polars/) of Polars.

### Reproducible example

```python
import polars as pl
a = pl.DataFrame({"x": [3.5]}, schema={"x": pl.Float64})
b = pl.DataFrame({"x": [None]}, schema={"x": pl.Null})
print(a.vstack(b))
```

### Log output

```shell
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/orlp/.localpython/lib/python3.11/site-packages/polars/utils/deprecation.py", line 96, in wrapper
    return function(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/orlp/.localpython/lib/python3.11/site-packages/polars/dataframe/frame.py", line 6248, in vstack
    return self._from_pydf(self._df.vstack(other._df))
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^
polars.exceptions.ShapeError: unable to vstack, dtypes for column "x" don't match: `f64` and `null`
```
```


### Issue description

While `null` might be a distinct type, it is compatible with concatenation with any other type. A lack of this support also breaks things such as inference in the JSON parser.

### Expected behavior

```python
>>> print(a.vstack(b))
shape: (2, 1)
┌──────┐
│ x    │
│ ---  │
│ f64  │
╞══════╡
│ 3.5  │
│ null │
└──────┘```

### Installed versions

0.19.9

**Comment by orlp** [comment]
Note that the problem is a bit more tricky than simply completely null columns, it also applies to a vstack of `List[u64]` and `List[null]` for example.

**Comment by Excidion** [comment]
The same error appears when you `scan_parquet` multiple files via a glob pattern and some files only have null values for a column that others have any other dtype.

```python
import polars as pl

pl.DataFrame({"x": [3.5]}, schema={"x": pl.Float64}).write_parquet("data_a.pq")
pl.DataFrame({"x": [None]}, schema={"x": pl.Null}).write_parquet("data_b.pq")

df = pl.scan_parquet("data_*.pq").collect()
```
Results in
```
polars.exceptions.ShapeError: unable to vstack, dtypes for column "x" don't match: `f64` and `null`
```

**Comment by Excidion** [comment]
@orlp You can achive your expected behavior using:
```python
import polars as pl

a = pl.DataFrame({"x": [3.5]}, schema={"x": pl.Float64})
b = pl.DataFrame({"x": [None]}, schema={"x": pl.Null})

pl.concat([a,b], how="vertical_relaxed")
```

**Comment by orlp** [comment]
@Excidion No, we don't want to do implicit casting here. That would allow things such as concatenating `i32` and `i64`. We need to relax the check to allow `null` to be equivalent to any other type, but allow no other coercions.

**Comment by uditrana** [comment]
@Excidion `vertical_relaxed` can be considerably slower (seems less parallel) than `vertical`. I do think this is an obvious issue that can be fixed. 

That said, I have temporarily solved this problem in my code by detecting all_null columns and casting/dropping them before I do a `pl.concat([a,b], how='vertical')`

**Comment by s-b90** [comment]
This issue was initially met in `read_ndjson` here: https://github.com/pola-rs/polars/issues/11496#issuecomment-1766963339
```python
import io
import polars as pl

text1 = '{"key": [1, 2]}'
text2 = '{"key1": [1, 2]}'


file = io.StringIO(
    '\n'.join([text1 for _ in range(100)]) + 
    '\n' + 
    '\n'.join([text2 for _ in range(100)])
    )
pl.read_ndjson(file, schema={"key": pl.List(pl.UInt32)})
RuntimeError: BindingsError: "lengths don't match: unable to vstack, dtypes for column \"key\" don't match: `list[u32]` and `list[null]`"
```
So basically I can not implement suggested workarounds like `casting/dropping all_null columns` or `using pl.concat([a,b], how="vertical_relaxed")`, because I have ndjson file with dynamic schema.

Maybe someone can suggest temporary solution until this fixed?

**Comment by cmdlineluser** [comment]
@s-b90 Can you read the input as a single string and use the `.str` methods?

```python
(pl.select(json = pl.lit(ndjson).str.split("\n"))
   .explode("json")
   .select(pl.col("json").str.json_extract(infer_schema_length=None))
   .unnest("json")
)

# DeprecationWarning: `json_extract` is deprecated. It has been renamed to `json_decode`.
# shape: (200, 2)
# ┌───────────┬───────────┐
# │ key       ┆ key1      │
# │ ---       ┆ ---       │
# │ list[i64] ┆ list[i64] │
# ╞═══════════╪═══════════╡
# │ [1, 2]    ┆ null      │
# │ [1, 2]    ┆ null      │
# │ [1, 2]    ┆ null      │
# │ [1, 2]    ┆ null      │
# │ …         ┆ …         │
# │ null      ┆ [1, 2]    │
# │ null      ┆ [1, 2]    │
# │ null      ┆ [1, 2]    │
# │ null      ┆ [1, 2]    │
# └───────────┴───────────┘
```

**Comment by s-b90** [comment]
Thank you @cmdlineluser! This works perfect!

**Comment by cmdlineluser** [comment]
@s-b90 Nice one.

Using your example, I did notice some other odd behaviour.

(I removed `schema=` for testing)

For me, it works up until `range(64)`

```python
text1 = '{"key": [1, 2]}'
text2 = '{"key1": [1, 2]}'


file = io.StringIO(
    '\n'.join([text1 for _ in range(64)]) + 
    '\n' + 
    '\n'.join([text2 for _ in range(64)])
)
pl.read_ndjson(file)

# shape: (128, 2)
# ┌───────────┬───────────┐
# │ key       ┆ key1      │
# │ ---       ┆ ---       │
# │ list[i64] ┆ list[i64] │
# ╞═══════════╪═══════════╡
# │ [1, 2]    ┆ null      │
# │ [1, 2]    ┆ null      │
# │ [1, 2]    ┆ null      │
# │ [1, 2]    ┆ null      │
# │ …         ┆ …         │
# │ null      ┆ [1, 2]    │
# │ null      ┆ [1, 2]    │
# │ null      ┆ [1, 2]    │
# │ null      ┆ [1, 2]    │
# └───────────┴───────────┘
```
`range(65)` returns the vstack error, but if I add an extra `\n` it works again.

```python
file = io.StringIO(
    '\n'.join([text1 for _ in range(65)]) + 
    '\n' + 
    '\n'.join([text2 for _ in range(65)])
    + '\n' # new
)
```

This works all the way up to `range(99)`.

At `range(100)` there is no error, but it produces only the `key` column.

I'm not sure if these are all the same underlying problem or not.

**Comment by s-b90** [comment]
I can confirm that. @orlp should we open separate issue for that, or this is related issues?

**Comment by ritchie46** [comment]
I think we should recursively check the types and if the inner type is null. Cast to the proper type JIT.

**Comment by ritchie46** [comment]
@kszlim can you make a separate case for that one. Adding a null to a concrete schema is something I have allowed in #12771. But changing the schema with new incoming data is something that requires more thought.

I would expect a dataset to have a coherent schema, but anything that is produced by pandas is a mess. In the wild you often see alternating `i64` / `f64` schemas in different files.

**Comment by stunlocked1** [comment]
so I created an empty dataframe, how do I add stuff to it?
