### ISSUE TITLE
`pl.read_excel` fails when both `schema_overrides` and `sheet_name` are provided

### ISSUE THREAD

**Issue by mcrumiller** [pola-rs/polars#11850]
### Checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pypi.org/project/polars/) of Polars.

### Reproducible example

Setup: simple `text.xlsx` file with two sheets (both identical):

Sheet 1 | Sheet 2
--------|---------
![image](https://github.com/pola-rs/polars/assets/1896992/259ac2fc-5d93-4c21-ac61-168ad46727bd) | ![image](https://github.com/pola-rs/polars/assets/1896992/e6a3837c-f8f1-41f3-ae59-87ab98cbbef2)

```python
import polars as pl

df = pl.read_excel(
    "test.xlsx",
    schema_overrides={
        "A": pl.UInt8,
        "B": pl.Float32,
        "C": pl.Date,
        "D": pl.Utf8,
    },
    sheet_name=["Sheet1", "Sheet2"] # or sheet_id=0
)
```

### Log output

```shell
file < 128 rows, no statistics determined
no. of chunks: 1 processed by: 1 threads.
Traceback (most recent call last):
  File "C:\Projects\project-brr\scripts\check_excel.py", line 3, in <module>
    df = pl.read_excel(
         ^^^^^^^^^^^^^^
  File "C:\Projects\project-brr\.venv_brr\Lib\site-packages\polars\io\spreadsheet\functions.py", line 242, in read_excel
    return _read_spreadsheet(
           ^^^^^^^^^^^^^^^^^^
  File "C:\Projects\project-brr\.venv_brr\Lib\site-packages\polars\io\spreadsheet\functions.py", line 434, in _read_spreadsheet
    parsed_sheets = {
                    ^
  File "C:\Projects\project-brr\.venv_brr\Lib\site-packages\polars\io\spreadsheet\functions.py", line 435, in <dictcomp>
    name: reader_fn(
          ^^^^^^^^^^
  File "C:\Projects\project-brr\.venv_brr\Lib\site-packages\polars\io\spreadsheet\functions.py", line 756, in _read_spreadsheet_xlsx2csv
    return _csv_buffer_to_frame(
           ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Projects\project-brr\.venv_brr\Lib\site-packages\polars\io\spreadsheet\functions.py", line 548, in _csv_buffer_to_frame
    raise ParameterCollisionError(
polars.exceptions.ParameterCollisionError: cannot specify columns in both `schema_overrides` and `read_csv_options['dtypes']`
```

### Issue description

When an Excel workbook has multiple sheets and `schema_overrides` is provided, you cannot retrieve data from multiple sheets simultaneously.

### Expected behavior

Should return a dict of frames, where the specified columns in each frame have the specified dtypes.

There's another separate issue when multiple sheets have the same column name but different dtypes. As suggested in #11274, it would be nice to be able to provide some structured dtype for multiple sheets.

On a side note, is it much slower to read sheet-by-sheet than multiple sheets at once, i.e. does it require unzipping the Excel file multiple times?

### Installed versions

<details>

```
--------Version info---------
Polars:              0.19.9
Index type:          UInt32
Platform:            Windows-10-10.0.19045-SP0
Python:              3.11.2 (tags/v3.11.2:878ead1, Feb  7 2023, 16:38:35) [MSC v.1934 64 bit (AMD64)]

----Optional dependencies----
adbc_driver_sqlite:  <not installed>
cloudpickle:         <not installed>
connectorx:          0.3.2
deltalake:           <not installed>
fsspec:              <not installed>
gevent:              <not installed>
matplotlib:          3.7.1
numpy:               1.25.2
openpyxl:            3.1.2
pandas:              2.0.3
pyarrow:             11.0.0
pydantic:            <not installed>
pyiceberg:           <not installed>
pyxlsb:              <not installed>
sqlalchemy:          2.0.7
xlsx2csv:            0.8.1
xlsxwriter:          3.0.9
```

</details>

**Comment by mcrumiller** [comment]
@alexander-beedie

**Comment by alexander-beedie** [comment]
> @alexander-beedie 

Thx! Will take care of it this evening.
