### ISSUE TITLE
`pl.read_excel` raise `StopIteration` when `sheet_id` or `sheet_name` is passed but does not exist

### ISSUE THREAD

**Issue by tt4g** [pola-rs/polars#11877]
### Checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pypi.org/project/polars/) of Polars.

### Reproducible example

```python
from io import BytesIO

import polars as pl
from openpyxl import Workbook

# Create dummy workbook in memory.
workbook = Workbook()
buffer = BytesIO()
workbook.save(buffer)

pl.read_excel(buffer, sheet_id=2)
```

### Log output

```shell
pl.read_excel(buffer, sheet_id=2)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "<PATH_TO_VENT>\Lib\site-packages\polars\io\spreadsheet\functions.py", line 242, in read
_excel
    return _read_spreadsheet(
           ^^^^^^^^^^^^^^^^^^
  File "<PATH_TO_VENT>\Lib\site-packages\polars\io\spreadsheet\functions.py", line 450, in _rea
d_spreadsheet
    return next(iter(parsed_sheets.values()))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
StopIteration
```

### Issue description

Thank you for the great library.

I noticed that when reading a single worksheet by passing `sheet_id` or `sheet_name` to `pl.read_excel()`, `StopIteration` is reported if the target worksheet is not found.

The traceback shows the location of the occurrence, the following line triggers `StopIteration`:

https://github.com/pola-rs/polars/blob/eac03a2211591708d0b1d096f33c9a812e23ca03/py-polars/polars/io/spreadsheet/functions.py#L450

If `StopIteration` occurs here, it will create a bug that will cause the loop to terminate unintentionally if the user code is executing `for` loop.
Perhaps it should be fixed as follows
(I am not an expert in Polars and do not know if there is an exception to be used here).

```diff
     if return_multi:
         return parsed_sheets
-    return next(iter(parsed_sheets.values()))
+    sheet = next(iter(parsed_sheets.values()), None)
+    if sheet is None:
+        raise # polars exception here.
+    return sheet
```

### Expected behavior

`raise` other exception.

### Installed versions

<details>

```
>>> pl.show_versions()
--------Version info---------
Polars:              0.19.9
Index type:          UInt32
Platform:            Windows-10-10.0.17763-SP0
Python:              3.12.0 (tags/v3.12.0:0fb18b0, Oct  2 2023, 13:03:39) [MSC v.1935 64 bit (AMD64)]

----Optional dependencies----
adbc_driver_sqlite:  <not installed>
cloudpickle:         <not installed>
connectorx:          <not installed>
deltalake:           <not installed>
fsspec:              <not installed>
gevent:              <not installed>
matplotlib:          <not installed>
numpy:               <not installed>
openpyxl:            3.0.10
pandas:              <not installed>
pyarrow:             <not installed>
pydantic:            <not installed>
pyiceberg:           <not installed>
pyxlsb:              <not installed>
sqlalchemy:          <not installed>
xlsx2csv:            0.8.1
xlsxwriter:          <not installed>
```

</details>

**Comment by alexander-beedie** [comment]
Thanks for the report 👍
