### ISSUE TITLE
PanicException when trying to sink Parquet on a LazyFrame with cumsum

### ISSUE THREAD

**Issue by frankrd** [pola-rs/polars#11890]
### Checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pypi.org/project/polars/) of Polars.

### Reproducible example

```python
import polars as pl

lf = pl.LazyFrame(
    {
        "a": [1, 2, 3, 4],
    }
).with_columns([pl.cumsum("a").alias("cs_a")])

lf.sink_parquet(path="lf_sink.parquet")  # This raises a PanicException

```

### Log output

```shell
thread '<unnamed>' panicked at /Users/runner/work/polars/polars/crates/polars-lazy/src/physical_plan/planner/lp.rs:156:50:
sink_Parquet(ParquetWriteOptions { compression: Zstd(None), statistics: false, row_group_size: None, data_pagesize_limit: None, maintain_order: true }) not yet supported in standard engine. Use 'collect().write_parquet()'
stack backtrace:
   0: _rust_begin_unwind
   1: core::panicking::panic_fmt
   2: polars_lazy::physical_plan::planner::lp::create_physical_plan
   3: polars_lazy::frame::LazyFrame::prepare_collect
   4: polars::lazyframe::PyLazyFrame::sink_parquet
   5: polars::lazyframe::_::<impl polars::lazyframe::PyLazyFrame>::__pymethod_sink_parquet__
   6: pyo3::impl_::trampoline::trampoline
   7: polars::lazyframe::_::_::__INVENTORY::trampoline
   8: _cfunction_call
   9: __PyObject_MakeTpCall
  10: _call_function
  11: __PyEval_EvalFrameDefault
  12: __PyEval_Vector
  13: _method_vectorcall
  14: _call_function
  15: __PyEval_EvalFrameDefault
  16: __PyEval_Vector
  17: _run_mod
  18: __PyRun_SimpleFileObject
  19: __PyRun_AnyFileObject
  20: _Py_RunMain
  21: _pymain_main
  22: _main
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
Traceback (most recent call last):
  File "...example.py", line 13, in <module>
    lf.sink_parquet(path="lf_sink.parquet")
  File "...lib/python3.10/site-packages/polars/lazyframe/frame.py", line 2030, in sink_parquet
    return lf.sink_parquet(
pyo3_runtime.PanicException: sink_Parquet(ParquetWriteOptions { compression: Zstd(None), statistics: false, row_group_size: None, data_pagesize_limit: None, maintain_order: true }) not yet supported in standard engine. Use 'collect().write_parquet()'
```

### Issue description

When attempting to sink a Parquet file from a LazyFrame which has a `cumsum` column added, I encounter a `PanicException`. The traceback suggests using `collect().write_parquet()` as a potential workaround, but I believe this should be directly supported for lazy evaluations.

### Expected behavior

I expect the code to seamlessly compute the cumulative sum for column `"a"` and store the result alongside the original data in a new Parquet file named `lf_sink.parquet`. The resulting Parquet file should have two columns: 

- `"a"` containing values `[1, 2, 3, 4]`
- `"cs_a"` representing the cumulative sum of `"a"`, containing values `[1, 3, 6, 10]`

No errors or exceptions should be raised during this process, and the operation should be performed lazily without the need to collect the data before writing to Parquet.

### Installed versions

<details>

```
--------Version info---------
Polars:              0.19.9
Index type:          UInt32
Platform:            macOS-14.0-arm64-arm-64bit
Python:              3.10.12 | packaged by conda-forge | (main, Jun 23 2023, 22:41:52) [Clang 15.0.7 ]

----Optional dependencies----
adbc_driver_sqlite:  <not installed>
cloudpickle:         <not installed>
connectorx:          <not installed>
deltalake:           <not installed>
fsspec:              <not installed>
gevent:              <not installed>
matplotlib:          3.7.2
numpy:               1.25.2
openpyxl:            <not installed>
pandas:              2.0.3
pyarrow:             10.0.1
pydantic:            2.4.2
pyiceberg:           <not installed>
pyxlsb:              <not installed>
sqlalchemy:          2.0.20
xlsx2csv:            <not installed>
xlsxwriter:          <not installed>
```

</details>

**Comment by ritchie46** [comment]
As the panic states we don't support this query with `sink_parquet`.
