### ISSUE TITLE
pl.sum_horizontal returns expression with wrong column name

### ISSUE THREAD

**Issue by rajeee** [pola-rs/polars#12098]
### Checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pypi.org/project/polars/) of Polars.

### Reproducible example

```python
mydf = pl.DataFrame({'id': [1, 2, 3], 'value1': [1, 2, 3], 'value2': [1, 2, 3]}).lazy()
mydf.select(pl.sum_horizontal(['value1', 'value2'])).sum().collect()  # Raises ColumnNotFoundError: value1
```

### Log output

```shell
Traceback (most recent call last):
  File "<redacted>, line 4, in <module>
    mydf.select(pl.sum_horizontal(['value1', 'value2'])).sum().collect()
  File "<redacted>/mambaforge/envs/<redacted>/lib/python3.10/site-packages/polars/utils/deprecation.py", line 96, in wrapper
    return function(*args, **kwargs)
  File "<redacted>mambaforge/envs/<redacted>/lib/python3.10/site-packages/polars/lazyframe/frame.py", line 1788, in collect
    return wrap_df(ldf.collect())
polars.exceptions.ColumnNotFoundError: value1
```

### Issue description

```
mydf = pl.DataFrame({'id': [1, 2, 3], 'value1': [1, 2, 3], 'value2': [1, 2, 3]}).lazy()
mydf.select(pl.sum_horizontal(['value1', 'value2'])).sum().collect()
```

It seems like the sum() is expecting `mydf.select(pl.sum_horizontal(['value1', 'value2']))` to have `value1` column, but in reality it doesn't.

```
mydf.select(pl.sum_horizontal(['value1', 'value2'])).collect().columns
# ['sum']
```

However, if I don't do collect, the LazyFrame does think there is `'value1'` column. 

```
mydf.select(pl.sum_horizontal(['value1', 'value2'])).columns
# ['value1']
```

I tested this with several past versions, and this error seems to be introduced in polars version 0.19.9. In version 0.19.8, the LazyFrame does return 'sum' as the column name and things work as expected and there is no exception. 
```
# version 0.19.8 and before
mydf.select(pl.sum_horizontal(['value1', 'value2'])).columns
# ['sum']
```

So, it appears to me that it is a problem with the LazyFrame (`mydf.select(pl.sum_horizontal(['value1', 'value2']))`) returning `['value1'] `as the column although, during collect, the LazyFrame will actually return ['sum'] as the column name.

### Expected behavior

Expected behavior is not to raise an exception and return 
![image](https://github.com/pola-rs/polars/assets/12487392/64dc3f02-e024-417f-9cfb-ad57c934c20f)

### Installed versions

<details>

```
Polars:              0.19.11
Index type:          UInt32
Platform:            macOS-12.7-arm64-arm-64bit
Python:              3.10.13 | packaged by conda-forge | (main, Oct 26 2023, 18:09:17) [Clang 16.0.6 ]

----Optional dependencies----
adbc_driver_sqlite:  <not installed>
cloudpickle:         <not installed>
connectorx:          <not installed>
deltalake:           <not installed>
fsspec:              2023.10.0
gevent:              <not installed>
matplotlib:          <not installed>
numpy:               1.26.1
openpyxl:            <not installed>
pandas:              2.1.2
pyarrow:             13.0.0
pydantic:            1.10.13
pyiceberg:           <not installed>
pyxlsb:              <not installed>
sqlalchemy:          1.4.46
xlsx2csv:            <not installed>
xlsxwriter:          <not installed>
```
</details>

<details>

```
--------Version info---------
Polars:              0.19.12
Index type:          UInt32
Platform:            macOS-12.7-arm64-arm-64bit
Python:              3.10.13 | packaged by conda-forge | (main, Oct 26 2023, 18:09:17) [Clang 16.0.6 ]

----Optional dependencies----
adbc_driver_sqlite:  <not installed>
cloudpickle:         <not installed>
connectorx:          <not installed>
deltalake:           <not installed>
fsspec:              2023.10.0
gevent:              <not installed>
matplotlib:          <not installed>
numpy:               1.26.1
openpyxl:            <not installed>
pandas:              2.1.2
pyarrow:             13.0.0
pydantic:            1.10.13
pyiceberg:           <not installed>
pyxlsb:              <not installed>
sqlalchemy:          1.4.46
xlsx2csv:            <not installed>
xlsxwriter:          <not installed>
```

</details>

**Comment by cmdlineluser** [comment]
#11812 was somewhat of a similar situation.

There was an `.alias("sum")` that was removed, however there is still:

https://github.com/pola-rs/polars/blob/6bc3896216b05ffcff54f6902148d79c36ca08cd/crates/polars-ops/src/series/ops/horizontal.rs#L31

```python
df.select(pl.sum_horizontal('value1', 'value2'))
# <LazyFrame [1 col, {"value1": Int64}] at 0x133AA46D0>
```
```python
df.select(pl.sum_horizontal('value1', 'value2')).collect().lazy()
# <LazyFrame [1 col, {"sum": Int64}] at 0x133586350>
```
`Expr.sum()` is still okay
```python
df.select(pl.sum_horizontal('value1', 'value2').sum()).collect()
# shape: (1, 1)
# ┌─────┐
# │ sum │
# │ --- │
# │ i64 │
# ╞═════╡
# │ 12  │
# └─────┘
```
It seems all `*_horizontal` functions are affected:
```python
df.select(pl.all_horizontal('value1', 'value2')).sum().collect()
# ComputeError: column 'all' not available in schema Schema:
# name: id, data type: Int64
# name: value1, data type: Int64
# name: value2, data type: Int64
```

**Comment by deanm0000** [comment]
I confirm @edavisau comment that this works now.
