### ISSUE TITLE
6 tests failing on WSL

### ISSUE THREAD

**Issue by Wainberg** [pola-rs/polars#12103]
### Checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pypi.org/project/polars/) of Polars.

### Reproducible example

Following the steps [here](https://pola-rs.github.io/polars/development/contributing/#setting-up-your-local-environment.), I forked and cloned the latest version of polars (6bc3896216b05ffcff54f6902148d79c36ca08cd) and ran `make test` on an up-to-date WSL installation running Ubuntu 22.04 LTS. 

### Issue description

Here's the output of `make test`: 

```
[...]
📦 Built wheel for abi3 Python ≥ 3.8 to /tmp/.tmpwuv183/polars-0.19.12-cp38-abi3-linux_x86_64.whl
🛠 Installed polars-0.19.12
../.venv/bin/pytest -n auto --dist loadgroup
========================================================================= test session starts =========================================================================
platform linux -- Python 3.11.6, pytest-7.4.0, pluggy-1.3.0
rootdir: /mnt/c/Users/Wainberg/Documents/polars/py-polars
configfile: pyproject.toml
plugins: hypothesis-6.88.1, cov-4.1.0, xdist-3.3.1
8 workers [3853 items]
............................................................................................................................................................... [  4%]
............................................................................................................................................................... [  8%]
............................................................................................................................................................... [ 12%]
.....................F......................................................................................................................................... [ 16%]
.............F................................................................................................................................................. [ 20%]
............................................................................................................................................................... [ 24%]
............................................................................................................................................................... [ 28%]
............................................................................................................................................................... [ 33%]
......................................................s........................................................................................................ [ 37%]
............................................................................................................................................................... [ 41%]
............................................................................................................................................................... [ 45%]
............................................................................................................................................................... [ 49%]
..........................................................................................................................F.................................... [ 53%]
....................................................................x.......x...................................F.............................................. [ 57%]
..............................................................................................................................F................................ [ 61%]
............................................................................................................................................................... [ 66%]
............................................................................................................................................................... [ 70%]
...........................................................................................................................s..s................................. [ 74%]
............................................................................................................................................................... [ 78%]
............................................................................................................................................................... [ 82%]
............................................................................................................................................................... [ 86%]
............................................................................................................................................................... [ 90%]
................................................................................x.........................................................................s.... [ 94%]
................................................................................................................................................................. [ 99%]
.........................F........                                                                                                                              [100%]
============================================================================== FAILURES ===============================================================================
____________________________________________________________________ test_null_array_print_format _____________________________________________________________________
[gw4] linux -- Python 3.11.6 /mnt/c/Users/Wainberg/Documents/polars/.venv/bin/python
tests/unit/test_constructors.py:636: in test_null_array_print_format
    assert (
E   AssertionError: assert ' a    \n nul...shape: (2, 1)' == 'shape: (2, 1...l │\n└──────┘'
E     +  a
E     +  null
E     +  null
E     - shape: (2, 1)
E     ?              -
E     + shape: (2, 1)
E     - ┌──────┐...
E
E     ...Full output truncated (7 lines hidden), use '-vv' to show
______________________________________________________________________ test_dataframe_from_repr _______________________________________________________________________
[gw1] linux -- Python 3.11.6 /mnt/c/Users/Wainberg/Documents/polars/.venv/bin/python
tests/unit/test_interop.py:870: in test_dataframe_from_repr
    df = cast(pl.DataFrame, pl.from_repr(repr(frame)))
polars/convert.py:439: in from_repr
    raise ValueError("input string does not contain DataFrame or Series")
E   ValueError: input string does not contain DataFrame or Series
_________________________________________________________________________ test_read_empty_csv _________________________________________________________________________
[gw4] linux -- Python 3.11.6 /mnt/c/Users/Wainberg/Documents/polars/.venv/bin/python
tests/unit/io/test_csv.py:1383: in test_read_empty_csv
    pl.read_csv(io_files_path / "empty.csv")
polars/io/csv/functions.py:366: in read_csv
    df = pl.DataFrame._read_csv(
polars/dataframe/frame.py:772: in _read_csv
    self._df = PyDataFrame.read_csv(
E   OSError: Exec format error (os error 8)
____________________________________________________________________ test_batched_csv_reader_empty ____________________________________________________________________
[gw7] linux -- Python 3.11.6 /mnt/c/Users/Wainberg/Documents/polars/.venv/bin/python
tests/unit/io/test_csv.py:1252: in test_batched_csv_reader_empty
    pl.read_csv_batched(source=empty_csv)
polars/io/csv/functions.py:667: in read_csv_batched
    return BatchedCsvReader(
polars/io/csv/batched_reader.py:78: in __init__
    self._reader = PyBatchedCsv.new(
E   OSError: Exec format error (os error 8)
_________________________________________________________________________ test_scan_empty_csv _________________________________________________________________________
[gw5] linux -- Python 3.11.6 /mnt/c/Users/Wainberg/Documents/polars/.venv/bin/python
tests/unit/io/test_lazy_csv.py:35: in test_scan_empty_csv
    lf = pl.scan_csv(io_files_path / "empty.csv", raise_if_empty=False)
polars/io/csv/functions.py:911: in scan_csv
    return pl.LazyFrame._scan_csv(
polars/lazyframe/frame.py:372: in _scan_csv
    self._ldf = PyLazyFrame.new_from_csv(
E   pyo3_runtime.PanicException: could not mmap file: Io(Os { code: 8, kind: Uncategorized, message: "Exec format error" })
------------------------------------------------------------------------ Captured stderr call -------------------------------------------------------------------------
thread '<unnamed>' panicked at /mnt/c/Users/Wainberg/Documents/polars/crates/polars-plan/src/logical_plan/builder.rs:324:56:
could not mmap file: Io(Os { code: 8, kind: Uncategorized, message: "Exec format error" })
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
______________________________________________________________________ test_scan_empty_csv_10818 ______________________________________________________________________
[gw4] linux -- Python 3.11.6 /mnt/c/Users/Wainberg/Documents/polars/.venv/bin/python
tests/unit/streaming/test_streaming_io.py:181: in test_scan_empty_csv_10818
    df = pl.scan_csv(empty_file_path, raise_if_empty=False).collect(streaming=True)
polars/io/csv/functions.py:911: in scan_csv
    return pl.LazyFrame._scan_csv(
polars/lazyframe/frame.py:372: in _scan_csv
    self._ldf = PyLazyFrame.new_from_csv(
E   pyo3_runtime.PanicException: could not mmap file: Io(Os { code: 8, kind: Uncategorized, message: "Exec format error" })
------------------------------------------------------------------------ Captured stderr call -------------------------------------------------------------------------
thread '<unnamed>' panicked at /mnt/c/Users/Wainberg/Documents/polars/crates/polars-plan/src/logical_plan/builder.rs:324:56:
could not mmap file: Io(Os { code: 8, kind: Uncategorized, message: "Exec format error" })
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
======================================================================= short test summary info =======================================================================
FAILED tests/unit/test_constructors.py::test_null_array_print_format - AssertionError: assert ' a    \n nul...shape: (2, 1)' == 'shape: (2, 1...l │\n└──────┘'
FAILED tests/unit/test_interop.py::test_dataframe_from_repr - ValueError: input string does not contain DataFrame or Series
FAILED tests/unit/io/test_csv.py::test_read_empty_csv - OSError: Exec format error (os error 8)
FAILED tests/unit/io/test_csv.py::test_batched_csv_reader_empty - OSError: Exec format error (os error 8)
FAILED tests/unit/io/test_lazy_csv.py::test_scan_empty_csv - pyo3_runtime.PanicException: could not mmap file: Io(Os { code: 8, kind: Uncategorized, message: "Exec format error" })
FAILED tests/unit/streaming/test_streaming_io.py::test_scan_empty_csv_10818@streaming - pyo3_runtime.PanicException: could not mmap file: Io(Os { code: 8, kind: Uncategorized, message: "Exec format error" })
======================================================== 6 failed, 3840 passed, 4 skipped, 3 xfailed in 59.24s ========================================================
make: *** [Makefile:76: test] Error 1
```

### Installed versions

<details>

```
--------Version info---------
Polars:              0.19.12
Index type:          UInt32
Platform:            Linux-4.4.0-22621-Microsoft-x86_64-with-glibc2.35
Python:              3.11.6 | packaged by conda-forge | (main, Oct  3 2023, 10:40:35) [GCC 12.3.0]

----Optional dependencies----
adbc_driver_sqlite:  0.7.0
cloudpickle:         3.0.0
connectorx:          0.3.2
deltalake:           0.10.1
fsspec:              2023.10.0
gevent:              23.9.1
matplotlib:          3.8.0
numpy:               1.26.1
openpyxl:            3.1.2
pandas:              2.1.2
pyarrow:             13.0.0
pydantic:            2.4.2
pyiceberg:           0.5.0
pyxlsb:              1.0.10
sqlalchemy:          2.0.22
xlsx2csv:            0.8.1
xlsxwriter:          3.1.9
```

</details>

**Comment by stinodego** [comment]
You probably need to update your `rustup`. I run WSL and am having no problems.

**Comment by MarcoGorelli** [comment]
same here - closing then, I'd suggest you join the discord for help with development

**Comment by stinodego** [comment]
I don't know if that is the issue here. You can try WSL2. In any case, it is recommended to really use the WSL filesystem rather than the Windows one.
