### ISSUE TITLE
LazyFrame crash "failed to determine supertype" when multiplying column derived from Array

### ISSUE THREAD

**Issue by eric-skydio** [pola-rs/polars#12123]
### Checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pypi.org/project/polars/) of Polars.

### Reproducible example

```python
df = pl.LazyFrame(
    [
        pl.Series("a", [[1., 3.], [2., 5.]]),
        pl.Series("b", [1.0, 2.0])
    ],
    schema_overrides={
        "a": pl.Array(inner=pl.Float64, width=2),
    },
)

print(df.collect())

df = df.with_columns(pl.col('a').arr.max().alias('c'))

print(df.collect())

df = df.with_columns(pl.col('c') * pl.col('b'))

print(df.collect())
```

```
shape: (2, 2)
┌───────────────┬─────┐
│ a             ┆ b   │
│ ---           ┆ --- │
│ array[f64, 2] ┆ f64 │
╞═══════════════╪═════╡
│ [1.0, 3.0]    ┆ 1.0 │
│ [2.0, 5.0]    ┆ 2.0 │
└───────────────┴─────┘
shape: (2, 3)
┌───────────────┬─────┬─────┐
│ a             ┆ b   ┆ c   │
│ ---           ┆ --- ┆ --- │
│ array[f64, 2] ┆ f64 ┆ f64 │
╞═══════════════╪═════╪═════╡
│ [1.0, 3.0]    ┆ 1.0 ┆ 3.0 │
│ [2.0, 5.0]    ┆ 2.0 ┆ 5.0 │
└───────────────┴─────┴─────┘
---------------------------------------------------------------------------
ComputeError                              Traceback (most recent call last)
Cell In[202], line 19
     15 print(df.collect())
     17 df = df.with_columns(pl.col('c') * pl.col('b'))
---> 19 print(df.collect())

File /mnt/old_disk/bazel-user-root/24e9e5e639d4f3b275afc3e229396ae9/execroot/aircam/bazel-out/k8-fastbuild/bin/tools/cloud_api/client_utils/repl.notebook3.runfiles/pip3_workstation_polars/site-packages/polars/utils/deprecation.py:100, in deprecate_renamed_parameter.<locals>.decorate.<locals>.wrapper(*args, **kwargs)
     95 @wraps(function)
     96 def wrapper(*args: P.args, **kwargs: P.kwargs) -> T:
     97     _rename_keyword_argument(
     98         old_name, new_name, kwargs, function.__name__, version
     99     )
--> 100     return function(*args, **kwargs)

File /mnt/old_disk/bazel-user-root/24e9e5e639d4f3b275afc3e229396ae9/execroot/aircam/bazel-out/k8-fastbuild/bin/tools/cloud_api/client_utils/repl.notebook3.runfiles/pip3_workstation_polars/site-packages/polars/lazyframe/frame.py:1787, in LazyFrame.collect(self, type_coercion, predicate_pushdown, projection_pushdown, simplify_expression, slice_pushdown, comm_subplan_elim, comm_subexpr_elim, no_optimization, streaming, _eager)
   1774     comm_subplan_elim = False
   1776 ldf = self._ldf.optimization_toggle(
   1777     type_coercion,
   1778     predicate_pushdown,
   (...)
   1785     _eager,
   1786 )
-> 1787 return wrap_df(ldf.collect())

ComputeError: failed to determine supertype of array[f64, 2] and f64

Error originated just after this operation:
 WITH_COLUMNS:
 [col("a").arr.max().alias("c")]
  DF ["a", "b"]; PROJECT */2 COLUMNS; SELECTION: "None"
```

### Log output

```shell
(note: the environment variable didn't seem to change anything)

Traceback (most recent call last):
  File "polars_err.py", line 18, in <module>
    print(df.collect())
  File "/home/skydio/aircam2/build/python3_venv/lib/python3.8/site-packages/polars/utils/deprecation.py", line 100, in wrapper
    return function(*args, **kwargs)
  File "/home/skydio/aircam2/build/python3_venv/lib/python3.8/site-packages/polars/lazyframe/frame.py", line 1787, in collect
    return wrap_df(ldf.collect())
polars.exceptions.ComputeError: failed to determine supertype of array[f64, 2] and f64

Error originated just after this operation:
 WITH_COLUMNS:
 [col("a").arr.max().alias("c")]
  DF ["a", "b"]; PROJECT */2 COLUMNS; SELECTION: "None"
```

### Issue description

This issue appears to happen only when using a LazyFrame, and seems to have something to do with the query optimizer? 

### Expected behavior

I would expect multiplying "b" and "c" to work, just like if they were any other two Float64 columns.

### Installed versions

<details>

```
--------Version info---------
Polars:              0.19.12
Index type:          UInt32
Platform:            Linux-5.4.0-150-generic-x86_64-with-glibc2.27
Python:              3.8.16 (default, Dec  7 2022, 01:12:13) 
[GCC 7.5.0]

----Optional dependencies----
adbc_driver_sqlite:  <not installed>
cloudpickle:         <not installed>
connectorx:          <not installed>
deltalake:           <not installed>
fsspec:              <not installed>
gevent:              <not installed>
matplotlib:          3.6.2
numpy:               1.21.6
openpyxl:            <not installed>
pandas:              1.4.4
pyarrow:             <not installed>
pydantic:            <not installed>
pyiceberg:           <not installed>
pyxlsb:              <not installed>
sqlalchemy:          <not installed>
xlsx2csv:            <not installed>
xlsxwriter:          <not installed>
```

</details>

**Comment by eric-skydio** [comment]
Thanks for the fast response! How likely is the array functionality to get additional development in the near future? At minimum, having `.get(i)` implemented or at least a `.to_list()` expression so that we can use all the existing List tooling would be awesome.

**Comment by stinodego** [comment]
> How likely is the array functionality to get additional development in the near future?

Likely! Personally, I think it's very important to make our existing data types complete and reliable. It's one of my priorities.

I the meantime, you can already cast your arrays to a `List` to get access to that namespace.

**Comment by eric-skydio** [comment]
Thanks. `.cast(pl.List(pl.Float64)).list.get(0)` did exactly what I want, and `df.schema` works to get the element type in more complicated cases.
