### ISSUE TITLE
Panick when initializing Series with nested `Array` dtype

### ISSUE THREAD

**Issue by stinodego** [pola-rs/polars#12137]
### Checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pypi.org/project/polars/) of Polars.

### Reproducible example

```python
import polars as pl

s = pl.Series(
    [[[1, 2], [3, 4]], [[5, 6], [7, 8]]],
    dtype=pl.List(pl.Array(inner=pl.Int8, width=2)),
)
# pyo3_runtime.PanicException: not implemented for dtype Array(Int8, 2)
```

Also happens in a struct:

```python
s = pl.Series(
    [{"x": [[1, 2], [3, 4]]}],
    dtype=pl.Struct({"x": pl.Array(inner=pl.Int8, width=2)}),
)
# pyo3_runtime.PanicException: not implemented for dtype Array(Int8, 2)
```

### Log output

```shell
thread '<unnamed>' panicked at /home/stijn/code/polars/crates/polars-core/src/chunked_array/builder/list/mod.rs:160:16:
not implemented for dtype Array(Int8, 2)
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
Traceback (most recent call last):
  File "/home/stijn/code/polars/py-polars/repro.py", line 6, in <module>
    s = pl.Series(
        ^^^^^^^^^^
  File "/home/stijn/code/polars/py-polars/polars/series/series.py", line 284, in __init__
    self._s = sequence_to_pyseries(
              ^^^^^^^^^^^^^^^^^^^^^
  File "/home/stijn/code/polars/py-polars/polars/utils/_construction.py", line 546, in sequence_to_pyseries
    srs = sequence_from_anyvalue_and_dtype_or_object(name, values, dtype)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/stijn/code/polars/py-polars/polars/utils/_construction.py", line 286, in sequence_from_anyvalue_and_dtype_or_object
    return PySeries.new_from_anyvalues_and_dtype(name, values, dtype, strict=True)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
pyo3_runtime.PanicException: not implemented for dtype Array(Int8, 2)
```

### Issue description

This should work.

### Expected behavior

Series should be initialized as expected.

### Installed versions

main branch

**Comment by stinodego** [comment]
@reswqa I think this can be closed after https://github.com/pola-rs/polars/pull/12148 , right?

**Comment by stinodego** [comment]
Struct version also seems to work now.
