### ISSUE TITLE
DataFrame constructor ignores datetime

### ISSUE THREAD

**Issue by sezanzeb** [pola-rs/polars#12151]
### Checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pypi.org/project/polars/) of Polars.

### Reproducible example

```python
import polars as pl
import datetime

time_1 = datetime.datetime(
	year=2023,
	month=10,
	day=10,
	tzinfo=datetime.UTC,
)

time_2 = datetime.datetime(
	year=2023,
	month=10,
	day=9,
	tzinfo=datetime.UTC,
)

df = pl.DataFrame([{
	"time": time_1
}])

df.filter(pl.col("time") > time_2)
```

```
>>> df
shape: (1, 1)
┌─────────────────────┐
│ time                │
│ ---                 │
│ datetime[μs]        │
╞═════════════════════╡
│ 2023-10-10 00:00:00 │
└─────────────────────┘
>>> df.schema
OrderedDict([('time', Datetime(time_unit='us', time_zone=None))])
```

### Log output

```shell
>>> df.filter(pl.col("time") > time_2)
thread '<unnamed>' panicked at /home/runner/work/polars/polars/crates/polars-core/src/series/comparison.rs:333:23:
cannot coerce datatypes: ComputeError(ErrString("failed to determine supertype of datetime[μs] and datetime[μs, UTC]"))
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/tobias/.local/lib/python3.11/site-packages/polars/dataframe/frame.py", line 4012, in filter
    return self.lazy().filter(*predicates, **constraints).collect(_eager=True)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/tobias/.local/lib/python3.11/site-packages/polars/utils/deprecation.py", line 100, in wrapper
    return function(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/tobias/.local/lib/python3.11/site-packages/polars/lazyframe/frame.py", line 1787, in collect
    return wrap_df(ldf.collect())
                   ^^^^^^^^^^^^^
pyo3_runtime.PanicException: cannot coerce datatypes: ComputeError(ErrString("failed to determine supertype of datetime[μs] and datetime[μs, UTC]"))
```
```


### Issue description

The timezone is missing in the dataframe. My datetime objects have timezones. This causes errors, unless I extend the DataFrame constructor, making my code more complicated.

### Expected behavior

I expect the dataframe to remember the timezone, so that it doesn't cause the error above.

This works:

```
df = pl.DataFrame(
	[{
		"time": time_1
	}],
	schema={"time": Datetime(time_unit="us", time_zone="UTC")}
)

df.filter(pl.col("time") > time_2)
```

But since it seemed that polars converts everything to utc by default, why don't add the "UTC" timezone by default as well?

### Installed versions

<details>

```
>>> pl.show_versions()
--------Version info---------
Polars:              0.19.12
Index type:          UInt32
Platform:            Linux-6.5.0-9-generic-x86_64-with-glibc2.38
Python:              3.11.6 (main, Oct  8 2023, 05:06:43) [GCC 13.2.0]

----Optional dependencies----
adbc_driver_sqlite:  <not installed>
cloudpickle:         <not installed>
connectorx:          <not installed>
deltalake:           <not installed>
fsspec:              <not installed>
gevent:              <not installed>
matplotlib:          3.6.3
numpy:               1.24.2
openpyxl:            <not installed>
pandas:              <not installed>
pyarrow:             <not installed>
pydantic:            1.10.4
pyiceberg:           <not installed>
pyxlsb:              <not installed>
sqlalchemy:          <not installed>
xlsx2csv:            <not installed>
xlsxwriter:          <not installed>
```

</details>

**Comment by deanm0000** [comment]
It does seem like constructing from a list of dicts should recognize the timezone. Another way to side step the issue until it's fixed is to construct with `pl.select(time=time_1)` or something like `pl.select(time=pl.Series([time_1]*10))`

As far as comparing UTC to naive raising an error, I think that's appropriate because if what you meant is for the naive timezone to be thought of as UTC then you should just make it UTC.

**Comment by cmdlineluser** [comment]
Just attempting to debug this due to #12638 

It seems this ends up calling `dicts_to_rows()`

https://github.com/pola-rs/polars/blob/0ee833c67c0a947b24a4d7945f825dd46af157bc/py-polars/src/conversion.rs#L1075

```rust
[py-polars/src/conversion.rs:1071] d = {'create_time': datetime.datetime(2023, 11, 22, 14, 27, 59, 173645, tzinfo=datetime.timezone.utc)}
[py-polars/src/conversion.rs:1080] val.clone() = Datetime(
    1700663279173645,
    Microseconds,
    None,
)
```

It looks like `.extract()` does not retain timezones - is this the actual source of the problem?
