### ISSUE TITLE
group_by aggregation of an empty dataframe raises a ComputeError instead of returning an empty dataframe

### ISSUE THREAD

**Issue by stfdxv** [pola-rs/polars#12194]
### Checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pypi.org/project/polars/) of Polars.

### Reproducible example

```python
import polars as pl


df = pl.DataFrame({"group": [], "x": []})
squared_deviation_sum = ((pl.col("x") - pl.col("x").mean()) ** 2).sum()
df1 = df.group_by("group").agg(squared_deviation_sum)
print(df1)
```

### Log output

```shell
keys/aggregates are not partitionable: running default HASH AGGREGATION
group_by keys are sorted; running sorted key fast path
Traceback (most recent call last):
  File "...\polars_sum_bug.py", line 6, in <module>
    df1 = df.group_by("group").agg(squared_deviation_sum)
  File "...\.venv\lib\site-packages\polars\dataframe\group_by.py", line 241, in agg
    self.df.lazy()
  File "...\.venv\lib\site-packages\polars\utils\deprecation.py", line 100, in wrapper
    return function(*args, **kwargs)
  File "...\.venv\lib\site-packages\polars\lazyframe\frame.py", line 1787, in collect
    return wrap_df(ldf.collect())
polars.exceptions.ComputeError: cannot aggregate as sum, the column is already aggregated
```

### Issue description

An empty dataframe is expected (at least by me) to be transformed into an empty dataframe without any error.
But a cryptic error message is returned instead.

### Expected behavior

```
shape: (0, 2)
┌───────┬──────┐
│ group ┆ x    │
│ ---   ┆ ---  │
│ f32   ┆ f32  │
╞═══════╪══════╡
└───────┴──────┘
```

### Installed versions

<details>

```
--------Version info---------
Polars:              0.19.12
Index type:          UInt32
Platform:            Windows-10-10.0.19041-SP0
Python:              3.10.5 (tags/v3.10.5:f377153, Jun  6 2022, 16:14:13) [MSC v.1929 64 bit (AMD64)]

----Optional dependencies----
adbc_driver_sqlite:  <not installed>
cloudpickle:         <not installed>
connectorx:          <not installed>
deltalake:           <not installed>
fsspec:              <not installed>
gevent:              <not installed>
matplotlib:          <not installed>
numpy:               1.24.3
openpyxl:            <not installed>
pandas:              2.1.1
pyarrow:             13.0.0
pydantic:            <not installed>
pyiceberg:           <not installed>
pyxlsb:              <not installed>
sqlalchemy:          <not installed>
xlsx2csv:            <not installed>
xlsxwriter:          <not installed>
```

</details>

**Comment by cmdlineluser** [comment]
It appears that because there are no values it ends up as `AggregatedScalar`
https://github.com/pola-rs/polars/blob/4a58499bdf97203c940a3c82c1113905e8c6087d/crates/polars-lazy/src/physical_plan/expressions/aggregation.rs#L61

```rust
[/Users/user/git/polars/crates/polars-lazy/src/physical_plan/expressions/aggregation.rs:98] ac.agg_state() = NotAggregated(
    shape: (0,)
    Series: 'x' [f32]
    [
    ],
)
[/Users/user/git/polars/crates/polars-lazy/src/physical_plan/expressions/aggregation.rs:104] ac.agg_state() = AggregatedScalar(
    shape: (0,)
    Series: 'x' [f32]
    [
    ],
)
```
Whereas with actual values it is `AggregatedList`
```rust
[/Users/user/git/polars/crates/polars-lazy/src/physical_plan/expressions/aggregation.rs:98] ac.agg_state() = NotAggregated(
    shape: (1,)
    Series: 'x' [i64]
    [
    	2
    ],
)
[/Users/user/git/polars/crates/polars-lazy/src/physical_plan/expressions/aggregation.rs:104] ac.agg_state() = AggregatedList(
    shape: (1,)
    Series: 'x' [list[f64]]
    [
    	[0.0]
    ],
)
```
