### ISSUE TITLE
`when/then` inside `.agg()` raises: predicates length does not match groups length

### ISSUE THREAD

**Issue by cmdlineluser** [pola-rs/polars#12242]
### Checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pypi.org/project/polars/) of Polars.

### Reproducible example

```python
import polars as pl

df = pl.DataFrame(
    {
        "array_name": ["A", "A", "A", "B", "B"],
        "array_idx": [5, 0, 3, 7, 2],
        "array_val": [1, 2, 3, 4, 5],
    } 
)

int_range = pl.int_range(pl.min("array_idx"), pl.max("array_idx") + 1)

is_valid_idx = int_range.is_in("array_idx")

idxs = is_valid_idx.cumsum() - 1

pl.Config(fmt_table_cell_list_len=-1)

print(
    df.group_by("array_name").agg( 
        pl.when(is_valid_idx)
          .then(pl.col("array_val").take(idxs))
    )
)

```

### Log output

```shell
keys/aggregates are not partitionable: running default HASH AGGREGATION
Traceback (most recent call last):
  File "/Users/user/polars-upsample.py", line 22, in <module>
    df.group_by("array_name").agg( 
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/polars/dataframe/group_by.py", line 244, in agg
    .collect(no_optimization=True)
     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/polars/utils/deprecation.py", line 100, in wrapper
    return function(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/polars/lazyframe/frame.py", line 1787, in collect
    return wrap_df(ldf.collect())
                   ^^^^^^^^^^^^^
polars.exceptions.ComputeError: predicates length: 12 does not match groups length: 2

Error originated in expression: '.when(col("array_idx").min().int_range([[(col("array_idx").max()) + (1)]]).is_in([col("array_idx")])).then(col("array_val").take([(col("array_idx").min().int_range([[(col("array_idx").max()) + (1)]]).is_in([col("array_idx")]).cumsum()) - (1)])).otherwise(null.cast(Int64))'
```

### Issue description

(The code example arose from trying to answer the question in https://github.com/pola-rs/polars/issues/12207#issuecomment-1793059330)

 The error comes from the closure here:

https://github.com/pola-rs/polars/blob/4a58499bdf97203c940a3c82c1113905e8c6087d/crates/polars-lazy/src/physical_plan/expressions/ternary.rs#L204

```python
polars.exceptions.ComputeError: predicates length: 12 does not match groups length: 2
```

The `12` seems to be the length of both `.int_range()` calls expanded (plus 2)?

While debugging, I did notice running the example through `finish_as_iters()` produces the expected result.

https://github.com/pola-rs/polars/blob/4a58499bdf97203c940a3c82c1113905e8c6087d/crates/polars-lazy/src/physical_plan/expressions/ternary.rs#L200-L201

```python
shape: (2, 2)
┌────────────┬────────────────────────────────┐
│ array_name ┆ array_val                      │
│ ---        ┆ ---                            │
│ str        ┆ list[i64]                      │
╞════════════╪════════════════════════════════╡
│ B          ┆ [4, null, null, null, null, 5] │
│ A          ┆ [1, null, null, 2, null, 3]    │
└────────────┴────────────────────────────────┘
```

### Expected behavior

```
shape: (2, 2)
┌────────────┬────────────────────────────────┐
│ array_name ┆ array_val                      │
│ ---        ┆ ---                            │
│ str        ┆ list[i64]                      │
╞════════════╪════════════════════════════════╡
│ B          ┆ [4, null, null, null, null, 5] │
│ A          ┆ [1, null, null, 2, null, 3]    │
└────────────┴────────────────────────────────┘
```

### Installed versions

<details>

```
--------Version info---------
Polars:              0.19.12
Index type:          UInt32
Platform:            macOS-12.6.7-arm64-arm-64bit
Python:              3.11.6 (main, Oct  2 2023, 20:46:17) [Clang 14.0.0 (clang-1400.0.29.202)]

----Optional dependencies----
adbc_driver_sqlite:  <not installed>
cloudpickle:         <not installed>
connectorx:          <not installed>
deltalake:           <not installed>
fsspec:              2023.6.0
gevent:              <not installed>
matplotlib:          <not installed>
numpy:               1.25.0
openpyxl:            <not installed>
pandas:              2.0.3
pyarrow:             12.0.1
pydantic:            <not installed>
pyiceberg:           <not installed>
pyxlsb:              <not installed>
sqlalchemy:          <not installed>
xlsx2csv:            <not installed>
xlsxwriter:          <not installed>
```

</details>

**Comment by cmdlineluser** [comment]
Just bumping this as 2 recent commits deal with this part of the code: https://github.com/pola-rs/polars/commit/a9259dbcdca282eada787abf04c00ceb56113293 https://github.com/pola-rs/polars/commit/817dcaeebddbdb8feb09722d76b6a39c86d427d4 and perhaps it's relevant

A simpler repro:
```python
pl.Config(fmt_table_cell_list_len=-1, fmt_str_lengths=120)

df = pl.DataFrame({"foo": ["A", "A"], "bar": [1, 7]})

df.group_by("foo").agg(pl.when(pl.int_range(0, 10).is_in("bar")).then(pl.int_range(0, 10)))

# ComputeError: predicates length: 10 does not match groups length: 1
```
However, if manually run `finish_as_iters()` it generates the "expected output"

 https://github.com/pola-rs/polars/blob/4a58499bdf97203c940a3c82c1113905e8c6087d/crates/polars-lazy/src/physical_plan/expressions/ternary.rs#L200-L201

```python
shape: (1, 2)
┌─────┬────────────────────────────────────────────────────────┐
│ foo ┆ int                                                    │
│ --- ┆ ---                                                    │
│ str ┆ list[i64]                                              │
╞═════╪════════════════════════════════════════════════════════╡
│ A   ┆ [null, 1, null, null, null, null, null, 7, null, null] │
└─────┴────────────────────────────────────────────────────────┘
```
So I think there may be some edge-case in the comparisons?

**Comment by cmdlineluser** [comment]
It seems to me that if the length of either list matches the mask length, then it should be run through `finish_as_iters`

```rust
+                if ac_truthy.is_literal() && ac_falsy.flat_naive().len() == mask.len() {
+                    return finish_as_iters(ac_truthy, ac_falsy, ac_mask);
+                }
+
+                if ac_falsy.is_literal() && ac_truthy.flat_naive().len() == mask.len() {
+                    return finish_as_iters(ac_truthy, ac_falsy, ac_mask);
+                }
```

If I do this, tests still pass.

Not sure if `.flat_naive()` is the correct way to get the length here.

There's also quite a bit going on in the surrounding branches, so I'm not sure if I understand everything correctly.
