### ISSUE TITLE
df.filter() throws PanicException when one of the columns is a decimal

### ISSUE THREAD

**Issue by vadimcn** [pola-rs/polars#12393]
### Checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pypi.org/project/polars/) of Polars.

### Reproducible example

```python
import polars as pl

df = pl.DataFrame(
    {
        "foo": [1, 2, 3],
        "bar": ["6", "7", "8"],
    }
)
df = df.with_columns(pl.col("bar").cast(pl.Decimal))
df = df.filter(pl.col("foo") > 1)  # <--- throws here
```

### Issue description

The above code throws on the last line:
```
thread '<unnamed>' panicked at crates/polars-arrow/src/compute/filter.rs:290:33:
operator does not support primitive `Int128`
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
Traceback (most recent call last):
  File "/home/user/proj/repro.py", line 10, in <module>
    df = df.filter(pl.col("foo") > 1)
  File "/home/user/.local/lib/python3.10/site-packages/polars/dataframe/frame.py", line 4028, in filter
    return self.lazy().filter(*predicates, **constraints).collect(_eager=True)
  File "/home/user/.local/lib/python3.10/site-packages/polars/utils/deprecation.py", line 100, in wrapper
    return function(*args, **kwargs)
  File "/home/user/.local/lib/python3.10/site-packages/polars/lazyframe/frame.py", line 1788, in collect
    return wrap_df(ldf.collect())
pyo3_runtime.PanicException: operator does not support primitive `Int128`
```

### Expected behavior

Should return a filtered dataframe.   The last version where this worked seems to have been 0.19.8

### Installed versions

<details>

```
--------Version info---------
Polars:              0.19.13
Index type:          UInt32
Platform:            Linux-5.19.0-50-generic-x86_64-with-glibc2.35
Python:              3.10.12 (main, Jun 11 2023, 05:26:28) [GCC 11.4.0]

----Optional dependencies----
adbc_driver_sqlite:  <not installed>
cloudpickle:         <not installed>
connectorx:          <not installed>
deltalake:           <not installed>
fsspec:              <not installed>
gevent:              <not installed>
matplotlib:          3.7.1
numpy:               1.24.3
openpyxl:            3.1.2
pandas:              2.0.2
pyarrow:             12.0.0
pydantic:            <not installed>
pyiceberg:           <not installed>
pyxlsb:              <not installed>
sqlalchemy:          2.0.22
xlsx2csv:            <not installed>
xlsxwriter:          <not installed>
```

</details>

**Comment by manhtaile** [comment]
@vadimcn polars.Decimal type is currently just a _'experimental'_ ([docs](https://pola-rs.github.io/polars/py-polars/html/reference/api/polars.Decimal.html)), instead of using it you should try this:
`df = df.with_columns(pl.col("bar").cast(pl.Float64))`

**Comment by vadimcn** [comment]
Sure, but this used to work, so I thought you might want to know about the regression.

**Comment by ritchie46** [comment]
Thanks for the issue report @vadimcn. Will fix it.
