### ISSUE TITLE
Problem of using `Expr` in ipython

### ISSUE THREAD

**Issue by hanjinliu** [pola-rs/polars#12394]
### Checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pypi.org/project/polars/) of Polars.

### Reproducible example

It seems that `Expr` is incompatible with the type inspection of IPython.
The following input in [qtconsole](https://github.com/jupyter/qtconsole):

```python
pl.col("a").mean(
```

triggers inspectiong of `Expr.mean` but it fails:

```
Traceback (most recent call last):
  File "C:\Users\liuha\mambaforge\envs\mt\Lib\site-packages\ipykernel\kernelbase.py", line 409, in dispatch_shell
    await result
  File "C:\Users\liuha\mambaforge\envs\mt\Lib\site-packages\ipykernel\kernelbase.py", line 798, in inspect_request
    reply_content = self.do_inspect(
                    ^^^^^^^^^^^^^^^^
  File "C:\Users\liuha\mambaforge\envs\mt\Lib\site-packages\ipykernel\ipkernel.py", line 555, in do_inspect
    bundle = self.shell.object_inspect_mime(
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\liuha\mambaforge\envs\mt\Lib\site-packages\IPython\core\interactiveshell.py", line 1865, in object_inspect_mime
    return self.inspector._get_info(
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\liuha\mambaforge\envs\mt\Lib\site-packages\IPython\core\oinspect.py", line 757, in _get_info
    info_dict = self.info(obj, oname=oname, info=info, detail_level=detail_level)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\liuha\mambaforge\envs\mt\Lib\site-packages\IPython\core\oinspect.py", line 859, in info
    parents_docs = parents_docs_dict.get(att_name, None)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: Expr.get() takes 2 positional arguments but 3 were given
```

The `?` command is also disabled:

```python
pl.col("a").mean?
```
```
Object `mean` not found.
```

If a `Expr` object is already created, all the behaviors are as expected:

```
a = pl.col("a")
a.mean(  # showing the doc in the tooltip
a.mean?  # showing the doc in the console
```

### Issue description

Versions of relevant modules:

```
ipython==8.17.2
qtconsole==5.4.4
```

### Expected behavior

Type inspection should work as other objects.

### Installed versions

<details>

```
--------Version info---------
Polars:              0.19.13
Index type:          UInt32
Platform:            Windows-10-10.0.22621-SP0
Python:              3.11.4 | packaged by conda-forge | (main, Jun 10 2023, 17:59:51) [MSC v.1935 64 bit (AMD64)] 

----Optional dependencies----
adbc_driver_sqlite:  <not installed>
cloudpickle:         2.2.1
connectorx:          <not installed>
deltalake:           <not installed>
fsspec:              2023.3.0
gevent:              <not installed>
matplotlib:          3.8.0
numpy:               1.24.4
openpyxl:            <not installed>
pandas:              2.1.1
pyarrow:             11.0.0
pydantic:            1.10.6
pyiceberg:           <not installed>
pyxlsb:              <not installed>
sqlalchemy:          <not installed>
xlsx2csv:            <not installed>
xlsxwriter:          <not installed>
```

</details>

**Comment by cmdlineluser** [comment]
With regards to `pinfo` / `?` being disabled.

It [seems anything with `()` gets transformed](https://github.com/ipython/ipython/blob/86d44b7f4674d5bf830afea5e6235c28a4b56bfd/IPython/core/inputtransformer2.py#L454) - in this case, `pl.col("a").mean` is turned into `mean`, which it cannot find.

(I assume to avoid any code execution/side-effects?)

```python
>>> get_ipython()._inspect('pinfo', 'mean')
Object `mean` not found.
```
It does appear you can pass custom namespaces

```python
namespace = 'Expr', {str(m): getattr(pl.Expr, m) for m in dir(pl.Expr)}
get_ipython()._inspect('pinfo', 'mean', namespaces=[namespace])

# Signature: mean(self) -> 'Self'
# Docstring:
# Get mean value.
# 
# Examples
# --------
# >>> df = pl.DataFrame({"a": [-1, 0, 1]})
# >>> df.select(pl.col("a").mean())
# shape: (1, 1)
# ┌─────┐
# │ a   │
# │ --- │
# │ f64 │
# ╞═════╡
# │ 0.0 │
# └─────┘
# File:      /usr/local/lib/python3.10/site-packages/polars/expr/expr.py
# Type:      function
```
I can't seem to find any information on adding a custom namespace so that it works with `?` directly - perhaps someone with more IPython knowledge knows?

**Comment by ethan-tau** [comment]
I am encountering a similar issue using qtconsole as a REPL - while constructing a code line,  type/argument hinting interrupts entering text with `TypeError: Expr.get() takes 2 positional arguments but 3 were given`, seeming to originate out of `IPython\core\oinspect.py", line 957, in info`.

Do Polars and the iPython core have different expectations around function signature?

Versions:

```
polars: 1.21.0
ipython: 8.32.0
python: 3.13.2
qtconsole: 5.6.1
```
Windows 11

<details>
<summary>Full error stack from QTconsole</summary>
(Replacing absolute path details with `~`)

> "~\Lib\site-packages\ipykernel\kernelbase.py", line 437, in dispatch_shell
>     await result


>   File "~\Lib\site-packages\ipykernel\kernelbase.py", line 852, in inspect_request
>     reply_content = self.do_inspect(
>         content["code"],
>     ...<2 lines>...
>         set(content.get("omit_sections", [])),
>     )

>   File "~\Lib\site-packages\ipykernel\ipkernel.py", line 588, in do_inspect
>     bundle = self.shell.object_inspect_mime(
>         name,
>         detail_level=detail_level,
>         omit_sections=omit_sections,
>     )

>   File "~\Lib\site-packages\IPython\core\interactiveshell.py", line 1891, in object_inspect_mime
>     return self.inspector._get_info(
>            ~~~~~~~~~~~~~~~~~~~~~~~~^
>         info.obj,
>         ^^^^^^^^^
>     ...<4 lines>...
>         omit_sections=omit_sections,
>         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>     )
>     ^

>   File "~site-packages\IPython\core\oinspect.py", line 827, in _get_info
>     info_dict = self.info(obj, oname=oname, info=info, detail_level=detail_level)


>   File "~\Lib\site-packages\IPython\core\oinspect.py", line 957, in info
>     parents_docs = parents_docs_dict.get(att_name, None)
> TypeError: Expr.get() takes 2 positional arguments but 3 were given
> ))
> 

</details>

**Comment by lll9p** [comment]
disable `calltips` should work.

- run with commmand: `jupyter qtconsole --JupyterWidget.enable_calltips=False`
- or add `c.JupyterWidget.enable_calltips = False` to your `juptyer_qtconsole_config.py`

**Comment by hanjinliu** [comment]
You don't want to disable the powerful calltip feature just for this. Calltip rarely causes troubles, which means that `Expr` has some unusual implementations.

**Comment by ethan-tau** [comment]
agreed, @hanjinliu , I really appreciate the calltip feature and don't want to disable that.

Still observing this behavior with updated packages:
* Polars '1.35.2'
* IPython '9.7.0'
* Jupyter QtConsole 5.7.0
* Python 3.13.2
