### ISSUE TITLE
Deltalake: Issues with schema when writing to existing table

### ISSUE THREAD

**Issue by fierzdev** [pola-rs/polars#12446]
### Checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pypi.org/project/polars/) of Polars.

### Reproducible example

```python
import pyarrow as pa
import polars as pl
my_schema = pa.schema([pa.field("large_list", pa.large_list(pa.field("large_string",pa.large_string())))])
df = pl.DataFrame({"large_list": [["large string"], ["large_string"]]})
df.write_delta("dataframe.pl", delta_write_options={"schema": my_schema})  # This works
df.write_delta("dataframe.pl", delta_write_options={"schema": my_schema}, mode="append")  # this fails because of schema errors

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/opt/conda/lib/python3.10/site-packages/polars/dataframe/frame.py", line 3634, in write_delta
    write_deltalake(
  File "/opt/conda/lib/python3.10/site-packages/deltalake/writer.py", line 201, in write_deltalake
    raise ValueError(
ValueError: Schema of data does not match table schema
Data schema:
large_list: large_list<large_string: large_string>
  child 0, large_string: large_string
Table Schema:
large_list: list<item: string>
  child 0, item: string

```

### Issue description

When writing to a deltatable and specifying a pyarrow schema, errors can occur when we want to write to the same table again. This seems to happen because Polars does not need to have the same schema as the stored data.

### Expected behavior

I guess it's fine if it fails if no schema is specified, but if a schema is explicitly specified, it should either check that the casted data matches the schema, or simply check if the specified schema is the same as the stored data has and fail on the writer.

### Installed versions

<details>

```
--------Version info---------
Polars:              0.19.12
Index type:          UInt32
Platform:            Linux-5.15.0-88-generic-x86_64-with-glibc2.31
Python:              3.10.13 (main, Sep 11 2023, 13:44:35) [GCC 11.2.0]

----Optional dependencies----
adbc_driver_sqlite:  <not installed>
cloudpickle:         <not installed>
connectorx:          <not installed>
deltalake:           0.13.0
fsspec:              2023.10.0
gevent:              <not installed>
matplotlib:          3.8.1
numpy:               1.26.2
openpyxl:            <not installed>
pandas:              2.1.3
pyarrow:             14.0.1
pydantic:            1.10.13
pyiceberg:           <not installed>
pyxlsb:              <not installed>
sqlalchemy:          <not installed>
xlsx2csv:            <not installed>
xlsxwriter:          <not installed>

```

</details>

**Comment by fierzdev** [comment]
Nevermind, just saw that I was one version behind. Fixed in the newest
