### ISSUE TITLE
Panic when hashing AnyValue::Struct::into_static

### ISSUE THREAD

**Issue by gregates** [pola-rs/polars#12455]
### Checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://crates.io/crates/polars) of Polars.

### Reproducible example

```rust
use polars::prelude::*;
use std::collections::HashSet;

fn main() {
    let struct_series = df!(
        "field_a" => &[1, 2, 3],
        "field_b" => &[4, 5, 6],
    ).unwrap().into_struct("structs").into_series();
    let mut cache = HashSet::new();
    for value in struct_series.iter() {
        cache.insert(value.into_static().unwrap());
    }
}
```

### Log output

```shell
$ POLARS_VERBOSE=1 RUST_BACKTRACE=1 cargo run --release
    Finished release [optimized] target(s) in 0.31s
     Running `target/release/struct_hash_repro`
thread 'main' panicked at /home/greg/.cargo/registry/src/index.crates.io-6f17d22bba15001f/polars-core-0.34.2/src/chunked_array/ops/any_value.rs:168:18:
internal error: entered unreachable code
stack backtrace:
   0: rust_begin_unwind
             at /rustc/cc66ad468955717ab92600c770da8c1601a4ff33/library/std/src/panicking.rs:595:5
   1: core::panicking::panic_fmt
             at /rustc/cc66ad468955717ab92600c770da8c1601a4ff33/library/core/src/panicking.rs:67:14
   2: core::panicking::panic
             at /rustc/cc66ad468955717ab92600c770da8c1601a4ff33/library/core/src/panicking.rs:117:5
   3: polars_core::chunked_array::ops::any_value::<impl polars_core::datatypes::any_value::AnyValue>::_materialize_struct_av
   4: <polars_core::datatypes::any_value::AnyValue as core::hash::Hash>::hash
   5: core::hash::BuildHasher::hash_one
   6: hashbrown::map::HashMap<K,V,S,A>::insert
   7: struct_hash_repro::main
```

### Issue description

It appears that `AnyValue::hash_impl` delegates to `_materialize_struct_av` for both `Struct` and `StructOwned`. But `_materialize_struct_av` calls `_iter_struct_av`, which only handles the `Struct` case. Hence the panic when hashing a struct value after calling `into_static`.

### Expected behavior

I expect that a static lifetime struct value should be hashable.

### Installed versions

<details>

polars = { version = "0.34.2", features = ["dtype-struct"] }

</details>

**Comment by collinprince** [comment]
Believe I have a working fix for this
