### ISSUE TITLE
scan_parquet triggers panic after collecting selecting certain columns

### ISSUE THREAD

**Issue by daviskirk** [pola-rs/polars#12500]
### Checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pypi.org/project/polars/) of Polars.

### Reproducible example

(update: this example was found later to trigger this behaviour as well)

Using `POLARS_FORCE_ASYNC=1`:
```python
pl.DataFrame(
    [
        pl.Series("c1", [{'a': 'foo', 'b': 'bar'}], dtype=pl.Struct),
        pl.Series("c2", [18]),
    ]
).write_parquet("a.parquet")
pl.scan_parquet("./a.parquet").select("c1").collect()
```

#### History

This is NOT a completely reproducible example, as I could not find the example parameters that trigger it.
Below are hopefully enough examples and analyses to track down the problem (although I will try and find a true reproducible example).

Sanning a gcs file previously uploaded with 

```
fs = gcsfs.GCSFileSystem()
with fs.open("gs://example.com/not_a_real_file", "wb"):
    df.write_parquet(f)

df = pl.scan_parquet("gs://example.com/not_a_real_file")
```

Selecting different subsets of columns causes the panik below:

```python
df.drop("column").collect()
```

```python
df.select(["x", "y"]).collect()
```

Collecting the entire frame works / works as intended.

```python
df.collect()
```

The profile (without the selection/drop of columns since that causes the panic is very simple:

```python
df.profile()[1]
shape: (2, 3)
┌───────────────────────────────────┬───────┬───────┐
│ node                              ┆ start ┆ end   │
│ ---                               ┆ ---   ┆ ---   │
│ str                               ┆ u64   ┆ u64   │
╞═══════════════════════════════════╪═══════╪═══════╡
│ optimization                      ┆ 0     ┆ 9     │
│ parquet(gs://example… ┆ 9     ┆ 62823 │
└───────────────────────────────────┴───────┴───────┘
```

* selecting the column subset after collecting the `scan_parquet` lazyframe, i.e.: `df.collect().lazy().select(["x", "y"]).collect()` works as well.
* `df.select(["x", "y"]).collect(no_optimization=True)` also works as intended (no panic)

### Log output

```shell
thread '<unnamed>' panicked at crates/polars-io/src/parquet/mmap.rs:53:17:
mmap_columns: column with start 11759 must be prefetched in ColumnStore.

stack backtrace:
   0: rust_begin_unwind
             at /rustc/475c71da0710fd1d40c046f9cee04b733b5b2b51/library/std/src/panicking.rs:597:5
   1: core::panicking::panic_fmt
             at /rustc/475c71da0710fd1d40c046f9cee04b733b5b2b51/library/core/src/panicking.rs:72:14
   2: polars_io::parquet::read_impl::column_idx_to_series
   3: rayon::iter::plumbing::bridge_producer_consumer::helper
   4: rayon_core::join::join_context::{{closure}}
   5: rayon::iter::plumbing::bridge_producer_consumer::helper
   6: rayon_core::join::join_context::{{closure}}
   7: rayon::iter::plumbing::bridge_producer_consumer::helper
   8: rayon_core::join::join_context::{{closure}}
   9: rayon::iter::plumbing::bridge_producer_consumer::helper
  10: rayon_core::join::join_context::{{closure}}
  11: rayon::iter::plumbing::bridge_producer_consumer::helper
  12: <rayon_core::job::StackJob<L,F,R> as rayon_core::job::Job>::execute
  13: rayon_core::registry::WorkerThread::wait_until_cold
  14: rayon_core::join::join_context::{{closure}}
  15: rayon::iter::plumbing::bridge_producer_consumer::helper
  16: <rayon_core::job::StackJob<L,F,R> as rayon_core::job::Job>::execute
  17: rayon_core::registry::WorkerThread::wait_until_cold
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
thread '<unnamed>' panicked at /home/runner/work/polars/polars/crates/polars-io/src/pl_async.rs:75:80:
called `Result::unwrap()` on an `Err` value: Any { .. }
stack backtrace:
   0: rust_begin_unwind
             at /rustc/475c71da0710fd1d40c046f9cee04b733b5b2b51/library/std/src/panicking.rs:597:5
   1: core::panicking::panic_fmt
             at /rustc/475c71da0710fd1d40c046f9cee04b733b5b2b51/library/core/src/panicking.rs:72:14
   2: core::result::unwrap_failed
             at /rustc/475c71da0710fd1d40c046f9cee04b733b5b2b51/library/core/src/result.rs:1653:5
   3: <polars_lazy::physical_plan::executors::scan::parquet::ParquetExec as polars_lazy::physical_plan::executors::executor::Executor>::execute::{{closure}}::{{closure}}
   4: <polars_lazy::physical_plan::executors::scan::parquet::ParquetExec as polars_lazy::physical_plan::executors::executor::Executor>::execute::{{closure}}
   5: <polars_lazy::physical_plan::executors::scan::parquet::ParquetExec as polars_lazy::physical_plan::executors::executor::Executor>::execute
   6: <polars_lazy::physical_plan::executors::udf::UdfExec as polars_lazy::physical_plan::executors::executor::Executor>::execute
   7: polars_lazy::frame::LazyFrame::collect
   8: polars::lazyframe::_::<impl polars::lazyframe::PyLazyFrame>::__pymethod_collect__
   9: pyo3::impl_::trampoline::trampoline
  10: method_vectorcall_NOARGS
             at /usr/local/src/conda/python-3.10.12/Objects/descrobject.c:432:24
  11: _PyObject_VectorcallTstate
             at /usr/local/src/conda/python-3.10.12/Include/cpython/abstract.h:114:11
  12: PyObject_Vectorcall
             at /usr/local/src/conda/python-3.10.12/Include/cpython/abstract.h:123:12
  13: call_function
             at /usr/local/src/conda/python-3.10.12/Python/ceval.c:5893:13
  14: _PyEval_EvalFrameDefault
             at /usr/local/src/conda/python-3.10.12/Python/ceval.c:4198:23
  15: _PyEval_EvalFrame
             at /usr/local/src/conda/python-3.10.12/Include/internal/pycore_ceval.h:46:12
  16: _PyEval_Vector
             at /usr/local/src/conda/python-3.10.12/Python/ceval.c:5067:24
  17: _PyFunction_Vectorcall
             at /usr/local/src/conda/python-3.10.12/Objects/call.c:342:16
  18: do_call_core
             at /usr/local/src/conda/python-3.10.12/Python/ceval.c:5945:12
  19: _PyEval_EvalFrameDefault
             at /usr/local/src/conda/python-3.10.12/Python/ceval.c:4277:22
  20: _PyEval_EvalFrame
             at /usr/local/src/conda/python-3.10.12/Include/internal/pycore_ceval.h:46:12
  21: _PyEval_Vector
             at /usr/local/src/conda/python-3.10.12/Python/ceval.c:5067:24
  22: _PyFunction_Vectorcall
             at /usr/local/src/conda/python-3.10.12/Objects/call.c:342:16
  23: _PyObject_VectorcallTstate
             at /usr/local/src/conda/python-3.10.12/Include/cpython/abstract.h:114:11
  24: method_vectorcall
             at /usr/local/src/conda/python-3.10.12/Objects/classobject.c:53:18
  25: _PyObject_VectorcallTstate
             at /usr/local/src/conda/python-3.10.12/Include/cpython/abstract.h:114:11
  26: PyObject_Vectorcall
             at /usr/local/src/conda/python-3.10.12/Include/cpython/abstract.h:123:12
  27: call_function
             at /usr/local/src/conda/python-3.10.12/Python/ceval.c:5893:13
  28: _PyEval_EvalFrameDefault
             at /usr/local/src/conda/python-3.10.12/Python/ceval.c:4181:23
  29: _PyEval_EvalFrame
             at /usr/local/src/conda/python-3.10.12/Include/internal/pycore_ceval.h:46:12
  30: _PyEval_Vector
             at /usr/local/src/conda/python-3.10.12/Python/ceval.c:5067:24
  31: PyEval_EvalCode
             at /usr/local/src/conda/python-3.10.12/Python/ceval.c:1134:12
  32: builtin_exec_impl
             at /usr/local/src/conda/python-3.10.12/Python/bltinmodule.c:1058:13
  33: builtin_exec
             at /usr/local/src/conda/python-3.10.12/Python/clinic/bltinmodule.c.h:371:20
  34: cfunction_vectorcall_FASTCALL
             at /usr/local/src/conda/python-3.10.12/Objects/methodobject.c:430:24
  35: _PyObject_VectorcallTstate
             at /usr/local/src/conda/python-3.10.12/Include/cpython/abstract.h:114:11
  36: PyObject_Vectorcall
             at /usr/local/src/conda/python-3.10.12/Include/cpython/abstract.h:123:12
  37: call_function
             at /usr/local/src/conda/python-3.10.12/Python/ceval.c:5893:13
  38: _PyEval_EvalFrameDefault
             at /usr/local/src/conda/python-3.10.12/Python/ceval.c:4213:19
  39: _PyEval_EvalFrame
             at /usr/local/src/conda/python-3.10.12/Include/internal/pycore_ceval.h:46:12
  40: _PyEval_Vector
             at /usr/local/src/conda/python-3.10.12/Python/ceval.c:5067:24
  41: _PyFunction_Vectorcall
             at /usr/local/src/conda/python-3.10.12/Objects/call.c:342:16
  42: _PyObject_VectorcallTstate
             at /usr/local/src/conda/python-3.10.12/Include/cpython/abstract.h:114:11
  43: method_vectorcall
             at /usr/local/src/conda/python-3.10.12/Objects/classobject.c:53:18
  44: _PyObject_VectorcallTstate
             at /usr/local/src/conda/python-3.10.12/Include/cpython/abstract.h:114:11
  45: PyObject_Vectorcall
             at /usr/local/src/conda/python-3.10.12/Include/cpython/abstract.h:123:12
  46: call_function
             at /usr/local/src/conda/python-3.10.12/Python/ceval.c:5893:13
  47: _PyEval_EvalFrameDefault
             at /usr/local/src/conda/python-3.10.12/Python/ceval.c:4181:23
  48: _PyEval_EvalFrame
             at /usr/local/src/conda/python-3.10.12/Include/internal/pycore_ceval.h:46:12
  49: _PyEval_Vector
             at /usr/local/src/conda/python-3.10.12/Python/ceval.c:5067:24
  50: _PyFunction_Vectorcall
             at /usr/local/src/conda/python-3.10.12/Objects/call.c:342:16
  51: _PyObject_VectorcallTstate
             at /usr/local/src/conda/python-3.10.12/Include/cpython/abstract.h:114:11
  52: PyObject_Vectorcall
             at /usr/local/src/conda/python-3.10.12/Include/cpython/abstract.h:123:12
  53: call_function
             at /usr/local/src/conda/python-3.10.12/Python/ceval.c:5893:13
  54: _PyEval_EvalFrameDefault
             at /usr/local/src/conda/python-3.10.12/Python/ceval.c:4198:23
  55: _PyEval_EvalFrame
             at /usr/local/src/conda/python-3.10.12/Include/internal/pycore_ceval.h:46:12
  56: _PyEval_Vector
             at /usr/local/src/conda/python-3.10.12/Python/ceval.c:5067:24
  57: _PyFunction_Vectorcall
             at /usr/local/src/conda/python-3.10.12/Objects/call.c:342:16
  58: _PyObject_VectorcallTstate
             at /usr/local/src/conda/python-3.10.12/Include/cpython/abstract.h:114:11
  59: PyObject_Vectorcall
             at /usr/local/src/conda/python-3.10.12/Include/cpython/abstract.h:123:12
  60: call_function
             at /usr/local/src/conda/python-3.10.12/Python/ceval.c:5893:13
  61: _PyEval_EvalFrameDefault
             at /usr/local/src/conda/python-3.10.12/Python/ceval.c:4181:23
  62: _PyEval_EvalFrame
             at /usr/local/src/conda/python-3.10.12/Include/internal/pycore_ceval.h:46:12
  63: _PyEval_Vector
             at /usr/local/src/conda/python-3.10.12/Python/ceval.c:5067:24
  64: _PyFunction_Vectorcall
             at /usr/local/src/conda/python-3.10.12/Objects/call.c:342:16
  65: _PyObject_VectorcallTstate
             at /usr/local/src/conda/python-3.10.12/Include/cpython/abstract.h:114:11
  66: PyObject_Vectorcall
             at /usr/local/src/conda/python-3.10.12/Include/cpython/abstract.h:123:12
  67: call_function
             at /usr/local/src/conda/python-3.10.12/Python/ceval.c:5893:13
  68: _PyEval_EvalFrameDefault
             at /usr/local/src/conda/python-3.10.12/Python/ceval.c:4198:23
  69: _PyEval_EvalFrame
             at /usr/local/src/conda/python-3.10.12/Include/internal/pycore_ceval.h:46:12
  70: _PyEval_Vector
             at /usr/local/src/conda/python-3.10.12/Python/ceval.c:5067:24
  71: _PyFunction_Vectorcall
             at /usr/local/src/conda/python-3.10.12/Objects/call.c:342:16
  72: _PyObject_VectorcallTstate
             at /usr/local/src/conda/python-3.10.12/Include/cpython/abstract.h:114:11
  73: PyObject_Vectorcall
             at /usr/local/src/conda/python-3.10.12/Include/cpython/abstract.h:123:12
  74: call_function
             at /usr/local/src/conda/python-3.10.12/Python/ceval.c:5893:13
  75: _PyEval_EvalFrameDefault
             at /usr/local/src/conda/python-3.10.12/Python/ceval.c:4198:23
  76: _PyEval_EvalFrame
             at /usr/local/src/conda/python-3.10.12/Include/internal/pycore_ceval.h:46:12
  77: _PyEval_Vector
             at /usr/local/src/conda/python-3.10.12/Python/ceval.c:5067:24
  78: _PyFunction_Vectorcall
             at /usr/local/src/conda/python-3.10.12/Objects/call.c:342:16
  79: _PyObject_VectorcallTstate
             at /usr/local/src/conda/python-3.10.12/Include/cpython/abstract.h:114:11
  80: PyObject_Vectorcall
             at /usr/local/src/conda/python-3.10.12/Include/cpython/abstract.h:123:12
  81: call_function
             at /usr/local/src/conda/python-3.10.12/Python/ceval.c:5893:13
  82: _PyEval_EvalFrameDefault
             at /usr/local/src/conda/python-3.10.12/Python/ceval.c:4198:23
  83: _PyEval_EvalFrame
             at /usr/local/src/conda/python-3.10.12/Include/internal/pycore_ceval.h:46:12
  84: _PyEval_Vector
             at /usr/local/src/conda/python-3.10.12/Python/ceval.c:5067:24
  85: _PyFunction_Vectorcall
             at /usr/local/src/conda/python-3.10.12/Objects/call.c:342:16
  86: _PyObject_VectorcallTstate
             at /usr/local/src/conda/python-3.10.12/Include/cpython/abstract.h:114:11
  87: PyObject_Vectorcall
             at /usr/local/src/conda/python-3.10.12/Include/cpython/abstract.h:123:12
  88: call_function
             at /usr/local/src/conda/python-3.10.12/Python/ceval.c:5893:13
  89: _PyEval_EvalFrameDefault
             at /usr/local/src/conda/python-3.10.12/Python/ceval.c:4198:23
  90: _PyEval_EvalFrame
             at /usr/local/src/conda/python-3.10.12/Include/internal/pycore_ceval.h:46:12
  91: _PyEval_Vector
             at /usr/local/src/conda/python-3.10.12/Python/ceval.c:5067:24
  92: _PyFunction_Vectorcall
             at /usr/local/src/conda/python-3.10.12/Objects/call.c:342:16
  93: _PyObject_VectorcallTstate
             at /usr/local/src/conda/python-3.10.12/Include/cpython/abstract.h:114:11
  94: PyObject_Vectorcall
             at /usr/local/src/conda/python-3.10.12/Include/cpython/abstract.h:123:12
  95: call_function
             at /usr/local/src/conda/python-3.10.12/Python/ceval.c:5893:13
  96: _PyEval_EvalFrameDefault
             at /usr/local/src/conda/python-3.10.12/Python/ceval.c:4198:23
  97: _PyEval_EvalFrame
             at /usr/local/src/conda/python-3.10.12/Include/internal/pycore_ceval.h:46:12
  98: _PyEval_Vector
             at /usr/local/src/conda/python-3.10.12/Python/ceval.c:5067:24
  99: _PyFunction_Vectorcall
             at /usr/local/src/conda/python-3.10.12/Objects/call.c:342:16
 100: _PyObject_VectorcallTstate
             at /usr/local/src/conda/python-3.10.12/Include/cpython/abstract.h:114:11
 101: PyObject_Vectorcall
             at /usr/local/src/conda/python-3.10.12/Include/cpython/abstract.h:123:12
 102: call_function
             at /usr/local/src/conda/python-3.10.12/Python/ceval.c:5893:13
 103: _PyEval_EvalFrameDefault
             at /usr/local/src/conda/python-3.10.12/Python/ceval.c:4198:23
 104: _PyEval_EvalFrame
             at /usr/local/src/conda/python-3.10.12/Include/internal/pycore_ceval.h:46:12
 105: _PyEval_Vector
             at /usr/local/src/conda/python-3.10.12/Python/ceval.c:5067:24
 106: _PyFunction_Vectorcall
             at /usr/local/src/conda/python-3.10.12/Objects/call.c:342:16
 107: _PyObject_VectorcallTstate
             at /usr/local/src/conda/python-3.10.12/Include/cpython/abstract.h:114:11
 108: method_vectorcall
             at /usr/local/src/conda/python-3.10.12/Objects/classobject.c:83:18
 109: _PyObject_VectorcallTstate
             at /usr/local/src/conda/python-3.10.12/Include/cpython/abstract.h:114:11
 110: _PyObject_FastCallTstate
             at /usr/local/src/conda/python-3.10.12/Include/cpython/abstract.h:151
 111: call_trampoline
             at /usr/local/src/conda/python-3.10.12/Python/sysmodule.c:965
 112: trace_trampoline
             at /usr/local/src/conda/python-3.10.12/Python/sysmodule.c:1010
 113: call_trace
             at /usr/local/src/conda/python-3.10.12/Python/ceval.c:5470
 114: maybe_call_line_trace
             at /usr/local/src/conda/python-3.10.12/Python/ceval.c:5513:22
 115: _PyEval_EvalFrameDefault
             at /usr/local/src/conda/python-3.10.12/Python/ceval.c:1799:19
 116: _PyEval_EvalFrame
             at /usr/local/src/conda/python-3.10.12/Include/internal/pycore_ceval.h:46:12
 117: _PyEval_Vector
             at /usr/local/src/conda/python-3.10.12/Python/ceval.c:5067:24
 118: _PyFunction_Vectorcall
             at /usr/local/src/conda/python-3.10.12/Objects/call.c:342:16
 119: do_call_core
             at /usr/local/src/conda/python-3.10.12/Python/ceval.c:5945:12
 120: _PyEval_EvalFrameDefault
             at /usr/local/src/conda/python-3.10.12/Python/ceval.c:4277:22
 121: _PyEval_EvalFrame
             at /usr/local/src/conda/python-3.10.12/Include/internal/pycore_ceval.h:46:12
 122: _PyEval_Vector
             at /usr/local/src/conda/python-3.10.12/Python/ceval.c:5067:24
 123: _PyFunction_Vectorcall
             at /usr/local/src/conda/python-3.10.12/Objects/call.c:342:16
 124: _PyObject_VectorcallTstate
             at /usr/local/src/conda/python-3.10.12/Include/cpython/abstract.h:114:11
 125: object_vacall
             at /usr/local/src/conda/python-3.10.12/Objects/call.c:734:14
 126: PyObject_CallFunctionObjArgs
             at /usr/local/src/conda/python-3.10.12/Objects/call.c:841:14
 127: WraptFunctionWrapperBase_call
             at /usr/local/src/conda/wrapt-1.14.1/src/wrapt/_wrappers.c:2365:14
 128: _PyObject_Call
             at /usr/local/src/conda/python-3.10.12/Objects/call.c:305:19
 129: PyObject_Call
             at /usr/local/src/conda/python-3.10.12/Objects/call.c:317:12
 130: do_call_core
             at /usr/local/src/conda/python-3.10.12/Python/ceval.c:5945:12
 131: _PyEval_EvalFrameDefault
             at /usr/local/src/conda/python-3.10.12/Python/ceval.c:4277:22
 132: _PyEval_EvalFrame
             at /usr/local/src/conda/python-3.10.12/Include/internal/pycore_ceval.h:46:12
 133: _PyEval_Vector
             at /usr/local/src/conda/python-3.10.12/Python/ceval.c:5067:24
 134: _PyFunction_Vectorcall
             at /usr/local/src/conda/python-3.10.12/Objects/call.c:342:16
 135: _PyObject_VectorcallTstate
             at /usr/local/src/conda/python-3.10.12/Include/cpython/abstract.h:114:11
 136: object_vacall
             at /usr/local/src/conda/python-3.10.12/Objects/call.c:734:14
 137: PyObject_CallFunctionObjArgs
             at /usr/local/src/conda/python-3.10.12/Objects/call.c:841:14
 138: WraptFunctionWrapperBase_call
             at /usr/local/src/conda/wrapt-1.14.1/src/wrapt/_wrappers.c:2365:14
 139: _PyObject_Call
             at /usr/local/src/conda/python-3.10.12/Objects/call.c:305:19
 140: PyObject_Call
             at /usr/local/src/conda/python-3.10.12/Objects/call.c:317:12
 141: do_call_core
             at /usr/local/src/conda/python-3.10.12/Python/ceval.c:5945:12
 142: _PyEval_EvalFrameDefault
             at /usr/local/src/conda/python-3.10.12/Python/ceval.c:4277:22
 143: _PyEval_EvalFrame
             at /usr/local/src/conda/python-3.10.12/Include/internal/pycore_ceval.h:46:12
 144: _PyEval_Vector
             at /usr/local/src/conda/python-3.10.12/Python/ceval.c:5067:24
 145: _PyFunction_Vectorcall
             at /usr/local/src/conda/python-3.10.12/Objects/call.c:342:16
 146: _PyObject_VectorcallTstate
             at /usr/local/src/conda/python-3.10.12/Include/cpython/abstract.h:114:11
 147: PyObject_Vectorcall
             at /usr/local/src/conda/python-3.10.12/Include/cpython/abstract.h:123:12
 148: call_function
             at /usr/local/src/conda/python-3.10.12/Python/ceval.c:5893:13
 149: _PyEval_EvalFrameDefault
             at /usr/local/src/conda/python-3.10.12/Python/ceval.c:4181:23
 150: _PyEval_EvalFrame
             at /usr/local/src/conda/python-3.10.12/Include/internal/pycore_ceval.h:46:12
 151: _PyEval_Vector
             at /usr/local/src/conda/python-3.10.12/Python/ceval.c:5067:24
 152: _PyFunction_Vectorcall
             at /usr/local/src/conda/python-3.10.12/Objects/call.c:342:16
 153: _PyObject_VectorcallTstate
             at /usr/local/src/conda/python-3.10.12/Include/cpython/abstract.h:114:11
 154: object_vacall
             at /usr/local/src/conda/python-3.10.12/Objects/call.c:734:14
 155: PyObject_CallFunctionObjArgs
             at /usr/local/src/conda/python-3.10.12/Objects/call.c:841:14
 156: _PyObject_GenericGetAttrWithDict
             at /usr/local/src/conda/python-3.10.12/Objects/object.c:1305:15
 157: PyObject_GenericGetAttr
             at /usr/local/src/conda/python-3.10.12/Objects/object.c:1335:12
 158: PyObject_GetAttr
             at /usr/local/src/conda/python-3.10.12/Objects/object.c:932:19
 159: _PyEval_EvalFrameDefault
             at /usr/local/src/conda/python-3.10.12/Python/ceval.c:3592:19
 160: _PyEval_EvalFrame
             at /usr/local/src/conda/python-3.10.12/Include/internal/pycore_ceval.h:46:12
 161: _PyEval_Vector
             at /usr/local/src/conda/python-3.10.12/Python/ceval.c:5067:24
 162: _PyFunction_Vectorcall
             at /usr/local/src/conda/python-3.10.12/Objects/call.c:342:16
 163: _PyObject_VectorcallTstate
             at /usr/local/src/conda/python-3.10.12/Include/cpython/abstract.h:114:11
 164: vectorcall_unbound
             at /usr/local/src/conda/python-3.10.12/Objects/typeobject.c:1629:12
 165: vectorcall_method
             at /usr/local/src/conda/python-3.10.12/Objects/typeobject.c:1661:24
 166: slot_tp_getattro
             at /usr/local/src/conda/python-3.10.12/Objects/typeobject.c:7519
 167: PyObject_GetAttr
             at /usr/local/src/conda/python-3.10.12/Objects/object.c:932:19
 168: _PyObject_GetMethod
             at /usr/local/src/conda/python-3.10.12/Objects/object.c:1149:19
 169: _PyEval_EvalFrameDefault
             at /usr/local/src/conda/python-3.10.12/Python/ceval.c:4128:30
 170: _PyEval_EvalFrame
             at /usr/local/src/conda/python-3.10.12/Include/internal/pycore_ceval.h:46:12
 171: _PyEval_Vector
             at /usr/local/src/conda/python-3.10.12/Python/ceval.c:5067:24
 172: _PyFunction_Vectorcall
             at /usr/local/src/conda/python-3.10.12/Objects/call.c:342:16
 173: PyVectorcall_Call
             at /usr/local/src/conda/python-3.10.12/Objects/call.c:267:24
 174: _PyObject_Call
             at /usr/local/src/conda/python-3.10.12/Objects/call.c:290:16
 175: PyObject_Call
             at /usr/local/src/conda/python-3.10.12/Objects/call.c:317:12
 176: do_call_core
             at /usr/local/src/conda/python-3.10.12/Python/ceval.c:5945:12
 177: _PyEval_EvalFrameDefault
             at /usr/local/src/conda/python-3.10.12/Python/ceval.c:4277:22
 178: _PyEval_EvalFrame
             at /usr/local/src/conda/python-3.10.12/Include/internal/pycore_ceval.h:46:12
 179: _PyEval_Vector
             at /usr/local/src/conda/python-3.10.12/Python/ceval.c:5067:24
 180: _PyFunction_Vectorcall
             at /usr/local/src/conda/python-3.10.12/Objects/call.c:342:16
 181: _PyObject_VectorcallTstate
             at /usr/local/src/conda/python-3.10.12/Include/cpython/abstract.h:114:11
 182: PyObject_Vectorcall
             at /usr/local/src/conda/python-3.10.12/Include/cpython/abstract.h:123:12
 183: call_function
             at /usr/local/src/conda/python-3.10.12/Python/ceval.c:5893:13
 184: _PyEval_EvalFrameDefault
             at /usr/local/src/conda/python-3.10.12/Python/ceval.c:4231:19
 185: _PyEval_EvalFrame
             at /usr/local/src/conda/python-3.10.12/Include/internal/pycore_ceval.h:46:12
 186: _PyEval_Vector
             at /usr/local/src/conda/python-3.10.12/Python/ceval.c:5067:24
 187: _PyFunction_Vectorcall
             at /usr/local/src/conda/python-3.10.12/Objects/call.c:342:16
 188: do_call_core
             at /usr/local/src/conda/python-3.10.12/Python/ceval.c:5945:12
 189: _PyEval_EvalFrameDefault
             at /usr/local/src/conda/python-3.10.12/Python/ceval.c:4277:22
 190: _PyEval_EvalFrame
             at /usr/local/src/conda/python-3.10.12/Include/internal/pycore_ceval.h:46:12
 191: _PyEval_Vector
             at /usr/local/src/conda/python-3.10.12/Python/ceval.c:5067:24
 192: _PyFunction_Vectorcall
             at /usr/local/src/conda/python-3.10.12/Objects/call.c:342:16
 193: _PyObject_VectorcallTstate
             at /usr/local/src/conda/python-3.10.12/Include/cpython/abstract.h:114:11
 194: method_vectorcall
             at /usr/local/src/conda/python-3.10.12/Objects/classobject.c:83:18
 195: do_call_core
             at /usr/local/src/conda/python-3.10.12/Python/ceval.c:5945:12
 196: _PyEval_EvalFrameDefault
             at /usr/local/src/conda/python-3.10.12/Python/ceval.c:4277:22
 197: _PyEval_EvalFrame
             at /usr/local/src/conda/python-3.10.12/Include/internal/pycore_ceval.h:46:12
 198: _PyEval_Vector
             at /usr/local/src/conda/python-3.10.12/Python/ceval.c:5067:24
 199: _PyFunction_Vectorcall
             at /usr/local/src/conda/python-3.10.12/Objects/call.c:342:16
 200: _PyObject_VectorcallTstate
             at /usr/local/src/conda/python-3.10.12/Include/cpython/abstract.h:114:11
 201: object_vacall
             at /usr/local/src/conda/python-3.10.12/Objects/call.c:734:14
 202: PyObject_CallFunctionObjArgs
             at /usr/local/src/conda/python-3.10.12/Objects/call.c:841:14
 203: WraptFunctionWrapperBase_call
             at /usr/local/src/conda/wrapt-1.14.1/src/wrapt/_wrappers.c:2365:14
 204: _PyObject_Call
             at /usr/local/src/conda/python-3.10.12/Objects/call.c:305:19
 205: PyObject_Call
             at /usr/local/src/conda/python-3.10.12/Objects/call.c:317:12
 206: do_call_core
             at /usr/local/src/conda/python-3.10.12/Python/ceval.c:5945:12
 207: _PyEval_EvalFrameDefault
             at /usr/local/src/conda/python-3.10.12/Python/ceval.c:4277:22
 208: _PyEval_EvalFrame
             at /usr/local/src/conda/python-3.10.12/Include/internal/pycore_ceval.h:46:12
 209: _PyEval_Vector
             at /usr/local/src/conda/python-3.10.12/Python/ceval.c:5067:24
 210: _PyFunction_Vectorcall
             at /usr/local/src/conda/python-3.10.12/Objects/call.c:342:16
 211: _PyObject_VectorcallTstate
             at /usr/local/src/conda/python-3.10.12/Include/cpython/abstract.h:114:11
 212: object_vacall
             at /usr/local/src/conda/python-3.10.12/Objects/call.c:734:14
 213: PyObject_CallFunctionObjArgs
             at /usr/local/src/conda/python-3.10.12/Objects/call.c:841:14
 214: WraptFunctionWrapperBase_call
             at /usr/local/src/conda/wrapt-1.14.1/src/wrapt/_wrappers.c:2365:14
 215: _PyObject_Call
             at /usr/local/src/conda/python-3.10.12/Objects/call.c:305:19
 216: PyObject_Call
             at /usr/local/src/conda/python-3.10.12/Objects/call.c:317:12
 217: do_call_core
             at /usr/local/src/conda/python-3.10.12/Python/ceval.c:5945:12
 218: _PyEval_EvalFrameDefault
             at /usr/local/src/conda/python-3.10.12/Python/ceval.c:4277:22
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
*** pyo3_runtime.PanicException: called `Result::unwrap()` on an `Err` value: Any { .. }
Traceback (most recent call last):
  File "/lib/python3.10/site-packages/polars/utils/deprecation.py", line 100, in wrapper
    return function(*args, **kwargs)
  File "/lib/python3.10/site-packages/polars/lazyframe/frame.py", line 1788, in collect
    return wrap_df(ldf.collect())
```

### Issue description

using `scan_parquet` and selecting certain subsets of columns and then collecting cause rust to panic with an error:

```
thread '<unnamed>' panicked at crates/polars-io/src/parquet/mmap.rs:53:17:
mmap_columns: column with start 11759 must be prefetched in ColumnStore.
```

### Expected behavior

`scan_parquet` should work the same as a `df.collect().lazy().select(["x", "y"])` call but be able to do optimizations like predicate pushdown.

### Installed versions

<details>

```
--------Version info---------
Polars:              0.19.13
Index type:          UInt32
Platform:            Linux-6.2.0-36-generic-x86_64-with-glibc2.37
Python:              3.10.12 (main, Jul  5 2023, 18:54:27) [GCC 11.2.0]

----Optional dependencies----
adbc_driver_sqlite:  <not installed>
cloudpickle:         <not installed>
connectorx:          <not installed>
deltalake:           <not installed>
fsspec:              2023.4.0
gevent:              <not installed>
matplotlib:          3.7.2
numpy:               1.24.3
openpyxl:            3.1.2
pandas:              2.1.1
pyarrow:             13.0.0
pydantic:            1.10.8
pyiceberg:           <not installed>
pyxlsb:              <not installed>
sqlalchemy:          1.4.39
xlsx2csv:            <not installed>
xlsxwriter:          <not installed>
```

</details>

**Comment by ritchie46** [comment]
Can you make a repro with a local file? You should be able if you set `POLARS_FORCE_ASYNC=1`.

**Comment by daviskirk** [comment]
Yes, I can.

The following file reproduces if for me using a 1 row parquet file:

[b.zip](https://github.com/pola-rs/polars/files/13376510/b.zip)

```shell
unzip b.zip
POLARS_FORCE_ASYNC=1 python -c 'import polars as pl; pl.scan_parquet("./b.parquet").drop("130").collect()'
```

A few things I can say additionally to explain why I couldn't make this smaller:
 
* If I remove the struct column it works again 
* If I remove too many columns it also works again

**Comment by daviskirk** [comment]
Thanks, I was able to build something to reproduce it this way:

```python
pl.DataFrame(
    [
        pl.Series("c1", [{'a': 'foo', 'b': 'bar'}], dtype=pl.Struct),
        pl.Series("c2", [18]),
    ]
).write_parquet("a.parquet")
pl.scan_parquet("./a.parquet").select("c1").collect()
```

**Comment by ritchie46** [comment]
Thanks, taking a look.
