### ISSUE TITLE
Panic when filtering any column when a Decimal column is present in the dataframe

### ISSUE THREAD

**Issue by aleewen** [pola-rs/polars#12516]
### Checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pypi.org/project/polars/) of Polars.

### Reproducible example

```python
os.environ["POLARS_VERBOSE"] = '1'

# Allow pl.Decimal columns
pl.Config(activate_decimals=True)

# Make a dataframe with columns: pl.Decimal, pl.Utf8, pl.Int64
my_df = (pl.DataFrame({'col1': [0.123456, 0.789101112, -0.1314151617],
                       'col2': ['A', 'B', 'C'],
                       'col3': [1, 2, 3]})
         .with_columns([
             pl.col('col1').cast(pl.Decimal(precision=18, scale=10))
         ]))

# This logic throws an error
my_df.filter(pl.col('col2').str.len_chars() > 1)

# But this line creates a pl.Series of pl.UInt32 without any issues
my_df['col2'].str.len_chars()

# Even this simple filter does not work
my_df.filter(pl.col('col2') == 'A')

# It's not just pl.Utf8 columns, this filter does not work either
my_df.filter(pl.col('col3') == 1)

os.environ.get('stderr')
```

### Log output

```shell
thread '<unnamed>' panicked at crates\polars-arrow\src\array\mod.rs:304:33:
operator does not support primitive `Int128`
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
Traceback (most recent call last):
  File "C:\Users\aleewen\Documents\polars_bug_report.py", line 14, in <module>
    my_df.filter(pl.col('col2').str.len_chars() > 1)
  File "C:\Users\aleewen\.pyenv\pyenv-win\versions\3.10.5\lib\site-packages\polars\dataframe\frame.py", line 4028, in filter
    return self.lazy().filter(*predicates, **constraints).collect(_eager=True)
  File "C:\Users\aleewen\.pyenv\pyenv-win\versions\3.10.5\lib\site-packages\polars\utils\deprecation.py", line 100, in wrapper
    return function(*args, **kwargs)
  File "C:\Users\aleewen\.pyenv\pyenv-win\versions\3.10.5\lib\site-packages\polars\lazyframe\frame.py", line 1788, in collect
    return wrap_df(ldf.collect())
pyo3_runtime.PanicException: operator does not support primitive `Int128`
```

### Issue description

Apologies if this issue is already opened elsewhere and I could not find it.

When there is a pl.Decimal column present in the dataframe, `df.filter()` does not work, even if the filtering condition logic has nothing to do with the pl.Decimal column.

A PanicException is thrown, claiming 'operator does not support primitive Int128'
This may be related to issue #12375 

### Expected behavior

We would expect `df.filter` to work, especially when the filter logic does not have anything to do with the pl.Decimal column

### Installed versions

<details>

```
--------Version info---------
Polars:              0.19.13
Index type:          UInt32
Platform:            Windows-10-10.0.19045-SP0
Python:              3.10.5 (tags/v3.10.5:f377153, Jun  6 2022, 16:14:13) [MSC v.1929 64 bit (AMD64)]

----Optional dependencies----
adbc_driver_sqlite:  <not installed>
cloudpickle:         <not installed>
connectorx:          0.3.2
deltalake:           <not installed>
fsspec:              <not installed>
gevent:              <not installed>
matplotlib:          <not installed>
numpy:               1.26.2
openpyxl:            3.1.2
pandas:              2.1.3
pyarrow:             14.0.1
pydantic:            2.5.0
pyiceberg:           <not installed>
pyxlsb:              <not installed>
sqlalchemy:          2.0.23
xlsx2csv:            0.8.1
xlsxwriter:          <not installed>
```

</details>

**Comment by aleewen** [comment]
Perfect, thank you. I suppose the fix will be present in the next release?
