### ISSUE TITLE
scan_parquet operation timed out reading from Azure Blob Storage

### ISSUE THREAD

**Issue by j-ricketts** [pola-rs/polars#12596]
### Checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pypi.org/project/polars/) of Polars.

### Reproducible example

```python
df = pl.scan_parquet(
    source=f"abfs://{container_name}/{file_to_download}",
    storage_options={
        'azure_storage_account_name': storage_account_name,
        'azure_use_azure_cli': 'true',
    }
)
df.collect(streaming=True)
```

### Log output

```shell
POLARS PREFETCH_SIZE: 16
RUN STREAMING PIPELINE
parquet -> ordered_sink
RefCell { value: [] }
STREAMING CHUNK SIZE: 1000 rows
POLARS ROW_GROUP PREFETCH_SIZE: 128
Traceback (most recent call last):
  File "c:/../credentialTesting.py", line 185, in <module>
    df.collect(streaming=True)
  File "c:\Miniconda\envs\dev-4\lib\site-packages\polars\utils\deprecation.py", line 100, in wrapper
    return function(*args, **kwargs)
  File "c:\Miniconda\envs\dev-4\lib\site-packages\polars\lazyframe\frame.py", line 1788, in collect
    return wrap_df(ldf.collect())
polars.exceptions.ComputeError: Generic MicrosoftAzure error: request or response body error: operation timed out
```

### Issue description

The latest version of Polars is failing to collect a LazyFrame from Azure Blob Storage. In contrast, Polars==0.19.10 works without any problem.

### Expected behavior

Lazyframe successfully collects.

### Installed versions

<details>

```
--------Version info---------
Polars:              0.19.15
Index type:          UInt32
Platform:            Windows-10-10.0.17763-SP0
Python:              3.8.5 (default, Sep  3 2020, 21:29:08) [MSC v.1916 64 bit (AMD64)]

----Optional dependencies----
adbc_driver_sqlite:  <not installed>
cloudpickle:         <not installed>
connectorx:          <not installed>
deltalake:           0.13.0
fsspec:              2023.10.0
gevent:              <not installed>
matplotlib:          <not installed>
numpy:               1.24.4
openpyxl:            <not installed>
pandas:              2.0.3
pyarrow:             14.0.1
pydantic:            <not installed>
pyiceberg:           <not installed>
pyxlsb:              <not installed>
sqlalchemy:          <not installed>
xlsx2csv:            <not installed>
xlsxwriter:          <not installed>
```

</details>

**Comment by ritchie46** [comment]
You can increase the number of retrys. Or reduce concurrency limit by setting `POLARS_CONCURRENCY_BUDGET=10`

**Comment by deanm0000** [comment]
@ritchie46 what's the default concurrency_budget if unspecified? infinite?

**Comment by ritchie46** [comment]
No, equal to the number of cores on your machine or 10. Whichever is lower.

The thing is, within a datacenter you want this to be high. If you run local fast away from the data, you want it lower.

**Comment by ion-elgreco** [comment]
To what value do you have to set it then to cloud? I think this will be a lot of unexpected behavior for many who use azure.

Can't the default concurrency budget be inferred based on the URI (source)?

**Comment by inigohidalgo** [comment]
@ion-elgreco are you able to test authenticating with a token or a different method which isn't the CLI? I am facing the same issue when authenticating using the CLI, but if I switch to identify using client_id, client_secret and tenant_id, everything runs.

**Comment by inigohidalgo** [comment]
@ritchie46 I don't know if it's related, but when instantiating a pyarrow parquet dataset using adlfs, if I am using the interactive authentication I first have to do a `blob_fs.ls(container_name)` before actually instantiating the `pq.ParquetDataset(filesystem=blob_fs`)

**Comment by deanm0000** [comment]
> To what value do you have to set it then to use polars in cloud? I think this will be a lot of unexpected behavior for many who use azure.
> 
> Can't the default concurrency budget be inferred based on the URI (source)?

It's probably based more on your own connection. I've never messed with that setting and azure *just works* most of the time. I'm on WiFi so I blame that on the intermittent issues. If I'm using a remote VM then it works flawlessly, as you'd expect.

**Comment by empowerVictor** [comment]
Same with `0.19.19`
