### ISSUE TITLE
`.scan_parquet` causing `PanicException` instead of raising a vstack `ShapeError`

### ISSUE THREAD

**Issue by cmdlineluser** [pola-rs/polars#12594]
### Checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pypi.org/project/polars/) of Polars.

### Reproducible example

```python
import polars as pl
import tempfile

f1 = tempfile.NamedTemporaryFile()
f2 = tempfile.NamedTemporaryFile()

pl.select(a = 1, b = 2).write_parquet(f1.name)
pl.select(c = 3, d = 4).write_parquet(f2.name)

f1.seek(0)
f2.seek(0)

pl.scan_parquet([f1.name, f2.name]).collect()

# thread '<unnamed>' panicked at '/Users/runner/work/polars/polars/crates/polars-parquet/src/arrow/read/deserialize/mod.rs:141:31:
# called `Option::unwrap()` on a `None` value
```

### Log output

```shell
thread 'thread '<unnamed><unnamed>' panicked at ' panicked at /Users/runner/work/polars/polars/crates/polars-parquet/src/arrow/read/deserialize/mod.rs:141:31:
called `Option::unwrap()` on a `None` value
```

### Issue description

I tested the last few versions and it seems `0.19.10` is the last version to give the expected vtstack error.
```python
# polars.exceptions.ShapeError: unable to vstack, column names don't match: "a" and "c"
```
https://github.com/pola-rs/polars/blob/2adc6692ce9b2dee148dadb146e4904169f13d6c/crates/polars-parquet/src/arrow/read/deserialize/mod.rs#L141

### Expected behavior

ShapeError.

### Installed versions

<details>

```
--------Version info---------
Polars:              0.19.15
Index type:          UInt32
Platform:            macOS-12.6.7-arm64-arm-64bit
Python:              3.11.6 (main, Oct  2 2023, 20:46:17) [Clang 14.0.0 (clang-1400.0.29.202)]

----Optional dependencies----
adbc_driver_sqlite:  <not installed>
cloudpickle:         <not installed>
connectorx:          <not installed>
deltalake:           <not installed>
fsspec:              2023.6.0
gevent:              <not installed>
matplotlib:          <not installed>
numpy:               1.25.0
openpyxl:            <not installed>
pandas:              2.0.3
pyarrow:             12.0.1
pydantic:            <not installed>
pyiceberg:           <not installed>
pyxlsb:              <not installed>
sqlalchemy:          <not installed>
xlsx2csv:            <not installed>
xlsxwriter:          <not installed>
```

</details>

**Comment by cmdlineluser** [comment]
This now raises a SchemaError.

```
SchemaError: schema names differ at index 0: a != c
```
