### ISSUE TITLE
Panic When Reading Struct Columns From Parquet File

### ISSUE THREAD

**Issue by harrymconner** [pola-rs/polars#12610]
### Checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pypi.org/project/polars/) of Polars.

### Reproducible example

I'm getting the below results for any arbitrary parquet file with struct columns.

```python
pl.read_parquet("my_file.parquet").collect() # reading the parquet file fails
pl.read_parquet("my_file.parquet", use_pyarrow=True).collect() # reading the parquet file with pyarrow works, however

pl.scan_parquet("my_file.parquet").collect() # scanning the parquet file fails

pl.scan_parquet("my_file.parquet").drop("StructCol1").collect() # dropping the struct column works
pl.scan_parquet("my_file.parquet").head(116508).collect() # keeping the struct column, but selecting less than 116,509 rows works
```

### Issue description

When I try to scan the parquet file, I get the following PanicException:

pyo3_runtime.PanicException: called `Result::unwrap()` on an `Err` value: ComputeError(ErrString("The children must have an equal number of values. However, the values at index 1 have a length of 116508, which is different from values at index 0, 116509."))

However, when I select less than 116,508 rows, I no longer get a panic. Reverting back to polars 0.19.14 resolves the issue. Happy to provide any additional details!

### Expected behavior

```python
pl.scan_parquet("my_file.parquet").collect() # the parquet file is scanned and collected
```

### Installed versions

<details>

```
--------Version info---------
Polars:              0.19.15
Index type:          UInt32
Platform:            Windows-10-10.0.22621-SP0
Python:              3.11.6 (tags/v3.11.6:8b6ee5b, Oct  2 2023, 14:57:12) [MSC v.1935 64 bit (AMD64)]

----Optional dependencies----
adbc_driver_sqlite:  <not installed>
cloudpickle:         <not installed>
connectorx:          0.3.2
deltalake:           <not installed>
fsspec:              <not installed>
gevent:              <not installed>
matplotlib:          <not installed>
numpy:               1.26.2
openpyxl:            <not installed>
pandas:              <not installed>
pyarrow:             13.0.0
pydantic:            <not installed>
pyiceberg:           <not installed>
pyxlsb:              <not installed>
sqlalchemy:          <not installed>
xlsx2csv:            0.8.1
xlsxwriter:          3.1.9
```

</details>

**Comment by deanm0000** [comment]
Can confirm using this file:

```
(
    pl.select(
        a=pl.repeat(1, 200_000), 
        b=pl.int_range(0, 200_000)
        )
    .with_columns(
        c=pl.struct('a','b')
        )
    .write_parquet('blah.parquet')
)
#Now reading
pl.read_parquet('blah.parquet')
thread '<unnamed>' panicked at crates/polars-arrow/src/array/struct_/mod.rs:117:52:
called `Result::unwrap()` on an `Err` value: ComputeError(ErrString("The children must have an equal number of values.\n                         However, the values at index 1 have a length of 116508, which is different from values at index 0, 200000."))
stack backtrace:
   0: rust_begin_unwind
             at /rustc/dd430bc8c22f57992ec1457a87437d14283fdd65/library/std/src/panicking.rs:645:5
   1: core::panicking::panic_fmt
             at /rustc/dd430bc8c22f57992ec1457a87437d14283fdd65/library/core/src/panicking.rs:72:14
   2: core::result::unwrap_failed
             at /rustc/dd430bc8c22f57992ec1457a87437d14283fdd65/library/core/src/result.rs:1649:5
   3: <polars_parquet::arrow::read::deserialize::struct_::StructIterator as core::iter::traits::iterator::Iterator>::next
   4: <core::iter::adapters::map::Map<I,F> as core::iter::traits::iterator::Iterator>::next
   5: polars_io::parquet::read_impl::column_idx_to_series
   6: rayon::iter::plumbing::bridge_producer_consumer::helper
   7: <rayon_core::job::StackJob<L,F,R> as rayon_core::job::Job>::execute
   8: rayon_core::registry::WorkerThread::wait_until_cold
```

**Comment by harrymconner** [comment]
@deanm0000  thank you so much for the additional example!
