### ISSUE TITLE
Another int_range() negative-number bug

### ISSUE THREAD

**Issue by Wainberg** [pola-rs/polars#12674]
### Checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pypi.org/project/polars/) of Polars.

### Reproducible example

```python
>>> pl.DataFrame({'a': [1, 2]}).select(pl.int_range(pl.col.a.is_not_null().sum(), -1, -1))
thread '<unnamed>' panicked at crates/polars-plan/src/dsl/function_expr/range/int_range.rs:16:41:
called `Option::unwrap()` on a `None` value
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/wainberg/mambaforge/lib/python3.12/site-packages/polars/dataframe/frame.py", line 7791, in select
    return self.lazy().select(*exprs, **named_exprs).collect(_eager=True)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/wainberg/mambaforge/lib/python3.12/site-packages/polars/utils/deprecation.py", line 100, in wrapper
    return function(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/wainberg/mambaforge/lib/python3.12/site-packages/polars/lazyframe/frame.py", line 1788, in collect
    return wrap_df(ldf.collect())
                   ^^^^^^^^^^^^^
pyo3_runtime.PanicException: called `Option::unwrap()` on a `None` value
```

### Issue description

Only happens when step and end are negative. May be related to two other reported bugs (https://github.com/pola-rs/polars/issues/10849, https://github.com/pola-rs/polars/issues/10867) which also involve `int_range()` and negative numbers. Casting the result of `is_null()` to Int64, Int32 or UInt64 (but not UInt32) avoids the error.

### Expected behavior

Shouldn't give an error.

### Installed versions

<details>

```
--------Version info---------
Polars:              0.19.14
Index type:          UInt32
Platform:            Linux-3.10.0-1160.102.1.el7.x86_64-x86_64-with-glibc2.17
Python:              3.12.0 | packaged by conda-forge | (main, Oct  3 2023, 08:43:22) [GCC 12.3.0]

----Optional dependencies----
adbc_driver_sqlite:  <not installed>
cloudpickle:         <not installed>
connectorx:          <not installed>
deltalake:           <not installed>
fsspec:              <not installed>
gevent:              <not installed>
matplotlib:          3.8.1
numpy:               1.26.0
openpyxl:            3.1.2
pandas:              2.1.3
pyarrow:             14.0.1
pydantic:            <not installed>
pyiceberg:           <not installed>
pyxlsb:              <not installed>
sqlalchemy:          <not installed>
xlsx2csv:            0.8.1
xlsxwriter:          3.1.9
```

</details>

**Comment by Wainberg** [comment]
This has since been fixed, closing.
