### ISSUE TITLE
Round trip between NumPy and Polars is returning at error

### ISSUE THREAD

**Issue by thomasjpfan** [pola-rs/polars#12696]
### Checks

- [X] I have checked that this issue has not already been reported.
- [X] I have confirmed this bug exists on the [latest version](https://pypi.org/project/polars/) of Polars.

### Reproducible example

```python
import numpy as np
import polars as pl
from polars.testing import assert_frame_equal

shape = (20, 10)
x = np.ones(shape=shape, dtype=np.float64)
names = [f"col_{i}" for i in range(shape[1])]

df1 = pl.DataFrame(x, schema=names)
df1_array = np.asarray(df1)
assert df1_array.shape == shape

df2 = pl.DataFrame(df1_array, schema=names)
assert_frame_equal(df1, df2)
```

### Log output

```shell
Traceback (most recent call last):
  File "/Users/thomasfan/Desktop/playground/polars_reg.py", line 13, in <module>
    df2 = pl.DataFrame(df_array, schema=names)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/thomasfan/miniforge3/envs/polars/lib/python3.11/site-packages/polars/dataframe/frame.py", line 381, in __init__
    self._df = numpy_to_pydf(
               ^^^^^^^^^^^^^^
  File "/Users/thomasfan/miniforge3/envs/polars/lib/python3.11/site-packages/polars/utils/_construction.py", line 1429, in numpy_to_pydf
    raise ValueError(
ValueError: dimensions of `schema` (10) must match data dimensions (20)
```

### Issue description

The code snippet worked with `0.19.15` and started failing in `0.19.16`.

### Expected behavior

I expect the assertion in the code snippet to pass.

### Installed versions

<details>

```
--------Version info---------
Polars:              0.19.16
Index type:          UInt32
Platform:            macOS-14.1.1-arm64-arm-64bit
Python:              3.11.6 | packaged by conda-forge | (main, Oct  3 2023, 10:37:07) [Clang 15.0.7 ]

----Optional dependencies----
adbc_driver_sqlite:  <not installed>
cloudpickle:         <not installed>
connectorx:          <not installed>
deltalake:           <not installed>
fsspec:              <not installed>
gevent:              <not installed>
matplotlib:          <not installed>
numpy:               1.26.2
openpyxl:            <not installed>
pandas:              <not installed>
pyarrow:             <not installed>
pydantic:            <not installed>
pyiceberg:           <not installed>
pyxlsb:              <not installed>
sqlalchemy:          <not installed>
xlsx2csv:            <not installed>
xlsxwriter:          <not installed>
```

</details>

**Comment by MarcoGorelli** [comment]
thanks for the report - @alexander-beedie do you know about this one?

**Comment by cmdlineluser** [comment]
If you remove the `schema` it creates a dataframe of 20 rows and 10 columns.

Forcing the orientation also "works".

```python
df2 = pl.DataFrame(df1_array, schema=names, orient="row")
```

**Comment by alexander-beedie** [comment]
> thanks for the report - @alexander-beedie do you know about this one?

Hmmm... I should be able to work this out first thing tomorrow AM 🤔
