### ISSUE TITLE
PanicException: index out of bounds: the len is 1 but the index is 1

### ISSUE THREAD

**Issue by Object905** [pola-rs/polars#12711]
### Checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pypi.org/project/polars/) of Polars.

### Reproducible example
```python
df = pl.LazyFrame(
    [],
    {
        "list1": pl.List(pl.UInt8),
        "list2": pl.List(pl.UInt8),
    },
)
df.select(pl.col("list2").list.set_intersection(pl.col("list1"))).collect()
```

### Log output

```shell
thread '<unnamed>' panicked at crates/polars-ops/src/chunked_array/list/sets.rs:152:20:
index out of bounds: the len is 1 but the index is 1
stack backtrace:
   0:     0x7f977e39fc05 - std::backtrace_rs::backtrace::libunwind::trace::ha293b6d87ccf1f1c
                               at /rustc/dd430bc8c22f57992ec1457a87437d14283fdd65/library/std/src/../../backtrace/src/backtrace/libunwind.rs:104:5
   1:     0x7f977e39fc05 - std::backtrace_rs::backtrace::trace_unsynchronized::h490dbd5f01054bca
                               at /rustc/dd430bc8c22f57992ec1457a87437d14283fdd65/library/std/src/../../backtrace/src/backtrace/mod.rs:66:5
   2:     0x7f977e39fc05 - std::sys_common::backtrace::_print_fmt::hb9cac74d01a13d4b
                               at /rustc/dd430bc8c22f57992ec1457a87437d14283fdd65/library/std/src/sys_common/backtrace.rs:67:5
   3:     0x7f977e39fc05 - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::hcf57bf5852a8c416
                               at /rustc/dd430bc8c22f57992ec1457a87437d14283fdd65/library/std/src/sys_common/backtrace.rs:44:22
   4:     0x7f977bfcd7c0 - core::fmt::rt::Argument::fmt::h5de7bc4768ddf33e
                               at /rustc/dd430bc8c22f57992ec1457a87437d14283fdd65/library/core/src/fmt/rt.rs:142:9
   5:     0x7f977bfcd7c0 - core::fmt::write::hbbbf6d556f1ac8b9
                               at /rustc/dd430bc8c22f57992ec1457a87437d14283fdd65/library/core/src/fmt/mod.rs:1120:17
   6:     0x7f977e364f1e - std::io::Write::write_fmt::h1b479e1ec81bc956
                               at /rustc/dd430bc8c22f57992ec1457a87437d14283fdd65/library/std/src/io/mod.rs:1762:15
   7:     0x7f977e3a19be - std::sys_common::backtrace::_print::hd9cfabd7d6a771d4
                               at /rustc/dd430bc8c22f57992ec1457a87437d14283fdd65/library/std/src/sys_common/backtrace.rs:47:5
   8:     0x7f977e3a19be - std::sys_common::backtrace::print::h07393481cb263284
                               at /rustc/dd430bc8c22f57992ec1457a87437d14283fdd65/library/std/src/sys_common/backtrace.rs:34:9
   9:     0x7f977e3a1257 - std::panicking::default_hook::{{closure}}::hb1598819f87c42e5
  10:     0x7f977e3a226b - std::panicking::default_hook::h7f873e973269c845
                               at /rustc/dd430bc8c22f57992ec1457a87437d14283fdd65/library/std/src/panicking.rs:292:9
  11:     0x7f977e3a226b - std::panicking::rust_panic_with_hook::he9c5618dc5aecbda
                               at /rustc/dd430bc8c22f57992ec1457a87437d14283fdd65/library/std/src/panicking.rs:779:13
  12:     0x7f977e3a1d3c - std::panicking::begin_panic_handler::{{closure}}::h2aa2ac3b94c55dff
                               at /rustc/dd430bc8c22f57992ec1457a87437d14283fdd65/library/std/src/panicking.rs:657:13
  13:     0x7f977e3a1c96 - std::sys_common::backtrace::__rust_end_short_backtrace::h1526146ec2c337f0
                               at /rustc/dd430bc8c22f57992ec1457a87437d14283fdd65/library/std/src/sys_common/backtrace.rs:170:18
  14:     0x7f977e3a1c81 - rust_begin_unwind
                               at /rustc/dd430bc8c22f57992ec1457a87437d14283fdd65/library/std/src/panicking.rs:645:5
  15:     0x7f977b0b9e54 - core::panicking::panic_fmt::h3ad8aa1488901c59
                               at /rustc/dd430bc8c22f57992ec1457a87437d14283fdd65/library/core/src/panicking.rs:72:14
  16:     0x7f977b0b9f51 - core::panicking::panic_bounds_check::h57c70ef0c36e14c7
                               at /rustc/dd430bc8c22f57992ec1457a87437d14283fdd65/library/core/src/panicking.rs:190:5
  17:     0x7f977d479e0f - polars_ops::chunked_array::list::sets::array_set_operation::h463ac00da62cd830
  18:     0x7f977d46ae0c - <core::iter::adapters::GenericShunt<I,R> as core::iter::traits::iterator::Iterator>::next::h5424154e2a006c83
  19:     0x7f977dd5b605 - <F as polars_plan::dsl::expr_dyn_fn::SeriesUdf>::call_udf::h60225b13d9d85903
  20:     0x7f977d223312 - polars_lazy::physical_plan::expressions::apply::ApplyExpr::eval_and_flatten::hc34d32f3cdd17131
  21:     0x7f977d21aa54 - <polars_lazy::physical_plan::expressions::apply::ApplyExpr as polars_lazy::physical_plan::expressions::PhysicalExpr>::evaluate::h5b77815cc28f517d
  22:     0x7f977d2b2516 - polars_lazy::physical_plan::executors::projection_utils::run_exprs_seq::h55a667f5e6efaefd
  23:     0x7f977d2b1e2d - polars_lazy::physical_plan::executors::projection_utils::evaluate_physical_expressions::h24c4ffd4d75a52db
  24:     0x7f977d3429bd - polars_lazy::physical_plan::executors::projection::ProjectionExec::execute_impl::h76e8bb4aad628680
  25:     0x7f977d342206 - <polars_lazy::physical_plan::executors::projection::ProjectionExec as polars_lazy::physical_plan::executors::executor::Executor>::execute::h0710198a0890a0e5
  26:     0x7f977d2a36e3 - polars_lazy::frame::LazyFrame::collect::ha399ac0a69ea1ad1
  27:     0x7f977bdd2d0e - polars::lazyframe::_::<impl polars::lazyframe::PyLazyFrame>::__pymethod_collect__::h53c817815072c7da
  28:     0x7f977b7613e7 - pyo3::impl_::trampoline::trampoline::h74be9d104d105ab7
  29:     0x7f97b35ba48f - <unknown>
  30:     0x7f97b35f7374 - PyObject_Vectorcall
  31:     0x7f97b3506b46 - _PyEval_EvalFrameDefault
  32:     0x7f97b35fbe7a - <unknown>
  33:     0x7f97b35b2782 - <unknown>
  34:     0x7f97b34ff11a - _PyEval_EvalFrameDefault
  35:     0x7f97b35fbe7a - <unknown>
  36:     0x7f97b35b2782 - <unknown>
  37:     0x7f97b34ff11a - _PyEval_EvalFrameDefault
  38:     0x7f97b35fbe7a - <unknown>
  39:     0x7f97b35b2782 - <unknown>
  40:     0x7f97b34ff11a - _PyEval_EvalFrameDefault
  41:     0x7f97b3771eb7 - PyEval_EvalCode
  42:     0x7f97b3775356 - <unknown>
  43:     0x7f97b377548a - <unknown>
  44:     0x7f97b37755a3 - <unknown>
  45:     0x7f97b377c956 - _PyRun_SimpleFileObject
  46:     0x7f97b377d4d0 - _PyRun_AnyFileObject
  47:     0x7f97b3781f8c - Py_RunMain
  48:     0x7f97b3245cd0 - <unknown>
  49:     0x7f97b3245d8a - __libc_start_main
  50:     0x55dd5f205055 - _start
  51:                0x0 - <unknown>
```

### Issue description

Regression after upgrading to 0.19.16. Does not happen on 0.19.15

### Expected behavior

No crashing

### Installed versions

<details>

```
--------Version info---------
Polars:               0.19.17
Index type:           UInt32
Platform:             Linux-6.6.2-arch1-1-x86_64-with-glibc2.38
Python:               3.12.0 (main, Nov 13 2023, 06:10:14) [GCC 13.2.1 20230801]

----Optional dependencies----
adbc_driver_manager:  <not installed>
cloudpickle:          3.0.0
connectorx:           <not installed>
deltalake:            <not installed>
fsspec:               <not installed>
gevent:               23.9.1
matplotlib:           <not installed>
numpy:                1.26.2
openpyxl:             <not installed>
pandas:               2.1.3
pyarrow:              14.0.1
pydantic:             2.5.2
pyiceberg:            <not installed>
pyxlsb:               <not installed>
sqlalchemy:           2.0.23
xlsx2csv:             0.8.1
xlsxwriter:           3.1.9
```

</details>

**Comment by ritchie46** [comment]
Can you please try to create a repro. It's hard to fix without.

**Comment by Object905** [comment]
@ritchie46 
Updated issue to include reproducible example.
Also verified that crash still happens on latest master [d3ecfe1](https://github.com/pola-rs/polars/commit/d3ecfe162e8e54fc9bb2f7062629e3d38f8a6059).
