### ISSUE TITLE
decimal.Decimal -> to_numpy regressed in 0.19.17

### ISSUE THREAD

**Issue by theunkn0wn1** [pola-rs/polars#12730]
### Checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pypi.org/project/polars/) of Polars.

### Reproducible example

```python
from decimal import Decimal
import polars
# data is originating from a more complex origin, but simplified to a literal for simplicity.
data = [{ "temperature": Decimal('35.65'), "name":"potato", "result": 42.42} ]
# cast data to polars dataframe for data science
df = polars.DataFrame(data)
# ... do stuff on the data frame (nothing for sake of concise example)
# Eventually, cast it to numpy (Actually passed directly to Plotly, which casts to numpy)
print(df.to_numpy())  # explosion
```

### Log output

```shell
root@35d03eb7dba6:/# POLARS_VERBOSE=1 python3
Python 3.11.6 (main, Nov 21 2023, 18:16:39) [GCC 12.2.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from decimal import Decimal
>>> import polars
>>> # data is originating from a more complex origin, but simplified to a literal for simplicity.
>>> data = [{ "temperature": Decimal('42.42'), "name":"potato", "result": 42.42} ]
>>> # cast data to polars dataframe for data science
>>> df = polars.DataFrame(data)
>>> # ... do stuff on the data frame (in this case nothing)
>>> # Eventually, cast it to numpy (Actually passed directly to Plotly, which casts to numpy)
>>> print(df.to_numpy())  # explosion
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.11/site-packages/polars/utils/deprecation.py", line 192, in wrapper
    return function(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/polars/dataframe/frame.py", line 2123, in to_numpy
    [self.to_series(i).to_numpy() for i in range(self.width)]
  File "/usr/local/lib/python3.11/site-packages/polars/dataframe/frame.py", line 2123, in <listcomp>
    [self.to_series(i).to_numpy() for i in range(self.width)]
     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/polars/series/series.py", line 4083, in to_numpy
    np_array = self._view(ignore_nulls=True)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/polars/series/series.py", line 4128, in _view
    ptr_type = dtype_to_ctype(self.dtype)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/polars/datatypes/convert.py", line 354, in dtype_to_ctype
    raise NotImplementedError(
NotImplementedError: conversion of polars data type Decimal to C-type not implemented
```

### Issue description

Polars 0.19.17 throws an exception when casting data including `decimal.Decimal` instances to numpy types.
Polars `>=1.19.13,<0.19.17` handles this data without throwing an exception.

### Expected behavior

Polars should transparently handle `Decimal` instances, as it did in prior versions.
```py
>>> from decimal import Decimal
>>> import polars
>>> # data is originating from a more complex origin, but simplified to a literal for simplicity.
>>> data = [{ "temperature": Decimal('35.65'), "name":"potato", "result": 42.42} ]
>>> # cast data to polars dataframe for data science
>>> df = polars.DataFrame(data)
>>> # ... do stuff on the data frame (nothing for sake of concise example)
>>> # Eventually, cast it to numpy (Actually passed directly to Plotly, which casts to numpy)
>>> print(df.to_numpy())  # explosion
[[35.65 'potato' 42.42]]

```

### Installed versions

<details>

```
>>> polars.show_versions()
--------Version info---------
Polars:               0.19.17
Index type:           UInt32
Platform:             Linux-5.15.0-84-generic-x86_64-with-glibc2.36
Python:               3.11.6 (main, Nov 21 2023, 18:16:39) [GCC 12.2.0]

----Optional dependencies----
adbc_driver_manager:  <not installed>
cloudpickle:          <not installed>
connectorx:           <not installed>
deltalake:            <not installed>
fsspec:               <not installed>
gevent:               <not installed>
matplotlib:           <not installed>
numpy:                1.26.2
openpyxl:             <not installed>
pandas:               <not installed>
pyarrow:              <not installed>
pydantic:             <not installed>
pyiceberg:            <not installed>
pyxlsb:               <not installed>
sqlalchemy:           <not installed>
xlsx2csv:             <not installed>
xlsxwriter:           <not installed>

```

</details>

**Comment by cmdlineluser** [comment]
Can't seem to reproduce here:
```python
from decimal import Decimal
import polars

data = [{ "temperature": Decimal('35.65'), "name":"potato", "result": 42.42} ]

df = polars.DataFrame(data)

print(df.to_numpy())
# [[Decimal('35.65') 'potato' 42.42]]
```
```python
pl.show_versions()
```
```python
--------Version info---------
Polars:               0.19.17
Index type:           UInt32
Platform:             macOS-13.6.1-arm64-arm-64bit
Python:               3.11.6 (main, Nov  2 2023, 04:39:40) [Clang 14.0.0 (clang-1400.0.29.202)]

----Optional dependencies----
adbc_driver_manager:  <not installed>
cloudpickle:          <not installed>
connectorx:           <not installed>
deltalake:            <not installed>
fsspec:               2023.6.0
gevent:               <not installed>
matplotlib:           <not installed>
numpy:                1.26.2
openpyxl:             <not installed>
pandas:               2.0.3
pyarrow:              12.0.1
pydantic:             <not installed>
pyiceberg:            <not installed>
pyxlsb:               <not installed>
sqlalchemy:           <not installed>
xlsx2csv:             <not installed>
xlsxwriter:           <not installed>
```

**Comment by alexander-beedie** [comment]
I can see how to repro; you need to _not_ have `pyarrow` installed, then it goes down a slightly different codepath. Will triage a little further...
