### ISSUE TITLE
Panic when melting since 0.19.14

### ISSUE THREAD

**Issue by bouianpe** [pola-rs/polars#12813]
### Checks

- [x] I have checked that this issue has not already been reported.

- [x] I have confirmed this bug exists on the [latest version](https://pypi.org/project/polars/) of Polars.

### Reproducible example

```python
import os
import polars as pl

os.environ["RUST_BACKTRACE"] = "1"

df = pl.scan_parquet("test1.parquet").collect()
df.melt()
```
[test1.zip](https://github.com/pola-rs/polars/files/13515696/test1.zip)
```python
import os
import polars as pl

os.environ["RUST_BACKTRACE"] = "1"

df = pl.scan_parquet("test4.parquet").collect()
df.melt()
```
[test4.zip](https://github.com/pola-rs/polars/files/13515695/test4.zip)

### Log output

```shell
thread '<unnamed>' panicked at crates\polars-core\src\frame\explode.rs:322:57:
called `Result::unwrap()` on an `Err` value: ComputeError(ErrString("cannot cast List type (inner: 'Struct([Field { name: \"code\", dtype: Utf8 }, Field { name: \"description\", dtype: Utf8 }])', to: 'Utf8')"))
stack backtrace:
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
Traceback (most recent call last):
  File "<PATH>\parquet_test.py", line 53, in <module>
    df.melt()
  File "<PATH>\virtualenvs\tools-J7sPKjr_-py3.9\lib\site-packages\polars\dataframe\frame.py", line 7227, in melt
    self._df.melt(id_vars, value_vars, value_name, variable_name)
pyo3_runtime.PanicException: called `Result::unwrap()` on an `Err` value: ComputeError(ErrString("cannot cast List type (inner: 'Struct([Field { name: \"code\", dtype: Utf8 }, Field { name: \"description\", dtype: Utf8 }])', to: 'Utf8')"))


thread '<unnamed>' panicked at crates\polars-arrow\src\array\growable\mod.rs:114:22:
called `Option::unwrap()` on a `None` value
stack backtrace:
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
Traceback (most recent call last):
  File "<PATH>\parquet_test.py", line 53, in <module>
    df.melt()
  File "<PATH>\virtualenvs\tools-J7sPKjr_-py3.9\lib\site-packages\polars\dataframe\frame.py", line 7227, in melt
    self._df.melt(id_vars, value_vars, value_name, variable_name)
pyo3_runtime.PanicException: called `Option::unwrap()` on a `None` value
```

### Issue description

Since upgrading from 0.19.14, polars panics on melting the sample dataframes

### Expected behavior

no panic. code works w/ 0.19.14

### Installed versions

<details>

```
--------Version info---------
Polars:               0.19.18
Index type:           UInt32
Platform:             Windows-10-10.0.17763-SP0
Python:               3.9.13 (tags/v3.9.13:6de2ca5, May 17 2022, 16:36:42) [MSC v.1929 64 bit (AMD64)]

----Optional dependencies----
adbc_driver_manager:  0.8.0
cloudpickle:          <not installed>
connectorx:           <not installed>
deltalake:            <not installed>
fsspec:               2023.10.0
gevent:               <not installed>
matplotlib:           <not installed>
numpy:                1.26.2
openpyxl:             <not installed>
pandas:               2.1.3
pyarrow:              14.0.1
pydantic:             2.5.2
pyiceberg:            <not installed>
pyxlsb:               <not installed>
sqlalchemy:           2.0.23
xlsx2csv:             <not installed>
xlsxwriter:           3.1.9
```

</details>

**Comment by bouianpe** [comment]
Interesting, I am also now running into the same issue w/ my code not working on 0.19.14 (and the reason i had included the files is i was unable to repro it w/ just a pl.DataFrame, even w/ schema).
These trimmed down examples came out of a full file that works to `.scan_parquet(...).collect()` on 0.19.14 but not on anything newer, throwing
```
thread '<unnamed>' panicked at crates\polars-arrow\src\array\struct_\mod.rs:117:52:
called `Result::unwrap()` on an `Err` value: ComputeError(ErrString("The children must have an equal number of values.\n                         However, the values at index 1 have a length of 33518, which is different from values at index 0, 33695."))
```

**Comment by cmdlineluser** [comment]
Rather strange alright.

That particular error did come up recently in #12610

I tried modifying the examples a bit to see if I could get it to reproduce but haven't been able to.

**Comment by ritchie46** [comment]
```python
df = pl.DataFrame({
    "a": [[]],
    "b": [1]
}, schema={"a": pl.List(pl.Struct([pl.Field("a", pl.Utf8)])), "b": pl.Int32})
df.melt()
```

**Comment by ritchie46** [comment]
We need to implement a cast from struct to utf8 in polars-arrow to fix this.

**Comment by Dobatymo** [comment]
On Python 3.11, polars==1.14.0

```python
>>> import polars as pl
>>> pl.DataFrame({"rollNumber": ["a"], "values": [{"value": 1}], "list_col": [[]]}).melt()
<stdin>:1: DeprecationWarning: `DataFrame.melt` is deprecated. Use `unpivot` instead, with `index` instead of `id_vars` and `on` instead of `value_vars`
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "...\Python311\Lib\site-packages\polars\_utils\deprecation.py", line 59, in wrapper
    return function(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "...\Python311\Lib\site-packages\polars\dataframe\frame.py", line 11268, in melt
    return self.unpivot(
           ^^^^^^^^^^^^^
  File "...\Python311\Lib\site-packages\polars\dataframe\frame.py", line 8421, in unpivot
    return self._from_pydf(self._df.unpivot(on, index, value_name, variable_name))
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
polars.exceptions.InvalidOperationError: 'unpivot' not supported for dtype: list[null]

Consider casting to String.
```
