### ISSUE TITLE
pl.scan_ndjson with infer_schema_length=0 throws ComputeError(ErrString("Struct array must be created with a DataType whose physical type is Struct"))

### ISSUE THREAD

**Issue by corneliusroemer** [pola-rs/polars#12839]
### Checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pypi.org/project/polars/) of Polars.

### Reproducible example

```python
import polars as pl
with open("test.ndjson", "w") as f:
    f.write("""
{"seqName":"England/MILK-28D52E2/2021","nearestNodes":["B.1.617.2"]}
{"seqName":"USA/CO-CDPHE-2102374275/2021","nearestNodes":["B.1.617.2"]}
{"seqName":"Wales/PHWC-PGY3IH/2021","nearestNodes":["B.1.617.2"]}
""")

pl.scan_ndjson("test.ndjson", infer_schema_length=0).collect()
```

Tested on version 0.19.8, conda-forge, osx-arm

### Log output

```shell
thread '<unnamed>' panicked at crates/polars-arrow/src/array/struct_/mod.rs:238:41:
called `Result::unwrap()` on an `Err` value: ComputeError(ErrString("Struct array must be created with a DataType whose physical type is Struct"))
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
Traceback (most recent call last):
  File "/Users/corneliusromer/code/nextclade_data_workflows/sars-cov-2/test.py", line 9, in <module>
    pl.scan_ndjson("test.ndjson", infer_schema_length=0).collect()
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Caskroom/miniforge/base/envs/py11/lib/python3.11/site-packages/polars/io/ndjson.py", line 107, in scan_ndjson
    return pl.LazyFrame._scan_ndjson(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Caskroom/miniforge/base/envs/py11/lib/python3.11/site-packages/polars/lazyframe/frame.py", line 555, in _scan_ndjson
    self._ldf = PyLazyFrame.new_from_ndjson(
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
pyo3_runtime.PanicException: called `Result::unwrap()` on an `Err` value: ComputeError(ErrString("Struct array must be created with a DataType whose physical type is Struct"))
```

### Issue description

pl.scan_ndjson with infer_schema_length=0 throws ComputeError(ErrString("Struct array must be created with a DataType whose physical type is Struct"))

When setting infer_schema_length to a non-zero value everything works fine

### Expected behavior

No error thrown

### Installed versions

<details>

```
--------Version info---------
Polars:               0.19.18
Index type:           UInt32
Platform:             macOS-14.1.1-arm64-arm-64bit
Python:               3.11.6 | packaged by conda-forge | (main, Oct  3 2023, 10:37:07) [Clang 15.0.7 ]

----Optional dependencies----
adbc_driver_manager:  <not installed>
cloudpickle:          <not installed>
connectorx:           <not installed>
deltalake:            <not installed>
fsspec:               <not installed>
gevent:               <not installed>
matplotlib:           3.8.2
numpy:                1.26.2
openpyxl:             <not installed>
pandas:               1.5.3
pyarrow:              14.0.1
pydantic:             2.5.2
pyiceberg:            <not installed>
pyxlsb:               <not installed>
sqlalchemy:           <not installed>
xlsx2csv:             0.8.1
xlsxwriter:           <not installed>```

</details>

**Comment by kdn36** [comment]
As per 1.39.2:
```
ValueError: 'infer_schema_length' should be positive
```
