### ISSUE TITLE
`scan_parquet` + `sink_parquet` with same filename PanicException and file truncation

### ISSUE THREAD

**Issue by cmdlineluser** [pola-rs/polars#12843]
### Checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pypi.org/project/polars/) of Polars.

### Reproducible example

```python
import tempfile
import polars as pl

f = tempfile.NamedTemporaryFile()

df = pl.DataFrame({"A": [1]})
df.write_parquet(f.name)

print(pl.read_parquet(f.name))
# ┌─────┐
# │ A   │
# │ --- │
# │ i64 │
# ╞═════╡
# │ 1   │
# └─────┘

pl.scan_parquet(f.name).sink_parquet(f.name)
# ComputeError: parquet: File out of specification: A parquet file must contain a header and footer with at least 12 bytes
```

### Issue description

Just noticed Polars lets you use the same filename here, but it ends up truncating the file.

Not sure if this is supposed to be allowed or not, but if not, it should raise and leave the input intact?

### Expected behavior

"Work" or raise exception and leave input intact.

### Installed versions

<details>

```
--------Version info---------
Polars:               0.19.18
Index type:           UInt32
Platform:             macOS-13.6.1-arm64-arm-64bit
Python:               3.11.6 (main, Nov  2 2023, 04:39:40) [Clang 14.0.0 (clang-1400.0.29.202)]

----Optional dependencies----
adbc_driver_manager:  <not installed>
cloudpickle:          <not installed>
connectorx:           <not installed>
deltalake:            <not installed>
fsspec:               2023.6.0
gevent:               <not installed>
matplotlib:           <not installed>
numpy:                1.26.2
openpyxl:             <not installed>
pandas:               2.0.3
pyarrow:              12.0.1
pydantic:             <not installed>
pyiceberg:            <not installed>
pyxlsb:               <not installed>
sqlalchemy:           <not installed>
xlsx2csv:             <not installed>
xlsxwriter:           <not installed>
```

</details>

**Comment by Putnam14** [comment]
I just got bit by this too, `pl.scan_parquet(f.name).with_columns(pl.col(pl.Utf8).str.strip_chars()).sink_parquet(f.name)`.


The [seek_len function](https://github.com/pola-rs/polars/blame/b14091a14fc0465bd6c5b11636f0d5820c1f5d91/crates/polars-parquet/src/parquet/read/stream.rs#L11) feels sketchy at best to determine the file size...

On https://github.com/rust-lang/rust/issues/59359 there's mention of using `file.metadata().len()` to get the size of a file without requiring a mutable borrow, maybe that's a better fit here?

**Comment by cmdlineluser** [comment]
This seems to now panic on 1.8.2
```
thread '<unnamed>' panicked at crates/polars-io/src/parquet/read/mmap.rs:49:23:
range end index 92 out of range for slice of length 0
PanicException: range end index 92 out of range for slice of length 0
```

**Comment by cmdlineluser** [comment]
It seems this actually crashes Python now.

```python
# thread 'polars-0' panicked at crates/polars-io/src/parquet/read/mmap.rs:49:23:
# range end index 92 out of range for slice of length 0
# note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
# Rayon: detected unexpected panic; aborting
# Abort trap: 6
```

**Comment by owenprough-sift** [comment]
This no longer seems to panic or crash or fail on `polars==1.31.0`:
```python
>>> import polars as pl
>>> pl.__version__
'1.31.0'
>>> filename='test.parquet'
>>> pl.DataFrame({'a':[1]}).write_parquet(filename)
>>> pl.scan_parquet(filename).sink_parquet(filename)
>>> pl.read_parquet(filename)
shape: (1, 1)
┌─────┐
│ a   │
│ --- │
│ i64 │
╞═════╡
│ 1   │
└─────┘
```

**Comment by etiennebacher** [comment]
Can this be reopened? I don't know why it worked for @owenprough-sift because for me this still panics on 1.31.0 and 1.32.2:

```python
import polars as pl

filename = "test_foo.parquet"
pl.DataFrame({"a": [1]}).write_parquet(filename)
pl.scan_parquet(filename).sink_parquet(filename)
```
```
PanicException: called `Result::unwrap()` on an `Err` value: JoinError::Panic(Id(10), "range
end index 92 out of range for slice of length 0", ...)
```

**Comment by etiennebacher** [comment]
@cmdlineluser can this also be labelled "A - streaming"? 

`pl.scan_parquet(filename).sink_parquet(filename, engine="in-memory")` runs fine.

**Comment by cmdlineluser** [comment]
(I think only Collaborators can add labels?)

It also seems to crash Python again for me every so often.

```python
import polars as pl

filename = "test_foo.parquet"

for _ in range(10_000):
    pl.DataFrame({"a": [1]}).write_parquet(filename)
    try:
        pl.scan_parquet(filename).sink_parquet(filename)
    except pl.exceptions.PanicException:
        pass
```


```
# thread 'async-executor-5' panicked at crates/polars-stream/src/nodes/io_sources/parquet/mod.rs:257:80:
called `Result::unwrap()` on an `Err` value: JoinError::Panic(Id(29305), "range end index 92 out of range for slice of length 0", ...)
```
```
# zsh: bus error 
```
