### ISSUE TITLE
Stochastic bug: "polars.exceptions.SchemaError: invalid series dtype: expected `List`, got `str`"

### ISSUE THREAD

**Issue by corneliusroemer** [pola-rs/polars#12841]
### Checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pypi.org/project/polars/) of Polars.

### Reproducible example

```python
import polars as pl
import pkg_resources
from packaging import version


polars_version = version.parse((pkg_resources.get_distribution("polars").version))

print(f"Polars version: {polars_version}")

import requests

url = "https://gist.githubusercontent.com/corneliusroemer/c571208e307e38f4424fd8b3c2a348fd/raw/0608135754f2bb23c92256be361225d70b0a2226/nearest_nodes.ndjson"
r = requests.get(url, allow_redirects=True)
open('nearest_nodes.ndjson', 'wb').write(r.content)

priors = (
pl.scan_ndjson("nearest_nodes.ndjson", infer_schema_length=10000000)
.select(
    [
	pl.col("nearestNodes"),
	pl.col("nearestNodes")
	.list.len()
	.pow(-1)
	.alias("1/nearestNodesListLength"),
    ]
)
.filter(pl.col("nearestNodes").list.len() > 0)
.explode("nearestNodes")
.group_by("nearestNodes")
.sum()
.sort("1/nearestNodesListLength", descending=True)
.with_columns(
    [
	(
	    pl.col("1/nearestNodesListLength")
	    / pl.col("1/nearestNodesListLength").sum()
	).alias("priors"),
    ]
)
.with_columns(
    [
	pl.col("priors").log10().alias("log_priors"),
    ]
)
.collect()
)
print(priors)
```

Run this as is, but do it multiple times. The error only occurs about one in 3 times for me. So before thinking you can't reproduce, run it 20 times please, it takes only a second.

### Log output

```shell
When it fails:

/Users/corneliusromer/code/nextclade_data_workflows/sars-cov-2/test.py:2: DeprecationWarning: pkg_resources is deprecated as an API. See https://setuptools.pypa.io/en/latest/pkg_resources.html
  import pkg_resources
Polars version: 0.19.18
Traceback (most recent call last):
  File "/Users/corneliusromer/code/nextclade_data_workflows/sars-cov-2/test.py", line 45, in <module>
    .collect()
     ^^^^^^^^^
  File "/opt/homebrew/Caskroom/miniforge/base/envs/py11/lib/python3.11/site-packages/polars/utils/deprecation.py", line 100, in wrapper
    return function(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Caskroom/miniforge/base/envs/py11/lib/python3.11/site-packages/polars/lazyframe/frame.py", line 1788, in collect
    return wrap_df(ldf.collect())
                   ^^^^^^^^^^^^^
polars.exceptions.SchemaError: invalid series dtype: expected `List`, got `str`


When it works:

/Users/corneliusromer/code/nextclade_data_workflows/sars-cov-2/test.py:2: DeprecationWarning: pkg_resources is deprecated as an API. See https://setuptools.pypa.io/en/latest/pkg_resources.html
  import pkg_resources
Polars version: 0.19.18
dataframe filtered
estimated unique values: 8243
estimated unique count: 8243 exceeded the boundary: 1000, running default HASH AGGREGATION
shape: (1_324, 4)
┌──────────────┬──────────────────────────┬──────────┬────────────┐
│ nearestNodes ┆ 1/nearestNodesListLength ┆ priors   ┆ log_priors │
│ ---          ┆ ---                      ┆ ---      ┆ ---        │
│ str          ┆ f64                      ┆ f64      ┆ f64        │
╞══════════════╪══════════════════════════╪══════════╪════════════╡
│ B.1.617.2    ┆ 4637.166667              ┆ 0.291627 ┆ -0.535172  │
│ BA.1         ┆ 2577.0                   ┆ 0.162065 ┆ -0.79031   │
│ B.1.1.7      ┆ 1206.0                   ┆ 0.075844 ┆ -1.120077  │
│ NODE_0000017 ┆ 535.635931               ┆ 0.033686 ┆ -1.472555  │
│ …            ┆ …                        ┆ …        ┆ …          │
│ BQ.1.27      ┆ 0.033333                 ┆ 0.000002 ┆ -5.678546  │
│ BQ.1.7       ┆ 0.030303                 ┆ 0.000002 ┆ -5.719938  │
│ BA.2.44      ┆ 0.027778                 ┆ 0.000002 ┆ -5.757727  │
│ BA.5.2.61    ┆ 0.02439                  ┆ 0.000002 ┆ -5.814208  │
└──────────────┴──────────────────────────┴──────────┴────────────┘
```

### Issue description

I get the error "polars.exceptions.SchemaError: invalid series dtype: expected `List`, got `str`" in about 50% of cases. No idea why. Maybe the schema inference is wrong? The length of the file is way below `10000000`, so the schema should be inferred from the entire file. Could it be that it's done on only 100 lines but the exact order of lines is arbitrary, hence the stochasticity?

### Expected behavior

No error should happen, schema inference should be done on whole file. And if an error happens, it should happen every time, not in 50% of times I run it.

### Installed versions

<details>

```
--------Version info---------
Polars:               0.19.18
Index type:           UInt32
Platform:             macOS-14.1.1-arm64-arm-64bit
Python:               3.11.6 | packaged by conda-forge | (main, Oct  3 2023, 10:37:07) [Clang 15.0.7 ]

----Optional dependencies----
adbc_driver_manager:  <not installed>
cloudpickle:          <not installed>
connectorx:           <not installed>
deltalake:            <not installed>
fsspec:               <not installed>
gevent:               <not installed>
matplotlib:           3.8.2
numpy:                1.26.2
openpyxl:             <not installed>
pandas:               1.5.3
pyarrow:              14.0.1
pydantic:             2.5.2
pyiceberg:            <not installed>
pyxlsb:               <not installed>
sqlalchemy:           <not installed>
xlsx2csv:             0.8.1
xlsxwriter:           <not installed>
```

</details>

**Comment by corneliusroemer** [comment]
Thank you for confirming @cmdlineluser! I'm happy my gist test data download worked :)

Have you tried running it multiple times to see if it ever _doesn't_ raise?

**Comment by cmdlineluser** [comment]
Yeah, it appears to be one of those "non-deterministic" issues:
```python
Polars version: 0.19.17
shape: (1_324, 4)
┌──────────────┬──────────────────────────┬──────────┬────────────┐
│ nearestNodes ┆ 1/nearestNodesListLength ┆ priors   ┆ log_priors │
│ ---          ┆ ---                      ┆ ---      ┆ ---        │
│ str          ┆ f64                      ┆ f64      ┆ f64        │
╞══════════════╪══════════════════════════╪══════════╪════════════╡
│ B.1.617.2    ┆ 4637.166667              ┆ 0.291627 ┆ -0.535172  │
│ BA.1         ┆ 2577.0                   ┆ 0.162065 ┆ -0.79031   │
│ B.1.1.7      ┆ 1206.0                   ┆ 0.075844 ┆ -1.120077  │
│ NODE_0000017 ┆ 535.635931               ┆ 0.033686 ┆ -1.472555  │
│ …            ┆ …                        ┆ …        ┆ …          │
│ BQ.1.27      ┆ 0.033333                 ┆ 0.000002 ┆ -5.678546  │
│ BQ.1.7       ┆ 0.030303                 ┆ 0.000002 ┆ -5.719938  │
│ BA.2.44      ┆ 0.027778                 ┆ 0.000002 ┆ -5.757727  │
│ BA.5.2.61    ┆ 0.02439                  ┆ 0.000002 ┆ -5.814208  │
└──────────────┴──────────────────────────┴──────────┴────────────┘
```

**Comment by RyRyRyNguyen** [comment]
I am getting a SchemaError exception, but it's whenever I am trying to call the **pl.any** expression.

**Polars Version**
'0.20.2'

**Reproducible example**
``` python
import polars as pl
import datetime
import zoneinfo
df = pl.DataFrame(
        [
            pl.Series("timestamp", [datetime.datetime(2020, 3, 20, 4, 59, 59, tzinfo=zoneinfo.ZoneInfo(key='UTC')), datetime.datetime(2020, 4, 21, 4, 59, 59, tzinfo=zoneinfo.ZoneInfo(key='UTC')), datetime.datetime(2020, 5, 20, 4, 59, 59, tzinfo=zoneinfo.ZoneInfo(key='UTC')), datetime.datetime(2020, 6, 19, 4, 59, 59, tzinfo=zoneinfo.ZoneInfo(key='UTC')), datetime.datetime(2020, 7, 21, 4, 59, 59, tzinfo=zoneinfo.ZoneInfo(key='UTC'))], dtype=pl.Datetime(time_unit='us', time_zone='UTC')),
        pl.Series("ANNOTATIONS", [None, None, None, None, None], dtype=pl.Null),
        pl.Series("SCALAR", ['55661.0', '132147.0', '57941.0', '76049.0', '20589.0'], dtype=pl.Utf8)
    ]
)
df.select(pl.any('ANNOTATIONS'))
Traceback (most recent call last):
  File "C:\Program Files\JetBrains\PyCharm 2022.3.1\plugins\python\helpers\pydev\pydevconsole.py", line 364, in runcode
    coro = func()
           ^^^^^^
  File "<input>", line 10, in <module>
  File "venv\Lib\site-packages\polars\dataframe\frame.py", line 8008, in select
    return self.lazy().select(*exprs, **named_exprs).collect(_eager=True)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File ".venv\Lib\site-packages\polars\lazyframe\frame.py", line 1706, in collect
    return wrap_df(ldf.collect())
                   ^^^^^^^^^^^^^
polars.exceptions.SchemaError: invalid series dtype: expected `Boolean`, got `null`
```

To test on non-nulls:
```python
df.select(pl.any('SCALAR'))
polars.exceptions.SchemaError: invalid series dtype: expected `Boolean`, got `str`
```

**Comment by evbo** [comment]
I'm reproducing this attempting to parse a String as Float64 for a column that originated from a `json_decode(schema)`, where `schema` declared it as `Utf8`...

```python
lf.select(
            [
                pl.col("start_time").str.to_decimal(),
                pl.col("end_time").str.to_decimal(),
            ]
        ).collect()
```

`cast(pl.Float64)` makes no difference...

> polars.exceptions.SchemaError: invalid series dtype: expected `String`, got `f64`

**Comment by CaselIT** [comment]
I think I've reported the same error here. I did not find it yesterday using the github search...

The reproducer at https://github.com/pola-rs/polars/issues/15183 is not random, it raises every time
