### ISSUE TITLE
Type Casting string to date does not for list of dicts

### ISSUE THREAD

**Issue by AdrianHaylerQC** [pola-rs/polars#12900]
### Checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pypi.org/project/polars/) of Polars.

### Reproducible example

```python
import polars as pl
pl.DataFrame([{'test':'2023-11-08'}], schema={'test':pl.Date})
```

### Log output

```shell
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/ahayler/miniforge3/lib/python3.10/os.py", line 685, in __setitem__
    value = self.encodevalue(value)
  File "/Users/ahayler/miniforge3/lib/python3.10/os.py", line 757, in encode
    raise TypeError("str expected, not %s" % type(value).__name__)
TypeError: str expected, not int
>>> os.environ["POLARS_VERBOSE"]="1"
>>> pl.DataFrame([{'test':'2023-11-08'}], schema={'test':pl.Date})
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/ahayler/miniforge3/lib/python3.10/site-packages/polars/dataframe/frame.py", line 368, in __init__
    self._df = sequence_to_pydf(
  File "/Users/ahayler/miniforge3/lib/python3.10/site-packages/polars/utils/_construction.py", line 940, in sequence_to_pydf
    return _sequence_to_pydf_dispatcher(
  File "/Users/ahayler/miniforge3/lib/python3.10/functools.py", line 889, in wrapper
    return dispatch(args[0].__class__)(*args, **kw)
  File "/Users/ahayler/miniforge3/lib/python3.10/site-packages/polars/utils/_construction.py", line 1159, in _sequence_of_dict_to_pydf
    pydf = PyDataFrame.read_dicts(
polars.exceptions.ComputeError: could not append value: "2023-11-08" of type: str to the builder; make sure that all rows have the same schema or consider increasing `infer_schema_length`

it might also be that a value overflows the data-type's capacity
```

### Issue description

This issue occurs when I try to parse strings as dates into a polars DataFrame from a list of dicts. Removing the list wrapper from the code above creates the expected DataFrame.

### Expected behavior

A one row, one column dataframe with `'2023-11-08'` in column `'test' ` of dtype `pl.Date`.

### Installed versions

<details>

```
--------Version info---------
Polars:               0.19.19
Index type:           UInt32
Platform:             macOS-13.2.1-arm64-arm-64bit
Python:               3.10.12 | packaged by conda-forge | (main, Jun 23 2023, 22:41:52) [Clang 15.0.7 ]

----Optional dependencies----
adbc_driver_manager:  <not installed>
cloudpickle:          <not installed>
connectorx:           <not installed>
deltalake:            <not installed>
fsspec:               <not installed>
gevent:               <not installed>
matplotlib:           <not installed>
numpy:                <not installed>
openpyxl:             <not installed>
pandas:               <not installed>
pyarrow:              <not installed>
pydantic:             <not installed>
pyiceberg:            <not installed>
pyxlsb:               <not installed>
sqlalchemy:           <not installed>
xlsx2csv:             <not installed>
xlsxwriter:           <not installed>

```

</details>

**Comment by mcrumiller** [comment]
I don't believe this is valid input to `pl.DataFrame`. The [documentation](https://pola-rs.github.io/polars/py-polars/html/reference/dataframe/index.html) says:

> **data : dict, Sequence, ndarray, Series, or pandas.DataFrame**
> Two-dimensional data in various forms; dict input must contain Sequences, Generators, or a `range`. Sequence may contain Series or other Sequences.

You have a Sequence containing a dict.

**Comment by alexander-beedie** [comment]
The input type is valid, but the schema is not - you aren't passing a date, you're passing a string and the schema argument is _not_ a cast operation; for this there is a frame-level `cast` operation (or expression-level `cast` or  `str.strptime`).

All of the following are valid ways of converting a string column to date:
```python
df = pl.DataFrame( [{'test':'2023-11-08'}] )

df.cast( pl.Date )
df.cast( {'test':pl.Date} )
df.with_columns( test = pl.col('test').cast(pl.Date) )
df.with_columns( test = pl.col('test').str.strptime(pl.Date,'%Y-%m-%d') )
```

**Comment by cmdlineluser** [comment]
> if we can get the builder's name/type into the error message that might help disambiguate

This would also close https://github.com/pola-rs/polars/issues/12536#issuecomment-1817444927 @alexander-beedie 

I think they both end up hitting the same codepath:

https://github.com/pola-rs/polars/blob/22a385a4203ee8d41b768303e9707e5d8fd28dc3/crates/polars-core/src/frame/row/av_buffer.rs#L129-L132

**Comment by AdrianHaylerQC** [comment]
@alexander-beedie Are you sure that this is always the case? Polars seems to normally try casting the columns automatically at DataFrame-creation.

**Example**

```python
import pandas as pd
df_pd = pd.DataFrame({"date": ["2023-11-08", "2023-12-09"]})
df = pl.DataFrame(df_pd, schema={"date": pl.Date})
df["date"][0], df_pd.dtypes
```

**Output**

```python
(datetime.date(2023, 11, 8), date    object
dtype: object)
```

Also is it documented somewhere when we cast the columns automatically and when we don't? I could not find anything.

**Comment by enchant3dmango** [comment]
@AdrianHaylerQC have you solved this issue? Because I was facing the same issue last month in version `0.19.12`.

Here is the log:
```
[2023-11-25T19:12:33.505+0000] {taskinstance.py:1772} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 175, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 192, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/repo/plugins/task_generators/rdbms_to_bq/rdbms_to_bq_v2.py", line 196, in __extract_and_upload_to_gcs
    for index, dataframe in enumerate(dataframes):
  File "/home/airflow/.local/lib/python3.8/site-packages/polars/io/database.py", line 289, in <genexpr>
    DataFrame(
  File "/home/airflow/.local/lib/python3.8/site-packages/polars/dataframe/frame.py", line 367, in __init__
    self._df = sequence_to_pydf(
  File "/home/airflow/.local/lib/python3.8/site-packages/polars/utils/_construction.py", line 932, in sequence_to_pydf
    return _sequence_to_pydf_dispatcher(
  File "/usr/local/lib/python3.8/functools.py", line 875, in wrapper
    return dispatch(args[0].__class__)(*args, **kw)
  File "/home/airflow/.local/lib/python3.8/site-packages/polars/utils/_construction.py", line 1124, in _sequence_of_tuple_to_pydf
    return _sequence_of_sequence_to_pydf(
  File "/home/airflow/.local/lib/python3.8/site-packages/polars/utils/_construction.py", line 1075, in _sequence_of_sequence_to_pydf
    pydf = PyDataFrame.read_rows(
polars.exceptions.ComputeError: could not append value: "Jgn sampe rusak ya. Pleaase" of type: str to the builder; make sure that all rows have the same schema or consider increasing `infer_schema_length`
```

**Comment by AdrianHaylerQC** [comment]
@enchant3dmango I just cast the columns to the wanted dtype using `.cast()` currently.

**Comment by enchant3dmango** [comment]
@AdrianHaylerQC could you please show me an example of how you do it?

I'm using .cast() as well while I faced the issue above.

Here is how I do it:

```
elif field_type == "STRING":
            dataframe = dataframe.with_columns(
                pl.col(field_name).cast(dtype=pl.Utf8, strict=False))
```

**Comment by AdrianHaylerQC** [comment]
@enchant3dmango Without a minimal reproducible example, I sadly won't be able to help you any further. Examples of casting can be found [here](https://docs.pola.rs/user-guide/expressions/casting/).
