### ISSUE TITLE
OOB error when using set operations on empty dataframes

### ISSUE THREAD

**Issue by manuels** [pola-rs/polars#12915]
### Checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pypi.org/project/polars/) of Polars.

### Reproducible example

```python
import polars as pl

df = pl.DataFrame(dict(a=[], b=[]), schema=dict(a=pl.List(pl.Utf8), b=pl.List(pl.Utf8)))
df.select(pl.col('a').list.set_intersection(pl.col('b')))
```

### Log output

```shell
thread '<unnamed>' panicked at crates/polars-ops/src/chunked_array/list/sets.rs:263:20:
index out of bounds: the len is 1 but the index is 1
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
Traceback (most recent call last):
  File "test.py", line 4, in <module>
    df.select(pl.col('a').list.set_intersection(pl.col('b')))
  File "venv/lib/python3.9/site-packages/polars/dataframe/frame.py", line 7851, in select
    return self.lazy().select(*exprs, **named_exprs).collect(_eager=True)
  File "venv/lib/python3.9/site-packages/polars/utils/deprecation.py", line 100, in wrapper
    return function(*args, **kwargs)
  File "venv/lib/python3.9/site-packages/polars/lazyframe/frame.py", line 1788, in collect
    return wrap_df(ldf.collect())
pyo3_runtime.PanicException: index out of bounds: the len is 1 but the index is 1
```

### Issue description

Looks like the rust code assumes that the dataframe is not empty ([in primitive()](https://github.com/pola-rs/polars/blob/main/crates/polars-ops/src/chunked_array/list/sets.rs#L152C24-L152C24) and [in binary()](https://github.com/pola-rs/polars/blob/main/crates/polars-ops/src/chunked_array/list/sets.rs#L263).
This code should be guarded by an if clause. I'll try to create a MR for that.

### Expected behavior

Return an empty data frame

### Installed versions

<details>

```
--------Version info---------
Polars:               0.19.19
Index type:           UInt32
Platform:             Linux-6.2.0-37-generic-x86_64-with-glibc2.35
Python:               3.9.8 (main, Jun 14 2022, 08:59:16) 
[GCC 11.2.0]

----Optional dependencies----
adbc_driver_manager:  <not installed>
cloudpickle:          <not installed>
connectorx:           <not installed>
deltalake:            <not installed>
fsspec:               <not installed>
gevent:               <not installed>
matplotlib:           <not installed>
numpy:                <not installed>
openpyxl:             <not installed>
pandas:               <not installed>
pyarrow:              <not installed>
pydantic:             <not installed>
pyiceberg:            <not installed>
pyxlsb:               <not installed>
sqlalchemy:           <not installed>
xlsx2csv:             <not installed>
xlsxwriter:           <not installed>
```

</details>

**Comment by cmdlineluser** [comment]
I think this was just fixed on main: https://github.com/pola-rs/polars/pull/12845

**Comment by manuels** [comment]
Oh, that was fixed yesterday! Sorry, I'll close this then.
