### ISSUE TITLE
Spark will not read pure rust written parquets with nested fields

### ISSUE THREAD

**Issue by Guillermogsjc** [pola-rs/polars#12929]
### Checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pypi.org/project/polars/) of Polars.

### Reproducible example

-

### Log output

```shell
-
```

### Issue description

is there any incompatibility when performing `.write_parquet` using the pure Rust Arrow engine instead of pyarrow? Because writing rust implementation, then the parquets **are not able to be read from spark**, but using pyarrow, the same DataFrames persisted are read without any problem from Spark

The DataFrame schema

```
OrderedDict([('details', Utf8),
             ('metadata----codification', List(Utf8)),
             ('metadata----operator', Utf8)])
```

### Expected behavior

read parquets generated by Rust Arrow without problems from Spark

### Installed versions

--------Version info---------
Polars:               0.19.19
Index type:           UInt32
Platform:             Linux-6.1.0-13-amd64-x86_64-with-glibc2.36
Python:               3.9.13 (main, Aug 25 2022, 23:26:10) 
[GCC 11.2.0]

----Optional dependencies----
adbc_driver_manager:  <not installed>
cloudpickle:          2.2.1
connectorx:           <not installed>
deltalake:            <not installed>
fsspec:               2022.7.1
gevent:               23.9.1
matplotlib:           3.5.2
numpy:                1.22.4
openpyxl:             3.0.9
pandas:               1.5.3
pyarrow:              13.0.0
pydantic:             1.8.2
pyiceberg:            <not installed>
pyxlsb:               <not installed>
sqlalchemy:           1.4.39
xlsx2csv:             <not installed>
xlsxwriter:           3.1.9

Spark versions:

Spark version 3.5.0
Using Scala version 2.12.18
pyspark==3.5.0

**Comment by ritchie46** [comment]
Thanks can you create a minimal example? E.g. creating the file that cannot be read?

**Comment by ritchie46** [comment]
Would really appreciate if someone could get a repro here.

**Comment by Guillermogsjc** [comment]
yesss, with versions commented in previous post:

this works

```python
from collections import OrderedDict
import polars as pl
from pyspark.sql import SparkSession


schema = OrderedDict([('a', pl.Utf8),
             ('c', pl.Utf8)])

example_df = pl.LazyFrame(
    [
        {"a": "qwe",  "c": "jk"},
        {"a": "ghj", "c": "bn"}
    ],
    schema=schema
)

path = "example.parquet"

example_df.sink_parquet(path, compression='zstd')


spark = SparkSession.builder \
    .appName("ReadParquetAndQuery") \
    .getOrCreate()
df = spark.read.parquet(*[path])
df.show()
```

This does not work (problems with nested fields at least with List)

```python
from collections import OrderedDict
import polars as pl

schema = OrderedDict([('a', pl.Utf8),
             ('b', pl.List(pl.Utf8)),
             ('c', pl.Utf8)])

example_df = pl.LazyFrame(
    [
        {"a": "qwe", "b": ["t", "e"], "c": "jk"},
        {"a": "ghj", "b": ["p"], "c": "bn"}
    ],
    schema=schema
)

path = "example.parquet"

example_df.sink_parquet(path, compression='zstd')

example_df.collect().write_parquet(path, compression='snappy')

from pyspark.sql import SparkSession
spark = SparkSession.builder \
    .appName("ReadParquetAndQuery") \
    .getOrCreate()
df = spark.read.parquet(*[path])
df.show()
```

with log error

```
23/12/07 12:38:27 ERROR Executor: Exception in task 0.0 in stage 15.0 (TID 15)
org.apache.spark.SparkException: Encountered error while reading file file:///home/infinitemonkeys/Desktop/scripting/parquets_polars/example.parquet. Details:
	at org.apache.spark.sql.errors.QueryExecutionErrors$.cannotReadFilesError(QueryExecutionErrors.scala:863)
	at org.apache.spark.sql.execution.datasources.FileScanRDD$$anon$1.nextIterator(FileScanRDD.scala:293)
	at org.apache.spark.sql.execution.datasources.FileScanRDD$$anon$1.hasNext(FileScanRDD.scala:129)
	at org.apache.spark.sql.execution.FileSourceScanExec$$anon$1.hasNext(DataSourceScanExec.scala:593)
	at org.apache.spark.sql.catalyst.expressions.GeneratedClass$GeneratedIteratorForCodegenStage1.columnartorow_nextBatch_0$(Unknown Source)
	at org.apache.spark.sql.catalyst.expressions.GeneratedClass$GeneratedIteratorForCodegenStage1.processNext(Unknown Source)
	at org.apache.spark.sql.execution.BufferedRowIterator.hasNext(BufferedRowIterator.java:43)
	at org.apache.spark.sql.execution.WholeStageCodegenEvaluatorFactory$WholeStageCodegenPartitionEvaluator$$anon$1.hasNext(WholeStageCodegenEvaluatorFactory.scala:43)
	at org.apache.spark.sql.execution.SparkPlan.$anonfun$getByteArrayRdd$1(SparkPlan.scala:388)
	at org.apache.spark.rdd.RDD.$anonfun$mapPartitionsInternal$2(RDD.scala:890)
	at org.apache.spark.rdd.RDD.$anonfun$mapPartitionsInternal$2$adapted(RDD.scala:890)
	at org.apache.spark.rdd.MapPartitionsRDD.compute(MapPartitionsRDD.scala:52)
	at org.apache.spark.rdd.RDD.computeOrReadCheckpoint(RDD.scala:364)
	at org.apache.spark.rdd.RDD.iterator(RDD.scala:328)
	at org.apache.spark.scheduler.ResultTask.runTask(ResultTask.scala:93)
	at org.apache.spark.TaskContext.runTaskWithListeners(TaskContext.scala:161)
	at org.apache.spark.scheduler.Task.run(Task.scala:141)
	at org.apache.spark.executor.Executor$TaskRunner.$anonfun$run$4(Executor.scala:620)
	at org.apache.spark.util.SparkErrorUtils.tryWithSafeFinally(SparkErrorUtils.scala:64)
	at org.apache.spark.util.SparkErrorUtils.tryWithSafeFinally$(SparkErrorUtils.scala:61)
	at org.apache.spark.util.Utils$.tryWithSafeFinally(Utils.scala:94)
	at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:623)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:840)
Caused by: org.apache.parquet.io.ParquetDecodingException: Failed to read from input stream
	at org.apache.spark.sql.execution.datasources.parquet.VectorizedRleValuesReader.readNextGroup(VectorizedRleValuesReader.java:944)
	at org.apache.spark.sql.execution.datasources.parquet.VectorizedRleValuesReader.readValues(VectorizedRleValuesReader.java:606)
	at org.apache.spark.sql.execution.datasources.parquet.VectorizedRleValuesReader.access$100(VectorizedRleValuesReader.java:45)
	at org.apache.spark.sql.execution.datasources.parquet.VectorizedRleValuesReader$DefLevelProcessor.finish(VectorizedRleValuesReader.java:571)
	at org.apache.spark.sql.execution.datasources.parquet.VectorizedRleValuesReader.readBatchRepeatedInternal(VectorizedRleValuesReader.java:509)
	at org.apache.spark.sql.execution.datasources.parquet.VectorizedRleValuesReader.readBatchRepeated(VectorizedRleValuesReader.java:346)
	at org.apache.spark.sql.execution.datasources.parquet.VectorizedColumnReader.readBatch(VectorizedColumnReader.java:254)
	at org.apache.spark.sql.execution.datasources.parquet.VectorizedParquetRecordReader.nextBatch(VectorizedParquetRecordReader.java:342)
	at org.apache.spark.sql.execution.datasources.parquet.VectorizedParquetRecordReader.nextKeyValue(VectorizedParquetRecordReader.java:233)
	at org.apache.spark.sql.execution.datasources.RecordReaderIterator.hasNext(RecordReaderIterator.scala:39)
	at org.apache.spark.sql.execution.datasources.FileScanRDD$$anon$1.hasNext(FileScanRDD.scala:129)
	at org.apache.spark.sql.execution.datasources.FileScanRDD$$anon$1.nextIterator(FileScanRDD.scala:283)
	... 23 more
Caused by: java.io.EOFException
	at org.apache.parquet.bytes.SingleBufferInputStream.slice(SingleBufferInputStream.java:116)
	at org.apache.spark.sql.execution.datasources.parquet.VectorizedRleValuesReader.readNextGroup(VectorizedRleValuesReader.java:935)
	... 34 more
23/12/07 12:38:27 WARN TaskSetManager: Lost task 0.0 in stage 15.0 (TID 15) (192.168.1.132 executor driver): org.apache.spark.SparkException: Encountered error while reading file file:///home/infinitemonkeys/Desktop/scripting/parquets_polars/example.parquet. Details:
	at org.apache.spark.sql.errors.QueryExecutionErrors$.cannotReadFilesError(QueryExecutionErrors.scala:863)
	at org.apache.spark.sql.execution.datasources.FileScanRDD$$anon$1.nextIterator(FileScanRDD.scala:293)
	at org.apache.spark.sql.execution.datasources.FileScanRDD$$anon$1.hasNext(FileScanRDD.scala:129)
	at org.apache.spark.sql.execution.FileSourceScanExec$$anon$1.hasNext(DataSourceScanExec.scala:593)
	at org.apache.spark.sql.catalyst.expressions.GeneratedClass$GeneratedIteratorForCodegenStage1.columnartorow_nextBatch_0$(Unknown Source)
	at org.apache.spark.sql.catalyst.expressions.GeneratedClass$GeneratedIteratorForCodegenStage1.processNext(Unknown Source)
	at org.apache.spark.sql.execution.BufferedRowIterator.hasNext(BufferedRowIterator.java:43)
	at org.apache.spark.sql.execution.WholeStageCodegenEvaluatorFactory$WholeStageCodegenPartitionEvaluator$$anon$1.hasNext(WholeStageCodegenEvaluatorFactory.scala:43)
	at org.apache.spark.sql.execution.SparkPlan.$anonfun$getByteArrayRdd$1(SparkPlan.scala:388)
	at org.apache.spark.rdd.RDD.$anonfun$mapPartitionsInternal$2(RDD.scala:890)
	at org.apache.spark.rdd.RDD.$anonfun$mapPartitionsInternal$2$adapted(RDD.scala:890)
	at org.apache.spark.rdd.MapPartitionsRDD.compute(MapPartitionsRDD.scala:52)
	at org.apache.spark.rdd.RDD.computeOrReadCheckpoint(RDD.scala:364)
	at org.apache.spark.rdd.RDD.iterator(RDD.scala:328)
	at org.apache.spark.scheduler.ResultTask.runTask(ResultTask.scala:93)
	at org.apache.spark.TaskContext.runTaskWithListeners(TaskContext.scala:161)
	at org.apache.spark.scheduler.Task.run(Task.scala:141)
	at org.apache.spark.executor.Executor$TaskRunner.$anonfun$run$4(Executor.scala:620)
	at org.apache.spark.util.SparkErrorUtils.tryWithSafeFinally(SparkErrorUtils.scala:64)
	at org.apache.spark.util.SparkErrorUtils.tryWithSafeFinally$(SparkErrorUtils.scala:61)
	at org.apache.spark.util.Utils$.tryWithSafeFinally(Utils.scala:94)
	at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:623)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:840)
Caused by: org.apache.parquet.io.ParquetDecodingException: Failed to read from input stream
	at org.apache.spark.sql.execution.datasources.parquet.VectorizedRleValuesReader.readNextGroup(VectorizedRleValuesReader.java:944)
	at org.apache.spark.sql.execution.datasources.parquet.VectorizedRleValuesReader.readValues(VectorizedRleValuesReader.java:606)
	at org.apache.spark.sql.execution.datasources.parquet.VectorizedRleValuesReader.access$100(VectorizedRleValuesReader.java:45)
	at org.apache.spark.sql.execution.datasources.parquet.VectorizedRleValuesReader$DefLevelProcessor.finish(VectorizedRleValuesReader.java:571)
	at org.apache.spark.sql.execution.datasources.parquet.VectorizedRleValuesReader.readBatchRepeatedInternal(VectorizedRleValuesReader.java:509)
	at org.apache.spark.sql.execution.datasources.parquet.VectorizedRleValuesReader.readBatchRepeated(VectorizedRleValuesReader.java:346)
	at org.apache.spark.sql.execution.datasources.parquet.VectorizedColumnReader.readBatch(VectorizedColumnReader.java:254)
	at org.apache.spark.sql.execution.datasources.parquet.VectorizedParquetRecordReader.nextBatch(VectorizedParquetRecordReader.java:342)
	at org.apache.spark.sql.execution.datasources.parquet.VectorizedParquetRecordReader.nextKeyValue(VectorizedParquetRecordReader.java:233)
	at org.apache.spark.sql.execution.datasources.RecordReaderIterator.hasNext(RecordReaderIterator.scala:39)
	at org.apache.spark.sql.execution.datasources.FileScanRDD$$anon$1.hasNext(FileScanRDD.scala:129)
	at org.apache.spark.sql.execution.datasources.FileScanRDD$$anon$1.nextIterator(FileScanRDD.scala:283)
	... 23 more
Caused by: java.io.EOFException
	at org.apache.parquet.bytes.SingleBufferInputStream.slice(SingleBufferInputStream.java:116)
	at org.apache.spark.sql.execution.datasources.parquet.VectorizedRleValuesReader.readNextGroup(VectorizedRleValuesReader.java:935)
	... 34 more

23/12/07 12:38:27 ERROR TaskSetManager: Task 0 in stage 15.0 failed 1 times; aborting job
```

**Comment by ion-elgreco** [comment]
This could be related to how the parquet nested types are written, see an example here under nested_compliant_types:  https://arrow.apache.org/docs/python/generated/pyarrow.parquet.ParquetWriter.html

Pyarrow can read/write both compliant and non-compliant versions of it.

**Comment by Guillermogsjc** [comment]
looks like a very dumb variant, just change a name of a internal a field between `element` or `item` .

 I hope Rust Arrow implementation allows this option and it can be added the option just bypass this parameter through polars?

**Comment by ritchie46** [comment]
That doesn't seem to be it. Can somebody get the full stacktrace? I am not able to.

**Comment by Guillermogsjc** [comment]
oh true, this works too so nothing to do with nested field compliance. I am not able either to config log4j.properties in such a way trace is not truncated for now

```
from collections import OrderedDict
import polars as pl

schema = OrderedDict([('a', pl.Utf8),
             ('b', pl.List(pl.Utf8)),
             ('c', pl.Utf8)])

example_df = pl.LazyFrame(
    [
        {"a": "qwe", "b": ["t", "e"], "c": "jk"},
        {"a": "ghj", "b": ["p"], "c": "bn"}
    ],
    schema=schema
)

path = "example.parquet"

example_df.collect().write_parquet(path, 
                                   compression='zstd',
                                   use_pyarrow=True, 
                                   pyarrow_options={"use_compliant_nested_type": False})

from pyspark.sql import SparkSession
spark = SparkSession.builder \
    .appName("ReadParquetAndQuery") \
    .getOrCreate()
df = spark.read.option("compression.codec", "zstd").parquet(*[path])
df.show()
```

**Comment by ritchie46** [comment]
>  I am not able either to config log4j.properties in such a way trace is not truncated for now

:')

**Comment by aksestok** [comment]
This is also an issue when [loading Parquet files into BigQuery](https://cloud.google.com/bigquery/docs/loading-data-cloud-storage-parquet#list_logical_type), where an additional "item" object is added as a nested object when reading files written with the Rust implementation. The BigQuery docs state that in order to infer schema correctly from Parquet, the schema must be on "the standard form":

> You can enable schema inference for Parquet LIST logical types. BigQuery checks whether the LIST node is in the [standard form](https://github.com/apache/parquet-format/blob/master/LogicalTypes.md#lists) or in one of the forms described by the [backward-compatibility rules](https://github.com/apache/parquet-format/blob/master/LogicalTypes.md#backward-compatibility-rules):
> ```
> // standard form
> <optional | required> group <name> (LIST) {
>   repeated group list {
>     <optional | required> <element-type> element;
>   }
> }
> ```

Writing to Parquet using Pyarrow solves the issue.
