### ISSUE TITLE
Unexpected NaN behavior with .unique()

### ISSUE THREAD

**Issue by TylerGrantSmith** [pola-rs/polars#12950]
### Checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pypi.org/project/polars/) of Polars.

### Reproducible example

```python
import polars as pl
import numpy as np

pl.DataFrame({"x": np.nan}).unique()
```

```ipython
In [19]: pl.DataFrame({"x": np.nan}).unique()
Out[19]: 
shape: (2, 1)
┌──────┐
│ x    │
│ ---  │
│ f64  │
╞══════╡
│ null │
│ NaN  │
└──────┘
```

### Issue description

Why does calling `.unique()` on a `NaN` produce a `null` and a `NaN`?

### Expected behavior

No `null` to be returned

### Installed versions

<details>

```
--------Version info---------
Polars:               0.19.19
Index type:           UInt32
Platform:             Linux-4.14.326-245.539.amzn2.x86_64-x86_64-with-glibc2.26
Python:               3.10.13 (main, Sep 11 2023, 13:44:35) [GCC 11.2.0]

----Optional dependencies----
adbc_driver_manager:  <not installed>
cloudpickle:          <not installed>
connectorx:           <not installed>
deltalake:            <not installed>
fsspec:               2023.12.1
gevent:               <not installed>
matplotlib:           3.8.2
numpy:                1.26.2
openpyxl:             3.1.2
pandas:               2.1.3
pyarrow:              12.0.1
pydantic:             2.5.2
pyiceberg:            <not installed>
pyxlsb:               <not installed>
sqlalchemy:           <not installed>
xlsx2csv:             0.8.1
xlsxwriter:           <not installed>
```

</details>

**Comment by cmdlineluser** [comment]
It seems `None` also has a problem:
```python
pl.DataFrame({"x": None}).unique()

# thread '<unnamed>' panicked at crates/polars-core/src/series/series_trait.rs:160:13:
# `group_tuples` operation not supported for dtype `null`
# PanicException: `group_tuples` operation not supported for dtype `null`
```

**Comment by cjackal** [comment]
> It seems `None` also has a problem:
> 
> ```python
> pl.DataFrame({"x": None}).unique()
> 
> # thread '<unnamed>' panicked at crates/polars-core/src/series/series_trait.rs:160:13:
> # `group_tuples` operation not supported for dtype `null`
> # PanicException: `group_tuples` operation not supported for dtype `null`
> ```

It sounds like `.unique` not supported on `Null` dtype is a separate issue from this `nan` misbehavior, it works normal for numeric dtypes.

**Comment by cjackal** [comment]
Interesting point - `.unique` works correctly for series:
```python
import polars as pl
import numpy as np

pl.DataFrame({"x": np.nan})["x"].unique()
```
