### ISSUE TITLE
`sort` and `arg_sort` on a Series with dtype Object raise a PanicException

### ISSUE THREAD

**Issue by jeromedockes** [pola-rs/polars#12956]
### Checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pypi.org/project/polars/) of Polars.

### Reproducible example

```python
import polars as pl
pl.Series([], dtype=pl.Object).sort()
```

### Log output

```shell
<details>


thread '<unnamed>' panicked at /home/conda/feedstock_root/build_artifacts/polars_1701471660423/work/crates/polars-core/src/series/series_trait.rs:337:9:
`sort_with` operation not supported for dtype `object`
stack backtrace:
   0: rust_begin_unwind
             at /rustc/0f44eb32f1123ac93ab404d74c295263ce468343/library/std/src/panicking.rs:645:5
   1: core::panicking::panic_fmt
             at /rustc/0f44eb32f1123ac93ab404d74c295263ce468343/library/core/src/panicking.rs:72:14
   2: polars_core::series::series_trait::SeriesTrait::sort_with
   3: polars::series::_::<impl polars::series::PySeries>::__pymethod_sort__
   4: pyo3::impl_::trampoline::trampoline
   5: polars::series::_::_::__INVENTORY::trampoline
   6: method_vectorcall_VARARGS_KEYWORDS
             at /usr/local/src/conda/python-3.12.0/Objects/descrobject.c:365:14
   7: _PyObject_VectorcallTstate
             at /usr/local/src/conda/python-3.12.0/Include/internal/pycore_call.h:92:11
   8: PyObject_Vectorcall
             at /usr/local/src/conda/python-3.12.0/Objects/call.c:325:12
   9: _PyEval_EvalFrameDefault
             at /home/conda/feedstock_root/build_artifacts/python-split_1696321225611/work/build-static/Python/bytecodes.c:2711:19
  10: PyEval_EvalCode
             at /usr/local/src/conda/python-3.12.0/Python/ceval.c:570:21
  11: run_eval_code_obj
             at /usr/local/src/conda/python-3.12.0/Python/pythonrun.c:1693
  12: run_mod
             at /usr/local/src/conda/python-3.12.0/Python/pythonrun.c:1714
  13: pyrun_file
             at /usr/local/src/conda/python-3.12.0/Python/pythonrun.c:1614
  14: _PyRun_SimpleFileObject
             at /usr/local/src/conda/python-3.12.0/Python/pythonrun.c:433
  15: _PyRun_AnyFileObject
             at /usr/local/src/conda/python-3.12.0/Python/pythonrun.c:78
  16: pymain_run_file_obj
             at /usr/local/src/conda/python-3.12.0/Modules/main.c:360
  17: pymain_run_file
             at /usr/local/src/conda/python-3.12.0/Modules/main.c:379
  18: pymain_run_python
             at /usr/local/src/conda/python-3.12.0/Modules/main.c:610
  19: Py_RunMain
             at /usr/local/src/conda/python-3.12.0/Modules/main.c:689
  20: Py_BytesMain
             at /usr/local/src/conda/python-3.12.0/Modules/main.c:743:12
  21: __libc_start_call_main
             at ./csu/../sysdeps/nptl/libc_start_call_main.h:58:16
  22: __libc_start_main_impl
             at ./csu/../csu/libc-start.c:392:3
  23: <unknown>
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
Traceback (most recent call last):
  File "/tmp/08-103310.py", line 2, in <module>
    pl.Series([], dtype=pl.Object).sort()
  File "/home/jerome/miniforge3/envs/skl/lib/python3.12/site-packages/polars/series/series.py", line 3104, in sort
    return self._from_pyseries(self._s.sort(descending))
                               ^^^^^^^^^^^^^^^^^^^^^^^^
pyo3_runtime.PanicException: `sort_with` operation not supported for dtype `object`
```

</details>
```


### Issue description

other operations not implemented for the Object dtype such as `unique` raise an `InvalidOperationError`, which is more convenient to catch because it is an `Exception`, and does not print an error message if caught

### Expected behavior

I think it would be more consistent with `unique` and more convenient if a `InvalidOperationError` was raised

### Installed versions

<details>

```
--------Version info---------
Polars:               0.19.19
Index type:           UInt32
Platform:             Linux-6.2.0-37-generic-x86_64-with-glibc2.35
Python:               3.12.0 | packaged by conda-forge | (main, Oct  3 2023, 08:43:22) [GCC 12.3.0]

----Optional dependencies----
adbc_driver_manager:  <not installed>
cloudpickle:          <not installed>
connectorx:           <not installed>
deltalake:            <not installed>
fsspec:               <not installed>
gevent:               <not installed>
matplotlib:           <not installed>
numpy:                1.26.2
openpyxl:             <not installed>
pandas:               2.1.3
pyarrow:              <not installed>
pydantic:             <not installed>
pyiceberg:            <not installed>
pyxlsb:               <not installed>
sqlalchemy:           <not installed>
xlsx2csv:             <not installed>
xlsxwriter:           <not installed>
```

</details>

**Comment by cmdlineluser** [comment]
Not sure if there is a proper way to test all methods, but this seems to be all the no-arg ones that panic:

<details><summary>find-no-arg-object-panics.py</summary>

```python
import polars as pl

panics = []
s = pl.Series([], dtype=pl.Object)

for method in dir(s):
    if method[0] == "_": 
        continue
    try:
        result = getattr(s, method)()
    except (
        NotImplementedError,
        TypeError,
        ValueError,
        pl.ComputeError,
        pl.InvalidOperationError,
        pl.SchemaError,
        pl.ShapeError
    ) as error:
        pass
    except (
        pl.PolarsPanicError
    ) as error:
        panics.append(dict(method=method, error=str(error)))

with pl.Config(set_tbl_rows=-1):
    print(pl.DataFrame(panics))
```

</details>

```python
shape: (14, 2)
┌────────────────┬───────────────────────────────────┐
│ method         ┆ error                             │
│ ---            ┆ ---                               │
│ str            ┆ str                               │
╞════════════════╪═══════════════════════════════════╡
│ arg_sort       ┆ `arg_sort` operation not support… │
│ diff           ┆ not yet implemented               │
│ estimated_size ┆ not implemented                   │
│ get_chunks     ┆ called `Option::unwrap()` on a `… │
│ hist           ┆ called `Option::unwrap()` on a `… │
│ implode        ┆ not implemented                   │
│ peak_max       ┆ not implemented                   │
│ peak_min       ┆ not implemented                   │
│ product        ┆ product not supported for dtype:… │
│ rle            ┆ not implemented                   │
│ shift          ┆ not yet implemented               │
│ shrink_to_fit  ┆ `shrink_to_fit` operation not su… │
│ sort           ┆ `sort_with` operation not suppor… │
│ to_dummies     ┆ object dtype not supported in Se… │
└────────────────┴───────────────────────────────────┘
```

**Comment by ritchie46** [comment]
We should raise an error here. We will never support sorting on object types. They are merely passengers in a dataframe.

**Comment by alonme** [comment]
This seems to be resolved?

```python
In [2]: import polars as pl
   ...: pl.Series([], dtype=pl.Object).sort()
---------------------------------------------------------------------------
InvalidOperationError                     Traceback (most recent call last)
Cell In[2], line 2
      1 import polars as pl
----> 2 pl.Series([], dtype=pl.Object).sort()

File ~/dev/analyses/.venv/lib/python3.11/site-packages/polars/series/series.py:3403, in Series.sort(self, descending, nulls_last, multithreaded, in_place)
   3400     return self
   3401 else:
   3402     return self._from_pyseries(
-> 3403         self._s.sort(descending, nulls_last, multithreaded)
   3404     )

InvalidOperationError: `sort_with` operation not supported for dtype `object`
```

**Comment by ritchie46** [comment]
Thanks, closing then.
