### ISSUE TITLE
GCP scan parquet timeout on large parquet

### ISSUE THREAD

**Issue by Itayazolay** [pola-rs/polars#13008]
### Checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pypi.org/project/polars/) of Polars.

### Reproducible example

```python
import pandas as pd
import polars as pl

path = 'gs://bucket/test.p'
pd.Series(range(100000000), name='data').reset_index().to_parquet(path)  # Around 700 Mb
pl.scan_parquet(path).collect()
```

### Log output

```shell
POLARS PREFETCH_SIZE: 16
querying metadata of 1/1 files...
reading of 1/1 file...
POLARS ROW_GROUP PREFETCH_SIZE: 128
Traceback (most recent call last):
  File "/home/itay/miniforge3/envs/jether/lib/python3.10/site-packages/IPython/core/interactiveshell.py", line 3526, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-20-7082554960da>", line 1, in <module>
    pl.scan_parquet('gs://jether_temp/Itay/test.p').collect()
  File "/home/itay/miniforge3/envs/jether/lib/python3.10/site-packages/polars/utils/deprecation.py", line 100, in wrapper
    return function(*args, **kwargs)
  File "/home/itay/miniforge3/envs/jether/lib/python3.10/site-packages/polars/lazyframe/frame.py", line 1788, in collect
    return wrap_df(ldf.collect())
polars.exceptions.ComputeError: Generic GCS error: request or response body error: operation timed out
```

### Issue description

Polars fails to collect large dataframe (700Mb in my case).
BTW, it works for local parquet

### Expected behavior

Dataframe should be loaded

### Installed versions

<details>

```
--------Version info---------
Polars:               0.19.19
Index type:           UInt32
Platform:             Linux-6.2.0-37-generic-x86_64-with-glibc2.35
Python:               3.10.11 | packaged by conda-forge | (main, May 10 2023, 18:58:44) [GCC 11.3.0]
----Optional dependencies----
adbc_driver_manager:  0.8.0
cloudpickle:          2.2.1
connectorx:           0.3.2
deltalake:            0.14.0
fsspec:               2023.9.0
gevent:               23.9.1
matplotlib:           3.8.2
numpy:                1.24.3
openpyxl:             3.1.2
pandas:               2.0.1
pyarrow:              12.0.1
pydantic:             2.5.2
pyiceberg:            0.5.1
pyxlsb:               1.0.10
sqlalchemy:           2.0.23
xlsx2csv:             0.8.1
xlsxwriter:           3.1.2
```

</details>

**Comment by thomasfrederikhoeck** [comment]
maybe related to #13006
