### ISSUE TITLE
polars.exceptions.ColumnNotFoundError after left join using ctx.execute(select )

### ISSUE THREAD

**Issue by dawsongzhao0523** [pola-rs/polars#13005]
### Checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pypi.org/project/polars/) of Polars.

### Reproducible example

```python
    def get_bi_dataset_relationship(self):
        """
        :return:
        """
        ctx = pl.SQLContext(t1=self.get_bi_dataset_relationship_by_id(),  eager_execution=True)

        df1 = self.get_bi_dataset_id_name().with_columns(  
            pl.col("tableName").map_elements(lambda x: x.decode('utf-8')).alias("tableNameTrans"),
        )
       
        # OK
        print(df1)

        ctx.register_many(t2=df1)
        ctx.register_many(t3=df1)
        df_all1 = ctx.execute('select * from t1 left join t2 on t1.targetId=t2.tableId left join t3 on t1.sourceId=t3.tableId')

       # OK
        print(df_all1)

        df_all2 = ctx.execute('select t1.targetId,t1.sourceId, t2.tableId, t2.tableNameTrans as targetName,t3.tableId as tableId3,t3.tableNameTrans as sourceName from t1 left join t2 on t1.targetId=t2.tableId left join t3 on t1.sourceId=t3.tableId')
        print(df_all2)
```

### Log output

```shell
shape: (6_242, 3)
┌──────────────────┬───────────────┬───────────────────────────────────┐
│ tableId          ┆ tableName     ┆ tableNameTrans                    │
│ ---              ┆ ---           ┆ ---                               │
│ str              ┆ binary        ┆ str                               │
╞══════════════════╪═══════════════╪═══════════════════════════════════╡
│ 0007480be5eea3b5 ┆ [binary data] ┆ API管理平台-core_api_java_portal_ │
│                  ┆               ┆ api…                              │
│ 000fb6d500e39008 ┆ [binary data] ┆ 部件-研发项目里程碑明细           │
│ 001a1b084b8712bf ┆ [binary data] ┆ 样机处理头:                       │
│                  ┆               ┆ v_bda_sd_spl_handle_heade…        │
│ 001bcb5cc5ba48d3 ┆ [binary data] ┆ 回款金额和合同金额                │
│ …                ┆ …             ┆ …                                 │
│ ffdecd3466f0037d ┆ [binary data] ┆ 财务-关联方收入明细表             │
│ ffe4411339509833 ┆ [binary data] ┆ pengjun的自助数据集5              │
│ ffedb040a037a180 ┆ [binary data] ┆ BI优化-更新任务fi                 │
│ fff2f72a9e609121 ┆ [binary data] ┆ BI Demo_贷款明细表                │
└──────────────────┴───────────────┴───────────────────────────────────┘
shape: (1_010, 6)
┌──────────────────┬──────────────────┬───────────────┬─────────────────────────────────┬─────────────────┬───────────────────────┐
│ targetId         ┆ sourceId         ┆ tableName     ┆ tableNameTrans                  ┆ tableName_right ┆ tableNameTrans_right  │
│ ---              ┆ ---              ┆ ---           ┆ ---                             ┆ ---             ┆ ---                   │
│ str              ┆ str              ┆ binary        ┆ str                             ┆ binary          ┆ str                   │
╞══════════════════╪══════════════════╪═══════════════╪═════════════════════════════════╪═════════════════╪═══════════════════════╡
│ 008c2673e8d2fb16 ┆ 1e9b13c59862ec9e ┆ [binary data] ┆ 05-库存明细（入子库）           ┆ [binary data]   ┆ 公共维-子库           │
│ 008c2673e8d2fb16 ┆ 63f652572712c22d ┆ [binary data] ┆ 05-库存明细（入子库）           ┆ [binary data]   ┆ 公共维-BG/BU映射      │
│ 008c2673e8d2fb16 ┆ b07c21d63e4995d2 ┆ [binary data] ┆ 05-库存明细（入子库）           ┆ [binary data]   ┆ 公共维-日期-天（新）  │
│ 008c2673e8d2fb16 ┆ b9a1234b40a7923a ┆ [binary data] ┆ 05-库存明细（入子库）           ┆ [binary data]   ┆ 公共维-库存组织       │
│ …                ┆ …                ┆ …             ┆ …                               ┆ …               ┆ …                     │
│ ff0bed977aff0463 ┆ 942659a42accd227 ┆ [binary data] ┆ 企服_报价单明细-test            ┆ [binary data]   ┆ 企服_权限_商务产品线  │
│ ff67a96ce8658e68 ┆ 9672c888dc9c5585 ┆ [binary data] ┆ 14-替代组计划配比和执行配比差异 ┆ [binary data]   ┆ 99-策采按小分类控权限 │
│ ff6b308ab52d0355 ┆ 6d68c82ef9ee3c51 ┆ [binary data] ┆ 营销-教育-02-商机线索按月事业部 ┆ [binary data]   ┆ dim_hcm_orgunit       │
│ ffd63803c348413d ┆ a6a02863cd4518d6 ┆ [binary data] ┆ 薪酬数据_SDA_EMP_薪资成本       ┆ [binary data]   ┆ DW_核算单元数据集     │
└──────────────────┴──────────────────┴───────────────┴─────────────────────────────────┴─────────────────┴───────────────────────┘
Traceback (most recent call last):
  File "finebi_row_auth.py", line 207, in <module>
    BIAuthParser().get_bi_dataset_relationship()
  File "finebi_row_auth.py", line 75, in get_bi_dataset_relationship
    df_all2 = ctx.execute('select t1.targetId,t1.sourceId, t2.tableId, t2.tableNameTrans as targetName,t3.tableId as tableId3,t3.tableNameTrans as sourceName from t1 left join t2 on t1.targetId=t2.tableId left join t3 on t1.sourceId=t3.tableId')
  File "/Users/dszhao/anaconda3/lib/python3.8/site-packages/polars/sql/context.py", line 275, in execute
    return res.collect() if (eager or self._eager_execution) else res
  File "/Users/dszhao/anaconda3/lib/python3.8/site-packages/polars/utils/deprecation.py", line 100, in wrapper
    return function(*args, **kwargs)
  File "/Users/dszhao/anaconda3/lib/python3.8/site-packages/polars/lazyframe/frame.py", line 1788, in collect
    return wrap_df(ldf.collect())
polars.exceptions.ColumnNotFoundError: tableId

Error originated just after this operation:
LEFT JOIN:
LEFT PLAN ON: [col("sourceId")]
  LEFT JOIN:
  LEFT PLAN ON: [col("targetId")]
    DF ["targetId", "sourceId"]; PROJECT */2 COLUMNS; SELECTION: "None"
  RIGHT PLAN ON: [col("tableId")]
    DF ["tableId", "tableName", "tableNameTrans"]; PROJECT */3 COLUMNS; SELECTION: "None"
  END LEFT JOIN
RIGHT PLAN ON: [col("tableId")]
  DF ["tableId", "tableName", "tableNameTrans"]; PROJECT */3 COLUMNS; SELECTION: "None"
END LEFT JOIN
```

### Issue description

why df_all1 = ctx.execute('select * from t1 left join t2 on t1.targetId=t2.tableId left join t3 on t1.sourceId=t3.tableId') is OK .
but df_all2 = ctx.execute('select t1.targetId,t1.sourceId, t2.tableId, t2.tableNameTrans as targetName,t3.tableId as tableId3,t3.tableNameTrans as sourceName from t1 left join t2 on t1.targetId=t2.tableId left join t3 on t1.sourceId=t3.tableId')
not ok ?

### Expected behavior

df_all2 = ctx.execute('select t1.targetId,t1.sourceId, t2.tableId, t2.tableNameTrans as targetName,t3.tableId as tableId3,t3.tableNameTrans as sourceName from t1 left join t2 on t1.targetId=t2.tableId left join t3 on t1.sourceId=t3.tableId') works OK.

### Installed versions

<details>

```
(base) dszhao@dszhao util % python3
Python 3.8.5 (default, Sep  4 2020, 02:22:02) 
[Clang 10.0.0 ] :: Anaconda, Inc. on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import polars as pl
>>> pl.show_versions()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/dszhao/anaconda3/lib/python3.8/site-packages/polars/utils/show_versions.py", line 45, in show_versions
    deps = _get_dependency_info()
  File "/Users/dszhao/anaconda3/lib/python3.8/site-packages/polars/utils/show_versions.py", line 81, in _get_dependency_info
    return {f"{name}:": _get_dependency_version(name) for name in opt_deps}
  File "/Users/dszhao/anaconda3/lib/python3.8/site-packages/polars/utils/show_versions.py", line 81, in <dictcomp>
    return {f"{name}:": _get_dependency_version(name) for name in opt_deps}
  File "/Users/dszhao/anaconda3/lib/python3.8/site-packages/polars/utils/show_versions.py", line 90, in _get_dependency_version
    module = importlib.import_module(dep_name)
  File "/Users/dszhao/anaconda3/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 783, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/Users/dszhao/anaconda3/lib/python3.8/site-packages/gevent/__init__.py", line 86, in <module>
    from gevent._hub_local import get_hub
  File "/Users/dszhao/anaconda3/lib/python3.8/site-packages/gevent/_hub_local.py", line 101, in <module>
    import_c_accel(globals(), 'gevent.__hub_local')
  File "/Users/dszhao/anaconda3/lib/python3.8/site-packages/gevent/_util.py", line 148, in import_c_accel
    mod = importlib.import_module(cname)
  File "/Users/dszhao/anaconda3/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "src/gevent/_hub_local.py", line 1, in init gevent._gevent_c_hub_local
ValueError: greenlet.greenlet size changed, may indicate binary incompatibility. Expected 152 from C header, got 40 from PyObject

```

</details>

**Comment by dawsongzhao0523** [comment]
(base) dszhao@dszhao util % python3
Python 3.8.5 (default, Sep  4 2020, 02:22:02) 
[Clang 10.0.0 ] :: Anaconda, Inc. on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import polars as pl
>>> pl.show_versions()
--------Version info---------
Polars:               0.19.19
Index type:           UInt32
Platform:             macOS-10.16-x86_64-i386-64bit
Python:               3.8.5 (default, Sep  4 2020, 02:22:02) 
[Clang 10.0.0 ]

----Optional dependencies----
adbc_driver_manager:  <not installed>
cloudpickle:          1.6.0
connectorx:           0.3.2
deltalake:            <not installed>
fsspec:               2022.11.0
gevent:               23.9.1
matplotlib:           3.3.2
numpy:                1.24.4
openpyxl:             3.1.2
pandas:               2.0.3
pyarrow:              10.0.0
pydantic:             1.10.11
pyiceberg:            <not installed>
pyxlsb:               <not installed>
sqlalchemy:           1.4.50
xlsx2csv:             <not installed>
xlsxwriter:           1.3.7
