### ISSUE TITLE
parameter `raise_if_empty` doesn't work with `comment_prefix` in `read_csv` gives `polars.exceptions.NoDataError: not enough lines to skip`

### ISSUE THREAD

**Issue by Gaura** [pola-rs/polars#13022]
### Checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pypi.org/project/polars/) of Polars.

### Reproducible example

minimal example input file, `test.tsv`
```
##comment to skip
Col1    Col2
```
Python code:
```python
import polars as pl
df = pl.read_csv('test.tsv', separator = '\t', comment_prefix='##', raise_if_empty=False)
```

### Log output

```shell
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "<path>/local/lib/python3.10/site-packages/polars/utils/deprecation.py", line 100, in wrapper
    return function(*args, **kwargs)
  File "<path>/local/lib/python3.10/site-packages/polars/io/csv/functions.py", line 369, in read_csv
    df = pl.DataFrame._read_csv(
  File "<path>/local/lib/python3.10/site-packages/polars/dataframe/frame.py", line 775, in _read_csv
    self._df = PyDataFrame.read_csv(
polars.exceptions.NoDataError: not enough lines to skip
```

### Issue description

The given minimal file and example give error `polars.exceptions.NoDataError: not enough lines to skip`. Detailed log added. However, if there's a file with NoData (without data, just columns) and no comments, the same loads without an error. 

### Expected behavior

Expected behavior is to just load the columns as with files where comment prefix is not present. Expected output:
```
file < 128 rows, no statistics determined                                                                 
no. of chunks: 1 processed by: 1 threads.                                                                 
shape: (0, 2)
┌──────┬──────┐
│ Col1 ┆ Col2 │
│ ---  ┆ ---  │
│ str  ┆ str  │
╞══════╪══════╡
```

### Installed versions

<details>

```
--------Version info---------
Polars:              0.19.15
Index type:          UInt32
Platform:            Linux-5.4.0-156-generic-x86_64-with-glibc2.31
Python:              3.10.6 (main, Aug  3 2022, 14:53:51) [GCC 9.4.0]

----Optional dependencies----
adbc_driver_sqlite:  <not installed>
cloudpickle:         2.2.1
connectorx:          <not installed>
deltalake:           <not installed>
fsspec:              <not installed>
gevent:              <not installed>
matplotlib:          3.8.2
numpy:               1.26.2
openpyxl:            <not installed>
pandas:              2.1.3
pyarrow:             14.0.1
pydantic:            <not installed>
pyiceberg:           <not installed>
pyxlsb:              <not installed>
sqlalchemy:          2.0.23
xlsx2csv:            <not installed>
xlsxwriter:          <not installed>
```

</details>

**Comment by alexander-beedie** [comment]
Thanks for the clean example - will be fixed in the upcoming release. (Note that the value of `raise_if_empty` wasn't connected to the error, there was actually a slightly different issue with parser logic that has now been resolved) 👌

**Comment by Gaura** [comment]
Thanks for the fix and sharing the information, @alexander-beedie! Much appreciated.
