### ISSUE TITLE
`shift(..).over(..)` fails with categorical columns when not every category is in each group

### ISSUE THREAD

**Issue by sotte** [pola-rs/polars#13041]
### Checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pypi.org/project/polars/) of Polars.

### Reproducible example

```python
import polars as pl

df = pl.DataFrame(
    {
        "id": [0, 0, 0, 1, 1, 1],
        "int_col": [1, 2, 3, 11, 12, 13],
        "str_col": ["zero", "one", "two", "three", "four", "five"],
    }
).with_columns(
    pl.Series(["a", "b", "c", "d", "e", "f"], dtype=pl.Categorical).alias("cat_col")
)
print(df)
# shape: (6, 4)
# ┌─────┬─────────┬─────────┬─────────┐
# │ id  ┆ int_col ┆ str_col ┆ cat_col │
# │ --- ┆ ---     ┆ ---     ┆ ---     │
# │ i64 ┆ i64     ┆ str     ┆ cat     │
# ╞═════╪═════════╪═════════╪═════════╡
# │ 0   ┆ 1       ┆ zero    ┆ a       │
# │ 0   ┆ 2       ┆ one     ┆ b       │
# │ 0   ┆ 3       ┆ two     ┆ c       │
# │ 1   ┆ 11      ┆ three   ┆ d       │
# │ 1   ┆ 12      ┆ four    ┆ e       │
# │ 1   ┆ 13      ┆ five    ┆ f       │
# └─────┴─────────┴─────────┴─────────┘

# shift & over with int and str columns works as expected
print(
    df.with_columns(
        [
            pl.col("int_col").shift(1).over("id").alias("int_col_1"),
            pl.col("int_col").shift(2).over("id").alias("int_col_2"),
            pl.col("str_col").shift(1).over("id").alias("str_col_1"),
        ]
    )
)
# shape: (6, 7)
# ┌─────┬─────────┬─────────┬─────────┬───────────┬───────────┬───────────┐
# │ id  ┆ int_col ┆ str_col ┆ cat_col ┆ int_col_1 ┆ int_col_2 ┆ str_col_1 │
# │ --- ┆ ---     ┆ ---     ┆ ---     ┆ ---       ┆ ---       ┆ ---       │
# │ i64 ┆ i64     ┆ str     ┆ cat     ┆ i64       ┆ i64       ┆ str       │
# ╞═════╪═════════╪═════════╪═════════╪═══════════╪═══════════╪═══════════╡
# │ 0   ┆ 1       ┆ zero    ┆ a       ┆ null      ┆ null      ┆ null      │
# │ 0   ┆ 2       ┆ one     ┆ b       ┆ 1         ┆ null      ┆ zero      │
# │ 0   ┆ 3       ┆ two     ┆ c       ┆ 2         ┆ 1         ┆ one       │
# │ 1   ┆ 11      ┆ three   ┆ d       ┆ null      ┆ null      ┆ null      │
# │ 1   ┆ 12      ┆ four    ┆ e       ┆ 11        ┆ null      ┆ three     │
# │ 1   ┆ 13      ┆ five    ┆ f       ┆ 12        ┆ 11        ┆ four      │
# └─────┴─────────┴─────────┴─────────┴───────────┴───────────┴───────────┘


# But shift&over fails with categorical columns.
# Note not every category is present in every group.
print(
    df.with_columns(
        pl.col("cat_col").shift(2).over("id").alias("cat_col_2"),
    )
)
# Traceback (most recent call last):
#   File "/home/stefan/work/paretos-demand/dummy.py", line 27, in <module>
#     df.with_columns(
#   File "/home/stefan/work/paretos-demand/.venv/lib/python3.10/site-packages/polars/dataframe/frame.py", line 8027, in with_columns
#     return self.lazy().with_columns(*exprs, **named_exprs).collect(_eager=True)
#   File "/home/stefan/work/paretos-demand/.venv/lib/python3.10/site-packages/polars/utils/deprecation.py", line 100, in wrapper
#     return function(*args, **kwargs)
#   File "/home/stefan/work/paretos-demand/.venv/lib/python3.10/site-packages/polars/lazyframe/frame.py", line 1788, in collect
#     return wrap_df(ldf.collect())
# polars.exceptions.ComputeError: aggregation expression ''col("cat_col").shift([2])' ' produced a different number of elements: 3 than the number of groups: 2 (this is likely invalid)
```

### Log output

```shell
Traceback (most recent call last):
  File "/home/stefan/work/paretos-demand/dummy.py", line 27, in <module>
    df.with_columns(
  File "/home/stefan/work/paretos-demand/.venv/lib/python3.10/site-packages/polars/dataframe/frame.py", line 8027, in with_columns
    return self.lazy().with_columns(*exprs, **named_exprs).collect(_eager=True)
  File "/home/stefan/work/paretos-demand/.venv/lib/python3.10/site-packages/polars/utils/deprecation.py", line 100, in wrapper
    return function(*args, **kwargs)
  File "/home/stefan/work/paretos-demand/.venv/lib/python3.10/site-packages/polars/lazyframe/frame.py", line 1788, in collect
    return wrap_df(ldf.collect())
polars.exceptions.ComputeError: aggregation expression ''col("cat_col").shift([2])' ' produced a different number of elements: 3 than the number of groups: 2 (this is likely invalid)
```

### Issue description

I have issues working with `shift` & `over` with categorical columns. Groups which don't contain every category fail (see error below). What is the proper way of handling this scenario or is this a bug?

### Expected behavior

I would expect that I can `shift(...).over(...)` groups with categorical values.
Or that I can configure to use the observed values (like with pandas `observed` [argument](https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.groupby.html)).

### Installed versions

<details>

```
--------Version info---------
Polars:               0.19.19
Index type:           UInt32
Platform:             Linux-6.5.4-76060504-generic-x86_64-with-glibc2.35
Python:               3.10.12 (main, Nov 20 2023, 15:14:05) [GCC 11.4.0]

----Optional dependencies----
adbc_driver_manager:  <not installed>
cloudpickle:          3.0.0
connectorx:           <not installed>
deltalake:            <not installed>
fsspec:               2023.6.0
gevent:               <not installed>
matplotlib:           3.7.2
numpy:                1.24.4
openpyxl:             3.1.2
pandas:               1.5.3
pyarrow:              14.0.1
pydantic:             1.10.12
pyiceberg:            <not installed>
pyxlsb:               <not installed>
sqlalchemy:           2.0.20
xlsx2csv:             <not installed>
xlsxwriter:           <not installed>

```

</details>

**Comment by mcrumiller** [comment]
Unrelated but want to fix that title? 👀

**Comment by sotte** [comment]
I'm more than willing to help out here, but I need some pointers.

**Comment by ritchie46** [comment]
@c-peters this might be a good one?

**Comment by sotte** [comment]
That was quick. Thanks!
