### ISSUE TITLE
ComputeError(ErrString("Chunk require all its arrays to have an equal number of rows")) when `streaming=True`

### ISSUE THREAD

**Issue by jmakov** [pola-rs/polars#13059]
### Checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pypi.org/project/polars/) of Polars.

### Reproducible example

```python
# works if (ts_ns_to - ts_ns_from) is about 1 month, if more, panics
# works with `streaming=False`
source = polars.scan_parquet("/parquet_partitioned_dataset_path/*/*/*/*.parquet") \
    .filter(
        polars.col("timestamp").is_between(ts_ns_from, ts_ns_to)
        & (polars.col("another_col") < some_threshold)) \
    .sort("timestamp")
q1 = source.select([polars.sum_horizontal([col for col in source.columns if "test" in col])/20])
q1.collect(streaming=True)
```

### Log output

```shell
chrome crashes when using `POLARS_VERBOSE`. A few rows before it does:
POLARS PREFETCH_SIZE: 48
RUN STREAMING PIPELINE
parquet -> sort -> projection -> ordered_sink
RefCell { value: [] }
STREAMING CHUNK SIZE: 2272 rows
STREAMING CHUNK SIZE: 2272 rows
STREAMING CHUNK SIZE: 2272 rows
parquet file must be read, statistics not sufficient for predicate.
parquet file must be read, statistics not sufficient for predicate.
parquet file must be read, statistics not sufficient for predicate.
STREAMING CHUNK SIZE: 2272 rows
parquet file must be read, statistics not sufficient for predicate.
parquet file must be read, statistics not sufficient for predicate.
...
```
Traceback:
```
thread '<unnamed>' panicked at /home/conda/feedstock_root/build_artifacts/polars_1701471768069/work/crates/polars-arrow/src/chunk.rs:20:31:
called `Result::unwrap()` on an `Err` value: ComputeError(ErrString("Chunk require all its arrays to have an equal number of rows"))
thread '<unnamed>' panicked at /home/conda/feedstock_root/build_artifacts/polars_1701471768069/work/crates/polars-arrow/src/chunk.rs:20:31:
called `Result::unwrap()` on an `Err` value: ComputeError(ErrString("Chunk require all its arrays to have an equal number of rows"))
thread '<unnamed>' panicked at crates/polars-core/src/series/into.rs:15:23:
index out of bounds: the len is 6 but the index is 6
thread '<unnamed>' panicked at /home/conda/feedstock_root/build_artifacts/polars_1701471768069/work/crates/polars-arrow/src/chunk.rs:20:31:
called `Result::unwrap()` on an `Err` value: ComputeError(ErrString("Chunk require all its arrays to have an equal number of rows"))
thread '<unnamed>' panicked at crates/polars-core/src/series/into.rs:15:23:
index out of bounds: the len is 9 but the index is 9
thread '<unnamed>' panicked at /home/conda/feedstock_root/build_artifacts/polars_1701471768069/work/crates/polars-arrow/src/chunk.rs:20:31:
called `Result::unwrap()` on an `Err` value: ComputeError(ErrString("Chunk require all its arrays to have an equal number of rows"))
thread '<unnamed>' panicked at /home/conda/feedstock_root/build_artifacts/polars_1701471768069/work/crates/polars-arrow/src/chunk.rs:20:31:
called `Result::unwrap()` on an `Err` value: ComputeError(ErrString("Chunk require all its arrays to have an equal number of rows"))
thread '<unnamed>' panicked at /home/conda/feedstock_root/build_artifacts/polars_1701471768069/work/crates/polars-arrow/src/chunk.rs:20:31:
called `Result::unwrap()` on an `Err` value: ComputeError(ErrString("Chunk require all its arrays to have an equal number of rows"))
thread '<unnamed>' panicked at /home/conda/feedstock_root/build_artifacts/polars_1701471768069/work/crates/polars-arrow/src/chunk.rs:20:31:
called `Result::unwrap()` on an `Err` value: ComputeError(ErrString("Chunk require all its arrays to have an equal number of rows"))
thread '<unnamed>' panicked at /home/conda/feedstock_root/build_artifacts/polars_1701471768069/work/crates/polars-arrow/src/chunk.rs:20:31:
called `Result::unwrap()` on an `Err` value: ComputeError(ErrString("Chunk require all its arrays to have an equal number of rows"))
thread '<unnamed>' panicked at /home/conda/feedstock_root/build_artifacts/polars_1701471768069/work/crates/polars-arrow/src/chunk.rs:20:31:
called `Result::unwrap()` on an `Err` value: ComputeError(ErrString("Chunk require all its arrays to have an equal number of rows"))
thread '<unnamed>' panicked at /home/conda/feedstock_root/build_artifacts/polars_1701471768069/work/crates/polars-arrow/src/chunk.rs:20:31:
called `Result::unwrap()` on an `Err` value: ComputeError(ErrString("Chunk require all its arrays to have an equal number of rows"))
thread '<unnamed>' panicked at crates/polars-core/src/series/into.rs:15:23:
index out of bounds: the len is 2 but the index is 2
thread '<unnamed>' panicked at crates/polars-core/src/series/into.rs:15:23:
index out of bounds: the len is 6 but the index is 6
thread '<unnamed>' panicked at /home/conda/feedstock_root/build_artifacts/polars_1701471768069/work/crates/polars-arrow/src/chunk.rs:20:31:
called `Result::unwrap()` on an `Err` value: ComputeError(ErrString("Chunk require all its arrays to have an equal number of rows"))
thread '<unnamed>' panicked at crates/polars-core/src/series/into.rs:15:23:
index out of bounds: the len is 1 but the index is 1
thread '<unnamed>' panicked at /home/conda/feedstock_root/build_artifacts/polars_1701471768069/work/crates/polars-arrow/src/chunk.rs:20:31:
called `Result::unwrap()` on an `Err` value: ComputeError(ErrString("Chunk require all its arrays to have an equal number of rows"))
thread '<unnamed>' panicked at /home/conda/feedstock_root/build_artifacts/polars_1701471768069/work/crates/polars-arrow/src/chunk.rs:20:31:
called `Result::unwrap()` on an `Err` value: ComputeError(ErrString("Chunk require all its arrays to have an equal number of rows"))
thread '<unnamed>' panicked at /home/conda/feedstock_root/build_artifacts/polars_1701471768069/work/crates/polars-arrow/src/chunk.rs:20:31:
called `Result::unwrap()` on an `Err` value: ComputeError(ErrString("Chunk require all its arrays to have an equal number of rows"))
thread '<unnamed>' panicked at crates/polars-core/src/series/into.rs:15:23:
index out of bounds: the len is 2 but the index is 2
thread '<unnamed>' panicked at crates/polars-core/src/series/into.rs:15:23:
index out of bounds: the len is 2 but the index is 2
thread '<unnamed>' panicked at crates/polars-core/src/series/into.rs:15:23:
index out of bounds: the len is 6 but the index is 6
thread '<unnamed>' panicked at crates/polars-core/src/series/into.rs:15:23:
index out of bounds: the len is 5 but the index is 5
thread '<unnamed>' panicked at /home/conda/feedstock_root/build_artifacts/polars_1701471768069/work/crates/polars-arrow/src/chunk.rs:20:31:
called `Result::unwrap()` on an `Err` value: ComputeError(ErrString("Chunk require all its arrays to have an equal number of rows"))
thread '<unnamed>' panicked at crates/polars-core/src/series/into.rs:15:23:
index out of bounds: the len is 1 but the index is 1
thread '<unnamed>' panicked at crates/polars-core/src/series/into.rs:15:23:
index out of bounds: the len is 4 but the index is 4
thread '<unnamed>' panicked at crates/polars-core/src/series/into.rs:15:23:
index out of bounds: the len is 8 but the index is 8
thread '<unnamed>' panicked at crates/polars-core/src/series/into.rs:15:23:
index out of bounds: the len is 5 but the index is 5
thread '<unnamed>' panicked at /home/conda/feedstock_root/build_artifacts/polars_1701471768069/work/crates/polars-arrow/src/chunk.rs:20:31:
called `Result::unwrap()` on an `Err` value: ComputeError(ErrString("Chunk require all its arrays to have an equal number of rows"))
thread '<unnamed>' panicked at crates/polars-core/src/series/into.rs:15:23:
index out of bounds: the len is 9 but the index is 9
thread '<unnamed>' panicked at crates/polars-core/src/series/into.rs:15:23:
index out of bounds: the len is 14 but the index is 14
thread '<unnamed>' panicked at /home/conda/feedstock_root/build_artifacts/polars_1701471768069/work/crates/polars-arrow/src/chunk.rs:20:31:
called `Result::unwrap()` on an `Err` value: ComputeError(ErrString("Chunk require all its arrays to have an equal number of rows"))
thread '<unnamed>' panicked at crates/polars-core/src/series/into.rs:15:23:
index out of bounds: the len is 5 but the index is 5
thread '<unnamed>' panicked at crates/polars-core/src/series/into.rs:15:23:
index out of bounds: the len is 15 but the index is 15
thread '<unnamed>' panicked at /home/conda/feedstock_root/build_artifacts/polars_1701471768069/work/crates/polars-arrow/src/chunk.rs:20:31:
called `Result::unwrap()` on an `Err` value: ComputeError(ErrString("Chunk require all its arrays to have an equal number of rows"))
thread '<unnamed>' panicked at crates/polars-core/src/series/into.rs:15:23:
index out of bounds: the len is 5 but the index is 5
thread '<unnamed>' panicked at crates/polars-core/src/series/into.rs:15:23:
index out of bounds: the len is 7 but the index is 7
thread '<unnamed>' panicked at crates/polars-core/src/series/into.rs:15:23:
index out of bounds: the len is 2 but the index is 2
thread '<unnamed>' panicked at crates/polars-core/src/series/into.rs:15:23:
index out of bounds: the len is 2 but the index is 2
thread '<unnamed>' panicked at crates/polars-core/src/series/into.rs:15:23:
index out of bounds: the len is 9 but the index is 9
thread '<unnamed>' panicked at crates/polars-core/src/series/into.rs:15:23:
index out of bounds: the len is 3 but the index is 3
thread '<unnamed>' panicked at /home/conda/feedstock_root/build_artifacts/polars_1701471768069/work/crates/polars-arrow/src/chunk.rs:20:31:
called `Result::unwrap()` on an `Err` value: ComputeError(ErrString("Chunk require all its arrays to have an equal number of rows"))
thread '<unnamed>' panicked at /home/conda/feedstock_root/build_artifacts/polars_1701471768069/work/crates/polars-arrow/src/chunk.rs:20:31:
called `Result::unwrap()` on an `Err` value: ComputeError(ErrString("Chunk require all its arrays to have an equal number of rows"))
thread '<unnamed>' panicked at crates/polars-core/src/series/into.rs:15:23:
index out of bounds: the len is 7 but the index is 7
thread '<unnamed>' panicked at /home/conda/feedstock_root/build_artifacts/polars_1701471768069/work/crates/polars-arrow/src/chunk.rs:20:31:
called `Result::unwrap()` on an `Err` value: ComputeError(ErrString("Chunk require all its arrays to have an equal number of rows"))
thread '<unnamed>' panicked at crates/polars-core/src/series/into.rs:15:23:
index out of bounds: the len is 6 but the index is 6
thread '<unnamed>' panicked at /home/conda/feedstock_root/build_artifacts/polars_1701471768069/work/crates/polars-arrow/src/chunk.rs:20:31:
called `Result::unwrap()` on an `Err` value: ComputeError(ErrString("Chunk require all its arrays to have an equal number of rows"))
thread '<unnamed>' panicked at /home/conda/feedstock_root/build_artifacts/polars_1701471768069/work/crates/polars-arrow/src/chunk.rs:20:31:
called `Result::unwrap()` on an `Err` value: ComputeError(ErrString("Chunk require all its arrays to have an equal number of rows"))
thread '<unnamed>' panicked at crates/polars-pipe/src/executors/sinks/io.rs:232:33:
called `Result::unwrap()` on an `Err` value: Io(Os { code: 28, kind: StorageFull, message: "No space left on device" })
```

### Issue description

The query executes fine for about 1 month of data. If more data is selected, the above panic happens (even with `low_memory=True`. Sometimes, even when it doesn't panic, I see a lot of data being written to `/tmp/polars/sort`.

### Expected behavior

According to docs, should work

### Installed versions

<details>

```
--------Version info---------
Polars:               0.19.19
Index type:           UInt32
Platform:             Linux-6.1.64-1-MANJARO-x86_64-with-glibc2.38
Python:               3.10.13 | packaged by conda-forge | (main, Oct 26 2023, 18:07:37) [GCC 12.3.0]

----Optional dependencies----
adbc_driver_manager:  <not installed>
cloudpickle:          3.0.0
connectorx:           0.3.2
deltalake:            <not installed>
fsspec:               2023.12.1
gevent:               23.9.1
matplotlib:           3.8.2
numpy:                1.24.4
openpyxl:             <not installed>
pandas:               1.5.3
pyarrow:              14.0.1
pydantic:             1.10.13
pyiceberg:            <not installed>
pyxlsb:               <not installed>
sqlalchemy:           1.4.50
xlsx2csv:             <not installed>
xlsxwriter:           <not installed>
```

</details>

**Comment by ritchie46** [comment]
It seems we cannot finish the query because we don't have enough space? The data we sort must be stored somewhere.

**Comment by jmakov** [comment]
Thanks for the quick response. Makes sense. However wondering how come that even if I don't select the sorted column in the resulting query, `/tmp/polars/sort` takes a lot of space e.g. 25GB. In addition it looks like the sorted column takes only 570MB of space: `source.select("timestamp").collect(streaming=True).estimated_size("mb")` returns `570`.
