### ISSUE TITLE
filtering date_range expression errors in debug mode

### ISSUE THREAD

**Issue by MarcoGorelli** [pola-rs/polars#13084]
### Checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pypi.org/project/polars/) of Polars.

### Reproducible example

```python
expr = pl.date_range(date(2020, 1, 1), date(2020, 1, 3))
expr = expr.filter(expr.is_in([date(2020, 1, 2)]))
print(pl.select(expr))
```

### Log output

```shell
thread '<unnamed>' panicked at crates/polars-lazy/src/physical_plan/expressions/apply.rs:41:13:
expr 2020-01-01.date_range([2020-01-03]).is_in([Series]) is not implemented correctly. 'returns_scalar' and 'elementwise' are mutually exclusive
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
Traceback (most recent call last):
  File "/home/marcogorelli/polars-dev/py-polars/t.py", line 9, in <module>
    print(pl.select(expr))
  File "/home/marcogorelli/polars-dev/py-polars/polars/functions/lazy.py", line 1617, in select
    return pl.DataFrame().select(*exprs, **named_exprs)
  File "/home/marcogorelli/polars-dev/py-polars/polars/dataframe/frame.py", line 8147, in select
    return self.lazy().select(*exprs, **named_exprs).collect(_eager=True)
  File "/home/marcogorelli/polars-dev/py-polars/polars/lazyframe/frame.py", line 1706, in collect
    return wrap_df(ldf.collect())
pyo3_runtime.PanicException: expr 2020-01-01.date_range([2020-01-03]).is_in([Series]) is not implemented correctly. 'returns_scalar' and 'elementwise' are mutually exclusive
```

### Issue description

Running the above on the latest release, I get:
```python
expr = pl.date_range(date(2020, 1, 1), date(2020, 1, 3))
expr = expr.filter(expr.is_in([date(2020, 1, 2)]))
print(pl.select(expr))
```
which looks correct

But, when running it from a debug build of Polars, I get the error above

### Expected behavior

No error in debug mode, it just looks a bit worrying to be getting one

### Installed versions

<details>

```
--------Version info---------
Polars:               0.20.0
Index type:           UInt32
Platform:             Linux-5.15.133.1-microsoft-standard-WSL2-x86_64-with-glibc2.35
Python:               3.10.12 (main, Nov 20 2023, 15:14:05) [GCC 11.4.0]

----Optional dependencies----
adbc_driver_manager:  <not installed>
cloudpickle:          2.2.1
connectorx:           <not installed>
deltalake:            0.9.0
fsspec:               2023.6.0
gevent:               <not installed>
matplotlib:           3.7.1
numpy:                1.26.2
openpyxl:             <not installed>
pandas:               2.1.4
pyarrow:              14.0.1
pydantic:             2.0.2
pyiceberg:            <not installed>
pyxlsb:               <not installed>
sqlalchemy:           2.0.20
xlsx2csv:             <not installed>
xlsxwriter:           <not installed>
```

</details>

**Comment by mcrumiller** [comment]
@MarcoGorelli I believe this applies to all ranges, not just date ranges:

```shell
>>> pl.select(pl.int_range(0, 2).is_in([1]))
pyo3_runtime.PanicException: expr 0.int_range([2]).is_in([Series]) is not implemented correctly. 'returns_scalar' and 'elementwise' are mutually exclusive
```
