### ISSUE TITLE
Simple test case fails with: NameError: name 'PyLazyFrame' is not defined

### ISSUE THREAD

**Issue by yurivict** [pola-rs/polars#13094]
### Checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pypi.org/project/polars/) of Polars.

### Reproducible example

[This](https://pola-rs.github.io/polars/) testcase:

```python
import polars as pl

q = (
    pl.scan_csv("docs/data/iris.csv")
    .filter(pl.col("sepal_length") > 5)
    .group_by("species")
    .agg(pl.all().sum())
)

df = q.collect()
```
fails:
```
$ python3.9 y.py
/usr/local/lib/python3.9/site-packages/polars/utils/build_info.py:5: UserWarning: polars binary missing!
  from polars.utils.polars_version import get_polars_version
Traceback (most recent call last):
  File "/usr/ports/misc/py-polars/y.py", line 4, in <module>
    pl.scan_csv("docs/data/iris.csv")
  File "/usr/local/lib/python3.9/site-packages/polars/io/csv/functions.py", line 911, in scan_csv
    return pl.LazyFrame._scan_csv(
  File "/usr/local/lib/python3.9/site-packages/polars/lazyframe/frame.py", line 372, in _scan_csv
    self._ldf = PyLazyFrame.new_from_csv(
NameError: name 'PyLazyFrame' is not defined
```

Version: polars-0.19.12
Python-3.9
FreeBSD 13.2

### Issue description

n/a

### Expected behavior

n/a

### Installed versions

n/a

**Comment by cmdlineluser** [comment]
Something is wrong with your installation of polars:

> UserWarning: polars binary missing!

Does `polars.abi3.so` exist?

```python
>>> import ctypes
>>> ctypes.CDLL("/usr/local/lib/python3.9/site-packages/polars/polars.abi3.so")
<CDLL '/usr/local/lib/python3.9/site-packages/polars/polars.abi3.so', handle 7f8119d47c30 at 0x10e394d30>
```

**Comment by yurivict** [comment]
```
$ python3.9
Python 3.9.18 (main, Oct 19 2023, 01:22:22) 
[Clang 14.0.5 (https://github.com/llvm/llvm-project.git llvmorg-14.0.5-0-gc1238 on freebsd13
Type "help", "copyright", "credits" or "license" for more information.
>>> import ctypes
>>> ctypes.CDLL("/usr/local/lib/python3.9/site-packages/polars/polars.abi3.so")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.9/ctypes/__init__.py", line 374, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: /usr/local/lib/python3.9/site-packages/polars/polars.abi3.so: No space available for static Thread Local Storage
```

**Comment by ritchie46** [comment]
How have you installed polars and on what kind of hardware are you running?

**Comment by yurivict** [comment]
polars is installed from the FreeBSD package.

Processor: Intel(R) Core(TM) i7 CPU         930  @ 2.80GHz

**Comment by ritchie46** [comment]
I think you should take this up with the suppliers from that package as it is not properly distributed.

We recommend installing from pypi
