### ISSUE TITLE
Consistently support Python types as aliases for polars types

### ISSUE THREAD

**Issue by Wainberg** [pola-rs/polars#13117]
### Description

Polars sometimes supports Python types (e.g. `str`, `float`, `int`) as aliases for polars types, and sometimes not.

For instance, these are inconsistent:

```python
>>> pl.Series([1], dtype=pl.Float64)
shape: (1,)
Series: '' [f64]
[
        1.0
]
>>> pl.Series([1], dtype=float)
shape: (1,)
Series: '' [i64]
[
        1
]
```

as are these:

```python
>>> pl.DataFrame({'a': [1]}).select(pl.all().cast(str))
 a
 1
shape: (1, 1)
>>> pl.DataFrame({'a': [1]}).cast(str)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/wainberg/miniforge3/lib/python3.12/site-packages/polars/dataframe/frame.py", line 6756, in cast
    return self.lazy().cast(dtypes, strict=strict).collect(_eager=True)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/wainberg/miniforge3/lib/python3.12/site-packages/polars/lazyframe/frame.py", line 2446, in cast
    return self._from_pyldf(self._ldf.cast_all(dtypes, strict))
                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: argument 'dtype': 'type' is not a Polars data type
```

and these:

```python
>>> pl.DataFrame({'a': ['foo']}).select(pl.col(pl.Utf8))
 a
 foo
shape: (1, 1)
>>> pl.DataFrame({'a': ['foo']}).select(pl.col(str))
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/wainberg/miniforge3/lib/python3.12/site-packages/polars/functions/col.py", line 287, in __new__
    return _create_col(name, *more_names)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/wainberg/miniforge3/lib/python3.12/site-packages/polars/functions/col.py", line 61, in _create_col
    raise TypeError(
TypeError: invalid input for `col`

Expected `str` or `DataType`, got 'type'.
```

**Comment by stinodego** [comment]
Yes, this has irked me for a while.

We should update the conversion logic in the PyO3 bindings to properly map some Python types.
And we should probably have some `normalize_dtype` util which should be called on `dtype` inputs that are used for Python logic.

**Comment by Wainberg** [comment]
It would also be good to support NumPy dtypes, e.g. `np.float32` and `np.dtype('float32')`. The latter is what you get when you take the dtype of an existing NumPy array, like `np.array([1], dtype=np.float32).dtype`
