### ISSUE TITLE
`not yet implemented` when call `pl.sum_horizontal`

### ISSUE THREAD

**Issue by wukan1986** [pola-rs/polars#13113]
### Checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pypi.org/project/polars/) of Polars.

### Reproducible example

```python
import polars as pl

df = pl.DataFrame(
    {
        "A": [5, None, 3, 2, 1],
        "B": [5, 3, None, 2, 1],
        "C": [None, None, None, None, None],
    }
)
print(df.schema)

result = df.select(pl.sum_horizontal(pl.col('A'), pl.col('B'), pl.col('C')))
print(result)
```

### Log output

```shell
thread '<unnamed>' panicked at crates\polars-core\src\chunked_array\ops\fill_null.rs:91:18:
not yet implemented
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
Traceback (most recent call last):
  File "b.py", line 12, in <module>
    result = df.select(pl.sum_horizontal(pl.col('A'), pl.col('B'), pl.col('C')))
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Users\Kan\miniconda3\envs\py311_1\Lib\site-packages\polars\dataframe\frame.py", line 8009, in select
    return self.lazy().select(*exprs, **named_exprs).collect(_eager=True)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Users\Kan\miniconda3\envs\py311_1\Lib\site-packages\polars\lazyframe\frame.py", line 1706, in collect
    return wrap_df(ldf.collect())
                   ^^^^^^^^^^^^^
pyo3_runtime.PanicException: not yet implemented
```

### Issue description

if a column dtype is pl.Null it will throw exception

### Expected behavior

1. treat null as 0 when sum_horizontal
2. treat null as 1 when prod_horizontal

### Installed versions

<details>

```
--------Version info---------
Polars:               0.20.1
Index type:           UInt32
Platform:             Windows-10-10.0.22631-SP0
Python:               3.11.3 | packaged by Anaconda, Inc. | (main, Apr 19 2023, 23:46:34) [MSC v.1916 64 bit (AMD64)]

----Optional dependencies----
adbc_driver_manager:  <not installed>
cloudpickle:          <not installed>
connectorx:           <not installed>
deltalake:            <not installed>
fsspec:               <not installed>
gevent:               <not installed>
matplotlib:           3.7.1
numpy:                1.24.3
openpyxl:             3.1.2
pandas:               2.0.1
pyarrow:              12.0.0
pydantic:             1.10.7
pyiceberg:            <not installed>
pyxlsb:               <not installed>
sqlalchemy:           2.0.13
xlsx2csv:             <not installed>
xlsxwriter:           <not installed>

```

</details>

**Comment by stinodego** [comment]
Thanks, I can confirm this bug. Indeed, `Null` columns should be treated as the identity for these functions.
