### ISSUE TITLE
Assigning to a slice of df.columns fails silently

### ISSUE THREAD

**Issue by Wainberg** [pola-rs/polars#13118]
### Checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pypi.org/project/polars/) of Polars.

### Reproducible example

```python
>>> df = pl.DataFrame({'a': [1], 'b': [2]})
>>> df
 a  b
 1  2
shape: (1, 2)
>>> df.columns = 'c', 'd'
>>> df
 c  d
 1  2
shape: (1, 2)
>>> df.columns[1:] = 'this fails'
>>> df
 c  d
 1  2
shape: (1, 2)
>>> df.columns[1:] = ['this also fails']
>>> df
 c  d
 1  2
shape: (1, 2)
```

### Issue description

Assigning to a slice of df.columns, like `df.columns[1:]`, is a null-op: it doesn't modify the columns, but doesn't give an error either.

### Expected behavior

`df.columns[1:] = 'this fails'` should give an error. `df.columns[1:] = ['this also fails']` should either succeed or give an error.

### Installed versions

<details>

```
--------Version info---------
Polars:               0.20.0
Index type:           UInt32
Platform:             Linux-4.18.0-513.5.1.el8_9.x86_64-x86_64-with-glibc2.28
Python:               3.12.0 | packaged by conda-forge | (main, Oct  3 2023, 08:43:22) [GCC 12.3.0]

----Optional dependencies----
adbc_driver_manager:  <not installed>
cloudpickle:          <not installed>
connectorx:           <not installed>
deltalake:            <not installed>
fsspec:               <not installed>
gevent:               <not installed>
matplotlib:           3.8.2
numpy:                1.26.2
openpyxl:             3.1.2
pandas:               2.1.4
pyarrow:              14.0.1
pydantic:             <not installed>
pyiceberg:            <not installed>
pyxlsb:               <not installed>
sqlalchemy:           <not installed>
xlsx2csv:             0.8.1
xlsxwriter:           3.1.9
```

</details>

**Comment by Wainberg** [comment]
Understood. This is a gotcha, though. (I'm posting this because it just happened to me.) It would be nice to at least give an error, like pandas: 

```python
>>> df = pd.DataFrame({'a': [1], 'b': [2]})
>>> df.columns = 'c', 'd'
>>> df
   c  d
0  1  2
>>> df.columns[1:] = 'this fails'
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/wainberg/miniforge3/lib/python3.12/site-packages/pandas/core/indexes/base.py", line 5348, in __setitem__
    raise TypeError("Index does not support mutable operations")
TypeError: Index does not support mutable operations
>>> df.columns[1:] = ['this also fails']
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/wainberg/miniforge3/lib/python3.12/site-packages/pandas/core/indexes/base.py", line 5348, in __setitem__
    raise TypeError("Index does not support mutable operations")
TypeError: Index does not support mutable operations
```

**Comment by mcrumiller** [comment]
@Wainberg the reason that works for pandas is because `df.columns` isn't a python list, it's a `pandas.Index` object, meaning they can intercept any slice assignments. Our `df.columns` is just a regular python list, so without re-implementing it as its own class, doing what you're asking isn't really possible.

**Comment by Wainberg** [comment]
It would also be nice to use NumPy-style indexing to select entries from df.columns. So implementing it as its own class could be useful in several ways!

**Comment by DavidEscott** [comment]
> Our `df.columns` is just a regular python list

Usually one returns a tuple in instances like this. That should be enough to prevent the most obvious sources of confusion.
