### ISSUE TITLE
weights not yet supported on array with null values

### ISSUE THREAD

**Issue by wukan1986** [pola-rs/polars#13169]
### Checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pypi.org/project/polars/) of Polars.

### Reproducible example

I use polars to reproduce  `talib.WMA` function, polars reported an error, but `talib` was fine.

All other `rolling_*(weights)` have same problems

```python
import talib

from polars_ta.imports.expr import *


def ts_decay_linear_pl(x: pl.Expr, d: int = 30) -> pl.Expr:
    weights = pl.arange(1, d + 1, eager=True)
    return x.rolling_mean(d, weights=weights)


def ts_decay_linear_ta(x: pl.Expr, d: int = 30) -> pl.Expr:
    return x.map_batches(lambda x: talib.WMA(x, d))


df = pl.DataFrame({
    'A': range(10),
    'B': [None, None, 2, 3, 4, 5, 6, 7, 8, 9],
    'C': [None, ] * 10,
})

df = df.with_columns([
    ts_decay_linear_ta(pl.col('A'), 5).alias('A_WMA_ta'),
    ts_decay_linear_pl(pl.col('A'), 5).alias('A_WMA_pl'),
    ts_decay_linear_ta(pl.col('B'), 5).alias('B_WMA_ta'),
    #
])

print(df.tail(9))
"""
shape: (9, 6)
┌─────┬──────┬──────┬──────────┬──────────┬──────────┐
│ A   ┆ B    ┆ C    ┆ A_WMA_ta ┆ A_WMA_pl ┆ B_WMA_ta │
│ --- ┆ ---  ┆ ---  ┆ ---      ┆ ---      ┆ ---      │
│ i64 ┆ i64  ┆ null ┆ f64      ┆ f64      ┆ f64      │
╞═════╪══════╪══════╪══════════╪══════════╪══════════╡
│ 1   ┆ null ┆ null ┆ NaN      ┆ null     ┆ NaN      │
│ 2   ┆ 2    ┆ null ┆ NaN      ┆ null     ┆ NaN      │
│ 3   ┆ 3    ┆ null ┆ NaN      ┆ null     ┆ NaN      │
│ 4   ┆ 4    ┆ null ┆ 2.666667 ┆ 2.666667 ┆ NaN      │
│ 5   ┆ 5    ┆ null ┆ 3.666667 ┆ 3.666667 ┆ NaN      │
│ 6   ┆ 6    ┆ null ┆ 4.666667 ┆ 4.666667 ┆ 4.666667 │
│ 7   ┆ 7    ┆ null ┆ 5.666667 ┆ 5.666667 ┆ 5.666667 │
│ 8   ┆ 8    ┆ null ┆ 6.666667 ┆ 6.666667 ┆ 6.666667 │
│ 9   ┆ 9    ┆ null ┆ 7.666667 ┆ 7.666667 ┆ 7.666667 │
└─────┴──────┴──────┴──────────┴──────────┴──────────┘
"""

df = df.with_columns([
    ts_decay_linear_pl(pl.col('B'), 5).alias('B_WMA_pl'),  # weights not yet supported on array with null values
])
print(df.tail(9))
```

### Issue description

```python
thread '<unnamed>' panicked at C:\a\polars\polars\crates\polars-arrow\src\legacy\kernels\rolling\nulls\mean.rs:52:9:
weights not yet supported on array with null values
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
Traceback (most recent call last):
  File "d.py", line 25, in <module>
    df = df.with_columns([
         ^^^^^^^^^^^^^^^^^
  File "D:\Users\Kan\miniconda3\envs\py311_1\Lib\site-packages\polars\dataframe\frame.py", line 8185, in with_columns
    return self.lazy().with_columns(*exprs, **named_exprs).collect(_eager=True)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Users\Kan\miniconda3\envs\py311_1\Lib\site-packages\polars\lazyframe\frame.py", line 1706, in collect
    return wrap_df(ldf.collect())
                   ^^^^^^^^^^^^^
pyo3_runtime.PanicException: weights not yet supported on array with null values
```

### Expected behavior

return like talib.WMA

### Installed versions

<details>

```
--------Version info---------
Polars:               0.20.2
Index type:           UInt32
Platform:             Windows-10-10.0.22631-SP0
Python:               3.11.3 | packaged by Anaconda, Inc. | (main, Apr 19 2023, 23:46:34) [MSC v.1916 64 bit (AMD64)]

----Optional dependencies----
adbc_driver_manager:  <not installed>
cloudpickle:          <not installed>
connectorx:           <not installed>
deltalake:            <not installed>
fsspec:               <not installed>
gevent:               <not installed>
matplotlib:           3.7.1
numpy:                1.24.3
openpyxl:             3.1.2
pandas:               2.0.1
pyarrow:              12.0.0
pydantic:             1.10.7
pyiceberg:            <not installed>
pyxlsb:               <not installed>
sqlalchemy:           2.0.13
xlsx2csv:             <not installed>
xlsxwriter:           <not installed>
```

</details>

**Comment by ritchie46** [comment]
Yes, even stronger than that. I am considering deprecating weights. They are impossible to effectively implement and hold back other implementations.

In such a case doing a group_by over windows will be almost as performant (save some function) overhead as the dedicated implementation.

**Comment by wukan1986** [comment]
x.fill_null(np.nan).rolling_mean

```python
import numpy as np
import talib
import polars as pl


def ts_decay_linear_pl(x: pl.Expr, d: int = 30) -> pl.Expr:
    weights = pl.arange(1, d + 1, eager=True)
    return x.fill_null(np.nan).rolling_mean(d, weights=weights).fill_nan(None)


def ts_decay_linear_ta(x: pl.Expr, d: int = 30) -> pl.Expr:
    return x.map_batches(lambda x: talib.WMA(x, d))


df = pl.DataFrame({
    'A': range(10),
    'B': [None, None, 2, 3, 4, 5, 6, 7, 8, 9],
    'C': [None, ] * 10,
})

df = df.with_columns([
    ts_decay_linear_ta(pl.col('A'), 5).alias('A_WMA_ta'),
    ts_decay_linear_pl(pl.col('B'), 5).alias('A_WMA_pl'),
    ts_decay_linear_ta(pl.col('B'), 5).alias('B_WMA_ta'),
    #
])

print(df.tail(9))
```


```python
shape: (9, 6)
┌─────┬──────┬──────┬──────────┬──────────┬──────────┐
│ A   ┆ B    ┆ C    ┆ A_WMA_ta ┆ A_WMA_pl ┆ B_WMA_ta │
│ --- ┆ ---  ┆ ---  ┆ ---      ┆ ---      ┆ ---      │
│ i64 ┆ i64  ┆ null ┆ f64      ┆ f64      ┆ f64      │
╞═════╪══════╪══════╪══════════╪══════════╪══════════╡
│ 1   ┆ null ┆ null ┆ NaN      ┆ null     ┆ NaN      │
│ 2   ┆ 2    ┆ null ┆ NaN      ┆ null     ┆ NaN      │
│ 3   ┆ 3    ┆ null ┆ NaN      ┆ null     ┆ NaN      │
│ 4   ┆ 4    ┆ null ┆ 2.666667 ┆ null     ┆ NaN      │
│ 5   ┆ 5    ┆ null ┆ 3.666667 ┆ null     ┆ NaN      │
│ 6   ┆ 6    ┆ null ┆ 4.666667 ┆ 4.666667 ┆ 4.666667 │
│ 7   ┆ 7    ┆ null ┆ 5.666667 ┆ 5.666667 ┆ 5.666667 │
│ 8   ┆ 8    ┆ null ┆ 6.666667 ┆ 6.666667 ┆ 6.666667 │
│ 9   ┆ 9    ┆ null ┆ 7.666667 ┆ 7.666667 ┆ 7.666667 │
└─────┴──────┴──────┴──────────┴──────────┴──────────┘
```
