### ISSUE TITLE
Unable to select more than 4 columns in scan_parquet_files function

### ISSUE THREAD

**Issue by horizondeep** [pola-rs/polars#13162]
### Checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://crates.io/crates/polars) of Polars.

### Reproducible example

```rust
I am trying to read a parquet files '1.parquet' and '2.parquet' contains following fields

upc | store | product_id | region_id | week | sales | units
-- | -- | -- | -- | -- | -- | --
5868--333 | 565656 | abc | 4-444 | 202325 | 153 | 9
5868--333 | 1014 | abc | 4-444 | 202321 | 374 | 1
5868--333 | 1014 | abc | 4-444 | 202319 | 131 | 5
5868--333 | 1014 | abc | 4-444 | 202333 | 387 | 8
5868--333 | 1014 | abc | 4-444 | 202339 | 386 | 4
5868--333 | 1014 | abc | 4-444 | 202334 | 112 | 6
5868--333 | 1014 | abc | 4-444 | 202340 | 274 | 10
5868--333 | 1014 | abc | 4-444 | 202341 | 280 | 1
5868--333 | 1014 | abc | 4-444 | 202324 | 96 | 4
5868--333 | 1014 | abc | 4-444 | 202337 | 255 | 9


let mut paths:Vec<PathBuf> = Vec::new();
mpath="/master/"
s=["1","2"]

for &s in store.iter(){
        let p = format!("{}{}{}{}","azure:/",mpath,&s,".parquet");
        //let p = r"azure:/"+mpath+&s+".parquet";
        let p1 = PathBuf::from(p);
        paths.push(p1);
    }
    let df = LazyFrame::scan_parquet_files(paths.into(),args).unwrap().with_streaming(true).select( [cols(["upc","store","product_id","region_id","week","sales","units"])]).collect().unwrap();;

Whenever I am trying to select more than 4 columns in scan_parquet_files it gives the error

```

### Log output

```shell
assertion failed: requested_budget <= *initial_budget
   0: std::panicking::begin_panic_handler
             at /rustc/1c05d50c8403c56d9a8b6fb871f15aaa26fb5d07/library\std\src\panicking.rs:597
   1: core::panicking::panic_fmt
             at /rustc/1c05d50c8403c56d9a8b6fb871f15aaa26fb5d07/library\core\src\panicking.rs:72
   2: core::panicking::panic
             at /rustc/1c05d50c8403c56d9a8b6fb871f15aaa26fb5d07/library\core\src\panicking.rs:127
   3: polars_io::pl_async::with_concurrency_budget::async_fn$0<polars_io::parquet::async_impl::impl$0::get_ranges::async_fn$0::closure_env$0,enum2$<polars_io::parquet::async_impl::impl$0::get_ranges::async_fn$0::closure$0::async_block_env$0> >
```

### Issue description

When trying to select more than 4 columns in scan_parquet_files, it throws an error.

### Expected behavior

scan_parquet_files should allow to select any number of columns.

### Installed versions

<details>

polars = { version = "0.35.4", features = ["parquet","azure","serde", "json", "lazy", "pivot", "rank", "log","lazy_regex","horizontal_concat","polars-lazy","dtype-struct","dtype-array","concat_str","is_in","polars-io","strings","cum_agg","cloud","streaming","dtype-full"] }
serde_json = { version = "1.0", default-features = false, features = ["alloc"] }
polars-ops = "0.35.4"
postgres = {version="0.19.5",features = ["with-chrono-0_4"]}
tokio-postgres = "0.7.8"
postgres_query = "0.3.3"
tokio = {version= "1.29.1", features = ["full"] }
</details>

**Comment by horizondeep** [comment]
@ritchie46 Even the dropping/excluding columns not working with scan_parquet_files. See the code below                                                                
 
**let df = LazyFrame::scan_parquet_files(paths.into(),args).unwrap().with_streaming(false).drop_columns(["store_id"]);**

is not working as it is selecting multiple columns(I guess more than 4). Same goes for exclude command as well:

**let df = LazyFrame::scan_parquet_files(paths.into(),args).unwrap().with_streaming(false).select(&[col("*").exclude(vec!["store_id"])]);**

**Error:**
thread '<unnamed>' panicked at C:\Users\arathore\.cargo\registry\src\index.crates.io-6f17d22bba15001f\polars-io-0.35.4\src\parquet\mmap.rs:53:17:
mmap_columns: column with start 42948 must be prefetched in ColumnStore.

**Comment by PacoDu** [comment]
I have the same issue (same polars version) using scan_parquet on a multi part S3 file and when I try to select more than 5 columns. The issue occurs in my deployed container but I can't reproduce it issue locally.

**Comment by PacoDu** [comment]
It looks like https://github.com/pola-rs/polars/pull/13026 fixed the issue on my side, compiling with the latest git version fixed the issue

**Comment by horizondeep** [comment]
> It looks like #13026 fixed the issue on my side, compiling with the latest git version fixed the issue

Thanks @PacoDu . I will compile with the above commit and check. I hope this get released in the next version of polars-rust :)
