### ISSUE TITLE
Converting DataFrame containing 

### ISSUE THREAD

**Issue by naanselmo** [pola-rs/polars#13207]
### Checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pypi.org/project/polars/) of Polars.

### Reproducible example

```python
import pandas as pd
import polars as pl

df = pd.DataFrame({"a": [{}]})
boom = pl.from_pandas(df)
```

### Log output

```shell
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File ".../lib/python3.10/site-packages/polars/convert.py", line 723, in from_pandas
    return pl.DataFrame._from_pandas(
  File ".../lib/python3.10/site-packages/polars/dataframe/frame.py", line 656, in _from_pandas
    pandas_to_pydf(
  File ".../lib/python3.10/site-packages/polars/utils/_construction.py", line 1751, in pandas_to_pydf
    return arrow_to_pydf(
  File ".../lib/python3.10/site-packages/polars/utils/_construction.py", line 1563, in arrow_to_pydf
    pydf = PyDataFrame.from_arrow_record_batches(tbl.to_batches())
polars.exceptions.ComputeError: a StructArray must contain at least one field
```
```


### Issue description

Attempting to convert a Pandas DataFrame that contains an empty dictionary throws an exception on StructArray.

This error is very similar to the one on https://github.com/pola-rs/polars/issues/10234, it happens when reading essentially the same data but from JSON instead.

### Expected behavior

That it would be properly converted.

### Installed versions

<details>

```
--------Version info---------
Polars:               0.20.2
Index type:           UInt32
Platform:             Linux-6.5.6-76060506-generic-x86_64-with-glibc2.35
Python:               3.10.13 | packaged by conda-forge | (main, Oct 26 2023, 18:07:37) [GCC 12.3.0]

----Optional dependencies----
adbc_driver_manager:  <not installed>
cloudpickle:          3.0.0
connectorx:           <not installed>
deltalake:            <not installed>
fsspec:               2023.12.2
gevent:               23.9.1
matplotlib:           <not installed>
numpy:                1.23.5
openpyxl:             <not installed>
pandas:               1.5.3
pyarrow:              10.0.1
pydantic:             1.10.13
pyiceberg:            <not installed>
pyxlsb:               <not installed>
sqlalchemy:           2.0.23
xlsx2csv:             <not installed>
xlsxwriter:           <not installed>
```

</details>

**Comment by ritchie46** [comment]
This is not supported. You must have data in your dictionaries. As the error says.

**Comment by naanselmo** [comment]
Would it be desired if it instead behaved as if the empty dictionaries were a None? Or do you think it would be inconsistent behavior?

Based on this PR (https://github.com/pola-rs/polars/pull/6039) I incorrectly assumed that would be the behavior.
