### ISSUE TITLE
is_in operator on Categoricals is overly restrictive

### ISSUE THREAD

**Issue by c-peters** [pola-rs/polars#13201]
### Checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pypi.org/project/polars/) of Polars.

### Reproducible example

Inspired by #13165, the `is_in` operator is overly restrictive on Categorical types

The following codes errors

```python
import polars as pl
s = pl.Series(["a","b"],dtype=pl.Categorical)
s.is_in(["b"])
```

also the following code breaks as well

```python
import polars as pl
s = pl.Series(["a","b"],dtype=pl.Categorical)
s2 = pl.Series(["b"],dtype=pl.Categorical)
s.is_in(s2)
```

### Log output

```shell
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/chiel/.local/lib/python3.10/site-packages/polars/series/utils.py", line 100, in wrapper
    return s.to_frame().select_seq(f(*args, **kwargs)).to_series()
  File "/home/chiel/.local/lib/python3.10/site-packages/polars/dataframe/frame.py", line 8034, in select_seq
    return self.lazy().select_seq(*exprs, **named_exprs).collect(_eager=True)
  File "/home/chiel/.local/lib/python3.10/site-packages/polars/lazyframe/frame.py", line 1706, in collect
    return wrap_df(ldf.collect())
polars.exceptions.StringCacheMismatchError: cannot compare categoricals coming from different sources, consider setting a global StringCache.

Help: if you're using Python, this may look something like:

    with pl.StringCache():
        # Initialize Categoricals.
        df1 = pl.DataFrame({'a': ['1', '2']}, schema={'a': pl.Categorical})
        df2 = pl.DataFrame({'a': ['1', '3']}, schema={'a': pl.Categorical})
    # Your operations go here.
    pl.concat([df1, df2])

Alternatively, if the performance cost is acceptable, you could just set:

    import polars as pl
    pl.enable_string_cache()

on startup.

polars.exceptions.StringCacheMismatchError: cannot compare categoricals coming from different sources, consider setting a global StringCache.

Help: if you're using Python, this may look something like:

    with pl.StringCache():
        # Initialize Categoricals.
        df1 = pl.DataFrame({'a': ['1', '2']}, schema={'a': pl.Categorical})
        df2 = pl.DataFrame({'a': ['1', '3']}, schema={'a': pl.Categorical})
    # Your operations go here.
    pl.concat([df1, df2])

Alternatively, if the performance cost is acceptable, you could just set:

    import polars as pl
    pl.enable_string_cache()

on startup.
```

### Issue description

-

### Expected behavior

Should be able to handle strings and categorical types with a different mapping

### Installed versions

<details>

```
--------Version info---------
Polars:               0.20.2
Index type:           UInt32
Platform:             Linux-6.2.0-39-generic-x86_64-with-glibc2.35
Python:               3.10.12 (main, Nov 20 2023, 15:14:05) [GCC 11.4.0]

----Optional dependencies----
adbc_driver_manager:  0.7.0
cloudpickle:          2.2.1
connectorx:           0.3.2
deltalake:            0.11.0
fsspec:               2023.9.2
gevent:               <not installed>
matplotlib:           3.7.2
numpy:                1.24.4
openpyxl:             <not installed>
pandas:               2.0.3
pyarrow:              12.0.0
pydantic:             2.4.2
pyiceberg:            <not installed>
pyxlsb:               <not installed>
sqlalchemy:           2.0.21
xlsx2csv:             0.8.1
xlsxwriter:           3.1.6

```

</details>

**Comment by mcrumiller** [comment]
Was this actually fixed? I'm on 0.20.3 and still getting issues:
 
```python
import polars as pl
from polars import col

s = pl.Series(["a", "b"], dtype = pl.Categorical)

# series checks
s.is_in(["a"])        # returns False for all items
s.is_in(pl.lit("a"))  # returns False for all items

# expr checks
df = pl.DataFrame({
    "s": s,
    "a": ["a", "a"],
})
# shape: (2, 2)
# ┌─────┬─────┐
# │ s   ┆ a   │
# │ --- ┆ --- │
# │ cat ┆ str │
# ╞═════╪═════╡
# │ a   ┆ a   │
# │ b   ┆ a   │
# └─────┴─────┘
df.select(col("s").is_in("a"))          # returns False for all items
df.select(col("s").is_in(pl.lit("a")))  # returns False for all items
df.select(col("s").is_in(pl.lit("a", dtype=pl.Categorical)))  # returns True, False (correct)
```
