### ISSUE TITLE
Allow expanding and renaming multiple columns

### ISSUE THREAD

**Issue by Wainberg** [pola-rs/polars#13225]
### Description

This isn't allowed, but there doesn't seem to be any fundamental reason why it shouldn't be:

```python
>>> pl.DataFrame({'A1': [1], 'A2': [2], 'B1': [3], 'B2': [4]}).select(pl.col('A1', 'B1') - pl.col('A2', 'B2'))
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/wainberg/miniforge3/lib/python3.12/site-packages/polars/dataframe/frame.py", line 8009, in select

  File "/home/wainberg/miniforge3/lib/python3.12/site-packages/polars/lazyframe/frame.py", line 1706, in collect
    return wrap_df(ldf.collect())
                   ^^^^^^^^^^^^^
polars.exceptions.ComputeError: expanding more than one `col` is not allowed

Error originated just after this operation:
DF ["A1", "A2", "B1", "B2"]; PROJECT */4 COLUMNS; SELECTION: "None"
```

Similarly, shouldn't `Expr.alias()` allow renaming multiple columns at once, without having to resort to `.name.map()`?

**Comment by Wainberg** [comment]
@ritchie46 I saw you wrote a comment that:

https://github.com/pola-rs/polars/blob/837ff46d2fb7435f3110e15b025af985bb5b6c8a/py-polars/tests/unit/test_errors.py#L412

Any plans to implement?

**Comment by ritchie46** [comment]
I am kind of busy. ^^ maybe later.

**Comment by cmdlineluser** [comment]
The new struct expansion can sort of emulate it:

```python
df.with_columns(
    (pl.struct('A1', 'B1') - pl.struct('A2', 'B2'))
       .struct.field('*')
)

# shape: (1, 4)
# ┌─────┬─────┬─────┬─────┐
# │ A1  ┆ A2  ┆ B1  ┆ B2  │
# │ --- ┆ --- ┆ --- ┆ --- │
# │ i64 ┆ i64 ┆ i64 ┆ i64 │
# ╞═════╪═════╪═════╪═════╡
# │ -1  ┆ 2   ┆ -1  ┆ 4   │
# └─────┴─────┴─────┴─────┘
 ```

```python
df.with_columns(
    (pl.struct('A1', 'B1') - pl.struct('A2', 'B2'))
       .struct.rename_fields(['C1', 'C2'])
       .struct.field('*')
)

# shape: (1, 6)
# ┌─────┬─────┬─────┬─────┬─────┬─────┐
# │ A1  ┆ A2  ┆ B1  ┆ B2  ┆ C1  ┆ C2  │
# │ --- ┆ --- ┆ --- ┆ --- ┆ --- ┆ --- │
# │ i64 ┆ i64 ┆ i64 ┆ i64 ┆ i64 ┆ i64 │
# ╞═════╪═════╪═════╪═════╪═════╪═════╡
# │ 1   ┆ 2   ┆ 3   ┆ 4   ┆ -1  ┆ -1  │
# └─────┴─────┴─────┴─────┴─────┴─────┘
```

Still some boilerplate, but may be useful.

**Comment by coastalwhite** [comment]
This is fixed as part of #23351.
