### ISSUE TITLE
Support expressions and selectors in `exclude`

### ISSUE THREAD

**Issue by Wainberg** [pola-rs/polars#13247]
### Description

`pl.exclude` and `Expr.exclude` do not currently support expressions or selectors. 

For example, you cannot do `pl.exclude(pl.first())` to exclude the first column:

```python
>>> pl.DataFrame({'a': [1], 'b': [2]}).with_columns(pl.exclude(pl.first()) + 1)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/wainberg/miniforge3/lib/python3.12/site-packages/polars/functions/lazy.py", line 1268, in exclude
    return F.col("*").exclude(columns, *more_columns)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/wainberg/miniforge3/lib/python3.12/site-packages/polars/expr/expr.py", line 934, in exclude
    raise TypeError(
TypeError: invalid input for `exclude`

Expected one or more `str`, `DataType`, or selector; found 'Expr' instead.
```

Nor can you do `pl.exclude(pl.selectors.first())`:

```python
>>> pl.DataFrame({'a': [1], 'b': [2]}).with_columns(pl.exclude(pl.selectors.first()) + 1)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/wainberg/miniforge3/lib/python3.12/site-packages/polars/functions/lazy.py", line 1268, in exclude
    return F.col("*").exclude(columns, *more_columns)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/wainberg/miniforge3/lib/python3.12/site-packages/polars/expr/expr.py", line 934, in exclude
    raise TypeError(
TypeError: invalid input for `exclude`

Expected one or more `str`, `DataType`, or selector; found '_selector_proxy_' instead.
```

This seems quite useful to support!

**Comment by alexander-beedie** [comment]
Got selector support working locally; will push to out later, in between bites of Christmas cake, board games, etc 🤣

**Comment by alexander-beedie** [comment]
FYI: note that `pl.exclude(pl.first())` would be better written as a `~cs.first()` selector  ;)
