### ISSUE TITLE
Support returning Arrays/Structs from map_elements

### ISSUE THREAD

**Issue by Wainberg** [pola-rs/polars#13276]
### Description

Currently, when you give `map_elements` that returns multiple things, it gives a list column:

```python
>>> pl.DataFrame({'a': [[1]]}).select(pl.col.a.map_elements(lambda x: x + 1))
 a
 [2]
shape: (1, 1)
>>> pl.DataFrame({'a': [[1]]}).select(pl.col.a.map_elements(lambda x: x + 1)).dtypes
[List(Int64)]
```

Unfortunately, you can't use `return_dtype` to return an `Array`:

```python
>>> pl.DataFrame({'a': [[1]]}).select(pl.col.a.map_elements(lambda x: x + 1, return_dtype=pl.Array(pl.Int64, 1)))
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/wainberg/miniforge3/lib/python3.12/site-packages/polars/dataframe/frame.py", line 8008, in select
    return self.lazy().select(*exprs, **named_exprs).collect(_eager=True)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/wainberg/miniforge3/lib/python3.12/site-packages/polars/lazyframe/frame.py", line 1706, in collect
    return wrap_df(ldf.collect())
                   ^^^^^^^^^^^^^
polars.exceptions.SchemaError: expected output type 'Array(Int64, 1)', got 'List(Int64)'; set `return_dtype` to the proper datatype
```

or `Struct`:

```python
>>> pl.DataFrame({'a': [[1]]}).select(pl.col.a.map_elements(lambda x: x + 1, return_dtype=pl.Struct({'a': pl.Int64})))
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/wainberg/miniforge3/lib/python3.12/site-packages/polars/dataframe/frame.py", line 8008, in select
    return self.lazy().select(*exprs, **named_exprs).collect(_eager=True)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/wainberg/miniforge3/lib/python3.12/site-packages/polars/lazyframe/frame.py", line 1706, in collect
    return wrap_df(ldf.collect())
                   ^^^^^^^^^^^^^
polars.exceptions.SchemaError: expected output type 'Struct([Field { name: "a", dtype: Int64 }])', got 'List(Int64)'; set `return_dtype` to the proper datatype
```

or even change the type of the inner list elements:

```python
>>> pl.DataFrame({'a': [[1]]}).select(pl.col.a.map_elements(lambda x: x + 1, return_dtype=pl.List(pl.Int32)))
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/wainberg/miniforge3/lib/python3.12/site-packages/polars/dataframe/frame.py", line 8008, in select
    return self.lazy().select(*exprs, **named_exprs).collect(_eager=True)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/wainberg/miniforge3/lib/python3.12/site-packages/polars/lazyframe/frame.py", line 1706, in collect
    return wrap_df(ldf.collect())
                   ^^^^^^^^^^^^^
polars.exceptions.SchemaError: expected output type 'List(Int32)', got 'List(Int64)'; set `return_dtype` to the proper datatype
```

Why does this matter? Because often you want to return multiple things from `map_elements`, and make each of them their own column. Currently you have to use `.list.to_struct` followed by `unnest` in this case, which is verbose and also computationally inefficient.

**Comment by howsiyu** [comment]
You can return a struct by returning a dictionary. I don't know of a way to return `pl.Array` though.
