### ISSUE TITLE
Expr.gather raises with negative indices but Expr.list.gather doesn't

### ISSUE THREAD

**Issue by MarcoGorelli** [pola-rs/polars#13328]
### Checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pypi.org/project/polars/) of Polars.

### Reproducible example

```python
import polars as pl

df = pl.DataFrame({'a': [[1,2,3], [4,5,6]]})

df.select(pl.col('a').list.gather([0, -1]))  # works

df.select(pl.col('a').gather([0, -1]))  # raises
```

### Log output

```shell
here's the full traceback:
-traceback
Traceback (most recent call last):
  File "/home/marcogorelli/tmp/t.py", line 7, in <module>
    df.select(pl.col('a').gather([0, -1]))
  File "/home/marcogorelli/tmp/.venv/lib/python3.10/site-packages/polars/expr/expr.py", line 2406, in gather
    indices_lit = F.lit(pl.Series("", indices, dtype=UInt32))._pyexpr
  File "/home/marcogorelli/tmp/.venv/lib/python3.10/site-packages/polars/series/series.py", line 287, in __init__
    self._s = sequence_to_pyseries(
  File "/home/marcogorelli/tmp/.venv/lib/python3.10/site-packages/polars/utils/_construction.py", line 447, in sequence_to_pyseries
    pyseries = _construct_series_with_fallbacks(
  File "/home/marcogorelli/tmp/.venv/lib/python3.10/site-packages/polars/utils/_construction.py", line 355, in _construct_series_with_fallbacks
    return constructor(name, values, strict)
OverflowError: out of range integral type conversion attempted
(.venv) marcogorelli@DESKTOP-U8OKFP3:~/tmp$ POLARS_VERBOSE=1 python t.py
Traceback (most recent call last):
  File "/home/marcogorelli/tmp/t.py", line 7, in <module>
    df.select(pl.col('a').gather([0, -1]))
  File "/home/marcogorelli/tmp/.venv/lib/python3.10/site-packages/polars/expr/expr.py", line 2406, in gather
    indices_lit = F.lit(pl.Series("", indices, dtype=UInt32))._pyexpr
  File "/home/marcogorelli/tmp/.venv/lib/python3.10/site-packages/polars/series/series.py", line 287, in __init__
    self._s = sequence_to_pyseries(
  File "/home/marcogorelli/tmp/.venv/lib/python3.10/site-packages/polars/utils/_construction.py", line 447, in sequence_to_pyseries
    pyseries = _construct_series_with_fallbacks(
  File "/home/marcogorelli/tmp/.venv/lib/python3.10/site-packages/polars/utils/_construction.py", line 355, in _construct_series_with_fallbacks
    return constructor(name, values, strict)
OverflowError: out of range integral type conversion attempted
```

### Issue description

I think these should both work?

### Expected behavior

to get
```python
shape: (2, 1)
┌───────────┐
│ a         │
│ ---       │
│ list[i64] │
╞═══════════╡
│ [1, 2, 3] │
│ [4, 5, 6] │
└───────────┘
```
with the second one

### Installed versions

<details>

```
--------Version info---------
Polars:               0.20.2
Index type:           UInt32
Platform:             Linux-5.15.133.1-microsoft-standard-WSL2-x86_64-with-glibc2.35
Python:               3.10.12 (main, Nov 20 2023, 15:14:05) [GCC 11.4.0]

----Optional dependencies----
adbc_driver_manager:  <not installed>
cloudpickle:          2.2.1
connectorx:           <not installed>
deltalake:            0.9.0
fsspec:               2023.6.0
gevent:               <not installed>
matplotlib:           3.7.1
numpy:                1.26.2
openpyxl:             <not installed>
pandas:               2.3.0.dev0+14.g62dbbe6713
pyarrow:              14.0.1
pydantic:             2.0.2
pyiceberg:            <not installed>
pyxlsb:               <not installed>
sqlalchemy:           2.0.20
xlsx2csv:             <not installed>
xlsxwriter:           <not installed>
```

</details>

**Comment by ritchie46** [comment]
Yes, currently it expects a `u32/u64` (depending on index size). I think we can also support `i64` and then do a conversion pass once the length is known.

**Comment by stinodego** [comment]
This works correctly now.
