### ISSUE TITLE
can write empty parquet but not read

### ISSUE THREAD

**Issue by wukan1986** [pola-rs/polars#13457]
### Checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pypi.org/project/polars/) of Polars.

### Reproducible example

```python
import pandas as pd
import polars as pl

pd.DataFrame().to_parquet('pd.parquet')
pl.DataFrame().write_parquet('pl.parquet')

a1 = pd.read_parquet('pd.parquet')
a2 = pd.read_parquet('pl.parquet')
print(a1)
print(a2)
"""
Empty DataFrame
Columns: []
Index: []
Empty DataFrame
Columns: []
Index: []
"""

b1 = pl.read_parquet('pd.parquet', use_pyarrow=True)
b2 = pl.read_parquet('pl.parquet', use_pyarrow=True)

# polars.exceptions.ComputeError: parquet: File out of specification: Physical type must be defined for a primitive type
c1 = pl.read_parquet('pd.parquet')
# polars.exceptions.ComputeError: parquet: File out of specification: Repetition level must be defined for a primitive type
c2 = pl.read_parquet('pl.parquet')
```

### Log output

```shell
Traceback (most recent call last):
  File "D:\GitHub\my_quant\tests\aaaa.py", line 24, in <module>
    c1 = pl.read_parquet('pd.parquet')
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Users\Kan\miniconda3\envs\py311_1\Lib\site-packages\polars\io\parquet\functions.py", line 163, in read_parquet
    lf = scan_parquet(
         ^^^^^^^^^^^^^
  File "D:\Users\Kan\miniconda3\envs\py311_1\Lib\site-packages\polars\io\parquet\functions.py", line 303, in scan_parquet
    return pl.LazyFrame._scan_parquet(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Users\Kan\miniconda3\envs\py311_1\Lib\site-packages\polars\lazyframe\frame.py", line 458, in _scan_parquet
    self._ldf = PyLazyFrame.new_from_parquet(
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
polars.exceptions.ComputeError: parquet: File out of specification: Physical type must be defined for a primitive type
```

### Issue description

na

### Expected behavior

na

### Installed versions

<details>

```
--------Version info---------
Polars:               0.20.3
Index type:           UInt32
Platform:             Windows-10-10.0.22631-SP0
Python:               3.11.3 | packaged by Anaconda, Inc. | (main, Apr 19 2023, 23:46:34) [MSC v.1916 64 bit (AMD64)]

----Optional dependencies----
adbc_driver_manager:  <not installed>
cloudpickle:          <not installed>
connectorx:           <not installed>
deltalake:            <not installed>
fsspec:               <not installed>
gevent:               <not installed>
hvplot:               0.9.1
matplotlib:           3.7.1
numpy:                1.26.2
openpyxl:             3.1.2
pandas:               2.0.1
pyarrow:              12.0.0
pydantic:             1.10.7
pyiceberg:            <not installed>
pyxlsb:               <not installed>
sqlalchemy:           2.0.13
xlsx2csv:             <not installed>
xlsxwriter:           <not installed>
```

</details>

**Comment by taki-mekhalfa** [comment]
Is not it sensible to keep the behavior as it? Parquet files without a schema? I think write_parquet should error when trying to write schema-less parquets. 

Duckdb fails  to read the file too: `Error: Invalid Error: Failed to read Parquet file "test.parquet": Need at least one non-root column in the file`

**Comment by wukan1986** [comment]
Hi, @taki-mekhalfa 

This problem easily occurs when reading a folder, because the folder contains files generated by other software using pandas and saved daily. There is no data on the new day, but the files are generated.
However, if you read the folder directly here, an error will be reported.

**Comment by adamreeve** [comment]
> Is not it sensible to keep the behavior as it? Parquet files without a schema? I think write_parquet should error when trying to write schema-less parquets.

I disagree, it is completely valid to create an empty Polars DataFrame, so why should it not be possible to round-trip this via Parquet too? I would also not describe such a file as schema-less, there is a schema and it has zero columns.

As a counter-example to DuckDB, PyArrow can read and write Parquet files with zero columns without any problem.

**Comment by corwinjoy** [comment]
I have started working on this. This has also been reported as part of (https://github.com/pola-rs/polars/issues/9016) where @gregates gave some Rust code for reproducing this directly.

**Comment by corwinjoy** [comment]
@adamreeve @wukan1986 
I have put in a PR to fix this issue. The fix was straightforward, but I am new to this project and am hoping to get help with the associated unit tests.
