### ISSUE TITLE
Treat dataclasses returned by `map_elements()` functions as structs

### ISSUE THREAD

**Issue by kalekundert** [pola-rs/polars#13469]
### Checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pypi.org/project/polars/) of Polars.

### Reproducible example

```python
import polars as pl
from dataclasses import dataclass

@dataclass
class Struct:
    a: int
    b: int

x = pl.Series([1, 2, 3]).map_elements(lambda x: Struct(x, x+1))

print(x.dtype)
print(x)
```

### Log output

```shell
Object
thread '<unnamed>' panicked at crates/polars-core/src/fmt.rs:366:19:
Object("object", Some(object-registry)) not impl
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
Traceback (most recent call last):
  File "/home/kale/map_dataclass.py", line 12, in <module>
    print(x)
  File "/home/kale/.pyenv/versions/3.10.0/lib/python3.10/site-packages/polars/series/series.py", line 575, in __str__
    s_repr: str = self._s.as_str()
pyo3_runtime.PanicException: Object("object", Some(object-registry)) not impl
```

### Issue description

There might be two issues here.  The first is that dataclasses are treated as objects when returned by `map_elements()` functions, while in other contexts (e.g. arguments to `Dataframe`/`Series` constructors) they are treated as structs.  It seems to me that dataclasses should be treated as structs everywhere.

The second issue is that a panic/exception is generated when trying to print the object-type series.  This appears to be a regression from version 0.19.19.

It might be relevant that I'm using the `polars-lts-cpu` package.

### Expected behavior

```
shape: (3,)
Series: '' [struct[2]]
[
	{1,2}
	{2,3}
	{3,4}
]
```
Note that the following snippets both produce the expected result:
- Return dict rather than dataclass:
  ```py
  pl.Series([1, 2, 3]).map_elements(lambda x: {'a': x, 'b': x+1})
  ```
- Provide dataclasses to `Series` constructor:
  ```py
  pl.Series([
      Struct(1, 2),
      Struct(2, 3),
      Struct(3, 4),
  ])
  ```

### Installed versions

<details>

```
--------Version info---------
Polars:               0.20.3
Index type:           UInt32
Platform:             Linux-6.6.4-arch1-1-x86_64-with-glibc2.38
Python:               3.10.0 (default, Oct 20 2021, 17:23:57) [Clang 12.0.1 ]

----Optional dependencies----
adbc_driver_manager:  <not installed>
cloudpickle:          2.2.1
connectorx:           <not installed>
deltalake:            <not installed>
fsspec:               2022.11.0
gevent:               <not installed>
hvplot:               <not installed>
matplotlib:           3.7.1
numpy:                1.24.4
openpyxl:             3.0.9
pandas:               2.0.3
pyarrow:              10.0.0
pydantic:             2.5.2
pyiceberg:            <not installed>
pyxlsb:               <not installed>
sqlalchemy:           1.4.31
xlsx2csv:             0.8
xlsxwriter:           <not installed>
```

</details>

**Comment by stinodego** [comment]
I think it would be reasonable to interpret dataclasses as Structs in this context. I wouldn't call the current behavior a bug though, so I've rebranded this as a feature request.

This is probably not easy to support elegantly, but I would be interested to see a PR for this.

For now, you can call [`asdict`](https://docs.python.org/3/library/dataclasses.html#dataclasses.asdict) on your dataclass, e.g. `lambda x: asdict(Struct(x, x + 1))`
