### ISSUE TITLE
Left join crashes when missng object type column has missing values

### ISSUE THREAD

**Issue by barak1412** [pola-rs/polars#13512]
### Checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pypi.org/project/polars/) of Polars.

### Reproducible example

```python
import polars as pl
import scipy.sparse as sp
from functools import reduce
import os

os.environ['RUST_BACKTRACE'] = 'full'


df = pl.DataFrame({
    'id': [0, 1, 2, 3, 4, 5]
})

df1 = pl.DataFrame({
    'id': [0, 2, 4, 5],
    'sparse_feature': [sp.csr_matrix(([1.0, 5.0], ([0, 0], [1, 3])), shape=(1, 5)),
                       sp.csr_matrix(([8.0, 4.0], ([0, 0], [0, 4])), shape=(1, 5)),
                       sp.csr_matrix(([2.5], ([0], [3])), shape=(1, 5)),
                       sp.csr_matrix(([4.3, 1.0, 5.0], ([0, 0, 0], [0, 2, 4])), shape=(1, 5))]
})

df2 = pl.DataFrame({
    'id': [0, 1, 5],
    'dense_feature': [[0, 5, 5], [6, 9, 3], [7, 1, 5]]
})

df3 = pl.DataFrame({
    'id': [2, 5],
    'numeric_feature': [9.8, 1.4]
})

print(df.join(df1, how='left', on='id'))
```

### Log output

```shell
thread '<unnamed>' panicked at crates\polars-core\src\fmt.rs:621:57:
called `Result::unwrap()` on an `Err` value: ComputeError(ErrString("index is out of bounds"))
stack backtrace:
   0:     0x7ffd152d7677 - ffi_select_with_compiled_path
   1:     0x7ffd1291577d - BrotliDecoderVersion
   2:     0x7ffd152babf1 - ffi_select_with_compiled_path
   3:     0x7ffd152d9a3a - ffi_select_with_compiled_path
   4:     0x7ffd152d90e9 - ffi_select_with_compiled_path
   5:     0x7ffd152da148 - ffi_select_with_compiled_path
   6:     0x7ffd152d9c59 - ffi_select_with_compiled_path
   7:     0x7ffd152d9b99 - ffi_select_with_compiled_path
   8:     0x7ffd152d9b82 - ffi_select_with_compiled_path
   9:     0x7ffd15402bb7 - ffi_select_with_compiled_path
  10:     0x7ffd154031b3 - ffi_select_with_compiled_path
  11:     0x7ffd1364bfbe - ffi_select_with_compiled_path
  12:     0x7ffd1291577d - BrotliDecoderVersion
  13:     0x7ffd12802b9a - BroccoliDestroyInstance
  14:     0x7ffd125d1136 - <unknown>
  15:     0x7ffd11f0aeab - <unknown>
  16:     0x7ffd46ce6726 - PyList_New
  17:     0x7ffd46d24240 - Py_CheckFunctionResult
  18:     0x7ffd46d25f82 - PyEval_EvalFrameDefault
  19:     0x7ffd46d2323d - PyFunction_Vectorcall
  20:     0x7ffd46ce9b7b - PySequence_GetItem
  21:     0x7ffd46d0f2a7 - PyObject_Str
  22:     0x7ffd46d4bd92 - PyFile_WriteObject
  23:     0x7ffd46d4bc59 - PyFile_WriteString
  24:     0x7ffd46ceb2f9 - PyArg_UnpackStack
  25:     0x7ffd46d24240 - Py_CheckFunctionResult
  26:     0x7ffd46d25def - PyEval_EvalFrameDefault
  27:     0x7ffd46d217c8 - PyEval_EvalCodeWithName
  28:     0x7ffd46d6fbe7 - PyEval_EvalCodeEx
  29:     0x7ffd46d6fb45 - PyEval_EvalCode
  30:     0x7ffd46d6ef76 - PyArena_New
  31:     0x7ffd46d6ef05 - PyArena_New
  32:     0x7ffd46df09e4 - PyRun_FileExFlags
  33:     0x7ffd46df0787 - PyRun_SimpleFileExFlags
  34:     0x7ffd46eb228b - PyRun_AnyFileExFlags
  35:     0x7ffd46e440a5 - Py_FatalError
  36:     0x7ffd46d95ae4 - Py_RunMain
  37:     0x7ffd46d9596d - Py_RunMain
  38:     0x7ffd46d949dd - Py_Main
  39:     0x7ff6035e1258 - <unknown>
  40:     0x7ffdbb367344 - BaseThreadInitThunk
  41:     0x7ffdbbc226b1 - RtlUserThreadStart
Traceback (most recent call last):
  File "C:/Users/Barak/PycharmProjects/flowit_benchmark/imputing.py", line 31, in <module>
    print(df.join(df1, how='left', on='id'))
  File "C:\Users\Barak\AppData\Local\Programs\Python\Python38\lib\site-packages\polars\dataframe\frame.py", line 1579, in __str__
    return self._df.as_str()
pyo3_runtime.PanicException: called `Result::unwrap()` on an `Err` value: ComputeError(ErrString("index is out of bounds"))
```

### Issue description

Apparently, while using left join, when the right dataframe has missing keys and contains object type columns, it leads to exception in the rust level.

### Expected behavior

It should return new dataframe with null values in the missing keys.
For example, with the above code and the following command:
`print(df.join(df2, how='left', on='id'))`

Should yield:

```
┌─────┬───────────────┐
│ id  ┆ dense_feature │
│ --- ┆ ---           │
│ i64 ┆ list[i64]     │
╞═════╪═══════════════╡
│ 0   ┆ [0, 5, 5]     │
│ 1   ┆ [6, 9, 3]     │
│ 2   ┆ null          │
│ 3   ┆ null          │
│ 4   ┆ null          │
│ 5   ┆ [7, 1, 5]     │
└─────┴───────────────┘

```

### Installed versions

<details>

```
--------Version info---------
Polars:               0.20.3
Index type:           UInt32
Platform:             Windows-10-10.0.19041-SP0
Python:               3.8.1 (tags/v3.8.1:1b293b6, Dec 18 2019, 23:11:46) [MSC v.1916 64 bit (AMD64)]

----Optional dependencies----
adbc_driver_manager:  <not installed>
cloudpickle:          2.2.0
connectorx:           0.3.3a1
deltalake:            <not installed>
fsspec:               2023.10.0
gevent:               <not installed>
hvplot:               <not installed>
matplotlib:           3.5.1
numpy:                1.24.4
openpyxl:             <not installed>
pandas:               2.0.3
pyarrow:              13.0.0
pydantic:             1.8.2
pyiceberg:            <not installed>
pyxlsb:               <not installed>
sqlalchemy:           1.4.32
xlsx2csv:             <not installed>
xlsxwriter:           <not installed>
```

</details>

**Comment by mcrumiller** [comment]
Can reproduce, here's a much more minimal example with no extra reqs:

```python
import polars as pl

df1 = pl.DataFrame({
    "key": [1],
})
df2 = pl.DataFrame({
    "key": [2],
    "a": pl.Series([1], dtype=pl.Object)
})
df1.join(df2, on="key", how="left")
```

This only appears to occur on left joins, not outer joins: if the key is missing from the *left* frame, we get the error; if it's missing from the *right* frame, we get a proper join:

```python
import polars as pl

df1 = pl.DataFrame({
    "key": [1],
})
df2 = pl.DataFrame({
    "key": [1, 2],
    "a": pl.Series([1, 2], dtype=pl.Object)
})
print(df1.join(df2, on="key", how="outer"))
```
```
shape: (2, 3)
┌──────┬───────────┬────────┐
│ key  ┆ key_right ┆ a      │
│ ---  ┆ ---       ┆ ---    │
│ i64  ┆ i64       ┆ object │
╞══════╪═══════════╪════════╡
│ 1    ┆ 1         ┆ 1      │
│ null ┆ 2         ┆ 2      │
└──────┴───────────┴────────┘
```

**Comment by mcrumiller** [comment]
Ok, the join works fine in either case, the issue is that the frame in the error case cannot be properly printed.
