### ISSUE TITLE
Panic when using `duration` with `LazyFrame` created from `LazyCsvReader`

### ISSUE THREAD

**Issue by rben01** [pola-rs/polars#13543]
### Checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://crates.io/crates/polars) of Polars.

### Reproducible example

`main.rs`:
```rust
use polars::prelude::*;

fn is_distant_past(date_col: Expr, days_past: u32) -> Expr {
    let date = date_col.str().strptime(
        DataType::Date,
        StrptimeOptions {
            format: Some("%Y-%m-%d".into()),
            strict: true,
            exact: false,
            cache: true,
        },
        lit("raise"),
    );
    let offset = duration(DurationArgs {
        days: lit(days_past),
        ..Default::default()
    });
    let today = lit(chrono::offset::Utc::now().naive_local().date());

    (date + offset).lt_eq(today)
}

fn main() -> Result<(), Box<dyn std::error::Error>> {
    let df = LazyCsvReader::new("./test.csv")
        .finish()?
        .filter(is_distant_past(col("date"), 5));

    println!("{:?}", df.collect()?);

    Ok(())
}
```

`test.csv`:
```csv
date
2024-01-01
2024-01-05
2024-01-10
```

### Log output

```shell
thread 'main' panicked at /Users/rben01/.cargo/registry/src/index.crates.io-6f17d22bba15001f/polars-plan-0.36.2/src/dsl/expr.rs:232:21:
not yet implemented: IMPLEMENT
stack backtrace:
   0: rust_begin_unwind
             at /rustc/82e1608dfa6e0b5569232559e3d385fea5a93112/library/std/src/panicking.rs:645:5
   1: core::panicking::panic_fmt
             at /rustc/82e1608dfa6e0b5569232559e3d385fea5a93112/library/core/src/panicking.rs:72:14
   2: <polars_plan::dsl::expr::Expr as core::hash::Hash>::hash
             at /Users/rben01/.cargo/registry/src/index.crates.io-6f17d22bba15001f/polars-plan-0.36.2/src/dsl/expr.rs:232:21
   3: <alloc::boxed::Box<T,A> as core::hash::Hash>::hash
             at /rustc/82e1608dfa6e0b5569232559e3d385fea5a93112/library/alloc/src/boxed.rs:1382:9
   4: <polars_plan::dsl::expr::Expr as core::hash::Hash>::hash
             at /Users/rben01/.cargo/registry/src/index.crates.io-6f17d22bba15001f/polars-plan-0.36.2/src/dsl/expr.rs:203:17
   5: <alloc::boxed::Box<T,A> as core::hash::Hash>::hash
             at /rustc/82e1608dfa6e0b5569232559e3d385fea5a93112/library/alloc/src/boxed.rs:1382:9
   6: <polars_plan::dsl::expr::Expr as core::hash::Hash>::hash
             at /Users/rben01/.cargo/registry/src/index.crates.io-6f17d22bba15001f/polars-plan-0.36.2/src/dsl/expr.rs:186:17
   7: <alloc::boxed::Box<T,A> as core::hash::Hash>::hash
             at /rustc/82e1608dfa6e0b5569232559e3d385fea5a93112/library/alloc/src/boxed.rs:1382:9
   8: <polars_plan::dsl::expr::Expr as core::hash::Hash>::hash
             at /Users/rben01/.cargo/registry/src/index.crates.io-6f17d22bba15001f/polars-plan-0.36.2/src/dsl/expr.rs:185:17
   9: <core::option::Option<T> as core::hash::Hash>::hash
             at /rustc/82e1608dfa6e0b5569232559e3d385fea5a93112/library/core/src/option.rs:577:56
  10: <polars_plan::logical_plan::optimizer::file_caching::FileFingerPrint as core::hash::Hash>::hash
             at /Users/rben01/.cargo/registry/src/index.crates.io-6f17d22bba15001f/polars-plan-0.36.2/src/logical_plan/optimizer/file_caching.rs:13:5
  11: hashbrown::map::make_hash
             at /Users/rben01/.cargo/registry/src/index.crates.io-6f17d22bba15001f/hashbrown-0.14.1/src/map.rs:249:5
  12: hashbrown::map::HashMap<K,V,S,A>::entry
             at /Users/rben01/.cargo/registry/src/index.crates.io-6f17d22bba15001f/hashbrown-0.14.1/src/map.rs:1228:20
  13: polars_plan::logical_plan::optimizer::file_caching::process_with_columns
             at /Users/rben01/.cargo/registry/src/index.crates.io-6f17d22bba15001f/polars-plan-0.36.2/src/logical_plan/optimizer/file_caching.rs:26:16
  14: polars_plan::logical_plan::optimizer::file_caching::find_column_union_and_fingerprints
             at /Users/rben01/.cargo/registry/src/index.crates.io-6f17d22bba15001f/polars-plan-0.36.2/src/logical_plan/optimizer/file_caching.rs:108:13
  15: polars_plan::logical_plan::optimizer::optimize
             at /Users/rben01/.cargo/registry/src/index.crates.io-6f17d22bba15001f/polars-plan-0.36.2/src/logical_plan/optimizer/mod.rs:195:9
  16: polars_lazy::frame::LazyFrame::optimize_with_scratch
             at /Users/rben01/.cargo/registry/src/index.crates.io-6f17d22bba15001f/polars-lazy-0.36.2/src/frame/mod.rs:567:22
  17: polars_lazy::frame::LazyFrame::prepare_collect
             at /Users/rben01/.cargo/registry/src/index.crates.io-6f17d22bba15001f/polars-lazy-0.36.2/src/frame/mod.rs:610:13
  18: polars_lazy::frame::LazyFrame::collect
             at /Users/rben01/.cargo/registry/src/index.crates.io-6f17d22bba15001f/polars-lazy-0.36.2/src/frame/mod.rs:667:49
  19: scratchpad::main
             at ./src/main.rs:28:22
  20: core::ops::function::FnOnce::call_once
             at /rustc/82e1608dfa6e0b5569232559e3d385fea5a93112/library/core/src/ops/function.rs:250:5
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```

### Issue description

Clearly this has to do with `impl Hash for Expr`. A branch that should not be reached (in debug mode, anyway) is in fact reached.

https://github.com/pola-rs/polars/blob/67507fffbff54679a4ff0e11f602b41e3ad6b99f/crates/polars-plan/src/dsl/expr.rs#L169

https://github.com/pola-rs/polars/blob/67507fffbff54679a4ff0e11f602b41e3ad6b99f/crates/polars-plan/src/dsl/expr.rs#L228-L233

When replacing the `todo!()` line above with `todo!("IMPLEMENT {self:?}")`, what is printed is `not yet implemented: IMPLEMENT 0.duration([5, 0, 0, 0, 0, 0, 0])`. I believe this means that the `expr` that was hashed was the `Function` created from `duration(DurationArgs { days: lit(5), ..Default::default() })`.

https://github.com/pola-rs/polars/blob/67507fffbff54679a4ff0e11f602b41e3ad6b99f/crates/polars-plan/src/logical_plan/format.rs#L360-L368

If I replace the `LazyCsvReader` with a regular `CsvReader` or an in-memory DataFrame created with `df!` (followed by `.lazy()` before the `filter`), this issue goes away. So I feel pretty confident in saying that it's somehow related to `LazyCsvReader` leading to a `Expr::Function` being hashed.

### Expected behavior

No panic. The results from above would be:

```rust
shape: (1, 1)
┌────────────┐
│ date       │
│ ---        │
│ str        │
╞════════════╡
│ 2024-01-01 │
└────────────┘
```

### Installed versions

Polars:
```toml
polars = { version = "0.36.2", features = [
	"csv",
	"lazy",
	"strings",
	"temporal",
] }
```

Rust:
```sh
$ rustc --version
rustc 1.75.0 (82e1608df 2023-12-21)
```

**Comment by ritchie46** [comment]
Interested in making a PR for this one?

**Comment by rben01** [comment]
Aside from removing that `todo!()' is there anything else that should happen? Is there supposed to be a better implementation for the wildcard branch than stringification?

**Comment by rben01** [comment]
Is it correct that that PR solves this issue specifically for `duration` but not for other anonymous functions?
