### ISSUE TITLE
Strings corrupted during streaming multi-column descending sort

### ISSUE THREAD

**Issue by jamiemortimore** [pola-rs/polars#13573]
### Checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pypi.org/project/polars/) of Polars.

### Reproducible example

```python
import polars as pl

tdf=pl.DataFrame({"a":["one","two","three","one","two","three"],"b":["four","five","six","six","five","four"],"c":[1,2,3,4,5,6]}).lazy()
print(tdf.sort("a","b",descending=[False,True]).collect(streaming=True))
```

### Log output

```shell
RUN STREAMING PIPELINE
df -> sort_multiple -> ordered_sink
RefCell { value: [] }
thread '<unnamed>' panicked at crates/polars-core/src/fmt.rs:384:21:
byte index 38 is out of bounds of `���`
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x8c in position 35: invalid start byte
thread '<unnamed>' panicked at /root/.cargo/registry/src/index.crates.io-6f17d22bba15001f/pyo3-0.20.1/src/err/mod.rs:788:5:
Python API call failed
fatal runtime error: failed to initiate panic, error 5
Aborted (core dumped)
```

### Issue description

During a multi-column sort of string columns where one or more columns are descending, the string value of the columns are corrupted.

### Expected behavior

Sort should work as expected.

### Installed versions

<details>

```
--------Version info---------
Polars:               0.20.3
Index type:           UInt32
Platform:             Linux-6.4.6-76060406-generic-x86_64-with-glibc2.35
Python:               3.10.9 (main, Mar  1 2023, 18:23:06) [GCC 11.2.0]

----Optional dependencies----
adbc_driver_manager:  <not installed>
cloudpickle:          2.0.0
connectorx:           <not installed>
deltalake:            <not installed>
fsspec:               2022.11.0
gevent:               <not installed>
hvplot:               0.8.2
matplotlib:           3.7.0
numpy:                1.23.5
openpyxl:             3.0.10
pandas:               1.5.3
pyarrow:              <not installed>
pydantic:             <not installed>
pyiceberg:            <not installed>
pyxlsb:               <not installed>
sqlalchemy:           1.4.39
xlsx2csv:             <not installed>
xlsxwriter:           <not installed>
```

</details>

**Comment by jamiemortimore** [comment]
Workaround is to convert to Categorical before sort:

tdf=pl.DataFrame({"a":["one","two","three","one","two","three"],"b":["four","five","six","six","five","four"],"c":[1,2,3,4,5,6]}).with_columns(pl.col(pl.Utf8).cast(pl.Categorical(ordering='lexical'))).lazy()

**Comment by ritchie46** [comment]
Reversed values are incorrectly decoded. Fix coming up.
