### ISSUE TITLE
Regression (0.20.2 -> 0.20.3): failure to initialize null column with nested struct dtypes (`ComputeError`)

### ISSUE THREAD

**Issue by brendancooley** [pola-rs/polars#13602]
### Checks

- [X] I have checked that this issue has not already been reported.
- [X] I have confirmed this bug exists on the [latest version](https://pypi.org/project/polars/) of Polars.

### Reproducible example

Null struct columns initialize fine
```python
pl.DataFrame().with_columns(pl.lit(None, pl.Struct([pl.Field("c", pl.Int8)])).alias("struct"))
```

But attempting to initialize a nested struct raises `ComputeError`
```python
pl.DataFrame().with_columns(pl.lit(None, pl.Struct([pl.Field("a", pl.Struct([pl.Field("c", pl.Int8)]))])).alias("struct"))
```

### Log output

```shell
Traceback (most recent call last):
  File ".../test_model.py", line 543, in <module>
    pl.DataFrame().with_columns(pl.lit(None, pl.Struct([pl.Field("a", pl.Struct([pl.Field("c", pl.Int8)]))])).alias("struct"))
  File ".../.venv/lib/python3.10/site-packages/polars/dataframe/frame.py", line 8235, in with_columns
    return self.lazy().with_columns(*exprs, **named_exprs).collect(_eager=True)
  File ".../.venv/lib/python3.10/site-packages/polars/lazyframe/frame.py", line 1749, in collect
    return wrap_df(ldf.collect())
polars.exceptions.ComputeError: conversion from `null` to `struct[1]` failed in column 'literal' for 0 out of 1 values: []
```

### Issue description

Believe this may be the source of the regression: https://github.com/pola-rs/polars/pull/13326

I will take a closer look and try to isolate the cause

### Expected behavior

With `polars==0.20.2` the nested initialization works fine, returning
```
shape: (1, 1)
┌───────────┐
│ struct    │
│ ---       │
│ struct[1] │
╞═══════════╡
│ {{null}}  │
└───────────┘
```

### Installed versions

<details>

```
--------Version info---------
Polars:               0.20.3
Index type:           UInt32
Platform:             macOS-13.6.1-x86_64-i386-64bit
Python:               3.10.13 (main, Sep 11 2023, 15:37:46) [Clang 12.0.5 (clang-1205.0.22.11)]

----Optional dependencies----
adbc_driver_manager:  <not installed>
cloudpickle:          <not installed>
connectorx:           <not installed>
deltalake:            <not installed>
fsspec:               <not installed>
gevent:               <not installed>
hvplot:               <not installed>
matplotlib:           <not installed>
numpy:                1.26.2
openpyxl:             <not installed>
pandas:               <not installed>
pyarrow:              14.0.2
pydantic:             2.5.3
pyiceberg:            <not installed>
pyxlsb:               <not installed>
sqlalchemy:           <not installed>
xlsx2csv:             <not installed>
xlsxwriter:           <not installed>```

</details>

**Comment by MarcoGorelli** [comment]
Thanks for the report

from git bisect, this is from #13255
```
639c4d51fa9ba300c14662c3ceadeefa86cd8e63 is the first bad commit
commit 639c4d51fa9ba300c14662c3ceadeefa86cd8e63
Author: Ritchie Vink <...>
Date:   Wed Dec 27 09:50:02 2023 +0100

    feat: dispatch strict_cast via cast (#13255)
```

**Comment by gab23r** [comment]
This do not raise anymore on polars 1.10 and produces the expected results. Can me close I think,

**Comment by kdn36** [comment]
This gives the expected result on main. Kindly let us know if you see it differently.
```
┌───────────┐
│ struct    │
│ ---       │
│ struct[1] │
╞═══════════╡
│ null      │
└───────────┘
```
I will go ahead and close the issue.
