### ISSUE TITLE
suggest add window function supports in sql

### ISSUE THREAD

**Issue by l1t1** [pola-rs/polars#13616]
### Description

I want to write sql to impl the  exmaple on the mainpage.
```
>>> import polars as pl
>>> df = pl.DataFrame(
...     {
...         "A": [1, 2, 3, 4, 5],
...         "fruits": ["banana", "banana", "apple", "apple", "banana"],
...         "B": [5, 4, 3, 2, 1],
...         "cars": ["beetle", "audi", "beetle", "beetle", "beetle"],
...     }
... )

# embarrassingly parallel execution & very expressive query language
>>> df.sort("fruits").select(
...     "fruits",
...     "cars",
...     pl.lit("fruits").alias("literal_string_fruits"),
...     pl.col("B").filter(pl.col("cars") == "beetle").sum(),
...     pl.col("A").filter(pl.col("B") > 2).sum().over("cars").alias("sum_A_by_cars"),
...     pl.col("A").sum().over("fruits").alias("sum_A_by_fruits"),
...     pl.col("A").reverse().over("fruits").alias("rev_A_by_fruits"),
...     pl.col("A").sort_by("B").over("fruits").alias("sort_A_by_B_by_fruits"),
... )
shape: (5, 8)
┌──────────┬──────────┬──────────────┬─────┬─────────────┬─────────────┬─────────────┬─────────────┐
│ fruits   ┆ cars     ┆ literal_stri ┆ B   ┆ sum_A_by_ca ┆ sum_A_by_fr ┆ rev_A_by_fr ┆ sort_A_by_B │
│ ---      ┆ ---      ┆ ng_fruits    ┆ --- ┆ rs          ┆ uits        ┆ uits        ┆ _by_fruits  │
│ str      ┆ str      ┆ ---          ┆ i64 ┆ ---         ┆ ---         ┆ ---         ┆ ---         │
│          ┆          ┆ str          ┆     ┆ i64         ┆ i64         ┆ i64         ┆ i64         │
╞══════════╪══════════╪══════════════╪═════╪═════════════╪═════════════╪═════════════╪═════════════╡
│ "apple"  ┆ "beetle" ┆ "fruits"     ┆ 11  ┆ 4           ┆ 7           ┆ 4           ┆ 4           │
│ "apple"  ┆ "beetle" ┆ "fruits"     ┆ 11  ┆ 4           ┆ 7           ┆ 3           ┆ 3           │
│ "banana" ┆ "beetle" ┆ "fruits"     ┆ 11  ┆ 4           ┆ 8           ┆ 5           ┆ 5           │
│ "banana" ┆ "audi"   ┆ "fruits"     ┆ 11  ┆ 2           ┆ 8           ┆ 2           ┆ 2           │
│ "banana" ┆ "beetle" ┆ "fruits"     ┆ 11  ┆ 4           ┆ 8           ┆ 1           ┆ 1           │
└──────────┴──────────┴──────────────┴─────┴─────────────┴─────────────┴─────────────┴─────────────┘
```
and  get the follwing error
```
>>> context = pl.SQLContext()
>>> context.register("t", df)
>>> lf = context.execute("select fruits,cars,'fruits' lit_str,sum(case when cars='beetle'then B else null end)over() from t")
>>> lf.collect()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "D:\Python38\lib\site-packages\polars\lazyframe\frame.py", line 1749, in collect
    return wrap_df(ldf.collect())
polars.exceptions.ComputeError: at least one key is required in a group_by operation
``

**Comment by alexander-beedie** [comment]
That error has been fixed by #25249.
Will be available in the upcoming `1.36.0` Polars release 👍 

**Example:**
```python
import polars as pl
df = pl.DataFrame({
    "A": [1, 2, 3, 4, 5],
    "fruits": ["banana", "banana", "apple", "apple", "banana"],
    "B": [5, 4, 3, 2, 1],
    "cars": ["beetle", "audi", "beetle", "beetle", "beetle"],
})
pl.sql("""
   SELECT
       fruits,
       cars,
       B AS orig_B,
       'fruits' AS literal_string_fruits,
       SUM(CASE WHEN cars = 'beetle' THEN B END) OVER () AS B,
       SUM(CASE WHEN B > 2 THEN A END) OVER (PARTITION BY cars) AS sum_A_by_cars,
       SUM(A) OVER (PARTITION BY fruits) AS sum_A_by_fruits,
   FROM df
   ORDER BY orig_B
""").collect()

# shape: (5, 7)
# ┌────────┬────────┬────────┬───────────────────────┬─────┬───────────────┬─────────────────┐
# │ fruits ┆ cars   ┆ orig_B ┆ literal_string_fruits ┆ B   ┆ sum_A_by_cars ┆ sum_A_by_fruits │
# │ ---    ┆ ---    ┆ ---    ┆ ---                   ┆ --- ┆ ---           ┆ ---             │
# │ str    ┆ str    ┆ i64    ┆ str                   ┆ i64 ┆ i64           ┆ i64             │
# ╞════════╪════════╪════════╪═══════════════════════╪═════╪═══════════════╪═════════════════╡
# │ banana ┆ beetle ┆ 1      ┆ fruits                ┆ 11  ┆ 4             ┆ 8               │
# │ apple  ┆ beetle ┆ 2      ┆ fruits                ┆ 11  ┆ 4             ┆ 7               │
# │ apple  ┆ beetle ┆ 3      ┆ fruits                ┆ 11  ┆ 4             ┆ 7               │
# │ banana ┆ audi   ┆ 4      ┆ fruits                ┆ 11  ┆ 2             ┆ 8               │
# │ banana ┆ beetle ┆ 5      ┆ fruits                ┆ 11  ┆ 4             ┆ 8               │
# └────────┴────────┴────────┴───────────────────────┴─────┴───────────────┴─────────────────┘
```
