### ISSUE TITLE
LazyFrame cross join + `sink_parquet` generates corrupted parquet file

### ISSUE THREAD

**Issue by dittos** [pola-rs/polars#13631]
### Checks

- [X] I have checked that this issue has not already been reported.
- [X] I have confirmed this bug exists on the [latest version](https://pypi.org/project/polars/) of Polars.

### Reproducible example

```python
import polars as pl

a = pl.DataFrame({"a": [1, 2]}).lazy()
b = pl.DataFrame({"b": ["b"]}).lazy()
a.join(b, how="cross").sink_parquet("temp.parquet")
print(a.join(b, how="cross").collect())  # to show correct result

pl.read_parquet("temp.parquet", parallel="none")  # parallel=none is set for less log (also fails when not set)
```

### Log output

```shell
RUN STREAMING PIPELINE
df -> cross_join_sink
RefCell { value: [df -> placeholder -> parquet_sink] }
join parallel: true
CROSS join dataframes finished
shape: (2, 2)
┌─────┬─────┐
│ a   ┆ b   │
│ --- ┆ --- │
│ i64 ┆ str │
╞═════╪═════╡
│ 1   ┆ b   │
│ 2   ┆ b   │
└─────┴─────┘
thread '<unnamed>' panicked at /home/runner/work/polars/polars/crates/polars-parquet/src/arrow/read/deserialize/primitive/basic.rs:51:9:
assertion `left == right` failed
  left: 5
 right: 0
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
Traceback (most recent call last):
  File "20240111-polars-cross-join-parquet.py", line 8, in <module>
    pl.read_parquet("temp.parquet", parallel="none")  # parallel=none is set for less log (also fails when not set)
  File "/home/ditto/.cache/pypoetry/virtualenvs/thinkingface-IAymwpp_-py3.8/lib/python3.8/site-packages/polars/io/parquet/functions.py", line 183, in read_parquet
    return lf.collect(no_optimization=True)
  File "/home/ditto/.cache/pypoetry/virtualenvs/thinkingface-IAymwpp_-py3.8/lib/python3.8/site-packages/polars/lazyframe/frame.py", line 1749, in collect
    return wrap_df(ldf.collect())
pyo3_runtime.PanicException: assertion `left == right` failed
  left: 5
 right: 0
```

### Issue description

it's okay when no string column exists

```
a = pl.DataFrame({"a": [1, 2]}).lazy()
b = pl.DataFrame({"b": [3]}).lazy()
```

it's also okay if both size is 1

```
a = pl.DataFrame({"a": [1]}).lazy()
b = pl.DataFrame({"b": ["b"]}).lazy()
```

the parquet file is not readable too from other implementations (e.g. pyarrow)

panics at the different line if left LF is larger

```
a = pl.DataFrame({"a": range(100)}).lazy()
b = pl.DataFrame({"b": ["b"]}).lazy()

thread '<unnamed>' panicked at /home/runner/work/polars/polars/crates/polars-parquet/src/arrow/read/deserialize/primitive/basic.rs:231:56:
index out of bounds: the len is 0 but the index is 0
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
Traceback (most recent call last):
  File "20240111-polars-cross-join-parquet.py", line 8, in <module>
    pl.read_parquet("temp.parquet", parallel="none")  # parallel=none is set for less log (also fails when not set)
  File "/home/ditto/.cache/pypoetry/virtualenvs/thinkingface-IAymwpp_-py3.8/lib/python3.8/site-packages/polars/io/parquet/functions.py", line 183, in read_parquet
    return lf.collect(no_optimization=True)
  File "/home/ditto/.cache/pypoetry/virtualenvs/thinkingface-IAymwpp_-py3.8/lib/python3.8/site-packages/polars/lazyframe/frame.py", line 1749, in collect
    return wrap_df(ldf.collect())
pyo3_runtime.PanicException: index out of bounds: the len is 0 but the index is 0
```

### Expected behavior

it should write valid parquet file

### Installed versions

<details>

```
--------Version info---------
Polars:               0.20.3
Index type:           UInt32
Platform:             Linux-5.15.133.1-microsoft-standard-WSL2-x86_64-with-glibc2.29
Python:               3.8.10 (default, Nov 22 2023, 10:22:35) 
[GCC 9.4.0]

----Optional dependencies----
adbc_driver_manager:  <not installed>
cloudpickle:          <not installed>
connectorx:           <not installed>
deltalake:            <not installed>
fsspec:               2023.12.2
gevent:               <not installed>
hvplot:               <not installed>
matplotlib:           3.7.1
numpy:                1.24.4
openpyxl:             3.1.2
pandas:               2.0.3
pyarrow:              14.0.2
pydantic:             2.5.3
pyiceberg:            <not installed>
pyxlsb:               <not installed>
sqlalchemy:           <not installed>
xlsx2csv:             <not installed>
xlsxwriter:           <not installed>
```

</details>

**Comment by ritchie46** [comment]
Got the culprit. We accidentally write the wrong schema order. Fix coming up.
