### ISSUE TITLE
Not able to specify pl.Datetime schema using from_dicts

### ISSUE THREAD

**Issue by egorbn** [pola-rs/polars#13652]
### Checks

- [X] I have checked that this issue has not already been reported.
- [X] I have confirmed this bug exists on the [latest version](https://pypi.org/project/polars/) of Polars.

### Reproducible example

This works
```python
>>> pl.from_dicts([{"datecol_int":4102358400000}]).with_columns(pl.col("datecol_int").cast(pl.Datetime("ms")).alias("datecol"))
shape: (1, 2)
┌───────────────┬─────────────────────┐
│ datecol_int   ┆ datecol             │
│ ---           ┆ ---                 │
│ i64           ┆ datetime[ms]        │
╞═══════════════╪═════════════════════╡
│ 4102358400000 ┆ 2099-12-31 00:00:00 │
└───────────────┴─────────────────────┘
```

But this doesn't:
```python
>>> pl.from_dicts([{"datecol":4102358400000}], schema={"datecol":pl.Datetime("ms")})
```
nor this:
```python
>>> pl.from_dicts([{"datecol":4102358400000}], schema_overrides={"datecol":pl.Datetime("ms")})
```

### Log output

```shell
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/blabla/venv/lib/python3.10/site-packages/polars/convert.py", line 172, in from_dicts
    return pl.DataFrame(
  File "/Users/blabla/venv/lib/python3.10/site-packages/polars/dataframe/frame.py", line 380, in __init__
    self._df = sequence_to_pydf(
  File "/Users/blabla/venv/lib/python3.10/site-packages/polars/utils/_construction.py", line 969, in sequence_to_pydf
    return _sequence_to_pydf_dispatcher(
  File "/opt/homebrew/Cellar/python@3.10/3.10.13_1/Frameworks/Python.framework/Versions/3.10/lib/python3.10/functools.py", line 889, in wrapper
    return dispatch(args[0].__class__)(*args, **kw)
  File "/Users/blabla/venv/lib/python3.10/site-packages/polars/utils/_construction.py", line 1188, in _sequence_of_dict_to_pydf
    pydf = PyDataFrame.read_dicts(
polars.exceptions.ComputeError: could not append value: 4102358400000 of type: i64 to the builder; make sure that all rows have the same schema or consider increasing `infer_schema_length`

it might also be that a value overflows the data-type's capacity
```

### Issue description

I have a column of integers that are actually datetime objects (JSON source).

When constructing a data frame, `from_dicts` just sees integers, of course, so I pass a schema, which should indicate to the constructor to interpret the values in those columns as datetimes.

However, this causes an error where the column is set to the datetime dtype, but polars tries to append what it thinks is an integer and fails.

Since polars sees an integer, but knows that it should be datetime based on the schema supplied, should it not cast automatically?

What is the purpose of supplying a schema if the constructor can't coerce the values to this schema as part of the df construction?

### Expected behavior

```python
>>> pl.from_dicts([{"datecol":4102358400000}], schema={"datecol":pl.Datetime("ms")})
shape: (1, 1)
┌─────────────────────┐
│ datecol             │
┆  ---                │
│ datetime[ms]        │
╞═════════════════════╡
│ 2099-12-31 00:00:00 │
└─────────────────────┘
```

### Installed versions

<details>

```
>>> pl.show_versions()
--------Version info---------
Polars:               0.20.3
Index type:           UInt32
Platform:             macOS-14.2-arm64-arm-64bit
Python:               3.10.13 (main, Nov  1 2023, 16:34:31) [Clang 14.0.3 (clang-1403.0.22.14.1)]

----Optional dependencies----
adbc_driver_manager:  <not installed>
cloudpickle:          3.0.0
connectorx:           <not installed>
deltalake:            <not installed>
fsspec:               2023.12.2
gevent:               <not installed>
hvplot:               <not installed>
matplotlib:           3.8.2
numpy:                1.23.0
openpyxl:             3.1.2
pandas:               1.5.3
pyarrow:              <not installed>
pydantic:             1.10.13
pyiceberg:            <not installed>
pyxlsb:               <not installed>
sqlalchemy:           1.4.51
xlsx2csv:             <not installed>
xlsxwriter:           <not installed>
```

</details>

**Comment by MarcoGorelli** [comment]
looks fine, thanks!

**Comment by egorbn** [comment]
Thank you @reswqa  and team! That was quick!
