### ISSUE TITLE
Negating/subtracting unsigned numbers overflows if the result is negative

### ISSUE THREAD

**Issue by Wainberg** [pola-rs/polars#13704]
### Checks

- [X] I have checked that this issue has not already been reported.
- [X] I have confirmed this bug exists on the [latest version](https://pypi.org/project/polars/) of Polars.

### Reproducible example

Taking the negative of an unsigned number gives an error:

```python
>>> -pl.Series([1], dtype=pl.UInt8)
thread '<unnamed>' panicked at polars/crates/polars-core/src/series/arithmetic/borrowed.rs:695:31:
attempt to subtract with overflow
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "polars/py-polars/polars/series/series.py", line 1162, in __neg__
    return 0 - self
           ~~^~~~~~
  File "polars/py-polars/polars/series/series.py", line 1111, in __rsub__
    return self._arithmetic(other, "sub", "sub_<>_rhs")
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "polars/py-polars/polars/series/series.py", line 981, in _arithmetic
    return self._from_pyseries(f(other))
                               ^^^^^^^^
pyo3_runtime.PanicException: attempt to subtract with overflow
```

Same with subtraction, though only if the result is negative:

```python
>>> 1 - pl.Series([1], dtype=pl.UInt64)
shape: (1,)
Series: '' [u64]
[
        0
]
>>> 1 - pl.Series([2], dtype=pl.UInt64)
thread '<unnamed>' panicked at polars/crates/polars-core/src/series/arithmetic/borrowed.rs:695:31:
attempt to subtract with overflow
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "polars/py-polars/polars/series/series.py", line 1111, in __rsub__
    return self._arithmetic(other, "sub", "sub_<>_rhs")
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "polars/py-polars/polars/series/series.py", line 981, in _arithmetic
    return self._from_pyseries(f(other))
                               ^^^^^^^^
pyo3_runtime.PanicException: attempt to subtract with overflow
```

This also affects functions like `Expr.len()` and `Expr.null_count()` that return unsigned integers:

```python
>>> pl.DataFrame({'a': [None]}).select(-pl.col.a.null_count())
thread '<unnamed>' panicked at crates/polars-core/src/chunked_array/arithmetic/numeric.rs:229:54:
attempt to subtract with overflow
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "polars/py-polars/polars/dataframe/frame.py", line 8097, in select
    return self.lazy().select(*exprs, **named_exprs).collect(_eager=True)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "polars/py-polars/polars/lazyframe/frame.py", line 1730, in collect
    return wrap_df(ldf.collect())
                   ^^^^^^^^^^^^^
pyo3_runtime.PanicException: attempt to subtract with overflow
```

[Here's](https://github.com/pola-rs/polars/issues/10849) an example of the problems this can cause in practice.

### Expected behavior

This should cast to signed if the result is negative (and overflow if any values aren't representable in the corresponding signed dtype).

### Installed versions

<details>

```
--------Version info---------
Polars:               0.20.4
Index type:           UInt32
Platform:             Linux-4.4.0-22621-Microsoft-x86_64-with-glibc2.35
Python:               3.12.1 | packaged by conda-forge | (main, Dec 23 2023, 08:03:24) [GCC 12.3.0]

----Optional dependencies----
adbc_driver_manager:  <not installed>
cloudpickle:          3.0.0
connectorx:           <not installed>
deltalake:            0.14.0
fsspec:               2023.12.2
gevent:               <not installed>
hvplot:               0.9.1
matplotlib:           3.8.2
numpy:                1.26.2
openpyxl:             <not installed>
pandas:               2.1.4
pyarrow:              14.0.2
pydantic:             2.5.3
pyiceberg:            0.5.1
pyxlsb:               <not installed>
sqlalchemy:           2.0.23
xlsx2csv:             <not installed>
xlsxwriter:           3.1.9
```

</details>

**Comment by stinodego** [comment]
The unary minus operator (negation) has recently been updated in https://github.com/pola-rs/polars/pull/13776 (not released yet).

When trying to negate unsigned columns, you will get an error. Negating unsigned numbers doesn't make sense.
```python
import polars as pl

out = -pl.Series([1], dtype=pl.UInt8)
print(out)  # -1
# polars.exceptions.InvalidOperationError: `neg` operation not supported for dtype `u8`
```

 Cast to a signed type first to avoid this:
```python
import polars as pl

out = -pl.Series([1], dtype=pl.UInt8).cast(pl.Int8)
print(out)  # -1
```

Subtracting two unsigned numbers can underflow, as you've noticed. When working with unsigned numbers, you are responsible for making sure this doesn't happen, otherwise it will panic. Generally it is advised to use signed integers when doing arithmetic.

**Comment by Wainberg** [comment]
Note that having to cast the result of `null_count()` and `len()` before negating them (but only for expressions; for Series it's still an int) makes it more difficult to write code that supports both Series and expressions. You have to do, e.g.:

`num_null = foo.null_count() if isinstance(foo, pl.Series) else foo.null_count().cast(pl.Int64)`
