### ISSUE TITLE
Support "multi-hot" encoding of List columns in df.to_dummies

### ISSUE THREAD

**Issue by Wainberg** [pola-rs/polars#13733]
### Description

I'd like to implement ["multi-hot" encoding](https://scikit-learn.org/stable/modules/generated/sklearn.preprocessing.MultiLabelBinarizer.html) for List columns in df.to_dummies, in which each row of the dummy dataframe has multiple elements turned on (one for each list element) instead of one. This is a common pre-processing step for statistical and machine learning applications.

So whereas this currently gives an error:

```python
>>> pl.DataFrame({'a': [['A', 'B'], ['B'], ['A', 'C']]}).to_dummies()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "polars/dataframe/frame.py", line 9033, in to_dummies
    return self._from_pydf(self._df.to_dummies(columns, separator, drop_first))
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
polars.exceptions.ComputeError: grouping on list type is only allowed if the inner type is numeric
```

It could instead give:

```python
>>> pl.DataFrame({'a': [['A', 'B'], ['B'], ['A', 'C']]}).to_dummies()
shape: (3, 3)
┌─────┬─────┬─────┐
│ A   ┆ B   ┆ C   │
│ --- ┆ --- ┆ --- │
│ u8  ┆ u8  ┆ u8  │
╞═════╪═════╪═════╡
│ 1   ┆ 1   ┆ 0   │
│ 0   ┆ 1   ┆ 0   │
│ 1   ┆ 0   ┆ 1   │
└─────┴─────┴─────┘
```

**Comment by Wainberg** [comment]
I was thinking it might be a better fit for polars itself because it's just about making an existing function "work" on new inputs (lists) in the obvious way.

**Comment by Wainberg** [comment]
You're thinking `Expr.list.to_dummies()`, and then regular `to_dummies` still gives an error?
