### ISSUE TITLE
Failure to read/scan ndjson file with faulty line with `ignore_errors=True`

### ISSUE THREAD

**Issue by nbrr** [pola-rs/polars#13768]
### Checks

- [X] I have checked that this issue has not already been reported.
- [X] I have confirmed this bug exists on the [latest version](https://pypi.org/project/polars/) of Polars.

### Reproducible example

`example.json`:
```JSON
{"a": 1,"b": 3}
x
{"a": 4,"b": 2}

```

scan:
```python
import polars as pl

pl.scan_ndjson('example.json', ignore_errors=True).collect()
```

read:
```python
import polars as pl

pl.read_ndjson('example.json', ignore_errors=True)
```

### Log output

```shell
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/nbrr/Library/Caches/pypoetry/virtualenvs/boulanger-20231205-13-FCFMsks8-py3.11/lib/python3.11/site-packages/polars/utils/deprecation.py", line 133, in wrapper
    return function(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/nbrr/Library/Caches/pypoetry/virtualenvs/boulanger-20231205-13-FCFMsks8-py3.11/lib/python3.11/site-packages/polars/utils/deprecation.py", line 133, in wrapper
    return function(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/nbrr/Library/Caches/pypoetry/virtualenvs/boulanger-20231205-13-FCFMsks8-py3.11/lib/python3.11/site-packages/polars/io/ndjson.py", line 110, in scan_ndjson
    return pl.LazyFrame._scan_ndjson(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/nbrr/Library/Caches/pypoetry/virtualenvs/boulanger-20231205-13-FCFMsks8-py3.11/lib/python3.11/site-packages/polars/lazyframe/frame.py", line 555, in _scan_ndjson
    self._ldf = PyLazyFrame.new_from_ndjson(
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
polars.exceptions.ComputeError: InternalError(TapeError) at character 0 ('x')
```

### Issue description

Both `read_ndjson` and `scan_ndjson` fail to process a ndjson file with a line that is not proper json.

### Expected behavior

File `example.json` is read, ignoring the non-json line.

### Installed versions

<details>

```
--------Version info---------
Polars:               0.20.4
Index type:           UInt32
Platform:             macOS-10.16-x86_64-i386-64bit
Python:               3.11.5 (main, Sep 11 2023, 08:19:27) [Clang 14.0.6 ]

----Optional dependencies----
adbc_driver_manager:  <not installed>
cloudpickle:          3.0.0
connectorx:           <not installed>
deltalake:            <not installed>
fsspec:               2023.12.2
gevent:               <not installed>
hvplot:               <not installed>
matplotlib:           <not installed>
numpy:                1.26.3
openpyxl:             <not installed>
pandas:               2.1.4
pyarrow:              13.0.0
pydantic:             <not installed>
pyiceberg:            <not installed>
pyxlsb:               <not installed>
sqlalchemy:           <not installed>
xlsx2csv:             <not installed>
xlsxwriter:           <not installed>
```

</details>

**Comment by jpedrick** [comment]
I am also seeing this error

**Comment by ChristofferCOASD** [comment]
+1

**Comment by mat-ej** [comment]
I second this.

**Comment by philosophicles** [comment]
Just replicated this bug in polars 1.43.2

**Comment by philosophicles** [comment]
Although - I am not sure this is actually a bug. The [current documentation](https://docs.pola.rs/api/python/stable/reference/api/polars.read_ndjson.html) for the `ignore_errors` switch says (emphasis mine): 

> Return Null if parsing fails **because of schema mismatches**.

This is not a schema mismatch problem with the sample JSON as provided. It's just a fundamentally invalid JSON file. I suspect this switch was not intended to do what @nbrr thinks it should have done - in which case, there is arguably a feature request here, but not a bug. 

Aside from any feature request, the documentation could be expanded a bit to make clearer what the intended limit of `ignore_errors` is.
