### ISSUE TITLE
In `.join()`, `validate` sometimes doesn't error when it should

### ISSUE THREAD

**Issue by etiennebacher** [pola-rs/polars#13852]
### Checks

- [X] I have checked that this issue has not already been reported.
- [X] I have confirmed this bug exists on the [latest version](https://pypi.org/project/polars/) of Polars.

### Reproducible example

```python
import polars as pl

df1 = pl.LazyFrame({"x": ["a", "a"], "y": [1, 2]})
df2 = pl.LazyFrame({"x": ["a", "b"], "y2": [3, 4]})

df1.collect()
df2.collect()

df1.join(df2, on="x", validate="1:1").collect() # should error but doesn't
df1.join(df2, on="x", validate="1:m").collect() # should error but doesn't
```

```python
>>> df1.collect()
shape: (2, 2)
┌─────┬─────┐
│ x   ┆ y   │
│ --- ┆ --- │
│ str ┆ i64 │
╞═════╪═════╡
│ a   ┆ 1   │
│ a   ┆ 2   │
└─────┴─────┘
>>> df2.collect()
shape: (2, 2)
┌─────┬─────┐
│ x   ┆ y2  │
│ --- ┆ --- │
│ str ┆ i64 │
╞═════╪═════╡
│ a   ┆ 3   │
│ b   ┆ 4   │
└─────┴─────┘
>>> df1.join(df2, on="x", validate="1:1").collect() # should error but doesn't
shape: (2, 3)
┌─────┬─────┬─────┐
│ x   ┆ y   ┆ y2  │
│ --- ┆ --- ┆ --- │
│ str ┆ i64 ┆ i64 │
╞═════╪═════╪═════╡
│ a   ┆ 1   ┆ 3   │
│ a   ┆ 2   ┆ 3   │
└─────┴─────┴─────┘
>>> df1.join(df2, on="x", validate="1:m").collect() # should error but doesn't
shape: (2, 3)
┌─────┬─────┬─────┐
│ x   ┆ y   ┆ y2  │
│ --- ┆ --- ┆ --- │
│ str ┆ i64 ┆ i64 │
╞═════╪═════╪═════╡
│ a   ┆ 1   ┆ 3   │
│ a   ┆ 2   ┆ 3   │
└─────┴─────┴─────┘
```

### Log output

```shell
None
```

### Issue description

It seems that `validate` sometimes doesn't error while it should. In the example above, the key `x` in `df1` is twice `"a"` and matches twice the key `x="a"` of `df2`. Therefore, setting `validate='1:1'` or `validate='1:m'` should error, but it currently outputs what we would have with `validate='m:m'`.

Note that if we remove the second row in `df2` (keeping only `x="a"` and `y2 = 3`), then we have two errors with the `validate` message (as expected).

Even weirder: swapping `df1` and `df2` and replacing `'1:m'` by `'m:1'` throws the expected error:

```python
>>> df2.join(df1, on="x", validate="m:1").collect()

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Python311\Lib\site-packages\polars\lazyframe\frame.py", line 1730, in collect
    return wrap_df(ldf.collect())
                   ^^^^^^^^^^^^^
polars.exceptions.ComputeError: the join keys did not fulfil m:1 validation
```

### Expected behavior

The two joins in the example should throw two errors:

```
polars.exceptions.ComputeError: the join keys did not fulfil 1:1 validation

polars.exceptions.ComputeError: the join keys did not fulfil 1:m validation
```

### Installed versions

<details>

```
Replace this line with the output of pl.show_versions(). Leave the backticks in place.
```

</details>

**Comment by mcrumiller** [comment]
Partial duplicate of #13550, although this seems to expose a larger extent of the problem.

This may also be a a miscommunication in the documentation. I may be wrong (someone please correct me if so), but I _believe_ the intent of the join validation is to **not** to determine whether the keys are unique in the left or right frame, but whether or not *rows of either frame are broadcast* (i.e. row in from `A` matches to multiple rows in frame `B`, and vice-versa) as a result of the join.

Regardless, there still seems to be an issue. In your example, row 1 from `df2` gets broadcast to both rows in `df1`, so `1:1` should fail validation. However, `1:m` should not fail, as each row in `df1` is only joined with one row in the right frame, so the `1` in `1:m` holds.

The swap also indeed seems to be an error. `df2.join(df1, on="x")` maps row 1 of the left frame to multiple rows of the right, which is a `1:m` mapping.

**Comment by etiennebacher** [comment]
> A small aside, your calls to df1.collect() and df2.collect() do nothing: the frames are collected and never assigned to anything, so that computation is completely discarded.

Yes I just collected to print them, I find it easier to visualize than reading the definition in `pl.LazyFrame()` ;)

**Comment by rob-superty** [comment]
> This may also be a miscommunication in the documentation. I may be wrong (someone please correct me if so), but I _believe_ the intent of the join validation is to **not** to determine whether the keys are unique in the left or right frame, but whether or not _rows are broadcast_ (i.e. row in from `A` matches to multiple rows in frame `B`, and vice-versa) during the join.

I was thinking the same thing -- this validation should be about the results of the _join_, not the uniqueness of the data -- so as an example, if the left or right table in an inner join contains any duplication on the join key, but _those rows are not involved in the result of the join (i.e., not shared between the tables)_, then I would expect `1:1` validation to pass.

> Regardless, there still seems to be an issue. In your example, row 1 from `df2` gets broadcast to both rows in `df1`, so `1:1` should fail validation. However, `1:m` should not fail, as each row in `df1` is only joined with one row in the right frame, so the `1` in `1:m` holds.

Isn't this the intention of the `m:1` validation?  In this case you have many rows in the left table being broadcast to the _same_ row on the right table -- so not `1:m` (which should fail), but instead `m:1` (which should pass).  Or did I misunderstand your comment there?
