### ISSUE TITLE
read_database + Sqlalchemy2 = 'ChunkedIteratorResult' object has no attribute 'cursor' when using the ORM

### ISSUE THREAD

**Issue by WilliamStam** [pola-rs/polars#13926]
### Checks

- [X] I have checked that this issue has not already been reported.
- [X] I have confirmed this bug exists on the [latest version](https://pypi.org/project/polars/) of Polars.

### Reproducible example

with an ORM query
```python
import polars
from sqlalchemy import create_engine, text, String, Integer, select
from sqlalchemy.orm import sessionmaker, mapped_column, Mapped, DeclarativeBase


class Base(DeclarativeBase):
    pass

class SourceTable(Base):
    __tablename__ = "UPD_AUDT"

    UPD_SEQ: Mapped[int] = mapped_column(Integer, primary_key=True)
    UPD_VERS1: Mapped[str] = mapped_column(String(2), nullable=True)
    UPD_VERS2: Mapped[str] = mapped_column(String(2), nullable=True)
    UPD_VERS3: Mapped[str] = mapped_column(String(2), nullable=True)


engine = create_engine('oracle+oracledb://***:***@***/***')
session = sessionmaker(bind=engine)()

query = select(*[
    SourceTable.UPD_SEQ,
    SourceTable.UPD_VERS1,
    SourceTable.UPD_VERS2,
])

rows = session.execute(query).fetchall()
print(rows)

df = polars.read_database(query, connection=session)
print(df)


```

### Log output

```shell
(***-3.12) W:\Projects\***>python app\test2.py
[(6, '7', '0'), (7, '7', '0'), (15, '7', '0')]
Traceback (most recent call last):
  File "W:\Projects\***\app\test2.py", line 32, in <module>
    df = polars.read_database(query, connection=session)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "W:\Projects\***\.venv\Lib\site-packages\polars\io\database.py", line 585, in read_database
    ).to_polars(
      ^^^^^^^^^^
  File "W:\Projects\***\.venv\Lib\site-packages\polars\io\database.py", line 383, in to_polars
    frame = frame_init(
            ^^^^^^^^^^^
  File "W:\Projects\***\.venv\Lib\site-packages\polars\io\database.py", line 283, in _from_rows
    self.result.cursor.description
    ^^^^^^^^^^^^^^^^^^
AttributeError: 'ChunkedIteratorResult' object has no attribute 'cursor'
```

### Issue description

When using the ORM for a query it errors out with `AttributeError: 'ChunkedIteratorResult' object has no attribute 'cursor'`.

this is caused on https://github.com/pola-rs/polars/blob/8bd1872848e93052e4057aac3ba12d40d1bce28b/py-polars/polars/io/database.py#L282 

```
def _from_rows(
   ...
) -> DataFrame | Iterable[DataFrame] | None:
... 
   if hasattr(self.result, "fetchall"):
        description = (
            self.result.cursor.description
            if self.driver_name == "sqlalchemy"
            else self.result.description
        )
        column_names = [desc[0] for desc in description]

```

there isnt a self.cursor.description when using the ORM. there is however a self.result._metadata.keys

propose changing it to this:
```
    column_names = (
        self.result._metadata.keys
        if self.driver_name == "sqlalchemy"
        else
        [desc[0] for desc in self.result.description]
    )
```

it does seem to work with the normal text() query as well

```
query = text("SELECT * FROM TABLE")
```

when using polars like this it does work with the current code.

```python
import polars
from sqlalchemy import create_engine, text, String, Integer, select
from sqlalchemy.orm import sessionmaker, mapped_column, Mapped

engine = create_engine('oracle+oracledb://***:***@***/***')
session = sessionmaker(bind=engine)()

query = text("SELECT * FROM TABLE")

rows = session.execute(query).fetchall()
print(rows)

df = polars.read_database(query, connection=session)
print(df)
```

### Expected behavior

![image](https://github.com/pola-rs/polars/assets/182800/3bd458c9-e7c5-4efc-b668-bf98cf6a60ae)

### Installed versions

<details>

```
--------Version info---------
Polars:               0.20.5
Index type:           UInt32
Platform:             Windows-11-10.0.22631-SP0
Python:               3.12.1 (tags/v3.12.1:2305ca5, Dec  7 2023, 22:03:25) [MSC v.1937 64 bit (AMD64)]

----Optional dependencies----
adbc_driver_manager:  <not installed>
cloudpickle:          <not installed>
connectorx:           <not installed>
deltalake:            <not installed>
fsspec:               <not installed>
gevent:               <not installed>
hvplot:               <not installed>
matplotlib:           3.8.2
numpy:                1.26.3
openpyxl:             <not installed>
pandas:               <not installed>
pyarrow:              <not installed>
pydantic:             2.6.0b1
pyiceberg:            <not installed>
pyxlsb:               <not installed>
sqlalchemy:           2.0.25
xlsx2csv:             <not installed>
xlsxwriter:           <not installed>

```

</details>

**Comment by deanm0000** [comment]
What about if you pass it the engine instead of the season?

**Comment by WilliamStam** [comment]
passing the engine in works! 

```
df = polars.read_database(query, connection=engine)
```
i really thought i was being clever with this issue :P but alas...

---

with engine however, we loose some stuff by letting polars handle the session. in my use-case i set the schema `session.execute(text(f"ALTER SESSION SET CURRENT_SCHEMA = MY_SCHEMA"))` for oracle and log connections. im guessing you also wont be able to use connection pools then? 

seems `self.result._metadata.keys` works for both as well tho.

**Comment by deanm0000** [comment]
What about `session.connection()` does that work?

**Comment by WilliamStam** [comment]
got to love sqlalchemy <3 like a billion things for slightly different purposes but essentially very similar

`session.connection()` works!!

```
import polars

from sqlalchemy import create_engine, text, String, Integer, select
from sqlalchemy.orm import sessionmaker, mapped_column, Mapped, DeclarativeBase


class Base(DeclarativeBase):
    pass

class SourceTable(Base):
    __tablename__ = "TABLE"


    UPD_SEQ: Mapped[int] = mapped_column(Integer, primary_key=True)
    UPD_VERS1: Mapped[str] = mapped_column(String(2), nullable=True)
    UPD_VERS2: Mapped[str] = mapped_column(String(2), nullable=True)
    UPD_VERS3: Mapped[str] = mapped_column(String(2), nullable=True)


engine = create_engine('oracle+oracledb://***:***@***/***',echo=True)
session_maker = sessionmaker(bind=engine)
session = session_maker()

session.execute(text(f"ALTER SESSION SET CURRENT_SCHEMA = ***"))

query = select(*[
    SourceTable.UPD_SEQ,
    SourceTable.UPD_VERS1,
    SourceTable.UPD_VERS2,
])
query = query.limit(10).offset(0)
query = query.filter(SourceTable.UPD_SEQ > 10)

df = polars.read_database(query, connection=session.connection())
print(df)

```

the type for connection shows as wrong (it did the same with just session. but was happy with engine)

`Expected type 'BasicConnection | BasicCursor | Cursor | Engine | str', got 'Connection' instead `

dudethem.. you rock!

**Comment by alexander-beedie** [comment]
I'll look at handling this more gracefully so it "just works".
Will re-open and assign myself as a reminder  ;)

**Comment by deanm0000** [comment]
> `session.connection()` works!!

Thanks for the feedback. It's always appreciated when people let me know my suggestions work and are helpful.

**Comment by alexander-beedie** [comment]
@WilliamStam: your query should work in the next release with no modification (keep an eye out for `0.20.10`) 👌
