### ISSUE TITLE
Using a 128-bit int in a LazyFrame with a schema specified as pl.Decimal results in PanicException

### ISSUE THREAD

**Issue by cdmoye** [pola-rs/polars#13965]
### Checks

- [X] I have checked that this issue has not already been reported.
- [X] I have confirmed this bug exists on the [latest version](https://pypi.org/project/polars/) of Polars.

### Reproducible example

```python
import uuid
import polars as pl

udid_int = uuid.uuid4().int
try:
    lf = pl.LazyFrame([{'udid': udid_int}], schema = {'udid': pl.Decimal})
    print(f'pl.Decimal type works with {udid_int.bit_length()}-bit int')
except BaseException as err:
    print(f'pl.Decimal type does not work with {udid_int.bit_length()}-bit int')
    print(repr(err))
```

### Log output

```shell
thread '<unnamed>' panicked at crates/polars-core/src/frame/row/av_buffer.rs:259:85:
called `Result::unwrap()` on an `Err` value: ComputeError(ErrString("unable to convert any-value of dtype f64 to decimal"))
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
pl.Decimal type does not work with 128-bit int
PanicException('called `Result::unwrap()` on an `Err` value: ComputeError(ErrString("unable to convert any-value of dtype f64 to decimal"))')
```

### Issue description

When using a 128-bit integer (in this case, obtained from the uuid package), assigning that value to a LazyFrame with a schema set to pl.Decimal causes a PanicException.

The output of my code sample (after setting RUST_BACKTRACE=full) is here:
```
thread '<unnamed>' panicked at crates/polars-core/src/frame/row/av_buffer.rs:259:85:
called `Result::unwrap()` on an `Err` value: ComputeError(ErrString("unable to convert any-value of dtype f64 to decimal"))
stack backtrace:
   0:     0x7f46f67f3455 - std::backtrace_rs::backtrace::libunwind::trace::h815354fef816bc86
                               at /rustc/503e129328080e924c0ddfca6abf4c2812580102/library/std/src/../../backtrace/src/backtrace/libunwind.rs:104:5
   1:     0x7f46f67f3455 - std::backtrace_rs::backtrace::trace_unsynchronized::h8ee509da58073872
                               at /rustc/503e129328080e924c0ddfca6abf4c2812580102/library/std/src/../../backtrace/src/backtrace/mod.rs:66:5
   2:     0x7f46f67f3455 - std::sys_common::backtrace::_print_fmt::ha7526b8479823d1a
                               at /rustc/503e129328080e924c0ddfca6abf4c2812580102/library/std/src/sys_common/backtrace.rs:68:5
   3:     0x7f46f67f3455 - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::haf74540a80629043
                               at /rustc/503e129328080e924c0ddfca6abf4c2812580102/library/std/src/sys_common/backtrace.rs:44:22
   4:     0x7f46f43ea630 - core::fmt::rt::Argument::fmt::hc68f5fa1b36668fc
                               at /rustc/503e129328080e924c0ddfca6abf4c2812580102/library/core/src/fmt/rt.rs:142:9
   5:     0x7f46f43ea630 - core::fmt::write::h4274fed398e9428e
                               at /rustc/503e129328080e924c0ddfca6abf4c2812580102/library/core/src/fmt/mod.rs:1120:17
   6:     0x7f46f67bc19e - std::io::Write::write_fmt::hc6c4a8568e7df724
                               at /rustc/503e129328080e924c0ddfca6abf4c2812580102/library/std/src/io/mod.rs:1810:15
   7:     0x7f46f67f520e - std::sys_common::backtrace::_print::h2e09ef8543bf3bd8
                               at /rustc/503e129328080e924c0ddfca6abf4c2812580102/library/std/src/sys_common/backtrace.rs:47:5
   8:     0x7f46f67f520e - std::sys_common::backtrace::print::h9a43f66a9d093046
                               at /rustc/503e129328080e924c0ddfca6abf4c2812580102/library/std/src/sys_common/backtrace.rs:34:9
   9:     0x7f46f67f4aa7 - std::panicking::default_hook::{{closure}}::h9c00a7d25a3e4c19
  10:     0x7f46f67f5abb - std::panicking::default_hook::h1b24ab04fe68d03a
                               at /rustc/503e129328080e924c0ddfca6abf4c2812580102/library/std/src/panicking.rs:292:9
  11:     0x7f46f67f5abb - std::panicking::rust_panic_with_hook::hbafd4f0baa9fdb9e
                               at /rustc/503e129328080e924c0ddfca6abf4c2812580102/library/std/src/panicking.rs:779:13
  12:     0x7f46f67f558c - std::panicking::begin_panic_handler::{{closure}}::h4c976a34ccffa9e2
                               at /rustc/503e129328080e924c0ddfca6abf4c2812580102/library/std/src/panicking.rs:657:13
  13:     0x7f46f67f54e6 - std::sys_common::backtrace::__rust_end_short_backtrace::h675039fe30aa0955
                               at /rustc/503e129328080e924c0ddfca6abf4c2812580102/library/std/src/sys_common/backtrace.rs:171:18
  14:     0x7f46f67f54d1 - rust_begin_unwind
                               at /rustc/503e129328080e924c0ddfca6abf4c2812580102/library/std/src/panicking.rs:645:5
  15:     0x7f46f34b9fa4 - core::panicking::panic_fmt::h32ca55ac70be178d
                               at /rustc/503e129328080e924c0ddfca6abf4c2812580102/library/core/src/panicking.rs:72:14
  16:     0x7f46f34ba562 - core::result::unwrap_failed::h179c95b92f11ec78
                               at /rustc/503e129328080e924c0ddfca6abf4c2812580102/library/core/src/result.rs:1649:5
  17:     0x7f46f506b597 - polars_core::frame::row::av_buffer::AnyValueBuffer::reset::h8c44644aa4e86c0e
  18:     0x7f46f3f3aaab - polars::dataframe::PyDataFrame::finish_from_rows::ha524363d73d7aba3
  19:     0x7f46f41296e7 - polars::dataframe::_::<impl polars::dataframe::PyDataFrame>::__pymethod_read_dicts__::h3c3646976ecee932
  20:     0x7f46f3b3c2f3 - pyo3::impl_::trampoline::trampoline::hb5e13dd52ff7d48e
  21:     0x7f46f42bf891 - polars::dataframe::_::_::__INVENTORY::trampoline::hb7678ce72d80efca
  22:     0x564142f6b216 - cfunction_call
                               at /usr/local/src/conda/python-3.11.7/Objects/methodobject.c:542:18
  23:     0x564142f49f53 - _PyObject_MakeTpCall
                               at /usr/local/src/conda/python-3.11.7/Objects/call.c:214:18
  24:     0x564142f57a36 - _PyEval_EvalFrameDefault
                               at /usr/local/src/conda/python-3.11.7/Python/ceval.c:4769:23
  25:     0x564142f7b031 - _PyEval_EvalFrame
                               at /usr/local/src/conda/python-3.11.7/Include/internal/pycore_ceval.h:73:16
  26:     0x564142f7b031 - _PyEval_Vector
                               at /usr/local/src/conda/python-3.11.7/Python/ceval.c:6434:24
  27:     0x564142f7b031 - _PyFunction_Vectorcall
                               at /usr/local/src/conda/python-3.11.7/Objects/call.c:393:16
  28:     0x564142f84d30 - _PyVectorcall_Call
                               at /usr/local/src/conda/python-3.11.7/Objects/call.c:257:24
  29:     0x564142f84d30 - _PyObject_Call
                               at /usr/local/src/conda/python-3.11.7/Objects/call.c:328:16
  30:     0x564142f84d30 - PyObject_Call
                               at /usr/local/src/conda/python-3.11.7/Objects/call.c:355:12
  31:     0x564142f5bb1c - do_call_core
                               at /usr/local/src/conda/python-3.11.7/Python/ceval.c:7352:12
  32:     0x564142f5bb1c - _PyEval_EvalFrameDefault
                               at /usr/local/src/conda/python-3.11.7/Python/ceval.c:5376:22
  33:     0x564142f7b031 - _PyEval_EvalFrame
                               at /usr/local/src/conda/python-3.11.7/Include/internal/pycore_ceval.h:73:16
  34:     0x564142f7b031 - _PyEval_Vector
                               at /usr/local/src/conda/python-3.11.7/Python/ceval.c:6434:24
  35:     0x564142f7b031 - _PyFunction_Vectorcall
                               at /usr/local/src/conda/python-3.11.7/Objects/call.c:393:16
  36:     0x564142f824b3 - _PyObject_FastCallDictTstate
                               at /usr/local/src/conda/python-3.11.7/Objects/call.c:152:15
  37:     0x564142f824b3 - _PyObject_Call_Prepend
                               at /usr/local/src/conda/python-3.11.7/Objects/call.c:482:24
  38:     0x564142f824b3 - slot_tp_init
                               at /usr/local/src/conda/python-3.11.7/Objects/typeobject.c:7854:15
  39:     0x564142f49f33 - type_call
                               at /usr/local/src/conda/python-3.11.7/Objects/typeobject.c:1103:19
  40:     0x564142f49f33 - _PyObject_MakeTpCall
                               at /usr/local/src/conda/python-3.11.7/Objects/call.c:214:18
  41:     0x564142f57a36 - _PyEval_EvalFrameDefault
                               at /usr/local/src/conda/python-3.11.7/Python/ceval.c:4769:23
  42:     0x564142f7b031 - _PyEval_EvalFrame
                               at /usr/local/src/conda/python-3.11.7/Include/internal/pycore_ceval.h:73:16
  43:     0x564142f7b031 - _PyEval_Vector
                               at /usr/local/src/conda/python-3.11.7/Python/ceval.c:6434:24
  44:     0x564142f7b031 - _PyFunction_Vectorcall
                               at /usr/local/src/conda/python-3.11.7/Objects/call.c:393:16
  45:     0x564142f824b3 - _PyObject_FastCallDictTstate
                               at /usr/local/src/conda/python-3.11.7/Objects/call.c:152:15
  46:     0x564142f824b3 - _PyObject_Call_Prepend
                               at /usr/local/src/conda/python-3.11.7/Objects/call.c:482:24
  47:     0x564142f824b3 - slot_tp_init
                               at /usr/local/src/conda/python-3.11.7/Objects/typeobject.c:7854:15
  48:     0x564142f49f33 - type_call
                               at /usr/local/src/conda/python-3.11.7/Objects/typeobject.c:1103:19
  49:     0x564142f49f33 - _PyObject_MakeTpCall
                               at /usr/local/src/conda/python-3.11.7/Objects/call.c:214:18
  50:     0x564142f57a36 - _PyEval_EvalFrameDefault
                               at /usr/local/src/conda/python-3.11.7/Python/ceval.c:4769:23
  51:     0x56414300e8bd - _PyEval_EvalFrame
                               at /usr/local/src/conda/python-3.11.7/Include/internal/pycore_ceval.h:73:16
  52:     0x56414300e8bd - _PyEval_Vector
                               at /usr/local/src/conda/python-3.11.7/Python/ceval.c:6434:24
  53:     0x56414300df4f - PyEval_EvalCode
                               at /usr/local/src/conda/python-3.11.7/Python/ceval.c:1148:21
  54:     0x56414302ceaa - run_eval_code_obj
                               at /usr/local/src/conda/python-3.11.7/Python/pythonrun.c:1710:9
  55:     0x564143028a23 - run_mod
                               at /usr/local/src/conda/python-3.11.7/Python/pythonrun.c:1731:19
  56:     0x56414303dde0 - pyrun_file
                               at /usr/local/src/conda/python-3.11.7/Python/pythonrun.c:1626:15
  57:     0x56414303d77e - _PyRun_SimpleFileObject
                               at /usr/local/src/conda/python-3.11.7/Python/pythonrun.c:440:13
  58:     0x56414303d4a4 - _PyRun_AnyFileObject
                               at /usr/local/src/conda/python-3.11.7/Python/pythonrun.c:79:15
  59:     0x564143037b94 - pymain_run_file_obj
                               at /usr/local/src/conda/python-3.11.7/Modules/main.c:360:15
  60:     0x564143037b94 - pymain_run_file
                               at /usr/local/src/conda/python-3.11.7/Modules/main.c:379:15
  61:     0x564143037b94 - pymain_run_python
                               at /usr/local/src/conda/python-3.11.7/Modules/main.c:601:21
  62:     0x564143037b94 - Py_RunMain
                               at /usr/local/src/conda/python-3.11.7/Modules/main.c:680:5
  63:     0x564142ffdf47 - Py_BytesMain
                               at /usr/local/src/conda/python-3.11.7/Modules/main.c:734:12
  64:     0x7f470523feb0 - __libc_start_call_main
  65:     0x7f470523ff60 - __libc_start_main_impl
  66:     0x564142ffdded - <unknown>
pl.Decimal type does not work with 128-bit int
PanicException('called `Result::unwrap()` on an `Err` value: ComputeError(ErrString("unable to convert any-value of dtype f64 to decimal"))')
```

### Expected behavior

It should work, and not panic

### Installed versions

<details>

```
>>> pl.show_versions()
--------Version info---------
Polars:               0.20.5
Index type:           UInt32
Platform:             Linux-6.1.72-96.166.amzn2023.x86_64-x86_64-with-glibc2.34
Python:               3.11.7 | packaged by conda-forge | (main, Dec 23 2023, 14:43:09) [GCC 12.3.0]

----Optional dependencies----
adbc_driver_manager:  <not installed>
cloudpickle:          <not installed>
connectorx:           <not installed>
deltalake:            <not installed>
fsspec:               <not installed>
gevent:               <not installed>
hvplot:               <not installed>
matplotlib:           <not installed>
numpy:                1.26.3
openpyxl:             <not installed>
pandas:               2.1.4
pyarrow:              11.0.0
pydantic:             <not installed>
pyiceberg:            <not installed>
pyxlsb:               <not installed>
sqlalchemy:           <not installed>
xlsx2csv:             <not installed>
xlsxwriter:           <not installed>
>>> 
```

</details>

**Comment by stinodego** [comment]
We don't support this way of initializing a Decimal column. Try converting it to a Python decimal first.

Still, we should gracefully handle this instead of panic.

And it might even be possible to support initialization from such integers. We can have a look.

**Comment by cdmoye** [comment]
> We don't support this way of initializing a Decimal column. Try converting it to a Python decimal first.

```python
import decimal
import uuid
import polars as pl

udid_int = decimal.Decimal(uuid.uuid4().int)
try:
    lf = pl.LazyFrame([{'udid': udid_int}], schema = {'udid': pl.Decimal})
except BaseException as err:
    print(repr(err))
```
`RuntimeError('BindingsError: "Decimal is too large to fit in Decimal128"')`

**Comment by mcrumiller** [comment]
> And it might even be possible to support initialization from such integers. We can have a look.


@stinodego @cdmoye's latest example does use a python decimal, but here is a somewhat clearer example:

```python
>>> pl.Series([Decimal(10**38-1)], dtype=pl.Decimal)
shape: (1,)
Series: '' [decimal[*,0]]
[
        99999999999999999999999999999999999999
]

>>> pl.Series([Decimal(10**38)], dtype=pl.Decimal)
RuntimeError: BindingsError: "Decimal is too large to fit in Decimal128"
```

I see in the code that we have a maximum decimal value of 99999999999999999999999999999999999999. See [here](https://github.com/pola-rs/polars/blob/main/py-polars/src/conversion/anyvalue.rs#L391-L416): 

```rust
fn abs_decimal_from_digits(
    digits: impl IntoIterator<Item = u8>,
    exp: i32,
) -> Option<(i128, usize)> {
    const MAX_ABS_DEC: i128 = 10_i128.pow(38) - 1;
    let mut v = 0_i128;

    ...

    // TODO: do we care for checking if it fits in MAX_ABS_DEC? (if we set precision to None anyway?)
    (v <= MAX_ABS_DEC).then_some((v, scale))
}
```

I'm not super familiar with how decimals (are you?) work, after a bit of googling I found [Apache Spark's decimal type documentation](https://spark.apache.org/docs/3.1.3/api/python/reference/api/pyspark.sql.types.DecimalType.html) which says the following:

> The DecimalType must have fixed precision (the maximum total number of digits) and scale (the number of digits on the right of dot). For example, (5, 2) can support the value from [-999.99 to 999.99].
>
> The precision can be up to 38, the scale must be less or equal to precision.

10^38 makes sense as a maximum value, because 10^39 exceeds 2^128 and wouldn't fit into our 128-bit representation. Python seems to be capable of supporting larger integers, as [here](https://docs.python.org/3/library/decimal.html#constants) it says that the maximum precision is not 38 but 999999999999999999, which is rather absurd. Indeed, `Decimal(9999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999)` runs just fine.

With that said, I think we should 1) remove the `TODO` and replace with a more informative comment since yes, we probably should care that the value fits, and also b) return a better error message.

Does this all sound reasonable?

**Comment by cdmoye** [comment]
Note also that the source I used for my number was uuid.UUID().int, which returns a 128-bit int. So, I wasn't even trying to overflow it.

**Comment by mcrumiller** [comment]
@cdmoye yeah, it looks like `uuid4()` creates an average of about 2^(126.5), and log2(10^38) = 126.2, so you'll probably get invalid values a bit more than half the time:

```python
>>> threshold = 10**38-1
>>> print(pl.Series([uuid4().int > threshold for _ in range(1_000_000)]).mean())
0.706942
```

**Comment by alexander-beedie** [comment]
I can see the use-case, but Decimal isn't (publicly) a 128bit int - it's a Decimal that _happens to be implemented using_ a 128bit int internally. And, as you've discovered, the distinction matters 😅

**Comment by mcrumiller** [comment]
Agree with @alexander-beedie, i128 is an implementation detail. But since we do use 128-bit ints, we *do* have a maximum value. Right now it's artificially set to 10^38-1, when theoretically it could be 2**127-1, which is a 1.7x higher maximum value than 999999.... I can see the rationale in that, in the space of decimals, it makes sense to cap it off at a value of 10^x instead of some seemingly arbitrary number between 10^x and 10^(x+1).

Should we keep the current max, or increase it? Regardless let me poke around and see if I can improve the warning/error behavior.

**Comment by notabeatle** [comment]
I'm currently getting bit by what may be this very issue, processing real data that's flirting with the max for a 128-bit-width Decimal. If there's more head-room there that may be achieved by removing an artificial limitation, that'd be great, even if the resulting max isn't "pretty". Polars is currently the weak-link on this, for me—Python, Parquet, and the databases up and down-stream of my pipeline handle these values just fine.

**Comment by mcrumiller** [comment]
@cdmoye the `Decimal` value is not meant to be a substitute for 128-bit ints. I would say that using `Decimal` to represent `uuid.uuid4().int` is not generally valid. However, I do code related to an internal implementation of a 256-bit decimal, but it does not appear to be exposed to either the python or rust API and perhaps is still in development. @stinodego are you familiar with this and/or can you chime in?

**Comment by stinodego** [comment]
The 256 bit Decimal is an arrow type but not a Polars type. We may support it in the future.

This issue is kept open because we need to handle this panic graciously and throw an error instead.

**Comment by mcrumiller** [comment]
Ok, I will look into the panic.

**Comment by mcrumiller** [comment]
@stinodego the reason is because Decimals can't be created from floats, and `pyo3` is passing in large integers as floats into the `AnyValue` machinery. I narrowed the issue down to [a specific `unwrap`](https://github.com/pola-rs/polars/blob/main/crates/polars-core/src/frame/row/av_buffer.rs#L252), but resolving that would require changing the AnyValue `into_series` logic into the fallible `try_into_series` instead and would hit a few other unrelated areas of the code. Do you think this is the right approach?

I do see that pyo3 has a [BigInt](https://pyo3.rs/main/doc/pyo3/num_bigint/index.html) type (that we use in some places). We may be able to use this in the AnyValue logic.

**Comment by mcrumiller** [comment]
Here is a better example of the actual issue to resolve:

```python
import polars as pl

x = 2**125  # a valid value into Decimal

# succeeds
pl.Series([x], dtype=pl.Decimal)

# fails due to specific AnyValue path
pl.DataFrame([{'x': x}], schema = {'udid': pl.Decimal})
```
```
pyo3_runtime.PanicException: called `Result::unwrap()` on an `Err` value: ComputeError(ErrString("unable to convert any-value of dtype f64 to decimal"))
```

**Comment by coastalwhite** [comment]
Panic is now gone and now gives a:

```shell
pl.Decimal type does not work with 128-bit int
OverflowError('int value too large for Polars integer types: 319030266201958241408806559310635971838')
```
