### ISSUE TITLE
duration-related `dt` expressions do not serialize

### ISSUE THREAD

**Issue by brendancooley** [pola-rs/polars#13989]
### Checks

- [X] I have checked that this issue has not already been reported.
- [X] I have confirmed this bug exists on the [latest version](https://pypi.org/project/polars/) of Polars.

### Reproducible example

```python
import polars as pl
pl.col("duration").dt.total_days().meta.write_json()
```

### Log output

```shell
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/.../.venv/lib/python3.10/site-packages/polars/expr/meta.py", line 235, in write_json
    self._pyexpr.meta_write_json(buf)
ValueError: Error("serialize not supported for this 'opaque' function", line: 0, column: 0)
```

### Issue description

datetime operations serialize as expected
```python
pl.col("datetime").dt.month().meta.write_json()
```

### Expected behavior

```
'{"Function":{"input":[{"Column":"datetime"}],"function":{"TemporalExpr":"Month"},"options":{"collect_groups":"ElementWise","fmt_str":"","input_wildcard_expansion":false,"returns_scalar":false,"cast_to_supertypes":false,"allow_rename":false,"pass_name_to_apply":false,"changes_length":false,"check_lengths":true,"allow_group_aware":true}}}'
```

### Installed versions

<details>

```
--------Version info---------
Polars:               0.20.5
Index type:           UInt32
Platform:             macOS-13.6.3-x86_64-i386-64bit
Python:               3.10.13 (main, Sep 11 2023, 15:37:46) [Clang 12.0.5 (clang-1205.0.22.11)]

----Optional dependencies----
adbc_driver_manager:  <not installed>
cloudpickle:          <not installed>
connectorx:           <not installed>
deltalake:            <not installed>
fsspec:               <not installed>
gevent:               <not installed>
hvplot:               <not installed>
matplotlib:           <not installed>
numpy:                1.26.2
openpyxl:             <not installed>
pandas:               <not installed>
pyarrow:              15.0.0
pydantic:             2.5.3
pyiceberg:            <not installed>
pyxlsb:               <not installed>
sqlalchemy:           <not installed>
xlsx2csv:             <not installed>
xlsxwriter:           <not installed>```

</details>

**Comment by deanm0000** [comment]
I'll close, if issue persists we can reopen
