### ISSUE TITLE
mean, median, mode, ... probably should not work for pl.Categorical

### ISSUE THREAD

**Issue by ghuls** [pola-rs/polars#1401]
#### Are you using Python or Rust?

*Python**.

#### What version of polars are you using?

Latest git.

#### What operating system are you using polars on?

CentOS 7

#### Describe your bug.

mean, median, mode, ... (there might be more operations that do not make much sense for pl.Categorical) probably should not work for pl.Categorical Series.

#### What are the steps to reproduce the behavior?

```
In [57]: cat_series = pl.Series('cat_series', ['a', 'b', 'b', 'c', 'a']).cast(pl.Categorical)

In [58]: cat_series
Out[58]: 
shape: (5,)
Series: 'cat_series' [cat]
[
        "a"
        "b"
        "b"
        "c"
        "a"
]

In [59]: cat_series.mean()
Out[59]: 0.8

In [60]: cat_series.median()
Out[60]: 1.0

In [61]: cat_series.std()
---------------------------------------------------------------------------
NotImplementedError                       Traceback (most recent call last)
<ipython-input-61-48d69c40f0d8> in <module>
----> 1 cat_series.std()
/software/miniconda3/envs/create_cistarget_databases/lib/python3.8/site-packages/polars/eager/series.py in std(self, ddof)
    726 
    727         """
--> 728         return np.std(self.drop_nulls().view(), ddof=ddof)
    729 
    730     def var(self, ddof: int = 1) -> float:

/software/miniconda3/envs/create_cistarget_databases/lib/python3.8/site-packages/polars/eager/series.py in view(self, ignore_nulls)
   1684             assert self.null_count() == 0
   1685 
-> 1686         ptr_type = dtype_to_ctype(self.dtype)
   1687         ptr = self._s.as_single_ptr()
   1688         array = _ptr_to_numpy(ptr, self.len(), ptr_type)
/software/miniconda3/envs/create_cistarget_databases/lib/python3.8/site-packages/polars/datatypes.py in dtype_to_ctype(dtype)
    224         ptr_type = ctypes.c_long
    225     else:
--> 226         raise NotImplementedError
    227     return ptr_type
    228 

NotImplementedError: 

In [62]: cat_series.drop_nulls()
Out[62]: 
shape: (5,)
Series: 'cat_series' [cat]
[
        "a"
        "b"
        "b"
        "c"
        "a"
]

In [63]: cat_series.max()
thread '<unnamed>' panicked at 'not implemented', /software/polars/polars/polars-core/src/chunked_array/ops/aggregate.rs:21:9
---------------------------------------------------------------------------
PanicException                            Traceback (most recent call last)
<ipython-input-63-04a98db2d5ca> in <module>
----> 1 cat_series.max()

/software/miniconda3/envs/create_cistarget_databases/lib/python3.8/site-packages/polars/eager/series.py in max(self)
    706 
    707         """
--> 708         return self._s.max()
    709 
    710     def std(self, ddof: int = 1) -> float:

PanicException: not implemented

In [64]: cat_series.min()
thread '<unnamed>' panicked at 'not implemented', /software/polars/polars/polars-core/src/chunked_array/ops/aggregate.rs:25:9
---------------------------------------------------------------------------
PanicException                            Traceback (most recent call last)
<ipython-input-64-4b7e05a2e026> in <module>
----> 1 cat_series.min()

/software/miniconda3/envs/create_cistarget_databases/lib/python3.8/site-packages/polars/eager/series.py in min(self)
    693 
    694         """
--> 695         return self._s.min()
    696 
    697     def max(self) -> Union[int, float]:

PanicException: not implemented

In [65]: cat_series.mode()
Out[65]: 
shape: (1,)
Series: 'cat_series' [cat]
[
        "a"
]

```

**Comment by ghuls** [comment]
'std' does not work for a categorical series but give results when run on this dataframe:

```python
In [102]: cat_float64_df = pl.DataFrame({'col_1': cat_series, 'col_2': np.array([2.0, 3.0 , 6.0, 7.0, 4.0])})

In [103]: cat_float64_df.median()
thread '<unnamed>' panicked at 'not implemented', /software/polars/polars/polars-core/src/chunked_array/ops/aggregate.rs:33:9
---------------------------------------------------------------------------
PanicException                            Traceback (most recent call last)
<ipython-input-103-8b9dc97982a1> in <module>
----> 1 cat_float64_df.median()

/software/miniconda3/envs/create_cistarget_databases/lib/python3.8/site-packages/polars/eager/frame.py in median(self)
   2746 
   2747         """
-> 2748         return wrap_df(self._df.median())
   2749 
   2750     def quantile(self, quantile: float) -> "DataFrame":

PanicException: not implemented

In [104]: cat_float64_df.std()
Out[104]: 
shape: (1, 2)
┌────────────────────┬───────────────────┐
│ col_1              ┆ col_2             │
│ ---                ┆ ---               │
│ f64                ┆ f64               │
╞════════════════════╪═══════════════════╡
│ 0.8366600265340756 ┆ 2.073644135332772 │
└────────────────────┴───────────────────┘
```

**Comment by ritchie46** [comment]
Yeap, you're right.

**Comment by wleftwich** [comment]
Why not allow mode for pl.Categorical? 
I'm working around by casting back to str.
