### ISSUE TITLE
Irrelevant error message when using native python functions

### ISSUE THREAD

**Issue by arnabanimesh** [pola-rs/polars#14066]
### Checks

- [X] I have checked that this issue has not already been reported.
- [X] I have confirmed this bug exists on the [latest version](https://pypi.org/project/polars/) of Polars.

### Reproducible example

```python
from datetime import datetime
import polars as pl

out_df = pl.read_csv(b"total_time,qty,end_time\n2009,106,2009")
out_df = out_df.select(pl.col("qty"),(pl.lit(datetime(2024,1,1,0,0,0),pl.Datetime)+pl.duration(minutes=max(0,pl.col("end_time").cast(pl.Int64)-pl.col("total_time").cast(pl.Int64)))).dt.strftime("%d-%m-%Y %H:%M").alias("start_time"))
print(out_df)
```

### Log output

```shell
file < 128 rows, no statistics determined
no. of chunks: 1 processed by: 1 threads.
Traceback (most recent call last):
  File "D:\coding\postproc.py", line 7, in <module>
    out_df = out_df.select(pl.col("qty"),(pl.lit(datetime(2024,1,1,0,0,0),pl.Datetime)+pl.duration(minutes=max(0,pl.col("end_time").cast(pl.Int64)-pl.col("total_time").cast(pl.Int64)))).dt.strftime("%d-%m-%Y %H:%M").alias("start_time"))
                                                                                                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Arnab\scoop\apps\python311\current\Lib\site-packages\polars\expr\expr.py", line 149, in __bool__
    raise TypeError(msg)
TypeError: the truth value of an Expr is ambiguous

Hint: use '&' or '|' to logically combine Expr, not 'and'/'or', and use `x.is_in([y,z])` instead of `x in [y,z]` to check membership.
```

### Issue description

Error message not helpful

### Expected behavior

Provide appropriate error message like : "Native Python function `max` is not supported. Try using `pl.max_horizontal` instead"

### Installed versions

<details>

```
--------Version info---------
Polars:               0.20.6
Index type:           UInt32
Platform:             Windows-10-10.0.22631-SP0
Python:               3.11.7 (tags/v3.11.7:fa7a6f2, Dec  4 2023, 19:24:49) [MSC v.1937 64 bit (AMD64)]

----Optional dependencies----
adbc_driver_manager:  <not installed>
cloudpickle:          3.0.0
connectorx:           <not installed>
deltalake:            <not installed>
fsspec:               2023.12.2
gevent:               <not installed>
hvplot:               <not installed>
matplotlib:           3.8.2
numpy:                1.26.2
openpyxl:             3.1.2
pandas:               2.1.4
pyarrow:              14.0.2
pydantic:             <not installed>
pyiceberg:            <not installed>
pyxlsb:               1.0.10
sqlalchemy:           <not installed>
xlsx2csv:             0.8.2
xlsxwriter:           3.1.9
```

</details>

**Comment by arnabanimesh** [comment]
#14062

**Comment by stinodego** [comment]
We can't change the error message here. It's the error message you get when trying to get the truth value of an `Expr`, e.g. `if expr: ...`. Apparently, Python's `max` relies on that internally. Nothing we can do about that.

**Comment by MarcoGorelli** [comment]
Presumably Python at some point does something like
```
if pl.col('a') > 0:
    ...
```
which triggers `(pl.col('a') > 0).__bool__()`, which in turn triggers the error message you were seeing

maybe the list of suggestions could be expanded though, this is a fairly common one to hit - brb
