### ISSUE TITLE
Unclear error messages when using unsupported types in DataFrame and Series operators

### ISSUE THREAD

**Issue by Wainberg** [pola-rs/polars#14086]
### Checks

- [X] I have checked that this issue has not already been reported.
- [X] I have confirmed this bug exists on the [latest version](https://pypi.org/project/polars/) of Polars.

### Reproducible example

```python
>>> s = pl.Series([1, 2, 3])
>>> df = s.to_frame()
>>> s + s.to_pandas()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "polars/series/series.py", line 1023, in __add__
    return self._arithmetic(other, "add", "add_<>")
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "polars/series/series.py", line 994, in _arithmetic
    other = maybe_cast(other, self.dtype)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "polars/datatypes/convert.py", line 501, in maybe_cast
    raise TypeError(msg) from None
TypeError: cannot convert Python type 'Series' to Int64
>>> s.to_pandas() + s
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "pandas/core/ops/common.py", line 76, in new_method
    return method(self, other)
           ^^^^^^^^^^^^^^^^^^^
  File "pandas/core/arraylike.py", line 186, in __add__
    return self._arith_method(other, operator.add)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "pandas/core/series.py", line 6115, in _arith_method
    return base.IndexOpsMixin._arith_method(self, other, op)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "pandas/core/base.py", line 1384, in _arith_method
    return self._construct_result(result, name=res_name)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "pandas/core/series.py", line 6211, in _construct_result
    out = self._constructor(result, index=self.index, dtype=dtype, copy=False)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "pandas/core/series.py", line 492, in __init__
    dtype = self._validate_dtype(dtype)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "pandas/core/generic.py", line 515, in _validate_dtype
    dtype = pandas_dtype(dtype)
            ^^^^^^^^^^^^^^^^^^^
  File "pandas/core/dtypes/common.py", line 1630, in pandas_dtype
    npdtype = np.dtype(dtype)
              ^^^^^^^^^^^^^^^
TypeError: Cannot interpret 'Int64' as a data type
>>> s + s.to_arrow()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "polars/series/series.py", line 1023, in __add__
    return self._arithmetic(other, "add", "add_<>")
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "polars/series/series.py", line 994, in _arithmetic
    other = maybe_cast(other, self.dtype)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "polars/datatypes/convert.py", line 501, in maybe_cast
    raise TypeError(msg) from None
TypeError: cannot convert Python type 'Int64Array' to Int64
>>> s.to_arrow() + s
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "polars/series/series.py", line 1129, in __radd__
    return self._arithmetic(other, "add", "add_<>_rhs")
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "polars/series/series.py", line 994, in _arithmetic
    other = maybe_cast(other, self.dtype)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "polars/datatypes/convert.py", line 501, in maybe_cast
    raise TypeError(msg) from None
TypeError: cannot convert Python type 'Int64Array' to Int64
>>> df + df.to_pandas()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "polars/dataframe/frame.py", line 1548, in __add__
    return self._from_pydf(self._df.add(other._s))
                           ^^^^^^^^^^^^^^^^^^^^^^
polars.exceptions.ComputeError: failed to determine supertype of i64 and object
>>> df.to_pandas() + df
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "pandas/core/ops/common.py", line 76, in new_method
    return method(self, other)
           ^^^^^^^^^^^^^^^^^^^
  File "pandas/core/arraylike.py", line 186, in __add__
    return self._arith_method(other, operator.add)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "pandas/core/frame.py", line 7894, in _arith_method
    self, other = self._align_for_op(other, axis, flex=True, level=None)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "pandas/core/frame.py", line 8167, in _align_for_op
    raise ValueError(
ValueError: Unable to coerce list of <class 'polars.dataframe.frame.DataFrame'> to Series/DataFrame
>>> df + df.to_arrow()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "polars/dataframe/frame.py", line 1548, in __add__
    return self._from_pydf(self._df.add(other._s))
                           ^^^^^^^^^^^^^^^^^^^^^^
polars.exceptions.ComputeError: failed to determine supertype of i64 and object
>>> df.to_arrow() + df
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "polars/dataframe/frame.py", line 1555, in __radd__
    return self + other
           ~~~~~^~~~~~~
  File "polars/dataframe/frame.py", line 1548, in __add__
    return self._from_pydf(self._df.add(other._s))
                           ^^^^^^^^^^^^^^^^^^^^^^
polars.exceptions.ComputeError: failed to determine supertype of i64 and object
```

### Issue description

None of the error messages get at the root cause, which is mixing polars with pandas/PyArrow. 

### Expected behavior

Polars should give the standard Python error message when operating on things with incompatible types:

```python
>>> {} + []
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: unsupported operand type(s) for +: 'dict' and 'list'
```

Ideally you'd also get this error message when doing nonsense like `s + {}` or `... - s` or `df * NotImplementedError`.

### Installed versions

<details>

```
>>> pl.show_versions()
--------Version info---------
Polars:               0.20.5
Index type:           UInt32
Platform:             Linux-4.4.0-22621-Microsoft-x86_64-with-glibc2.35
Python:               3.12.1 | packaged by conda-forge | (main, Dec 23 2023, 08:03:24) [GCC 12.3.0]

----Optional dependencies----
adbc_driver_manager:  <not installed>
cloudpickle:          <not installed>
connectorx:           <not installed>
deltalake:            <not installed>
fsspec:               <not installed>
gevent:               <not installed>
hvplot:               <not installed>
matplotlib:           3.8.2
numpy:                1.26.3
openpyxl:             3.1.2
pandas:               2.2.0
pyarrow:              14.0.2
pydantic:             <not installed>
pyiceberg:            <not installed>
pyxlsb:               <not installed>
sqlalchemy:           <not installed>
xlsx2csv:             0.8.1
xlsxwriter:           3.1.9
```

</details>

**Comment by Wainberg** [comment]
Note that to do this properly for `pandas.DataFrame + polars.DataFrame`, you'd need to set `__pandas_priority__` as discussed at https://github.com/pola-rs/polars/issues/14080, so that it delegates to `polars.DataFrame.__radd__` and not `pandas.DataFrame.__add__`.
