### ISSUE TITLE
Unexpected Behavior of Diagonal Concatenation on Struct Fields

### ISSUE THREAD

**Issue by andrewthad** [pola-rs/polars#14109]
### Checks

- [X] I have checked that this issue has not already been reported.
- [X] I have confirmed this bug exists on the [latest version](https://pypi.org/project/polars/) of Polars.

### Reproducible example

```
>>> import polars
>>> y = polars.DataFrame(None,{"foo":polars.UInt64, "network":polars.Struct({"barg":polars.UInt32})})
>>> z = polars.DataFrame(None,{"foo":polars.UInt64, "network":polars.Struct({"swiz":polars.String})})
>>> polars.concat([y,z],how='diagonal')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/amartin/Data/Development/polars-playground/lib/python3.10/site-packages/polars/functions/eager.py", line 190, in concat
    out = wrap_df(plr.concat_df_diagonal(elems))
polars.exceptions.SchemaError: cannot extend/append UInt32 with String
```

### Issue description

The behavior of a diagonal [concat](https://docs.pola.rs/py-polars/html/reference/api/polars.concat.html#polars.concat) on struct fields is undocumented. But the actual behavior is that polars ignores all of the field name in the struct, perforrms vertical concatenation, and uses the field name from the rightmost dataframe argument. We can see this behavior in this example:

```
>>> y = polars.DataFrame(None,{"foo":polars.UInt64, "network":polars.Struct({"barg":polars.UInt32})})
>>> z = polars.DataFrame(None,{"foo":polars.UInt64, "network":polars.Struct({"blurp":polars.UInt32})})
>>> polars.concat([y,z],how='diagonal').schema
OrderedDict([('foo', UInt64), ('network', Struct({'blurp': UInt32}))])
```

Since the documentation doesn't mention structs or nested fields, it's possible that this is the intended behavior, but it is surprising. My personal preference is that structs be concatenated diagonally in this case. (It would all me to delete a lot of tedious code that patches missing deep columns with nulls.) Depending on the project goals, there are several (mutually exclusive) ways this could be improved:

1. Leave the existing behavior alone. Add an example to the documentation that shows that struct field participating in a diagonal concatenation are concatenated vertically.
2. Throw an exception if diagonal concatenation tries to concatenation structs whose schemata differ in any way. Document this with an example.
3. Change the behavior so that structs are concatenated diagonally. Document this with an example.

### Expected behavior

```
>>> import polars
>>> y = polars.DataFrame(None,{"foo":polars.UInt64, "network":polars.Struct({"barg":polars.UInt32})})
>>> z = polars.DataFrame(None,{"foo":polars.UInt64, "network":polars.Struct({"swiz":polars.String})})
>>> polars.concat([y,z],how='diagonal')
shape: (0, 2)
┌─────┬───────────┐
│ foo ┆ network   │
│ --- ┆ ---       │
│ u64 ┆ struct[2] │
╞═════╪═══════════╡
└─────┴───────────┘
```

### Installed versions

<details>

```
--------Version info---------
Polars:               0.20.5
Index type:           UInt32
Platform:             Linux-6.5.0-15-generic-x86_64-with-glibc2.35
Python:               3.10.12 (main, Nov 20 2023, 15:14:05) [GCC 11.4.0]

----Optional dependencies----
adbc_driver_manager:  <not installed>
cloudpickle:          <not installed>
connectorx:           <not installed>
deltalake:            <not installed>
fsspec:               <not installed>
gevent:               <not installed>
hvplot:               <not installed>
matplotlib:           <not installed>
numpy:                <not installed>
openpyxl:             <not installed>
pandas:               <not installed>
pyarrow:              <not installed>
pydantic:             <not installed>
pyiceberg:            <not installed>
pyxlsb:               <not installed>
sqlalchemy:           <not installed>
xlsx2csv:             <not installed>
xlsxwriter:           <not installed>

```

</details>

**Comment by cmdlineluser** [comment]
Does it need to be `diagonal_relaxed` in this case as the schemas are different?

```python
polars.concat([y,z],how='diagonal_relaxed').schema
# OrderedDict([('foo', UInt64),
#             ('network', Struct({'barg': UInt32, 'swiz': String}))])
```

**Comment by andrewthad** [comment]
Oh, that does what I need. It's actually a little more permissive than what I want (I want to get an error when integer sizes differ, not a cast), but that's not a big deal since I control all the data.

I still think there's at least documentation issue here. All of the documentation for `relaxed` strategies only discusses common supertypes for integral types, and some discussion of struct types would be useful. And also why does the non-relaxed diagonal allow structs to have different field names? That might be an oversight, or it might be intended.

**Comment by cmdlineluser** [comment]
> And also why does the non-relaxed diagonal allow structs to have different field names?

It appears I completely scanned over the `polars.UInt32` same dtype example - apologies.

That would suggest that I am mistaken in thinking `_relaxed` would be needed.
