### ISSUE TITLE
Make unique() and hash_rows() work with null / None columns

### ISSUE THREAD

**Issue by butla** [pola-rs/polars#14100]
### Description

It looks like these functions can work with null values, but the code is preventing that.

An example for `hash_rows` from the [docs](https://docs.pola.rs/py-polars/html/reference/dataframe/api/polars.DataFrame.hash_rows.html#polars.DataFrame.hash_rows) that has nulls in rows works fine:
```python
>>> df = pl.DataFrame(
...     {
...         "foo": [1, None, 3, 4],
...         "ham": ["a", "b", None, "d"],
...     }
... )
>>> df.dtypes
[Int64, String]
>>> df.hash_rows()
shape: (4,)
Series: '' [u64]
[
        13466810634976288179
        16903212301692297511
        15120227826074220218
        17124807185645538643
]
```

But if I'd change it so that the `ham` column has dtype `Null` instead of `String` it'll error out:

```python
>>> df = pl.DataFrame(
...     {
...         "foo": [1, None, 3, 4],
...         "ham": [None, None, None, None],
...     },
... )
>>> df.dtypes
[Int64, Null]
>>> df.hash_rows()
Traceback (most recent call last):
   (...omitted...)
    return wrap_s(self._df.hash_rows(k0, k1, k2, k3))
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
polars.exceptions.InvalidOperationError: `vec_hash_combine` operation not supported for dtype `null`
```

Related: #8030, #11926

**Comment by cmdlineluser** [comment]
I recently encountered this with a "self-join" - I think it may be the same underlying problem:

```python
df.join(df, on=df.columns)

# thread '<unnamed>' panicked at crates/polars-ops/src/frame/join/hash_join/multiple_keys.rs:188:91:
# called `Result::unwrap()` on an `Err` value: 
# InvalidOperation(ErrString("`vec_hash_combine` operation not supported for dtype `null`"))
```

```python
df.join(df, on="ham")

# thread '<unnamed>' panicked at crates/polars-core/src/series/series_trait.rs:60:13:
# PanicException: not implemented
```

**Comment by atellouAyte** [comment]
Not a solution but I was able to make a workaround by casting the Null type columns to String or something else (looking forward to a better fix):
```
import polars as pl
df = pl.DataFrame(
    {
        "integer": [],
        "date": [],
        "float": [],
        "string": [],
    },
).lazy()
print(
    df.select(
        [
            pl.col(field_name).cast(pl.String)
            if isinstance(field_dtype, pl.Null)
            else pl.col(field_name)
            for field_name, field_dtype in df.schema.items()
        ]
    )
    .unique()
    .fetch()
)
```

**Comment by butla** [comment]
Woah, that was expedient :)
