### ISSUE TITLE
Group by operation panic for string column

### ISSUE THREAD

**Issue by paladin158** [pola-rs/polars#14116]
### Checks

- [X] I have checked that this issue has not already been reported.
- [X] I have confirmed this bug exists on the [latest version](https://crates.io/crates/polars) of Polars.

### Reproducible example

```rust
use polars::prelude::*;
use pyo3::prelude::*;
use pyo3_polars::error::PyPolarsErr;
use pyo3_polars::PyDataFrame;

fn custom_fn(s: Series) -> Result<Option<Series>, PolarsError> {
    let n = s.len();
    let res = Series::full_null("s", n, &DataType::Float64);
    Ok(Some(res))
}

#[pyfunction]
fn test(pydf: PyDataFrame, cols: Vec<&str>, by: Vec<&str>) -> PyResult<PyDataFrame> {
    let df: DataFrame = pydf.into();
    let agg_cols = cols
        .iter()
        .map(|&col_name| {
            col(col_name).apply(|s| custom_fn(s), GetOutput::from_type(DataType::Float64))
        })
        .collect::<Vec<_>>();
    let res = df
        .lazy()
        .group_by(&by)
        .agg(agg_cols)
        .collect()
        .map_err(PyPolarsErr::from)?;

    Ok(PyDataFrame(res))
}

#[pymodule]
fn test_module(_py: Python, m: &PyModule) -> PyResult<()> {
    m.add_function(wrap_pyfunction!(test, m)?)?;
    Ok(())
}
```

```python
import polars as pl
from testpkg.test_module import test

df = pl.DataFrame({"a": [1, 2, 3.1], "g": ["a", "a", "a"]})

test(df, ["a"], ["g"])
```

### Log output

```shell
pyo3_runtime.PanicException: called `Result::unwrap()` on an `Err` value: PyErr { type: <class 'KeyError'>, value: KeyError(39), trackback: Some(<trackback object at 0x7fed7a1dbd00>) }
```

### Issue description

Reopened #14091.

There is still error even after updating `pyarrow` to the latest version.

The group_by operation failed on this example when the column "g" contains string. However, when the column "g" contains integers, the code above works fine.

### Expected behavior

No panic behavior.

### Installed versions

<details>

rust side
polars: 0.37.0
pyo3: 0.20.2
pyo3-polars: 0.11.1

python side
pyarrow: 15.0.0

</details>

**Comment by ritchie46** [comment]
What is your rust backtrace?

**Comment by paladin158** [comment]
The first few of stack backtrace:
0: rust_begin_unwind
1: core::panicking::panic_fmt
2: core::result::unwrap_failed
3: <pyo3_polars::PyDataFrame as pyo3::conversion::IntoPy<pyo3::instance::Py<pyo3::types::any::PyAny>>>::into_py
4: test_module::_::__pyfunction_test
5: pyo3::impl_::trampoline::trampoline
6: test_module::_::<impl test_module::test::MakeDef>::DEF::trampoline
7: cfunction_call
               at ...

**Comment by paladin158** [comment]
Do we have any insights about what could go wrong here? Thanks for your help!

**Comment by DaanDD** [comment]
Experiencing the same issue. Not sure where the issue originates from exactly, could be in PyArrow, Polars or pyo3-polars. This issue is probably related: https://github.com/pola-rs/pyo3-polars/issues/61. It occurs when passing a Polars dataframe containing a String series into Python.

Here's the backtrace:

```
called `Result::unwrap()` on an `Err` value: PyErr { type: <class 'KeyError'>, value: KeyError(39), traceback: Some(<traceback object at 0x116f36700>) }
stack backtrace:
   0: rust_begin_unwind
             at /rustc/11f32b73e0dc9287e305b5b9980d24aecdc8c17f/library/std/src/panicking.rs:647:5
   1: core::panicking::panic_fmt
             at /rustc/11f32b73e0dc9287e305b5b9980d24aecdc8c17f/library/core/src/panicking.rs:72:14
   2: core::result::unwrap_failed
             at /rustc/11f32b73e0dc9287e305b5b9980d24aecdc8c17f/library/core/src/result.rs:1649:5
   3: core::result::Result<T,E>::unwrap
             at /rustc/11f32b73e0dc9287e305b5b9980d24aecdc8c17f/library/core/src/result.rs:1073:23
   4: <pyo3_polars::PySeries as pyo3::conversion::IntoPy<pyo3::instance::Py<pyo3::types::any::PyAny>>>::into_py
             at ./pyo3-polars/pyo3-polars/src/lib.rs:169:19
   5: <pyo3_polars::PyDataFrame as pyo3::conversion::IntoPy<pyo3::instance::Py<pyo3::types::any::PyAny>>>::into_py::{{closure}}
             at ./pyo3-polars/pyo3-polars/src/lib.rs:182:22
   6: core::iter::adapters::map::map_fold::{{closure}}
```

The panic occurs when calling PyArrow's `_import_from_c` here: https://github.com/pola-rs/pyo3-polars/blob/main/pyo3-polars/src/ffi/to_py.rs#L18. Only happens with PyArrow 15.0.0, so I guess something might have changed there?

**Comment by YuriiKhomych** [comment]
Hi guys, have the same issue with the latest version of polars:
```
polars = "0.37.0"
pyo3-polars = "0.11.1"
```
When I try to send df with string or binary column into python I'm getting such exception:
```
RUST_BACKTRACE=full cargo run
    Finished dev [unoptimized + debuginfo] target(s) in 0.18s
     Running `target/debug/research`
1. create a Polars dataframe
shape: (1_000_000, 6)
┌─────────────────────┬─────────┬──────────┬──────────┬──────────┬──────────┐
│ time                ┆ market  ┆ open     ┆ high     ┆ low      ┆ close    │
│ ---                 ┆ ---     ┆ ---      ┆ ---      ┆ ---      ┆ ---      │
│ datetime[ms]        ┆ str     ┆ f32      ┆ f32      ┆ f32      ┆ f32      │
╞═════════════════════╪═════════╪══════════╪══════════╪══════════╪══════════╡
│ 1970-02-22 00:00:00 ┆ BINANCE ┆ 0.993068 ┆ 0.393908 ┆ 0.832287 ┆ 0.91719  │
│ 1970-07-15 00:00:00 ┆ BINANCE ┆ 0.931191 ┆ 0.637663 ┆ 0.131723 ┆ 0.932127 │
│ 1970-11-04 00:00:00 ┆ BINANCE ┆ 0.32026  ┆ 0.161253 ┆ 0.942456 ┆ 0.588208 │
│ 1969-07-15 00:00:00 ┆ BINANCE ┆ 0.577883 ┆ 0.467096 ┆ 0.142304 ┆ 0.925859 │
│ 1970-04-16 00:00:00 ┆ BINANCE ┆ 0.128321 ┆ 0.08555  ┆ 0.806424 ┆ 0.242199 │
│ …                   ┆ …       ┆ …        ┆ …        ┆ …        ┆ …        │
│ 1970-06-21 00:00:00 ┆ BINANCE ┆ 0.4554   ┆ 0.628688 ┆ 0.79761  ┆ 0.6254   │
│ 1970-01-12 00:00:00 ┆ BINANCE ┆ 0.370163 ┆ 0.043268 ┆ 0.231372 ┆ 0.532575 │
│ 1970-09-01 00:00:00 ┆ BINANCE ┆ 0.915194 ┆ 0.492398 ┆ 0.087483 ┆ 0.214888 │
│ 1969-05-01 00:00:00 ┆ BINANCE ┆ 0.917355 ┆ 0.147056 ┆ 0.82902  ┆ 0.630131 │
│ 1970-09-11 00:00:00 ┆ BINANCE ┆ 0.281294 ┆ 0.540632 ┆ 0.203651 ┆ 0.510396 │
└─────────────────────┴─────────┴──────────┴──────────┴──────────┴──────────┘
[Datetime(Milliseconds, None), String, Float32, Float32, Float32, Float32]
estimate size of dataframe: 40000000
2. pass Polars dataframe to python
thread 'main' panicked at /Users/yuriikhomych/.cargo/registry/src/index.crates.io-6f17d22bba15001f/pyo3-polars-0.11.1/src/lib.rs:169:49:
called `Result::unwrap()` on an `Err` value: PyErr { type: <class 'KeyError'>, value: KeyError(39), traceback: Some(<traceback object at 0x10abf1740>) }
stack backtrace:
   0:        0x10354fbac - std::backtrace_rs::backtrace::libunwind::trace::h2966c6fbfac9d426
                               at /rustc/82e1608dfa6e0b5569232559e3d385fea5a93112/library/std/src/../../backtrace/src/backtrace/libunwind.rs:104:5
   1:        0x10354fbac - std::backtrace_rs::backtrace::trace_unsynchronized::h8a5f4aefe890b7c5
                               at /rustc/82e1608dfa6e0b5569232559e3d385fea5a93112/library/std/src/../../backtrace/src/backtrace/mod.rs:66:5
   2:        0x10354fbac - std::sys_common::backtrace::_print_fmt::h7574dd98fd39c257
                               at /rustc/82e1608dfa6e0b5569232559e3d385fea5a93112/library/std/src/sys_common/backtrace.rs:67:5
   3:        0x10354fbac - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::h298c9ab285ff3934
                               at /rustc/82e1608dfa6e0b5569232559e3d385fea5a93112/library/std/src/sys_common/backtrace.rs:44:22
   4:        0x10356ca68 - core::fmt::rt::Argument::fmt::hf9661447f7b99899
                               at /rustc/82e1608dfa6e0b5569232559e3d385fea5a93112/library/core/src/fmt/rt.rs:142:9
   5:        0x10356ca68 - core::fmt::write::h4e276abdb6d0c2a1
                               at /rustc/82e1608dfa6e0b5569232559e3d385fea5a93112/library/core/src/fmt/mod.rs:1120:17
   6:        0x10354de80 - std::io::Write::write_fmt::hd421848f5f0bf9d0
                               at /rustc/82e1608dfa6e0b5569232559e3d385fea5a93112/library/std/src/io/mod.rs:1762:15
   7:        0x10354f9e8 - std::sys_common::backtrace::_print::h09e653c6686dbd70
                               at /rustc/82e1608dfa6e0b5569232559e3d385fea5a93112/library/std/src/sys_common/backtrace.rs:47:5
   8:        0x10354f9e8 - std::sys_common::backtrace::print::hd8bd9ecab1f94b94
                               at /rustc/82e1608dfa6e0b5569232559e3d385fea5a93112/library/std/src/sys_common/backtrace.rs:34:9
   9:        0x103550ef4 - std::panicking::default_hook::{{closure}}::h520eeb743fc98fb4
  10:        0x103550c3c - std::panicking::default_hook::ha6550ffe49b63df1
                               at /rustc/82e1608dfa6e0b5569232559e3d385fea5a93112/library/std/src/panicking.rs:292:9
  11:        0x10355131c - std::panicking::rust_panic_with_hook::hddb0e884a202de7c
                               at /rustc/82e1608dfa6e0b5569232559e3d385fea5a93112/library/std/src/panicking.rs:779:13
  12:        0x10355121c - std::panicking::begin_panic_handler::{{closure}}::hd2798398a2fd9077
                               at /rustc/82e1608dfa6e0b5569232559e3d385fea5a93112/library/std/src/panicking.rs:657:13
  13:        0x103550014 - std::sys_common::backtrace::__rust_end_short_backtrace::h9201cc364dbb8a23
                               at /rustc/82e1608dfa6e0b5569232559e3d385fea5a93112/library/std/src/sys_common/backtrace.rs:170:18
  14:        0x103550fb8 - rust_begin_unwind
                               at /rustc/82e1608dfa6e0b5569232559e3d385fea5a93112/library/std/src/panicking.rs:645:5
  15:        0x1035eb608 - core::panicking::panic_fmt::h4d5168028d4c43c7
                               at /rustc/82e1608dfa6e0b5569232559e3d385fea5a93112/library/core/src/panicking.rs:72:14
  16:        0x1035eb9fc - core::result::unwrap_failed::hc60ef978ea39e1b4
                               at /rustc/82e1608dfa6e0b5569232559e3d385fea5a93112/library/core/src/result.rs:1653:5
  17:        0x102204eec - core::result::Result<T,E>::unwrap::hcd99af56382ecf7c
                               at /rustc/82e1608dfa6e0b5569232559e3d385fea5a93112/library/core/src/result.rs:1077:23
  18:        0x10220ada0 - <pyo3_polars::PySeries as pyo3::conversion::IntoPy<pyo3::instance::Py<pyo3::types::any::PyAny>>>::into_py::hc30d3de63f7f1b76
                               at /Users/yuriikhomych/.cargo/registry/src/index.crates.io-6f17d22bba15001f/pyo3-polars-0.11.1/src/lib.rs:169:19
  19:        0x10220b118 - <pyo3_polars::PyDataFrame as pyo3::conversion::IntoPy<pyo3::instance::Py<pyo3::types::any::PyAny>>>::into_py::{{closure}}::h6120ca840bfbd1f5
                               at /Users/yuriikhomych/.cargo/registry/src/index.crates.io-6f17d22bba15001f/pyo3-polars-0.11.1/src/lib.rs:182:22
  20:        0x102204cc4 - core::iter::adapters::map::map_fold::{{closure}}::h705096585aca6044
                               at /rustc/82e1608dfa6e0b5569232559e3d385fea5a93112/library/core/src/iter/adapters/map.rs:84:28
  21:        0x1022094f8 - <core::slice::iter::Iter<T> as core::iter::traits::iterator::Iterator>::fold::h78b2ea8ca16d5758
                               at /rustc/82e1608dfa6e0b5569232559e3d385fea5a93112/library/core/src/slice/iter/macros.rs:232:27
  22:        0x1022038d8 - <core::iter::adapters::map::Map<I,F> as core::iter::traits::iterator::Iterator>::fold::h51e611f41ada75e4
                               at /rustc/82e1608dfa6e0b5569232559e3d385fea5a93112/library/core/src/iter/adapters/map.rs:124:9
  23:        0x102204c58 - core::iter::traits::iterator::Iterator::for_each::haf80cb763bffa18b
                               at /rustc/82e1608dfa6e0b5569232559e3d385fea5a93112/library/core/src/iter/traits/iterator.rs:858:9
  24:        0x102208218 - alloc::vec::Vec<T,A>::extend_trusted::h08630c9e4f8d6be3
                               at /rustc/82e1608dfa6e0b5569232559e3d385fea5a93112/library/alloc/src/vec/mod.rs:2885:17
  25:        0x1022095ec - <alloc::vec::Vec<T,A> as alloc::vec::spec_extend::SpecExtend<T,I>>::spec_extend::ha711b04c6b4fd1dc
                               at /rustc/82e1608dfa6e0b5569232559e3d385fea5a93112/library/alloc/src/vec/spec_extend.rs:26:9
  26:        0x102203ae0 - <alloc::vec::Vec<T> as alloc::vec::spec_from_iter_nested::SpecFromIterNested<T,I>>::from_iter::h8f0cb32f2547374b
                               at /rustc/82e1608dfa6e0b5569232559e3d385fea5a93112/library/alloc/src/vec/spec_from_iter_nested.rs:62:9
  27:        0x102209604 - <alloc::vec::Vec<T> as alloc::vec::spec_from_iter::SpecFromIter<T,I>>::from_iter::heb074cb441a46c26
                               at /rustc/82e1608dfa6e0b5569232559e3d385fea5a93112/library/alloc/src/vec/spec_from_iter.rs:33:9
  28:        0x1022095c8 - <alloc::vec::Vec<T> as core::iter::traits::collect::FromIterator<T>>::from_iter::h61b7869ecb0d8ed4
                               at /rustc/82e1608dfa6e0b5569232559e3d385fea5a93112/library/alloc/src/vec/mod.rs:2753:9
  29:        0x102204c10 - core::iter::traits::iterator::Iterator::collect::h2301d3b87b58ff99
                               at /rustc/82e1608dfa6e0b5569232559e3d385fea5a93112/library/core/src/iter/traits/iterator.rs:2054:9
  30:        0x10220af98 - <pyo3_polars::PyDataFrame as pyo3::conversion::IntoPy<pyo3::instance::Py<pyo3::types::any::PyAny>>>::into_py::h7abb9bbd5ca72517
                               at /Users/yuriikhomych/.cargo/registry/src/index.crates.io-6f17d22bba15001f/pyo3-polars-0.11.1/src/lib.rs:178:24
  31:        0x1021ea6e8 - pyo3::types::tuple::<impl pyo3::conversion::IntoPy<pyo3::instance::Py<pyo3::types::tuple::PyTuple>> for (T0,)>::into_py::h04a6601bb28ff014
                               at /Users/yuriikhomych/.cargo/registry/src/index.crates.io-6f17d22bba15001f/pyo3-0.20.2/src/types/tuple.rs:325:37
  32:        0x1021f1450 - pyo3::instance::Py<T>::call::hbed177974f544382
                               at /Users/yuriikhomych/.cargo/registry/src/index.crates.io-6f17d22bba15001f/pyo3-0.20.2/src/instance.rs:695:20
  33:        0x1021f1598 - pyo3::instance::Py<T>::call1::h981deafc85be0809
                               at /Users/yuriikhomych/.cargo/registry/src/index.crates.io-6f17d22bba15001f/pyo3-0.20.2/src/instance.rs:712:9
  34:        0x1021eb2d0 - research::main::{{closure}}::h3fcab27770284111
                               at /Users/yuriikhomych/istari/pyo3-research/research/src/main.rs:60:19
  35:        0x1021ef08c - pyo3::marker::Python::with_gil::h1eb8ac12d1a15c4d
                               at /Users/yuriikhomych/.cargo/registry/src/index.crates.io-6f17d22bba15001f/pyo3-0.20.2/src/marker.rs:434:9
  36:        0x1021f0544 - research::main::h114305e85f125205
                               at /Users/yuriikhomych/istari/pyo3-research/research/src/main.rs:48:14
  37:        0x1021f0910 - core::ops::function::FnOnce::call_once::hb3c2a8b7ffbf6067
                               at /rustc/82e1608dfa6e0b5569232559e3d385fea5a93112/library/core/src/ops/function.rs:250:5
  38:        0x1021eb6a8 - std::sys_common::backtrace::__rust_begin_short_backtrace::h2288a823a81d5ee5
                               at /rustc/82e1608dfa6e0b5569232559e3d385fea5a93112/library/std/src/sys_common/backtrace.rs:154:18
  39:        0x1021edf98 - std::rt::lang_start::{{closure}}::h4c5bb832b49ef449
                               at /rustc/82e1608dfa6e0b5569232559e3d385fea5a93112/library/std/src/rt.rs:167:18
  40:        0x10354aae8 - core::ops::function::impls::<impl core::ops::function::FnOnce<A> for &F>::call_once::h1a7c0e059d971da5
                               at /rustc/82e1608dfa6e0b5569232559e3d385fea5a93112/library/core/src/ops/function.rs:284:13
  41:        0x10354aae8 - std::panicking::try::do_call::h07a34a23e615022b
                               at /rustc/82e1608dfa6e0b5569232559e3d385fea5a93112/library/std/src/panicking.rs:552:40
  42:        0x10354aae8 - std::panicking::try::h1111644420b4cc09
                               at /rustc/82e1608dfa6e0b5569232559e3d385fea5a93112/library/std/src/panicking.rs:516:19
  43:        0x10354aae8 - std::panic::catch_unwind::h31a3b9d6e2ef9973
                               at /rustc/82e1608dfa6e0b5569232559e3d385fea5a93112/library/std/src/panic.rs:142:14
  44:        0x10354aae8 - std::rt::lang_start_internal::{{closure}}::h63c3452500a36531
                               at /rustc/82e1608dfa6e0b5569232559e3d385fea5a93112/library/std/src/rt.rs:148:48
  45:        0x10354aae8 - std::panicking::try::do_call::h9c5c8a2a0a297bb7
                               at /rustc/82e1608dfa6e0b5569232559e3d385fea5a93112/library/std/src/panicking.rs:552:40
  46:        0x10354aae8 - std::panicking::try::h424cfcafca1bde97
                               at /rustc/82e1608dfa6e0b5569232559e3d385fea5a93112/library/std/src/panicking.rs:516:19
  47:        0x10354aae8 - std::panic::catch_unwind::h345d3d448041017f
                               at /rustc/82e1608dfa6e0b5569232559e3d385fea5a93112/library/std/src/panic.rs:142:14
  48:        0x10354aae8 - std::rt::lang_start_internal::h5b246d44f1526226
                               at /rustc/82e1608dfa6e0b5569232559e3d385fea5a93112/library/std/src/rt.rs:148:20
  49:        0x1021edf5c - std::rt::lang_start::hd94a14c545a7d558
                               at /rustc/82e1608dfa6e0b5569232559e3d385fea5a93112/library/std/src/rt.rs:166:17
  50:        0x1021f0880 - _main
  ```

on these versions everything is working like a charm:

```
polars = "0.36.2"
pyo3-polars = "0.10.0"
```

```
1. create a Polars dataframe
shape: (1_000_000, 6)
┌─────────────────────┬─────────┬──────────┬──────────┬──────────┬──────────┐
│ time                ┆ market  ┆ open     ┆ high     ┆ low      ┆ close    │
│ ---                 ┆ ---     ┆ ---      ┆ ---      ┆ ---      ┆ ---      │
│ datetime[ms]        ┆ str     ┆ f32      ┆ f32      ┆ f32      ┆ f32      │
╞═════════════════════╪═════════╪══════════╪══════════╪══════════╪══════════╡
│ 1970-04-23 00:00:00 ┆ BINANCE ┆ 0.377794 ┆ 0.311562 ┆ 0.852294 ┆ 0.018167 │
│ 1970-03-04 00:00:00 ┆ BINANCE ┆ 0.248263 ┆ 0.985235 ┆ 0.384743 ┆ 0.993637 │
│ 1969-01-27 00:00:00 ┆ BINANCE ┆ 0.228853 ┆ 0.518697 ┆ 0.978462 ┆ 0.800359 │
│ 1970-05-21 00:00:00 ┆ BINANCE ┆ 0.711021 ┆ 0.558778 ┆ 0.970607 ┆ 0.690879 │
│ …                   ┆ …       ┆ …        ┆ …        ┆ …        ┆ …        │
│ 1970-06-16 00:00:00 ┆ BINANCE ┆ 0.34919  ┆ 0.076561 ┆ 0.686683 ┆ 0.499083 │
│ 1970-05-14 00:00:00 ┆ BINANCE ┆ 0.273559 ┆ 0.112252 ┆ 0.287343 ┆ 0.361571 │
│ 1969-07-03 00:00:00 ┆ BINANCE ┆ 0.969665 ┆ 0.551859 ┆ 0.924267 ┆ 0.694692 │
│ 1970-10-20 00:00:00 ┆ BINANCE ┆ 0.446303 ┆ 0.548277 ┆ 0.210237 ┆ 0.729793 │
└─────────────────────┴─────────┴──────────┴──────────┴──────────┴──────────┘
[Datetime(Milliseconds, None), String, Float32, Float32, Float32, Float32]
estimate size of dataframe: 39000008
2. pass Polars dataframe to python
3. python gets dataframe from rust
4. python does some calculations
5. python returns dataframe to rust
5. Got a Polars dataframe back from python
[Datetime(Milliseconds, None), String, Float32, Float32, Float32, Float32, Float32, Float32, Float32, Float32]
estimate size of dataframe: 55000008
shape: (1_000_000, 10)
┌─────────────────────┬─────────┬──────────┬──────────┬───┬───────────────┬───────────────┬──────────────┬────────────────┐
│ time                ┆ market  ┆ open     ┆ high     ┆ … ┆ open_ewm_mean ┆ high_ewm_mean ┆ low_ewm_mean ┆ close_ewm_mean │
│ ---                 ┆ ---     ┆ ---      ┆ ---      ┆   ┆ ---           ┆ ---           ┆ ---          ┆ ---            │
│ datetime[ms]        ┆ str     ┆ f32      ┆ f32      ┆   ┆ f32           ┆ f32           ┆ f32          ┆ f32            │
╞═════════════════════╪═════════╪══════════╪══════════╪═══╪═══════════════╪═══════════════╪══════════════╪════════════════╡
│ 1970-04-23 00:00:00 ┆ BINANCE ┆ 0.377794 ┆ 0.311562 ┆ … ┆ 0.377794      ┆ 0.311562      ┆ 0.852294     ┆ 0.018167       │
│ 1970-03-04 00:00:00 ┆ BINANCE ┆ 0.248263 ┆ 0.985235 ┆ … ┆ 0.291295      ┆ 0.761431      ┆ 0.54007      ┆ 0.669571       │
│ 1969-01-27 00:00:00 ┆ BINANCE ┆ 0.228853 ┆ 0.518697 ┆ … ┆ 0.255511      ┆ 0.622327      ┆ 0.7913       ┆ 0.744522       │
│ 1970-05-21 00:00:00 ┆ BINANCE ┆ 0.711021 ┆ 0.558778 ┆ … ┆ 0.499346      ┆ 0.588309      ┆ 0.887283     ┆ 0.715807       │
│ …                   ┆ …       ┆ …        ┆ …        ┆ … ┆ …             ┆ …             ┆ …            ┆ …              │
│ 1970-06-16 00:00:00 ┆ BINANCE ┆ 0.34919  ┆ 0.076561 ┆ … ┆ 0.323197      ┆ 0.1957        ┆ 0.719744     ┆ 0.589244       │
│ 1970-05-14 00:00:00 ┆ BINANCE ┆ 0.273559 ┆ 0.112252 ┆ … ┆ 0.298253      ┆ 0.153766      ┆ 0.502457     ┆ 0.474835       │
│ 1969-07-03 00:00:00 ┆ BINANCE ┆ 0.969665 ┆ 0.551859 ┆ … ┆ 0.635646      ┆ 0.353813      ┆ 0.714422     ┆ 0.585316       │
│ 1970-10-20 00:00:00 ┆ BINANCE ┆ 0.446303 ┆ 0.548277 ┆ … ┆ 0.540499      ┆ 0.451534      ┆ 0.461063     ┆ 0.657918       │
└─────────────────────┴─────────┴──────────┴──────────┴───┴───────────────┴───────────────┴──────────────┴────────────────┘
```

**Comment by ritchie46** [comment]
Which python polars version do you use?

**Comment by paladin158** [comment]
> Which python polars version do you use? This should only work with python polars 0.20.6

I am using the latest python polars - v0.20.6.

**Comment by paladin158** [comment]
Any updates on this issue?

**Comment by ritchie46** [comment]
Ok, I found the culprit. I believe this is a bug in pyarrow. It doesn't seem to recognize the schema of their new string type yet. I can patch it on our side, but that means we must do a copy.

**Comment by ritchie46** [comment]
Published a patch.

**Comment by ritchie46** [comment]
This makes we realize we can ditch pyarrow completely and make polars a direct arrow consumer. That will elide the copy.

**Comment by ritchie46** [comment]
With `pyo3-polars -0.11.3`  and polars `0.20.7` we don't require pyarrow, no copy and we will also not rechunk. So all should be optimial then. :)
