### ISSUE TITLE
Can't filter Series with NumPy arrays

### ISSUE THREAD

**Issue by Wainberg** [pola-rs/polars#14154]
### Checks

- [X] I have checked that this issue has not already been reported.
- [X] I have confirmed this bug exists on the [latest version](https://pypi.org/project/polars/) of Polars.

### Reproducible example

```python
>>> pl.Series([1]).filter([True])
shape: (1,)
Series: '' [i64]
[
        1
]
>>> pl.Series([1]).filter(pl.Series([True]))
shape: (1,)
Series: '' [i64]
[
        1
]
>>> pl.Series([1]).filter(np.array([True]))
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "polars/series/series.py", line 3250, in filter
    return self._from_pyseries(self._s.filter(predicate._s))
                                              ^^^^^^^^^^^^
AttributeError: 'numpy.ndarray' object has no attribute '_s'
```

### Issue description

Filtering a Series with a NumPy array gives an error, even though it works with a list and a Series. DataFrames work in all three cases:

```python
>>> pl.DataFrame([1]).filter([True])
 column_0
 1
shape: (1, 1)
>>> pl.DataFrame([1]).filter(pl.Series([True]))
 column_0
 1
shape: (1, 1)
>>> pl.DataFrame([1]).filter(np.array([True]))
 column_0
 1
shape: (1, 1)
```

### Expected behavior

Filtering with NumPy arrays should work for Series like it works for DataFrames.

### Installed versions

<details>

```
--------Version info---------
Polars:               0.20.6
Index type:           UInt32
Platform:             Linux-4.18.0-513.5.1.el8_9.x86_64-x86_64-with-glibc2.28
Python:               3.12.1 | packaged by conda-forge | (main, Dec 23 2023, 08:03:24) [GCC 12.3.0]

----Optional dependencies----
adbc_driver_manager:  <not installed>
cloudpickle:          <not installed>
connectorx:           <not installed>
deltalake:            <not installed>
fsspec:               <not installed>
gevent:               <not installed>
hvplot:               <not installed>
matplotlib:           3.8.2
numpy:                1.26.3
openpyxl:             3.1.2
pandas:               2.2.0
pyarrow:              14.0.2
pydantic:             <not installed>
pyiceberg:            <not installed>
pyxlsb:               <not installed>
sqlalchemy:           <not installed>
xlsx2csv:             0.8.1
xlsxwriter:           3.1.9
```

</details>

**Comment by stinodego** [comment]
This should work and it's already up on my whiteboard :+1:
