### ISSUE TITLE
pl.read_csv with raise_if_empty doesn't work when specifying columns

### ISSUE THREAD

**Issue by vitorbaptista** [pola-rs/polars#14213]
### Description

Consider the following example:

```python
import polars as pl

df = pl.read_csv(
    "empty.csv",
    raise_if_empty=False,
    new_columns=["id", "name"],
    dtypes=[pl.Int64, pl.String]
)
```

As the `empty.csv` file is empty, I expected polars to return an empty dataframe with the columns and dtypes set. Similar to what it works if I don't specify the `new_columns` and `dtypes` parameters (just `pl.read_csv("empty.csv", raise_if_empty=False)`, which returns an empty dataframe).

Unfortunately, this is the exception raised:

```
thread '<unnamed>' panicked at crates/polars-io/src/csv/read_impl/mod.rs:219:57:
called `Option::unwrap()` on a `None` value
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
Traceback (most recent call last):
  File "/home/vitor/Projetos/royaltyexchange/royaltyexchange-music-db/polars-example.py", line 3, in <module>
    df = pl.read_csv(
  File "/home/vitor/.pyenv/versions/3.9.13/envs/venv_musicdb/lib/python3.9/site-packages/polars/utils/deprecation.py", line 133, in wrapper
    return function(*args, **kwargs)
  File "/home/vitor/.pyenv/versions/3.9.13/envs/venv_musicdb/lib/python3.9/site-packages/polars/utils/deprecation.py", line 133, in wrapper
    return function(*args, **kwargs)
  File "/home/vitor/.pyenv/versions/3.9.13/envs/venv_musicdb/lib/python3.9/site-packages/polars/utils/deprecation.py", line 133, in wrapper
    return function(*args, **kwargs)
  File "/home/vitor/.pyenv/versions/3.9.13/envs/venv_musicdb/lib/python3.9/site-packages/polars/io/csv/functions.py", line 397, in read_csv
    df = pl.DataFrame._read_csv(
  File "/home/vitor/.pyenv/versions/3.9.13/envs/venv_musicdb/lib/python3.9/site-packages/polars/dataframe/frame.py", line 786, in _read_csv
    self._df = PyDataFrame.read_csv(
pyo3_runtime.PanicException: called `Option::unwrap()` on a `None` value
```

I wrote a helper to change this behavior:

```python
def _read_csv_ignore_empty(*args, **kwargs):
    try:
        return pl.read_csv(*args, **kwargs)
    except pl.exceptions.NoDataError:
        new_columns = kwargs.get("new_columns")
        dtypes = kwargs.get("dtypes")
        schema = None

        if new_columns and dtypes:
            schema = dict(zip(new_columns, dtypes))
        elif new_columns:
            schema = new_columns

        return pl.DataFrame([], schema=schema)
```

And it works. If I use this function instead on the first example, this is what I get:

```
>>> _read_csv_ignore_empty('empty.csv', new_columns=['id', 'name'], dtypes=[pl.Int64, pl.String])
shape: (0, 2)
┌─────┬─────┐
│ id ┆ name │
│ --- ┆ --- │
│ i64 ┆ string │
╞═════╪═════╡
└─────┴─────┘
```

It would be great if this was the default polars' behavior.

What do you folks think?

**Comment by MarcNuebel** [comment]
I think your suggestion would be more clear if you rename it to 
```
pl.read_csv: let `new_columns` create new columns
```
Its not that anything doesnt work, `new_columns` just has a confusing name since it only renames existing columns:
```
new_columns
        Rename columns right after parsing the CSV file. If the given
        list is shorter than the width of the DataFrame the remaining
        columns will have their original name
```

**Comment by rjboczar** [comment]
Possibly related: an error is not raised when reading an empty CSV with `pl.read_csv` if `schema` or `schema_overrides` are passed.
