### ISSUE TITLE
Decoding Arrow Buffers Fails When -1 is Used to Disable Compression

### ISSUE THREAD

**Issue by andrewthad** [pola-rs/polars#14215]
### Checks

- [X] I have checked that this issue has not already been reported.
- [X] I have confirmed this bug exists on the [latest version](https://pypi.org/project/polars/) of Polars.

### Reproducible example

Here is a hexadecimal dump of an arrow file (less than 1KB):

```
4152 524f 5731 0000 ffff ffff 0001 0000 0800 0000 0000 0000
d8ff ffff 0000 0000 0400 0000 0000 0000 0100 0000 0000 0000
2000 0000 0000 0000 0000 0000 0000 0000 0c00 2800 0800 1000
1800 2000 0000 0000 e8ff ffff 0000 0000 0000 0000 0000 0000
1000 0000 0000 0000 0800 1800 0800 1000 0100 0000 0400 0000
c8ff ffff 0000 0000 4000 0000 0000 0000 0100 0000 0000 0000
0200 0000 0000 0000 3000 0000 0000 0000 0000 0000 0000 0000
4000 0000 0000 0000 1000 3800 0800 1000 1800 2000 0000 3000
0300 0000 6167 6500 e8ff ffff 0000 0000 0800 0000 0000 0000
0000 0000 0000 0000 0800 1800 0800 1000 0000 0000 0000 0000
0000 0000 0000 0000 0000 0000 0000 0000 0000 0000 0000 0000
0000 0000 0000 0000 ffff ffff f800 0000 0800 0000 0000 0000
d8ff ffff 0000 0000 0400 0000 0000 0000 0300 0000 0000 0000
2000 0000 0000 0000 2800 0000 0000 0000 0c00 2800 0800 1000
1800 2000 0000 0000 d8ff ffff 0000 0000 0f00 0000 0000 0000
2c00 0000 0000 0000 3c00 0000 0000 0000 5800 0000 0000 0000
0c00 2800 0800 1000 1800 2000 0000 0000 0000 0000 0100 0000
0f00 0000 0000 0000 0000 0000 0000 0000 0000 0000 0200 0000
0000 0000 0000 0000 1000 0000 0000 0000 1000 0000 0000 0000
1700 0000 0000 0000 f8ff ffff 0000 0000 0400 0800 0000 0000
0000 0000 0000 0000 0000 0000 0000 0000 0000 0000 0000 0000
0000 0000 0000 0000 0000 0000 0000 0000 0000 0000 0000 0000
ffff ffff ffff ffff ff7f 0000 0000 0000 ffff ffff ffff ffff
280d 592c 3030 300c 605b 4711 0804 0100 ffff ffff 0000 0000
0800 0000 0000 0000 d8ff ffff 0000 0000 0400 0000 0000 0000
2800 0000 0000 0000 c400 0000 0000 0000 c400 0000 0000 0000
0c00 2800 0800 1000 1800 2000 0000 0000 e8ff ffff 0000 0000
0000 0000 0000 0000 1000 0000 0000 0000 0800 1800 0800 1000
0100 0000 0400 0000 c8ff ffff 0000 0000 4000 0000 0000 0000
0100 0000 0000 0000 0200 0000 0000 0000 3000 0000 0000 0000
0000 0000 0000 0000 4000 0000 0000 0000 1000 3800 0800 1000
1800 2000 0000 3000 0300 0000 6167 6500 e8ff ffff 0000 0000
0800 0000 0000 0000 0000 0000 0000 0000 0800 1800 0800 1000
0000 0000 0000 0000 0000 0000 0000 0000 0000 0000 0100 0000
1001 0000 0000 0000 0001 0000 0000 0000 2800 0000 0000 0000
0801 0000 4152 524f 5731
```

If you paste this into a file `example.hexdump`, then you can run `xxd -r -p example.hexdump > ages.arrow` to create an arrow file. If we load this arrow file with `pyarrow`, it works fine:

```
>>> import pyarrow.feather as pf
>>> pf.read_feather('/home/amartin/Data/Development/haskell-arrow-interchange/output.arrow')
    age
0    40
1    13
2    89
3    44
4    48
5    48
6    48
7    12
8    96
9    91
10   71
11   17
12    8
13    4
14    1
```

But if we try to load it with polars, it fails:

```
>>> import polars
>>> x = polars.read_ipc('/home/amartin/Data/Development/haskell-arrow-interchange/output.arrow')
Could not mmap compressed IPC file, defaulting to normal read. Toggle off 'memory_map' to silence this warning.
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/amartin/Data/Development/polars-playground/lib/python3.10/site-packages/polars/utils/deprecation.py", line 133, in wrapper
    return function(*args, **kwargs)
  File "/home/amartin/Data/Development/polars-playground/lib/python3.10/site-packages/polars/utils/deprecation.py", line 133, in wrapper
    return function(*args, **kwargs)
  File "/home/amartin/Data/Development/polars-playground/lib/python3.10/site-packages/polars/io/ipc/functions.py", line 103, in read_ipc
    return pl.DataFrame._read_ipc(
  File "/home/amartin/Data/Development/polars-playground/lib/python3.10/site-packages/polars/dataframe/frame.py", line 987, in _read_ipc
    self._df = PyDataFrame.read_ipc(
OSError: LZ4 error: ERROR_frameType_unknown
```

### Issue description

I've done a few other experiments with an in-house tool that exports data in the arrow format (feather v2), and the arrow file feature that seems to trigger this is disabling compression by setting an uncompressed buffer length to -1. Here is the relevant part of arrow's flatbuffer schema definition:

```
/// Provided for forward compatibility in case we need to support different                                                                              
/// strategies for compressing the IPC message body (like whole-body
/// compression rather than buffer-level) in the future                                                                                                  
enum BodyCompressionMethod:byte {                                                                                                                        
  /// Each constituent buffer is first compressed with the indicated                                                                                     
  /// compressor, and then written with the uncompressed length in the first 8
  /// bytes as a 64-bit little-endian signed integer followed by the compressed
  /// buffer bytes (and then padding as required by the protocol). The
  /// uncompressed length may be set to -1 to indicate that the data that
  /// follows is not compressed, which can be useful for cases where
  /// compression does not yield appreciable savings.
  BUFFER                       
}                  
```

The arrow file format lets you do this so that compression may be selectively disabled on a per-buffer basis. The bad behavior in polars that I observe happens when I use LZ4 Frame compression. I'm not sure about zstd since I don't produce feather files that use that one. I suspect that polars isn't special-casing the uncompressed length of -1, and then it feeds the buffer into lz4's decompress routine, which leads to failure.

### Expected behavior

The expected behavior is that polars decodes the arrow file. The python example using pyarrow (given in the Reproducible Example section) shows what the decoded data should be.

### Installed versions

<details>

```
--------Version info---------
Polars:               0.20.6
Index type:           UInt32
Platform:             Linux-6.5.0-15-generic-x86_64-with-glibc2.35
Python:               3.10.12 (main, Nov 20 2023, 15:14:05) [GCC 11.4.0]

----Optional dependencies----
adbc_driver_manager:  <not installed>
cloudpickle:          <not installed>
connectorx:           <not installed>
deltalake:            <not installed>
fsspec:               <not installed>
gevent:               <not installed>
hvplot:               <not installed>
matplotlib:           <not installed>
numpy:                1.26.3
openpyxl:             <not installed>
pandas:               2.2.0
pyarrow:              15.0.0
pydantic:             <not installed>
pyiceberg:            <not installed>
pyxlsb:               <not installed>
sqlalchemy:           <not installed>
xlsx2csv:             <not installed>
xlsxwriter:           <not installed>
```

</details>

**Comment by utkarshgupta137** [comment]
Had the same issue with zstd. You can workaround this using `use_pyarrow=True`. (Needs a proper fix in the polars reader as well)
