### ISSUE TITLE
SQL joins cannot be "chained"

### ISSUE THREAD

**Issue by michiel-de-muynck** [pola-rs/polars#14217]
### Checks

- [X] I have checked that this issue has not already been reported.
- [X] I have confirmed this bug exists on the [latest version](https://crates.io/crates/polars) of Polars.

### Reproducible example

```rust
use polars;
use polars::prelude::*;

fn main() {
    let mut ctx = polars::sql::SQLContext::new();
    
    let df1 = df! {
        "a" => [1, 2, 3],
        "b" => [4, 5, 6],
    }
    .unwrap();

    let df2 = df! {
        "b" => [4, 5, 6],
        "c" => [7, 8, 9]
    }
    .unwrap();

    let df3 = df! {
        "c" => [7, 8, 9],
        "d" => [10, 11, 12],
    }
    .unwrap();

    ctx.register("df1", df1.lazy());
    ctx.register("df2", df2.lazy());
    ctx.register("df3", df3.lazy());
    
    let sql = r#"
        SELECT * FROM df1
        INNER JOIN df2 ON df1.b = df2.b
        INNER JOIN df3 ON df2.c = df3.c
    "#;

    let result = ctx.execute(sql).unwrap();
    
    println!("{:?}", result.collect());
}
```

### Log output

```shell
thread 'main' panicked at src/main.rs:35:35:
called `Result::unwrap()` on an `Err` value: InvalidOperation(ErrString("collect_compound_identifiers: left_name=\"df1\", right_name=\"df3\", tbl_a=\"df2\", tbl_b=\"df3\""))
stack backtrace:
   0: rust_begin_unwind
             at /rustc/82e1608dfa6e0b5569232559e3d385fea5a93112/library/std/src/panicking.rs:645:5
   1: core::panicking::panic_fmt
             at /rustc/82e1608dfa6e0b5569232559e3d385fea5a93112/library/core/src/panicking.rs:72:14
   2: core::result::unwrap_failed
             at /rustc/82e1608dfa6e0b5569232559e3d385fea5a93112/library/core/src/result.rs:1653:5
   3: core::result::Result<T,E>::unwrap
             at /rustc/82e1608dfa6e0b5569232559e3d385fea5a93112/library/core/src/result.rs:1077:23
   4: polars_issue::main
             at ./src/main.rs:35:18
   5: core::ops::function::FnOnce::call_once
             at /rustc/82e1608dfa6e0b5569232559e3d385fea5a93112/library/core/src/ops/function.rs:250:5
```

### Issue description

When joining 3+ tables as such:
```SQL
SELECT *
FROM a ON ...
JOIN b ON ...
JOIN c ON b.x = c.x
```
Polars fails to compile this SQL query because the last join expression refers to table `b`, but only the first table (`a`) and the last/current table (`c`) can be referred to. However, column `x` may not exist in table `a`.

### Expected behavior

It should be possible to refer to all columns that have been joined so far.

### Installed versions

<details>

sql, lazy

</details>

**Comment by alexander-beedie** [comment]
Feels like this is related to https://github.com/pola-rs/polars/issues/13618.
