### ISSUE TITLE
`Series.to_numpy` doesn't work for Array types with nulls

### ISSUE THREAD

**Issue by stinodego** [pola-rs/polars#14268]
### Checks

- [X] I have checked that this issue has not already been reported.
- [X] I have confirmed this bug exists on the [latest version](https://pypi.org/project/polars/) of Polars.

### Reproducible example

```python
import polars as pl

values = [[1, 2], [3, 4], None]
dtype = pl.Array(pl.Int8, 2)
s = pl.Series(values=values, dtype=dtype)

result = s.to_numpy()
```

### Log output

```shell
Traceback (most recent call last):
  File "/home/stijn/code/polars/py-polars/repro.py", line 14, in <module>
    print(s.to_numpy())
          ^^^^^^^^^^^^
  File "/home/stijn/code/polars/py-polars/polars/series/series.py", line 4365, in to_numpy
    np_array.shape = (self.len(), self.dtype.width)  # type: ignore[attr-defined]
    ^^^^^^^^^^^^^^
ValueError: cannot reshape array of size 5 into shape (3,2)
```

### Issue description

The problem is that after the explode, the size of the array is not `len * width`, because the null value is only present once (instead of `width` times).

### Expected behavior

I would expect an ndarray of `f32` type with values `[[1.0, 2.0], [3.0, 4.0], [nan, nan]]`.

### Installed versions

main

**Comment by stinodego** [comment]
I think the current behavior of `explode` for arrays is OK. We should address this in `Series.to_numpy`.

Not sure what the right approach is. If we can access the Array values + validity mask directly in Rust, that would be useful so we can address this issue at least. I wouldn't want to expose any new methods in the Python API for this though.

**Comment by stinodego** [comment]
I think @ritchie46 already had some idea on how to address this, so I'll defer to him on this one.
