### ISSUE TITLE
`DataFrame.explode()` errors on string columns

### ISSUE THREAD

**Issue by etiennebacher** [pola-rs/polars#14284]
### Checks

- [X] I have checked that this issue has not already been reported.
- [X] I have confirmed this bug exists on the [latest version](https://pypi.org/project/polars/) of Polars.

### Reproducible example

```python
import polars as pl

df = pl.DataFrame({"letters": ["aa", "bbb"]})
df.explode("letters")
```

### Log output

```shell
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Python311\Lib\site-packages\polars\dataframe\frame.py", line 7268, in explode  
    return self.lazy().explode(columns, *more_columns).collect(_eager=True)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python311\Lib\site-packages\polars\lazyframe\frame.py", line 1940, in collect  
    return wrap_df(ldf.collect())
                   ^^^^^^^^^^^^^
polars.exceptions.InvalidOperationError: `explode` operation not supported for dtype `str`
```

### Issue description

The documentation for [`DataFrame.explode()`](https://docs.pola.rs/docs/python/dev/reference/dataframe/api/polars.DataFrame.explode.html) says that the arg `columns` is:

>  Column names, expressions, or a selector defining them. The underlying columns being exploded must be of List or String datatype.

However, in the example above, exploding a string column throws an error.

### Expected behavior

Not sure if this is a bug or a mistake in the docs.

### Installed versions

<details>

```
--------Version info---------
Polars:               0.20.7
Index type:           UInt32
Platform:             Windows-10-10.0.19044-SP0
Python:               3.11.0 (main, Oct 24 2022, 18:26:48) [MSC v.1933 64 bit (AMD64)]

----Optional dependencies----
adbc_driver_manager:  <not installed>
cloudpickle:          <not installed>
connectorx:           <not installed>
deltalake:            <not installed>
fsspec:               2023.6.0
gevent:               <not installed>
hvplot:               <not installed>
matplotlib:           3.7.1
numpy:                1.24.3
openpyxl:             <not installed>
pandas:               2.0.3
pyarrow:              12.0.1
pydantic:             <not installed>
pyiceberg:            <not installed>
pyxlsb:               <not installed>
sqlalchemy:           <not installed>
xlsx2csv:             <not installed>
xlsxwriter:           <not installed>
```

</details>

**Comment by stinodego** [comment]
This was recently changed - it should mention `List` or `Array`.
