### ISSUE TITLE
Cryptic error message when empty list is passed to all_horizontal

### ISSUE THREAD

**Issue by antonioalegria** [pola-rs/polars#14287]
### Checks

- [X] I have checked that this issue has not already been reported.
- [X] I have confirmed this bug exists on the [latest version](https://pypi.org/project/polars/) of Polars.

### Reproducible example

```python
df = pl.DataFrame(
    {
        "a": [False, False, True, True, False, None],
        "b": [False, True, True, None, None, None],
        "c": ["u", "v", "w", "x", "y", "z"],
    }
)

result = df.filter(pl.all_horizontal([])) # BOOM: ComputeError: cannot return empty fold because the number of output rows is unknown
```

### Log output

```shell
Traceback (most recent call last):
  File "test.py", line 66, in <module>
    result = df.filter(pl.all_horizontal([]))
                       ^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/polars/functions/aggregation/horizontal.py", line 62, in all_horizontal
    return wrap_expr(plr.all_horizontal(pyexprs))
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^
polars.exceptions.ComputeError: cannot return empty fold because the number of output rows is unknown
```

### Issue description

The error message is too cryptic. Actually this should either not result in an error or it should give a more explicit error for the arguments of all_horizontal

### Expected behavior

Either not raise an error, and yield False, or raise a more explanatory error.

### Installed versions

<details>

```
Replace this line with the output of pl.show_versions(). Leave the backticks in place.
```
--------Version info---------
Polars:               0.20.7
Index type:           UInt32
Platform:             macOS-14.2.1-arm64-arm-64bit
Python:               3.11.6 (main, Oct  2 2023, 20:46:14) [Clang 14.0.3 (clang-1403.0.22.14.1)]

----Optional dependencies----
adbc_driver_manager:  <not installed>
cloudpickle:          2.2.1
connectorx:           <not installed>
deltalake:            <not installed>
fsspec:               2023.6.0
gevent:               <not installed>
hvplot:               <not installed>
matplotlib:           3.7.1
numpy:                1.24.3
openpyxl:             3.1.2
pandas:               1.5.3
pyarrow:              12.0.1
pydantic:             1.10.9
pyiceberg:            <not installed>
pyxlsb:               <not installed>
sqlalchemy:           2.0.18
xlsx2csv:             <not installed>
xlsxwriter:           <not installed>
</details>

**Comment by deanm0000** [comment]
I'll grant you the error is a bit cryptic but if we set that aside for a moment, under the scenario where it doesn't raise an error, what would you expect it to return?

**Comment by antonioalegria** [comment]
I think raising an error is fine. It could also not raise an error and yield the same result as False. Though that would have to be consistent with other equivalent operations in polars (I don't know enough to say right now).

**Comment by cmdlineluser** [comment]
Just for reference, the error arose from the discussion here:

- https://github.com/pola-rs/polars/pull/12106
