### ISSUE TITLE
Installation of `polars-u64-idx["all"]` fails successfully and provides `polars` instead

### ISSUE THREAD

**Issue by christianrickert** [pola-rs/polars#14301]
### Checks

- [X] I have checked that this issue has not already been reported.
- [X] I have confirmed this bug exists on the [latest version](https://pypi.org/project/polars/) of Polars.

### Reproducible example

I ran into `polars` default size limitation for number of rows.

Looks like this issue has been identified and addressed, so I could follow the "Going big..." [instructions](https://pypi.org/project/polars-u64-idx).
However, after installation of `polars-u64-idx["all"]` the size limitation seems to remain:

Example:
```Python
import numpy as np
import polars as pl

big_array = np.empty((2**16, 2**16))
print(big_array)

big_arrow = pl.from_numpy(big_array.ravel(), schema=["pixls"], orient="col")
print(big_arrow)
```

The above code produced a `PanicException`:
```Terminal
python go_big.py
[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]
thread '<unnamed>' panicked at /Users/runner/work/polars/polars/crates/polars-core/src/chunked_array/ops/chunkops.rs:83:62:
polars' maximum length reached. Consider installing 'polars-u64-idx'.: TryFromIntError(())
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
Traceback (most recent call last):
  File "/Users/christianrickert/Desktop/go_big.py", line 7, in <module>
    big_arrow = pl.from_numpy(big_array.ravel(), schema=["pixls"], orient="col")
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/anaconda3/envs/laquacco/lib/python3.12/site-packages/polars/convert.py", line 498, in from_numpy
    return pl.DataFrame._from_numpy(
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/anaconda3/envs/laquacco/lib/python3.12/site-packages/polars/dataframe/frame.py", line 554, in _from_numpy
    numpy_to_pydf(
  File "/opt/homebrew/anaconda3/envs/laquacco/lib/python3.12/site-packages/polars/utils/_construction.py", line 1436, in numpy_to_pydf
    pl.Series(
  File "/opt/homebrew/anaconda3/envs/laquacco/lib/python3.12/site-packages/polars/series/series.py", line 293, in __init__
    self._s = numpy_to_pyseries(
              ^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/anaconda3/envs/laquacco/lib/python3.12/site-packages/polars/utils/_construction.py", line 228, in numpy_to_pyseries
    return constructor(
           ^^^^^^^^^^^^
pyo3_runtime.PanicException: polars' maximum length reached. Consider installing 'polars-u64-idx'.: TryFromIntError(())
```
In a second step, I removed `polars` to make sure I'm actually using the "Going big..." version:
```Terminal
pip uninstall polars
Found existing installation: polars 0.19.12
Uninstalling polars-0.19.12:
  Would remove:
    /opt/homebrew/anaconda3/envs/laquacco/lib/python3.12/site-packages/polars-0.19.12.dist-info/*
    /opt/homebrew/anaconda3/envs/laquacco/lib/python3.12/site-packages/polars/*
  Would not remove (might be manually added):
    /opt/homebrew/anaconda3/envs/laquacco/lib/python3.12/site-packages/polars/_cpu_check.py
    /opt/homebrew/anaconda3/envs/laquacco/lib/python3.12/site-packages/polars/_cpu_check.py''
    /opt/homebrew/anaconda3/envs/laquacco/lib/python3.12/site-packages/polars/functions/len.py
    /opt/homebrew/anaconda3/envs/laquacco/lib/python3.12/site-packages/polars/lazyframe/in_process.py
    /opt/homebrew/anaconda3/envs/laquacco/lib/python3.12/site-packages/polars/meta/__init__.py
    /opt/homebrew/anaconda3/envs/laquacco/lib/python3.12/site-packages/polars/meta/build.py
    /opt/homebrew/anaconda3/envs/laquacco/lib/python3.12/site-packages/polars/meta/index_type.py
    /opt/homebrew/anaconda3/envs/laquacco/lib/python3.12/site-packages/polars/meta/thread_pool.py
    /opt/homebrew/anaconda3/envs/laquacco/lib/python3.12/site-packages/polars/meta/versions.py
    /opt/homebrew/anaconda3/envs/laquacco/lib/python3.12/site-packages/polars/utils/_polars_version.py
    /opt/homebrew/anaconda3/envs/laquacco/lib/python3.12/site-packages/polars/utils/unstable.py
Proceed (Y/n)? y
  Successfully uninstalled polars-0.19.12
```
Then, in a third step, I installed `polars-u64-idx` alone:
```Terminal
pip install polars-u64-idx
Requirement already satisfied: polars-u64-idx in /opt/homebrew/anaconda3/envs/laquacco/lib/python3.12/site-packages (0.20.7)
```
But the example code fails to run successfully:
```Terminal
python go_big.py          
[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]
Traceback (most recent call last):
  File "/Users/christianrickert/Desktop/go_big.py", line 7, in <module>
    big_arrow = pl.from_numpy(big_array.ravel(), schema=["pixls"], orient="col")
                ^^^^^^^^^^^^^
AttributeError: module 'polars' has no attribute 'from_numpy'
```
In a fourth step, I uninstalled `polars-u64-idx`:
```Terminal
pip uninstall polars-u64-idx
Found existing installation: polars-u64-idx 0.20.7
Uninstalling polars-u64-idx-0.20.7:
  Would remove:
    /opt/homebrew/anaconda3/envs/laquacco/lib/python3.12/site-packages/polars/_cpu_check.py
    /opt/homebrew/anaconda3/envs/laquacco/lib/python3.12/site-packages/polars/_cpu_check.py''
    /opt/homebrew/anaconda3/envs/laquacco/lib/python3.12/site-packages/polars/functions/len.py
    /opt/homebrew/anaconda3/envs/laquacco/lib/python3.12/site-packages/polars/lazyframe/in_process.py
    /opt/homebrew/anaconda3/envs/laquacco/lib/python3.12/site-packages/polars/meta/*
    /opt/homebrew/anaconda3/envs/laquacco/lib/python3.12/site-packages/polars/utils/_polars_version.py
    /opt/homebrew/anaconda3/envs/laquacco/lib/python3.12/site-packages/polars/utils/unstable.py
    /opt/homebrew/anaconda3/envs/laquacco/lib/python3.12/site-packages/polars_u64_idx-0.20.7.dist-info/*
    /opt/homebrew/anaconda3/envs/laquacco/lib/python3.12/site-packages/rust-toolchain.toml
Proceed (Y/n)? y
  Successfully uninstalled polars-u64-idx-0.20.7
```
And, in step number five, I installed `polars-u64-idx` again:
```Terminal
pip install polars-u64-idx
Collecting polars-u64-idx
  Using cached polars_u64_idx-0.20.7-cp38-abi3-macosx_11_0_arm64.whl.metadata (15 kB)
Using cached polars_u64_idx-0.20.7-cp38-abi3-macosx_11_0_arm64.whl (25.2 MB)
Installing collected packages: polars-u64-idx
Successfully installed polars-u64-idx-0.20.7
```
Now, the example code finally executes successfully:
```Terminal
python go_big.py
[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]
shape: (4_294_967_296, 1)
┌───────┐
│ pixls │
│ ---   │
│ f64   │
╞═══════╡
│ 0.0   │
│ 0.0   │
│ 0.0   │
│ 0.0   │
│ 0.0   │
│ …     │
│ 0.0   │
│ 0.0   │
│ 0.0   │
│ 0.0   │
│ 0.0   │
└───────┘
```
Okay.

### Issue description

It looks to me like the `["all"]` option pulls in `polars` (0.19.12) additionally which masks `polars-u64-idx` (0.20.7) and leaves the latter version broken when uninstalled.
Explicit removal of `polars`, `polars-u64-idx`, and explicit installation of `polars-u64-idx` then produces a working "Going big..." version of `polars`.

### Expected behavior

`polars-u64-idx["all"]` should provide `polars-u64-idx` plus extras and not `polars` plus extras.

### Installed versions

<details>

```
Python 3.12.1 | packaged by Anaconda, Inc. | (main, Jan 19 2024, 09:45:58) [Clang 14.0.6 ] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import polars
>>> polars.show_versions()
--------Version info---------
Polars:               0.20.7
Index type:           UInt64
Platform:             macOS-14.3-arm64-arm-64bit
Python:               3.12.1 | packaged by Anaconda, Inc. | (main, Jan 19 2024, 09:45:58) [Clang 14.0.6 ]

----Optional dependencies----
adbc_driver_manager:  0.9.0
cloudpickle:          3.0.0
connectorx:           <not installed>
deltalake:            0.15.2
fsspec:               2023.12.2
gevent:               23.9.1
hvplot:               <not installed>
matplotlib:           3.8.0
numpy:                1.26.3
openpyxl:             <not installed>
pandas:               2.2.0
pyarrow:              15.0.0
pydantic:             2.6.1
pyiceberg:            0.5.1
pyxlsb:               <not installed>
sqlalchemy:           2.0.25
xlsx2csv:             0.8.2
xlsxwriter:           3.1.9
>>> 
```

</details>

**Comment by knl** [comment]
I noticed that when doing `uv pip install polars-u64-idx[pyarrow]` works as expected and installs the version with 64bit index. However, `uv pip install polars-u64-idx[pyarrow,pandas]` brings in regular polars that shadows the version with 64bit index.

**Comment by christianrickert** [comment]
Thanks for looking into this issue!
