### ISSUE TITLE
Polars can't read RLE boolean Parquet files written by PyArrow 14+

### ISSUE THREAD

**Issue by mattaubury** [pola-rs/polars#14333]
### Checks

- [X] I have checked that this issue has not already been reported.
- [X] I have confirmed this bug exists on the [latest version](https://pypi.org/project/polars/) of Polars.

### Reproducible example

```python
import pyarrow as pa
import pyarrow.parquet as pq
import polars as pl

# create a table with booleans in it
table = pa.table(
    {"a": [True, False, True, False, True, False, True, False, True, False]}
)

# write it to parquet
pq.write_table(table, "bools.parquet", data_page_version="2.0")

# read it back using polars
df = pl.read_parquet("bools.parquet")
```

### Log output

```shell
$ POLARS_VERBOSE=1 python pyarrow_polars.py
Traceback (most recent call last):
  File "/physical/gpfs/carp2-home/car_home02/data_files/jcs/maubury/jca/juggernaut/pyarrow_polars.py", line 14, in <module>
    df = pl.read_parquet("bools.parquet")
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/maubury/.conda/envs/juggernaut/lib/python3.11/site-packages/polars/utils/deprecation.py", line 136, in wrapper
    return function(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/maubury/.conda/envs/juggernaut/lib/python3.11/site-packages/polars/utils/deprecation.py", line 136, in wrapper
    return function(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/maubury/.conda/envs/juggernaut/lib/python3.11/site-packages/polars/io/parquet/functions.py", line 191, in read_parquet
    return lf.collect(no_optimization=True)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/maubury/.conda/envs/juggernaut/lib/python3.11/site-packages/polars/lazyframe/frame.py", line 1940, in collect
    return wrap_df(ldf.collect())
                   ^^^^^^^^^^^^^
polars.exceptions.ComputeError: Decoding Boolean "Rle"-encoded optional  parquet pages not yet implemented
```

### Issue description

Tested with pyarrow-14.0.1 (or pyarrow-15.0.0) and polars-0.20.7. It works with pyarrow-13.0.2 and earlier.

### Expected behavior

No error

### Installed versions

<details>

```
--------Version info---------
Polars:               0.20.7
Index type:           UInt64
Platform:             Linux-4.18.0-372.32.1.el8_6.x86_64-x86_64-with-glibc2.28
Python:               3.11.0 | packaged by conda-forge | (main, Jan 14 2023, 12:27:40) [GCC 11.3.0]

----Optional dependencies----
adbc_driver_manager:  <not installed>
cloudpickle:          3.0.0
connectorx:           <not installed>
deltalake:            <not installed>
fsspec:               2023.12.2
gevent:               <not installed>
hvplot:               <not installed>
matplotlib:           3.8.2
numpy:                1.26.3
openpyxl:             3.1.2
pandas:               2.1.4
pyarrow:              15.0.0
pydantic:             2.5.3
pyiceberg:            <not installed>
pyxlsb:               <not installed>
sqlalchemy:           <not installed>
xlsx2csv:             <not installed>
xlsxwriter:           <not installed>
```

</details>

**Comment by ritchie46** [comment]
I cannot reproduce? Anybody else?
