### ISSUE TITLE
read_csv followed by map_elements panics when number of rows exceeds threshold

### ISSUE THREAD

**Issue by lee170** [pola-rs/polars#14390]
### Checks

- [X] I have checked that this issue has not already been reported.
- [X] I have confirmed this bug exists on the [latest version](https://pypi.org/project/polars/) of Polars.

### Reproducible example

```python
import polars as pl
import argparse

def show_panic(list_mult):
    # create list of 30 date strings of the form 2023-12-01 to 2023-12-30,
    # repeated list_mult times, for a length of 30 * list_mult
    dates = [f"2023-12-{'0'*(i < 10)}{i}" for i in range(1,31)] * list_mult

    # make dataframe and save to file
    df = pl.DataFrame({"date": dates})
    df.write_csv('panic_date_strings.csv')

    # using the created list of date strings, convert to date type, and map a function to dates
    # this runs fine regardless of number of rows
    df = df.with_columns(pl.col('date').str.strptime(pl.Date, format="%Y-%m-%d").alias('calendar_date'))
    df = df.with_columns(pl.col('calendar_date').map_elements(lambda x: x.weekday()).alias('weekday'))

    print(df.head())

    # read in the created date strings from previously saved file
    fdf = pl.read_csv('panic_date_strings.csv')

    # convert strings to date
    fdf = fdf.with_columns(pl.col('date').str.strptime(pl.Date, format="%Y-%m-%d").alias('calendar_date'))

    # this code panics when list_mult >= 69
    fdf = fdf.with_columns(pl.col('calendar_date').map_elements(lambda x: x.weekday()).alias('weekday'))

    print(fdf.head())

if __name__ == "__main__":
    parser = argparse.ArgumentParser(description="demonstrate map_elements panic")
    parser.add_argument('list_multiplier', help="multiply list of 30 dates by this amount")
    args = parser.parse_args()

    show_panic(int(args.list_multiplier))
```

### Log output

```shell
(base) iMac:dpr lee$ python panic_dates.py 69
shape: (5, 3)
┌────────────┬───────────────┬─────────┐
│ date       ┆ calendar_date ┆ weekday │
│ ---        ┆ ---           ┆ ---     │
│ str        ┆ date          ┆ i64     │
╞════════════╪═══════════════╪═════════╡
│ 2023-12-01 ┆ 2023-12-01    ┆ 4       │
│ 2023-12-02 ┆ 2023-12-02    ┆ 5       │
│ 2023-12-03 ┆ 2023-12-03    ┆ 6       │
│ 2023-12-04 ┆ 2023-12-04    ┆ 0       │
│ 2023-12-05 ┆ 2023-12-05    ┆ 1       │
└────────────┴───────────────┴─────────┘
avg line length: 11                                                           
std. dev. line length: 0                    
initial row estimate: 2070
no. of chunks: 8 processed by: 8 threads.
thread '<unnamed>' panicked at crates/polars-core/src/series/iterator.rs:74:9:
assertion `left == right` failed: impl error                                 
  left: 8                
 right: 1                         
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace                          
--- PyO3 is resuming a panic after fetching a PanicException from Python. ---
Python stack trace below:                  
Traceback (most recent call last):                                                                   
  File "/Users/lee/miniconda3/lib/python3.11/site-packages/polars/expr/expr.py", line 4021, in __call__
    result = self.function(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^                                                                    
  File "/Users/lee/miniconda3/lib/python3.11/site-packages/polars/expr/expr.py", line 4356, in wrap_f
    return x.map_elements(                                               
           ^^^^^^^^^^^^^^^
  File "/Users/lee/miniconda3/lib/python3.11/site-packages/polars/series/series.py", line 5335, in map_elements
    self._s.apply_lambda(function, pl_return_dtype, skip_nulls)
pyo3_runtime.PanicException: assertion `left == right` failed: impl error 
  left: 8                                
 right: 1                                                                   
Traceback (most recent call last):                                                                      
  File "/Users/lee/Documents/gse/dpr/panic_dates.py", line 36, in <module>                              
    show_panic(int(args.list_multiplier))                                                                        
  File "/Users/lee/Documents/gse/dpr/panic_dates.py", line 27, in show_panic   
    fdf = fdf.with_columns(pl.col('calendar_date').map_elements(lambda x: x.weekday()).alias('weekday'))
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^    
  File "/Users/lee/miniconda3/lib/python3.11/site-packages/polars/dataframe/frame.py", line 8315, in with_columns
    return self.lazy().with_columns(*exprs, **named_exprs).collect(_eager=True)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/lee/miniconda3/lib/python3.11/site-packages/polars/lazyframe/frame.py", line 1940, in collect
    return wrap_df(ldf.collect())
                   ^^^^^^^^^^^^^            
pyo3_runtime.PanicException: assertion `left == right` failed: impl error
```

### Issue description

The panic occurs only in polars version 0.20.4 and later.  I can't figure out why the panic does not occur when a list of dates is generated in memory, but does occur when read from a file with read_csv if the date list exceeds a threshold length (~2070).  This can be seen by running panic_dates.py with an argument of 69 or greater.

### Expected behavior

The expected result is a dataframe with three columns: date string, date, and weekday number.

### Installed versions

<details>

```
--------Version info---------
Polars:               0.20.7
Index type:           UInt32
Platform:             macOS-10.16-x86_64-i386-64bit
Python:               3.11.5 (main, Sep 11 2023, 08:19:27) [Clang 14.0.6 ]

----Optional dependencies----
adbc_driver_manager:  <not installed>
cloudpickle:          <not installed>
connectorx:           0.3.2
deltalake:            <not installed>
fsspec:               2023.12.2
gevent:               <not installed>
hvplot:               <not installed>
matplotlib:           3.8.2
numpy:                1.26.4
openpyxl:             3.1.2
pandas:               2.2.0
pyarrow:              14.0.2
pydantic:             2.6.1
pyiceberg:            <not installed>
pyxlsb:               <not installed>
sqlalchemy:           2.0.25
xlsx2csv:             0.8.1
xlsxwriter:           <not installed>
```

</details>

**Comment by cmdlineluser** [comment]
That is odd alright, it seems specific to `read_csv` - using `scan_csv` doesn't trigger the exception.

(I'm not sure if it's just an example or not, but `map_elements` is not needed for the task, you can use [`dt.weekday()`](https://docs.pola.rs/docs/python/dev/reference/expressions/api/polars.Expr.dt.weekday.html#polars.Expr.dt.weekday) directly.)

**Comment by lee170** [comment]
I started with code that worked in 0.20.3 and reduced until the error was easily repeatable.  It occurs with any function passed to map_elements().  Thanks for determining it is unrelated to map_elements.  I will revise the issue.

**Comment by lee170** [comment]
When I replace map_elements(lambda x: x.weekday()) with dt.weekday(), the panic does not occur, regardless of list length.

**Comment by taki-mekhalfa** [comment]
This is probably due to chunking; when the file exceeds a given size, it will be read in chunks.

Use `rechunk=True ` in `read_csv` in the mean time:

```python
>>> fdf = pl.read_csv('panic_date_strings.csv', rechunk=True)
>>> fdf = fdf.with_columns(pl.col('date').str.strptime(pl.Date, format="%Y-%m-%d").alias('calendar_date'))
>>> fdf = fdf.with_columns(pl.col('calendar_date').map_elements(lambda x: x.weekday()).alias('weekday'))
>>> fdf
shape: (2_070, 3)
┌────────────┬───────────────┬─────────┐
│ date       ┆ calendar_date ┆ weekday │
│ ---        ┆ ---           ┆ ---     │
│ str        ┆ date          ┆ i64     │
╞════════════╪═══════════════╪═════════╡
│ 2023-12-01 ┆ 2023-12-01    ┆ 4       │
│ 2023-12-02 ┆ 2023-12-02    ┆ 5       │
│ 2023-12-03 ┆ 2023-12-03    ┆ 6       │
│ 2023-12-04 ┆ 2023-12-04    ┆ 0       │
│ 2023-12-05 ┆ 2023-12-05    ┆ 1       │
│ …          ┆ …             ┆ …       │
│ 2023-12-26 ┆ 2023-12-26    ┆ 1       │
│ 2023-12-27 ┆ 2023-12-27    ┆ 2       │
│ 2023-12-28 ┆ 2023-12-28    ┆ 3       │
│ 2023-12-29 ┆ 2023-12-29    ┆ 4       │
│ 2023-12-30 ┆ 2023-12-30    ┆ 5       │
└────────────┴───────────────┴─────────┘
```

you can also call `.rechunk()` on the df before mapping elements

**Comment by lee170** [comment]
That is very helpful, thank you!
