### ISSUE TITLE
CSV parsing bug in lazy frames when using schema and has_header: ComputeError in pl.scan_csv(path, schema=schema, has_header=False)

### ISSUE THREAD

**Issue by Joe-TheBro** [pola-rs/polars#14412]
### Checks

- [X] I have checked that this issue has not already been reported.
- [X] I have confirmed this bug exists on the [latest version](https://pypi.org/project/polars/) of Polars.

### Reproducible example

```python
import polars as pl

schema = {
    "somefloat": pl.Float64
}

df = pl.DataFrame({
    "somefloat": [8092.32, 4523.45, 1234.56] 
}).write_csv("test.csv")

q = (
    pl.scan_csv("test.csv", schema=schema, has_header=False)
)    

df = q.collect()
```

### Log output

```shell
Traceback (most recent call last):
  File "test-polars.py", line 20, in <module>
    df = q.collect()
         ^^^^^^^^^^^
  File "\env\Lib\site-packages\polars\lazyframe\frame.py", line 1940, in collect
    return wrap_df(ldf.collect())
                   ^^^^^^^^^^^^^
polars.exceptions.ComputeError: could not parse `somefloat` as dtype `f64` at column 'somefloat' (column number 1)

The current offset in the file is 0 bytes.

You might want to try:
- increasing `infer_schema_length` (e.g. `infer_schema_length=10000`),
- specifying correct dtype with the `dtypes` argument
- setting `ignore_errors` to `True`,
- adding `somefloat` to the `null_values` list.

Original error:  bytes non-empty
```

### Issue description

This only happens while specifying a schema using lazyframes and ```has_header=False```, this might be related to #14140 and #14038

### Expected behavior

The expected behavior is for the file to parse with no issue.

### Installed versions

<details>

```
--------Version info---------
Polars:               0.20.7
Index type:           UInt32
Platform:             Windows-11-10.0.22621-SP0
Python:               3.12.1 | packaged by conda-forge | (main, Dec 23 2023, 07:53:56) [MSC v.1937 64 bit (AMD64)]

----Optional dependencies----
adbc_driver_manager:  <not installed>
cloudpickle:          3.0.0
connectorx:           <not installed>
deltalake:            <not installed>
fsspec:               <not installed>
gevent:               <not installed>
hvplot:               <not installed>
matplotlib:           <not installed>
numpy:                1.26.4
openpyxl:             <not installed>
pandas:               2.2.0
pyarrow:              14.0.2
pydantic:             <not installed>
pyiceberg:            <not installed>
pyxlsb:               <not installed>
sqlalchemy:           <not installed>
xlsx2csv:             <not installed>
xlsxwriter:           <not installed>
```

</details>

**Comment by Joe-TheBro** [comment]
I'm going to close this issue because I think I'm being dumb; when you write the CSV, it has the header, so if you specify ```has_header=False``` it tries to infer a float value from a string describing the column name. My bad.
