### ISSUE TITLE
Out of core query panics with "expected BinaryOffset, got binary"

### ISSUE THREAD

**Issue by stinodego** [pola-rs/polars#14430]
### Checks

- [X] I have checked that this issue has not already been reported.
- [X] I have confirmed this bug exists on the [latest version](https://pypi.org/project/polars/) of Polars.

### Reproducible example

```python
import os
from pathlib import Path

import polars as pl

# Run this script from the `py-polars` folder, or otherwise make sure it points to that folder
io_files_path = Path() / "tests" / "unit" / "io" / "files"
df = pl.read_csv(io_files_path / "foods*.csv")

os.environ["POLARS_FORCE_OOC"] = "1"
os.environ["POLARS_STREAMING_GROUPBY_SPILL_SIZE"] = "256"

# this creates 10M rows
q = df.lazy()
q = q.join(q, how="cross").select(df.columns).head(10_000)

# uses out-of-core unique
df1 = q.join(q.head(1000), how="cross").unique().collect(streaming=True)
print(df1)
```

### Log output

```shell
run UdfExec
RUN STREAMING PIPELINE
df -> cross_join_sink
RefCell { value: [df -> placeholder -> slice_sink -> fast_projection -> cross_join_sink, df -> cross_join_sink, df -> placeholder -> slice_sink -> fast_projection -> slice_sink -> placeholder -> re-project-sink -> ordered_sink] }
OOC group_by started
Temporary directory path in use: /tmp
Temporary directory path in use: /tmp
OOC group_by started
OOC group_by started
OOC group_by started
OOC group_by started
OOC group_by started
OOC group_by started
OOC group_by started
OOC group_by started
OOC group_by started
OOC group_by started
OOC group_by started
process partition 0 during generic-group_by-source
thread '<unnamed>' panicked at crates/polars-pipe/src/executors/sinks/group_by/generic/mod.rs:97:44:
called `Result::unwrap()` on an `Err` value: SchemaMismatch(ErrString("invalid series dtype: expected `BinaryOffset`, got `binary`"))
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
Traceback (most recent call last):
  File "/home/stijn/code/polars/py-polars/repro.py", line 18, in <module>
    df1 = q.join(q.head(1000), how="cross").unique().collect(streaming=True)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/stijn/code/polars/py-polars/polars/lazyframe/frame.py", line 1935, in collect
    return wrap_df(ldf.collect())
                   ^^^^^^^^^^^^^
pyo3_runtime.PanicException: called `Result::unwrap()` on an `Err` value: SchemaMismatch(ErrString("invalid series dtype: expected `BinaryOffset`, got `binary`"))
```

### Issue description

There is actually a test for this in our test suite. It runs fine when you run it together with other tests, but fails like the script above when you run it independently:

```
pytest tests/unit/streaming/test_streaming_unique.py::test_streaming_out_of_core_unique -m ''
```

### Expected behavior

It should work.

### Installed versions

main

**Comment by stinodego** [comment]
I marked this as high priority as I believe this is related to the recent string of CI failures detailed here:
https://github.com/pola-rs/polars/issues/13526
