### ISSUE TITLE
Appending two categorical series causes panic even when global string cache enabled

### ISSUE THREAD

**Issue by aguspdana** [pola-rs/polars#1457]
#### Are you using Python or Rust?
**Rust**

#### Which feature gates did you use?
```
"strings",
"dtype-categorical"
```

#### What version of polars are you using?

git

#### What operating system are you using polars on?

Ubuntu 21.04

#### Describe your bug.

Appending two categorical series causes panic when printed. This happens even when the global string cache is enabled.

#### What are the steps to reproduce the behavior?

```rust
use polars::{
    prelude::*,
    toggle_string_cache
};

fn main() {
    toggle_string_cache(true);
    
    let mut s1 = Series::new("1", vec!["a", "b", "c"]).cast::<CategoricalType>().unwrap();
    let s2 = Series::new("2", vec!["a", "x", "y"]).cast::<CategoricalType>().unwrap();
    let appended = s1.append(&s2).unwrap();
    println!("{}", appended);
}
```

#### What is the actual behavior?

```
shape: (6,)
Series: '1' [cat]
[
        "a"
        "b"
        "c"
        "a"
thread 'main' panicked at 'called `Option::unwrap()` on a `None` value', /.cargo/git/checkouts/polars-b0d90607192fd414/d7d63b1/polars/polars-core/src/chunked_array/builder/categorical.rs:56:42
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

#### What is the expected behavior?

```
shape: (6,)
Series: '1' [cat]
[
        "a"
        "b"
        "c"
        "a"
        "x"
        "y"
]
```

#### Possible cause

Upon investigation (please correct me if I'm wrong)

```rust
use polars::{
    prelude::*,
    chunked_array::builder::categorical::RevMapping,
    toggle_string_cache
};

fn main() {
    toggle_string_cache(true);
    
    let mut s1 = Series::new("1", vec!["a", "b", "c"]).cast::<CategoricalType>().unwrap();
    let s2 = Series::new("2", vec!["a", "x", "y"]).cast::<CategoricalType>().unwrap();

    let rev1 = &**s1.categorical().unwrap().get_categorical_map().unwrap();
    let rev2 = &**s2.categorical().unwrap().get_categorical_map().unwrap();

    println!("\n# Series");
    println!("1 => {}", s1);
    println!("2 => {}", s2);

    println!("\n# UInt32 Representasion");
    println!("1 => {:?}", s1.cast::<UInt32Type>().unwrap());
    println!("2 => {:?}", s2.cast::<UInt32Type>().unwrap());

    println!("\n# RevMapping 1");
    match rev1 {
        RevMapping::Global(hash, utf, id) => {
            println!("hash => {:?}", hash);
            println!("utf => {}", utf);
            println!("uuid => {}", id);
        },
        RevMapping::Local(utf) => println!("UTF => {}", utf)
    }

    println!("\n# RevMapping 2");
    match rev2 {
        RevMapping::Global(hash, utf, id) => {
            println!("hash => {:?}", hash);
            println!("utf => {}", utf);
            println!("uuid => {}", id);
        },
        RevMapping::Local(utf) => println!("UTF => {}", utf)
    }

    println!("\n# Appended");

    let appended = s1.append(&s2).unwrap();
    let rev_appended = &**appended.categorical().unwrap().get_categorical_map().unwrap();
    println!("\nUInt32 Representasion => {:?}", appended.cast::<UInt32Type>().unwrap());

    let appended_chunks = appended.categorical().unwrap().chunks();
    println!("\nChunks");
    appended_chunks.iter().for_each(|i| {
        println!("{}", i);
    });

    println!("\nRevMapping");
    match rev_appended {
        RevMapping::Global(hash, utf, id) => {
            println!("hash => {:?}", hash);
            println!("utf => {}", utf);
            println!("uuid => {}", id);
        },
        RevMapping::Local(utf) => println!("UTF => {}", utf)
    }

    println!("\nSeries => {}", appended);
}
```

```
# Series
1 => shape: (3,)
Series: '1' [cat]
[
        "a"
        "b"
        "c"
]
2 => shape: (3,)
Series: '2' [cat]
[
        "a"
        "x"
        "y"
]

# UInt32 Representasion
1 => shape: (3,)
Series: '1' [u32]
[
        0
        1
        2
]
2 => shape: (3,)
Series: '2' [u32]
[
        0
        3
        4
]

# RevMapping 1
hash => {0: 0, 1: 1, 2: 2}
utf => LargeUtf8[a, b, c]
uuid => 1632886459380875521

# RevMapping 2
hash => {4: 2, 0: 0, 3: 1}
utf => LargeUtf8[a, x, y]
uuid => 1632886459380875521

# Appended

UInt32 Representasion => shape: (6,)
Series: '1' [u32]
[
        0
        1
        2
        0
        3
        4
]

Chunks
UInt32[0, 1, 2]
UInt32[0, 3, 4]

RevMapping
hash => {0: 0, 1: 1, 2: 2}
utf => LargeUtf8[a, b, c]
uuid => 1632886459380875521

Series => shape: (6,)
Series: '1' [cat]
[
        "a"
        "b"
        "c"
        "a"
thread 'main' panicked at 'called `Option::unwrap()` on a `None` value', /.cargo/git/checkouts/polars-b0d90607192fd414/d7d63b1/polars/polars-core/src/chunked_array/builder/categorical.rs:56:42
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

The `append` method seems to only append the chunks of the second series to the first series, but the `categorical_map` doesn't get updated.

polars_core/chunked_array/mod.rs
```rust
impl<T> ChunkedArray<T> {
    ...
    pub fn append(&mut self, other: &Self)
    where
        Self: std::marker::Sized,
    {
        #[cfg(feature = "dtype-categorical")]
        if let (Some(rev_map_l), Some(rev_map_r)) = (
            self.categorical_map.as_ref(),
            other.categorical_map.as_ref(),
        ) {
            // first assertion checks if the global string cache is equal,
            // the second checks if we append a slice from this array to self
            if !rev_map_l.same_src(rev_map_r) && !Arc::ptr_eq(rev_map_l, rev_map_r) {
                panic!("Appending categorical data can only be done if they are made under the same global string cache. \
                Consider using a global string cache.")
            }
        }
  
        // replace an empty array
        if self.chunks.len() == 1 && self.is_empty() {
            self.chunks = other.chunks.clone();
        } else {
            self.chunks.extend_from_slice(&other.chunks);
        }
    }
    ...
}
```

Looking at polars_core/chunked_array/builder/categorical.rs, the global string cache seems to use a global hash map to synchronize the `u32` representation, and each `CategoricalChunks` has its own hash map that contains only the `category_map` of the items it holds.

Is there any consideration to make all `CategoricalChunks` that are created with global string cache enabled to holds the entire categorical map including categories that don't exist in its item list?

**Comment by ritchie46** [comment]
> Looking at polars_core/chunked_array/builder/categorical.rs, the global string cache seems to use a global hash map to synchronize the u32 representation, and each CategoricalChunks has its own hash map that contains only the category_map of the items it holds.

It's correct that a global hash map serves as a global cache for `String -> u32`. The categorical arrays themselves still hold a reverse hashmap, mapping the indexes returned by the global cache to and index that fits the Arrow string array of the categorical array itself. If we don't  do this, we'd need to waste memory with empty slots. For example let's imagine that we create a new categorical array, with a new string that was not seen before. If there are at that moment 1200 values in the global string cache, the first index of the categorical array would be 1201, waisting 1200 slots.

I think we have to recompute the categorical rev maps upon an append operation.
