### ISSUE TITLE
Series.to_list() panic

### ISSUE THREAD

**Issue by aptr322** [pola-rs/polars#1460]
#### Are you using Python or Rust?

 **Rust**

#### Which feature gates did you use?

["polars-io", "parquet"]

#### What operating system are you using polars on?

macos CAtalina 10.15.7

#### Describe your bug.
```
thread 'main' panicked at 'assertion failed: `(left == right)`
  left: `LargeList(Field { name: "", data_type: LargeUtf8, nullable: true, dict_id: 0, dict_is_ordered: false, metadata: None })`,
 right: `LargeList(Field { name: "item", data_type: LargeUtf8, nullable: true, dict_id: 0, dict_is_ordered: false, metadata: None })`: The child's datatype must match the inner type of the 'data_type'', /Users/petrov/.cargo/git/checkouts/arrow2-945af624853845da/142f05a/src/array/list/mod.rs:61:9
stack backtrace:
   0: rust_begin_unwind
             at /rustc/c8dfcfe046a7680554bf4eb612bad840e7631c4b/library/std/src/panicking.rs:515:5
   1: core::panicking::panic_fmt
             at /rustc/c8dfcfe046a7680554bf4eb612bad840e7631c4b/library/core/src/panicking.rs:92:14
   2: core::panicking::assert_failed_inner
             at /rustc/c8dfcfe046a7680554bf4eb612bad840e7631c4b/library/core/src/panicking.rs:154:23
   3: core::panicking::assert_failed
             at /rustc/c8dfcfe046a7680554bf4eb612bad840e7631c4b/library/core/src/panicking.rs:117:5
   4: arrow2::array::list::ListArray<O>::from_data
             at /Users/petrov/.cargo/git/checkouts/arrow2-945af624853845da/142f05a/src/array/list/mod.rs:61:9
   5: polars_core::series::ops::to_list::<impl polars_core::series::Series>::to_list
             at /Users/petrov/.cargo/git/checkouts/polars-a7cd433de180eb5f/ee865c1/polars/polars-core/src/series/ops/to_list.rs:17:19
   6: echo_topics::main
             at ./src/bin/echo_topics.rs:83:18
   7: core::ops::function::FnOnce::call_once
             at /rustc/c8dfcfe046a7680554bf4eb612bad840e7631c4b/library/core/src/ops/function.rs:227:5
```
#### What are the steps to reproduce the behavior?

https://gist.github.com/aptr322/cdbdc48dc9d82ac62c52e49726a2eab7

 
#### What is the actual behavior?

Show the query you ran and the actual output. 

If the output is large, put it in a gist: https://gist.github.com/

If the output is small, put it in code fences:

```
your
output
goes
here
```

#### What is the expected behavior?

What do you think polars should have done?

**Comment by aptr322** [comment]
data https://drive.google.com/file/d/1f0bLgg7wx-lkiCzqah8dsut7BvNL2rgS/view?usp=sharing

**Comment by ritchie46** [comment]
If you want to unpack a `Series` of dtype `List`, you must call `list()` not `to_list()`.

**Comment by aptr322** [comment]
ok, closing
