### ISSUE TITLE
`Array` columns not supported by `extend()`

### ISSUE THREAD

**Issue by guyrosin** [pola-rs/polars#14606]
### Checks

- [X] I have checked that this issue has not already been reported.
- [X] I have confirmed this bug exists on the [latest version](https://pypi.org/project/polars/) of Polars.

### Reproducible example

```python
# schema = {"foo": pl.List(pl.Int32)} <-- this works
schema = {"foo": pl.Array(pl.Int32, 2)}  # this does not
lists = [[1, 1], [2, 2]]
df1 = pl.DataFrame({"foo": lists}, schema=schema)
df2 = pl.DataFrame({"foo": lists}, schema=schema)
df1.extend(df2)
```

### Log output

```shell
thread '<unnamed>' panicked at crates/polars-core/src/series/mod.rs:881:13:
implementation error, cannot get ref Array(Null, 0) from Array(Int32, 2)
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/ubuntu/playground/.venv/lib/python3.9/site-packages/polars/dataframe/frame.py", line 6668, in extend
    self._df.extend(other._df)
pyo3_runtime.PanicException: implementation error, cannot get ref Array(Null, 0) from Array(Int32, 2)
```

### Issue description

It seems like `df.extend()` doesn't support Array columns.

### Expected behavior

`extend()` should succeed, as it does for `List` columns.

### Installed versions

<details>

```
--------Version info---------
Polars:               0.20.10
Index type:           UInt32
Platform:             Linux-6.2.0-1017-aws-x86_64-with-glibc2.35
Python:               3.9.18 (main, Aug 28 2023, 13:16:32) 
[GCC 11.4.0]

----Optional dependencies----
adbc_driver_manager:  <not installed>
cloudpickle:          3.0.0
connectorx:           <not installed>
deltalake:            <not installed>
fsspec:               2023.12.2
gevent:               <not installed>
hvplot:               0.9.2
matplotlib:           3.8.3
numpy:                1.26.4
openpyxl:             3.1.2
pandas:               2.2.0
pyarrow:              15.0.0
pydantic:             <not installed>
pyiceberg:            <not installed>
pyxlsb:               <not installed>
sqlalchemy:           2.0.27
xlsx2csv:             0.8.2
xlsxwriter:           3.2.0
```

</details>

**Comment by guyrosin** [comment]
Right, it seems to work fine now :)
