### ISSUE TITLE
read_parquet - The maximum key is too small

### ISSUE THREAD

**Issue by magic-lantern** [pola-rs/polars#14641]
### Checks

- [X] I have checked that this issue has not already been reported.
- [X] I have confirmed this bug exists on the [latest version](https://pypi.org/project/polars/) of Polars.

### Reproducible example

```python
import glob
import os
import pandas as pd
import polars as pl

os.environ["RUST_BACKTRACE"] = "1"
os.environ["POLARS_MAX_THREADS"] = "1"
os.environ["RUST_BACKTRACE"] = "full"
os.environ["POLARS_VERBOSE"] = "1"

cols_of_interest = [
    'redcap id',
    'timestamp',
    'sequencenumber',
    'label',
    'sublabel',
    'value',
    'unitlabel',
    'scale',
    'validity',
    'patientid',
    'dataset #'
]

# directory has 30GB of parquet files - 16 total files
# total rows of data ~630 million
path_base = '/phi/waveform/processed/parquet/'

print(pl.__version__)
# 0.20.10

# this works fine
# df = pd.read_parquet(path_base, columns=cols_of_interest)
# as does this
# df = pl.read_parquet(source=path_base, columns=cols_of_interest, use_pyarrow=True)
# and this
# df = pl.read_parquet(source='/phi/waveform/processed/parquet/NumericFullData_Set11.parquet', columns=cols_of_interest)

# results in error "The maximum key is too small" repeated many times
df = pl.read_parquet(source=glob.glob(path_base + '*.parquet'), columns=cols_of_interest)
```

### Log output

```shell
thread '<unnamed>' panicked at /home/conda/feedstock_root/build_artifacts/polars_1708361485302/work/crates/polars-parquet/src/arrow/read/deserialize/dictionary/mod.rs:168:35:
The maximum key is too small
stack backtrace:
   0:     0x7f280665b575 - std::backtrace_rs::backtrace::libunwind::trace::h815354fef816bc86
                               at /rustc/503e129328080e924c0ddfca6abf4c2812580102/library/std/src/../../backtrace/src/backtrace/libunwind.rs:104:5
   1:     0x7f280665b575 - std::backtrace_rs::backtrace::trace_unsynchronized::h8ee509da58073872
                               at /rustc/503e129328080e924c0ddfca6abf4c2812580102/library/std/src/../../backtrace/src/backtrace/mod.rs:66:5
   2:     0x7f280665b575 - std::sys_common::backtrace::_print_fmt::ha7526b8479823d1a
                               at /rustc/503e129328080e924c0ddfca6abf4c2812580102/library/std/src/sys_common/backtrace.rs:68:5
   3:     0x7f280665b575 - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::haf74540a80629043
                               at /rustc/503e129328080e924c0ddfca6abf4c2812580102/library/std/src/sys_common/backtrace.rs:44:22
   4:     0x7f2803ee6830 - core::fmt::rt::Argument::fmt::hc68f5fa1b36668fc
                               at /rustc/503e129328080e924c0ddfca6abf4c2812580102/library/core/src/fmt/rt.rs:142:9
   5:     0x7f2803ee6830 - core::fmt::write::h4274fed398e9428e
                               at /rustc/503e129328080e924c0ddfca6abf4c2812580102/library/core/src/fmt/mod.rs:1120:17
   6:     0x7f280662478e - std::io::Write::write_fmt::hc6c4a8568e7df724
                               at /rustc/503e129328080e924c0ddfca6abf4c2812580102/library/std/src/io/mod.rs:1810:15
   7:     0x7f280665d32e - std::sys_common::backtrace::_print::h2e09ef8543bf3bd8
                               at /rustc/503e129328080e924c0ddfca6abf4c2812580102/library/std/src/sys_common/backtrace.rs:47:5
   8:     0x7f280665d32e - std::sys_common::backtrace::print::h9a43f66a9d093046
                               at /rustc/503e129328080e924c0ddfca6abf4c2812580102/library/std/src/sys_common/backtrace.rs:34:9
   9:     0x7f280665cbc7 - std::panicking::default_hook::{{closure}}::h9c00a7d25a3e4c19
  10:     0x7f280665dbdb - std::panicking::default_hook::h1b24ab04fe68d03a
                               at /rustc/503e129328080e924c0ddfca6abf4c2812580102/library/std/src/panicking.rs:292:9
  11:     0x7f280665dbdb - std::panicking::rust_panic_with_hook::hbafd4f0baa9fdb9e
                               at /rustc/503e129328080e924c0ddfca6abf4c2812580102/library/std/src/panicking.rs:779:13
  12:     0x7f280665d678 - std::panicking::begin_panic_handler::{{closure}}::h4c976a34ccffa9e2
                               at /rustc/503e129328080e924c0ddfca6abf4c2812580102/library/std/src/panicking.rs:649:13
  13:     0x7f280665d606 - std::sys_common::backtrace::__rust_end_short_backtrace::h675039fe30aa0955
                               at /rustc/503e129328080e924c0ddfca6abf4c2812580102/library/std/src/sys_common/backtrace.rs:171:18
  14:     0x7f280665d5f1 - rust_begin_unwind
                               at /rustc/503e129328080e924c0ddfca6abf4c2812580102/library/std/src/panicking.rs:645:5
  15:     0x7f2802fc4844 - core::panicking::panic_fmt::h32ca55ac70be178d
                               at /rustc/503e129328080e924c0ddfca6abf4c2812580102/library/core/src/panicking.rs:72:14
  16:     0x7f2804db4d74 - <polars_parquet::arrow::read::deserialize::dictionary::PrimitiveDecoder<K> as polars_parquet::arrow::read::deserialize::utils::Decoder>::extend_from_state::h727e23160c3fcf38
  17:     0x7f2804db407d - polars_parquet::arrow::read::deserialize::utils::extend_from_new_page::h937191f7400bcb9f
  18:     0x7f2804dc44da - polars_parquet::arrow::read::deserialize::dictionary::next_dict::hdb92b9bb6c860693
  19:     0x7f2804dc3e7e - <polars_parquet::arrow::read::deserialize::binview::dictionary::DictIter<K,I> as core::iter::traits::iterator::Iterator>::next::haa1c85746b33308b
  20:     0x7f2804dc39f5 - <core::iter::adapters::map::Map<I,F> as core::iter::traits::iterator::Iterator>::next::hbe605f3a9174ba0d
  21:     0x7f2804d28592 - <core::iter::adapters::map::Map<I,F> as core::iter::traits::iterator::Iterator>::next::h44eb13d4abfbb6c4
  22:     0x7f2804d2816c - <core::iter::adapters::map::Map<I,F> as core::iter::traits::iterator::Iterator>::next::h73e753e234089680
  23:     0x7f2804d1bf40 - polars_io::parquet::read_impl::array_iter_to_series::h10a806eb71fded4a
  24:     0x7f2804ef9a82 - rayon::iter::plumbing::bridge_producer_consumer::helper::h01c35619a0033b08
  25:     0x7f2804efa981 - rayon_core::join::join_context::{{closure}}::hfd4e202577f2ac8e
  26:     0x7f2804ef9fbe - rayon::iter::plumbing::bridge_producer_consumer::helper::h01c35619a0033b08
  27:     0x7f2804d15e4e - rayon_core::thread_pool::ThreadPool::install::{{closure}}::hdc570676c9b4e5bc
  28:     0x7f2804d1533b - polars_io::parquet::read_impl::rg_to_dfs::h6cdec21adfc20165
  29:     0x7f28051938b0 - <core::iter::adapters::map::Map<I,F> as core::iter::traits::iterator::Iterator>::next::h40a17e50e9156906
  30:     0x7f280519211e - rayon::iter::plumbing::bridge_producer_consumer::helper::he97bfb3c4f4ab47a
  31:     0x7f28051915c9 - rayon_core::thread_pool::ThreadPool::install::{{closure}}::h3aa46f38e394eeb1
  32:     0x7f28051a7a2b - <rayon_core::job::StackJob<L,F,R> as rayon_core::job::Job>::execute::h16846a4b7b60704e
  33:     0x7f28032306ee - rayon_core::registry::WorkerThread::wait_until_cold::h4492c21ed6bd5c20
  34:     0x7f28063bd887 - std::sys_common::backtrace::__rust_begin_short_backtrace::h5158499b1bc9905d
  35:     0x7f28063bd56e - core::ops::function::FnOnce::call_once{{vtable.shim}}::hbbced209f456c5a9
  36:     0x7f280665fe86 - <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once::h2d19f142671865ec
                               at /rustc/503e129328080e924c0ddfca6abf4c2812580102/library/alloc/src/boxed.rs:2015:9
  37:     0x7f280665fe86 - <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once::h710d713fa9cb7127
                               at /rustc/503e129328080e924c0ddfca6abf4c2812580102/library/alloc/src/boxed.rs:2015:9
  38:     0x7f280665fe86 - std::sys::unix::thread::Thread::new::thread_start::haaff457ad882d05b
                               at /rustc/503e129328080e924c0ddfca6abf4c2812580102/library/std/src/sys/unix/thread.rs:108:17
  39:     0x7f29d19e5609 - start_thread
  40:     0x7f29d17b0353 - clone
  41:                0x0 - <unknown>
thread '<unnamed>' panicked at /home/conda/feedstock_root/build_artifacts/polars_1708361485302/work/crates/polars-parquet/src/arrow/read/deserialize/dictionary/mod.rs:168:35:
The maximum key is too small
stack backtrace:
   0:     0x7f280665b575 - std::backtrace_rs::backtrace::libunwind::trace::h815354fef816bc86
                               at /rustc/503e129328080e924c0ddfca6abf4c2812580102/library/std/src/../../backtrace/src/backtrace/libunwind.rs:104:5
   1:     0x7f280665b575 - std::backtrace_rs::backtrace::trace_unsynchronized::h8ee509da58073872
                               at /rustc/503e129328080e924c0ddfca6abf4c2812580102/library/std/src/../../backtrace/src/backtrace/mod.rs:66:5
   2:     0x7f280665b575 - std::sys_common::backtrace::_print_fmt::ha7526b8479823d1a
                               at /rustc/503e129328080e924c0ddfca6abf4c2812580102/library/std/src/sys_common/backtrace.rs:68:5
   3:     0x7f280665b575 - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::haf74540a80629043
                               at /rustc/503e129328080e924c0ddfca6abf4c2812580102/library/std/src/sys_common/backtrace.rs:44:22
   4:     0x7f2803ee6830 - core::fmt::rt::Argument::fmt::hc68f5fa1b36668fc
                               at /rustc/503e129328080e924c0ddfca6abf4c2812580102/library/core/src/fmt/rt.rs:142:9
   5:     0x7f2803ee6830 - core::fmt::write::h4274fed398e9428e
                               at /rustc/503e129328080e924c0ddfca6abf4c2812580102/library/core/src/fmt/mod.rs:1120:17
   6:     0x7f280662478e - std::io::Write::write_fmt::hc6c4a8568e7df724
                               at /rustc/503e129328080e924c0ddfca6abf4c2812580102/library/std/src/io/mod.rs:1810:15
   7:     0x7f280665d32e - std::sys_common::backtrace::_print::h2e09ef8543bf3bd8
                               at /rustc/503e129328080e924c0ddfca6abf4c2812580102/library/std/src/sys_common/backtrace.rs:47:5
   8:     0x7f280665d32e - std::sys_common::backtrace::print::h9a43f66a9d093046
                               at /rustc/503e129328080e924c0ddfca6abf4c2812580102/library/std/src/sys_common/backtrace.rs:34:9
   9:     0x7f280665cbc7 - std::panicking::default_hook::{{closure}}::h9c00a7d25a3e4c19
  10:     0x7f280665dbdb - std::panicking::default_hook::h1b24ab04fe68d03a
                               at /rustc/503e129328080e924c0ddfca6abf4c2812580102/library/std/src/panicking.rs:292:9
  11:     0x7f280665dbdb - std::panicking::rust_panic_with_hook::hbafd4f0baa9fdb9e
                               at /rustc/503e129328080e924c0ddfca6abf4c2812580102/library/std/src/panicking.rs:779:13
  12:     0x7f280665d678 - std::panicking::begin_panic_handler::{{closure}}::h4c976a34ccffa9e2
                               at /rustc/503e129328080e924c0ddfca6abf4c2812580102/library/std/src/panicking.rs:649:13
  13:     0x7f280665d606 - std::sys_common::backtrace::__rust_end_short_backtrace::h675039fe30aa0955
                               at /rustc/503e129328080e924c0ddfca6abf4c2812580102/library/std/src/sys_common/backtrace.rs:171:18
  14:     0x7f280665d5f1 - rust_begin_unwind
                               at /rustc/503e129328080e924c0ddfca6abf4c2812580102/library/std/src/panicking.rs:645:5
  15:     0x7f2802fc4844 - core::panicking::panic_fmt::h32ca55ac70be178d
                               at /rustc/503e129328080e924c0ddfca6abf4c2812580102/library/core/src/panicking.rs:72:14
  16:     0x7f2804db4d74 - <polars_parquet::arrow::read::deserialize::dictionary::PrimitiveDecoder<K> as polars_parquet::arrow::read::deserialize::utils::Decoder>::extend_from_state::h727e23160c3fcf38
  17:     0x7f2804db407d - polars_parquet::arrow::read::deserialize::utils::extend_from_new_page::h937191f7400bcb9f
  18:     0x7f2804dc44da - polars_parquet::arrow::read::deserialize::dictionary::next_dict::hdb92b9bb6c860693
  19:     0x7f2804dc3e7e - <polars_parquet::arrow::read::deserialize::binview::dictionary::DictIter<K,I> as core::iter::traits::iterator::Iterator>::next::haa1c85746b33308b
  20:     0x7f2804dc39f5 - <core::iter::adapters::map::Map<I,F> as core::iter::traits::iterator::Iterator>::next::hbe605f3a9174ba0d
  21:     0x7f2804d28592 - <core::iter::adapters::map::Map<I,F> as core::iter::traits::iterator::Iterator>::next::h44eb13d4abfbb6c4
  22:     0x7f2804d2816c - <core::iter::adapters::map::Map<I,F> as core::iter::traits::iterator::Iterator>::next::h73e753e234089680
  23:     0x7f2804d1bf40 - polars_io::parquet::read_impl::array_iter_to_series::h10a806eb71fded4a
  24:     0x7f2804ef9a82 - rayon::iter::plumbing::bridge_producer_consumer::helper::h01c35619a0033b08
  25:     0x7f2804efa981 - rayon_core::join::join_context::{{closure}}::hfd4e202577f2ac8e
  26:     0x7f2804ef9fbe - rayon::iter::plumbing::bridge_producer_consumer::helper::h01c35619a0033b08
  27:     0x7f2804efa981 - rayon_core::join::join_context::{{closure}}::hfd4e202577f2ac8e
  28:     0x7f2804ef9fbe - rayon::iter::plumbing::bridge_producer_consumer::helper::h01c35619a0033b08
  29:     0x7f2804efb2ed - <rayon_core::job::StackJob<L,F,R> as rayon_core::job::Job>::execute::hab74119359c13b1a
  30:     0x7f2803230155 - rayon_core::registry::WorkerThread::wait_until_cold::h4492c21ed6bd5c20
  31:     0x7f280323008e - rayon_core::join::join_recover_from_panic::h00d7bc6f17180b3d
  32:     0x7f2804efaca0 - rayon_core::join::join_context::{{closure}}::hfd4e202577f2ac8e
  33:     0x7f2804ef9fbe - rayon::iter::plumbing::bridge_producer_consumer::helper::h01c35619a0033b08
  34:     0x7f2804d15e4e - rayon_core::thread_pool::ThreadPool::install::{{closure}}::hdc570676c9b4e5bc
  35:     0x7f2804d1533b - polars_io::parquet::read_impl::rg_to_dfs::h6cdec21adfc20165
  36:     0x7f28051938b0 - <core::iter::adapters::map::Map<I,F> as core::iter::traits::iterator::Iterator>::next::h40a17e50e9156906
  37:     0x7f280519211e - rayon::iter::plumbing::bridge_producer_consumer::helper::he97bfb3c4f4ab47a
  38:     0x7f28051915c9 - rayon_core::thread_pool::ThreadPool::install::{{closure}}::h3aa46f38e394eeb1
  39:     0x7f28051a7a2b - <rayon_core::job::StackJob<L,F,R> as rayon_core::job::Job>::execute::h16846a4b7b60704e
  40:     0x7f28032306ee - rayon_core::registry::WorkerThread::wait_until_cold::h4492c21ed6bd5c20
  41:     0x7f28063bd887 - std::sys_common::backtrace::__rust_begin_short_backtrace::h5158499b1bc9905d
  42:     0x7f28063bd56e - core::ops::function::FnOnce::call_once{{vtable.shim}}::hbbced209f456c5a9
  43:     0x7f280665fe86 - <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once::h2d19f142671865ec
                               at /rustc/503e129328080e924c0ddfca6abf4c2812580102/library/alloc/src/boxed.rs:2015:9
  44:     0x7f280665fe86 - <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once::h710d713fa9cb7127
                               at /rustc/503e129328080e924c0ddfca6abf4c2812580102/library/alloc/src/boxed.rs:2015:9
  45:     0x7f280665fe86 - std::sys::unix::thread::Thread::new::thread_start::haaff457ad882d05b
                               at /rustc/503e129328080e924c0ddfca6abf4c2812580102/library/std/src/sys/unix/thread.rs:108:17
  46:     0x7f29d19e5609 - start_thread
  47:     0x7f29d17b0353 - clone
  48:                0x0 - <unknown>
thread '<unnamed>' panicked at /home/conda/feedstock_root/build_artifacts/polars_1708361485302/work/crates/polars-parquet/src/arrow/read/deserialize/dictionary/mod.rs:168:35:
The maximum key is too small
stack backtrace:
   0:     0x7f280665b575 - std::backtrace_rs::backtrace::libunwind::trace::h815354fef816bc86
                               at /rustc/503e129328080e924c0ddfca6abf4c2812580102/library/std/src/../../backtrace/src/backtrace/libunwind.rs:104:5
   1:     0x7f280665b575 - std::backtrace_rs::backtrace::trace_unsynchronized::h8ee509da58073872
                               at /rustc/503e129328080e924c0ddfca6abf4c2812580102/library/std/src/../../backtrace/src/backtrace/mod.rs:66:5
   2:     0x7f280665b575 - std::sys_common::backtrace::_print_fmt::ha7526b8479823d1a
                               at /rustc/503e129328080e924c0ddfca6abf4c2812580102/library/std/src/sys_common/backtrace.rs:68:5
   3:     0x7f280665b575 - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::haf74540a80629043
                               at /rustc/503e129328080e924c0ddfca6abf4c2812580102/library/std/src/sys_common/backtrace.rs:44:22
   4:     0x7f2803ee6830 - core::fmt::rt::Argument::fmt::hc68f5fa1b36668fc
                               at /rustc/503e129328080e924c0ddfca6abf4c2812580102/library/core/src/fmt/rt.rs:142:9
   5:     0x7f2803ee6830 - core::fmt::write::h4274fed398e9428e
                               at /rustc/503e129328080e924c0ddfca6abf4c2812580102/library/core/src/fmt/mod.rs:1120:17
   6:     0x7f280662478e - std::io::Write::write_fmt::hc6c4a8568e7df724
                               at /rustc/503e129328080e924c0ddfca6abf4c2812580102/library/std/src/io/mod.rs:1810:15
   7:     0x7f280665d32e - std::sys_common::backtrace::_print::h2e09ef8543bf3bd8
                               at /rustc/503e129328080e924c0ddfca6abf4c2812580102/library/std/src/sys_common/backtrace.rs:47:5
   8:     0x7f280665d32e - std::sys_common::backtrace::print::h9a43f66a9d093046
                               at /rustc/503e129328080e924c0ddfca6abf4c2812580102/library/std/src/sys_common/backtrace.rs:34:9
   9:     0x7f280665cbc7 - std::panicking::default_hook::{{closure}}::h9c00a7d25a3e4c19
  10:     0x7f280665dbdb - std::panicking::default_hook::h1b24ab04fe68d03a
                               at /rustc/503e129328080e924c0ddfca6abf4c2812580102/library/std/src/panicking.rs:292:9
  11:     0x7f280665dbdb - std::panicking::rust_panic_with_hook::hbafd4f0baa9fdb9e
                               at /rustc/503e129328080e924c0ddfca6abf4c2812580102/library/std/src/panicking.rs:779:13
  12:     0x7f280665d678 - std::panicking::begin_panic_handler::{{closure}}::h4c976a34ccffa9e2
                               at /rustc/503e129328080e924c0ddfca6abf4c2812580102/library/std/src/panicking.rs:649:13
  13:     0x7f280665d606 - std::sys_common::backtrace::__rust_end_short_backtrace::h675039fe30aa0955
                               at /rustc/503e129328080e924c0ddfca6abf4c2812580102/library/std/src/sys_common/backtrace.rs:171:18
  14:     0x7f280665d5f1 - rust_begin_unwind
                               at /rustc/503e129328080e924c0ddfca6abf4c2812580102/library/std/src/panicking.rs:645:5
  15:     0x7f2802fc4844 - core::panicking::panic_fmt::h32ca55ac70be178d
                               at /rustc/503e129328080e924c0ddfca6abf4c2812580102/library/core/src/panicking.rs:72:14
  16:     0x7f2804db4d74 - <polars_parquet::arrow::read::deserialize::dictionary::PrimitiveDecoder<K> as polars_parquet::arrow::read::deserialize::utils::Decoder>::extend_from_state::h727e23160c3fcf38
  17:     0x7f2804db407d - polars_parquet::arrow::read::deserialize::utils::extend_from_new_page::h937191f7400bcb9f
  18:     0x7f2804dc44da - polars_parquet::arrow::read::deserialize::dictionary::next_dict::hdb92b9bb6c860693
  19:     0x7f2804dc3e7e - <polars_parquet::arrow::read::deserialize::binview::dictionary::DictIter<K,I> as core::iter::traits::iterator::Iterator>::next::haa1c85746b33308b
  20:     0x7f2804dc39f5 - <core::iter::adapters::map::Map<I,F> as core::iter::traits::iterator::Iterator>::next::hbe605f3a9174ba0d
  21:     0x7f2804d28592 - <core::iter::adapters::map::Map<I,F> as core::iter::traits::iterator::Iterator>::next::h44eb13d4abfbb6c4
  22:     0x7f2804d2816c - <core::iter::adapters::map::Map<I,F> as core::iter::traits::iterator::Iterator>::next::h73e753e234089680
  23:     0x7f2804d1bf40 - polars_io::parquet::read_impl::array_iter_to_series::h10a806eb71fded4a
  24:     0x7f2804ef9a82 - rayon::iter::plumbing::bridge_producer_consumer::helper::h01c35619a0033b08
  25:     0x7f2804efaaa3 - rayon_core::join::join_context::{{closure}}::hfd4e202577f2ac8e
  26:     0x7f2804ef9fbe - rayon::iter::plumbing::bridge_producer_consumer::helper::h01c35619a0033b08
  27:     0x7f2804efaaa3 - rayon_core::join::join_context::{{closure}}::hfd4e202577f2ac8e
  28:     0x7f2804ef9fbe - rayon::iter::plumbing::bridge_producer_consumer::helper::h01c35619a0033b08
  29:     0x7f2804efb2ed - <rayon_core::job::StackJob<L,F,R> as rayon_core::job::Job>::execute::hab74119359c13b1a
  30:     0x7f2803230155 - rayon_core::registry::WorkerThread::wait_until_cold::h4492c21ed6bd5c20
  31:     0x7f280323008e - rayon_core::join::join_recover_from_panic::h00d7bc6f17180b3d
  32:     0x7f2804efaca0 - rayon_core::join::join_context::{{closure}}::hfd4e202577f2ac8e
  33:     0x7f2804ef9fbe - rayon::iter::plumbing::bridge_producer_consumer::helper::h01c35619a0033b08
  34:     0x7f2804efb2ed - <rayon_core::job::StackJob<L,F,R> as rayon_core::job::Job>::execute::hab74119359c13b1a
  35:     0x7f2803230155 - rayon_core::registry::WorkerThread::wait_until_cold::h4492c21ed6bd5c20
  36:     0x7f280323008e - rayon_core::join::join_recover_from_panic::h00d7bc6f17180b3d
  37:     0x7f2804efaca0 - rayon_core::join::join_context::{{closure}}::hfd4e202577f2ac8e
  38:     0x7f2804ef9fbe - rayon::iter::plumbing::bridge_producer_consumer::helper::h01c35619a0033b08
  39:     0x7f2804d15e4e - rayon_core::thread_pool::ThreadPool::install::{{closure}}::hdc570676c9b4e5bc
  40:     0x7f2804d1533b - polars_io::parquet::read_impl::rg_to_dfs::h6cdec21adfc20165
  41:     0x7f28051938b0 - <core::iter::adapters::map::Map<I,F> as core::iter::traits::iterator::Iterator>::next::h40a17e50e9156906
  42:     0x7f280519211e - rayon::iter::plumbing::bridge_producer_consumer::helper::he97bfb3c4f4ab47a
  43:     0x7f28051915c9 - rayon_core::thread_pool::ThreadPool::install::{{closure}}::h3aa46f38e394eeb1
  44:     0x7f28051a7a2b - <rayon_core::job::StackJob<L,F,R> as rayon_core::job::Job>::execute::h16846a4b7b60704e
  45:     0x7f28032306ee - rayon_core::registry::WorkerThread::wait_until_cold::h4492c21ed6bd5c20
  46:     0x7f28063bd887 - std::sys_common::backtrace::__rust_begin_short_backtrace::h5158499b1bc9905d
  47:     0x7f28063bd56e - core::ops::function::FnOnce::call_once{{vtable.shim}}::hbbced209f456c5a9
  48:     0x7f280665fe86 - <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once::h2d19f142671865ec
                               at /rustc/503e129328080e924c0ddfca6abf4c2812580102/library/alloc/src/boxed.rs:2015:9
  49:     0x7f280665fe86 - <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once::h710d713fa9cb7127
                               at /rustc/503e129328080e924c0ddfca6abf4c2812580102/library/alloc/src/boxed.rs:2015:9
  50:     0x7f280665fe86 - std::sys::unix::thread::Thread::new::thread_start::haaff457ad882d05b
                               at /rustc/503e129328080e924c0ddfca6abf4c2812580102/library/std/src/sys/unix/thread.rs:108:17
  51:     0x7f29d19e5609 - start_thread
  52:     0x7f29d17b0353 - clone
  53:                0x0 - <unknown>

---------------------------------------------------------------------------
PanicException                            Traceback (most recent call last)
Cell In[4], line 2
      1 # results in error "The maximum key is too small" repeated many times
----> 2 df = pl.read_parquet(source=glob.glob(path_base + '*.parquet'), columns=cols_of_interest)

File /opt/miniconda3/envs/waveform/lib/python3.11/site-packages/polars/utils/deprecation.py:136, in deprecate_renamed_parameter.<locals>.decorate.<locals>.wrapper(*args, **kwargs)
    131 @wraps(function)
    132 def wrapper(*args: P.args, **kwargs: P.kwargs) -> T:
    133     _rename_keyword_argument(
    134         old_name, new_name, kwargs, function.__name__, version
    135     )
--> 136     return function(*args, **kwargs)

File /opt/miniconda3/envs/waveform/lib/python3.11/site-packages/polars/utils/deprecation.py:136, in deprecate_renamed_parameter.<locals>.decorate.<locals>.wrapper(*args, **kwargs)
    131 @wraps(function)
    132 def wrapper(*args: P.args, **kwargs: P.kwargs) -> T:
    133     _rename_keyword_argument(
    134         old_name, new_name, kwargs, function.__name__, version
    135     )
--> 136     return function(*args, **kwargs)

File /opt/miniconda3/envs/waveform/lib/python3.11/site-packages/polars/io/parquet/functions.py:191, in read_parquet(source, columns, n_rows, row_index_name, row_index_offset, parallel, use_statistics, hive_partitioning, rechunk, low_memory, storage_options, retries, use_pyarrow, pyarrow_options, memory_map)
    188         columns = [lf.columns[i] for i in columns]
    189     lf = lf.select(columns)
--> 191 return lf.collect(no_optimization=True)

File /opt/miniconda3/envs/waveform/lib/python3.11/site-packages/polars/lazyframe/frame.py:1937, in LazyFrame.collect(self, type_coercion, predicate_pushdown, projection_pushdown, simplify_expression, slice_pushdown, comm_subplan_elim, comm_subexpr_elim, no_optimization, streaming, background, _eager)
   1934 if background:
   1935     return InProcessQuery(ldf.collect_concurrently())
-> 1937 return wrap_df(ldf.collect())

PanicException: The maximum key is too small
```

### Issue description

I'm using Polars (0.20.10) to read some parquet files using this syntax

```python
pl.read_parquet(source=glob.glob(path_base + '*.parquet'), columns=cols_of_interest)
```

and getting the error: `The maximum key is too small`

I can alternatively use the Pyarrow backend with no errors:

```python
pl.read_parquet(source=path_base, columns=cols_of_interest, use_pyarrow=True)
```

Or just load a single 4GB file with no errors:

```python
df = pl.read_parquet(source='/phi/waveform/processed/parquet/NumericFullData_Set11_2024_02_07.parquet', columns=cols_of_interest)
```

Not sure how to troubleshoot this further.

### Expected behavior

Loads parquet files from disk into memory

### Installed versions

<details>

```
--------Version info---------
Polars:               0.20.10
Index type:           UInt32
Platform:             Linux-5.4.0-170-generic-x86_64-with-glibc2.31
Python:               3.11.6 | packaged by conda-forge | (main, Oct  3 2023, 10:40:35) [GCC 12.3.0]

----Optional dependencies----
adbc_driver_manager:  <not installed>
cloudpickle:          3.0.0
connectorx:           <not installed>
deltalake:            <not installed>
fsspec:               2024.2.0
gevent:               <not installed>
hvplot:               0.9.2
matplotlib:           3.8.3
numpy:                1.26.4
openpyxl:             3.1.2
pandas:               2.2.0
pyarrow:              15.0.0
pydantic:             <not installed>
pyiceberg:            <not installed>
pyxlsb:               <not installed>
sqlalchemy:           1.4.49
xlsx2csv:             <not installed>
xlsxwriter:           <not installed>
```

</details>

**Comment by ritchie46** [comment]
There is an overflow on a dictionary key. Curious if pyarrow does simply overflow and Polars panics, or if they read a different dictionary type. Have you got a sample file?

**Comment by magic-lantern** [comment]
If I replace this line:

```python
df = pl.read_parquet(source=glob.glob(path_base + '*.parquet'), columns=cols_of_interest)
```

With this:

```python
dfs = []
for f in glob.glob(path_base + '*.parquet'):
    print(f)
    dfs.append(pl.read_parquet(source=f, columns=cols_of_interest))
```

No errors occur and all data is read into memory without error.

However, if I then try to combine all 16 individual dataframes into one single dataframe with this code:

```python
df = pl.concat(dfs)
```

I get the following error:

```shell
---------------------------------------------------------------------------
SchemaError                               Traceback (most recent call last)
Cell In[6], line 1
----> 1 df = pl.concat(dfs)

File [/opt/miniconda3/envs/waveform/lib/python3.11/site-packages/polars/functions/eager.py:184](https://f:8000/opt/miniconda3/envs/waveform/lib/python3.11/site-packages/polars/functions/eager.py#line=183), in concat(items, how, rechunk, parallel)
    182 if isinstance(first, pl.DataFrame):
    183     if how == "vertical":
--> 184         out = wrap_df(plr.concat_df(elems))
    185     elif how == "vertical_relaxed":
    186         out = wrap_ldf(
    187             plr.concat_lf(
    188                 [df.lazy() for df in elems],
   (...)
    192             )
    193         ).collect(no_optimization=True)

SchemaError: cannot extend[/append](https://f:8000/append) Datetime(Microseconds, Some("Etc[/GMT](https://f:8000/GMT)+6")) with Datetime(Nanoseconds, Some("Etc[/GMT](https://f:8000/GMT)+7"))
```

So perhaps `The maximum key is too small` error is due to multiple timezones?

Will reprocess my files to remove time zone and see if that fixes the error.

**Comment by ritchie46** [comment]
Ah.. Your schema must be the same between the files. This doesn't seem to be the case. Somehow Polars didn't properly error here.

**Comment by magic-lantern** [comment]
In my case, the parquet files were generated using Pandas, but then parsed with Polars. I'm guessing the `maximum key is too small` error was due to something supported by Pandas but not by Polars. After fixing the schema issues, the error seems to have gone away.
