### ISSUE TITLE
`scan_parquet` segfault on main

### ISSUE THREAD

**Issue by cmdlineluser** [pola-rs/polars#14714]
### Checks

- [X] I have checked that this issue has not already been reported.
- [X] I have confirmed this bug exists on the [latest version](https://pypi.org/project/polars/) of Polars.

### Reproducible example

```python
import polars as pl

pl.scan_parquet("foo.parquet").collect()
```

### Log output

```shell
thread 'thread '<unnamed>' panicked at /Users/user/git/polars/crates/polars-utils/src/slice.rs:<unnamed>' panicked at /Users/user/git/polars/crates/polars-utils/src/slice.rs:92:18:
range end index 37 out of range for slice of length 16
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
92:18:
range end index 178 out of range for slice of length 16
thread '<unnamed>' panicked at /Users/user/git/polars/crates/polars-utils/src/slice.rs:92:18:
range end index 124 out of range for slice of length 16
```

### Issue description

The full dataset is from: https://github.com/pypi-data/data/releases/download/2024-02-22-03-05/index-15.parquet (1.3GB)

Reading that I get either a compute utf8 error or a segfault. (non-deterministic)

```python
import polars as pl

pl.scan_parquet("index-15.parquet").head(100_000).collect()
# utf8 error or segfault
```

Using `0.20.10` I extracted a single row which is attached: [foo.parquet.zip](https://github.com/pola-rs/polars/files/14417582/foo.parquet.zip) in an attempt for a minimal repro.

It produces range index errors and a thread panic.

### Expected behavior

Read file without error.

### Installed versions

<details>

```
--------Version info---------
Polars:               0.20.11
Index type:           UInt32
Platform:             macOS-13.6.1-arm64-arm-64bit
Python:               3.11.6 (main, Nov  2 2023, 04:39:43) [Clang 14.0.3 (clang-1403.0.22.14.1)]

----Optional dependencies----
adbc_driver_manager:  <not installed>
cloudpickle:          <not installed>
connectorx:           0.3.2
deltalake:            <not installed>
fsspec:               2023.6.0
gevent:               <not installed>
hvplot:               <not installed>
matplotlib:           3.8.2
numpy:                1.26.2
openpyxl:             <not installed>
pandas:               2.0.3
pyarrow:              12.0.1
pydantic:             2.5.2
pyiceberg:            <not installed>
pyxlsb:               <not installed>
sqlalchemy:           <not installed>
xlsx2csv:             0.8.1
xlsxwriter:           3.1.9
```

</details>

**Comment by ritchie46** [comment]
Found the culprit.
