### ISSUE TITLE
Divide each element in a list by an int

### ISSUE THREAD

**Issue by Liyixin95** [pola-rs/polars#14711]
### Description

I have a dataframe with a list column and an int column, then I want to divide these two columns like this:
```python
import polars as pl
from polars import col

lf = pl.DataFrame({"a": [[1, 2, 3], [1, 3], [2, 4, 6]], "b": [4, 5, 6]}).lazy()

df = lf.with_columns(c=(col("a") / col("b")).alias("c")).collect()

print(df)
```

then I get an error: 

```
Traceback (most recent call last):
  File "/root/miniconda3/envs/factor/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/root/miniconda3/envs/factor/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/root/python/ring_next/test/test.py", line 6, in <module>
    df = lf.with_columns(c=(col("a") / col("b")).alias("c")).collect()
  File "/root/miniconda3/envs/factor/lib/python3.10/site-packages/polars/lazyframe/frame.py", line 1937, in collect
    return wrap_df(ldf.collect())
polars.exceptions.ComputeError: cannot cast List type (inner: 'Int64', to: 'Float64')
```

**Comment by mcrumiller** [comment]
Related is #14541. I definitely think simple arithmetic should be allowed on lists/arrays, and inter-series arithmetic on arrays of the same dtype.

**Comment by itamarst** [comment]
I will start on this once #17823 is merged.

**Comment by deanm0000** [comment]
This is a narrow case of https://github.com/pola-rs/polars/issues/17496

**Comment by cmdlineluser** [comment]
This now works https://github.com/pola-rs/polars/pull/19162

```python
df = pl.DataFrame({"a": [[1, 2, 3], [1, 3], [2, 4, 6]], "b": [4, 5, 6]})

df.with_columns(c=(pl.col.a / pl.col.b))

# shape: (3, 3)
# ┌───────────┬─────┬───────────────────────────┐
# │ a         ┆ b   ┆ c                         │
# │ ---       ┆ --- ┆ ---                       │
# │ list[i64] ┆ i64 ┆ list[f64]                 │
# ╞═══════════╪═════╪═══════════════════════════╡
# │ [1, 2, 3] ┆ 4   ┆ [0.25, 0.5, 0.75]         │
# │ [1, 3]    ┆ 5   ┆ [0.2, 0.6]                │
# │ [2, 4, 6] ┆ 6   ┆ [0.333333, 0.666667, 1.0] │
# └───────────┴─────┴───────────────────────────┘
```
