### ISSUE TITLE
Polars job faces timeouts while reading multiple parquet files on a AWS EKS pod

### ISSUE THREAD

**Issue by arnaud-vennin** [pola-rs/polars#14841]
### Checks

- [X] I have checked that this issue has not already been reported.
- [X] I have confirmed this bug exists on the [latest version](https://pypi.org/project/polars/) of Polars.

### Reproducible example

```python
import logging

import polars as pl
import s3fs

pl.Config.set_verbose(True)


def mre_timeout(catalog: dict, env: str) -> str:
    """MRE timeout test"""

    logger = logging.getLogger()

    pl.Config.activate_decimals()

    logger.info(env)

    # Loads the catalog
    flow_name = catalog["df_taxi"]

    logger.info("Loading sources tables")

    df_taxi = pl.scan_parquet("s3://[bucket_name]/nyc_taxi_trip/*.parquet")

    taxi_final_df = (
        df_taxi.select(
            "VendorID", "passenger_count", "trip_distance", "fare_amount", "tip_amount", "congestion_surcharge"
        )
        .filter(pl.col("passenger_count").is_between(1, 5))  # type: ignore
        .group_by("VendorID")
        .agg(
            pl.col("passenger_count").sum().alias("passenger_total_count"),  # type: ignore
            pl.col("trip_distance").sum().alias("trip_total_distance"),  # type: ignore
            pl.col("fare_amount").sum().alias("total_fare_amount"),  # type: ignore
            pl.col("tip_amount").sum().alias("total_tip_amount"),  # type: ignore
            pl.col("congestion_surcharge").sum().alias("total_congestion_surcharge"),  # type: ignore
        )  # type: ignore
        .select(
            "VendorID",
            "passenger_total_count",
            "trip_total_distance",
            "total_fare_amount",
            "total_tip_amount",
            "total_congestion_surcharge",
        )
        .sort("VendorID", descending=True)
    )

    fs_sys = s3fs.S3FileSystem()
    with fs_sys.open("s3:/[bucket_name]/nyc_taxi_trip_output" + ".parquet", mode="wb") as final_df:
        taxi_final_df.collect(streaming=True).write_parquet(final_df, compression="snappy")  # type: ignore

    return "NYC taxi trip dataset saved" + flow_name
```

### Log output

```shell
POLARS PREFETCH_SIZE: 16
RUN STREAMING PIPELINE
parquet -> projection -> filter -> primitive_group_by -> fast_projection -> sort -> ordered_sink
RefCell { value: [] }
STREAMING CHUNK SIZE: 49998 rows
STREAMING CHUNK SIZE: 49998 rows
STREAMING CHUNK SIZE: 49998 rows
STREAMING CHUNK SIZE: 49998 rows
STREAMING CHUNK SIZE: 49998 rows
STREAMING CHUNK SIZE: 49998 rows
STREAMING CHUNK SIZE: 49998 rows
STREAMING CHUNK SIZE: 49998 rows
STREAMING CHUNK SIZE: 49998 rows
STREAMING CHUNK SIZE: 49998 rows
STREAMING CHUNK SIZE: 49998 rows
STREAMING CHUNK SIZE: 49998 rows
STREAMING CHUNK SIZE: 49998 rows
STREAMING CHUNK SIZE: 49998 rows
STREAMING CHUNK SIZE: 49998 rows
STREAMING CHUNK SIZE: 49998 rows
POLARS ROW_GROUP PREFETCH_SIZE: 128


Traceback (most recent call last):
  File "/usr/local/bin/[project_name]", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.9/site-packages/[project_name]/main.py", line 51, in main
    print(name_to_func[args.job_name](catalog, args.env))
  File "/usr/local/lib/python3.9/site-packages/[project_name]/jobs/mre_timeout.py", line 59, in mre_timeout
    taxi_final_df.collect(streaming=True).write_parquet(final_df, compression="snappy")  # type: ignore
  File "/usr/local/lib/python3.9/site-packages/polars/lazyframe/frame.py", line 1939, in collect
    return wrap_df(ldf.collect())
polars.exceptions.ComputeError: Generic S3 error: Error after 0 retries in 300.001210265s, max_retries:2, retry_timeout:10s, source:error sending request for url (https://s3.eu-west-1.amazonaws.com/[bucket_name]/nyc_taxi_trip/yellow_tripdata_2021-01.parquet): operation timed out
```

### Issue description

The job is launched from a AWS EKS cluster (version 1.28) directly on OpenLens through a kubectl command.
The pod has 30 Gb memory and 2 CPUs.
The dataset used for the test comes from NYC open data concerning Yellow Taxi Trip Records (https://www.nyc.gov/site/tlc/about/tlc-trip-record-data.page). Years from january 2020 to december 2023 were download and put on a unique folder. Each file has 54 Mo compressed size.
The dataset is read in Polars from an AWS S3 bucket.
The transformation are provided for testing purpose only, they don't attempt to calculate anything.
The container metrics are monitored on OpensLens interface. During the launch the memory and CPU usages remain very low (around 100 MiB and 0. respectively). No activity on the filesystem.
I noticed that the timeouts increased on the 0.20.13 Polars version.
"Type: ignore" are to skip mypy error messages related to Polars.

### Expected behavior

The job should read the data through scan_parquet function, transform and save it on AWS S3.

### Installed versions

<details>

```
--------Version info---------
Polars:               0.20.13
Index type:           UInt32
Platform:             Linux-6.1.77-x86_64-with-glibc2.28
Python:               3.9.17 (main, Jun 13 2023, 16:07:34) 
[GCC 8.3.0]

----Optional dependencies----
adbc_driver_manager:  <not installed>
cloudpickle:          <not installed>
connectorx:           <not installed>
deltalake:            0.13.0
fsspec:               2024.2.0
gevent:               <not installed>
hvplot:               <not installed>
matplotlib:           <not installed>
numpy:                1.26.4
openpyxl:             <not installed>
pandas:               1.5.3
pyarrow:              10.0.1
pydantic:             2.4.2
pyiceberg:            <not installed>
pyxlsb:               <not installed>
sqlalchemy:           <not installed>
xlsx2csv:             <not installed>
xlsxwriter:           <not installed>
```

</details>

**Comment by arnaud-vennin** [comment]
Hi,
We investigated with the Ops team which manages the EKS cluster on which the Polars script runs.
Apparently it may be due to the fact that the pod does not have time to fully gets up before Polars starts.
A simple solution was proposed : adding a 10 seconds sleep function at the beginning of the script. 
Polars version was also turn back to 0.20.10 since we faces concurrency tuner deadlock as mentioned on Discord (https://github.com/pola-rs/polars/pull/14827).
The data ingestion will run for several days to fully validate this solution.

**Comment by arnaud-vennin** [comment]
Hi,
I let the Polars job runs for several days : 15 launches, no retry nor timeout. It works perfectly.
The solution was to add a 10 seconds sleep function at the beginning of the main.py to give time to the EKS pod to get up completely.
