### ISSUE TITLE
[Regression, Python 0.20.14] Extending separate DataFrames from the same original DataFrame results in null values

### ISSUE THREAD

**Issue by jasperswallen** [pola-rs/polars#14914]
### Checks

- [X] I have checked that this issue has not already been reported.
- [X] I have confirmed this bug exists on the [latest version](https://pypi.org/project/polars/) of Polars.

### Reproducible example

```python
import polars as pl
from polars.testing import assert_frame_equal

df = pl.DataFrame({"t": [1, 2, 3, 4], "a": [3.0, 2.0, 1.0, None], "b": [6.0, 5.0, None, 4.0]})

a = df.select("t", "a").drop_nulls()
b = df.select("t", "b").drop_nulls().rename({"b": "a"})

ef = a.extend(b)

assert_frame_equal(
    ef,
    pl.DataFrame(
        {
            "t": [1, 2, 3, 1, 2, 4],
            "a": [3.0, 2.0, 1.0, 6.0, 5.0, 4.0],
        }
    ),
)
```

Output:

```shell
$ python3 test/test.py
a: shape: (3, 2)
┌─────┬─────┐
│ t   ┆ a   │
│ --- ┆ --- │
│ i64 ┆ f64 │
╞═════╪═════╡
│ 1   ┆ 3.0 │
│ 2   ┆ 2.0 │
│ 3   ┆ 1.0 │
└─────┴─────┘
b: shape: (3, 2)
┌─────┬─────┐
│ t   ┆ a   │
│ --- ┆ --- │
│ i64 ┆ f64 │
╞═════╪═════╡
│ 1   ┆ 6.0 │
│ 2   ┆ 5.0 │
│ 4   ┆ 4.0 │
└─────┴─────┘

a (extended): shape: (6, 2)
┌─────┬──────┐
│ t   ┆ a    │
│ --- ┆ ---  │
│ i64 ┆ f64  │
╞═════╪══════╡
│ 1   ┆ 3.0  │
│ 2   ┆ 2.0  │
│ 3   ┆ 1.0  │
│ 1   ┆ null │
│ 2   ┆ null │
│ 4   ┆ null │
└─────┴──────┘
b: shape: (3, 2)
┌─────┬─────┐
│ t   ┆ a   │
│ --- ┆ --- │
│ i64 ┆ f64 │
╞═════╪═════╡
│ 1   ┆ 6.0 │
│ 2   ┆ 5.0 │
│ 4   ┆ 4.0 │
└─────┴─────┘
extended: shape: (6, 2)
┌─────┬──────┐
│ t   ┆ a    │
│ --- ┆ ---  │
│ i64 ┆ f64  │
╞═════╪══════╡
│ 1   ┆ 3.0  │
│ 2   ┆ 2.0  │
│ 3   ┆ 1.0  │
│ 1   ┆ null │
│ 2   ┆ null │
│ 4   ┆ null │
└─────┴──────┘
Traceback (most recent call last):
  File "/home/jswallen/venv/lib/python3.11/site-packages/polars/testing/asserts/frame.py", line 116, in assert_frame_equal
    _assert_series_values_equal(
  File "/home/jswallen/venv/lib/python3.11/site-packages/polars/testing/asserts/series.py", line 178, in _assert_series_values_equal
    _assert_series_null_values_match(left, right)
  File "/home/jswallen/venv/lib/python3.11/site-packages/polars/testing/asserts/series.py", line 233, in _assert_series_null_values_match
    raise_assertion_error(
  File "/home/jswallen/venv/lib/python3.11/site-packages/polars/testing/asserts/utils.py", line 12, in raise_assertion_error
    raise AssertionError(msg) from cause
AssertionError: Series are different (null value mismatch)
[left]:  [3.0, 2.0, 1.0, None, None, None]
[right]: [3.0, 2.0, 1.0, 6.0, 5.0, 4.0]

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/jswallen/test/test.py", line 17, in <module>
    assert_frame_equal(
  File "/home/jswallen/venv/lib/python3.11/site-packages/polars/testing/asserts/frame.py", line 125, in assert_frame_equal
    raise_assertion_error(
  File "/home/jswallen/venv/lib/python3.11/site-packages/polars/testing/asserts/utils.py", line 12, in raise_assertion_error
    raise AssertionError(msg) from cause
AssertionError: DataFrames are different (value mismatch for column 'a')
[left]:  [3.0, 2.0, 1.0, None, None, None]
[right]: [3.0, 2.0, 1.0, 6.0, 5.0, 4.0]
```

### Issue description

In this example, I am splitting a dataframe into two separate dataframes, renaming a column, and then stacking them. I expect the columns from each new dataframe to be preserved - however, the second dataframe's renamed column is essentially not extended.

Using `a.vstack(b)` works as expected.

This is a regression - this functionality worked in Polars Python 0.20.13.

### Expected behavior

```python
import polars as pl
from polars.testing import assert_frame_equal

df = pl.DataFrame({"t": [1, 2, 3, 4], "a": [3.0, 2.0, 1.0, None], "b": [6.0, 5.0, None, 4.0]})

a = df.select("t", "a").drop_nulls()
b = df.select("t", "b").drop_nulls().rename({"b": "a"})

ef = a.vstack(b)

assert_frame_equal(
    ef,
    pl.DataFrame(
        {
            "t": [1, 2, 3, 1, 2, 4],
            "a": [3.0, 2.0, 1.0, 6.0, 5.0, 4.0],
        }
    ),
)
```

Output:

```
python3 test/test.py
a: shape: (3, 2)
┌─────┬─────┐
│ t   ┆ a   │
│ --- ┆ --- │
│ i64 ┆ f64 │
╞═════╪═════╡
│ 1   ┆ 3.0 │
│ 2   ┆ 2.0 │
│ 3   ┆ 1.0 │
└─────┴─────┘
b: shape: (3, 2)
┌─────┬─────┐
│ t   ┆ a   │
│ --- ┆ --- │
│ i64 ┆ f64 │
╞═════╪═════╡
│ 1   ┆ 6.0 │
│ 2   ┆ 5.0 │
│ 4   ┆ 4.0 │
└─────┴─────┘

a (vstack non-in-place): shape: (3, 2)
┌─────┬─────┐
│ t   ┆ a   │
│ --- ┆ --- │
│ i64 ┆ f64 │
╞═════╪═════╡
│ 1   ┆ 3.0 │
│ 2   ┆ 2.0 │
│ 3   ┆ 1.0 │
└─────┴─────┘
b: shape: (3, 2)
┌─────┬─────┐
│ t   ┆ a   │
│ --- ┆ --- │
│ i64 ┆ f64 │
╞═════╪═════╡
│ 1   ┆ 6.0 │
│ 2   ┆ 5.0 │
│ 4   ┆ 4.0 │
└─────┴─────┘
vstacked: shape: (6, 2)
┌─────┬─────┐
│ t   ┆ a   │
│ --- ┆ --- │
│ i64 ┆ f64 │
╞═════╪═════╡
│ 1   ┆ 3.0 │
│ 2   ┆ 2.0 │
│ 3   ┆ 1.0 │
│ 1   ┆ 6.0 │
│ 2   ┆ 5.0 │
│ 4   ┆ 4.0 │
└─────┴─────┘
```

### Installed versions

<details>

```
--------Version info---------
Polars:               0.20.14
Index type:           UInt32
Platform:             Linux-5.15.133.1-microsoft-standard-WSL2-x86_64-with-glibc2.35
Python:               3.11.7 (main, Dec  8 2023, 18:56:58) [GCC 11.4.0]

----Optional dependencies----
adbc_driver_manager:  <not installed>
cloudpickle:          <not installed>
connectorx:           <not installed>
deltalake:            <not installed>
fastexcel:            <not installed>
fsspec:               <not installed>
gevent:               <not installed>
hvplot:               <not installed>
matplotlib:           <not installed>
numpy:                1.26.4
openpyxl:             <not installed>
pandas:               2.2.0
pyarrow:              15.0.0
pydantic:             2.6.1
pyiceberg:            <not installed>
pyxlsb:               <not installed>
sqlalchemy:           <not installed>
xlsx2csv:             <not installed>
xlsxwriter:           <not installed>
```

</details>

**Comment by MarcoGorelli** [comment]
Thanks @jasperswallen for the report

from git bisect, I'm seeing:

8dd179fbf53e492848942a26c2430bbf14b26e7b is the first bad commit
commit 8dd179fbf53e492848942a26c2430bbf14b26e7b
Author: Orson Peters <...>
Date:   Wed Mar 6 07:37:01 2024 +0100

    perf: rework scalar filter kernels (#14865)

@orlp does this seem plausible? fancy taking a look?

**Comment by orlp** [comment]
@MarcoGorelli I can't reproduce on the latest `main` anymore, but can on the latest released version. Not sure what the cause is right now.

**Comment by orlp** [comment]
@MarcoGorelli I found the issue, my new filter code gives buffers `Vec<u8>` that are larger than necessary (as the efficient filter code uses this padding for more efficient processing) to the validity bitmap, but `MutableBitmap` still has several codepaths that assume the length of the buffer is exactly long enough for the data.

**Comment by orlp** [comment]
@MarcoGorelli Actually scratch that, the issue is in my scalar code, I do give too large a buffer but that's because I set the length wrong. This is pretty rough, I did
```rust
out.set_len(mask_bits_set);
```
instead of
```rust
out.set_len(mask_bits_set.ceil_div(8));
```
