### ISSUE TITLE
Segmentation Fault on Accessing Field of Struct in List when null

### ISSUE THREAD

**Issue by JacquesDonnelly** [pola-rs/polars#14927]
### Checks

- [X] I have checked that this issue has not already been reported.
- [X] I have confirmed this bug exists on the [latest version](https://pypi.org/project/polars/) of Polars.

### Reproducible example

```python
import polars as pl

df = pl.DataFrame(
    [
        {
            "index": 0,
            "col_0": [{"field_0": 1.}],
        },
        {
            "index": 1,
            "col_0": None,
        },
    ]
)

expr = pl.col("col_0").list.get(0).struct.field("field_0")
df = df.filter(pl.col("index") > 0).with_columns(expr)
```

### Log output

```shell
dataframe filtered
[1]    15546 segmentation fault (core dumped)  POLARS_VERBOSE=1 python3 scratch.py
```

### Issue description

Upgraded from version `0.18.13` to `0.20.14` and the error was introduced. 

When I tried reproducing the example I initially set all values of `col_0` to None yielding a column dype of `null`. The code runs as expected when this is the case. However, when the col dtype is `list[struct[n]]` I observe the issue (Hence why I start with two rows and filter to 1). 

### Expected behavior

I would expect the expression to just return `null` and obviously not seg fault. 

### Installed versions

<details>

```
--------Version info---------
Polars:               0.20.14
Index type:           UInt32
Platform:             Linux-5.4.0-1106-gcp-x86_64-with-glibc2.27
Python:               3.9.5 (default, Aug 25 2023, 09:33:52)
[GCC 7.5.0]

----Optional dependencies----
adbc_driver_manager:  <not installed>
cloudpickle:          <not installed>
connectorx:           <not installed>
deltalake:            <not installed>
fastexcel:            <not installed>
fsspec:               <not installed>
gevent:               <not installed>
hvplot:               <not installed>
matplotlib:           3.6.2
numpy:                1.23.4
openpyxl:             <not installed>
pandas:               1.5.1
pyarrow:              10.0.1
pydantic:             <not installed>
pyiceberg:            <not installed>
pyxlsb:               <not installed>
sqlalchemy:           <not installed>
xlsx2csv:             <not installed>
xlsxwriter:           <not installed>
```

</details>

**Comment by JacquesDonnelly** [comment]
something else I just observed additionally:

If you remove the filtering from the above example and call `with_columns` with both rows in the dataframe,  everything works as expected. The error only appears to be present when all values are null.

**Comment by JacquesDonnelly** [comment]
And from some more debugging, it appears the error is happening in `list.get(0)`

**Comment by orlp** [comment]
Can reproduce in the latest main, in debug mode we see the failing assertion:

```rust
thread '<unnamed>' panicked at crates/polars-arrow/src/compute/take/bitmap.rs:9:9:
assertion failed: (index as usize) < values.len()
stack backtrace:
   0: rust_begin_unwind
             at /rustc/397937d812852f9bbeb671005cb399dbcb357cde/library/std/src/panicking.rs:648:5
   1: core::panicking::panic_fmt
             at /rustc/397937d812852f9bbeb671005cb399dbcb357cde/library/core/src/panicking.rs:72:14
   2: core::panicking::panic
             at /rustc/397937d812852f9bbeb671005cb399dbcb357cde/library/core/src/panicking.rs:144:5
   3: polars_arrow::compute::take::bitmap::take_bitmap_unchecked::{{closure}}
             at /Users/orlp/programming/rust/polars/crates/polars-arrow/src/compute/take/bitmap.rs:9:9
   4: core::ops::function::impls::<impl core::ops::function::FnOnce<A> for &mut F>::call_once
             at /rustc/397937d812852f9bbeb671005cb399dbcb357cde/library/core/src/ops/function.rs:305:13
   5: core::option::Option<T>::map
             at /rustc/397937d812852f9bbeb671005cb399dbcb357cde/library/core/src/option.rs:1072:29
   6: <core::iter::adapters::map::Map<I,F> as core::iter::traits::iterator::Iterator>::next
             at /rustc/397937d812852f9bbeb671005cb399dbcb357cde/library/core/src/iter/adapters/map.rs:108:26
   7: polars_arrow::bitmap::mutable::get_byte_unchecked
             at /Users/orlp/programming/rust/polars/crates/polars-arrow/src/bitmap/mutable.rs:473:27
   8: polars_arrow::bitmap::mutable::extend_aligned_trusted_iter_unchecked
             at /Users/orlp/programming/rust/polars/crates/polars-arrow/src/bitmap/mutable.rs:522:29
   9: polars_arrow::bitmap::mutable::MutableBitmap::from_trusted_len_iter_unchecked
             at /Users/orlp/programming/rust/polars/crates/polars-arrow/src/bitmap/mutable.rs:596:22
  10: polars_arrow::bitmap::mutable::MutableBitmap::from_trusted_len_iter
             at /Users/orlp/programming/rust/polars/crates/polars-arrow/src/bitmap/mutable.rs:608:18
  11: polars_arrow::bitmap::immutable::Bitmap::from_trusted_len_iter
             at /Users/orlp/programming/rust/polars/crates/polars-arrow/src/bitmap/immutable.rs:510:9
  12: polars_arrow::compute::take::bitmap::take_bitmap_unchecked
             at /Users/orlp/programming/rust/polars/crates/polars-arrow/src/compute/take/bitmap.rs:12:5
  13: polars_arrow::compute::take::structure::take_unchecked::{{closure}}
             at /Users/orlp/programming/rust/polars/crates/polars-arrow/src/compute/take/structure.rs:31:18
  14: core::option::Option<T>::map
             at /rustc/397937d812852f9bbeb671005cb399dbcb357cde/library/core/src/option.rs:1072:29
  15: polars_arrow::compute::take::structure::take_unchecked
             at /Users/orlp/programming/rust/polars/crates/polars-arrow/src/compute/take/structure.rs:29:20
  16: polars_arrow::compute::take::take_unchecked
             at /Users/orlp/programming/rust/polars/crates/polars-arrow/src/compute/take/mod.rs:63:13
  17: polars_arrow::legacy::kernels::list::sublist_get
             at /Users/orlp/programming/rust/polars/crates/polars-arrow/src/legacy/kernels/list.rs:75:14
  18: polars_ops::chunked_array::list::namespace::ListNameSpaceImpl::lst_get::{{closure}}
             at /Users/orlp/programming/rust/polars/crates/polars-ops/src/chunked_array/list/namespace.rs:349:24
```

**Comment by orlp** [comment]
Bisecting to see where the error pops up...

**Comment by orlp** [comment]
```
e989418fbdd635b61771bf56a941897a57c90ae1 is the first bad commit
commit e989418fbdd635b61771bf56a941897a57c90ae1
Author: Ritchie Vink <ritchie46@gmail.com>
Date:   Wed Jan 31 21:32:04 2024 +0100

    chore: merge take kernels (#14137)

 .../polars-arrow/src/compute/cast/dictionary_to.rs |  39 +---
 crates/polars-arrow/src/compute/cast/mod.rs        |   2 +-
 crates/polars-arrow/src/compute/take/binary.rs     |   2 +-
 crates/polars-arrow/src/compute/take/binview.rs    |  22 ++
 crates/polars-arrow/src/compute/take/bitmap.rs     |  12 +
 crates/polars-arrow/src/compute/take/boolean.rs    |  56 ++---
 crates/polars-arrow/src/compute/take/dict.rs       |  44 ----
 .../src/compute/take/generic_binary.rs             |  80 ++++---
 crates/polars-arrow/src/compute/take/list.rs       |   7 +-
 crates/polars-arrow/src/compute/take/mod.rs        |  44 ++--
 crates/polars-arrow/src/compute/take/primitive.rs  | 157 ++++++-------
 crates/polars-arrow/src/compute/take/structure.rs  |  45 +---
 crates/polars-arrow/src/compute/take/utf8.rs       |  41 ----
 crates/polars-arrow/src/datatypes/mod.rs           |   5 +
 crates/polars-arrow/src/legacy/compute/mod.rs      |   2 +-
 .../polars-arrow/src/legacy/compute/take/bitmap.rs |  12 -
 .../src/legacy/compute/take/boolean.rs             |  79 -------
 .../src/legacy/compute/take/fixed_size_list.rs     | 109 ---------
 crates/polars-arrow/src/legacy/compute/take/mod.rs | 248 ---------------------
 .../src/legacy/kernels/fixed_size_list.rs          |   2 +-
 crates/polars-arrow/src/legacy/kernels/list.rs     |   4 +-
 .../src/chunked_array/ops/explode_and_offsets.rs   |   2 +-
 crates/polars-core/src/chunked_array/ops/gather.rs |   2 +-
 23 files changed, 215 insertions(+), 801 deletions(-)
 create mode 100644 crates/polars-arrow/src/compute/take/binview.rs
 create mode 100644 crates/polars-arrow/src/compute/take/bitmap.rs
 delete mode 100644 crates/polars-arrow/src/compute/take/dict.rs
 delete mode 100644 crates/polars-arrow/src/compute/take/utf8.rs
 delete mode 100644 crates/polars-arrow/src/legacy/compute/take/bitmap.rs
 delete mode 100644 crates/polars-arrow/src/legacy/compute/take/boolean.rs
 delete mode 100644 crates/polars-arrow/src/legacy/compute/take/fixed_size_list.rs
 delete mode 100644 crates/polars-arrow/src/legacy/compute/take/mod.rs
bisect found first bad commit
```
