### ISSUE TITLE
UInt16/Uint8 using by schema to create empty dataframe got error

### ISSUE THREAD

**Issue by SuFIND** [pola-rs/polars#14944]
### Checks

- [X] I have checked that this issue has not already been reported.
- [X] I have confirmed this bug exists on the [latest version](https://crates.io/crates/polars) of Polars.

### Reproducible example

- src/main.rs
```rust
use polars::prelude::{DataFrame, Schema, DataType};
use smartstring::SmartString;

fn main() {
    let mut schema = Schema::with_capacity(3);
    schema.insert_at_index(0, SmartString::from("UInt32"), DataType::UInt32).expect("error");
    schema.insert_at_index(1, SmartString::from("UInt16"), DataType::UInt16).expect("error");
    schema.insert_at_index(2, SmartString::from("UInt8"), DataType::UInt8).expect("error");

    let _empty_df = DataFrame::from(&schema);
}

```
- Cargo.toml
```toml
[package]
name = "polars_bug"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
polars = "0.38.1"
smartstring = "1.0.1"

```

### Log output

```shell
thread 'main' panicked at /Users/dimon/.cargo/registry/src/mirrors.tuna.tsinghua.edu.cn-2eab394af869c8a2/polars-core-0.38.1/src/series/ops/null.rs:74:17:
not implemented for dtype UInt16
stack backtrace:
   0: rust_begin_unwind
             at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/std/src/panicking.rs:645:5
   1: core::panicking::panic_fmt
             at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/core/src/panicking.rs:72:14
   2: polars_core::series::ops::null::<impl polars_core::series::Series>::full_null
             at /Users/dimon/.cargo/registry/src/mirrors.tuna.tsinghua.edu.cn-2eab394af869c8a2/polars-core-0.38.1/src/series/ops/null.rs:74:17
   3: polars_core::series::Series::new_empty
             at /Users/dimon/.cargo/registry/src/mirrors.tuna.tsinghua.edu.cn-2eab394af869c8a2/polars-core-0.38.1/src/series/mod.rs:156:9
   4: polars_core::frame::from::<impl core::convert::From<&polars_core::schema::Schema> for polars_core::frame::DataFrame>::from::{{closure}}
             at /Users/dimon/.cargo/registry/src/mirrors.tuna.tsinghua.edu.cn-2eab394af869c8a2/polars-core-0.38.1/src/frame/from.rs:36:34
   5: core::ops::function::impls::<impl core::ops::function::FnOnce<A> for &mut F>::call_once
             at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/core/src/ops/function.rs:305:13
   6: core::option::Option<T>::map
             at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/core/src/option.rs:1072:29
   7: <core::iter::adapters::map::Map<I,F> as core::iter::traits::iterator::Iterator>::next
             at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/core/src/iter/adapters/map.rs:104:26
   8: alloc::vec::Vec<T,A>::extend_desugared
             at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/alloc/src/vec/mod.rs:2891:35
   9: <alloc::vec::Vec<T,A> as alloc::vec::spec_extend::SpecExtend<T,I>>::spec_extend
             at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/alloc/src/vec/spec_extend.rs:17:9
  10: <alloc::vec::Vec<T> as alloc::vec::spec_from_iter_nested::SpecFromIterNested<T,I>>::from_iter
             at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/alloc/src/vec/spec_from_iter_nested.rs:43:9
  11: <alloc::vec::Vec<T> as alloc::vec::spec_from_iter::SpecFromIter<T,I>>::from_iter
             at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/alloc/src/vec/spec_from_iter.rs:33:9
  12: <alloc::vec::Vec<T> as core::iter::traits::collect::FromIterator<T>>::from_iter
             at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/alloc/src/vec/mod.rs:2791:9
  13: core::iter::traits::iterator::Iterator::collect
             at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/core/src/iter/traits/iterator.rs:2054:9
  14: polars_core::frame::from::<impl core::convert::From<&polars_core::schema::Schema> for polars_core::frame::DataFrame>::from
             at /Users/dimon/.cargo/registry/src/mirrors.tuna.tsinghua.edu.cn-2eab394af869c8a2/polars-core-0.38.1/src/frame/from.rs:34:20
  15: polars_bug::main
             at ./src/main.rs:10:21
  16: core::ops::function::FnOnce::call_once
             at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/core/src/ops/function.rs:250:5
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```

### Issue description

Try to create a no-data DataFrame by DataFrame::from(&schema). UInt16 / UInt8 got the error.

### Expected behavior

No Error.

### Installed versions

```toml
polars = "0.38.1"
smartstring = "1.0.1"
```

**Comment by lukemanley** [comment]
@SuFIND - can you try enabling the `dtype-u8` and `dtype-u16` features? They are not enabled by default.
