### ISSUE TITLE
Certain String Series results in getting rust panics when when `s.unique()`.

### ISSUE THREAD

**Issue by dalejung** [pola-rs/polars#14955]
### Checks

- [X] I have checked that this issue has not already been reported.
- [X] I have confirmed this bug exists on the [latest version](https://pypi.org/project/polars/) of Polars.

### Reproducible example

```python
    chunky = table['iq_id']
    assert isinstance(chunky, pa.ChunkedArray)
    chunky.unique()  # pyarrow unique works fine

    # reconverting strings. pyarrow => list => pyarrow
    new_chunks = pa.chunked_array([list(chunk) for chunk in chunky.chunks])

    also_good = pl.Series(chunky.combine_chunks())
    good_s = pl.Series(new_chunks)
    assert set(also_good.unique()) == set(good_s.unique())

    pl.Series(chunky.to_pandas()).unique()  # Also works

    bad_s = pl.Series(chunky)
    bad_s.unique()  # This panics
```

### Log output

```shell
thread '<unnamed>' panicked at library/core/src/panicking.rs:155:5:
slice::get_unchecked requires that the range is within the slice
stack backtrace:
   0:     0x71d272c33886 - std::backtrace_rs::backtrace::libunwind::trace::hd6c95564158d2ad1
                               at /rustc/397937d812852f9bbeb671005cb399dbcb357cde/library/std/src/../../backtrace/src/backtrace/libunwind.rs:104:5
   1:     0x71d272c33886 - std::backtrace_rs::backtrace::trace_unsynchronized::h1e73453937ee07b8
                               at /rustc/397937d812852f9bbeb671005cb399dbcb357cde/library/std/src/../../backtrace/src/backtrace/mod.rs:66:5
   2:     0x71d272c33886 - std::sys_common::backtrace::_print_fmt::ha4e1fd706ce229f6
                               at /rustc/397937d812852f9bbeb671005cb399dbcb357cde/library/std/src/sys_common/backtrace.rs:68:5
   3:     0x71d272c33886 - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::h39795cad8f90e005
                               at /rustc/397937d812852f9bbeb671005cb399dbcb357cde/library/std/src/sys_common/backtrace.rs:44:22
   4:     0x71d272c636cc - core::fmt::rt::Argument::fmt::h3960dd13bbb5335d
                               at /rustc/397937d812852f9bbeb671005cb399dbcb357cde/library/core/src/fmt/rt.rs:142:9
   5:     0x71d272c636cc - core::fmt::write::h2b281d9025b7c47b
                               at /rustc/397937d812852f9bbeb671005cb399dbcb357cde/library/core/src/fmt/mod.rs:1120:17
   6:     0x71d272c2feef - std::io::Write::write_fmt::h18044c54acec8470
                               at /rustc/397937d812852f9bbeb671005cb399dbcb357cde/library/std/src/io/mod.rs:1846:15
   7:     0x71d272c33634 - std::sys_common::backtrace::_print::h7a96956925b1db50
                               at /rustc/397937d812852f9bbeb671005cb399dbcb357cde/library/std/src/sys_common/backtrace.rs:47:5
   8:     0x71d272c33634 - std::sys_common::backtrace::print::h154e885ac7142937
                               at /rustc/397937d812852f9bbeb671005cb399dbcb357cde/library/std/src/sys_common/backtrace.rs:34:9
   9:     0x71d272c34cab - std::panicking::default_hook::{{closure}}::hcfb38eaaff34d735
  10:     0x71d272c349f9 - std::panicking::default_hook::h9d19a71b480c31c0
                               at /rustc/397937d812852f9bbeb671005cb399dbcb357cde/library/std/src/panicking.rs:292:9
  11:     0x71d272c3514d - std::panicking::rust_panic_with_hook::hb2c8227f8d32aff4
                               at /rustc/397937d812852f9bbeb671005cb399dbcb357cde/library/std/src/panicking.rs:782:13
  12:     0x71d272c34fe9 - std::panicking::begin_panic_handler::{{closure}}::h987389c1664b681c
                               at /rustc/397937d812852f9bbeb671005cb399dbcb357cde/library/std/src/panicking.rs:652:13
  13:     0x71d272c33d66 - std::sys_common::backtrace::__rust_end_short_backtrace::hfacc8ef11205d4dc
                               at /rustc/397937d812852f9bbeb671005cb399dbcb357cde/library/std/src/sys_common/backtrace.rs:171:18
  14:     0x71d272c34d54 - rust_begin_unwind
                               at /rustc/397937d812852f9bbeb671005cb399dbcb357cde/library/std/src/panicking.rs:648:5
  15:     0x71d26844179a - core::panicking::panic_nounwind_fmt::runtime::h9e10acb3330b810e
                               at /rustc/397937d812852f9bbeb671005cb399dbcb357cde/library/core/src/panicking.rs:110:18
  16:     0x71d26844179a - core::panicking::panic_nounwind_fmt::h5f2e5fe039d44d4b
                               at /rustc/397937d812852f9bbeb671005cb399dbcb357cde/library/core/src/panicking.rs:122:9
  17:     0x71d268441849 - core::panicking::panic_nounwind::hcc90671dffb8029c
                               at /rustc/397937d812852f9bbeb671005cb399dbcb357cde/library/core/src/panicking.rs:155:5
  18:     0x71d272802d11 - <core::ops::range::Range<usize> as core::slice::index::SliceIndex<[T]>>::get_unchecked::h46ec5f39b3e0031b
                               at /rustc/397937d812852f9bbeb671005cb399dbcb357cde/library/core/src/slice/index.rs:365:9
  19:     0x71d271e27e2b - core::slice::<impl [T]>::get_unchecked::h4995b687d6c866c5
                               at /rustc/397937d812852f9bbeb671005cb399dbcb357cde/library/core/src/slice/mod.rs:677:20
  20:     0x71d271914cb5 - polars_arrow::array::binview::BinaryViewArrayGeneric<T>::value_unchecked::h03b8fcbd494684bb
                               at /python/externals/polars/crates/polars-arrow/src/array/binview/mod.rs:296:13
  21:     0x71d2719126d7 - polars_arrow::array::binview::iterator::<impl polars_arrow::array::iterator::ArrayAccessor for polars_arrow::array::binview::BinaryViewArrayGeneric<T>>::value_unchecked::ha61e70ff11cc0366
                               at /python/externals/polars/crates/polars-arrow/src/array/binview/iterator.rs:11:9
  22:     0x71d271a2fac6 - <polars_arrow::array::iterator::ArrayValuesIter<A> as core::iter::traits::iterator::Iterator>::next::h22088cb35e1572d9
                               at /python/externals/polars/crates/polars-arrow/src/array/iterator.rs:53:23
  23:     0x71d270069241 - core::iter::traits::iterator::Iterator::fold::h693f3246ea15ec35
                               at /rustc/397937d812852f9bbeb671005cb399dbcb357cde/library/core/src/iter/traits/iterator.rs:2617:29
  24:     0x71d26f1ba925 - <core::iter::adapters::map::Map<I,F> as core::iter::traits::iterator::Iterator>::fold::h75748b4abb7cc1b1
                               at /rustc/397937d812852f9bbeb671005cb399dbcb357cde/library/core/src/iter/adapters/map.rs:129:9
  25:     0x71d26f2911d9 - core::iter::traits::iterator::Iterator::for_each::hf82c7c58f43ccc48
                               at /rustc/397937d812852f9bbeb671005cb399dbcb357cde/library/core/src/iter/traits/iterator.rs:848:9
  26:     0x71d26efc8daa - <hashbrown::map::HashMap<K,V,S,A> as core::iter::traits::collect::Extend<(K,V)>>::extend::hbaaaa7da08e722dc
                               at /home/user/.cargo/registry/src/index.crates.io-6f17d22bba15001f/hashbrown-0.14.3/src/map.rs:6511:9
  27:     0x71d26ec88f69 - <hashbrown::set::HashSet<T,S,A> as core::iter::traits::collect::Extend<T>>::extend::h50e0b9166a7652af
                               at /home/user/.cargo/registry/src/index.crates.io-6f17d22bba15001f/hashbrown-0.14.3/src/set.rs:1355:9
  28:     0x71d26fb2c053 - polars_core::chunked_array::ops::unique::<impl polars_core::chunked_array::ops::ChunkUnique<polars_core::datatypes::BinaryType> for polars_core::chunked_array::ChunkedArray<polars_core::datatypes::BinaryType>>::unique::hb8d2882d8403a861
                               at /python/externals/polars/crates/polars-core/src/chunked_array/ops/unique/mod.rs:196:21
  29:     0x71d26fb2baf5 - polars_core::chunked_array::ops::unique::<impl polars_core::chunked_array::ops::ChunkUnique<polars_core::datatypes::StringType> for polars_core::chunked_array::ChunkedArray<polars_core::datatypes::StringType>>::unique::h1b73dea35a5143af
                               at /python/externals/polars/crates/polars-core/src/chunked_array/ops/unique/mod.rs:176:19
  30:     0x71d26f4db60d - polars_core::series::implementations::string::<impl polars_core::series::series_trait::SeriesTrait for polars_core::series::implementations::SeriesWrap<polars_core::chunked_array::ChunkedArray<polars_core::datatypes::StringType>>>::unique::hadbd3e7dd3dd13bc
                               at /python/externals/polars/crates/polars-core/src/series/implementations/string.rs:201:9
  31:     0x71d26b22fdbe - polars_plan::dsl::function_expr::unique::unique::h988325f13b128f23
                               at /python/externals/polars/crates/polars-plan/src/dsl/function_expr/unique.rs:7:9
  32:     0x71d26b47bff9 - polars_plan::dsl::function_expr::<impl core::convert::From<polars_plan::dsl::function_expr::FunctionExpr> for polars_plan::dsl::expr_dyn_fn::SpecialEq<alloc::sync::Arc<dyn polars_plan::dsl::expr_dyn_fn::SeriesUdf>>>::from::{{closure}}::h90568845d867bb69
                               at /python/externals/polars/crates/polars-plan/src/dsl/function_expr/mod.rs:783:13
  33:     0x71d26b479344 - <F as polars_plan::dsl::expr_dyn_fn::SeriesUdf>::call_udf::hdf5a32d934e56cfe
                               at /python/externals/polars/crates/polars-plan/src/dsl/expr_dyn_fn.rs:84:9
  34:     0x71d26a99a531 - polars_lazy::physical_plan::expressions::apply::ApplyExpr::eval_and_flatten::hef3617c2d2f92ab9
                               at /python/externals/polars/crates/polars-lazy/src/physical_plan/expressions/apply.rs:120:28
  35:     0x71d26a99d927 - <polars_lazy::physical_plan::expressions::apply::ApplyExpr as polars_lazy::physical_plan::expressions::PhysicalExpr>::evaluate::h5c5526f88b242fb7
                               at /python/externals/polars/crates/polars-lazy/src/physical_plan/expressions/apply.rs:313:16
  36:     0x71d26a54f54a - polars_lazy::physical_plan::executors::projection_utils::run_exprs_seq::{{closure}}::hecf86115a153cda8
                               at /python/externals/polars/crates/polars-lazy/src/physical_plan/executors/projection_utils.rs:212:29
  37:     0x71d26a76bc50 - core::iter::adapters::map::map_try_fold::{{closure}}::h9677ed35b886a54b
                               at /rustc/397937d812852f9bbeb671005cb399dbcb357cde/library/core/src/iter/adapters/map.rs:96:28
  38:     0x71d26a4d7c41 - core::iter::traits::iterator::Iterator::try_fold::h1dda0145007e8915
                               at /rustc/397937d812852f9bbeb671005cb399dbcb357cde/library/core/src/iter/traits/iterator.rs:2440:21
  39:     0x71d26a75f500 - <core::iter::adapters::map::Map<I,F> as core::iter::traits::iterator::Iterator>::try_fold::h67998e5c88da175e
                               at /rustc/397937d812852f9bbeb671005cb399dbcb357cde/library/core/src/iter/adapters/map.rs:122:9
  40:     0x71d26aa2f82a - <core::iter::adapters::GenericShunt<I,R> as core::iter::traits::iterator::Iterator>::try_fold::he0cefacf3532fad5
                               at /rustc/397937d812852f9bbeb671005cb399dbcb357cde/library/core/src/iter/adapters/mod.rs:201:9
  41:     0x71d26aa2b3cf - core::iter::traits::iterator::Iterator::try_for_each::hdf46c567d25d0374
                               at /rustc/397937d812852f9bbeb671005cb399dbcb357cde/library/core/src/iter/traits/iterator.rs:2502:9
  42:     0x71d26aa2b3cf - <core::iter::adapters::GenericShunt<I,R> as core::iter::traits::iterator::Iterator>::next::h33f98acd709e97e2
                               at /rustc/397937d812852f9bbeb671005cb399dbcb357cde/library/core/src/iter/adapters/mod.rs:184:14
  43:     0x71d26a5c0143 - <alloc::vec::Vec<T> as alloc::vec::spec_from_iter_nested::SpecFromIterNested<T,I>>::from_iter::hb48b25795ec7a406
                               at /rustc/397937d812852f9bbeb671005cb399dbcb357cde/library/alloc/src/vec/spec_from_iter_nested.rs:26:32
  44:     0x71d26a5fd23e - <alloc::vec::Vec<T> as alloc::vec::spec_from_iter::SpecFromIter<T,I>>::from_iter::h125b3a7bfdc28814
                               at /rustc/397937d812852f9bbeb671005cb399dbcb357cde/library/alloc/src/vec/spec_from_iter.rs:33:9
  45:     0x71d26a5fc2d7 - <alloc::vec::Vec<T> as core::iter::traits::collect::FromIterator<T>>::from_iter::hff51eb8e2310db07
                               at /rustc/397937d812852f9bbeb671005cb399dbcb357cde/library/alloc/src/vec/mod.rs:2836:9
  46:     0x71d26a525e12 - core::iter::traits::iterator::Iterator::collect::h8f2e33739764a7bd
                               at /rustc/397937d812852f9bbeb671005cb399dbcb357cde/library/core/src/iter/traits/iterator.rs:2034:9
  47:     0x71d26a525e12 - <core::result::Result<V,E> as core::iter::traits::collect::FromIterator<core::result::Result<A,E>>>::from_iter::{{closure}}::hd80de412808f8fde
                               at /rustc/397937d812852f9bbeb671005cb399dbcb357cde/library/core/src/result.rs:1934:51
  48:     0x71d26aa3bacf - core::iter::adapters::try_process::h031887d09e255050
                               at /rustc/397937d812852f9bbeb671005cb399dbcb357cde/library/core/src/iter/adapters/mod.rs:170:17
  49:     0x71d26a525339 - <core::result::Result<V,E> as core::iter::traits::collect::FromIterator<core::result::Result<A,E>>>::from_iter::hc73f048aef023baa
                               at /rustc/397937d812852f9bbeb671005cb399dbcb357cde/library/core/src/result.rs:1934:9
  50:     0x71d26a767a7e - core::iter::traits::iterator::Iterator::collect::hc8de1ef9e8ad9c38
                               at /rustc/397937d812852f9bbeb671005cb399dbcb357cde/library/core/src/iter/traits/iterator.rs:2034:9
  51:     0x71d26a55f4ae - polars_lazy::physical_plan::executors::projection_utils::run_exprs_seq::hf655d798c5e6066e
                               at /python/externals/polars/crates/polars-lazy/src/physical_plan/executors/projection_utils.rs:212:5
  52:     0x71d26a55f674 - polars_lazy::physical_plan::executors::projection_utils::evaluate_physical_expressions::hf9bba6b5143dfeee
                               at /python/externals/polars/crates/polars-lazy/src/physical_plan/executors/projection_utils.rs:259:9
  53:     0x71d26aab0970 - polars_lazy::physical_plan::executors::projection::ProjectionExec::execute_impl::h72c26d12ea2ef641
                               at /python/externals/polars/crates/polars-lazy/src/physical_plan/executors/projection.rs:23:29
  54:     0x71d26aab1279 - <polars_lazy::physical_plan::executors::projection::ProjectionExec as polars_lazy::physical_plan::executors::executor::Executor>::execute::h75ab58e4eacdcfa4
                               at /python/externals/polars/crates/polars-lazy/src/physical_plan/executors/projection.rs:85:13
  55:     0x71d26a67e131 - polars_lazy::frame::LazyFrame::collect::hec91afae60564709
                               at /python/externals/polars/crates/polars-lazy/src/frame/mod.rs:699:19
  56:     0x71d269b17dc7 - polars::lazyframe::PyLazyFrame::collect::{{closure}}::h65471c5ff12564fc
                               at /python/externals/polars/py-polars/src/lazyframe/mod.rs:496:13
  57:     0x71d26987d29c - pyo3::marker::Python::allow_threads::h5fb5d629cc045a01
                               at /home/user/.cargo/registry/src/index.crates.io-6f17d22bba15001f/pyo3-0.20.3/src/marker.rs:544:9
  58:     0x71d269dd5195 - polars::lazyframe::PyLazyFrame::collect::h2d1d17fb75cfdaf6
                               at /python/externals/polars/py-polars/src/lazyframe/mod.rs:494:18
  59:     0x71d269de6e87 - polars::lazyframe::_::<impl polars::lazyframe::PyLazyFrame>::__pymethod_collect__::h12b8a2a63f258823
                               at /python/externals/polars/py-polars/src/lazyframe/mod.rs:44:1
  60:     0x71d2692a6257 - pyo3::impl_::trampoline::noargs::{{closure}}::h53b4379f0768fc4b
                               at /home/user/.cargo/registry/src/index.crates.io-6f17d22bba15001f/pyo3-0.20.3/src/impl_/trampoline.rs:31:21
  61:     0x71d2692a613b - pyo3::impl_::trampoline::trampoline::{{closure}}::hfaa9f78b704c79f1
                               at /home/user/.cargo/registry/src/index.crates.io-6f17d22bba15001f/pyo3-0.20.3/src/impl_/trampoline.rs:181:54
  62:     0x71d2689245ad - std::panicking::try::do_call::ha50ea5e1d3a73c89
                               at /rustc/397937d812852f9bbeb671005cb399dbcb357cde/library/std/src/panicking.rs:555:40
  63:     0x71d26893c76b - __rust_try
  64:     0x71d268907c63 - std::panicking::try::h9f91b0a71023343e
                               at /rustc/397937d812852f9bbeb671005cb399dbcb357cde/library/std/src/panicking.rs:519:19
  65:     0x71d2688bf3ea - std::panic::catch_unwind::h78d74b288316e495
                               at /rustc/397937d812852f9bbeb671005cb399dbcb357cde/library/std/src/panic.rs:142:14
  66:     0x71d2692a5d44 - pyo3::impl_::trampoline::trampoline::hb3b0dadd5a8a547f
                               at /home/user/.cargo/registry/src/index.crates.io-6f17d22bba15001f/pyo3-0.20.3/src/impl_/trampoline.rs:181:9
  67:     0x71d269a763a1 - pyo3::impl_::trampoline::noargs::h04c9855fbaeb443a
                               at /home/user/.cargo/registry/src/index.crates.io-6f17d22bba15001f/pyo3-0.20.3/src/impl_/trampoline.rs:31:5
  68:     0x71d269df819a - polars::lazyframe::_::_::__INVENTORY::trampoline::he8ef27be959925ae
                               at /python/externals/polars/py-polars/src/lazyframe/mod.rs:44:1
  69:     0x559319df723f - method_vectorcall_NOARGS
                               at /usr/local/src/conda/python-3.12.2/Objects/descrobject.c:454:24
  70:     0x559319de0dff - _PyObject_VectorcallTstate
                               at /usr/local/src/conda/python-3.12.2/Include/internal/pycore_call.h:92:11
  71:     0x559319de0dff - PyObject_Vectorcall
                               at /usr/local/src/conda/python-3.12.2/Objects/call.c:325:12
  72:     0x559319ccda7e - _PyEval_EvalFrameDefault
                               at /home/conda/feedstock_root/build_artifacts/python-split_1708115583107/work/build-static/Python/bytecodes.c:2706:19
  73:     0x559319e94cae - PyEval_EvalCode
                               at /usr/local/src/conda/python-3.12.2/Python/ceval.c:578:21
  74:     0x559319eaf43d - builtin_exec_impl
                               at /usr/local/src/conda/python-3.12.2/Python/bltinmodule.c:1096
  75:     0x559319eaf43d - builtin_exec
                               at /usr/local/src/conda/python-3.12.2/Python/clinic/bltinmodule.c.h:586
  76:     0x559319cd133e - _PyEval_EvalFrameDefault
                               at /home/conda/feedstock_root/build_artifacts/python-split_1708115583107/work/build-static/Python/bytecodes.c:2966:19
  77:     0x559319eaa002 - _PyEval_EvalFrame
                               at /usr/local/src/conda/python-3.12.2/Include/internal/pycore_ceval.h:89:16
  78:     0x559319eaa002 - gen_send_ex2
                               at /usr/local/src/conda/python-3.12.2/Objects/genobject.c:230:14
  79:     0x559319eab267 - gen_send_ex
                               at /usr/local/src/conda/python-3.12.2/Objects/genobject.c:274:9
  80:     0x559319cd1bcd - _PyEval_EvalFrameDefault
                               at /home/conda/feedstock_root/build_artifacts/python-split_1708115583107/work/build-static/Python/bytecodes.c:3085:19
  81:     0x559319e1e03c - _PyEval_EvalFrame
                               at /usr/local/src/conda/python-3.12.2/Include/internal/pycore_ceval.h:89:16
  82:     0x559319e1e03c - _PyEval_Vector
                               at /usr/local/src/conda/python-3.12.2/Python/ceval.c:1683:12
  83:     0x559319e1e03c - _PyFunction_Vectorcall
                               at /usr/local/src/conda/python-3.12.2/Objects/call.c:419:16
  84:     0x559319e1e03c - _PyObject_VectorcallTstate
                               at /usr/local/src/conda/python-3.12.2/Include/internal/pycore_call.h:92:11
  85:     0x559319e1dbad - method_vectorcall
                               at /usr/local/src/conda/python-3.12.2/Objects/classobject.c:61:18
  86:     0x559319dff513 - _PyVectorcall_Call
                               at /usr/local/src/conda/python-3.12.2/Objects/call.c:283:24
  87:     0x559319dff513 - _PyObject_Call
                               at /usr/local/src/conda/python-3.12.2/Objects/call.c:354:16
  88:     0x559319ccc688 - PyCFunction_Call
                               at /usr/local/src/conda/python-3.12.2/Objects/call.c:387:12
  89:     0x559319ccc688 - _PyEval_EvalFrameDefault
                               at /home/conda/feedstock_root/build_artifacts/python-split_1708115583107/work/build-static/Python/bytecodes.c:3254:26
  90:     0x559319e94cae - PyEval_EvalCode
                               at /usr/local/src/conda/python-3.12.2/Python/ceval.c:578:21
  91:     0x559319eb845a - run_eval_code_obj
                               at /usr/local/src/conda/python-3.12.2/Python/pythonrun.c:1722
  92:     0x559319eb3acb - run_mod
                               at /usr/local/src/conda/python-3.12.2/Python/pythonrun.c:1743
  93:     0x559319eca230 - pyrun_file
                               at /usr/local/src/conda/python-3.12.2/Python/pythonrun.c:1643
  94:     0x559319ec9e0e - _PyRun_SimpleFileObject
                               at /usr/local/src/conda/python-3.12.2/Python/pythonrun.c:433
  95:     0x559319ec9684 - _PyRun_AnyFileObject
                               at /usr/local/src/conda/python-3.12.2/Python/pythonrun.c:78
  96:     0x559319ec36b2 - pymain_run_file_obj
                               at /usr/local/src/conda/python-3.12.2/Modules/main.c:360
  97:     0x559319ec36b2 - pymain_run_file
                               at /usr/local/src/conda/python-3.12.2/Modules/main.c:379
  98:     0x559319ec36b2 - pymain_run_python
                               at /usr/local/src/conda/python-3.12.2/Modules/main.c:629
  99:     0x559319ec36b2 - Py_RunMain
                               at /usr/local/src/conda/python-3.12.2/Modules/main.c:709
 100:     0x559319e7f217 - Py_BytesMain
                               at /usr/local/src/conda/python-3.12.2/Modules/main.c:763:12
 101:     0x71d4ae735cd0 - <unknown>
 102:     0x71d4ae735d8a - __libc_start_main
 103:     0x559319e7f095 - <unknown>
thread caused non-unwinding panic. aborting.
zsh: IOT instruction (core dumped)  ipython
```

### Issue description

This is similar to https://github.com/pola-rs/polars/issues/13972 where figuring out the exact replication steps is difficult.

The same string data, if converted back to python or even calling `chunky.combine_chunks()` doesn't trigger the same issues.

The `iq_id` column is basically option ids.

```
print(good_s)
shape: (209_613,)
Series: '' [str]
[
        "@ESH24C290000"
        "@ESH24C290000"
        "@ESH24C290000"
        "@ESH24C290000"
        "@ESH24C290000"
        …
        "@ESH24C535500"
        "@ESH24C535500"
        "@ESH24C535500"
        "@ESH24C535500"
        "@ESH24C536500"
]
```

But again, the same strings work when doing things like combine_chunks or convert to python/pandas then back.

### Expected behavior

No errors.

### Installed versions

<details>

```
--------Version info---------
Polars:               0.20.14
Index type:           UInt32
Platform:             Linux-6.7.8-arch1-1-x86_64-with-glibc2.39
Python:               3.12.2 | packaged by conda-forge | (main, Feb 16 2024, 20:50:58) [GCC 12.3.0]

----Optional dependencies----
adbc_driver_manager:  <not installed>
cloudpickle:          3.0.0
connectorx:           <not installed>
deltalake:            <not installed>
fastexcel:            <not installed>
fsspec:               2024.2.0
gevent:               <not installed>
hvplot:               <not installed>
matplotlib:           3.8.3
numpy:                1.26.4
openpyxl:             3.1.2
pandas:               3.0.0.dev0+432.g5bcc7b7077
pyarrow:              16.0.0.dev248+g120a1dbec
pydantic:             1.10.13
pyiceberg:            <not installed>
pyxlsb:               <not installed>
sqlalchemy:           <not installed>
xlsx2csv:             <not installed>
xlsxwriter:           <not installed>
```

</details>

**Comment by ritchie46** [comment]
Can you provide a minimal repro?

**Comment by ritchie46** [comment]
I cannot reproduce, can you come up with an MRE?
