### ISSUE TITLE
Leading whitespace for a string value in qoutes is causing a error when the string value contains a "," which is also the delimiter

### ISSUE THREAD

**Issue by philter87** [pola-rs/polars#15011]
### Checks

- [X] I have checked that this issue has not already been reported.
- [X] I have confirmed this bug exists on the [latest version](https://pypi.org/project/polars/) of Polars.

### Reproducible example

A CSV with leading space before a string value in quotes is causing an issue. See CSV below:

```python
csv_content = """
"Index", "Item", "Cost", "Tax", "Total"
 6, "Banana Boat Sunscreen, 8 oz",     6.68, 0.50,  7.18
 7, "Wrench Set, 18 pieces",          10.00, 0.75, 10.75
 8, "M and M, 42 oz",                  8.98, 0.67,  9.65
 9, "Bertoli Alfredo Sauce",           2.12, 0.16,  2.28
10, "Large Paperclips, 10 boxes",      6.19, 0.46,  6.65
"""

with open('temp.csv', 'w') as csv_file:
    csv_file.write(csv_content)

# Error when reading csv
df = polars.read_csv("temp.csv")

print(df)
```

The value ` "Banana Boat Sunscreen, 8 oz"` is converted to two values ` "Banana Boat Sunscreen` and ` 8 oz"` and hence we get an error: `polars.exceptions.ComputeError: found more fields than defined in 'Schema'`. 

The two values should have been one value: `Banana Boat Sunscreen, 8 oz`. 

If I remove the leading whitespace its works.

### Log output

```shell
Error
Traceback (most recent call last):
  File "C:\mjolner-code\seedcase-sprout\sprout\tests\tests_csv_reader.py", line 113, in test_csv_with_quotes_and_aligned
    df = polars.read_csv("temp.csv", )
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\pch\AppData\Local\pypoetry\Cache\virtualenvs\seedcase-sprout-yovK5VTW-py3.11\Lib\site-packages\polars\_utils\deprecation.py", line 134, in wrapper
    return function(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\pch\AppData\Local\pypoetry\Cache\virtualenvs\seedcase-sprout-yovK5VTW-py3.11\Lib\site-packages\polars\_utils\deprecation.py", line 134, in wrapper
    return function(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\pch\AppData\Local\pypoetry\Cache\virtualenvs\seedcase-sprout-yovK5VTW-py3.11\Lib\site-packages\polars\_utils\deprecation.py", line 134, in wrapper
    return function(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\pch\AppData\Local\pypoetry\Cache\virtualenvs\seedcase-sprout-yovK5VTW-py3.11\Lib\site-packages\polars\io\csv\functions.py", line 397, in read_csv
    df = pl.DataFrame._read_csv(
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\pch\AppData\Local\pypoetry\Cache\virtualenvs\seedcase-sprout-yovK5VTW-py3.11\Lib\site-packages\polars\dataframe\frame.py", line 749, in _read_csv
    self._df = PyDataFrame.read_csv(
               ^^^^^^^^^^^^^^^^^^^^^
polars.exceptions.ComputeError: found more fields than defined in 'Schema'

Consider setting 'truncate_ragged_lines=True'.
```

### Issue description

Leading whitespace seems to cause an error.

It seems similar to #14530, but here it causes an error

### Expected behavior

The value ` "Banana Boat Sunscreen, 8 oz"` is converted to two values ` "Banana Boat Sunscreen` and ` 8 oz"`. It should have been one value `Banana Boat Sunscreen, 8 oz`.

### Installed versions

<details>

```
--------Version info---------
Polars:               0.20.15
Index type:           UInt32
Platform:             Windows-10-10.0.19045-SP0
Python:               3.11.7 (tags/v3.11.7:fa7a6f2, Dec  4 2023, 19:24:49) [MSC v.1937 64 bit (AMD64)]
----Optional dependencies----
adbc_driver_manager:  0.10.0
cloudpickle:          <not installed>
connectorx:           <not installed>
deltalake:            <not installed>
fastexcel:            <not installed>
fsspec:               <not installed>
gevent:               <not installed>
hvplot:               <not installed>
matplotlib:           <not installed>
numpy:                1.26.4
openpyxl:             <not installed>
pandas:               <not installed>
pyarrow:              15.0.0
pydantic:             <not installed>
pyiceberg:            <not installed>
pyxlsb:               <not installed>
sqlalchemy:           <not installed>
xlsx2csv:             <not installed>
xlsxwriter:           <not installed>
```

</details>

**Comment by JulianCologne** [comment]
honestly hard to tell what should / should not happen for your example.
CSV files need some kind of rules / specifications if you parse them.
You cannot just try to read anything as a csv.

One can argue that your format in invalid according to the specs: https://www.rfc-editor.org/rfc/rfc4180
ALL whitespace in a csv belongs to the value.
And "Each field may or may not be enclosed in double quotes"
This is NOT the case for your example data. The filed is **not** completely enclosed in quotes because you have a leading whitespace which is not allowed.

imo this is a case where the data is incorrectly formatted and therefore cannot be parsed.
Reading csv files is already very complicated and there is no end to adding special cases once you start.

If anyone wants to implement this I have no objection but personally I think this is the intended behaviour for an ill formatted csv file, sorry 😞 😆

**Comment by cmdlineluser** [comment]
Just trying some different tools, DuckDB seems to be the only one that "works" for this example.

```python
>>> pd.read_csv("temp.csv")
                       Index           "Item"   "Cost"   "Tax"   "Total"
6     "Banana Boat Sunscreen            8 oz"     6.68    0.50      7.18
7                "Wrench Set       18 pieces"    10.00    0.75     10.75
8                   "M and M           42 oz"     8.98    0.67      9.65
9    "Bertoli Alfredo Sauce"             2.12     0.16    2.28       NaN
10         "Large Paperclips        10 boxes"     6.19    0.46      6.65
```

```python
>>> duckdb.sql("from 'temp.csv'")
┌───────┬─────────────────────────────┬────────┬────────┬────────┐
│ Index │            Item             │  Cost  │  Tax   │ Total  │
│ int64 │           varchar           │ double │ double │ double │
├───────┼─────────────────────────────┼────────┼────────┼────────┤
│     6 │ Banana Boat Sunscreen, 8 oz │   6.68 │    0.5 │   7.18 │
│     7 │ Wrench Set, 18 pieces       │   10.0 │   0.75 │  10.75 │
│     8 │ M and M, 42 oz              │   8.98 │   0.67 │   9.65 │
│     9 │ Bertoli Alfredo Sauce       │   2.12 │   0.16 │   2.28 │
│    10 │ Large Paperclips, 10 boxes  │   6.19 │   0.46 │   6.65 │
└───────┴─────────────────────────────┴────────┴────────┴────────┘
```
```python
>>> pyarrow.csv.read_csv("temp.csv")
ArrowInvalid: CSV parse error: Expected 5 columns, got 6:  6, "Banana Boat Sunscreen, 8 oz",     6.68, 0.50,  7.18
```

**Comment by philter87** [comment]
Thanks for the quick response. Maybe I will give it a try tomorrow, otherwise, I will just "sanitize" the file before loading it into polars

**Comment by alexander-beedie** [comment]
Yup, this is definitely out of spec for a valid CSV (it looks like a sort of hybrid between fixed-width and CSV? 🤔). I'd suggest preprocessing it (or generating valid CSV data to start with, if that's in your control?)
