### ISSUE TITLE
polars_bail macro produces meaningless for unsupported `rolling_min` invocation

### ISSUE THREAD

**Issue by MarcoGorelli** [pola-rs/polars#15087]
### Checks

- [X] I have checked that this issue has not already been reported.
- [X] I have confirmed this bug exists on the [latest version](https://pypi.org/project/polars/) of Polars.

### Reproducible example

```python
df = pl.DataFrame({'a': [1,2,3], 'b': [4,5,6]}).sort('a')

df.select(pl.col('b').rolling_min(2, by='a'))
```

### Log output

```shell
Traceback (most recent call last):
  File "/home/marcogorelli/scratch/t.py", line 6, in <module>
    df.select(pl.col('b').rolling_min(2, by='a'))
  File "/home/marcogorelli/scratch/.venv/lib/python3.11/site-packages/polars/dataframe/frame.py", line 8116, in select
    return self.lazy().select(*exprs, **named_exprs).collect(_eager=True)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/marcogorelli/scratch/.venv/lib/python3.11/site-packages/polars/lazyframe/frame.py", line 1934, in collect
    return wrap_df(ldf.collect())
                   ^^^^^^^^^^^^^
polars.exceptions.InvalidOperationError: `expr_name` operation not supported for dtype `i64` (expected: date/datetime)
```

### Issue description

`expr_name` is being printed instead of `rolling_min`

### Expected behavior

```
polars.exceptions.InvalidOperationError: `rolling_min` operation not supported for dtype `i64` (expected: date/datetime)
```

### Installed versions

<details>

```
--------Version info---------
Polars:               0.20.15
Index type:           UInt32
Platform:             Linux-5.15.146.1-microsoft-standard-WSL2-x86_64-with-glibc2.35
Python:               3.11.7 (main, Dec  8 2023, 18:56:58) [GCC 11.4.0]

----Optional dependencies----
adbc_driver_manager:  <not installed>
cloudpickle:          <not installed>
connectorx:           <not installed>
deltalake:            <not installed>
fastexcel:            <not installed>
fsspec:               <not installed>
gevent:               <not installed>
hvplot:               0.9.2
matplotlib:           3.8.3
numpy:                1.26.4
openpyxl:             <not installed>
pandas:               2.2.1
pyarrow:              15.0.1
pydantic:             2.6.1
pyiceberg:            <not installed>
pyxlsb:               <not installed>
sqlalchemy:           <not installed>
xlsx2csv:             <not installed>
xlsxwriter:           <not installed>
```

</details>

**Comment by MarcoGorelli** [comment]
The error comes from:

https://github.com/pola-rs/polars/blob/00e84fcd8d80bc11a36157ea4ba789937ad26351/crates/polars-plan/src/dsl/function_expr/rolling.rs#L88
