### ISSUE TITLE
`attempt to add with overflow` in CsvReader when file length is > 2^16

### ISSUE THREAD

**Issue by Adamkadaban** [pola-rs/polars#15101]
### Checks

- [X] I have checked that this issue has not already been reported.
- [X] I have confirmed this bug exists on the [latest version](https://crates.io/crates/polars) of Polars.

### Reproducible example

```rust
use polars::prelude::*;
use std::env;

fn parse_file(filepath: &String) {
    // let captures = col("column_1");
    let mut df = CsvReader::from_path(filepath).expect("Filepath not found")
        .with_separator('\r' as u8)
        .has_header(false)
        .with_columns(  // takes in Option<Vec<String>>
            // captures.extract_groups(r"\[(.*)\] (.*): (.*)")
            // Some(vec!["Date".to_string(), "Name".to_string(), "Message".to_string()])
            Some(vec!["column_1".into()])
        )
        .truncate_ragged_lines(true)
        .finish().unwrap();
    
    println!("{}", df);
}

fn main(){
    let args: Vec<String> = env::args().collect();
    let filename = &args[1]; // filename
    parse_file(filename);
}
```

### Log output

```shell
thread 'main' panicked at /home/adam/.cargo/registry/src/index.crates.io-6f17d22bba15001f/polars-io-0.38.2/src/csv/parser.rs:155:9:
attempt to add with overflow
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```
`POLAR=VERBOSE=1` didn't show any output.

Here's the stacktrace though
```
thread 'main' panicked at /home/adam/.cargo/registry/src/index.crates.io-6f17d22bba15001f/polars-io-0.38.2/src/csv/parser.rs:155:9:
attempt to add with overflow
stack backtrace:
   0: rust_begin_unwind
             at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/std/src/panicking.rs:645:5
   1: core::panicking::panic_fmt
             at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/core/src/panicking.rs:72:14
   2: core::panicking::panic
             at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/core/src/panicking.rs:144:5
   3: polars_io::csv::parser::next_line_position
             at /home/adam/.cargo/registry/src/index.crates.io-6f17d22bba15001f/polars-io-0.38.2/src/csv/parser.rs:155:9
   4: polars_io::csv::parser::get_line_stats
             at /home/adam/.cargo/registry/src/index.crates.io-6f17d22bba15001f/polars-io-0.38.2/src/csv/parser.rs:266:19
   5: polars_io::csv::read_impl::CoreReader::estimate_rows_and_set_upper_bound
             at /home/adam/.cargo/registry/src/index.crates.io-6f17d22bba15001f/polars-io-0.38.2/src/csv/read_impl/mod.rs:344:36
   6: polars_io::csv::read_impl::CoreReader::determine_file_chunks_and_statistics
             at /home/adam/.cargo/registry/src/index.crates.io-6f17d22bba15001f/polars-io-0.38.2/src/csv/read_impl/mod.rs:410:13
   7: polars_io::csv::read_impl::CoreReader::parse_csv
             at /home/adam/.cargo/registry/src/index.crates.io-6f17d22bba15001f/polars-io-0.38.2/src/csv/read_impl/mod.rs:473:13
   8: polars_io::csv::read_impl::CoreReader::as_df
             at /home/adam/.cargo/registry/src/index.crates.io-6f17d22bba15001f/polars-io-0.38.2/src/csv/read_impl/mod.rs:668:22
   9: <polars_io::csv::read::CsvReader<R> as polars_io::SerReader<R>>::finish
             at /home/adam/.cargo/registry/src/index.crates.io-6f17d22bba15001f/polars-io-0.38.2/src/csv/read.rs:646:13
  10: analyzer_v2::parse_file
             at /home/adam/Desktop/analyzerv2/src/main.rs:88:18
  11: analyzer_v2::main
             at /home/adam/Desktop/analyzerv2/src/main.rs:107:5
  12: core::ops::function::FnOnce::call_once
             at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/core/src/ops/function.rs:250:5
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```

### Issue description

I've created a python script to generate the file:

```python
with open('generated.txt', 'w') as fout:
	for i in range(2**16):
		fout.write('[1/1/20, 1:1:1 AM] A: sample text\r\n')
```

It seems that when the seperator is `\r` here, it breaks (but only when the number of lines is 2^16)

### Expected behavior

Program should output df correctly regardless of the number of lines. 

### Installed versions

<details>
cargo 1.76.0 (c84b36747 2024-01-18)

polars = { version = "=0.38.2", features = ["default", "lazy"]}
</details>

**Comment by Adamkadaban** [comment]
May be related to https://github.com/pola-rs/polars/pull/391

Have not tested

**Comment by Adamkadaban** [comment]
https://github.com/pola-rs/polars/pull/15109 fixed everything

Thanks!
