### ISSUE TITLE
segfault/out of bounds when reading binary series through streaming plan

### ISSUE THREAD

**Issue by j-baker** [pola-rs/polars#15112]
### Checks

- [X] I have checked that this issue has not already been reported.
- [X] I have confirmed this bug exists on the [latest version](https://crates.io/crates/polars) of Polars.

### Reproducible example

I do not know how to reproduce this more minimally at present. However, my query is:

- reading a Parquet dataset stored in a cloud blob store.
- doing some joins
- eventually running a udf on the results.

The column in question contains around 250 jpegs, which are each around 0.6-1.0MB in size each, and is a binary column. I've validated that I'm only querying for data that's in range.

The bug can only be reproduced when streaming is on. It happens on a call to `Series.binary().get(idx)`.

Sometimes it doesn't occur in `--release` mode, especially with `performant` enabled. However, this probably just means there's corruption at play!

### Log output

```shell
UserWarning: Cannot combine 'streaming' with 'comm_subplan_elim'. CSE will be turned off.
POLARS PREFETCH_SIZE: 20
POLARS PREFETCH_SIZE: 20
POLARS PREFETCH_SIZE: 20
POLARS PREFETCH_SIZE: 20
run UdfExec
run StackExec with 5 CSE
run ProjectionExec
run UdfExec
RUN STREAMING PIPELINE
parquet -> hstack -> generic_join_build
RefCell { value: [parquet -> hstack -> generic_join_build, parquet -> hstack -> generic_join_build, parquet -> hstack -> callback -> fast_projection -> callback -> fast_projection -> callback -> fast_projection -> ordered_sink] }
STREAMING CHUNK SIZE: 25000 rows
POLARS ROW_GROUP PREFETCH_SIZE: 128
STREAMING CHUNK SIZE: 2000 rows
POLARS ROW_GROUP PREFETCH_SIZE: 128
concurrency tuner finished after adding 1 steps
STREAMING CHUNK SIZE: 1923 rows
POLARS ROW_GROUP PREFETCH_SIZE: 128
STREAMING CHUNK SIZE: 10000 rows
POLARS ROW_GROUP PREFETCH_SIZE: 128
thread '<unnamed>' panicked at /Users/james/.cargo/registry/src/index.crates.io-6f17d22bba15001f/polars-utils-0.38.2/src/slice.rs:92:18:
range end index 786112 out of range for slice of length 785636
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
thread '<unnamed>' panicked at /Users/james/.cargo/registry/src/index.crates.io-6f17d22bba15001f/polars-utils-0.38.2/src/slice.rs:92:18:
range end index 786112 out of range for slice of length 785636
thread '<unnamed>' panicked at /Users/james/.cargo/registry/src/index.crates.io-6f17d22bba15001f/polars-utils-0.38.2/src/slice.rs:92:18:
range end index 786112 out of range for slice of length 785636
Error: task 40 panicked
```

A sample backtrace is:

```
range end index 786112 out of range for slice of length 785636
stack backtrace:
   0: rust_begin_unwind
             at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/std/src/panicking.rs:645:5
   1: core::panicking::panic_fmt
             at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/core/src/panicking.rs:72:14
   2: core::slice::index::slice_end_index_len_fail_rt
             at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/core/src/slice/index.rs:76:5
   3: core::slice::index::slice_end_index_len_fail
             at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/core/src/slice/index.rs:68:9
   4: <core::ops::range::Range<usize> as core::slice::index::SliceIndex<[T]>>::index
             at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/core/src/slice/index.rs:394:13
   5: core::slice::index::<impl core::ops::index::Index<I> for [T]>::index
             at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/core/src/slice/index.rs:18:9
   6: <[T] as polars_utils::slice::GetSaferUnchecked<T>>::get_unchecked_release
             at /Users/james/.cargo/registry/src/index.crates.io-6f17d22bba15001f/polars-utils-0.38.2/src/slice.rs:92:18
   7: polars_arrow::array::binview::BinaryViewArrayGeneric<T>::value_unchecked
             at /Users/james/.cargo/registry/src/index.crates.io-6f17d22bba15001f/polars-arrow-0.38.2/src/array/binview/mod.rs:299:13
   8: <polars_arrow::array::binview::BinaryViewArrayGeneric<[u8]> as polars_arrow::array::static_array::StaticArray>::value_unchecked
             at /Users/james/.cargo/registry/src/index.crates.io-6f17d22bba15001f/polars-arrow-0.38.2/src/array/static_array.rs:250:9
   9: polars_arrow::array::static_array::StaticArray::get_unchecked
             at /Users/james/.cargo/registry/src/index.crates.io-6f17d22bba15001f/polars-arrow-0.38.2/src/array/static_array.rs:48:18
  10: polars_core::chunked_array::ChunkedArray<T>::get
             at /Users/james/.cargo/registry/src/index.crates.io-6f17d22bba15001f/polars-core-0.38.2/src/chunked_array/mod.rs:399:18
  11: <polars_core::series::Series as MY_CODE::MY_TRAIT>::get_bytes
             at ./vta-eval/src/dataset.rs:680:27
  12: <MY_CODE::MY_NAME as polars_plan::dsl::expr_dyn_fn::SeriesUdf>::call_udf
             at ./MY_PATH/src/dataset.rs:699:54
  13: polars_lazy::physical_plan::expressions::apply::ApplyExpr::eval_and_flatten
             at /Users/james/.cargo/registry/src/index.crates.io-6f17d22bba15001f/polars-lazy-0.38.2/src/physical_plan/expressions/apply.rs:120:28
  14: <polars_lazy::physical_plan::expressions::apply::ApplyExpr as polars_lazy::physical_plan::expressions::PhysicalExpr>::evaluate
             at /Users/james/.cargo/registry/src/index.crates.io-6f17d22bba15001f/polars-lazy-0.38.2/src/physical_plan/expressions/apply.rs:313:16
  15: <polars_lazy::physical_plan::expressions::alias::AliasExpr as polars_lazy::physical_plan::expressions::PhysicalExpr>::evaluate
             at /Users/james/.cargo/registry/src/index.crates.io-6f17d22bba15001f/polars-lazy-0.38.2/src/physical_plan/expressions/alias.rs:32:22
  16: polars_lazy::physical_plan::executors::projection_utils::run_exprs_par::{{closure}}::{{closure}}
             at /Users/james/.cargo/registry/src/index.crates.io-6f17d22bba15001f/polars-lazy-0.38.2/src/physical_plan/executors/projection_utils.rs:202:25
```
```


### Issue description

- segfaults if run in release mode
- panics if run in debug mode
- as expected from out-of-bounds

### Expected behavior

Does not panic.

### Installed versions

<details>
"lazy", "ipc", "dtype-struct", "abs", "async", "aws", "polars-io", "parquet", "streaming", "performant"
</details>

**Comment by j-baker** [comment]
I can also confirm that this issue is hit independently of whether we are reading from a cloud datasource source.

**Comment by ritchie46** [comment]
Thanks for the report. Can you come up with MRE? I would like to fix it. I made #1520 to be entirely sure we panic if we hit this.

This code isn't hit much in the python front-end as we do the bounds checks on another level.
