### ISSUE TITLE
.collect() gives different results based on if streaming is/isn't used

### ISSUE THREAD

**Issue by concur1** [pola-rs/polars#15110]
### Checks

- [X] I have checked that this issue has not already been reported.
- [X] I have confirmed this bug exists on the [latest version](https://pypi.org/project/polars/) of Polars.

### Reproducible example

```python
import polars as pl
from pl_compare import compare

netflix_original = pl.read_csv("https://github.com/concur1/pl_compare/raw/main/example_data/netflix_titles.csv").lazy()
netflix_updated = pl.read_csv("https://github.com/concur1/pl_compare/raw/main/example_data/netflix_titles-corrupted.csv").lazy()

def default_equality_check(col: str) -> pl.Expr:
    return (
        (pl.col(f"{col}") != pl.col(f"{col}_right"))
        | (pl.col(f"{col}").is_null() & ~pl.col(f"{col}_right").is_null())
        | (~pl.col(f"{col}").is_null() & pl.col(f"{col}_right").is_null())
    )

compare_cols = [col for col in netflix_updated.columns 
             if col not in ['show_id', 'rating', 'duration', 'listed_in', 'cast', 'country']]

diff_summary = (
    netflix_original.join(netflix_updated, on=['show_id'], how='inner')
    .with_columns(default_equality_check(col).alias(col+'_diff') for col in compare_cols)
    .group_by([col+'_diff' for col in compare_cols])
    .agg(pl.len())
    
)
 
print(diff_summary.collect(),
      diff_summary.collect(streaming=True))

assert diff_summary.collect()==diff_summary.collect(streaming=True), "These dataframes should be exactly equal. One uses streaming and one does not."

print("If the above assertion no longer raises an error then I guess this bug is fixed =)")
```

### Log output

```shell
>>> print(diff_summary.collect(),
...       diff_summary.collect(streaming=True))
keys/aggregates are not partitionable: running default HASH AGGREGATION
join parallel: true
INNER join dataframes finished
RUN STREAMING PIPELINE
[df -> callback -> fast_projection -> hstack -> generic-group_by -> ordered_sink, df -> generic_join_build]
finish streaming aggregation with local in-memory table
shape: (1, 7)
┌───────────┬────────────┬───────────────┬─────────────────┬───────────────────┬──────────────────┬──────┐
│ type_diff ┆ title_diff ┆ director_diff ┆ date_added_diff ┆ release_year_diff ┆ description_diff ┆ len  │
│ ---       ┆ ---        ┆ ---           ┆ ---             ┆ ---               ┆ ---              ┆ ---  │
│ bool      ┆ bool       ┆ bool          ┆ bool            ┆ bool              ┆ bool             ┆ u32  │
╞═══════════╪════════════╪═══════════════╪═════════════════╪═══════════════════╪══════════════════╪══════╡
│ false     ┆ false      ┆ true          ┆ false           ┆ false             ┆ false            ┆ 6173 │
└───────────┴────────────┴───────────────┴─────────────────┴───────────────────┴──────────────────┴──────┘ shape: (8, 7)
┌───────────┬────────────┬───────────────┬─────────────────┬───────────────────┬──────────────────┬──────┐
│ type_diff ┆ title_diff ┆ director_diff ┆ date_added_diff ┆ release_year_diff ┆ description_diff ┆ len  │
│ ---       ┆ ---        ┆ ---           ┆ ---             ┆ ---               ┆ ---              ┆ ---  │
│ bool      ┆ bool       ┆ bool          ┆ bool            ┆ bool              ┆ bool             ┆ u32  │
╞═══════════╪════════════╪═══════════════╪═════════════════╪═══════════════════╪══════════════════╪══════╡
│ false     ┆ false      ┆ true          ┆ true            ┆ false             ┆ true             ┆ 1317 │
│ false     ┆ true       ┆ true          ┆ false           ┆ false             ┆ true             ┆ 291  │
│ false     ┆ true       ┆ true          ┆ true            ┆ false             ┆ true             ┆ 2087 │
│ false     ┆ false      ┆ true          ┆ false           ┆ false             ┆ true             ┆ 931  │
│ false     ┆ true       ┆ true          ┆ true            ┆ false             ┆ false            ┆ 427  │
│ false     ┆ true       ┆ true          ┆ false           ┆ false             ┆ false            ┆ 60   │
│ false     ┆ false      ┆ true          ┆ false           ┆ false             ┆ false            ┆ 811  │
│ false     ┆ false      ┆ true          ┆ true            ┆ false             ┆ false            ┆ 249  │
└───────────┴────────────┴───────────────┴─────────────────┴───────────────────┴──────────────────┴──────┘
>>>
>>> assert diff_summary.collect()==diff_summary.collect(streaming=True), "These dataframes should be exactly equal. One uses streaming and one does not."
keys/aggregates are not partitionable: running default HASH AGGREGATION
join parallel: true
INNER join dataframes finished
RUN STREAMING PIPELINE
[df -> callback -> fast_projection -> hstack -> generic-group_by -> ordered_sink, df -> generic_join_build]
finish streaming aggregation with local in-memory table
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/o/.cache/pypoetry/virtualenvs/pl-compare-WzCieGQ9-py3.8/lib/python3.8/site-packages/polars/dataframe/frame.py", line 1464, in __eq__
    return self._comp(other, "eq")
  File "/home/o/.cache/pypoetry/virtualenvs/pl-compare-WzCieGQ9-py3.8/lib/python3.8/site-packages/polars/dataframe/frame.py", line 1353, in _comp
    return self._compare_to_other_df(other, op)
  File "/home/o/.cache/pypoetry/virtualenvs/pl-compare-WzCieGQ9-py3.8/lib/python3.8/site-packages/polars/dataframe/frame.py", line 1368, in _compare_to_other_df
    raise ValueError(msg)
ValueError: DataFrame dimensions do not match
>>>
>>> print("If the above assertion no longer raises an error then I guess this bug is fixed =)")
If the above assertion no longer raises an error then I guess this bug is fixed =)
>>>
```

### Issue description

Using polars 0.20.25 I am getting different results depending on if I do/don't use streaming=True in a collect().

I noticed the issue when upgrading to 0.20.15. I was previously using polars 0.19.19 which did not have this issue.

I have seen this occurring when:
- I join two lazyframes
- calculate new columns using values from the original table
- group the results (although I think the problem might be happening before the grouping)

### Expected behavior

The example code shows that my result_df.collect() != result_df.collect(streaming=True).

I would expect them to have the same behavior regardless of the value of streaming supplied to collect().

### Installed versions

<details>

```
--------Version info---------
Polars:               0.20.15
Index type:           UInt32
Platform:             Linux-6.1.58+-x86_64-with-glibc2.35
Python:               3.10.12 (main, Nov 20 2023, 15:14:05) [GCC 11.4.0]

----Optional dependencies----
adbc_driver_manager:  <not installed>
cloudpickle:          2.2.1
connectorx:           <not installed>
deltalake:            <not installed>
fastexcel:            <not installed>
fsspec:               2023.6.0
gevent:               <not installed>
hvplot:               <not installed>
matplotlib:           3.7.1
numpy:                1.25.2
openpyxl:             3.1.2
pandas:               1.5.3
pyarrow:              14.0.2
pydantic:             2.6.4
pyiceberg:            <not installed>
pyxlsb:               <not installed>
sqlalchemy:           2.0.28
xlsx2csv:             <not installed>
xlsxwriter:           <not installed>

```

</details>

**Comment by ritchie46** [comment]
Thank a lot for the bisect @nameexhaustion :100:

**Comment by ritchie46** [comment]
PS. I hope you use `scan_csv` vs `read_csv().lazy` :see_no_evil:
