### ISSUE TITLE
Can't Series of List with explicit dtype

### ISSUE THREAD

**Issue by josh** [pola-rs/polars#15139]
### Checks

- [X] I have checked that this issue has not already been reported.
- [X] I have confirmed this bug exists on the [latest version](https://pypi.org/project/polars/) of Polars.

### Reproducible example

```python
import polars as pl

s = pl.Series(values=[1, 2, 3])

# okay
pl.Series(values=[s])

# TypeError: the truth value of a Series is ambiguous
pl.Series(values=[s], dtype=pl.List(pl.Int64))
```

### Log output

```shell
Traceback (most recent call last):
  File "/workspaces/example/bug.py", line 9, in <module>
    pl.Series(values=[s], dtype=pl.List(pl.Int64))
  File "/opt/python/3.11.7/lib/python3.11/site-packages/polars/series/series.py", line 311, in __init__
    self._s = sequence_to_pyseries(
              ^^^^^^^^^^^^^^^^^^^^^
  File "/opt/python/3.11.7/lib/python3.11/site-packages/polars/_utils/construction/series.py", line 257, in sequence_to_pyseries
    pyseries_list = [
                    ^
  File "/opt/python/3.11.7/lib/python3.11/site-packages/polars/_utils/construction/series.py", line 260, in <listcomp>
    else sequence_to_pyseries(
         ^^^^^^^^^^^^^^^^^^^^^
  File "/opt/python/3.11.7/lib/python3.11/site-packages/polars/_utils/construction/series.py", line 90, in sequence_to_pyseries
    if not values and dtype is None:
  File "/opt/python/3.11.7/lib/python3.11/site-packages/polars/series/series.py", line 631, in __bool__
    raise TypeError(msg)
TypeError: the truth value of a Series is ambiguous

Hint: use '&' or '|' to chain Series boolean results together, not and/or. To check if a Series contains any values, use `is_empty()`.
```

### Issue description

Regression from 0.25.15 to 0.25.16.

Possibly related #15002.

CC: @petrosbar @stinodego

### Expected behavior

Creation of series works the same with or without explicit dtype.

### Installed versions

<details>

```
--------Version info---------
Polars:               0.20.16
Index type:           UInt32
Platform:             Linux-6.2.0-1019-azure-x86_64-with-glibc2.31
Python:               3.11.7 (main, Jan  8 2024, 20:44:44) [GCC 9.4.0]

----Optional dependencies----
adbc_driver_manager:  <not installed>
cloudpickle:          <not installed>
connectorx:           <not installed>
deltalake:            <not installed>
fastexcel:            <not installed>
fsspec:               2024.3.1
gevent:               <not installed>
hvplot:               <not installed>
matplotlib:           <not installed>
numpy:                1.26.4
openpyxl:             <not installed>
pandas:               <not installed>
pyarrow:              <not installed>
pydantic:             <not installed>
pyiceberg:            <not installed>
pyxlsb:               <not installed>
sqlalchemy:           <not installed>
xlsx2csv:             <not installed>
xlsxwriter:           <not installed>
```

</details>

**Comment by stinodego** [comment]
I broke this in a drive-by refactor in a recent PR. Apologies. Fix will be easy enough fortunately.
