### ISSUE TITLE
PanicException: impl error, should be a list at this point "invalid series dtype: expected `List`, got `str`"

### ISSUE THREAD

**Issue by CaselIT** [pola-rs/polars#15183]
### Checks

- [X] I have checked that this issue has not already been reported.
- [X] I have confirmed this bug exists on the [latest version](https://pypi.org/project/polars/) of Polars.

### Reproducible example

```python
import polars as pl
dfOk = (
    pl.DataFrame({"a": [1, 2, 3, 4, 5, 2, 3, 5, 1], "b": [1, 2, 3, 1, 2, 3, 1, 2, 3]})
    .group_by("a")
    .agg(pl.col.b.sort().str.concat("-").str.split("-"))
)
print(dfOk)
dfBug = (
    pl.DataFrame({"a": [1, 2, 3, 4, 5, 2, 3, 5, 1], "b": [1, 2, 3, 1, 2, 3, 1, 2, 3]})
    .group_by("a")
    .agg(pl.col.b.unique().sort().str.concat("-").str.split("-"))
)
print(dfBug)
```

### Log output

```shell
shape: (5, 2)
┌─────┬────────────┐
│ a   ┆ b          │
│ --- ┆ ---        │
│ i64 ┆ list[str]  │
╞═════╪════════════╡
│ 5   ┆ ["2", "2"] │
│ 4   ┆ ["1"]      │
│ 2   ┆ ["2", "3"] │
│ 1   ┆ ["1", "3"] │
│ 3   ┆ ["1", "3"] │
└─────┴────────────┘
thread 'polars-1' panicked at crates\polars-lazy\src\physical_plan\expressions\mod.rs:278:14:
impl error, should be a list at this point: SchemaMismatch(ErrString("invalid series dtype: expected `List`, got `str`"))
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
Traceback (most recent call last):
  File "\polars_test.py", line 54, in <module>
    .agg(pl.col.b.unique().sort().str.concat("-").str.split("-"))
  File "\lib\site-packages\polars\dataframe\group_by.py", line 247, in agg
    self.df.lazy()
  File "\lib\site-packages\polars\lazyframe\frame.py", line 1943, in collect
    return wrap_df(ldf.collect())
pyo3_runtime.PanicException: impl error, should be a list at this point: SchemaMismatch(ErrString("invalid series dtype: expected `List`, got `str`"))
```

### Issue description

Adding unique to the expression makes polars panic

### Expected behavior

No panic happens

### Installed versions

<details>

```
--------Version info---------
Polars:               0.20.16
Index type:           UInt32
Platform:             Windows-10-10.0.19045-SP0
Python:               3.10.13 | packaged by Anaconda, Inc. | (main, Sep 11 2023, 13:24:38) [MSC v.1916 64 bit (AMD64)]

----Optional dependencies----
adbc_driver_manager:  <not installed>
cloudpickle:          <not installed>
connectorx:           <not installed>
deltalake:            <not installed>
fastexcel:            <not installed>
fsspec:               <not installed>
gevent:               <not installed>
hvplot:               <not installed>
matplotlib:           <not installed>
numpy:                1.26.2
openpyxl:             3.1.2
pandas:               2.1.3
pyarrow:              14.0.1
pydantic:             1.10.13
pyiceberg:            <not installed>
pyxlsb:               <not installed>
sqlalchemy:           2.0.23
xlsx2csv:             <not installed>
xlsxwriter:           <not installed>
```

</details>

**Comment by CaselIT** [comment]
This may be a duplicate of #12841. I did not find it yesterday, sorry

**Comment by CaselIT** [comment]
Thanks for fixing!
