### ISSUE TITLE
Many operators do not work with dtype null

### ISSUE THREAD

**Issue by drhagen** [pola-rs/polars#15257]
### Checks

- [X] I have checked that this issue has not already been reported.
- [X] I have confirmed this bug exists on the [latest version](https://pypi.org/project/polars/) of Polars.

### Reproducible example

```python
import polars as pl
pl.DataFrame({"a": [None, None]}).with_columns(pl.col("a").abs())
```

### Log output

```shell
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/david/tabeline/.venv/lib/python3.11/site-packages/polars/dataframe/frame.py", line 8366, in with_columns
    return self.lazy().with_columns(*exprs, **named_exprs).collect(_eager=True)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/david/tabeline/.venv/lib/python3.11/site-packages/polars/lazyframe/frame.py", line 1943, in collect
    return wrap_df(ldf.collect())
                   ^^^^^^^^^^^^^
polars.exceptions.InvalidOperationError: `abs` operation not supported for dtype `null`
```

### Issue description

The following operations cannot be run columns with dtype null:

- abs
- sin
- cos
- tan
- arcsin
- arccos
- arctan
- floor
- ceil
- is_nan
- is_finite
- std
- var
- max
- min
- sum
- median
- any
- all

All of them except `any` and `all` used to complete without error. Issue #14093 seems to suggests that behavior like this is considered a bug.

### Expected behavior

Return `null` for every operation.

### Installed versions

<details>

```
--------Version info---------
Polars:               0.20.16
Index type:           UInt32
Platform:             Linux-5.15.0-101-generic-x86_64-with-glibc2.31
Python:               3.11.3 | packaged by conda-forge | (main, Apr  6 2023, 08:57:19) [GCC 11.3.0]

----Optional dependencies----
adbc_driver_manager:  <not installed>
cloudpickle:          <not installed>
connectorx:           <not installed>
deltalake:            <not installed>
fastexcel:            <not installed>
fsspec:               <not installed>
gevent:               <not installed>
hvplot:               <not installed>
matplotlib:           <not installed>
numpy:                1.26.4
openpyxl:             <not installed>
pandas:               <not installed>
pyarrow:              <not installed>
pydantic:             <not installed>
pyiceberg:            <not installed>
pyxlsb:               <not installed>
sqlalchemy:           <not installed>
xlsx2csv:             <not installed>
xlsxwriter:           <not installed>
```

</details>

**Comment by Elvynzs** [comment]
I have encountered the same issue in my usage of polars.

This result in some extra code to handle `pl.Null` inputs as an edge case. (In my use case, I do not know in advance the dtype of the input)
