### ISSUE TITLE
`pl.int_range()` panicks when `dtype=pl.String`, and is inconsistent with `pl.int_ranges()`

### ISSUE THREAD

**Issue by etiennebacher** [pola-rs/polars#15307]
### Checks

- [X] I have checked that this issue has not already been reported.
- [X] I have confirmed this bug exists on the [latest version](https://pypi.org/project/polars/) of Polars.

### Reproducible example

```python
>>> import polars as pl
>>> pl.int_range(0, 3, dtype=pl.String, eager=True)

thread '<unnamed>' panicked at py-polars\src\functions\eager.rs:104:15:
not implemented for dtype String
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\etienne\AppData\Roaming\Python\Python311\site-packages\polars\functions\range\int_range.py", line 218, in int_range
    return wrap_s(plr.eager_int_range(start, end, step, dtype))
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
pyo3_runtime.PanicException: not implemented for dtype String

>>> pl.DataFrame({"start": [1, -1], "end": [3, 2]}).with_columns(
    int_ranges=pl.int_ranges("start", "end", dtype=pl.String)
)

shape: (2, 3)
┌───────┬─────┬──────────────────┐
│ start ┆ end ┆ int_ranges       │
│ ---   ┆ --- ┆ ---              │
│ i64   ┆ i64 ┆ list[str]        │
╞═══════╪═════╪══════════════════╡
│ 1     ┆ 3   ┆ ["1", "2"]       │
│ -1    ┆ 2   ┆ ["-1", "0", "1"] │
└───────┴─────┴──────────────────┘
```

### Issue description

`pl.int_range()` panicks with `dtype=pl.String`. 

There's also a consistency issue since `pl.int_ranges()` casts the output to `list[str]`.

### Expected behavior

Not sure if both `pl.int_range()` and `pl.int_ranges()` should error or cast the output to `str` and `list[str]` respectively.

### Installed versions

<details>

```
--------Version info---------
Polars:               0.20.16
Index type:           UInt32 
Platform:             Windows-10-10.0.19044-SP0
Python:               3.11.0 (main, Oct 24 2022, 18:26:48) [MSC v.1933 64 bit (AMD64)]

----Optional dependencies----
adbc_driver_manager:  <not installed>
cloudpickle:          <not installed>
connectorx:           <not installed>
deltalake:            <not installed>
fastexcel:            <not installed>
fsspec:               2023.6.0
gevent:               <not installed>
hvplot:               0.9.2
matplotlib:           3.7.1
numpy:                1.24.3
openpyxl:             <not installed>
pandas:               2.0.3
pyarrow:              12.0.1
pydantic:             2.6.4
pyiceberg:            <not installed>
pyxlsb:               <not installed>
sqlalchemy:           <not installed>
xlsx2csv:             <not installed>
xlsxwriter:           <not installed>
```

</details>

**Comment by stinodego** [comment]
Both should error.
