### ISSUE TITLE
`offset_by` raises ambiguous datetime error for day light time change

### ISSUE THREAD

**Issue by fletawe-haulogy** [pola-rs/polars#15319]
### Checks

- [X] I have checked that this issue has not already been reported.
- [X] I have confirmed this bug exists on the [latest version](https://pypi.org/project/polars/) of Polars.

### Reproducible example

```python
from datetime import datetime, timedelta
import polars as pl

s = (
    pl.Series([datetime(2023, 10, 10, 3, 45) + timedelta(minutes=i * 15) for i in range((365 * 24 * 4) + 2)])
    .dt.replace_time_zone("UTC")
    .dt.convert_time_zone("Europe/Brussels")
)
s.dt.offset_by("1d")
```

### Log output

```shell
Traceback (most recent call last):
  File "/Users/fletawe/Documents/haulogy/scripts/test_offset_by.py", line 9, in <module>
    s.dt.offset_by("1d")
  File "/opt/homebrew/Caskroom/miniforge/base/envs/ameo-3.9/lib/python3.9/site-packages/polars/series/utils.py", line 107, in wrapper
    return s.to_frame().select_seq(f(*args, **kwargs)).to_series()
  File "/opt/homebrew/Caskroom/miniforge/base/envs/ameo-3.9/lib/python3.9/site-packages/polars/dataframe/frame.py", line 8218, in select_seq
    return self.lazy().select_seq(*exprs, **named_exprs).collect(_eager=True)
  File "/opt/homebrew/Caskroom/miniforge/base/envs/ameo-3.9/lib/python3.9/site-packages/polars/lazyframe/frame.py", line 1943, in collect
    return wrap_df(ldf.collect())
polars.exceptions.ComputeError: datetime '2023-10-29 02:00:00' is ambiguous in time zone 'Europe/Brussels'. Please use `ambiguous` to tell how it should be localized.
```

### Issue description

Hello,
`offset_by` does not seem to work properly for the time change with calendar days/months/year.
We get ambiguous datetime error for summer to winter and non-existent datetime error for winter to summer.

### Expected behavior

It should be able to compute the correct datetimes and avoid ambiguous (summer -> winter) or non-existent (winter -> summer) errors.

### Installed versions

<details>

```
--------Version info---------
Polars:               0.20.16
Index type:           UInt32
Platform:             macOS-14.0-arm64-arm-64bit
Python:               3.9.18 | packaged by conda-forge | (main, Dec 23 2023, 16:35:41)
[Clang 16.0.6 ]

----Optional dependencies----
adbc_driver_manager:  <not installed>
cloudpickle:          <not installed>
connectorx:           <not installed>
deltalake:            <not installed>
fastexcel:            <not installed>
fsspec:               <not installed>
gevent:               <not installed>
hvplot:               <not installed>
matplotlib:           <not installed>
numpy:                1.23.5
openpyxl:             3.1.0
pandas:               1.5.3
pyarrow:              14.0.2
pydantic:             1.10.13
pyiceberg:            <not installed>
pyxlsb:               <not installed>
sqlalchemy:           1.3.23
xlsx2csv:             <not installed>
xlsxwriter:           <not installed>
```

</details>

**Comment by MarcoGorelli** [comment]
thanks @fletawe-haulogy for the report - `offset_by` should probably get `ambiguous` / `non_existent` arguments too

> It should be able to compute the correct datetimes

Problem is, what is the correct datetime? `2023-10-29 02:00:00 CEST` plus one day, would you expect `2023-10-29 02:00:00 CEST` or `2023-10-29 02:00:00 CET`?

Note that you can use `.dt.offset_by('24h')` to offset by exactly 24 hours - that's always well-defined, so you'll avoid any ambiguous / non-existent datetimes that way (if 24 hours is actually what you want)

**Comment by inyutin** [comment]
The error message could be much clearer here. 

This code:
```python
pl.col(col_name).dt.convert_time_zone("Europe/London").dt.offset_by("1d")
```

Produces this exception:
```
datetime '2025-03-30 01:00:00' is non-existent in time zone 'Europe/London'
```

The problem is that `'2025-03-30 01:00:00'` doesn't include any timezone information, which made me think the issue was in the `convert_time_zone("Europe/London")` part. If it showed `'2025-03-30 01:00:00+00:00'` instead, it would be obvious that the error happens after the timezone conversion.

Also, `'2025-03-30 01:00:00'` is actually the datetime *after* applying the "1d" offset, but I thought it was the input datetime. I spent way too much time trying to reproduce this with the wrong data because of that.

A better error message would be something like: `Cannot apply "1d" offset to '2025-03-29 01:00:00+00:00' due to ...`. This would immediately tell you that the offset operation is failing and show the actual input datetime.
