### ISSUE TITLE
PanicException: invalid or out-of-range datetime for large datetime in combination with to_pandas() and from_pandas()

### ISSUE THREAD

**Issue by MarcusJellinghaus** [pola-rs/polars#15313]
### Checks

- [X] I have checked that this issue has not already been reported.
- [X] I have confirmed this bug exists on the [latest version](https://pypi.org/project/polars/) of Polars.

### Reproducible example

```python
import polars as pl

str_values = [
    "2000-01-02 12:23:34",
    "3000-01-02 12:23:34",
    "2001-01-01 00:00:00",
    "3001-01-01 00:00:00",
    None,
    None,
    None,
    None,
]
pl_series_str = pl.Series(str_values)
pl_series_datetime = pl_series_str.str.to_datetime()

pandas_series = pl_series_datetime.to_pandas()
pl_series_from_pandas = pl.from_pandas(pandas_series)

try:
    pl_series_datetime_sql_compliant = pl.select(
        pl.when(pl_series_from_pandas.dt.year() < 1753).then(None).otherwise(pl_series_from_pandas)
    ).to_series(0)
except Exception as e:
    print("Try except worked")
    raise
```

### Log output

```shell
c:/Users/Marcus/Documents/Development/Polars_bug/bug_test.py
thread '<unnamed>' panicked at crates\polars-arrow\src\temporal_conversions.rs:167:37:
invalid or out-of-range datetime
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
Traceback (most recent call last):
  File "c:\Users\Marcus\Documents\Development\Polars_bug\bug_test.py", line 25, in <module>
    pl.when(pl_series_from_pandas.dt.year() < 1753).then(None).otherwise(pl_series_from_pandas)
  File "C:\Users\Marcus\Documents\Development\Polars_bug\.venv\lib\site-packages\polars\series\utils.py", line 107, in wrapper  
    return s.to_frame().select_seq(f(*args, **kwargs)).to_series()
  File "C:\Users\Marcus\Documents\Development\Polars_bug\.venv\lib\site-packages\polars\dataframe\frame.py", line 8218, in select_seq
    return self.lazy().select_seq(*exprs, **named_exprs).collect(_eager=True)
  File "C:\Users\Marcus\Documents\Development\Polars_bug\.venv\lib\site-packages\polars\lazyframe\frame.py", line 1943, in collect
    return wrap_df(ldf.collect())
pyo3_runtime.PanicException: invalid or out-of-range datetime



RUST_BACKTRACE=1
C:\myenv\Scripts\python.exe C:\myrepo\code_snippets\testing.py
thread '<unnamed>' panicked at crates\polars-arrow\src\temporal_conversions.rs:189:37:
invalid or out-of-range datetime
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
Traceback (most recent call last):
  File "C:\myrepo\code_snippets\testing.py", line 68, in <module>
    pl.when(pl_series_from_pandas.dt.year() < 1753).then(None).otherwise(pl_series_from_pandas)
  File "C:\myenv\lib\site-packages\polars\series\utils.py", line 107, in wrapper
    return s.to_frame().select_seq(f(*args, **kwargs)).to_series()
  File "C:\myenv\lib\site-packages\polars\dataframe\frame.py", line 8154, in select_seq
    return self.lazy().select_seq(*exprs, **named_exprs).collect(_eager=True)
  File "C:\myenv\lib\site-packages\polars\lazyframe\frame.py", line 1937, in collect
    return wrap_df(ldf.collect())
pyo3_runtime.PanicException: invalid or out-of-range datetime
```

### Issue description

When reading large datetime values from pandas, a PanicException occured. The normal python exception handling is not working.

### Expected behavior

- A roundtrip (to_pandas() and from_pandas()) should work.
- A `pyo3_runtime.PanicException: invalid or out-of-range datetime` should not happen. Instead, the python try / except should work.

### Installed versions

<details>

```
--------Version info---------
Polars:               0.20.16
Index type:           UInt32
Platform:             Windows-10-10.0.19041-SP0
Python:               3.9.0 (tags/v3.9.0:9cf6752, Oct  5 2020, 15:34:40) [MSC v.1927 64 bit (AMD64)]

----Optional dependencies----
adbc_driver_manager:  <not installed>
cloudpickle:          <not installed>
connectorx:           <not installed>
deltalake:            <not installed>
fastexcel:            <not installed>
fsspec:               <not installed>
gevent:               <not installed>
hvplot:               <not installed>
matplotlib:           <not installed>
numpy:                1.26.4
openpyxl:             <not installed>
pandas:               2.2.1
pyarrow:              15.0.2
pydantic:             <not installed>
pyiceberg:            <not installed>
pyxlsb:               <not installed>
sqlalchemy:           <not installed>
xlsx2csv:             <not installed>
xlsxwriter:           <not installed>
```

</details>

**Comment by MarcoGorelli** [comment]
thanks for the ping, fix incoming
