### ISSUE TITLE
`pl.repeat()` panicks if input doesn't match data type

### ISSUE THREAD

**Issue by etiennebacher** [pola-rs/polars#15379]
### Checks

- [X] I have checked that this issue has not already been reported.
- [X] I have confirmed this bug exists on the [latest version](https://pypi.org/project/polars/) of Polars.

### Reproducible example

```python
>>> import polars as pl
>>> pl.repeat([1, 2], n=2)
thread 'python3' panicked at py-polars/src/functions/lazy.rs:454:36:
called `Option::unwrap()` on a `None` value
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/etienne/.local/lib/python3.10/site-packages/polars/functions/repeat.py", line 143, in repeat
    expr = wrap_expr(plr.repeat(value, n._pyexpr, dtype))
pyo3_runtime.PanicException: called `Option::unwrap()` on a `None` value
```

### Issue description

`pl.repeat()` panicks when input length is greater than 1.

### Expected behavior

Not panick but throw an error instead.

### Installed versions

<details>

```
--------Version info---------
Polars:               0.20.17
Index type:           UInt32
Platform:             Linux-6.5.0-21-generic-x86_64-with-glibc2.35
Python:               3.10.12 (main, Nov 20 2023, 15:14:05) [GCC 11.4.0]

----Optional dependencies----
adbc_driver_manager:  <not installed>
cloudpickle:          <not installed>
connectorx:           <not installed>
deltalake:            <not installed>
fastexcel:            <not installed>
fsspec:               <not installed>
gevent:               <not installed>
hvplot:               <not installed>
matplotlib:           <not installed>
nest_asyncio:         <not installed>
numpy:                1.21.5
openpyxl:             <not installed>
pandas:               <not installed>
pyarrow:              <not installed>
pydantic:             <not installed>
pyiceberg:            <not installed>
pyxlsb:               <not installed>
sqlalchemy:           <not installed>
xlsx2csv:             <not installed>
xlsxwriter:           <not installed>
```

</details>

**Comment by mcrumiller** [comment]
The issue is that your value is a list. This actually works if you specify the dtype properly:

```python
import polars as pl

pl.select(
    pl.repeat([1, 2], n=2, dtype=pl.List(pl.Int32))
)

# shape: (2, 1)
# ┌───────────┐
# │ repeat    │
# │ ---       │
# │ list[i32] │
# ╞═══════════╡
# │ [1, 2]    │
# │ [1, 2]    │
# └───────────┘
```

However, the error message should probably be more informative.

**Comment by etiennebacher** [comment]
The problem here isn't that the code doesn't work but that it panicks instead of having a proper error (cf https://github.com/pola-rs/polars/issues/14463)
