### ISSUE TITLE
`.clear(-1)` doesn't have the same behavior for `Series` and `DataFrame`

### ISSUE THREAD

**Issue by etiennebacher** [pola-rs/polars#15421]
### Checks

- [X] I have checked that this issue has not already been reported.
- [X] I have confirmed this bug exists on the [latest version](https://pypi.org/project/polars/) of Polars.

### Reproducible example

```python
import polars as pl

s = pl.Series("a", [None, True, False])
s.clear(-1)

df = pl.DataFrame(
    {
        "a": [None, 2, 3, 4],
        "b": [0.5, None, 2.5, 13],
        "c": [True, True, False, None],
    }
)

df.clear(-1)
```

### Log output

```shell
>>> s.clear(-1)
shape: (0,)
Series: 'a' [bool]
[
]

>>> df.clear(-1)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Python311\Lib\site-packages\polars\dataframe\frame.py", line 6898, in clear
    {
  File "C:\Python311\Lib\site-packages\polars\dataframe\frame.py", line 6899, in <dictcomp>
    nm: pl.Series(name=nm, dtype=tp).extend_constant(None, n)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python311\Lib\site-packages\polars\series\utils.py", line 107, in wrapper
    return s.to_frame().select_seq(f(*args, **kwargs)).to_series()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python311\Lib\site-packages\polars\dataframe\frame.py", line 8127, in select_seq
    return self.lazy().select_seq(*exprs, **named_exprs).collect(_eager=True)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python311\Lib\site-packages\polars\lazyframe\frame.py", line 1943, in collect
    return wrap_df(ldf.collect())
                   ^^^^^^^^^^^^^
polars.exceptions.ComputeError: conversion from `i32` to `u64` failed in column 'literal' for 1 out 
of 1 values: [-1]
```

### Issue description

`.clear(-1)` is equivalent to `.clear(0)` for `Series`, but it errors for `DataFrame`. 

### Expected behavior

It should probably error in both cases. In any case, it should have the same behavior.

### Installed versions

<details>

```
--------Version info---------
Polars:               0.20.17
Index type:           UInt32 
Platform:             Windows-10-10.0.19044-SP0
Python:               3.11.0 (main, Oct 24 2022, 18:26:48) [MSC v.1933 64 bit (AMD64)]

----Optional dependencies----
adbc_driver_manager:  <not installed>
cloudpickle:          <not installed>
connectorx:           <not installed>
deltalake:            <not installed>
fastexcel:            <not installed>
fsspec:               2023.6.0
gevent:               <not installed>
hvplot:               0.9.2
matplotlib:           3.7.1
nest_asyncio:         1.5.6
numpy:                1.24.3
openpyxl:             <not installed>
pandas:               2.0.3
pyarrow:              12.0.1
pydantic:             2.6.4
pyiceberg:            <not installed>
pyxlsb:               <not installed>
sqlalchemy:           <not installed>
xlsx2csv:             <not installed>
xlsxwriter:           <not installed>
```

</details>

**Comment by stinodego** [comment]
Thanks for the report. Both should error.
