### ISSUE TITLE
Column data type when first element is empty list

### ISSUE THREAD

**Issue by DJDuque** [pola-rs/polars#15425]
### Checks

- [X] I have checked that this issue has not already been reported.
- [X] I have confirmed this bug exists on the [latest version](https://pypi.org/project/polars/) of Polars.

### Reproducible example

```python
import polars as pl
from typing import NamedTuple


class Event(NamedTuple):
    name: str
    description: str


def event_table(num) -> list[Event]:
    events = []
    for i in range(num):
        events.append(Event("name", "description"))
    return events

data = {"events": [0, 1, 2]}
df = pl.DataFrame(data).select(
    events=pl.col("events").map_elements(
        event_table,
        return_dtype=pl.List(pl.Struct({"name": pl.String, "description": pl.String})),
    )
)
```

### Log output

```shell
Traceback (most recent call last):
  File "/home/daniel/Trash/question_polars/script.py", line 17, in <module>
    df = pl.DataFrame(data).select(
         ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/daniel/Trash/question_polars/.venv/lib/python3.11/site-packages/polars/dataframe/frame.py", line 8102, in select
    return self.lazy().select(*exprs, **named_exprs).collect(_eager=True)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/daniel/Trash/question_polars/.venv/lib/python3.11/site-packages/polars/lazyframe/frame.py", line 1943, in collect
    return wrap_df(ldf.collect())
                   ^^^^^^^^^^^^^
polars.exceptions.SchemaError: expected output type 'List(Struct([Field { name: "name", dtype: String }, Field { name: "description", dtype: String }]))', got 'List(List(String))'; set `return_dtype` to the proper datatype
```

### Issue description

See my SO question [here](https://stackoverflow.com/questions/78253818/how-to-specify-column-data-type/78256063?noredirect=1#comment137964119_78256063)

Someone mentioned being able to get this working with `pl.Field`, but I am not able to reproduce it.

### Expected behavior

I would expect this to produce a correct df where the data type is `list[struct[2]]`. Same as running with `data = {"events": [1, 2]}` (non-empty first list).

### Installed versions

<details>

```
--------Version info---------
Polars:               0.20.17
Index type:           UInt32
Platform:             Linux-6.8.1-arch1-1-x86_64-with-glibc2.39
Python:               3.11.8 (main, Feb 12 2024, 14:50:05) [GCC 13.2.1 20230801]

----Optional dependencies----
adbc_driver_manager:  <not installed>
cloudpickle:          <not installed>
connectorx:           <not installed>
deltalake:            <not installed>
fastexcel:            <not installed>
fsspec:               <not installed>
gevent:               <not installed>
hvplot:               <not installed>
matplotlib:           <not installed>
nest_asyncio:         <not installed>
numpy:                <not installed>
openpyxl:             <not installed>
pandas:               <not installed>
pyarrow:              <not installed>
pydantic:             <not installed>
pyiceberg:            <not installed>
pyxlsb:               <not installed>
sqlalchemy:           <not installed>
xlsx2csv:             <not installed>
xlsxwriter:           <not installed>
```

</details>

**Comment by cmdlineluser** [comment]
@hericks The difference seems to be in `def events_table`

You're appending a plain dict:

```python
events.append({"name": "my_name", "description": "my_desc"})
```

As opposed to an Event object:

```python
events.append(Event("name", "description"))
```

**Comment by DJDuque** [comment]
Ok. After seeing @hericks code I can reproduce.

See the `event_table` function:
- With `events.append({"name": "my_name", "description": "my_desc"})` works.
- With `events.append(Event("name", "description"))` breaks.

**Comment by deanm0000** [comment]
The issue is that when polars is handling the nested NamedTuple it just checks `isinstance(x, tuple)` which is True for NamedTuples so it treats it like a list. I added a check if `_asdict` method exists and if it does then treat it like a dict instead.
