### ISSUE TITLE
Spurious test failure in `polars-lazy` tests

### ISSUE THREAD

**Issue by stinodego** [pola-rs/polars#15435]
https://github.com/pola-rs/polars/actions/runs/8518212184/job/23329986671?pr=15434

```
error: test failed, to rerun pass `-p polars-lazy --lib`

Caused by:
  process didn't exit successfully: `D:\a\polars\polars\target\debug\deps\polars_lazy-57caa9d387777920.exe` (exit code: 0xc0000005, STATUS_ACCESS_VIOLATION)
note: test exited abnormally; to see the full output pass --nocapture to the harness.
Error: Process completed with exit code 1.
```

Gather more similar test failures here so we can reproduce this.

**Comment by stinodego** [comment]
Different failure:
https://github.com/pola-rs/polars/actions/runs/8504614170/job/23291796336?pr=15412

```
thread 'logical_plan::optimizer::cse::cse_expr::test::test_cse_replacer' panicked at library\core\src\panicking.rs:152:5:
unsafe precondition(s) violated: slice::from_raw_parts requires the pointer to be aligned and non-null, and the total size of the slice not to exceed `isize::MAX`
stack backtrace:
   0: std::panicking::begin_panic_handler
             at /rustc/c9f8f3438a8134a413aa5d4903e0196e44e37bbc/library\std\src\panicking.rs:646
   1: core::panicking::panic_nounwind_fmt::runtime
             at /rustc/c9f8f3438a8134a413aa5d4903e0196e44e37bbc/library\core\src\panicking.rs:110
   2: core::panicking::panic_nounwind_fmt
             at /rustc/c9f8f3438a8134a413aa5d4903e0196e44e37bbc/library\core\src\panicking.rs:120
   3: core::panicking::panic_nounwind
             at /rustc/c9f8f3438a8134a413aa5d4903e0196e44e37bbc/library\core\src\panicking.rs:152
   4: core::slice::raw::from_raw_parts::precondition_check
   5: <alloc::vec::Vec<T,A> as core::ops::deref::Deref>::deref
   6: <alloc::vec::Vec<T,A> as core::clone::Clone>::clone
   7: <polars_plan::logical_plan::aexpr::AExpr as core::clone::Clone>::clone
   8: <polars_plan::logical_plan::visitor::expr::AexprNode as polars_plan::logical_plan::visitor::visitors::TreeWalker>::map_children
   9: polars_plan::logical_plan::visitor::visitors::TreeWalker::rewrite::{{closure}}
  10: polars_plan::logical_plan::visitor::visitors::TreeWalker::rewrite
  11: polars_plan::logical_plan::optimizer::cse::cse_expr::test::test_cse_replacer::{{closure}}
  12: polars_plan::logical_plan::visitor::expr::AexprNode::with_context
  13: polars_plan::logical_plan::optimizer::cse::cse_expr::test::test_cse_replacer::{{closure}}
  14: polars_plan::logical_plan::optimizer::cse::cse_expr::test::test_cse_replacer::{{closure}}
  15: core::ops::function::FnOnce::call_once
  16: core::ops::function::FnOnce::call_once
             at /rustc/c9f8f3438a8134a413aa5d4903e0196e44e37bbc/library\core\src\ops\function.rs:250
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
thread caused non-unwinding panic. aborting.
error: test failed, to rerun pass `-p polars-plan --lib`

Caused by:
  process didn't exit successfully: `D:\a\polars\polars\target\debug\deps\polars_plan-7980ed978d422670.exe` (exit code: 0xc0000409, STATUS_STACK_BUFFER_OVERRUN)
note: test exited abnormally; to see the full output pass --nocapture to the harness.
```

**Comment by stinodego** [comment]
Closing as stale.
