### ISSUE TITLE
Projection pushdown regression when dropping selected columns

### ISSUE THREAD

**Issue by josh** [pola-rs/polars#15430]
### Checks

- [X] I have checked that this issue has not already been reported.
- [X] I have confirmed this bug exists on the [latest version](https://pypi.org/project/polars/) of Polars.

### Reproducible example

```python
import polars as pl

print(
    pl.LazyFrame([{"a": {"b": "c"}}])
    .with_columns(pl.col("a").struct.field("b"))
    .drop("a")
    .collect()
)
```

### Log output

```shell
Traceback (most recent call last):
  File "bug.py", line 7, in <module>
    .collect()
     ^^^^^^^^^
  File "/opt/python/3.11.7/lib/python3.11/site-packages/polars/lazyframe/frame.py", line 1943, in collect
    return wrap_df(ldf.collect())
                   ^^^^^^^^^^^^^
polars.exceptions.SchemaFieldNotFoundError: b
```

### Issue description

Not entirely sure how to describe the issue. But tried to get the example as simple as possible. But it seems like selecting a struct field, then dropping the column that contains the struct after leads to some query optimizer bug where it thinks the original column is missing.

Version 0.20.16 seems okay, then both 0.20.17 and 0.20.18 crash as above.

### Expected behavior

```
shape: (1, 1)
┌─────┐
│ b   │
│ --- │
│ str │
╞═════╡
│ c   │
└─────┘
```

### Installed versions

<details>

```
--------Version info---------
Polars:               0.20.18
Index type:           UInt32
Platform:             Linux-6.2.0-1019-azure-x86_64-with-glibc2.31
Python:               3.11.7 (main, Jan  8 2024, 20:44:44) [GCC 9.4.0]

----Optional dependencies----
adbc_driver_manager:  <not installed>
cloudpickle:          <not installed>
connectorx:           <not installed>
deltalake:            <not installed>
fastexcel:            <not installed>
fsspec:               2024.3.1
gevent:               <not installed>
hvplot:               <not installed>
matplotlib:           <not installed>
nest_asyncio:         <not installed>
numpy:                1.26.4
openpyxl:             <not installed>
pandas:               <not installed>
pyarrow:              <not installed>
pydantic:             <not installed>
pyiceberg:            <not installed>
pyxlsb:               <not installed>
sqlalchemy:           <not installed>
xlsx2csv:             <not installed>
xlsxwriter:           <not installed>
```

</details>

**Comment by cmdlineluser** [comment]
I believe `projection_pushdown` is the name:

```python
print(
    pl.LazyFrame([{"a": {"b": "c"}}])
    .with_columns(pl.col("a").struct.field("b"))
    .drop("a")
    .collect(projection_pushdown=False)
)

# shape: (1, 1)
# ┌─────┐
# │ b   │
# │ --- │
# │ str │
# ╞═════╡
# │ c   │
# └─────┘
```
