### ISSUE TITLE
`SchemaError` when combining boolean expressions on Decimals using `!=` (fine with `.ne()`)

### ISSUE THREAD

**Issue by butla** [pola-rs/polars#15465]
### Checks

- [X] I have checked that this issue has not already been reported.
- [X] I have confirmed this bug exists on the [latest version](https://pypi.org/project/polars/) of Polars.

### Reproducible example

```python
import polars as pl
from decimal import Decimal
df = pl.DataFrame({'a': [Decimal('0.5'), None, Decimal('0.00001'), Decimal(0)], 'b': [1, 2, 3, 4]})

# is fine
df.with_columns((pl.col('a').is_not_null() & pl.col('a').ne(0)).alias('a_is_not_null_and_not_equal_zero'))
# crashes
df.with_columns((pl.col('a').is_not_null() & pl.col('a') != 0).alias('a_is_not_null_and_not_equal_zero'))
# is fine
df.with_columns((pl.col('a') != 0).alias('a_is_not_equal_zero'))
```

### Log output

```shell
Traceback (most recent call last):
  File "<stdin>", line 8, in <module>
  File "/home/butla/<omitted>/.venv/lib/python3.11/site-packages/polars/dataframe/frame.py", line 8297, in with_columns
    return self.lazy().with_columns(*exprs, **named_exprs).collect(_eager=True)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/butla/<omitted>/.venv/lib/python3.11/site-packages/polars/lazyframe/frame.py", line 1943, in collect
    return wrap_df(ldf.collect())
                   ^^^^^^^^^^^^^
polars.exceptions.SchemaError: cannot unpack series of type `decimal[*,5]` into `bool`

cannot unpack series of type `decimal[*,5]` into `bool`

```

### Issue description

When I'm using decimals and combining decimal expressions that use `!=` I get an error.
It's fine if I replace `!=` with `.ne()`. Documentation states that `!=` and `.ne()` are equivalent. Looks like some quirk in Decimals implementation is breaking `!=` and `==` when expressions are combined with `&`.

### Expected behavior

All the code I pasted should pass.

Both of these lines should run the same code, but they clearly don't:
```
df.with_columns((pl.col('a').is_not_null() & pl.col('a').ne(0)).alias('a_is_not_null_and_not_equal_zero'))
df.with_columns((pl.col('a').is_not_null() & pl.col('a') != 0).alias('a_is_not_null_and_not_equal_zero'))
```

### Installed versions

0.20.18

**Comment by cmdlineluser** [comment]
It's a precedence issue, you need to use parens around the != condition.

```python
df.with_columns((pl.col('a').is_not_null() & (pl.col('a') != 0)).alias('a_is_not_null_and_not_equal_zero'))

# shape: (4, 3)
# ┌──────────────┬─────┬──────────────────────────────────┐
# │ a            ┆ b   ┆ a_is_not_null_and_not_equal_zero │
# │ ---          ┆ --- ┆ ---                              │
# │ decimal[*,5] ┆ i64 ┆ bool                             │
# ╞══════════════╪═════╪══════════════════════════════════╡
# │ 0.50000      ┆ 1   ┆ true                             │
# │ null         ┆ 2   ┆ false                            │
# │ 0.00001      ┆ 3   ┆ true                             │
# │ 0            ┆ 4   ┆ false                            │
# └──────────────┴─────┴──────────────────────────────────┘
```

**Comment by butla** [comment]
@cmdlineluser [Ahh, true!](https://docs.python.org/3/reference/expressions.html#operator-precedence) Sorry to bother!

The error is more clear with floats, though:
```
>>> df = pl.DataFrame({'a': [0.5, None, 0.1, 0], 'b': [1, 2, 3, 4]})
>>> df.with_columns((pl.col('a').is_not_null() & pl.col('a') != 0).alias('a_is_not_null_and_not_equal_zero'))
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/butla/.local/pipx/venvs/ptpython/lib/python3.10/site-packages/polars/dataframe/frame.py", line 8297, in with_columns
    return self.lazy().with_columns(*exprs, **named_exprs).collect(_eager=True)
  File "/home/butla/.local/pipx/venvs/ptpython/lib/python3.10/site-packages/polars/lazyframe/frame.py", line 1943, in collect
    return wrap_df(ldf.collect())
polars.exceptions.InvalidOperationError: `bitand` operation not supported for dtype `f64`
```
