### ISSUE TITLE
pyo3_runtime.PanicException: python function failed: PyErr { type: <class 'TypeError'>, value: TypeError("'list' object is not callable"), traceback: None }

### ISSUE THREAD

**Issue by AlesyaSeliazniova30032012** [pola-rs/polars#15484]
### Description

Hi. I want to read csv. Try:
`
ldf = (
        pl.scan_csv(fn, has_header=True, with_column_names=ALL_PNL_COLUMNS, dtypes={"market_id": pl.String, "runner_id": pl.String,})  
        .select(EXPECTED_PNL_COLUMNS)
        .with_columns('bet_timestamp', pl.col('bet_timestamp').str.to_datetime("%Y-%m-%d %H:%M:%S.%f"))
        .sort('bet_id')
        .drop('index')
        .filter(pl.col('bet_status') != 'VOID')
    )
    ldf = ldf.collect()`

and get error:
`
thread 'python' panicked at py-polars/src/lazyframe/mod.rs:223:58:
python function failed: PyErr { type: <class 'TypeError'>, value: TypeError("'list' object is not callable"), traceback: None }
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
Process Process-1:
Traceback (most recent call last):
  File "/home/alesja/anaconda3/envs/myenv/lib/python3.11/site-packages/multiprocess/process.py", line 314, in _bootstrap
    self.run()
  File "/home/alesja/anaconda3/envs/myenv/lib/python3.11/site-packages/multiprocess/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/home/alesja/anaconda3/envs/myenv/lib/python3.11/site-packages/dash/long_callback/managers/diskcache_manager.py", line 197, in job_fn
    ctx.run(run)
  File "/home/alesja/anaconda3/envs/myenv/lib/python3.11/site-packages/dash/long_callback/managers/diskcache_manager.py", line 179, in run
    user_callback_output = fn(*maybe_progress, *user_callback_args)
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/alesja/whitehorse/gui/pages/polar.py", line 221, in update_layout
    strategy_ldf, balance_ldf = get_experiment_reports(select)
                                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/alesja/whitehorse/gui/utils/util.py", line 52, in get_experiment_reports
    pnl_ldf = get_lazy_pnl_df_from_csv(os.path.join(tmp_dir, REPORT_FILENAME))
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/alesja/whitehorse/gui/utils/common.py", line 120, in get_lazy_pnl_df_from_csv
    pl.scan_csv(fn, has_header=True, with_column_names=ALL_PNL_COLUMNS, dtypes={"market_id": pl.String, "runner_id": pl.String,})
  File "/home/alesja/anaconda3/envs/myenv/lib/python3.11/site-packages/polars/_utils/deprecation.py", line 134, in wrapper
    return function(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/alesja/anaconda3/envs/myenv/lib/python3.11/site-packages/polars/_utils/deprecation.py", line 134, in wrapper
    return function(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/alesja/anaconda3/envs/myenv/lib/python3.11/site-packages/polars/_utils/deprecation.py", line 134, in wrapper
    return function(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/alesja/anaconda3/envs/myenv/lib/python3.11/site-packages/polars/io/csv/functions.py", line 947, in scan_csv
    return pl.LazyFrame._scan_csv(
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/alesja/anaconda3/envs/myenv/lib/python3.11/site-packages/polars/lazyframe/frame.py", line 389, in _scan_csv
    self._ldf = PyLazyFrame.new_from_csv(
                ^^^^^^^^^^^^^^^^^^^^^^^^^
pyo3_runtime.PanicException: python function failed: PyErr { type: <class 'TypeError'>, value: TypeError("'list' object is not callable"), traceback: None }`
Why it happen? Help pls

**Comment by cmdlineluser** [comment]
This may fall under 

- https://github.com/pola-rs/polars/issues/15431

As it is currently a bit confusing:

<blockquote>

**with_column_names**
Apply a function over the column names just in time

</blockquote>


<blockquote>

**new_columns**
Provide an explicit list of string column names to use

</blockquote>
