### ISSUE TITLE
`.backward_fill()` does not consider `np.nan` to be invalid

### ISSUE THREAD

**Issue by marc-at-brightnight** [pola-rs/polars#15494]
### Checks

- [X] I have checked that this issue has not already been reported.
- [X] I have confirmed this bug exists on the [latest version](https://pypi.org/project/polars/) of Polars.

### Reproducible example

```python
import numpy as np

df = pl.DataFrame({
    "f": [1.0, None, 1.0],
})

bfilled_df = df.select(pl.all().backward_fill())

assert bfilled_df[1, 'f'] == 1 # works

df = pl.DataFrame({
    "f": [1.0, np.nan, 1.0],
})

bfilled_df = df.select(pl.all().backward_fill())

assert bfilled_df[1, 'f'] == 1 # does not work
```

### Log output

```shell
Traceback (most recent call last):
  File "/Users/mnhmbp/PycharmProjects/poweralpha/venv/lib/python3.10/site-packages/IPython/core/interactiveshell.py", line 3577, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-4-cc1558aaef03>", line 17, in <module>
    assert bfilled_df[1, 'f'] == 1 # does not work
AssertionError
```

### Issue description

`.backward_fill()` works as expected with `None`s. However, with `np.nan` values, it does not work. This seems strange to me.

### Expected behavior

It should work with `np.nan` as it does with `None`

### Installed versions

<details>

```
--------Version info---------
Polars:               0.20.18
Index type:           UInt32
Platform:             macOS-14.2-arm64-arm-64bit
Python:               3.10.13 (main, Aug 24 2023, 12:59:26) [Clang 15.0.0 (clang-1500.0.40.1)]
----Optional dependencies----
adbc_driver_manager:  <not installed>
cloudpickle:          3.0.0
connectorx:           <not installed>
deltalake:            <not installed>
fastexcel:            <not installed>
fsspec:               2024.2.0
gevent:               <not installed>
hvplot:               <not installed>
matplotlib:           3.8.3
nest_asyncio:         <not installed>
numpy:                1.23.0
openpyxl:             3.1.2
pandas:               1.5.3
pyarrow:              15.0.1
pydantic:             2.6.3
pyiceberg:            <not installed>
pyxlsb:               <not installed>
sqlalchemy:           1.4.52
xlsx2csv:             <not installed>
xlsxwriter:           <not installed>
```

</details>

**Comment by cmdlineluser** [comment]
I think this is expected:

> These NaN values are considered to be a type of floating point data rather than missing data.

- https://docs.pola.rs/user-guide/expressions/missing-data/#notanumber-or-nan-values

**Comment by orlp** [comment]
This is by design. Use `.fill_nan(None)` first if you want to also fill NaNs.
