### ISSUE TITLE
Why two struct series with different type are equal?

### ISSUE THREAD

**Issue by 52hz11** [pola-rs/polars#15524]
### Checks

- [X] I have checked that this issue has not already been reported.
- [X] I have confirmed this bug exists on the [latest version](https://crates.io/crates/polars) of Polars.

### Reproducible example

```rust
use polars::prelude::*;
fn main() {
    let a_series = Series::new("a", vec!["a1"]);
    let b_series = Series::new("b", vec!["b1"]);
    let series_1 = StructChunked::new("test_ab", &[a_series, b_series])
        .unwrap()
        .into_series();
    let a_series = Series::new("a", vec![Series::new("a", vec!["a1"])]);
    let b_series = Series::new("b", vec![Series::new("b", vec!["b1"])]);
    let series_2 = StructChunked::new("test_ab", &[a_series, b_series])
        .unwrap()
        .into_series();
    assert_eq!(series_1, series_2);
    assert_eq!(series_1.dtype(), series_2.dtype());
    ()
}

```

### Log output

```shell
thread 'main' panicked at src/main.rs:14:5:
assertion `left == right` failed
  left: Struct([Field { name: "a", dtype: String }, Field { name: "b", dtype: String }])
 right: Struct([Field { name: "a", dtype: List(String) }, Field { name: "b", dtype: List(String) }])
stack backtrace:
   0: rust_begin_unwind
             at /rustc/e0d7ed1f453fb54578cc96dfea859b0e7be15016/library/std/src/panicking.rs:597:5
   1: core::panicking::panic_fmt
             at /rustc/e0d7ed1f453fb54578cc96dfea859b0e7be15016/library/core/src/panicking.rs:72:14
   2: core::panicking::assert_failed_inner
   3: core::panicking::assert_failed
             at /rustc/e0d7ed1f453fb54578cc96dfea859b0e7be15016/library/core/src/panicking.rs:280:5
   4: polarstest::main
             at ./src/main.rs:14:5
   5: core::ops::function::FnOnce::call_once
             at /rustc/e0d7ed1f453fb54578cc96dfea859b0e7be15016/library/core/src/ops/function.rs:250:5
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```

### Issue description

two struct series with different type are equal

### Expected behavior

I expect series_1 and series_2 are unequal

### Installed versions

<details>

[dependencies]
polars = { version = "0.38.3", features = [
  "dtype-struct",
] }

</details>

**Comment by 52hz11** [comment]
> @52hz11 Why you use `.unwrap().into_series()`? `StructChunked` already implemented [equal](https://docs.rs/polars/latest/polars/datatypes/struct.StructChunked.html#method.equal). Just assert two your's series without `.unwrap().into_series()`, and it works!

But I don't understand why StructChunked implements equal but Series do not？Is is by design or just not implemented？

**Comment by 52hz11** [comment]
And I tried by StructChunked::equal，it did not works：
```rust
use polars::prelude::*;
fn main() {
    let a_series = Series::new("a", vec!["a1"]);
    let b_series = Series::new("b", vec!["b1"]);
    let series_1 = StructChunked::new("test_ab", &[a_series, b_series]).unwrap();
    let a_series = Series::new("a", vec![Series::new("a", vec!["a1"])]);
    let b_series = Series::new("b", vec![Series::new("b", vec!["b1"])]);
    let series_2 = StructChunked::new("test_ab", &[a_series, b_series]).unwrap();
    dbg!(&series_1.equal(&series_2));
    assert_eq!(series_1.dtype(), series_2.dtype());
    ()
}
```
output:
```
[src/main.rs:9] &series_1.equal(&series_2) = shape: (1,)
ChunkedArray: 'a' [bool]
[
        true
]
thread 'main' panicked at src/main.rs:10:5:
assertion `left == right` failed
  left: Struct([Field { name: "a", dtype: String }, Field { name: "b", dtype: String }])
 right: Struct([Field { name: "a", dtype: List(String) }, Field { name: "b", dtype: List(String) }])
```
It still get two StructChunked are equal but actually not.
