### ISSUE TITLE
Accept hexadecimal `0x` prefix (and others) in `to_integer()` (maybe also in CSV integer parsing?)

### ISSUE THREAD

**Issue by BGR360** [pola-rs/polars#15567]
## Motivation

I have a program which outputs performance diagnostic logs as CSV with both decimal- and hexadecimal-formatted integer literals:

```csv
...,file_id,name,size
...,0x123,foo,100
...,0xffe,bar,42
```

The explicit `0x` is to aid readability; somebody inspecting the logs should not confuse a hex literal for a decimal literal.

However, polars can't load the `file_id` column as an integer:

```python
df = pl.scan_csv('data.csv', dtypes={'file_id': pl.Int64})
print(df.schema)
print(df.collect())
```

```
OrderedDict([('file_id', Int64), ('name', String), ('size', Int64)])
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/breeves/polars/.venv/lib/python3.9/site-packages/polars/lazyframe/frame.py", line 1683, in collect
    return wrap_df(ldf.collect())
polars.exceptions.ComputeError: could not parse `0x123` as dtype `i64` at column 'file_id' (column number 1)

The current offset in the file is 18 bytes.

You might want to try:
- increasing `infer_schema_length` (e.g. `infer_schema_length=10000`),
- specifying correct dtype with the `dtypes` argument
- setting `ignore_errors` to `True`,
- adding `0x123` to the `null_values` list.
```

It also doesn't work if I manually do `to_integer()` or `to_integer(base=16)` on the column.

The following functions as a workaround, but it'd be great if all the parsing could be done in the Rust code rather than me having to trust the expression optimizer:

```python
def to_integer_from_hex(expr: pl.Expr) -> pl.Expr:
    expr = expr.str.slice(2)             # Trim the `0x`
    expr = expr.str.to_integer(base=16)  # Convert to int
    return expr

pl.scan_csv('data.csv').with_columns(to_integer_from_hex(pl.col('file_id'))).collect()
```

## Feature Request

Accept `0x` prefix (and others) in `Expr.str.to_integer()`, overriding whatever `base` was provided on a per-row basis.

### Desired behavior

For the following CSV file:

```csv
value
100
0xff
0xFF
0hFF
0b111
0o644
0644
```

I want the following code:

```python
pl.scan_csv('data.csv').with_columns(pl.col('value').str.to_integer()).collect()
```

To produce the following:

```
shape: (7, 1)
┌───────┐
│ value │
│ ---   │
│ i64   │
╞═══════╡
│ 100   │
│ 255   │
│ 255   │
│ 255   │
│ 7     │
│ 420   │
│ 420   │
└───────┘
```

Whether the leading `0` by itself should indicate octal is surely debatable.

### Potential extensions

Make the following code produce the same result as above:

```python
pl.scan_csv('data.csv', dtypes={'value': pl.Int64}).collect()
```

Even better, make the following code produce the same result too:

```python
pl.scan_csv('data.csv').collect()
```

### Potential reductions

If it's too much of a change to make `to_integer()` accept all of those , then it would be sufficient (for my purposes) to only change the behavior of `to_integer(base=16)` to accept the leading `0x`.

**Comment by JulianCologne** [comment]
Hi @BGR360 

I think your solution is already very good!
```pythyon
col("x").str.slice(2).str.to_integer(base=16)
```

Adding your logic to `read_csv` / `scan_csv` is probably hard to justify because this is a very "weird" csv file that probably almost no one else has 🤔. This is also quite difficult to add to an already very complicated parsing logic.
On the one hand hex values (0xff) in a csv and on the other also having different (normal) integers (255) sounds to me like either
- fix the csv format
- read as str and convery later (you solution)

**Comment by orlp** [comment]
I would not support changing our CSV readers for this.

I would support changing `.str.to_integer` in the following way:

- Change default `base = 10` to `base = None`.
- If the `base` is None, parse in base 2 if the string starts with `0b`, parse in base 16 if the string starts with `0x` and parse in base 10 otherwise.
- If the `base` is specified, ignore that specific prefix (e.g. `0b` is ignored for base 2), but throw an error otherwise (or output null if `strict = False`).

@stinodego What do you think?

**Comment by stinodego** [comment]
That would be very user-friendly, but is it really worth doing this check on every string?

I think a better solution would be to allow the `base` parameter to take an expression. Then, if the user can calculate the element-wise base (something like `col.str.slice(1,2).replace({'b': 2, 'x': 16}, default=None)` and input that to `str.to_integer(base=my_base_column)`.

**Comment by JulianCologne** [comment]
@stinodego I agree with the performance concern but I think your ideal is too complicated/confusing for users.

IMO @orlp suggestion is very nice!
Regarding the performance concerns I personally would check for `0b` / `0x` only in the first row and use that on all values in the column. Having different representations would then ofc fail but this again is very "weird" data then I would not worry about.

**Comment by orlp** [comment]
After discussing with @stinodego we've decided that it's a bit too much of a can of worms to do the prefix parsing automatically, most notably because `0b01` could be the integer `1`, but it's also a valid hexadecimal number `2817`. We're open to someone expressifying the radix argument however so you can implement whatever radix logic you want.

**Comment by orlp** [comment]
In hindsight it's probably cleaner to make a dedicated issue for this.

**Comment by orlp** [comment]
Now found here: https://github.com/pola-rs/polars/issues/15594.
