### ISSUE TITLE
read_database fails with polars.exceptions.ComputeError if too many NULLs occur first in a json column

### ISSUE THREAD

**Issue by willtalmadge** [pola-rs/polars#15683]
### Checks

- [X] I have checked that this issue has not already been reported.
- [X] I have confirmed this bug exists on the [latest version](https://pypi.org/project/polars/) of Polars.

### Reproducible example

```python
import sqlite3
import polars as pl
import pandas as pd
import json

def main():
    connection = sqlite3.connect(":memory:")
    connection.execute("create table my_table ( value real, config json )")

    # If the range of this loop is 100, polars will fail to load the dataframe
    # with error:
    # polars.exceptions.ComputeError: could not append value: 1.0 of type: f64 to the builder; make sure that all rows have the same schema or consider increasing `infer_schema_length`
    # If this upper limit on the loop is changed to 10, polars will load the dataframe successfully.
    for i in range(100):
        connection.execute(f'insert into my_table (value, config) values (?, ?)',
                           (1.0, json.dumps({"val": None}),) )

    for i in range(100):
        connection.execute(f'insert into my_table (value, config) values (?, ?)',
                       (3.0, json.dumps({"val": 1.0}, sort_keys=True),) )


    # Pandas will succeed, reading 100 sqlite NULLs as NaNs
    query = "select value, json_extract(config, '$.val') as val from my_table"
    df_pandas = pd.read_sql(query, connection )
    print(df_pandas)

    # If we ensure the NULLs occur after the non-NULLs by adding an order by,
    # polars will succeed.
    query = "select value, json_extract(config, '$.val') as val from my_table order by val desc"
    df_pl = pl.read_database(query=query, connection=connection)
    print(df_pl)

    # If the sqlite NULLs occur first in the query result, the following
    # 'read_database' call will fail.
    query = "select value, json_extract(config, '$.val') as val from my_table"
    df_pl = pl.read_database(query=query, connection=connection)
    print(df_pl)

if __name__ == '__main__':
    main()
```

### Log output

```shell
value  val
0      1.0  NaN
1      1.0  NaN
2      1.0  NaN
3      1.0  NaN
4      1.0  NaN
..     ...  ...
195    3.0  1.0
196    3.0  1.0
197    3.0  1.0
198    3.0  1.0
199    3.0  1.0

[200 rows x 2 columns]
shape: (200, 2)
┌───────┬──────┐
│ value ┆ val  │
│ ---   ┆ ---  │
│ f64   ┆ f64  │
╞═══════╪══════╡
│ 3.0   ┆ 1.0  │
│ 3.0   ┆ 1.0  │
│ 3.0   ┆ 1.0  │
│ 3.0   ┆ 1.0  │
│ 3.0   ┆ 1.0  │
│ …     ┆ …    │
│ 1.0   ┆ null │
│ 1.0   ┆ null │
│ 1.0   ┆ null │
│ 1.0   ┆ null │
│ 1.0   ┆ null │
└───────┴──────┘
Traceback (most recent call last):
  File "<redact>.py", line 41, in <module>
    main()
  File "<redact>.py", line 37, in main
    df_pl = pl.read_database(query=query, connection=connection)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<redact>/lib/python3.12/site-packages/polars/io/database/functions.py", line 267, in read_database
    ).to_polars(
      ^^^^^^^^^^
  File "<redact>/lib/python3.12/site-packages/polars/io/database/_executor.py", line 462, in to_polars
    frame = frame_init(
            ^^^^^^^^^^^
  File "<redact>/lib/python3.12/site-packages/polars/io/database/_executor.py", line 274, in _from_rows
    return frames if iter_batches else next(frames)  # type: ignore[arg-type]
                                       ^^^^^^^^^^^^
  File "<redact>/lib/python3.12/site-packages/polars/io/database/_executor.py", line 261, in <genexpr>
    DataFrame(
  File "<redact>/lib/python3.12/site-packages/polars/dataframe/frame.py", line 376, in __init__
    self._df = sequence_to_pydf(
               ^^^^^^^^^^^^^^^^^
  File "<redact>/lib/python3.12/site-packages/polars/_utils/construction/dataframe.py", line 433, in sequence_to_pydf
    return _sequence_to_pydf_dispatcher(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<redact>/lib/python3.12/functools.py", line 909, in wrapper
    return dispatch(args[0].__class__)(*args, **kw)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<redact>/lib/python3.12/site-packages/polars/_utils/construction/dataframe.py", line 644, in _sequence_of_tuple_to_pydf
    return _sequence_of_sequence_to_pydf(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<redact>/lib/python3.12/site-packages/polars/_utils/construction/dataframe.py", line 561, in _sequence_of_sequence_to_pydf
    pydf = PyDataFrame.from_rows(
           ^^^^^^^^^^^^^^^^^^^^^^
polars.exceptions.ComputeError: could not append value: 1.0 of type: f64 to the builder; make sure that all rows have the same schema or consider increasing `infer_schema_length`

it might also be that a value overflows the data-type's capacity
```

### Issue description

In code comments

### Expected behavior

In comments and log output

### Installed versions

<details>

Polars:               0.20.20
Index type:           UInt32
Platform:             macOS-14.2-arm64-arm-64bit
Python:               3.12.2 | packaged by conda-forge | (main, Feb 16 2024, 20:54:21) [Clang 16.0.6 ]

----Optional dependencies----
adbc_driver_manager:  <not installed>
cloudpickle:          <not installed>
connectorx:           <not installed>
deltalake:            <not installed>
fastexcel:            <not installed>
fsspec:               2024.2.0
gevent:               <not installed>
hvplot:               <not installed>
matplotlib:           3.8.3
nest_asyncio:         <not installed>
numpy:                1.26.4
openpyxl:             <not installed>
pandas:               2.2.2
pyarrow:              <not installed>
pydantic:             <not installed>
pyiceberg:            <not installed>
pyxlsb:               <not installed>
sqlalchemy:           <not installed>
xlsx2csv:             <not installed>
xlsxwriter:           <not installed>
</details>

**Comment by alexander-beedie** [comment]
As the error suggests:
```
...or consider increasing `infer_schema_length`.
```
By default we only infer types from the first 100 values, hence the cutoff you're seeing.
Have you tried setting a higher value?

**Comment by alexander-beedie** [comment]
I'm going to close this out as it doesn't seem be a bug here - if you follow the error message suggestion of setting a higher value for `infer_schema_length` then everything will work 🤔
