### ISSUE TITLE
`str.json_decode` panics on `{}` entry

### ISSUE THREAD

**Issue by stinodego** [pola-rs/polars#15720]
### Checks

- [X] I have checked that this issue has not already been reported.
- [X] I have confirmed this bug exists on the [latest version](https://pypi.org/project/polars/) of Polars.

### Reproducible example

```python
import polars as pl

s = pl.Series(["{}"])
result = s.str.json_decode()
print(result)
```

### Log output

```shell
thread '<unnamed>' panicked at crates/polars-arrow/src/array/struct_/mod.rs:117:52:
called `Result::unwrap()` on an `Err` value: ComputeError(ErrString("a StructArray must contain at least one field"))
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
Traceback (most recent call last):
  File "/home/stijn/code/polars/py-polars/repro.py", line 4, in <module>
    result = s.str.json_decode()
             ^^^^^^^^^^^^^^^^^^^
  File "/home/stijn/code/polars/py-polars/polars/series/utils.py", line 107, in wrapper
    return s.to_frame().select_seq(f(*args, **kwargs)).to_series()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/stijn/code/polars/py-polars/polars/dataframe/frame.py", line 7709, in select_seq
    return self.lazy().select_seq(*exprs, **named_exprs).collect(_eager=True)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/stijn/code/polars/py-polars/polars/lazyframe/frame.py", line 1683, in collect
    return wrap_df(ldf.collect())
                   ^^^^^^^^^^^^^
pyo3_runtime.PanicException: called `Result::unwrap()` on an `Err` value: ComputeError(ErrString("a StructArray must contain at least one field"))
```

### Issue description

Brought up in https://github.com/pola-rs/polars/issues/9216

Empty structs do not exist, so this will error.

### Expected behavior

This should raise a proper error.

### Installed versions

main

**Comment by theelderbeever** [comment]
I would be great to be able to coerce to null any empty structs instead of just erroring. In deeply nested json it can be entirely untenable to sanitize the json to make it readable by polars. 

duckdb handles a lot of data that polars isn't as of today.

**Comment by cmdlineluser** [comment]
After https://github.com/pola-rs/polars/pull/18249 this produces:

```python
>>> pl.Series(["{}"]).str.json_decode()
shape: (0,)
Series: '' [struct[0]]
[
]
```

It seems an empty struct in a list will also need support:

```python
>>> pl.Series(["[{}]"]).str.json_decode()
PanicException: called `Result::unwrap()` on an `Err` value: ComputeError(ErrString("offsets must not exceed the values length"))
```

**Comment by cmdlineluser** [comment]
The empty struct in list case is now also fixed:

```python
>>> pl.Series(["[{}]"]).str.json_decode()
shape: (1,)
Series: '' [list[struct[0]]]
[
	[{}]
]
```
