### ISSUE TITLE
`scan_parquet` with `row_index_name` causes inconsistent columns through various transformations

### ISSUE THREAD

**Issue by mathewf2** [pola-rs/polars#15730]
### Checks

- [X] I have checked that this issue has not already been reported.
- [X] I have confirmed this bug exists on the [latest version](https://pypi.org/project/polars/) of Polars.

### Reproducible example

`row_index` column seems to persist no matter what transformations you do
```python
>>> import polars as pl
>>> pl.DataFrame({
...     'a': [1,2,3],
...     'b': [4,5,6]
... }).write_parquet('test0.parquet')
>>> pl.DataFrame({
...     'b': [6,5,4],
...     'a': [9,8,7]
... }).write_parquet('test1.parquet')
>>> lf0 = pl.scan_parquet('test0.parquet', row_index_name='id')
>>> lf1 = pl.scan_parquet('test1.parquet', row_index_name='id')
>>> lf0.collect()
shape: (3, 3)
┌─────┬─────┬─────┐
│ id  ┆ a   ┆ b   │
│ --- ┆ --- ┆ --- │
│ u32 ┆ i64 ┆ i64 │
╞═════╪═════╪═════╡
│ 0   ┆ 1   ┆ 4   │
│ 1   ┆ 2   ┆ 5   │
│ 2   ┆ 3   ┆ 6   │
└─────┴─────┴─────┘
>>> lf0.drop('id')
<LazyFrame [2 cols, {"a": Int64, "b": Int64}] at 0x1ED70773090>
>>> lf0.drop('id').collect()
shape: (3, 3)
┌─────┬─────┬─────┐
│ id  ┆ a   ┆ b   │
│ --- ┆ --- ┆ --- │
│ u32 ┆ i64 ┆ i64 │
╞═════╪═════╪═════╡
│ 0   ┆ 1   ┆ 4   │
│ 1   ┆ 2   ┆ 5   │
│ 2   ┆ 3   ┆ 6   │
└─────┴─────┴─────┘
>>> lf0.select(pl.col('a'))
<LazyFrame [1 col, {"a": Int64}] at 0x1ED7043B750>
>>> lf0.select(pl.col('a')).collect()
shape: (3, 2)
┌─────┬─────┐
│ id  ┆ a   │
│ --- ┆ --- │
│ u32 ┆ i64 │
╞═════╪═════╡
│ 0   ┆ 1   │
│ 1   ┆ 2   │
│ 2   ┆ 3   │
└─────┴─────┘
```

if you try to remove `row_index` column and sink it, it seems like there is a discrepancy between what is stored in the LazyFrame vs. what sink expects

```python
>>> lf0.select(pl.col('a')).sink_parquet('testtest0.parquet')
thread '<unnamed>' panicked at crates\polars-pipe\src\executors\sinks\output\parquet.rs:42:49:
called `Result::unwrap()` on an `Err` value: ComputeError(ErrString("parquet: File out of specification: The max_value of statistics MUST be plain encoded"))
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
thread '<unnamed>' panicked at crates\polars-pipe\src\executors\sinks\output\parquet.rs:126:14:
called `Result::unwrap()` on an `Err` value: Any { .. }
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\vaavew\.conda\envs\tiaia\Lib\site-packages\polars\_utils\unstable.py", line 59, in wrapper
    return function(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\vaavew\.conda\envs\tiaia\Lib\site-packages\polars\lazyframe\frame.py", line 1962, in sink_parquet
    return lf.sink_parquet(
           ^^^^^^^^^^^^^^^^
pyo3_runtime.PanicException: called `Result::unwrap()` on an `Err` value: Any { .. }
>>> lf0.drop('id').columns
['a', 'b']
>>> lf0.drop('id').sink_parquet('testtest0.parquet')
thread 'polars-1' panicked at crates\polars-io\src\parquet\read_impl.rs:60:36:
index out of bounds: the len is 2 but the index is 2
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\vaavew\.conda\envs\tiaia\Lib\site-packages\polars\_utils\unstable.py", line 59, in wrapper
    return function(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\vaavew\.conda\envs\tiaia\Lib\site-packages\polars\lazyframe\frame.py", line 1962, in sink_parquet
    return lf.sink_parquet(
           ^^^^^^^^^^^^^^^^
pyo3_runtime.PanicException: index out of bounds: the len is 2 but the index is 2
```

for joins, if `id` is kept, it will appropriately add the `_right` qualifer. however, if you exclude `id` from both lazyframes to join..
```python
>>> lf2 = lf0.select(pl.col('b'), pl.col('a')).join(lf1.select(pl.col('b'), pl.col('a')), left_on='b', right_on='b', how='left')
>>> lf2
<LazyFrame [3 cols, {"b": Int64 … "a_right": Int64}] at 0x1ED11B4D610>
>>> lf2.collect()
shape: (3, 4)
┌─────┬─────┬─────┬─────────┐
│ b   ┆ a   ┆ id  ┆ a_right │
│ --- ┆ --- ┆ --- ┆ ---     │
│ i64 ┆ i64 ┆ u32 ┆ i64     │
╞═════╪═════╪═════╪═════════╡
│ 4   ┆ 1   ┆ 2   ┆ 7       │
│ 5   ┆ 2   ┆ 1   ┆ 8       │
│ 6   ┆ 3   ┆ 0   ┆ 9       │
└─────┴─────┴─────┴─────────┘
>>> lf2.sink_parquet('testtest.parquet')
thread 'polars-1' panicked at crates\polars-io\src\parquet\read_impl.rs:60:36:
index out of bounds: the len is 2 but the index is 2
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\vaavew\.conda\envs\tiaia\Lib\site-packages\polars\_utils\unstable.py", line 59, in wrapper
    return function(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\vaavew\.conda\envs\tiaia\Lib\site-packages\polars\lazyframe\frame.py", line 1962, in sink_parquet
    return lf.sink_parquet(
           ^^^^^^^^^^^^^^^^
pyo3_runtime.PanicException: index out of bounds: the len is 2 but the index is 2
```
I am unable to reproduce it with a simple example (as it just produces the index out of bounds panic in my simple repros), but when doing a similar join to above, i receive a `ColumnNotFoundError` when trying to sink. however, if i print the colums prior to this sink, the column that is supposed to be missing is clearly in the list. the error where this specific exception is arising is on work data so i can't share explicitly, but it is very comparable to the above join. i will continue to try to repro if necessary and update if i'm able to.

### Issue description

when providing a valid `row_index_name` kwarg to `scan_parquet`, it seems this `row_index` column leads to some inconsistencies with the lazyframe's structure. Namely, this `row_index` column will persist no matter what selection you make or if you try to drop it. If you try and then sink the frame without this column or a variety of simple transformations, it panics as the sink expects n-1 columns (excluding the `row_index`), when it is given n columns (including the `row_index`). In some cases, the sink operation even claims a column does not exist, when the column name is present in `lf.columns` (unable to repro a simple working example of this at this time). `lf.explain(streaming=True)` claims all operations are streaming.

These issues do not seem to be present with `lf.with_row_index()`, as this is no longer entirely streamable.

### Expected behavior

Ability to select a subset of columns of a lazyframe that is scanned in with a `row_index` column and subsequently being able to sink said lazyframe & subset of columns w/o issue.

This doesn't seem like intended behavior, but a lot of the magic of Polars alludes me. I am trying to create a unique id for each row (and concat it with a literal) w/o materializing the frame. `with_row_index()` leads to inability to sink or stream the frame, so being able to create the column on scan (or any streamable operation) is ideal.

### Installed versions

<details>

```
>>> pl.show_versions()
--------Version info---------
Polars:               0.20.21
Index type:           UInt32
Platform:             Windows-10-10.0.19045-SP0
Python:               3.11.3 | packaged by Anaconda, Inc. | (main, May 15 2023, 15:41:31) [MSC v.1916 64 bit (AMD64)]

----Optional dependencies----
adbc_driver_manager:  <not installed>
cloudpickle:          <not installed>
connectorx:           <not installed>
deltalake:            <not installed>
fastexcel:            <not installed>
fsspec:               2024.3.1
gevent:               <not installed>
hvplot:               <not installed>
matplotlib:           3.7.2
nest_asyncio:         1.5.6
numpy:                1.24.3
openpyxl:             <not installed>
pandas:               2.0.2
pyarrow:              15.0.2
pydantic:             2.5.2
pyiceberg:            <not installed>
pyxlsb:               <not installed>
sqlalchemy:           <not installed>
xlsx2csv:             <not installed>
xlsxwriter:           <not installed>
```

</details>

**Comment by mmcdermott** [comment]
I think this is related to a bug I've been experiencing, which can be reproduced on the latest version of polars with this simple script, which should throw no asserts but instead errors out on the third to last assert:

```python
import polars as pl
from pathlib import Path
import tempfile

ADMIT_VITALS_CSV = """
patient_id,admit_date,disch_date,department,vitals_date,HR,temp
239684,"05/11/2010, 17:41:51","05/11/2010, 19:27:19",CARDIAC,"05/11/2010, 18:57:18",112.6,95.5
754281,"01/03/2010, 06:27:59","01/03/2010, 08:22:13",PULMONARY,"01/03/2010, 06:27:59",142.0,99.8
814703,"02/05/2010, 05:55:39","02/05/2010, 07:02:30",ORTHOPEDIC,"02/05/2010, 05:55:39",170.2,100.1
239684,"05/11/2010, 17:41:51","05/11/2010, 19:27:19",CARDIAC,"05/11/2010, 18:25:35",113.4,95.8
68729,"05/26/2010, 02:30:56","05/26/2010, 04:51:52",PULMONARY,"05/26/2010, 02:30:56",86.0,97.8
1195293,"06/20/2010, 19:23:52","06/20/2010, 20:50:04",CARDIAC,"06/20/2010, 20:12:31",112.5,99.8
1500733,"06/03/2010, 14:54:38","06/03/2010, 16:44:26",ORTHOPEDIC,"06/03/2010, 16:20:49",90.1,100.1
239684,"05/11/2010, 17:41:51","05/11/2010, 19:27:19",CARDIAC,"05/11/2010, 17:48:48",105.1,96.2
239684,"05/11/2010, 17:41:51","05/11/2010, 19:27:19",CARDIAC,"05/11/2010, 17:41:51",102.6,96.0
1195293,"06/20/2010, 19:23:52","06/20/2010, 20:50:04",CARDIAC,"06/20/2010, 19:25:32",114.1,100.0
1500733,"06/03/2010, 14:54:38","06/03/2010, 16:44:26",ORTHOPEDIC,"06/03/2010, 14:54:38",91.4,100.0
1195293,"06/20/2010, 19:23:52","06/20/2010, 20:50:04",CARDIAC,"06/20/2010, 20:41:33",107.5,100.4
1195293,"06/20/2010, 19:23:52","06/20/2010, 20:50:04",CARDIAC,"06/20/2010, 20:24:44",107.7,100.0
1195293,"06/20/2010, 19:23:52","06/20/2010, 20:50:04",CARDIAC,"06/20/2010, 19:45:19",119.8,99.9
1195293,"06/20/2010, 19:23:52","06/20/2010, 20:50:04",CARDIAC,"06/20/2010, 19:23:52",109.0,100.0
1500733,"06/03/2010, 14:54:38","06/03/2010, 16:44:26",ORTHOPEDIC,"06/03/2010, 15:39:49",84.4,100.3
"""

with tempfile.TemporaryDirectory() as d:
    test_dir = Path(d)

    admit_vitals_csv = test_dir / "admit_vitals.csv"
    admit_vitals_csv.write_text(ADMIT_VITALS_CSV.strip())

    admit_vitals_parquet = test_dir / "admit_vitals.parquet"
    df = pl.read_csv(admit_vitals_csv)

    old_shape = df.shape
    assert old_shape[0] > 0, "Should have some rows"

    columns = list(df.columns)

    df.write_parquet(admit_vitals_parquet, use_pyarrow=True)
    assert pl.read_parquet(admit_vitals_parquet).shape == old_shape, "Shapes should be the same after writing and reading parquet."

    df = pl.scan_parquet(admit_vitals_parquet)
    assert df.select(pl.len()).collect().item() == old_shape[0], "Should have the same number of rows after select."
    assert df.collect().shape == old_shape, "Shapes should be the same after scanning the parquet file."

    df = pl.scan_parquet(admit_vitals_parquet, row_index_name="idx")
    assert df.select(pl.len()).collect().item() == old_shape[0], "WITH ROW INDEX: Should have the same number of rows after select."
    assert df.collect().shape[0] == old_shape[0], "WITH ROW INDEX: Shapes should be the same after scanning the parquet file."
    assert df.collect().shape[1] == old_shape[1] + 1, "WITH ROW INDEX: Shapes should be the same after scanning the parquet file."

    df = pl.scan_parquet(admit_vitals_parquet, row_index_name="idx")
    df = df.select(list(df.columns))
    assert df.select(pl.len()).collect().item() == old_shape[0], "WITH ROW INDEX AND SELECT: Should have the same number of rows after select."
    assert df.collect().shape[0] == old_shape[0], "WITH ROW INDEX AND SELECT: Shapes should be the same after scanning the parquet file."
    assert df.collect().shape[1] == old_shape[1] + 1, "WITH ROW INDEX AND SELECT: Shapes should be the same after scanning the parquet file."

```

**Comment by mmcdermott** [comment]
It is unfortunate, as I'm trying to use the row index to allow me to efficiently chunk a parquet file into groups of rows to shard a file on disk to enable more efficient parallelism (for some reason this really seems to help in some cases despite the internal row-groups), and without this I've needed to add `df = df.scan_parquet(fp).with_columns((pl.lit(1).cumsum() - 1).alias('row_index'))` which I'm not sure will end up being efficient in comparison to a recognized integer index in practice. Though if all you need is a unique ID @mathewf2 it may work for you.

**Comment by mmcdermott** [comment]
Also the issue also occurs (at least the one that manifests with my example) if you manually call `.with_row_index` after the `scan_parquet`

**Comment by cmdlineluser** [comment]
@mmcdermott I can reproduce that.

```python
import tempfile
import polars as pl
from pathlib import Path

data = b"""
A,B
1,2
4,5
""".strip()

with tempfile.TemporaryDirectory() as d:
    test_dir = Path(d)
    filename = test_dir / "polars.parquet"
    pl.read_csv(data).write_parquet(filename)

    df = pl.scan_parquet(filename).with_row_index()

    print(df.select(pl.len()).collect()) # 2 

    print(df.select(pl.all()).select(pl.len()).collect()) # 0 - ???
```

```python
# shape: (1, 1)
# ┌─────┐
# │ len │
# │ --- │
# │ u32 │
# ╞═════╡
# │ 2   │
# └─────┘
# shape: (1, 1)
# ┌─────┐
# │ len │
# │ --- │
# │ u32 │
# ╞═════╡
# │ 0   │
# └─────┘
```

**Comment by mathewf2** [comment]
> It is unfortunate, as I'm trying to use the row index to allow me to efficiently chunk a parquet file into groups of rows to shard a file on disk to enable more efficient parallelism (for some reason this really seems to help in some cases despite the internal row-groups), and without this I've needed to add `df = df.scan_parquet(fp).with_columns((pl.lit(1).cumsum() - 1).alias('row_index'))` which I'm not sure will end up being efficient in comparison to a recognized integer index in practice. Though if all you need is a unique ID @mathewf2 it may work for you.

Thanks for the suggestion. We ended up foregoing polars for this and a few other reasons. It's really too bad, we just needed to generate a unique idx for each row lazily. This suggested alternative is still a lazy id generation that is streamable?
