### ISSUE TITLE
Deserializing dataframes using bincode panics

### ISSUE THREAD

**Issue by nmandery** [pola-rs/polars#1575]
#### Are you using Python or Rust?

Rust 1.55

#### Which feature gates did you use?

```toml
[dependencies.polars-core]
version = "0.16.0"
features = ["serde", "dtype-u64"]
```

#### What version of polars are you using?

0.16.0 and a current master (6727f25022f6ad707c4edf63faa604ccc0a0dc89)

#### What operating system are you using polars on?

Ubuntu 20.04.3 LTS

Linux amsel 5.8.0-59-generic #66~20.04.1-Ubuntu SMP Thu Jun 17 11:14:10 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux

#### Describe your bug.

Deserialization of a dataframe using bincode panics while deserializing a series is fine. Deserialization of single series not being part of a dataframe works. I also saw bincode is already being used for Series in #1119.

I am not sure if the bug is to be found in `polars` or `bincode`. Maybe its worth noting that using `serde_cbor` works fine. 

#### What are the steps to reproduce the behavior?

I first observed the issue with the released `polars` version 0.16.0 when deserializing a dataframe as a part of a larger struct. I am currently not able to share this code here, but the panic was this:

```
thread 'tokio-runtime-worker' panicked at 'called `Result::unwrap()` on an `Err` value: Custom("invalid type: string \"name\", expected a borrowed string")', /home/nico/.cargo/registry/src/github.com-1ecc6299db9ec823/polars-core-0.16.0/src/serde/series.rs:76:54
```

Not exactly the same error, but an error pointing to the same location can be reproduced on the master branch using the test I added in this commit: https://github.com/nmandery/polars/commit/0e2436b62eee38aad47ea9dfd7f77fe784ba02e7

I ran this test from within the `polars-core` directory using

```
cargo test --features="serde,serde_json,bincode" serde::test::test_serde
```

It produces this output/panic:

```
running 4 tests
test serde::test::test_serde ... ok
test serde::test::test_serde_bincode ... ok
test serde::test::test_serde_df ... ok
test serde::test::test_serde_df_bincode ... FAILED

failures:

---- serde::test::test_serde_df_bincode stdout ----
thread 'serde::test::test_serde_df_bincode' panicked at 'called `Result::unwrap()` on an `Err` value: Io(Custom { kind: UnexpectedEof, error: "" })', polars/polars-core/src/serde/series.rs:79:54
stack backtrace:
   0: rust_begin_unwind
             at /rustc/c8dfcfe046a7680554bf4eb612bad840e7631c4b/library/std/src/panicking.rs:515:5
   1: core::panicking::panic_fmt
             at /rustc/c8dfcfe046a7680554bf4eb612bad840e7631c4b/library/core/src/panicking.rs:92:14
   2: core::result::unwrap_failed
             at /rustc/c8dfcfe046a7680554bf4eb612bad840e7631c4b/library/core/src/result.rs:1599:5
   3: core::result::Result<T,E>::unwrap
             at /rustc/c8dfcfe046a7680554bf4eb612bad840e7631c4b/library/core/src/result.rs:1281:23
   4: <polars_core::serde::series::<impl serde::de::Deserialize for polars_core::series::Series>::deserialize::SeriesVisitor as serde::de::Visitor>::visit_map
             at ./src/serde/series.rs:79:39
   5: <&mut bincode::de::Deserializer<R,O> as serde::de::Deserializer>::deserialize_map
             at /home/nico/.cargo/registry/src/github.com-1ecc6299db9ec823/bincode-1.3.3/src/de/mod.rs:396:9
   6: polars_core::serde::series::<impl serde::de::Deserialize for polars_core::series::Series>::deserialize
             at ./src/serde/series.rs:176:9
   7: <core::marker::PhantomData<T> as serde::de::DeserializeSeed>::deserialize
             at /home/nico/.cargo/registry/src/github.com-1ecc6299db9ec823/serde-1.0.130/src/de/mod.rs:785:9
   8: <<&mut bincode::de::Deserializer<R,O> as serde::de::Deserializer>::deserialize_tuple::Access<R,O> as serde::de::SeqAccess>::next_element_seed
             at /home/nico/.cargo/registry/src/github.com-1ecc6299db9ec823/bincode-1.3.3/src/de/mod.rs:314:25
   9: serde::de::SeqAccess::next_element
             at /home/nico/.cargo/registry/src/github.com-1ecc6299db9ec823/serde-1.0.130/src/de/mod.rs:1707:9
  10: <serde::de::impls::<impl serde::de::Deserialize for alloc::vec::Vec<T>>::deserialize::VecVisitor<T> as serde::de::Visitor>::visit_seq
             at /home/nico/.cargo/registry/src/github.com-1ecc6299db9ec823/serde-1.0.130/src/de/impls.rs:928:46
  11: <&mut bincode::de::Deserializer<R,O> as serde::de::Deserializer>::deserialize_tuple
             at /home/nico/.cargo/registry/src/github.com-1ecc6299db9ec823/bincode-1.3.3/src/de/mod.rs:326:9
  12: <&mut bincode::de::Deserializer<R,O> as serde::de::Deserializer>::deserialize_seq
             at /home/nico/.cargo/registry/src/github.com-1ecc6299db9ec823/bincode-1.3.3/src/de/mod.rs:350:9
  13: serde::de::impls::<impl serde::de::Deserialize for alloc::vec::Vec<T>>::deserialize
             at /home/nico/.cargo/registry/src/github.com-1ecc6299db9ec823/serde-1.0.130/src/de/impls.rs:939:9
  14: <core::marker::PhantomData<T> as serde::de::DeserializeSeed>::deserialize
             at /home/nico/.cargo/registry/src/github.com-1ecc6299db9ec823/serde-1.0.130/src/de/mod.rs:785:9
  15: <<&mut bincode::de::Deserializer<R,O> as serde::de::Deserializer>::deserialize_map::Access<R,O> as serde::de::MapAccess>::next_value_seed
             at /home/nico/.cargo/registry/src/github.com-1ecc6299db9ec823/bincode-1.3.3/src/de/mod.rs:385:29
  16: serde::de::MapAccess::next_value
             at /home/nico/.cargo/registry/src/github.com-1ecc6299db9ec823/serde-1.0.130/src/de/mod.rs:1846:9
  17: <polars_core::serde::series::<impl serde::de::Deserialize for polars_core::series::Series>::deserialize::SeriesVisitor as serde::de::Visitor>::visit_map
             at ./src/serde/series.rs:166:51
  18: <&mut bincode::de::Deserializer<R,O> as serde::de::Deserializer>::deserialize_map
             at /home/nico/.cargo/registry/src/github.com-1ecc6299db9ec823/bincode-1.3.3/src/de/mod.rs:396:9
  19: polars_core::serde::series::<impl serde::de::Deserialize for polars_core::series::Series>::deserialize
             at ./src/serde/series.rs:176:9
  20: <core::marker::PhantomData<T> as serde::de::DeserializeSeed>::deserialize
             at /home/nico/.cargo/registry/src/github.com-1ecc6299db9ec823/serde-1.0.130/src/de/mod.rs:785:9
  21: <<&mut bincode::de::Deserializer<R,O> as serde::de::Deserializer>::deserialize_tuple::Access<R,O> as serde::de::SeqAccess>::next_element_seed
             at /home/nico/.cargo/registry/src/github.com-1ecc6299db9ec823/bincode-1.3.3/src/de/mod.rs:314:25
  22: serde::de::SeqAccess::next_element
             at /home/nico/.cargo/registry/src/github.com-1ecc6299db9ec823/serde-1.0.130/src/de/mod.rs:1707:9
  23: <serde::de::impls::<impl serde::de::Deserialize for alloc::vec::Vec<T>>::deserialize::VecVisitor<T> as serde::de::Visitor>::visit_seq
             at /home/nico/.cargo/registry/src/github.com-1ecc6299db9ec823/serde-1.0.130/src/de/impls.rs:928:46
  24: <&mut bincode::de::Deserializer<R,O> as serde::de::Deserializer>::deserialize_tuple
             at /home/nico/.cargo/registry/src/github.com-1ecc6299db9ec823/bincode-1.3.3/src/de/mod.rs:326:9
  25: <&mut bincode::de::Deserializer<R,O> as serde::de::Deserializer>::deserialize_seq
             at /home/nico/.cargo/registry/src/github.com-1ecc6299db9ec823/bincode-1.3.3/src/de/mod.rs:350:9
  26: serde::de::impls::<impl serde::de::Deserialize for alloc::vec::Vec<T>>::deserialize
             at /home/nico/.cargo/registry/src/github.com-1ecc6299db9ec823/serde-1.0.130/src/de/impls.rs:939:9
  27: <core::marker::PhantomData<T> as serde::de::DeserializeSeed>::deserialize
             at /home/nico/.cargo/registry/src/github.com-1ecc6299db9ec823/serde-1.0.130/src/de/mod.rs:785:9
  28: <<&mut bincode::de::Deserializer<R,O> as serde::de::Deserializer>::deserialize_tuple::Access<R,O> as serde::de::SeqAccess>::next_element_seed
             at /home/nico/.cargo/registry/src/github.com-1ecc6299db9ec823/bincode-1.3.3/src/de/mod.rs:314:25
  29: serde::de::SeqAccess::next_element
             at /home/nico/.cargo/registry/src/github.com-1ecc6299db9ec823/serde-1.0.130/src/de/mod.rs:1707:9
  30: <polars_core::frame::_::<impl serde::de::Deserialize for polars_core::frame::DataFrame>::deserialize::__Visitor as serde::de::Visitor>::visit_seq
             at ./src/frame/mod.rs:51:49
  31: <&mut bincode::de::Deserializer<R,O> as serde::de::Deserializer>::deserialize_tuple
             at /home/nico/.cargo/registry/src/github.com-1ecc6299db9ec823/bincode-1.3.3/src/de/mod.rs:326:9
  32: <&mut bincode::de::Deserializer<R,O> as serde::de::Deserializer>::deserialize_struct
             at /home/nico/.cargo/registry/src/github.com-1ecc6299db9ec823/bincode-1.3.3/src/de/mod.rs:411:9
  33: polars_core::frame::_::<impl serde::de::Deserialize for polars_core::frame::DataFrame>::deserialize
             at ./src/frame/mod.rs:51:49
  34: <core::marker::PhantomData<T> as serde::de::DeserializeSeed>::deserialize
             at /home/nico/.cargo/registry/src/github.com-1ecc6299db9ec823/serde-1.0.130/src/de/mod.rs:785:9
  35: bincode::internal::deserialize_seed
             at /home/nico/.cargo/registry/src/github.com-1ecc6299db9ec823/bincode-1.3.3/src/internal.rs:118:15
  36: bincode::internal::deserialize
             at /home/nico/.cargo/registry/src/github.com-1ecc6299db9ec823/bincode-1.3.3/src/internal.rs:106:5
  37: bincode::config::Options::deserialize
             at /home/nico/.cargo/registry/src/github.com-1ecc6299db9ec823/bincode-1.3.3/src/config/mod.rs:200:9
  38: bincode::deserialize
             at /home/nico/.cargo/registry/src/github.com-1ecc6299db9ec823/bincode-1.3.3/src/lib.rs:181:5
  39: polars_core::serde::test::test_serde_df_bincode
             at ./src/serde/mod.rs:136:19
  40: polars_core::serde::test::test_serde_df_bincode::{{closure}}
             at ./src/serde/mod.rs:128:5
  41: core::ops::function::FnOnce::call_once
             at /rustc/c8dfcfe046a7680554bf4eb612bad840e7631c4b/library/core/src/ops/function.rs:227:5
  42: core::ops::function::FnOnce::call_once
             at /rustc/c8dfcfe046a7680554bf4eb612bad840e7631c4b/library/core/src/ops/function.rs:227:5
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.


failures:
    serde::test::test_serde_df_bincode

test result: FAILED. 3 passed; 1 failed; 0 ignored; 0 measured; 115 filtered out; finished in 0.07s
```

BTW: Thanks for providing this library!

**Comment by ritchie46** [comment]
Thanks for the issue report. Strange that `cbor` works fine. Could you isolate a minumal working example for me? A DataFrame with 10 rows, something like that.

**Comment by nmandery** [comment]
Sure, this adaptation of the original json-testcase will reproduce the issue: https://github.com/nmandery/polars/commit/0e2436b62eee38aad47ea9dfd7f77fe784ba02e7#diff-8e3cc4a39b1419f17e9218bb094910d988ba137f8c0d900a92215da952a935e0R128

I could not exactly reproduce the original `invalid type: string \"name\", expected a borrowed string` panic outside of the larger codebase so far, only the `UnexpectedEof`-panic of the testcase. I will give it a second try later.
