### ISSUE TITLE
`pl.read_parquet` does not identify `io.IOBase` as a byte stream

### ISSUE THREAD

**Issue by AnH0ang** [pola-rs/polars#15760]
### Checks

- [X] I have checked that this issue has not already been reported.
- [X] I have confirmed this bug exists on the [latest version](https://pypi.org/project/polars/) of Polars.

### Reproducible example

```python
import fsspec
import polars as pl

# create example dataframe 
pl.DataFrame({"a": [1, 2, 3]}).write_parquet("test.parquet")

# load dataframe with fsspec
with fsspec.open("test.parquet") as fs:
    pl.read_parquet(fs)
```

### Log output

```shell
Traceback (most recent call last):
  File "/Users/anhoang/Git/numforecast/test.py", line 7, in <module>
    pl.read_parquet(fs)
  File "/Users/anhoang/Git/numforecast/.venv/lib/python3.11/site-packages/polars/_utils/deprecation.py", line 134, in wrapper
    return function(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/anhoang/Git/numforecast/.venv/lib/python3.11/site-packages/polars/_utils/deprecation.py", line 134, in wrapper
    return function(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/anhoang/Git/numforecast/.venv/lib/python3.11/site-packages/polars/io/parquet/functions.py", line 180, in read_parquet
    lf = scan_parquet(
         ^^^^^^^^^^^^^
  File "/Users/anhoang/Git/numforecast/.venv/lib/python3.11/site-packages/polars/_utils/deprecation.py", line 134, in wrapper
    return function(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/anhoang/Git/numforecast/.venv/lib/python3.11/site-packages/polars/_utils/deprecation.py", line 134, in wrapper
    return function(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/anhoang/Git/numforecast/.venv/lib/python3.11/site-packages/polars/io/parquet/functions.py", line 394, in scan_parquet
    return _scan_parquet_impl(
           ^^^^^^^^^^^^^^^^^^^
  File "/Users/anhoang/Git/numforecast/.venv/lib/python3.11/site-packages/polars/io/parquet/functions.py", line 454, in _scan_parquet_impl
    pylf = PyLazyFrame.new_from_parquet(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: argument 'paths': 'bytes' object cannot be converted to 'PyString'
```

### Issue description

The error occurs because `fsspec.open("test.parquet")` returns an object of type `io.IOBase`. In `pl.read_parquet`, the function checks if the input is a path-like object or a byte stream by checking if the object is an instance of `io.BufferedIOBase` and `io.RawIOBase`, which `io.IOBase` is not.

 https://github.com/pola-rs/polars/blob/96e1f012fcad74d4671fdd1be6f95ba3b7dab22f/py-polars/polars/io/parquet/functions.py#L166

### Expected behavior

`pl.read_parquet` should run without errors

### Installed versions

<details>

```
--------Version info---------
Polars:               0.20.21
Index type:           UInt32
Platform:             macOS-14.4.1-arm64-arm-64bit
Python:               3.11.6 (main, Oct  2 2023, 20:31:07) [Clang 16.0.3 ]

----Optional dependencies----
adbc_driver_manager:  <not installed>
cloudpickle:          <not installed>
connectorx:           <not installed>
deltalake:            <not installed>
fastexcel:            <not installed>
fsspec:               2024.3.1
gevent:               <not installed>
hvplot:               <not installed>
matplotlib:           3.8.4
nest_asyncio:         1.6.0
numpy:                1.26.4
openpyxl:             <not installed>
pandas:               2.2.2
pyarrow:              15.0.2
pydantic:             2.7.0
pyiceberg:            <not installed>
pyxlsb:               <not installed>
sqlalchemy:           2.0.29
xlsx2csv:             <not installed>
xlsxwriter:           <not installed>
```

</details>

**Comment by AnH0ang** [comment]
I just saw that this was changed around back in issue #13218. @stinodego, do you know the reason for this error?

**Comment by stinodego** [comment]
Perhaps we can just use `IOBase` here.. will look into this.
