### ISSUE TITLE
PanicException using `qcut` with `include_breaks=True` and `.over`

### ISSUE THREAD

**Issue by mishavanbeek** [pola-rs/polars#15781]
### Checks

- [X] I have checked that this issue has not already been reported.
- [X] I have confirmed this bug exists on the [latest version](https://pypi.org/project/polars/) of Polars.

### Reproducible example

```python
import polars as pl

df = pl.DataFrame({
    "group": [1, 1, 2],
    "value": [1.0, 2.0, 3.0],
})

df.with_columns(pl.col("value").qcut([0.5], include_breaks=True).over("group"))
```

### Log output

```shell
thread '' panicked at crates/polars-core/src/chunked_array/logical/categorical/revmap.rs:103:42:
called `Option::unwrap()` on a `None` value
```

### Issue description

With `include_breaks=True`, `qcut` throws an error when used in a grouped fashion (with `over`).

If I add labels in the following way, then the issue seems to be resolved, but this raises another issue with randomly wrong output every now and then (https://github.com/pola-rs/polars/issues/15670). I.e. this works.
```python
df.with_columns(pl.col("value").qcut([0.5], labels=["1", "2"], include_breaks=True).over("group"))
```

### Expected behavior

I expected the output to look structurally the same as the ungrouped output, but with different numbers. I.e. the following works just fine:
```python
df.with_columns(pl.col("value").qcut([0.5], include_breaks=True))
```

### Installed versions

<details>

```
--------Version info---------
Polars:               0.20.21
Index type:           UInt32
Platform:             macOS-14.4-arm64-arm-64bit
Python:               3.11.6 (main, Dec 20 2023, 23:16:20) [Clang 15.0.0 (clang-1500.1.0.2.5)]

----Optional dependencies----
adbc_driver_manager:  <not installed>
cloudpickle:          <not installed>
connectorx:           <not installed>
deltalake:            <not installed>
fastexcel:            <not installed>
fsspec:               2024.3.1
gevent:               <not installed>
hvplot:               <not installed>
matplotlib:           <not installed>
nest_asyncio:         1.6.0
numpy:                1.26.4
openpyxl:             <not installed>
pandas:               2.2.2
pyarrow:              15.0.2
pydantic:             2.7.0
pyiceberg:            <not installed>
pyxlsb:               <not installed>
sqlalchemy:           <not installed>
xlsx2csv:             <not installed>
xlsxwriter:           <not installed>
```

</details>

**Comment by cmdlineluser** [comment]
Trying a regular `.group_by` I am getting random PanicExceptions:

```python
import polars as pl

df = pl.DataFrame({
    "group": [1, 1, 2],
    "value": [1.0, 2.0, 3.0],
})

for _ in range(10):
    print(
        df.group_by("group")
          .agg(
              pl.col("value").qcut([0.5], include_breaks=True)
          )
    )
```

```python
shape: (2, 2)
┌───────┬───────────────────────────────────┐
│ group ┆ value                             │
│ ---   ┆ ---                               │
│ i64   ┆ list[struct[2]]                   │
╞═══════╪═══════════════════════════════════╡
│ 1     ┆ [{1.5,"(-inf, 1.5]"}, {inf,"(1.5… │
│ 2     ┆ [{3.0,"(-inf, 1.5]"}]             │
└───────┴───────────────────────────────────┘
thread '<unnamed>' panicked at polars/crates/polars-arrow/src/array/binview/mod.rs:256:9:
assertion failed: i < self.len()
```

**Comment by mishavanbeek** [comment]
> return a regular str

Thank you! This is a great workaround, it's 10x slower but still much faster than the numpy alternative I coded up.

**Comment by cmdlineluser** [comment]
Just to add to this, `cut` works with `.over()`

```python
df.with_columns(
    pl.col("value").cut([-1, 1], include_breaks=True)
      .over("group")
)

# shape: (3, 2)
# ┌───────┬──────────────────┐
# │ group ┆ value            │
# │ ---   ┆ ---              │
# │ i64   ┆ struct[2]        │
# ╞═══════╪══════════════════╡
# │ 1     ┆ {1.0,"(-1, 1]"}  │
# │ 1     ┆ {inf,"(1, inf]"} │
# │ 2     ┆ {inf,"(1, inf]"} │
# └───────┴──────────────────┘
```

But in `.group_by` it will randomly generate PanicExceptions.

**Comment by mcrumiller** [comment]
`cut` still fails:

```python
import polars as pl
from polars import col

pl.enable_string_cache()

df = pl.DataFrame({
    "group": [1, 2],
    "value": [1, 2],
})

out = df.with_columns(col("value").cut([1.0], include_breaks=True).over("group"))
print(out.head(1))  # works
print(out)          # pyo3_runtime.PanicException: called `Option::unwrap()` on a `None` value
```
Note that generating `out` actually works, but fails once the 2nd element is accessed.
