### ISSUE TITLE
Trouble reading parquet files via SFTP

### ISSUE THREAD

**Issue by benmayersohn** [pola-rs/polars#15811]
### Checks

- [X] I have checked that this issue has not already been reported.
- [X] I have confirmed this bug exists on the [latest version](https://pypi.org/project/polars/) of Polars.

### Reproducible example

```python
import polars as pl
import os

a = pl.DataFrame({'a': [1, 2, 3], 'b': [4, 5, 6]})
a.write_parquet('example.parquet')
username = os.environ['USER']
currdir = os.getcwd()
url = f'sftp://{username}@localhost/{currdir[1:]}/example.parquet'
df = pl.scan_parquet(url)
```

### Log output

```shell
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/ben/test_venv/lib/python3.10/site-packages/polars/_utils/deprecation.py", line 134, in wrapper
    return function(*args, **kwargs)
  File "/home/ben/test_venv/lib/python3.10/site-packages/polars/_utils/deprecation.py", line 134, in wrapper
    return function(*args, **kwargs)
  File "/home/ben/test_venv/lib/python3.10/site-packages/polars/io/parquet/functions.py", line 394, in scan_parquet
    return _scan_parquet_impl(
  File "/home/ben/test_venv/lib/python3.10/site-packages/polars/io/parquet/functions.py", line 441, in _scan_parquet_impl
    scan = _scan_parquet_fsspec(source, storage_options)  # type: ignore[arg-type]
  File "/home/ben/test_venv/lib/python3.10/site-packages/polars/io/parquet/anonymous_scan.py", line 21, in _scan_parquet_fsspec
    schema = polars.io.parquet.read_parquet_schema(data)
  File "/home/ben/test_venv/lib/python3.10/site-packages/polars/io/parquet/functions.py", line 284, in read_parquet_schema
    return _read_parquet_schema(source)
polars.exceptions.ComputeError: parquet: File out of specification: underlying IO error: 'NoneType' object cannot be interpreted as an integer
```

### Issue description

This also fails with `pl.read_parquet` when `use_pyarrow` is `False` (However, it works when `use_pyarrow=True`)

### Expected behavior

Return a `LazyFrame` with `scan_parquet` or a `DataFrame` with `read_parquet`

### Installed versions

<details>

```
--------Version info---------
Polars:               0.20.21
Index type:           UInt32
Platform:             Linux-5.4.0-170-generic-x86_64-with-glibc2.31
Python:               3.10.8 (main, Nov 24 2022, 14:13:03) [GCC 11.2.0]

----Optional dependencies----
adbc_driver_manager:  <not installed>
cloudpickle:          <not installed>
connectorx:           <not installed>
deltalake:            <not installed>
fastexcel:            <not installed>
fsspec:               2024.3.1
gevent:               <not installed>
hvplot:               <not installed>
matplotlib:           <not installed>
nest_asyncio:         <not installed>
numpy:                1.26.4
openpyxl:             <not installed>
pandas:               <not installed>
pyarrow:              16.0.0
pydantic:             <not installed>
pyiceberg:            <not installed>
pyxlsb:               <not installed>
sqlalchemy:           <not installed>
xlsx2csv:             <not installed>
xlsxwriter:           <not installed>
```

</details>

**Comment by ritchie46** [comment]
We don't support the sftp protocol. You could make a feature request upstream at object-store.

**Comment by ritchie46** [comment]
Tag it as not a bug, as we never supported this.

**Comment by benmayersohn** [comment]
Ah I didn't realize that - sorry! I'll make a feature request
