### ISSUE TITLE
.with_columns unsupported python additional functions

### ISSUE THREAD

**Issue by clsteam** [pola-rs/polars#15964]
### Checks

- [X] I have checked that this issue has not already been reported.
- [X] I have confirmed this bug exists on the [latest version](https://pypi.org/project/polars/) of Polars.

### Reproducible example

```python
import polars as pl


def mode_method(genotype_list: list[str], locus: str,
                  increasing_chance: list[str] = None) -> str:
    if increasing_chance is None or len(genotype_list) == 1:
        return genotype_list.pop()
    if extra := set(genotype_list) - set(increasing_chance):
        for gt in extra:
            if gt[::-1] not in increasing_chance:
                raise ValueError("error")
            genotype_list[genotype_list.index(gt)] = gt[::-1]
    return max(genotype_list, key=increasing_chance.index)


chance_dict = {"locus1": ["TC", "TT", "CC"], "locus2": ["TC", "TT", "CC"], "locus3": ["CC", "TC", "TT"]}
df = pl.DataFrame(
    {
        "locus": ["locus1", "locus2", "locus3", "locus4", "locus5"],
        "s1": [["CT", "TT"], ["TT"], ["CC", "CT"], ["TC", "CC"], ["TT"]],
        "s2": [["TT"], ["CC", "TC"], ["TC"], ["CC"], ["CT"]],
        "s3": [["TC"], ["TT", "CC"], ["TC"], ["CC"], ["TT", "CT"]],
    }
)

samples = ["s1", "s2", "s3"]
_df = df
# run success
for col in samples:
    df = df.with_columns(
        pl.struct("locus", col).map_elements(
            lambda dt: mode_method(dt[col], dt["locus"], chance_dict.get(dt["locus"])),
            return_dtype=pl.String
        ).alias(col)
    )

# run failed
_df.with_columns(
    *[
        pl.struct("locus", col).map_elements(
            lambda dt: mode_method(dt[col], dt["locus"], chance_dict.get(dt["locus"])),
            return_dtype=pl.String
        ).alias(col)
        for col in samples
    ]
)

# run success
_df.with_columns(
    *[
        pl.struct("locus", col).map_elements(
            lambda dt: chance_dict.get(dt["locus"]),
            return_dtype=pl.String
        ).alias(col)
        for col in samples
    ]
)
```

### Log output

```shell
thread 'polars-1' panicked at py-polars/src/map/series.rs:213:19:
python function failed KeyError: 's3'
--- PyO3 is resuming a panic after fetching a PanicException from Python. ---
Python stack trace below:
thread 'polars-0' panicked at py-polars/src/map/series.rs:213:19:
python function failed KeyError: 's3'
--- PyO3 is resuming a panic after fetching a PanicException from Python. ---
Python stack trace below:
---------------------------------------------------------------------------
PanicException                            Traceback (most recent call last)
File ~/miniconda3/envs/py311/lib/python3.11/site-packages/polars/expr/expr.py:4107, in Expr._map_batches_wrapper.__call__(self, *args, **kwargs)
   4106 def __call__(self, *args: Any, **kwargs: Any) -> Any:
-> 4107     result = self.function(*args, **kwargs)
   4108     if _check_for_numpy(result) and isinstance(result, np.ndarray):
   4109         result = pl.Series(result, dtype=self.return_dtype)

File ~/miniconda3/envs/py311/lib/python3.11/site-packages/polars/expr/expr.py:4446, in Expr.map_elements.<locals>.wrap_f(x)
   4444 with warnings.catch_warnings():
   4445     warnings.simplefilter("ignore", PolarsInefficientMapWarning)
-> 4446     return x.map_elements(
   4447         function, return_dtype=return_dtype, skip_nulls=skip_nulls
   4448     )

File ~/miniconda3/envs/py311/lib/python3.11/site-packages/polars/series/series.py:5326, in Series.map_elements(self, function, return_dtype, skip_nulls)
   5322     pl_return_dtype = py_type_to_dtype(return_dtype)
   5324 warn_on_inefficient_map(function, columns=[self.name], map_target="series")
   5325 return self._from_pyseries(
-> 5326     self._s.apply_lambda(function, pl_return_dtype, skip_nulls)
   5327 )

PanicException: python function failed KeyError: 's3'
```

### Issue description

Currently in use `.with_columns` This is the python function of the python function.

### Expected behavior

# run success
for col in samples:
    df = df.with_columns(
        pl.struct("locus", col).map_elements(
            lambda dt: mode_method(dt[col], dt["locus"], chance_dict.get(dt["locus"])),
            return_dtype=pl.String
        ).alias(col)
    )

### Installed versions

<details>

```
--------Version info---------
Polars:               0.20.23
Index type:           UInt32
Platform:             Linux-3.10.0-957.21.3.el7.x86_64-x86_64-with-glibc2.17
Python:               3.11.7 (main, Dec 15 2023, 18:12:31) [GCC 11.2.0]

----Optional dependencies----
adbc_driver_manager:  <not installed>
cloudpickle:          <not installed>
connectorx:           <not installed>
deltalake:            <not installed>
fastexcel:            <not installed>
fsspec:               2024.3.1
gevent:               <not installed>
hvplot:               <not installed>
matplotlib:           3.8.2
nest_asyncio:         <not installed>
numpy:                1.26.3
openpyxl:             3.1.2
pandas:               2.1.4
pyarrow:              15.0.0
pydantic:             <not installed>
pyiceberg:            <not installed>
pyxlsb:               <not installed>
sqlalchemy:           2.0.25
xlsx2csv:             <not installed>
xlsxwriter:           <not installed>
```

</details>

**Comment by cmdlineluser** [comment]
It's more of a general Python issue/gotcha:

- https://docs.python.org/3/faq/programming.html#why-do-lambdas-defined-in-a-loop-with-different-values-all-return-the-same-result

You can pass `col` in as a keyword arg in order to bind its value at "define time" as opposed to "call time".

```python
lambda dt, col=col
```

```python
_df.with_columns(
    *[
        pl.struct("locus", col).map_elements(
            lambda dt, col=col: mode_method(dt[col], dt["locus"], chance_dict.get(dt["locus"])),
            return_dtype=pl.String
        ).alias(col)
        for col in samples
    ]
)

# shape: (5, 4)
# ┌────────┬─────┬─────┬─────┐
# │ locus  ┆ s1  ┆ s2  ┆ s3  │
# │ ---    ┆ --- ┆ --- ┆ --- │
# │ str    ┆ str ┆ str ┆ str │
# ╞════════╪═════╪═════╪═════╡
# │ locus1 ┆ TT  ┆ TT  ┆ TC  │
# │ locus2 ┆ TT  ┆ CC  ┆ CC  │
# │ locus3 ┆ TC  ┆ TC  ┆ TC  │
# │ locus4 ┆ CC  ┆ CC  ┆ CC  │
# │ locus5 ┆ TT  ┆ CT  ┆ CT  │
# └────────┴─────┴─────┴─────┘
```

**Comment by clsteam** [comment]
thats great！ thanks !!!!
