### ISSUE TITLE
Confusing error during multi-column join with 1:1 validation

### ISSUE THREAD

**Issue by maitreyakv** [pola-rs/polars#15998]
### Checks

- [X] I have checked that this issue has not already been reported.
- [X] I have confirmed this bug exists on the [latest version](https://pypi.org/project/polars/) of Polars.

### Reproducible example

```python
df_1 = pl.DataFrame({"a": [1, 2, 3], "b": ["A", "B", "C"]})
df_2 = pl.DataFrame({"a": [1, 2], "b": ["A", "B"]})
df_1.join(df_2, left_on=["a", "b"], right_on=["a", "b"], how="inner", validate="1:1")
```

### Log output

```shell
join parallel: true
INNER join dataframes finished
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/maitreya/.pyenv/versions/mdb-dev/lib/python3.11/site-packages/polars/dataframe/frame.py", line 6159, in join
    .collect(_eager=True)
     ^^^^^^^^^^^^^^^^^^^^
  File "/Users/maitreya/.pyenv/versions/mdb-dev/lib/python3.11/site-packages/polars/lazyframe/frame.py", line 1810, in collect
    return wrap_df(ldf.collect())
                   ^^^^^^^^^^^^^
polars.exceptions.InvalidOperationError: `n_unique` operation not supported for dtype `binary[offset]`
```

### Issue description

If I remove the validation argument, the error doesn't occur.

### Expected behavior

Expected output (generated by running the example without `validate` argument):
```
join parallel: true
INNER join dataframes finished
shape: (2, 2)
┌─────┬─────┐
│ a   ┆ b   │
│ --- ┆ --- │
│ i64 ┆ str │
╞═════╪═════╡
│ 1   ┆ A   │
│ 2   ┆ B   │
└─────┴─────┘
```

### Installed versions

<details>

```
--------Version info---------
Polars:               0.20.23
Index type:           UInt32
Platform:             macOS-13.3.1-arm64-arm-64bit
Python:               3.11.4 (main, Nov 14 2023, 11:23:45) [Clang 14.0.3 (clang-1403.0.22.14.1)]

----Optional dependencies----
adbc_driver_manager:  <not installed>
cloudpickle:          3.0.0
connectorx:           <not installed>
deltalake:            <not installed>
fastexcel:            <not installed>
fsspec:               2024.3.1
gevent:               <not installed>
hvplot:               <not installed>
matplotlib:           3.8.4
nest_asyncio:         1.6.0
numpy:                1.26.4
openpyxl:             3.1.2
pandas:               2.2.2
pyarrow:              15.0.2
pydantic:             2.7.1
pyiceberg:            <not installed>
pyxlsb:               1.0.10
sqlalchemy:           2.0.29
xlsx2csv:             <not installed>
xlsxwriter:           3.2.0
```

</details>

**Comment by maitreyakv** [comment]
@DeflateAwning Cool, thanks for the context. I'll maybe mark this as duplicate then?

**Comment by maitreyakv** [comment]
Closing this a duplicate of #15829, will wait for the next release.

**Comment by maitreyakv** [comment]
[Release v0.20.24](https://github.com/pola-rs/polars/releases/tag/py-0.20.24) fixes this, thanks all!
