### ISSUE TITLE
Can not sink df after scan_ipc

### ISSUE THREAD

**Issue by s-b90** [pola-rs/polars#16134]
### Checks

- [X] I have checked that this issue has not already been reported.
- [X] I have confirmed this bug exists on the [latest version](https://pypi.org/project/polars/) of Polars.

### Reproducible example

```python
import polars as pl

pl.DataFrame({'col': [1, 2]}).write_ipc('test.ipc')
ldf = pl.scan_ipc('test.ipc')
ldf.sink_ipc('test2.ipc')
```

### Log output

```shell
Traceback (most recent call last):
  File "test.py", line 30, in <module>
    ldf.sink_ipc('test2.ipc')
  File "venv/lib/python3.11/site-packages/polars/_utils/unstable.py", line 59, in wrapper
    return function(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "venv/lib/python3.11/site-packages/polars/lazyframe/frame.py", line 2144, in sink_ipc
    return lf.sink_ipc(
           ^^^^^^^^^^^^
polars.exceptions.InvalidOperationError: sink_Ipc(IpcWriterOptions { compression: Some(ZSTD), maintain_order: true }) not yet supported in standard engine. Use 'collect().write_parquet()'
```

### Issue description

After scanning ipc you can not sink lazy frame with any sink_* function.

### Expected behavior

sink_* should work with lazy frames created with scan_ipc.
This is may be not implemented feature as error says, so pls add feature-request tag to this issue than.

### Installed versions

<details>

```
--------Version info---------
Polars:               0.20.25
Index type:           UInt32
Platform:             Linux-6.8.0-31-generic-x86_64-with-glibc2.39
Python:               3.11.9 (main, Apr 27 2024, 21:16:11) [GCC 13.2.0]

----Optional dependencies----
adbc_driver_manager:  <not installed>
cloudpickle:          <not installed>
connectorx:           <not installed>
deltalake:            <not installed>
fastexcel:            <not installed>
fsspec:               <not installed>
gevent:               <not installed>
hvplot:               <not installed>
matplotlib:           <not installed>
nest_asyncio:         1.6.0
numpy:                1.26.1
openpyxl:             <not installed>
pandas:               <not installed>
pyarrow:              <not installed>
pydantic:             <not installed>
pyiceberg:            <not installed>
pyxlsb:               <not installed>
sqlalchemy:           <not installed>
torch:                <not installed>
xlsx2csv:             <not installed>
xlsxwriter:           <not installed>
```

</details>

**Comment by ritchie46** [comment]
This is expected. See the error. `scan_ipc` isn't yet supported in the streaming engine.
