### ISSUE TITLE
Generalized ufuncs won't work in case where input sizes don't match

### ISSUE THREAD

**Issue by itamarst** [pola-rs/polars#16193]
### Checks

- [X] I have checked that this issue has not already been reported.
- [X] I have confirmed this bug exists on the [latest version](https://pypi.org/project/polars/) of Polars.

### Reproducible example

```python
import numpy as np
import polars as pl
from numba import guvectorize, float64


@guvectorize([(float64[:], float64[:], float64[:])], "(n),(m)->(m)")
def different_output_size(arr, arr2, result):
    total = arr.mean()
    for i in range(len(arr2)):
        result[i] = total


series = pl.Series([1.0], dtype=pl.Float64)
series2 = pl.Series([1.0] * 100_000, dtype=pl.Float64)
different_output_size(series, series2)
```

### Issue description

Polars assumes input and output array sizes for ufuncs are always the same. For generalized ufuncs (https://numpy.org/neps/nep-0020-gufunc-signature-enhancement.html) this is not always the case, as in the example code.

The reason Polars does this is an optimization: rather than relying on the ufunc to allocate memory, it allocates memory itself, which means it needs to know the size in advance.

Initially I thought this assumption about sizes could lead to memory corruption or garbage, but NumPy actually validates the inputs. So the result is just that this is sort of ufunc is unusable.

(This issue was originally part of #14811 but was split off).

### Expected behavior

This code should run. However, instead it hits a safety check that NumPy does:

```
Traceback (most recent call last):
  File "/home/itamarst/devel/polars/py-polars/example.py", line 15, in <module>
    different_output_size(series, series2)
  File "/home/itamarst/devel/polars/.venv/lib/python3.10/site-packages/numba/np/ufunc/gufunc.py", line 172, in __call__
    return self.ufunc(*args, **kwargs)
  File "/home/itamarst/devel/polars/py-polars/polars/series/series.py", line 1456, in __array_ufunc__
    series = f(lambda out: ufunc(*args, out=out, dtype=dtype_char, **kwargs))
  File "/home/itamarst/devel/polars/py-polars/polars/series/series.py", line 1456, in <lambda>
    series = f(lambda out: ufunc(*args, out=out, dtype=dtype_char, **kwargs))
ValueError: different_output_size: Output operand 0 has a mismatch in its core dimension 0, with gufunc signature (n),(m)->(m) (size 1 is different from 100000)
```

### Installed versions

Polars from git, May 13, 2024.

**Comment by itamarst** [comment]
I have code that fixes this, will submit PR once #16198 is merged.
