### ISSUE TITLE
Panic on creating nested Array with logical inner dtype with nulls

### ISSUE THREAD

**Issue by stinodego** [pola-rs/polars#16210]
### Checks

- [X] I have checked that this issue has not already been reported.
- [X] I have confirmed this bug exists on the [latest version](https://pypi.org/project/polars/) of Polars.

### Reproducible example

```python
import polars as pl

dtype = pl.Array(pl.Datetime, shape=(2, 2))
s = pl.Series([[None, None]], dtype=dtype)

print(s)
```

### Log output

```shell
thread '<unnamed>' panicked at crates/polars-arrow/src/array/list/mod.rs:82:61:
called `Result::unwrap()` on an `Err` value: ComputeError(ErrString("ListArray's child's DataType must match. However, the expected DataType is FixedSizeList(Field { name: \"item\", data_type: Int64, is_nullable: true, metadata: {} }, 2) while it got FixedSizeList(Field { name: \"item\", data_type: Timestamp(Microsecond, None), is_nullable: true, metadata: {} }, 2)."))
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
Traceback (most recent call last):
  File "/home/stijn/code/polars/py-polars/repro.py", line 4, in <module>
    s = pl.Series([[None, None]], dtype=dtype)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/stijn/code/polars/py-polars/polars/series/series.py", line 294, in __init__
    self._s = sequence_to_pyseries(
              ^^^^^^^^^^^^^^^^^^^^^
  File "/home/stijn/code/polars/py-polars/polars/_utils/construction/series.py", line 286, in sequence_to_pyseries
    pyseries = PySeries.new_series_list(name, pyseries_list, strict)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
pyo3_runtime.PanicException: called `Result::unwrap()` on an `Err` value: ComputeError(ErrString("ListArray's child's DataType must match. However, the expected DataType is FixedSizeList(Field { name: \"item\", data_type: Int64, is_nullable: true, metadata: {} }, 2) while it got FixedSizeList(Field { name: \"item\", data_type: Timestamp(Microsecond, None), is_nullable: true, metadata: {} }, 2)."))
```

### Issue description

It seems like the nulls in the nested array cause this panic. It thinks the first value has inner type Int64, while the second one has Timestamp.

### Expected behavior

A new Series should be created.

### Installed versions

main

**Comment by ritchie46** [comment]
Yes, we have the invariant that lists only use physical types. That invariant doesn't seem to be respected here.
