### ISSUE TITLE
read_json errors when parsing NaN

### ISSUE THREAD

**Issue by twoertwein** [pola-rs/polars#16245]
### Checks

- [X] I have checked that this issue has not already been reported.
- [X] I have confirmed this bug exists on the [latest version](https://pypi.org/project/polars/) of Polars.

### Reproducible example

```python
import json
from io import StringIO

import polars as pl

pl.read_json(StringIO(json.dumps([{"foo": float("nan")}])))
```

### Log output

```shell
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/twoertwein/miniforge3/lib/python3.10/site-packages/polars/io/json.py", line 94, in read_json
    pydf = PyDataFrame.read_json(
RuntimeError: BindingsError: "InternalError(TapeError) at character 9 ('N')"
```

### Issue description

read_json errors when parsing NaNs.

### Expected behavior

read_json can parse NaNs.

### Installed versions

<details>

```
--------Version info---------
Polars:               0.20.23
Index type:           UInt32
Platform:             macOS-14.4.1-arm64-arm-64bit
Python:               3.10.14 | packaged by conda-forge | (main, Mar 20 2024, 12:51:49) [Clang 16.0.6 ]

----Optional dependencies----
adbc_driver_manager:  <not installed>
cloudpickle:          <not installed>
connectorx:           <not installed>
deltalake:            <not installed>
fastexcel:            <not installed>
fsspec:               2024.3.1
gevent:               <not installed>
hvplot:               <not installed>
matplotlib:           3.8.4
nest_asyncio:         <not installed>
numpy:                1.24.3
openpyxl:             <not installed>
pandas:               2.2.1
pyarrow:              <not installed>
pydantic:             <not installed>
pyiceberg:            <not installed>
pyxlsb:               <not installed>
sqlalchemy:           <not installed>
xlsx2csv:             <not installed>
xlsxwriter:           <not installed>
```

</details>

**Comment by tushar-nitave** [comment]
Can I work on this?

**Comment by ritchie46** [comment]
`NaN` isn't part of the JSON spec. So our json parser (external crate) don't parse it.

https://www.json.org/json-en.html

**Comment by ktvanzwol** [comment]
The same is true for IEEE 754's `inf` it would be nice if these could be supported in some way as they represent valid floating-point values. 

The Python's standard `json` module did choose to support these values [json — JSON encoder and decoder — Python 3.13.7 documentation](https://docs.python.org/3/library/json.html#encoders-and-decoders)

_"It also understands `NaN`, `Infinity`, and `-Infinity` as their corresponding float values, which is outside the JSON spec."_
