### ISSUE TITLE
Panic when using `Series.clear` on nested Object types

### ISSUE THREAD

**Issue by stinodego** [pola-rs/polars#16261]
### Checks

- [X] I have checked that this issue has not already been reported.
- [X] I have confirmed this bug exists on the [latest version](https://pypi.org/project/polars/) of Polars.

### Reproducible example

```python
import polars as pl

s = pl.Series([[object()]], dtype=pl.List(pl.Object()))
s.clear()
```

### Log output

```shell
thread '<unnamed>' panicked at /home/stijn/code/polars/crates/polars-core/src/named_from.rs:162:86:
called `Result::unwrap()` on an `Err` value: InvalidOperation(ErrString("`list_builder` operation not supported for dtype `object`"))
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
Traceback (most recent call last):
  File "/home/stijn/code/polars/py-polars/repro.py", line 11, in <module>
    s = pl.Series([[object()]], dtype=pl.List(pl.Object()))
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/stijn/code/polars/py-polars/polars/series/series.py", line 314, in __init__
    self._s = sequence_to_pyseries(
              ^^^^^^^^^^^^^^^^^^^^^
  File "/home/stijn/code/polars/py-polars/polars/_utils/construction/series.py", line 277, in sequence_to_pyseries
    pyseries = PySeries.new_series_list(name, pyseries_list, strict)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
pyo3_runtime.PanicException: called `Result::unwrap()` on an `Err` value: InvalidOperation(ErrString("`list_builder` operation not supported for dtype `object`"))
```

### Issue description

Offending code is here:
https://github.com/pola-rs/polars/blob/d7d720ad3634d64094c9101de72be083baaede5d/crates/polars-core/src/series/mod.rs#L161-L173

Clearly this doesn't account for nested object types.

### Expected behavior

Return an empty Series.

### Installed versions

main

**Comment by stinodego** [comment]
@ritchie46 Thanks for the fixing the panic - but the issue persists! This should not error either. We should be careful not to close panic issues when the underlying issue persists.

**Comment by ohines** [comment]
I also encountered this issue and found that lists of objects type can be created in group by operations but can cause segfaults if one tries to do anything with them
```python
df = pl.DataFrame(
    [pl.Series("foo", [object(), object(), object()]), pl.Series("bar", [1, 1, 2])]
)
# shape: (3, 2)
# ┌────────────────────────────────┬─────┐
# │ foo                            ┆ bar │
# │ ---                            ┆ --- │
# │ object                         ┆ i64 │
# ╞════════════════════════════════╪═════╡
# │ <object object at 0x105159210> ┆ 1   │
# │ <object object at 0x1051591b0> ┆ 1   │
# │ <object object at 0x1051591e0> ┆ 2   │
# └────────────────────────────────┴─────┘

df_grouped = df.group_by("bar").agg("foo")

str(df_grouped)
# pyo3_runtime.PanicException: object dtype not supported in Series.iter

foo = df_grouped.select("foo").to_series()

foo.dtype
# List(Object)

foo.to_list()
# segmentation fault
```
