### ISSUE TITLE
`ComputeError: cannot aggregate a literal` for literals in `.over()` 

### ISSUE THREAD

**Issue by kevinli1993** [pola-rs/polars#16343]
### Checks

- [X] I have checked that this issue has not already been reported.
- [X] I have confirmed this bug exists on the [latest version](https://pypi.org/project/polars/) of Polars.

### Reproducible example

```python
import polars as pl
ds = pl.DataFrame(dict(A=[1,1,1,2,2,3]))
ds.with_columns(pl.lit(1).alias("B").sum().over(pl.col("A")))   # This will trigger a compute error

ds.with_columns(pl.repeat(1, pl.len()).alias("B").sum().over(pl.col("A"))) # this works
```

The error is 
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File ".../.venv/lib/python3.12/site-packages/polars/dataframe/frame.py", line 8310, in with_columns
    return self.lazy().with_columns(*exprs, **named_exprs).collect(_eager=True)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File ".venv/lib/python3.12/site-packages/polars/lazyframe/frame.py", line 1816, in collect
    return wrap_df(ldf.collect(callback))
                   ^^^^^^^^^^^^^^^^^^^^^
polars.exceptions.ComputeError: cannot aggregate a literal
```

### Issue description

This is similar to [this bug](https://github.com/pola-rs/polars/issues/2987).

It seems sensible to allow literals in an `.over()` context, to allow for either `pl.col("...")` or `pl.lit(1)` for user defined functions.

### Expected behavior

The behavior should be the same as using
```python
ds.with_columns(pl.repeat(1, pl.len()).alias("B").sum().over(pl.col("A"))) # this works
```

### Installed versions

<details>

```
--------Version info---------
Polars:               0.20.26
Index type:           UInt32
Platform:             macOS-14.4.1-arm64-arm-64bit
Python:               3.12.3 (main, Apr 12 2024, 17:16:04) [Clang 15.0.0 (clang-1500.1.0.2.5)]

----Optional dependencies----
adbc_driver_manager:  <not installed>
cloudpickle:          <not installed>
connectorx:           <not installed>
deltalake:            <not installed>
fastexcel:            <not installed>
fsspec:               <not installed>
gevent:               <not installed>
hvplot:               <not installed>
matplotlib:           3.8.4
nest_asyncio:         <not installed>
numpy:                1.26.4
openpyxl:             <not installed>
pandas:               2.2.2
pyarrow:              16.1.0
pydantic:             <not installed>
pyiceberg:            <not installed>
pyxlsb:               <not installed>
sqlalchemy:           <not installed>
torch:                <not installed>
xlsx2csv:             <not installed>
xlsxwriter:           <not installed>```

</details>

**Comment by JulianCologne** [comment]
Do you have a "real-world-example" where this is useful?

Seems like you want to know the number of rows per group?

No computer access currently but this might work and is very easy:
`pl.len().over(pl.col("A"))`

**Comment by ritchie46** [comment]
> pl.len().over("A")

This works indeed.

We do allow literals in `over`. We don't allow the summation of literals during group by.  Which is a good decision as you already expected this to work differently that it would. `pl.lit(1).sum()` would return `1`, not very useful.

**Comment by kevinli1993** [comment]
Here is a non-contrived use-case I have. I want to define this function
```
def grouped_weighted_mean(grouping, x, weight):
    return ((x * weight).sum() / weight.sum()).over(grouping)
```

So the user may do:
```
(
    ds
    .with_columns(
        grouped_weighted_mean(pl.col("G"), pl.col("x"), pl.lit(1.0)).alias("XW0"),
        grouped_weighted_mean(pl.col("G"), pl.col("x"), pl.col("weight_one")).alias("XW1"),
        grouped_weighted_mean(pl.col("G"), pl.col("x"), pl.col("weight_one").pow(2)).alias("XW2")
    )
)
```
Here, the first line does not work due to `pl.lit(1.0)` being a literal. 

@ritchie46, I understand now that `pl.lit(1).sum()` won't work as expected, but curious if you have any suggestions for the above use-case? The idea is to keep the function interface consistent, e.g., so the user could use an existing column/expression, or a literal for a constant weight.

Thanks!

**Comment by cjackal** [comment]
> So the user may do:
> 
> ```
> (
>     ds
>     .with_columns(
>         grouped_weighted_mean(pl.col("G"), pl.col("x"), pl.lit(1.0)).alias("XW0"),
>         grouped_weighted_mean(pl.col("G"), pl.col("x"), pl.col("weight_one")).alias("XW1"),
>         grouped_weighted_mean(pl.col("G"), pl.col("x"), pl.col("weight_one").pow(2)).alias("XW2")
>     )
> )
> ```
Can the user just set `pl.col("weight_one").pow(0)` instead of `pl.lit(1.0)`, if they are just interested in grouped weighted average?

**Comment by kevinli1993** [comment]
> Can the user just set pl.col("weight_one").pow(0) instead of pl.lit(1.0), if they are just interested in grouped exponentially weighted average?

There are many workarounds, but this is missing the point -- the question is whether we could use a literal in situations like this in general.

**Comment by cjackal** [comment]
> There are many workarounds (`.pow(0)` is one, using `pl.col("const")` where `const` is all 1.0 is another), but this is missing the point -- the question is whether we could use a literal in situations like this in general.

Sounds quite like a riddle, how about applying a tautological identity of existing columns like `weight + pl.lit("A") - pl.lit("A")`

**Comment by kevinli1993** [comment]
Yep! For now I'm just passing the burden/choice onto the user; if they want to use a constant weight, they will either need to do `pl.col("W") * 0 + 1`, or use `pl.col("const")` (assuming they have a constant column available in their dataframe). 

Neither is as aesthetically pleasing as `pl.lit(1.0)`, imo :-)

**Comment by ritchie46** [comment]
> Here, the first line does not work due to pl.lit(1.0) being a literal.


The caller shouldn't pass a literal, but something of the groups length: `pl.ones(pl.len())`.

**Comment by cmdlineluser** [comment]
[`.meta.is_literal()`](https://docs.pola.rs/api/python/dev/reference/expressions/api/polars.Expr.meta.is_literal.html#polars.Expr.meta.is_literal) has jus been added.

- https://github.com/pola-rs/polars/pull/19773

**Comment by kdn36** [comment]
This should be solved on main now. Output for the original example:
```
shape: (6, 2)
┌─────┬─────┐
│ A   ┆ B   │
│ --- ┆ --- │
│ i64 ┆ i32 │
╞═════╪═════╡
│ 1   ┆ 1   │
│ 1   ┆ 1   │
│ 1   ┆ 1   │
│ 2   ┆ 1   │
│ 2   ┆ 1   │
│ 3   ┆ 1   │
└─────┴─────┘
shape: (6, 2)
┌─────┬─────┐
│ A   ┆ B   │
│ --- ┆ --- │
│ i64 ┆ i32 │
╞═════╪═════╡
│ 1   ┆ 3   │
│ 1   ┆ 3   │
│ 1   ┆ 3   │
│ 2   ┆ 2   │
│ 2   ┆ 2   │
│ 3   ┆ 1   │
└─────┴─────┘
```
Presumably https://github.com/pola-rs/polars/pull/24820

Kindly let us know if there is still an issue.
