### ISSUE TITLE
`Series.unique_counts` not supported for dtype `bool`

### ISSUE THREAD

**Issue by lars-reimann** [pola-rs/polars#16356]
### Checks

- [X] I have checked that this issue has not already been reported.
- [X] I have confirmed this bug exists on the [latest version](https://pypi.org/project/polars/) of Polars.

### Reproducible example

```python
import polars as pl

if __name__ == "__main__":
    series = pl.Series("a", [True, False])
    print(series.unique_counts())
```

### Log output

```shell
Traceback (most recent call last):
  File "C:\Users\Lars\AppData\Roaming\JetBrains\PyCharm2024.1\scratches\scratch_8.py", line 7, in <module>
    print(frame.unique_counts())
          ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Lars\AppData\Local\pypoetry\Cache\virtualenvs\safe-ds-N_Ih5G5i-py3.12\Lib\site-packages\polars\series\utils.py", line 107, in wrapper
    return s.to_frame().select_seq(f(*args, **kwargs)).to_series()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Lars\AppData\Local\pypoetry\Cache\virtualenvs\safe-ds-N_Ih5G5i-py3.12\Lib\site-packages\polars\dataframe\frame.py", line 8162, in select_seq
    return self.lazy().select_seq(*exprs, **named_exprs).collect(_eager=True)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Lars\AppData\Local\pypoetry\Cache\virtualenvs\safe-ds-N_Ih5G5i-py3.12\Lib\site-packages\polars\lazyframe\frame.py", line 1816, in collect
    return wrap_df(ldf.collect(callback))
                   ^^^^^^^^^^^^^^^^^^^^^
polars.exceptions.InvalidOperationError: `unique_counts` operation not supported for dtype `bool`
```
```


### Issue description

I would not expect this call to fail, especially since `value_counts` works on boolean series.

### Expected behavior

It should be equivalent to `frame.cast(pl.String).unique_counts()`:

```
shape: (2,)
Series: 'a' [u32]
[
	1
	2
]
```

### Installed versions

<details>

```
--------Version info---------
Polars:               0.20.26
Index type:           UInt32
Platform:             Windows-11-10.0.22631-SP0
Python:               3.12.3 (tags/v3.12.3:f6650f9, Apr  9 2024, 14:05:25) [MSC v.1938 64 bit (AMD64)]

----Optional dependencies----
adbc_driver_manager:  <not installed>
cloudpickle:          <not installed>
connectorx:           <not installed>
deltalake:            <not installed>
fastexcel:            <not installed>
fsspec:               2024.5.0
gevent:               <not installed>
hvplot:               0.10.0
matplotlib:           3.9.0
nest_asyncio:         1.6.0
numpy:                1.26.4
openpyxl:             3.1.2
pandas:               2.2.2
pyarrow:              16.1.0
pydantic:             <not installed>
pyiceberg:            <not installed>
pyxlsb:               <not installed>
sqlalchemy:           <not installed>
torch:                2.3.0+cu121
xlsx2csv:             <not installed>
xlsxwriter:           <not installed>
```

</details>

**Comment by henrikig** [comment]
Had a go on this one in #16588. Agree that it makes sense to support it given that `value_counts` is supported for `bool` already.
