### ISSUE TITLE
`min` fails on `duration` types

### ISSUE THREAD

**Issue by ion-elgreco** [pola-rs/polars#16382]
### Checks

- [X] I have checked that this issue has not already been reported.
- [X] I have confirmed this bug exists on the [latest version](https://pypi.org/project/polars/) of Polars.

### Reproducible example

```python
## 0.20.26 - works
import polars as pl
df = pl.DataFrame({
    "duration": [-5500000000000000000, 123123123123]
}, schema={"duration":pl.Duration})
print(df.describe())

## 0.20.27 - doesn't work
thread 'polars-2' panicked at crates/polars-core/src/datatypes/any_value.rs:811:19:
cannot create date from other type. dtype: -63657407d -9h -46m -40s
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```
Caused by min failing

```python
df = pl.DataFrame({
    "duration": [-5555, 9999]
}, schema={"duration":pl.Duration})
print(df.min())
```

### Issue description

Taking the minimum of a duration type fails.

### Expected behavior

Return min properly.

### Installed versions

<details>

```
--------Version info---------
Polars:               0.20.27
Index type:           UInt32
Platform:             Linux-5.15.146.1-microsoft-standard-WSL2-x86_64-with-glibc2.31
Python:               3.10.12 (main, Sep 17 2023, 19:42:13) [GCC 9.4.0]

----Optional dependencies----
adbc_driver_manager:  <not installed>
cloudpickle:          3.0.0
connectorx:           <not installed>
deltalake:            0.14.0
fastexcel:            <not installed>
fsspec:               2023.12.2
gevent:               <not installed>
hvplot:               <not installed>
matplotlib:           3.8.2
nest_asyncio:         1.5.8
numpy:                1.26.0
openpyxl:             <not installed>
pandas:               2.0.3
pyarrow:              14.0.2
pydantic:             1.10.12
pyiceberg:            <not installed>
pyxlsb:               <not installed>
sqlalchemy:           1.4.51
torch:                <not installed>
xlsx2csv:             <not installed>
xlsxwriter:           <not installed>
```

</details>

**Comment by BGR360** [comment]
Same problem in 0.20.28:

```python
lf = pl.LazyFrame({
    "duration": [1000, 2000, 3000]
}, schema={"duration": pl.Duration})

print(lf.select(pl.col('duration').min()).collect())
```

```
thread '<unnamed>' panicked at crates/polars-core/src/datatypes/any_value.rs:811:19:
cannot create date from other type. dtype: 1ms
---------------------------------------------------------------------------
PanicException                            Traceback (most recent call last)
Cell In[33], line 5
      1 lf = pl.LazyFrame({
      2     "duration": [1000, 2000, 3000]
      3 }, schema={"duration": pl.Duration})
----> 5 print(lf.select(pl.col('duration').min()).collect())

File ~/scratch/oplogs-demo/.venv/lib/python3.8/site-packages/polars/lazyframe/frame.py:1817, in LazyFrame.collect(self, type_coercion, predicate_pushdown, projection_pushdown, simplify_expression, slice_pushdown, comm_subplan_elim, comm_subexpr_elim, no_optimization, streaming, background, _eager, **_kwargs)
   1814 # Only for testing purposes atm.
   1815 callback = _kwargs.get("post_opt_callback")
-> 1817 return wrap_df(ldf.collect(callback))

PanicException: cannot create date from other type. dtype: 1ms
```

**Comment by BGR360** [comment]
Might this be the bug?

https://github.com/pola-rs/polars/blob/24b77de821f30a34c901f7a280f8f5e170ff13c0/crates/polars-core/src/series/implementations/duration.rs#L407-L414

`.as_duration()` is called twice.

**Comment by BGR360** [comment]
Or perhaps `AnyValue::as_duration()` should just be fixed to handle the case where `self` is already `AnyValue::Duration`
