### ISSUE TITLE
Strange issue when using `.over()` with sum.

### ISSUE THREAD

**Issue by koaning** [pola-rs/polars#1642]
I have a query over here:

```python
(df
 .filter(pl.col("char") == 9)
 .pipe(set_types)
 .pipe(sessionize)
 .with_columns([
     pl.col("new_session_mark").sum()
 ])
 .collect()
 .head(5)
)
```

This returns the following dataframe. 

```
┌──────┬───────┬──────┬───────────┬─────┬──────────────────┬─────────┬───────────┬─────────────────┐
│ char ┆ level ┆ race ┆ charclass ┆ ... ┆ timestamp        ┆ ts_diff ┆ char_diff ┆ new_session_mar │
│ ---  ┆ ---   ┆ ---  ┆ ---       ┆     ┆ ---              ┆ ---     ┆ ---       ┆ k               │
│ i64  ┆ i64   ┆ str  ┆ str       ┆     ┆ datetime         ┆ bool    ┆ bool      ┆ ---             │
│      ┆       ┆      ┆           ┆     ┆                  ┆         ┆           ┆ u32             │
╞══════╪═══════╪══════╪═══════════╪═════╪══════════════════╪═════════╪═══════════╪═════════════════╡
│ 9    ┆ 70    ┆ Orc  ┆ Hunter    ┆ ... ┆ 2008-01-01       ┆ true    ┆ true      ┆ 265             │
│      ┆       ┆      ┆           ┆     ┆ 11:02:20         ┆         ┆           ┆                 │
├╌╌╌╌╌╌┼╌╌╌╌╌╌╌┼╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┤
│ 9    ┆ 70    ┆ Orc  ┆ Hunter    ┆ ... ┆ 2008-01-01       ┆ false   ┆ false     ┆ 265             │
│      ┆       ┆      ┆           ┆     ┆ 11:12:07         ┆         ┆           ┆                 │
├╌╌╌╌╌╌┼╌╌╌╌╌╌╌┼╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┤
│ 9    ┆ 70    ┆ Orc  ┆ Hunter    ┆ ... ┆ 2008-01-01       ┆ false   ┆ false     ┆ 265             │
│      ┆       ┆      ┆           ┆     ┆ 11:22:40         ┆         ┆           ┆                 │
├╌╌╌╌╌╌┼╌╌╌╌╌╌╌┼╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┤
│ 9    ┆ 70    ┆ Orc  ┆ Hunter    ┆ ... ┆ 2008-01-01       ┆ false   ┆ false     ┆ 265             │
│      ┆       ┆      ┆           ┆     ┆ 11:32:29         ┆         ┆           ┆                 │
├╌╌╌╌╌╌┼╌╌╌╌╌╌╌┼╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┤
│ 9    ┆ 70    ┆ Orc  ┆ Hunter    ┆ ... ┆ 2008-01-01       ┆ false   ┆ false     ┆ 265             │
│      ┆       ┆      ┆           ┆     ┆ 11:42:18         ┆         ┆           ┆                 │
└──────┴───────┴──────┴───────────┴─────┴──────────────────┴─────────┴───────────┴─────────────────┘
```

But if I were to attach an `.over()` here ... 

```python
print(df
 .filter(pl.col("char") == 9)
 .pipe(set_types)
 .pipe(sessionize)
 .with_columns([
     pl.col("new_session_mark").over(pl.col("char")).sum()
 ])
 .collect()
 .head(5)
)
```

... it's panic at the disco. 

```
thread '<unnamed>' panicked at 'not implemented for dtype Null', /github/workspace/polars/polars-core/src/chunked_array/builder/list.rs:314:5
thread '<unnamed>' panicked at 'not implemented for dtype Null', /github/workspace/polars/polars-core/src/chunked_array/builder/list.rs:314:5
thread '<unnamed>' panicked at 'not implemented for dtype Null', /github/workspace/polars/polars-core/src/chunked_array/builder/list.rs:314:5
thread '<unnamed>' panicked at 'thread 'not implemented for dtype Null', <unnamed>/github/workspace/polars/polars-core/src/chunked_array/builder/list.rsthread '' panicked at ':<unnamed>not implemented for dtype Null314' panicked at '', :not implemented for dtype Null/github/workspace/polars/polars-core/src/chunked_array/builder/list.rs', :5/github/workspace/polars/polars-core/src/chunked_array/builder/list.rs
:314314::55

thread '<unnamed>thread '' panicked at 'not implemented for dtype Null<unnamed>', ' panicked at 'not implemented for dtype Null/github/workspace/polars/polars-core/src/chunked_array/builder/list.rs', :/github/workspace/polars/polars-core/src/chunked_array/builder/list.rs314::3145:
5
thread '<unnamed>' panicked at 'not implemented for dtype Null', /github/workspace/polars/polars-core/src/chunked_array/builder/list.rs:314:5
thread '<unnamed>' panicked at 'not implemented for dtype Null', /github/workspace/polars/polars-core/src/chunked_array/builder/list.rs:314thread ':5<unnamed>
' panicked at 'not implemented for dtype Null', /github/workspace/polars/polars-core/src/chunked_array/builder/list.rs:314:5
thread '<unnamed>' panicked at 'not implemented for dtype Null', /github/workspace/polars/polars-core/src/chunked_array/builder/list.rs:314:5
---------------------------------------------------------------------------
PanicException                            Traceback (most recent call last)
/tmp/ipykernel_3614596/3977872856.py in <module>
      4  .pipe(sessionize)
      5  .with_columns([
----> 6      pl.col("new_session_mark").over(pl.col("char")).sum()
      7  ])
      8  .collect()

~/Development/dask-demo/venv/lib/python3.7/site-packages/polars/lazy/frame.py in collect(self, type_coercion, predicate_pushdown, projection_pushdown, simplify_expression, string_cache, no_optimization)
    283             string_cache,
    284         )
--> 285         return pl.eager.frame.wrap_df(ldf.collect())
    286 
    287     def fetch(

PanicException: not implemented for dtype Null
```

**Comment by koaning** [comment]
It also seems like I cannot use [.cumsum()](https://pola-rs.github.io/polars/py-polars/html/reference/api/polars.Expr.cumsum.html) together with `.over()`.

**Comment by ritchie46** [comment]
I think you already figured it out. The aggregation expressions are meant to be used before the `.over()` as you mentioned in #1645
