### ISSUE TITLE
order of aggregation expressions and `.over()`. 

### ISSUE THREAD

**Issue by koaning** [pola-rs/polars#1645]
I tried counting the number of sessions for a character in a dataframe via: 

```python
.with_columns([
    pl.col("session").over("char").n_unique()
]))
```

Which told me it wasn't implemented.

```
thread '<unnamed>' panicked at 'not implemented', /github/workspace/polars/polars-core/src/series/series_trait.rs:687:9
---------------------------------------------------------------------------
PanicException                            Traceback (most recent call last)
/tmp/ipykernel_3614596/4181745090.py in <module>
      3  .pipe(set_types)
      4  .pipe(sessionize)
----> 5  .pipe(add_features)
      6  .collect()
      7 )

~/Development/dask-demo/venv/lib/python3.7/site-packages/polars/lazy/frame.py in collect(self, type_coercion, predicate_pushdown, projection_pushdown, simplify_expression, string_cache, no_optimization)
    283             string_cache,
    284         )
--> 285         return pl.eager.frame.wrap_df(ldf.collect())
    286 
    287     def fetch(

PanicException: not implemented
```

This is a bit confusing because the [docs](https://pola-rs.github.io/polars/py-polars/html/reference/api/polars.n_unique.html) suggest it's around.

**Comment by koaning** [comment]
I'm also getting errors with this method: 

```python
def add_features(dataf):
    return (dataf
             .with_columns([
                 pl.lit(1).alias("one")
             ])
             .with_columns([
                 pl.col("one").over("session").sum()
             ]))
```

It may be related. Slightly more verbose error though. 

```
thread 'thread '<unnamed><unnamed>' panicked at '' panicked at 'not implemented for dtype Nullnot implemented for dtype Null', /github/workspace/polars/polars-core/src/chunked_array/builder/list.rs', :/github/workspace/polars/polars-core/src/chunked_array/builder/list.rs314::5thread '314
:<unnamed>5' panicked at '
not implemented for dtype Null', /github/workspace/polars/polars-core/src/chunked_array/builder/list.rs:314:5
thread '<unnamed>' panicked at 'not implemented for dtype Null', /github/workspace/polars/polars-core/src/chunked_array/builder/list.rs:314:5
thread '<unnamed>thread '' panicked at 'not implemented for dtype Null', thread '/github/workspace/polars/polars-core/src/chunked_array/builder/list.rs<unnamed>thread '<unnamed>' panicked at 'thread 'not implemented for dtype Null:<unnamed><unnamed>314' panicked at '' panicked at ':' panicked at '', not implemented for dtype Nullnot implemented for dtype Null/github/workspace/polars/polars-core/src/chunked_array/builder/list.rs', not implemented for dtype Null5/github/workspace/polars/polars-core/src/chunked_array/builder/list.rs:
', thread '', :314<unnamed>314/github/workspace/polars/polars-core/src/chunked_array/builder/list.rs/github/workspace/polars/polars-core/src/chunked_array/builder/list.rs:' panicked at '5::5:
not implemented for dtype Null
', 314/github/workspace/polars/polars-core/src/chunked_array/builder/list.rs314:thread '314thread ':<unnamed><unnamed>' panicked at '' panicked at 'not implemented for dtype Nullnot implemented for dtype Null:', :55

', /github/workspace/polars/polars-core/src/chunked_array/builder/list.rs5/github/workspace/polars/polars-core/src/chunked_array/builder/list.rs:
:314314::55

---------------------------------------------------------------------------
PanicException                            Traceback (most recent call last)
/tmp/ipykernel_3614596/4181745090.py in <module>
      3  .pipe(set_types)
      4  .pipe(sessionize)
----> 5  .pipe(add_features)
      6  .collect()
      7 )

~/Development/dask-demo/venv/lib/python3.7/site-packages/polars/lazy/frame.py in collect(self, type_coercion, predicate_pushdown, projection_pushdown, simplify_expression, string_cache, no_optimization)
    283             string_cache,
    284         )
--> 285         return pl.eager.frame.wrap_df(ldf.collect())
    286 
    287     def fetch(

PanicException: not implemented for dtype Null
```

**Comment by koaning** [comment]
doh! the order was wrong. 

## Do Not

```
pl.col("a").over("b").sum()
```

## Do 

```
pl.col("a").sum().over("b")
```

That said ... maybe there's something to be said for a meaningful error message here?

**Comment by ritchie46** [comment]
Yes, indeed the error information could definitely be more clear.

The syntax is `col("foo") -> various aggregation expressions -> .over("groups")`.

**Comment by ritchie46** [comment]
Creating the errors takes a bit of effort. Because it depends on the final `dtype` if another aggregation is allowed.

```python
df = pl.DataFrame({
    "timestamp": ["2021-02-01", "2021-03-1", "2021-04-1"],
    "guild": [1, 2, 3],
    "char": ["a", "a", "b"],
    
})


df.select([
    col("guild").over("char").sum(), # this panics as we can sum dtype list
    col("guild").mean().over("char").sum() # this is allowed, because we sum the mean values of dtype Float64
])
```

**Comment by ritchie46** [comment]
#1647 added dtype information to the panics. This should inform the user why certain operations are not available.
