### ISSUE TITLE
`struct.rename_fields` does not work on structs with categorical columns after scanning a parquet file with more than one row group.

### ISSUE THREAD

**Issue by MaksHess** [pola-rs/polars#16478]
### Checks

- [X] I have checked that this issue has not already been reported.
- [X] I have confirmed this bug exists on the [latest version](https://pypi.org/project/polars/) of Polars.

### Reproducible example

```python
"""Example for reproducing the bug."""
from itertools import combinations
from pathlib import Path

import polars as pl
import pyarrow.parquet as pq

pl.enable_string_cache()

def try_rename_struct_fields(
    df,
    name,
    struct_columns,
):
    df_struct = df.select(pl.struct(struct_columns).alias('struct'))
    try:
        df_struct.select(
            pl.col('struct').struct.rename_fields(
                [f"rename_{i}" for i in range(len(struct_columns))]
            )
        )
        print(f'success: {name}')
    except pl.PolarsPanicError as e:
        print(f'failure: {e.__class__} {name}')


def main():
    # Create a test df with categorical columns
    n = 100
    row_group_size_one = 512**2
    row_group_size_multiple = 30

    df_orig = pl.DataFrame(
        {
            "cat_lex": [f"cat_{i}" for i in range(n)],
            "cat_phys": [f"cat_{i}" for i in range(n)],
            "uint": list(range(n)),
            "int": list(range(-(n - 1), 1)),
        },
        schema={
            "cat_lex": pl.Categorical(ordering='physical'),
            "cat_phys": pl.Categorical(ordering="lexical"),
            "uint": pl.UInt32,
            "int": pl.Int32,
        },
    )

    # Write with a row group size larger than n
    fn_arrow_one_group = Path('temp.pyarrow.parquet')
    fn_polars_one_group = Path('temp.polars.parquet')
    df_orig.write_parquet(fn_arrow_one_group, use_pyarrow=False, row_group_size=row_group_size_one)
    df_orig.write_parquet(fn_polars_one_group, use_pyarrow=True, row_group_size=row_group_size_one)

    # Write with a row group size smaller n -> multiple row groups
    fn_arrow_multiple_groups = Path('temp.pyarrow_mult.parquet')
    fn_polars_multiple_groups = Path('temp.polars_mult.parquet')
    df_orig.write_parquet(fn_arrow_multiple_groups, use_pyarrow=False, row_group_size=row_group_size_multiple)
    df_orig.write_parquet(fn_polars_multiple_groups, use_pyarrow=True, row_group_size=row_group_size_multiple)

    # Read from the one-row-group files and try creating and renaming a struct between all combinations of column types
    FN_POLARS = fn_polars_one_group
    FN_ARROW = fn_arrow_one_group

    print(">> Testing files with one row group:")
    # Metadata shows one row group for both files
    print(FN_POLARS.stem)
    print(pq.read_metadata(FN_POLARS))
    print()
    print(FN_ARROW.stem)
    print(pq.read_metadata(FN_ARROW))
    print()

    test_frames = {
        "orig": df_orig,
        "write polars read polars": pl.read_parquet(FN_POLARS),
        "write pyarrw read polars": pl.read_parquet(FN_ARROW),
        "write polars read pyarrw": pl.read_parquet(
            FN_POLARS, use_pyarrow=True
        ),
        "write pyarrw read pyarrw": pl.read_parquet(
            FN_ARROW, use_pyarrow=True
        ),
        "write polars scan polars": pl.scan_parquet(FN_POLARS).collect(),
        "write pyarrw scan polars": pl.scan_parquet(FN_ARROW).collect(),
    }

    # Renaming structs succeeds on all combinations of read/write and column type.
    for name, df in test_frames.items():
        for c1, c2 in combinations(df_orig.columns, 2):
            try_rename_struct_fields(
                df, struct_columns=[c1, c2], name=f"{name!r}, ({c1}, {c2})"
            )
        print()


    # Same for the multiple row group files.
    print(">> Testing files with multiple row groups:")
    FN_POLARS = fn_polars_multiple_groups
    FN_ARROW = fn_arrow_multiple_groups

    print(FN_POLARS.stem)
    print(pq.read_metadata(FN_POLARS))
    print()
    print(FN_ARROW.stem)
    print(pq.read_metadata(FN_ARROW))
    print()

    test_frames = {
        "orig": df_orig,
        "write polars read polars": pl.read_parquet(FN_POLARS),
        "write pyarrw read polars": pl.read_parquet(FN_ARROW),
        "write polars read pyarrw": pl.read_parquet(
            FN_POLARS, use_pyarrow=True
        ),
        "write pyarrw read pyarrw": pl.read_parquet(
            FN_ARROW, use_pyarrow=True
        ),
        "write polars scan polars": pl.scan_parquet(FN_POLARS).collect(),
        "write pyarrw scan polars": pl.scan_parquet(FN_ARROW).collect(),
    }

    # Renaming structs succeeds only when reading with the pyarrow backend, both ordering = 'physical' and 'lexical' show the bug.
    # Which writer backend is used does not matter, only wheter there's more than one row group in the resulting praquet file
    for name, df in test_frames.items():
        for c1, c2 in combinations(df_orig.columns, 2):
            try_rename_struct_fields(
                df, struct_columns=[c1, c2], name=f"{name!r}, ({c1}, {c2})"
            )
        print()

if __name__ == "__main__":
    main()
```

### Log output

```shell
# Error message
---------------------------------------------------------------------------
PanicException                            Traceback (most recent call last)
Cell In[91], line 2
      1 # %%
----> 2 test_frames['write polars read polars'].select(pl.struct('cat_lex')).select(pl.col('cat_lex').struct.rename_fields(['a']))

File c:\****\Lib\site-packages\polars\dataframe\frame.py:8469, in DataFrame.select(self, *exprs, **named_exprs)
   8369 def select(
   8370     self, *exprs: IntoExpr | Iterable[IntoExpr], **named_exprs: IntoExpr
   8371 ) -> DataFrame:
   8372     """
   8373     Select columns from this DataFrame.
   8374 
   (...)
   8467     └───────────┘
   8468     """
-> 8469     return self.lazy().select(*exprs, **named_exprs).collect(_eager=True)

File c:\****\Lib\site-packages\polars\lazyframe\frame.py:1837, in LazyFrame.collect(self, type_coercion, predicate_pushdown, projection_pushdown, simplify_expression, slice_pushdown, comm_subplan_elim, comm_subexpr_elim, cluster_with_columns, no_optimization, streaming, background, _eager, **_kwargs)
   1834 # Only for testing purposes atm.
   1835 callback = _kwargs.get("post_opt_callback")
-> 1837 return wrap_df(ldf.collect(callback))

PanicException: called `Option::unwrap()` on a `None` value

# Output of the above test script
>> Testing files with one row group:
temp.polars
<pyarrow._parquet.FileMetaData object at 0x000001BE5BDED8F0>
  created_by: parquet-cpp-arrow version 16.1.0
  num_columns: 4
  num_rows: 100
  num_row_groups: 1
  format_version: 2.6
  serialized_size: 969

temp.pyarrow
<pyarrow._parquet.FileMetaData object at 0x000001BE5BDED8F0>
  created_by: Polars
  num_columns: 4
  num_rows: 100
  num_row_groups: 1
  format_version: 1.0
  serialized_size: 949

success: 'orig', (cat_lex, cat_phys)
success: 'orig', (cat_lex, uint)
success: 'orig', (cat_lex, int)
success: 'orig', (cat_phys, uint)
success: 'orig', (cat_phys, int)
success: 'orig', (uint, int)

success: 'write polars read polars', (cat_lex, cat_phys)
success: 'write polars read polars', (cat_lex, uint)
success: 'write polars read polars', (cat_lex, int)
success: 'write polars read polars', (cat_phys, uint)
success: 'write polars read polars', (cat_phys, int)
success: 'write polars read polars', (uint, int)

success: 'write pyarrw read polars', (cat_lex, cat_phys)
success: 'write pyarrw read polars', (cat_lex, uint)
success: 'write pyarrw read polars', (cat_lex, int)
success: 'write pyarrw read polars', (cat_phys, uint)
success: 'write pyarrw read polars', (cat_phys, int)
success: 'write pyarrw read polars', (uint, int)

success: 'write polars read pyarrw', (cat_lex, cat_phys)
success: 'write polars read pyarrw', (cat_lex, uint)
success: 'write polars read pyarrw', (cat_lex, int)
success: 'write polars read pyarrw', (cat_phys, uint)
success: 'write polars read pyarrw', (cat_phys, int)
success: 'write polars read pyarrw', (uint, int)

success: 'write pyarrw read pyarrw', (cat_lex, cat_phys)
success: 'write pyarrw read pyarrw', (cat_lex, uint)
success: 'write pyarrw read pyarrw', (cat_lex, int)
success: 'write pyarrw read pyarrw', (cat_phys, uint)
success: 'write pyarrw read pyarrw', (cat_phys, int)
success: 'write pyarrw read pyarrw', (uint, int)

success: 'write polars scan polars', (cat_lex, cat_phys)
success: 'write polars scan polars', (cat_lex, uint)
success: 'write polars scan polars', (cat_lex, int)
success: 'write polars scan polars', (cat_phys, uint)
success: 'write polars scan polars', (cat_phys, int)
success: 'write polars scan polars', (uint, int)

success: 'write pyarrw scan polars', (cat_lex, cat_phys)
success: 'write pyarrw scan polars', (cat_lex, uint)
success: 'write pyarrw scan polars', (cat_lex, int)
success: 'write pyarrw scan polars', (cat_phys, uint)
success: 'write pyarrw scan polars', (cat_phys, int)
success: 'write pyarrw scan polars', (uint, int)

>> Testing files with multiple row groups:
temp.polars_mult
<pyarrow._parquet.FileMetaData object at 0x000001BE7DE52110>
  created_by: parquet-cpp-arrow version 16.1.0
  num_columns: 4
  num_rows: 100
  num_row_groups: 4
  format_version: 2.6
  serialized_size: 1904

temp.pyarrow_mult
<pyarrow._parquet.FileMetaData object at 0x000001BE7DD18860>
  created_by: Polars
  num_columns: 4
  num_rows: 100
  num_row_groups: 3
  format_version: 1.0
  serialized_size: 1468

success: 'orig', (cat_lex, cat_phys)
success: 'orig', (cat_lex, uint)
success: 'orig', (cat_lex, int)
success: 'orig', (cat_phys, uint)
success: 'orig', (cat_phys, int)
success: 'orig', (uint, int)

thread '<unnamed>' panicked at crates\polars-core\src\series\from.rs:332:25:
called `Option::unwrap()` on a `None` value
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
failure: <class 'pyo3_runtime.PanicException'> 'write polars read polars', (cat_lex, cat_phys)
thread '<unnamed>' panicked at crates\polars-core\src\series\from.rs:332:25:
called `Option::unwrap()` on a `None` value
failure: <class 'pyo3_runtime.PanicException'> 'write polars read polars', (cat_lex, uint)
thread '<unnamed>' panicked at crates\polars-core\src\series\from.rs:332:25:
called `Option::unwrap()` on a `None` value
failure: <class 'pyo3_runtime.PanicException'> 'write polars read polars', (cat_lex, int)
thread '<unnamed>' panicked at crates\polars-core\src\series\from.rs:332:25:
called `Option::unwrap()` on a `None` value
failure: <class 'pyo3_runtime.PanicException'> 'write polars read polars', (cat_phys, uint)
thread '<unnamed>' panicked at crates\polars-core\src\series\from.rs:332:25:
called `Option::unwrap()` on a `None` value
failure: <class 'pyo3_runtime.PanicException'> 'write polars read polars', (cat_phys, int)
success: 'write polars read polars', (uint, int)

thread '<unnamed>' panicked at crates\polars-core\src\series\from.rs:332:25:
called `Option::unwrap()` on a `None` value
failure: <class 'pyo3_runtime.PanicException'> 'write pyarrw read polars', (cat_lex, cat_phys)
thread '<unnamed>' panicked at crates\polars-core\src\series\from.rs:332:25:
called `Option::unwrap()` on a `None` value
failure: <class 'pyo3_runtime.PanicException'> 'write pyarrw read polars', (cat_lex, uint)
thread '<unnamed>' panicked at crates\polars-core\src\series\from.rs:332:25:
called `Option::unwrap()` on a `None` value
failure: <class 'pyo3_runtime.PanicException'> 'write pyarrw read polars', (cat_lex, int)
thread '<unnamed>' panicked at crates\polars-core\src\series\from.rs:332:25:
called `Option::unwrap()` on a `None` value
failure: <class 'pyo3_runtime.PanicException'> 'write pyarrw read polars', (cat_phys, uint)
thread '<unnamed>' panicked at crates\polars-core\src\series\from.rs:332:25:
called `Option::unwrap()` on a `None` value
failure: <class 'pyo3_runtime.PanicException'> 'write pyarrw read polars', (cat_phys, int)
success: 'write pyarrw read polars', (uint, int)

success: 'write polars read pyarrw', (cat_lex, cat_phys)
success: 'write polars read pyarrw', (cat_lex, uint)
success: 'write polars read pyarrw', (cat_lex, int)
success: 'write polars read pyarrw', (cat_phys, uint)
success: 'write polars read pyarrw', (cat_phys, int)
success: 'write polars read pyarrw', (uint, int)

success: 'write pyarrw read pyarrw', (cat_lex, cat_phys)
success: 'write pyarrw read pyarrw', (cat_lex, uint)
success: 'write pyarrw read pyarrw', (cat_lex, int)
success: 'write pyarrw read pyarrw', (cat_phys, uint)
success: 'write pyarrw read pyarrw', (cat_phys, int)
success: 'write pyarrw read pyarrw', (uint, int)

thread '<unnamed>' panicked at crates\polars-core\src\series\from.rs:332:25:
called `Option::unwrap()` on a `None` value
failure: <class 'pyo3_runtime.PanicException'> 'write polars scan polars', (cat_lex, cat_phys)
thread '<unnamed>' panicked at crates\polars-core\src\series\from.rs:332:25:
called `Option::unwrap()` on a `None` value
failure: <class 'pyo3_runtime.PanicException'> 'write polars scan polars', (cat_lex, uint)
thread '<unnamed>' panicked at crates\polars-core\src\series\from.rs:332:25:
called `Option::unwrap()` on a `None` value
failure: <class 'pyo3_runtime.PanicException'> 'write polars scan polars', (cat_lex, int)
thread '<unnamed>' panicked at crates\polars-core\src\series\from.rs:332:25:
called `Option::unwrap()` on a `None` value
failure: <class 'pyo3_runtime.PanicException'> 'write polars scan polars', (cat_phys, uint)
thread '<unnamed>' panicked at crates\polars-core\src\series\from.rs:332:25:
called `Option::unwrap()` on a `None` value
failure: <class 'pyo3_runtime.PanicException'> 'write polars scan polars', (cat_phys, int)
success: 'write polars scan polars', (uint, int)

thread '<unnamed>' panicked at crates\polars-core\src\series\from.rs:332:25:
called `Option::unwrap()` on a `None` value
failure: <class 'pyo3_runtime.PanicException'> 'write pyarrw scan polars', (cat_lex, cat_phys)
thread '<unnamed>' panicked at crates\polars-core\src\series\from.rs:332:25:
called `Option::unwrap()` on a `None` value
failure: <class 'pyo3_runtime.PanicException'> 'write pyarrw scan polars', (cat_lex, uint)
thread '<unnamed>' panicked at crates\polars-core\src\series\from.rs:332:25:
called `Option::unwrap()` on a `None` value
failure: <class 'pyo3_runtime.PanicException'> 'write pyarrw scan polars', (cat_lex, int)
thread '<unnamed>' panicked at crates\polars-core\src\series\from.rs:332:25:
called `Option::unwrap()` on a `None` value
failure: <class 'pyo3_runtime.PanicException'> 'write pyarrw scan polars', (cat_phys, uint)
thread '<unnamed>' panicked at crates\polars-core\src\series\from.rs:332:25:
called `Option::unwrap()` on a `None` value
failure: <class 'pyo3_runtime.PanicException'> 'write pyarrw scan polars', (cat_phys, int)
success: 'write pyarrw scan polars', (uint, int)
```

#### Description
When writing a parquet file that contains multiple row groups and categorical columns, using `scan_parquet` (or `read_parquet` with `pyarrow=False`) returns a `LazyFrame`/`DataFrame` as expected. Only when collecting a categorical column into a struct `df2 = df.select(pl.struct(pl.col('cat'))` and subsequently trying to rename the fields `df2.select(pl.col('cat').struct.rename_fields(['a']))` does polars throw an exception. The bug does not occur when renaming in the same select statement than creating the struct, i. e. `df2 = df.select(pl.struct(pl.col('cat').struct.rename_fields(['a']))` works fine.  

#### Additional info
Using `read_parquet` with `pyarrow=True` works as expected on files with multiple row groups (both written with pyarrow and polars backend). 

`pl.Categorical(ordering='physical')` and `pl.Categorical(ordering='lexical')` behave the same.

Casting the categorical column to string OR calling `df2.sample(fraction=1)` also solves the problem.

`pl.enable_string_cache()` does not solve the issue.

### Expected behavior

The behaviour of a `DataFrame` collected after `scan_parquet` should be identical to the one read using `read_parquet(..., pyarrow=True)`.

### Installed versions

<details>

```
--------Version info---------
Polars:               0.20.29
Index type:           UInt32
Platform:             Windows-10-10.0.22631-SP0
Python:               3.11.9 | packaged by conda-forge | (main, Apr 19 2024, 18:27:10) [MSC v.1938 64 bit (AMD64)]

----Optional dependencies----
adbc_driver_manager:  <not installed>
cloudpickle:          3.0.0
connectorx:           <not installed>
deltalake:            <not installed>
fastexcel:            <not installed>
fsspec:               2024.5.0
gevent:               <not installed>
hvplot:               <not installed>
matplotlib:           3.9.0
nest_asyncio:         1.6.0
numpy:                1.26.4
openpyxl:             <not installed>
pandas:               2.2.2
pyarrow:              16.1.0
pydantic:             2.7.1
pyiceberg:            <not installed>
pyxlsb:               <not installed>
sqlalchemy:           <not installed>
torch:                <not installed>
xlsx2csv:             <not installed>
xlsxwriter:           <not installed>
```

</details>

**Comment by cmdlineluser** [comment]
Can reproduce.

This is the minimal repro I can manage on my system:

```python
import tempfile
import polars as pl
from pathlib import Path

with tempfile.TemporaryDirectory() as tmpdir:
    filename = Path(tmpdir) / "polars.parquet"

    N = 17

    df_orig = pl.DataFrame({
        "cat_a": ["a"] * N,
        "cat_b": ["b"] * N
    }).cast(pl.Categorical)

    df_orig.write_parquet(filename, row_group_size=2)

    df = pl.read_parquet(filename)

    (df.select(pl.struct(pl.all()))
       .select(pl.first().struct.rename_fields(["a", "b"]))
    )
```

```
thread '<unnamed>' panicked at crates/polars-core/src/series/from.rs:332:25:
called `Option::unwrap()` on a `None` value
```

N < 17 runs without error.

**Comment by magbak** [comment]
Experiencing the error in the context of concatenating DataFrames without re-chunking, indicating that the issue may arise due to the chunked data, and is not specifically tied to Parquet. This reproduces the error with Polars 0.20.29.

```Python
import polars as pl
from polars import concat

N=9
df_orig1 = pl.DataFrame({
    "cat_a": ["a"] * N,
    "cat_b": ["b"] * N
})

df_orig2 = pl.DataFrame({
    "cat_a": ["a"] * N,
    "cat_b": ["b"] * N
})

df = concat([df_orig1, df_orig2], rechunk=False).cast(pl.Categorical)

(df.select(pl.struct(pl.all()))
   .select(pl.first().struct.rename_fields(["a", "b"]))
)
```

```
thread '<unnamed>' panicked at crates/polars-core/src/series/from.rs:332:25:
called `Option::unwrap()` on a `None` value
```

On e.g. 0.20.15 and at latest 0.20.19, the error is not present. 
However, by version 0.20.20 (yanked) and 0.20.21 the error is present.

**Comment by ritchie46** [comment]
I cannot reproduce on `main`. I don't know which PR fixed it.

**Comment by magbak** [comment]
Thank you for the fast turnaround @ritchie46 ! 

After the fix however, I get a lot of errors of this type where the previous error would show up: 
```
`Result::unwrap()` on an `Err` value: ShapeMismatch(ErrString("unable to add a column of length 0 to a DataFrame of height 46"))
```
Appears to happen when a filter is applied that removes all of the values from only one of the chunks. 
Will have a go at reproducing, have not been able to yet.
