### ISSUE TITLE
`SchemaFieldNotFound` on LazyFrame when using `select` after `struct.field(...)`

### ISSUE THREAD

**Issue by mrjsj** [pola-rs/polars#16480]
### Checks

- [X] I have checked that this issue has not already been reported.
- [X] I have confirmed this bug exists on the [latest version](https://pypi.org/project/polars/) of Polars.

### Reproducible example

```python
data = {
    "foo": "bar",
    "my_struct": [
        {
            "x": 1, 
            "y": 2
        }
    ],
}

df = LazyFrame(data).select(
        pl.col("my_struct").struct.field("x")
    )

df = df.select("x")

print(df.collect()) # Raises error
```

### Log output

```shell
Traceback (most recent call last):
  File "/Users/xxx/test2.py", line 124, in <module>
    print(df.collect())
          ^^^^^^^^^^^^
  File "/Users/xxx/.venv/lib/python3.12/site-packages/polars/lazyframe/frame.py", line 1837, in collect
    return wrap_df(ldf.collect(callback))
                   ^^^^^^^^^^^^^^^^^^^^^
polars.exceptions.SchemaFieldNotFoundError: x
```

### Issue description

The above example fails to find the field "x", when `select`-ing even though it exists.

- Works fine with **Data**Frame
- Works if **not** `select`-ing "x"
- Works if `struct.field("x")` is appended `.alias("x")`

Notes:
- `drop("x")` works
- `rename({"x":"z"})` works
- `with_columns(pl.col("x"))` works
- Also works if using `unnest("my_struct")` instead of `struct.field("x")`

### Expected behavior

I expect it correctly identify the field without explicitly using `alias`

### Installed versions

<details>

```
--------Version info---------
Polars:               0.20.29
Index type:           UInt32
Platform:             macOS-14.4-arm64-arm-64bit
Python:               3.12.3 (main, Apr  9 2024, 08:09:14) [Clang 15.0.0 (clang-1500.3.9.4)]

----Optional dependencies----
adbc_driver_manager:  <not installed>
cloudpickle:          <not installed>
connectorx:           <not installed>
deltalake:            0.17.4
fastexcel:            <not installed>
fsspec:               2024.5.0
gevent:               <not installed>
hvplot:               <not installed>
matplotlib:           <not installed>
nest_asyncio:         <not installed>
numpy:                1.26.4
openpyxl:             <not installed>
pandas:               2.2.2
pyarrow:              16.1.0
pydantic:             <not installed>
pyiceberg:            <not installed>
pyxlsb:               <not installed>
sqlalchemy:           <not installed>
torch:                <not installed>
xlsx2csv:             <not installed>
xlsxwriter:           <not installed>
```

</details>

**Comment by cmdlineluser** [comment]
Can reproduce.

Seems to be `projection_pushdown` related.

```python
>>> df.collect(projection_pushdown=False)
shape: (1, 1)
┌─────┐
│ x   │
│ --- │
│ i64 │
╞═════╡
│ 1   │
└─────┘
```
