### ISSUE TITLE
`concat_list` PanicException inside `agg()`

### ISSUE THREAD

**Issue by cmdlineluser** [pola-rs/polars#16519]
### Checks

- [X] I have checked that this issue has not already been reported.
- [X] I have confirmed this bug exists on the [latest version](https://pypi.org/project/polars/) of Polars.

### Reproducible example

```python
import polars as pl

df = pl.DataFrame({
    "group": [1],
    "value": [2]
})

(df.group_by("group")
   .agg(
      pl.concat_list(
          pl.col("value").filter(False).backward_fill()
      )
   )
)

# PanicException: called `Result::unwrap()` on an `Err` value: 
# ComputeError(ErrString("cannot reshape len 0 into shape [-1, 1]"))
```

### Log output

```shell
keys/aggregates are not partitionable: running default HASH AGGREGATION
thread 'polars-0' panicked at crates/polars-plan/src/dsl/function_expr/list.rs:401:50:
called `Result::unwrap()` on an `Err` value: ComputeError(ErrString("cannot reshape len 0 into shape [-1, 1]"))
```

### Issue description

Without the `backward_fill` we get an empty list:

```python
shape: (1, 2)
┌───────┬─────────────────┐
│ group ┆ value           │
│ ---   ┆ ---             │
│ i64   ┆ list[list[i64]] │
╞═══════╪═════════════════╡
│ 1     ┆ []              │
└───────┴─────────────────┘
```

### Expected behavior

No panic.

### Installed versions

<details>

```
--------Version info---------
Polars:               0.20.30
Index type:           UInt32
Platform:             macOS-13.6.1-arm64-arm-64bit
Python:               3.12.2 (main, Feb  6 2024, 20:19:44) [Clang 15.0.0 (clang-1500.1.0.2.5)]

----Optional dependencies----
adbc_driver_manager:  <not installed>
cloudpickle:          <not installed>
connectorx:           <not installed>
deltalake:            <not installed>
fastexcel:            <not installed>
fsspec:               <not installed>
gevent:               <not installed>
hvplot:               <not installed>
matplotlib:           <not installed>
nest_asyncio:         <not installed>
numpy:                1.26.4
openpyxl:             <not installed>
pandas:               2.2.1
pyarrow:              15.0.2
pydantic:             <not installed>
pyiceberg:            <not installed>
pyxlsb:               <not installed>
sqlalchemy:           <not installed>
xlsx2csv:             <not installed>
xlsxwriter:           <not installed>
```

</details>

**Comment by MarcoGorelli** [comment]
Thanks for reporting!

Simpler reproducer:
```python
In [4]: df = pl.DataFrame({'a': []})

In [5]: df.select(pl.concat_list('a'))
thread '<unnamed>' panicked at crates/polars-plan/src/dsl/function_expr/list.rs:401:50:
called `Result::unwrap()` on an `Err` value: ComputeError(ErrString("cannot reshape len 0 into shape [-1, 1]"))
---------------------------------------------------------------------------
PanicException                            Traceback (most recent call last)
Cell In[5], line 1
----> 1 df.select(pl.concat_list('a'))

File ~/scratch/.venv/lib/python3.11/site-packages/polars/dataframe/frame.py:8301, in DataFrame.select(self, *exprs, **named_exprs)
   8201 def select(
   8202     self, *exprs: IntoExpr | Iterable[IntoExpr], **named_exprs: IntoExpr
   8203 ) -> DataFrame:
   8204     """
   8205     Select columns from this DataFrame.
   8206
   (...)
   8299     └───────────┘
   8300     """
-> 8301     return self.lazy().select(*exprs, **named_exprs).collect(_eager=True)

File ~/scratch/.venv/lib/python3.11/site-packages/polars/lazyframe/frame.py:1855, in LazyFrame.collect(self, type_coercion, predicate_pushdown, projection_pushdown, simplify_expression, slice_pushdown, comm_subplan_elim, comm_subexpr_elim, cluster_with_columns, no_optimization, streaming, background, _eager, **_kwargs)
   1852 # Only for testing purposes atm.
   1853 callback = _kwargs.get("post_opt_callback")
-> 1855 return wrap_df(ldf.collect(callback))

PanicException: called `Result::unwrap()` on an `Err` value: ComputeError(ErrString("cannot reshape len 0 into shape [-1, 1]"))
```
