### ISSUE TITLE
A regression in numpy-to-series conversion

### ISSUE THREAD

**Issue by KDruzhkin** [pola-rs/polars#16522]
### Checks

- [X] I have checked that this issue has not already been reported.
- [X] I have confirmed this bug exists on the [latest version](https://pypi.org/project/polars/) of Polars.

### Reproducible example

```python
import numpy as np
import polars as pl

empty_array = np.array([], dtype=np.int32)

pl.Series(
    name="word_id",
    values=[empty_array, empty_array],
    dtype=pl.List(pl.Int32),
)
```

### Log output

```shell
Traceback (most recent call last):
  File "tmp.py", line 6, in <module>
    pl.Series(
  File ".venv/lib/python3.11/site-packages/polars/series/series.py", line 316, in __init__
    self._s = sequence_to_pyseries(
              ^^^^^^^^^^^^^^^^^^^^^
  File ".venv/lib/python3.11/site-packages/polars/_utils/construction/series.py", line 251, in sequence_to_pyseries
    return numpy_to_pyseries(
           ^^^^^^^^^^^^^^^^^^
  File ".venv/lib/python3.11/site-packages/polars/_utils/construction/series.py", line 514, in numpy_to_pyseries
    return wrap_s(py_s).reshape(original_shape)._s
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File ".venv/lib/python3.11/site-packages/polars/series/series.py", line 7005, in reshape
    return self._from_pyseries(self._s.reshape(dimensions, is_list))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
polars.exceptions.ComputeError: cannot reshape len 0 into shape [2, 0]
```

### Issue description

The releases 0.20.27 - 0.20.29 have been yanked due to a bug in numpy processing.
Here is a bug in numpy-related code in 0.20.30.

### Expected behavior

As is 0.20.26: a Series of empty Lists.

### Installed versions

<details>

```
--------Version info---------
Polars:               0.20.30
Index type:           UInt32
Platform:             Linux-5.15.0-107-generic-x86_64-with-glibc2.31
Python:               3.11.9 (main, Apr  6 2024, 17:59:24) [GCC 9.4.0]

----Optional dependencies----
adbc_driver_manager:  <not installed>
cloudpickle:          3.0.0
connectorx:           <not installed>
deltalake:            <not installed>
fastexcel:            <not installed>
fsspec:               2024.3.1
gevent:               <not installed>
hvplot:               <not installed>
matplotlib:           3.9.0
nest_asyncio:         1.6.0
numpy:                1.26.4
openpyxl:             <not installed>
pandas:               2.2.2
pyarrow:              16.1.0
pydantic:             2.7.1
pyiceberg:            <not installed>
pyxlsb:               <not installed>
sqlalchemy:           <not installed>
torch:                2.2.2+cu121
xlsx2csv:             <not installed>
xlsxwriter:           <not installed>
```

</details>

**Comment by KDruzhkin** [comment]
This bug is present in 1.0.0.

**Comment by KDruzhkin** [comment]
With polars 1.2.0 (and python 3.12, numpy 2.0) the error message is more meaningful:
**cannot reshape array into shape containing a zero dimension after the first: (2, 0)**

```sh
Traceback (most recent call last):
  File "/Users/konstantin/Desktop/lecture/src/example.py", line 6, in <module>
    pl.Series(
  File ".venv/lib/python3.12/site-packages/polars/series/series.py", line 288, in __init__
    self._s = sequence_to_pyseries(
              ^^^^^^^^^^^^^^^^^^^^^
  File ".venv/lib/python3.12/site-packages/polars/_utils/construction/series.py", line 227, in sequence_to_pyseries
    return numpy_to_pyseries(
           ^^^^^^^^^^^^^^^^^^
  File ".venv/lib/python3.12/site-packages/polars/_utils/construction/series.py", line 478, in numpy_to_pyseries
    return wrap_s(py_s).reshape(original_shape)._s
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File ".venv/lib/python3.12/site-packages/polars/series/series.py", line 6779, in reshape
    return self._from_pyseries(self._s.reshape(dimensions))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^
polars.exceptions.InvalidOperationError:
cannot reshape array into shape containing a zero dimension after the first: (2, 0)
```

**Comment by ADraginda** [comment]
FWIW v1.2.1 (+py39 +numpy1.26.4) - issue persists

```python
pl.DataFrame({'empty_arrays': [np.array([]), np.array([])]})
```

```
polars.exceptions.InvalidOperationError: cannot reshape array into shape containing a zero dimension after the first: (2, 0)
```

**Comment by hexane360** [comment]
As of #18940 this is fixed:

```
>>> pl.DataFrame({'empty_arrays': [np.array([]), np.array([])]})
shape: (2, 1)
┌───────────────┐
│ empty_arrays  │
│ ---           │
│ array[f64, 0] │
╞═══════════════╡
│ []            │
│ []            │
└───────────────┘
```
