### ISSUE TITLE
LazyFrames containing nested List types will cause panic in `collect()`

### ISSUE THREAD

**Issue by eitsupi** [pola-rs/polars#16553]
### Checks

- [X] I have checked that this issue has not already been reported.
- [X] I have confirmed this bug exists on the [latest version](https://pypi.org/project/polars/) of Polars.

### Reproducible example

```python
>>> import polars as pl
>>> pl.LazyFrame().select(a=[[[1]]]).collect()
```

### Log output

```shell
thread '<unnamed>' panicked at /home/runner/work/polars/polars/crates/polars-core/src/series/mod.rs:149:37:
called `Result::unwrap()` on an `Err` value: InvalidOperation(ErrString("`vec_hash` operation not supported for dtype `list[list[i64]]`"))
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/rstudio/.local/lib/python3.10/site-packages/polars/lazyframe/frame.py", line 1855, in collect
    return wrap_df(ldf.collect(callback))
pyo3_runtime.PanicException: called `Result::unwrap()` on an `Err` value: InvalidOperation(ErrString("`vec_hash` operation not supported for dtype `list[list[i64]]`"))
```

### Issue description

This is in fact a Rust issue, introduced in version 0.40.0. (https://github.com/pola-rs/r-polars/pull/1104#issuecomment-2132039095)

I mistakenly thought this was an R bindings issue that did not occur in Python at first, but in fact it also occurs in Python when collecting LazyFrames.

### Expected behavior

Should not panic.

### Installed versions

<details>

```
>>> pl.show_versions()
--------Version info---------
Polars:               0.20.30
Index type:           UInt32
Platform:             Linux-5.15.146.1-microsoft-standard-WSL2-x86_64-with-glibc2.35
Python:               3.10.12 (main, Nov 20 2023, 15:14:05) [GCC 11.4.0]

----Optional dependencies----
adbc_driver_manager:  <not installed>
cloudpickle:          <not installed>
connectorx:           <not installed>
deltalake:            <not installed>
fastexcel:            <not installed>
fsspec:               <not installed>
gevent:               <not installed>
hvplot:               <not installed>
matplotlib:           <not installed>
nest_asyncio:         <not installed>
numpy:                <not installed>
openpyxl:             <not installed>
pandas:               <not installed>
pyarrow:              <not installed>
pydantic:             <not installed>
pyiceberg:            <not installed>
pyxlsb:               <not installed>
sqlalchemy:           <not installed>
torch:                <not installed>
xlsx2csv:             <not installed>
xlsxwriter:           <not installed>
```

</details>

**Comment by eitsupi** [comment]
Thanks for the quick update!
