### ISSUE TITLE
utf-8 sequence of 1 bytes from index X

### ISSUE THREAD

**Issue by 1beb** [pola-rs/polars#16612]
### Checks

- [X] I have checked that this issue has not already been reported.
- [X] I have confirmed this bug exists on the [latest version](https://pypi.org/project/polars/) of Polars.

### Reproducible example

```python
import pandas as pd
import polars as pl

file = "path/to/file"

r = pl.read_parquet(file)
```

### Log output

```shell
Traceback (most recent call last):
  File "<stdin>", line 3, in <module>
  File "/.../python3.11/site-packages/polars/io/parquet/functions.py", line 131, in read_parquet
    return pl.DataFrame._read_parquet(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/.../python3.11/site-packages/polars/dataframe/frame.py", line 859, in _read_parquet
    self._df = PyDataFrame.read_parquet(
               ^^^^^^^^^^^^^^^^^^^^^^^^^
exceptions.ArrowErrorException: OutOfSpec("In <KeyValue@b08>::value(): Invalid utf-8: invalid utf-8 sequence of 1 bytes from index 417")
```
```


### Issue description

When reading the file with `pl.read_parquet` I am unable to load the file. Interestingly, the same file opens with pandas version of read_parquet without issue. 

### Expected behavior

The file would read. I don't think this is necessarily a bug in polars, but would appreciate some guidance diagnosing the problem. My suspicion is that it's something to do with how the files were created but it strikes me that I can open the same file with `pandas.read_parquet` and `pyarrow.parquet.read_table`

### Installed versions

<details>

```
--------Version info---------
Polars:              0.19.3
Index type:          UInt32
Platform:            Linux-6.8.0-76060800daily20240311-generic-x86_64-with-glibc2.35
Python:              3.11.0rc1 (main, Aug 12 2022, 10:02:14) [GCC 11.2.0]

----Optional dependencies----
adbc_driver_sqlite:  1.0.0
cloudpickle:         2.2.1
connectorx:          0.3.3
deltalake:           0.17.4
fsspec:              2023.4.0
gevent:              23.9.0.post1
matplotlib:          3.7.1
numpy:               1.24.2
pandas:              1.5.3
pyarrow:             10.0.1
pydantic:            1.10.8
sqlalchemy:          2.0.15
xlsx2csv:            0.8.2
xlsxwriter:          3.2.0```

</details>

**Comment by ritchie46** [comment]
Can you share the file?

**Comment by 1beb** [comment]
Yes, I can but no publicly. Can I provision via email?

**Comment by ritchie46** [comment]
Please. ritchie@polars.tech

**Comment by 1beb** [comment]
Sent via email. Thank you!

**Comment by MarcoGorelli** [comment]
was this ever resolved via email? can the issue be closed?
