### ISSUE TITLE
polars >= `0.20.23` does no longer raise `FileNotFoundError` immediately for non-existing files

### ISSUE THREAD

**Issue by MaxWinterstein** [pola-rs/polars#16624]
### Checks

- [X] I have checked that this issue has not already been reported.
- [X] I have confirmed this bug exists on the [latest version](https://pypi.org/project/polars/) of Polars.

### Reproducible example

```python
>>> import polars
>>> polars.__version__
'0.20.30'
>>> foo = polars.scan_parquet("non-existing")
>>>
```

### Log output

```shell
none
```

### Issue description

Starting with `0.20.23` polars no longer raises `FileNotFound` when e.g. using `scan_parquet` with some non existing local path.

Explicit call on the returned DataFrame is needed, e.g. `.schema` will raise. 

I can't find any changelog mention that this is intentional. 

### Expected behavior

```python
FileNotFoundError: No such file or directory (os error 2): non-existing
```

Just like `0.20.22` does:

```python
>>> import polars
>>> polars.__version__
'0.20.22'
>>> foo = polars.scan_parquet("non-existing")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/max/venv/x/lib/python3.11/site-packages/polars/_utils/deprecation.py", line 134, in wrapper
    return function(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/max/venv/x/lib/python3.11/site-packages/polars/_utils/deprecation.py", line 134, in wrapper
    return function(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/max/venv/x/lib/python3.11/site-packages/polars/io/parquet/functions.py", line 394, in scan_parquet
    return _scan_parquet_impl(
           ^^^^^^^^^^^^^^^^^^^
  File "/Users/max/venv/x/lib/python3.11/site-packages/polars/io/parquet/functions.py", line 441, in _scan_parquet_impl
    scan = _scan_parquet_fsspec(source, storage_options)  # type: ignore[arg-type]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/max/venv/x/lib/python3.11/site-packages/polars/io/parquet/anonymous_scan.py", line 21, in _scan_parquet_fsspec
    schema = polars.io.parquet.read_parquet_schema(data)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/max/venv/x/lib/python3.11/site-packages/polars/io/parquet/functions.py", line 284, in read_parquet_schema
    return _read_parquet_schema(source)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: No such file or directory (os error 2): non-existing
```

### Installed versions

<details>

```
>>> pl.show_versions()
--------Version info---------
Polars:               0.20.30
Index type:           UInt32
Platform:             macOS-14.4-arm64-arm-64bit
Python:               3.11.9 (main, Apr  2 2024, 08:25:04) [Clang 15.0.0 (clang-1500.3.9.4)]

----Optional dependencies----
adbc_driver_manager:  <not installed>
cloudpickle:          3.0.0
connectorx:           <not installed>
deltalake:            <not installed>
fastexcel:            <not installed>
fsspec:               2024.5.0
gevent:               <not installed>
hvplot:               <not installed>
matplotlib:           3.9.0
nest_asyncio:         1.6.0
numpy:                1.26.4
openpyxl:             3.1.2
pandas:               2.0.3
pyarrow:              16.1.0
pydantic:             <not installed>
pyiceberg:            <not installed>
pyxlsb:               <not installed>
sqlalchemy:           2.0.30
torch:                <not installed>
xlsx2csv:             <not installed>
xlsxwriter:           <not installed>

```

</details>

**Comment by ritchie46** [comment]
It does raise, but not immediately.

```python
>>> pl.scan_parquet("non-existing").collect()
FileNotFoundError: No such file or directory (os error 2): non-existing
```

Polars will resolve queries upon collection, not upon DSL creation. This is important as we want to be able to send the query to another machine. At that point the schema will be resolved not when you write the query.
