### ISSUE TITLE
Panic when casting Array of Categoricals to Array of String

### ISSUE THREAD

**Issue by stinodego** [pola-rs/polars#16706]
### Checks

- [X] I have checked that this issue has not already been reported.
- [X] I have confirmed this bug exists on the [latest version](https://pypi.org/project/polars/) of Polars.

### Reproducible example

```python
import polars as pl

s = pl.Series([["a", "b"], ["a", "c"]], dtype=pl.Array(pl.Categorical, 2))
s.cast(pl.Array(pl.String, 2))
```

### Log output

```shell
thread '<unnamed>' panicked at crates/polars-core/src/series/from.rs:90:37:
called `Option::unwrap()` on a `None` value
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
Traceback (most recent call last):
  File "/home/stijn/code/polars/py-polars/repro.py", line 4, in <module>
    s.cast(pl.Array(pl.String, 2))
  File "/home/stijn/code/polars/py-polars/polars/series/series.py", line 4200, in cast
    return self._from_pyseries(self._s.cast(dtype, strict))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^
pyo3_runtime.PanicException: called `Option::unwrap()` on a `None` value
```

### Issue description

This cast fails when there is no reason it should. It works fine for List types.

### Expected behavior

Works.

### Installed versions

main

**Comment by ritchie46** [comment]
Ah, yes. This should be trivially fixed. We can cast the inner recursively.
