### ISSUE TITLE
suggest sql add `select sth` without a `from` syntax

### ISSUE THREAD

**Issue by l1t1** [pola-rs/polars#16826]
### Description

 

such as
select 1,select 1 as a,select 1 a
```
it isn't supported now

Polars CLI version 0.8.0
Type .help for help.
〉select 1 a;
Error: no table name provided in query
〉select 1 as a;
Error: no table name provided in query
〉select 1 ;
Error: no table name provided in query
〉create table t(a int);
Error: only CREATE TABLE AS SELECT is supported
〉create table as select 1 a;
Error: sql parser error: Expected end of statement, found: select at Line: 1, Column 17
```

**Comment by alexander-beedie** [comment]
Thanks for the suggestion 👍

**Comment by l1t1** [comment]
thanks, it works in rel. 1.0.0a1
```python
pip install polars==1.0.0a1
>>> import polars as pl
>>> sql = pl.SQLContext()
>>> sql.execute("select 1 a", eager=True)
shape: (1, 1)
┌─────┐
│ a   │
│ --- │
│ i32 │
╞═════╡
│ 1   │
└─────┘
>>> sql.execute("select * from (values(1),(2))t(i)", eager=True)
shape: (2, 1)
┌─────┐
│ i   │
│ --- │
│ i32 │
╞═════╡
│ 1   │
│ 2   │
└─────┘
```

**Comment by l1t1** [comment]
a select with an alias cannot union a select without an alias
```python
>>> sql.execute("select 1 union select 2 ", eager=True)
shape: (2, 1)
┌─────────┐
│ literal │
│ ---     │
│ i32     │
╞═════════╡
│ 1       │
│ 2       │
└─────────┘
>>> sql.execute("select 1 as a  union select 2 a", eager=True)
shape: (2, 1)
┌─────┐
│ a   │
│ --- │
│ i32 │
╞═════╡
│ 1   │
│ 2   │
└─────┘
>>>
>>> sql.execute("select 1 a union select 2", eager=True)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.10/dist-packages/polars/sql/context.py", line 436, in execute
    return res.collect() if (eager or self._eager_execution) else res
  File "/usr/local/lib/python3.10/dist-packages/polars/lazyframe/frame.py", line 1848, in collect
    return wrap_df(ldf.collect(callback))
polars.exceptions.ComputeError: schema names differ: got a, expected literal

This error occurred with the following context stack:
        [1] 'vertical concat' input failed to resolve
        [2] 'unique' input failed to resolve

>>> sql.execute("select 1 as a  union select 2", eager=True)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.10/dist-packages/polars/sql/context.py", line 436, in execute
    return res.collect() if (eager or self._eager_execution) else res
  File "/usr/local/lib/python3.10/dist-packages/polars/lazyframe/frame.py", line 1848, in collect
    return wrap_df(ldf.collect(callback))
polars.exceptions.ComputeError: schema names differ: got a, expected literal

This error occurred with the following context stack:
        [1] 'vertical concat' input failed to resolve
        [2] 'unique' input failed to resolve
```

**Comment by l1t1** [comment]
union different aliases also got error, so does `union all`
```python
>>> sql.execute("select 1 as a  union select 2 b", eager=True)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.10/dist-packages/polars/sql/context.py", line 436, in execute
    return res.collect() if (eager or self._eager_execution) else res
  File "/usr/local/lib/python3.10/dist-packages/polars/lazyframe/frame.py", line 1848, in collect
    return wrap_df(ldf.collect(callback))
polars.exceptions.ComputeError: schema names differ: got a, expected b

This error occurred with the following context stack:
        [1] 'vertical concat' input failed to resolve
        [2] 'unique' input failed to resolve

>>> sql.execute("select 1 as a  union all select 2 b", eager=True)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.10/dist-packages/polars/sql/context.py", line 436, in execute
    return res.collect() if (eager or self._eager_execution) else res
  File "/usr/local/lib/python3.10/dist-packages/polars/lazyframe/frame.py", line 1848, in collect
    return wrap_df(ldf.collect(callback))
polars.exceptions.ComputeError: schema names differ: got a, expected b
```
