### ISSUE TITLE
polars.exceptions.SchemaError: type Int64 is incompatible with expected type Int32

### ISSUE THREAD

**Issue by eromoe** [pola-rs/polars#16863]
### Checks

- [X] I have checked that this issue has not already been reported.
- [X] I have confirmed this bug exists on the [latest version](https://pypi.org/project/polars/) of Polars.

### Reproducible example

```
import polars as pl
df = pl.DataFrame(dict(a=1))
df1 = df.with_columns(b=pl.lit(0))
df2 = df.with_columns(b=pl.col('a') -1)
df3 = pl.concat([df1, df2])
```

### Log output

```shell
Traceback (most recent call last):
  File "E:\Workspace\github_me\data_dumper\data_dumper\qmt\etl_polars.py", line 416, in <module>
    main2()
  File "C:\envs\quant\lib\site-packages\click\core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
  File "C:\envs\quant\lib\site-packages\click\core.py", line 1078, in main
    rv = self.invoke(ctx)
  File "C:\envs\quant\lib\site-packages\click\core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "C:\envs\quant\lib\site-packages\click\core.py", line 783, in invoke
    return __callback(*args, **kwargs)
  File "E:\Workspace\github_me\data_dumper\data_dumper\qmt\etl_polars.py", line 409, in main2
    df2 = df1.collect()
  File "C:\envs\quant\lib\site-packages\polars\lazyframe\frame.py", line 1967, in collect
    return wrap_df(ldf.collect(callback))
polars.exceptions.SchemaError: type Int64 is incompatible with expected type Int32
```
```


### Issue description

I have a piece of code like below

```python

    df_0930 = df.filter((pl.col('time') % 86400) == 34200)
    df_0930 = (
        df_0930.with_columns(time_id=pl.col('time'))
        .with_columns(seconds=pl.lit(0))
    )

    df = df.filter((pl.col('time') % 86400) > 34200)
    
    df = (
        df.with_columns(time_id =(pl.col('time') - 1) // window *  window)
        .with_columns(seconds=pl.col('time') - pl.col('time_id'))
    )

    df = pl.concat([df_0930, df])

```

This is fine on two month ago , but got error in recent version.
Have to add type declartion to `pl.lit`
```
.with_columns(seconds=pl.lit(0, dtype=pl.Int64))
```

### Expected behavior

No need to declare type explicitly

### Installed versions

<details>

```
polars                    0.20.31
```

</details>

**Comment by ritchie46** [comment]
Can you create a minimal repro please?

**Comment by eromoe** [comment]
@ritchie46 updated

**Comment by cmdlineluser** [comment]
I'm not sure what previous version you were using, but the minimal example produces an error going back to version `0.18.0` in my testing.

The `vertical_relaxed` concat strategy was introduced to allow supertype coercion, which could possibly be used:

```python
df = pl.concat([df_0930, df], how='vertical_relaxed')
```

You may also be able to do it without concat.

It seems you're doing something along the lines of:

```python
df.with_columns(
    pl.when((pl.col('time') % 86400) == 34200)
      .then(pl.struct(time_id='time', seconds=0))
      .when((pl.col('time') % 86400) > 34200)
      .then(pl.struct(
          time_id = (pl.col('time') - 1) // window *  window,
          seconds = pl.col('time') - ((pl.col('time') - 1) // window *  window)
      ))
      .struct.field('*')
)
```

**Comment by eromoe** [comment]
I used the latest version and got this error :

```
In [8]: pl.__version__
Out[8]: '0.20.31'
```


And,  I had never seen `.struct.field('*')` before, learn a new way, thanks .  
Though, I think  the `concat` way is easier to read, the dtype automatically convertion should be enabled by default,  it is really inconvenient to located which columns of which dfs are different.

**Comment by MarcoGorelli** [comment]
thanks for the report - this looks expected, closing then
