### ISSUE TITLE
read_json unable to parse json list of lists, and doesn't respect documented schema arguments

### ISSUE THREAD

**Issue by NSchrading** [pola-rs/polars#16911]
### Checks

- [X] I have checked that this issue has not already been reported.
- [X] I have confirmed this bug exists on the [latest version](https://pypi.org/project/polars/) of Polars.

### Reproducible example

```python

import polars as pl
from io import StringIO

example_json = """
[
["2024-05-15T23:59:00Z",-0.512,null,null,null,"a"],
["2024-05-15T23:59:01Z",-0.5,null,null,null,"a"],
["2024-05-15T23:59:00Z",0.4,null,null,null,"b"]
]
"""

pl.read_json(StringIO(example_json))
```

```python-traceback
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\NSchr\Programming\temp\venv\lib\site-packages\polars\io\json.py", line 94, in read_json
    pydf = PyDataFrame.read_json(
RuntimeError: BindingsError: "can only deserialize json objects"
```

```python

# change value array, make one of the other fields non-null, same error
example_json = """
[
["2024-05-15T23:59:00Z",-0.512,null,null,null,"a"],
["2024-05-15T23:59:01Z",-0.5,null,null,null,"a"],
["2024-05-15T23:59:00Z",null,true,null,null,"b"]
]
"""
pl.read_json(StringIO(example_json))
```

```python-traceback
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\NSchr\Programming\temp\venv\lib\site-packages\polars\io\json.py", line 94, in read_json
    pydf = PyDataFrame.read_json(
RuntimeError: BindingsError: "can only deserialize json objects"
```

```python

# remove nulls. same error
example_json = """
[
["2024-05-15T23:59:00Z",-0.512,"a"],
["2024-05-15T23:59:01Z",-0.5,"a"],
["2024-05-15T23:59:00Z",true,"b"]
]
"""
pl.read_json(StringIO(example_json))
```

```python-traceback
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\NSchr\Programming\temp\venv\lib\site-packages\polars\io\json.py", line 94, in read_json
    pydf = PyDataFrame.read_json(
RuntimeError: BindingsError: "can only deserialize json objects"
```

```python

# try with a schema for the column names
# fails despite documentation saying you can pass a list of column names
pl.read_json(StringIO(example_json), schema=["col1", "col2", "col3"])
```

```python-traceback
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\NSchr\Programming\temp\venv\lib\site-packages\polars\io\json.py", line 94, in read_json
    pydf = PyDataFrame.read_json(
TypeError: argument 'schema': 'list' object cannot be converted to 'PyDict'
```

```python

# try with ndjson
example_json = """
["2024-05-15T23:59:00Z",-0.512,null,null,null,"a"]
["2024-05-15T23:59:01Z",-0.5,null,null,null,"a"]
["2024-05-15T23:59:00Z",null,true,null,null,"b"]
"""

pl.read_ndjson(StringIO(example_json))
"""


```python-traceback
thread '<unnamed>' panicked at crates\polars-arrow\src\array\struct_\mod.rs:239:41:
called `Result::unwrap()` on an `Err` value: ComputeError(ErrString("Struct array must be created with a DataType whose physical type is Struct"))
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\NSchr\Programming\temp\venv\lib\site-packages\polars\io\ndjson.py", line 77, in read_ndjson
    pydf = PyDataFrame.read_ndjson(
pyo3_runtime.PanicException: called `Result::unwrap()` on an `Err` value: ComputeError(ErrString("Struct array must be created with a DataType whose physical type is Struct"))
```

### Issue description

Polars is unable to parse a valid json list of lists. See the reproducible examples. It also doesn't support a schema with a list of column names despite the documentation saying so: https://docs.pola.rs/api/python/stable/reference/api/polars.read_json.html:

```
As a list of column names; in this case types are automatically inferred.
```

### Expected behavior

Expected behavior is something like pandas:

```python

import pandas as pd

example_json = """
[
["2024-05-15T23:59:00Z",-0.512,null,null,null,"a"],
["2024-05-15T23:59:01Z",-0.5,null,null,null,"a"],
["2024-05-15T23:59:00Z",0.4,null,null,null,"b"]
]
"""

pd.read_json(StringIO(example_json))
```

```
                      0      1   2   3   4  5
0  2024-05-15T23:59:00Z -0.512 NaN NaN NaN  a
1  2024-05-15T23:59:01Z -0.500 NaN NaN NaN  a
2  2024-05-15T23:59:00Z  0.400 NaN NaN NaN  b
```

If provided a schema with column names they would be set appropriately instead of 0-5.

### Installed versions

<details>

```
>>> pl.show_versions()
--------Version info---------
Polars:               0.20.31
Index type:           UInt32
Platform:             Windows-10-10.0.19045-SP0
Python:               3.9.7 (tags/v3.9.7:1016ef3, Aug 30 2021, 20:19:38) [MSC v.1929 64 bit (AMD64)]

----Optional dependencies----
adbc_driver_manager:  <not installed>
cloudpickle:          <not installed>
connectorx:           <not installed>
deltalake:            <not installed>
fastexcel:            <not installed>
fsspec:               <not installed>
gevent:               <not installed>
hvplot:               <not installed>
matplotlib:           <not installed>
nest_asyncio:         <not installed>
numpy:                1.24.2
openpyxl:             <not installed>
pandas:               2.0.0
pyarrow:              <not installed>
pydantic:             <not installed>
pyiceberg:            <not installed>
pyxlsb:               <not installed>
sqlalchemy:           <not installed>
torch:                <not installed>
xlsx2csv:             <not installed>
xlsxwriter:           <not installed>
```

</details>

**Comment by stinodego** [comment]
I don't think that's valid JSON... :thinking:

**Comment by NSchrading** [comment]
I wouldn't expect python's builtin json parser or pandas to parse it if it wasn't valid json:

```python
>>> example_json = """
... [
... ["2024-05-15T23:59:00Z",-0.512,null,null,null,"a"],
... ["2024-05-15T23:59:01Z",-0.5,null,null,null,"a"],
... ["2024-05-15T23:59:00Z",0.4,null,null,null,"b"]
... ]
... """
>>>
>>> json.loads(example_json)
[['2024-05-15T23:59:00Z', -0.512, None, None, None, 'a'], ['2024-05-15T23:59:01Z', -0.5, None, None, None, 'a'], ['2024-05-15T23:59:00Z', 0.4, None, None, None, 'b']]
```

It also passes online json lint/validators, e.g. https://jsonlint.com/. I believe according to the json spec these are valid json arrays: 

```
JSON is built on two structures:

A collection of name/value pairs. In various languages, this is realized as an object, record, struct, dictionary, hash table, keyed list, or associative array.
An ordered list of values. In most languages, this is realized as an array, vector, list, or sequence.
```

https://www.json.org/json-en.html

**Comment by cmdlineluser** [comment]
It is valid json, but it is problematic.

Pandas appears to explode the list and then "unnest" the values.

```python
>>> pd.read_json(StringIO(example_json))
#                       0      1   2   3   4  5
# 0  2024-05-15T23:59:00Z -0.512 NaN NaN NaN  a
# 1  2024-05-15T23:59:01Z -0.500 NaN NaN NaN  a
# 2  2024-05-15T23:59:00Z  0.400 NaN NaN NaN  b
```

If we use `.str.json_decode()` - we can see it is parsed as valid:

```python
>>> pl.select(pl.lit(example_json).str.json_decode())
# shape: (1, 1)
# ┌─────────────────────────────────┐
# │ literal                         │
# │ ---                             │
# │ list[list[str]]                 │
# ╞═════════════════════════════════╡
# │ [["2024-05-15T23:59:00Z", "-0.… │
# └─────────────────────────────────┘
```

But as lists are homogeneous in Polars, everything has been coerced into Strings.

```python
>>> (pl.select(pl.lit(example_json).str.json_decode().flatten())
...    .select(cols = pl.all().list.to_struct("max_width"))
...    .unnest("cols")
... )
# shape: (3, 6)
# ┌──────────────────────┬─────────┬─────────┬─────────┬─────────┬─────────┐
# │ field_0              ┆ field_1 ┆ field_2 ┆ field_3 ┆ field_4 ┆ field_5 │
# │ ---                  ┆ ---     ┆ ---     ┆ ---     ┆ ---     ┆ ---     │
# │ str                  ┆ str     ┆ str     ┆ str     ┆ str     ┆ str     │
# ╞══════════════════════╪═════════╪═════════╪═════════╪═════════╪═════════╡
# │ 2024-05-15T23:59:00Z ┆ -0.512  ┆ null    ┆ null    ┆ null    ┆ a       │
# │ 2024-05-15T23:59:01Z ┆ -0.5    ┆ null    ┆ null    ┆ null    ┆ a       │
# │ 2024-05-15T23:59:00Z ┆ 0.4     ┆ null    ┆ null    ┆ null    ┆ b       │
# └──────────────────────┴─────────┴─────────┴─────────┴─────────┴─────────┘
```

It seems that when reading from a file, only JSON objects are considered valid?

**Comment by eckertliam** [comment]
Has anyone found a fix or workaround for this? I'm working with an API that gives me a JSON list similar to the initial example. It is valid JSON but Polars does not accept it

**Comment by cmdlineluser** [comment]
I think you'd need to manually wrap it in `{}`

```python
>>> pl.read_json(f"""{{"result":{example_json}}}""".encode())
# shape: (1, 1)
# ┌─────────────────────────────────┐
# │ result                          │
# │ ---                             │
# │ list[list[str]]                 │
# ╞═════════════════════════════════╡
# │ [["2024-05-15T23:59:00Z", "-0.… │
# └─────────────────────────────────┘
```

Or use `.str.json_decode()`

```python
>>> pl.select(pl.lit(example_json).str.json_decode())
# shape: (1, 1)
# ┌─────────────────────────────────┐
# │ literal                         │
# │ ---                             │
# │ list[list[str]]                 │
# ╞═════════════════════════════════╡
# │ [["2024-05-15T23:59:00Z", "-0.… │
# └─────────────────────────────────┘
```
