### ISSUE TITLE
Panic when sorting DataFrame by Null column

### ISSUE THREAD

**Issue by stinodego** [pola-rs/polars#17007]
### Checks

- [X] I have checked that this issue has not already been reported.
- [X] I have confirmed this bug exists on the [latest version](https://pypi.org/project/polars/) of Polars.

### Reproducible example

```python
import polars as pl

df = pl.DataFrame({"a": [None], "b": [1]})
result = df.sort("a")
print(result)
```

### Log output

```shell
thread '<unnamed>' panicked at crates/polars-core/src/series/series_trait.rs:363:9:
`arg_sort` operation not supported for dtype `null`
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
Traceback (most recent call last):
  File "/home/stijn/code/polars/py-polars/repro.py", line 9, in <module>
    result = df.sort("a")
             ^^^^^^^^^^^^
  File "/home/stijn/code/polars/py-polars/polars/dataframe/frame.py", line 4727, in sort
    .collect(_eager=True)
     ^^^^^^^^^^^^^^^^^^^^
  File "/home/stijn/code/polars/py-polars/polars/lazyframe/frame.py", line 1896, in collect
    return wrap_df(ldf.collect(callback))
                   ^^^^^^^^^^^^^^^^^^^^^
pyo3_runtime.PanicException: `arg_sort` operation not supported for dtype `null`
```

### Issue description

Sorting panics when sorting by a Null column.

There is no issue if the null column is the only column being sorted.

The same happens when sorting a Struct Series, though this gives a proper error (should still just work though):

```python
s = pl.Series([{"a": None, "b": 1}])
result = s.sort()
```
```
Traceback (most recent call last):
  File "/home/stijn/code/polars/py-polars/repro.py", line 8, in <module>
    result = s.sort()
             ^^^^^^^^
  File "/home/stijn/code/polars/py-polars/polars/series/series.py", line 3148, in sort
    self._s.sort(descending, nulls_last, multithreaded)
polars.exceptions.InvalidOperationError: `arg_sort_multiple` operation not supported for dtype `null
```

### Expected behavior

Sorting should complete successfully.

### Installed versions

main

**Comment by ritchie46** [comment]
Ah, can be a trivial clone in that case.

**Comment by KilianKW** [comment]
I think there is a similar issue (maybe with same root cause) related to this:

```python
df = pl.DataFrame({"a": [1], "b": [None]})
result = df.sort(["a", "b"])
```
leads to 
```
pyo3_runtime.PanicException: `into_total_ord_inner` operation not supported for dtype `null`
```
Furthermore,
```python
df = pl.DataFrame({"a": [1], "b": [None]})
result = df.sort(["a", "b"], nulls_last=True)
```
leads to 
```
pyo3_runtime.PanicException: not implemented: Null
```

**Comment by vincent-octo** [comment]
Has this fix been released?

I am encountering the issue in v1.22:


```
In [1]: import polars as pl

In [2]: pl.__version__
Out[2]: '1.22.0'

In [3]: df = pl.DataFrame({"a": [1], "b": [None]})
   ...: result = df.sort(["a", "b"])

thread '<unnamed>' panicked at crates/polars-core/src/series/implementations/null.rs:88:9:
`into_total_ord_inner` operation not supported for dtype `null`
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
---------------------------------------------------------------------------
PanicException                            Traceback (most recent call last)
Cell In[3], line 2
      1 df = pl.DataFrame({"a": [1], "b": [None]})
----> 2 result = df.sort(["a", "b"])

File ~/.cache/uv/archive-v0/EuJjXbsW6RvT2rhmiWSry/lib/python3.13/site-packages/polars/dataframe/frame.py:5406, in DataFrame.sort(self, by, descending, nulls_las
t, multithreaded, maintain_order, *more_by)
   5301 def sort(
   5302     self,
   5303     by: IntoExpr | Iterable[IntoExpr],
   (...)
   5308     maintain_order: bool = False,
   5309 ) -> DataFrame:
   5310     """
   5311     Sort the dataframe by the given columns.
   5312
   (...)
   5394     └──────┴─────┴─────┘
   5395     """
   5396     return (
   5397         self.lazy()
   5398         .sort(
   5399             by,
   5400             *more_by,
   5401             descending=descending,
   5402             nulls_last=nulls_last,
   5403             multithreaded=multithreaded,
   5404             maintain_order=maintain_order,
   5405         )
-> 5406         .collect(_eager=True)
   5407     )

File ~/.cache/uv/archive-v0/EuJjXbsW6RvT2rhmiWSry/lib/python3.13/site-packages/polars/lazyframe/frame.py:2066, in LazyFrame.collect(self, type_coercion, _type_check, predicate_pushdown, projection_pushdown, simplify_expression, slice_pushdown, comm_subplan_elim, comm_subexpr_elim, cluster_with_columns, collapse_joins, no_optimization, streaming, engine, background, _check_order, _eager, **_kwargs)
   2064 # Only for testing purposes
   2065 callback = _kwargs.get("post_opt_callback", callback)
-> 2066 return wrap_df(ldf.collect(callback))

PanicException: `into_total_ord_inner` operation not supported for dtype `null`
```
