### ISSUE TITLE
`join` on a `literal` causes segfault when either frame has 0 rows.

### ISSUE THREAD

**Issue by cmdlineluser** [pola-rs/polars#17027]
### Checks

- [X] I have checked that this issue has not already been reported.
- [X] I have confirmed this bug exists on the [latest version](https://pypi.org/project/polars/) of Polars.

### Reproducible example

```python
import polars as pl

df1 = pl.DataFrame({"a": [1]})
df2 = pl.DataFrame(schema={"b": pl.Int64})

df1.join(df2, on=pl.lit("c"))
# zsh: segmentation fault 
```

### Log output

```shell
join parallel: true
```

### Issue description

Just while trying to reproduce https://github.com/pola-rs/polars/issues/9711 I ended up with a segfault for a reduced example.

### Expected behavior

No segfault.

### Installed versions

<details>

```
--------Version info---------
Polars:               1.0.0-alpha.1
Index type:           UInt32
Platform:             macOS-13.6.1-arm64-arm-64bit
Python:               3.12.2 (main, Feb  6 2024, 20:19:44) [Clang 15.0.0 (clang-1500.1.0.2.5)]

----Optional dependencies----
adbc_driver_manager:  <not installed>
cloudpickle:          <not installed>
connectorx:           <not installed>
deltalake:            <not installed>
fastexcel:            <not installed>
fsspec:               <not installed>
gevent:               <not installed>
hvplot:               <not installed>
matplotlib:           <not installed>
nest_asyncio:         <not installed>
numpy:                1.26.4
openpyxl:             <not installed>
pandas:               2.2.1
pyarrow:              15.0.2
pydantic:             <not installed>
pyiceberg:            <not installed>
sqlalchemy:           <not installed>
torch:                <not installed>
xlsx2csv:             <not installed>
xlsxwriter:           <not installed>
```

</details>

**Comment by coastalwhite** [comment]
Here is a backtrace of the `get_unchecked` going wrong.

```
thread 'polars-0' panicked at library/core/src/panicking.rs:219:5:
unsafe precondition(s) violated: slice::get_unchecked requires that the index is within the slice
stack backtrace:
   0: rust_begin_unwind
             at /rustc/ab14f944afe4234db378ced3801e637eae6c0f30/library/std/src/panicking.rs:652:5
   1: core::panicking::panic_nounwind_fmt::runtime
             at /rustc/ab14f944afe4234db378ced3801e637eae6c0f30/library/core/src/panicking.rs:110:18
   2: core::panicking::panic_nounwind_fmt
             at /rustc/ab14f944afe4234db378ced3801e637eae6c0f30/library/core/src/panicking.rs:120:5
   3: core::panicking::panic_nounwind
             at /rustc/ab14f944afe4234db378ced3801e637eae6c0f30/library/core/src/panicking.rs:219:5
   4: <usize as core::slice::index::SliceIndex<[T]>>::get_unchecked::precondition_check
             at /rustc/ab14f944afe4234db378ced3801e637eae6c0f30/library/core/src/ub_checks.rs:68:21
   5: <usize as core::slice::index::SliceIndex<[T]>>::get_unchecked
             at /rustc/ab14f944afe4234db378ced3801e637eae6c0f30/library/core/src/ub_checks.rs:75:17
   6: core::slice::<impl [T]>::get_unchecked
             at /rustc/ab14f944afe4234db378ced3801e637eae6c0f30/library/core/src/slice/mod.rs:686:20
   7: polars_core::chunked_array::ops::gather::gather_idx_array_unchecked::{{closure}}
             at ./crates/polars-core/src/chunked_array/ops/gather.rs:126:24
   8: core::ops::function::impls::<impl core::ops::function::FnOnce<A> for &mut F>::call_once
             at /rustc/ab14f944afe4234db378ced3801e637eae6c0f30/library/core/src/ops/function.rs:305:13
   9: core::option::Option<T>::map
             at /rustc/ab14f944afe4234db378ced3801e637eae6c0f30/library/core/src/option.rs:1072:29
```
