### ISSUE TITLE
sql conbine CTE and cross join leads to internal error

### ISSUE THREAD

**Issue by l1t1** [pola-rs/polars#17056]
### Checks

- [X] I have checked that this issue has not already been reported.
- [X] I have confirmed this bug exists on the [latest version](https://pypi.org/project/polars/) of Polars.

### Reproducible example

```python
>>> import polars as pl
>>> pl.__version__
'1.0.0-beta.1'
>>> sql = pl.SQLContext()
>>> sql.execute("with t as (select a from (values(1),(2))t1(a))select * from t cross join t", eager=True)
thread '<unnamed>' panicked at crates\polars-lazy\src\physical_plan\planner\lp.rs:616:20:
internal error: entered unreachable code
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Python312\Lib\site-packages\polars\sql\context.py", line 437, in execute
    return res.collect() if (eager or self._eager_execution) else res
           ^^^^^^^^^^^^^
  File "C:\Python312\Lib\site-packages\polars\lazyframe\frame.py", line 1896, in collect
    return wrap_df(ldf.collect(callback))
                   ^^^^^^^^^^^^^^^^^^^^^
pyo3_runtime.PanicException: internal error: entered unreachable code

```

### Issue description

I use a CTE table to cross join itself, it raise errors.

### Expected behavior

it returns value same as following two sql commands
```sql
>>> sql.execute("create table t as with t as (select a from (values(1),(2))t1(a))select * from t", eager=True)
shape: (1, 1)
┌──────────────┐
│ Response     │
│ ---          │
│ str          │
╞══════════════╡
│ CREATE TABLE │
└──────────────┘
>>> sql.execute("select * from t cross join t", eager=True)
shape: (4, 2)
┌─────┬─────┐
│ a   ┆ a:t │
│ --- ┆ --- │
│ i32 ┆ i32 │
╞═════╪═════╡
│ 1   ┆ 1   │
│ 1   ┆ 2   │
│ 2   ┆ 1   │
│ 2   ┆ 2   │
└─────┴─────┘
```

### Installed versions

<details>

```
>>> pl.show_versions()
--------Version info---------
Polars:               1.0.0-beta.1
Index type:           UInt32
Platform:             Windows-10-10.0.19045-SP0
Python:               3.12.2 (tags/v3.12.2:6abddd9, Feb  6 2024, 21:26:36) [MSC v.1937 64 bit (AMD64)]

----Optional dependencies----
adbc_driver_manager:  <not installed>
cloudpickle:          <not installed>
connectorx:           <not installed>
deltalake:            <not installed>
fastexcel:            <not installed>
fsspec:               <not installed>
gevent:               <not installed>
great_tables:         <not installed>
hvplot:               <not installed>
matplotlib:           <not installed>
nest_asyncio:         <not installed>
numpy:                1.26.4
openpyxl:             <not installed>
pandas:               <not installed>
pyarrow:              16.0.0
pydantic:             <not installed>
pyiceberg:            <not installed>
sqlalchemy:           <not installed>
torch:                <not installed>
xlsx2csv:             <not installed>
xlsxwriter:           <not installed>
```

</details>

**Comment by Darcy-Linde** [comment]
I have a similar issue and it looks like the issue starts on version 0.20.31 because my code works until version 0.20.30. There was a change made to the join function in the 0.20.31 release as well -> https://github.com/pola-rs/polars/pull/16507/commits/17ab6662c3c465bfee3456ed668e021efc322cf5
