### ISSUE TITLE
Cannot chain over() and list.set_intersection() in polars-1.0.0beta1 (works in 0.20.31)

### ISSUE THREAD

**Issue by ruomad** [pola-rs/polars#17129]
### Checks

- [X] I have checked that this issue has not already been reported.
- [X] I have confirmed this bug exists on the [latest version](https://pypi.org/project/polars/) of Polars.

### Reproducible example

```python
df = pl.DataFrame({
	"a": [1, 2, 2, 3, 3],
	"b": [2, 2, 4, 7, 8]
	})

df.with_columns(
      pl.col("b")
	 .over("a", mapping_strategy = 'join')
	 .list.set_intersection([4, 8])
         .alias("intersect")
	)
```
yields expected result in polars 0.20.31 :
```
shape: (5, 3)
┌─────┬─────┬───────────┐
│ a   ┆ b   ┆ intersect │
│ --- ┆ --- ┆ ---       │
│ i64 ┆ i64 ┆ list[i64] │
╞═════╪═════╪═══════════╡
│ 1   ┆ 2   ┆ []        │
│ 2   ┆ 2   ┆ [4]       │
│ 2   ┆ 4   ┆ [4]       │
│ 3   ┆ 7   ┆ [8]       │
│ 3   ┆ 8   ┆ [8]       │
└─────┴─────┴───────────┘
```
but fails in 1.0.0beta1 with :
```
Traceback (most recent call last):
  File "...\Lib\site-packages\polars\dataframe\frame.py", line 8592, in with_columns
    return self.lazy().with_columns(*exprs, **named_exprs).collect(_eager=True)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "...\Lib\site-packages\polars\lazyframe\frame.py", line 1896, in collect
    return wrap_df(ldf.collect(callback))
                   ^^^^^^^^^^^^^^^^^^^^^
polars.exceptions.InvalidOperationError: could not determine supertype of: [i64, list[i64]]
```

### Issue description

Chaining over() and list.set_intersection() in the same expression works in 0.20.31 but fails in 1.0.0beta1

It works though if the operations are not directly chained :
```
(df.with_columns(
      pl.col("b")
	.over("a", mapping_strategy = 'join')
      )
   .with_columns(
      pl.col("b")
	.list.set_intersection([4, 8])
        .alias("intersect")
      )
)
```
Is this expected ?

### Expected behavior

No error and correct result

### Installed versions

<details>

```
--------Version info---------
Polars:               1.0.0-beta.1
Index type:           UInt32
Platform:             Windows-10-10.0.19045-SP0
Python:               3.12.4 (tags/v3.12.4:8e8a4ba, Jun  6 2024, 19:30:16) [MSC v.1940 64 bit (AMD64)]

----Optional dependencies----
adbc_driver_manager:  <not installed>
cloudpickle:          <not installed>
connectorx:           <not installed>
deltalake:            <not installed>
fastexcel:            <not installed>
fsspec:               2024.6.0
gevent:               <not installed>
great_tables:         <not installed>
hvplot:               <not installed>
matplotlib:           <not installed>
nest_asyncio:         <not installed>
numpy:                1.26.4
openpyxl:             <not installed>
pandas:               <not installed>
pyarrow:              16.1.0
pydantic:             <not installed>
pyiceberg:            <not installed>
sqlalchemy:           <not installed>
torch:                <not installed>
xlsx2csv:             <not installed>
xlsxwriter:           3.2.0
```

</details>

**Comment by stinodego** [comment]
Thanks for the report. This must be a byproduct of https://github.com/pola-rs/polars/pull/16918
