### ISSUE TITLE
Cannot instantiate Series of type List(UInt64) with large integer value

### ISSUE THREAD

**Issue by stinodego** [pola-rs/polars#17231]
### Checks

- [X] I have checked that this issue has not already been reported.
- [X] I have confirmed this bug exists on the [latest version](https://pypi.org/project/polars/) of Polars.

### Reproducible example

```python
import polars as pl

values = [{"f0": 0, "f1": [9223372036854775808]}]
dtype = pl.Struct({"f0": pl.Int64, "f1": pl.List(pl.UInt64)})

s = pl.Series(values, dtype=dtype)
print(s)
```

### Log output

```shell
Traceback (most recent call last):
  File "/home/stijn/code/polars/py-polars/repro.py", line 8, in <module>
    s = pl.Series(values, dtype=dtype)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/stijn/code/polars/py-polars/polars/series/series.py", line 287, in __init__
    self._s = sequence_to_pyseries(
              ^^^^^^^^^^^^^^^^^^^^^
  File "/home/stijn/code/polars/py-polars/polars/_utils/construction/series.py", line 154, in sequence_to_pyseries
    return plc.sequence_to_pydf(
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/stijn/code/polars/py-polars/polars/_utils/construction/dataframe.py", line 459, in sequence_to_pydf
    return _sequence_to_pydf_dispatcher(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/stijn/.pyenv/versions/3.12.3/lib/python3.12/functools.py", line 909, in wrapper
    return dispatch(args[0].__class__)(*args, **kw)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/stijn/code/polars/py-polars/polars/_utils/construction/dataframe.py", line 697, in _sequence_of_dict_to_pydf
    pydf = PyDataFrame.from_dicts(
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/stijn/code/polars/py-polars/polars/series/series.py", line 287, in __init__
    self._s = sequence_to_pyseries(
              ^^^^^^^^^^^^^^^^^^^^^
  File "/home/stijn/code/polars/py-polars/polars/_utils/construction/series.py", line 281, in sequence_to_pyseries
    return _construct_series_with_fallbacks(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/stijn/code/polars/py-polars/polars/_utils/construction/series.py", line 296, in _construct_series_with_fallbacks
    return constructor(name, values, strict)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
OverflowError: Python int too large to convert to C long
```

### Issue description

The Series constructor fails when it should succeed. It seems to be using Int64 when it should be using UInt64.

### Expected behavior

Succeeds

### Installed versions

main

**Comment by coastalwhite** [comment]
Related repro: 

```python
import polars as pl
pl.Series([0] * 25 + [9223372036854775808])
```
