### ISSUE TITLE
SchemaError for Non-Exiting dtype on Concat

### ISSUE THREAD

**Issue by starzar** [pola-rs/polars#17300]
### Checks

- [X] I have checked that this issue has not already been reported.
- [X] I have confirmed this bug exists on the [latest version](https://pypi.org/project/polars/) of Polars.

### Reproducible example

```import polars as pl
dfAnalysis_total = pl.DataFrame()
df_1 = 18-06-2024(CotFinancials)_dfAnalysis_cur
df_2 = 25-06-2024(CotFinancials)_dfAnalysis_cur
df_list =  [df_1,df_2]

for df_cur in range(df_list):
    # SchemaError: type; Int64 is incompatible with expected type Float64
    # But I64 does not exist in any of the concatenated dataframes
    dfAnalysis_total = pl.concat([dfAnalysis_total,df_cur],how="diagonal_relaxed")

```

### Log output

```shell
Traceback (most recent call last):
  File "C:\Users\User_0\Documents\Code\Python\NseScraping\Others\CotReport\py\cotAnalysis_financials.py", line 219, in txt_to_df
    cotSoloAnalysis(cot_df_total.with_row_index(),fileName)
  File "C:\Users\User_0\Documents\Code\Python\NseScraping\Others\CotReport\py\cotAnalysis_financials.py", line 437, in cotSoloAnalysis
    dfAnalysis_total = pl.concat(items = [dfAnalysis_total,dfAnalysis_cur],how="diagonal")
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\User_0\AppData\Local\Programs\Python\Python312\Lib\site-packages\polars\functions\eager.py", line 196, in concat
    out = wrap_df(plr.concat_df_diagonal(elems))
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
polars.exceptions.SchemaError: type Int64 is incompatible with expected type Float64
```

### Issue description

 [https://drive.google.com/file/d/1x182gU8SwwcuHtXGom8JsGC1kuIUC_Br/view?usp=sharing](IMAGE)
    I64 does not exist in any of the concatenated dataframes but polars gives  **" SchemaError: type; Int64 is incompatible with expected type Float64"**

### Expected behavior

I64 should not shown as a dtype at all.

### Installed versions

<details>

```
polars 0.20.31
```

</details>

**Comment by ritchie46** [comment]
Can you create a reproducible example?

**Comment by starzar** [comment]
Since this error is given on pl.concat([df1.df2],how= "diagonal_relaxed") , **_is it possible to output the 'INDEX' at which the schema error  occurs?_** 
Traceback error -
```
Traceback (most recent call last):
  File "C:\Users\User_0\Documents\Code\Python\NseScraping\Others\CotReport\py\cotAnalysis_financials.py", line 439, in cotSoloAnalysis
    dfAnalysis_total = pl.concat(items = [dfAnalysis_total,dfAnalysis_cur],how="diagonal")
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\User_0\AppData\Local\Programs\Python\Python312\Lib\site-packages\polars\functions\eager.py", line 196, in concat
    out = wrap_df(plr.concat_df_diagonal(elems))
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
polars.exceptions.SchemaError: type Int64 is incompatible with expected type Float64
Traceback (most recent call last):
  File "C:\Users\User_0\Documents\Code\Python\NseScraping\Others\CotReport\py\cotAnalysis_financials.py", line 439, in cotSoloAnalysis
    dfAnalysis_total = pl.concat(items = [dfAnalysis_total,dfAnalysis_cur],how="diagonal")
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\User_0\AppData\Local\Programs\Python\Python312\Lib\site-packages\polars\functions\eager.py", line 196, in concat
    out = wrap_df(plr.concat_df_diagonal(elems))
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
polars.exceptions.SchemaError: type Int64 is incompatible with expected type Float64  
```

**Comment by cmdlineluser** [comment]
@starzar You'll need to provide a full code example in order for other people to run it and reproduce the problem.
