### ISSUE TITLE
min/max operations on i16 list with None elements

### ISSUE THREAD

**Issue by kgv** [pola-rs/polars#17310]
### Checks

- [X] I have checked that this issue has not already been reported.
- [X] I have confirmed this bug exists on the [latest version](https://crates.io/crates/polars) of Polars.

### Reproducible example

```rust
let df = df! {
    "List" => [Series::from_iter([None::<i16>, None, None])],
    // "List" => [Series::from_iter([None::<i32>, None, None])],
}?;
println!("df: {df}");
let df = df
    .lazy()
    .with_columns([
        col("List").list().min().name().suffix(".Min"), // if i16 - Err; if i32 - Ok: List.Min = null
        col("List").list().max().name().suffix(".Max"), // if i16 - Err; if i32 - Ok: List.Max = null
        col("List").list().sum().name().suffix(".Sum"), // Ok: List.Sum = 0
    ])
    .collect()?;
println!("df: {df}");
```

### Log output

<details>

```shell
thread 'polars-18' panicked at C:\Users\9\.cargo\git\checkouts\polars-b0d90607192fd414\59d2529\crates\polars-ops\src\chunked_array\list\min_max.rs:87:17:
not implemented for dtype Int16
stack backtrace:
   0: std::panicking::begin_panic_handler
             at /rustc/da159eb331b27df528185c616b394bb0e1d2a4bd/library\std\src\panicking.rs:652
   1: core::panicking::panic_fmt
             at /rustc/da159eb331b27df528185c616b394bb0e1d2a4bd/library\core\src\panicking.rs:72
   2: polars_ops::chunked_array::list::min_max::list_min_function::inner
             at C:\Users\9\.cargo\git\checkouts\polars-b0d90607192fd414\59d2529\crates\polars-ops\src\chunked_array\list\min_max.rs:87
   3: polars_ops::chunked_array::list::namespace::has_inner_nulls
             at C:\Users\9\.cargo\git\checkouts\polars-b0d90607192fd414\59d2529\crates\polars-ops\src\chunked_array\list\namespace.rs:26
   4: polars_ops::chunked_array::list::min_max::list_min_function
             at C:\Users\9\.cargo\git\checkouts\polars-b0d90607192fd414\59d2529\crates\polars-ops\src\chunked_array\list\min_max.rs:109
   5: polars_plan::dsl::function_expr::list::min
             at C:\Users\9\.cargo\git\checkouts\polars-b0d90607192fd414\59d2529\crates\polars-plan\src\dsl\function_expr\list.rs:543
   6: polars_plan::dsl::function_expr::list::impl$2::from::closure$5
             at C:\Users\9\.cargo\git\checkouts\polars-b0d90607192fd414\59d2529\crates\polars-plan\src\dsl\function_expr\mod.rs:838
   7: polars_plan::dsl::expr_dyn_fn::impl$0::call_udf<polars_plan::dsl::function_expr::list::impl$2::from::closure_env$5>
             at C:\Users\9\.cargo\git\checkouts\polars-b0d90607192fd414\59d2529\crates\polars-plan\src\dsl\expr_dyn_fn.rs:83
   8: polars_expr::expressions::apply::ApplyExpr::eval_and_flatten
             at C:\Users\9\.cargo\git\checkouts\polars-b0d90607192fd414\59d2529\crates\polars-expr\src\expressions\apply.rs:127
   9: polars_expr::expressions::apply::impl$1::evaluate
             at C:\Users\9\.cargo\git\checkouts\polars-b0d90607192fd414\59d2529\crates\polars-expr\src\expressions\apply.rs:335
  10: polars_expr::expressions::alias::impl$1::evaluate
             at C:\Users\9\.cargo\git\checkouts\polars-b0d90607192fd414\59d2529\crates\polars-expr\src\expressions\alias.rs:32
  11: polars_mem_engine::executors::projection_utils::run_exprs_par::closure$0::closure$0
             at C:\Users\9\.cargo\git\checkouts\polars-b0d90607192fd414\59d2529\crates\polars-mem-engine\src\executors\projection_utils.rs:203
  12: core::ops::function::impls::impl$1::call_mut
             at /rustc/da159eb331b27df528185c616b394bb0e1d2a4bd\library\core\src\ops\function.rs:272
  13: core::ops::function::impls::impl$4::call_once
             at /rustc/da159eb331b27df528185c616b394bb0e1d2a4bd\library\core\src\ops\function.rs:305
  14: enum2$<core::option::Option<ref$<alloc::sync::Arc<dyn$<polars_expr::expressions::PhysicalExpr>,alloc::alloc::Global> > > >::map
             at /rustc/da159eb331b27df528185c616b394bb0e1d2a4bd\library\core\src\option.rs:1075
  15: core::iter::adapters::map::impl$2::next
             at /rustc/da159eb331b27df528185c616b394bb0e1d2a4bd\library\core\src\iter\adapters\map.rs:108
  16: core::iter::adapters::map::impl$2::next
             at /rustc/da159eb331b27df528185c616b394bb0e1d2a4bd\library\core\src\iter\adapters\map.rs:108
  17: core::iter::adapters::take_while::impl$2::next
             at /rustc/da159eb331b27df528185c616b394bb0e1d2a4bd\library\core\src\iter\adapters\take_while.rs:47
  18: core::iter::adapters::map::impl$2::next
             at /rustc/da159eb331b27df528185c616b394bb0e1d2a4bd\library\core\src\iter\adapters\map.rs:108
  19: alloc::vec::Vec<polars_core::series::Series,alloc::alloc::Global>::extend_desugared
             at /rustc/da159eb331b27df528185c616b394bb0e1d2a4bd\library\alloc\src\vec\mod.rs:3064
  20: alloc::vec::spec_extend::impl$0::spec_extend<polars_core::series::Series,core::iter::adapters::map::Map<core::iter::adapters::take_while::TakeWhile<core::iter::adapters::map::Map<core::iter::adapters::map::Map<core::slice::iter::Iter<alloc::sync::Arc<dyn$<
             at /rustc/da159eb331b27df528185c616b394bb0e1d2a4bd\library\alloc\src\vec\spec_extend.rs:17
  21: alloc::vec::impl$19::extend
             at /rustc/da159eb331b27df528185c616b394bb0e1d2a4bd\library\alloc\src\vec\mod.rs:3038
  22: rayon::iter::extend::impl$2::consume_iter
             at C:\Users\9\.cargo\registry\src\index.crates.io-6f17d22bba15001f\rayon-1.10.0\src\iter\extend.rs:130
  23: rayon::iter::while_some::impl$4::consume_iter
             at C:\Users\9\.cargo\registry\src\index.crates.io-6f17d22bba15001f\rayon-1.10.0\src\iter\while_some.rs:139
  24: rayon::iter::map::impl$8::consume_iter
             at C:\Users\9\.cargo\registry\src\index.crates.io-6f17d22bba15001f\rayon-1.10.0\src\iter\map.rs:248
  25: rayon::iter::map::impl$8::consume_iter
             at C:\Users\9\.cargo\registry\src\index.crates.io-6f17d22bba15001f\rayon-1.10.0\src\iter\map.rs:248
  26: rayon::iter::plumbing::Producer::fold_with
             at C:\Users\9\.cargo\registry\src\index.crates.io-6f17d22bba15001f\rayon-1.10.0\src\iter\plumbing\mod.rs:109
  27: rayon::iter::plumbing::bridge_producer_consumer::helper<rayon::slice::IterProducer<alloc::sync::Arc<dyn$<polars_expr::expressions::PhysicalExpr>,alloc::alloc::Global> >,rayon::iter::map::MapConsumer<rayon::iter::map::MapConsumer<rayon::iter::while_some::Wh
             at C:\Users\9\.cargo\registry\src\index.crates.io-6f17d22bba15001f\rayon-1.10.0\src\iter\plumbing\mod.rs:437
  28: rayon::iter::plumbing::bridge_producer_consumer::helper::closure$0
             at C:\Users\9\.cargo\registry\src\index.crates.io-6f17d22bba15001f\rayon-1.10.0\src\iter\plumbing\mod.rs:417
  29: rayon_core::join::join_context::call_a::closure$0
             at C:\Users\9\.cargo\registry\src\index.crates.io-6f17d22bba15001f\rayon-core-1.12.1\src\join\mod.rs:124
  30: core::panic::unwind_safe::impl$25::call_once
             at /rustc/da159eb331b27df528185c616b394bb0e1d2a4bd\library\core\src\panic\unwind_safe.rs:272
  31: std::panicking::try::do_call
             at /rustc/da159eb331b27df528185c616b394bb0e1d2a4bd\library\std\src\panicking.rs:559
  32: std::panicking::try<alloc::collections::linked_list::LinkedList<alloc::vec::Vec<polars_core::series::Series,alloc::alloc::Global>,alloc::alloc::Global>,core::panic::unwind_safe::AssertUnwindSafe<rayon_core::join::join_context::call_a::closure_env$0<alloc::
             at /rustc/da159eb331b27df528185c616b394bb0e1d2a4bd\library\std\src\panicking.rs:523
  33: rayon_core::join::join_context::closure$0<rayon::iter::plumbing::bridge_producer_consumer::helper::closure_env$0<rayon::slice::IterProducer<alloc::sync::Arc<dyn$<polars_expr::expressions::PhysicalExpr>,alloc::alloc::Global> >,rayon::iter::map::MapConsumer<
             at C:\Users\9\.cargo\registry\src\index.crates.io-6f17d22bba15001f\rayon-core-1.12.1\src\join\mod.rs:142
  34: rayon_core::registry::Registry::in_worker
             at C:\Users\9\.cargo\registry\src\index.crates.io-6f17d22bba15001f\rayon-core-1.12.1\src\registry.rs:496
  35: rayon_core::registry::in_worker<rayon_core::join::join_context::closure_env$0<rayon::iter::plumbing::bridge_producer_consumer::helper::closure_env$0<rayon::slice::IterProducer<alloc::sync::Arc<dyn$<polars_expr::expressions::PhysicalExpr>,alloc::alloc::Glob
             at C:\Users\9\.cargo\registry\src\index.crates.io-6f17d22bba15001f\rayon-core-1.12.1\src\registry.rs:953
  36: rayon_core::join::join_context
             at C:\Users\9\.cargo\registry\src\index.crates.io-6f17d22bba15001f\rayon-core-1.12.1\src\join\mod.rs:132
  37: rayon::iter::plumbing::bridge_producer_consumer::helper<rayon::slice::IterProducer<alloc::sync::Arc<dyn$<polars_expr::expressions::PhysicalExpr>,alloc::alloc::Global> >,rayon::iter::map::MapConsumer<rayon::iter::map::MapConsumer<rayon::iter::while_some::Wh
             at C:\Users\9\.cargo\registry\src\index.crates.io-6f17d22bba15001f\rayon-1.10.0\src\iter\plumbing\mod.rs:415
  38: rayon::iter::plumbing::bridge_producer_consumer
             at C:\Users\9\.cargo\registry\src\index.crates.io-6f17d22bba15001f\rayon-1.10.0\src\iter\plumbing\mod.rs:396
  39: rayon::iter::plumbing::bridge::impl$0::callback
             at C:\Users\9\.cargo\registry\src\index.crates.io-6f17d22bba15001f\rayon-1.10.0\src\iter\plumbing\mod.rs:372
  40: rayon::slice::impl$6::with_producer
             at C:\Users\9\.cargo\registry\src\index.crates.io-6f17d22bba15001f\rayon-1.10.0\src\slice\mod.rs:826
  41: rayon::iter::plumbing::bridge
             at C:\Users\9\.cargo\registry\src\index.crates.io-6f17d22bba15001f\rayon-1.10.0\src\iter\plumbing\mod.rs:356
  42: rayon::slice::impl$5::drive_unindexed
             at C:\Users\9\.cargo\registry\src\index.crates.io-6f17d22bba15001f\rayon-1.10.0\src\slice\mod.rs:802
  43: rayon::iter::map::impl$2::drive_unindexed
             at C:\Users\9\.cargo\registry\src\index.crates.io-6f17d22bba15001f\rayon-1.10.0\src\iter\map.rs:49
  44: rayon::iter::map::impl$2::drive_unindexed
             at C:\Users\9\.cargo\registry\src\index.crates.io-6f17d22bba15001f\rayon-1.10.0\src\iter\map.rs:49
  45: rayon::iter::while_some::impl$1::drive_unindexed
             at C:\Users\9\.cargo\registry\src\index.crates.io-6f17d22bba15001f\rayon-1.10.0\src\iter\while_some.rs:44
  46: rayon::iter::extend::impl$33::par_extend<polars_core::series::Series,rayon::iter::while_some::WhileSome<rayon::iter::map::Map<rayon::iter::map::Map<rayon::slice::Iter<alloc::sync::Arc<dyn$<polars_expr::expressions::PhysicalExpr>,alloc::alloc::Global> >,pol
             at C:\Users\9\.cargo\registry\src\index.crates.io-6f17d22bba15001f\rayon-1.10.0\src\iter\extend.rs:588
  47: rayon::iter::from_par_iter::collect_extended
             at C:\Users\9\.cargo\registry\src\index.crates.io-6f17d22bba15001f\rayon-1.10.0\src\iter\from_par_iter.rs:20
  48: rayon::iter::from_par_iter::impl$0::from_par_iter
             at C:\Users\9\.cargo\registry\src\index.crates.io-6f17d22bba15001f\rayon-1.10.0\src\iter\from_par_iter.rs:33
  49: rayon::iter::ParallelIterator::collect
             at C:\Users\9\.cargo\registry\src\index.crates.io-6f17d22bba15001f\rayon-1.10.0\src\iter\mod.rs:2069
  50: rayon::result::impl$4::from_par_iter<alloc::vec::Vec<polars_core::series::Series,alloc::alloc::Global>,polars_core::series::Series,enum2$<polars_error::PolarsError>,rayon::iter::map::Map<rayon::slice::Iter<alloc::sync::Arc<dyn$<polars_expr::expressions::Ph
             at C:\Users\9\.cargo\registry\src\index.crates.io-6f17d22bba15001f\rayon-1.10.0\src\result.rs:125
  51: rayon::iter::ParallelIterator::collect
             at C:\Users\9\.cargo\registry\src\index.crates.io-6f17d22bba15001f\rayon-1.10.0\src\iter\mod.rs:2069
  52: polars_mem_engine::executors::projection_utils::run_exprs_par::closure$0
             at C:\Users\9\.cargo\git\checkouts\polars-b0d90607192fd414\59d2529\crates\polars-mem-engine\src\executors\projection_utils.rs:204
  53: rayon_core::thread_pool::impl$0::install::closure$0
             at C:\Users\9\.cargo\registry\src\index.crates.io-6f17d22bba15001f\rayon-core-1.12.1\src\thread_pool\mod.rs:147
  54: rayon_core::registry::impl$6::in_worker_cold::closure$0::closure$0
             at C:\Users\9\.cargo\registry\src\index.crates.io-6f17d22bba15001f\rayon-core-1.12.1\src\registry.rs:522
  55: rayon_core::job::impl$9::call::closure$0
             at C:\Users\9\.cargo\registry\src\index.crates.io-6f17d22bba15001f\rayon-core-1.12.1\src\job.rs:218
  56: core::panic::unwind_safe::impl$25::call_once
             at /rustc/da159eb331b27df528185c616b394bb0e1d2a4bd\library\core\src\panic\unwind_safe.rs:272
  57: std::panicking::try::do_call
             at /rustc/da159eb331b27df528185c616b394bb0e1d2a4bd\library\std\src\panicking.rs:559
  58: std::panicking::try<enum2$<core::result::Result<alloc::vec::Vec<polars_core::series::Series,alloc::alloc::Global>,enum2$<polars_error::PolarsError> > >,core::panic::unwind_safe::AssertUnwindSafe<rayon_core::job::impl$9::call::closure_env$0<enum2$<core::res
             at /rustc/da159eb331b27df528185c616b394bb0e1d2a4bd\library\std\src\panicking.rs:523
  59: std::panic::catch_unwind
             at /rustc/da159eb331b27df528185c616b394bb0e1d2a4bd\library\std\src\panic.rs:149
  60: rayon_core::unwind::halt_unwinding
             at C:\Users\9\.cargo\registry\src\index.crates.io-6f17d22bba15001f\rayon-core-1.12.1\src\unwind.rs:17
  61: enum2$<rayon_core::job::JobResult<enum2$<core::result::Result<alloc::vec::Vec<polars_core::series::Series,alloc::alloc::Global>,enum2$<polars_error::PolarsError> > > > >::call  
             at C:\Users\9\.cargo\registry\src\index.crates.io-6f17d22bba15001f\rayon-core-1.12.1\src\job.rs:218
  62: rayon_core::job::impl$4::execute<rayon_core::latch::LatchRef<rayon_core::latch::LockLatch>,rayon_core::registry::impl$6::in_worker_cold::closure$0::closure_env$0<rayon_core::thread_pool::impl$0::install::closure_env$0<polars_mem_engine::executors::projecti
             at C:\Users\9\.cargo\registry\src\index.crates.io-6f17d22bba15001f\rayon-core-1.12.1\src\job.rs:120
  63: rayon_core::registry::WorkerThread::wait_until_cold
             at C:\Users\9\.cargo\registry\src\index.crates.io-6f17d22bba15001f\rayon-core-1.12.1\src\registry.rs:794
  64: rayon_core::registry::WorkerThread::wait_until
             at C:\Users\9\.cargo\registry\src\index.crates.io-6f17d22bba15001f\rayon-core-1.12.1\src\registry.rs:769
  65: rayon_core::registry::WorkerThread::wait_until_out_of_work
             at C:\Users\9\.cargo\registry\src\index.crates.io-6f17d22bba15001f\rayon-core-1.12.1\src\registry.rs:818
  66: rayon_core::registry::main_loop
             at C:\Users\9\.cargo\registry\src\index.crates.io-6f17d22bba15001f\rayon-core-1.12.1\src\registry.rs:923
  67: rayon_core::registry::ThreadBuilder::run
             at C:\Users\9\.cargo\registry\src\index.crates.io-6f17d22bba15001f\rayon-core-1.12.1\src\registry.rs:53
  68: rayon_core::registry::impl$2::spawn::closure$0
             at C:\Users\9\.cargo\registry\src\index.crates.io-6f17d22bba15001f\rayon-core-1.12.1\src\registry.rs:98
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.

failures:
    app::test::test

test result: FAILED. 0 passed; 1 failed; 0 ignored; 0 measured; 0 filtered out; finished in 0.67s
```
</details>

### Issue description

`min`/`max` operations on `i16` list with `None` elements throws Err: "not implemented for dtype Int16" but `i32` is Ok.

Related: #13978

### Expected behavior

`min` or `max` returns `null`

### Installed versions

<details>

features = [
    "dtype-array",
    "dtype-struct",
    "lazy",
    "pivot",
    "polars-ops",
    "regex",
    "row_hash",
    "serde",
]

</details>

**Comment by kgv** [comment]
add "dtype-i16" feature
