### ISSUE TITLE
Polars use nest_asyncio

### ISSUE THREAD

**Issue by douglas-raillard-arm** [pola-rs/polars#17334]
### Checks

- [X] I have checked that this issue has not already been reported.
- [X] I have confirmed this bug exists on the [latest version](https://pypi.org/project/polars/) of Polars.

### Reproducible example

No polars example at hand since I only realized polars used nest_asyncio from the changelog. The general problem looks like that:

```python
import uvloop
import nest_asyncio

async def main():
    print('hello world')
    nest_asyncio.apply()

uvloop.run(main())
```

### Log output

```shell
Traceback (most recent call last):
  File "/work/projects/lisa/testuvloop.py", line 8, in <module>
    uvloop.run(main())
  File "venv/lib/python3.12/site-packages/uvloop/__init__.py", line 109, in run
    return __asyncio.run(
           ^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/asyncio/runners.py", line 194, in run
    return runner.run(main)
           ^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/asyncio/runners.py", line 118, in run
    return self._loop.run_until_complete(task)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "uvloop/loop.pyx", line 1517, in uvloop.loop.Loop.run_until_complete
  File "venv/lib/python3.12/site-packages/uvloop/__init__.py", line 61, in wrapper
    return await main
           ^^^^^^^^^^
  File "/work/projects/lisa/testuvloop.py", line 6, in main
    nest_asyncio.apply()
  File "venv/lib/python3.12/site-packages/nest_asyncio.py", line 19, in apply
    _patch_loop(loop)
  File "venv/lib/python3.12/site-packages/nest_asyncio.py", line 193, in _patch_loop
    raise ValueError('Can\'t patch loop of type %s' % type(loop))
ValueError: Can't patch loop of type <class 'uvloop.Loop'>
```

### Issue description

Polars currently relies on nest_asyncio: https://github.com/pola-rs/polars/blob/f73937ab5213a44eaaba8cfc799d8f837600f179/py-polars/polars/io/database/_utils.py#L39

I would suggest to avoid doing so, as `nest_asyncio` only works with event loop implementations shipped with the standard library (as per its documentation). On top of that, we observed that failed `nest_asyncio.apply()` calls were leaving behind some broken state that would force to restart the process [1].

The library is currently not maintained anymore (github repo is archived and the original author and maintainer has sadly left us), so there is little hope of these issues fixed shortly.

We faced the aforementioned issues when running under uvloop (FastAPI server with uvicorn), which lead us to implement [an equivalent based on greenlets](https://github.com/ARM-software/devlib/pull/683) (see `devlib.utils.asyn.run()` for an equivalent of `asyncio.run()` that nests). [greenback](https://greenback.readthedocs.io/) does more-or-less the same thing but seemed to be using unsafe code (access of stdlib C structs using ctypes from pure-Python) [2].

[1] I can't remember the details, something related to the event loop policy staying patched to modify event loops to use nest_asyncio's equivalent to the original `asyncio.run()`)

[2] AFAIR greenback uses ctypes to patch the current running `asyncio.Task` in `await greenback.ensure_portal()`, which we found unnecessary in devlib. Instead we use [loop.set_task_factory](https://docs.python.org/3/library/asyncio-eventloop.html#asyncio.loop.set_task_factory) to interpose our coroutine shim in the top-level . If we happen to run in an non-instrumented asyncio.Task, we just delegate the call to another thread with another event loop as a fallback.

### Expected behavior

Polars should work with any asyncio event loop implementation.

### Installed versions

N/A

**Comment by douglas-raillard-arm** [comment]
Fixed by https://github.com/pola-rs/polars/pull/20793/files

**Comment by giang-hq** [comment]
Hi, re checkout on this. Why the changes are reverted?
Can't use uvloop replacement for now.

> Fixed by https://github.com/pola-rs/polars/pull/20793/files

**Comment by cmdlineluser** [comment]
@giang-hq I don't know, but the followup PR contains more info:

- https://github.com/pola-rs/polars/pull/21641

**Comment by douglas-raillard-arm** [comment]
@giang-hq If you have a reproducer that uses polars, I can add it to the issue description and re-open it.

**Comment by giang-hq** [comment]
Thanks @cmdlineluser  and @douglas-raillard-arm 
I've come up with reproducer

### Reproducible example
```python3
import asyncio
import uvloop
import polars as pl
from sqlalchemy.ext.asyncio import create_async_engine


def get_engine():
    return create_async_engine(
        "postgresql+asyncpg://postgres:postgres@localhost:5434/postgres",
        pool_pre_ping=True,
    )

async def read(engine, query: str) -> pl.DataFrame:
    return pl.read_database(
        query, engine, infer_schema_length=10000
    )
    
async def main():
    engine = get_engine()
    results = await read(engine, "SELECT 1")
    print(results)

if __name__ == "__main__":
    uvloop.run(main())
```

### Log Output
```
Traceback (most recent call last):
  File "mypath/.venv/lib/python3.12/site-packages/polars/io/database/functions.py", line 294, in read_database
    ).to_polars(
      ^^^^^^^^^^
  File "mypath/.venv/lib/python3.12/site-packages/polars/io/database/_executor.py", line 582, in to_polars
    frame = frame_init(
            ^^^^^^^^^^^
  File "mypath/.venv/lib/python3.12/site-packages/polars/io/database/_executor.py", line 279, in _from_rows
    self.result = _run_async(self.result)
                  ^^^^^^^^^^^^^^^^^^^^^^^
  File "mypath/.venv/lib/python3.12/site-packages/polars/io/database/_utils.py", line 32, in _run_async
    polars._utils.nest_asyncio.apply()  # type: ignore[attr-defined]
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "mypath/.venv/lib/python3.12/site-packages/polars/_utils/nest_asyncio.py", line 54, in apply
    _patch_loop(loop)
  File "mypath/.venv/lib/python3.12/site-packages/polars/_utils/nest_asyncio.py", line 233, in _patch_loop
    raise ValueError("Can't patch loop of type %s" % type(loop))
ValueError: Can't patch loop of type <class 'uvloop.Loop'>
```

### Installed versions
```
"polars[sqlalchemy]>=1.36.1"
"sqlalchemy[asyncio]>=2.0.43"
```

### Issue description
The example use SQlAlchemy Async engine to work with Polars.
The program run on `uvloop` via `uvloop.run(main())`. 
If it is fine on `asyncio` (`asyncio.run(main()`)

also, `nested_asyncio` seem to be discontinued so I'm not sure if polars should continue use it.

### Expected behavior
Polars should work with any asyncio event loop implementation.

**Comment by douglas-raillard-arm** [comment]
I've edited the issue description and re-opened it, thanks @giang-hq .

**Comment by pintaf1** [comment]
Hello. Just to say the issue is still present on last version of Polars
