### ISSUE TITLE
Bug: Using `group_by` renames the column to `by`

### ISSUE THREAD

**Issue by kartzke** [pola-rs/polars#17449]
### Checks

- [X] I have checked that this issue has not already been reported.
- [X] I have confirmed this bug exists on the [latest version](https://pypi.org/project/polars/) of Polars.

### Reproducible example

```python
import polars as pl

data = {"date": ["July 1", "July 1", "July 1", "July 2", "July 3"], "sales": [100, 200, 300, 400, 500], "tax_collected": [7, 14, 21, 28, 35]}

df = pl.DataFrame(data)

## You can see the column is renamed to "by" instead of "date"

print(df.group_by(by="date").agg(pl.col("sales").mean()))
```

### Log output

```
shape: (3, 2)
┌────────┬───────┐
│ by     ┆ sales │
│ ---    ┆ ---   │
│ str    ┆ f64   │
╞════════╪═══════╡
│ July 3 ┆ 500.0 │
│ July 1 ┆ 200.0 │
│ July 2 ┆ 400.0 │
└────────┴───────┘
```

### Issue description

When using group_by on a data frame, the column used for the grouping gets renamed to `by`. 

### Expected behavior

The column name should not change.

### Installed versions

I get several NumPy exceptions when running `pl.show_versions()`, here is the full output.

<details>

```
A module that was compiled using NumPy 1.x cannot be run in
NumPy 2.0.0 as it may crash. To support both 1.x and 2.x
versions of NumPy, modules must be compiled with NumPy 2.0.
Some module may need to rebuild instead e.g. with 'pybind11>=2.12'.

If you are a user of the module, the easiest solution will be to
downgrade to 'numpy<2' or try to upgrade the affected module.
We expect that some modules will need time to support NumPy 2.

Traceback (most recent call last):  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "/opt/homebrew/Caskroom/miniforge/base/envs/project/lib/python3.11/site-packages/ipykernel_launcher.py", line 18, in <module>
    app.launch_new_instance()
  File "/opt/homebrew/Caskroom/miniforge/base/envs/project/lib/python3.11/site-packages/traitlets/config/application.py", line 1075, in launch_instance
    app.start()
  File "/opt/homebrew/Caskroom/miniforge/base/envs/project/lib/python3.11/site-packages/ipykernel/kernelapp.py", line 739, in start
    self.io_loop.start()
  File "/opt/homebrew/Caskroom/miniforge/base/envs/project/lib/python3.11/site-packages/tornado/platform/asyncio.py", line 205, in start
    self.asyncio_loop.run_forever()
  File "/opt/homebrew/Caskroom/miniforge/base/envs/project/lib/python3.11/asyncio/base_events.py", line 607, in run_forever
    self._run_once()
  File "/opt/homebrew/Caskroom/miniforge/base/envs/project/lib/python3.11/asyncio/base_events.py", line 1922, in _run_once
    handle._run()
  File "/opt/homebrew/Caskroom/miniforge/base/envs/project/lib/python3.11/asyncio/events.py", line 80, in _run
...
  File "/opt/homebrew/Caskroom/miniforge/base/envs/project/lib/python3.11/site-packages/pandas/compat/pyarrow.py", line 8, in <module>
    import pyarrow as pa
  File "/opt/homebrew/Caskroom/miniforge/base/envs/project/lib/python3.11/site-packages/pyarrow/__init__.py", line 65, in <module>
    import pyarrow.lib as _lib
Output is truncated. View as a scrollable element or open in a text editor. Adjust cell output settings...
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
AttributeError: _ARRAY_API not found

A module that was compiled using NumPy 1.x cannot be run in
NumPy 2.0.0 as it may crash. To support both 1.x and 2.x
versions of NumPy, modules must be compiled with NumPy 2.0.
Some module may need to rebuild instead e.g. with 'pybind11>=2.12'.

If you are a user of the module, the easiest solution will be to
downgrade to 'numpy<2' or try to upgrade the affected module.
We expect that some modules will need time to support NumPy 2.

Traceback (most recent call last):  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "/opt/homebrew/Caskroom/miniforge/base/envs/project/lib/python3.11/site-packages/ipykernel_launcher.py", line 18, in <module>
    app.launch_new_instance()
  File "/opt/homebrew/Caskroom/miniforge/base/envs/project/lib/python3.11/site-packages/traitlets/config/application.py", line 1075, in launch_instance
    app.start()
  File "/opt/homebrew/Caskroom/miniforge/base/envs/project/lib/python3.11/site-packages/ipykernel/kernelapp.py", line 739, in start
    self.io_loop.start()
  File "/opt/homebrew/Caskroom/miniforge/base/envs/project/lib/python3.11/site-packages/tornado/platform/asyncio.py", line 205, in start
    self.asyncio_loop.run_forever()
  File "/opt/homebrew/Caskroom/miniforge/base/envs/project/lib/python3.11/asyncio/base_events.py", line 607, in run_forever
    self._run_once()
  File "/opt/homebrew/Caskroom/miniforge/base/envs/project/lib/python3.11/asyncio/base_events.py", line 1922, in _run_once
    handle._run()
  File "/opt/homebrew/Caskroom/miniforge/base/envs/project/lib/python3.11/asyncio/events.py", line 80, in _run
...
  File "/opt/homebrew/Caskroom/miniforge/base/envs/project/lib/python3.11/site-packages/pandas/core/dtypes/dtypes.py", line 24, in <module>
    from pandas._libs import (
  File "/opt/homebrew/Caskroom/miniforge/base/envs/project/lib/python3.11/site-packages/pyarrow/__init__.py", line 65, in <module>
    import pyarrow.lib as _lib
Output is truncated. View as a scrollable element or open in a text editor. Adjust cell output settings...
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
AttributeError: _ARRAY_API not found

A module that was compiled using NumPy 1.x cannot be run in
NumPy 2.0.0 as it may crash. To support both 1.x and 2.x
versions of NumPy, modules must be compiled with NumPy 2.0.
Some module may need to rebuild instead e.g. with 'pybind11>=2.12'.

If you are a user of the module, the easiest solution will be to
downgrade to 'numpy<2' or try to upgrade the affected module.
We expect that some modules will need time to support NumPy 2.

Traceback (most recent call last):  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "/opt/homebrew/Caskroom/miniforge/base/envs/project/lib/python3.11/site-packages/ipykernel_launcher.py", line 18, in <module>
    app.launch_new_instance()
  File "/opt/homebrew/Caskroom/miniforge/base/envs/project/lib/python3.11/site-packages/traitlets/config/application.py", line 1075, in launch_instance
    app.start()
  File "/opt/homebrew/Caskroom/miniforge/base/envs/project/lib/python3.11/site-packages/ipykernel/kernelapp.py", line 739, in start
    self.io_loop.start()
  File "/opt/homebrew/Caskroom/miniforge/base/envs/project/lib/python3.11/site-packages/tornado/platform/asyncio.py", line 205, in start
    self.asyncio_loop.run_forever()
  File "/opt/homebrew/Caskroom/miniforge/base/envs/project/lib/python3.11/asyncio/base_events.py", line 607, in run_forever
    self._run_once()
  File "/opt/homebrew/Caskroom/miniforge/base/envs/project/lib/python3.11/asyncio/base_events.py", line 1922, in _run_once
    handle._run()
  File "/opt/homebrew/Caskroom/miniforge/base/envs/project/lib/python3.11/asyncio/events.py", line 80, in _run
...
  File "/opt/homebrew/Caskroom/miniforge/base/envs/project/lib/python3.11/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "/opt/homebrew/Caskroom/miniforge/base/envs/project/lib/python3.11/site-packages/pyarrow/__init__.py", line 65, in <module>
    import pyarrow.lib as _lib
Output is truncated. View as a scrollable element or open in a text editor. Adjust cell output settings...
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
AttributeError: _ARRAY_API not found
--------Version info---------
Polars:               1.0.0
Index type:           UInt32
Platform:             macOS-14.5-arm64-arm-64bit
Python:               3.11.6 | packaged by conda-forge | (main, Oct  3 2023, 10:37:07) [Clang 15.0.7 ]

----Optional dependencies----
adbc_driver_manager:  <not installed>
cloudpickle:          <not installed>
connectorx:           <not installed>
deltalake:            <not installed>
fastexcel:            <not installed>
fsspec:               <not installed>
gevent:               <not installed>
great_tables:         <not installed>
hvplot:               <not installed>
matplotlib:           3.9.1
nest_asyncio:         1.6.0
numpy:                2.0.0
openpyxl:             3.1.5
pandas:               2.2.2
pyarrow:              <not installed>
pydantic:             2.8.2
pyiceberg:            <not installed>
sqlalchemy:           2.0.31
torch:                <not installed>
xlsx2csv:             0.8.2
xlsxwriter:           3.2.0
```

</details>

**Comment by MarcoGorelli** [comment]
hey @kartzke - I can't reproduce this, I get `ColumnNotFoundError: date`

regarding the versions, could you install numpy<2.0 and try again please?

**Comment by MarcoGorelli** [comment]
thanks @kartzke for the report, can confirm this reproduces (I just edited your example slightly)

**Comment by MarcoGorelli** [comment]
I think this is intentional (@deanm0000 thoughts?), though perhaps it wasn't called out as a breaking change

https://docs.pola.rs/api/python/stable/reference/dataframe/api/polars.DataFrame.group_by.html

> Additional columns to group by, specified as keyword arguments. The columns will be renamed to the keyword used.

The same thing happens when using keyword arguments in `with_columns`:
```
In [14]: df.with_columns(exprs=pl.col('c')*2)
Out[14]:
shape: (4, 4)
┌─────┬──────┬───────┬───────┐
│ a   ┆ b    ┆ c     ┆ exprs │
│ --- ┆ ---  ┆ ---   ┆ ---   │
│ i64 ┆ f64  ┆ bool  ┆ i32   │
╞═════╪══════╪═══════╪═══════╡
│ 1   ┆ 0.5  ┆ true  ┆ 2     │
│ 2   ┆ 4.0  ┆ true  ┆ 2     │
│ 3   ┆ 10.0 ┆ false ┆ 0     │
│ 4   ┆ 13.0 ┆ true  ┆ 2     │
└─────┴──────┴───────┴───────┘
```

If you don't want the renaming to happen, just use `group_by('date')`

**Comment by ritchie46** [comment]
This isn't a bug. The keyword arguments are syntactic sugar for `alias`, similar to what happens in `select` and `with_columns`.

**Comment by kartzke** [comment]
Ok, thanks for the feedback on this.  So just to confirm some details in my testing:

- My old code to perform the group_by was `df.group_by(by='date')`
- Under Polars `0.20.31`, the column was not renamed to `by`
- Under Polars `1.0`, the column was renamed to `by`
- Changing the `by` kwarg into a regular arg kept the original column name. Thx @MarcoGorelli for this pointer!
-- `group_by('date')`

**Comment by deanm0000** [comment]
@MarcoGorelli I can't see why it's different now. I have the github blame up on `group_by` and I see where I changed it to `*by` which was 0.20.7 but don't see what changed between 0.20.31 and 1.0.
