### ISSUE TITLE
Cannot `dot` two `Array(float64, N)` columns

### ISSUE THREAD

**Issue by rben01** [pola-rs/polars#17456]
### Checks

- [X] I have checked that this issue has not already been reported.
- [X] I have confirmed this bug exists on the [latest version](https://pypi.org/project/polars/) of Polars.

### Reproducible example

```python
import polars as pl

df = pl.DataFrame(
    {"a": [np.arange(3) for _ in range(2)], "b": [np.arange(3) + 10 for _ in range(2)]},
    schema={"a": pl.Array(pl.Float64, 3), "b": pl.Array(pl.Float64, 3)},
)

df.with_columns(pl.col("a").dot(pl.col("b")))
```

### Log output

```shell
Traceback (most recent call last):
  File "/Users/rben01/file.py", line 24, in <module>
    df.with_columns(pl.col("a").dot(pl.col("b")))
  File "/Users/rben01/Library/Caches/pypoetry/virtualenvs/base-wTklQcO3-py3.12/lib/python3.12/site-packages/polars/dataframe/frame.py", line 8763, in with_columns
    return self.lazy().with_columns(*exprs, **named_exprs).collect(_eager=True)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/rben01/Library/Caches/pypoetry/virtualenvs/base-wTklQcO3-py3.12/lib/python3.12/site-packages/polars/lazyframe/frame.py", line 1942, in collect
    return wrap_df(ldf.collect(callback))
                   ^^^^^^^^^^^^^^^^^^^^^
polars.exceptions.InvalidOperationError: `sum` operation not supported for dtype `array[f64, 3]`
```

### Issue description

I guess that after computing the elementwise product, Polars fails to take the sum of the resulting array?

### Expected behavior

`0 * 10 + 1 * 11 + 2 * 12 = 35`

### Installed versions

<details>

```
--------Version info---------
Polars:               1.0.0
Index type:           UInt32
Platform:             macOS-14.5-arm64-arm-64bit
Python:               3.12.4 (main, Jun  6 2024, 18:26:44) [Clang 15.0.0 (clang-1500.3.9.4)]

----Optional dependencies----
adbc_driver_manager:  <not installed>
cloudpickle:          <not installed>
connectorx:           <not installed>
deltalake:            <not installed>
fastexcel:            <not installed>
fsspec:               <not installed>
gevent:               <not installed>
great_tables:         <not installed>
hvplot:               <not installed>
matplotlib:           3.9.1
nest_asyncio:         1.6.0
numpy:                2.0.0
openpyxl:             3.1.5
pandas:               2.2.2
pyarrow:              16.1.0
pydantic:             <not installed>
pyiceberg:            <not installed>
sqlalchemy:           2.0.31
torch:                <not installed>
xlsx2csv:             <not installed>
xlsxwriter:           <not installed>
```

</details>

**Comment by ritchie46** [comment]
More of a feature request. We don't support that yet, the array type is rather new.
