### ISSUE TITLE
Writing a DataFrame which has a column with type `pl.List(SomePolarsEnum)` inside a `pl.Struct` causes panic "ListArray's child's DataType must match"

### ISSUE THREAD

**Issue by bzm3r** [pola-rs/polars#17479]
### Checks

- [X] I have checked that this issue has not already been reported.
- [X] I have confirmed this bug exists on the [latest version](https://pypi.org/project/polars/) of Polars.

### Reproducible example

A minimal not-working example:

```python
from pathlib import Path
import polars as pl

Alphas = pl.Enum(["hello"])
MiniStruct = pl.Struct({
  "alpha": Alphas,
})
MiniStructs = pl.List(MiniStruct)
df = pl.DataFrame(
    pl.Series("xs", [[] for _ in range(1)], dtype=MiniStructs)
)

path = Path("xs.arrow")
if path.exists():
  path.unlink()

df.write_ipc(path)
```

Produces:

```
thread '<unnamed>' panicked at /home/runner/work/polars/polars/crates/polars-arrow/src/array/list/mod.rs:82:61:
called `Result::unwrap()` on an `Err` value: ComputeError(ErrString("ListArray's child's DataType must match. However, the expected DataType is Struct([Field { name: \"alpha\", data_type: Dictionary(UInt32, LargeUtf8, false), is_nullable: true, metadata: {\"POLARS.CATEGORICAL_TYPE\": \"ENUM\"} }]) while it got Struct([Field { name: \"alpha\", data_type: Dictionary(UInt32, LargeUtf8, false), is_nullable: true, metadata: {} }])."))
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```
```---------------------------------------------------------------------------
PanicException                            Traceback (most recent call last)
/tmp/ipykernel_264688/3257874384.py in ?()
     13 path = Path("xs.arrow")
     14 if path.exists():
     15   path.unlink()
     16 
---> 17 df.write_ipc(path)

~/bumblebee/.venv/lib/python3.12/site-packages/polars/dataframe/frame.py in ?(self, file, compression, future)
   3251             issue_unstable_warning(
   3252                 "The `future` parameter of `DataFrame.write_ipc` is considered unstable."
   3253             )
   3254 
-> 3255         self._df.write_ipc(file, compression, future)
   3256         return file if return_bytes else None  # type: ignore[return-value]

PanicException: called `Result::unwrap()` on an `Err` value: ComputeError(ErrString("ListArray's child's DataType must match. However, the expected DataType is Struct([Field { name: \"alpha\", data_type: Dictionary(UInt32, LargeUtf8, false), is_nullable: true, metadata: {\"POLARS.CATEGORICAL_TYPE\": \"ENUM\"} }]) while it got Struct([Field { name: \"alpha\", data_type: Dictionary(UInt32, LargeUtf8, false), is_nullable: true, metadata: {} }])."))
```

### Log output

```shell
thread '<unnamed>' panicked at /home/runner/work/polars/polars/crates/polars-arrow/src/array/list/mod.rs:82:61:
called `Result::unwrap()` on an `Err` value: ComputeError(ErrString("ListArray's child's DataType must match. However, the expected DataType is Struct([Field { name: \"alpha\", data_type: Dictionary(UInt32, Utf8View, false), is_nullable: true, metadata: {\"POLARS.CATEGORICAL_TYPE\": \"ENUM\"} }]) while it got Struct([Field { name: \"alpha\", data_type: Dictionary(UInt32, Utf8View, false), is_nullable: true, metadata: {} }])."))
stack backtrace:
   0:     0x7f2bc39864f8 - <std::sys::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::h3a6f42a8e0ee8a9c
   1:     0x7f2bc0d1029b - core::fmt::write::h177be2ba2d093c62
   2:     0x7f2bc395019e - std::io::Write::write_fmt::h492358c2a62f94ff
   3:     0x7f2bc398b609 - std::sys::backtrace::print::h07e10026e993404f
   4:     0x7f2bc398af19 - std::panicking::default_hook::{{closure}}::h7e1c3b39f850ffe2
   5:     0x7f2bc398c0ec - std::panicking::rust_panic_with_hook::h034879b724d0634e
   6:     0x7f2bc398b9f5 - std::panicking::begin_panic_handler::{{closure}}::h8007915cb5ce2b2c
   7:     0x7f2bc398b959 - std::sys::backtrace::__rust_end_short_backtrace::h98ae259c9f224aec
   8:     0x7f2bc398b943 - rust_begin_unwind
   9:     0x7f2bc0d0e461 - core::panicking::panic_fmt::ha74ff1cd4a1753c2
  10:     0x7f2bc0d15c75 - core::result::unwrap_failed::h106769287811eb01
  11:     0x7f2bc120118c - polars_core::series::into::<impl polars_core::series::Series>::to_arrow::hffcbd17653b2d6ec
  12:     0x7f2bc1b1f5ed - <polars_core::frame::RecordBatchIter as core::iter::traits::iterator::Iterator>::next::h8ca1756fdb949bcc
  13:     0x7f2bc0ab4993 - polars::dataframe::io::<impl polars::dataframe::PyDataFrame>::__pymethod_write_ipc__::hd510d17e1263007e
  14:     0x7f2bc01efe61 - pyo3::impl_::trampoline::trampoline::h2c6333d6a9caaff1
  15:     0x7f2bc0ab8651 - polars::dataframe::io::_::__INVENTORY::trampoline::hdd0b86232dcd1e6d
  16:     0x7f2bf0a118cf - method_vectorcall_VARARGS_KEYWORDS
                               at /build/Python-3.12.3/Objects/descrobject.c:365:14
  17:     0x7f2bf0996338 - _PyObject_VectorcallTstate
                               at /build/Python-3.12.3/./Include/internal/pycore_call.h:92:11
  18:     0x7f2bf0996338 - PyObject_Vectorcall
                               at /build/Python-3.12.3/Objects/call.c:325:12
  19:     0x7f2bf0996338 - _PyEval_EvalFrameDefault
                               at /build/Python-3.12.3/Python/bytecodes.c:2706:19
  20:     0x7f2bf0a89949 - PyEval_EvalCode
                               at /build/Python-3.12.3/Python/ceval.c:578:21
  21:     0x7f2bf0a87253 - builtin_exec_impl
                               at /build/Python-3.12.3/Python/bltinmodule.c:1096:17
  22:     0x7f2bf0a87253 - builtin_exec
                               at /build/Python-3.12.3/Python/clinic/bltinmodule.c.h:586:20
  23:     0x7f2bf0999880 - _PyEval_EvalFrameDefault
                               at /build/Python-3.12.3/Python/bytecodes.c:2966:19
  24:     0x7f2bf0a1898f - _PyEval_EvalFrame
                               at /build/Python-3.12.3/./Include/internal/pycore_ceval.h:89:16
  25:     0x7f2bf0a1898f - gen_send_ex2
                               at /build/Python-3.12.3/Objects/genobject.c:230:14
  26:     0x7f2bf0a187f7 - gen_send_ex
                               at /build/Python-3.12.3/Objects/genobject.c:274:9
  27:     0x7f2bf099a07e - _PyEval_EvalFrameDefault
                               at /build/Python-3.12.3/Python/bytecodes.c:3085:19
  28:     0x7f2bf08fd917 - _PyObject_VectorcallTstate
                               at /build/Python-3.12.3/./Include/internal/pycore_call.h:92:11
  29:     0x7f2bf08fd917 - method_vectorcall
                               at /build/Python-3.12.3/Objects/classobject.c:61:18
  30:     0x7f2bf099adb1 - _PyVectorcall_Call
                               at /build/Python-3.12.3/Objects/call.c:283:24
  31:     0x7f2bf099adb1 - _PyObject_Call
                               at /build/Python-3.12.3/Objects/call.c:354:16
  32:     0x7f2bf099adb1 - PyObject_Call
                               at /build/Python-3.12.3/Objects/call.c:379:12
  33:     0x7f2bf099adb1 - _PyEval_EvalFrameDefault
                               at /build/Python-3.12.3/Python/bytecodes.c:3254:26
  34:     0x7f2bf0a1898f - _PyEval_EvalFrame
                               at /build/Python-3.12.3/./Include/internal/pycore_ceval.h:89:16
  35:     0x7f2bf0a1898f - gen_send_ex2
                               at /build/Python-3.12.3/Objects/genobject.c:230:14
  36:     0x7f2bf083374b - task_step_impl
                               at /build/Python-3.12.3/./Modules/_asynciomodule.c:2826:22
  37:     0x7f2bf083353c - task_step
                               at /build/Python-3.12.3/./Modules/_asynciomodule.c:3127:11
  38:     0x7f2bf083454e - task_wakeup
                               at /build/Python-3.12.3/./Modules/_asynciomodule.c:3222:20
  39:     0x7f2bf0925d61 - cfunction_vectorcall_O
                               at /build/Python-3.12.3/Objects/methodobject.c:509:24
  40:     0x7f2bf0816749 - _PyObject_VectorcallTstate
                               at /build/Python-3.12.3/./Include/internal/pycore_call.h:92:11
  41:     0x7f2bf0816638 - context_run
                               at /build/Python-3.12.3/Python/context.c:668:29
  42:     0x7f2bf0925ba6 - cfunction_vectorcall_FASTCALL_KEYWORDS
                               at /build/Python-3.12.3/Objects/methodobject.c:438:24
  43:     0x7f2bf099a888 - _PyVectorcall_Call
                               at /build/Python-3.12.3/Objects/call.c:271:16
  44:     0x7f2bf099a888 - _PyObject_Call
                               at /build/Python-3.12.3/Objects/call.c:354:16
  45:     0x7f2bf099a888 - PyObject_Call
                               at /build/Python-3.12.3/Objects/call.c:379:12
  46:     0x7f2bf099a888 - _PyEval_EvalFrameDefault
                               at /build/Python-3.12.3/Python/bytecodes.c:3254:26
  47:     0x7f2bf0a89949 - PyEval_EvalCode
                               at /build/Python-3.12.3/Python/ceval.c:578:21
  48:     0x7f2bf0a87253 - builtin_exec_impl
                               at /build/Python-3.12.3/Python/bltinmodule.c:1096:17
  49:     0x7f2bf0a87253 - builtin_exec
                               at /build/Python-3.12.3/Python/clinic/bltinmodule.c.h:586:20
  50:     0x7f2bf0925ba6 - cfunction_vectorcall_FASTCALL_KEYWORDS
                               at /build/Python-3.12.3/Objects/methodobject.c:438:24
  51:     0x7f2bf0996338 - _PyObject_VectorcallTstate
                               at /build/Python-3.12.3/./Include/internal/pycore_call.h:92:11
  52:     0x7f2bf0996338 - PyObject_Vectorcall
                               at /build/Python-3.12.3/Objects/call.c:325:12
  53:     0x7f2bf0996338 - _PyEval_EvalFrameDefault
                               at /build/Python-3.12.3/Python/bytecodes.c:2706:19
  54:     0x7f2bf0830814 - pymain_run_module
                               at /build/Python-3.12.3/Modules/main.c:300:14
  55:     0x7f2bf0ae3f07 - pymain_run_python
                               at /build/Python-3.12.3/Modules/main.c:623:21
  56:     0x7f2bf0ae3f07 - Py_RunMain
                               at /build/Python-3.12.3/Modules/main.c:709:5
  57:     0x7f2bf0830447 - Py_BytesMain
                               at /build/Python-3.12.3/Modules/main.c:763:12
  58:     0x7f2bf027dd90 - __libc_start_call_main
                               at ./csu/../sysdeps/nptl/libc_start_call_main.h:58:16
  59:     0x7f2bf027de40 - __libc_start_main_impl
                               at ./csu/../csu/libc-start.c:392:3
  60:           0x6000a9 - _start
  61:                0x0 - <unknown>
```
### Issue description

If I change `pl.Enum(["hello"])` to `pl.Categorical()`, the issue does not occur. Similarly for other data types.

### Expected behavior

A successful write to disk in Arrow format.

### Installed versions

```
--------Version info---------
Polars:               1.1.0
Index type:           UInt32
Platform:             Linux-5.15.0-113-generic-x86_64-with-glibc2.35
Python:               3.12.3 (main, Apr 15 2024, 18:25:56) [Clang 17.0.6 ]

----Optional dependencies----
adbc_driver_manager:  <not installed>
cloudpickle:          <not installed>
connectorx:           <not installed>
deltalake:            <not installed>
fastexcel:            <not installed>
fsspec:               <not installed>
gevent:               <not installed>
great_tables:         <not installed>
hvplot:               0.10.0
matplotlib:           3.9.0
nest_asyncio:         1.6.0
numpy:                2.0.0
openpyxl:             <not installed>
pandas:               2.2.2
pyarrow:              16.1.0
pydantic:             <not installed>
pyiceberg:            <not installed>
sqlalchemy:           2.0.31
torch:                <not installed>
xlsx2csv:             <not installed>
xlsxwriter:           <not installed>
```

**Comment by cmdlineluser** [comment]
Can reproduce.

```python
(pl.DataFrame(schema={"a": pl.List(pl.Struct({"x": pl.Enum(["y"])}))})
   .write_json("17479.json")
)
```

```
# PanicException: called `Result::unwrap()` on an `Err` value: 
# ComputeError(ErrString("ListArray's child's DataType must match. However, the expected DataType is 
#   Struct([Field { name: \"x\", data_type: Dictionary(UInt32, Utf8View, false), is_nullable: true, metadata: {\"POLARS.CATEGORICAL_TYPE\": \"ENUM\"} }]) 
#   while it got 
#   Struct([Field { name: \"x\", data_type: Dictionary(UInt32, Utf8View, false), is_nullable: true, metadata: {} }])."))
```

**Comment by tpaxman** [comment]
Just noting I encountered a similar issue, related instead to sorting when nested enum values are present in the dataframe (see #18026. The following will reproduce that error:

```
# create DataFrame with a list[struct] column formed by aggregating an enum column
(
    pl.DataFrame({'a': [1,1,2,2], 'b': ['Y','Z','Z','Y']})
    .cast({'b': pl.Enum(['Z','Y'])})
    .with_columns(pl.struct('b','a').alias('c'))
    .group_by('a')
    .agg(pl.col('c'))
    .sort('a')
)
```

**Comment by moritzwilksch** [comment]
I'm experiencing a similar issue without using Enums when converting to arrow. The dataframe is constructed from parsing deeply nested JSONs, i.e. there are some `.explodes` and many `.list.eval(pl.element().struct.field())` involved. Working on a reproducer, but haven't been able to create on yet.

`PanicException: called `Result::unwrap()` on an `Err` value: ComputeError(ErrString("ListArray's child's DataType must match. However, the expected DataType is Int32 while it got Null."))`

<details>
<summary>Rust backtrace</summary>

```
thread 'polars-4' panicked at /home/conda/feedstock_root/build_artifacts/polars_1730209296944/work/crates/polars-arrow/src/array/list/mod.rs:81:57:
called `Result::unwrap()` on an `Err` value: ComputeError(ErrString("ListArray's child's DataType must match. However, the expected DataType is Int32 while it got Null."))
stack backtrace:
   0:     0x7f8b877c81ef - <std::sys::backtrace::BacktraceLock::print::DisplayBacktrace as core::fmt::Display>::fmt::he49223be0828c2da
   1:     0x7f8b8331c6ab - core::fmt::write::h4fe12f6cb3392adb
   2:     0x7f8b8778c3e2 - std::io::Write::write_fmt::hec0f9e215795ad8e
   3:     0x7f8b877c9872 - std::sys::backtrace::BacktraceLock::print::hb2fbe0e79fb51bb5
   4:     0x7f8b877c96d4 - std::panicking::default_hook::{{closure}}::h5458010bed85c320
   5:     0x7f8b877c9e65 - std::panicking::rust_panic_with_hook::h1f6a459c24b862a1
   6:     0x7f8b877c99d5 - std::panicking::begin_panic_handler::{{closure}}::h3409b1bef1bb40d4
   7:     0x7f8b877c9939 - std::sys::backtrace::__rust_end_short_backtrace::he7b1e8e6f5aa08a5
   8:     0x7f8b877c9923 - rust_begin_unwind
   9:     0x7f8b8331ac31 - core::panicking::panic_fmt::h4cbccb8f16fdf66b
  10:     0x7f8b833221f5 - core::result::unwrap_failed::h3948b8b0dc793c75
  11:     0x7f8b83a3d9de - polars_core::series::into::<impl polars_core::series::Series>::to_arrow::h1ec10f9ffddbd457
  12:     0x7f8b8440b263 - rayon::iter::plumbing::bridge_producer_consumer::helper::h6cf2997b449d002a
  13:     0x7f8b8440bb07 - rayon_core::join::join_context::{{closure}}::h732303e81190a34d
  14:     0x7f8b8440b415 - rayon::iter::plumbing::bridge_producer_consumer::helper::h6cf2997b449d002a
  15:     0x7f8b8440c372 - <rayon_core::job::StackJob<L,F,R> as rayon_core::job::Job>::execute::h32e23d6ba16a389f
  16:     0x7f8b874ff1f5 - rayon_core::registry::WorkerThread::wait_until_cold::h1b1eaec28bfe1086
  17:     0x7f8b87501be4 - std::sys::backtrace::__rust_begin_short_backtrace::h1784a2c90b13510b
  18:     0x7f8b875019ab - core::ops::function::FnOnce::call_once{{vtable.shim}}::h74bea0b03fe01b46
  19:     0x7f8b877cc89b - std::sys::pal::unix::thread::Thread::new::thread_start::h01ba1847dfc214af
  20:     0x7f8bc0a9f7f2 - start_thread
  21:     0x7f8bc0a3f450 - clone3
  22:                0x0 - <unknown>
thread 'polars-6' panicked at /home/conda/feedstock_root/build_artifacts/polars_1730209296944/work/crates/polars-arrow/src/array/list/mod.rs:81:57:
called `Result::unwrap()` on an `Err` value: ComputeError(ErrString("ListArray's child's DataType must match. However, the expected DataType is Int32 while it got Null."))
stack backtrace:
   0:     0x7f8b877c81ef - <std::sys::backtrace::BacktraceLock::print::DisplayBacktrace as core::fmt::Display>::fmt::he49223be0828c2da
   1:     0x7f8b8331c6ab - core::fmt::write::h4fe12f6cb3392adb
   2:     0x7f8b8778c3e2 - std::io::Write::write_fmt::hec0f9e215795ad8e
   3:     0x7f8b877c9872 - std::sys::backtrace::BacktraceLock::print::hb2fbe0e79fb51bb5
   4:     0x7f8b877c96d4 - std::panicking::default_hook::{{closure}}::h5458010bed85c320
   5:     0x7f8b877c9e65 - std::panicking::rust_panic_with_hook::h1f6a459c24b862a1
   6:     0x7f8b877c99d5 - std::panicking::begin_panic_handler::{{closure}}::h3409b1bef1bb40d4
   7:     0x7f8b877c9939 - std::sys::backtrace::__rust_end_short_backtrace::he7b1e8e6f5aa08a5
   8:     0x7f8b877c9923 - rust_begin_unwind
   9:     0x7f8b8331ac31 - core::panicking::panic_fmt::h4cbccb8f16fdf66b
  10:     0x7f8b833221f5 - core::result::unwrap_failed::h3948b8b0dc793c75
  11:     0x7f8b83a3d9de - polars_core::series::into::<impl polars_core::series::Series>::to_arrow::h1ec10f9ffddbd457
  12:     0x7f8b8440b263 - rayon::iter::plumbing::bridge_producer_consumer::helper::h6cf2997b449d002a
  13:     0x7f8b8440bb07 - rayon_core::join::join_context::{{closure}}::h732303e81190a34d
  14:     0x7f8b8440b415 - rayon::iter::plumbing::bridge_producer_consumer::helper::h6cf2997b449d002a
  15:     0x7f8b8440bc7f - rayon_core::join::join_context::{{closure}}::h732303e81190a34d
  16:     0x7f8b8440b415 - rayon::iter::plumbing::bridge_producer_consumer::helper::h6cf2997b449d002a
  17:     0x7f8b8440c372 - <rayon_core::job::StackJob<L,F,R> as rayon_core::job::Job>::execute::h32e23d6ba16a389f
  18:     0x7f8b874ff1f5 - rayon_core::registry::WorkerThread::wait_until_cold::h1b1eaec28bfe1086
  19:     0x7f8b87501be4 - std::sys::backtrace::__rust_begin_short_backtrace::h1784a2c90b13510b
  20:     0x7f8b875019ab - core::ops::function::FnOnce::call_once{{vtable.shim}}::h74bea0b03fe01b46
  21:     0x7f8b877cc89b - std::sys::pal::unix::thread::Thread::new::thread_start::h01ba1847dfc214af
  22:     0x7f8bc0a9f7f2 - start_thread
  23:     0x7f8bc0a3f450 - clone3
  24:                0x0 - <unknown>
```

</details>

**Comment by lukemanley** [comment]
The OP example as well as the other examples in comments above all seem to now work on main.

**Comment by moritzwilksch** [comment]
I can still reproduce the issue in #19738

**Comment by lukemanley** [comment]
> I can still reproduce the issue in #19738 in `1.19.0` or are you referring to unreleased changes?

I agree the example in #19738 still panics. I was referring to the examples in this issue which seem to now work on the main branch.

**Comment by mishavanbeek** [comment]
> I can still reproduce the issue in #19738 in `1.19.0` or are you referring to unreleased changes?

The earlier example
```python
pl.DataFrame(schema={"a": pl.List(pl.Struct({"x": pl.Enum(["y"])}))}).write_json("17479.json")
```
now works for me in 1.19.0, but interchanging the list and struct results in an error:
```python
pl.DataFrame(schema={"a": pl.Struct({"x": pl.List(pl.Enum(["y"]))})}).write_json("17479.json")
```
```
thread '<unnamed>' panicked at crates/polars-arrow/src/array/struct_/mod.rs:120:56:
called `Result::unwrap()` on an `Err` value: ComputeError(ErrString("The children DataTypes of a StructArray must equal the children data types.
```
