### ISSUE TITLE
Unable to write polars DaraFrame to parquet file with UUID in column data

### ISSUE THREAD

**Issue by tribunsky-kir** [pola-rs/polars#17486]
### Checks

- [X] I have checked that this issue has not already been reported.
- [X] I have confirmed this bug exists on the [latest version](https://pypi.org/project/polars/) of Polars.

### Reproducible example

```python
import uuid

import polars as pl

df = pl.DataFrame([{'user_id': uuid.uuid4(), 'data': '...'}])

df.write_parquet('test.pq')
```

### Log output

```shell
thread 'polars-1' panicked at crates/polars-arrow/src/compute/aggregate/memory.rs:68:18:
called `Option::unwrap()` on a `None` value
stack backtrace:
   0: _rust_begin_unwind
   1: core::panicking::panic_fmt
   2: core::panicking::panic
   3: core::option::unwrap_failed
   4: polars_arrow::compute::aggregate::memory::estimated_bytes_size
   5: <core::iter::adapters::GenericShunt<I,R> as core::iter::traits::iterator::Iterator>::next
   6: polars_io::parquet::write::batched_writer::array_to_pages_iter
   7: rayon::iter::plumbing::bridge_producer_consumer::helper
   8: rayon_core::join::join_context::{{closure}}
   9: rayon::iter::plumbing::bridge_producer_consumer::helper
  10: rayon_core::thread_pool::ThreadPool::install::{{closure}}
  11: <rayon_core::job::StackJob<L,F,R> as rayon_core::job::Job>::execute
  12: rayon_core::registry::WorkerThread::wait_until_cold
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
Traceback (most recent call last):
  File "/Users/user/my_project/df_chk.py", line 7, in <module>
    df.write_parquet('test.pq')
  File "/Users/user/Library/Caches/pypoetry/virtualenvs/my_project-iaMsdIag-py3.12/lib/python3.12/site-packages/polars/dataframe/frame.py", line 3440, in write_parquet
    self._df.write_parquet(
pyo3_runtime.PanicException: called `Option::unwrap()` on a `None` value
```

### Issue description

Looks like I've hit the limitations of arrow format, because pandas (pyarrow) has the same behavior, but more explicit error message like
```
pyarrow.lib.ArrowInvalid: ("Could not convert UUID('020802b8-b917-407b-92d6-145d5e99cf0f') with type UUID: did not recognize Python value type when inferring an Arrow data type", 'Conversion failed for column user_id with type object')
```

### Expected behavior

As polars is able to handle columns with UUID data it is expected to be able to at least serialize it to parquet.

Or, the error message may be improved (the absence of explicit mapping of UUID to arrow types).

### Installed versions

<details>

```
pl.show_versions()
--------Version info---------
Polars:               0.20.31
Index type:           UInt32
Platform:             macOS-14.5-arm64-arm-64bit
Python:               3.12.4 (main, Jun  6 2024, 18:26:44) [Clang 15.0.0 (clang-1500.3.9.4)]
----Optional dependencies----
adbc_driver_manager:  <not installed>
cloudpickle:          <not installed>
connectorx:           <not installed>
deltalake:            <not installed>
fastexcel:            <not installed>
fsspec:               2024.6.1
gevent:               <not installed>
hvplot:               <not installed>
matplotlib:           <not installed>
nest_asyncio:         <not installed>
numpy:                2.0.0
openpyxl:             <not installed>
pandas:               2.2.2
pyarrow:              16.1.0
pydantic:             2.7.4
pyiceberg:            <not installed>
pyxlsb:               <not installed>
sqlalchemy:           <not installed>
torch:                <not installed>
xlsx2csv:             <not installed>
xlsxwriter:           <not installed>
```

</details>

**Comment by alexander-beedie** [comment]
> As polars is able to handle columns with UUID data

Actually it isn't (not really); in this case the UUID values are just Python objects, hence the problem - Parquet can't store arbitrary Python objects as native types.

**Comment by Julian-J-S** [comment]
as @alexander-beedie mentioned you cannot store any arbitrary classes or objects in parquet/csv/database/ ...

The common solution to your problem is to convert the data to a type the destination format can unterstand (`str` for example)
- `uuid.uuid4().hex`: returns the uuid as string which works 
- there is also `.urn` (string), `.bytes` (bytes) or `.int` (integer)

**Comment by tribunsky-kir** [comment]
@Julian-J-S , that's exactly how I solved the problem for myself (via `str`)... After I discovered the problem _type_ itself.

**Comment by bnewman-tech** [comment]
I found a workaround for the issue with writing DataFrame containing UUID columns to a parquet file. By converting the UUID objects to strings before writing, I was able to save it. Here's how I did it:
```

import uuid
import polars as pl
     
def convert_polars_uuid_to_string(df: pl.DataFrame) -> pl.DataFrame:
 """Convert UUIDs to Strings."""
 for col in df.columns:
     if df[col].dtype == pl.Object:
         df = df.with_columns(
             pl.col(col).map_elements(
                 lambda x: str(x) if isinstance(x, uuid.UUID) else None,
                 return_dtype=pl.Utf8,
             ),
         )
 return df
df = pl.DataFrame([{"user_id": uuid.uuid4(), "data": "..."}])
df = convert_polars_uuid_to_string(df)
df.write_parquet("test.pq")
```

**Comment by kacper-sellforte** [comment]
Now Arrow has a support for UUIDs: https://arrow.apache.org/docs/format/CanonicalExtensions.html#uuid, however the conversion from Python side is still lacking: https://github.com/apache/arrow/issues/43855.

**Comment by tim-x-y-z** [comment]
It would be a great type addition to have `UUID` as a polars type that maps to python and can natively read and write.

**Comment by olly-writes-code** [comment]
The same goes for Postgres UUIDs https://www.postgresql.org/docs/current/datatype-uuid.html. 

When writing to a schema that expects a UUID this makes using polars problematic.
