### ISSUE TITLE
error in tests when `pandas<2.2` and `sqlalchemy<2`

### ISSUE THREAD

**Issue by phi-friday** [pola-rs/polars#17487]
### Checks

- [X] I have checked that this issue has not already been reported.
- [X] I have confirmed this bug exists on the [latest version](https://pypi.org/project/polars/) of Polars.

### [`tests/unit/interchange/test_roundtrip.py::test_from_dataframe_pandas_timestamp_ns`](https://github.com/pola-rs/polars/blob/2b54214f862d2792e393fa00edb0fdf238f3d330/py-polars/tests/unit/interchange/test_roundtrip.py#L283)
```python
import polars as pl
from datetime import datetime


def main() -> None:
    df = pl.Series("a", [datetime(2000, 1, 1)], dtype=pl.Datetime("ns")).to_frame()
    df_pd = df.to_pandas(use_pyarrow_extension_array=True)
    result = pl.from_dataframe(df_pd)
    print(result, df)
    assert result.equals(df)


if __name__ == "__main__":
    main()
```

### [`tests/unit/io/database/test_read.py::test_read_database_parameterised`](https://github.com/pola-rs/polars/blob/2b54214f862d2792e393fa00edb0fdf238f3d330/py-polars/tests/unit/io/database/test_read.py#L367)
```python
import polars as pl
import sqlite3
import sqlalchemy as sa
from sqlalchemy.orm import Session

engine = sa.create_engine("sqlite://")


def init() -> None:
    query = """
    create table test_data (
        date date,
        name text,
        value float
    );
    """
    with engine.connect() as conn:
        conn.execute(sa.text(query))
    with engine.begin() as conn:
        conn.execute("insert into test_data values ('2021-01-01', 'other', -99.5);")


def main() -> None:
    init()
    session = Session(engine)
    conn = session.connection()
    raw_conn = conn.connection.driver_connection
    assert isinstance(raw_conn, sqlite3.Connection)

    # establish parameterised queries and validate usage
    query = """
        SELECT CAST(STRFTIME('%Y',"date") AS INT) as "year", name, value
        FROM test_data
        WHERE value < {n}
    """
    expected_frame = pl.DataFrame({"year": [2021], "name": ["other"], "value": [-99.5]})

    for param, param_value in (
        (":n", {"n": 0}),
        ("?", (0,)),
        ("?", [0]),
    ):
        for sub_conn in (session, engine, conn, raw_conn):
            print(type(sub_conn), sub_conn, param, param_value)
            from_database = pl.read_database(
                query.format(n=param),
                connection=sub_conn,
                execute_options={"parameters": param_value},
            )
            print(expected_frame, from_database)
            assert expected_frame.equals(from_database)


if __name__ == "__main__":
    try:
        main()
    finally:
        engine.dispose()

```

### [`tests/unit/io/database/test_async.py`](https://github.com/pola-rs/polars/blob/e713045cbc3b026cac6692921cd5bf697cd6d771/py-polars/tests/unit/io/database/test_async.py#L8)
```python
def main() -> None:
    from sqlalchemy.ext.asyncio import async_sessionmaker  # noqa: F401


if __name__ == "__main__":
    main()
```

#### error 1
```shell
shape: (1, 1)
┌───────────────────────────────┐
│ a                             │
│ ---                           │
│ datetime[ns]                  │
╞═══════════════════════════════╡
│ 1970-01-01 00:00:05.097318736 │
└───────────────────────────────┘ shape: (1, 1)
┌─────────────────────┐
│ a                   │
│ ---                 │
│ datetime[ns]        │
╞═════════════════════╡
│ 2000-01-01 00:00:00 │
└─────────────────────┘
Traceback (most recent call last):
  File "/Users/***/git/test/polars_error/./error_0.py", line 14, in <module>
    main()
  File "/Users/***/git/test/polars_error/./error_0.py", line 10, in main
    assert result.equals(df)
           ^^^^^^^^^^^^^^^^^
AssertionError
```

#### error 2
```shell
❯ rye run python ./error_1.py
/Users/***/git/test/polars_error/./error_1.py:18: RemovedIn20Warning: Deprecated API features detected! These feature(s) are not compatible with SQLAlchemy 2.0. To prevent incompatible upgrades prior to updating applications, ensure requirements files are pinned to "sqlalchemy<2.0". Set environment variable SQLALCHEMY_WARN_20=1 to show all deprecation warnings.  Set environment variable SQLALCHEMY_SILENCE_UBER_WARNING=1 to silence this message. (Background on SQLAlchemy 2.0 at: https://sqlalche.me/e/b8d9)
  conn.execute(sa.text(query))
<class 'sqlalchemy.orm.session.Session'> <sqlalchemy.orm.session.Session object at 0x101ca55e0> :n {'n': 0}
shape: (1, 3)
┌──────┬───────┬───────┐
│ year ┆ name  ┆ value │
│ ---  ┆ ---   ┆ ---   │
│ i64  ┆ str   ┆ f64   │
╞══════╪═══════╪═══════╡
│ 2021 ┆ other ┆ -99.5 │
└──────┴───────┴───────┘ shape: (1, 3)
┌──────┬───────┬───────┐
│ year ┆ name  ┆ value │
│ ---  ┆ ---   ┆ ---   │
│ i64  ┆ str   ┆ f64   │
╞══════╪═══════╪═══════╡
│ 2021 ┆ other ┆ -99.5 │
└──────┴───────┴───────┘
<class 'sqlalchemy.engine.base.Engine'> Engine(sqlite://) :n {'n': 0}
Traceback (most recent call last):
  File "/Users/***/git/test/polars_error/.venv/lib/python3.12/site-packages/sqlalchemy/engine/base.py", line 1810, in _execute_context
    context = constructor(
              ^^^^^^^^^^^^
  File "/Users/***/git/test/polars_error/.venv/lib/python3.12/site-packages/sqlalchemy/engine/default.py", line 1002, in _init_compiled
    compiled.construct_params(
  File "/Users/***/git/test/polars_error/.venv/lib/python3.12/site-packages/sqlalchemy/sql/compiler.py", line 1026, in construct_params
    raise exc.InvalidRequestError(
sqlalchemy.exc.InvalidRequestError: A value is required for bind parameter 'n' (Background on this error at: https://sqlalche.me/e/14/cd3x)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Users/***/git/test/polars_error/./error_1.py", line 56, in <module>
    main()
  File "/Users/***/git/test/polars_error/./error_1.py", line 45, in main
    from_database = pl.read_database(
                    ^^^^^^^^^^^^^^^^^
  File "/Users/***/git/test/polars_error/.venv/lib/python3.12/site-packages/polars/io/database/functions.py", line 253, in read_database
    return cx.execute(
           ^^^^^^^^^^^
  File "/Users/***/git/test/polars_error/.venv/lib/python3.12/site-packages/polars/io/database/_executor.py", line 480, in execute
    result = cursor_execute(query, **options)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/***/git/test/polars_error/.venv/lib/python3.12/site-packages/sqlalchemy/engine/base.py", line 1385, in execute
    return meth(self, multiparams, params, _EMPTY_EXECUTION_OPTS)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/***/git/test/polars_error/.venv/lib/python3.12/site-packages/sqlalchemy/sql/elements.py", line 334, in _execute_on_connection
    return connection._execute_clauseelement(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/***/git/test/polars_error/.venv/lib/python3.12/site-packages/sqlalchemy/engine/base.py", line 1577, in _execute_clauseelement
    ret = self._execute_context(
          ^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/***/git/test/polars_error/.venv/lib/python3.12/site-packages/sqlalchemy/engine/base.py", line 1816, in _execute_context
    self._handle_dbapi_exception(
  File "/Users/***/git/test/polars_error/.venv/lib/python3.12/site-packages/sqlalchemy/engine/base.py", line 2134, in _handle_dbapi_exception
    util.raise_(
  File "/Users/***/git/test/polars_error/.venv/lib/python3.12/site-packages/sqlalchemy/util/compat.py", line 211, in raise_
    raise exception
  File "/Users/***/git/test/polars_error/.venv/lib/python3.12/site-packages/sqlalchemy/engine/base.py", line 1810, in _execute_context
    context = constructor(
              ^^^^^^^^^^^^
  File "/Users/***/git/test/polars_error/.venv/lib/python3.12/site-packages/sqlalchemy/engine/default.py", line 1002, in _init_compiled
    compiled.construct_params(
  File "/Users/***/git/test/polars_error/.venv/lib/python3.12/site-packages/sqlalchemy/sql/compiler.py", line 1026, in construct_params
    raise exc.InvalidRequestError(
sqlalchemy.exc.StatementError: (sqlalchemy.exc.InvalidRequestError) A value is required for bind parameter 'n'
[SQL: 
        SELECT CAST(STRFTIME('%Y',"date") AS INT) as "year", name, value
        FROM test_data
        WHERE value < ?
    ]
[parameters: [{'parameters': {'n': 0}}]]
(Background on this error at: https://sqlalche.me/e/14/cd3x)
```

#### error 3
```shell
❯ rye run python ./error_2.py
Traceback (most recent call last):
  File "/Users/***/git/test/polars_error/./error_2.py", line 6, in <module>
    main()
  File "/Users/***/git/test/polars_error/./error_2.py", line 2, in main
    from sqlalchemy.ext.asyncio import async_sessionmaker  # noqa: F401
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ImportError: cannot import name 'async_sessionmaker' from 'sqlalchemy.ext.asyncio' (/Users/***/git/test/polars_error/.venv/lib/python3.12/site-packages/sqlalchemy/ext/asyncio/__init__.py). Did you mean: 'async_session'?
```

### Issue description

error in tests when `pandas<2.2` and `sqlalchemy<2`

### Expected behavior

Either limit the versions of `sqlalchemy` and `pandas`, or the test code needs to be modified

### Installed versions

<details>

```
>>> pl.show_versions()
--------Version info---------
Polars:               1.1.0
Index type:           UInt32
Platform:             macOS-14.5-arm64-arm-64bit
Python:               3.12.3 (main, Apr 15 2024, 17:43:11) [Clang 17.0.6 ]

----Optional dependencies----
adbc_driver_manager:  <not installed>
cloudpickle:          <not installed>
connectorx:           <not installed>
deltalake:            <not installed>
fastexcel:            <not installed>
fsspec:               <not installed>
gevent:               <not installed>
great_tables:         <not installed>
hvplot:               <not installed>
matplotlib:           <not installed>
nest_asyncio:         <not installed>
numpy:                1.26.4
openpyxl:             <not installed>
pandas:               2.1.4
pyarrow:              16.1.0
pydantic:             <not installed>
pyiceberg:            <not installed>
sqlalchemy:           1.4.52
torch:                <not installed>
xlsx2csv:             <not installed>
xlsxwriter:           <not installed>
```

</details>

**Comment by phi-friday** [comment]
https://github.com/pola-rs/polars/blob/553f30bf18656c268fe0c6bfd965846a43fb70a1/py-polars/polars/io/database/_executor.py#L356
like `error 3`, error when `sqlalchemy<2`
