### ISSUE TITLE
from_numpy does not support object-dtyped string arrays with missing values

### ISSUE THREAD

**Issue by Wainberg** [pola-rs/polars#17484]
### Checks

- [X] I have checked that this issue has not already been reported.
- [X] I have confirmed this bug exists on the [latest version](https://pypi.org/project/polars/) of Polars.

### Reproducible example

```python
>>> pl.Series(np.array(['foo', float('nan')], dtype=object))
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File ".../polars/series/series.py", line 299, in __init__
    self._s = numpy_to_pyseries(
              ^^^^^^^^^^^^^^^^^^
  File ".../polars/_utils/construction/series.py", line 442, in numpy_to_pyseries
    return constructor(
           ^^^^^^^^^^^^
TypeError: 'float' object cannot be converted to 'PyString'
```

```python
>>> pl.from_numpy(np.array(['foo', float('nan')], dtype=object))
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File ".../polars/convert/general.py", line 346, in from_numpy
    numpy_to_pydf(
  File ".../polars/_utils/construction/dataframe.py", line 1298, in numpy_to_pydf
    pl.Series(
  File ".../polars/series/series.py", line 299, in __init__
    self._s = numpy_to_pyseries(
              ^^^^^^^^^^^^^^^^^^
  File ".../polars/_utils/construction/series.py", line 442, in numpy_to_pyseries
    return constructor(
           ^^^^^^^^^^^^
TypeError: 'float' object cannot be converted to 'PyString'
```

### Issue description

NumPy string arrays with missing values are often represented with `dtype=object` and `np.nan` for missing values. This gives an error when converting to polars, which I don't think was there pre-1.0.

### Expected behavior

This should convert to `pl.Series(['foo', None])`.

### Installed versions

<details>

```
Replace this line with the output of pl.show_versions(). Leave the backticks in place.
```

</details>

**Comment by ritchie46** [comment]
@stinodego can this one be on your stack somewhere?

**Comment by stinodego** [comment]
Before going into the nitty gritty: you should use `None` for null values in object arrays to get the behavior you want:

```python
arr = np.array(["foo", None], dtype=object)
res = pl.from_numpy(arr)
print(res)
```
```
shape: (2, 1)
┌──────────┐
│ column_0 │
│ ---      │
│ str      │
╞══════════╡
│ foo      │
│ null     │
└──────────┘
```

So what should the result be when the input is `["foo", float("nan")]`? I guess an Object Series with the objects "foo" and `float("nan")`. We should definitely not assume `float("nan")` is a null value.

The reason this worked on earlier patches is that we would just set any non-string input to null (e.g. `["hello", 1234]` would also result in `["hello", null]`). Now we raise here. I don't think the previous nulling behavior is good either.

Currently, for object types, we check if the first non-null is a string or bytes object and then assume the rest is as well:
https://github.com/pola-rs/polars/blob/2b54214f862d2792e393fa00edb0fdf238f3d330/py-polars/polars/datatypes/constructor.py#L136-L144

We can just remove the logic but then `["a", "b"]` will not be parsed as a String Series.

I guess we need to do a full scan over the Series to check if all objects are string or bytes?

**Comment by dpinol** [comment]
Hi,
some issues

###  1. `nan_to_null` does not work with orient="row". 
I get _"The following 'float' object cannot be converted to 'PyString'"_ anyway.

`pl.DataFrame(np.array([["ES"],[np.nan]], np.object_),orient="row", nan_to_null=True)`



### 2. With `numpy.array.tolist()` it does not crash, but it converts the NaN to string.
```
pl.DataFrame(np.array([["ES"],[np.nan]], np.object_).tolist(),orient="row", nan_to_null=True)
Out[59]: 
shape: (2, 1)
┌──────────┐
│ column_0 │
│ ---      │
│ str      │
╞══════════╡
│ ES       │
│ NaN      │
└──────────┘
```


### 3. nan as null?
> We should definitely not assume float("nan") is a null value for object types, unless I guess nan_to_null=True.

NaNs are now "pervasive" in numpy arrays due to https://github.com/pola-rs/polars/issues/17113, since now `to_numpy` converts Null to NaNs.

thanks!

**Comment by Baukebrenninkmeijer** [comment]
@stinodego I'm looking to start contributing to Polars, would this be a suitable first ticket to start with? It seems not too large and scoped clearly. Would appreciate any advice!

**Comment by glthm** [comment]
Seems related to #16633, as `sequence_to_pyseries` calls `numpy_to_pyseries` which calls `numpy_type_from_constructor`, and some parts of the faulty logic used in the branch handling `numpy` in `sequence_to_pyseries` is used a second time downstream in `numpy_type_to_constructor`

Or am I mistaken?
