### ISSUE TITLE
Broken and inconsistent API for dealing with Categorical variables

### ISSUE THREAD

**Issue by user529481** [pola-rs/polars#17576]
### Checks

- [X] I have checked that this issue has not already been reported.
- [X] I have confirmed this bug exists on the [latest version](https://pypi.org/project/polars/) of Polars.

### Reproducible example

```python
import polars as pl
pl.enable_string_cache()

df = pl.DataFrame({'foo': ['a', 'b']}, schema={'foo': pl.Categorical})
df2 = df.filter(
    pl.col('foo').str.contains('a')
)
```

### Log output

```shell
Traceback (most recent call last):
  File "/Users/xyz/Library/Application Support/JetBrains/PyCharmCE2024.1/scratches/scratch_31.py", line 5, in <module>
    df2 = df.filter(
          ^^^^^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/polars/dataframe/frame.py", line 4092, in filter
    return self.lazy().filter(*predicates, **constraints).collect(_eager=True)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/polars/utils/deprecation.py", line 100, in wrapper
    return function(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/polars/lazyframe/frame.py", line 1788, in collect
    return wrap_df(ldf.collect())
                   ^^^^^^^^^^^^^
polars.exceptions.SchemaError: invalid series dtype: expected `Utf8`, got `cat`
```

### Issue description

Not able to filter Categorical variables.  I've tried:

```py
pl.toggle_string_cache(True)
```
```py
with pl.StringCache():
    df2 = df.filter(
        pl.col('foo').str.contains('a')
    )
```
```py
pl.Config.set_global_string_cache()
```

It seems like the API is changing every few months. It's a bit humorous that stackoverflow has comments saying it's X, and then only a couple months later it's Y. Can we just pick one and stick with it? 

### Expected behavior

Filter a column based on its string value. 

### Installed versions

<details>

```
Platform:             macOS-14.5-arm64-arm-64bit
Python:               3.11.9 (main, Apr  2 2024, 08:25:04) [Clang 15.0.0 (clang-1500.3.9.4)]

----Optional dependencies----
adbc_driver_manager:  <not installed>
cloudpickle:          3.0.0
connectorx:           <not installed>
deltalake:            <not installed>
fsspec:               2024.2.0
gevent:               <not installed>
matplotlib:           3.8.0
numpy:                1.26.4
openpyxl:             3.1.2
pandas:               2.2.2
pyarrow:              16.1.0
pydantic:             2.5.3
pyiceberg:            <not installed>
pyxlsb:               <not installed>
sqlalchemy:           2.0.30
xlsx2csv:             <not installed>
xlsxwriter:           <not installed>
None
```

</details>

**Comment by s-banach** [comment]
Did it ever work to use the Expr.str namespace on categorical columns?

**Comment by cmdlineluser** [comment]
From what I understand, it has yet to be implemented:

- https://github.com/pola-rs/polars/issues/9773
