### ISSUE TITLE
Panic when decoding creating fixed-size list of Time values

### ISSUE THREAD

**Issue by coastalwhite** [pola-rs/polars#17599]
### Checks

- [X] I have checked that this issue has not already been reported.
- [X] I have confirmed this bug exists on the [latest version](https://pypi.org/project/polars/) of Polars.

### Reproducible example

```python
import polars as pl

s = pl.Series([[None], [[0]]], dtype = pl.Array(pl.Time, (1, 1)))

```

### Log output

```shell
thread '<unnamed>' panicked at crates/polars-core/src/chunked_array/builder/list/anonymous.rs:161:69:
called `Result::unwrap()` on an `Err` value: InvalidOperation(ErrString("It is not possible to concatenate arrays of different data types."))
stack backtrace:
   0: rust_begin_unwind
             at /rustc/032af18af578f4283a2927fb43b90df2bbb72b67/library/std/src/panicking.rs:652:5
   1: core::panicking::panic_fmt
             at /rustc/032af18af578f4283a2927fb43b90df2bbb72b67/library/core/src/panicking.rs:72:14
   2: core::result::unwrap_failed
             at /rustc/032af18af578f4283a2927fb43b90df2bbb72b67/library/core/src/result.rs:1679:5
   3: core::result::Result<T,E>::unwrap
             at /rustc/032af18af578f4283a2927fb43b90df2bbb72b67/library/core/src/result.rs:1102:23
   4: <polars_core::chunked_array::builder::list::anonymous::AnonymousOwnedListBuilder as polars_core::chunked_array::builder::list::ListBuilderTrait>::finish
             at ./crates/polars-core/src/chunked_array/builder/list/anonymous.rs:161:19
   5: <alloc::boxed::Box<S> as polars_core::chunked_array::builder::list::ListBuilderTrait>::finish
             at ./crates/polars-core/src/chunked_array/builder/list/mod.rs:75:9
   6: <polars_core::series::Series as polars_core::named_from::NamedFrom<T,[core::option::Option<polars_core::series::Series>]>>::new
             at ./crates/polars-core/src/named_from.rs:172:9
   7: polars::series::construction::<impl polars::series::PySeries>::new_series_list
             at ./py-polars/src/series/construction.rs:280:12
   8: polars::series::construction::<impl polars::series::PySeries>::__pymethod_new_series_list__
             at ./py-polars/src/series/construction.rs:169:1
   9: pyo3::impl_::trampoline::cfunction_with_keywords::{{closure}}
             at /home/johndoe/.cargo/registry/src/index.crates.io-6f17d22bba15001f/pyo3-0.21.2/src/impl_/trampoline.rs:45:29
  10: pyo3::impl_::trampoline::trampoline::{{closure}}
             at /home/johndoe/.cargo/registry/src/index.crates.io-6f17d22bba15001f/pyo3-0.21.2/src/impl_/trampoline.rs:187:54
  11: std::panicking::try::do_call
             at /rustc/032af18af578f4283a2927fb43b90df2bbb72b67/library/std/src/panicking.rs:559:40
  12: __rust_try
  13: std::panicking::try
             at /rustc/032af18af578f4283a2927fb43b90df2bbb72b67/library/std/src/panicking.rs:523:19
  14: std::panic::catch_unwind
             at /rustc/032af18af578f4283a2927fb43b90df2bbb72b67/library/std/src/panic.rs:149:14
  15: pyo3::impl_::trampoline::trampoline
             at /home/johndoe/.cargo/registry/src/index.crates.io-6f17d22bba15001f/pyo3-0.21.2/src/impl_/trampoline.rs:187:9
  16: pyo3::impl_::trampoline::cfunction_with_keywords
             at /home/johndoe/.cargo/registry/src/index.crates.io-6f17d22bba15001f/pyo3-0.21.2/src/impl_/trampoline.rs:45:13
  17: polars::series::construction::_::__INVENTORY::trampoline
             at ./py-polars/src/series/construction.rs:169:1
  18: cfunction_call
  19: _PyObject_MakeTpCall.localalias
  20: _PyEval_EvalFrameDefault
  21: _PyEval_Vector
  22: _PyObject_FastCallDictTstate
  23: slot_tp_init
  24: type_call
  25: _PyObject_MakeTpCall.localalias
  26: _PyEval_EvalFrameDefault
  27: _PyEval_Vector.constprop.0
  28: PyEval_EvalCode
  29: run_mod
  30: _PyRun_SimpleFileObject
  31: _PyRun_AnyFileObject
  32: Py_RunMain.localalias
  33: __libc_start_call_main
  34: __libc_start_main@@GLIBC_2.34
  35: _start
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
Traceback (most recent call last):
  File "/home/johndoe/Projects/polars/repro.py", line 3, in <module>
    s = pl.Series([[None], [[0]]], dtype = pl.Array(pl.Time, (1, 1)))
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/johndoe/Projects/polars/py-polars/polars/series/series.py", line 288, in __init__
    self._s = sequence_to_pyseries(
              ^^^^^^^^^^^^^^^^^^^^^
  File "/home/johndoe/Projects/polars/py-polars/polars/_utils/construction/series.py", line 249, in sequence_to_pyseries
    pyseries = PySeries.new_series_list(name, pyseries_list, strict)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
pyo3_runtime.PanicException: called `Result::unwrap()` on an `Err` value: InvalidOperation(ErrString("It is not possible to concatenate arrays of different data types."))
```

### Issue description

A panic when decoding from Parquet.

It seems to convert `Time64` values to `Int64` if the row is not an array with only `nulls`.

### Expected behavior

No panic.

### Installed versions

<details>

```
Replace this line with the output of pl.show_versions(). Leave the backticks in place.
```

</details>

**Comment by coastalwhite** [comment]
This no longer reproduces. Closing.
