### ISSUE TITLE
Run then() and otherwise() expressions depending on result of when()

### ISSUE THREAD

**Issue by itamarst** [pola-rs/polars#17601]
### Description

(Moved out of #15091, since it's different issue)

Right now `when(when_expr).then(truthy_expr).otherwise(falsy_expr)` runs the `truthy_expr` and `falsy_expr` on all data, regardless of whether the results will be used or dropped based on `when_expr`. This is documented, but users find it surprising, and it's not clear how else users might get the desired effect.

Here's an example:

```python
import polars as pl

df = (
    pl.DataFrame({"idx": [0, 1, 2], "x": [3, 4, 5]})
    .group_by_dynamic(
        "idx",
        every="1i",
        offset="0i",  # '1i' or '2i' has no effect on the window
        period="2i",
    )
    .agg(
        pl.when(pl.col("x").count() > 1)
        .then(pl.col("x").get(1))
        .otherwise(pl.col("x").get(0) + 100)
    )  # throws
)
print(df)
```

Naively one would expect this to work, since `pl.col("x").get(1)` seemingly is only called if `pl.col("x").count() > 1`. In fact, it fails because the truthy expression is run on all data:

```
Traceback (most recent call last):
  File "/home/itamarst/devel/polars/py-polars/../15091.py", line 11, in <module>
    .agg(
  File "/home/itamarst/devel/polars/py-polars/polars/dataframe/group_by.py", line 980, in agg
    self.df.lazy()
  File "/home/itamarst/devel/polars/py-polars/polars/lazyframe/frame.py", line 1942, in collect
    return wrap_df(ldf.collect(callback))
polars.exceptions.OutOfBoundsError: index out of bounds

Error originated in expression: 'col("x").get(1)'
```

### Alternative 1: only run truthy or falsey expression, not both, depending on the `when_expr`

Polars could change to only run the truthy expression when the `when_expr` was true, and the falsy expression when `when_expr` was false.

Potential issues:
* It's unclear how to get backwards compatible semantics. Currently the return dtype is based on _both_ the dtype of the falsey and the truthy expressions output. This dtype is unknowable in some situations without actually running the code, for example if one is doing `pl.col("x").map_batches(some_python_function)`. In situations where only one branch is taken, how can the return dtype take into account the dtype of the other branch? Perhaps any calls to Python functions should require the return dtype be specified manually by the user? But that's not backwards compatible either.
* This may be slower in some cases (no batch operations). On the other hand it might be faster in some cases (typically only one expression will be run per value, rather than both truthy and falsy expressions as is currently the case).

### Alternative 2: don't abort whole run if an expression errors

In the example above, we run `truthy_expr` on three items; it fails on one out of the three, which means the whole evaluation fails with that error. But in a ternary expression, we can imagine throwing away that result if the `when_expr` happens to be False.

So conceptually one can imagine returning `Series<Result<T>>` instead of `Series<T>`. Given `Series` can't do that, it'd probably be something like returning `(Vec<Option<Error>>, Series<T>)` where indexes with an error are nulled out in the `Series`.

Then, a ternary expression would be able to run `truthy_expr` and `falsy_expr` on all data items in advance, and then choose the appropriate ones, and errors were be ignored if they're in the unchosen branch.

This would be a much less isolated change, since it would need to change the `PhysicalExpr` trait and then all of its implementations. And might also need to change error handling much more deeply in Polars.

### Questions

* Before I spend more time on this, would a PR implementing this be accepted at all, or are the current semantics sufficiently desirable that no change would be accepted?
* If the current semantics are desirable, what should users do as workaround? I can update documentation at least.
* If current semantics are not desirable, which of the alternatives above seems best? Is there another alternative I didn't think of?

**Comment by barak1412** [comment]
@stinodego stated this behavior will be remained -https://github.com/pola-rs/polars/issues/17405

So maybe Alternative 2 will be more welcomed.

**Comment by ritchie46** [comment]
> This dtype is unknowable in some situations without actually running the code

That's not allowed in Polars. The output of an operation should always be dependent of its input types (there are only a few exceptions, mostly inference related).  In `pl.col("x").map_batches(some_python_function)` the user should provide the correct output type. This is documented.


Alternative 2 I am also not happy about as that would only work if all is `false` or all is `true`. For partial truthness we would now have different behaviors. 

I am strongly opposed to any change on this as that would mean we should execute procedural where all of our expressions are vectorized executions, not in interpreter over single values. Polars is not built for this. If you need procedural execution you can branch in `map_elements` yourself. Python is built for single element evaluation.

**Comment by itamarst** [comment]
Ok, so the design constraint is can't make existing supported queries slower. But ideally there would be a way to address unsupported queries (e.g. the example above) work faster. (The Python fallback works, but so very slowly.)

@ritchie46 I am not sure why alternative 2 would only work if everything is true or false? The basic algorithm would be:

1. Get all truthy results, and all falsy results. This is no different than current code, except we'd set a flag that accumulates errors by index (`Vec<(usize, Error)>`?) in addition to actual results. For those indexes that errored, the result would be null.
2. Calculate mask.
3. Using the mask, for all true values check if there are any errors in the truthy `Vec<(usize, Error)>`, or any false values in the falsy `Vec<(usize, Error)>`. If yes, error out.
4. Otherwise, proceed with current algorithm.

So in the currently supported path, you've created two extra vecs, and done a few extra checks and that's about it (maybe `Vec<(usize, Error)>` should be a `HashSet` instead, so the checks are cheaper? some variant no doubt could be workable).

In the unsupported path, you've accumulated errors and done more work, but at least it's supported, and it would still run at same basic speed as supported path.

The main issue that I see is that having a mode where errors is accumulated might percolate throughout large parts of the code base, to the point where it's not worth the benefit.

**Comment by itamarst** [comment]
Actually I guess the "accumulate errors instead of returning" might have more performance cost than the above suggests, since it would involve checks in every location where there's an error. Though not necessarily much more than the `?` try operator.

The maintainability/widespread code change still seems like the biggest concern.

**Comment by itamarst** [comment]
### Alternative 3

By default, run current algorithm. If it errors out, switch to alternative 1 above (one by one choice of truthy or falsy).

This has the downside of doing a whole bunch of extra work before proceeding to the slower path, making the slower path even slower. But probably still faster than using Python :sob:

**Comment by cmdlineluser** [comment]
> If the current semantics are desirable, what should users do as workaround?

I have a potentially silly question.

Modifying the example slightly:

```python
import polars as pl

df = pl.from_repr("""
┌─────┬─────┐
│ idx ┆ x   │
│ --- ┆ --- │
│ i64 ┆ i64 │
╞═════╪═════╡
│ 0   ┆ 3   │
│ 0   ┆ 4   │
│ 1   ┆ 4   │
│ 1   ┆ 5   │
│ 2   ┆ 5   │
└─────┴─────┘
""")

(
    df.group_by("idx", maintain_order=True)
    .agg(
        true  = pl.col.x.filter(pl.col.x.count() > 1),
        false = pl.col.x.filter((pl.col.x.count() > 1).not_())
    )
    .with_columns(
        pl.when(pl.col("true", "false") != [])
          .then(pl.col("true", "false"))
    )
    .with_columns(
        x = pl.coalesce(
            pl.col.true.list.get(1), 
            pl.col.false.list.get(0) + 100
        )
    )
)
```

```python
shape: (3, 4)
┌─────┬───────────┬───────────┬─────┐
│ idx ┆ true      ┆ false     ┆ x   │
│ --- ┆ ---       ┆ ---       ┆ --- │
│ i64 ┆ list[i64] ┆ list[i64] ┆ i64 │
╞═════╪═══════════╪═══════════╪═════╡
│ 0   ┆ [3, 4]    ┆ null      ┆ 4   │
│ 1   ┆ [4, 5]    ┆ null      ┆ 5   │
│ 2   ┆ null      ┆ [5]       ┆ 105 │
└─────┴───────────┴───────────┴─────┘
```

Would it be possible to do this directly in `agg` with some hypothetical function?

```python
.agg(
    pl.coalesce(
        pl.col.x.NAME_ME(pl.col.x.count() > 1).get(1),
        pl.col.x.NAME_ME((pl.col.x.count() > 1).not_()).get(0) + 100
    )
)
```

Which I guess would be similar to the `filter`, but in the case of `[]` it would propagate `null` instead?

**Comment by deanm0000** [comment]
I made [this](https://github.com/pola-rs/polars/issues/11985) suggestion a while ago which is like 80% of alternative 2 except it would make it never raise instead of tracking if an error is picked by the when.

**Comment by itamarst** [comment]
> I made [this](https://github.com/pola-rs/polars/issues/11985) suggestion a while ago which is like 80% of alternative 2 except it would make it never raise instead of tracking if an error is picked by the when.

Tracking errors would be nicer for debugging, but suppressing errors would at least make this case possible, so if #11985 is an acceptable solution I could go figure it out.

**Comment by cmdlineluser** [comment]
So it seems outside of `.agg` you can get a bit closer to the coalesce(true, false) pattern:

```python
mask = lambda cond: (
    pl.when(
        pl.col.x.filter(cond).over("idx", mapping_strategy="join").list.len() > 0
    ).then(
        pl.col.x.filter(cond).over("idx", mapping_strategy="join")
          .cast(pl.List(pl.Int64)) # needed to avoid SchemaError, bug?
    )
)

cond = pl.col.x.count() > 1

df.with_columns(
    pl.coalesce(
        mask(cond).list.get(1), 
        mask(cond.not_()).list.get(0) + 100
    )
)

# shape: (5, 2)
# ┌─────┬─────┐
# │ idx ┆ x   │
# │ --- ┆ --- │
# │ i64 ┆ i64 │
# ╞═════╪═════╡
# │ 0   ┆ 4   │
# │ 0   ┆ 4   │
# │ 1   ┆ 5   │
# │ 1   ┆ 5   │
# │ 2   ┆ 105 │
# └─────┴─────┘
```

Would some sort of `Expr.mask` be possible / make sense?

Something that just nulled out values not matching the condition, so that we could potentially write `pl.col.x.mask(cond).get(1)`

**Comment by ritchie46** [comment]
I don't want to go into the details, but all of this would be terrible expensive and therefore not a direction I want to go in.
