### ISSUE TITLE
Printing a LazyFrame triggers resolving to the IR

### ISSUE THREAD

**Issue by stinodego** [pola-rs/polars#17652]
### Checks

- [X] I have checked that this issue has not already been reported.
- [X] I have confirmed this bug exists on the [latest version](https://pypi.org/project/polars/) of Polars.

### Reproducible example

```python
import polars as pl

lf = pl.scan_parquet("nonexistent.parquet")
print(lf)
```

### Log output

```shell
Traceback (most recent call last):
  File "/home/stijn/code/polars/py-polars/repro.py", line 4, in <module>
    print(lf)
  File "/home/stijn/code/polars/py-polars/polars/lazyframe/frame.py", line 624, in __str__
    {self.explain(optimized=False)}\
     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/stijn/code/polars/py-polars/polars/lazyframe/frame.py", line 1107, in explain
    return self._ldf.describe_plan()
           ^^^^^^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: No such file or directory (os error 2): nonexistent.parquet
```

### Issue description

The `__str__` implementation of LazyFrame points to `explain`, but `explain` will trigger DSL resolving. That means that printing is impossible on LazyFrames that would error on execution.

### Expected behavior

Should print the non-resolved plan. Perhaps `explain` should not resolve to the IR at all?

### Installed versions

main

**Comment by coastalwhite** [comment]
I implemented this not too long ago. We did it then to reduce the maintenance burden. If you want we can just revert part of that PR and have different print for the dsl and IR.
