### ISSUE TITLE
Cannot tell if hvplot version 0.10.0 >= 0.9.1

### ISSUE THREAD

**Issue by lmocsi** [pola-rs/polars#17668]
### Checks

- [X] I have checked that this issue has not already been reported.
- [X] I have confirmed this bug exists on the [latest version](https://pypi.org/project/polars/) of Polars.

### Reproducible example

```python
!pip install hvplot
import polars as pl
import hvplot

hvplot.extension("plotly")   # Setting the backend
plt = pl.DataFrame({"x": [1, 2, 3], "y": [3, 2, 1]}).plot.bar()
hvplot.show(plt)
```

### Log output

```shell
Traceback (most recent call last):
  File "/tmp/1000780000/ipykernel_7910/1858297842.py", line 6, in <module>
    plt = pl.DataFrame({"x": [1, 2, 3], "y": [3, 2, 1]}).plot.bar()
  File "/opt/conda/envs/Python-3.9-Premium/lib/python3.9/site-packages/polars/_utils/unstable.py", line 58, in wrapper
    return function(*args, **kwargs)
  File "/opt/conda/envs/Python-3.9-Premium/lib/python3.9/site-packages/polars/dataframe/frame.py", line 637, in plot
    raise ModuleUpgradeRequiredError(msg)
polars.exceptions.ModuleUpgradeRequiredError: hvplot>=0.9.1 is required for `.plot`
```

### Issue description

Just installed the most recent hvplot package (0.10.0), then trying to run the code in https://github.com/pola-rs/polars/issues/17647 throws the above ModuleUpgradeRequiredError.
As if could not tell, that 0.10.0 >= 0.9.1

### Expected behavior

Be able to check version number

### Installed versions

<details>

```
--------Version info---------
Polars:               1.1.0
Index type:           UInt32
Platform:             Linux-4.18.0-372.76.1.el8_6.x86_64-x86_64-with-glibc2.28
Python:               3.9.13 (main, Oct 13 2022, 21:15:33) 
[GCC 11.2.0]

----Optional dependencies----
adbc_driver_manager:  <not installed>
cloudpickle:          2.0.0
connectorx:           <not installed>
deltalake:            <not installed>
fastexcel:            <not installed>
fsspec:               2022.02.0
gevent:               <not installed>
great_tables:         <not installed>
hvplot:               0.10.0
matplotlib:           3.8.4
nest_asyncio:         1.5.5
numpy:                1.23.5
openpyxl:             3.0.9
pandas:               2.2.2
pyarrow:              16.1.0
pydantic:             <not installed>
pyiceberg:            <not installed>
sqlalchemy:           1.4.27
torch:                1.10.2
xlsx2csv:             <not installed>
xlsxwriter:           3.2.0
```

</details>

**Comment by MarcoGorelli** [comment]
I suspect you need to restart and re-run your jupyter notebook

**Comment by lmocsi** [comment]
It cannot run in cloud so I cannot test it more, closing this issue.
