### ISSUE TITLE
Panic when call `hash()` on `struct` dtype

### ISSUE THREAD

**Issue by ruihe774** [pola-rs/polars#17689]
### Checks

- [X] I have checked that this issue has not already been reported.
- [X] I have confirmed this bug exists on the [latest version](https://pypi.org/project/polars/) of Polars.

### Reproducible example

```python
import polars as pl
df = pl.DataFrame({"a": [1, 2, 3], "b": [4, 5, 6]})
df = df.select(pl.struct(pl.all()))
df = df.select(pl.struct(pl.all()))

# this panics
print(df.select(pl.col("a").hash()))
```

### Log output

```shell
thread '<unnamed>' panicked at /home/runner/work/polars/polars/crates/polars-ops/src/series/ops/various.rs:63:52:
called `Result::unwrap()` on an `Err` value: InvalidOperation(ErrString("`vec_hash` operation not supported for dtype `struct[1]`"))
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
Traceback (most recent call last):
  File "/var/home/msk/mcckit/test.py", line 7, in <module>
    print(df.select(pl.col("a").hash()))
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/msk/.conda/envs/mcckit/lib/python3.12/site-packages/polars/dataframe/frame.py", line 8618, in select
    return self.lazy().select(*exprs, **named_exprs).collect(_eager=True)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/msk/.conda/envs/mcckit/lib/python3.12/site-packages/polars/lazyframe/frame.py", line 1942, in collect
    return wrap_df(ldf.collect(callback))
                   ^^^^^^^^^^^^^^^^^^^^^
pyo3_runtime.PanicException: called `Result::unwrap()` on an `Err` value: InvalidOperation(ErrString("`vec_hash` operation not supported for dtype `struct[1]`"))
```

### Issue description

Polars 1.2 panics when call `hash()` on `struct` dtype, while Polars 1.1 did not.

### Expected behavior

Output of Polars 1.1:
```
shape: (3, 1)
┌──────────────────────┐
│ a                    │
│ ---                  │
│ u64                  │
╞══════════════════════╡
│ 4765690112321800547  │
│ 13496407243000087834 │
│ 3120322361086630706  │
└──────────────────────┘
```

### Installed versions

<details>

```
--------Version info---------
Polars:               1.2.0
Index type:           UInt32
Platform:             Linux-6.9.9-200.fc40.x86_64-x86_64-with-glibc2.39
Python:               3.12.3 | packaged by conda-forge | (main, Apr 15 2024, 18:38:13) [GCC 12.3.0]

----Optional dependencies----
adbc_driver_manager:  <not installed>
cloudpickle:          <not installed>
connectorx:           <not installed>
deltalake:            <not installed>
fastexcel:            <not installed>
fsspec:               <not installed>
gevent:               <not installed>
great_tables:         <not installed>
hvplot:               0.10.0
matplotlib:           3.9.1
nest_asyncio:         1.6.0
numpy:                2.0.0
openpyxl:             <not installed>
pandas:               2.2.2
pyarrow:              16.1.0
pydantic:             <not installed>
pyiceberg:            <not installed>
sqlalchemy:           <not installed>
torch:                <not installed>
xlsx2csv:             <not installed>
xlsxwriter:           <not installed>
```

</details>

I tried HEAD as well.

**Comment by coastalwhite** [comment]
@ritchie46 this is likely another bug with the struct refactor.
