### ISSUE TITLE
Panic on datetime column min()

### ISSUE THREAD

**Issue by Jex-y** [pola-rs/polars#17713]
### Checks

- [X] I have checked that this issue has not already been reported.
- [X] I have confirmed this bug exists on the [latest version](https://pypi.org/project/polars/) of Polars.

### Reproducible example

```python
from datetime import datetime

import polars as pl

df = pl.DataFrame().with_columns(
    pl.datetime_range(datetime(2024, 7, 18), datetime(2024, 7, 19), '15m').alias(
        'datetime'
    )
)

print(df['datetime'].min())

df = df.with_columns(pl.col('datetime').dt.replace_time_zone('UTC'))

print(df['datetime'].min())

>>> 2024-07-18 00:00:00
>>> thread '<unnamed>' panicked at py-polars\src\conversion\any_value.rs:84:22:
>>> called `Result::unwrap()` on an `Err` value: PyErr { type: <class 'ValueError'>, value: ValueError("unexpected time zone offset: 'Europe/London'"), traceback: Some(<traceback object at 0x00000144BF81DB80>) }
>>> note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
>>> Traceback (most recent call last):
>>>   File "D:\code\river-level-analysis\hydro-api\tests\polars_bug.py", line 15, in <module>
>>>     print(df['datetime'].min())
>>>           ^^^^^^^^^^^^^^^^^^^^
>>>   File "D:\code\river-level-analysis\hydro-api\.venv\Lib\site-packages\polars\series\series.py", line 1980, in min
>>>     return self._s.min()
>>>            ^^^^^^^^^^^^^
>>> pyo3_runtime.PanicException: called `Result::unwrap()` on an `Err` value: PyErr { type: <class 'ValueError'>, value: ValueError("unexpected time zone offset: 'Europe/London'"), traceback: Some(<traceback object at 0x00000144BF81DB80>) }
```

### Log output

```shell
thread '<unnamed>' panicked at py-polars\src\conversion\any_value.rs:84:22:
called `Result::unwrap()` on an `Err` value: PyErr { type: <class 'ValueError'>, value: ValueError("unexpected time zone offset: 'UTC'"), traceback: Some(<traceback object at 0x000002249D6ADBC0>) }
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
Traceback (most recent call last):
  File "D:\code\river-level-analysis\hydro-api\tests\polars_bug.py", line 15, in <module>
    print(df['datetime'].min())
          ^^^^^^^^^^^^^^^^^^^^
  File "D:\code\river-level-analysis\hydro-api\.venv\Lib\site-packages\polars\series\series.py", line 1980, in min
    return self._s.min()
           ^^^^^^^^^^^^^
pyo3_runtime.PanicException: called `Result::unwrap()` on an `Err` value: PyErr { type: <class 'ValueError'>, value: ValueError("unexpected time zone offset: 'UTC'"), traceback: Some(<traceback object at 0x000002249D6ADBC0>) }
```

### Issue description

This appears to happen with other timezones as well, not just UTC. E.g. Europe/London also produced the same error.

### Expected behavior

Should not panic and should return a timezone aware datetime like: 2024-07-18 00:00:00+00:00

### Installed versions

<details>

```
>>> pl.show_versions()  
--------Version info---------
Polars:               1.2.1
Index type:           UInt32
Platform:             Windows-10-10.0.19045-SP0
Python:               3.11.9 | packaged by Anaconda, Inc. | (main, Apr 19 2024, 16:40:41) [MSC v.1916 64 bit (AMD64)]

----Optional dependencies----
adbc_driver_manager:  <not installed>
cloudpickle:          <not installed>
connectorx:           <not installed>
deltalake:            <not installed>
fastexcel:            <not installed>
fsspec:               <not installed>
gevent:               <not installed>
great_tables:         <not installed>
hvplot:               <not installed>
matplotlib:           <not installed>
nest_asyncio:         <not installed>
numpy:                <not installed>
openpyxl:             <not installed>
pandas:               <not installed>
pyarrow:              <not installed>
pydantic:             <not installed>
pyiceberg:            <not installed>
sqlalchemy:           <not installed>
torch:                <not installed>
xlsx2csv:             <not installed>
xlsxwriter:           <not installed>
```

</details>

**Comment by Jex-y** [comment]
I forgot to install with timezones. It now works with this installed, however an error message rather than a panic would be an improvement.

**Comment by blaylockbk** [comment]
Glad this showed up in my web searching. I couldn't figure out why my tests on Windows always failed. Found in the docs that it indeed says timezones is...

> Only needed if you are on Python < 3.9 or you are on Windows. 

Thanks! (I agree, it would be nice if the error told me I was missing timezones)

**Comment by etiennebacher** [comment]
This no longer panics, it returns:

```
2024-07-18 00:00:00
2024-07-18 00:00:00+00:00
```
