### ISSUE TITLE
`pl.cum_count()` with no arguments does not work as documented

### ISSUE THREAD

**Issue by Oreilles** [pola-rs/polars#17796]
### Checks

- [X] I have checked that this issue has not already been reported.
- [X] I have confirmed this bug exists on the [latest version](https://pypi.org/project/polars/) of Polars.

### Reproducible example

```python
pl.DataFrame().select(pl.cum_count())
```

### Log output

```shell
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File ".../.venv/lib/python3.12/site-packages/polars/functions/lazy.py", line 208, in cum_count
    return F.col(*columns).cum_count(reverse=reverse)
           ^^^^^^^^^^^^^^^
TypeError: Col.__call__() missing 1 required positional argument: 'name'
```

### Issue description

According to the documentation for `pl.cum_count`:
> If no arguments are passed, returns the cumulative count of a context. Rows containing null values count towards the result.

However, when used within a context without arguments, the functions raises.

### Expected behavior

```python
pl.DataFrame().select(pl.cum_count())
# should return 0
```

### Installed versions

<details>

```
--------Version info---------
Polars:               1.2.0
Index type:           UInt32
Platform:             macOS-14.5-arm64-arm-64bit
Python:               3.12.4 (main, Jun  6 2024, 18:26:44) [Clang 15.0.0 (clang-1500.3.9.4)]

----Optional dependencies----
adbc_driver_manager:  <not installed>
cloudpickle:          <not installed>
connectorx:           <not installed>
deltalake:            <not installed>
fastexcel:            <not installed>
fsspec:               <not installed>
gevent:               <not installed>
great_tables:         <not installed>
hvplot:               <not installed>
matplotlib:           3.9.1
nest_asyncio:         1.6.0
numpy:                2.0.0
openpyxl:             3.1.5
pandas:               2.2.2
pyarrow:              17.0.0
pydantic:             2.8.2
pyiceberg:            <not installed>
sqlalchemy:           <not installed>
torch:                <not installed>
xlsx2csv:             <not installed>
xlsxwriter:           <not installed>
```

</details>

**Comment by ahmadsaadat** [comment]
Hi @Oreilles, try passing a column name like pl.cum_count(COLUMN_NAME)

see this documentation for version >= 1.0.0:
https://docs.pola.rs/api/python/stable/reference/expressions/api/polars.cum_count.html#polars-cum-count

Hope it helps
