### ISSUE TITLE
`the name 'literal' is duplicate` when selecting a multi-element NumPy array or list

### ISSUE THREAD

**Issue by Wainberg** [pola-rs/polars#17801]
### Checks

- [X] I have checked that this issue has not already been reported.
- [X] I have confirmed this bug exists on the [latest version](https://pypi.org/project/polars/) of Polars.

### Reproducible example

NumPy array:

```python
>>> pl.DataFrame().select(np.array([1]))
 literal
 1
shape: (1, 1)
>>> pl.DataFrame().select(np.array([1, 2]))
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File ".../polars/dataframe/frame.py", line 8672, in select
    return self.lazy().select(*exprs, **named_exprs).collect(_eager=True)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File ".../polars/lazyframe/frame.py", line 1942, in collect
    return wrap_df(ldf.collect(callback))
                   ^^^^^^^^^^^^^^^^^^^^^
polars.exceptions.DuplicateError: the name 'literal' is duplicate

It's possible that multiple expressions are returning the same default column name. If this is the case, try renaming the columns with `.alias("new_name")` to avoid duplicate column names.
>>> pl.DataFrame().select(literal=np.array([1, 2]))
 literal
 1
 2
shape: (2, 1)
```

List:
```python
>>> pl.DataFrame().select([1])
 literal
 1
shape: (1, 1)
>>> pl.DataFrame().select([1, 2])
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File ".../polars/dataframe/frame.py", line 8672, in select
    return self.lazy().select(*exprs, **named_exprs).collect(_eager=True)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File ".../polars/lazyframe/frame.py", line 1942, in collect
    return wrap_df(ldf.collect(callback))
                   ^^^^^^^^^^^^^^^^^^^^^
polars.exceptions.DuplicateError: the name 'literal' is duplicate

It's possible that multiple expressions are returning the same default column name. If this is the case, try renaming the columns with `.alias("new_name")` to avoid duplicate column names.
>>> pl.DataFrame().select(literal=[1, 2])
 literal
 [1, 2]
shape: (1, 1)
```

### Issue description

`select()`ing a NumPy array or list with more than one element gives the error `the name 'literal' is duplicate`, presumably because polars tries to interpret each element as a column. Assigning a column name (e.g. `'literal'`) via a keyword argument succeeds and creates a single-column DataFrame, which is inconsistent.

### Expected behavior

For NumPy arrays, `pl.DataFrame().select(np.array([1, 2]))` should give the same result as `pl.DataFrame().select(literal=np.array([1, 2]))`. 

For lists, `pl.DataFrame().select([1, 2])` should give the same result as `pl.DataFrame().select(literal=[1, 2])`. These should also both match NumPy arrays, since currently `pl.DataFrame().select(literal=[1])` gives an integer column while `pl.DataFrame().select(literal=[1, 2])` gives a list-of-integer column.

### Installed versions

<details>

```
Replace this line with the output of pl.show_versions(). Leave the backticks in place.
```

</details>

**Comment by coastalwhite** [comment]
I don't think there is much that can be done here. The first argument accepts `Iterable[IntoExpr]`. I don't think we should special case NumPy arrays here.
