### ISSUE TITLE
Concat of columns with lists of objects raises error

### ISSUE THREAD

**Issue by matt035343** [pola-rs/polars#17806]
### Checks

- [X] I have checked that this issue has not already been reported.
- [X] I have confirmed this bug exists on the [latest version](https://pypi.org/project/polars/) of Polars.

### Reproducible example

```python
pl.DataFrame({
  'A': [1,2], 
  'B': [[object()],[object()]], 
  'C': [[object()],[object()]]
}).select(
  col('B').list.concat(col('C'))
)
```

### Log output

```shell
Traceback (most recent call last):
  File "/opt/pycharm-2023.1.2/plugins/python/helpers/pydev/_pydevd_bundle/pydevd_exec2.py", line 3, in Exec
    exec(exp, global_vars, local_vars)
  File "<input>", line 1, in <module>
  File "/home/mata/.cache/pypoetry/virtualenvs/ecco-auto-replenishment-mip-wbg8xxpV-py3.11/lib/python3.11/site-packages/polars/dataframe/frame.py", line 8618, in select
    return self.lazy().select(*exprs, **named_exprs).collect(_eager=True)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/mata/.cache/pypoetry/virtualenvs/ecco-auto-replenishment-mip-wbg8xxpV-py3.11/lib/python3.11/site-packages/polars/lazyframe/frame.py", line 1942, in collect
    return wrap_df(ldf.collect(callback))
                   ^^^^^^^^^^^^^^^^^^^^^
polars.exceptions.InvalidOperationError: `list_builder` operation not supported for dtype `extension`
```

### Issue description

I generally use dataframes with object columns and object list columns. I have noticed this operation does not work in polars.
Generally, I have two (or more) columns with lists of objects that need to be concatenated.

Changing the example to concatenating lists of integers works fine.

### Expected behavior

I expected following result:

```python
pl.DataFrame({
  'B': [[object(), object()], [object() ,object()]]
})
```

### Installed versions

<details>

```
--------Version info---------
Polars:               1.2.1
Index type:           UInt32
Platform:             Linux-5.15.153.1-microsoft-standard-WSL2-x86_64-with-glibc2.35
Python:               3.11.9 (main, Apr  6 2024, 17:59:24) [GCC 11.4.0]
----Optional dependencies----
adbc_driver_manager:  <not installed>
cloudpickle:          <not installed>
connectorx:           <not installed>
deltalake:            <not installed>
fastexcel:            <not installed>
fsspec:               2024.6.1
gevent:               <not installed>
great_tables:         <not installed>
hvplot:               <not installed>
matplotlib:           <not installed>
nest_asyncio:         <not installed>
numpy:                1.26.4
openpyxl:             <not installed>
pandas:               2.2.2
pyarrow:              17.0.0
pydantic:             2.8.2
pyiceberg:            <not installed>
sqlalchemy:           <not installed>
torch:                <not installed>
xlsx2csv:             <not installed>
xlsxwriter:           <not installed>

```

</details>

**Comment by ritchie46** [comment]
I don't want to support that. It leads to all kinds of problems as every nested data type has gone from plain old data to reference counted objects that requires the python process and a  GIL lock to drop them. 

If you want to do nesting with objects do it within the objects itself. E.g. create python lists.

**Comment by matt035343** [comment]
@ritchie46 I don't know if I understand your suggestion correctly, but are you suggesting to store the objects separately from the dataframe in a simpler data structure (such as pure Python lists or np arrays)? 
That would complicate things a bit in my use case since there is a direct relation between the other rows in the dataframe and the object columns. Needing to maintain indexing/order across lists and dataframe is a bit inconvenient

**Comment by matt035343** [comment]
For anyone else reading this issue, concatenating two dataframes with lists of objects also does not work:

```python
pl.concat([pl.DataFrame({'A': [[object()]]}),pl.DataFrame({'A': [[object()]]})])
```

**Comment by henrikfoss** [comment]
I too would like to request this feature :)
