### ISSUE TITLE
ColumnNotFoundError in `polars.DataFrame.join` with `how='right'` and different `left_on` and `right_on` columns

### ISSUE THREAD

**Issue by kartoria** [pola-rs/polars#17831]
### Checks

- [X] I have checked that this issue has not already been reported.
- [X] I have confirmed this bug exists on the [latest version](https://pypi.org/project/polars/) of Polars.

### Reproducible example

```python
import polars as pl

df = pl.DataFrame(
    {
        "foo": [1, 2, 3],
        "bar": [6.0, 7.0, 8.0],
        "ham1": ["a", "b", "c"],
    }
)
other_df = pl.DataFrame(
    {
        "apple": ["x", "y", "z"],
        "ham2": ["a", "b", "d"],
    }
)

df.join(other_df, left_on="ham1", right_on="ham2", how="right")

```

### Log output

```shell
Traceback (most recent call last):
  File "/idfilter/test.py", line 19, in <module>
    df.join(other_df, left_on="ham1", right_on="ham2", how="right")
  File "lib/python3.11/site-packages/polars/dataframe/frame.py", line 6828, in join
    .collect(_eager=True)
     ^^^^^^^^^^^^^^^^^^^^
  File "lib/python3.11/site-packages/polars/lazyframe/frame.py", line 1942, in collect
    return wrap_df(ldf.collect(callback))
                   ^^^^^^^^^^^^^^^^^^^^^
polars.exceptions.ColumnNotFoundError: ham1
```

### Issue description

This does not occur when 'on' is used instead of 'left_on', 'right_on', and only how is 'right'
And it is an error only when 'how' is 'right'.

I can't speak English, so I wrote it using a translator.

### Expected behavior

`
import polars as pd
# same dataframe
pd.merge(df, other_df, left_on="ham1", right_on="ham2", how="right")
`

	foo	bar	ham1	apple	ham2
0	1.0	6.0	a	x	a
1	2.0	7.0	b	y	b
2	NaN	NaN	NaN	z	d

### Installed versions

<details>
--------Version info---------
Polars:               1.2.1
Index type:           UInt32
Platform:             Linux-3.10.0-1160.80.1.el7.x86_64-x86_64-with-glibc2.17
Python:               3.11.9 (main, Apr 19 2024, 16:48:06) [GCC 11.2.0]

----Optional dependencies----
adbc_driver_manager:  <not installed>
cloudpickle:          3.0.0
connectorx:           <not installed>
deltalake:            <not installed>
fastexcel:            <not installed>
fsspec:               2024.6.1
gevent:               <not installed>
great_tables:         <not installed>
hvplot:               <not installed>
matplotlib:           3.8.3
nest_asyncio:         1.6.0
numpy:                1.26.4
openpyxl:             3.1.2
pandas:               2.2.2
pyarrow:              15.0.2
pydantic:             <not installed>
pyiceberg:            <not installed>
sqlalchemy:           <not installed>
torch:                <not installed>
xlsx2csv:             <not installed>
xlsxwriter:           <not installed>
pl ver: None

</details>

**Comment by ritchie46** [comment]
Thanks for the report. That was silly. Fix coming up.

**Comment by kartoria** [comment]
> 보고해주셔서 감사합니다. 고맙습니다. 곧 수정하겠습니다.

Very fast! thanks you.
