### ISSUE TITLE
`.over()` fails with `.top_k_by`

### ISSUE THREAD

**Issue by Ge0rges** [pola-rs/polars#17883]
### Checks

- [X] I have checked that this issue has not already been reported.
- [X] I have confirmed this bug exists on the [latest version](https://pypi.org/project/polars/) of Polars.

### Reproducible example

```python
import polars as pl

# Sample data
    data = {
        "group": ["A", "A", "A", "A", "A", "B", "B", "B", "B", "B", "B", "C"],
        "score": [10, 20, 30, 40, 50, 15, 25, 35, 45, 55, 65, 1]
    }

    # Create a DataFrame
    df = pl.DataFrame(data)

    # Use top_k and over methods to filter the DataFrame
    filtered_df = df.select(pl.all().top_k_by("score", 2).over("group"))

```

### Log output

```shell
Traceback (most recent call last):
  File "/Applications/PyCharm.app/Contents/plugins/python/helpers/pydev/pydevd.py", line 1551, in _exec
    pydev_imports.execfile(file, globals, locals)  # execute the script
  File "/Applications/PyCharm.app/Contents/plugins/python/helpers/pydev/_pydev_imps/_pydev_execfile.py", line 18, in execfile
    exec(compile(contents+"\n", file, 'exec'), glob, loc)
  File "/Users/GeorgesKanaan/Documents/Development/Methylation/code/composite.py", line 174, in <module>
    filtered_df = df.select(pl.all().top_k_by("score", 2).over("group"))
  File "/Users/GeorgesKanaan/micromamba/envs/jupyter/lib/python3.10/site-packages/polars/dataframe/frame.py", line 8618, in select
    return self.lazy().select(*exprs, **named_exprs).collect(_eager=True)
  File "/Users/GeorgesKanaan/micromamba/envs/jupyter/lib/python3.10/site-packages/polars/lazyframe/frame.py", line 1942, in collect
    return wrap_df(ldf.collect(callback))
polars.exceptions.ComputeError: the length of the window expression did not match that of the group

Error originated in expression: 'col("group").top_k_by([dyn int: 2, col("score")]).over([col("group")])'
```

### Issue description

It seems like `pl.Expr.over` causes a crash when used in combination with `pl.Expr.top_k` or `pl.Expr.top_k_by`.

### Expected behavior

I expected the returned dataframe to have 2 or less rows per group, with the rows being those that have the highest score among the group.

### Installed versions

<details>

```
PyDev console: using IPython 8.17.2
--------Version info---------
Polars:               1.2.1
Index type:           UInt32
Platform:             macOS-14.5-arm64-arm-64bit
Python:               3.10.14 | packaged by conda-forge | (main, Mar 20 2024, 12:51:49) [Clang 16.0.6 ]
----Optional dependencies----
adbc_driver_manager:  <not installed>
cloudpickle:          3.0.0
connectorx:           <not installed>
deltalake:            <not installed>
fastexcel:            <not installed>
fsspec:               2024.6.0
gevent:               <not installed>
great_tables:         <not installed>
hvplot:               <not installed>
matplotlib:           3.8.4
nest_asyncio:         1.5.8
numpy:                1.26.4
openpyxl:             3.1.2
pandas:               2.2.2
pyarrow:              15.0.0
pydantic:             1.10.8
pyiceberg:            <not installed>
sqlalchemy:           <not installed>
torch:                <not installed>
xlsx2csv:             <not installed>
xlsxwriter:           <not installed>
```

</details>

**Comment by Ge0rges** [comment]
Work around: ` filtered_df = df.group_by("group").agg([pl.col("score").top_k(2), pl.exclude("score")]).with_columns(pl.exclude("group").list.slice(0,2)).explode(pl.exclude("group"))`

**Comment by ritchie46** [comment]
This is expected. You also get a proper bug.  The result of the window expression must match the length of that group.

**Comment by cmdlineluser** [comment]
You can change the `mapping_strategy=`

```python
df.select(pl.all().top_k_by("score", 2).over("group", mapping_strategy="explode"))

# shape: (5, 2)
# ┌───────┬───────┐
# │ group ┆ score │
# │ ---   ┆ ---   │
# │ str   ┆ i64   │
# ╞═══════╪═══════╡
# │ A     ┆ 50    │
# │ A     ┆ 40    │
# │ B     ┆ 65    │
# │ B     ┆ 55    │
# │ C     ┆ 1     │
# └───────┴───────┘
```

Which is basically:

```python
df.group_by("group").agg(pl.all().top_k_by("score", 2)).explode("score")

# shape: (5, 2)
# ┌───────┬───────┐
# │ group ┆ score │
# │ ---   ┆ ---   │
# │ str   ┆ i64   │
# ╞═══════╪═══════╡
# │ A     ┆ 50    │
# │ A     ┆ 40    │
# │ B     ┆ 65    │
# │ B     ┆ 55    │
# │ C     ┆ 1     │
# └───────┴───────┘
```
