### ISSUE TITLE
Regression from 0.20.31 to 1.0.0 when reading deeply nested JSON with a schema: schema is ignored

### ISSUE THREAD

**Issue by mbschonborn** [pola-rs/polars#17956]
### Checks

- [X] I have checked that this issue has not already been reported.
- [X] I have confirmed this bug exists on the [latest version](https://pypi.org/project/polars/) of Polars.

### Reproducible example

It might just be me, but I think I found a bug regarding creating data frames from JSON data and how data types are inferred. I cannot for the life of me import a JSON object where there's deeply nestled within a list of numbers, where the list looks like a list of integers at first, but it's really a list of floats.

```python
import polars as pl
from polars import Struct, Field, List, Float64

schema = {
    "logged_event": Struct(
        [
            Field(
                "completetask",
                Struct(
                    [
                        Field(
                            "parameters",
                            List(
                                Struct(
                                    [
                                        Field(
                                            "numericarray",
                                            Struct(
                                                [
                                                    Field(
                                                        "value",
                                                        List(
                                                            Float64
                                                        )
                                                    ),
                                                ]
                                            ),
                                        ),
                                    ]
                                )
                            ),
                        ),
                    ]
                ),
            ),
        ]
    ),
}
 


data = {
    "logged_event": {
        "completetask": {
            "parameters": [ {
                "numericarray": {
                    "value": [
                        431,
                        431,
                        431,
                        431,
                        431,
                        431,
                        431,
                        431,
                        431,
                        431,
                        431,
                        431,
                        431,
                        431,
                        431,
                        431,
                        431,
                        431,
                        431,
                        431,
                        431,
                        431,
                        431,
                        431,
                        431,
                        431,
                        431,
                        431,
                        431,
                        431,
                        431,
                        431,
                        431,
                        431,
                        430.5,
                        431,
                        431,
                        431
                    ]
                }
            } ]
        }
    }
}


lazyframe = pl.LazyFrame(
    [ data ],
    schema = schema,
    strict = False,
    infer_schema_length = None,
)

print(lazyframe.collect())
```

With version 0.20.31 this works as expected:
```
shape: (1, 1)
┌─────────────────────────────────┐
│ logged_event                    │
│ ---                             │
│ struct[1]                       │
╞═════════════════════════════════╡
│ {{[{{[431.0, 431.0, … 431.0]}}… │
└─────────────────────────────────┘
```

But for Polars version 1.0.0 and 1.3.0 this gives:
```
Traceback (most recent call last):
  File "/home/mbschonborn/fusion/.venv/lib/python3.11/site-packages/polars/_utils/construction/series.py", line 309, in _construct_series_with_fallbacks
    return constructor(name, values, strict)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: 'float' object cannot be interpreted as an integer

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/mbschonborn/fusion/../schema_test.py", line 91, in <module>
    lazyframe = pl.LazyFrame(
                ^^^^^^^^^^^^^
  File "/home/mbschonborn/fusion/.venv/lib/python3.11/site-packages/polars/lazyframe/frame.py", line 307, in __init__
    DataFrame(
  File "/home/mbschonborn/fusion/.venv/lib/python3.11/site-packages/polars/dataframe/frame.py", line 369, in __init__
    self._df = sequence_to_pydf(
               ^^^^^^^^^^^^^^^^^
  File "/home/mbschonborn/fusion/.venv/lib/python3.11/site-packages/polars/_utils/construction/dataframe.py", line 462, in sequence_to_pydf
    return _sequence_to_pydf_dispatcher(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/mbschonborn/.pyenv/versions/3.11.4/lib/python3.11/functools.py", line 909, in wrapper
    return dispatch(args[0].__class__)(*args, **kw)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/mbschonborn/fusion/.venv/lib/python3.11/site-packages/polars/_utils/construction/dataframe.py", line 714, in _sequence_of_dict_to_pydf
    pydf = PyDataFrame.from_dicts(
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/mbschonborn/fusion/.venv/lib/python3.11/site-packages/polars/series/series.py", line 292, in __init__
    self._s = sequence_to_pyseries(
              ^^^^^^^^^^^^^^^^^^^^^
  File "/home/mbschonborn/fusion/.venv/lib/python3.11/site-packages/polars/_utils/construction/series.py", line 294, in sequence_to_pyseries
    return _construct_series_with_fallbacks(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/mbschonborn/fusion/.venv/lib/python3.11/site-packages/polars/_utils/construction/series.py", line 312, in _construct_series_with_fallbacks
    return PySeries.new_from_any_values(name, values, strict=strict)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: unexpected value while building Series of type Int64; found value of type Float64: 430.5

Hint: Try setting `strict=False` to allow passing data with mixed types.
```

### Log output

```shell
Traceback (most recent call last):
  File "/home/mbschonborn/fusion/.venv/lib/python3.11/site-packages/polars/_utils/construction/series.py", line 309, in _construct_series_with_fallbacks
    return constructor(name, values, strict)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: 'float' object cannot be interpreted as an integer

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/mbschonborn/fusion/../schema_test.py", line 91, in <module>
    lazyframe = pl.LazyFrame(
                ^^^^^^^^^^^^^
  File "/home/mbschonborn/fusion/.venv/lib/python3.11/site-packages/polars/lazyframe/frame.py", line 307, in __init__
    DataFrame(
  File "/home/mbschonborn/fusion/.venv/lib/python3.11/site-packages/polars/dataframe/frame.py", line 369, in __init__
    self._df = sequence_to_pydf(
               ^^^^^^^^^^^^^^^^^
  File "/home/mbschonborn/fusion/.venv/lib/python3.11/site-packages/polars/_utils/construction/dataframe.py", line 462, in sequence_to_pydf
    return _sequence_to_pydf_dispatcher(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/mbschonborn/.pyenv/versions/3.11.4/lib/python3.11/functools.py", line 909, in wrapper
    return dispatch(args[0].__class__)(*args, **kw)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/mbschonborn/fusion/.venv/lib/python3.11/site-packages/polars/_utils/construction/dataframe.py", line 714, in _sequence_of_dict_to_pydf
    pydf = PyDataFrame.from_dicts(
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/mbschonborn/fusion/.venv/lib/python3.11/site-packages/polars/series/series.py", line 292, in __init__
    self._s = sequence_to_pyseries(
              ^^^^^^^^^^^^^^^^^^^^^
  File "/home/mbschonborn/fusion/.venv/lib/python3.11/site-packages/polars/_utils/construction/series.py", line 294, in sequence_to_pyseries
    return _construct_series_with_fallbacks(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/mbschonborn/fusion/.venv/lib/python3.11/site-packages/polars/_utils/construction/series.py", line 312, in _construct_series_with_fallbacks
    return PySeries.new_from_any_values(name, values, strict=strict)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: unexpected value while building Series of type Int64; found value of type Float64: 430.5

Hint: Try setting `strict=False` to allow passing data with mixed types.
```

### Issue description

The LazyFrame cannot be constructed because somehow the schema is ignored and Polars tries to create a series of integeres, although it should be a series of floats. It works when commenting out enough integers before the float though.

### Expected behavior

The LazyFrame should be created successfully.

### Installed versions

<details>

```
--------Version info---------
Polars:               1.3.0
Index type:           UInt32
Platform:             Linux-5.15.153.1-microsoft-standard-WSL2-x86_64-with-glibc2.35
Python:               3.11.4 (main, Sep 11 2023, 14:38:02) [GCC 11.3.0]

----Optional dependencies----
adbc_driver_manager:  <not installed>
cloudpickle:          <not installed>
connectorx:           <not installed>
deltalake:            <not installed>
fastexcel:            <not installed>
fsspec:               <not installed>
gevent:               23.9.1
great_tables:         <not installed>
hvplot:               <not installed>
matplotlib:           <not installed>
nest_asyncio:         1.5.7
numpy:                1.26.1
openpyxl:             <not installed>
pandas:               2.2.2
pyarrow:              16.1.0
pydantic:             <not installed>
pyiceberg:            <not installed>
sqlalchemy:           <not installed>
torch:                <not installed>
xlsx2csv:             <not installed>
xlsxwriter:           <not installed>
```

</details>

**Comment by ritchie46** [comment]
Ai, I see the `strict` argument isn't passed recursively. Fix coming up.

**Comment by mbschonborn** [comment]
Thanks!
