### ISSUE TITLE
PanicException: implementation error in fill_null

### ISSUE THREAD

**Issue by phil-zxx** [pola-rs/polars#18051]
### Checks

- [X] I have checked that this issue has not already been reported.
- [X] I have confirmed this bug exists on the [latest version](https://pypi.org/project/polars/) of Polars.

### Reproducible example

```python
import polars as pl

dummy_data = {'sZcR': {'COL_sMy3': None, 'COL_mTmp': None, 'COL_rP05': 0.14, 'COL_YJbC': None, 'COL_ptRs': 64, 'COL_agEk': 91, 'COL_Bbmw': 0.17, 'COL_Lxcj': 0.99}, 'PVFG': {'COL_sMy3': None, 'COL_mTmp': None, 'COL_rP05': 0.83, 'COL_YJbC': None, 'COL_ptRs': 97, 'COL_agEk': 12, 'COL_Bbmw': 0.88, 'COL_Lxcj': 0.88}, 'YrgF': {'COL_sMy3': None, 'COL_mTmp': None, 'COL_rP05': 0.76, 'COL_YJbC': None, 'COL_ptRs': 51, 'COL_agEk': 49, 'COL_Bbmw': 0.59, 'COL_Lxcj': 0.17}, 'U1FT': {'COL_sMy3': None, 'COL_mTmp': None, 'COL_rP05': 0.28, 'COL_YJbC': None, 'COL_ptRs': 29, 'COL_agEk': 58, 'COL_Bbmw': 0.62, 'COL_Lxcj': 0.76}, 'fVHR': {'COL_sMy3': None, 'COL_mTmp': None, 'COL_rP05': 0.32, 'COL_YJbC': 0.37, 'COL_nBny': 0.83, 'COL_ZL2X': 0.98}, 'K4OR': {'COL_sMy3': None, 'COL_mTmp': None, 'COL_rP05': 0.32, 'COL_YJbC': 0.72, 'COL_nBny': 0.4, 'COL_ZL2X': 0.26}, 'SWTC': {'COL_sMy3': None, 'COL_mTmp': None, 'COL_rP05': 0.92, 'COL_YJbC': 0.97, 'COL_nBny': 0.68, 'COL_ZL2X': 0.88}, 'zPvt': {'COL_sMy3': None, 'COL_mTmp': None, 'COL_rP05': 0.26, 'COL_YJbC': 0.56, 'COL_nBny': 0.44, 'COL_ZL2X': 0.57}, 'FEN5': {'COL_sMy3': None, 'COL_mTmp': None, 'COL_rP05': 3, 'COL_YJbC': 45, 'COL_nBny': 14, 'COL_ZL2X': 34}, 'LWiB': {'COL_sMy3': None, 'COL_mTmp': None, 'COL_rP05': 0.03, 'COL_YJbC': 0.8, 'COL_nBny': 0.49, 'COL_ZL2X': 0.66}, 'GsHo': {'COL_sMy3': None, 'COL_mTmp': None, 'COL_rP05': 0.87, 'COL_YJbC': 0.64, 'COL_nBny': 0.49, 'COL_ZL2X': 0.18}, '2NW3': {'COL_sMy3': None, 'COL_mTmp': None, 'COL_rP05': 0.43, 'COL_YJbC': 0.22, 'COL_nBny': 0.8, 'COL_ZL2X': 0.41}, 'h39x': {'COL_sMy3': None, 'COL_mTmp': None, 'COL_rP05': 0.91, 'COL_YJbC': 0.62, 'COL_nBny': 0.05, 'COL_ZL2X': 0.49}, 'P1uR': {'COL_sMy3': None, 'COL_mTmp': None, 'COL_rP05': 0.09, 'COL_YJbC': 0.43, 'COL_nBny': 0.8, 'COL_ZL2X': 0.91}, '8hhd': {'COL_sMy3': None, 'COL_mTmp': None, 'COL_rP05': 0.64, 'COL_YJbC': 0.96, 'COL_nBny': 0.24, 'COL_ZL2X': 0.41}, 'yZAi': {'COL_sMy3': None, 'COL_mTmp': None, 'COL_rP05': 0.5, 'COL_YJbC': 0.55, 'COL_nBny': 0.83, 'COL_ZL2X': 0.47}, 'cnwg': {'COL_sMy3': None, 'COL_mTmp': None, 'COL_rP05': 37, 'COL_YJbC': 13, 'COL_nBny': 3, 'COL_ZL2X': 57}, '4dlc': {'COL_sMy3': None, 'COL_mTmp': None, 'COL_rP05': 0.16, 'COL_YJbC': 0.03, 'COL_nBny': 0.45, 'COL_ZL2X': 0.78}, 'It36': {'COL_sMy3': None, 'COL_mTmp': None, 'COL_rP05': 0.92, 'COL_YJbC': 0.43, 'COL_nBny': 0.47, 'COL_ZL2X': 0.95}, 'pH2N': {'COL_sMy3': None, 'COL_mTmp': None, 'COL_rP05': 0.88, 'COL_YJbC': 0.82, 'COL_nBny': 0.44, 'COL_ZL2X': 0.46}}
SCHEMA     = {'COL_rP05': pl.Float64, 'COL_sMy3': pl.Float64, 'COL_mTmp': pl.Float64, 'COL_YJbC': pl.Float64, 'COL_Bbmw': pl.Float64, 'COL_Lxcj': pl.Float64, 'COL_agEk': pl.Float64, 'COL_ptRs': pl.Float64, 'COL_qFEW': pl.Float64, 'COL_nBny': pl.Float64, 'COL_ZL2X': pl.Float64, 'COL_JJJz': pl.Object, 'COL_yEi2': pl.Object, 'COL_RYJB': pl.Object, 'COL_mwlr': pl.Object}

dummy_ids  = list(dummy_data)
df_temp    = pl.DataFrame(list(dummy_data.values()), schema=SCHEMA).with_columns([pl.Series('my_id', dummy_data.keys())])
df_temp    = df_temp.filter(pl.col('my_id').is_in(dummy_ids))
df_temp.fill_null(float('nan'))
```

### Log output

```shell
PanicException Traceback (most recent call last)
---> 9 df_temp.fill_null(float('nan'))

File Lib\site-packages\polars\dataframe\frame.py:7702, in DataFrame.fill_null(self, value, strategy, limit, matches_supertype)
   7699     return (
   7700         self.lazy()
   7701         .fill_null(value, strategy, limit, matches_supertype=matches_supertype)
-> 7702         .collect(_eager=True)
   7703     )

File Lib\site-packages\polars\lazyframe\frame.py:2027,
	in LazyFrame.collect(self, type_coercion, predicate_pushdown, projection_pushdown, simplify_expression, slice_pushdown,
		comm_subplan_elim, comm_subexpr_elim, cluster_with_columns, no_optimization, streaming, engine, background, _eager, **_kwargs)
   2025 # Only for testing purposes
   2026 callback = _kwargs.get("post_opt_callback", callback)
-> 2027 return wrap_df(ldf.collect(callback))

PanicException: implementation error
```

### Issue description

Code panics when it shouldn't

### Expected behavior

I'd expect no error (or at least no panic)

### Installed versions

<details>

```
--------Version info---------
Polars:               1.4.1
Index type:           UInt32
Platform:             Windows-10-10.0.19045-SP0
Python:               3.11.0 (main, Oct 24 2022, 18:26:48) [MSC v.1933 64 bit (AMD64)]

----Optional dependencies----
adbc_driver_manager:  <not installed>
cloudpickle:          <not installed>
connectorx:           <not installed>
deltalake:            <not installed>
fastexcel:            <not installed>
fsspec:               <not installed>
gevent:               <not installed>
great_tables:         <not installed>
hvplot:               <not installed>
matplotlib:           3.7.1
nest_asyncio:         1.5.6
numpy:                1.26.4
openpyxl:             <not installed>
pandas:               2.1.4
pyarrow:              16.1.0
pydantic:             <not installed>
pyiceberg:            <not installed>
sqlalchemy:           1.4.47
torch:                <not installed>
xlsx2csv:             <not installed>
xlsxwriter:           <not installed>
```

</details>

**Comment by EricTulowetzke** [comment]
Been playing around with this if you remove the `pl.Object` and have them be `pl.Float` it work see below:

```
import polars as pl
dummy_data = {'sZcR': {'COL_sMy3': None, 'COL_mTmp': None, 'COL_rP05': 0.14, 'COL_YJbC': None, 'COL_ptRs': 64, 'COL_agEk': 91, 'COL_Bbmw': 0.17, 'COL_Lxcj': 0.99}, 'PVFG': {'COL_sMy3': None, 'COL_mTmp': None, 'COL_rP05': 0.83, 'COL_YJbC': None, 'COL_ptRs': 97, 'COL_agEk': 12, 'COL_Bbmw': 0.88, 'COL_Lxcj': 0.88}, 'YrgF': {'COL_sMy3': None, 'COL_mTmp': None, 'COL_rP05': 0.76, 'COL_YJbC': None, 'COL_ptRs': 51, 'COL_agEk': 49, 'COL_Bbmw': 0.59, 'COL_Lxcj': 0.17}, 'U1FT': {'COL_sMy3': None, 'COL_mTmp': None, 'COL_rP05': 0.28, 'COL_YJbC': None, 'COL_ptRs': 29, 'COL_agEk': 58, 'COL_Bbmw': 0.62, 'COL_Lxcj': 0.76}, 'fVHR': {'COL_sMy3': None, 'COL_mTmp': None, 'COL_rP05': 0.32, 'COL_YJbC': 0.37, 'COL_nBny': 0.83, 'COL_ZL2X': 0.98}, 'K4OR': {'COL_sMy3': None, 'COL_mTmp': None, 'COL_rP05': 0.32, 'COL_YJbC': 0.72, 'COL_nBny': 0.4, 'COL_ZL2X': 0.26}, 'SWTC': {'COL_sMy3': None, 'COL_mTmp': None, 'COL_rP05': 0.92, 'COL_YJbC': 0.97, 'COL_nBny': 0.68, 'COL_ZL2X': 0.88}, 'zPvt': {'COL_sMy3': None, 'COL_mTmp': None, 'COL_rP05': 0.26, 'COL_YJbC': 0.56, 'COL_nBny': 0.44, 'COL_ZL2X': 0.57}, 'FEN5': {'COL_sMy3': None, 'COL_mTmp': None, 'COL_rP05': 3, 'COL_YJbC': 45, 'COL_nBny': 14, 'COL_ZL2X': 34}, 'LWiB': {'COL_sMy3': None, 'COL_mTmp': None, 'COL_rP05': 0.03, 'COL_YJbC': 0.8, 'COL_nBny': 0.49, 'COL_ZL2X': 0.66}, 'GsHo': {'COL_sMy3': None, 'COL_mTmp': None, 'COL_rP05': 0.87, 'COL_YJbC': 0.64, 'COL_nBny': 0.49, 'COL_ZL2X': 0.18}, '2NW3': {'COL_sMy3': None, 'COL_mTmp': None, 'COL_rP05': 0.43, 'COL_YJbC': 0.22, 'COL_nBny': 0.8, 'COL_ZL2X': 0.41}, 'h39x': {'COL_sMy3': None, 'COL_mTmp': None, 'COL_rP05': 0.91, 'COL_YJbC': 0.62, 'COL_nBny': 0.05, 'COL_ZL2X': 0.49}, 'P1uR': {'COL_sMy3': None, 'COL_mTmp': None, 'COL_rP05': 0.09, 'COL_YJbC': 0.43, 'COL_nBny': 0.8, 'COL_ZL2X': 0.91}, '8hhd': {'COL_sMy3': None, 'COL_mTmp': None, 'COL_rP05': 0.64, 'COL_YJbC': 0.96, 'COL_nBny': 0.24, 'COL_ZL2X': 0.41}, 'yZAi': {'COL_sMy3': None, 'COL_mTmp': None, 'COL_rP05': 0.5, 'COL_YJbC': 0.55, 'COL_nBny': 0.83, 'COL_ZL2X': 0.47}, 'cnwg': {'COL_sMy3': None, 'COL_mTmp': None, 'COL_rP05': 37, 'COL_YJbC': 13, 'COL_nBny': 3, 'COL_ZL2X': 57}, '4dlc': {'COL_sMy3': None, 'COL_mTmp': None, 'COL_rP05': 0.16, 'COL_YJbC': 0.03, 'COL_nBny': 0.45, 'COL_ZL2X': 0.78}, 'It36': {'COL_sMy3': None, 'COL_mTmp': None, 'COL_rP05': 0.92, 'COL_YJbC': 0.43, 'COL_nBny': 0.47, 'COL_ZL2X': 0.95}, 'pH2N': {'COL_sMy3': None, 'COL_mTmp': None, 'COL_rP05': 0.88, 'COL_YJbC': 0.82, 'COL_nBny': 0.44, 'COL_ZL2X': 0.46}}
SCHEMA     = {'COL_rP05': pl.Float64, 'COL_sMy3': pl.Float64, 'COL_mTmp': pl.Float64, 'COL_YJbC': pl.Float64, 'COL_Bbmw': pl.Float64, 'COL_Lxcj': pl.Float64, 'COL_agEk': pl.Float64, 'COL_ptRs': pl.Float64, 'COL_qFEW': pl.Float64, 'COL_nBny': pl.Float64, 'COL_ZL2X': pl.Float64, 'COL_JJJz': pl.Float64, 'COL_yEi2': pl.Float64, 'COL_RYJB': pl.Float64, 'COL_mwlr': pl.Float64}
dummy_ids  = list(dummy_data)
df_temp    = pl.DataFrame(list(dummy_data.values()), schema=SCHEMA).with_columns([pl.Series('my_id', dummy_data.keys())])
df_temp    = df_temp.filter(pl.col('my_id').is_in(dummy_ids))
df_temp = df_temp.fill_null(float('nan'))
print(df_temp)
```

Output:

```
shape: (20, 16)
┌─────────┬─────────┬─────────┬─────────┬───┬─────────┬─────────┬────────┬───────┐
│ COL_rP0 ┆ COL_sMy ┆ COL_mTm ┆ COL_YJb ┆ … ┆ COL_yEi ┆ COL_RYJ ┆ COL_mw ┆ my_id │
│ 5       ┆ 3       ┆ p       ┆ C       ┆   ┆ 2       ┆ B       ┆ lr     ┆ ---   │
│ ---     ┆ ---     ┆ ---     ┆ ---     ┆   ┆ ---     ┆ ---     ┆ ---    ┆ str   │
│ f64     ┆ f64     ┆ f64     ┆ f64     ┆   ┆ f64     ┆ f64     ┆ f64    ┆       │
╞═════════╪═════════╪═════════╪═════════╪═══╪═════════╪═════════╪════════╪═══════╡
│ 0.14    ┆ NaN     ┆ NaN     ┆ NaN     ┆ … ┆ NaN     ┆ NaN     ┆ NaN    ┆ sZcR  │
│ 0.83    ┆ NaN     ┆ NaN     ┆ NaN     ┆ … ┆ NaN     ┆ NaN     ┆ NaN    ┆ PVFG  │
│ 0.76    ┆ NaN     ┆ NaN     ┆ NaN     ┆ … ┆ NaN     ┆ NaN     ┆ NaN    ┆ YrgF  │
│ 0.28    ┆ NaN     ┆ NaN     ┆ NaN     ┆ … ┆ NaN     ┆ NaN     ┆ NaN    ┆ U1FT  │
│ 0.32    ┆ NaN     ┆ NaN     ┆ 0.37    ┆ … ┆ NaN     ┆ NaN     ┆ NaN    ┆ fVHR  │
│ …       ┆ …       ┆ …       ┆ …       ┆ … ┆ …       ┆ …       ┆ …      ┆ …     │
│ 0.5     ┆ NaN     ┆ NaN     ┆ 0.55    ┆ … ┆ NaN     ┆ NaN     ┆ NaN    ┆ yZAi  │
│ 37.0    ┆ NaN     ┆ NaN     ┆ 13.0    ┆ … ┆ NaN     ┆ NaN     ┆ NaN    ┆ cnwg  │
│ 0.16    ┆ NaN     ┆ NaN     ┆ 0.03    ┆ … ┆ NaN     ┆ NaN     ┆ NaN    ┆ 4dlc  │
│ 0.92    ┆ NaN     ┆ NaN     ┆ 0.43    ┆ … ┆ NaN     ┆ NaN     ┆ NaN    ┆ It36  │
│ 0.88    ┆ NaN     ┆ NaN     ┆ 0.82    ┆ … ┆ NaN     ┆ NaN     ┆ NaN    ┆ pH2N  │
└─────────┴─────────┴─────────┴─────────┴───┴─────────┴─────────┴────────┴───────┘
```
So something about `pl.Object` cause this issue will keep on looking into it

**Comment by barak1412** [comment]
Can't reproduce in windows.

**Comment by EricTulowetzke** [comment]
I just pulled the code from the main and ran it on Pop OS 22.04 and this is still an issue, I wonder why it works on windows.

below is the code with the output

```
import polars as pl

print(pl.__version__)

dummy_data = {
    "sZcR": {
        "COL_sMy3": None,
        "COL_mTmp": None,
        "COL_rP05": 0.14,
        "COL_YJbC": None,
        "COL_ptRs": 64,
        "COL_agEk": 91,
        "COL_Bbmw": 0.17,
        "COL_Lxcj": 0.99,
    },
    "PVFG": {
        "COL_sMy3": None,
        "COL_mTmp": None,
        "COL_rP05": 0.83,
        "COL_YJbC": None,
        "COL_ptRs": 97,
        "COL_agEk": 12,
        "COL_Bbmw": 0.88,
        "COL_Lxcj": 0.88,
    },
    "YrgF": {
        "COL_sMy3": None,
        "COL_mTmp": None,
        "COL_rP05": 0.76,
        "COL_YJbC": None,
        "COL_ptRs": 51,
        "COL_agEk": 49,
        "COL_Bbmw": 0.59,
        "COL_Lxcj": 0.17,
    },
    "U1FT": {
        "COL_sMy3": None,
        "COL_mTmp": None,
        "COL_rP05": 0.28,
        "COL_YJbC": None,
        "COL_ptRs": 29,
        "COL_agEk": 58,
        "COL_Bbmw": 0.62,
        "COL_Lxcj": 0.76,
    },
    "fVHR": {
        "COL_sMy3": None,
        "COL_mTmp": None,
        "COL_rP05": 0.32,
        "COL_YJbC": 0.37,
        "COL_nBny": 0.83,
        "COL_ZL2X": 0.98,
    },
    "K4OR": {
        "COL_sMy3": None,
        "COL_mTmp": None,
        "COL_rP05": 0.32,
        "COL_YJbC": 0.72,
        "COL_nBny": 0.4,
        "COL_ZL2X": 0.26,
    },
    "SWTC": {
        "COL_sMy3": None,
        "COL_mTmp": None,
        "COL_rP05": 0.92,
        "COL_YJbC": 0.97,
        "COL_nBny": 0.68,
        "COL_ZL2X": 0.88,
    },
    "zPvt": {
        "COL_sMy3": None,
        "COL_mTmp": None,
        "COL_rP05": 0.26,
        "COL_YJbC": 0.56,
        "COL_nBny": 0.44,
        "COL_ZL2X": 0.57,
    },
    "FEN5": {
        "COL_sMy3": None,
        "COL_mTmp": None,
        "COL_rP05": 3,
        "COL_YJbC": 45,
        "COL_nBny": 14,
        "COL_ZL2X": 34,
    },
    "LWiB": {
        "COL_sMy3": None,
        "COL_mTmp": None,
        "COL_rP05": 0.03,
        "COL_YJbC": 0.8,
        "COL_nBny": 0.49,
        "COL_ZL2X": 0.66,
    },
    "GsHo": {
        "COL_sMy3": None,
        "COL_mTmp": None,
        "COL_rP05": 0.87,
        "COL_YJbC": 0.64,
        "COL_nBny": 0.49,
        "COL_ZL2X": 0.18,
    },
    "2NW3": {
        "COL_sMy3": None,
        "COL_mTmp": None,
        "COL_rP05": 0.43,
        "COL_YJbC": 0.22,
        "COL_nBny": 0.8,
        "COL_ZL2X": 0.41,
    },
    "h39x": {
        "COL_sMy3": None,
        "COL_mTmp": None,
        "COL_rP05": 0.91,
        "COL_YJbC": 0.62,
        "COL_nBny": 0.05,
        "COL_ZL2X": 0.49,
    },
    "P1uR": {
        "COL_sMy3": None,
        "COL_mTmp": None,
        "COL_rP05": 0.09,
        "COL_YJbC": 0.43,
        "COL_nBny": 0.8,
        "COL_ZL2X": 0.91,
    },
    "8hhd": {
        "COL_sMy3": None,
        "COL_mTmp": None,
        "COL_rP05": 0.64,
        "COL_YJbC": 0.96,
        "COL_nBny": 0.24,
        "COL_ZL2X": 0.41,
    },
    "yZAi": {
        "COL_sMy3": None,
        "COL_mTmp": None,
        "COL_rP05": 0.5,
        "COL_YJbC": 0.55,
        "COL_nBny": 0.83,
        "COL_ZL2X": 0.47,
    },
    "cnwg": {
        "COL_sMy3": None,
        "COL_mTmp": None,
        "COL_rP05": 37,
        "COL_YJbC": 13,
        "COL_nBny": 3,
        "COL_ZL2X": 57,
    },
    "4dlc": {
        "COL_sMy3": None,
        "COL_mTmp": None,
        "COL_rP05": 0.16,
        "COL_YJbC": 0.03,
        "COL_nBny": 0.45,
        "COL_ZL2X": 0.78,
    },
    "It36": {
        "COL_sMy3": None,
        "COL_mTmp": None,
        "COL_rP05": 0.92,
        "COL_YJbC": 0.43,
        "COL_nBny": 0.47,
        "COL_ZL2X": 0.95,
    },
    "pH2N": {
        "COL_sMy3": None,
        "COL_mTmp": None,
        "COL_rP05": 0.88,
        "COL_YJbC": 0.82,
        "COL_nBny": 0.44,
        "COL_ZL2X": 0.46,
    },
}
SCHEMA = {
    "COL_rP05": pl.Float64,
    "COL_sMy3": pl.Float64,
    "COL_mTmp": pl.Float64,
    "COL_YJbC": pl.Float64,
    "COL_Bbmw": pl.Float64,
    "COL_Lxcj": pl.Float64,
    "COL_agEk": pl.Float64,
    "COL_ptRs": pl.Float64,
    "COL_qFEW": pl.Float64,
    "COL_nBny": pl.Float64,
    "COL_ZL2X": pl.Float64,
    "COL_JJJz": pl.Object, # obj
    "COL_yEi2": pl.Object,
    "COL_RYJB": pl.Object,
    "COL_mwlr": pl.Object,
}
dummy_ids = list(dummy_data)
df_temp = pl.DataFrame(list(dummy_data.values()), schema=SCHEMA).with_columns(
    [pl.Series("my_id", dummy_data.keys())]
)
df_temp = df_temp.filter(pl.col("my_id").is_in(dummy_ids))
df_temp = df_temp.fill_null(float("nan"))
print(df_temp)
```

output:

```
/home/eric/Documents/polars/.venv/bin/python /home/eric/Documents/polars/py-pola
rs/demo.py
1.5.0
thread '<unnamed>' panicked at /home/eric/Documents/polars/crates/polars-core/src/chunked_array/ops/chunkops.rs:146:17:
implementation error
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
Traceback (most recent call last):
  File "/home/eric/Documents/polars/py-polars/demo.py", line 197, in <module>
    df_temp = df_temp.fill_null(float("nan"))
  File "/home/eric/Documents/polars/py-polars/polars/dataframe/frame.py", line 7857, in fill_null
    self.lazy()
  File "/home/eric/Documents/polars/py-polars/polars/lazyframe/frame.py", line 2034, in collect
    return wrap_df(ldf.collect(callback))
pyo3_runtime.PanicException: implementation error

```

**Comment by cmdlineluser** [comment]
Cannot reproduce on macOS.

**Comment by EricTulowetzke** [comment]
@barak1412 and @cmdlineluser can I get both your `pl.show_version()` info? I just tried the example on Linux in the dev build and the release build with Python 3.12 and still getting the error.

**Comment by cmdlineluser** [comment]
@EricTulowetzke sure.

```python
>>> pl.show_versions()
--------Version info---------
Polars:              1.6.0
Index type:          UInt32
Platform:            macOS-13.6.1-arm64-arm-64bit
Python:              3.12.2 (main, Feb  6 2024, 20:19:44) [Clang 15.0.0 (clang-1500.1.0.2.5)]

----Optional dependencies----
adbc_driver_manager  <not installed>
altair               <not installed>
cloudpickle          <not installed>
connectorx           <not installed>
deltalake            <not installed>
fastexcel            <not installed>
fsspec               <not installed>
gevent               <not installed>
great_tables         <not installed>
matplotlib           <not installed>
nest_asyncio         <not installed>
numpy                1.26.4
openpyxl             <not installed>
pandas               2.2.1
pyarrow              15.0.2
pydantic             <not installed>
pyiceberg            <not installed>
sqlalchemy           <not installed>
torch                <not installed>
xlsx2csv             <not installed>
xlsxwriter           <not installed>
```
```python
>>> df_temp
shape: (20, 16)
┌──────────┬──────────┬──────────┬──────────┬───┬──────────┬──────────┬──────────┬───────┐
│ COL_rP05 ┆ COL_sMy3 ┆ COL_mTmp ┆ COL_YJbC ┆ … ┆ COL_yEi2 ┆ COL_RYJB ┆ COL_mwlr ┆ my_id │
│ ---      ┆ ---      ┆ ---      ┆ ---      ┆   ┆ ---      ┆ ---      ┆ ---      ┆ ---   │
│ f64      ┆ f64      ┆ f64      ┆ f64      ┆   ┆ object   ┆ object   ┆ object   ┆ str   │
╞══════════╪══════════╪══════════╪══════════╪═══╪══════════╪══════════╪══════════╪═══════╡
│ 0.14     ┆ NaN      ┆ NaN      ┆ NaN      ┆ … ┆ null     ┆ null     ┆ null     ┆ sZcR  │
│ 0.83     ┆ NaN      ┆ NaN      ┆ NaN      ┆ … ┆ null     ┆ null     ┆ null     ┆ PVFG  │
│ 0.76     ┆ NaN      ┆ NaN      ┆ NaN      ┆ … ┆ null     ┆ null     ┆ null     ┆ YrgF  │
│ 0.28     ┆ NaN      ┆ NaN      ┆ NaN      ┆ … ┆ null     ┆ null     ┆ null     ┆ U1FT  │
│ 0.32     ┆ NaN      ┆ NaN      ┆ 0.37     ┆ … ┆ null     ┆ null     ┆ null     ┆ fVHR  │
│ …        ┆ …        ┆ …        ┆ …        ┆ … ┆ …        ┆ …        ┆ …        ┆ …     │
│ 0.5      ┆ NaN      ┆ NaN      ┆ 0.55     ┆ … ┆ null     ┆ null     ┆ null     ┆ yZAi  │
│ 37.0     ┆ NaN      ┆ NaN      ┆ 13.0     ┆ … ┆ null     ┆ null     ┆ null     ┆ cnwg  │
│ 0.16     ┆ NaN      ┆ NaN      ┆ 0.03     ┆ … ┆ null     ┆ null     ┆ null     ┆ 4dlc  │
│ 0.92     ┆ NaN      ┆ NaN      ┆ 0.43     ┆ … ┆ null     ┆ null     ┆ null     ┆ It36  │
│ 0.88     ┆ NaN      ┆ NaN      ┆ 0.82     ┆ … ┆ null     ┆ null     ┆ null     ┆ pH2N  │
└──────────┴──────────┴──────────┴──────────┴───┴──────────┴──────────┴──────────┴───────┘
```

**Comment by barak1412** [comment]
```
--------Version info---------
Polars:              1.6.0
Index type:          UInt32
Platform:            Windows-11-10.0.22621-SP0
Python:              3.12.5 (tags/v3.12.5:ff3bc82, Aug  6 2024, 20:45:27) [MSC v.1940 64 bit (AMD64)]

----Optional dependencies----
adbc_driver_manager  <not installed>
altair               <not installed>
cloudpickle          <not installed>
connectorx           <not installed>
deltalake            <not installed>
fastexcel            <not installed>
fsspec               <not installed>
gevent               <not installed>
great_tables         <not installed>
matplotlib           <not installed>
nest_asyncio         <not installed>
numpy                <not installed>
openpyxl             <not installed>
pandas               <not installed>
pyarrow              <not installed>
pydantic             <not installed>
pyiceberg            <not installed>
sqlalchemy           <not installed>
torch                <not installed>
xlsx2csv             <not installed>
xlsxwriter           <not installed>
```

**Comment by EricTulowetzke** [comment]
Ok, that info is helpful I might need to re-fork my repo to double check my code is up to date. Right now I'm fairly busy with school and work. So if others want to look into this that is fine too. I will work on this when I have time too.

**Comment by etiennebacher** [comment]
Can't reproduce this on Ubuntu 24.04 and polars 1.19.0

**Comment by kdn36** [comment]
Unable to reproduce on latest main (b71a814a79ea4aec11d990a04f3247bdb5ff6c27), Ubuntu 24.04.2 LTS (WSL2).

Outcome:
```
shape: (20, 16)
┌──────────┬──────────┬──────────┬──────────┬───┬──────────┬──────────┬──────────┬───────┐
│ COL_rP05 ┆ COL_sMy3 ┆ COL_mTmp ┆ COL_YJbC ┆ … ┆ COL_yEi2 ┆ COL_RYJB ┆ COL_mwlr ┆ my_id │
│ ---      ┆ ---      ┆ ---      ┆ ---      ┆   ┆ ---      ┆ ---      ┆ ---      ┆ ---   │
│ f64      ┆ f64      ┆ f64      ┆ f64      ┆   ┆ object   ┆ object   ┆ object   ┆ str   │
╞══════════╪══════════╪══════════╪══════════╪═══╪══════════╪══════════╪══════════╪═══════╡
│ 0.14     ┆ NaN      ┆ NaN      ┆ NaN      ┆ … ┆ null     ┆ null     ┆ null     ┆ sZcR  │
│ 0.83     ┆ NaN      ┆ NaN      ┆ NaN      ┆ … ┆ null     ┆ null     ┆ null     ┆ PVFG  │
│ 0.76     ┆ NaN      ┆ NaN      ┆ NaN      ┆ … ┆ null     ┆ null     ┆ null     ┆ YrgF  │
│ 0.28     ┆ NaN      ┆ NaN      ┆ NaN      ┆ … ┆ null     ┆ null     ┆ null     ┆ U1FT  │
│ 0.32     ┆ NaN      ┆ NaN      ┆ 0.37     ┆ … ┆ null     ┆ null     ┆ null     ┆ fVHR  │
│ …        ┆ …        ┆ …        ┆ …        ┆ … ┆ …        ┆ …        ┆ …        ┆ …     │
│ 0.5      ┆ NaN      ┆ NaN      ┆ 0.55     ┆ … ┆ null     ┆ null     ┆ null     ┆ yZAi  │
│ 37.0     ┆ NaN      ┆ NaN      ┆ 13.0     ┆ … ┆ null     ┆ null     ┆ null     ┆ cnwg  │
│ 0.16     ┆ NaN      ┆ NaN      ┆ 0.03     ┆ … ┆ null     ┆ null     ┆ null     ┆ 4dlc  │
│ 0.92     ┆ NaN      ┆ NaN      ┆ 0.43     ┆ … ┆ null     ┆ null     ┆ null     ┆ It36  │
│ 0.88     ┆ NaN      ┆ NaN      ┆ 0.82     ┆ … ┆ null     ┆ null     ┆ null     ┆ pH2N  │
└──────────┴──────────┴──────────┴──────────┴───┴──────────┴──────────┴──────────┴───────┘
```

If someone can reproduce, please flag and specify the versions and environment details.

If not, we will close this issue, but feel free to reopen if it reoccurs.
