### ISSUE TITLE
Filter string column with python StrEnum could raise conversion error

### ISSUE THREAD

**Issue by rcliu623** [pola-rs/polars#18087]
### Checks

- [X] I have checked that this issue has not already been reported.
- [X] I have confirmed this bug exists on the [latest version](https://pypi.org/project/polars/) of Polars.

### Reproducible example

```python
import polars as pl
from enum import StrEnum, auto

class Fruit(StrEnum):
    apple = auto()
    orange = auto()

pl.DataFrame({"bar": ["apple", "pear"]}, schema={"bar": pl.Utf8}).filter(pl.col("bar") == Fruit.apple)
```

### Log output

```shell
dataframe filtered
Traceback (most recent call last):
  File ".../polars/test_enum.py", line 10, in <module>
    pl.DataFrame({"bar": ["apple", "pear"]}, schema={"bar": pl.Utf8}).filter(pl.col("bar") == Fruit.apple)
  File ".../lib/python3.11/site-packages/polars/dataframe/frame.py", line 4554, in filter
    return self.lazy().filter(*predicates, **constraints).collect(_eager=True)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File ".../lib/python3.11/site-packages/polars/lazyframe/frame.py", line 2027, in collect
    return wrap_df(ldf.collect(callback))
                   ^^^^^^^^^^^^^^^^^^^^^
polars.exceptions.InvalidOperationError: conversion from `str` to `enum` failed in column 'bar' for 1 out of 2 values: ["pear"]

Ensure that all values in the input column are present in the categories of the enum datatype.
```

### Issue description

I think internally polars tried to cast `bar` column into type `Enum(Fruit)` before filtering and failed. 

### Expected behavior

I'd expect simple equality matching between a string column and the string enum value without the conversion. This feels more intuitive and after all `Fruit.apple == "apple"`. 

### Installed versions

<details>

```
--------Version info---------
Polars:               1.4.1
Index type:           UInt32
Platform:             Linux-4.18.0-477.36.1.el8_8-x86_64-with-glibc2.28
Python:               3.11.9 (main, Apr 19 2024, 16:48:06) [GCC 11.2.0]

----Optional dependencies----
adbc_driver_manager:  <not installed>
cloudpickle:          3.0.0
connectorx:           <not installed>
deltalake:            <not installed>
fastexcel:            <not installed>
fsspec:               2024.6.1
gevent:               <not installed>
great_tables:         <not installed>
hvplot:               0.10.0
matplotlib:           <not installed>
nest_asyncio:         1.6.0
numpy:                1.25.0
openpyxl:             <not installed>
pandas:               2.2.2
pyarrow:              17.0.0
pydantic:             2.8.2
pyiceberg:            <not installed>
sqlalchemy:           2.0.31
torch:                <not installed>
xlsx2csv:             <not installed>
xlsxwriter:           <not installed>
```

</details>

**Comment by lukemanley** [comment]
This now works on main.
