### ISSUE TITLE
LazyFrame `collect` method, does not work when using GPU

### ISSUE THREAD

**Issue by amirhosss** [pola-rs/polars#18114]
### Checks

- [X] I have checked that this issue has not already been reported.
- [X] I have confirmed this bug exists on the [latest version](https://pypi.org/project/polars/) of Polars.

### Reproducible example

```python
q1 = (
    some_df.group_by(
        "date"
    )
    .agg(
        pl.col("id").count()
    )
)
df = q1.collect(engine="gpu")
```

### Log output

```shell
Traceback (most recent call last):
  File "/tmp/Untitled-1.py", line 165, in <module>
    df = q1.collect(engine="gpu")
  File "/home/some/.local/lib/python3.10/site-packages/polars/lazyframe/frame.py", line 2027, in collect
    return wrap_df(ldf.collect(callback))
polars.exceptions.ComputeError: 'cuda' conversion failed: TypeError: execute_with_cudf() got an unexpected keyword argument 'config'
```

### Issue description

When using the GPU engine with the `collect` method, the above error occurs. I removed `config` from the source code, and it seems the problem is solved.

### Expected behavior

Works as expected

### Installed versions

<details>

```
--------Version info---------
Polars:               1.4.1
Index type:           UInt32
Platform:             Linux-6.2.0-26-generic-x86_64-with-glibc2.35
Python:               3.10.12 (main, Jun 11 2023, 05:26:28) [GCC 11.4.0]

----Optional dependencies----
adbc_driver_manager:  <not installed>
cloudpickle:          3.0.0
connectorx:           <not installed>
deltalake:            <not installed>
fastexcel:            <not installed>
fsspec:               2024.6.1
gevent:               <not installed>
great_tables:         <not installed>
hvplot:               <not installed>
matplotlib:           3.8.2
nest_asyncio:         1.5.8
numpy:                1.26.2
openpyxl:             3.1.2
pandas:               2.2.2
pyarrow:              16.1.0
pydantic:             2.8.2
pyiceberg:            <not installed>
sqlalchemy:           <not installed>
torch:                <not installed>
xlsx2csv:             <not installed>
xlsxwriter:           <not installed>
```

</details>

**Comment by CHDev93** [comment]
I don't think `polars[gpu]` has been released publicly yet so I wouldn't expect this to work. When you change the source code, are you sure it's using the GPU?

**Comment by coastalwhite** [comment]
The gpu option is not ready yet and is purely there for future use.

Closing this.

**Comment by amirhosss** [comment]
> are you sure it's using the GPU?

I don't think it's using the GPU, but the error is gone
