### ISSUE TITLE
LazyFrame join on list[i64] succeeds with empty dataframe

### ISSUE THREAD

**Issue by CHDev93** [pola-rs/polars#18120]
### Checks

- [X] I have checked that this issue has not already been reported.
- [X] I have confirmed this bug exists on the [latest version](https://pypi.org/project/polars/) of Polars.

### Reproducible example

```python
sensor_df = pl.DataFrame({"sensor": np.arange(1000)})
date_df = pl.DataFrame({"date": np.arange(250)})

# sensor, date
idx_df = sensor_df.join(date_df, how="cross")

id_df = pl.DataFrame({"_sensor": np.arange(1000)})
day_df = pl.DataFrame({"_date": np.arange(250)})
times_df = pl.DataFrame({"time": np.arange(150)})

# _sensor, _date, time, _marker, 0, 1, 2, 3
data_df = (
    id_df.join(day_df, how="cross")
    .join(times_df, how="cross")
    .with_columns(
        pl.lit(0).alias("_marker"),
        pl.lit(0.0).cast(pl.Float32).alias("0"),
        pl.lit(1.0).cast(pl.Float32).alias("1"),
        pl.lit(2.0).cast(pl.Float32).alias("2"),
        pl.lit(3.0).cast(pl.Float32).alias("3"),
    )
)


time_coords_df = data_df.select(pl.col("time").unique().sort())
time_idx_df = idx_df.join(time_coords_df, how="cross").select(pl.concat_list("sensor", "date", "time").alias("index"))


data_df = data_df.select(pl.concat_list("_sensor", "_date", "time").alias("index").set_sorted())
data_lf = data_df.lazy()

tmp_lf = time_idx_lf.join(
    data_lf,
    how="left",
    on="index",
    coalesce=True,
)

# _sensor, _date, time, _marker, 0, 1, 2, 3
result_df = tmp_df.drop("index").fill_null(0).collect() # EMPTY DATAFRAME

# ComputeError: not yet implemented: Hash Left Join between list[i64] and list[i64]
time_idx_df.join(
    data_df,
    how="left",
    on="index",
    coalesce=True,
)
```

### Log output

```shell
join parallel: true
CROSS join dataframes finished
join parallel: true
CROSS join dataframes finished
join parallel: true
CROSS join dataframes finished
join parallel: true
CROSS join dataframes finished
join parallel: true
LEFT join dataframes finished
Traceback (most recent call last):
  File "/persist/code/gr-goulash/polars_schema_error.py", line 45, in <module>
    time_idx_df.join(
  File "/persist/.virtualenvs/redcarpet/lib/python3.10/site-packages/polars/dataframe/frame.py", line 6870, in join
    self.lazy()
  File "/persist/.virtualenvs/redcarpet/lib/python3.10/site-packages/polars/lazyframe/frame.py", line 1942, in collect
    return wrap_df(ldf.collect(callback))
polars.exceptions
```
```


### Issue description

Was trying to solve my join on a triple index key using too much memory and so tried creating a single list dtype column and joining on that.

Running in eager mode, the query fails because hash join is not implemented on the list dtype. Doing it with a lazy frame succeeds but silently returns an empty dataframe.


### Expected behavior

Doing the operation with a lazy frame should also hard fail indicating that the join has not been implemented

### Installed versions

<details>

```
--------Version info---------
Polars:               1.4.1
Index type:           UInt32
Platform:             Linux-5.15.0-91-generic-x86_64-with-glibc2.35
Python:               3.10.12 (main, Mar 22 2024, 16:50:05) [GCC 11.4.0]

----Optional dependencies----
adbc_driver_manager:  <not installed>
cloudpickle:          3.0.0
connectorx:           <not installed>
deltalake:            <not installed>
fastexcel:            <not installed>
fsspec:               2024.6.1
gevent:               <not installed>
great_tables:         <not installed>
hvplot:               <not installed>
matplotlib:           3.9.1
nest_asyncio:         1.6.0
numpy:                1.23.5
openpyxl:             <not installed>
pandas:               1.5.3
pyarrow:              11.0.0
pydantic:             2.8.2
pyiceberg:            <not installed>
sqlalchemy:           <not installed>
torch:                2.4.0+cu121
xlsx2csv:             <not installed>
xlsxwriter:           <not installed>```

</details>

**Comment by ritchie46** [comment]
Is there a minimal repro on this one? Seems to happen an lot of unneeded work/ and operations.

**Comment by CHDev93** [comment]
@ritchie46 I've simplified the example in the main issue. Basically I think both lazy and eager path should fail with not implemented yet the lazy one succeeds with a 0 row dataframe
