### ISSUE TITLE
Calling `to_deserializer` with `filter = None` results in a panic

### ISSUE THREAD

**Issue by nameexhaustion** [pola-rs/polars#18137]
### Checks

- [X] I have checked that this issue has not already been reported.
- [X] I have confirmed this bug exists on the [latest version](https://pypi.org/project/polars/) of Polars.

### Reproducible example

Change this line to pass `None` instead of `filter` to `mmap::to_deserializer`:

https://github.com/pola-rs/polars/blob/4233d6128a7ff2415c56318e315fca6fdf879504/crates/polars-io/src/parquet/read/read_impl.rs#L72

And then run:

```python
import polars as pl

path = ".env/data.parquet"
df = pl.DataFrame(
    [
        pl.Series("c1", [{"a": "foo", "b": "bar"}], dtype=pl.Struct),
    ]
)

df.write_parquet(path)

lf = pl.scan_parquet(path)

print(lf.collect())

```
(taken from https://github.com/pola-rs/polars/blob/4233d6128a7ff2415c56318e315fca6fdf879504/py-polars/tests/unit/io/test_lazy_parquet.py#L382-L392)

### Log output

```shell
thread 'polars-0' panicked at crates/polars-parquet/src/arrow/read/deserialize/nested_utils.rs:555:9:
assertion `left == right` failed
  left: 1
 right: 1024
stack backtrace:
   0: rust_begin_unwind
             at /rustc/7120fdac7a6e55a5e4b606256042890b36067052/library/std/src/panicking.rs:665:5
   1: core::panicking::panic_fmt
             at /rustc/7120fdac7a6e55a5e4b606256042890b36067052/library/core/src/panicking.rs:74:14
   2: core::panicking::assert_failed_inner
   3: core::panicking::assert_failed
             at /rustc/7120fdac7a6e55a5e4b606256042890b36067052/library/core/src/panicking.rs:365:5
   4: polars_parquet::arrow::read::deserialize::nested_utils::extend_offsets_limited
             at ./crates/polars-parquet/src/arrow/read/deserialize/nested_utils.rs:555:9
   5: polars_parquet::arrow::read::deserialize::nested_utils::extend_offsets2
             at ./crates/polars-parquet/src/arrow/read/deserialize/nested_utils.rs:393:13
   6: polars_parquet::arrow::read::deserialize::nested_utils::PageNestedDecoder<D>::collect_n
             at ./crates/polars-parquet/src/arrow/read/deserialize/nested_utils.rs:718:21
   7: polars_parquet::arrow::read::deserialize::nested::columns_to_iter_recursive
             at ./crates/polars-parquet/src/arrow/read/deserialize/nested.rs:186:13
   8: polars_parquet::arrow::read::deserialize::nested::columns_to_iter_recursive::{{closure}}
             at ./crates/polars-parquet/src/arrow/read/deserialize/nested.rs:403:25
   9: polars_parquet::arrow::read::deserialize::nested::columns_to_iter_recursive
             at ./crates/polars-parquet/src/arrow/read/deserialize/nested.rs:413:21
  10: polars_parquet::arrow::read::deserialize::columns_to_iter_recursive
             at ./crates/polars-parquet/src/arrow/read/deserialize/mod.rs:149:5
  11: polars_parquet::arrow::read::deserialize::column_iter_to_arrays
             at ./crates/polars-parquet/src/arrow/read/deserialize/mod.rs:201:22
  12: polars_io::parquet::read::mmap::to_deserializer
             at ./crates/polars-io/src/parquet/read/mmap.rs:90:5
  13: polars_io::parquet::read::read_impl::column_idx_to_series
             at ./crates/polars-io/src/parquet/read/read_impl.rs:72:16
  14: polars_io::parquet::read::read_impl::rg_to_dfs_optionally_par_over_columns::{{closure}}
             at ./crates/polars-io/src/parquet/read/read_impl.rs:507:21
  15: core::iter::adapters::map::map_try_fold::{{closure}}
             at /rustc/7120fdac7a6e55a5e4b606256042890b36067052/library/core/src/iter/adapters/map.rs:96:28
  16: core::iter::traits::iterator::Iterator::try_fold
             at /rustc/7120fdac7a6e55a5e4b606256042890b36067052/library/core/src/iter/traits/iterator.rs:2410:21
  17: <core::iter::adapters::map::Map<I,F> as core::iter::traits::iterator::Iterator>::try_fold
             at /rustc/7120fdac7a6e55a5e4b606256042890b36067052/library/core/src/iter/adapters/map.rs:122:9
  18: <core::iter::adapters::GenericShunt<I,R> as core::iter::traits::iterator::Iterator>::try_fold
             at /rustc/7120fdac7a6e55a5e4b606256042890b36067052/library/core/src/iter/adapters/mod.rs:204:9
  19: core::iter::traits::iterator::Iterator::try_for_each
             at /rustc/7120fdac7a6e55a5e4b606256042890b36067052/library/core/src/iter/traits/iterator.rs:2472:9
  20: <core::iter::adapters::GenericShunt<I,R> as core::iter::traits::iterator::Iterator>::next
             at /rustc/7120fdac7a6e55a5e4b606256042890b36067052/library/core/src/iter/adapters/mod.rs:187:14
  21: <alloc::vec::Vec<T> as alloc::vec::spec_from_iter_nested::SpecFromIterNested<T,I>>::from_iter
             at /rustc/7120fdac7a6e55a5e4b606256042890b36067052/library/alloc/src/vec/spec_from_iter_nested.rs:26:32
  22: <alloc::vec::Vec<T> as alloc::vec::spec_from_iter::SpecFromIter<T,I>>::from_iter
             at /rustc/7120fdac7a6e55a5e4b606256042890b36067052/library/alloc/src/vec/spec_from_iter.rs:33:9
  23: <alloc::vec::Vec<T> as core::iter::traits::collect::FromIterator<T>>::from_iter
             at /rustc/7120fdac7a6e55a5e4b606256042890b36067052/library/alloc/src/vec/mod.rs:2977:9
  24: core::iter::traits::iterator::Iterator::collect
             at /rustc/7120fdac7a6e55a5e4b606256042890b36067052/library/core/src/iter/traits/iterator.rs:2005:9
  25: <core::result::Result<V,E> as core::iter::traits::collect::FromIterator<core::result::Result<A,E>>>::from_iter::{{closure}}
             at /rustc/7120fdac7a6e55a5e4b606256042890b36067052/library/core/src/result.rs:1960:51
  26: core::iter::adapters::try_process
             at /rustc/7120fdac7a6e55a5e4b606256042890b36067052/library/core/src/iter/adapters/mod.rs:173:17
  27: <core::result::Result<V,E> as core::iter::traits::collect::FromIterator<core::result::Result<A,E>>>::from_iter
             at /rustc/7120fdac7a6e55a5e4b606256042890b36067052/library/core/src/result.rs:1960:9
  28: core::iter::traits::iterator::Iterator::collect
             at /rustc/7120fdac7a6e55a5e4b606256042890b36067052/library/core/src/iter/traits/iterator.rs:2005:9
  29: polars_io::parquet::read::read_impl::rg_to_dfs_optionally_par_over_columns
             at ./crates/polars-io/src/parquet/read/read_impl.rs:504:13
  30: polars_io::parquet::read::read_impl::rg_to_dfs
             at ./crates/polars-io/src/parquet/read/read_impl.rs:192:33
  31: polars_io::parquet::read::read_impl::read_parquet
             at ./crates/polars-io/src/parquet/read/read_impl.rs:696:15
  32: <polars_io::parquet::read::reader::ParquetReader<R> as polars_io::shared::SerReader<R>>::finish
             at ./crates/polars-io/src/parquet/read/reader.rs:216:22
  33: polars_mem_engine::executors::scan::parquet::ParquetExec::read_par::{{closure}}::{{closure}}
             at ./crates/polars-mem-engine/src/executors/scan/parquet.rs:198:42
  34: core::ops::function::impls::<impl core::ops::function::FnMut<A> for &F>::call_mut
             at /rustc/7120fdac7a6e55a5e4b606256042890b36067052/library/core/src/ops/function.rs:272:13
  35: core::ops::function::impls::<impl core::ops::function::FnOnce<A> for &mut F>::call_once
             at /rustc/7120fdac7a6e55a5e4b606256042890b36067052/library/core/src/ops/function.rs:305:13
  36: core::option::Option<T>::map
             at /rustc/7120fdac7a6e55a5e4b606256042890b36067052/library/core/src/option.rs:1110:29
  37: <core::iter::adapters::map::Map<I,F> as core::iter::traits::iterator::Iterator>::next
             at /rustc/7120fdac7a6e55a5e4b606256042890b36067052/library/core/src/iter/adapters/map.rs:108:26
  38: <core::iter::adapters::map::Map<I,F> as core::iter::traits::iterator::Iterator>::next
             at /rustc/7120fdac7a6e55a5e4b606256042890b36067052/library/core/src/iter/adapters/map.rs:108:9
  39: <core::iter::adapters::take_while::TakeWhile<I,P> as core::iter::traits::iterator::Iterator>::next
             at /rustc/7120fdac7a6e55a5e4b606256042890b36067052/library/core/src/iter/adapters/take_while.rs:47:21
  40: <core::iter::adapters::map::Map<I,F> as core::iter::traits::iterator::Iterator>::next
             at /rustc/7120fdac7a6e55a5e4b606256042890b36067052/library/core/src/iter/adapters/map.rs:108:9
  41: alloc::vec::Vec<T,A>::extend_desugared
             at /rustc/7120fdac7a6e55a5e4b606256042890b36067052/library/alloc/src/vec/mod.rs:3081:35
  42: <alloc::vec::Vec<T,A> as alloc::vec::spec_extend::SpecExtend<T,I>>::spec_extend
             at /rustc/7120fdac7a6e55a5e4b606256042890b36067052/library/alloc/src/vec/spec_extend.rs:17:9
  43: <alloc::vec::Vec<T,A> as core::iter::traits::collect::Extend<T>>::extend
             at /rustc/7120fdac7a6e55a5e4b606256042890b36067052/library/alloc/src/vec/mod.rs:3045:9
  44: <rayon::iter::extend::ListVecFolder<T> as rayon::iter::plumbing::Folder<T>>::consume_iter
             at /Users/nxs/.cargo/registry/src/index.crates.io-6f17d22bba15001f/rayon-1.10.0/src/iter/extend.rs:130:9
  45: <rayon::iter::while_some::WhileSomeFolder<C> as rayon::iter::plumbing::Folder<core::option::Option<T>>>::consume_iter
             at /Users/nxs/.cargo/registry/src/index.crates.io-6f17d22bba15001f/rayon-1.10.0/src/iter/while_some.rs:139:21
  46: <rayon::iter::map::MapFolder<C,F> as rayon::iter::plumbing::Folder<T>>::consume_iter
             at /Users/nxs/.cargo/registry/src/index.crates.io-6f17d22bba15001f/rayon-1.10.0/src/iter/map.rs:248:21
  47: <rayon::iter::map::MapFolder<C,F> as rayon::iter::plumbing::Folder<T>>::consume_iter
             at /Users/nxs/.cargo/registry/src/index.crates.io-6f17d22bba15001f/rayon-1.10.0/src/iter/map.rs:248:21
  48: rayon::iter::plumbing::Producer::fold_with
             at /Users/nxs/.cargo/registry/src/index.crates.io-6f17d22bba15001f/rayon-1.10.0/src/iter/plumbing/mod.rs:109:9
  49: rayon::iter::plumbing::bridge_producer_consumer::helper
             at /Users/nxs/.cargo/registry/src/index.crates.io-6f17d22bba15001f/rayon-1.10.0/src/iter/plumbing/mod.rs:437:13
  50: rayon::iter::plumbing::bridge_producer_consumer
             at /Users/nxs/.cargo/registry/src/index.crates.io-6f17d22bba15001f/rayon-1.10.0/src/iter/plumbing/mod.rs:396:12
  51: <rayon::iter::plumbing::bridge::Callback<C> as rayon::iter::plumbing::ProducerCallback<I>>::callback
             at /Users/nxs/.cargo/registry/src/index.crates.io-6f17d22bba15001f/rayon-1.10.0/src/iter/plumbing/mod.rs:372:13
  52: <<rayon::iter::enumerate::Enumerate<I> as rayon::iter::IndexedParallelIterator>::with_producer::Callback<CB> as rayon::iter::plumbing::ProducerCallback<I>>::callback
             at /Users/nxs/.cargo/registry/src/index.crates.io-6f17d22bba15001f/rayon-1.10.0/src/iter/enumerate.rs:78:17
  53: <<rayon::iter::zip::Zip<A,B> as rayon::iter::IndexedParallelIterator>::with_producer::CallbackB<CB,A> as rayon::iter::plumbing::ProducerCallback<ITEM>>::callback
             at /Users/nxs/.cargo/registry/src/index.crates.io-6f17d22bba15001f/rayon-1.10.0/src/iter/zip.rs:112:17
  54: <rayon::vec::Drain<T> as rayon::iter::IndexedParallelIterator>::with_producer
             at /Users/nxs/.cargo/registry/src/index.crates.io-6f17d22bba15001f/rayon-1.10.0/src/vec.rs:147:13
  55: <rayon::vec::IntoIter<T> as rayon::iter::IndexedParallelIterator>::with_producer
             at /Users/nxs/.cargo/registry/src/index.crates.io-6f17d22bba15001f/rayon-1.10.0/src/vec.rs:83:9
  56: <<rayon::iter::zip::Zip<A,B> as rayon::iter::IndexedParallelIterator>::with_producer::CallbackA<CB,B> as rayon::iter::plumbing::ProducerCallback<ITEM>>::callback
             at /Users/nxs/.cargo/registry/src/index.crates.io-6f17d22bba15001f/rayon-1.10.0/src/iter/zip.rs:89:17
  57: <rayon::vec::Drain<T> as rayon::iter::IndexedParallelIterator>::with_producer
             at /Users/nxs/.cargo/registry/src/index.crates.io-6f17d22bba15001f/rayon-1.10.0/src/vec.rs:147:13
  58: <rayon::vec::IntoIter<T> as rayon::iter::IndexedParallelIterator>::with_producer
             at /Users/nxs/.cargo/registry/src/index.crates.io-6f17d22bba15001f/rayon-1.10.0/src/vec.rs:83:9
  59: <rayon::iter::zip::Zip<A,B> as rayon::iter::IndexedParallelIterator>::with_producer
             at /Users/nxs/.cargo/registry/src/index.crates.io-6f17d22bba15001f/rayon-1.10.0/src/iter/zip.rs:68:16
  60: <rayon::iter::enumerate::Enumerate<I> as rayon::iter::IndexedParallelIterator>::with_producer
             at /Users/nxs/.cargo/registry/src/index.crates.io-6f17d22bba15001f/rayon-1.10.0/src/iter/enumerate.rs:62:16
  61: rayon::iter::plumbing::bridge
             at /Users/nxs/.cargo/registry/src/index.crates.io-6f17d22bba15001f/rayon-1.10.0/src/iter/plumbing/mod.rs:356:12
  62: <rayon::iter::enumerate::Enumerate<I> as rayon::iter::ParallelIterator>::drive_unindexed
             at /Users/nxs/.cargo/registry/src/index.crates.io-6f17d22bba15001f/rayon-1.10.0/src/iter/enumerate.rs:38:9
  63: <rayon::iter::map::Map<I,F> as rayon::iter::ParallelIterator>::drive_unindexed
             at /Users/nxs/.cargo/registry/src/index.crates.io-6f17d22bba15001f/rayon-1.10.0/src/iter/map.rs:49:9
  64: <rayon::iter::map::Map<I,F> as rayon::iter::ParallelIterator>::drive_unindexed
             at /Users/nxs/.cargo/registry/src/index.crates.io-6f17d22bba15001f/rayon-1.10.0/src/iter/map.rs:49:9
  65: <rayon::iter::while_some::WhileSome<I> as rayon::iter::ParallelIterator>::drive_unindexed
             at /Users/nxs/.cargo/registry/src/index.crates.io-6f17d22bba15001f/rayon-1.10.0/src/iter/while_some.rs:44:9
  66: rayon::iter::extend::<impl rayon::iter::ParallelExtend<T> for alloc::vec::Vec<T>>::par_extend
             at /Users/nxs/.cargo/registry/src/index.crates.io-6f17d22bba15001f/rayon-1.10.0/src/iter/extend.rs:588:28
  67: rayon::iter::from_par_iter::collect_extended
             at /Users/nxs/.cargo/registry/src/index.crates.io-6f17d22bba15001f/rayon-1.10.0/src/iter/from_par_iter.rs:20:5
  68: rayon::iter::from_par_iter::<impl rayon::iter::FromParallelIterator<T> for alloc::vec::Vec<T>>::from_par_iter
             at /Users/nxs/.cargo/registry/src/index.crates.io-6f17d22bba15001f/rayon-1.10.0/src/iter/from_par_iter.rs:33:9
  69: rayon::iter::ParallelIterator::collect
             at /Users/nxs/.cargo/registry/src/index.crates.io-6f17d22bba15001f/rayon-1.10.0/src/iter/mod.rs:2069:9
  70: rayon::result::<impl rayon::iter::FromParallelIterator<core::result::Result<T,E>> for core::result::Result<C,E>>::from_par_iter
             at /Users/nxs/.cargo/registry/src/index.crates.io-6f17d22bba15001f/rayon-1.10.0/src/result.rs:121:26
  71: rayon::iter::ParallelIterator::collect
             at /Users/nxs/.cargo/registry/src/index.crates.io-6f17d22bba15001f/rayon-1.10.0/src/iter/mod.rs:2069:9
  72: polars_mem_engine::executors::scan::parquet::ParquetExec::read_par::{{closure}}
             at ./crates/polars-mem-engine/src/executors/scan/parquet.rs:187:17
  73: rayon_core::thread_pool::ThreadPool::install::{{closure}}
             at /Users/nxs/.cargo/registry/src/index.crates.io-6f17d22bba15001f/rayon-core-1.12.1/src/thread_pool/mod.rs:147:40
  74: rayon_core::registry::Registry::in_worker_cold::{{closure}}::{{closure}}
             at /Users/nxs/.cargo/registry/src/index.crates.io-6f17d22bba15001f/rayon-core-1.12.1/src/registry.rs:522:21
  75: rayon_core::job::JobResult<T>::call::{{closure}}
             at /Users/nxs/.cargo/registry/src/index.crates.io-6f17d22bba15001f/rayon-core-1.12.1/src/job.rs:218:41
  76: <core::panic::unwind_safe::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once
             at /rustc/7120fdac7a6e55a5e4b606256042890b36067052/library/core/src/panic/unwind_safe.rs:272:9
  77: std::panicking::try::do_call
             at /rustc/7120fdac7a6e55a5e4b606256042890b36067052/library/std/src/panicking.rs:557:40
  78: ___rust_try
  79: std::panicking::try
             at /rustc/7120fdac7a6e55a5e4b606256042890b36067052/library/std/src/panicking.rs:521:19
  80: std::panic::catch_unwind
             at /rustc/7120fdac7a6e55a5e4b606256042890b36067052/library/std/src/panic.rs:350:14
  81: rayon_core::unwind::halt_unwinding
             at /Users/nxs/.cargo/registry/src/index.crates.io-6f17d22bba15001f/rayon-core-1.12.1/src/unwind.rs:17:5
  82: rayon_core::job::JobResult<T>::call
             at /Users/nxs/.cargo/registry/src/index.crates.io-6f17d22bba15001f/rayon-core-1.12.1/src/job.rs:218:15
  83: <rayon_core::job::StackJob<L,F,R> as rayon_core::job::Job>::execute
             at /Users/nxs/.cargo/registry/src/index.crates.io-6f17d22bba15001f/rayon-core-1.12.1/src/job.rs:120:32
  84: rayon_core::job::JobRef::execute
             at /Users/nxs/.cargo/registry/src/index.crates.io-6f17d22bba15001f/rayon-core-1.12.1/src/job.rs:64:9
  85: rayon_core::registry::WorkerThread::execute
             at /Users/nxs/.cargo/registry/src/index.crates.io-6f17d22bba15001f/rayon-core-1.12.1/src/registry.rs:860:9
  86: rayon_core::registry::WorkerThread::wait_until_cold
             at /Users/nxs/.cargo/registry/src/index.crates.io-6f17d22bba15001f/rayon-core-1.12.1/src/registry.rs:794:21
  87: rayon_core::registry::WorkerThread::wait_until
             at /Users/nxs/.cargo/registry/src/index.crates.io-6f17d22bba15001f/rayon-core-1.12.1/src/registry.rs:769:13
  88: rayon_core::registry::WorkerThread::wait_until_out_of_work
             at /Users/nxs/.cargo/registry/src/index.crates.io-6f17d22bba15001f/rayon-core-1.12.1/src/registry.rs:818:9
  89: rayon_core::registry::main_loop
             at /Users/nxs/.cargo/registry/src/index.crates.io-6f17d22bba15001f/rayon-core-1.12.1/src/registry.rs:923:5
  90: rayon_core::registry::ThreadBuilder::run
             at /Users/nxs/.cargo/registry/src/index.crates.io-6f17d22bba15001f/rayon-core-1.12.1/src/registry.rs:53:18
  91: <rayon_core::registry::DefaultSpawn as rayon_core::registry::ThreadSpawn>::spawn::{{closure}}
             at /Users/nxs/.cargo/registry/src/index.crates.io-6f17d22bba15001f/rayon-core-1.12.1/src/registry.rs:98:20
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```

### Issue description

I ran into this while working on the new parquet source node. Note this cannot be triggered without patching the line as all existing codepaths always pass a filter.

### Expected behavior

Should fully deserialize without panicking

### Installed versions

main / 1.4.1

**Comment by ritchie46** [comment]
@coastalwhite FYI.
