### ISSUE TITLE
`Series.search_sorted` gives wrong answer when using expression arguments

### ISSUE THREAD

**Issue by jeffpollock9** [pola-rs/polars#18180]
### Checks

- [X] I have checked that this issue has not already been reported.
- [X] I have confirmed this bug exists on the [latest version](https://pypi.org/project/polars/) of Polars.

### Reproducible example

```python
import numpy as np
import polars as pl

a = [0, 1, 10]
v = [0, 0, 10, 1]

np.searchsorted(a, v)
# array([0, 0, 2, 1])

pl.Series(a).search_sorted(pl.Series(v))
# shape: (4,)
# Series: '' [u32]
# [
# 	0
# 	0
# 	2
# 	1
# ]

pl.DataFrame({"v": v}).with_columns(search_sorted=pl.Series(a).search_sorted("v"))
# shape: (4, 2)
# ┌─────┬───────────────┐
# │ v   ┆ search_sorted │
# │ --- ┆ ---           │
# │ i64 ┆ i32           │
# ╞═════╪═══════════════╡
# │ 0   ┆ 3             │
# │ 0   ┆ 3             │
# │ 10  ┆ 3             │
# │ 1   ┆ 3             │
# └─────┴───────────────┘
```

### Log output

```shell
none
```

### Issue description

`pl.Series(a).search_sorted(pl.Series(v))` and `np.searchsorted(a, v)` match and give the correct answer, however when `v` is inside a `DataFrame` and passed to `search_sorted` it appears to give the wrong answer. Perhaps I am missing something but I _think_ this is a bug. Thanks!

### Expected behavior

I would have expected `pl.DataFrame({"v": v}).with_columns(search_sorted=pl.Series(a).search_sorted("v"))` to give the same answer as `pl.Series(a).search_sorted(pl.Series(v))`

### Installed versions

<details>

```
>>> pl.show_versions()
--------Version info---------
Polars:               1.4.1
Index type:           UInt32
Platform:             Linux-6.5.0-1027-oem-x86_64-with-glibc2.35
Python:               3.10.12 (main, Jul 29 2024, 16:56:48) [GCC 11.4.0]

----Optional dependencies----
adbc_driver_manager:  <not installed>
cloudpickle:          3.0.0
connectorx:           <not installed>
deltalake:            <not installed>
fastexcel:            <not installed>
fsspec:               <not installed>
gevent:               <not installed>
great_tables:         <not installed>
hvplot:               <not installed>
matplotlib:           <not installed>
nest_asyncio:         <not installed>
numpy:                1.26.4
openpyxl:             <not installed>
pandas:               2.2.2
pyarrow:              <not installed>
pydantic:             <not installed>
pyiceberg:            <not installed>
sqlalchemy:           <not installed>
torch:                <not installed>
xlsx2csv:             <not installed>
xlsxwriter:           <not installed>
```

</details>

**Comment by etiennebacher** [comment]
Might be a duplicate of https://github.com/pola-rs/polars/issues/18096

**Comment by jeffpollock9** [comment]
> Might be a duplicate of #18096

@etiennebacher thanks for the comment, it does seem at least very similar. I'm still confused though, using `pl.col("v")` in this case now gives an error:

``` python
>>> pl.DataFrame({"v": v}).with_columns(search_sorted=pl.Series(a).search_sorted(pl.col("v")))

Traceback (most recent call last):
  File "<string>", line 19, in __PYTHON_EL_eval
  File "/home/jeff/workspace/misc/search_sorted.py", line 27, in <module>
    pl.DataFrame({"v": v}).with_columns(search_sorted=pl.Series(a).search_sorted(pl.col("v")))
  File "/home/jeff/workspace/envs/universe/lib/python3.10/site-packages/polars/series/series.py", line 3415, in search_sorted
    df = F.select(F.lit(self).search_sorted(element, side))
  File "/home/jeff/workspace/envs/universe/lib/python3.10/site-packages/polars/functions/lazy.py", line 1899, in select
    return pl.DataFrame().select(*exprs, **named_exprs)
  File "/home/jeff/workspace/envs/universe/lib/python3.10/site-packages/polars/dataframe/frame.py", line 8717, in select
    return self.lazy().select(*exprs, **named_exprs).collect(_eager=True)
  File "/home/jeff/workspace/envs/universe/lib/python3.10/site-packages/polars/lazyframe/frame.py", line 2027, in collect
    return wrap_df(ldf.collect(callback))
polars.exceptions.ColumnNotFoundError: v
```

I guess the issue was just not fixed quite right.

**Comment by cmdlineluser** [comment]
Yeah, on main the current example now raises:

```
InvalidOperationError: got invalid or ambiguous dtypes: '[i64, str]' in expression 'search_sorted'
```

(This is due to `"v"` being interpreted as a literal string and not a column name: https://github.com/pola-rs/polars/issues/18099)

You need to wrap the Series in `pl.lit()` to prevent eager evaluation of the `col` argument:

```python
(pl.DataFrame({"v": v})
   .with_columns(search_sorted=pl.lit(pl.Series(a)).search_sorted(pl.col("v")))
) 
```
```
shape: (4, 2)
┌─────┬───────────────┐
│ v   ┆ search_sorted │
│ --- ┆ ---           │
│ i64 ┆ u32           │
╞═════╪═══════════════╡
│ 0   ┆ 0             │
│ 0   ┆ 0             │
│ 10  ┆ 2             │
│ 1   ┆ 1             │
└─────┴───────────────┘
```
