### ISSUE TITLE
No non-strict creation of literals

### ISSUE THREAD

**Issue by guyrosin** [pola-rs/polars#18256]
### Checks

- [X] I have checked that this issue has not already been reported.
- [X] I have confirmed this bug exists on the [latest version](https://pypi.org/project/polars/) of Polars.

### Reproducible example

```python
pl.lit([1, 2.0])  # results in TypeError: unexpected value while building Series of type Float64; found value of type Int64: 1
# Hint: Try setting `strict=False` to allow passing data with mixed types.

pl.lit([1, 2.0], dtype=pl.Float64)  # results in the same TypeError

pl.lit([1, 2.0], strict=False)  # results in TypeError: lit() got an unexpected keyword argument 'strict'
```

### Log output

```shell
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/ubuntu/playground/.venv/lib/python3.11/site-packages/polars/functions/lit.py", line 128, in lit
    return lit(pl.Series("literal", [value], dtype=dtype))
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/playground/.venv/lib/python3.11/site-packages/polars/series/series.py", line 292, in __init__
    self._s = sequence_to_pyseries(
              ^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/playground/.venv/lib/python3.11/site-packages/polars/_utils/construction/series.py", line 245, in sequence_to_pyseries
    return PySeries.new_from_any_values(name, values, strict=strict)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: unexpected value while building Series of type Float64; found value of type Int64: 1

Hint: Try setting `strict=False` to allow passing data with mixed types.
```

### Issue description

There's no option (that I'm aware of) to create a literal in a non-strict manner

### Expected behavior

I expected to have a `strict` argument for pl.lit()

### Installed versions

<details>

```
--------Version info---------
Polars:               1.5.0
Index type:           UInt32
Platform:             Linux-6.5.0-1015-aws-x86_64-with-glibc2.35
Python:               3.11.9 (main, Jul 13 2024, 23:44:43) [Clang 17.0.6 ]

----Optional dependencies----
adbc_driver_manager:  <not installed>
cloudpickle:          3.0.0
connectorx:           <not installed>
deltalake:            <not installed>
fastexcel:            0.11.5
fsspec:               2024.6.1
gevent:               <not installed>
great_tables:         <not installed>
hvplot:               0.10.0
matplotlib:           3.9.2
nest_asyncio:         1.6.0
numpy:                1.26.4
openpyxl:             <not installed>
pandas:               2.2.2
pyarrow:              17.0.0
pydantic:             <not installed>
pyiceberg:            <not installed>
sqlalchemy:           2.0.32
torch:                2.2.2+cu121
xlsx2csv:             0.8.3
xlsxwriter:           <not installed>
```

</details>

**Comment by ritchie46** [comment]
> There's no option (that I'm aware of) to create a literal in a non-strict manner

There is. If you pass a list of values, it is syntactic sugar for passing a `Series`.

`pl.lit(pl.Series([1, 2.0], strict=False))`

**Comment by mcrumiller** [comment]
FYI, we could add a `strict` parameter to `lit` anyway. This would not raise here, but return a null instead:

```pycon
>>> pl.select(pl.lit(256, dtype=pl.UInt8))
polars.exceptions.InvalidOperationError: conversion from `i32` to `u8` failed in column 'literal' for 1 out of 1 values: [256]
```

**Comment by guyrosin** [comment]
@ritchie46 Thanks, it's very helpful. 
Anyway I think the displayed hint of using `strict=False` is a bit misleading. If you prefer not to add a `strict` parameter to `lit` I would modify that hint to propose using `Series` as you suggested.
Thank you for your attention!
