### ISSUE TITLE
group_by on all columns cannot suppot tail

### ISSUE THREAD

**Issue by mingqi830** [pola-rs/polars#18279]
### Checks

- [X] I have checked that this issue has not already been reported.
- [X] I have confirmed this bug exists on the [latest version](https://pypi.org/project/polars/) of Polars.

### Reproducible example

```python

```
import pandas as pd
import polars as pl
df = pd.DataFrame({'a': ['Tom', 'Nick', 'Marry', 'Krish', 'Jack', None],
                   'b': ["2020-01-01", "2020-01-02", "2020-01-03", "2020-01-04", "2020-01-05", None],
                   'c': [5, 6, 6, 7, 8, 5]
                   })
pldf = pl.from_pandas(df)

res=pldf.group_by(['a','b','c']).tail(1)

res2=df.groupby(['a','b','c']).tail(1)

### Log output

```shell
Traceback (most recent call last):
  File "D:\git\sdmpymetric\test\df\df_polars_test.py", line 63, in <module>
    res=pldf.group_by(['a','b','c']).tail(1)
  File "D:\Program Files\Python39\lib\site-packages\polars\dataframe\group_by.py", line 404, in tail
    self.df.lazy()
  File "D:\Program Files\Python39\lib\site-packages\polars\lazyframe\frame.py", line 2027, in collect
    return wrap_df(ldf.collect(callback))
polars.exceptions.InvalidOperationError: no columns provided in explode
```

### Issue description

If group by on all columns, then cannot use tail method. But pandas support this kind of operation.
You can try the code above, the res2 can be returned but not res.

### Expected behavior

return the last n row of each group, same as the pandas' behavior.

### Installed versions

<details>

```
--------Version info---------
Polars:               1.4.1
Index type:           UInt32
Platform:             Windows-10-10.0.18362-SP0
Python:               3.9.7 (tags/v3.9.7:1016ef3, Aug 30 2021, 20:19:38) [MSC v.1929 64 bit (AMD64)]

----Optional dependencies----
adbc_driver_manager:  1.1.0
cloudpickle:          2.2.1
connectorx:           0.3.3
deltalake:            <not installed>
fastexcel:            <not installed>
fsspec:               2023.6.0
gevent:               <not installed>
great_tables:         <not installed>
hvplot:               <not installed>
matplotlib:           3.8.4
nest_asyncio:         1.5.6
numpy:                1.24.3
openpyxl:             <not installed>
pandas:               2.1.3
pyarrow:              16.1.0
pydantic:             1.10.2
pyiceberg:            <not installed>
sqlalchemy:           1.4.37
torch:                <not installed>
xlsx2csv:             <not installed>
xlsxwriter:           <not installed>
None
```

</details>

**Comment by MarcoGorelli** [comment]
thanks @mingqi830 for the report

agree, this looks like a bug
```
In [21]: pldf.group_by('a', 'b').tail(2)
Out[21]:
shape: (6, 3)
┌───────┬────────────┬─────┐
│ a     ┆ b          ┆ c   │
│ ---   ┆ ---        ┆ --- │
│ str   ┆ str        ┆ i64 │
╞═══════╪════════════╪═════╡
│ Nick  ┆ 2020-01-02 ┆ 6   │
│ Tom   ┆ 2020-01-01 ┆ 5   │
│ Jack  ┆ 2020-01-05 ┆ 8   │
│ null  ┆ null       ┆ 5   │
│ Marry ┆ 2020-01-03 ┆ 6   │
│ Krish ┆ 2020-01-04 ┆ 7   │
└───────┴────────────┴─────┘

In [22]: pldf.group_by('a', 'b', 'c').tail(2)
---------------------------------------------------------------------------
InvalidOperationError                     Traceback (most recent call last)
Cell In[22], line 1
----> 1 pldf.group_by('a', 'b', 'c').tail(2)

File ~/scratch/.venv/lib/python3.11/site-packages/polars/dataframe/group_by.py:409, in GroupBy.tail(self, n)
    360 def tail(self, n: int = 5) -> DataFrame:
    361     """
    362     Get the last `n` rows of each group.
    363
   (...)
    403     └─────────┴─────┘
    404     """
    405     return (
    406         self.df.lazy()
    407         .group_by(*self.by, **self.named_by, maintain_order=self.maintain_order)
    408         .tail(n)
--> 409         .collect(no_optimization=True)
    410     )

File ~/scratch/.venv/lib/python3.11/site-packages/polars/lazyframe/frame.py:2027, in LazyFrame.collect(self, type_coercion, predicate_pushdown, projection_pushdown, simplify_expression, slice_pushdown, comm_subplan_elim, comm_subexpr_elim, cluster_with_columns, no_optimization, streaming, engine, background, _eager, **_kwargs)
   2025 # Only for testing purposes
   2026 callback = _kwargs.get("post_opt_callback", callback)
-> 2027 return wrap_df(ldf.collect(callback))

InvalidOperationError: no columns provided in explode

In [23]: pldf.group_by('*').tail(2)
---------------------------------------------------------------------------
InvalidOperationError                     Traceback (most recent call last)
Cell In[23], line 1
----> 1 pldf.group_by('*').tail(2)

File ~/scratch/.venv/lib/python3.11/site-packages/polars/dataframe/group_by.py:409, in GroupBy.tail(self, n)
    360 def tail(self, n: int = 5) -> DataFrame:
    361     """
    362     Get the last `n` rows of each group.
    363
   (...)
    403     └─────────┴─────┘
    404     """
    405     return (
    406         self.df.lazy()
    407         .group_by(*self.by, **self.named_by, maintain_order=self.maintain_order)
    408         .tail(n)
--> 409         .collect(no_optimization=True)
    410     )

File ~/scratch/.venv/lib/python3.11/site-packages/polars/lazyframe/frame.py:2027, in LazyFrame.collect(self, type_coercion, predicate_pushdown, projection_pushdown, simplify_expression, slice_pushdown, comm_subplan_elim, comm_subexpr_elim, cluster_with_columns, no_optimization, streaming, engine, background, _eager, **_kwargs)
   2025 # Only for testing purposes
   2026 callback = _kwargs.get("post_opt_callback", callback)
-> 2027 return wrap_df(ldf.collect(callback))

InvalidOperationError: `explode` operation not supported for dtype `str`
```
