### ISSUE TITLE
Join result cannot be used in `with_context` for LazyFrame

### ISSUE THREAD

**Issue by Kryzpoo** [pola-rs/polars#18297]
### Checks

- [X] I have checked that this issue has not already been reported.
- [X] I have confirmed this bug exists on the [latest version](https://pypi.org/project/polars/) of Polars.

### Reproducible example

```python
df1 = pl.LazyFrame({"a": [1, 2, 3, 4], "c": [4, 5, 6, 7]})
df2 = pl.LazyFrame({"a": [4, 5, 6, 7], "b": [7, 8, 9, 10]})
result = df1.join(df2, how='cross')
df1.with_context(result).collect()
```

### Log output

```shell
Traceback (most recent call last):
  File "/root/.pycharm_helpers/pydevd_asyncio/pydevd_asyncio_utils.py", line 117, in _exec_async_code
    result = func()
             ^^^^^^
  File "<input>", line 1, in <module>
  File "/usr/local/lib/python3.11/site-packages/polars/lazyframe/frame.py", line 2027, in collect
    return wrap_df(ldf.collect(callback))
                   ^^^^^^^^^^^^^^^^^^^^^
pyo3_runtime.PanicException: called `Option::unwrap()` on a `None` value
```

### Issue description

Join result cannot be used in `with_context` for LazyFrame

### Expected behavior

As `join` result is a valid LazyFrame object, it should be acceptable for using in any place where other LazyFrame object can be fit.

### Installed versions

<details>

```
--------Version info---------
Polars:               1.5.0
Index type:           UInt32
Platform:             Linux-5.15.49-linuxkit-pr-aarch64-with-glibc2.28
Python:               3.11.4 (main, Jun 13 2023, 11:34:58) [GCC 8.3.0]
----Optional dependencies----
adbc_driver_manager:  <not installed>
cloudpickle:          <not installed>
connectorx:           <not installed>
deltalake:            <not installed>
fastexcel:            <not installed>
fsspec:               <not installed>
gevent:               <not installed>
great_tables:         <not installed>
hvplot:               <not installed>
matplotlib:           <not installed>
nest_asyncio:         <not installed>
numpy:                2.1.0
openpyxl:             <not installed>
pandas:               <not installed>
pyarrow:              16.1.0
pydantic:             1.10.13
pyiceberg:            <not installed>
sqlalchemy:           <not installed>
torch:                <not installed>
xlsx2csv:             <not installed>
xlsxwriter:           <not installed>
```

</details>

**Comment by cmdlineluser** [comment]
```
DeprecationWarning: `LazyFrame.with_context` is deprecated. 
Use `pl.concat(..., how='horizontal')` instead.
```

https://github.com/pola-rs/polars/issues/7484#issuecomment-2159202509

> LazyFrame.with_context will be deprecated with the release of 1.0.0 (https://github.com/pola-rs/polars/pull/16860). We will not fix any bugs associated with it.

**Comment by ritchie46** [comment]
We will not fix this. `with_context` is deprecated and will be removed.

**Comment by Kryzpoo** [comment]
What about situations when LazyFrame column is needed as filter condition for other LazyFrame?

Example 1:
```python
lf1 = pl.LazyFrame({"a": [1, 2, 3, 4], "b": [4, 5, 6, 7]})
lf2 = pl.LazyFrame({"c": [4, 5, 6, 7]})

lf1.with_context(lf2).filter(pl.col('a').is_in(pl.col('c')))
```
is equivalent to example 2, but without necessary to materialize data from lf2:
```python
lf1 = pl.LazyFrame({"a": [1, 2, 3, 4], "b": [4, 5, 6, 7]})
lf2 = pl.LazyFrame({"c": [4, 5, 6, 7]})

lf1.filter(pl.col('a').is_in(lf2.collect()['c']))
```

I think that `pl.concat` is not applicable for this case

**Comment by cmdlineluser** [comment]
The suggestion would be:

```python
(pl.concat([lf1, lf2], how="horizontal")
   .filter(pl.col('a').is_in(pl.col('c')))
   .collect()
)

# shape: (1, 3)
# ┌─────┬─────┬─────┐
# │ a   ┆ b   ┆ c   │
# │ --- ┆ --- ┆ --- │
# │ i64 ┆ i64 ┆ i64 │
# ╞═════╪═════╪═════╡
# │ 4   ┆ 7   ┆ 7   │
# └─────┴─────┴─────┘
```
