### ISSUE TITLE
`read_ndjson()` and `read_parquet()` behave differently when the input is a list of files with different schemas

### ISSUE THREAD

**Issue by etiennebacher** [pola-rs/polars#18306]
### Checks

- [X] I have checked that this issue has not already been reported.
- [X] I have confirmed this bug exists on the [latest version](https://pypi.org/project/polars/) of Polars.

### Reproducible example

```python
import polars as pl

# ndjson
pl.DataFrame({"x": [1]}).write_ndjson("foo.json")
pl.DataFrame({"y": [1]}).write_ndjson("foo2.json")
pl.read_ndjson(["data.json", "data2.json"])

# parquet
pl.DataFrame({"x": [1]}).write_parquet("foo.parquet")
pl.DataFrame({"y": [1]}).write_parquet("foo2.parquet")
pl.read_parquet(["foo.parquet", "foo2.parquet"])
```

### Log output

```shell
# ndjson

shape: (2, 1)
┌───────────┐
│ a         │
│ ---       │
│ list[i64] │
╞═══════════╡
│ [1, 2]    │
│ null      │
└───────────┘

# parquet

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\etienne\AppData\Roaming\Python\Python311\site-packages\polars\_utils\deprecation.py", line 91, in wrapper
    return function(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\etienne\AppData\Roaming\Python\Python311\site-packages\polars\_utils\deprecation.py", line 91, in wrapper
    return function(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\etienne\AppData\Roaming\Python\Python311\site-packages\polars\io\parquet\functions.py", line 208, in read_parquet
    return lf.collect()
           ^^^^^^^^^^^^
  File "C:\Users\etienne\AppData\Roaming\Python\Python311\site-packages\polars\lazyframe\frame.py", line 2027, in collect
    return wrap_df(ldf.collect(callback))
                   ^^^^^^^^^^^^^^^^^^^^^
polars.exceptions.SchemaError: schema names differ at index 0: x != y
```

### Issue description

`read_ndjson()` and `read_parquet()` behave differently when the input is a list of files with different schemas:

* `read_ndjson()` only keeps the schema of the first file and adds empty rows
* `read_parquet()` ignores (probably the best behavior here)

### Expected behavior

Both functions should have the same behavior.

### Installed versions

<details>

```
--------Version info---------
Polars:               1.5.0
Index type:           UInt32
Platform:             Windows-10-10.0.19045-SP0
Python:               3.11.0 (main, Oct 24 2022, 18:26:48) [MSC v.1933 64 bit (AMD64)]

----Optional dependencies----
adbc_driver_manager:  <not installed>
cloudpickle:          <not installed>
connectorx:           <not installed>
deltalake:            <not installed>
fastexcel:            <not installed>
fsspec:               2023.6.0
gevent:               <not installed>
great_tables:         <not installed>
hvplot:               0.9.2
matplotlib:           3.7.1
nest_asyncio:         1.5.6
numpy:                1.24.3
openpyxl:             <not installed>
pandas:               2.0.3
pyarrow:              12.0.1
pydantic:             2.6.4
pyiceberg:            <not installed>
sqlalchemy:           <not installed>
torch:                <not installed>
xlsx2csv:             <not installed>
xlsxwriter:           <not installed>
```

</details>

**Comment by ion-elgreco** [comment]
Both should just deepmerge the schemas or have an option to provide the schema
