### ISSUE TITLE
pl.from_numpy produces column with null dtype when input array is empty

### ISSUE THREAD

**Issue by danpatton** [pola-rs/polars#18310]
### Checks

- [X] I have checked that this issue has not already been reported.
- [X] I have confirmed this bug exists on the [latest version](https://pypi.org/project/polars/) of Polars.

### Reproducible example

```python
import numpy as np
import polars as pl
from polars.testing import assert_frame_equal

data = np.zeros((0,))
assert_frame_equal(pl.from_numpy(data, schema=["foo"]), pl.Series("foo", data).to_frame())
```

### Log output

```shell
Traceback (most recent call last):
  File "repro.py", line 6, in <module>
    assert_frame_equal(pl.from_numpy(data, schema=["foo"]), pl.Series("foo", data).to_frame())
  File ".venv/lib/python3.11/site-packages/polars/_utils/deprecation.py", line 91, in wrapper
    return function(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File ".venv/lib/python3.11/site-packages/polars/testing/asserts/frame.py", line 91, in assert_frame_equal
    _assert_frame_schema_equal(
  File ".venv/lib/python3.11/site-packages/polars/testing/asserts/frame.py", line 187, in _assert_frame_schema_equal
    raise_assertion_error(objects, detail, left_schema_dict, right_schema_dict)
  File ".venv/lib/python3.11/site-packages/polars/testing/asserts/utils.py", line 12, in raise_assertion_error
    raise AssertionError(msg) from cause
AssertionError: DataFrames are different (dtypes do not match)
[left]:  {'foo': Null}
[right]: {'foo': Float64}
```

### Issue description

If you change the shape of `data` to `(1,)` then the assertion passes

### Expected behavior

Assertion passes when the shape of the data is `(0,)`

### Installed versions

<details>

```
Polars:               1.5.0
Index type:           UInt32
Platform:             Linux-6.5.0-44-generic-x86_64-with-glibc2.35
Python:               3.11.9 (main, Apr  6 2024, 17:59:24) [GCC 11.4.0]

----Optional dependencies----
adbc_driver_manager:  <not installed>
cloudpickle:          <not installed>
connectorx:           <not installed>
deltalake:            <not installed>
fastexcel:            <not installed>
fsspec:               <not installed>
gevent:               <not installed>
great_tables:         <not installed>
hvplot:               <not installed>
matplotlib:           <not installed>
nest_asyncio:         <not installed>
numpy:                2.1.0
openpyxl:             <not installed>
pandas:               <not installed>
pyarrow:              <not installed>
pydantic:             <not installed>
pyiceberg:            <not installed>
sqlalchemy:           <not installed>
torch:                <not installed>
xlsx2csv:             <not installed>
xlsxwriter:           <not installed>
```

</details>

**Comment by deanm0000** [comment]
The issue is that `pl.from_numpy(data, schema=["foo"])` returns a `0,0` dataframe. Since a dataframe is just a collection of Series, having 0 columns means no Series to store dtype info.

A `Series` doesn't have columns, it is a column, so when you do `pl.Series("foo", data)` it has no issue stashing the dtype in itself.

@alexander-beedie is there a workable solution here? Maybe make `from_numpy` return (0,1) instead of (0,0)?

**Comment by ion-elgreco** [comment]
If you explicitly provide a schema with the dtypes this is not an issue

**Comment by danpatton** [comment]
> If you explicitly provide a schema with the dtypes this is not an issue

I tried this, but it gives the same behaviour:
```
assert_frame_equal(pl.from_numpy(data, schema={"foo": pl.Float32}), pl.Series("foo", data).to_frame())
```
