### ISSUE TITLE
Possible miscompilation/unsoundness with latest toolchain update

### ISSUE THREAD

**Issue by wence-** [pola-rs/polars#18409]
Consider:

```python
import polars as pl

df = pl.DataFrame(
        {
            "a": [1, 2, 3, 2, 4],
            "c": [1, 1, 4, 5, 5],
        }
    )
df.write_csv("foo.csv")

df2 = pl.read_csv("foo.csv")

print(df)
print(df2)
```

On `main` (d12131a8b), compiling with `--profile opt-dev`, the above example fails to run with a panic:
```
thread 'polars-0' panicked at crates/polars-io/src/csv/read/splitfields.rs:155:9:
internal error: entered unreachable code
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
Traceback (most recent call last):
  File "/home/coder/doodles/python/polars-interp/bug.py", line 12, in <module>
    df2 = pl.read_csv("foo.csv")
  File "/home/coder/third-party/polars/py-polars/polars/_utils/deprecation.py", line 91, in wrapper
    return function(*args, **kwargs)
  File "/home/coder/third-party/polars/py-polars/polars/_utils/deprecation.py", line 91, in wrapper
    return function(*args, **kwargs)
  File "/home/coder/third-party/polars/py-polars/polars/_utils/deprecation.py", line 91, in wrapper
    return function(*args, **kwargs)
  File "/home/coder/third-party/polars/py-polars/polars/io/csv/functions.py", line 496, in read_csv
    df = _read_csv_impl(
  File "/home/coder/third-party/polars/py-polars/polars/io/csv/functions.py", line 642, in _read_csv_impl
    pydf = PyDataFrame.read_csv(
pyo3_runtime.PanicException: internal error: entered unreachable code
```

<details>
<summary><code>RUST_BACKTRACE=full</code></summary>

```
thread 'polars-0' panicked at crates/polars-io/src/csv/read/splitfields.rs:155:9:
internal error: entered unreachable code
stack backtrace:
   0:     0x7d7a50f3c5dd - std::backtrace_rs::backtrace::libunwind::trace::h91845c451f8de049
                               at /rustc/c6db1ca3c93ad69692a4c4b5542f26fda4bf3aec/library/std/src/../../backtrace/src/backtrace/libunwind.rs:116:5
   1:     0x7d7a50f3c5dd - std::backtrace_rs::backtrace::trace_unsynchronized::hba51bd6b35f4c19c
                               at /rustc/c6db1ca3c93ad69692a4c4b5542f26fda4bf3aec/library/std/src/../../backtrace/src/backtrace/mod.rs:66:5
   2:     0x7d7a50f3c5dd - std::sys::backtrace::_print_fmt::h5df6ae8419e5a7d0
                               at /rustc/c6db1ca3c93ad69692a4c4b5542f26fda4bf3aec/library/std/src/sys/backtrace.rs:66:9
   3:     0x7d7a50f3c5dd - <std::sys::backtrace::BacktraceLock::print::DisplayBacktrace as core::fmt::Display>::fmt::h08c68512b2311366
                               at /rustc/c6db1ca3c93ad69692a4c4b5542f26fda4bf3aec/library/std/src/sys/backtrace.rs:39:26
   4:     0x7d7a50f6beab - core::fmt::rt::Argument::fmt::h11296e5540fbe1b9
                               at /rustc/c6db1ca3c93ad69692a4c4b5542f26fda4bf3aec/library/core/src/fmt/rt.rs:173:76
   5:     0x7d7a50f6beab - core::fmt::write::h6e3f8345ff37039b
                               at /rustc/c6db1ca3c93ad69692a4c4b5542f26fda4bf3aec/library/core/src/fmt/mod.rs:1178:21
   6:     0x7d7a50f37cb3 - std::io::Write::write_fmt::hc6823578ffc00004
                               at /rustc/c6db1ca3c93ad69692a4c4b5542f26fda4bf3aec/library/std/src/io/mod.rs:1823:15
   7:     0x7d7a50f3d722 - std::sys::backtrace::BacktraceLock::print::hdba6c7eedfb8a6b8
                               at /rustc/c6db1ca3c93ad69692a4c4b5542f26fda4bf3aec/library/std/src/sys/backtrace.rs:42:9
   8:     0x7d7a50f3d722 - std::panicking::default_hook::{{closure}}::hee63056ca50632bf
                               at /rustc/c6db1ca3c93ad69692a4c4b5542f26fda4bf3aec/library/std/src/panicking.rs:266:22
   9:     0x7d7a50f3d38e - std::panicking::default_hook::hf7cfdbe4468ff824
                               at /rustc/c6db1ca3c93ad69692a4c4b5542f26fda4bf3aec/library/std/src/panicking.rs:293:9
  10:     0x7d7a50f3e01f - std::panicking::rust_panic_with_hook::hdfce2b8bd7fc4cbd
                               at /rustc/c6db1ca3c93ad69692a4c4b5542f26fda4bf3aec/library/std/src/panicking.rs:797:13
  11:     0x7d7a50f3dcd3 - std::panicking::begin_panic_handler::{{closure}}::h1fea56f9bbc92609
                               at /rustc/c6db1ca3c93ad69692a4c4b5542f26fda4bf3aec/library/std/src/panicking.rs:664:13
  12:     0x7d7a50f3cac9 - std::sys::backtrace::__rust_end_short_backtrace::h60ce9d111c920856
                               at /rustc/c6db1ca3c93ad69692a4c4b5542f26fda4bf3aec/library/std/src/sys/backtrace.rs:170:18
  13:     0x7d7a50f3d994 - rust_begin_unwind
                               at /rustc/c6db1ca3c93ad69692a4c4b5542f26fda4bf3aec/library/std/src/panicking.rs:662:5
  14:     0x7d7a50f68623 - core::panicking::panic_fmt::hca2ff70b38236a4a
                               at /rustc/c6db1ca3c93ad69692a4c4b5542f26fda4bf3aec/library/core/src/panicking.rs:74:14
  15:     0x7d7a50f686ac - core::panicking::panic::hc8dd6686aa7d0640
                               at /rustc/c6db1ca3c93ad69692a4c4b5542f26fda4bf3aec/library/core/src/panicking.rs:148:5
  16:     0x7d7a4db04688 - polars_io::csv::read::splitfields::inner::simple_argmax::h53a43cafd3c337b0
                               at /home/coder/third-party/polars/crates/polars-io/src/csv/read/splitfields.rs:155:9
  17:     0x7d7a4db04688 - <polars_io::csv::read::splitfields::inner::SplitFields as core::iter::traits::iterator::Iterator>::next::hd6475fec51240fac
                               at /home/coder/third-party/polars/crates/polars-io/src/csv/read/splitfields.rs:294:46
  18:     0x7d7a4db02b7f - polars_io::csv::read::parser::parse_lines::h98ca9e5056867bc7
                               at /home/coder/third-party/polars/crates/polars-io/src/csv/read/parser.rs:495:19
  19:     0x7d7a4dc84468 - polars_io::csv::read::read_impl::read_chunk::h3dd66a700bdb7e46
                               at /home/coder/third-party/polars/crates/polars-io/src/csv/read/read_impl.rs:748:17
  20:     0x7d7a4dc324fd - polars_io::csv::read::read_impl::CoreReader::parse_csv::{{closure}}::{{closure}}::had8b19800bbd1407
                               at /home/coder/third-party/polars/crates/polars-io/src/csv/read/read_impl.rs:597:38
  21:     0x7d7a4dc324fd - core::ops::function::impls::<impl core::ops::function::FnMut<A> for &F>::call_mut::h7673e5d685cb9a81
                               at /rustc/c6db1ca3c93ad69692a4c4b5542f26fda4bf3aec/library/core/src/ops/function.rs:272:13
  22:     0x7d7a4dc1aebf - core::ops::function::impls::<impl core::ops::function::FnOnce<A> for &mut F>::call_once::h167cdb16017aeb17
                               at /rustc/c6db1ca3c93ad69692a4c4b5542f26fda4bf3aec/library/core/src/ops/function.rs:305:13
  23:     0x7d7a4dc1aebf - core::option::Option<T>::map::hbeab6ff7549393df
                               at /rustc/c6db1ca3c93ad69692a4c4b5542f26fda4bf3aec/library/core/src/option.rs:1105:29
  24:     0x7d7a4dc1aebf - <core::iter::adapters::map::Map<I,F> as core::iter::traits::iterator::Iterator>::next::hb69ab0747a2e5fcd
                               at /rustc/c6db1ca3c93ad69692a4c4b5542f26fda4bf3aec/library/core/src/iter/adapters/map.rs:107:26
  25:     0x7d7a4dc1aebf - <core::iter::adapters::map::Map<I,F> as core::iter::traits::iterator::Iterator>::next::h24e8bb9bf3d20b1a
                               at /rustc/c6db1ca3c93ad69692a4c4b5542f26fda4bf3aec/library/core/src/iter/adapters/map.rs:107:9
  26:     0x7d7a4dc1aebf - <core::iter::adapters::take_while::TakeWhile<I,P> as core::iter::traits::iterator::Iterator>::next::h9e53218716dbc5d1
                               at /rustc/c6db1ca3c93ad69692a4c4b5542f26fda4bf3aec/library/core/src/iter/adapters/take_while.rs:48:21
  27:     0x7d7a4dc1aebf - <core::iter::adapters::map::Map<I,F> as core::iter::traits::iterator::Iterator>::next::h2bdbe6fe8dd926df
                               at /rustc/c6db1ca3c93ad69692a4c4b5542f26fda4bf3aec/library/core/src/iter/adapters/map.rs:107:9
  28:     0x7d7a4dc1aebf - alloc::vec::Vec<T,A>::extend_desugared::hd78dd18b7d6864d7
                               at /rustc/c6db1ca3c93ad69692a4c4b5542f26fda4bf3aec/library/alloc/src/vec/mod.rs:3089:35
  29:     0x7d7a4db52196 - <alloc::vec::Vec<T,A> as alloc::vec::spec_extend::SpecExtend<T,I>>::spec_extend::hf9f2d70765686d4e
                               at /rustc/c6db1ca3c93ad69692a4c4b5542f26fda4bf3aec/library/alloc/src/vec/spec_extend.rs:17:9
  30:     0x7d7a4db52196 - <alloc::vec::Vec<T,A> as core::iter::traits::collect::Extend<T>>::extend::hbfa7b0002358da2d
                               at /rustc/c6db1ca3c93ad69692a4c4b5542f26fda4bf3aec/library/alloc/src/vec/mod.rs:3053:9
  31:     0x7d7a4db52196 - <rayon::iter::extend::ListVecFolder<T> as rayon::iter::plumbing::Folder<T>>::consume_iter::hcf6b40319a78d8d6
                               at /usr/local/cargo/registry/src/index.crates.io-6f17d22bba15001f/rayon-1.10.0/src/iter/extend.rs:130:9
  32:     0x7d7a4db52196 - <rayon::iter::while_some::WhileSomeFolder<C> as rayon::iter::plumbing::Folder<core::option::Option<T>>>::consume_iter::hce9eaf9c6da696ae
                               at /usr/local/cargo/registry/src/index.crates.io-6f17d22bba15001f/rayon-1.10.0/src/iter/while_some.rs:139:21
  33:     0x7d7a4db52196 - <rayon::iter::map::MapFolder<C,F> as rayon::iter::plumbing::Folder<T>>::consume_iter::h74dbf6a935345fd8
                               at /usr/local/cargo/registry/src/index.crates.io-6f17d22bba15001f/rayon-1.10.0/src/iter/map.rs:248:21
  34:     0x7d7a4db52196 - <rayon::iter::map::MapFolder<C,F> as rayon::iter::plumbing::Folder<T>>::consume_iter::h0cb46cf070238da3
                               at /usr/local/cargo/registry/src/index.crates.io-6f17d22bba15001f/rayon-1.10.0/src/iter/map.rs:248:21
  35:     0x7d7a4db52196 - rayon::iter::plumbing::Producer::fold_with::h306ac6400a097b36
                               at /usr/local/cargo/registry/src/index.crates.io-6f17d22bba15001f/rayon-1.10.0/src/iter/plumbing/mod.rs:109:9
  36:     0x7d7a4dbbb60c - rayon::iter::plumbing::bridge_producer_consumer::helper::hbb6484c6df5341d7
                               at /usr/local/cargo/registry/src/index.crates.io-6f17d22bba15001f/rayon-1.10.0/src/iter/plumbing/mod.rs:437:13
  37:     0x7d7a4db52ea5 - rayon::iter::plumbing::bridge_producer_consumer::h924faeb19dc1397b
                               at /usr/local/cargo/registry/src/index.crates.io-6f17d22bba15001f/rayon-1.10.0/src/iter/plumbing/mod.rs:396:12
  38:     0x7d7a4db52ea5 - <rayon::iter::plumbing::bridge::Callback<C> as rayon::iter::plumbing::ProducerCallback<I>>::callback::h8c32bec9787ac383
                               at /usr/local/cargo/registry/src/index.crates.io-6f17d22bba15001f/rayon-1.10.0/src/iter/plumbing/mod.rs:372:13
  39:     0x7d7a4db52ea5 - <rayon::vec::Drain<T> as rayon::iter::IndexedParallelIterator>::with_producer::h41d1b29e5edd9f3e
                               at /usr/local/cargo/registry/src/index.crates.io-6f17d22bba15001f/rayon-1.10.0/src/vec.rs:147:13
  40:     0x7d7a4db52ea5 - <rayon::vec::IntoIter<T> as rayon::iter::IndexedParallelIterator>::with_producer::h4323e7a9c5e407a0
                               at /usr/local/cargo/registry/src/index.crates.io-6f17d22bba15001f/rayon-1.10.0/src/vec.rs:83:9
  41:     0x7d7a4dc1d84a - rayon::iter::plumbing::bridge::h39ab7bf40074e76e
                               at /usr/local/cargo/registry/src/index.crates.io-6f17d22bba15001f/rayon-1.10.0/src/iter/plumbing/mod.rs:356:12
  42:     0x7d7a4dc1d84a - <rayon::vec::IntoIter<T> as rayon::iter::ParallelIterator>::drive_unindexed::hc4ad7ecd843fe36d
                               at /usr/local/cargo/registry/src/index.crates.io-6f17d22bba15001f/rayon-1.10.0/src/vec.rs:58:9
  43:     0x7d7a4dc1d84a - <rayon::iter::map::Map<I,F> as rayon::iter::ParallelIterator>::drive_unindexed::hd179e3ed7bb0e6f5
                               at /usr/local/cargo/registry/src/index.crates.io-6f17d22bba15001f/rayon-1.10.0/src/iter/map.rs:49:9
  44:     0x7d7a4dc1d84a - <rayon::iter::map::Map<I,F> as rayon::iter::ParallelIterator>::drive_unindexed::h9034b118ba04b5f6
                               at /usr/local/cargo/registry/src/index.crates.io-6f17d22bba15001f/rayon-1.10.0/src/iter/map.rs:49:9
  45:     0x7d7a4dc1d84a - <rayon::iter::while_some::WhileSome<I> as rayon::iter::ParallelIterator>::drive_unindexed::hea2b5116c6789bf1
                               at /usr/local/cargo/registry/src/index.crates.io-6f17d22bba15001f/rayon-1.10.0/src/iter/while_some.rs:44:9
  46:     0x7d7a4dc1d84a - rayon::iter::extend::<impl rayon::iter::ParallelExtend<T> for alloc::vec::Vec<T>>::par_extend::hd3fd5a6ab72a9c2c
                               at /usr/local/cargo/registry/src/index.crates.io-6f17d22bba15001f/rayon-1.10.0/src/iter/extend.rs:588:28
  47:     0x7d7a4dbdacdc - rayon::iter::from_par_iter::collect_extended::h425dbde7a2550715
                               at /usr/local/cargo/registry/src/index.crates.io-6f17d22bba15001f/rayon-1.10.0/src/iter/from_par_iter.rs:20:5
  48:     0x7d7a4dbdacdc - rayon::iter::from_par_iter::<impl rayon::iter::FromParallelIterator<T> for alloc::vec::Vec<T>>::from_par_iter::h8b474c9ac88c0e88
                               at /usr/local/cargo/registry/src/index.crates.io-6f17d22bba15001f/rayon-1.10.0/src/iter/from_par_iter.rs:33:9
  49:     0x7d7a4dbdacdc - rayon::iter::ParallelIterator::collect::h0d10ebc990d19925
                               at /usr/local/cargo/registry/src/index.crates.io-6f17d22bba15001f/rayon-1.10.0/src/iter/mod.rs:2069:9
  50:     0x7d7a4dbdacdc - rayon::result::<impl rayon::iter::FromParallelIterator<core::result::Result<T,E>> for core::result::Result<C,E>>::from_par_iter::h6e6589440596fcd1
                               at /usr/local/cargo/registry/src/index.crates.io-6f17d22bba15001f/rayon-1.10.0/src/result.rs:121:26
  51:     0x7d7a4dc7ae42 - rayon::iter::ParallelIterator::collect::h5e8d43af4355b6cf
                               at /usr/local/cargo/registry/src/index.crates.io-6f17d22bba15001f/rayon-1.10.0/src/iter/mod.rs:2069:9
  52:     0x7d7a4dc7ae42 - polars_io::csv::read::read_impl::CoreReader::parse_csv::{{closure}}::hdd15d24b0a90c437
                               at /home/coder/third-party/polars/crates/polars-io/src/csv/read/read_impl.rs:594:17
  53:     0x7d7a4dc7ae42 - rayon_core::thread_pool::ThreadPool::install::{{closure}}::h2bb3b1fe78c0f92a
                               at /usr/local/cargo/registry/src/index.crates.io-6f17d22bba15001f/rayon-core-1.12.1/src/thread_pool/mod.rs:147:40
  54:     0x7d7a4dc7ae42 - rayon_core::registry::Registry::in_worker_cold::{{closure}}::{{closure}}::hc09821631e034295
                               at /usr/local/cargo/registry/src/index.crates.io-6f17d22bba15001f/rayon-core-1.12.1/src/registry.rs:522:21
  55:     0x7d7a4dc7ae42 - rayon_core::job::JobResult<T>::call::{{closure}}::h45d17f1da7ca7558
                               at /usr/local/cargo/registry/src/index.crates.io-6f17d22bba15001f/rayon-core-1.12.1/src/job.rs:218:41
  56:     0x7d7a4dc7ae42 - <core::panic::unwind_safe::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once::h58650f45b008abae
                               at /rustc/c6db1ca3c93ad69692a4c4b5542f26fda4bf3aec/library/core/src/panic/unwind_safe.rs:272:9
  57:     0x7d7a4dc7ae42 - std::panicking::try::do_call::he2d0d88ab854abd3
                               at /rustc/c6db1ca3c93ad69692a4c4b5542f26fda4bf3aec/library/std/src/panicking.rs:554:40
  58:     0x7d7a4dc7ae42 - std::panicking::try::h90e43757838e15e3
                               at /rustc/c6db1ca3c93ad69692a4c4b5542f26fda4bf3aec/library/std/src/panicking.rs:518:19
  59:     0x7d7a4dc7ae42 - std::panic::catch_unwind::h4a2dc61517905560
                               at /rustc/c6db1ca3c93ad69692a4c4b5542f26fda4bf3aec/library/std/src/panic.rs:345:14
  60:     0x7d7a4db5ad0b - rayon_core::unwind::halt_unwinding::h98d8a0d5be11b8c0
                               at /usr/local/cargo/registry/src/index.crates.io-6f17d22bba15001f/rayon-core-1.12.1/src/unwind.rs:17:5
  61:     0x7d7a4db5ad0b - rayon_core::job::JobResult<T>::call::h524be7bd8c3b46d7
                               at /usr/local/cargo/registry/src/index.crates.io-6f17d22bba15001f/rayon-core-1.12.1/src/job.rs:218:15
  62:     0x7d7a4db5ad0b - <rayon_core::job::StackJob<L,F,R> as rayon_core::job::Job>::execute::h601c09f102956468
                               at /usr/local/cargo/registry/src/index.crates.io-6f17d22bba15001f/rayon-core-1.12.1/src/job.rs:120:32
  63:     0x7d7a50cdc499 - rayon_core::job::JobRef::execute::h1374376af137b683
                               at /usr/local/cargo/registry/src/index.crates.io-6f17d22bba15001f/rayon-core-1.12.1/src/job.rs:64:9
  64:     0x7d7a50cdc499 - rayon_core::registry::WorkerThread::execute::h2c58e57ba2bb2deb
                               at /usr/local/cargo/registry/src/index.crates.io-6f17d22bba15001f/rayon-core-1.12.1/src/registry.rs:860:9
  65:     0x7d7a50cdc499 - rayon_core::registry::WorkerThread::wait_until_cold::haa8e6b2ae327b948
                               at /usr/local/cargo/registry/src/index.crates.io-6f17d22bba15001f/rayon-core-1.12.1/src/registry.rs:794:21
  66:     0x7d7a50cda601 - rayon_core::registry::WorkerThread::wait_until::h1d07dac1aef3f5cd
                               at /usr/local/cargo/registry/src/index.crates.io-6f17d22bba15001f/rayon-core-1.12.1/src/registry.rs:769:13
  67:     0x7d7a50cda601 - rayon_core::registry::WorkerThread::wait_until_out_of_work::h2965e0dd58f90cf1
                               at /usr/local/cargo/registry/src/index.crates.io-6f17d22bba15001f/rayon-core-1.12.1/src/registry.rs:818:9
  68:     0x7d7a50cda601 - rayon_core::registry::main_loop::hedbc3e4964cd3e27
                               at /usr/local/cargo/registry/src/index.crates.io-6f17d22bba15001f/rayon-core-1.12.1/src/registry.rs:923:5
  69:     0x7d7a50cda601 - rayon_core::registry::ThreadBuilder::run::hd547936c11668dc2
                               at /usr/local/cargo/registry/src/index.crates.io-6f17d22bba15001f/rayon-core-1.12.1/src/registry.rs:53:18
  70:     0x7d7a50cddfea - <rayon_core::registry::DefaultSpawn as rayon_core::registry::ThreadSpawn>::spawn::{{closure}}::h8f87bf8dae6e6c60
                               at /usr/local/cargo/registry/src/index.crates.io-6f17d22bba15001f/rayon-core-1.12.1/src/registry.rs:98:20
  71:     0x7d7a50cddfea - std::sys::backtrace::__rust_begin_short_backtrace::h631469fada854b1d
                               at /rustc/c6db1ca3c93ad69692a4c4b5542f26fda4bf3aec/library/std/src/sys/backtrace.rs:154:18
  72:     0x7d7a50ce06e9 - std::thread::Builder::spawn_unchecked_::{{closure}}::{{closure}}::hd27f015ed1bf7774
                               at /rustc/c6db1ca3c93ad69692a4c4b5542f26fda4bf3aec/library/std/src/thread/mod.rs:522:17
  73:     0x7d7a50ce06e9 - <core::panic::unwind_safe::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once::hd36f725523b89298
                               at /rustc/c6db1ca3c93ad69692a4c4b5542f26fda4bf3aec/library/core/src/panic/unwind_safe.rs:272:9
  74:     0x7d7a50ce06e9 - std::panicking::try::do_call::hd60d0f82e8426a88
                               at /rustc/c6db1ca3c93ad69692a4c4b5542f26fda4bf3aec/library/std/src/panicking.rs:554:40
  75:     0x7d7a50ce06e9 - std::panicking::try::h5efc1e591de85787
                               at /rustc/c6db1ca3c93ad69692a4c4b5542f26fda4bf3aec/library/std/src/panicking.rs:518:19
  76:     0x7d7a50ce06e9 - std::panic::catch_unwind::h25ec556ee6ebf06d
                               at /rustc/c6db1ca3c93ad69692a4c4b5542f26fda4bf3aec/library/std/src/panic.rs:345:14
  77:     0x7d7a50ce06e9 - std::thread::Builder::spawn_unchecked_::{{closure}}::hb4fb26dff872af17
                               at /rustc/c6db1ca3c93ad69692a4c4b5542f26fda4bf3aec/library/std/src/thread/mod.rs:521:30
  78:     0x7d7a50ce06e9 - core::ops::function::FnOnce::call_once{{vtable.shim}}::h41308c32538c8d1e
                               at /rustc/c6db1ca3c93ad69692a4c4b5542f26fda4bf3aec/library/core/src/ops/function.rs:250:5
  79:     0x7d7a50f43d6b - <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once::ha832d324d85fb45d
                               at /rustc/c6db1ca3c93ad69692a4c4b5542f26fda4bf3aec/library/alloc/src/boxed.rs:2242:9
  80:     0x7d7a50f43d6b - <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once::hbc424539ef665b89
                               at /rustc/c6db1ca3c93ad69692a4c4b5542f26fda4bf3aec/library/alloc/src/boxed.rs:2242:9
  81:     0x7d7a50f43d6b - std::sys::pal::unix::thread::Thread::new::thread_start::h5575404a57e52770
                               at /rustc/c6db1ca3c93ad69692a4c4b5542f26fda4bf3aec/library/std/src/sys/pal/unix/thread.rs:105:17
  82:     0x7d7a51e44ac3 - start_thread
                               at ./nptl/pthread_create.c:442:8
  83:     0x7d7a51ed6850 - __GI___clone3
                               at ./misc/../sysdeps/unix/sysv/linux/x86_64/clone3.S:81
  84:                0x0 - <unknown>
```

</details>

After reverting 8cfedc8c0d (toolchain update) and recompiling, the example completes successfully.

```
pl.show_versions()
--------Version info---------
Polars:              1.5.0
Index type:          UInt32
Platform:            Linux-6.8.0-40-generic-x86_64-with-glibc2.35
Python:              3.10.14 | packaged by conda-forge | (main, Mar 20 2024, 12:45:18) [GCC 12.3.0]

----Optional dependencies----
adbc_driver_manager  1.1.0
altair               5.4.1
cloudpickle          3.0.0
connectorx           0.3.3
deltalake            0.19.1
fastexcel            0.11.6
fsspec               2024.6.1
gevent               24.2.1
great_tables         0.10.0
matplotlib           3.9.2
nest_asyncio         1.6.0
numpy                1.26.4
openpyxl             3.1.5
pandas               2.2.2
pyarrow              16.1.0
pydantic             2.8.2
pyiceberg            0.7.1
sqlalchemy           2.0.32
torch                2.4.0.post300
xlsx2csv             0.8.3
xlsxwriter           3.2.0
```

<details>
<summary> CPU info </summary>

```
processor       : 0
vendor_id       : GenuineIntel
cpu family      : 6
model           : 85
model name      : Intel(R) Xeon(R) Gold 6226R CPU @ 2.90GHz
stepping        : 7
microcode       : 0x5003707
cpu MHz         : 1199.954
cache size      : 22528 KB
physical id     : 0
siblings        : 32
core id         : 0
cpu cores       : 16
apicid          : 0
initial apicid  : 0
fpu             : yes
fpu_exception   : yes
cpuid level     : 22
wp              : yes
flags           : fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush dts acpi mmx fxsr sse sse2 ss ht tm pbe syscall nx pdpe1gb rdtscp lm constant_tsc art arch_perfmon pebs bts rep_good nopl xtopology nonstop_tsc cpuid aperfmperf pni pclmulqdq dtes64 monitor ds_cpl vmx smx est tm2 ssse3 sdbg fma cx16 xtpr pdcm pcid dca sse4_1 sse4_2 x2apic movbe popcnt tsc_deadline_timer aes xsave avx f16c rdrand lahf_lm abm 3dnowprefetch cpuid_fault epb cat_l3 cdp_l3 intel_ppin ssbd mba ibrs ibpb stibp ibrs_enhanced tpr_shadow flexpriority ept vpid ept_ad fsgsbase tsc_adjust bmi1 avx2 smep bmi2 erms invpcid cqm mpx rdt_a avx512f avx512dq rdseed adx smap clflushopt clwb intel_pt avx512cd avx512bw avx512vl xsaveopt xsavec xgetbv1 xsaves cqm_llc cqm_occup_llc cqm_mbm_total cqm_mbm_local dtherm ida arat pln pts hwp hwp_act_window hwp_epp hwp_pkg_req vnmi pku ospke avx512_vnni md_clear flush_l1d arch_capabilities
vmx flags       : vnmi preemption_timer posted_intr invvpid ept_x_only ept_ad ept_1gb flexpriority apicv tsc_offset vtpr mtf vapic ept vpid unrestricted_guest vapic_reg vid ple shadow_vmcs pml ept_mode_based_exec tsc_scaling
bugs            : spectre_v1 spectre_v2 spec_store_bypass swapgs taa itlb_multihit mmio_stale_data retbleed eibrs_pbrsb gds bhi
bogomips        : 5800.00
clflush size    : 64
cache_alignment : 64
address sizes   : 46 bits physical, 48 bits virtual
power management:
```

</details>

**Comment by orlp** [comment]
```rust
                                // soundness we can transmute because we have the same alignment
                                let has_any = std::mem::transmute::<
                                    Mask<_, SIMD_SIZE>,
                                    [bool; SIMD_SIZE],
                                >(has_any);
```

From https://github.com/pola-rs/polars/blob/d12131a8b56e58da68221edf872e7d8a3e73cfb6/crates/polars-io/src/csv/read/splitfields.rs#L289 looks... well, it's just unsound.

**Comment by orlp** [comment]
@wence- Could you try replacing this expression:

```rust
if has_any.any() {
    // soundness we can transmute because we have the same alignment
    let has_any = std::mem::transmute::<
        Mask<_, SIMD_SIZE>,
        [bool; SIMD_SIZE],
    >(has_any);
    total_idx += simple_argmax(&has_any);
    break;
} else {
    total_idx += SIMD_SIZE;
}
```
with

```rust
if let Some(idx) = has_any.first_set() {
    total_idx += idx;
    break;
} else {
    total_idx += SIMD_SIZE;
}
```

and see if it fixes the issue?

**Comment by orlp** [comment]
Testing locally it seems to fix it, sending PR.

**Comment by wence-** [comment]
Worked for me too, thanks.
