### ISSUE TITLE
Inconsistent construction between UInt16Type and UInt32/64Type

### ISSUE THREAD

**Issue by HarlanHeilman** [pola-rs/polars#18410]
### Checks

- [X] I have checked that this issue has not already been reported.
- [X] I have confirmed this bug exists on the [latest version](https://crates.io/crates/polars) of Polars.

### Reproducible example

```rust
use ndarray::{array, Array2, ArrayD, Axis, Ix2};
use polars::prelude::*;

fn main() {
    let array: Array2<u16> = array![[1, 2], [3, 4], [5, 6]];

    let mut chunked_builder = ListPrimitiveChunkedBuilder::<UInt16Type>::new(
        "",
        array.len_of(Axis(0)),
        array.len_of(Axis(1)),
        DataType::UInt16,
    );
    for row in array.axis_iter(Axis(0)) {
        match row.as_slice() {
            Some(row) => chunked_builder.append_slice(row),
            None => chunked_builder.append_slice(&row.to_vec()),
        }
    }
    let series = chunked_builder.finish().into_series();
    let df = DataFrame::new(vec![series]);
    println!("{:?}", df);
}
```

### Log output

```shell
thread 'main' panicked at C:\Users\hduva\.cargo\registry\src\index.crates.io-6f17d22bba15001f\polars-core-0.42.0\src\series\from.rs:134:18:
internal error: entered unreachable code
stack backtrace:
   0:     0x7ff619f65f2d - std::backtrace_rs::backtrace::dbghelp64::trace
                               at /rustc/3f5fd8dd41153bc5fdca9427e9e05be2c767ba23/library\std\src\..\..\backtrace\src\backtrace\dbghelp64.rs:91
   1:     0x7ff619f65f2d - std::backtrace_rs::backtrace::trace_unsynchronized
                               at /rustc/3f5fd8dd41153bc5fdca9427e9e05be2c767ba23/library\std\src\..\..\backtrace\src\backtrace\mod.rs:66
   2:     0x7ff619f65f2d - std::sys_common::backtrace::_print_fmt
                               at /rustc/3f5fd8dd41153bc5fdca9427e9e05be2c767ba23/library\std\src\sys_common\backtrace.rs:68
   3:     0x7ff619f65f2d - std::sys_common::backtrace::_print::impl$0::fmt
                               at /rustc/3f5fd8dd41153bc5fdca9427e9e05be2c767ba23/library\std\src\sys_common\backtrace.rs:44
   4:     0x7ff619f7ad59 - core::fmt::rt::Argument::fmt
                               at /rustc/3f5fd8dd41153bc5fdca9427e9e05be2c767ba23/library\core\src\fmt\rt.rs:165
   5:     0x7ff619f7ad59 - core::fmt::write
                               at /rustc/3f5fd8dd41153bc5fdca9427e9e05be2c767ba23/library\core\src\fmt\mod.rs:1168
   6:     0x7ff619f63cc1 - std::io::Write::write_fmt<std::sys::pal::windows::stdio::Stderr>
                               at /rustc/3f5fd8dd41153bc5fdca9427e9e05be2c767ba23/library\std\src\io\mod.rs:1835
   7:     0x7ff619f65d06 - std::sys_common::backtrace::print
                               at /rustc/3f5fd8dd41153bc5fdca9427e9e05be2c767ba23/library\std\src\sys_common\backtrace.rs:34
   8:     0x7ff619f676f8 - std::panicking::default_hook::closure$1
                               at /rustc/3f5fd8dd41153bc5fdca9427e9e05be2c767ba23/library\std\src\panicking.rs:271
   9:     0x7ff619f673a6 - std::panicking::default_hook
                               at /rustc/3f5fd8dd41153bc5fdca9427e9e05be2c767ba23/library\std\src\panicking.rs:298
  10:     0x7ff619f67c28 - std::panicking::rust_panic_with_hook
                               at /rustc/3f5fd8dd41153bc5fdca9427e9e05be2c767ba23/library\std\src\panicking.rs:795
  11:     0x7ff619f67aa9 - std::panicking::begin_panic_handler::closure$0
                               at /rustc/3f5fd8dd41153bc5fdca9427e9e05be2c767ba23/library\std\src\panicking.rs:656
  12:     0x7ff619f6661f - std::sys_common::backtrace::__rust_end_short_backtrace<std::panicking::begin_panic_handler::closure_env$0,never$>
                               at /rustc/3f5fd8dd41153bc5fdca9427e9e05be2c767ba23/library\std\src\sys_common\backtrace.rs:171
  13:     0x7ff619f67798 - std::panicking::begin_panic_handler
                               at /rustc/3f5fd8dd41153bc5fdca9427e9e05be2c767ba23/library\std\src\panicking.rs:652
  14:     0x7ff619f83c94 - core::panicking::panic_fmt
                               at /rustc/3f5fd8dd41153bc5fdca9427e9e05be2c767ba23/library\core\src\panicking.rs:72
  15:     0x7ff619f83d5d - core::panicking::panic
                               at /rustc/3f5fd8dd41153bc5fdca9427e9e05be2c767ba23/library\core\src\panicking.rs:146
  16:     0x7ff618e4f4b8 - polars_core::series::Series::from_chunks_and_dtype_unchecked
                               at C:\Users\hduva\.cargo\registry\src\index.crates.io-6f17d22bba15001f\polars-core-0.42.0\src\series\from.rs:134
  17:     0x7ff6194ef9a1 - polars_core::chunked_array::ops::any_value::arr_to_any_value
                               at C:\Users\hduva\.cargo\registry\src\index.crates.io-6f17d22bba15001f\polars-core-0.42.0\src\chunked_array\ops\any_value.rs:52
  18:     0x7ff618caae12 - polars_core::chunked_array::ops::any_value::impl$5::get_any_value_unchecked
                               at C:\Users\hduva\.cargo\registry\src\index.crates.io-6f17d22bba15001f\polars-core-0.42.0\src\chunked_array\ops\any_value.rs:200
  19:     0x7ff618caae6e - polars_core::chunked_array::ops::any_value::impl$5::get_any_value
                               at C:\Users\hduva\.cargo\registry\src\index.crates.io-6f17d22bba15001f\polars-core-0.42.0\src\chunked_array\ops\any_value.rs:211
  20:     0x7ff618e66edb - polars_core::series::implementations::list::impl$1::get
                               at C:\Users\hduva\.cargo\registry\src\index.crates.io-6f17d22bba15001f\polars-core-0.42.0\src\series\implementations\list.rs:138
  21:     0x7ff618e849c5 - polars_core::series::Series::str_value
                               at C:\Users\hduva\.cargo\registry\src\index.crates.io-6f17d22bba15001f\polars-core-0.42.0\src\series\mod.rs:794
  22:     0x7ff61944a3ad - polars_core::fmt::impl$8::fmt::closure$3
                               at C:\Users\hduva\.cargo\registry\src\index.crates.io-6f17d22bba15001f\polars-core-0.42.0\src\fmt.rs:649
  23:     0x7ff61956d337 - core::iter::adapters::map::map_fold::closure$0<ref$<polars_core::series::Series>,enum2$<alloc::borrow::Cow<str$> >,tuple$<>,polars_core::fmt::impl$8::fmt::closure_env$3,core::iter::traits::iterator::Iterator::for_each::call::closure_env$0<enum2$<alloc::bor
                               at /rustc/3f5fd8dd41153bc5fdca9427e9e05be2c767ba23\library\core\src\iter\adapters\map.rs:89
  24:     0x7ff61919779c - core::slice::iter::impl$182::fold<polars_core::series::Series,tuple$<>,core::iter::adapters::map::map_fold::closure_env$0<ref$<polars_core::series::Series>,enum2$<alloc::borrow::Cow<str$> >,tuple$<>,polars_core::fmt::impl$8::fmt::closure_env$3,core::iter::
                               at /rustc/3f5fd8dd41153bc5fdca9427e9e05be2c767ba23\library\core\src\slice\iter\macros.rs:230
  25:     0x7ff619516433 - core::iter::adapters::map::impl$2::fold<enum2$<alloc::borrow::Cow<str$> >,core::slice::iter::Iter<polars_core::series::Series>,polars_core::fmt::impl$8::fmt::closure_env$3,tuple$<>,core::iter::traits::iterator::Iterator::for_each::call::closure_env$0<enum2
                               at /rustc/3f5fd8dd41153bc5fdca9427e9e05be2c767ba23\library\core\src\iter\adapters\map.rs:129
  26:     0x7ff6195546f8 - core::iter::traits::iterator::Iterator::for_each<core::iter::adapters::map::Map<core::slice::iter::Iter<polars_core::series::Series>,polars_core::fmt::impl$8::fmt::closure_env$3>,alloc::vec::impl$20::extend_trusted::closure_env$0<enum2$<alloc::borrow::Cow<
                               at /rustc/3f5fd8dd41153bc5fdca9427e9e05be2c767ba23\library\core\src\iter\traits\iterator.rs:818
  27:     0x7ff6196bd4ca - alloc::vec::Vec<enum2$<alloc::borrow::Cow<str$> >,alloc::alloc::Global>::extend_trusted<enum2$<alloc::borrow::Cow<str$> >,alloc::alloc::Global,core::iter::adapters::map::Map<core::slice::iter::Iter<polars_core::series::Series>,polars_core::fmt::impl$8::fmt
                               at /rustc/3f5fd8dd41153bc5fdca9427e9e05be2c767ba23\library\alloc\src\vec\mod.rs:3096
  28:     0x7ff619709d8e - alloc::vec::spec_extend::impl$1::spec_extend<enum2$<alloc::borrow::Cow<str$> >,core::iter::adapters::map::Map<core::slice::iter::Iter<polars_core::series::Series>,polars_core::fmt::impl$8::fmt::closure_env$3>,alloc::alloc::Global>
                               at /rustc/3f5fd8dd41153bc5fdca9427e9e05be2c767ba23\library\alloc\src\vec\spec_extend.rs:26
  29:     0x7ff61966b50b - alloc::vec::spec_from_iter_nested::impl$1::from_iter<enum2$<alloc::borrow::Cow<str$> >,core::iter::adapters::map::Map<core::slice::iter::Iter<polars_core::series::Series>,polars_core::fmt::impl$8::fmt::closure_env$3> >
                               at /rustc/3f5fd8dd41153bc5fdca9427e9e05be2c767ba23\library\alloc\src\vec\spec_from_iter_nested.rs:62
  30:     0x7ff61970dc01 - alloc::vec::spec_from_iter::impl$0::from_iter<enum2$<alloc::borrow::Cow<str$> >,core::iter::adapters::map::Map<core::slice::iter::Iter<polars_core::series::Series>,polars_core::fmt::impl$8::fmt::closure_env$3> >
                               at /rustc/3f5fd8dd41153bc5fdca9427e9e05be2c767ba23\library\alloc\src\vec\spec_from_iter.rs:33
  31:     0x7ff619704fc7 - alloc::vec::impl$15::from_iter<enum2$<alloc::borrow::Cow<str$> >,core::iter::adapters::map::Map<core::slice::iter::Iter<polars_core::series::Series>,polars_core::fmt::impl$8::fmt::closure_env$3> >
                               at /rustc/3f5fd8dd41153bc5fdca9427e9e05be2c767ba23\library\alloc\src\vec\mod.rs:2970
  32:     0x7ff61954d421 - core::iter::traits::iterator::Iterator::collect<core::iter::adapters::map::Map<core::slice::iter::Iter<polars_core::series::Series>,polars_core::fmt::impl$8::fmt::closure_env$3>,alloc::vec::Vec<enum2$<alloc::borrow::Cow<str$> >,alloc::alloc::Global> >
                               at /rustc/3f5fd8dd41153bc5fdca9427e9e05be2c767ba23\library\core\src\iter\traits\iterator.rs:2005
  33:     0x7ff618e4219a - polars_core::fmt::impl$8::fmt
                               at C:\Users\hduva\.cargo\registry\src\index.crates.io-6f17d22bba15001f\polars-core-0.42.0\src\fmt.rs:646
  34:     0x7ff618e413a3 - polars_core::fmt::impl$7::fmt
                               at C:\Users\hduva\.cargo\registry\src\index.crates.io-6f17d22bba15001f\polars-core-0.42.0\src\fmt.rs:423
  35:     0x7ff618c475a6 - core::fmt::impl$51::fmt<polars_core::frame::DataFrame>
                               at /rustc/3f5fd8dd41153bc5fdca9427e9e05be2c767ba23\library\core\src\fmt\mod.rs:2354
  36:     0x7ff619f788ce - core::fmt::builders::impl$4::field::closure$0
                               at /rustc/3f5fd8dd41153bc5fdca9427e9e05be2c767ba23/library\core\src\fmt\builders.rs:330
  37:     0x7ff619f788ce - core::fmt::builders::impl$4::field_with::closure$0
                               at /rustc/3f5fd8dd41153bc5fdca9427e9e05be2c767ba23/library\core\src\fmt\builders.rs:355
  38:     0x7ff619f788ce - core::result::Result::and_then
                               at /rustc/3f5fd8dd41153bc5fdca9427e9e05be2c767ba23/library\core\src\result.rs:1346
  39:     0x7ff619f788ce - core::fmt::builders::DebugTuple::field_with
                               at /rustc/3f5fd8dd41153bc5fdca9427e9e05be2c767ba23/library\core\src\fmt\builders.rs:342
  40:     0x7ff619f788ce - core::fmt::builders::DebugTuple::field
                               at /rustc/3f5fd8dd41153bc5fdca9427e9e05be2c767ba23/library\core\src\fmt\builders.rs:330
  41:     0x7ff619f7be0c - core::fmt::Formatter::debug_tuple_field1_finish
                               at /rustc/3f5fd8dd41153bc5fdca9427e9e05be2c767ba23/library\core\src\fmt\mod.rs:2116
  42:     0x7ff618c423a9 - core::result::impl$36::fmt<polars_core::frame::DataFrame,enum2$<polars_error::PolarsError> >
                               at /rustc/3f5fd8dd41153bc5fdca9427e9e05be2c767ba23\library\core\src\result.rs:523
  43:     0x7ff619f7ad59 - core::fmt::rt::Argument::fmt
                               at /rustc/3f5fd8dd41153bc5fdca9427e9e05be2c767ba23/library\core\src\fmt\rt.rs:165
  44:     0x7ff619f7ad59 - core::fmt::write
                               at /rustc/3f5fd8dd41153bc5fdca9427e9e05be2c767ba23/library\core\src\fmt\mod.rs:1168
  45:     0x7ff619f62a49 - std::io::stdio::impl$16::write_fmt
                               at /rustc/3f5fd8dd41153bc5fdca9427e9e05be2c767ba23/library\std\src\io\stdio.rs:787
  46:     0x7ff619f63363 - std::io::stdio::_print
                               at /rustc/3f5fd8dd41153bc5fdca9427e9e05be2c767ba23/library\std\src\io\stdio.rs:1227
  47:     0x7ff618c41316 - pyref_ccd::main
                               at C:\Users\hduva\.projects\pyref\pyref-ccd\src\main.rs:139
  48:     0x7ff618c4259b - core::ops::function::FnOnce::call_once<void (*)(),tuple$<> >
                               at /rustc/3f5fd8dd41153bc5fdca9427e9e05be2c767ba23\library\core\src\ops\function.rs:250
  49:     0x7ff618c43cae - core::hint::black_box
                               at /rustc/3f5fd8dd41153bc5fdca9427e9e05be2c767ba23\library\core\src\hint.rs:338
  50:     0x7ff618c43cae - std::sys_common::backtrace::__rust_begin_short_backtrace<void (*)(),tuple$<> >
                               at /rustc/3f5fd8dd41153bc5fdca9427e9e05be2c767ba23\library\std\src\sys_common\backtrace.rs:155
  51:     0x7ff618c44491 - std::rt::lang_start::closure$0<tuple$<> >
                               at /rustc/3f5fd8dd41153bc5fdca9427e9e05be2c767ba23\library\std\src\rt.rs:159
  52:     0x7ff619f60d4e - std::rt::lang_start_internal
                               at /rustc/3f5fd8dd41153bc5fdca9427e9e05be2c767ba23/library\std\src\rt.rs:141
  53:     0x7ff618c4446a - std::rt::lang_start<tuple$<> >
                               at /rustc/3f5fd8dd41153bc5fdca9427e9e05be2c767ba23\library\std\src\rt.rs:158
  54:     0x7ff618c41519 - main
  55:     0x7ff619f81a9c - invoke_main
                               at D:\a\_work\1\s\src\vctools\crt\vcstartup\src\startup\exe_common.inl:78
  56:     0x7ff619f81a9c - __scrt_common_main_seh
                               at D:\a\_work\1\s\src\vctools\crt\vcstartup\src\startup\exe_common.inl:288
  57:     0x7ffaeb33257d - BaseThreadInitThunk
  58:     0x7ffaebb8af28 - RtlUserThreadStart
error: process didn't exit successfully: `target\debug\pyref_ccd.exe` (exit code: 101)
```

### Issue description

When trying to build a series from `ListPrimitiveChunkedBuilder::<UInt16Type>` I get a panic error that I do not get with the same setup using both Uint32 and UInt64 types. I am somewhat new to rust, so I am unfamiliar with more robust methods for trouble shooting this issue. 

### Expected behavior

Using UInt32Type constructors, I get
```
Ok(shape: (3, 1)
┌───────────┐
│           │
│ ---       │
│ list[u32] │
╞═══════════╡
│ [1, 2]    │
│ [3, 4]    │
│ [5, 6]    │
└───────────┘)
```

And Uint64Type I get
```
Ok(shape: (3, 1)
┌───────────┐
│           │
│ ---       │
│ list[u64] │
╞═══════════╡
│ [1, 2]    │
│ [3, 4]    │
│ [5, 6]    │
└───────────┘)
```

### Installed versions

<details>
[dependencies]
astrors = "0.1.8"
ndarray = "0.15.6"
polars = "0.42.0"
</details>

**Comment by ritchie46** [comment]
You must activate `dtype-u16.

**Comment by HarlanHeilman** [comment]
That fixed it...
