### ISSUE TITLE
unreachable code panic on invalid argument for unique

### ISSUE THREAD

**Issue by mdavis-xyz** [pola-rs/polars#18499]
### Checks

- [X] I have checked that this issue has not already been reported.
- [X] I have confirmed this bug exists on the [latest version](https://pypi.org/project/polars/) of Polars.

### Reproducible example

```python
import polars as pl

lf = pl.DataFrame(
    {
        "foo": [1, 2, 3, 1],
        "bar": ["a", "a", "a", "a"],
        "ham": ["b", "b", "b", "b"],
    }
)
cols = ['bar', 'ham']
lf.unique(subset=[cols])
```

### Log output

```shell
thread '<unnamed>' panicked at crates/polars-plan/src/plans/conversion/expr_expansion.rs:932:21:
internal error: entered unreachable code
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
Traceback (most recent call last):
  File "/home/azureuser/mwe.py", line 11, in <module>
    lf.unique(subset=[cols])
  File "/home/azureuser/venv/lib/python3.10/site-packages/polars/dataframe/frame.py", line 9687, in unique
    self.lazy()
  File "/home/azureuser/venv/lib/python3.10/site-packages/polars/lazyframe/frame.py", line 2034, in collect
    return wrap_df(ldf.collect(callback))
pyo3_runtime.PanicException: internal error: entered unreachable code
```

### Issue description

I mistakenly passed a list of list of column names to the `subset` argument. Obviously this is my fault. However my understanding is that even for invalid input, a panic is not the expected behavior. I expect this to be handled more gracefully.

### Expected behavior

A clear error message about the `subset` argument being invalid.

### Installed versions

<details>

```
--------Version info---------
Polars:              1.6.0
Index type:          UInt32
Platform:            Linux-6.5.0-1025-azure-x86_64-with-glibc2.35
Python:              3.10.12 (main, Jul 29 2024, 16:56:48) [GCC 11.4.0]

----Optional dependencies----
adbc_driver_manager  <not installed>
altair               <not installed>
cloudpickle          <not installed>
connectorx           <not installed>
deltalake            <not installed>
fastexcel            0.11.6
fsspec               <not installed>
gevent               <not installed>
great_tables         <not installed>
matplotlib           3.9.2
nest_asyncio         1.6.0
numpy                2.0.0
openpyxl             3.1.5
pandas               2.2.2
pyarrow              16.1.0
pydantic             <not installed>
pyiceberg            <not installed>
sqlalchemy           <not installed>
torch                <not installed>
xlsx2csv             0.8.3
xlsxwriter           3.2.0
```

</details>

**Comment by ritchie46** [comment]
@stinodego could you take a look at this one? This should ideally error at ir resolving and maybe on the python side as well.
