### ISSUE TITLE
Crash when using write_parquet

### ISSUE THREAD

**Issue by kirbykirby** [pola-rs/polars#18541]
### Checks

- [X] I have checked that this issue has not already been reported.
- [X] I have confirmed this bug exists on the [latest version](https://pypi.org/project/polars/) of Polars.

### Reproducible example

```python
import polars as pl

# `merged_data ` is a DataFrame with 100k rows and 24 columns
merged_data = pl.read_parquet(PARQUET_FILE_NEW, low_memory=True)
df_parquet = pl.read_parquet(PARQUET_FILE, low_memory=True)
df_updated = df_parquet.vstack(merged_data)
# `df_updated ` is a DataFrame with 12 million rows and 24 columns
df_updated .write_parquet("output.parquet", compression="zstd", compression_level=1)
```

### Issue description

I'm experiencing a crash when attempting to use the write_parquet function in Polars. Below are the details of my environment and the issue:
File size: ~660MB
Number of rows: 12 million
Available memory: 8GB
Function call: write_parquet
The process consistently crashes during the write operation. No error messages are displayed, the process simply crashes or the kernel gets killed, likely due to memory overload. I’ve checked that I have enough disk space and permissions in the target directory.

Observed Behavior:
After several crashes, the original content is missing, and the Parquet file size reduces to approximately 18MB.
Attempting to read the resulting Parquet file produces the following error:
`polars.exceptions.ComputeError: parquet: File out of specification: The file must end with PAR1`

Please advise on how to proceed or if there are any settings I should adjust to handle files of this size. Any guidance or recommendations would be greatly appreciated.

### Expected behavior

The dataframe is written normally into the parquet file.

### Installed versions

<details>

```
--------Version info---------
Polars: 1.6.0
Index type: UInt32
Platform: Linux-3.10.0-1160.92.1.el7.x86_64-x86_64-with-glibc2.28
Python: 3.11.8 (main, Apr 22 2024, 17:19:44) [GCC 4.8.5 20150623 (Red Hat 4.8.5-44)]

----Optional dependencies----
adbc_driver_manager <not installed>
altair <not installed>
cloudpickle <not installed>
connectorx <not installed>
deltalake <not installed>
fastexcel <not installed>
fsspec <not installed>
gevent <not installed>
great_tables <not installed>
matplotlib <not installed>
nest_asyncio <not installed>
numpy 2.0.1
openpyxl <not installed>
pandas <not installed>
pyarrow <not installed>
pydantic 2.8.2
pyiceberg <not installed>
sqlalchemy <not installed>
torch <not installed>
xlsx2csv 0.8.2
xlsxwriter <not installed>
```

</details>

**Comment by coastalwhite** [comment]
Is there any way you have a reproducible example or can share the files privately with me?

**Comment by kirbykirby** [comment]
> Is there any way you have a reproducible example or can share the files privately with me?

Thank you for your prompt reply! Unfortunately, I'm unable to share the file. I also haven't been able to reproduce the issue on my local machine, which have 32GB RAM—everything works fine there.

On my 8GB server, the crash is inconsistent and happens around 3 times out of 10 attempts. This makes it difficult to reliably reproduce the issue. Could you try reproducing the problem on a machine with limited memory using mock data? It might help isolate if the issue is related to memory constraints.

**Comment by kirbykirby** [comment]
> Is there any way you have a reproducible example or can share the files privately with me?

I wanted to share some additional information that might be relevant. I recently upgraded my Polars version from 1.2.1 to 1.6.0, and that's when the issue started occurring (It occurred sometimes in 1.2.1 but didn't break the parquet). I've also noticed another problem after the update: reading the parquet file used to take around 2.5 seconds, but now it takes approximately 35 seconds. This significant increase in read time might be related to the crashing issue.

**Comment by coastalwhite** [comment]
What kind of hardware on are you using? Windows, macOS or Linux? Is some sort of cloud platform involved?

**Comment by kirbykirby** [comment]
> What kind of hardware on are you using? Windows, macOS or Linux? Is some sort of cloud platform involved?

CPU: Intel(R) Xeon(R) Platinum 8255C CPU @ 2.50GHz * 1
RAM: 7725 MB 
System: Linux-3.10.0-1160.92.1.el7.x86_64-x86_64-with-glibc2.28
Cloud platform: Baota Panel & Tencentcloud

**Comment by felipe7710** [comment]
Any updates about this issue ? I've been facing a similar problem. 

```
Traceback (most recent call last):
File "/root/backend/etl/extraiPerfilCompras py", line 253, in extrai_perfil_compras
f_usuarios = [pl.read_parquet (arquivo) for arquivo in arquivos
os_temporarios _usuarios]

File "/usr/local/lib/python3.12/site-packages/polars/_utils/deprecation.py", line 92, in wrapper return function(*args, **kwargs)

File "/usr/local/lib/python3.12/site-packages/polars/_utils/deprecation.py", line 92, in wrapper
return function(*args, **kwargs)

File "/usr/local/lib/python3.12/site-packages/polars/io/parquet/functions.py", line 241, in read_parquet
return (lf.collect)

File "/us/local/lib/python3.12/site-packages/polars/lazyframe/frame.py", line 2050, in collect
return wrap_df(ldf.collect(callback))

polars.exceptions. ComputeError: parquet: File out of specification
: The file must end with PAR1
```

**Comment by Elkozel** [comment]
For people still encountering this bug, for me it was caused by reading an incomplete parquet file using the lazy variant of the function (`scan_parquet`).

I think the error message:
`polars.exceptions. ComputeError: parquet: File out of specification
: The file must end with PAR1`
points you not to the filename, but the contents of the file itself, which should end with the magic bytes 'PAR1' (please see file structure [reference here](https://parquet.apache.org/docs/file-format/))

My guess, `low_memory=True` tries to be somewhat lazy and that's why you encounter the issue when you write and not when you try to read the file.
