### ISSUE TITLE
PanicException on exploded DF that contains list of list of numpy vectors.

### ISSUE THREAD

**Issue by grochmal** [pola-rs/polars#18559]
### Checks

- [X] I have checked that this issue has not already been reported.
- [X] I have confirmed this bug exists on the [latest version](https://pypi.org/project/polars/) of Polars.

### Reproducible example

```python
import numpy as np
import polars as pl

products = [
    ["laptop", "phone", "mouse"],
    ["ilaptop", "iphone", "imouse", "mpad"],
    ["mlaptop", "keyboard", "mic", "cable", "horse"],
]
def vectors(l: list[str]) -> list[np.ndarray]:
    return [np.random.rand(4) for _ in l]

df = pl.DataFrame({
    "id": ["lemon", "apple", "banana"],
    "products": products,
    "vectors": [vectors(i) for i in products],
})

# the three prints
print(df.explode(["products", "vectors"])["vectors"].to_list())
print(df.explode(["products", "vectors"]).estimated_size())
print(df["vectors"])
```

### Log output

```shell
[array([0.53836089, 0.73640293, 0.66648706, 0.25082413]), array([0.04023722, 0.90108382, 0.87593587, 0.21914096]), array([0.46494288, 0.50821717, 0.56090915, 0.06540202]), array([0.60243753, 0.49072561, 0.39106541, 0.97637977]), array([0.65107802, 0.27636529, 0.73317087, 0.23689458]), array([0.41270381, 0.8242421 , 0.75047667, 0.54253147]), array([0.72657665, 0.51314263, 0.80467766, 0.394793  ]), array([0.00683539, 0.79962113, 0.81312836, 0.62125778]), array([0.41899141, 0.42908795, 0.13740306, 0.59357007]), array([0.89625532, 0.71713273, 0.50643356, 0.86430969]), array([0.54577223, 0.75553139, 0.81547158, 0.48368828]), array([0.08762268, 0.61182713, 0.23267549, 0.59560709])]
thread '<unnamed>' panicked at crates/polars-arrow/src/compute/aggregate/memory.rs:68:18:
called `Option::unwrap()` on a `None` value
stack backtrace:
   0: _rust_begin_unwind
   1: core::panicking::panic_fmt
   2: core::panicking::panic
   3: core::option::unwrap_failed
   4: polars_arrow::compute::aggregate::memory::estimated_bytes_size
   5: polars_core::series::Series::estimated_size
   6: polars_python::dataframe::general::<impl polars_python::dataframe::PyDataFrame>::__pymethod_estimated_size__
   7: pyo3::impl_::trampoline::trampoline
   8: polars_python::dataframe::general::_::__INVENTORY::trampoline
   9: _method_vectorcall_NOARGS
  10: _PyObject_Vectorcall
  11: __PyEval_EvalFrameDefault
  12: _PyEval_EvalCode
  13: _run_mod
  14: __PyRun_SimpleFileObject
  15: __PyRun_AnyFileObject
  16: _Py_RunMain
  17: _pymain_main
  18: _Py_BytesMain
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
Traceback (most recent call last):
  File "/Users/grochmal/thema/pl/z.py", line 20, in <module>
    print(df.explode(["products", "vectors"]).estimated_size())
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/grochmal/.pyenv/versions/pl/lib/python3.11/site-packages/polars/dataframe/frame.py", line 4304, in estimated_size
    sz = self._df.estimated_size()
         ^^^^^^^^^^^^^^^^^^^^^^^^^
pyo3_runtime.PanicException: called `Option::unwrap()` on a `None` value
```
```


### Issue description

I have been crashing against the inconsistent behaviour of `polars` over lists of `numpy` arrays.

The MVP code builds a polars DF that include a series of lists of numpy arrays.  And then the code perform three independent operations on it.  The three prints can be executed independently and they always behave in the same way. i.e. the order of the prints makes no different.

The first print explodes the DF over the list of lists and collects the resulting series into a list.  This behaviour works.

The second print attempts to take the size of the exploded DF.  And it fails.  Despite the fact that we can retrieve the data from within the DF.  This is likely related to https://github.com/pola-rs/polars/issues/4872

The third print attempts to retrieve the exact same data from the DF as the first print but without exploding the Df first.  And this attempt also crashes.

I can replicate with the code above on several versions of polars.  I'm on a MacOS.  Have not tried on Linux.

### Expected behavior

I expect all three calls to work.  Polars is able to treat the numpy vectors as simple object pointers - it wouldn't be bale to to the `.explode()` and `.to_list()` if it didn't treat the arrays as just object pointers and move them around.  The other tow calls (`estimated_size` and printing without exploding first) are doing something extra on the numpy arrays and failing.

### Installed versions

<details>

```
--------Version info---------
Polars:              1.6.0
Index type:          UInt32
Platform:            macOS-14.5-arm64-arm-64bit
Python:              3.11.9 (main, Apr 30 2024, 18:50:14) [Clang 15.0.0 (clang-1500.3.9.4)]

----Optional dependencies----
adbc_driver_manager  <not installed>
altair               <not installed>
cloudpickle          <not installed>
connectorx           <not installed>
deltalake            <not installed>
fastexcel            <not installed>
fsspec               <not installed>
gevent               <not installed>
great_tables         <not installed>
matplotlib           <not installed>
nest_asyncio         <not installed>
numpy                2.1.1
openpyxl             <not installed>
pandas               <not installed>
pyarrow              <not installed>
pydantic             <not installed>
pyiceberg            <not installed>
sqlalchemy           <not installed>
torch                <not installed>
xlsx2csv             <not installed>
xlsxwriter           <not installed>
```

</details>

**Comment by grochmal** [comment]
Interestingly enough the above `.estimated_size()` fails, but if i explode the vectors myself and add the exploded vectors to the exploded DF then `estimated_size` works:

```python
import numpy as np
import polars as pl

products = [
    ["laptop", "phone", "mouse"],
    ["ilaptop", "iphone", "imouse", "mpad"],
    ["mlaptop", "keyboard", "mic", "cable", "horse"],
]
def vectors(l: list[str]) -> list[np.ndarray]:
    return [np.random.rand(4) for _ in l]

df = pl.DataFrame({
    "id": ["lemon", "apple", "banana"],
    "products": products,
})
vectors = [vectors(i) for i in products]
exploded_vectors = [v for l in vectors for v in l]

df = df.explode(["products"])
df = df.with_columns(pl.Series("vectors", exploded_vectors))
df.estimated_size()
```

**Comment by coastalwhite** [comment]
No longer reproduces.
