### ISSUE TITLE
scan_ndjson fails with non-intuitive error message even though python can load files correctly

### ISSUE THREAD

**Issue by ShahBinoy** [pola-rs/polars#18575]
### Checks

- [X] I have checked that this issue has not already been reported.
- [X] I have confirmed this bug exists on the [latest version](https://pypi.org/project/polars/) of Polars.

### Reproducible example

```python
with open ('./fitbit_json_working.json') as j:
    print(json.load(j))
    
# Prints {'activities': ...}

with open ('./fitbit_json_not_working.json') as j:
    print(json.load(j))
    
# Prints {'activities': ...}

pl.scan_ndjson('./fitbit_json_working.json', include_file_paths='file_name').collect_schema()

# Prints 
# Schema([('activities',
#         ...,
#        ('goals'...,
#        ('summary',...)
pl.scan_ndjson('./fitbit_json_not_working.json', include_file_paths='file_name').collect_schema()
```
last call `pl.scan_ndjson('./fitbit_json_not_working.json', include_file_paths='file_name').collect_schema()` fails with the error as shown below

### Log output

```shell
Traceback (most recent call last):
  File "/Users/bshah/workspace/data-workflows/.venv/lib/python3.10/site-packages/IPython/core/interactiveshell.py", line 3577, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-22-001fc36f99b7>", line 1, in <module>
    pl.scan_ndjson('/Users/bshah/fitbit_json_not_working.json', include_file_paths='file_name').collect_schema()
  File "/Users/bshah/workspace/data-workflows/.venv/lib/python3.10/site-packages/polars/lazyframe/frame.py", line 2238, in collect_schema
    return Schema(self._ldf.collect_schema())
polars.exceptions.ComputeError: Syntax at character 0 ('{')
```

### Issue description

The below attached sample files are causing issue

[fitbit_json_files_working_and_non_working.zip](https://github.com/user-attachments/files/16898080/fitbit_json_files_working_and_non_working.zip)

The usage pattern is scanning JSON files from S3 via wild card patterns

`pl.scan_ndjson('s3://bucket/path/sub-path/*.json')`

Python's json.load reads both the attached files correctly as shown in code sample above

### Expected behavior

Ideally, the file should be loaded.

Similar issue in https://github.com/pola-rs/polars/issues/18535 talks about workarounds but that's not feasible for large scale data parsing. When trying to load 10000s of files natively it should work and not have to resort to slower read verification workarounds

### Installed versions

<details>

```
Polars Version 1.6.0
DuckDb Version 0.9.2
--------Version info---------
Polars:              1.6.0
Index type:          UInt32
Platform:            macOS-14.4.1-arm64-arm-64bit
Python:              3.10.14 (main, Mar 19 2024, 21:46:16) [Clang 15.0.0 (clang-1500.3.9.4)]

----Optional dependencies----
adbc_driver_manager  <not installed>
altair               <not installed>
cloudpickle          <not installed>
connectorx           0.3.3
deltalake            <not installed>
fastexcel            <not installed>
fsspec               2024.6.1
gevent               <not installed>
great_tables         <not installed>
matplotlib           <not installed>
nest_asyncio         1.6.0
numpy                1.26.4
openpyxl             <not installed>
pandas               1.5.3
pyarrow              17.0.0
pydantic             1.10.18
pyiceberg            <not installed>
sqlalchemy           1.4.53
torch                <not installed>
xlsx2csv             <not installed>
xlsxwriter           3.2.0

```

</details>

**Comment by cmdlineluser** [comment]
The failing file is not ndjson formatted:

```sh
$ head fitbit_json_not_working.json 
{
  "activities": [{
    "logId": 123456,
    "activityId": 1111,
    "activityParentId": 1111,
    "activityParentName": "Walk",
    "name": "Walk",
    "calories": 169,
    "distance": 1.014072,
```

Shouldn't the error be expected in this case?

**Comment by ShahBinoy** [comment]
> The failing file is not ndjson formatted:
> 
> ```shell
> $ head fitbit_json_not_working.json 
> {
>   "activities": [{
>     "logId": 123456,
>     "activityId": 1111,
>     "activityParentId": 1111,
>     "activityParentName": "Walk",
>     "name": "Walk",
>     "calories": 169,
>     "distance": 1.014072,
> ```
> 
> Shouldn't the error be expected in this case?

My python code in python console produces this output

```python

with open ('/Users/bshah/fitbit_json_not_working.json') as j:
    print(json.load(j))
```

Output

```json    
{'activities': [{'logId': 2521166786840660280, 'activityId': 90013, 'activityParentId': 90013, 'activityParentName': 'Walk', 'name': 'Walk', 'calories': 169, 'distance': 1.014072, 'steps': 2479, 'duration': 2092000, 'lastModified': '2024-09-03T19:39:33.404Z', 'startTime': '13:01:35', 'hasActiveZoneMinutes': True, 'startDate': '2024-09-03'}, {'logId': 6908945711972019568, 'activityId': 90013, 'activityParentId': 90013, 'activityParentName': 'Walk', 'name': 'Walk', 'calories': 336, 'distance': 1.284784, 'steps': 3367, 'duration': 3763000, 'lastModified': '2024-09-03T20:24:51.285Z', 'startTime': '15:09:46', 'hasActiveZoneMinutes': True, 'startDate': '2024-09-03'}, {'logId': 2610263429665978584, 'activityId': 90009, 'activityParentId': 90009, 'activityParentName': 'Run', 'name': 'Run', 'calories': 131, 'distance': 1.042307, 'steps': 2333, 'duration': 1174000, 'lastModified': '2024-09-03T22:36:41.781Z', 'startTime': '18:05:31', 'hasActiveZoneMinutes': True, 'startDate': '2024-09-03'}], 'summary': {'caloriesOut': 2587, 'activityCalories': 15134, 'caloriesBmr': 1415, 'activeScore': '-1', 'steps': 13809, 'floors': 16, 'elevation': 160.0, 'sedentaryMinutes': 334, 'lightlyActiveMinutes': 91, 'fairlyActiveMinutes': 23, 'veryActiveMinutes': 148, 'distances': [{'activity': 'total', 'distance': 5.813425}, {'activity': 'tracker', 'distance': 5.813425}, {'activity': 'sedentaryActive', 'distance': 0.000435}, {'activity': 'lightlyActive', 'distance': 0.512196}, {'activity': 'moderatelyActive', 'distance': 0.387798}, {'activity': 'veryActive', 'distance': 4.912996}, {'activity': 'loggedActivities', 'distance': 3.341163}, {'activity': 'Walk', 'distance': 1.014072}, {'activity': 'Walk', 'distance': 1.284784}, {'activity': 'Run', 'distance': 1.042307}], 'marginalCalories': 1107, 'heartRateZones': [], 'customHeartRateZones': []}, 'goals': {'caloriesOut': 2331, 'steps': 10000, 'distance': 8.05, 'floors': 10, 'activeMinutes': 30}}
```

**Comment by cmdlineluser** [comment]
Yes but they are general JSON parsers, i.e. the same as `pl.read_json`

`scan_ndjson` only works with ndjson formatted data.

**Comment by ShahBinoy** [comment]
> Yes but they are general JSON parsers, i.e. the same as `pl.read_json`
> 
> `scan_ndjson` only works with ndjson formatted data.

Yeah, you're write, it's not single line ndjson, misinterpreted it. Sorry for the confusion
