### ISSUE TITLE
`PanicException` occurs when applying a deserialized `rolling_quantile`

### ISSUE THREAD

**Issue by 3ok** [pola-rs/polars#18595]
### Checks

- [X] I have checked that this issue has not already been reported.
- [X] I have confirmed this bug exists on the [latest version](https://pypi.org/project/polars/) of Polars.

### Reproducible example

```python
import polars as pl

expr = pl.col("A").rolling_quantile(quantile=0.25, window_size=4)
expr_rt = pl.Expr.deserialize(expr.meta.serialize())

df = pl.DataFrame({"A": [1.0, 2.0, 3.0, 4.0, 5.0, 6.0]})
df.with_columns(rolling_quantile=expr)  # works
df.with_columns(rolling_quantile=expr_rt)  # panics
```

### Log output

```shell
$ POLARS_VERBOSE=1 python example.py 
thread '<unnamed>' panicked at /home/runner/work/polars/polars/crates/polars-arrow/src/legacy/kernels/rolling/no_nulls/quantile.rs:129:46:
called `Option::unwrap()` on a `None` value
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
Traceback (most recent call last):
  File "/home/redab/projects/polars-roundtrip/example.py", line 8, in <module>
    df.with_columns(rolling_quantile=expr_rt)  # panics
  File "/home/redab/projects/polars-roundtrip/venv/lib/python3.10/site-packages/polars/dataframe/frame.py", line 9046, in with_columns
    return self.lazy().with_columns(*exprs, **named_exprs).collect(_eager=True)
  File "/home/redab/projects/polars-roundtrip/venv/lib/python3.10/site-packages/polars/lazyframe/frame.py", line 2034, in collect
    return wrap_df(ldf.collect(callback))
pyo3_runtime.PanicException: called `Option::unwrap()` on a `None` value
```

### Issue description

When using the `rolling_quantile` method within a Polars expression and serializing/deserializing it, applying the deserialized expression causes a panic. The original expression works correctly when used directly, but after deserialization, it leads to a crash.

I noticed the issue for `rolling_quantile` and `rolling_quantile_by`. I did not notice it for similar `rolling_` methods such as `rolling_min` or `rolling_mean`.

### Expected behavior

The expected behaviour would be that
* `df.with_columns(rolling_quantile=expr_rt)` would not panic
* `df.with_columns(rolling_quantile=expr_rt)` would return the same result as `df.with_columns(rolling_quantile=expr)`

### Installed versions

<details>

```
--------Version info---------
Polars:              1.6.0
Index type:          UInt32
Platform:            Linux-5.15.153.1-microsoft-standard-WSL2-x86_64-with-glibc2.35
Python:              3.10.12 (main, Jul 29 2024, 16:56:48) [GCC 11.4.0]

----Optional dependencies----
adbc_driver_manager  <not installed>
altair               <not installed>
cloudpickle          <not installed>
connectorx           <not installed>
deltalake            <not installed>
fastexcel            <not installed>
fsspec               <not installed>
gevent               <not installed>
great_tables         <not installed>
matplotlib           <not installed>
nest_asyncio         <not installed>
numpy                <not installed>
openpyxl             <not installed>
pandas               <not installed>
pyarrow              <not installed>
pydantic             <not installed>
pyiceberg            <not installed>
sqlalchemy           <not installed>
torch                <not installed>
xlsx2csv             <not installed>
xlsxwriter           <not installed>
```

</details>

**Comment by 3ok** [comment]
I did a little bit of digging, and it seems that the `DynArgs` options of the `rolling_` expression is lost when serializing it as they're being skipped for [`RollingOptionsFixedWindow`](https://github.com/pola-rs/polars/blob/6037ca5a57ae8d50b659c1cfd5a18d0e3b5c0000/crates/polars-core/src/chunked_array/ops/rolling_window.rs#L17-L18) and [`RollingOptionsDynamicWindow`](https://github.com/pola-rs/polars/blob/6037ca5a57ae8d50b659c1cfd5a18d0e3b5c0000/crates/polars-time/src/chunkedarray/rolling_window/mod.rs#L24-L25).

This woud either lead to the `PanicException` like above, or [silently use default values](https://github.com/pola-rs/polars/blob/6037ca5a57ae8d50b659c1cfd5a18d0e3b5c0000/crates/polars-arrow/src/legacy/kernels/rolling/no_nulls/variance.rs#L105).
```python
import polars as pl

df = pl.DataFrame({"A": [1.0, 2.0, 3.0, 4.0, 5.0, 6.0]})

expr = pl.col("A").rolling_var(window_size=2, ddof=0)
expr_rt = pl.Expr.deserialize(expr.meta.serialize())

print(df.with_columns(rolling_var=expr))  # behaves normally
print(df.with_columns(rolling_var=expr_rt))  # behaves like ddof=1
```

**Comment by 3ok** [comment]
I've got some time this weekend and would like to take a dig at this issue and come up with some solution.
