### ISSUE TITLE
`test_delta_encoding_roundtrip` hypothesis test failure in CI

### ISSUE THREAD

**Issue by MarcoGorelli** [pola-rs/polars#18610]
```
You can add @seed(91691230697029663097472053918202727681) to this test or run pytest with --hypothesis-seed=91691230697029663097472053918202727681 to reproduce this failure.
```

traceback:

<details>

```
________________________ test_delta_encoding_roundtrip _________________________
[gw3] linux -- Python 3.12.5 /home/runner/work/polars/polars/py-polars/.venv/bin/python3
tests/unit/io/test_parquet.py:1435: in test_delta_encoding_roundtrip
    df=dataframes(
tests/unit/io/test_parquet.py:1465: in test_delta_encoding_roundtrip
    assert_frame_equal(pl.read_parquet(f), df)
polars/_utils/deprecation.py:91: in wrapper
    return function(*args, **kwargs)
polars/_utils/deprecation.py:91: in wrapper
    return function(*args, **kwargs)
polars/io/parquet/functions.py:170: in read_parquet
    return _read_parquet_binary(
polars/io/parquet/functions.py:257: in _read_parquet_binary
    pydf = PyDataFrame.read_parquet(
E   pyo3_runtime.PanicException: attempt to add with overflow
----------------------------- Captured stderr call -----------------------------
thread 'polars-3' panicked at crates/polars-parquet/src/arrow/read/deserialize/primitive/mod.rs:227:64:
attempt to add with overflow
stack backtrace:
   0: rust_begin_unwind
             at /rustc/c6db1ca3c93ad69692a4c4b5542f26fda4bf3aec/library/std/src/panicking.rs:662:5
   1: core::panicking::panic_fmt
             at /rustc/c6db1ca3c93ad69692a4c4b5542f26fda4bf3aec/library/core/src/panicking.rs:74:14
   2: core::panicking::panic_const::panic_const_add_overflow
             at /rustc/c6db1ca3c93ad69692a4c4b5542f26fda4bf3aec/library/core/src/panicking.rs:181:21
   3: <polars_parquet::arrow::read::deserialize::primitive::DeltaTranslator<P,T,D> as polars_parquet::parquet::encoding::delta_bitpacked::decoder::DeltaGatherer>::gather_constant::{{closure}}
   4: core::iter::adapters::map::map_fold::{{closure}}
   5: core::iter::traits::iterator::Iterator::fold
   6: <core::iter::adapters::map::Map<I,F> as core::iter::traits::iterator::Iterator>::fold
   7: core::iter::traits::iterator::Iterator::for_each
   8: alloc::vec::Vec<T,A>::extend_trusted
   9: <alloc::vec::Vec<T,A> as alloc::vec::spec_extend::SpecExtend<T,I>>::spec_extend
  10: <alloc::vec::Vec<T,A> as core::iter::traits::collect::Extend<T>>::extend
  11: <polars_parquet::arrow::read::deserialize::primitive::DeltaTranslator<P,T,D> as polars_parquet::parquet::encoding::delta_bitpacked::decoder::DeltaGatherer>::gather_constant
  12: polars_parquet::parquet::encoding::delta_bitpacked::decoder::Decoder::gather_miniblock_n_into
  13: polars_parquet::parquet::encoding::delta_bitpacked::decoder::Decoder::gather_block_n_into
  14: polars_parquet::parquet::encoding::delta_bitpacked::decoder::Decoder::gather_n_into
  15: <polars_parquet::arrow::read::deserialize::primitive::integer::StateTranslation<P> as polars_parquet::arrow::read::deserialize::utils::StateTranslation<polars_parquet::arrow::read::deserialize::primitive::integer::IntDecoder<P,T,D>>>::extend_from_state
  16: polars_parquet::arrow::read::deserialize::utils::State<D>::extend_from_state
  17: polars_parquet::arrow::read::deserialize::utils::NestedDecoder::push_n_valids
  18: <polars_parquet::arrow::read::deserialize::nested_utils::BatchedNestedDecoder<D> as polars_parquet::arrow::read::deserialize::utils::BatchableCollector<(),<D as polars_parquet::arrow::read::deserialize::utils::Decoder>::DecodedState>>::push_n
  19: polars_parquet::arrow::read::deserialize::utils::BatchedCollector<I,T,C>::skip_in_place
  20: polars_parquet::arrow::read::deserialize::nested_utils::extend_offsets2
  21: polars_parquet::arrow::read::deserialize::nested_utils::PageNestedDecoder<D>::collect_n
  22: polars_parquet::arrow::read::deserialize::nested::columns_to_iter_recursive
  23: polars_parquet::arrow::read::deserialize::nested::columns_to_iter_recursive
  24: polars_parquet::arrow::read::deserialize::columns_to_iter_recursive
  25: polars_parquet::arrow::read::deserialize::column_iter_to_arrays
  26: polars_io::parquet::read::mmap::to_deserializer
  27: polars_io::parquet::read::read_impl::column_idx_to_series
  28: polars_io::parquet::read::read_impl::rg_to_dfs_par_over_rg::{{closure}}::{{closure}}::{{closure}}
  29: core::iter::adapters::map::map_try_fold::{{closure}}
  30: core::iter::traits::iterator::Iterator::try_fold
  31: <core::iter::adapters::map::Map<I,F> as core::iter::traits::iterator::Iterator>::try_fold
  32: <core::iter::adapters::GenericShunt<I,R> as core::iter::traits::iterator::Iterator>::try_fold
  33: <core::iter::adapters::GenericShunt<I,R> as core::iter::traits::iterator::Iterator>::next
  34: alloc::vec::Vec<T,A>::extend_desugared
  35: <alloc::vec::Vec<T,A> as alloc::vec::spec_extend::SpecExtend<T,I>>::spec_extend
  36: <alloc::vec::Vec<T> as alloc::vec::spec_from_iter_nested::SpecFromIterNested<T,I>>::from_iter
  37: <alloc::vec::Vec<T> as alloc::vec::spec_from_iter::SpecFromIter<T,I>>::from_iter
  38: <alloc::vec::Vec<T> as core::iter::traits::collect::FromIterator<T>>::from_iter
  39: <core::result::Result<V,E> as core::iter::traits::collect::FromIterator<core::result::Result<A,E>>>::from_iter::{{closure}}
  40: core::iter::adapters::try_process
  41: <core::result::Result<V,E> as core::iter::traits::collect::FromIterator<core::result::Result<A,E>>>::from_iter
  42: core::iter::traits::iterator::Iterator::collect
  43: polars_io::parquet::read::read_impl::rg_to_dfs_par_over_rg::{{closure}}::{{closure}}
  44: core::ops::function::impls::<impl core::ops::function::FnMut<A> for &F>::call_mut
  45: core::ops::function::impls::<impl core::ops::function::FnOnce<A> for &mut F>::call_once
  46: <core::iter::adapters::map::Map<I,F> as core::iter::traits::iterator::Iterator>::next
  47: <core::iter::adapters::map::Map<I,F> as core::iter::traits::iterator::Iterator>::next
  48: <core::iter::adapters::take_while::TakeWhile<I,P> as core::iter::traits::iterator::Iterator>::next
  49: <core::iter::adapters::map::Map<I,F> as core::iter::traits::iterator::Iterator>::next
  50: alloc::vec::Vec<T,A>::extend_desugared
  51: <alloc::vec::Vec<T,A> as alloc::vec::spec_extend::SpecExtend<T,I>>::spec_extend
  52: <alloc::vec::Vec<T,A> as core::iter::traits::collect::Extend<T>>::extend
  53: <rayon::iter::extend::ListVecFolder<T> as rayon::iter::plumbing::Folder<T>>::consume_iter
  54: <rayon::iter::while_some::WhileSomeFolder<C> as rayon::iter::plumbing::Folder<core::option::Option<T>>>::consume_iter
  55: <rayon::iter::map::MapFolder<C,F> as rayon::iter::plumbing::Folder<T>>::consume_iter
  56: <rayon::iter::map::MapFolder<C,F> as rayon::iter::plumbing::Folder<T>>::consume_iter
  57: rayon::iter::plumbing::Producer::fold_with
  58: rayon::iter::plumbing::bridge_producer_consumer::helper
  59: rayon::iter::plumbing::bridge_producer_consumer::helper::{{closure}}
  60: rayon_core::join::join_context::call_b::{{closure}}
  61: rayon_core::job::StackJob<L,F,R>::run_inline
  62: rayon_core::join::join_context::{{closure}}
  63: rayon_core::registry::in_worker
  64: rayon_core::join::join_context
  65: rayon::iter::plumbing::bridge_producer_consumer::helper
  66: rayon::iter::plumbing::bridge_producer_consumer::helper::{{closure}}
  67: rayon_core::join::join_context::call_b::{{closure}}
  68: rayon_core::job::StackJob<L,F,R>::run_inline
  69: rayon_core::join::join_context::{{closure}}
  70: rayon_core::registry::in_worker
  71: rayon_core::join::join_context
  72: rayon::iter::plumbing::bridge_producer_consumer::helper
  73: rayon::iter::plumbing::bridge_producer_consumer::helper::{{closure}}
  74: rayon_core::join::join_context::call_a::{{closure}}
  75: <core::panic::unwind_safe::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once
  76: std::panicking::try::do_call
  77: __rust_try
  78: std::panic::catch_unwind
  79: rayon_core::unwind::halt_unwinding
  80: rayon_core::join::join_context::{{closure}}
  81: rayon_core::registry::in_worker
  82: rayon_core::join::join_context
  83: rayon::iter::plumbing::bridge_producer_consumer::helper
  84: rayon::iter::plumbing::bridge_producer_consumer::helper::{{closure}}
  85: rayon_core::join::join_context::call_a::{{closure}}
  86: <core::panic::unwind_safe::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once
  87: std::panicking::try::do_call
  88: __rust_try
  89: std::panic::catch_unwind
  90: rayon_core::unwind::halt_unwinding
  91: rayon_core::join::join_context::{{closure}}
  92: rayon_core::registry::in_worker
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
---------------------------------- Hypothesis ----------------------------------
You can add @seed(91691230697029663097472053918202727681) to this test or run pytest with --hypothesis-seed=91691230697029663097472053918202727681 to reproduce this failure.
=========================== short test summary info ============================
FAILED tests/unit/io/test_parquet.py::test_delta_encoding_roundtrip - pyo3_runtime.PanicException: attempt to add with overflow
====== 1 failed, 11493 passed, 10 skipped, 3 xfailed in 186.38s (0:03:06) ======
```

</details>

**Comment by coastalwhite** [comment]
I think this is solved now.
