### ISSUE TITLE
Thread Spawn Failure: Resource Temporarily Unavailable (ThreadPoolBuildError)

### ISSUE THREAD

**Issue by Qazalbash** [pola-rs/polars#18675]
### Checks

- [X] I have checked that this issue has not already been reported.
- [X] I have confirmed this bug exists on the [latest version](https://pypi.org/project/polars/) of Polars.

### Reproducible example

<details><summary>Truncated sample of data.dat file</summary>
<p>

```bash
mass_1_source mass_2_source a_1 a_2 tilt_1 tilt_2
5.741292275849664861e+01 3.276669747635708774e+01 5.615950800550530142e-02 2.140210076112010473e-01 9.386886485873165986e-01 8.930504175698152913e-01
5.016225892142769993e+01 3.053250157339956061e+01 4.281906140598081834e-01 1.097283456760532738e-01 9.436933289889515297e-01 9.578949784545613966e-01
1.421308222267335353e+01 1.299391939077209734e+01 1.442803893713876483e-02 3.104585238947892289e-01 9.713061187184875989e-01 9.180796262517419981e-01
4.873906355709093674e+01 3.289870244921134201e+01 2.364898112983717104e-01 6.711514954620453888e-02 9.782847679176990274e-01 9.425379949519497869e-01
4.222057753005867653e+01 4.119156207376207846e+01 1.281542351114389189e-01 2.223361212993785196e-01 9.743877873600730322e-01 9.630280591388334921e-01
5.166772828129342088e+01 3.421692286157028917e+01 3.032749053239199855e-01 1.550162486660218164e-01 9.249374499207445588e-01 9.193498301505464987e-01
4.834474896095586161e+01 4.735432919318556344e+01 3.307586196248250565e-01 5.434482623059791462e-02 9.194682508272545851e-01 8.980416007815310575e-01
4.977119956983534621e+01 3.478192957183769352e+01 1.432526366290803599e-01 1.306893053374038050e-01 8.512105826970803868e-01 9.950791416029125536e-01
4.718645618921284068e+01 3.259208988034968257e+01 1.008140552025805353e-01 1.885414981803884282e-01 9.302991607345961755e-01 9.897220682602798636e-01
1.297724747267267276e+01 1.251102329964831661e+01 1.342574772689990315e-01 1.754545834817100858e-01 9.360785255282010331e-01 7.859193976264957637e-01
4.272702335807608165e+01 2.854880621366392290e+01 7.548586391338718560e-02 2.066775082658865170e-01 9.570240853974614215e-01 8.483945711590230587e-01
3.335203614918445680e+01 2.045962246974452725e+01 1.354545707726979020e-01 2.087395637170897100e-01 9.210418030571686510e-01 8.474459645307487188e-01
5.495565434035877672e+01 3.001372424226803304e+01 7.211828914506566990e-02 1.333055374276583549e-01 9.763970370580589142e-01 9.409610251832803973e-01
4.802083731628692931e+01 2.704879768235590376e+01 2.564532228151157334e-01 2.255747231187134605e-01 9.552235495009359090e-01 9.341354921836863001e-01
```

</p>
</details> 

```python
import polars as pl

data = pl.read_csv("data.dat", has_header=True, separator=" ")[
    ["mass_1_source", "mass_2_source"]
].to_numpy()

print(data)
```

### Issue description

I am using polars on GPU clusters. We have in past encountered errors related to threads while using JAX. We were able to suppress them by using the following environment variables. I think polars is using multithreading to load data or for some internal functionality, is there a way we can suppress it or make it workable on the cluster?

```bash
#!/bin/bash

export NPROC=4
export intra_op_parallelism_threads=1
export TF_CPP_MIN_LOG_LEVEL=0
export OPENBLAS_NUM_THREADS=1
export XLA_PYTHON_CLIENT_ALLOCATOR=platform
export TF_FORCE_GPU_ALLOW_GROWTH=false
export CUDA_VISIBLE_DEVICES=2

# Comment to run on GPU
export JAX_PLATFORMS=cpu

# JAX Configuration
export JAX_COMPILATION_CACHE_DIR="/tmp/jax_cache"
```

```bash
thread 'thread '<unnamed>thread '<unnamed>' panicked at thread '<unnamed>' panicked at crates/polars-core/src/lib.rs<unnamed>' panicked at crates/polars-core/src/lib.rs:' panicked at crates/polars-core/src/lib.rs:64crates/polars-core/src/lib.rs:64::64:1064:10:
:10:
could not spawn threads: ThreadPoolBuildError { kind: IOError(Os { code: 11, kind: WouldBlock, message: "Resource temporarily unavailable" }) }10:
could not spawn threads: ThreadPoolBuildError { kind: IOError(Os { code: 11, kind: WouldBlock, message: "Resource temporarily unavailable" }) }
:
could not spawn threads: ThreadPoolBuildError { kind: IOError(Os { code: 11, kind: WouldBlock, message: "Resource temporarily unavailable" }) }
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
could not spawn threads: ThreadPoolBuildError { kind: IOError(Os { code: 11, kind: WouldBlock, message: "Resource temporarily unavailable" }) }
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
Traceback (most recent call last):
Traceback (most recent call last):
Traceback (most recent call last):
  File "/home/muhammad.zeeshan/.conda/envs/kvenv/bin/gwk_scatter2d", line 8, in <module>
  File "/home/muhammad.zeeshan/.conda/envs/kvenv/bin/gwk_batch_scatter2d", line 8, in <module>
  File "/home/muhammad.zeeshan/.conda/envs/kvenv/bin/gwk_batch_scatter2d", line 8, in <module>
Traceback (most recent call last):
  File "/home/muhammad.zeeshan/.conda/envs/kvenv/bin/gwk_scatter2d", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/home/muhammad.zeeshan/.conda/envs/kvenv/lib/python3.11/site-packages/gwkokab/_src/scripts/scatter2d.py", line 93, in main
    sys.exit(main())
             ^^^^^^
    sys.exit(main())
  File "/home/muhammad.zeeshan/.conda/envs/kvenv/lib/python3.11/site-packages/gwkokab/_src/scripts/batch_scatter2d.py", line 118, in main
             ^^^^^^
  File "/home/muhammad.zeeshan/.conda/envs/kvenv/lib/python3.11/site-packages/gwkokab/_src/scripts/batch_scatter2d.py", line 118, in main
    sys.exit(main())
             ^^^^^^
  File "/home/muhammad.zeeshan/.conda/envs/kvenv/lib/python3.11/site-packages/gwkokab/_src/scripts/scatter2d.py", line 93, in main
    data = pl.read_csv(file_path, has_header=True, separator=" ")
    data = pl.read_csv(file_path, has_header=True, separator=" ")
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/muhammad.zeeshan/.conda/envs/kvenv/lib/python3.11/site-packages/polars/_utils/deprecation.py", line 91, in wrapper
  File "/home/muhammad.zeeshan/.conda/envs/kvenv/lib/python3.11/site-packages/polars/_utils/deprecation.py", line 91, in wrapper
    return function(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/muhammad.zeeshan/.conda/envs/kvenv/lib/python3.11/site-packages/polars/_utils/deprecation.py", line 91, in wrapper
    return function(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/muhammad.zeeshan/.conda/envs/kvenv/lib/python3.11/site-packages/polars/_utils/deprecation.py", line 91, in wrapper
    return function(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/muhammad.zeeshan/.conda/envs/kvenv/lib/python3.11/site-packages/polars/_utils/deprecation.py", line 91, in wrapper
    return function(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/muhammad.zeeshan/.conda/envs/kvenv/lib/python3.11/site-packages/polars/_utils/deprecation.py", line 91, in wrapper
    return function(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
    return function(*args, **kwargs)
  File "/home/muhammad.zeeshan/.conda/envs/kvenv/lib/python3.11/site-packages/polars/io/csv/functions.py", line 496, in read_csv
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/muhammad.zeeshan/.conda/envs/kvenv/lib/python3.11/site-packages/polars/io/csv/functions.py", line 496, in read_csv
    df = _read_csv_impl(
    df = _read_csv_impl(
         ^^^^^^^^^^^^^^^
         ^^^^^^^^^^^^^^^
  File "/home/muhammad.zeeshan/.conda/envs/kvenv/lib/python3.11/site-packages/polars/io/csv/functions.py", line 642, in _read_csv_impl
  File "/home/muhammad.zeeshan/.conda/envs/kvenv/lib/python3.11/site-packages/polars/io/csv/functions.py", line 642, in _read_csv_impl
    pydf = PyDataFrame.read_csv(
    pydf = PyDataFrame.read_csv(
           ^^^^^^^^^^^^^^^^^^^^^
           ^^^^^^^^^^^^^^^^^^^^^
pyo3_runtime.PanicException: could not spawn threads: ThreadPoolBuildError { kind: IOError(Os { code: 11, kind: WouldBlock, message: "Resource temporarily unavailable" }) }
pyo3_runtime.PanicException: could not spawn threads: ThreadPoolBuildError { kind: IOError(Os { code: 11, kind: WouldBlock, message: "Resource temporarily unavailable" }) }
    data = pl.read_csv(args.data.name, has_header=True, separator=" ")
    data = pl.read_csv(args.data.name, has_header=True, separator=" ")
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/muhammad.zeeshan/.conda/envs/kvenv/lib/python3.11/site-packages/polars/_utils/deprecation.py", line 91, in wrapper
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/muhammad.zeeshan/.conda/envs/kvenv/lib/python3.11/site-packages/polars/_utils/deprecation.py", line 91, in wrapper
    return function(*args, **kwargs)
    return function(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/muhammad.zeeshan/.conda/envs/kvenv/lib/python3.11/site-packages/polars/_utils/deprecation.py", line 91, in wrapper
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/muhammad.zeeshan/.conda/envs/kvenv/lib/python3.11/site-packages/polars/_utils/deprecation.py", line 91, in wrapper
    return function(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/muhammad.zeeshan/.conda/envs/kvenv/lib/python3.11/site-packages/polars/_utils/deprecation.py", line 91, in wrapper
    return function(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/muhammad.zeeshan/.conda/envs/kvenv/lib/python3.11/site-packages/polars/_utils/deprecation.py", line 91, in wrapper
    return function(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/muhammad.zeeshan/.conda/envs/kvenv/lib/python3.11/site-packages/polars/io/csv/functions.py", line 496, in read_csv
    return function(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/muhammad.zeeshan/.conda/envs/kvenv/lib/python3.11/site-packages/polars/io/csv/functions.py", line 496, in read_csv
    df = _read_csv_impl(
         ^^^^^^^^^^^^^^^
  File "/home/muhammad.zeeshan/.conda/envs/kvenv/lib/python3.11/site-packages/polars/io/csv/functions.py", line 642, in _read_csv_impl
    df = _read_csv_impl(
         ^^^^^^^^^^^^^^^
  File "/home/muhammad.zeeshan/.conda/envs/kvenv/lib/python3.11/site-packages/polars/io/csv/functions.py", line 642, in _read_csv_impl
    pydf = PyDataFrame.read_csv(
           ^^^^^^^^^^^^^^^^^^^^^
pyo3_runtime.PanicException: could not spawn threads: ThreadPoolBuildError { kind: IOError(Os { code: 11, kind: WouldBlock, message: "Resource temporarily unavailable" }) }
    pydf = PyDataFrame.read_csv(
           ^^^^^^^^^^^^^^^^^^^^^
pyo3_runtime.PanicException: could not spawn threads: ThreadPoolBuildError { kind: IOError(Os { code: 11, kind: WouldBlock, message: "Resource temporarily unavailable" }) }
```

### Expected behavior

It should print.

```bash
[[57.41292276 32.76669748]
 [50.16225892 30.53250157]
 [14.21308222 12.99391939]
 [48.73906356 32.89870245]
 [42.22057753 41.19156207]
 [51.66772828 34.21692286]
 [48.34474896 47.35432919]
 [49.77119957 34.78192957]
 [47.18645619 32.59208988]
 [12.97724747 12.5110233 ]
 [42.72702336 28.54880621]
 [33.35203615 20.45962247]
 [54.95565434 30.01372424]
 [48.02083732 27.04879768]]
```

### Installed versions

<details>

```
--------Version info---------
Polars:               1.5.0
Index type:           UInt32
Platform:             Linux-6.1.0-22-amd64-x86_64-with-glibc2.36
Python:               3.10.14 | packaged by conda-forge | (main, Mar 20 2024, 12:45:18) [GCC 12.3.0]

----Optional dependencies----
adbc_driver_manager:  <not installed>
cloudpickle:          3.0.0
connectorx:           <not installed>
deltalake:            <not installed>
fastexcel:            <not installed>
fsspec:               2024.9.0
gevent:               <not installed>
great_tables:         <not installed>
hvplot:               <not installed>
matplotlib:           3.9.2
nest_asyncio:         1.6.0
numpy:                2.1.1
openpyxl:             3.1.5
pandas:               2.2.2
pyarrow:              <not installed>
pydantic:             2.7.1
pyiceberg:            <not installed>
sqlalchemy:           <not installed>
torch:                <not installed>
xlsx2csv:             <not installed>
xlsxwriter:           <not installed>
```

</details>

**Comment by ritchie46** [comment]
> I think polars is using multithreading to load data or for some internal functionality, is there a way we can suppress it or make it workable on the cluster?

Polars is a multithreaded library. The cluster needs to allow mulithreading for Polars to run.
