### ISSUE TITLE
[1.7.0 Regression] Lit with a list creates a series of one element, thus with_columns fails.

### ISSUE THREAD

**Issue by TinoSM** [pola-rs/polars#18686]
### Checks

- [X] I have checked that this issue has not already been reported.
- [X] I have confirmed this bug exists on the [latest version](https://pypi.org/project/polars/) of Polars.

### Reproducible example

```python

import polars as pl 
df = pl.DataFrame({
    "column1": [1, 2],
    "column2": ["A", "B"]
})
output_df = df.with_columns(
        [
            # pl.lit([]).cast(pl.List(pl.String)).first().alias("whatever"), # this works but seems counter-intuitive to me?
            pl.lit([]).cast(pl.List(pl.String)).alias("whatever"),
            pl.lit([]).alias("this_also_breaks")
  ])

```

### Log output

```shell
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/.../lib/python3.11/site-packages/polars/dataframe/frame.py", line 9141, in with_columns
    return self.lazy().with_columns(*exprs, **named_exprs).collect(_eager=True)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/.../.venv/lib/python3.11/site-packages/polars/lazyframe/frame.py", line 2034, in collect
    return wrap_df(ldf.collect(callback))
                   ^^^^^^^^^^^^^^^^^^^^^
polars.exceptions.InvalidOperationError: Series whatever, length 1 doesn't match the DataFrame height of 2

If you want this Series to be broadcasted, ensure it is a scalar (for instance by adding '.first()').
```

### Issue description

Adding a new column with an empty list for each registry is not working/doesn't seem natural in 1.7.0 IMO, it tries to add a Series of length 1 to the dataframe thus fails, in 1.6.0 it added the column correctly.

Also, calling first() on my empty list returns yet another list (??)

Is this expected? (i.e. me having to call first())?

### Expected behavior

A column with empty list for each row is added.

### Installed versions

<details>

```

>>> pl.show_versions()
--------Version info---------
Polars:              1.7.0
Index type:          UInt32
Platform:            macOS-14.6.1-arm64-arm-64bit
Python:              3.11.9 (main, Apr  2 2024, 08:25:04) [Clang 15.0.0 (clang-1500.3.9.4)]

----Optional dependencies----
adbc_driver_manager  <not installed>
altair               5.4.1
cloudpickle          <not installed>
connectorx           <not installed>
deltalake            0.19.1
fastexcel            <not installed>
fsspec               2024.9.0
gevent               <not installed>
great_tables         <not installed>
matplotlib           <not installed>
nest_asyncio         <not installed>
numpy                1.26.4
openpyxl             <not installed>
pandas               2.2.2
pyarrow              17.0.0
pydantic             2.9.1
pyiceberg            <not installed>
sqlalchemy           <not installed>
torch                <not installed>
xlsx2csv             <not installed>
xlsxwriter           <not installed>
```

</details>

**Comment by ritchie46** [comment]
A `lit` with a `Series` isn't a scalar it is a column, so you get a shapemismatch. However, I see there is a bug in `lit` that we cannot create a `List` scalar yet, so we must address that.

**Comment by cmitchelltudor** [comment]
Having a similar issue

**Comment by barak1412** [comment]
@ritchie46 
I saw this:
```rust
pub fn is_scalar(&self) -> bool {
    !matches!(self, LiteralValue::Series(_) | LiteralValue::Range { .. })
}
```

Why it is not simple as remove the `LiteralValue::Series(_)`? I mean, in what case it's not considered scalar?

**Comment by ritchie46** [comment]
Because a `Series` is an added column, not a scalar.

E.g. why should 

```python
(
   pl.DataFrame({"a": [1, 2, 3]})
   .with_columns(
      pl.lit(Series([1, 2])
   )
)

```

raise and a `Series` of length `1`, not. Both don't match the shape of the `DataFrame`.

**Comment by TinoSM** [comment]
thanks!
