### ISSUE TITLE
scan_csv does not work with IO[bytes]

### ISSUE THREAD

**Issue by NobodyXu** [pola-rs/polars#18684]
### Checks

- [X] I have checked that this issue has not already been reported.
- [X] I have confirmed this bug exists on the [latest version](https://pypi.org/project/polars/) of Polars.

### Reproducible example

```python
import polars as pl
import io

pl.scan_csv(io.BytesIO(b"sdc")).collect(streaming=True)
```

### Log output

```shell
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/nobodyxu/Library/Python/3.12/lib/python/site-packages/polars/lazyframe/frame.py", line 2034, in collect
    return wrap_df(ldf.collect(callback))
                   ^^^^^^^^^^^^^^^^^^^^^
polars.exceptions.ComputeError: not yet implemented: Streaming scanning of in-memory buffers
```

### Issue description

https://github.com/pola-rs/polars/releases/tag/py-1.7.0 says pl.scan_csv now supports IO[bytes], however when I try to pass one it doesn't work.

### Expected behavior

Should not thorw unsupported exception

### Installed versions

<details>

```
--------Version info---------
Polars:              1.7.0
Index type:          UInt32
Platform:            macOS-14.6.1-arm64-arm-64bit
Python:              3.12.6 (main, Sep  6 2024, 19:03:47) [Clang 15.0.0 (clang-1500.3.9.4)]

----Optional dependencies----
adbc_driver_manager  <not installed>
altair               5.4.1
cloudpickle          <not installed>
connectorx           <not installed>
deltalake            <not installed>
fastexcel            <not installed>
fsspec               <not installed>
gevent               <not installed>
great_tables         <not installed>
matplotlib           <not installed>
nest_asyncio         <not installed>
numpy                2.1.1
openpyxl             <not installed>
pandas               2.2.2
pyarrow              17.0.0
pydantic             <not installed>
pyiceberg            <not installed>
sqlalchemy           <not installed>
torch                <not installed>
xlsx2csv             <not installed>
xlsxwriter           <not installed>
```

</details>

**Comment by NobodyXu** [comment]
Thanks!

Is there any issue I can subscribe to?

**Comment by coastalwhite** [comment]
Solved now
