### ISSUE TITLE
`read_csv` PanicException when `pl.Decimal` used in schema with invalid precision

### ISSUE THREAD

**Issue by cmdlineluser** [pola-rs/polars#18812]
### Checks

- [X] I have checked that this issue has not already been reported.
- [X] I have confirmed this bug exists on the [latest version](https://pypi.org/project/polars/) of Polars.

### Reproducible example

```python
import polars as pl

pl.read_csv(b"a,b\n1,2", schema_overrides={"b": pl.Decimal(39)})
# thread 'polars-0' panicked at crates/polars-core/src/datatypes/dtype.rs:545:41:
# called `Result::unwrap()` on an `Err` value: InvalidOperation(ErrString("decimal precision should be <= 38 & >= 1"))
# PanicException: called `Result::unwrap()` on an `Err` value: InvalidOperation(ErrString("decimal precision should be <= 38 & >= 1"))
```

### Issue description

Just a panic instead of raising the underlying error.

### Expected behavior

InvalidOperationError

### Installed versions

<details>

```
--------Version info---------
Polars:               1.7.1
Index type:           UInt32
Platform:             macOS-13.6.1-arm64-arm-64bit
Python:               3.12.2 (main, Feb  6 2024, 20:19:44) [Clang 15.0.0 (clang-1500.1.0.2.5)]

----Optional dependencies----
adbc_driver_manager:  <not installed>
cloudpickle:          <not installed>
connectorx:           <not installed>
deltalake:            <not installed>
fastexcel:            <not installed>
fsspec:               <not installed>
gevent:               <not installed>
great_tables:         <not installed>
hvplot:               <not installed>
matplotlib:           <not installed>
nest_asyncio:         <not installed>
numpy:                1.26.4
openpyxl:             <not installed>
pandas:               2.2.1
pyarrow:              15.0.2
pydantic:             <not installed>
pyiceberg:            <not installed>
sqlalchemy:           <not installed>
torch:                <not installed>
xlsx2csv:             <not installed>
xlsxwriter:           <not installed>
```

</details>

**Comment by rodrigogiraoserrao** [comment]
Looks related: when specifying a `Decimal` dtype with a scale that is too large, I also get a panic error:

```py
pl.Series([2.5], dtype=pl.Decimal(scale=100))
```
```
thread '<unnamed>' panicked at crates/polars-arrow/src/compute/cast/primitive_to.rs:236:49:
called `Option::unwrap()` on a `None` value
-- python traceback --
PanicException: called `Option::unwrap()` on a `None` value
```

**Comment by cmdlineluser** [comment]
These no longer panic.

```python
pl.read_csv(b"a,b\n1,2", schema_overrides={"b": pl.Decimal(39)})
# shape: (1, 2)
# ┌─────┬───────────────┐
# │ a   ┆ b             │
# │ --- ┆ ---           │
# │ i64 ┆ decimal[39,0] │
# ╞═════╪═══════════════╡
# │ 1   ┆ 2             │
# └─────┴───────────────┘
```
```python
pl.Series([2.5], dtype=pl.Decimal(scale=100))
# InvalidOperationError: conversion from `f64` to `decimal[*,100]` failed in column '' for 1 out of 1 values: [2.5]
```
