### ISSUE TITLE
`read_csv` raises ComputeError when filename contains "["

### ISSUE THREAD

**Issue by hirohira9119** [pola-rs/polars#18826]
### Checks

- [X] I have checked that this issue has not already been reported.
- [X] I have confirmed this bug exists on the [latest version](https://pypi.org/project/polars/) of Polars.

### Reproducible example

```python
import polars as pl

pl.read_csv("[a.csv") # -> ComputeError: invalid glob pattern given

pl.read_csv("[a].csv") # -> ComputeError: expected at least 1 source (traceback is same as "[a.csv")

# pl.read_csv("a].csv") # -> OK
```

### Log output

```shell
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "~\AppData\Roaming\Python\Python312\site-packages\polars\_utils\deprecation.py", line 91, in wrapper
    return function(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "~\Roaming\Python\Python312\site-packages\polars\_utils\deprecation.py", line 91, in wrapper
    return function(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "~\AppData\Roaming\Python\Python312\site-packages\polars\_utils\deprecation.py", line 91, in wrapper
    return function(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "~\AppData\Roaming\Python\Python312\site-packages\polars\io\csv\functions.py", line 499, in read_csv
    df = _read_csv_impl(
         ^^^^^^^^^^^^^^^
  File "~\AppData\Roaming\Python\Python312\site-packages\polars\io\csv\functions.py", line 633, in _read_csv_impl    
    return scan.collect()
           ^^^^^^^^^^^^^^
  File "~\AppData\Roaming\Python\Python312\site-packages\polars\lazyframe\frame.py", line 2032, in collect
    return wrap_df(ldf.collect(callback))
                   ^^^^^^^^^^^^^^^^^^^^^
polars.exceptions.ComputeError: invalid glob pattern given
```

### Issue description

It occurs whether the file exists or not.

### Expected behavior

No exception. Or if this behavior is due to constraints related to glob and is working as intended, I believe it should be documented.

### Installed versions

<details>

```
--------Version info---------
Polars:              1.7.1
Index type:          UInt32
Platform:            Windows-11-10.0.22631-SP0
Python:              3.12.5 (tags/v3.12.5:ff3bc82, Aug  6 2024, 20:45:27) [MSC v.1940 64 bit (AMD64)]

----Optional dependencies----
adbc_driver_manager  <not installed>
altair               <not installed>
cloudpickle          <not installed>
connectorx           <not installed>
deltalake            <not installed>
fastexcel            <not installed>
fsspec               <not installed>
gevent               <not installed>
great_tables         <not installed>
matplotlib           3.9.0
nest_asyncio         1.6.0
numpy                2.0.0
openpyxl             <not installed>
pandas               2.2.2
pyarrow              <not installed>
pydantic             <not installed>
pyiceberg            <not installed>
sqlalchemy           <not installed>
torch                <not installed>
xlsx2csv             <not installed>
xlsxwriter           <not installed>
```

</details>

**Comment by hirohira9119** [comment]
I noticed that adding `glob=False` resolves the issue, so I’m closing this.
