### ISSUE TITLE
Panicking with "Unreachable code" when passing a DataFrame into `DataFrame.drop`

### ISSUE THREAD

**Issue by LeandroVandari** [pola-rs/polars#18837]
### Checks

- [X] I have checked that this issue has not already been reported.
- [X] I have confirmed this bug exists on the [latest version](https://pypi.org/project/polars/) of Polars.

### Reproducible example

```python
import polars as pl
data = pl.DataFrame({"SomeColumn": [0]})
data.drop(pl.DataFrame({"Anything": [1]}))
```

### Log output

```shell
thread '<unnamed>' panicked at crates/polars-plan/src/plans/conversion/expr_expansion.rs:932:21:
internal error: entered unreachable code
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
Traceback (most recent call last):
  File "/tmp/bug.py", line 5, in <module>
    data.drop(pl.DataFrame({"Anything": [1]}))
  File "/home/leandro_vandari/.local/lib/python3.10/site-packages/polars/dataframe/frame.py", line 7434, in drop
    return self.lazy().drop(*columns, strict=strict).collect(_eager=True)
  File "/home/leandro_vandari/.local/lib/python3.10/site-packages/polars/lazyframe/frame.py", line 2034, in collect
    return wrap_df(ldf.collect(callback))
pyo3_runtime.PanicException: internal error: entered unreachable code
```

### Issue description

Whenever passing any `DataFrame` to the [`DataFrame.drop`](https://docs.pola.rs/api/python/stable/reference/dataframe/api/polars.DataFrame.drop.html) function, polars panics with an unreachable code entered error.

### Expected behavior

A panic with a message specifying that `drop` cannot take in `DataFrame`s as arguments. `unreachable!()`s shouldn't be reachable.

### Installed versions

<details>

```
--------Version info---------
Polars:              1.6.0
Index type:          UInt32
Platform:            Linux-6.8.0-40-generic-x86_64-with-glibc2.39
Python:              3.10.12 (main, Jul 29 2024, 16:56:48) [GCC 11.4.0]

----Optional dependencies----
adbc_driver_manager  <not installed>
altair               5.4.1
cloudpickle          <not installed>
connectorx           <not installed>
deltalake            <not installed>
fastexcel            0.11.6
fsspec               <not installed>
gevent               <not installed>
great_tables         <not installed>
matplotlib           3.9.2
nest_asyncio         <not installed>
numpy                2.1.1
openpyxl             3.1.5
pandas               2.2.2
pyarrow              17.0.0
pydantic             <not installed>
pyiceberg            <not installed>
sqlalchemy           <not installed>
torch                <not installed>
xlsx2csv             <not installed>
xlsxwriter           <not installed>
None
```

</details>

**Comment by LeandroVandari** [comment]
I was using polars `1.6.0`, this is fixed in `1.7.1` 🤦
