### ISSUE TITLE
Adding Literal column of Enum dtype fails (for small DataFrame only)

### ISSUE THREAD

**Issue by freerkvenhuizen** [pola-rs/polars#18866]
### Checks

- [X] I have checked that this issue has not already been reported.
- [X] I have confirmed this bug exists on the [latest version](https://pypi.org/project/polars/) of Polars.

### Reproducible example

```python
import polars as pl

k = 1 # when changing this to 10 it suddenly works...

df1 = pl.DataFrame({"a": [1, 2, 3] * k, "b": ["foo", "bar", "baz"] * k})

enum_dtype = pl.Enum(["yolo", "biem"])

# both variants fail
df_2 = df1.with_columns(c=pl.lit("yolo", dtype=enum_dtype))
df_2 = df1.with_columns(c=pl.lit("yolo").cast(enum_dtype))

print(df_2)

```

### Log output

```shell
thread '<unnamed>' panicked at crates/polars-core/src/scalar/mod.rs:46:92:
called `Result::unwrap()` on an `Err` value: SchemaMismatch(ErrString("unexpected value while building Series of type String; found value of type Enum(None, Physical): \"yolo\""))
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
Traceback (most recent call last):
  File "/Users/xxx/code-repos/rate-periodicity-core/MWE.py", line 18, in <module>
    print(df_2)
  File "/Users/xxx/code-repos/rate-periodicity-core/.venv/lib/python3.10/site-packages/polars/dataframe/frame.py", line 1171, in __str__
    return self._df.as_str()
pyo3_runtime.PanicException: called `Result::unwrap()` on an `Err` value: SchemaMismatch(ErrString("unexpected value while building Series of type String; found value of type Enum(None, Physical): \"yolo\""))
```

### Issue description

When adding a new column of Enum dtype it fails for small DataFrames only. 
I added a minimal example to show this:
- When setting k to 1 (i.e., DataFrame contains 3 rows) an error is thrown (in both situations: direct lit creation and casting)
- When setting k to 10 (i.e., DataFrame contains 30 rows) it successfully creates the DataFrame with an additional Enum column.

### Expected behavior

I expect the Enum column to be added for a small DataFrame in the same way it adds it to a large(r) DataFrame.

### Installed versions

<details>

```
--------Version info---------
Polars:              1.8.0
Index type:          UInt32
Platform:            macOS-14.6.1-x86_64-i386-64bit
Python:              3.10.12 (main, Jul 31 2023, 16:18:15) [Clang 14.0.3 (clang-1403.0.22.14.1)]

----Optional dependencies----
adbc_driver_manager  <not installed>
altair               <not installed>
cloudpickle          <not installed>
connectorx           <not installed>
deltalake            <not installed>
fastexcel            <not installed>
fsspec               2024.9.0
gevent               <not installed>
great_tables         <not installed>
matplotlib           3.9.2
nest_asyncio         1.6.0
numpy                2.1.1
openpyxl             <not installed>
pandas               2.2.3
pyarrow              16.1.0
pydantic             2.9.2
pyiceberg            <not installed>
sqlalchemy           <not installed>
torch                <not installed>
xlsx2csv             <not installed>
xlsxwriter           <not installed>
None```

</details>

**Comment by fredrikmalmfors** [comment]
Encountered the exact same issue today. Issue seems to have appeared in v1.8.0, works fine in v1.7.1.
