### ISSUE TITLE
Casting String lit to Categorical

### ISSUE THREAD

**Issue by josh** [pola-rs/polars#18874]
### Checks

- [X] I have checked that this issue has not already been reported.
- [X] I have confirmed this bug exists on the [latest version](https://pypi.org/project/polars/) of Polars.

### Reproducible example

```python
# crashes
df = pl.DataFrame(
    {"a": [1, 2, 3]},
).with_columns(b=pl.lit("foo").cast(pl.Categorical))
print(df)

# workaround, works okay
df = (
    pl.DataFrame(
        {"a": [1, 2, 3]},
    )
    .with_columns(b=pl.lit("foo"))
    .with_columns(b=pl.col("b").cast(pl.Categorical))
)
print(df)
```

### Log output

```shell
thread '<unnamed>' panicked at crates/polars-core/src/scalar/mod.rs:46:92:
called `Result::unwrap()` on an `Err` value: SchemaMismatch(ErrString("unexpected value while building Series of type String; found value of type Categorical(None, Physical): \"foo\""))
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
Traceback (most recent call last):
  File "/workspaces/test/test.py", line 25, in <module>
    print(df)
  File "/home/codespace/.python/current/lib/python3.12/site-packages/polars/dataframe/frame.py", line 1171, in __str__
    return self._df.as_str()
           ^^^^^^^^^^^^^^^^^
pyo3_runtime.PanicException: called `Result::unwrap()` on an `Err` value: SchemaMismatch(ErrString("unexpected value while building Series of type String; found value of type Categorical(None, Physical): \"foo\""))
```

### Issue description

Immediately casting a String `pl.lit` to categorical crashes. It seems like you can work around it by creating the column first, then casting as a separate step.

Crashes on `1.8.1`, `1.8.0`, okay on `1.7.1`, `1.6.0`.

### Expected behavior

```
# shape: (3, 2)
# ┌─────┬─────┐
# │ a   ┆ b   │
# │ --- ┆ --- │
# │ i64 ┆ cat │
# ╞═════╪═════╡
# │ 1   ┆ foo │
# │ 2   ┆ foo │
# │ 3   ┆ foo │
# └─────┴─────┘
```

### Installed versions

<details>

```
--------Version info---------
Polars:              1.8.1
Index type:          UInt32
Platform:            Linux-6.5.0-1025-azure-x86_64-with-glibc2.31
Python:              3.12.1 (main, Aug 20 2024, 19:28:58) [GCC 9.4.0]

----Optional dependencies----
adbc_driver_manager  <not installed>
altair               <not installed>
cloudpickle          <not installed>
connectorx           <not installed>
deltalake            <not installed>
fastexcel            <not installed>
fsspec               2024.9.0
gevent               <not installed>
great_tables         <not installed>
matplotlib           3.9.2
nest_asyncio         1.6.0
numpy                2.1.1
openpyxl             <not installed>
pandas               2.2.2
pyarrow              <not installed>
pydantic             <not installed>
pyiceberg            <not installed>
sqlalchemy           <not installed>
torch                2.4.0+cpu
xlsx2csv             <not installed>
xlsxwriter           <not installed>
```

</details>

**Comment by deanm0000** [comment]
Instead of calling cast on the lit, you can just do 

```
df = pl.DataFrame(
    {"a": [1, 2, 3]},
).with_columns(b=pl.lit("foo",pl.Categorical))
```

It's still a bug because there's a panic but even if/when the bug is fixed, that'd be the better way.

**Comment by coastalwhite** [comment]
Pretty sure this is regression caused by #18664.
