### ISSUE TITLE
Support datetime arithemetic within lists

### ISSUE THREAD

**Issue by itamarst** [pola-rs/polars#18899]
### Description

This is a follow-up to #9188 and #8006.

Much like adding lists to each other is (or for some cases, soon will be) working for numbers, it can also be made to work for dates, datetimes, and durations.

For example, adding these two series works:

```python
>>> import polars as pl
>>> from datetime import date, timedelta
>>> s = pl.Series([timedelta(days=2), timedelta(days=3)])
>>> s2 = pl.Series([timedelta(days=2), timedelta(days=3)])
>>> s + s2
shape: (2,)
Series: '' [date]
[
        2007-01-02
        2006-01-04
]
```

But nested as a list, it doesn't work:

```python
>>> s = pl.Series([[date(2006, 12, 31), date(2006, 1, 1)]])
>>> s2 = pl.Series([[timedelta(days=2), timedelta(days=3)]])
>>> s + s2
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/itamarst/devel/polars/py-polars/polars/series/series.py", line 1051, in __add__
    return self._arithmetic(other, "add", "add_<>")
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/itamarst/devel/polars/py-polars/polars/series/series.py", line 997, in _arithmetic
    return self._from_pyseries(getattr(self._s, op_s)(other._s))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
polars.exceptions.InvalidOperationError: casting from Duration(Microseconds) to Date not supported
```

**Comment by itamarst** [comment]
This now gives a different result; instead of an error, the wrong type:

```python
>>> s + s2
shape: (1,)
Series: '' [list[i64]]
[
        [172800013513, 259200013149]
]
```
