### ISSUE TITLE
Support arithmetic operations between numeric List Series and a scalar

### ISSUE THREAD

**Issue by itamarst** [pola-rs/polars#18900]
### Description

A follow-up to #9188 and #8006.

Multiplying a numeric Series by a scalar works, but currently doing the same with a list fails; this should be fixed for consistency with new ability to do arithmetic between List Series (#9188) and List series and numeric series (#8006):

```python
>>> s = pl.Series([1, 2])
>>> s * 2
shape: (2,)
Series: '' [i64]
[
        2
        4
]
>>> s = pl.Series([[1, 2]])
>>> s * 2
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/itamarst/devel/polars/py-polars/polars/series/series.py", line 1136, in __mul__
    return self._arithmetic(other, "mul", "mul_<>")
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/itamarst/devel/polars/py-polars/polars/series/series.py", line 1022, in _arithmetic
    other = maybe_cast(other, self.dtype)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/itamarst/devel/polars/py-polars/polars/datatypes/convert.py", line 350, in maybe_cast
    raise TypeError(msg) from None
TypeError: cannot convert Python type 'int' to List(Int64)
```

**Comment by itamarst** [comment]
I _think_ this overlaps with the in-progress PR https://github.com/pola-rs/polars/pull/18858, so might be able to build on that.

**Comment by itamarst** [comment]
This never got implemented, still a missing feature.
