### ISSUE TITLE
Diagonal concat when lazyframe other than first item contains list dtype for a column not in first item causes incompatible types error

### ISSUE THREAD

**Issue by jaredcolerosenberg** [pola-rs/polars#18911]
### Checks

- [X] I have checked that this issue has not already been reported.
- [X] I have confirmed this bug exists on the [latest version](https://pypi.org/project/polars/) of Polars.

### Reproducible example

```python
import polars as pl
a = pl.LazyFrame({"a": [[1]], "b": [1]})
b = pl.LazyFrame({"c": [1, 2]})
df = pl.concat([b, a], how="diagonal", rechunk=True).collect()

```

### Log output

```shell
UNION: union is run in parallel
Traceback (most recent call last):
  File "/home/jared/bla/bla-python/bla-entity/bug_report.py", line 42, in <module>
    df = pl.concat([b, a], how="diagonal", rechunk=True).collect()
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/jared/bla/bla-python/bla-entity/venv/lib/python3.12/site-packages/polars/lazyframe/frame.py", line 2033, in collect
    return wrap_df(ldf.collect(callback))
                   ^^^^^^^^^^^^^^^^^^^^^
polars.exceptions.SchemaError: type Int64 is incompatible with expected type Null
```

### Issue description

- changing the order of `a` and `b` produces a correct diagonal concat
- using eager instead of lazy produces the expected result
- doesn't matter if `rechunk=True` or `rechunk=False`. Both produce an exception.

### Expected behavior

Expected this to concat the frames vertically and fill in nulls where appropriate.

### Installed versions

<details>

```
--------Version info---------
Polars:              1.8.1
Index type:          UInt32
Platform:            Linux-6.8.0-40-generic-x86_64-with-glibc2.35
Python:              3.12.2 (main, May  7 2024, 12:21:38) [GCC 11.4.0]

----Optional dependencies----
adbc_driver_manager  <not installed>
altair               <not installed>
cloudpickle          <not installed>
connectorx           <not installed>
deltalake            0.20.0
fastexcel            <not installed>
fsspec               <not installed>
gevent               <not installed>
great_tables         <not installed>
matplotlib           <not installed>
nest_asyncio         <not installed>
numpy                2.1.1
openpyxl             <not installed>
pandas               <not installed>
pyarrow              17.0.0
pydantic             2.9.2
pyiceberg            <not installed>
sqlalchemy           <not installed>
torch                <not installed>
xlsx2csv             <not installed>
xlsxwriter           <not installed>

```

</details>

**Comment by cmdlineluser** [comment]
Even `diagonal_relaxed` produces the same error.

The example works for me in 1.7.1 - so it seems this is a regression from 1.8.0
