### ISSUE TITLE
read_csv() with schema_overrides cause ComputeError

### ISSUE THREAD

**Issue by AntonioST** [pola-rs/polars#18951]
### Checks

- [X] I have checked that this issue has not already been reported.
- [X] I have confirmed this bug exists on the [latest version](https://pypi.org/project/polars/) of Polars.

### Reproducible example

```python

import polars as pl
import io

csv = """\
a,c,b
1,2,3
"""

s = {'a': int, 'b': int, 'd': int}

pl.read_csv(io.StringIO(csv), schema_overrides=s)

```

### Log output

```shell
file < 128 rows, no statistics determined
no. of chunks: 1 processed by: 1 threads.
Traceback (most recent call last):
  File "test_polars_bug.py", line 11, in <module>
    pl.read_csv(io.StringIO(csv), schema_overrides=s)
  File ".../lib/python3.10/site-packages/polars/_utils/deprecation.py", line 91, in wrapper
    return function(*args, **kwargs)
  File ".../lib/python3.10/site-packages/polars/_utils/deprecation.py", line 91, in wrapper
    return function(*args, **kwargs)
  File ".../lib/python3.10/site-packages/polars/_utils/deprecation.py", line 91, in wrapper
    return function(*args, **kwargs)
  File ".../lib/python3.10/site-packages/polars/io/csv/functions.py", line 500, in read_csv
    df = _read_csv_impl(
  File ".../lib/python3.10/site-packages/polars/io/csv/functions.py", line 646, in _read_csv_impl
    pydf = PyDataFrame.read_csv(
polars.exceptions.ComputeError: found more fields than defined in 'Schema'

Consider setting 'truncate_ragged_lines=True'.
```

### Issue description

I have two different kinds of CSV files with some common headers. I used the same script to load them with a common schema dict to the `schema_overrides` parameter. The schema also contains some columns that don't show in the CSV file and are added after reading. The Reproducible example code is a simplified version of one of my problem CSV files. It could be the minimal example that the error could disappear after I removed one column from the CSV or from the schema. No error is raised when reading the content directly (without providing a schema).

### Expected behavior

Successfully read without error.

### Installed versions

<details>

```
--------Version info---------
Polars:              1.8.2
Index type:          UInt32
Platform:            Linux-6.10.5-arch1-1-x86_64-with-glibc2.40
Python:              3.10.14 (main, Mar 21 2024, 16:24:04) [GCC 11.2.0]

----Optional dependencies----
adbc_driver_manager  <not installed>
altair               <not installed>
cloudpickle          2.2.1
connectorx           <not installed>
deltalake            <not installed>
fastexcel            <not installed>
fsspec               2023.10.0
gevent               <not installed>
great_tables         <not installed>
matplotlib           3.8.4
nest_asyncio         1.6.0
numpy                1.25.2
openpyxl             <not installed>
pandas               1.5.3
pyarrow              16.1.0
pydantic             1.9.1
pyiceberg            <not installed>
sqlalchemy           2.0.29
torch                <not installed>
xlsx2csv             <not installed>
xlsxwriter           <not installed>

```

</details>

**Comment by josemcorderoc** [comment]
I'm having the same issue. It seems to happen only when the number of columns of the CSV and the dict size are the same.

In your example:
```python

import polars as pl
import io

csv = """\
a,c,b
1,2,3
"""

# Works as expected
s = {'a': int, 'b': int}
pl.read_csv(io.StringIO(csv), schema_overrides=s)

# ComputeError
s = {'a': int, 'b': int, 'd': int}
pl.read_csv(io.StringIO(csv), schema_overrides=s)

# Works as expected
s = {'a': int, 'b': int, 'd': int, 'x': int}
pl.read_csv(io.StringIO(csv), schema_overrides=s)
```

As a workaround, I added a random key to the dict in that case

```python
import csv
import uuid
from polars.exceptions import ComputeError

csv_str = """\
a,c,b
1,2,3
"""
s = {'a': int, 'b': int, 'd': int}

try:
    pl.read_csv(io.StringIO(csv_str), schema_overrides=s)
except ComputeError as e:
    # Count columns in CSV
    num_columns = len(next(csv.reader(io.StringIO(csv_str))))
    if num_columns != len(s):
        raise e
    
    # Add a random key to the schema_overrides
    random_key = str(uuid.uuid4())
    s[random_key] = int
    pl.read_csv(io.StringIO(csv_str), schema_overrides=s)

    # Remove the random key
    del s[random_key]
```

**Comment by davidrodriguezcofi** [comment]
Any news on this?

**Comment by DeastinY** [comment]
same here

**Comment by AntonioST** [comment]
The issue is caused by the `if` statement at [schema_inference.rs:L474](https://github.com/pola-rs/polars/blob/main/crates/polars-io/src/csv/read/schema_inference.rs#L474). I removed it and used the following test.

```python
def test_read_csv_18951():
    csv = textwrap.dedent("""\
    a,c,b
    1,2,3
    """)

    s = {'a': int, 'b': int, 'd': int}
    actual = pl.read_csv(csv.encode(), schema_overrides=s)
    expect = pl.DataFrame([{'a': 1, 'c': 2, 'b':3}])
    assert_frame_equal(actual, expect)
```

All tests with an additional one were passed (10933 passed, 6 skipped, 11 xfailed in 43.04s).

Polars was compiled and tested on my machine.

```
--------Version info---------
Polars:              1.27.1
Index type:          UInt32
Platform:            Linux-6.14.1-arch1-1-x86_64-with-glibc2.41
Python:              3.13.2 (main, Feb  5 2025, 08:05:21) [GCC 14.2.1 20250128]
LTS CPU:             False

----Optional dependencies----
Azure CLI            <not installed>
adbc_driver_manager  1.5.0
altair               5.5.0
azure.identity       <not installed>
boto3                1.37.1
cloudpickle          3.1.1
connectorx           0.4.3
deltalake            0.25.5
fastexcel            0.13.0
fsspec               2025.3.2
gevent               25.4.1
google.auth          2.39.0
great_tables         0.17.0
matplotlib           3.10.1
numpy                2.2.4
openpyxl             3.1.5
pandas               2.2.3
polars_cloud         0.0.7
pyarrow              19.0.1
pydantic             2.11.3
pyiceberg            <not installed>
sqlalchemy           2.0.40
torch                <not installed>
xlsx2csv             0.8.4
xlsxwriter           3.2.3
```

**Comment by josemcorderoc** [comment]
Upgrading to Polars 1.37.1 fixed this issue for me.

**Comment by kdn36** [comment]
Unable to reproduce on latest release (1.38.1). This has likely been fixed. I will go ahead and close the issue, but feel free to reopen in case you run into this issue again.

```
shape: (1, 3)
┌─────┬─────┬─────┐
│ a   ┆ c   ┆ b   │
│ --- ┆ --- ┆ --- │
│ i64 ┆ i64 ┆ i64 │
╞═════╪═════╪═════╡
│ 1   ┆ 2   ┆ 3   │
└─────┴─────┴─────┘
```
