### ISSUE TITLE
Starting 1.7.0, calling Expr.str.replace on a Int64 column raises

### ISSUE THREAD

**Issue by BartSchuurmans** [pola-rs/polars#19047]
### Checks

- [X] I have checked that this issue has not already been reported.
- [X] I have confirmed this bug exists on the [latest version](https://pypi.org/project/polars/) of Polars.

### Reproducible example

```python
pl.select(pl.lit(1, dtype=pl.Int64).str.replace(",", "."))
```

Polars 1.6.0:
```
shape: (1, 1)
┌─────────┐
│ literal │
│ ---     │
│ str     │
╞═════════╡
│ 1       │
└─────────┘
```

Polars 1.7.0:
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/bart/src/proj/.venv/lib/python3.12/site-packages/polars/functions/lazy.py", line 1908, in select
    return pl.DataFrame().select(*exprs, **named_exprs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/bart/src/proj/.venv/lib/python3.12/site-packages/polars/dataframe/frame.py", line 8981, in select
    return self.lazy().select(*exprs, **named_exprs).collect(_eager=True)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/bart/src/proj/.venv/lib/python3.12/site-packages/polars/lazyframe/frame.py", line 2053, in collect
    return wrap_df(ldf.collect(callback))
                   ^^^^^^^^^^^^^^^^^^^^^
polars.exceptions.InvalidOperationError: expected String type, got: i64
```

### Issue description

Starting 1.7.0, calling Expr.str.replace on a Int64 column raises instead of silently casting to String.

The i64 column type was inferred by `pl.read_csv()`, which is why I didn't expect it to be an `i64` but a `str`.

### Expected behavior

Current behavior might be correct, I just can't find the change in the release notes.

### Installed versions

<details>

```
--------Version info---------
Polars:              1.8.2
Index type:          UInt32
Platform:            Linux-5.15.153.1-microsoft-standard-WSL2-x86_64-with-glibc2.35
Python:              3.12.5 (main, Aug 17 2024, 16:46:05) [GCC 11.4.0]

----Optional dependencies----
adbc_driver_manager  <not installed>
altair               <not installed>
cloudpickle          <not installed>
connectorx           <not installed>
deltalake            <not installed>
fastexcel            <not installed>
fsspec               <not installed>
gevent               <not installed>
great_tables         <not installed>
matplotlib           <not installed>
nest_asyncio         1.6.0
numpy                2.1.0
openpyxl             <not installed>
pandas               2.2.2
pyarrow              16.1.0
pydantic             2.8.2
pyiceberg            <not installed>
sqlalchemy           <not installed>
torch                <not installed>
xlsx2csv             <not installed>
xlsxwriter           <not installed>```

</details>

**Comment by stinodego** [comment]
This is indeed expected behavior. You would have to cast your column to a String before using `str.replace`, or provide `schema_overrides` to `read_csv`. 

Not sure which PR introduced the change in behavior that affected you, but we make correctness improvements all the time. This would fall into that category.

**Comment by cmdlineluser** [comment]
The PR, if interested:

- https://github.com/pola-rs/polars/pull/18474
