### ISSUE TITLE
Panic on join_where with string ordering since `1.8.0`

### ISSUE THREAD

**Issue by ryzhakar** [pola-rs/polars#19080]
### Checks

- [X] I have checked that this issue has not already been reported.
- [X] I have confirmed this bug exists on the [latest version](https://pypi.org/project/polars/) of Polars.

### Reproducible example

```python
import polars as pl

df = pl.DataFrame(
    {
        'a': ['a', 'b', 'c'],
        'b': ['b', 'b', 'b'],
    }
)
print(
    df.select(
        pl.col('a').ge(pl.col('b'))
    )
)
# ┌───────┐
# │ a     │
# │ ---   │
# │ bool  │
# ╞═══════╡
# │ false │
# │ true  │
# │ true  │
# └───────┘
print(
    df.join_where(
        df,
        pl.col('a').ge(pl.col('a_right'))
    )
)
# pyo3_runtime.PanicException: not implemented for dtype String


```

### Log output

```shell
join parallel: true
thread 'polars-4' panicked at crates/polars-ops/src/frame/join/iejoin/mod.rs:559:41:
not implemented for dtype String
stack backtrace:
   0: _rust_begin_unwind
   1: core::panicking::panic_fmt
   2: polars_ops::frame::join::iejoin::piecewise_merge_join_tuples
   3: rayon::iter::plumbing::bridge_producer_consumer::helper
   4: rayon_core::join::join_context::{{closure}}
   5: rayon::iter::plumbing::bridge_producer_consumer::helper
   6: <rayon_core::job::StackJob<L,F,R> as rayon_core::job::Job>::execute
   7: rayon_core::registry::WorkerThread::wait_until_cold
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
thread 'polars-0' panicked at crates/polars-ops/src/frame/join/iejoin/mod.rs:559:41:
not implemented for dtype String
stack backtrace:
   0: _rust_begin_unwind
   1: core::panicking::panic_fmt
   2: polars_ops::frame::join::iejoin::piecewise_merge_join_tuples
   3: rayon::iter::plumbing::bridge_producer_consumer::helper
   4: rayon_core::join::join_context::{{closure}}
   5: rayon::iter::plumbing::bridge_producer_consumer::helper
   6: rayon_core::join::join_context::{{closure}}
   7: rayon::iter::plumbing::bridge_producer_consumer::helper
   8: rayon_core::join::join_context::{{closure}}
   9: rayon::iter::plumbing::bridge_producer_consumer::helper
  10: rayon_core::join::join_context::{{closure}}
  11: rayon::iter::plumbing::bridge_producer_consumer::helper
  12: rayon_core::thread_pool::ThreadPool::install::{{closure}}
  13: <rayon_core::job::StackJob<L,F,R> as rayon_core::job::Job>::execute
  14: rayon_core::registry::WorkerThread::wait_until_cold
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
thread 'polars-3' panicked at crates/polars-ops/src/frame/join/iejoin/mod.rs:559:41:
not implemented for dtype String
stack backtrace:
   0: _rust_begin_unwind
   1: core::panicking::panic_fmt
   2: polars_ops::frame::join::iejoin::piecewise_merge_join_tuples
   3: rayon::iter::plumbing::bridge_producer_consumer::helper
   4: <rayon_core::job::StackJob<L,F,R> as rayon_core::job::Job>::execute
   5: rayon_core::registry::WorkerThread::wait_until_cold
   6: rayon_core::join::join_context::{{closure}}
   7: rayon::iter::plumbing::bridge_producer_consumer::helper
   8: <rayon_core::job::StackJob<L,F,R> as rayon_core::job::Job>::execute
   9: rayon_core::registry::WorkerThread::wait_until_cold
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
thread 'polars-1' panicked at crates/polars-ops/src/frame/join/iejoin/mod.rs:559:41:
not implemented for dtype String
stack backtrace:
   0: _rust_begin_unwind
   1: core::panicking::panic_fmt
   2: polars_ops::frame::join::iejoin::piecewise_merge_join_tuples
   3: rayon::iter::plumbing::bridge_producer_consumer::helper
   4: <rayon_core::job::StackJob<L,F,R> as rayon_core::job::Job>::execute
   5: rayon_core::registry::WorkerThread::wait_until_cold
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
thread 'polars-7' panicked at crates/polars-ops/src/frame/join/iejoin/mod.rs:559:41:
not implemented for dtype String
stack backtrace:
   0: _rust_begin_unwind
   1: core::panicking::panic_fmt
   2: polars_ops::frame::join::iejoin::piecewise_merge_join_tuples
   3: rayon::iter::plumbing::bridge_producer_consumer::helper
   4: rayon_core::join::join_context::{{closure}}
   5: rayon::iter::plumbing::bridge_producer_consumer::helper
   6: <rayon_core::job::StackJob<L,F,R> as rayon_core::job::Job>::execute
   7: rayon_core::registry::WorkerThread::wait_until_cold
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.

Traceback (most recent call last):
  File "/Users/ryzhakar/similarity-sandbox/throwaway_scripts/.partial_eq_issue1.py", line 24, in <module>
    df.join_where(
  File "/Users/ryzhakar/similarity-sandbox/.venv/lib/python3.11/site-packages/polars/_utils/unstable.py", line 58, in wrapper
    return function(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ryzhakar/similarity-sandbox/.venv/lib/python3.11/site-packages/polars/dataframe/frame.py", line 7191, in join_where
    .collect(_eager=True)
     ^^^^^^^^^^^^^^^^^^^^
  File "/Users/ryzhakar/similarity-sandbox/.venv/lib/python3.11/site-packages/polars/lazyframe/frame.py", line 2033, in collect
    return wrap_df(ldf.collect(callback))
                   ^^^^^^^^^^^^^^^^^^^^^
pyo3_runtime.PanicException: not implemented for dtype String
```

### Issue description

Works okay in 1.7.1
Consistently fails in every version since 1.8.0

### Expected behavior

```sh
shape: (3, 1)
┌───────┐
│ a     │
│ ---   │
│ bool  │
╞═══════╡
│ false │
│ true  │
│ true  │
└───────┘
join parallel: true
CROSS join dataframes finished
dataframe filtered
shape: (6, 4)
┌─────┬─────┬─────────┬─────────┐
│ a   ┆ b   ┆ a_right ┆ b_right │
│ --- ┆ --- ┆ ---     ┆ ---     │
│ str ┆ str ┆ str     ┆ str     │
╞═════╪═════╪═════════╪═════════╡
│ a   ┆ b   ┆ a       ┆ b       │
│ b   ┆ b   ┆ a       ┆ b       │
│ b   ┆ b   ┆ b       ┆ b       │
│ c   ┆ b   ┆ a       ┆ b       │
│ c   ┆ b   ┆ b       ┆ b       │
│ c   ┆ b   ┆ c       ┆ b       │
└─────┴─────┴─────────┴─────────┘
```

### Installed versions

<details>

```
--------Version info---------
Polars:              1.9.0
Index type:          UInt32
Platform:            macOS-15.0-arm64-arm-64bit
Python:              3.11.9 (main, Sep  2 2024, 18:32:37) [Clang 15.0.0 (clang-1500.3.9.4)]

----Optional dependencies----
adbc_driver_manager  <not installed>
altair               <not installed>
cloudpickle          <not installed>
connectorx           <not installed>
deltalake            <not installed>
fastexcel            <not installed>
fsspec               2024.9.0
gevent               <not installed>
great_tables         <not installed>
matplotlib           <not installed>
nest_asyncio         <not installed>
numpy                2.1.1
openpyxl             <not installed>
pandas               <not installed>
pyarrow              <not installed>
pydantic             <not installed>
pyiceberg            <not installed>
sqlalchemy           <not installed>
torch                2.4.1
xlsx2csv             <not installed>
xlsxwriter           <not installed>
```

</details>

**Comment by ryzhakar** [comment]
Wow, that was quick!
Thank you 🥰
