### ISSUE TITLE
`allow_missing_columns` combined with passing `schema` fails if columns are missing from first file

### ISSUE THREAD

**Issue by aersam** [pola-rs/polars#19081]
### Checks

- [X] I have checked that this issue has not already been reported.
- [X] I have confirmed this bug exists on the [latest version](https://pypi.org/project/polars/) of Polars.

### Reproducible example

```python
import polars as pl

schema = {"UserId": pl.Int64, "FirstName": pl.String}
pl.DataFrame({"UserId": [1555], "FirstName": ["Peter"]}).write_parquet("test1.parquet")
pl.DataFrame({"UserId": [1556]}).write_parquet("test2.parquet")
print(
    pl.scan_parquet("test2.parquet", schema=schema, allow_missing_columns=True)
    .select(pl.col("FirstName"), pl.col("UserId"))
    .collect()
)

```

### Log output

```shell
Traceback (most recent call last):
  File "C:\Projects\BMS_Github\deltalake2db\repo.py", line 9, in <module>
    .collect()
     ^^^^^^^^^
  File "C:\Projects\BMS_Github\deltalake2db\.venv\Lib\site-packages\polars\lazyframe\frame.py", line 2050, in collect
    return wrap_df(ldf.collect(callback))
                   ^^^^^^^^^^^^^^^^^^^^^
polars.exceptions.ColumnNotFoundError: FirstName

Resolved plan until failure:

        ---> FAILED HERE RESOLVING 'select' <---
Parquet SCAN [test2.parquet]
PROJECT */1 COLUMNS
```

### Issue description

As I pass the column Name "FirstName" in the schema and set allow_missing_columns to true, I would also expect it to work. However I get this ColumnNotFoundError

### Expected behavior

First Name should be Null. Feature was introduced in this PR: #18922 

### Installed versions

<details>

```
Polars:              1.9.0
Index type:          UInt32
Platform:            Windows-10-10.0.19045-SP0
Python:              3.11.1 (tags/v3.11.1:a7a450f, Dec  6 2022, 19:58:39) [MSC v.1934 64 bit (AMD64)]

----Optional dependencies----
adbc_driver_manager  <not installed>
altair               <not installed>
cloudpickle          <not installed>
connectorx           <not installed>
deltalake            0.18.1
fastexcel            <not installed>
fsspec               2024.9.0
gevent               <not installed>
great_tables         <not installed>
matplotlib           <not installed>
nest_asyncio         <not installed>
numpy                2.1.1
openpyxl             <not installed>
pandas               2.2.3
pyarrow              17.0.0
pydantic             <not installed>
pyiceberg            <not installed>
sqlalchemy           <not installed>
torch                <not installed>
xlsx2csv             <not installed>
xlsxwriter           <not installed>
```

</details>

**Comment by etiennebacher** [comment]
I think `allow_missing_columns` only works in cases where you scan multiple files at once, here you only scan one.

**Comment by lmocsi** [comment]
@nameexhaustion Question: if both schema and dataframes put UserId at first place, then why is it displayed on the second place (in the correct query)?
