### ISSUE TITLE
OOC sort `PanicException` RecordBatch requires all its arrays to have an equal number of rows

### ISSUE THREAD

**Issue by cmdlineluser** [pola-rs/polars#19111]
### Checks

- [X] I have checked that this issue has not already been reported.
- [X] I have confirmed this bug exists on the [latest version](https://pypi.org/project/polars/) of Polars.

### Reproducible example

```python
import tempfile
import polars as pl

pl.Config.set_verbose(True)  

N = 20_000_000 # needs to be large enough to force OOC sort

one = "00;XPTO;99999991000197;20240905;130444;000001;20240905;130444;000001;20240901;0000"
two = "01;99900000001;F;1;0;000000321"
three = "99;00000000005;"

with (tempfile.NamedTemporaryFile() as f_in, 
      tempfile.NamedTemporaryFile() as f_out):
    
    pl.select(
        pl.concat([
            pl.repeat(one, 1),
            pl.repeat(two, N),
            pl.repeat(three, 1)
        ])
    ).write_csv(f_in.name, include_header=False)
    f_in.seek(0)

    # Read the input files
    lf = pl.scan_csv(
        f_in.name,
        separator=chr(0000),
        has_header=False,
        infer_schema=False,
    )

    (lf.with_columns(splitn = pl.nth(0).str.splitn(";", 2))
       .with_columns(pl.col.splitn.struct[idx].alias(f"sort_{idx}") for idx in [1, 0])
       .sort(r"^sort_\d+$")
       .drop("splitn", r"^sort_\d+$")
       .sink_csv(f_out.name, include_header=False)
    )
```

### Log output

```shell
RUN STREAMING PIPELINE
[csv -> hstack -> hstack -> sort_multiple -> fast_projection -> parquet_sink]
STREAMING CHUNK SIZE: 50000 rows
OOC sort started
Temporary directory path in use: /var/folders/06/98tx92k103g3sjqpg3zp7z440000gn/T/
OOC sort started
OOC sort started
OOC sort started
OOC sort started
OOC sort started
OOC sort started
OOC sort started
finished sinking into OOC sort in 1.49320675s
full file dump of OOC sort took 2.432418584s
spill size: 18 mb
processing 48 files
thread 'polars-4' panicked at /Users/runner/work/polars/polars/crates/polars-arrow/src/record_batch.rs:22:31:
called `Result::unwrap()` on an `Err` value: ComputeError(ErrString("RecordBatch requires all its arrays to have an equal number of rows"))
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
Traceback (most recent call last):
  File "/Users/user/recordbatch-panic.py", line 36, in <module>
    .sink_csv(f_out.name, include_header=False)
     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.12/site-packages/polars/_utils/unstable.py", line 58, in wrapper
    return function(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.12/site-packages/polars/lazyframe/frame.py", line 2604, in sink_csv
    return lf.sink_csv(
           ^^^^^^^^^^^^
pyo3_runtime.PanicException: called `Result::unwrap()` on an `Err` value: ComputeError(ErrString("RecordBatch requires all its arrays to have an equal number of rows"))
```

### Issue description

This error has appeared in some previous issues: https://github.com/pola-rs/polars/issues/17842 https://github.com/pola-rs/polars/issues/18599

But it seems nobody else has been able to reproduce.

It appears to be non-deterministic, sometimes it runs without error.

With 10 runs, the given example succeeds 2 / 10 times - so it may require multiple runs to trigger.

An OOC sort is required, so N may need to be increased.

### Expected behavior

No panic.

### Installed versions

<details>

```
--------Version info---------
Polars:              1.9.0
Index type:          UInt32
Platform:            macOS-13.6.1-arm64-arm-64bit
Python:              3.12.6 (main, Sep  6 2024, 19:03:47) [Clang 15.0.0 (clang-1500.1.0.2.5)]

----Optional dependencies----
adbc_driver_manager  <not installed>
altair               5.4.1
cloudpickle          <not installed>
connectorx           <not installed>
deltalake            <not installed>
fastexcel            <not installed>
fsspec               2024.9.0
gevent               <not installed>
great_tables         <not installed>
matplotlib           <not installed>
nest_asyncio         <not installed>
numpy                1.26.4
openpyxl             <not installed>
pandas               2.2.3
pyarrow              15.0.2
pydantic             <not installed>
pyiceberg            <not installed>
sqlalchemy           <not installed>
torch                <not installed>
xlsx2csv             <not installed>
xlsxwriter           <not installed>
```

</details>

**Comment by ritchie46** [comment]
Can we get something minimal. We can force OOC with setting `POLARS_FORCE_OOC=1`.

**Comment by cmdlineluser** [comment]
Ah - thanks @ritchie46 

That allows me to reduce it down to ~790_000 rows and still trigger.

```python
import os
import tempfile

os.environ["POLARS_FORCE_OOC"] = "1"

import polars as pl

pl.Config.set_verbose(True)  

N = 790_000

data = "AA;AAAAAAAAAAA;A;A;A;AAAAAA"

with tempfile.NamedTemporaryFile() as f:
    pl.select(pl.repeat(data, N)).write_csv(f.name, include_header=False)

    f.seek(0)

    lf = pl.scan_csv(f.name, has_header=False)

    (lf.with_columns(splitn = pl.nth(0).str.splitn(";", 2))
       .with_columns(
           sort_1 = pl.col.splitn.struct[1],
           sort_0 = pl.col.splitn.struct[0]
       )
       .sort(r"^sort_\d+$")
       .collect(streaming=True)
    )
```

It seems to require adding a struct column and adding fields as columns.

Will see if I can reduce it further.

**Comment by cmdlineluser** [comment]
Not sure if a backtrace is of help, but here it is:
```
stack backtrace:
   0:        0x10e74fd84 - <std::sys::backtrace::BacktraceLock::print::DisplayBacktrace as core::fmt::Display>::fmt::ha2729a89d5947d1a
   1:        0x10b38a164 - core::fmt::write::h4703849e38e1d299
   2:        0x10e7213b4 - std::io::Write::write_fmt::h43e14666b738b3c0
   3:        0x10e750d6c - std::sys::backtrace::BacktraceLock::print::hdc428fb2ed43dcbe
   4:        0x10e750bd0 - std::panicking::default_hook::{{closure}}::h6b351e7e30ce1b5c
   5:        0x10e751424 - std::panicking::rust_panic_with_hook::h3872e75c8800c436
   6:        0x10e750e34 - std::panicking::begin_panic_handler::{{closure}}::h4987bf2d8d740314
   7:        0x10e750da4 - std::sys::backtrace::__rust_end_short_backtrace::he50949e753308285
   8:        0x10e750d98 - _rust_begin_unwind
   9:        0x10e89313c - core::panicking::panic_fmt::heaa919ecddc98c07
  10:        0x10e893458 - core::result::unwrap_failed::hf8d357922869640a
  11:        0x10c150c94 - <polars_core::frame::RecordBatchIter as core::iter::traits::iterator::Iterator>::next::hc158e36c936bef13
  12:        0x10d159bdc - polars_io::ipc::write::BatchedWriter<W>::write_batch::h87cce25bca0c44da
  13:        0x10d227b0c - rayon::iter::plumbing::bridge_producer_consumer::helper::hb827230b990542ca
  14:        0x10d2352a4 - <rayon_core::job::StackJob<L,F,R> as rayon_core::job::Job>::execute::h1e758bc35f14ea41
  15:        0x10eb4e808 - rayon_core::registry::WorkerThread::wait_until_cold::hd284f75426e73438
  16:        0x10e50aea4 - std::sys::backtrace::__rust_begin_short_backtrace::h277396daceaf6f02
  17:        0x10e50ac84 - core::ops::function::FnOnce::call_once{{vtable.shim}}::he6d364c23ad2ce52
  18:        0x10e753c80 - std::sys::pal::unix::thread::Thread::new::thread_start::hed13b2d12c31ec52
  19:        0x1928bffa8 - __pthread_joiner_wake
```

**Comment by cmdlineluser** [comment]
Just tried to add some dbg calls to try understand what's going on.

In the sinking I get 3 chunks:

```rust
[crates/polars-pipe/src/executors/sinks/sort/sink.rs:95:9] chunk.data.height() = 262145
[crates/polars-pipe/src/executors/sinks/sort/sink.rs:95:9] chunk.data.height() = 258710
[crates/polars-pipe/src/executors/sinks/sort/sink.rs:95:9] chunk.data.height() = 262145
```

Then finalising the sinking those 3 chunks are there:

```rust
[crates/polars-arrow/src/record_batch.rs:31:13] len = 262145
[crates/polars-arrow/src/record_batch.rs:32:13] arrays.len() = 3
[crates/polars-arrow/src/record_batch.rs:31:13] len = 262145
[crates/polars-arrow/src/record_batch.rs:32:13] arrays.len() = 3
[crates/polars-arrow/src/record_batch.rs:31:13] len = 258710
[crates/polars-arrow/src/record_batch.rs:32:13] arrays.len() = 3
```

Then I get 4 files to be processed, and 4 chunks. (1 file per chunk I guess?)

```rust
full file dump of OOC sort took 731.493958ms
spill size: 64 mb
processing 4 files
[crates/polars-arrow/src/record_batch.rs:31:13] len = 258710
[crates/polars-arrow/src/record_batch.rs:32:13] arrays.len() = 3
[crates/polars-arrow/src/record_batch.rs:33:55] array.as_ref().len() = 258710
[crates/polars-arrow/src/record_batch.rs:33:55] array.as_ref().len() = 258710
[crates/polars-arrow/src/record_batch.rs:33:55] array.as_ref().len() = 258710
[crates/polars-arrow/src/record_batch.rs:31:13] len = 262145
[crates/polars-arrow/src/record_batch.rs:32:13] arrays.len() = 3
[crates/polars-arrow/src/record_batch.rs:33:55] array.as_ref().len() = 262145
[crates/polars-arrow/src/record_batch.rs:33:55] array.as_ref().len() = 262145
[crates/polars-arrow/src/record_batch.rs:33:55] array.as_ref().len() = 262145
[crates/polars-arrow/src/record_batch.rs:31:13] len = 262145
[crates/polars-arrow/src/record_batch.rs:32:13] arrays.len() = 3
[crates/polars-arrow/src/record_batch.rs:33:55] array.as_ref().len() = 262145
[crates/polars-arrow/src/record_batch.rs:33:55] array.as_ref().len() = 262145
[crates/polars-arrow/src/record_batch.rs:33:55] array.as_ref().len() = 262145
[crates/polars-arrow/src/record_batch.rs:31:13] len = 524290
[crates/polars-arrow/src/record_batch.rs:32:13] arrays.len() = 3
[crates/polars-arrow/src/record_batch.rs:33:55] array.as_ref().len() = 524290
[crates/polars-arrow/src/record_batch.rs:33:55] array.as_ref().len() = 262145
[crates/polars-arrow/src/record_batch.rs:33:55] array.as_ref().len() = 524290
```

The extra chunk at the end has a length of (262145 + 262145)

**Comment by ritchie46** [comment]
Thanks, found it. :)
