### ISSUE TITLE
read_csv() does not support `file:///tmp/foo.csv` fsspec URLs while scan_csv() does

### ISSUE THREAD

**Issue by BartSchuurmans** [pola-rs/polars#19140]
### Checks

- [X] I have checked that this issue has not already been reported.
- [X] I have confirmed this bug exists on the [latest version](https://pypi.org/project/polars/) of Polars.

### Reproducible example

```python
import fsspec
import polars as pl

path = "file:///tmp/test.csv"

with fsspec.open(path, "w") as f:
    f.write("a,b\n1,2\n")

print("scan_csv()")
print(pl.scan_csv(path).collect())

print("read_csv()")
print(pl.read_csv(path))
```

```
❯ python example.py
scan_csv()
shape: (1, 2)
┌─────┬─────┐
│ a   ┆ b   │
│ --- ┆ --- │
│ i64 ┆ i64 │
╞═════╪═════╡
│ 1   ┆ 2   │
└─────┴─────┘
read_csv()
Traceback (most recent call last):
  File "/home/bart/src/proj/example.py", line 13, in <module>
    print(pl.read_csv(path))
          ^^^^^^^^^^^^^^^^^
  File "/home/bart/src/proj/.venv/lib/python3.12/site-packages/polars/_utils/deprecation.py", line 92, in wrapper
    return function(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/bart/src/proj/.venv/lib/python3.12/site-packages/polars/_utils/deprecation.py", line 92, in wrapper
    return function(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/bart/src/proj/.venv/lib/python3.12/site-packages/polars/_utils/deprecation.py", line 92, in wrapper
    return function(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/bart/src/proj/.venv/lib/python3.12/site-packages/polars/io/csv/functions.py", line 503, in read_csv
    df = _read_csv_impl(
         ^^^^^^^^^^^^^^^
  File "/home/bart/src/proj/.venv/lib/python3.12/site-packages/polars/io/csv/functions.py", line 649, in _read_csv_impl
    pydf = PyDataFrame.read_csv(
           ^^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: No such file or directory (os error 2): file:///tmp/test.csv
```

### Log output

```shell
Async thread count: 3
file cache prefix: /tmp/polars/file-cache/
[file_cache] init_entry: creating new entry for uri = file:///tmp/test.csv, hash = 524f4dc11d6d8bd90f028db8c3df4ea2
[file_cache::entry] try_open_check_latest: fetching new data file for uri = file:///tmp/test.csv, remote_version = ETag("f21705fc71da558155d6df15cc8edf75"), remote_size = 8
read files in parallel
[file_cache::entry] try_open_assume_latest: opening already fetched file for uri = file:///tmp/test.csv
file < 128 rows, no statistics determined
no. of chunks: 1 processed by: 1 threads.
```

### Issue description

The documentation mentions fsspec support for both functions, it is unclear why one works and the other doesn't.

### Expected behavior

Both functions accept all fsspec URLs.

### Installed versions

<details>

```
--------Version info---------
Polars:              1.9.0
Index type:          UInt32
Platform:            Linux-5.15.153.1-microsoft-standard-WSL2-x86_64-with-glibc2.35
Python:              3.12.7 (main, Oct  1 2024, 08:52:12) [GCC 11.4.0]

----Optional dependencies----
adbc_driver_manager  <not installed>
altair               <not installed>
cloudpickle          <not installed>
connectorx           <not installed>
deltalake            <not installed>
fastexcel            <not installed>
fsspec               2024.9.0
gevent               <not installed>
great_tables         <not installed>
matplotlib           <not installed>
nest_asyncio         1.6.0
numpy                2.1.0
openpyxl             <not installed>
pandas               2.2.2
pyarrow              16.1.0
pydantic             2.9.2
pyiceberg            <not installed>
sqlalchemy           <not installed>
torch                <not installed>
xlsx2csv             <not installed>
xlsxwriter           <not installed>```

</details>

**Comment by coastalwhite** [comment]
This is due to #13040.

**Comment by BartSchuurmans** [comment]
Note that `s3://` URLs work with both functions, so it is not just that fsspec is entirely unsupported in `read_csv()`.

**Comment by BartSchuurmans** [comment]
I created a small script to compare various inputs to `read_csv` and `scan_csv`:

<details>

```python
from pathlib import Path
from upath import UPath
import fsspec
import io
import polars as pl
import warnings

good = "/tmp/good.csv"
contents = "a,b\n1,2\n"
with open(good, "w") as f:
    f.write(contents)

bad = "/tmp/bad.csv"
assert not Path(bad).exists()

functions = [
    pl.read_csv,
    pl.scan_csv,
]

all_inputs = (
    [
        # In-memory data
        contents,
        bytes(contents, "utf-8"),
        lambda: io.StringIO(contents),
        lambda: io.BytesIO(bytes(contents, "utf-8")),
    ]
    + [
        # Open files
        lambda: open(good),
        lambda: fsspec.open(good),
    ]
    + [
        # File paths
        typefn(file)
        for typefn in [
            str,
            Path,
            UPath,
            lambda x: f"file://{x}",
            lambda x: f"local://{x}",
        ]
        for file in [
            good,
            bad,
        ]
    ]
    + [
        # HTTP URLs
        typefn(url)
        for typefn in [
            str,
            UPath,
        ]
        for url in [
            "https://minnozz.com/good.csv",
            "https://minnozz.com/bad.csv",
        ]
    ]
)
for gen in all_inputs:
    for fn in functions:
        input = gen() if callable(gen) else gen
        try:
            with warnings.catch_warnings(record=True) as w:
                when = "calling function"
                res = fn(input)
                if isinstance(res, pl.LazyFrame):
                    when = "after collect()"
                    res.collect()
            if len(w) > 0:
                result = f"success with warning: {w[0].message}"
            else:
                result = "success" if len(w) == 0 else f"success with warnings: {w}"
        except Exception as e:
            result = f"ERROR {when}: {e}"
        print(f"{fn.__name__}({input.__repr__()}): {result}")
    print()

```
</details>

```
read_csv('a,b\n1,2\n'): ERROR calling function: No such file or directory (os error 2): a,b
1,2

scan_csv('a,b\n1,2\n'): ERROR after collect(): No such file or directory (os error 2): a,b
1,2


read_csv(b'a,b\n1,2\n'): success
scan_csv(b'a,b\n1,2\n'): success

read_csv(<_io.StringIO object at 0x7f2a62087e80>): success
scan_csv(<_io.StringIO object at 0x7f2a62087dc0>): success

read_csv(<_io.BytesIO object at 0x7f2a697b7e70>): success
scan_csv(<_io.BytesIO object at 0x7f2a61dff2e0>): success

read_csv(<_io.TextIOWrapper name='/tmp/good.csv' mode='r' encoding='UTF-8'>): success
scan_csv(<_io.TextIOWrapper name='/tmp/good.csv' mode='r' encoding='UTF-8'>): success

read_csv(<OpenFile '/tmp/good.csv'>): ERROR calling function: Object does not have a .read() method.
scan_csv(<OpenFile '/tmp/good.csv'>): ERROR calling function: Object does not have a .read() method.

read_csv('/tmp/good.csv'): success
scan_csv('/tmp/good.csv'): success

read_csv('/tmp/bad.csv'): ERROR calling function: No such file or directory (os error 2): /tmp/bad.csv
scan_csv('/tmp/bad.csv'): ERROR after collect(): No such file or directory (os error 2): /tmp/bad.csv

read_csv(PosixPath('/tmp/good.csv')): success
scan_csv(PosixPath('/tmp/good.csv')): success

read_csv(PosixPath('/tmp/bad.csv')): ERROR calling function: No such file or directory (os error 2): /tmp/bad.csv
scan_csv(PosixPath('/tmp/bad.csv')): ERROR after collect(): No such file or directory (os error 2): /tmp/bad.csv

read_csv(PosixUPath('/tmp/good.csv')): success
scan_csv(PosixUPath('/tmp/good.csv')): success

read_csv(PosixUPath('/tmp/bad.csv')): ERROR calling function: No such file or directory (os error 2): /tmp/bad.csv
scan_csv(PosixUPath('/tmp/bad.csv')): ERROR after collect(): No such file or directory (os error 2): /tmp/bad.csv

read_csv('file:///tmp/good.csv'): ERROR calling function: No such file or directory (os error 2): file:///tmp/good.csv
scan_csv('file:///tmp/good.csv'): success

read_csv('file:///tmp/bad.csv'): ERROR calling function: No such file or directory (os error 2): file:///tmp/bad.csv
scan_csv('file:///tmp/bad.csv'): ERROR after collect(): Object at location /tmp/bad.csv not found: No such file or directory (os error 2)

read_csv('local:///tmp/good.csv'): success with warning: Polars found a filename. Ensure you pass a path to the file instead of a python file object when possible for best performance.
scan_csv('local:///tmp/good.csv'): ERROR calling function: unknown url scheme

read_csv('local:///tmp/bad.csv'): ERROR calling function: [Errno 2] No such file or directory: '/tmp/bad.csv'
scan_csv('local:///tmp/bad.csv'): ERROR calling function: unknown url scheme

read_csv('https://minnozz.com/good.csv'): success
scan_csv('https://minnozz.com/good.csv'): success

read_csv('https://minnozz.com/bad.csv'): ERROR calling function: HTTP Error 404: Not Found
scan_csv('https://minnozz.com/bad.csv'): ERROR after collect(): Object at location  not found: Client error with status 404 Not Found: No Body

read_csv(HTTPPath('https://minnozz.com/good.csv')): ERROR calling function: No such file or directory (os error 2): https://minnozz.com/good.csv
scan_csv(HTTPPath('https://minnozz.com/good.csv')): success

read_csv(HTTPPath('https://minnozz.com/bad.csv')): ERROR calling function: No such file or directory (os error 2): https://minnozz.com/bad.csv
scan_csv(HTTPPath('https://minnozz.com/bad.csv')): ERROR after collect(): Object at location  not found: Client error with status 404 Not Found: No Body
```
