### ISSUE TITLE
head() on a lazy opened parquet leads to panic: called `Option::unwrap()` on a `None` value

### ISSUE THREAD

**Issue by testmannono** [pola-rs/polars#19158]
### Checks

- [X] I have checked that this issue has not already been reported.
- [X] I have confirmed this bug exists on the [latest version](https://pypi.org/project/polars/) of Polars.

### Reproducible example

```python

import polars as pl

pl.scan_parquet(["https://ftp.ebi.ac.uk/pub/databases/opentargets/platform/24.09/output/etl/parquet/molecule/part-00000-a8f22a42-0a15-4e45-9b89-aeb8a530174e-c000.snappy.parquet"]).head(5).collect()
```

### Log output

```shell
$ POLARS_VERBOSE=1 RUST_BACKTRACE=1 python error.py

Async thread count: 4
POLARS PREFETCH_SIZE: 48
querying metadata of 1/1 files...
reading of 1/1 file...
POLARS ROW_GROUP PREFETCH_SIZE: 128
thread 'polars-2' panicked at crates/polars-parquet/src/arrow/read/deserialize/nested_utils.rs:159:51:
called `Option::unwrap()` on a `None` value
stack backtrace:
   0: rust_begin_unwind
   1: core::panicking::panic_fmt
   2: core::panicking::panic
   3: core::option::unwrap_failed
   4: polars_parquet::arrow::read::deserialize::nested_utils::extend_offsets_limited
   5: polars_parquet::arrow::read::deserialize::nested_utils::extend_offsets2
   6: polars_parquet::arrow::read::deserialize::nested_utils::PageNestedDecoder<D>::collect_n
   7: polars_parquet::arrow::read::deserialize::nested::columns_to_iter_recursive
   8: polars_parquet::arrow::read::deserialize::nested::columns_to_iter_recursive
   9: polars_parquet::arrow::read::deserialize::nested::columns_to_iter_recursive::{{closure}}
  10: polars_parquet::arrow::read::deserialize::nested::columns_to_iter_recursive
  11: polars_io::parquet::read::read_impl::column_idx_to_series
  12: rayon::iter::plumbing::bridge_producer_consumer::helper
  13: rayon_core::join::join_context::{{closure}}
  14: rayon::iter::plumbing::bridge_producer_consumer::helper
  15: <rayon_core::job::StackJob<L,F,R> as rayon_core::job::Job>::execute
  16: rayon_core::registry::WorkerThread::wait_until_cold
  17: rayon_core::join::join_context::{{closure}}
  18: rayon::iter::plumbing::bridge_producer_consumer::helper
  19: rayon_core::join::join_context::{{closure}}
  20: rayon::iter::plumbing::bridge_producer_consumer::helper
  21: <rayon_core::job::StackJob<L,F,R> as rayon_core::job::Job>::execute
  22: rayon_core::registry::WorkerThread::wait_until_cold
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
thread 'polars-7' panicked at crates/polars-parquet/src/arrow/read/deserialize/nested_utils.rs:159:51:
called `Option::unwrap()` on a `None` value
stack backtrace:
   0: rust_begin_unwind
   1: core::panicking::panic_fmt
   2: core::panicking::panic
   3: core::option::unwrap_failed
   4: polars_parquet::arrow::read::deserialize::nested_utils::extend_offsets_limited
   5: polars_parquet::arrow::read::deserialize::nested_utils::extend_offsets2
   6: polars_parquet::arrow::read::deserialize::nested_utils::PageNestedDecoder<D>::collect_n
   7: polars_parquet::arrow::read::deserialize::nested::columns_to_iter_recursive
   8: polars_parquet::arrow::read::deserialize::nested::columns_to_iter_recursive
   9: polars_parquet::arrow::read::deserialize::nested::columns_to_iter_recursive::{{closure}}
  10: polars_parquet::arrow::read::deserialize::nested::columns_to_iter_recursive
  11: polars_io::parquet::read::read_impl::column_idx_to_series
  12: rayon::iter::plumbing::bridge_producer_consumer::helper
  13: rayon_core::join::join_context::{{closure}}
  14: rayon::iter::plumbing::bridge_producer_consumer::helper
  15: <rayon_core::job::StackJob<L,F,R> as rayon_core::job::Job>::execute
  16: rayon_core::registry::WorkerThread::wait_until_cold
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
Rayon: detected unexpected panic; aborting
Aborted
```
```


### Issue description

Lazy opening one public parquet file leads to a rust panic.

### Expected behavior

No panic.

### Installed versions

<details>

```
>>> pl.show_versions()
--------Version info---------
Polars:              1.9.0
Index type:          UInt32
Platform:            Linux-6.9.10-1rodete5-amd64-x86_64-with-glibc2.38
Python:              3.11.9 (main, Jul  8 2024, 08:29:22) [GCC 13.2.0]

----Optional dependencies----
adbc_driver_manager  <not installed>
altair               <not installed>
cloudpickle          <not installed>
connectorx           <not installed>
deltalake            <not installed>
fastexcel            <not installed>
fsspec               2024.9.0
gevent               <not installed>
great_tables         <not installed>
matplotlib           <not installed>
nest_asyncio         1.6.0
numpy                1.26.4
openpyxl             <not installed>
pandas               2.2.3
pyarrow              16.1.0
pydantic             2.9.2
pyiceberg            <not installed>
sqlalchemy           <not installed>
torch                <not installed>
xlsx2csv             <not installed>
xlsxwriter           <not installed>
```

</details>

**Comment by testmannono** [comment]
This panic is very unfortunate, since I can not catch this panic somehow, the python process just aborts.

E.g. trying to catch this somehow (i get the same with `PanicException`):

```python
import polars as pl

try:
  pl.scan_parquet(["https://ftp.ebi.ac.uk/pub/databases/opentargets/platform/24.09/output/etl/parquet/molecule/part-00000-a8f22a42-0a15-4e45-9b89-aeb8a530174e-c000.snappy.parquet"]).head(5).collect()
except Exception as e:
  print(f"Caught this: {e}")
print("Still alive!")
```

Leads to 

```
thread 'polars-21' panicked at crates/polars-parquet/src/arrow/read/deserialize/nested_utils.rs:159:51:
called `Option::unwrap()` on a `None` value
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
thread 'polars-14' panicked at crates/polars-parquet/src/arrow/read/deserialize/nested_utils.rs:159:51:
called `Option::unwrap()` on a `None` value
Rayon: detected unexpected panic; aborting
Aborted
```

**Comment by cmdlineluser** [comment]
Can reproduce. 

Saving the file locally and using `.read_parquet()` also generates the panic.

DuckDB can read the file OK:

```python
df = duckdb.sql("""
from 'https://ftp.ebi.ac.uk/pub/databases/opentargets/platform/24.09/output/etl/parquet/molecule/part-00000-a8f22a42-0a15-4e45-9b89-aeb8a530174e-c000.snappy.parquet'
""").pl()
```

(It may serve as an alternative way to get a Polars DataFrame until the devs fix this.)

**Comment by orlp** [comment]
@coastalwhite Can you take a look?
