### ISSUE TITLE
Columns not in correct order due to caching using LazyFrames

### ISSUE THREAD

**Issue by niekrongen** [pola-rs/polars#19227]
### Checks

- [X] I have checked that this issue has not already been reported.
- [X] I have confirmed this bug exists on the [latest version](https://pypi.org/project/polars/) of Polars.

### Reproducible example

```python
from random import choice, randrange
from string import ascii_lowercase, ascii_uppercase, digits

import polars as pl

pl.show_versions()

chars = ascii_lowercase + digits, ascii_uppercase

lf1 = pl.LazyFrame(
    {
        "column_1": ["".join(choice(chars) for _ in range(4)) for _ in range(1000)],
        "column_2": ["".join(choice(chars) for _ in range(4)) for _ in range(1000)],
        "column_3": ["".join(choice(chars) for _ in range(4)) for _ in range(1000)],
        "column_4": ["".join(choice(chars) for _ in range(4)) for _ in range(1000)],
        "column_5": [choice(chars) for _ in range(1000)],
        "column_6": [choice(chars) for _ in range(1000)],
        "column_7": [str(randrange(500, 800)) for _ in range(1000)],
        "column_8": ["".join(choice(chars) for _ in range(4)) for _ in range(1000)],
        "column_9": [randrange(2000, 3000) for _ in range(1000)],
    }
)

lazyframe_1 = lf1.with_columns(
    pl.concat_str(pl.col("column_1", "column_2"), separator="-").alias("%C"),
    pl.concat_str(pl.col("column_3", "column_4"), separator="-").alias("%B"),
).select("%C", "%B")

lazyframe_2 = lf1.with_columns(
    pl.concat_str(pl.col("column_1", "column_2"), separator="-").alias("%C"),
    pl.concat_str(pl.col("column_3", "column_4"), separator="-").alias("%A"),
).select("%C", "%A")

lazyframe_3 = (
    lf1.with_columns(
        pl.concat_str(pl.col("column_1", "column_2"), separator="-").alias("%C"),
        pl.concat_str(pl.col("column_3", "column_4"), separator="-").alias("%RLN"),
    )
    .select("%C", "%RLN")
    .join(
        lf1.with_columns(
            pl.concat_str(pl.col("column_1", "column_2"), separator="-").alias("%RLN"),
            pl.concat_str(pl.col("column_3", "column_4"), separator="-").alias("%A"),
        ).select("%RLN", "%A"),
        on="%RLN",
        how="left",
    )
    .select("%C", "%A")
)

lazyframe_4 = (
    lf1.with_columns(
        pl.concat_str(pl.col("column_1", "column_2"), separator="-").alias("%lp"),
        pl.concat_str(pl.col("column_3", "column_4"), separator="-").alias("%A"),
    )
    .select("%lp", "%A")
    .join(
        lf1.with_columns(
            pl.concat_str(pl.col("column_1", "column_2"), separator="-").alias("%lp"),
            pl.concat_str(pl.col("column_3", "column_4"), separator="-").alias("%B"),
        ).select("%lp", "%B"),
        on="%lp",
        how="left",
    )
    .select("%A", "%B")
)


lazyframe_5 = (
    lf1.with_columns(
        pl.concat_str(pl.col("column_1", "column_2"), separator="-").alias("%lp"),
        pl.concat_str(pl.col("column_3", "column_4"), separator="-").alias("%A"),
    )
    .select("%lp", "%A")
    .join(
        lf1.with_columns(
            pl.concat_str(pl.col("column_1", "column_2"), separator="-").alias("%lp"),
            pl.concat_str(pl.col("column_3", "column_4"), separator="-").alias("%B"),
        ).select("%lp", "%B"),
        on="%lp",
        how="left",
    )
    .select("%A", "%B")
)


direct = (
    pl.concat(
        [
            lazyframe_2,
            lazyframe_3,
        ],
        how="vertical_relaxed",
    )
    .join(
        pl.concat(
            [
                lazyframe_4,
                lazyframe_5,
            ],
            how="vertical_relaxed",
        ).filter(pl.col("%A").is_not_null() & pl.col("%B").is_not_null()),
        on="%A",
        how="full",
        coalesce=True,
    )
    .select("%C", "%A", "%B")
)


indirect = (
    lazyframe_1.join(
        direct.filter(pl.col("%C").is_not_null() & pl.col("%B").is_not_null()).select(
            "%C", "%B"
        ),
        on=["%C", "%B"],
        how="anti",
    )
    .with_columns(pl.lit(None, pl.String).alias("%A"))
    .select("%C", "%A", "%B")
)

final_lf = pl.concat([direct, indirect])
other_lf = pl.concat([direct.collect().lazy(), indirect.collect().lazy()])
# Can collect
print("collecting other_df")
other_df = other_lf.collect()
# Cannot collect
print("collecting df")
df = final_lf.collect()
```

### Log output

```shell
--------Version info---------
Polars:              1.9.0
Index type:          UInt32
Platform:            Windows-11-10.0.22621-SP0
Python:              3.12.5 (tags/v3.12.5:ff3bc82, Aug  6 2024, 20:45:27) [MSC v.1940 64 bit (AMD64)]

----Optional dependencies----
adbc_driver_manager  <not installed>
altair               <not installed>
cloudpickle          <not installed>
connectorx           0.3.3
deltalake            <not installed>
fastexcel            0.11.6
fsspec               <not installed>
gevent               <not installed>
great_tables         <not installed>
matplotlib           <not installed>
nest_asyncio         <not installed>
numpy                2.1.2
openpyxl             <not installed>
pandas               2.2.3
pyarrow              17.0.0
pydantic             <not installed>
pyiceberg            <not installed>
sqlalchemy           2.0.35
torch                <not installed>
xlsx2csv             <not installed>
xlsxwriter           <not installed>
found multiple sources; run comm_subplan_elim
cache nodes will be removed because predicates don't match
join parallel: false
UNION: union is run in parallel
join parallel: true
LEFT join dataframes finished
UNION: `parallel=false` union is run sequentially
join parallel: true
LEFT join dataframes finished
dataframe filtered
join parallel: true
LEFT join dataframes finished
dataframe filtered
FULL join dataframes finished
found multiple sources; run comm_subplan_elim
join parallel: false
join parallel: false
UNION: union is run in parallel
join parallel: true
LEFT join dataframes finished
UNION: `parallel=false` union is run sequentially
join parallel: true
LEFT join dataframes finished
dataframe filtered
CACHE SET: cache id: 1
CACHE HIT: cache id: 1
FULL join dataframes finished
dataframe filtered
ANTI join dataframes finished
collecting other_df
UNION: union is run in parallel
collecting df
found multiple sources; run comm_subplan_elim
UNION: `parallel=false` union is run sequentially
join parallel: true
UNION: union is run in parallel
UNION: union is run in parallel
join parallel: true
join parallel: true
join parallel: true
dataframe filtered
dataframe filtered
LEFT join dataframes finished
LEFT join dataframes finished
LEFT join dataframes finished
dataframe filtered
dataframe filtered
FULL join dataframes finished
CACHE SET: cache id: 0
join parallel: false
CACHE HIT: cache id: 0
dataframe filtered
ANTI join dataframes finished
Traceback (most recent call last):
  File "C:\Users\niek\project\example.py", line 130, in <module>
    df = final_lf.collect()
         ^^^^^^^^^^^^^^^^^^
  File "C:\Users\niek\project\.venv\Lib\site-packages\polars\lazyframe\frame.py", line 2050, in collect
    return wrap_df(ldf.collect(callback))
                   ^^^^^^^^^^^^^^^^^^^^^
polars.exceptions.ShapeError: unable to vstack, column names don't match: "%A" and "%C"
```

### Issue description

It looks like the select statement at the end of the lazyframe has no influence on the correct order. 
When using final_lf.explain I can see that the ordering of the second lazyframe in the concat function is not correct and that this line is proceeded by the line that makes sure that states that I caches the lazyframe. 
It could be solved with the "align" functionality of the concat function. 
However I would prefer to keep the same order of columns as this is the default and wanted behavior.
When using align I would guess that any or even a random alignment of columns can be the output which can probably lead to unexpected behavior due to possibly select statements not working as intended. 

### Expected behavior

Select statements should always result in the expected order of columns. 

### Installed versions

<details>

```
--------Version info---------
Polars:              1.9.0
Index type:          UInt32
Platform:            Windows-11-10.0.22621-SP0
Python:              3.12.5 (tags/v3.12.5:ff3bc82, Aug  6 2024, 20:45:27) [MSC v.1940 64 bit (AMD64)]

----Optional dependencies----
adbc_driver_manager  <not installed>
altair               <not installed>
cloudpickle          <not installed>
connectorx           0.3.3
deltalake            <not installed>
fastexcel            0.11.6
fsspec               <not installed>
gevent               <not installed>
great_tables         <not installed>
matplotlib           <not installed>
nest_asyncio         <not installed>
numpy                2.1.2
openpyxl             <not installed>
pandas               2.2.3
pyarrow              17.0.0
pydantic             <not installed>
pyiceberg            <not installed>
sqlalchemy           2.0.35
torch                <not installed>
xlsx2csv             <not installed>
xlsxwriter           <not installed>
```

</details>

**Comment by cmdlineluser** [comment]
Can reproduce.

It works with the `comm_subplan_elim` optimization turned off.

```python
import polars as pl

lf = pl.LazyFrame({ "A": [1], "B": [2]})

lf_1 = lf.select(C = "A", B = "B")
lf_2 = lf.select(C = "A", A = "B")

lf_3 = (
    lf.select(LP = "A", A = "B")
      .join(
          lf.select(LP = "A", B = "B"),
          on="LP",
      )
      .select("A", "B")
)

direct = (
    lf_2
     .join(lf, on="A")
     .select("C", "A", "B")
)

indirect = (
    lf_1
     .join(direct, on=["C", "B"])
     .select("C", "A", "B")
)

out = pl.concat([direct, indirect])
```
```python
out.collect()
# ShapeError: unable to vstack, column names don't match: "A" and "C"
```
```python
out.collect(comm_subplan_elim=False)
# shape: (0, 3)
# ┌─────┬─────┬─────┐
# │ C   ┆ A   ┆ B   │
# │ --- ┆ --- ┆ --- │
# │ i64 ┆ i64 ┆ i64 │
# ╞═════╪═════╪═════╡
# └─────┴─────┴─────┘
```
