### ISSUE TITLE
allow_missing_columns seems to break pushdown of column select in scan_parquet

### ISSUE THREAD

**Issue by jingo64** [pola-rs/polars#19249]
### Checks

- [X] I have checked that this issue has not already been reported.
- [X] I have confirmed this bug exists on the [latest version](https://pypi.org/project/polars/) of Polars.

### Reproducible example

```python
import polars as pl

df1 = pl.DataFrame({"A": 1, "B": 2, "C": "mismatched_type"})

df2 = pl.DataFrame({"A": 1, "B": 2, "C": 3})

df1.write_parquet("test1")

df2.write_parquet("test2")
try:
    pl.scan_parquet(["test1", "test2"]).collect()
except pl.exceptions.SchemaError:
    print("failed as expected")  # would expect this to fail as the schema is mismatched


pl.scan_parquet(["test1", "test2"]).select(["A", "B"]).collect()  # works fine
pl.scan_parquet(["test1", "test2"], allow_missing_columns=True).select(
    ["A", "B"]
).collect()  # fails - wouldn't expect a failure as we don't care about column C

```

### Log output

```shell
Traceback (most recent call last):
  File "/home/dmeadows/code/phoenix/david_stuff/pushdown_bug.py", line 19, in <module>
    ).collect()  # fails - wouldn't expect a failure as we don't care about column C
      ^^^^^^^^^
  File "/home/dmeadows/code/phoenix/pyenv/lib/python3.11/site-packages/polars/lazyframe/frame.py", line 2050, in collect
    return wrap_df(ldf.collect(callback))
                   ^^^^^^^^^^^^^^^^^^^^^
polars.exceptions.SchemaError: dtypes differ for column C: Int64 != Utf8View
```

### Issue description

I'd expect allow_missing_columns to add any columns requested in the query if some of the parquet files are missing it. It seems to be causing an issue where its trying to read columns that shouldn't be looked up - in this case, the select should only cause us to read data from columns A and B, but its seemingly trying to figure out something related to C. 

This is a toy example, but in my larger codebase, it seems to be causing reads to happen across all columns of parquet files which is problematic as the files are very wide, and most of the time we just want 1-2 columns.

### Expected behavior

allow_missing_columns shouldn't cause columns not selected in the query to be read

### Installed versions

<details>

```
--------Version info---------
Polars:              1.9.0
Index type:          UInt32
Platform:            Linux-6.1.109-x86_64-with-glibc2.31
Python:              3.11.3 (main, May 15 2023, 15:45:52) [GCC 11.2.0]

----Optional dependencies----
adbc_driver_manager  <not installed>
altair               <not installed>
cloudpickle          <not installed>
connectorx           <not installed>
deltalake            0.18.2
fastexcel            <not installed>
fsspec               2023.6.0
gevent               <not installed>
great_tables         <not installed>
matplotlib           3.7.2
nest_asyncio         1.6.0
numpy                1.24.4
openpyxl             <not installed>
pandas               2.0.2
pyarrow              12.0.1
pydantic             <not installed>
pyiceberg            <not installed>
sqlalchemy           1.4.46
torch                <not installed>
xlsx2csv             <not installed>
xlsxwriter           <not installed>
```

</details>

**Comment by jingo64** [comment]
I'm not sure if this is the same issue as https://github.com/pola-rs/polars/issues/19205 which seemed like the closest current issue to this one, so created it separately in case its distinct!

**Comment by coastalwhite** [comment]
@nameexhaustion could you have a look at this?
