### ISSUE TITLE
Failed extract number with small float number lead to `could not extract number from any-value of dtype: 'List(Int64)'`

### ISSUE THREAD

**Issue by thuyetbao** [pola-rs/polars#19243]
### Checks

- [X] I have checked that this issue has not already been reported.
- [X] I have confirmed this bug exists on the [latest version](https://pypi.org/project/polars/) of Polars.

### Reproducible example

```python

# Import
import polars as pl

# Check version
print(pl.__version__)

# Sample dataset with List(Float64)
df = pl.DataFrame({"a": [[0.1, 0.2, 0.3]]})

# Get the first value of the list with column `c`
df.with_columns(pl.lit([0]).alias("c")).with_columns(gather=pl.col("a").list.gather(pl.col("c"), null_on_oob=True))
```

### Log output

```shell
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "D:\PROJECT\app-flareon\venv\lib\site-packages\polars\dataframe\frame.py", line 9183, in with_columns
    return self.lazy().with_columns(*exprs, **named_exprs).collect(_eager=True)
  File "D:\PROJECT\app-flareon\venv\lib\site-packages\polars\lazyframe\frame.py", line 2050, in collect
    return wrap_df(ldf.collect(callback))
polars.exceptions.ComputeError: could not extract number from any-value of dtype: 'List(Int64)'
```

### Issue description

The method `list.gather` failed when extract small float number in the `List(Float64)`

### Expected behavior

It should return the first value of the list

```python
┌─────────────────┬───────────┐
│ a               ┆ gather    │
│ ---             ┆ ---       │
│ list[f64]       ┆ list[f64] │
╞═════════════════╪═══════════╡
│ [0.1, 0.2, 0.3] ┆ [0.1]     │
└─────────────────┴───────────┘
```

### Installed versions

<details>

```python
pl.show_versions()
--------Version info---------
Polars:              1.9.0
Index type:          UInt32
Platform:            Windows-10-10.0.22631-SP0
Python:              3.9.13 (tags/v3.9.13:6de2ca5, May 17 2022, 16:36:42) [MSC v.1929 64 bit (AMD64)]

----Optional dependencies----
adbc_driver_manager  <not installed>
altair               <not installed>
cloudpickle          <not installed>
connectorx           <not installed>
deltalake            <not installed>
fastexcel            0.11.5
fsspec               <not installed>
gevent               <not installed>
great_tables         <not installed>
matplotlib           <not installed>
nest_asyncio         <not installed>
numpy                2.0.1
openpyxl             3.1.5
pandas               2.2.2
pyarrow              16.1.0
pydantic             2.7.4
pyiceberg            <not installed>
sqlalchemy           2.0.32
torch                <not installed>
xlsx2csv             0.8.3
xlsxwriter           3.2.0
```

</details>

**Comment by orlp** [comment]
Reproduced, interestingly it only causes the error when `null_on_oob=True` is specified.
