### ISSUE TITLE
`list.contains(None)` fails

### ISSUE THREAD

**Issue by guyrosin** [pola-rs/polars#19332]
### Checks

- [X] I have checked that this issue has not already been reported.
- [X] I have confirmed this bug exists on the [latest version](https://pypi.org/project/polars/) of Polars.

### Reproducible example

```python
import polars as pl

pl.DataFrame({"a": [[1, 2], [3, None]]}).with_columns(pl.col("a").list.contains(None))  # <-- raises InvalidOperationError
```

### Log output

```shell
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/guy/code/playground/.venv/lib/python3.12/site-packages/polars/dataframe/frame.py", line 9194, in with_columns
    return self.lazy().with_columns(*exprs, **named_exprs).collect(_eager=True)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/guy/code/playground/.venv/lib/python3.12/site-packages/polars/lazyframe/frame.py", line 2055, in collect
    return wrap_df(ldf.collect(callback))
                   ^^^^^^^^^^^^^^^^^^^^^
polars.exceptions.InvalidOperationError: Series a, length 1 doesn't match the DataFrame height of 2

If you want expression: col("a").list.contains([null]) to be broadcasted, ensure it is a scalar (for instance by adding '.first()').
```

### Issue description

Checking if sublists contain nulls fails.

### Expected behavior

I expected the method to support nulls.

### Installed versions

<details>

```
--------Version info---------
Polars:              1.10.0
Index type:          UInt32
Platform:            macOS-15.0.1-arm64-arm-64bit
Python:              3.12.7 (main, Oct  7 2024, 23:45:10) [Clang 18.1.8 ]
LTS CPU:             False

----Optional dependencies----
adbc_driver_manager  <not installed>
altair               5.4.1
cloudpickle          3.1.0
connectorx           <not installed>
deltalake            <not installed>
fastexcel            0.12.0
fsspec               2024.9.0
gevent               <not installed>
great_tables         <not installed>
matplotlib           3.9.2
nest_asyncio         1.6.0
numpy                2.0.2
openpyxl             <not installed>
pandas               2.2.3
pyarrow              17.0.0
pydantic             2.9.2
pyiceberg            <not installed>
sqlalchemy           2.0.36
torch                2.5.0
xlsx2csv             0.8.3
xlsxwriter           <not installed>
```

</details>

**Comment by orlp** [comment]
This is just a matter of supporting the Python syntax properly, `.list.contains(pl.lit(None, dtype=pl.Int32))` works.

**Comment by PaulieDesigns** [comment]
I'd like to work on this if no one else is!

**Comment by cmdlineluser** [comment]
I think it was already fixed.

```python
(pl.DataFrame({"a": [[1, 2], [3, None]]})
   .with_columns(pl.col("a").list.contains(None))
)  

# shape: (2, 1)
# ┌───────┐
# │ a     │
# │ ---   │
# │ bool  │
# ╞═══════╡
# │ false │
# │ true  │
# └───────┘
```
