### ISSUE TITLE
`group_by().agg()` may cause panic when the number of rows in the original data frame is 15 or more

### ISSUE THREAD

**Issue by eitsupi** [pola-rs/polars#19337]
### Checks

- [X] I have checked that this issue has not already been reported.
- [X] I have confirmed this bug exists on the [latest version](https://crates.io/crates/polars) of Polars.

### Reproducible example

```rust
fn main() {
    use polars::df;
    use polars::prelude::*;

    let df = df![
        // "a" => [0; 14], // <- It works
        "a" => [0; 15], // <- Causes panic
    ]
    .unwrap();
    let out = df
        .lazy()
        .group_by([lit(Series::new("".into(), [1, 2])), lit(true).alias("foo")])
        .agg([])
        .collect()
        .unwrap();
    println!("{:?}", out);
}
```

### Log output

```shell
Finished `dev` profile [unoptimized + debuginfo] target(s) in 0.09s
     Running `target/debug/polars-agg-test`
thread 'main' panicked at /usr/local/cargo/registry/src/index.crates.io-6f17d22bba15001f/polars-mem-engine-0.43.1/src/executors/group_by_partitioned.rs:157:37:
called `Result::unwrap()` on an `Err` value: ShapeMismatch(ErrString("series used as keys should have the same length as the DataFrame"))
stack backtrace:
   0: rust_begin_unwind
             at /rustc/eeb90cda1969383f56a2637cbd3037bdf598841c/library/std/src/panicking.rs:665:5
   1: core::panicking::panic_fmt
             at /rustc/eeb90cda1969383f56a2637cbd3037bdf598841c/library/core/src/panicking.rs:74:14
   2: core::result::unwrap_failed
             at /rustc/eeb90cda1969383f56a2637cbd3037bdf598841c/library/core/src/result.rs:1679:5
   3: core::result::Result<T,E>::unwrap
             at /rustc/eeb90cda1969383f56a2637cbd3037bdf598841c/library/core/src/result.rs:1102:23
   4: polars_mem_engine::executors::group_by_partitioned::estimate_unique_count
             at /usr/local/cargo/registry/src/index.crates.io-6f17d22bba15001f/polars-mem-engine-0.43.1/src/executors/group_by_partitioned.rs:157:18
   5: polars_mem_engine::executors::group_by_partitioned::can_run_partitioned
             at /usr/local/cargo/registry/src/index.crates.io-6f17d22bba15001f/polars-mem-engine-0.43.1/src/executors/group_by_partitioned.rs:218:18
   6: polars_mem_engine::executors::group_by_partitioned::PartitionGroupByExec::execute_impl
             at /usr/local/cargo/registry/src/index.crates.io-6f17d22bba15001f/polars-mem-engine-0.43.1/src/executors/group_by_partitioned.rs:262:17
   7: <polars_mem_engine::executors::group_by_partitioned::PartitionGroupByExec as polars_mem_engine::executors::executor::Executor>::execute
             at /usr/local/cargo/registry/src/index.crates.io-6f17d22bba15001f/polars-mem-engine-0.43.1/src/executors/group_by_partitioned.rs:371:13
   8: polars_lazy::frame::LazyFrame::_collect_post_opt
             at /usr/local/cargo/registry/src/index.crates.io-6f17d22bba15001f/polars-lazy-0.43.1/src/frame/mod.rs:678:9
   9: polars_lazy::frame::LazyFrame::collect
             at /usr/local/cargo/registry/src/index.crates.io-6f17d22bba15001f/polars-lazy-0.43.1/src/frame/mod.rs:760:9
  10: polars_agg_test::main
             at ./src/main.rs:10:15
  11: core::ops::function::FnOnce::call_once
             at /rustc/eeb90cda1969383f56a2637cbd3037bdf598841c/library/core/src/ops/function.rs:250:5
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```

### Issue description

Reported in eitsupi/neo-r-polars#23

It seems that depending on the number of rows in the original DataFrame, lazy `group_by().agg()` may cause panic.
This is not reproduced in released versions of Python Polars or R Polars, and may be resolved by some additional feature flag (?).

The panic is came from here.
https://github.com/pola-rs/polars/blob/01e801faa734096b1a4cdf3ec77ecbc521d31e66/crates/polars-mem-engine/src/executors/group_by_partitioned.rs#L161

Strangely this error does not seem to be seen when the number of rows in the original data frame is less than 14.

### Expected behavior

Should not cause panic

### Installed versions

<details>

```toml
[package]
name = "polars-agg-test"
version = "0.1.0"
edition = "2021"

[dependencies.polars]
version = "0.43.1"
features = [
    "lazy",
]
```

</details>

**Comment by dxe4** [comment]
interesting.
i tried to write a python test for this to work on it, but the test does not panic.

```
def test_19337(partition_limit: int) -> None:
    df = pl.DataFrame({
        "a": [0] * (partition_limit + 1)
    })

    out = (
        df.lazy()
        .group_by([
            pl.lit(pl.Series("", [1, 2])),
            pl.lit(True).alias("foo")
        ])
        .agg([])
        .collect()
    )
    print(out)
```

**Comment by eitsupi** [comment]
> interesting.
> i tried to write a python test for this to work on it, but the test does not panic.

Did you build using the dev profile?
If not, the restrictions are far more numerous. see #21634.

**Comment by eitsupi** [comment]
Seems fixed by #21843
