### ISSUE TITLE
polars.exceptions.ComputeError: parquet: Not yet supported: is_min_value_exact in statistics

### ISSUE THREAD

**Issue by aersam** [pola-rs/polars#19342]
### Checks

- [X] I have checked that this issue has not already been reported.
- [X] I have confirmed this bug exists on the [latest version](https://pypi.org/project/polars/) of Polars.

### Reproducible example

```python
import polars as pl

pl.scan_parquet(
    "part-00001-0618c014-7d83-4ef9-9eb2-281f3ed1da89-c000.zstd.parquet"
).filter(pl.col("Age") == 23.0).collect().to_dicts()

```
Here's the file:
[part-00001-0618c014-7d83-4ef9-9eb2-281f3ed1da89-c000.zstd.zip](https://github.com/user-attachments/files/17456400/part-00001-0618c014-7d83-4ef9-9eb2-281f3ed1da89-c000.zstd.zip)

### Log output

```shell
Traceback (most recent call last):
  File "deltalake2db\repo.py", line 5, in <module>
    ).filter(pl.col("Age") == 23.0).collect().to_dicts()
                                    ^^^^^^^^^
  File "C:\Projects\BMS_Github\deltalake2db\.venv\Lib\site-packages\polars\lazyframe\frame.py", line 2055, in collect
    return wrap_df(ldf.collect(callback))
                   ^^^^^^^^^^^^^^^^^^^^^
polars.exceptions.ComputeError: parquet: Not yet supported: is_min_value_exact in statistics
```

### Issue description

I'm fine if polars does not understand all kind of statistics, but it should not fail because of that. I cannot read the parquet file

### Expected behavior

Let me read that file somehow - with or without statistics

### Installed versions

<details>

```
--------Version info---------
Polars:              1.10.0
Index type:          UInt32
Platform:            Windows-10-10.0.19045-SP0
Python:              3.11.1 (tags/v3.11.1:a7a450f, Dec  6 2022, 19:58:39) [MSC v.1934 64 bit (AMD64)]
LTS CPU:             False

----Optional dependencies----
adbc_driver_manager  <not installed>
altair               <not installed>
cloudpickle          <not installed>
connectorx           <not installed>
deltalake            0.18.1
fastexcel            <not installed>
fsspec               2024.10.0
gevent               <not installed>
great_tables         <not installed>
matplotlib           <not installed>
nest_asyncio         <not installed>
numpy                2.1.2
openpyxl             <not installed>
pandas               2.2.3
pyarrow              17.0.0
pydantic             <not installed>
pyiceberg            <not installed>
sqlalchemy           <not installed>
torch                <not installed>
xlsx2csv             <not installed>
xlsxwriter           <not installed>
```

</details>

**Comment by ritchie46** [comment]
@coastalwhite

**Comment by coastalwhite** [comment]
Interestingly enough, pyarrow's parquet reader (which I commonly use as a reference) also doesn't seem to accept these statistics.
