### ISSUE TITLE
Broken in 1.10.0: Cannot extract struct values within list

### ISSUE THREAD

**Issue by aersam** [pola-rs/polars#19345]
### Checks

- [X] I have checked that this issue has not already been reported.
- [X] I have confirmed this bug exists on the [latest version](https://pypi.org/project/polars/) of Polars.

### Reproducible example

```python

print(
    pl.DataFrame(
        [
            {
                "a": [
                    {
                        "b": 1.0,
                        "c": 4,
                    }
                ]
            }
        ],
        {
            "a": pl.List(
                pl.Struct(
                    {
                        "b": pl.Float64(),
                        "c": pl.Float64(),
                    }
                )
            ),
        },
    ).select(
        pl.col("a").list.eval(
            pl.element().struct.field("b"),
        )
    )
)
```

### Log output

```shell
Traceback (most recent call last):
  File "C:\Projects\BMS_Github\deltalake2db\repo.py", line 25, in <module>
    ).select(
      ^^^^^^^
  File "C:\Projects\BMS_Github\deltalake2db\.venv\Lib\site-packages\polars\dataframe\frame.py", line 9021, in select
    return self.lazy().select(*exprs, **named_exprs).collect(_eager=True)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Projects\BMS_Github\deltalake2db\.venv\Lib\site-packages\polars\lazyframe\frame.py", line 2055, in collect
    return wrap_df(ldf.collect(callback))
                   ^^^^^^^^^^^^^^^^^^^^^
polars.exceptions.ColumnNotFoundError
```

### Issue description

This should work as it did up to 1.9.0

### Expected behavior

Print the dataframe

### Installed versions

<details>

```
--------Version info---------
Polars:              1.10.0
Index type:          UInt32
Platform:            Windows-10-10.0.19045-SP0
Python:              3.11.1 (tags/v3.11.1:a7a450f, Dec  6 2022, 19:58:39) [MSC v.1934 64 bit (AMD64)]
LTS CPU:             False

----Optional dependencies----
adbc_driver_manager  <not installed>
altair               <not installed>
cloudpickle          <not installed>
connectorx           <not installed>
deltalake            0.18.1
fastexcel            <not installed>
fsspec               2024.10.0
gevent               <not installed>
great_tables         <not installed>
matplotlib           <not installed>
nest_asyncio         <not installed>
numpy                2.1.2
openpyxl             <not installed>
pandas               2.2.3
pyarrow              17.0.0
pydantic             <not installed>
pyiceberg            <not installed>
sqlalchemy           <not installed>
torch                <not installed>
xlsx2csv             <not installed>
xlsxwriter           <not installed>
```

</details>

**Comment by cmdlineluser** [comment]
It seems there is now some general breakage due to how `pl.element()` is currently implemented. 

```ipython
>>> print(pl.element())
col("")
```

https://github.com/pola-rs/polars/issues/19317

**Comment by aersam** [comment]
If pl.element is completely broken, I really hope for a fast bug fix... This could break lots of stuff

**Comment by ritchie46** [comment]
Can we get a bisect here?

**Comment by cmdlineluser** [comment]
@ritchie46 It seemed to be https://github.com/pola-rs/polars/pull/19195 to me.

(I posted some extra details in https://github.com/pola-rs/polars/issues/19317)

**Comment by adamreeve** [comment]
We've also hit this regression and I can confirm it is caused by #19195, this works with the parent commit (1cc2cb80e7) but fails with 251e171c23.
