### ISSUE TITLE
Parquet does not support writing empty structs for Polars 1.10.0

### ISSUE THREAD

**Issue by GibbonJojo** [pola-rs/polars#19352]
### Checks

- [X] I have checked that this issue has not already been reported.
- [X] I have confirmed this bug exists on the [latest version](https://pypi.org/project/polars/) of Polars.

### Reproducible example

```python
>>> import polars as pl
>>> data = [
...     {"name": "one", "attr": {}},
...     {"name": "two", "attr": {}}
... ]
>>> df = pl.DataFrame(data)
>>> df
shape: (2, 2)
┌──────┬───────────┐
│ name ┆ attr      │
│ ---  ┆ ---       │
│ str  ┆ struct[0] │
╞══════╪═══════════╡
│ one  ┆ {}        │
│ two  ┆ {}        │
└──────┴───────────┘
>>> df.write_parquet("test.pq")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/jo/miniconda3/envs/test/lib/python3.9/site-packages/polars/dataframe/frame.py", line 3847, in write_parquet
    self._df.write_parquet(
polars.exceptions.InvalidOperationError: Parquet does not support writing empty structs

```

### Issue description

This worked in 1.9:
```python
# polars 1.9.0
>>> data = [
...     {"name": "one", "attr": {}},
...     {"name": "two", "attr": {}}
... ]
>>> df = pl.DataFrame(data)
>>> df
shape: (2, 2)
┌──────┬───────────┐
│ name ┆ attr      │
│ ---  ┆ ---       │
│ str  ┆ struct[1] │
╞══════╪═══════════╡
│ one  ┆ null      │
│ two  ┆ null      │
└──────┴───────────┘
>>> df.write_parquet("test.pq")
```
Apparently the dtype for all-empty structs changed from struct[1] to struct[0] as well

There's also a difference in fetching the structs:

```python
# polars 1.10.0
>>> df.row(0)
('one', {})

# polars 1.9.0
>>> df.row(0)
('one', None)
```

---

It also works when atleast one struct/dict is not empty:

```python
# polars 1.10.0
>>> data = [
...     {"name": "one", "attr": {}},
...     {"name": "two", "attr": {"foo": "bar"}}
... ]
>>> df = pl.DataFrame(data)
>>> df
shape: (2, 2)
┌──────┬───────────┐
│ name ┆ attr      │
│ ---  ┆ ---       │
│ str  ┆ struct[1] │
╞══════╪═══════════╡
│ one  ┆ {null}    │
│ two  ┆ {"bar"}   │
└──────┴───────────┘
>>> df.write_parquet("test.pq")
```

### Expected behavior

Polars 1.10 should write the empty structs, just as 1.9 did

### Installed versions

<details>

```
>>> pl.show_versions()
--------Version info---------
Polars:              1.10.0
Index type:          UInt32
Platform:            Linux-6.8.0-45-generic-x86_64-with-glibc2.35
Python:              3.9.20 | packaged by conda-forge | (main, Sep 30 2024, 17:49:10) 
[GCC 13.3.0]
LTS CPU:             False

----Optional dependencies----
adbc_driver_manager  <not installed>
altair               <not installed>
cloudpickle          <not installed>
connectorx           <not installed>
deltalake            <not installed>
fastexcel            <not installed>
fsspec               <not installed>
gevent               <not installed>
great_tables         <not installed>
matplotlib           <not installed>
nest_asyncio         <not installed>
numpy                2.0.2
openpyxl             <not installed>
pandas               2.2.3
pyarrow              17.0.0
pydantic             2.9.2
pyiceberg            <not installed>
sqlalchemy           <not installed>
torch                <not installed>
xlsx2csv             <not installed>
xlsxwriter           <not installed>

```

</details>

**Comment by ritchie46** [comment]
@coastalwhite

**Comment by GibbonJojo** [comment]
I don't think breaking changes should be introduced in minor versions.

**Comment by ritchie46** [comment]
> I don't think breaking changes should be introduced in minor versions.

You don't have to state the obvious. We understand that. This is due to a bug fix and those have side effects.
