### ISSUE TITLE
Incorrect parsing of scientific notation when converting `pl.String` to `pl.Decimal`

### ISSUE THREAD

**Issue by plaflamme** [pola-rs/polars#19367]
### Checks

- [X] I have checked that this issue has not already been reported.
- [X] I have confirmed this bug exists on the [latest version](https://pypi.org/project/polars/) of Polars.

### Reproducible example

```python
pl.read_csv(io.StringIO("f\n6.4E2"), schema_overrides={"f": pl.Decimal(scale=2)})
```

### Log output

```shell
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File ".venv/lib/python3.11/site-packages/polars/_utils/deprecation.py", line 92, in wrapper
    return function(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File ".venv/lib/python3.11/site-packages/polars/_utils/deprecation.py", line 92, in wrapper
    return function(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File ".venv/lib/python3.11/site-packages/polars/_utils/deprecation.py", line 92, in wrapper
    return function(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File ".venv/lib/python3.11/site-packages/polars/io/csv/functions.py", line 506, in read_csv
    df = _read_csv_impl(
         ^^^^^^^^^^^^^^^
  File ".venv/lib/python3.11/site-packages/polars/io/csv/functions.py", line 651, in _read_csv_impl
    pydf = PyDataFrame.read_csv(
           ^^^^^^^^^^^^^^^^^^^^^
polars.exceptions.InvalidOperationError: conversion from `str` to `decimal[*,2]` failed in column 'f' for 1 out of 1 values: ["6.4E2"]
```
```


### Issue description

Note that setting scale to 0 or 1 successfully parses the number, but the result is wrong:

```python
pl.read_csv(io.StringIO("f\n6.4E2"), schema_overrides={"f": pl.Decimal(scale=0)})
```

```
shape: (1, 1)
┌──────────────┐
│ f            │
│ ---          │
│ decimal[*,0] │
╞══════════════╡
│ 6            │
└──────────────┘
```

### Expected behavior

The number should be parsed as `640` as a `pl.Decimal`

### Installed versions

<details>

```
--------Version info---------
Polars:              1.10.0
Index type:          UInt32
Platform:            macOS-14.7-arm64-arm-64bit
Python:              3.11.9 (main, Apr  2 2024, 08:25:04) [Clang 16.0.6 ]
LTS CPU:             False

----Optional dependencies----
adbc_driver_manager  <not installed>
altair               <not installed>
cloudpickle          <not installed>
connectorx           <not installed>
deltalake            <not installed>
fastexcel            <not installed>
fsspec               2024.10.0
gevent               <not installed>
great_tables         <not installed>
matplotlib           <not installed>
nest_asyncio         <not installed>
numpy                2.1.2
openpyxl             <not installed>
pandas               <not installed>
pyarrow              17.0.0
pydantic             <not installed>
pyiceberg            <not installed>
sqlalchemy           <not installed>
torch                <not installed>
xlsx2csv             <not installed>
xlsxwriter           <not installed>
```

</details>

**Comment by plaflamme** [comment]
Also note that `str.to_decimal` also fails to parse these numbers:

```python
pl.Series("f", ["6.4", "6.4E2"]).str.to_decimal()
```
```
shape: (2,)
Series: 'f' [decimal[*,3]]
[
	6.400
	null
]
```

**Comment by orlp** [comment]
That `6.4E2` parses with `scale = 0` is a bug, it chops off the remainder of the string without checking that what it chops off were indeed digits.

But besides that, none of this is a bug because `pl.Decimal` does not support being parsed from scientific notation at the moment.

**Comment by plaflamme** [comment]
> But besides that, none of this is a bug because pl.Decimal does not support being parsed from scientific notation at the moment.

Ok, is there an issue tracking this limitation? I couldn't find anything. If not, should I create one?

**Comment by tooptoop4** [comment]
"pl.Decimal does not support being parsed from scientific notation" 🙏

**Comment by almostintuitive** [comment]
We're also bumping into this, native support (like with Float64) would make our lives a lot easier!
