### ISSUE TITLE
PanicException when concatenating IPC files with incompatible categoricals

### ISSUE THREAD

**Issue by coastalwhite** [pola-rs/polars#19532]
### Checks

- [X] I have checked that this issue has not already been reported.
- [X] I have confirmed this bug exists on the [latest version](https://pypi.org/project/polars/) of Polars.

### Reproducible example

```python
import polars as pl
import io

f1 = io.BytesIO()
f2 = io.BytesIO()

pl.Series('x', ["a"], pl.Categorical).to_frame().write_ipc(f1)
pl.Series('x', ["b"], pl.Categorical).to_frame().write_ipc(f2)

f1.seek(0)
f2.seek(0)

pl.scan_ipc([f1, f2]).collect()
```

### Log output

```shell
thread '<unnamed>' panicked at crates/polars-arrow/src/array/binview/mutable.rs:262:9:
attempt to add with overflow
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
Traceback (most recent call last):
  File "/home/johndoe/Projects/polars/t6.py", line 13, in <module>
    pl.scan_ipc([f1, f2]).collect()
  File "/home/johndoe/Projects/polars/py-polars/polars/lazyframe/frame.py", line 2055, in collect
    return wrap_df(ldf.collect(callback))
                   ^^^^^^^^^^^^^^^^^^^^^
pyo3_runtime.PanicException: attempt to add with overflow
```

### Issue description

panic exception

### Expected behavior

no panic exception

### Installed versions

<details>

```
Replace this line with the output of pl.show_versions(). Leave the backticks in place.
```

</details>

**Comment by coastalwhite** [comment]
No longer panics.
