### ISSUE TITLE
`scan_ndjson` / `read_ndjson` does not respect the `storage_options` endpoint url

### ISSUE THREAD

**Issue by blinkseb** [pola-rs/polars#19699]
### Checks

- [X] I have checked that this issue has not already been reported.
- [X] I have confirmed this bug exists on the [latest version](https://pypi.org/project/polars/) of Polars.

### Reproducible example

```python
storage_options = {
    "aws_access_key_id": "xxx",
    "aws_secret_access_key": "xxx",
    "aws_region": "fr-par",
    "endpoint": "https://s3.fr-par.scw.cloud",
    "aws_endpoint": "https://s3.fr-par.scw.cloud",
    "aws_endpoint_url": "https://s3.fr-par.scw.cloud",
}

pl.scan_ndjson("s3://bucket/path/to/data/*.json.gz", storage_options=storage_options)
```

### Log output

```shell
Async thread count: 4
Traceback (most recent call last):
  File "/home/sbrochet/Projets/data-circle/data/notebooks/iceberg/test.py", line 12, in <module>
    print(pl.scan_ndjson("s3://bucket/path/to/data/*.json.gz", storage_options=storage_options))
    ~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/sbrochet/.venvs/jupyter-py3.13/lib64/python3.13/site-packages/polars/lazyframe/frame.py", line 626, in __str__
    {self.explain(optimized=False)}\
     ~~~~~~~~~~~~^^^^^^^^^^^^^^^^^
  File "/home/sbrochet/.venvs/jupyter-py3.13/lib64/python3.13/site-packages/polars/lazyframe/frame.py", line 1116, in explain
    return self._ldf.describe_plan()
           ~~~~~~~~~~~~~~~~~~~~~~~^^
polars.exceptions.ComputeError: Generic S3 error: Error performing list request: Error after 2 retries in 274.839231ms, max_retries:2, retry_timeout:10s, source:error sending request for url (https://s3.fr-par.amazonaws.com/bucket?list-type=2&prefix=path%2Fto%2Fdata%2F)
```

### Issue description

Hello!

It seems that `scan_ndjson` / `read_ndjson` does not respect the `storage_options` endpoint url. Using `scan_parquet` instead of `scan_ndjson` (using the same `storage_options`) works perfectly fine.

### Expected behavior

`scan_ndjson` / `read_ndjson` should read data from a non-AWS S3 service

### Installed versions

<details>

```
--------Version info---------
Polars:              1.12.0
Index type:          UInt32
Platform:            Linux-6.11.5-200.fc40.x86_64-x86_64-with-glibc2.40
Python:              3.13.0 (main, Oct  8 2024, 00:00:00) [GCC 14.2.1 20240912 (Red Hat 14.2.1-3)]
LTS CPU:             False

----Optional dependencies----
adbc_driver_manager  <not installed>
altair               <not installed>
cloudpickle          <not installed>
connectorx           <not installed>
deltalake            <not installed>
fastexcel            <not installed>
fsspec               2024.10.0
gevent               <not installed>
great_tables         <not installed>
matplotlib           3.9.2
nest_asyncio         1.6.0
numpy                2.1.3
openpyxl             3.1.5
pandas               2.2.3
pyarrow              18.0.0
pydantic             2.9.2
pyiceberg            0.7.1
sqlalchemy           2.0.36
torch                <not installed>
xlsx2csv             <not installed>
xlsxwriter           <not installed>
```

</details>

**Comment by MHajjem** [comment]
use endpoint_url

**Comment by blinkseb** [comment]
I'm closing this issue, it's now working using polars 1.31.0.
