### ISSUE TITLE
Inconsistency dealing with "file://..." paths

### ISSUE THREAD

**Issue by atzannes** [pola-rs/polars#19749]
### Checks

- [X] I have checked that this issue has not already been reported.
- [X] I have confirmed this bug exists on the [latest version](https://pypi.org/project/polars/) of Polars.

### Reproducible example

```python
import polars as pl
df = pl.DataFrame()

df.write_parquet('file:///home/username/tmp/empty.parquet')  # FAILS
df.write_parquet('/home/username/tmp/empty.parquet')  # SUCCEEDS
pl.read_parquet('file:///home/username/tmp/empty.parquet')  # SUCCEEDS
```

### Log output

```shell
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/atzannes/code/tmp/.venv/lib/python3.12/site-packages/polars/dataframe/frame.py", line 3848, in write_parquet
    self._df.write_parquet(
FileNotFoundError: No such file or directory (os error 2)
```

### Issue description

When my path starts with `file://`  df.write_parquet fails whereas `polars.read_parquet` doesn't care whether the path starts with `file://` or not

### Expected behavior

The behaviors of DataFrame.write_parquet and polars.read_parquet should not have different restrictions as to how paths are presented. 

### Installed versions

<details>

```
>>> pl.show_versions()
--------Version info---------
Polars:              1.13.0
Index type:          UInt32
Platform:            Linux-6.8.0-48-generic-x86_64-with-glibc2.39
Python:              3.12.3 (main, Oct  3 2024, 13:41:51) [GCC 13.2.0]
LTS CPU:             False

----Optional dependencies----
adbc_driver_manager  <not installed>
altair               <not installed>
cloudpickle          <not installed>
connectorx           <not installed>
deltalake            <not installed>
fastexcel            <not installed>
fsspec               <not installed>
gevent               <not installed>
great_tables         <not installed>
matplotlib           <not installed>
nest_asyncio         <not installed>
numpy                <not installed>
openpyxl             <not installed>
pandas               <not installed>
pyarrow              <not installed>
pydantic             <not installed>
pyiceberg            <not installed>
sqlalchemy           <not installed>
torch                <not installed>
xlsx2csv             <not installed>
xlsxwriter           <not installed>
```

</details>

**Comment by atzannes** [comment]
Here's a wrinkle to the workaround of using `use_pyarrow=True`: it seems that if the path has a space in it, pyarrow fails with 
```
File "pyarrow/error.pxi", line 92, in pyarrow.lib.check_status
pyarrow.lib.ArrowInvalid: Expected a local filesystem path, got a URI: 's3://bucket/file with space.parquet'
```
conversely, this fixes my problem:
```
from upath import UPath

with UPath('s3://bucket/file with space.parquet').open("w") as fd:
    df.write_parquet(fd)
```
So it looks like I will have to avoid passing path-like args to write_parquet for now, unless it's for the local file-system
