### ISSUE TITLE
`pl.cum_sum_horizontal(...).struct.unnest()` errors with `StructFieldNotFoundError: literal`

### ISSUE THREAD

**Issue by rben01** [pola-rs/polars#19765]
### Checks

- [X] I have checked that this issue has not already been reported.
- [X] I have confirmed this bug exists on the [latest version](https://pypi.org/project/polars/) of Polars.

### Reproducible example

```python
df = pl.DataFrame({"a": [1, 2], "b": [3, 4]})
df.select(pl.cum_sum_horizontal("a", "b").struct.unnest())
```

### Log output

```shell
Traceback (most recent call last):
  File "/Users/rben01/test.py", line 44, in <module>
    df.select(pl.cum_sum_horizontal("a", "b").struct.unnest())
  File "/Users/rben01/Library/Caches/pypoetry/virtualenvs/base-wTklQcO3-py3.12/lib/python3.12/site-packages/polars/dataframe/frame.py", line 9024, in select
    return self.lazy().select(*exprs, **named_exprs).collect(_eager=True)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/rben01/Library/Caches/pypoetry/virtualenvs/base-wTklQcO3-py3.12/lib/python3.12/site-packages/polars/lazyframe/frame.py", line 2021, in collect
    return wrap_df(ldf.collect(callback))
                   ^^^^^^^^^^^^^^^^^^^^^
polars.exceptions.StructFieldNotFoundError: literal
```

### Issue description

This goes back to working if you do `.struct.unnest()` in a separate `select()`:

```python
df = pl.DataFrame({"a": [1, 2], "b": [3, 4]})
df.select(pl.cum_sum_horizontal("a", "b")).select(pl.col("cum_sum").struct.unnest())
```

```
shape: (2, 2)
┌─────┬─────┐
│ a   ┆ b   │
│ --- ┆ --- │
│ i64 ┆ i64 │
╞═════╪═════╡
│ 1   ┆ 4   │
│ 2   ┆ 6   │
└─────┴─────┘
```

### Expected behavior

```python
df.select(pl.cum_sum_horizontal("a", "b").struct.unnest())
```

should just work and return

```
shape: (2, 2)
┌─────┬─────┐
│ a   ┆ b   │
│ --- ┆ --- │
│ i64 ┆ i64 │
╞═════╪═════╡
│ 1   ┆ 4   │
│ 2   ┆ 6   │
└─────┴─────┘
```

### Installed versions

<details>

```
--------Version info---------
Polars:              1.13.0
Index type:          UInt32
Platform:            macOS-15.1-arm64-arm-64bit
Python:              3.12.7 (main, Oct  1 2024, 02:05:46) [Clang 16.0.0 (clang-1600.0.26.3)]
LTS CPU:             False

----Optional dependencies----
adbc_driver_manager  <not installed>
altair               5.4.1
cloudpickle          <not installed>
connectorx           <not installed>
deltalake            <not installed>
fastexcel            <not installed>
fsspec               2024.9.0
gevent               <not installed>
great_tables         <not installed>
matplotlib           3.9.1.post1
nest_asyncio         1.6.0
numpy                2.1.3
openpyxl             3.1.5
pandas               2.2.3
pyarrow              17.0.0
pydantic             2.9.2
pyiceberg            <not installed>
sqlalchemy           2.0.32
torch                2.4.1
xlsx2csv             <not installed>
xlsxwriter           <not installed>
```

</details>

**Comment by cmdlineluser** [comment]
It seems the literal used for `acc=` in the underlying `cum_fold` call becomes part of the output dtype.

https://github.com/pola-rs/polars/blob/1a8735f6e26abcf76b43e90ab91f9d99b76f2fe9/py-polars/polars/functions/aggregation/horizontal.py#L286

```python
(df
  .lazy()
  .select(pl.cum_fold(0, lambda x, y: x + y, pl.all()))
  .collect_schema()
)
# Schema([('cum_fold', Struct({'a': Int64, 'b': Int64, 'literal': Int64}))])
#                                                       ^^^^^^^
```

```python
(df
  .lazy()
  .select(pl.cum_fold(0, lambda x, y: x + y, pl.all()))
  .collect()
  .collect_schema()
)
# Schema([('cum_fold', Struct({'a': Int64, 'b': Int64}))])
```
