### ISSUE TITLE
Creating a DataFrame from Pydantic models fails if there is missing data/Nones

### ISSUE THREAD

**Issue by miikka-oura** [pola-rs/polars#19761]
### Checks

- [X] I have checked that this issue has not already been reported.
- [X] I have confirmed this bug exists on the [latest version](https://pypi.org/project/polars/) of Polars.

### Reproducible example

```python
import polars as pl
from pydantic import BaseModel

class MyModel(BaseModel):
    x: int

df = pl.DataFrame({"a": [MyModel(x=1), None]})
print(df)
```

### Log output

```shell
Traceback (most recent call last):
  File "/Users/miikka.koskinen/mess/2024-46/polars-bug/bug.py", line 7, in <module>
    df = pl.DataFrame({"a": [MyModel(x=1), None]})
  File "/Users/miikka.koskinen/mess/2024-46/polars-bug/.venv/lib/python3.10/site-packages/polars/dataframe/frame.py", line 367, in __init__
    self._df = dict_to_pydf(
  File "/Users/miikka.koskinen/mess/2024-46/polars-bug/.venv/lib/python3.10/site-packages/polars/_utils/construction/dataframe.py", line 160, in dict_to_pydf
    for s in _expand_dict_values(
  File "/Users/miikka.koskinen/mess/2024-46/polars-bug/.venv/lib/python3.10/site-packages/polars/_utils/construction/dataframe.py", line 389, in _expand_dict_values
    updated_data[name] = pl.Series(
  File "/Users/miikka.koskinen/mess/2024-46/polars-bug/.venv/lib/python3.10/site-packages/polars/series/series.py", line 289, in __init__
    self._s = sequence_to_pyseries(
  File "/Users/miikka.koskinen/mess/2024-46/polars-bug/.venv/lib/python3.10/site-packages/polars/_utils/construction/series.py", line 109, in sequence_to_pyseries
    return pl.DataFrame(values).to_struct(name)._s
  File "/Users/miikka.koskinen/mess/2024-46/polars-bug/.venv/lib/python3.10/site-packages/polars/dataframe/frame.py", line 376, in __init__
    self._df = sequence_to_pydf(
  File "/Users/miikka.koskinen/mess/2024-46/polars-bug/.venv/lib/python3.10/site-packages/polars/_utils/construction/dataframe.py", line 460, in sequence_to_pydf
    return _sequence_to_pydf_dispatcher(
  File "/usr/local/Cellar/python@3.10/3.10.14_1/Frameworks/Python.framework/Versions/3.10/lib/python3.10/functools.py", line 889, in wrapper
    return dispatch(args[0].__class__)(*args, **kw)
  File "/Users/miikka.koskinen/mess/2024-46/polars-bug/.venv/lib/python3.10/site-packages/polars/_utils/construction/dataframe.py", line 528, in _sequence_to_pydf_dispatcher
    return to_pydf(**common_params)
  File "/Users/miikka.koskinen/mess/2024-46/polars-bug/.venv/lib/python3.10/site-packages/polars/_utils/construction/dataframe.py", line 880, in _sequence_of_pydantic_models_to_pydf
    dicts = [md.__dict__ for md in data]
  File "/Users/miikka.koskinen/mess/2024-46/polars-bug/.venv/lib/python3.10/site-packages/polars/_utils/construction/dataframe.py", line 880, in <listcomp>
    dicts = [md.__dict__ for md in data]
AttributeError: 'NoneType' object has no attribute '__dict__'. Did you mean: '__dir__'?
```

### Issue description

When creating a DataFrame from a list of Pydantic model instances, you get `AttributeError: 'NoneType' object has no attribute '__dict__'.` if there are Nones in the list.

### Expected behavior

I'd expected that the Nones in the input list get converted to Polars nulls, similarly to what you get if you pass in a list of dicts and Nones. Example below:

```python
import polars as pl
from pydantic import BaseModel

df = pl.DataFrame({"a": [{"x": 1}, None]})
print(df)
```

Output:
```
shape: (2, 1)
┌───────────┐
│ a         │
│ ---       │
│ struct[1] │
╞═══════════╡
│ {1}       │
│ null      │
└───────────┘
```

### Installed versions

<details>

```
--------Version info---------
Polars:              1.13.0
Index type:          UInt32
Platform:            macOS-15.1-x86_64-i386-64bit
Python:              3.10.14 (main, Mar 19 2024, 21:46:16) [Clang 15.0.0 (clang-1500.3.9.4)]
LTS CPU:             False

----Optional dependencies----
adbc_driver_manager  <not installed>
altair               <not installed>
cloudpickle          <not installed>
connectorx           <not installed>
deltalake            <not installed>
fastexcel            <not installed>
fsspec               <not installed>
gevent               <not installed>
great_tables         <not installed>
matplotlib           <not installed>
nest_asyncio         <not installed>
numpy                <not installed>
openpyxl             <not installed>
pandas               <not installed>
pyarrow              <not installed>
pydantic             2.9.2
pyiceberg            <not installed>
sqlalchemy           <not installed>
torch                <not installed>
xlsx2csv             <not installed>
xlsxwriter           <not installed>
```

</details>

**Comment by ritchie46** [comment]
@alexander-beedie could you take a look at this one?

**Comment by alexander-beedie** [comment]
Can see what's going on; will see about fixing in the next day or two 👌

**Comment by taranraj123** [comment]
Hi @alexander-beedie I'm seeing this happen on values other than `None` as well. 

Doing the following yields the same error that @miikka-oura indicated.

```
import polars as pl
from pydantic import BaseModel

class MyModel(BaseModel):
    x: int

df = pl.DataFrame({"a": [MyModel(x=1), "foo"]})
print(df)
```
