### ISSUE TITLE
GOOGLE_APPLICATION_CREDENTIALS environment variable no more detected

### ISSUE THREAD

**Issue by Vincenthays** [pola-rs/polars#19781]
### Checks

- [X] I have checked that this issue has not already been reported.
- [X] I have confirmed this bug exists on the [latest version](https://pypi.org/project/polars/) of Polars.

### Reproducible example

```python
import os
import polars as pl

os.environ['GOOGLE_APPLICATION_CREDENTIALS'] = '/Users/HAVI1001/gs_credentials.json'

pl.scan_parquet('gs://di_data_lab/test.parquet').collect()
```

### Log output

```shell
Auto-selected credential provider: CredentialProviderGCP
Async thread count: 2
[FetchedCredentialsCache]: Call update_func: current_time = 1731582518, last_fetched_expiry = 0
[FetchedCredentialsCache]: Call update_func: current_time = 1731582519, last_fetched_expiry = 0
Traceback (most recent call last):
  File "<python-input-1>", line 4, in <module>
    ).collect()
      ~~~~~~~^^
  File "/opt/homebrew/lib/python3.13/site-packages/polars/lazyframe/frame.py", line 2021, in collect
    return wrap_df(ldf.collect(callback))
                   ~~~~~~~~~~~^^^^^^^^^^
polars.exceptions.ComputeError: Generic credential-provider-gcp error: RefreshError: ('invalid_scope: Invalid OAuth scope or ID token audience provided.', {'error': 'invalid_scope', 'error_description': 'Invalid OAuth scope or ID token audience provided.'}))
```

### Issue description

The issue is resolved when the `GOOGLE_APPLICATION_CREDENTIALS` path is manually pass to the scan_parquet, indicating the environment variable is functional but not being automatically detected:

```python
pl.scan_parquet(
    'gs://di_data_lab/test.parquet', 
    storage_options={'service_account': '/Users/HAVI1001/gs_credentials.json'}
).collect()
# shape: (3, 1)
# ┌─────┐
# │ a   │
# │ --- │
# │ i64 │
# ╞═════╡
# │ 1   │
# │ 2   │
# │ 3   │
# └─────┘
```

### Expected behavior

Use `GOOGLE_APPLICATION_CREDENTIALS` environment variable

### Installed versions

<details>

--------Version info---------
Polars:              1.13.1
Index type:          UInt32
Platform:            macOS-15.1-arm64-arm-64bit-Mach-O
Python:              3.13.0 (main, Oct  7 2024, 05:02:14) [Clang 16.0.0 (clang-1600.0.26.3)]
LTS CPU:             False

----Optional dependencies----
adbc_driver_manager  <not installed>
altair               <not installed>
cloudpickle          <not installed>
connectorx           0.4.0
deltalake            <not installed>
fastexcel            0.12.0
fsspec               2024.10.0
gevent               <not installed>
great_tables         <not installed>
matplotlib           <not installed>
nest_asyncio         1.6.0
numpy                2.1.2
openpyxl             <not installed>
pandas               2.2.3
pyarrow              18.0.0
pydantic             <not installed>
pyiceberg            <not installed>
sqlalchemy           2.0.36
torch                <not installed>
xlsx2csv             <not installed>
xlsxwriter           3.2.0

</details>

**Comment by Vincenthays** [comment]
I tested using `read_parquet`, and it resulted in the same crash.
Can be fixed `storage_options` option, exactly like the scan_parquet issue
