### ISSUE TITLE
Handle serialization for nulled structs

### ISSUE THREAD

**Issue by mallport** [pola-rs/polars#19975]
### Description

Unsure if this bug - filing this under feature request seeing as the [error message received](https://github.com/pola-rs/polars/blob/742c7372e71d8f133f0d3cb45ba697da9d04274a/crates/polars-core/src/serde/chunked_array.rs#L170) refers to this specific case.
 
Following the struct refactoring released in Polars 1.2, we can no longer serialize null structs. This means that the following is not possible, and throws an error:

```python
import polars as pl

df = pl.DataFrame(
    {"foo": None, "bar": "bar_value", "baz": "baz_value"},
    schema={
        "foo": pl.Struct({"inner_foo": pl.String}), "bar": pl.String, "baz": pl.String
        }
)
df.serialize(format="json")
```

Trace:
```
Traceback (most recent call last):
  File "tester4.py", line 11, in <module>
    print(df.serialize(format="json"))
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File ".venv/lib/python3.12/site-packages/polars/dataframe/frame.py", line 2633, in serialize
    return serialize_polars_object(serializer, file, format)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File ".venv/lib/python3.12/site-packages/polars/_utils/serde.py", line 47, in serialize_polars_object
    serialized = serialize_to_bytes()
                 ^^^^^^^^^^^^^^^^^^^^
  File ".venv/lib/python3.12/site-packages/polars/_utils/serde.py", line 42, in serialize_to_bytes
    serializer(buf)
polars.exceptions.ComputeError: serializing struct with outer validity not yet supported
```

**Usecase**

We use Polars to work with highly hierarchical, raw data. The `serialize()` function is useful in order to group rows of hierarchical data together and perform business logic on these rows, as well as send requests to an API with a subset of the dataset.

It would be great to give the user an option on how to handle serialization such that you could possibly skip serialization of nulled structs instead of throwing an error for the entire serialization. Alternatively - a sane default :))

**Comment by cmdlineluser** [comment]
It seems this is now resolved:

```python
df.serialize(format="json")
# '[255,255,255,255,48,1,0,0,4,0,0,0,242,255,...
```
