### ISSUE TITLE
PanicException for Hist method

### ISSUE THREAD

**Issue by BenGale93** [pola-rs/polars#19998]
### Checks

- [X] I have checked that this issue has not already been reported.
- [X] I have confirmed this bug exists on the [latest version](https://pypi.org/project/polars/) of Polars.

### Reproducible example

```python
import polars as pl

df = pl.DataFrame(
    {
        "floats": [
            9514.988509739183,
            30738.098872148617,
            41400.15705103004,
            49093.06982022727,
        ]
    }
)

result = df.lazy().select(pl.col("floats").hist(bin_count=50, include_breakpoint=True)).collect()

print(result)
```

### Log output

```shell
thread '<unnamed>' panicked at crates/polars-ops/src/chunked_array/hist.rs:112:22:
index out of bounds: the len is 50 but the index is 50
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
Traceback (most recent call last):
  File "****/test.py", line 18, in <module>
    result = df.lazy().select(pl.col("floats").hist(bin_count=50, include_breakpoint=True)).collect()
  File "****/.venv/lib/python3.9/site-packages/polars/lazyframe/frame.py", line 2029, in collect
    return wrap_df(ldf.collect(callback))
pyo3_runtime.PanicException: index out of bounds: the len is 50 but the index is 50
```

### Issue description

Only occurs in 1.15 as I've tested in 1.14 too.

If you set `bin_count=49`, it works.
If you delete `9514.988509739183` from the list, it also works.

### Expected behavior

The histogram should be computed without a panic.

### Installed versions

<details>

```
--------Version info---------
Polars:              1.15.0
Index type:          UInt32
Platform:            Linux-4.4.0-19041-Microsoft-x86_64-with-glibc2.31
Python:              3.9.20 (main, Oct 16 2024, 04:36:33) 
[Clang 18.1.8 ]
LTS CPU:             False

----Optional dependencies----
adbc_driver_manager  <not installed>
altair               <not installed>
boto3                1.35.36
cloudpickle          <not installed>
connectorx           <not installed>
deltalake            <not installed>
fastexcel            0.11.5
fsspec               2024.9.0
gevent               <not installed>
google.auth          <not installed>
great_tables         0.13.0
matplotlib           3.9.2
nest_asyncio         <not installed>
numpy                1.26.0
openpyxl             3.1.5
pandas               1.5.0
pyarrow              18.0.0
pydantic             2.8.0
pyiceberg            <not installed>
sqlalchemy           <not installed>
torch                <not installed>
xlsx2csv             <not installed>
xlsxwriter           3.2.0
```

</details>

**Comment by BenGale93** [comment]
Hi, @lukemanley, sorry but I've managed to find another example that causes the error. Even smaller this time.

Some background, these are random floats generated for some fake data in a test suite.
I then trim down the fake data to be as small as possible and still trigger the error.

```python
df = pl.DataFrame(
    {
        "floats": [
            122.2905130704109,
            49093.06982022727,
        ]
    }
)
```
