### ISSUE TITLE
Cast on NULL column fails.

### ISSUE THREAD

**Issue by cfarino1** [pola-rs/polars#20005]
### Checks

- [X] I have checked that this issue has not already been reported.
- [X] I have confirmed this bug exists on the [latest version](https://pypi.org/project/polars/) of Polars.

### Reproducible example

```python
df = pl.DataFrame({"rpt_dt_lts":[None, None]})
df = df.with_columns(pl.col('rpt_dt_lts').str.to_datetime('%Y-%m-%dT%H:%M:%S%.3fZ'))
print(df)
```

### Log output

```shell
Traceback (most recent call last):
  File "lib/python3.10/site-packages/polars/dataframe/frame.py", line 9211, in with_columns
    return self.lazy().with_columns(*exprs, **named_exprs).collect(_eager=True)
  File "lib/python3.10/site-packages/polars/lazyframe/frame.py", line 2029, in collect
    return wrap_df(ldf.collect(callback))
polars.exceptions.SchemaError: invalid series dtype: expected `String`, got `null`
```

### Issue description

If entire series, or column in data frame is NULL, cast fails.  If one row is not NULL, cast succeeds.

This code will pass:
```python
df = pl.DataFrame({"rpt_dt_lts":[None, None,'2019-01-11T13:08:35Z']})
df = df.with_columns(pl.col('rpt_dt_lts').str.to_datetime('%Y-%m-%dT%H:%M:%S%.3fZ'))
print(df)
```
```console
shape: (3, 1)
┌─────────┐
 │ rpt_dt_lts                   │
 │ ---                               │
 │ datetime[ms]             │
╞═════════════╡
 │ null                              │
 │ null                              │
 │ 2019-01-11 13:08:35 │
└─────────┘
```

### Expected behavior

```console
shape: (2, 1)
┌───────┐
 │ rpt_dt_lts.         │
 │ ---                      │
 │ datetime[ms]    │
╞══════════╡
 │ null                     │
 │ null                     │
└───────┘
```

### Installed versions

<details>

```
--------Version info---------
Polars:              1.15.0
Index type:          UInt32
Platform:            macOS-15.1.1-arm64-arm-64bit
Python:              3.10.11 (v3.10.11:7d4cc5aa85, Apr  4 2023, 19:05:19) [Clang 13.0.0 (clang-1300.0.29.30)]
LTS CPU:             False

----Optional dependencies----
adbc_driver_manager  <not installed>
altair               <not installed>
boto3                1.35.5
cloudpickle          2.2.1
connectorx           <not installed>
deltalake            <not installed>
fastexcel            <not installed>
fsspec               2023.6.0
gevent               <not installed>
google.auth          <not installed>
great_tables         <not installed>
matplotlib           <not installed>
nest_asyncio         <not installed>
numpy                1.25.1
openpyxl             <not installed>
pandas               1.5.0
pyarrow              12.0.1
pydantic             <not installed>
pyiceberg            <not installed>
sqlalchemy           2.0.29
torch                <not installed>
xlsx2csv             <not installed>
xlsxwriter           <not installed>
None

```

</details>

**Comment by lmocsi** [comment]
If you specify the schema in the dataframe, then it runs fine:
```python
import polars as pl

df = pl.DataFrame({"rpt_dt_lts":[None, None]}, schema={'rpt_dt_lts': pl.String})
df = df.with_columns(pl.col('rpt_dt_lts').str.to_datetime('%Y-%m-%dT%H:%M:%S%.3fZ'))
print(df)
```
```
┌──────────────┐
│ rpt_dt_lts   │
│ ---          │
│ datetime[ms] │
╞══════════════╡
│ null         │
│ null         │
└──────────────┘
```

**Comment by coastalwhite** [comment]
This is not a bug. If you inspect the original dataframe, it has the `Null` datatype. If you want to it to always have a string dtype, you need to supply it a `String` dtype (as suggested by @lmocsi).
