### ISSUE TITLE
Cannot merge DeltaTable when predicate is Decimal 

### ISSUE THREAD

**Issue by ponychicken** [pola-rs/polars#20009]
### Checks

- [X] I have checked that this issue has not already been reported.
- [X] I have confirmed this bug exists on the [latest version](https://pypi.org/project/polars/) of Polars.

### Reproducible example

```python
import polars as pl
from datetime import datetime, date, timedelta
from deltalake import DeltaTable

# Define schema
schema = {
    "timestamp": pl.Datetime(time_unit="us", time_zone="UTC"),
    "date": pl.Date,
    "lon": pl.Decimal(precision=9, scale=6),
    "lat": pl.Decimal(precision=9, scale=6),
    "altitude": pl.Decimal(precision=6, scale=1),
    "course": pl.Decimal(precision=4, scale=1),
    "heading": pl.Decimal(precision=4, scale=1),
    "speed": pl.Decimal(precision=4, scale=1),
    "name": pl.String,
    "s3_key": pl.String,
}

# Create sample data
data = {
    "timestamp": [datetime(2024, 3, 20, 12, 30, 0)],
    "date": [date(2024, 3, 20)],
    "lon": [122.123456],
    "lat": [41.987654],
    "altitude": [150.5],
    "course": [45.5],
    "heading": [90.0],
    "speed": [12.5],
    "name": ["NAME"],
    "s3_key": ["s3"],
}

# Create DataFrame with sample data and schema
df = pl.DataFrame(data, schema=schema)

# Write DataFrame as Delta table
df.write_delta("B")


df.write_delta(
    "B",
    mode="merge",
    delta_merge_options={
        "predicate": """
        t.timestamp = s.timestamp 
        AND t.lat = s.lat 
        AND t.lon = s.lon
    """,
        "source_alias": "s",
        "target_alias": "t",
    }
).when_matched_update_all().when_not_matched_insert_all().execute()

```

### Log output

```shell
Traceback (most recent call last):
  File "<stdin>", line 13, in <module>
  File ".venv/lib/python3.12/site-packages/deltalake/table.py", line 1800, in execute
    metrics = self._table.merge_execute(self._builder)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
_internal.DeltaError: Generic DeltaTable error: Unable to convert expression to string
```

### Issue description

If I modify the predicate to only check the timestamp or check a string, it will succeed

### Expected behavior

Write should succeed

### Installed versions

<details>

--------Version info---------
Polars:              1.15.0
Index type:          UInt32
Platform:            Linux-6.11
Python:              3.12.7
LTS CPU:             False

----Optional dependencies----
adbc_driver_manager  <not installed>
altair               <not installed>
boto3                1.35.69
cloudpickle          <not installed>
connectorx           <not installed>
deltalake            0.21.0
fastexcel            <not installed>
fsspec               2024.10.0
gevent               <not installed>
google.auth          <not installed>
great_tables         <not installed>
matplotlib           <not installed>
nest_asyncio         <not installed>
numpy                2.1.3
openpyxl             3.1.5
pandas               2.2.3
pyarrow              18.1.0
pydantic             2.9.2
pyiceberg            <not installed>
sqlalchemy           2.0.36
torch                <not installed>
xlsx2csv             <not installed>
xlsxwriter           <not installed>

</details>

**Comment by ponychicken** [comment]
This is probably a upstream bug: https://github.com/delta-io/delta-rs/issues/3033

**Comment by ion-elgreco** [comment]
It seems we are missing a match arm for decimal to allow round tripping through the log
