### ISSUE TITLE
Failing `Lazyframe.join` if onclauses are expressions and are using similar named columns

### ISSUE THREAD

**Issue by fhoehle** [pola-rs/polars#20040]
### Checks

- [X] I have checked that this issue has not already been reported.
- [X] I have confirmed this bug exists on the [latest version](https://pypi.org/project/polars/) of Polars.

### Reproducible example

```python
import polars as pl

ldf_1 = pl.LazyFrame(
    data={
    "col1": ["11", "12", None],
    "col2": ["1", "2", "31"]
    }
)
ldf_2 = pl.LazyFrame(
    data={
        "col2": ["1", "3"]
    }
)

ldf_join = ldf_1.join(
    other=ldf_2,
    left_on=[pl.col("col1").fill_null(pl.col("col2"))],
    right_on=[pl.col("col2") + "1"],
)

#fails
ldf_join.select("col1", "col2").collect()
```

### Log output

```shell
Traceback (most recent call last):
  File "/tmp/test_polars.py", line 23, in <module>
    ldf_join.select("col1", "col2").collect()
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^
  File "/private/tmp/polars-test/lib/python3.13/site-packages/polars/lazyframe/frame.py", line 2029, in collect
    return wrap_df(ldf.collect(callback))
                   ~~~~~~~~~~~^^^^^^^^^^
polars.exceptions.DuplicateError: found duplicate columns
```

### Issue description

Latest `polars` release `1.15.0` fails joining two dataframes having same columns and expressions in the `on` experssions. Adding `projection_pushdown=False` to the `collect` expression yields a successful execution. Also creating a dedicated column instead of the on the fly creation does not raise an issue. Similar `polars=1.14.0` returns the expected result.

Some findings:
It is necessary to use the same column name in both dataframes used for joining and both on clauses need to be an expression.

### Expected behavior

```
shape: (2, 2)
┌──────┬──────┐
│ col1 ┆ col2 │
│ ---  ┆ ---  │
│ str  ┆ str  │
╞══════╪══════╡
│ 11   ┆ 1    │
│ null ┆ 31   │
└──────┴──────┘
```

### Installed versions

<details>

```
--------Version info---------
Polars:              1.15.0
Index type:          UInt32
Platform:            macOS-15.1.1-arm64-arm-64bit
Python:              3.11.10 | packaged by conda-forge | (main, Oct 16 2024, 01:26:25) [Clang 17.0.6 ]
LTS CPU:             False

----Optional dependencies----
adbc_driver_manager  <not installed>
altair               <not installed>
boto3                <not installed>
cloudpickle          <not installed>
connectorx           <not installed>
deltalake            <not installed>
fastexcel            <not installed>
fsspec               <not installed>
gevent               <not installed>
google.auth          <not installed>
great_tables         <not installed>
matplotlib           3.9.2
nest_asyncio         <not installed>
numpy                2.1.3
openpyxl             <not installed>
pandas               <not installed>
pyarrow              16.1.0
pydantic             <not installed>
pyiceberg            <not installed>
sqlalchemy           <not installed>
torch                <not installed>
xlsx2csv             <not installed>
xlsxwriter           <not installed>
```

</details>

**Comment by coastalwhite** [comment]
This now runs.
