### ISSUE TITLE
Timezone aware feather read error

### ISSUE THREAD

**Issue by Tapanhaz** [pola-rs/polars#20078]
### Checks

- [X] I have checked that this issue has not already been reported.
- [X] I have confirmed this bug exists on the [latest version](https://pypi.org/project/polars/) of Polars.

### Reproducible example

```python

```
I got some feather files with schema :
``` 
{'date': Datetime(time_unit='ns', time_zone='+05:30'), 'open': Float64, 'high': Float64, 'low': Float64, 'close': Float64, 'volume': Int64, 'oi': Int64, 'symbol': String, 'name': String, 'expiry': Date, 'strike': Float64, 'instrument_type': String}
```

It produces error on reading :
```
 polars.exceptions.ComputeError: unable to parse time zone: '+05:30'. Please check the Time Zone Database for a list of available time zones
```

use_pyarrow= True doesn't solve that issue.

### Log output

```shell
Traceback (most recent call last):
  File "/home/tapan-hazarika/Documents/python/project_I/binance_historical/test_feather.py", line 26, in <module>
    df = pl.read_ipc("test_data.feather", use_pyarrow= True)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/tapan-hazarika/Documents/venv/normal/v3123/lib/python3.12/site-packages/polars/_utils/deprecation.py", line 92, in wrapper
    return function(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/tapan-hazarika/Documents/venv/normal/v3123/lib/python3.12/site-packages/polars/_utils/deprecation.py", line 92, in wrapper
    return function(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/tapan-hazarika/Documents/venv/normal/v3123/lib/python3.12/site-packages/polars/io/ipc/functions.py", line 155, in read_ipc
    df = pl.DataFrame._from_arrow(tbl, rechunk=rechunk)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/tapan-hazarika/Documents/venv/normal/v3123/lib/python3.12/site-packages/polars/dataframe/frame.py", line 548, in _from_arrow
    arrow_to_pydf(
  File "/home/tapan-hazarika/Documents/venv/normal/v3123/lib/python3.12/site-packages/polars/_utils/construction/dataframe.py", line 1213, in arrow_to_pydf
    pydf = PyDataFrame.from_arrow_record_batches(tbl.to_batches())
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
polars.exceptions.ComputeError: unable to parse time zone: '+05:30'. Please check the Time Zone Database for a list of available time zones
```

### Issue description

 I tried to read that with pyarrow and load to to polars by  using from_pandas with schema_overrides= {"date": pl.Utf8} But the error persists.

### Expected behavior

from_pandas should work  here.

### Installed versions

<details>

```
--------Version info---------
Polars:              1.16.0
Index type:          UInt32
Platform:            Linux-6.8.0-49-generic-x86_64-with-glibc2.39
Python:              3.12.3 (main, Nov  6 2024, 18:32:19) [GCC 13.2.0]
LTS CPU:             False

----Optional dependencies----
adbc_driver_manager  <not installed>
altair               <not installed>
boto3                <not installed>
cloudpickle          <not installed>
connectorx           <not installed>
deltalake            <not installed>
fastexcel            <not installed>
fsspec               <not installed>
gevent               <not installed>
google.auth          <not installed>
great_tables         <not installed>
matplotlib           3.9.2
nest_asyncio         1.6.0
numpy                2.1.3
openpyxl             <not installed>
pandas               2.2.3
pyarrow              18.1.0
pydantic             <not installed>
pyiceberg            <not installed>
sqlalchemy           <not installed>
torch                <not installed>
xlsx2csv             <not installed>
xlsxwriter           <not installed>
```

</details>

**Comment by MarcoGorelli** [comment]
thanks @Tapanhaz for the report

Polars currently supports timezones from the time zone database (e.g. 'Asia/Kolkata') as well as the fix-offset ones in https://docs.rs/chrono-tz/latest/chrono_tz/Etc/index.html

Is it possible for your to first set 'Asia/Kolkata' (just a guess, don't know if that's the right one) when you save your feather files?

**Comment by Tapanhaz** [comment]
Thanks . Yes , the timezone is  "Asia/Kolkata" and that is working..  The original timezone is detected by pyarrow as pytz.FixedOffset(330)

![Screenshot from 2024-12-01 02-33-06](https://github.com/user-attachments/assets/d9608ec6-e89c-493f-9e78-630c4085e165)
