### ISSUE TITLE
polars.exceptions.ComputeError: unsupported data type when reading CSV: enum when reading CSV

### ISSUE THREAD

**Issue by gsamatt** [pola-rs/polars#20112]
### Checks

- [X] I have checked that this issue has not already been reported.
- [X] I have confirmed this bug exists on the [latest version](https://pypi.org/project/polars/) of Polars.

### Reproducible example

```python
import polars as pl
schema=pl.Schema({'A': pl.Int32, 'B': pl.Enum(["1","2","3","4","5"])})
df = pl.DataFrame({'A' : [1, 2, 3, 4, 5], 'B' : ["5", "4", "3", "2", "1"]}, schema=schema)
df.write_csv('example.csv')
pl.read_csv('example.csv', schema=schema)
```

### Log output

```shell
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "lib/python3.10/site-packages/polars/_utils/deprecation.py", line 92, in wrapper
    return function(*args, **kwargs)
  File "lib/python3.10/site-packages/polars/_utils/deprecation.py", line 92, in wrapper
    return function(*args, **kwargs)
  File "lib/python3.10/site-packages/polars/_utils/deprecation.py", line 92, in wrapper
    return function(*args, **kwargs)
  File "lib/python3.10/site-packages/polars/io/csv/functions.py", line 527, in read_csv
    df = _read_csv_impl(
  File "lib/python3.10/site-packages/polars/io/csv/functions.py", line 672, in _read_csv_impl
    pydf = PyDataFrame.read_csv(
polars.exceptions.ComputeError: unsupported data type when reading CSV: enum when reading CSV
```

### Issue description

Can not parse enums from CSV.

### Expected behavior

Not crash and parse enums from csv

### Installed versions

<details>

```
--------Version info---------
Polars:              1.15.0
```

</details>

**Comment by Zan-L** [comment]
Just adding something related here - the same error happens for Decimal type (if we specify it in the schema).

**Comment by Zan-L** [comment]
@cmdlineluser Sorry to have misinformed - Decimal can be read correctly now! It was something in my backlog for quite some time, but I couldn't remember to submit a new issue. Never mind!
