### ISSUE TITLE
prefix_fields operation not supported for dtype `unknown` (expected: Struct)

### ISSUE THREAD

**Issue by niccolopetti** [pola-rs/polars#20137]
### Checks

- [X] I have checked that this issue has not already been reported.
- [X] I have confirmed this bug exists on the [latest version](https://pypi.org/project/polars/) of Polars.

### Reproducible example

```python

(pl.DataFrame({"A": [[1, 2]]})
   .lazy()
   .with_columns(pl.col("A").list.to_struct(n_field_strategy="max_width", fields=lambda idx: f"-{idx}"))
   .with_columns(pl.col("A").name.prefix_fields("A"))
).collect()
```

### Log output

```shell
Traceback (most recent call last):
  File "./file.py", line 113, in <module>
    main()
  File "./file.py", line 101, in main
    ).collect()
  File "./env/lib/python3.10/site-packages/polars/lazyframe/frame.py", line 2029, in collect
    return wrap_df(ldf.collect(callback))
polars.exceptions.InvalidOperationError: prefix_fields operation not supported for dtype `unknown` (expected: Struct)

Resolved plan until failure:

	---> FAILED HERE RESOLVING 'with_columns' <---
 WITH_COLUMNS:
 [col("A").list.to_struct()] 
  DF ["A"]; PROJECT */1 COLUMNS; SELECTION: None
```

### Issue description

I am unable to run prefix_fields when I am executing code in a Lazyframe,
I would expect to be able to do so as I am able to with a Dataframe

### Expected behavior

I would expect the same result that I would get if I executed all directly on a Dataframe instead of a lazyframe, so the same output of

```python

(pl.DataFrame({"A": [[1, 2]]})
   #.lazy()
   .with_columns(pl.col("A").list.to_struct(n_field_strategy="max_width", fields=lambda idx: f"-{idx}"))
   .with_columns(pl.col("A").name.prefix_fields("A"))
)


```

which is 

| A     |
|-------|
| {1,2} |

### Installed versions

<details>

```
--------Version info---------
Polars:              1.16.0
Index type:          UInt32
Platform:            Linux-6.9.3-76060903-generic-x86_64-with-glibc2.35
Python:              3.10.12 (main, Nov  6 2024, 20:22:13) [GCC 11.4.0]
LTS CPU:             False

----Optional dependencies----
adbc_driver_manager  <not installed>
altair               5.5.0
boto3                <not installed>
cloudpickle          <not installed>
connectorx           <not installed>
deltalake            <not installed>
fastexcel            <not installed>
fsspec               <not installed>
gevent               <not installed>
google.auth          <not installed>
great_tables         <not installed>
matplotlib           3.9.3
nest_asyncio         1.6.0
numpy                2.0.2
openpyxl             <not installed>
pandas               2.2.3
pyarrow              18.1.0
pydantic             <not installed>
pyiceberg            <not installed>
sqlalchemy           <not installed>
torch                <not installed>
xlsx2csv             <not installed>
xlsxwriter           <not installed>
```

</details>

**Comment by wukan1986** [comment]
https://github.com/pola-rs/polars/issues/20043

**Comment by nameexhaustion** [comment]
This isn't necessarily a bug - it's more of an unfortunate footgun of our `to_struct()` API. It's strongly recommended to specify a list of field names, otherwise we cannot determine the output field names of the expression, hence the reason why the dtype becomes `Unknown`.

We've added a descriptive warning to be displayed when fields are not specified, and we will improve the API in the future in a breaking change.
