### ISSUE TITLE
Error slicing parquet file starting with Polars 1.13.0+

### ISSUE THREAD

**Issue by jmurray-clarify** [pola-rs/polars#20174]
### Checks

- [X] I have checked that this issue has not already been reported.
- [X] I have confirmed this bug exists on the [latest version](https://pypi.org/project/polars/) of Polars.

### Reproducible example

Parquet file (77MB): https://drive.google.com/file/d/1tFatKynd5DSEieTTIUwXtBYKltUjWJJA/view?usp=drive_link

```
pl.scan_parquet(path).select('code_description').slice(1898054, 1).collect()
```

### Log output

```shell
parquet scan with parallel = RowGroups
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/jordanmurray/Packages/clarify-payer-rates/.venv/lib/python3.9/site-packages/polars/lazyframe/frame.py", line 2029, in collect
    return wrap_df(ldf.collect(callback))
polars.exceptions.ComputeError: parquet: File out of specification: String data contained invalid UTF-8
```

### Issue description

Starting after upgrading to polars 1.13.0, we encountered the below error upon slicing a parquet file. When creating a simpler code example for the Reproducible Example, it produced that other error. Using an older version of polars to read and write that affected row into a separate parquet file, does not reproduce the issue.

```
POLARS PREFETCH_SIZE: 16
RUN STREAMING PIPELINE
[parquet -> hstack -> hstack -> ordered_sink]
STREAMING CHUNK SIZE: 1048576 rows
parquet scan with parallel = Columns
thread 'polars-6' panicked at crates/polars-parquet/src/arrow/read/deserialize/binview.rs:427:40:
range start index 18446744073709536829 out of range for slice of length 7896
stack backtrace:
   0:        0x10a355bac - <std::sys::backtrace::BacktraceLock::print::DisplayBacktrace as core::fmt::Display>::fmt::h47fda2adb1d95ca6
   1:        0x106b07078 - core::fmt::write::hf02c740536f0830c
   2:        0x10a326d2c - std::io::Write::write_fmt::h18cd01bac5cbac08
   3:        0x10a356b9c - std::sys::backtrace::BacktraceLock::print::hfdb3f5f734a161c5
   4:        0x10a356a04 - std::panicking::default_hook::{{closure}}::hcfb606595fc6038e
   5:        0x10a3572a4 - std::panicking::rust_panic_with_hook::h5feeb8802cd3d0bd
   6:        0x10a356c64 - std::panicking::begin_panic_handler::{{closure}}::he394d57f81ff5447
   7:        0x10a356bd4 - std::sys::backtrace::__rust_end_short_backtrace::h0362d52013de77c2
   8:        0x10a356bc8 - _rust_begin_unwind
   9:        0x10a49bad4 - core::panicking::panic_fmt::h0da7cadfe6cfa60b
  10:        0x10a49bb24 - core::slice::index::slice_start_index_len_fail::h9ab9bc9338860fb4
  11:        0x1086b2390 - polars_parquet::arrow::read::deserialize::binview::decode_masked_required_plain::h4dbd428ca41f472f
  12:        0x1086af290 - <polars_parquet::arrow::read::deserialize::binview::BinViewDecoder as polars_parquet::arrow::read::deserialize::utils::Decoder>::extend_filtered_with_state::hbac4195dc35b8c4b
  13:        0x10873aac0 - polars_parquet::arrow::read::deserialize::utils::PageDecoder<D>::collect_n::h6ae1ba8e6357ee5a
  14:        0x108712310 - polars_parquet::arrow::read::deserialize::simple::page_iter_to_array::h31f6af7f152267b5
  15:        0x107c9ff88 - polars_io::parquet::read::mmap::to_deserializer::h4877119fa1bdc456
  16:        0x107ca7788 - polars_io::parquet::read::read_impl::column_idx_to_series::hc661f66adbe4a3b7
  17:        0x107ca6400 - rayon::iter::plumbing::bridge_producer_consumer::helper::h57662d4671f245af
  18:        0x107ca7014 - <rayon_core::job::StackJob<L,F,R> as rayon_core::job::Job>::execute::h177f121e117c4848
  19:        0x10a761d44 - rayon_core::registry::WorkerThread::wait_until_cold::h5e96eb8af978a90e
  20:        0x107ca6ccc - rayon_core::join::join_context::{{closure}}::h69f9a7f19d97a699
  21:        0x107ca6828 - rayon::iter::plumbing::bridge_producer_consumer::helper::h57662d4671f245af
  22:        0x107ca7014 - <rayon_core::job::StackJob<L,F,R> as rayon_core::job::Job>::execute::h177f121e117c4848
  23:        0x10a761d44 - rayon_core::registry::WorkerThread::wait_until_cold::h5e96eb8af978a90e
  24:        0x10a1105f0 - std::sys::backtrace::__rust_begin_short_backtrace::h364e5ead79615d37
  25:        0x10a11031c - core::ops::function::FnOnce::call_once{{vtable.shim}}::h06ad2f0e26d2abad
  26:        0x10a359af0 - std::sys::pal::unix::thread::Thread::new::thread_start::h17cdff74b7aff0be
  27:        0x1838a9f94 - __pthread_joiner_wake
Rayon: detected unexpected panic; aborting
```

### Expected behavior

For the reproducible example:
```
>>> pl.scan_parquet(path).select('code_description').slice(1898054, 1).collect()
shape: (1, 1)
┌──────────────────┐
│ code_description │
│ ---              │
│ str              │
╞══════════════════╡
│ DENTAL           │
└──────────────────┘
```

### Installed versions

<details>

```
--------Version info---------
Polars:              1.15.0
Index type:          UInt32
Platform:            macOS-14.7.1-arm64-arm-64bit
Python:              3.9.18 (main, Aug 24 2023, 21:19:58) 
[Clang 14.0.3 (clang-1403.0.22.14.1)]
LTS CPU:             True

----Optional dependencies----
adbc_driver_manager  <not installed>
altair               <not installed>
boto3                1.34.0
cloudpickle          3.0.0
connectorx           <not installed>
deltalake            <not installed>
fastexcel            <not installed>
fsspec               <not installed>
gevent               <not installed>
google.auth          2.36.0
great_tables         <not installed>
matplotlib           <not installed>
nest_asyncio         <not installed>
numpy                1.26.4
openpyxl             <not installed>
pandas               1.5.3
pyarrow              16.1.0
pydantic             2.10.2
pyiceberg            <not installed>
sqlalchemy           <not installed>
torch                <not installed>
xlsx2csv             <not installed>
xlsxwriter           <not installed>
```

</details>

**Comment by jkimcubist** [comment]
I have same issues with version 1.13.0+. I am using version 1.12.0

**Comment by cmdlineluser** [comment]
Can reproduce.

Just trying `.slice(1_898_054).collect()` - it seems something is up with the range start:

```
# thread 'polars-1' panicked at crates/polars-parquet/src/arrow/read/deserialize/binview.rs:427:40:
# range start index 18446744073709548716 out of range for slice of length 16277
# PanicException: range start index 18446744073709548716 out of range for slice of length 16277
```

Possibly slice_pushdown related:

`.slice(1_898_054, 1).collect(slice_pushdown=False)`

```
shape: (1, 1)
┌──────────────────┐
│ code_description │
│ ---              │
│ str              │
╞══════════════════╡
│ DENTAL           │
└──────────────────┘
```

**Comment by coastalwhite** [comment]
Way smaller MRE:

```python
import polars as pl
import pyarrow.parquet as pq
import io

f = io.BytesIO()

pq.write_table(
    pl.Series('s', ["a", "a" * 128]).to_frame().to_arrow(),
    f,
    use_dictionary=False
)

f.seek(0)
pl.scan_parquet(f).head(1).collect()
```
