### ISSUE TITLE
PanicException when dropping last colum in place after dropping in place another column

### ISSUE THREAD

**Issue by MatthieuDartiailh** [pola-rs/polars#20195]
### Checks

- [X] I have checked that this issue has not already been reported.
- [X] I have confirmed this bug exists on the [latest version](https://pypi.org/project/polars/) of Polars.

### Reproducible example

```python
import polars as pl

df = pl.from_dicts([{"DT": "a", "Name": "a", "DST": "a"}])

# Leads to a panic error
df.drop_in_place("DT")
df.drop_in_place("DST")

# Works fine
# df.drop_in_place("DST")
# df.drop_in_place("DT")
```

### Log output

```shell
thread '<unnamed>' panicked at crates\polars-core\src\frame\mod.rs:1627:16:
index out of bounds: the len is 2 but the index is 2
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
Traceback (most recent call last):
  File "c:\Users\DartiailhMatthieu\Documents\Coding\BugsRepro\polars_drop_in_place.py", line 7, in <module>
    df.drop_in_place("DST")
  File "C:\Users\DartiailhMatthieu\miniconda3\envs\charac\Lib\site-packages\polars\dataframe\frame.py", line 7708, in drop_in_place       
    return wrap_s(self._df.drop_in_place(name))
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
pyo3_runtime.PanicException: index out of bounds: the len is 2 but the index is 2
```

### Issue description

When dropping in place a column of a table and then attempting to drop the last (rightmost) column of the same table, polars 1.16 fails with a panic exception while polars 1.15 has no trouble with the operation.

I am assuming it may be related to the caching introduced in 1.16 but looking at the implementation of drop_in_place on the Rust side and in particular `get_column_idx` (https://github.com/pola-rs/polars/blob/main/crates/polars-core/src/frame/mod.rs#L1618) I do not see any obvious reason for the bug.

### Expected behavior

It should be possible to drop the last column after dropping another one.

### Installed versions

<details>

```
--------Version info---------
Polars:              1.16.0
Index type:          UInt32
Platform:            Windows-11-10.0.22631-SP0
Python:              3.12.7 | packaged by conda-forge | (main, Oct  4 2024, 15:47:54) [MSC v.1941 64 bit (AMD64)]
LTS CPU:             False

----Optional dependencies----
adbc_driver_manager  <not installed>
altair               <not installed>
boto3                <not installed>
cloudpickle          3.0.0
connectorx           <not installed>
deltalake            <not installed>
fastexcel            <not installed>
fsspec               <not installed>
gevent               <not installed>
google.auth          <not installed>
great_tables         <not installed>
matplotlib           <not installed>
nest_asyncio         <not installed>
numpy                2.1.2
openpyxl             <not installed>
pandas               2.2.3
pyarrow              17.0.0
pydantic             <not installed>
pyiceberg            <not installed>
sqlalchemy           <not installed>
torch                <not installed>
xlsx2csv             <not installed>
xlsxwriter           <not installed>
```

</details>

**Comment by cmdlineluser** [comment]
This is fixed on main:

- https://github.com/pola-rs/polars/issues/20119

```
shape: (1,)
Series: 'DT' [str]
[
	"a"
]
shape: (1,)
Series: 'DST' [str]
[
	"a"
]
```
