### ISSUE TITLE
scan_delta on partitioned and compacted delta table fails

### ISSUE THREAD

**Issue by sebvey** [pola-rs/polars#20238]
### Checks

- [X] I have checked that this issue has not already been reported.
- [X] I have confirmed this bug exists on the [latest version](https://pypi.org/project/polars/) of Polars.

### Reproducible example

**CREATE TABLE SCRIPT**
```python
from datetime import date, datetime, timedelta
from pathlib import Path
import shutil

import polars as pl
import pyarrow as pa
from pyarrow import compute as pc
from deltalake import Schema, Field, DeltaTable, WriterProperties, write_deltalake
from deltalake.schema import PrimitiveType


schema = Schema([
    Field("yearmonth",PrimitiveType("string")),
    Field("datetime",PrimitiveType("timestamp_ntz")),
    Field("location", PrimitiveType("string")),
    Field("value",PrimitiveType("double")),
])

def batch(day: date,location: str) -> pa.Table:
    """Produces a DataFrame with 86400 records for given day and location:
    - one 'query' per day -> ~30 files per month.
    - data partitioned by yearmonth
    """

    start_dt = datetime(day.year,day.month,day.day)
    end_dt = start_dt + timedelta(days=1, seconds=-1)

    dt_series = pl.datetime_range(start_dt,end_dt,timedelta(seconds=1),eager=True)
    value_series = pl.Series(pc.random(dt_series.len()))

    return (
        pl.DataFrame([
            dt_series.alias("datetime"),
            value_series.alias("value"),
        ])
        .with_columns(
            pl.col("datetime").dt.to_string("%Y%m").alias("yearmonth"),
            pl.lit(location).alias("location"),
        )
        .select(
            pl.col("yearmonth"),
            pl.col("datetime"),
            pl.col("location"),
            pl.col("value"),
        )
    ).to_arrow()


def create_table(
    table_path: Path,
    days: list[date],
    locations: list[str]
    ) -> DeltaTable:

    if table_path.is_dir(): shutil.rmtree(table_path)

    dt = DeltaTable.create(
        table_uri=str(table_path),
        schema=schema,
        partition_by=["yearmonth"],
    )

    for day in days:
        for location in locations:
            write_deltalake(
                dt,
                batch(day, location),
                mode="append",
                writer_properties=WriterProperties(compression="ZSTD")
            )

    return dt


DT_PATH = Path("tmp/delta_table")
LOCATIONS = ["Lyon","Paris","Marseille"]
START_DATE, END_DATE = date(2024,1,1), date(2024,3,1)
DAYS = (
    START_DATE + timedelta(days=i)
    for i in range((END_DATE - START_DATE).days)
)

dt = create_table(DT_PATH,DAYS,LOCATIONS)
```

**COMPACT AND QUERY**
```python
from pathlib import Path

import polars as pl
from deltalake import DeltaTable


def _polars_base_query[T: pl.DataFrame | pl.LazyFrame](df: T) -> T:
    return (
        df
        .filter(pl.col("location") == "Lyon")
        .group_by("location","yearmonth")
        .agg(pl.len())
        .sort("location","yearmonth")
    )

def polars_eager_query(dt: DeltaTable) -> pl.DataFrame:
    return pl.read_delta(dt).pipe(_polars_base_query)

def polars_lazy_query(dt: DeltaTable) -> pl.DataFrame:
    return pl.scan_delta(dt).pipe(_polars_base_query).collect()


DT_PATH = Path("tmp/delta_table")
dt = DeltaTable(DT_PATH)

# print("QUERY ON INITIAL TABLE: EVERYTHING'S FINE")
# print(f"{len(dt.files())=}")
# print(f"{len(dt.get_add_actions()["path"])=}")
# print(f"{polars_eager_query(dt)}")
# print(f"{polars_lazy_query(dt)}")

dt.optimize.compact(target_size=500 * 1_000_000)
print("QUERY ON COMPACTED TABLE:")
print(f"{len(dt.files())=}")
print(f"{len(dt.get_add_actions()["path"])=}")
# print(f"{polars_eager_query(dt)}") # FINE
print(f"{polars_lazy_query(dt)}")
```

### Log output

```shell
QUERY ON COMPACTED TABLE:
len(dt.files())=2
len(dt.get_add_actions()["path"])=2
parquet scan with parallel = Prefiltered
parquet live columns = 1, dead columns = 1
parquet scan with parallel = Prefiltered
parquet live columns = 1, dead columns = 1
parquet file must be read, statistics not sufficient for predicate.
parquet file must be read, statistics not sufficient for predicate.
parquet file must be read, statistics not sufficient for predicate.
parquet row group must be read, statistics not sufficient for predicate.
parquet file must be read, statistics not sufficient for predicate.
parquet file must be read, statistics not sufficient for predicate.
parquet row group must be read, statistics not sufficient for predicate.
parquet file must be read, statistics not sufficient for predicate.
parquet row group must be read, statistics not sufficient for predicate.
parquet row group must be read, statistics not sufficient for predicate.
parquet file must be read, statistics not sufficient for predicate.
parquet file must be read, statistics not sufficient for predicate.
parquet row group must be read, statistics not sufficient for predicate.
parquet row group must be read, statistics not sufficient for predicate.
parquet row group must be read, statistics not sufficient for predicate.
parquet row group must be read, statistics not sufficient for predicate.
parquet file must be read, statistics not sufficient for predicate.
parquet row group must be read, statistics not sufficient for predicate.
parquet file must be read, statistics not sufficient for predicate.
parquet row group must be read, statistics not sufficient for predicate.
parquet file must be read, statistics not sufficient for predicate.
parquet row group must be read, statistics not sufficient for predicate.
parquet file must be read, statistics not sufficient for predicate.
parquet row group must be read, statistics not sufficient for predicate.
parquet file must be read, statistics not sufficient for predicate.
parquet row group must be read, statistics not sufficient for predicate.
parquet file must be read, statistics not sufficient for predicate.
parquet row group must be read, statistics not sufficient for predicate.
parquet file must be read, statistics not sufficient for predicate.
parquet row group must be read, statistics not sufficient for predicate.
parquet file must be read, statistics not sufficient for predicate.
parquet row group must be read, statistics not sufficient for predicate.
estimated unique values: 1
run PARTITIONED HASH AGGREGATION
thread '<unnamed>' panicked at /Users/runner/work/polars/polars/crates/polars-core/src/frame/upstream_traits.rs:23:27:
could not create DataFrame from iterator: ShapeMismatch(ErrString("could not create a new DataFrame: series \"location\" has length 5184000 while series \"yearmonth\" has length 15552000"))
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
Traceback (most recent call last):
  File "/Users/ippon/code/workspaces/sebvey/mre-delta-compaction/query.py", line 37, in <module>
    print(f"{polars_lazy_query(dt)}")
             ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ippon/code/workspaces/sebvey/mre-delta-compaction/query.py", line 20, in polars_lazy_query
    return pl.scan_delta(dt, use_pyarrow=False).pipe(_polars_base_query).collect()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ippon/code/workspaces/sebvey/mre-delta-compaction/.venv/lib/python3.12/site-packages/polars/lazyframe/frame.py", line 2057, in collect
    return wrap_df(ldf.collect(callback))
                   ^^^^^^^^^^^^^^^^^^^^^
pyo3_runtime.PanicException: could not create DataFrame from iterator: ShapeMismatch(ErrString("could not create a new DataFrame: series \"location\" has length 5184000 while series \"yearmonth\" has length 15552000"))
```

### Issue description

With the script provided, a delta table with two partitions is produced, appending ~180 files.   

Everything is fine when this table is queried (both with the given 'lazy query' and the 'eager query').  

After compaction using deltalake, the 'lazy query' fails. It seems that it tries to construct a DataFrame with a series from the partitioned field that is not filtered correctly.  

The query can be run successfully with the parameter use_pyarrow set to True 

### Expected behavior

The query is expected to succeed

### Installed versions

<details>

```
--------Version info---------
Polars:              1.19.0
Index type:          UInt32
Platform:            macOS-13.7.2-x86_64-i386-64bit
Python:              3.12.7 (main, Oct 16 2024, 09:10:10) [Clang 18.1.8 ]
LTS CPU:             False

----Optional dependencies----
adbc_driver_manager  <not installed>
altair               <not installed>
azure.identity       <not installed>
boto3                <not installed>
cloudpickle          <not installed>
connectorx           <not installed>
deltalake            0.23.1
fastexcel            <not installed>
fsspec               <not installed>
gevent               <not installed>
google.auth          <not installed>
great_tables         <not installed>
matplotlib           <not installed>
nest_asyncio         <not installed>
numpy                <not installed>
openpyxl             <not installed>
pandas               <not installed>
pyarrow              18.1.0
pydantic             <not installed>
pyiceberg            <not installed>
sqlalchemy           <not installed>
torch                <not installed>
xlsx2csv             <not installed>
xlsxwriter           <not installed>
```

</details>

**Comment by Bidek56** [comment]
Just tried the code above using Polars `1.19.0` on a MacOS `Darwin Kernel Version 23.6.0` and it all works fine.
```
QUERY ON INITIAL TABLE: EVERYTHING'S FINE
len(dt.files())=180
len(dt.get_add_actions()["path"])=180
shape: (2, 3)
┌──────────┬───────────┬─────────┐
│ location ┆ yearmonth ┆ len     │
│ ---      ┆ ---       ┆ ---     │
│ str      ┆ str       ┆ u32     │
╞══════════╪═══════════╪═════════╡
│ Lyon     ┆ 202401    ┆ 2678400 │
│ Lyon     ┆ 202402    ┆ 2505600 │
└──────────┴───────────┴─────────┘
shape: (2, 3)
┌──────────┬───────────┬─────────┐
│ location ┆ yearmonth ┆ len     │
│ ---      ┆ ---       ┆ ---     │
│ str      ┆ str       ┆ u32     │
╞══════════╪═══════════╪═════════╡
│ Lyon     ┆ 202401    ┆ 2678400 │
│ Lyon     ┆ 202402    ┆ 2505600 │
└──────────┴───────────┴─────────┘
QUERY ON COMPACTED TABLE:
len(dt.files())=2
len(dt.get_add_actions()["path"])=2
shape: (2, 3)
┌──────────┬───────────┬─────────┐
│ location ┆ yearmonth ┆ len     │
│ ---      ┆ ---       ┆ ---     │
│ str      ┆ str       ┆ u32     │
╞══════════╪═══════════╪═════════╡
│ Lyon     ┆ 202401    ┆ 2678400 │
│ Lyon     ┆ 202402    ┆ 2505600 │
└──────────┴───────────┴─────────┘
```

**Comment by sebvey** [comment]
Mm.. Still the same problem on my side with polars updated to 1.19.1, deltalake to 0.23.1 (and my kernel from macOS-13.7.1 to 13.7.2). I have updated my original message to reflect the last tested versions

**Comment by Bidek56** [comment]
Your r using I386 processor vs. me on Arm64.
Something must be off with the build for i386.

**Comment by sebvey** [comment]
I don't know if it's of any use but the same panic occurs when using docker (platform: Linux-5.15.82-0-virt-x86_64-with-glibc2.36, still i386)

**Comment by Bidek56** [comment]
`Linux-5.15.82-0-virt-x86_64-with-glibc2.36` is super old. 
Can you try something more recent like Linux 6? Thx

**Comment by sebvey** [comment]
@Bidek56 , done with `Linux-6.8.0-50-generic-x86_64-with-glibc2.36`, the exact same result

**Comment by Bidek56** [comment]
Is this a real path: `tmp/delta_table`?
Should it be `/tmp/delta_table` or `./tmp/delta_table`?
R u using a network storage? Thx
