### ISSUE TITLE
polars 1.17 can not save file to RamDisk

### ISSUE THREAD

**Issue by wukan1986** [pola-rs/polars#20231]
### Checks

- [X] I have checked that this issue has not already been reported.
- [X] I have confirmed this bug exists on the [latest version](https://pypi.org/project/polars/) of Polars.

### Reproducible example

```python
import polars as pl

df = pl.DataFrame({'A': [1, 2, 3, 4, 5], 'B': ['a', 'b', 'c', 'd', 'e']})

df.write_parquet(r'd:\test.parquet')  # SSD

df.write_parquet(r'M:\test.parquet')  # ImDisk Toolkit
r"""
Traceback (most recent call last):
  File "D:\GitHub\ddump\examples\jqresearch\t1.py", line 6, in <module>
    df.write_parquet(r'M:\test.parquet')  # ImDisk Toolkit
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Users\Kan\miniconda3\envs\py311_1\Lib\site-packages\polars\dataframe\frame.py", line 4038, in write_parquet
    self._df.write_parquet(
OSError: 函数不正确。 (os error 1)
"""

df.write_csv(r'N:\test.csv')  # Rubik's Cube RamDisk
r"""
Traceback (most recent call last):
  File "D:\GitHub\ddump\examples\jqresearch\t1.py", line 16, in <module>
    df.write_csv(r'N:\test.csv')  # Rubik's Cube RamDisk
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Users\Kan\miniconda3\envs\py311_1\Lib\site-packages\polars\dataframe\frame.py", line 2983, in write_csv
    self._df.write_csv(
FileNotFoundError: 系统找不到指定的文件。 (os error 2)
"""
```

I used to save files on RamDisk, but after updating from 1.16 to 1.17, I found that the files could not be saved anymore.
I tested two RamDisk software, but neither of them works

ImDisk Toolkit
https://imdisk-toolkit.en.lo4d.com/download

### Issue description

polars 1.17 can not save file to RamDisk

### Expected behavior

save file to RamDisk

### Installed versions

<details>

```
--------Version info---------
Polars:              1.17.1
Index type:          UInt32
Platform:            Windows-10-10.0.22631-SP0
Python:              3.11.3 | packaged by Anaconda, Inc. | (main, Apr 19 2023, 23:46:34) [MSC v.1916 64 bit (AMD64)]
LTS CPU:             False

----Optional dependencies----
adbc_driver_manager  <not installed>
altair               5.0.1
boto3                <not installed>
cloudpickle          <not installed>
connectorx           <not installed>
deltalake            <not installed>
fastexcel            <not installed>
fsspec               <not installed>
gevent               <not installed>
google.auth          2.26.1
great_tables         <not installed>
matplotlib           3.7.1
nest_asyncio         1.5.6
numpy                1.26.4
openpyxl             3.1.2
pandas               2.2.3
pyarrow              12.0.0
pydantic             1.10.7
pyiceberg            <not installed>
sqlalchemy           2.0.13
torch                2.0.1+cu118
xlsx2csv             <not installed>
xlsxwriter           3.2.0
```

</details>

**Comment by wukan1986** [comment]
I have tried on two computers and they both reported errors

Could it be caused by this place?

https://github.com/pola-rs/polars/pull/20101

**Comment by wukan1986** [comment]
Hi, @nameexhaustion 

```rust
use std::path::{Path};


fn main() {
    let path = Path::new("D:\\test.csv");

    eprintln!(
        "try_get_writeable: local: {} (canonicalize: {:?})",
        path.to_str().unwrap(),
        std::fs::canonicalize(&path)
    );

    let path = Path::new("M:\\test.csv");

    eprintln!(
        "try_get_writeable: local: {} (canonicalize: {:?})",
        path.to_str().unwrap(),
        std::fs::canonicalize(&path)
    );
}

```
```shell
warning: `C:\Users\Kan\.cargo\config` is deprecated in favor of `config.toml`
note: if you need to support cargo 1.38 or earlier, you can symlink `config` to `config.toml`
    Finished `dev` profile [unoptimized + debuginfo] target(s) in 0.01s
     Running `target\debug\rust-test.exe`
try_get_writeable: local: D:\test.csv (canonicalize: Ok("\\\\?\\D:\\test.csv"))
try_get_writeable: local: M:\test.csv (canonicalize: Err(Os { code: 1, kind: Uncategorized, message: "函数不正确。" }))

```

M drive is create by ImDisk Toolkit

**Comment by nameexhaustion** [comment]
I see, in that case it should work after the PR is merged
