### ISSUE TITLE
Panic When Aggregating Parquet LazyFrame: validity mask length must match the number of values

### ISSUE THREAD

**Issue by Aryik** [pola-rs/polars#20242]
### Checks

- [X] I have checked that this issue has not already been reported.
- [X] I have confirmed this bug exists on the [latest version](https://pypi.org/project/polars/) of Polars.

### Reproducible example

```python
import polars as pl 
import datetime
import zoneinfo 
print(pl.__version__)
start_date = datetime.datetime(2024, 10, 2, 0, 0, tzinfo=zoneinfo.ZoneInfo(key='UTC'))
df = pl.scan_parquet("polars_minimal_repro.parquet")
df.filter(pl.col("datetime_col").gt(start_date)).group_by("string_col").agg(
    pl.n_unique("enum_col"),
).collect()
```

In polars 1.12.0, this is fine: 
```
>>> import polars as pl 
>>> import datetime
>>> import zoneinfo 
>>> print(pl.__version__)
1.12.0
>>> start_date = datetime.datetime(2024, 10, 2, 0, 0, tzinfo=zoneinfo.ZoneInfo(key='UTC'))
>>> df = pl.scan_parquet("polars_minimal_repro.parquet")
>>> df.filter(pl.col("datetime_col").gt(start_date)).group_by("string_col").agg(
...     pl.n_unique("enum_col"),
... ).collect()
shape: (7_897_465, 2)
┌──────────────────────┬──────────┐
│ string_col           ┆ enum_col │
│ ---                  ┆ ---      │
│ str                  ┆ u32      │
╞══════════════════════╪══════════╡
│ 8604122513921788285  ┆ 1        │
│ 6028805287010285681  ┆ 1        │
│ 5325329696969523616  ┆ 1        │
│ 17510005466429574147 ┆ 1        │
│ 12290517284928471532 ┆ 1        │
│ …                    ┆ …        │
│ 2236822817610814946  ┆ 1        │
│ 7255832370614837454  ┆ 1        │
│ 18220362948434179914 ┆ 1        │
│ 14065194591260067140 ┆ 1        │
│ 14544684152382932294 ┆ 1        │
└──────────────────────┴──────────┘
```

On the latest polars, it fails:
```
Python 3.12.2 (main, Feb  6 2024, 20:19:44) [Clang 15.0.0 (clang-1500.1.0.2.5)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import polars as pl 
>>> import datetime
>>> import zoneinfo 
>>> print(pl.__version__)
1.17.1
>>> start_date = datetime.datetime(2024, 10, 2, 0, 0, tzinfo=zoneinfo.ZoneInfo(key='UTC'))
>>> df = pl.scan_parquet("polars_minimal_repro.parquet")
>>> df.filter(pl.col("datetime_col").gt(start_date)).group_by("string_col").agg(
...     pl.n_unique("enum_col"),
... ).collect()
thread 'polars-5' panicked at /Users/runner/work/polars/polars/crates/polars-arrow/src/array/primitive/mod.rs:447:48:
called `Result::unwrap()` on an `Err` value: ComputeError(ErrString("validity mask length must match the number of values"))
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
thread 'polars-10' panicked at /Users/runner/work/polars/polars/crates/polars-arrow/src/array/primitive/mod.rs:447:48:
called `Result::unwrap()` on an `Err` value: ComputeError(ErrString("validity mask length must match the number of values"))
thread 'polars-9' panicked at /Users/runner/work/polars/polars/crates/polars-arrow/src/array/primitive/mod.rs:447:48:
called `Result::unwrap()` on an `Err` value: ComputeError(ErrString("validity mask length must match the number of values"))
thread 'polars-4' panicked at /Users/runner/work/polars/polars/crates/polars-arrow/src/array/primitive/mod.rs:447:48:
called `Result::unwrap()` on an `Err` value: ComputeError(ErrString("validity mask length must match the number of values"))
thread 'polars-9' panicked at /Users/runner/work/polars/polars/crates/polars-arrow/src/array/primitive/mod.rs:447:48:
called `Result::unwrap()` on an `Err` value: ComputeError(ErrString("validity mask length must match the number of values"))
thread 'polars-0' panicked at /Users/runner/work/polars/polars/crates/polars-arrow/src/array/primitive/mod.rs:447:48:
called `Result::unwrap()` on an `Err` value: ComputeError(ErrString("validity mask length must match the number of values"))
thread 'polars-9' panicked at /Users/runner/work/polars/polars/crates/polars-arrow/src/array/primitive/mod.rs:447:48:
called `Result::unwrap()` on an `Err` value: ComputeError(ErrString("validity mask length must match the number of values"))
thread 'polars-5' panicked at /Users/runner/work/polars/polars/crates/polars-arrow/src/array/primitive/mod.rs:447:48:
called `Result::unwrap()` on an `Err` value: ComputeError(ErrString("validity mask length must match the number of values"))
thread 'polars-4' panicked at /Users/runner/work/polars/polars/crates/polars-arrow/src/array/primitive/mod.rs:447:48:
called `Result::unwrap()` on an `Err` value: ComputeError(ErrString("validity mask length must match the number of values"))
thread 'polars-6' panicked at /Users/runner/work/polars/polars/crates/polars-arrow/src/array/primitive/mod.rs:447:48:
called `Result::unwrap()` on an `Err` value: ComputeError(ErrString("validity mask length must match the number of values"))
thread 'polars-10' panicked at /Users/runner/work/polars/polars/crates/polars-arrow/src/array/primitive/mod.rs:447:48:
called `Result::unwrap()` on an `Err` value: ComputeError(ErrString("validity mask length must match the number of values"))
thread 'polars-8' panicked at /Users/runner/work/polars/polars/crates/polars-arrow/src/array/primitive/mod.rs:447:48:
called `Result::unwrap()` on an `Err` value: ComputeError(ErrString("validity mask length must match the number of values"))
thread 'polars-7' panicked at /Users/runner/work/polars/polars/crates/polars-arrow/src/array/primitive/mod.rs:447:48:
called `Result::unwrap()` on an `Err` value: ComputeError(ErrString("validity mask length must match the number of values"))
thread 'polars-5' panicked at /Users/runner/work/polars/polars/crates/polars-arrow/src/array/primitive/mod.rs:447:48:
called `Result::unwrap()` on an `Err` value: ComputeError(ErrString("validity mask length must match the number of values"))
thread 'polars-2' panicked at /Users/runner/work/polars/polars/crates/polars-arrow/src/array/primitive/mod.rs:447:48:
called `Result::unwrap()` on an `Err` value: ComputeError(ErrString("validity mask length must match the number of values"))
thread 'polars-5' panicked at /Users/runner/work/polars/polars/crates/polars-arrow/src/array/primitive/mod.rs:447:48:
called `Result::unwrap()` on an `Err` value: ComputeError(ErrString("validity mask length must match the number of values"))
thread 'polars-5' panicked at /Users/runner/work/polars/polars/crates/polars-arrow/src/array/primitive/mod.rs:447:48:
called `Result::unwrap()` on an `Err` value: ComputeError(ErrString("validity mask length must match the number of values"))
thread 'polars-11' panicked at /Users/runner/work/polars/polars/crates/polars-arrow/src/array/primitive/mod.rs:447:48:
called `Result::unwrap()` on an `Err` value: ComputeError(ErrString("validity mask length must match the number of values"))
thread 'polars-3' panicked at /Users/runner/work/polars/polars/crates/polars-arrow/src/array/primitive/mod.rs:447:48:
called `Result::unwrap()` on an `Err` value: ComputeError(ErrString("validity mask length must match the number of values"))
thread 'polars-6' panicked at /Users/runner/work/polars/polars/crates/polars-arrow/src/array/primitive/mod.rs:447:48:
called `Result::unwrap()` on an `Err` value: ComputeError(ErrString("validity mask length must match the number of values"))
Traceback (most recent call last):
  File "<stdin>", line 3, in <module>
  File "/Users/aryik/Library/Caches/pypoetry/virtualenvs/LFRtXiTt-py3.12/lib/python3.12/site-packages/polars/lazyframe/frame.py", line 2031, in collect
    return wrap_df(ldf.collect(callback))
                   ^^^^^^^^^^^^^^^^^^^^^
pyo3_runtime.PanicException: called `Result::unwrap()` on an `Err` value: ComputeError(ErrString("validity mask length must match the number of values"))
```

I'm unable to attach `polars_minimal_repro.parquet` here because it's 560 MB. Please let me know what a good way is to share the file, I'm happy to do so and made an effort to create an obfuscated version of the offending parquet file. The size of the file seems to be closely related to the issue - a truncated version of the file does not fail. 

### Log output

```shell
Python 3.12.2 (main, Feb  6 2024, 20:19:44) [Clang 15.0.0 (clang-1500.1.0.2.5)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
Python 3.12.2 (main, Feb  6 2024, 20:19:44) [Clang 15.0.0 (clang-1500.1.0.2.5)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
keys/aggregates are not partitionable: running default HASH AGGREGATION
keys/aggregates are not partitionable: running default HASH AGGREGATION
parquet scan with parallel = Prefiltered
parquet scan with parallel = Prefiltered
parquet live columns = 1, dead columns = 2
parquet live columns = 1, dead columns = 2
parquet file can be skipped, the statistics were sufficient to apply the predicate.
parquet file must be read, statistics not sufficient for predicate.
parquet file can be skipped, the statistics were sufficient to apply the predicate.
parquet file must be read, statistics not sufficient for predicate.
parquet file must be read, statistics not sufficient for predicate.
parquet file can be skipped, the statistics were sufficient to apply the predicate.
parquet row group must be read, statistics not sufficient for predicate.
parquet row group can be skipped, the statistics were sufficient to apply the predicate.
parquet file must be read, statistics not sufficient for predicate.
parquet file must be read, statistics not sufficient for predicate.
parquet file can be skipped, the statistics were sufficient to apply the predicate.
parquet row group must be read, statistics not sufficient for predicate.
parquet row group can be skipped, the statistics were sufficient to apply the predicate.
parquet file must be read, statistics not sufficient for predicate.
parquet file must be read, statistics not sufficient for predicate.
parquet row group must be read, statistics not sufficient for predicate.
parquet file can be skipped, the statistics were sufficient to apply the predicate.
parquet file must be read, statistics not sufficient for predicate.
parquet row group must be read, statistics not sufficient for predicate.
parquet file can be skipped, the statistics were sufficient to apply the predicate.
parquet file must be read, statistics not sufficient for predicate.
parquet file must be read, statistics not sufficient for predicate.
parquet file must be read, statistics not sufficient for predicate.
parquet file must be read, statistics not sufficient for predicate.
parquet row group must be read, statistics not sufficient for predicate.
parquet row group must be read, statistics not sufficient for predicate.
parquet row group can be skipped, the statistics were sufficient to apply the predicate.
parquet row group can be skipped, the statistics were sufficient to apply the predicate.
parquet file can be skipped, the statistics were sufficient to apply the predicate.
parquet file can be skipped, the statistics were sufficient to apply the predicate.
parquet file must be read, statistics not sufficient for predicate.
parquet row group can be skipped, the statistics were sufficient to apply the predicate.
parquet file must be read, statistics not sufficient for predicate.
parquet row group can be skipped, the statistics were sufficient to apply the predicate.
parquet row group must be read, statistics not sufficient for predicate.
parquet file must be read, statistics not sufficient for predicate.
parquet row group must be read, statistics not sufficient for predicate.
parquet row group must be read, statistics not sufficient for predicate.
parquet row group must be read, statistics not sufficient for predicate.
parquet file must be read, statistics not sufficient for predicate.
parquet row group must be read, statistics not sufficient for predicate.
parquet row group must be read, statistics not sufficient for predicate.
parquet file must be read, statistics not sufficient for predicate.
parquet file must be read, statistics not sufficient for predicate.
parquet row group must be read, statistics not sufficient for predicate.
parquet row group must be read, statistics not sufficient for predicate.
parquet row group must be read, statistics not sufficient for predicate.
parquet file can be skipped, the statistics were sufficient to apply the predicate.
parquet row group can be skipped, the statistics were sufficient to apply the predicate.
parquet row group must be read, statistics not sufficient for predicate.
parquet file can be skipped, the statistics were sufficient to apply the predicate.
parquet file can be skipped, the statistics were sufficient to apply the predicate.
parquet row group can be skipped, the statistics were sufficient to apply the predicate.
parquet file can be skipped, the statistics were sufficient to apply the predicate.
parquet row group can be skipped, the statistics were sufficient to apply the predicate.
parquet file can be skipped, the statistics were sufficient to apply the predicate.
parquet row group can be skipped, the statistics were sufficient to apply the predicate.
parquet row group can be skipped, the statistics were sufficient to apply the predicate.
parquet file can be skipped, the statistics were sufficient to apply the predicate.
parquet file can be skipped, the statistics were sufficient to apply the predicate.
parquet row group can be skipped, the statistics were sufficient to apply the predicate.
parquet file can be skipped, the statistics were sufficient to apply the predicate.
parquet row group can be skipped, the statistics were sufficient to apply the predicate.
parquet row group can be skipped, the statistics were sufficient to apply the predicate.
parquet file must be read, statistics not sufficient for predicate.
parquet row group must be read, statistics not sufficient for predicate.
parquet row group can be skipped, the statistics were sufficient to apply the predicate.
parquet file can be skipped, the statistics were sufficient to apply the predicate.
parquet row group can be skipped, the statistics were sufficient to apply the predicate.
parquet file can be skipped, the statistics were sufficient to apply the predicate.
parquet row group can be skipped, the statistics were sufficient to apply the predicate.
parquet file can be skipped, the statistics were sufficient to apply the predicate.
parquet row group can be skipped, the statistics were sufficient to apply the predicate.
parquet file can be skipped, the statistics were sufficient to apply the predicate.
parquet row group can be skipped, the statistics were sufficient to apply the predicate.
parquet file can be skipped, the statistics were sufficient to apply the predicate.
parquet file must be read, statistics not sufficient for predicate.
parquet row group can be skipped, the statistics were sufficient to apply the predicate.
parquet file must be read, statistics not sufficient for predicate.
parquet row group must be read, statistics not sufficient for predicate.
parquet row group must be read, statistics not sufficient for predicate.
parquet row group must be read, statistics not sufficient for predicate.
parquet file can be skipped, the statistics were sufficient to apply the predicate.
parquet row group can be skipped, the statistics were sufficient to apply the predicate.
parquet row group must be read, statistics not sufficient for predicate.
parquet file can be skipped, the statistics were sufficient to apply the predicate.
parquet file can be skipped, the statistics were sufficient to apply the predicate.
parquet row group can be skipped, the statistics were sufficient to apply the predicate.
parquet file can be skipped, the statistics were sufficient to apply the predicate.
parquet row group can be skipped, the statistics were sufficient to apply the predicate.
parquet file can be skipped, the statistics were sufficient to apply the predicate.
parquet row group can be skipped, the statistics were sufficient to apply the predicate.
parquet row group can be skipped, the statistics were sufficient to apply the predicate.
parquet file can be skipped, the statistics were sufficient to apply the predicate.
parquet file can be skipped, the statistics were sufficient to apply the predicate.
parquet row group can be skipped, the statistics were sufficient to apply the predicate.
parquet file can be skipped, the statistics were sufficient to apply the predicate.
parquet row group can be skipped, the statistics were sufficient to apply the predicate.
parquet row group can be skipped, the statistics were sufficient to apply the predicate.
parquet file must be read, statistics not sufficient for predicate.
parquet row group must be read, statistics not sufficient for predicate.
parquet row group can be skipped, the statistics were sufficient to apply the predicate.
parquet file can be skipped, the statistics were sufficient to apply the predicate.
parquet row group can be skipped, the statistics were sufficient to apply the predicate.
parquet file can be skipped, the statistics were sufficient to apply the predicate.
parquet row group can be skipped, the statistics were sufficient to apply the predicate.
parquet file can be skipped, the statistics were sufficient to apply the predicate.
parquet row group can be skipped, the statistics were sufficient to apply the predicate.
parquet file can be skipped, the statistics were sufficient to apply the predicate.
parquet row group can be skipped, the statistics were sufficient to apply the predicate.
parquet file can be skipped, the statistics were sufficient to apply the predicate.
parquet file must be read, statistics not sufficient for predicate.
parquet row group can be skipped, the statistics were sufficient to apply the predicate.
parquet file must be read, statistics not sufficient for predicate.
parquet row group must be read, statistics not sufficient for predicate.
parquet row group must be read, statistics not sufficient for predicate.
thread 'polars-5' panicked at /Users/runner/work/polars/polars/crates/polars-arrow/src/array/primitive/mod.rs:447:48:
called `Result::unwrap()` on an `Err` value: ComputeError(ErrString("validity mask length must match the number of values"))
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
thread 'polars-5' panicked at /Users/runner/work/polars/polars/crates/polars-arrow/src/array/primitive/mod.rs:447:48:
called `Result::unwrap()` on an `Err` value: ComputeError(ErrString("validity mask length must match the number of values"))
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace


TRUNCATED DUE TO GITHUB LIMITATIONS. Full file is attached to the description. 
```

### Issue description

We first ran into this issue on Polars 1.13, and are currently stuck on Polars 1.12 because of it. We have a production system that heavily utilizes polars. As a part of the system, we have to write out a very large parquet file occasionally - this file contains ~50,000,000 rows of data. Upon an upgrade to polars 1.13, we started seeing a few issues which I originally reported on Discord. 

This issue is a `PanicException`:
```
Traceback (most recent call last):
  File "<stdin>", line 3, in <module>
  File "/Users/aryik/Library/Caches/pypoetry/virtualenvs/decision-engine-LFRtXiTt-py3.12/lib/python3.12/site-packages/polars/lazyframe/frame.py", line 2031, in collect
  File "<stdin>", line 3, in <module>
  File "/Users/aryik/Library/Caches/pypoetry/virtualenvs/decision-engine-LFRtXiTt-py3.12/lib/python3.12/site-packages/polars/lazyframe/frame.py", line 2031, in collect
    return wrap_df(ldf.collect(callback))
    return wrap_df(ldf.collect(callback))
                   ^^^^^^^^^^^^^^^^^^^^^
                   ^^^^^^^^^^^^^^^^^^^^^
pyo3_runtime.PanicException: called `Result::unwrap()` on an `Err` value: ComputeError(ErrString("validity mask length must match the number of values"))
```

I've been trying to isolate the issue, but struggled to figure out exactly what's going on. Here are some notes:

- It only seems to happen with `scan_parquet` .
- It seems to have something to do with aggregations on enum columns.
- It seems to have something to do with filtering on datetimes with timezones.
- It seems to pass when I turn optimization off.
- It only seems to happen on large parquet files - when we run the exact same code on a smaller dataset, it passes. 

Prior to polars 1.17, I would get a panic exception on `pl.scan("other_minimal_repro.parquet").head().collect()`, but one of @coastalwhite's fixes seems to have resolved that issue. 

In case it's helpful, I've attached the log output from the successful run on polars 1.12: 
[stderr_polars_1_12_success.txt](https://github.com/user-attachments/files/18072676/stderr_polars_1_12_success.txt)

I've also attached the full output from 1.17.1: 
[stderr_polars_1_17_failure.txt](https://github.com/user-attachments/files/18072667/stderr_polars_1_17_failure.txt)

### Expected behavior

I expect to be able to filter and aggregate without getting a `PanicException`. 

### Installed versions

<details>
Note: I also observed this on an x64 linux EC2 machine. 

```
--------Version info---------
Polars:              1.17.1
Index type:          UInt32
Platform:            macOS-15.1-arm64-arm-64bit
Python:              3.12.2 (main, Feb  6 2024, 20:19:44) [Clang 15.0.0 (clang-1500.1.0.2.5)]
LTS CPU:             False

----Optional dependencies----
adbc_driver_manager  <not installed>
altair               <not installed>
boto3                1.35.76
cloudpickle          3.1.0
connectorx           <not installed>
deltalake            <not installed>
fastexcel            <not installed>
fsspec               <not installed>
gevent               <not installed>
google.auth          2.36.0
great_tables         <not installed>
matplotlib           3.9.3
nest_asyncio         1.6.0
numpy                2.0.2
openpyxl             <not installed>
pandas               2.2.3
pyarrow              18.1.0
pydantic             2.10.2
pyiceberg            <not installed>
sqlalchemy           <not installed>
torch                <not installed>
xlsx2csv             <not installed>
xlsxwriter           <not installed>
```

</details>

**Comment by Aryik** [comment]
I was able to upload the anonymized file to my google drive: https://drive.google.com/file/d/1nFcdLGL9HJwio20in1sabEIvrDmZNJ02/view?usp=sharing

**Comment by cmdlineluser** [comment]
I can reproduce the panic with the sample file.

In case any of this is useful information:

The minimal case that still panicked for me was:

```python
(pl.scan_parquet("polars_minimal_repro.parquet")
   .head(998_812) # 998_811 succeeds
   .select(pl.col("datetime_col").cast(pl.Date), "enum_col")
   .sink_parquet("panic.parquet")
)

(pl.scan_parquet("panic.parquet")
   .filter(pl.col("datetime_col") > pl.date(2024, 10, 2))
   .collect()
)   

# thread 'polars-2' panicked at /Users/runner/work/polars/polars/crates/polars-arrow/src/array/primitive/mod.rs:447:48:
# called `Result::unwrap()` on an `Err` value: ComputeError(ErrString("validity mask length must match the number of values"))
# PanicException: called `Result::unwrap()` on an `Err` value: ComputeError(ErrString("validity mask length must match the number of values"))
```

Setting `parallel=` to none, columns or row_groups succeeds.

```python
(pl.scan_parquet("panic.parquet", parallel="row_groups")
   .filter(pl.col("datetime_col") > pl.date(2024, 10, 2))
   .collect()
)   

# shape: (497_891, 2)
# ┌──────────────┬──────────┐
# │ datetime_col ┆ enum_col │
# │ ---          ┆ ---      │
# │ date         ┆ enum     │
# ╞══════════════╪══════════╡
# │ 2024-10-27   ┆ null     │
# │ 2024-10-27   ┆ null     │
# │ 2024-10-27   ┆ uniform  │
# │ 2024-10-27   ┆ null     │
# │ 2024-10-27   ┆ null     │
# │ …            ┆ …        │
# │ 2024-10-04   ┆ null     │
# │ 2024-10-04   ┆ null     │
# │ 2024-10-04   ┆ null     │
# │ 2024-10-04   ┆ null     │
# │ 2024-10-04   ┆ null     │
# └──────────────┴──────────┘
```

So it seems it may be "prefiltered" specific as was mentioned in one of the previous issues/on Discord.

**Comment by Erigara** [comment]
Was the issue fixed? faced similar panic when `parallel="prefiltered"` was used.

**Comment by coastalwhite** [comment]
I think this issue was fixed. If you have a reproducer on the latest version, I would love to see it.

**Comment by Erigara** [comment]
Sorry, looks like false alarm, can't reproduce it anymore...
