### ISSUE TITLE
Read_delta does not return latest version of delta table when called in streamlit app

### ISSUE THREAD

**Issue by AnskePlanon** [pola-rs/polars#20253]
### Checks

- [X] I have checked that this issue has not already been reported.
- [X] I have confirmed this bug exists on the [latest version](https://pypi.org/project/polars/) of Polars.

### Reproducible example

```python

import streamlit as st
import polars as pl
from deltalake import DeltaTable
import logging
import os
import time

os.environ['POLARS_VERBOSE'] = '1'
now = time.time()
tablepath = r'\test\data\deltatable'  
logging.basicConfig(filename=r'streamlit.log',format='%(asctime)s %(levelname)-8s %(message)s', level=logging.DEBUG, datefmt='%Y-%m-%d %H:%M:%S')
logger = logging.getLogger(__name__)

def main():
    logging.info(f"Streamlit app test read delta started")
    logging.info(f"POLARS_VERBOSE: {str(os.environ['POLARS_VERBOSE'])}")
    st.set_page_config(page_title="Delta Lake Explorer", page_icon="📊", layout="wide")
    st.title("Delta Lake Explorer")
    #st.write(f"Polar versions: {pl.show_versions()}")
    try:
        foolist = []
        for i in range(10):
            foolist.append(i+1)
        df = pl.DataFrame({"foo": foolist})
        df.write_delta(tablepath,delta_write_options={"configuration": {"delta.logRetentionDuration": "0 days"}} )
        time.sleep(2)
        dt = DeltaTable(tablepath)
        dt.create_checkpoint()
        dt.delete(predicate=f"foo = 1")
        files = [os.path.join(tablepath, filename) for filename in os.listdir(tablepath)]
        created = 0
        file_to_delete = ""
        for filename in files:
            if os.path.isfile(filename):
                ti_c = os.path.getctime(filename)  ## created time in seconds elapsed since EPOCH 
                print(f"{filename} created {time.ctime(ti_c)}")
                if ti_c  < (created) or created == 0:
                    file_to_delete = filename
                    created =  ti_c
        print(f"file to delete: {file_to_delete}, created {time.ctime(created)} ")
        os.remove(file_to_delete)

        df = pl.read_delta(tablepath)
        print(df)
        st.write("read delta suceeded")
        st.dataframe(
            df,
            use_container_width=True,
            hide_index=False
        )
    except Exception as e:
        st.write(f"read delta failed: {e}")
        logging.error(e)
        raise e

    
if __name__ == "__main__":
    main()

```

### Log output

```shell
To redirect stderr to a streamlit.log file while running the streamlit app, start it up with the following flag:
streamlit run your_streamlit_app.py --logger.level=debug 2>streamlit.log
I have set the environment variable POLARS_VERBOSE to 1, but I do not see any more logging compared to not setting it, not sure if it carries through when running in the streamlit context...

The exception shows up in below logfile at 2024-12-10 15:20:02.889: FileNotFoundError: The system cannot find the file specified. (os error 2): C:/test/data/deltatable/part-00001-8f72ee44-ec07-44ad-ab2d-4072d6c825be-c000.snappy.parquet

2024-12-10 15:19:56.449 No singleton. Registering one.
2024-12-10 15:19:56.452 Watcher created for C:\Users\aaluij\Documents\Delta Lake Explorer\delta-lake-explorer\.streamlit\config.toml
2024-12-10 15:19:56.453 Starting server...
2024-12-10 15:19:56.453 Serving static content from C:\Users\aaluij\Documents\Delta Lake Explorer\delta-lake-explorer\.venv\Lib\site-packages\streamlit\static
2024-12-10 15:19:56.459 Server started on port 8501
2024-12-10 15:19:56.459 Runtime state: RuntimeState.INITIAL -> RuntimeState.NO_SESSIONS_CONNECTED
2024-12-10 15:19:57.199 Setting up signal handler
2024-12-10 15:19:57.420 Watcher created for C:\Users\aaluij\Documents\Delta Lake Explorer\delta-lake-explorer\pages
2024-12-10 15:19:57.422 Watcher created for C:\Users\aaluij\Documents\Delta Lake Explorer\delta-lake-explorer\streamlit_test_read_delta.py
2024-12-10 15:19:57.422 AppSession initialized (id=2cabcd25-6fd9-4859-a20e-ade58f98fce0)
2024-12-10 15:19:57.422 Created new session for client 1787831536528. Session ID: 2cabcd25-6fd9-4859-a20e-ade58f98fce0
2024-12-10 15:19:57.422 Runtime state: RuntimeState.NO_SESSIONS_CONNECTED -> RuntimeState.ONE_OR_MORE_SESSIONS_CONNECTED
2024-12-10 15:19:57.443 Watcher created for C:\Users\aaluij\Documents\Delta Lake Explorer\delta-lake-explorer\streamlit_test_read_delta.py
2024-12-10 15:19:57.443 AppSession initialized (id=14a2ee98-7f8d-4b55-b078-ed0aab430288)
2024-12-10 15:19:57.443 Created new session for client 1787831543696. Session ID: 14a2ee98-7f8d-4b55-b078-ed0aab430288
2024-12-10 15:19:57.443 Runtime state: RuntimeState.ONE_OR_MORE_SESSIONS_CONNECTED -> RuntimeState.ONE_OR_MORE_SESSIONS_CONNECTED
2024-12-10 15:19:57.458 Watcher created for C:\Users\aaluij\Documents\Delta Lake Explorer\delta-lake-explorer\streamlit_test_read_delta.py
2024-12-10 15:19:57.459 AppSession initialized (id=5c54028b-6b52-4020-bea6-fb2f08246576)
2024-12-10 15:19:57.459 Created new session for client 1787831583952. Session ID: 5c54028b-6b52-4020-bea6-fb2f08246576
2024-12-10 15:19:57.459 Runtime state: RuntimeState.ONE_OR_MORE_SESSIONS_CONNECTED -> RuntimeState.ONE_OR_MORE_SESSIONS_CONNECTED
2024-12-10 15:19:57.902 Watcher created for C:\Users\aaluij\Documents\Delta Lake Explorer\delta-lake-explorer\streamlit_test_read_delta.py
2024-12-10 15:19:57.902 AppSession initialized (id=481a202c-d43b-4a6e-9db4-ed2dbaf0ea8b)
2024-12-10 15:19:57.902 Created new session for client 1787831703184. Session ID: 481a202c-d43b-4a6e-9db4-ed2dbaf0ea8b
2024-12-10 15:19:57.902 Runtime state: RuntimeState.ONE_OR_MORE_SESSIONS_CONNECTED -> RuntimeState.ONE_OR_MORE_SESSIONS_CONNECTED
2024-12-10 15:19:57.910 Received the following back message:
rerun_script {
  widget_states {
  }
}

2024-12-10 15:19:57.911 Beginning script thread
2024-12-10 15:19:57.911 Running script RerunData(widget_states=)
2024-12-10 15:19:57.911 Disconnecting files for session with ID 481a202c-d43b-4a6e-9db4-ed2dbaf0ea8b
2024-12-10 15:19:57.911 Sessions still active: dict_keys([])
2024-12-10 15:19:57.911 Files: 0; Sessions with files: 0
2024-12-10 15:19:58.981 Watcher created for C:\Users\aaluij\Documents\Delta Lake Explorer\delta-lake-explorer\streamlit_test_read_delta.py
2024-12-10 15:19:58.982 AppSession initialized (id=2725e756-1006-49be-b7c8-63d47c5629c3)
2024-12-10 15:19:58.982 Created new session for client 1788505447312. Session ID: 2725e756-1006-49be-b7c8-63d47c5629c3
2024-12-10 15:19:58.982 Runtime state: RuntimeState.ONE_OR_MORE_SESSIONS_CONNECTED -> RuntimeState.ONE_OR_MORE_SESSIONS_CONNECTED
2024-12-10 15:19:59.334 Ignoring changed path C:\Users\aaluij\Documents\Delta Lake Explorer\delta-lake-explorer\streamlit.log.
Watched_paths: {'C:\\Users\\aaluij\\Documents\\Delta Lake Explorer\\delta-lake-explorer\\pages': WatchedPath(md5='c8cf409fd8a79c04285aeda4d4e1f585', glob_pattern='*.py', allow_nonexistent=True, on_changed=<blinker.base.Signal object at 0x000001A043105590>), 'C:\\Users\\aaluij\\Documents\\Delta Lake Explorer\\delta-lake-explorer\\streamlit_test_read_delta.py': WatchedPath(md5='e7ba8c62727fd846bcfc84d6085e23b3', modification_time=1733840379.5880826, on_changed=<blinker.base.Signal object at 0x000001A043105810>)}
2024-12-10 15:19:59.685 Ignoring changed path C:\Users\aaluij\Documents\Delta Lake Explorer\delta-lake-explorer\streamlit.log.
Watched_paths: {'C:\\Users\\aaluij\\Documents\\Delta Lake Explorer\\delta-lake-explorer\\pages': WatchedPath(md5='c8cf409fd8a79c04285aeda4d4e1f585', glob_pattern='*.py', allow_nonexistent=True, on_changed=<blinker.base.Signal object at 0x000001A043105590>), 'C:\\Users\\aaluij\\Documents\\Delta Lake Explorer\\delta-lake-explorer\\streamlit_test_read_delta.py': WatchedPath(md5='e7ba8c62727fd846bcfc84d6085e23b3', modification_time=1733840379.5880826, on_changed=<blinker.base.Signal object at 0x000001A043105810>)}
2024-12-10 15:20:02.889 Uncaught app exception
Traceback (most recent call last):
  File "C:\Users\aaluij\Documents\Delta Lake Explorer\delta-lake-explorer\.venv\Lib\site-packages\streamlit\runtime\scriptrunner\exec_code.py", line 88, in exec_func_with_error_handling
    result = func()
             ^^^^^^
  File "C:\Users\aaluij\Documents\Delta Lake Explorer\delta-lake-explorer\.venv\Lib\site-packages\streamlit\runtime\scriptrunner\script_runner.py", line 579, in code_to_exec
    exec(code, module.__dict__)
  File "C:\Users\aaluij\Documents\Delta Lake Explorer\delta-lake-explorer\streamlit_test_read_delta.py", line 66, in <module>
    main()
  File "C:\Users\aaluij\Documents\Delta Lake Explorer\delta-lake-explorer\streamlit_test_read_delta.py", line 62, in main
    raise e
  File "C:\Users\aaluij\Documents\Delta Lake Explorer\delta-lake-explorer\streamlit_test_read_delta.py", line 51, in main
    df = pl.read_delta(tablepath)
         ^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\aaluij\Documents\Delta Lake Explorer\delta-lake-explorer\.venv\Lib\site-packages\polars\io\delta.py", line 149, in read_delta
    return df.collect()
           ^^^^^^^^^^^^
  File "C:\Users\aaluij\Documents\Delta Lake Explorer\delta-lake-explorer\.venv\Lib\site-packages\polars\lazyframe\frame.py", line 2029, in collect
    return wrap_df(ldf.collect(callback))
                   ^^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: The system cannot find the file specified. (os error 2): C:/test/data/deltatable/part-00001-8f72ee44-ec07-44ad-ab2d-4072d6c825be-c000.snappy.parquet
2024-12-10 15:20:02.899 Removing orphaned files...
2024-12-10 15:20:03.225 Script run finished successfully; removing expired entries from MessageCache (max_age=2)
2024-12-10 15:20:18.037 Watcher created for C:\Users\aaluij\Documents\Delta Lake Explorer\delta-lake-explorer\streamlit_test_read_delta.py
2024-12-10 15:20:18.037 AppSession initialized (id=00e0f886-d529-4e8c-a320-d36874800de4)
2024-12-10 15:20:18.037 Created new session for client 1788547488400. Session ID: 00e0f886-d529-4e8c-a320-d36874800de4
2024-12-10 15:20:18.037 Runtime state: RuntimeState.ONE_OR_MORE_SESSIONS_CONNECTED -> RuntimeState.ONE_OR_MORE_SESSIONS_CONNECTED
2024-12-10 15:20:45.022 Watcher created for C:\Users\aaluij\Documents\Delta Lake Explorer\delta-lake-explorer\streamlit_test_read_delta.py
2024-12-10 15:20:45.022 AppSession initialized (id=d0762f52-6e3e-4e4e-8b63-e67b67c48083)
2024-12-10 15:20:45.022 Created new session for client 1788547493200. Session ID: d0762f52-6e3e-4e4e-8b63-e67b67c48083
2024-12-10 15:20:45.022 Runtime state: RuntimeState.ONE_OR_MORE_SESSIONS_CONNECTED -> RuntimeState.ONE_OR_MORE_SESSIONS_CONNECTED
2024-12-10 15:20:48.043 Watcher created for C:\Users\aaluij\Documents\Delta Lake Explorer\delta-lake-explorer\streamlit_test_read_delta.py
2024-12-10 15:20:48.043 AppSession initialized (id=516f15d2-a444-412c-ba1e-685107e43cc4)
2024-12-10 15:20:48.043 Created new session for client 1788564377104. Session ID: 516f15d2-a444-412c-ba1e-685107e43cc4
2024-12-10 15:20:48.043 Runtime state: RuntimeState.ONE_OR_MORE_SESSIONS_CONNECTED -> RuntimeState.ONE_OR_MORE_SESSIONS_CONNECTED
2024-12-10 15:22:19.918 Move event: src C:\Users\aaluij\Documents\Delta Lake Explorer\delta-lake-explorer\streamlit_test_read_delta.py; dest C:\Users\aaluij\Documents\Delta Lake Explorer\delta-lake-explorer\streamlit_test_read_delta_old.py
2024-12-10 15:22:19.918 Ignoring changed path C:\Users\aaluij\Documents\Delta Lake Explorer\delta-lake-explorer\streamlit_test_read_delta_old.py.
Watched_paths: {'C:\\Users\\aaluij\\Documents\\Delta Lake Explorer\\delta-lake-explorer\\pages': WatchedPath(md5='c8cf409fd8a79c04285aeda4d4e1f585', glob_pattern='*.py', allow_nonexistent=True, on_changed=<blinker.base.Signal object at 0x000001A043105590>), 'C:\\Users\\aaluij\\Documents\\Delta Lake Explorer\\delta-lake-explorer\\streamlit_test_read_delta.py': WatchedPath(md5='e7ba8c62727fd846bcfc84d6085e23b3', modification_time=1733840379.5880826, on_changed=<blinker.base.Signal object at 0x000001A043105810>)}
2024-12-10 15:22:24.760 File/dir timestamp did not change: C:\Users\aaluij\Documents\Delta Lake Explorer\delta-lake-explorer\streamlit_test_read_delta.py
2024-12-10 15:24:23.517 File/dir MD5 changed: C:\Users\aaluij\Documents\Delta Lake Explorer\delta-lake-explorer\streamlit_test_read_delta.py
2024-12-10 15:24:23.540 File/dir MD5 changed: C:\Users\aaluij\Documents\Delta Lake Explorer\delta-lake-explorer\streamlit_test_read_delta.py
2024-12-10 15:27:12.919 Runtime stopping...
2024-12-10 15:27:12.919 Runtime state: RuntimeState.ONE_OR_MORE_SESSIONS_CONNECTED -> RuntimeState.STOPPING
2024-12-10 15:27:12.920 Shutting down (id=2cabcd25-6fd9-4859-a20e-ade58f98fce0)
2024-12-10 15:27:12.921 Disconnecting files for session with ID 2cabcd25-6fd9-4859-a20e-ade58f98fce0
2024-12-10 15:27:12.921 Sessions still active: dict_keys([])
2024-12-10 15:27:12.921 Files: 0; Sessions with files: 0
2024-12-10 15:27:12.921 Removing orphaned files...
2024-12-10 15:27:12.922 Shutting down (id=14a2ee98-7f8d-4b55-b078-ed0aab430288)
2024-12-10 15:27:12.922 Disconnecting files for session with ID 14a2ee98-7f8d-4b55-b078-ed0aab430288
2024-12-10 15:27:12.922 Sessions still active: dict_keys([])
2024-12-10 15:27:12.923 Files: 0; Sessions with files: 0
2024-12-10 15:27:12.925 Removing orphaned files...
2024-12-10 15:27:12.925 Shutting down (id=5c54028b-6b52-4020-bea6-fb2f08246576)
2024-12-10 15:27:12.925 Disconnecting files for session with ID 5c54028b-6b52-4020-bea6-fb2f08246576
2024-12-10 15:27:12.925 Sessions still active: dict_keys([])
2024-12-10 15:27:12.925 Files: 0; Sessions with files: 0
2024-12-10 15:27:12.925 Removing orphaned files...
2024-12-10 15:27:12.927 Shutting down (id=481a202c-d43b-4a6e-9db4-ed2dbaf0ea8b)
2024-12-10 15:27:12.927 Disconnecting files for session with ID 481a202c-d43b-4a6e-9db4-ed2dbaf0ea8b
2024-12-10 15:27:12.927 Sessions still active: dict_keys([])
2024-12-10 15:27:12.927 Files: 0; Sessions with files: 0
2024-12-10 15:27:12.927 Removing orphaned files...
2024-12-10 15:27:12.927 Shutting down (id=2725e756-1006-49be-b7c8-63d47c5629c3)
2024-12-10 15:27:12.927 Disconnecting files for session with ID 2725e756-1006-49be-b7c8-63d47c5629c3
2024-12-10 15:27:12.927 Sessions still active: dict_keys([])
2024-12-10 15:27:12.928 Files: 0; Sessions with files: 0
2024-12-10 15:27:12.928 Removing orphaned files...
2024-12-10 15:27:12.928 Shutting down (id=00e0f886-d529-4e8c-a320-d36874800de4)
2024-12-10 15:27:12.928 Disconnecting files for session with ID 00e0f886-d529-4e8c-a320-d36874800de4
2024-12-10 15:27:12.928 Sessions still active: dict_keys([])
2024-12-10 15:27:12.928 Files: 0; Sessions with files: 0
2024-12-10 15:27:12.928 Removing orphaned files...
2024-12-10 15:27:12.929 Shutting down (id=d0762f52-6e3e-4e4e-8b63-e67b67c48083)
2024-12-10 15:27:12.929 Disconnecting files for session with ID d0762f52-6e3e-4e4e-8b63-e67b67c48083
2024-12-10 15:27:12.929 Sessions still active: dict_keys([])
2024-12-10 15:27:12.929 Files: 0; Sessions with files: 0
2024-12-10 15:27:12.929 Removing orphaned files...
2024-12-10 15:27:12.929 Shutting down (id=516f15d2-a444-412c-ba1e-685107e43cc4)
2024-12-10 15:27:12.929 Disconnecting files for session with ID 516f15d2-a444-412c-ba1e-685107e43cc4
2024-12-10 15:27:12.929 Sessions still active: dict_keys([])
2024-12-10 15:27:12.929 Files: 0; Sessions with files: 0
2024-12-10 15:27:12.929 Removing orphaned files...
2024-12-10 15:27:12.930 Runtime state: RuntimeState.STOPPING -> RuntimeState.STOPPED
```

### Issue description

Hi there,

I'm trying to create a little Delta Lake app in which a user can input and a query against the latest version of a Delta Table on AWS S3 using Polars. I created the code on my local machine, where it runs fine (using the default Python interpreter / debugger in VS Code) on any table I have in my datalake on S3. But, when running the exact same code from inside a streamlit app, it returns a ComputeError: Object at location .../part-00001-747373c8-281b-4f70-937d-358e2a4e121d-c000.zstd.parquet not found: Client error with status 404 Not Found.

After inspecting the checkpoint file, the commits and the files in the bucket, the part-00001-747373c8-281b-4f70-937d-358e2a4e121d-c000.zstd.parquet file indeed does not exist, and it is not part of the latest version of the table (it got removed by some earlier vacuum action done by some other code that updates the delta table daily). It is, however, included in an older of the table, which happens to be the checkpoint version. As such, the file is referenced as added by the checkpoint file and in the commit creating the checkpoint version.  Again, running locally, this is not a problem, and the code (polars.read_delta(tablepath, storageoptions)) just returns the latest version of the table as expected). 
I realize that vacuuming daily (with dry_run = False) icw relying on default checkpointing behavior is not a good choice (breaks the ability to time-travel), but that is not really the issue here, as I'm not trying to read an older version, I'm reading the latest version. 

To reproduce, I have added a minimal example that creates a tiny delta table in a local folder (instead of S3). It creates version 0 of the table, and writes a single parquet file. The code then creates a checkpoint, referring to version 0 and that single parquet file. After sleeping for 2 seconds, the code then deletes a single row from the delta table, creating version 1 and adding another file. The code then goes through all files in the table folder and deletes the parquet file that was written first (the file created in v0), to simulate a vacuum deleting an older version, after which it tries to read the delta table again with polars.read_delta. Read_delta raises the os error FileNotFoundError: The system cannot find the file specified. 

To reproduce, paste the code from the minimal example in a streamlit_test_read_delta.py file, and run by using the following command:
streamlit run streamlit_test_read_delta.py --logger.level=debug 2>streamlit.log  

That final flag 2>streamlit.log redirects the stderr to a streamlit.log file

Edit: This code ran on polars 1.16, but I just upgraded to 1.17.1 and the same error is raised.
 

### Expected behavior

I expect polars returning a dataframe that represents the latest version of the table: 
![Screenshot Streamlit Delta Table v0](https://github.com/user-attachments/assets/7a2385c8-f0fc-4dae-ae90-c99d1238dc7c) 
If I run the minimal example with deleting any files from disk (mimicking the vacuum) but creating two table version by deleting a row from the table, the code does not error out but it also does not return only the data in the latest version. Instead, it returns a single dataframe in which data from v0 and v1 are appended: ![Screenshot Streamlit Delta Table](https://github.com/user-attachments/assets/a1159097-4843-4876-824c-3c368467ce0b) 
This leaves me to believe that read_delta inside streamlit cannot handle versioned Delta Tables (adapted the title to reflect this).

### Installed versions

<details>

```
--------Version info---------
Polars:              1.16.0
Index type:          UInt32
Platform:            Windows-10-10.0.26100-SP0
Python:              3.11.9 (tags/v3.11.9:de54cf5, Apr  2 2024, 10:12:12) [MSC v.1938 64 bit (AMD64)]
LTS CPU:             False

----Optional dependencies----
adbc_driver_manager  <not installed>
altair               5.5.0
boto3                <not installed>
cloudpickle          <not installed>
connectorx           <not installed>
deltalake            0.22.2
fastexcel            <not installed>
fsspec               <not installed>
gevent               <not installed>
google.auth          <not installed>
great_tables         <not installed>
matplotlib           <not installed>
nest_asyncio         <not installed>
numpy                2.1.3
openpyxl             <not installed>
pandas               2.2.3
pyarrow              18.1.0
pydantic             <not installed>
pyiceberg            <not installed>
sqlalchemy           <not installed>
torch                <not installed>
xlsx2csv             <not installed>
xlsxwriter           <not installed>
```

</details>

**Comment by ion-elgreco** [comment]
Deltalake 0.22.2 got yanked due to some issues that occured with checkpoint log replay. 

0.22.3 should resolve your issue

**Comment by AnskePlanon** [comment]
> Deltalake 0.22.2 got yanked due to some issues that occured with checkpoint log replay.
> 
> 0.22.3 should resolve your issue @AnskePlanon

Great, thanks, that indeed solved my issue :-).

**Comment by ion-elgreco** [comment]
@stinodego this one is resolved
