### ISSUE TITLE
bug: pl.cum_sum_horizontal(pl.all()).struct.unnest() raises

### ISSUE THREAD

**Issue by MarcoGorelli** [pola-rs/polars#20277]
### Checks

- [X] I have checked that this issue has not already been reported.
- [X] I have confirmed this bug exists on the [latest version](https://pypi.org/project/polars/) of Polars.

### Reproducible example

```python
import polars as pl

df = pl.DataFrame({'a': [1,2,3], 'b': [4,5,6]})
print(df.select(c=pl.cum_sum_horizontal(pl.all())).select(pl.col('c').struct.unnest()))
print(df.select(pl.cum_sum_horizontal(pl.all()).struct.unnest()))
```

### Log output

```shell
shape: (3, 2)
┌─────┬─────┐
│ a   ┆ b   │
│ --- ┆ --- │
│ i64 ┆ i64 │
╞═════╪═════╡
│ 1   ┆ 5   │
│ 2   ┆ 7   │
│ 3   ┆ 9   │
└─────┴─────┘
Traceback (most recent call last):
  File "/home/marcogorelli/scratch/t.py", line 5, in <module>
    print(df.select(pl.cum_sum_horizontal(pl.all()).struct.unnest()))
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/marcogorelli/scratch/.venv/lib/python3.12/site-packages/polars/dataframe/frame.py", line 9322, in select
    return self.lazy().select(*exprs, **named_exprs).collect(_eager=True)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/marcogorelli/scratch/.venv/lib/python3.12/site-packages/polars/lazyframe/frame.py", line 2031, in collect
    return wrap_df(ldf.collect(callback))
                   ^^^^^^^^^^^^^^^^^^^^^
polars.exceptions.StructFieldNotFoundError: literal
(scratch) marcogorelli@DESKTOP-U8OKFP3:~/scratch$ POLARS_VERBOSE=1 python t.py  | clip.exe
Traceback (most recent call last):
  File "/home/marcogorelli/scratch/t.py", line 5, in <module>
    print(df.select(pl.cum_sum_horizontal(pl.all()).struct.unnest()))
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/marcogorelli/scratch/.venv/lib/python3.12/site-packages/polars/dataframe/frame.py", line 9322, in select
    return self.lazy().select(*exprs, **named_exprs).collect(_eager=True)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/marcogorelli/scratch/.venv/lib/python3.12/site-packages/polars/lazyframe/frame.py", line 2031, in collect
    return wrap_df(ldf.collect(callback))
                   ^^^^^^^^^^^^^^^^^^^^^
polars.exceptions.StructFieldNotFoundError: literal
```

### Issue description

The first example works, but the second one raises

### Expected behavior

Should they produce the same output?

### Installed versions

<details>

```
--------Version info---------
Polars:              1.17.1
Index type:          UInt32
Platform:            Linux-5.15.167.4-microsoft-standard-WSL2-x86_64-with-glibc2.35
Python:              3.12.5 (main, Aug 14 2024, 05:08:31) [Clang 18.1.8 ]
LTS CPU:             False

----Optional dependencies----
adbc_driver_manager  <not installed>
altair               5.5.0
boto3                <not installed>
cloudpickle          3.0.0
connectorx           <not installed>
deltalake            <not installed>
fastexcel            <not installed>
fsspec               2024.9.0
gevent               <not installed>
google.auth          <not installed>
great_tables         0.14.0
matplotlib           3.9.2
nest_asyncio         1.6.0
numpy                2.1.3
openpyxl             <not installed>
pandas               2.2.3
pyarrow              18.1.0
pydantic             <not installed>
pyiceberg            <not installed>
sqlalchemy           <not installed>
torch                <not installed>
xlsx2csv             <not installed>
xlsxwriter           <not installed>
None

```

</details>

**Comment by cmdlineluser** [comment]
It seems to be the underlying `cum_fold` which adds `acc=` to the Schema.

https://github.com/pola-rs/polars/blob/08ddc4b2a320dc03a4d6c3eda210bd384fad6d0e/py-polars/polars/functions/aggregation/horizontal.py#L296

```python
df.lazy().select(pl.cum_fold(0, lambda x, y: x + y, pl.all())).collect_schema()
# Schema([('cum_fold', Struct({'a': Int64, 'b': Int64, 'literal': Int64}))])
#                                                       ^^^^^^^
```

`cum_reduce` doesn't have that issue

```python
df.select(pl.cum_reduce(lambda x, y: x + y, pl.all()).struct.unnest())
# shape: (3, 2)
# ┌─────┬─────┐
# │ a   ┆ b   │
# │ --- ┆ --- │
# │ i64 ┆ i64 │
# ╞═════╪═════╡
# │ 1   ┆ 5   │
# │ 2   ┆ 7   │
# │ 3   ┆ 9   │
# └─────┴─────┘
```

I'm assuming cum_fold is used to specify the initital UInt32 dtype? 

(But it actually returns `i64` in this example?) 

Just noticed it also panics for an empty call.

```python
df.select(pl.cum_sum_horizontal())
# PanicException: index out of bounds: the len is 0 but the index is 0
```
