### ISSUE TITLE
Panic of `LazyFrame::scan_parquet` with hive partitioned parquet files occurring with polars 0.45.0 (0.44.0 works)

### ISSUE THREAD

**Issue by ericdoerheit** [pola-rs/polars#20279]
### Checks

- [X] I have checked that this issue has not already been reported.
- [X] I have confirmed this bug exists on the [latest version](https://crates.io/crates/polars) of Polars.

### Reproducible example

```rust
use chrono::{Datelike, NaiveDate};
use fastrand::Rng;
use polars::prelude::ParquetWriter;
use polars::prelude::*;
use std::fs;
use std::iter::repeat_with;
use std::path::PathBuf;

const TEST_DIR_DATA: &str = "tmp/data";

fn generate_and_save_test_data() {
    fastrand::seed(42);
    let mut rng = Rng::new();
    let base_directory = TEST_DIR_DATA.to_string();
    let source = 1;
    let start_date = NaiveDate::from_ymd_opt(2021, 1, 1).unwrap();
    let end_date = NaiveDate::from_ymd_opt(2021, 1, 2).unwrap();
    let mut date = start_date.clone() - chrono::Duration::days(1);

    while date < end_date {
        date += chrono::Duration::days(1);
        let dir_path = format!("{}/source={}/year={}",
                               base_directory, source,
                               date.year());

        if fs::metadata(dir_path.clone()).is_ok() {
            // Omit the creation of the data frames if the directory already exists
            continue;
        } else {
            // Create the directory if it does not exist
            match fs::create_dir_all(dir_path.clone()) {
                Ok(_) => (),
                Err(e) => println!("Error creating directory: {}", e),
            }
        }

        let mut df = create_dataframe(&mut rng, date.clone());
        let file_path = format!("{}/{}.parquet", dir_path, date);
        let file = fs::File::create(file_path).unwrap();
        ParquetWriter::new(file).with_row_group_size(Some(1024)).finish(&mut df).unwrap();
    }
}

fn create_dataframe(rng: &mut Rng, date: NaiveDate) -> DataFrame {
    let frame_interval_ms = 4000;

    let start = date.and_hms_opt(0, 0, 0).unwrap().and_utc().timestamp_millis();
    let end = date.and_hms_opt(23, 59, 59).unwrap().and_utc().timestamp_millis();

    let timestamps: Vec<i64> = (start..end).filter(|x| *x % frame_interval_ms == 0).collect();

    let x: Vec<f32> = repeat_with(|| rng.f32()).take(timestamps.len()).collect();
    let y: Vec<f32> = repeat_with(|| rng.f32()).take(timestamps.len()).collect();
    let z: Vec<f32> = vec![0.0; timestamps.len()];

    df!(
        "timestamp" => &timestamps.clone(),
        "x" => &x.clone(),
        "y" => &y.clone(),
        "z" => &z.clone(),
    ).unwrap()
}

#[test]
fn test_polars_parquet_scan() {
    generate_and_save_test_data();

    let schema_path = format!("{}/*/*/*.parquet", TEST_DIR_DATA.to_string());
    let schema_path = PathBuf::from(schema_path);

    let lf = LazyFrame::scan_parquet(schema_path, ScanArgsParquet::default()).unwrap();
    let lf = lf
        .filter(
            col("year").eq(lit(2021))
                .and(col("x").gt(lit(0.7)))
                .and(col("y").lt(lit(0.5)))
                .and(col("z").eq(lit(0)))
        ).collect().unwrap();
    lf.get_columns().iter().for_each(|s| println!("{} {}", s.name(), s.len()));
    println!("Result:\n{}", lf);
}
```

Cargo.toml:
```toml
[package]
name = "rust-experiments"
version = "0.1.0"
edition = "2021"

[dependencies]
chrono = "0.4.38"
fastrand = "2.0.2"
glob = "0.3.1"
polars = { version = "0.45.0", features = [
    "lazy", "streaming", "ndarray", "parquet", "rows", "diagonal_concat",
    "rolling_window", "dtype-full", "polars-io", "sql", "binary_encoding",
    "dtype-categorical"
] }
hashbrown = { version = "0.14.5", features = ["raw"] }
```

### Log output

```shell
Testing started at 08:24 ...
    Finished `test` profile [unoptimized + debuginfo] target(s) in 0.18s
     Running tests\test_polars_scan_parquet_hive.rs (target\debug\deps\test_polars_scan_parquet_hive-f0d44efe137b8ac0.exe)
thread 'test_polars_parquet_scan' panicked at C:\Users\ericd\.cargo\registry\src\index.crates.io-6f17d22bba15001f\polars-core-0.45.1\src\fmt.rs:575:13:
The column lengths in the DataFrame are not equal.
stack backtrace:
   0: std::panicking::begin_panic_handler
             at /rustc/90b35a6239c3d8bdabc530a6a0816f7ff89a0aaf\library/std\src\panicking.rs:665
   1: core::panicking::panic_fmt
             at /rustc/90b35a6239c3d8bdabc530a6a0816f7ff89a0aaf\library/core\src\panicking.rs:74
   2: polars_core::fmt::impl$9::fmt
             at C:\Users\ericd\.cargo\registry\src\index.crates.io-6f17d22bba15001f\polars-core-0.45.1\src\fmt.rs:575
   3: core::fmt::rt::Argument::fmt
             at /rustc/90b35a6239c3d8bdabc530a6a0816f7ff89a0aaf\library/core\src\fmt\rt.rs:177
   4: core::fmt::write
             at /rustc/90b35a6239c3d8bdabc530a6a0816f7ff89a0aaf\library/core\src\fmt\mod.rs:1186
   5: std::io::Write::write_fmt<alloc::vec::Vec<u8,alloc::alloc::Global> >
             at /rustc/90b35a6239c3d8bdabc530a6a0816f7ff89a0aaf\library/std\src\io\mod.rs:1839
   6: std::io::stdio::print_to_buffer_if_capture_used::closure$0
             at /rustc/90b35a6239c3d8bdabc530a6a0816f7ff89a0aaf\library/std\src\io\stdio.rs:1133
   7: std::thread::local::LocalKey::try_with
             at /rustc/90b35a6239c3d8bdabc530a6a0816f7ff89a0aaf\library/std\src\thread\local.rs:283
   8: std::io::stdio::print_to_buffer_if_capture_used
             at /rustc/90b35a6239c3d8bdabc530a6a0816f7ff89a0aaf\library/std\src\io\stdio.rs:1129
   9: std::io::stdio::_print
             at /rustc/90b35a6239c3d8bdabc530a6a0816f7ff89a0aaf\library/std\src\io\stdio.rs:1232
  10: test_polars_scan_parquet_hive::test_polars_parquet_scan
             at .\tests\test_polars_scan_parquet_hive.rs:80
  11: test_polars_scan_parquet_hive::test_polars_parquet_scan::closure$0
             at .\tests\test_polars_scan_parquet_hive.rs:65
  12: core::ops::function::FnOnce::call_once<test_polars_scan_parquet_hive::test_polars_parquet_scan::closure_env$0,tuple$<> >
             at C:\Users\ericd\.rustup\toolchains\stable-x86_64-pc-windows-msvc\lib\rustlib\src\rust\library\core\src\ops\function.rs:250
  13: core::ops::function::FnOnce::call_once
             at /rustc/90b35a6239c3d8bdabc530a6a0816f7ff89a0aaf\library/core\src\ops\function.rs:250
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
parquet file must be read, statistics not sufficient for predicate.
parquet scan with parallel = Prefiltered
parquet live columns = 4, dead columns = 2
parquet file must be read, statistics not sufficient for predicate.
parquet file must be read, statistics not sufficient for predicate.
parquet file must be read, statistics not sufficient for predicate.
parquet file must be read, statistics not sufficient for predicate.
parquet file must be read, statistics not sufficient for predicate.
parquet file must be read, statistics not sufficient for predicate.
parquet file must be read, statistics not sufficient for predicate.
parquet file must be read, statistics not sufficient for predicate.
parquet file must be read, statistics not sufficient for predicate.
parquet file must be read, statistics not sufficient for predicate.
parquet file must be read, statistics not sufficient for predicate.
parquet file must be read, statistics not sufficient for predicate.
parquet file must be read, statistics not sufficient for predicate.
parquet file must be read, statistics not sufficient for predicate.
parquet file must be read, statistics not sufficient for predicate.
parquet file must be read, statistics not sufficient for predicate.
parquet file must be read, statistics not sufficient for predicate.
parquet file must be read, statistics not sufficient for predicate.
parquet row group must be read, statistics not sufficient for predicate.
parquet row group must be read, statistics not sufficient for predicate.
parquet file must be read, statistics not sufficient for predicate.
parquet file must be read, statistics not sufficient for predicate.
parquet row group must be read, statistics not sufficient for predicate.
parquet file must be read, statistics not sufficient for predicate.
parquet row group must be read, statistics not sufficient for predicate.
parquet row group must be read, statistics not sufficient for predicate.
parquet row group must be read, statistics not sufficient for predicate.
parquet row group must be read, statistics not sufficient for predicate.
parquet file must be read, statistics not sufficient for predicate.
parquet file must be read, statistics not sufficient for predicate.
parquet file must be read, statistics not sufficient for predicate.
parquet row group must be read, statistics not sufficient for predicate.
parquet file must be read, statistics not sufficient for predicate.
parquet file must be read, statistics not sufficient for predicate.
parquet file must be read, statistics not sufficient for predicate.
parquet row group must be read, statistics not sufficient for predicate.
parquet file must be read, statistics not sufficient for predicate.
parquet file must be read, statistics not sufficient for predicate.
parquet file must be read, statistics not sufficient for predicate.
parquet file must be read, statistics not sufficient for predicate.
parquet file must be read, statistics not sufficient for predicate.
parquet row group must be read, statistics not sufficient for predicate.
parquet file must be read, statistics not sufficient for predicate.
parquet row group must be read, statistics not sufficient for predicate.
parquet file must be read, statistics not sufficient for predicate.
parquet file must be read, statistics not sufficient for predicate.
parquet file must be read, statistics not sufficient for predicate.
parquet row group must be read, statistics not sufficient for predicate.
parquet file must be read, statistics not sufficient for predicate.
parquet file must be read, statistics not sufficient for predicate.
parquet file must be read, statistics not sufficient for predicate.
parquet row group must be read, statistics not sufficient for predicate.
parquet file must be read, statistics not sufficient for predicate.
parquet file must be read, statistics not sufficient for predicate.
parquet file must be read, statistics not sufficient for predicate.
parquet file must be read, statistics not sufficient for predicate.
parquet row group must be read, statistics not sufficient for predicate.
parquet file must be read, statistics not sufficient for predicate.
parquet file must be read, statistics not sufficient for predicate.
parquet row group must be read, statistics not sufficient for predicate.
parquet file must be read, statistics not sufficient for predicate.
parquet file must be read, statistics not sufficient for predicate.
parquet file must be read, statistics not sufficient for predicate.
parquet file must be read, statistics not sufficient for predicate.
parquet file must be read, statistics not sufficient for predicate.
parquet file must be read, statistics not sufficient for predicate.
parquet file must be read, statistics not sufficient for predicate.
parquet file must be read, statistics not sufficient for predicate.
parquet file must be read, statistics not sufficient for predicate.
parquet file must be read, statistics not sufficient for predicate.
parquet file must be read, statistics not sufficient for predicate.
parquet row group must be read, statistics not sufficient for predicate.
parquet file must be read, statistics not sufficient for predicate.
parquet file must be read, statistics not sufficient for predicate.
parquet file must be read, statistics not sufficient for predicate.
parquet row group must be read, statistics not sufficient for predicate.
parquet row group must be read, statistics not sufficient for predicate.
parquet file must be read, statistics not sufficient for predicate.
parquet file must be read, statistics not sufficient for predicate.
parquet file must be read, statistics not sufficient for predicate.
parquet row group must be read, statistics not sufficient for predicate.
parquet file must be read, statistics not sufficient for predicate.
parquet row group must be read, statistics not sufficient for predicate.
parquet row group must be read, statistics not sufficient for predicate.
timestamp 3265
x 3265
y 3265
z 3265
source 21600
year 21600
Result:


error: test failed, to rerun pass `-p rust-experiments --test test_polars_scan_parquet_hive`
error: 1 target failed:
    `-p rust-experiments --test test_polars_scan_parquet_hive`

Process finished with exit code 101
```

### Issue description

Scanning hive-partitioned parquet files that contain multiple row groups leads to unequal column lengths. Polars panics and prints `The column lengths in the DataFrame are not equal.`.

In particular, the columns that are added from the hive partitioning (the columns `source` and `year` in the example) have the full size, i.e. no rows are filtered. It seems that the columns are constructed no matter how many rows are actually in the returned data frame.

Furthermore, it looks like this only happens with parquet files that have multiple row groups. When I increase the row group size, the above test passes.

In polars 0.44.0 the test also passes. The issue arose with polars 0.45.0.

I think a test similar to the above should be added to the polars test suite.

Edit:
I found out that the test does not pass anymore starting with this commit [430bb](https://github.com/pola-rs/polars/commit/430bb4d1919acc2200b861286d201d39fbb39c12)

### Expected behavior

No panic and equal sized columns.

### Installed versions

<details>
polars = { version = "0.45.0", features = [
    "lazy", "streaming", "ndarray", "parquet", "rows", "diagonal_concat",
    "rolling_window", "dtype-full", "polars-io", "sql", "binary_encoding",
    "dtype-categorical"
] }
</details>

**Comment by kdn36** [comment]
Are you still seeing this issue?

I am unable to reproduce.

On latest main, Rust, (provided example modified for `PlPath`):
```
timestamp 3265
x 3265
y 3265
z 3265
source 3265
year 3265
Result:
shape: (3_265, 6)
┌───────────────┬──────────┬──────────┬─────┬────────┬──────┐
│ timestamp     ┆ x        ┆ y        ┆ z   ┆ source ┆ year │
│ ---           ┆ ---      ┆ ---      ┆ --- ┆ ---    ┆ ---  │
│ i64           ┆ f32      ┆ f32      ┆ f32 ┆ i64    ┆ i64  │
╞═══════════════╪══════════╪══════════╪═════╪════════╪══════╡
│ 1609459212000 ┆ 0.721517 ┆ 0.324488 ┆ 0.0 ┆ 1      ┆ 2021 │
│ 1609459228000 ┆ 0.762859 ┆ 0.434733 ┆ 0.0 ┆ 1      ┆ 2021 │
│ 1609459236000 ┆ 0.785977 ┆ 0.071697 ┆ 0.0 ┆ 1      ┆ 2021 │
│ 1609459280000 ┆ 0.714617 ┆ 0.080402 ┆ 0.0 ┆ 1      ┆ 2021 │
│ 1609459300000 ┆ 0.984916 ┆ 0.113453 ┆ 0.0 ┆ 1      ┆ 2021 │
│ …             ┆ …        ┆ …        ┆ …   ┆ …      ┆ …    │
│ 1609545356000 ┆ 0.736452 ┆ 0.299713 ┆ 0.0 ┆ 1      ┆ 2021 │
│ 1609545388000 ┆ 0.809845 ┆ 0.274621 ┆ 0.0 ┆ 1      ┆ 2021 │
│ 1609545408000 ┆ 0.862715 ┆ 0.128922 ┆ 0.0 ┆ 1      ┆ 2021 │
│ 1609545440000 ┆ 0.801115 ┆ 0.428291 ┆ 0.0 ┆ 1      ┆ 2021 │
│ 1609545544000 ┆ 0.966387 ┆ 0.258751 ┆ 0.0 ┆ 1      ┆ 2021 │
└───────────────┴──────────┴──────────┴─────┴────────┴──────┘
test test_polars_parquet_scan ... ok

test result: ok. 1 passed; 0 failed; 0 ignored; 0 measured; 0 filtered out; finished in 0.48s
```

Similar on python, using the Rust generated test data, provides the same result:
```
import polars as pl

lf = pl.scan_parquet("tmp/data/*/*/*.parquet", hive_partitioning=True)
out = lf.filter(
    pl.col("year").eq(pl.lit(2021))
    & (pl.col("x").gt(pl.lit(0.7)))
    & (pl.col("y").lt(pl.lit(0.5)))
    & (pl.col("z").eq(pl.lit(0)))
).collect()

print(out)
```
