### ISSUE TITLE
Unable to write directly to Azure Datalake Gen2 Storage

### ISSUE THREAD

**Issue by edgBR** [pola-rs/polars#20282]
### Checks

- [X] I have checked that this issue has not already been reported.
- [X] I have confirmed this bug exists on the [latest version](https://pypi.org/project/polars/) of Polars.

### Reproducible example

```python
import polars as pl
with pl.Config(verbose=True):
    df = pl.DataFrame({"text": ["spark is dead", "no more boilerplate code"]})
    df.write_parquet("abfss://YYYYY@XXXXX.dfs.core.windows.net/polars_test_native_cred/test.parquet")
...

```

### Log output

```shell
try_get_writeable: cloud: abfss://YYYYYY@XXXXXX.dfs.core.windows.net/polars_test_native_cred/test.parquet
Async thread count: 4
async upload_chunk_size: 67108864
thread '<unnamed>' panicked at crates\polars-io\src\cloud\adaptors.rs:132:50:
called `Result::unwrap()` on an `Err` value: ComputeError(ErrString("Generic MicrosoftAzure error: Error performing token request: Error after 2 retries in 316.5691ms, max_retries:2, retry_timeout:10s, source:error sending request for url (http://169.XXX.XXX.XXX/metadata/identity/oauth2/token?api-version=2019-08-01&resource=https%3A%2F%2Fstorage.azure.com)"))
stack backtrace:
   0:     0x7ffc75d57ffc - ffi_select_with_compiled_path
   1:     0x7ffc7076d61a - PyInit_polars
   2:     0x7ffc75d36e97 - ffi_select_with_compiled_path
   3:     0x7ffc75d59324 - ffi_select_with_compiled_path
   4:     0x7ffc75d597e7 - ffi_select_with_compiled_path
   5:     0x7ffc75d59409 - ffi_select_with_compiled_path
   6:     0x7ffc75d5935f - ffi_select_with_compiled_path
   7:     0x7ffc75d5934e - ffi_select_with_compiled_path
   8:     0x7ffc75e9b631 - ffi_select_with_compiled_path
   9:     0x7ffc75e9ba20 - ffi_select_with_compiled_path
  10:     0x7ffc7210aa6b - ffi_select_with_compiled_path
  11:     0x7ffc740046fc - ffi_select_with_compiled_path
  12:     0x7ffc7400bf35 - ffi_select_with_compiled_path
  13:     0x7ffc740085eb - ffi_select_with_compiled_path
  14:     0x7ffc74002a6e - ffi_select_with_compiled_path
  15:     0x7ffc74000dfa - ffi_select_with_compiled_path
  16:     0x7ffc73f7cc1f - ffi_select_with_compiled_path
  17:     0x7ffc73fe8b92 - ffi_select_with_compiled_path
  18:     0x7ffcd6ee3cc2 - cfunction_call
                               at \Objects\methodobject.c:543
  19:     0x7ffcd6e51ee5 - _PyObject_MakeTpCall
                               at \Objects\call.c:191
  20:     0x7ffcd6e61b1c - _PyEval_EvalFrameDefault
                               at \Python\ceval.c:3537
  21:     0x7ffcd6e5880f - _PyEval_EvalFrame
                               at \Include\internal\pycore_ceval.h:40
  22:     0x7ffcd6e5880f - _PyEval_EvalCode
                               at \Python\ceval.c:4329
  23:     0x7ffcd6e5c519 - _PyEval_EvalFrameDefault
                               at \Python\ceval.c:3506
  24:     0x7ffcd6e5880f - _PyEval_EvalFrame
                               at \Include\internal\pycore_ceval.h:40
  25:     0x7ffcd6e5880f - _PyEval_EvalCode
                               at \Python\ceval.c:4329
  26:     0x7ffcd6e924ed - _PyEval_EvalCodeWithName
                               at \Python\ceval.c:4361
  27:     0x7ffcd6ed7b67 - PyEval_EvalCodeEx
                               at \Python\ceval.c:4377
  28:     0x7ffcd6ed7ac5 - PyEval_EvalCode
                               at \Python\ceval.c:828
  29:     0x7ffcd6ed77e6 - run_eval_code_obj
                               at \Python\pythonrun.c:1221
  30:     0x7ffcd6ed7766 - run_mod
                               at \Python\pythonrun.c:1242
  31:     0x7ffcd70656ae - PyRun_InteractiveOneObjectEx
                               at \Python\pythonrun.c:274
  32:     0x7ffcd7065299 - PyRun_InteractiveLoopFlags
                               at \Python\pythonrun.c:127
  33:     0x7ffcd6fe4384 - PyRun_AnyFileExFlags
                               at \Python\pythonrun.c:86
  34:     0x7ffcd6fe425f - pymain_run_stdin
                               at \Modules\main.c:516
  35:     0x7ffcd6eca0fb - pymain_run_python
                               at \Modules\main.c:609
  36:     0x7ffcd6ec9fad - Py_RunMain
                               at \Modules\main.c:685
  37:     0x7ffcd6ec6ed3 - pymain_main
                               at \Modules\main.c:1081
  38:     0x7ffcd6ec6e89 - Py_Main
                               at \Modules\main.c:1093
  39:     0x7ff674b81264 - invoke_main
                               at D:\a\_work\1\s\src\vctools\crt\vcstartup\src\startup\exe_common.inl:90
  40:     0x7ff674b81264 - __scrt_common_main_seh
                               at D:\a\_work\1\s\src\vctools\crt\vcstartup\src\startup\exe_common.inl:288
  41:     0x7ffd2f5e7374 - BaseThreadInitThunk
  42:     0x7ffd3101cc91 - RtlUserThreadStart
Traceback (most recent call last):
Traceback (most recent call last):
  File "<stdin>", line 3, in <module>
  File "C:\Users\ebr\miniconda3\envs\devops\lib\site-packages\polars\dataframe\frame.py", line 4038, in write_parquet
    self._df.write_parquet(
pyo3_runtime.PanicException: called `Result::unwrap()` on an `Err` value: ComputeError(ErrString("Generic MicrosoftAzure error: Error performing token request: Error after 2 retries in 316.5691ms, max_retries:2, retry_timeout:10s, source:error sending request for url (http://169.XXX.XXX.XXX/metadata/identity/oauth2/token?api-version=2019-08-01&resource=https%3A%2F%2Fstorage.azure.com)"))
>>>
```

### Issue description

Hi!

Im trying to take advantage of the new features that allow us to write directly to object storage without handling the credentials ourselves.

Currently I am connected to an Azure VPN client to allow me to reach my storage account (as it is under a private endpoint).

Even that I have authenticated with Az Cli I can not write directly to storage.

### Expected behavior

I will expect that the code works in the same way as if I do:

```python
import polars as pl
with pl.Config(verbose=True):
    df = pl.DataFrame({"text": ["spark is dead", "no more boilerplate code"]})
    df.write_parquet("abfss://YYYYY@XXXXX.dfs.core.windows.net/polars_test_native_cred/test.parquet", storage_credentials={mycredentialshere})
...

### Installed versions

<details>

```
--------Version info---------
Polars:              1.17.1
Index type:          UInt32
Platform:            Windows-10-10.0.19045-SP0
Python:              3.9.20 (main, Oct  3 2024, 07:38:01) [MSC v.1929 64 bit (AMD64)]
LTS CPU:             False

----Optional dependencies----
adbc_driver_manager  <not installed>
altair               <not installed>
boto3                <not installed>
cloudpickle          <not installed>
connectorx           <not installed>
deltalake            0.22.3
fastexcel            <not installed>
fsspec               2024.10.0
gevent               <not installed>
google.auth          <not installed>
great_tables         <not installed>
matplotlib           3.9.3
nest_asyncio         1.6.0
numpy                2.0.2
openpyxl             <not installed>
pandas               2.2.3
pyarrow              18.1.0
pydantic             <not installed>
pyiceberg            <not installed>
sqlalchemy           <not installed>
torch                <not installed>
xlsx2csv             <not installed>
xlsxwriter           <not installed>
```

</details>

**Comment by ion-elgreco** [comment]
@edgBR you need to explicitly tell object store to use azure cli with `use_az_cli` https://docs.rs/object_store/0.11.1/object_store/azure/enum.AzureConfigKey.html

**Comment by edgBR** [comment]
Do I take this as incorrect?

![image](https://github.com/user-attachments/assets/82a2ac87-81fa-4145-9938-e178902c61a8)

**Comment by ion-elgreco** [comment]
> Do I take this as incorrect?
> 
> ![image](https://github.com/user-attachments/assets/82a2ac87-81fa-4145-9938-e178902c61a8)
> 

Impossible to see what authentication there is configured, might have been using env vars which automatically get parsed. But you mentioned you use azure cli, which needs to be explicitly set to be used

**Comment by edgBR** [comment]
I think I missunderstood the functionality then.

Currently we are doing this:

```python
.....

class AMLManager:
    """MLHelper utility class."""

    def __init__(self, client_id: str):
        """MLHelper constructor, creates chain credentials.

        Parameters
        ----------
        client_id : str
            The client ID associated with the managed identity, used when creating
            the `ManagedIdentityCredential`.

        """
        self.client_id = client_id
        self.credentials = self.get_chained_credentials()

    def get_chained_credentials(self):
        """Creates and returns a chained token credential for Azure authentication.

        This function initializes a `ChainedTokenCredential` instance that combines
        a managed identity credential and a default credential.

        Returns
        -------
        chained_creds : ChainedTokenCredential
            A chained token credential combining `ManagedIdentityCredential` and
            `AzureCliCredential`, allowing applications to authenticate using
            either managed identity or CLI credentials.
        """
        try:
            chained_creds = ChainedTokenCredential(
                AzureCliCredential(),
                ManagedIdentityCredential(client_id=self.client_id),
            )
            return chained_creds
        except Exception as e:
            raise e
....
```


```python
....

from utils.logger import Logger
from utils.sdk_utils import AMLManager

logging = Logger().getLogger(__name__)


class Preprocessor(AMLManager):
    """

    Attributes
    ----------
    logger : class
        A custom logger initialized in a separate class according to the format
        standards of XXXXX.
    ......
    storage_credentials : None | dict
        A dictionary or an empty initialization containing the storage crendetials for
        delta lake and remote polars operations.
    delta_table_version : None | int
        An integer storing the delta table version to tag it in AzureML.
    preprocessing_utils : PreprocessUtils
    A class containing utility functions for preprocessing.
    """

    def __init__(self, args: argparse.Namespace) -> None:
        """Init the preprocessing class.

        Args:
            args (argparse.Namespace):
        """
        '''''''''
        ## Super class initiation and clients
        super().__init__(self.cluster_identity_id)
        self.setup_client_workspace(
            subscription_id=self.subscription_id,
            resource_group=self.resource_group,
            workspace_name=self.workspace_name,
        )
        ....

    def get_storage_credentials(self) -> None:
        """Gets storage credentials using AD Token Auth."""
        self.logger.info("Set credentials")
        token_credential = self.credentials.get_token("https://storage.azure.com/.default")
        self.storage_credentials = {"account_name": self.account_name, "token": token_credential.token}

   def landing_to_bronze(self) -> None:
        """The method converts parquet files into append only delta tables."""
        try:
            self.logger.info(f"Reading raw landing file {self.args.landing_file_name}")

            raw_data = (
                pl.scan_parquet(
                    source=f"""abfss://{self.landing_container}/{self.landing_table}/{self.args.landing_file_name}""",
                    storage_options=self.storage_credentials,
          .....

```

My expectations were that with the new upgrades in polars I will not need to specify anything as by default it will get the credentials from environment variables in the same way that AzureCliCredential() picks them from env variables when az login is executed before running your python script.

**Comment by ion-elgreco** [comment]
> Hi @ion-elgreco should I close this (not sure if you had the time to look to my previous comment).

I did but I didn't see you try using the the use_azure_cli flag yet in the storage options or env vars, could you give that a go first

**Comment by edgBR** [comment]
Hi @ion-elgreco 

Apologies, I answered in my mind. I deed when using azure cli flag after running az login everything works as expected.

I was wandering tough if it would be possible to share/document/point in the code what is the default credential resolution polars does. Just similar to the authorization flow than azure identity uses when you use DefaultAzureCredential()

BR
E
