### ISSUE TITLE
`concat` + `sink_parquet` creates corrupt file instead of raising `ShapeError`

### ISSUE THREAD

**Issue by cmdlineluser** [pola-rs/polars#20355]
### Checks

- [X] I have checked that this issue has not already been reported.
- [X] I have confirmed this bug exists on the [latest version](https://pypi.org/project/polars/) of Polars.

### Reproducible example

```python
import polars as pl

lf1 = pl.LazyFrame({"x": [1], "y": [None]})
lf2 = pl.LazyFrame({"y": [1]})

pl.concat([lf1, lf2]).sink_parquet("20355.parquet")

print(pl.read_parquet("20355.parquet"))

# ComputeError: parquet: File out of specification: The number of columns in the row group (1) must be equal to the number of columns in the schema (2)
```

### Log output

```shell
try_get_writeable: local: 20355.parquet (canonicalize: Ok("/Users/user/20355.parquet"))
RUN STREAMING PIPELINE
[df -> union -> parquet_sink, df -> union -> parquet_sink]
```

### Issue description

`.collect()` raises a ShapeError as expected.

```python
pl.concat([lf1, lf2]).collect()
# ShapeError: unable to append to a DataFrame of width 2 with a DataFrame of width 1
```

They are probably all the same issue, but:

`.collect(streaming=True)` causes a PanicException.

`.sink_csv()` also has a different panic.

```python
thread '<unnamed>' panicked at crates/polars-pipe/src/operators/chunks.rs:81:18:
These are chunks from the same dataframe: ShapeMismatch(ErrString("unable to append to a DataFrame of width 2 with a DataFrame of width 1"))
thread '<unnamed>' panicked at crates/polars-pipe/src/executors/sinks/output/file_sink.rs:110:14:
called `Result::unwrap()` on an `Err` value: Any { .. }
```

### Expected behavior

ShapeError

### Installed versions

<details>

```
--------Version info---------
Polars:              1.17.1
Index type:          UInt32
Platform:            macOS-13.6.1-arm64-arm-64bit-Mach-O
Python:              3.13.0 (main, Oct  7 2024, 05:02:14) [Clang 15.0.0 (clang-1500.1.0.2.5)]
LTS CPU:             False

----Optional dependencies----
adbc_driver_manager  <not installed>
altair               <not installed>
boto3                <not installed>
cloudpickle          <not installed>
connectorx           <not installed>
deltalake            <not installed>
fastexcel            0.12.0
fsspec               <not installed>
gevent               <not installed>
google.auth          <not installed>
great_tables         0.14.0
matplotlib           <not installed>
nest_asyncio         <not installed>
numpy                2.1.3
openpyxl             3.1.5
pandas               2.2.3
pyarrow              18.0.0
pydantic             <not installed>
pyiceberg            <not installed>
sqlalchemy           <not installed>
torch                <not installed>
xlsx2csv             <not installed>
xlsxwriter           3.2.0
```

</details>

**Comment by ritchie46** [comment]
Ah, yes. We should catch this much higher up.
