### ISSUE TITLE
`SchemaFieldNotFoundError` with `rename` and `select` combination

### ISSUE THREAD

**Issue by c0dearm** [pola-rs/polars#20407]
### Checks

- [X] I have checked that this issue has not already been reported.
- [X] I have confirmed this bug exists on the [latest version](https://pypi.org/project/polars/) of Polars.

### Reproducible example

```python
import polars as pl

pl.LazyFrame({"TEST": [1]}).rename({"NOT FOUND": "TEST"}, strict=False).select("TEST").collect()
```

### Log output

```shell
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/Users/aitor/Projects/.venv/lib/python3.12/site-packages/polars/lazyframe/frame.py", line 2031, in collect
    return wrap_df(ldf.collect(callback))
                   ^^^^^^^^^^^^^^^^^^^^^
polars.exceptions.SchemaFieldNotFoundError: NOT FOUND
```

### Issue description

This combination of `rename` + `select` causes the issue shown above.

### Expected behavior

Polars complains about not finding the `NOT FOUND` field, but the select is on the `TEST` field and the renaming was not strict, so it shouldn't complain and should successfully return a `DataFrame` with the `TEST` column.

### Installed versions

<details>

```
--------Version info---------
Polars:              1.17.1
Index type:          UInt32
Platform:            macOS-15.0.1-arm64-arm-64bit
Python:              3.12.6 (main, Sep  6 2024, 19:03:47) [Clang 16.0.0 (clang-1600.0.26.3)]
LTS CPU:             False

----Optional dependencies----
adbc_driver_manager  <not installed>
altair               <not installed>
boto3                1.35.81
cloudpickle          3.1.0
connectorx           <not installed>
deltalake            <not installed>
fastexcel            <not installed>
fsspec               <not installed>
gevent               <not installed>
google.auth          2.37.0
great_tables         <not installed>
matplotlib           3.10.0
nest_asyncio         <not installed>
numpy                2.2.1
openpyxl             <not installed>
pandas               2.2.3
pyarrow              18.1.0
pydantic             2.10.4
pyiceberg            <not installed>
sqlalchemy           2.0.36
torch                <not installed>
xlsx2csv             <not installed>
xlsxwriter           <not installed>
```

</details>

**Comment by c0dearm** [comment]
The workaround for now is to do `.collect(projection_pushdown=True)`, but I say we should fix it for good! 😄

**Comment by magbak** [comment]
In Rust at latest (91d04b855a37aa116b6f871c8be0a1b4ab770434): 
`
#[test]
    fn rename() {
        let s = Column::new_empty("s".into(), &DataType::Null);
        let mut df = DataFrame::new(vec![s]).unwrap();
        df.rename("s".into(), "o".into()).unwrap();
        assert!(df.column("o").is_ok());
        df.lazy().select([col("o")]).collect().unwrap();
    }
`

Results in called: `Result::unwrap()` on an `Err` value: ColumnNotFound(ErrString("o\n\nResolved plan until failure:\n\n\t---> FAILED HERE RESOLVING 'select' <---\nDF [\"s\"]; PROJECT */1 COLUMNS"))

**Comment by cmdlineluser** [comment]
@KronosTheLate You should create a new issue for that if possible. 

As it is a `join` problem, I think it would be of higher priority.

**Comment by wi-ski** [comment]
Same issue.

**Comment by sharky564** [comment]
I was having this exact same issue below:
```python
df = pl.LazyFrame({'a': [1, 2], 'b': [2, 3], 'c': [3, 4]})
column_mapping = {'x': 'c'}
renamed_df = df.rename(column_mapping, strict=False) # should do nothing
out_df = renamed_df.filter(pl.col('c') > 3)
out_df.collect()
```
would give me a ColumnNotFoundError. My fix was to replace the dictionary with a lambda function which would behave like the dictionary
```python
df = pl.LazyFrame({'a': [1, 2], 'b': [2, 3], 'c': [3, 4]})
column_mapping = {'x': 'c'}
renamed_df = df.rename(lambda t: column_mapping.get(t, t))
out_df = renamed_df.filter(pl.col('c') > 3)
print(out_df.collect())
```
