### ISSUE TITLE
Cannot read the delta table if that table was written with a dataframe that had columns with categorical dtype.

### ISSUE THREAD

**Issue by SidPharVision** [pola-rs/polars#20438]
### Checks

- [X] I have checked that this issue has not already been reported.
- [X] I have confirmed this bug exists on the [latest version](https://pypi.org/project/polars/) of Polars.

### Reproducible example

```python

import polars as pl

# Create a hard-coded DataFrame with a string column
df = pl.DataFrame({
    "id": [1, 2, 3, 4, 5],
    "value": [0.5, 0.8, 0.3, 0.9, 0.1],
    "category": ["apple", "banana", "cherry", "date", "elderberry"]
})

df = df.cast({"category" : pl.Categorical})

path_to_delta_table = "Path_to_delta_table"
df.write_delta(path_to_delta_table)

#re-read the table

df_new = pl.read_delta(path_to_delta_table) # errors out

```

### Log output

```shell
---------------------------------------------------------------------------
SchemaError                               Traceback (most recent call last)
Cell In[28], line 15
     11 df.write_delta(path_to_delta_table)
     13 #re-read the table
---> 15 df_new = pl.read_delta(path_to_delta_table) # errors out

File /usr/local/lib/python3.9/site-packages/polars/io/delta.py:149, in read_delta(source, version, columns, rechunk, storage_options, delta_table_options, use_pyarrow, pyarrow_options)
    147 if columns is not None:
    148     df = df.select(columns)
--> 149 return df.collect()

File /usr/local/lib/python3.9/site-packages/polars/lazyframe/frame.py:2029, in LazyFrame.collect(self, type_coercion, predicate_pushdown, projection_pushdown, simplify_expression, slice_pushdown, comm_subplan_elim, comm_subexpr_elim, cluster_with_columns, collapse_joins, no_optimization, streaming, engine, background, _eager, **_kwargs)
   2027 # Only for testing purposes
   2028 callback = _kwargs.get("post_opt_callback", callback)
-> 2029 return wrap_df(ldf.collect(callback))

SchemaError: dtypes differ for column category: Dictionary(UInt32, Utf8View, false) != Utf8View
```

### Issue description

This issue was observed in 1.16 and still exists in 1.18.
I can confirm this that it did not exists till 1.12 version.

### Expected behavior

Table read operation should be successful. If possible, the data schema should reflect those columns as categorical instead of string columns.

### Installed versions

<details>

```
--------Version info---------
Polars:              1.16.0
Index type:          UInt32
Platform:            Linux-6.8.0-49-generic-x86_64-with-glibc2.36
Python:              3.9.21 (main, Dec  4 2024, 20:35:10) 
[GCC 12.2.0]
LTS CPU:             False

----Optional dependencies----
adbc_driver_manager  <not installed>
altair               4.2.2
boto3                1.28.64
cloudpickle          3.0.0
connectorx           <not installed>
deltalake            0.21.0
fastexcel            <not installed>
fsspec               2024.6.1
gevent               <not installed>
google.auth          <not installed>
great_tables         <not installed>
matplotlib           3.8.4
nest_asyncio         1.6.0
numpy                1.23.5
openpyxl             <not installed>
pandas               1.1.3
pyarrow              16.0.0
pydantic             2.7.4
pyiceberg            <not installed>
sqlalchemy           <not installed>
torch                2.3.1+cu118
xlsx2csv             <not installed>
xlsxwriter           3.2.0
```

</details>

**Comment by yxtay** [comment]
Raising a somewhat related issue. `write_delta` now fails if there is a categorical column. It used to work. I'm not sure when the regression happened.

```
>>> df.write_delta(path_to_delta_table)

thread 'tokio-runtime-worker' panicked at /Users/runner/.cargo/registry/src/index.crates.io-6f17d22bba15001f/parquet-53.3.0/src/arrow/arrow_writer/byte_array.rs:462:9:
internal error: entered unreachable code: cannot downcast Utf8View dictionary value to byte array
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/yuxuantay/git/matrix-factorization-torch/.venv/lib/python3.11/site-packages/polars/dataframe/frame.py", line 4550, in write_delta
    write_deltalake(
  File "/Users/yuxuantay/git/matrix-factorization-torch/.venv/lib/python3.11/site-packages/deltalake/writer.py", line 323, in write_deltalake
    write_deltalake_rust(
_internal.DeltaError: Generic error: Failed to execute write task: task 22 panicked with message "internal error: entered unreachable code: cannot downcast Utf8View dictionary value to byte array"
```

**Comment by npetkov** [comment]
I can confirm that using version 1.17.0, it is not even possible to write the table, as @yxtay noted above. This is a regression from 1.16.0.
