### ISSUE TITLE
OSError when trying to user polars in PyCafe

### ISSUE THREAD

**Issue by MarcSkovMadsen** [pola-rs/polars#20467]
### Checks

- [X] I have checked that this issue has not already been reported.
- [X] I have confirmed this bug exists on the [latest version](https://pypi.org/project/polars/) of Polars.

### Reproducible example

https://py.cafe/snippet/panel/v1?#c=H4sIAGh6bWcEA41YXW-rRhD9KxZPjmQTvjGW8tJKVSu1L-1DK9WVRfDaRiVAYfPhXt3_3jk7EGB3rVtHkcOenZkzZ86urXxxiuYknL1TvrRNJ1dtXotqlfertj7U41pT5V2vFqsDLbe1Kz6kqPuyqdcH501c8oPzoJBcXldPq4NTdmXvFv3bwTnUpzMttZXbifx0pLU1dqntJ3EmoJHHvJJ52a0f9od6Ra_imlPZp9Vqzc94nc4utrptU9Zyto7Xx9PB6UWbV8f38iSvB2ezxG-feCXqi2VD0VRNh02tKErRL3Biqt7p5bZd04pO0pa1qvQUe95mJUtZCYr-iZpG8DyiaOpzeXntxLEv8kqs_xVd8_RDXvXCviv_KPs_1rIs_v6lrH-Ton3yh43Dm9LGFTWNrawv7oerqivRf0OLq99ZAuvum7H750EQ3t4J-drVHKXmWbvKEOvFlB7cXnRv-TO18-BsnE7881p24kXUsicjqYBDd6ivUrb9_vGxvblFfhaPl-sjpS3PeSEfYalt16t3egvCeBfHcer5w8rWd_2d622LNsy2-XMZbsVLX3RlS7Y7hkf_GO-O73n_Egbu-1VVY3JER95a-FnRoMf2Jq9NjYUbaXAS2zfPDRLXJ6jKb82rdPZfyMIdzOzsA2qnaeSvzTuWh1QdPW2c4lpWp07Qpj8_EZk_90ISqNzg7P3Y2zgvZa1m4OxDfvpRlJcr1cFjeaKwc1mJ7ygryfh9UxPvWoC5rQK2bp95L21p6ejQqvP1r6-bzz0Ti6FQunOzNMu8NEiiIEvSxJ6b4qaUedu67c1Zpp3g-ZBd-SHvbhxP_pIiSzjy8wPf9QLPy4I0pKGHQXSXoNZY5kahl3hRtgsCL6Gwb4s9iPctoUeNF7QNAn7guXGShVns-WmahaTsdYB2Ufp_6EjR0XJefYvPuA-E8PN1o7xAJ4z21PkL9nxqTSkoHc2GFucX3WZ2K25aISeAHxgYbz06RbHrb0I33vhutKFzQvGy6XMgkZsR4lmRlJCAkNBAEkJ8QmINiSlTSKiZLaaVkGr5lNWjvyeEs0VDTDhDOBsQvU5Eq4HKptfhfkZu_gxhBqk1226ok1iRUZ15toiYMuJrSEwxkUICLVtM1cGcGcw1mNSB1kvEJ2Sc3FIdzGdHCBRdIogBgjpLBHXAADFLbogZ1Zkz4Plgpp41JhyyxTNkUjQzYjBTqKNrPU0byJxBTPtYA3BbxgBBjOmD0b16HeYGh-jIpI6uAepEd1wVE4I6JoO5E-cId4oY0yExIejUPHPINp6sOQM4ihXVY3g-Yz9LBAzGOnOHRLQa0IoNQR2wNuuM2aBoskDAAE6ED-aK8hTAGv3M60wx-nzYiTatY8owuXeJgBv60WNShWCuiIs26suC-sYINKEVRtFXbKA8W0zFRDFFaBip_kINTRSKOwLTNGPTAeXpLNGEVtANc040FGwCxRv9ehqa0H7cmVxXzwyHB5Q1VB3pakDFgH55ynrmmGIwSz4HekcJIYFSEmrosfSVjVCwsk0hHjiz83XOieKLKfANsEQRy6xsE4xJY_QbUbyNFdS4N31mhZMKrXwDBV_EwsM7DeV-x08Is6NQZbb7aoqFVoGB8mciPplsmUc1bFollJUzg7OJQmdvAxfgrtdRzBd17VrBz6gNVNeZTwoci7qmkiOKfs1YniBPwVQDrFLijPnqJ4Vv-nveQCzuTUb12Ml1YGXGYoI4odBZn8LkSbAyUfSL6du8wWgyZDb7xa2JzDgp-gRZK8Qisx6LuYKz_d5gt-Ok8N2vo-wNRs3MmD68YYvlU3bPsZgcnzJwNr0x3pM2Jcd7kl1AMyq7S1mXxfCRwMZha2RLMKVFVIwJCOjvBcjDzQiEyHS0lyBz5fSkxBxMKQIgX8JaWpx2njv8RudrDqZDTdS21IQKsappgCmRwMXJ14YmArMNKBIgzXwJ4iqBQqipKZRQHe4TftRa4bGAEITX0rIyOwJRkzw6B8cPXNSEGTVw1BYKGX3CgjvqE7UN4bEIEaCxkRYsURMWMxTie5xb0iL5UMB-SKv1yTVHQhrIHsJxwrWltYII-JZratryPANKC7ZGJM7SeIMb4Hg5WGti2JiKxZpck02trsIlyJFIb9gkpQWeCjYZIsxraiNjhdgmlqnAO4mKVPfcHGQneIqQMTKkxa3ONbVIEMKlbjUYBEfaO9qiT0SiJU0-nidAa80x0sKWz8qdSyohkK1pNfXcQ4Z8rBB_3TMiITwfXkvN8Qgi0pgnbAJtIYKWFiw5Eq1o8uH_IP8BIWZUX60WAAA

### Log output

```shell
ERROR:bokeh.application.application:Error running application handler <panel.io.handlers.ScriptHandler object at 0x3c43180>: No such device (os error 43)
File 'functions.py', line 682, in _read_csv_impl:
pydf = PyDataFrame.read_csv( Traceback (most recent call last):
  File "/lib/python3.12/site-packages/panel/io/handlers.py", line 412, in run
    exec(self._code, module.__dict__)
  File "/home/pyodide/project-files/app.py", line 7, in <module>
    df = pl.read_csv(path)
         ^^^^^^^^^^^^^^^^^
  File "/lib/python3.12/site-packages/polars/_utils/deprecation.py", line 92, in wrapper
    return function(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/lib/python3.12/site-packages/polars/_utils/deprecation.py", line 92, in wrapper
    return function(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/lib/python3.12/site-packages/polars/_utils/deprecation.py", line 92, in wrapper
    return function(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/lib/python3.12/site-packages/polars/io/csv/functions.py", line 534, in read_csv
    df = _read_csv_impl(
         ^^^^^^^^^^^^^^^
  File "/lib/python3.12/site-packages/polars/io/csv/functions.py", line 682, in _read_csv_impl
    pydf = PyDataFrame.read_csv(
           ^^^^^^^^^^^^^^^^^^^^^
OSError: No such device (os error 43)
```

### Issue description

I saw in https://x.com/DataPolars/status/1871786600981819805 that it should now be possible to use polars with pyodide. So I thought I would like to try it in py.cafe. After some struggling I found out how to [extract the wheel from github action artifact](https://py.cafe/docs/api#extract-wheel-from-a-github-action-artifact). But when using the library I get OSError.

### Expected behavior

I would expect to be able to use Polars in pyodide and pycafe.

### Installed versions

https://py.cafe/gh/artifact/pola-rs/polars/2358555701/polars-1.18.0-cp39-abi3-emscripten_3_1_58_wasm32.whl

**Comment by MarcSkovMadsen** [comment]
If I load data from a `https` url instead of "local file" it seems to work.

Next (no-polars) step is to figure out why Py.CAFE does not allow me to install altair>=5.4.0 for plotting with polars.

[Open on PY.CAFE](https://py.cafe/snippet/panel/v1?#c=H4sIAIF9bWcEA41Y24rjRhD9FaMnL3hk3WUNzEsCIYHkJfuQQBxMj9y2lWgkReq5OMv-e-p0SWOpu4eNl8VWn67bqVNlM1-8sj1K796rnrq2V6tONLJeiWHVNftmOmtr0Q_6sN7Tcdf48k3JZqjaZr33XuRZ7L1PGhHqsnpY7b2LUt1wv92eq0H550pdnh-fB9mXbUN2yi_bp20j1V_b3S7OoiDc9uJ1m52KOMjEMQrjYidFEpePIjnlxzTOs7A4BjKgz0LG26qvBr8cXvbevjmeKF5X-70UxwOdrZGCzuUoTwS06iBqJap-_el-36zoVV4E1fSwWq35Ga_jycdVv2urRs3O8Xp72HuD7ER9eK2O6rL3Nkv8-o7Xsjk7LpRt3fa41MmyksMCp0z1O738rm872Su6staRHtIg2KxUpWpJ1j9R0TCeWxCdp-r83MvDUIparv-Vffvwg6gH6b4l3qrh97Wqyr9_qZrPSnYP4XhxfNPc-LIhTVTN2X_zdXTd0c8ocfUbU-C8fbVu_zwSwtd7qZ77hq1GGWm1rRdd-uSTTl7EI5Xzydt4vfznuerlE6lmIJVqg32_byaBdVe_FCe5PV-25LY6iVJtode7ftDv9BbF6S5N05xkxid3oR_u_OCu7OLiTjxW8Z18Gsq-6kibh_gQHtLd4VUMT3Hkv150NE6O0lHXDsOi06DH7qoubYODK3FwlHcvgR9lfkhQLa7ts_Luv9B89JgU7z6ictpW_dq-4nh01dPTxisvVX3sJV364x1R4nGQikCtBu8-TION91Q1ugfefcxPP8rqfKE4eKyOZHaqavkdeSUav6dxE1UjkbkrAq7ePfJduoLRoVPv659fN-93blmMgfKdX-RFEeRRlkRFlmdu32R3cym6zu-u3tLtDZ432Vdv6sOL0-QvU2QKp_zCKPSDKAiKKI-p6XGUfJigUVjhJ7SAgqTYRVGQkdm3yR7J-xbRE8eLtK0Ewijw06yIizQI87yIidnLCO2S_P-ko2RPx6L-Vj7TPSSEf183Wgs0YXSnEU-48841uSB31Bs6nC-6zWwrbjqpbgA_MDBtPZqi1A83sZ9uQj_Z0JyQvWoHASTxC0ICJ5ITEhESW0hGSEhIaiApeYoJtb2ldBJTrJC8BvT5hrC3ZLSJZwh7A2LGSeg00t7MOFzPlFs4QziD3OltN8bJnMjEztxbQpkyEhpISjaJRiLDW0rRkTlnMOfgxg64XiIhIVPnluygPztCwOgSgQ0QxFkiiIMMYLPMDTYTO_MMuD_oaeC0iUdv6Qy5MVpYNugp2DG5vnUbyDyDlO4xB8htaQMENrYOJvWacTg3KMREbuyYHCBO8oGqUkIQx85grsQ5wpXCxlZISggqtWcO3qbJmmcARTGjpg33Z6pniSCDKc5cIQmdRnTiQhAHWdtxJm9gNFsgyABKhA7mjC4nax7nZmP2h5Xo4jolDzf1LhHkhnpMm1wj6Cvsko3-saB_MQLN6IRR1JVaKPcWXbFRdBEc8haIDTTTKHYEumnb5iPK3VmiGZ2gGs45M1BkE-m8UW9goBndx87kuKZnKDwir7yFTDbAYkT_ucum55Rs0EueA7OijJBIMwk2TFv6yUYosnJ1IR1zZuWbOWc6X3SBN8AShS1n5eogtjTq5am2swIbH3Wfs8KkgqvQQpEvbKHhnYFyvdM3hF1RrD27dXWzBVeRhfJ3Ir6ZXJ4nNlxcZeSVPSNnGwXPwQYqwK43UfQXcd1cQc-IDdTkmScFikVcm8kJRb22LXeQu2Czgaxyyhn9NSeFN_1H2oAt9iajpu1NdcjKtkUHMaHg2ezCTZPIykZRL7rv0gaj2ejZrhdbE54xKWYHmSvYwrNpy9PNm8XFM9SOSeHdb6KsDUZtz-g-tOGy5Sn7SLHoHE8Zcra1Me1JF5PTnmQVUI-q_lw1VTl-JbBwWBrFEszpEBExxRF9XoDc3IJAkEyjvQQ5V3ZPTMzBnCwA8hI23PLeRt-hN5qvOZiPMRHbERMspDqmBeaUBBYnrw2DBM42IkuA1PMliFUChhDTYAi7guuEHo1SuC1ICMQbbpmZHYGISRqdg9MXLmJCjAY4cQuGrDohwR3VidgW8TgECeDYcossERMSsxjiPc4lGZY8FJAf3Bp1cswpIQNkDWGcsLaMUmAB3XJMg1vuZ0Ruka1liVmaNrgFTsvBGRPNRlcc0uSYLGq9CpcgW8K9JZOcDrgruGSRMI9ptIwZYpk4ugLtZNpS77k5yEoIdEJWy-AWW51jGpZICEvdKTAQzvQ5uUWdsERJBn3cT4DOmJOlI1uelQ-WFI8gpOkU9VxDFn3MEP_csyxBPA-vI-Y0grC0-gmZgFuQYLjlH0SwRCkGffg7yH_lYg0-ChcAAA)

![image](https://github.com/user-attachments/assets/00b43513-1dbe-4309-add6-a82fdba14a6b)

**Comment by MarcSkovMadsen** [comment]
Ok. I can try to use Altair or hvplot directly as described in [Polars Dataviz Guide](https://docs.pola.rs/user-guide/misc/visualization/). Unfortunately both altair and hvplot require pyarrow installed. It [should be possible to install pyarrow in pyodide](https://github.com/pyodide/pyodide/issues/2933). But I'm not able to as I get

```bash
RuntimeError: No universal wheels found for pyarrow 18.1.0
```

![image](https://github.com/user-attachments/assets/c4458b43-90ef-4584-a427-9aadb5e977bf)

[Open reproducible example on PY.CAFE](https://py.cafe/snippet/panel/v1?#c=H4sIAA2AbWcEA41Y247iRhD9FeSXZSTG-G480rxkpSiR8pREykOIUAMNODG2Y_dcyGr_PXW67LHdbbTLagXu03U7dapA88U5VEfpPDn5ta4atahFKYuFaBd1uS37s6oQTasPiy0d16Ur35Us27wql1vnVZ7F1nnQiFCXxfNi61yUqtun9fqct8o95-rysn9pZXOoSrJT7qG6rkup_l5vNmESeP66EW_r5JSFXiKOgR9mGymi8LAX0Sk9xmGa-NnRkx59FjJc503euof2detsy-OJ4tWF20hx3NHZEinoXI7yRECldqJQIm-WD0_bckGvrig-RVH0iZFGqpemXCz5CS-C3M8X0ajl8eSqakfsHEW7fHhwr6L5Z1dXeamWqqoKldfPvzcv8sGVJQgd-cDr_XnrtLIWhVvI8qwuW2c1vXD7uPCWH2fwQ1VUDe7U8pDLdoJTtfqdXm7dVLVsFF1ZakfPseeNcWrAKT-_NHLXHkQhl__Jpnr-URSt7G7R24i6yyveTOr41GVZMNJRRyx1ILlXSjYjHgYO7BKH8mf42Wt0pnCuMIm90ZnKVSHp_s-kEeP6eyH2snj-9BsCLf6A8acRfJvAv-g8epzFXbp6OpYo8IOaB5d0_Sr2ROaDs3Ia-e9L3sgrqbylqdIG22Zb9gNR39yDOMn1-bImWeUncVBrEPnYtPqd3oIw3sRxnNJY8Mmj7_ob13s81GH2KPZ5-Civ7aHJa5qlXbjzd_Fm9ybaaxi4bxeOppPTn0g4r7l8a_GAw-KGT1eh9EO-1-c30TTVG6WvbjWWgU6bHuubulQlDm7VMT_Kx1fPDRLXJ6gQt-pFOU9faP4bbALnKaDyq0r9Sp7ouHPFfg-XvDg2ki79-YEosW-lIlD30XnyqZHONS91Z5ynkJ9-kvn5QnHwmB_J7JQX8gfySrR_pnUi8lI2dyLg6uOe79IVrAY6db7-9XX1cWfIoguUbtwszTIvDZIoyJI0mfdNdoNLUddufXOmbgd4LApXvau7F_vNNk2RKezz8wPf9QLPy4I0JJGEQXQ3QaOwzI1owXpRtgkCLyGzb5PdkfctonuOJ2lbCfiB58ZJFmax56dpFhKzlw7aROn3pEMbhY5F8a18-ntICP--rrQWaCLpTimuuPPBNbkgd9QbOtRLaMdLaMUPWp2rWqoB4AcG-sVEYxS7_ip045XvRiuaE7JXVSuARG5GiDeLpIQEhIQWkhDiExIbSEyeQkJtbzGdhBTLJ68efR4Q9hZ1NuEIYW9AzDgRnQbamxmH6-lz80cIZ5DOett0cZJZpGdn7C2iTBnxDSQmm0gjgeEtpujInDMYczCwA66niE9I37kpO-jPhhAwOkVgAwRxpgjiIAPYTHODTc_OOAPuD3rqzdqEnbd4hAyMZpYNegp2TK6HbgMZZxDTPeYAuU1tgMDG1kGvXjMO5waFmMjAjskB4kR3VBUTgjh2BmMljhGuFDa2QmJCUKk9c_DWT9Y4AyiKGTVtuD99PVMEGfRxxgqJ6DSgkzkEcZC1Haf3BkaTCYIMoEToYMzodLLGcQYbsz-sxDmuY_IwqHeKIDfUY9qkGkFfYRet9I8F_WsWaEInjKKu2EK5t-iKjaKL4JC3QGigiUaxI9BN2zbtUO7OFE3oBNVwzomBIptA5416PQNN6D52Jsc1PUPhAXnlLWSyARYD-s9dNj3HZINe8hyYFSWEBJpJsGHa0k82QpHVXBfiLmdWvplzovNFF3gDTFHYclZzHcSWRr081XZWYONe9zkrTCq48i0U-cIWGt4YKNfbf0PYFYXa87yuBltwFVgofyfim2nOc8_GHFcJeWXPyNlGwbO3ggqw600U_UXcea6gZ8QGavLMkwLFIq7NZI-iXtuWO8hdsNlAVinljP6ak8Kb_p42YIu9yahpO6gOWdm26CAmFDybXRg0iaxsFPWi-3PaYDTpPNv1YmvCMybF7CBzBVt4Nm15unmzzPEMtWNSePebKGuDUdszug9tzNnylN1TLDrHU4acbW30e3KOyX5PsgqoR3lzzsv80H0lsHBYGtkUTOkQETHFAX2egNzcjECQTKM9BTlXdk9MjMGULADyEjbc8t5G36E3mq8xmHYxEXsmJliIdUwLTCkJLE5eGwYJnG1AlgCp51MQqwQMIabBEHYF1wk9GqVwW5AQiDfcMjMbAhGTNDoG-y9cxIQYDbDnFgxZdUKCG6oTsS3icQgSwLHlFlkiJiRmMcR7nEsyLHkoID-4NerkmH1CBsgawjhhbRmlwAK65ZgGt9zPgNwiW8sSs9RvcAvsl8NsTDQbXZmRJsdkUetVOAXZEu4tmaR0wF3BJYuEcUyjZcwQy2SmK9BOoi31nhuDrARPJ2S1DG6x1TmmYYmEsNRnBQbCmb5ZblEnLFGSQR_3E-BszN5yJluelTtLikcQ0pwV9VhDFn3MEP_csyxBPA_vTMx-BGFp9RMyAbcgwXDLP4hgiVIM-vB3kP8BmNFHUOoXAAA)

**Comment by MarcSkovMadsen** [comment]
If I stay with Matplotlib I can get some data visualization

![image](https://github.com/user-attachments/assets/53f0de4e-401d-44f2-abe5-3e1a59f1af4a)

[Reproduce on PY.CAFE](https://py.cafe/snippet/panel/v1?#c=H4sIAN-FbWcEA41YXY_aRhT9K9R9CCuxxh_YhpX2pVHaRorUKEnVhxChAQZwa2zXnv2gUf5775lrr-0Zo4QoAs-Z-3XuuReSr86u2EvnzknPZVGpSSlymU1EPSnzdd6eFZmoan2Yrem4zF35rGRep0U-XTuP8ijWzo1GhDpN7idr56RUWd_N58e0Vu4xVaeH7UMtq12Rk51yd8V5nkv193y5DOPA8-eVeJrHh1XoxWIf-OFqKcUi3G3F4pDsozCJ_dXekx59FjKcp1Vau7v6ce2s8_2B4pWZW0mx39DZFCnoXPbyQEChNiJTIq2mN3frfEKvpig-RVH0iZFKqocqn0z5CS-C3NcnUanp_uCqYkPs7EU9vblxz6L6Z1MWaa6mqigylZb3n6oHeePKHIT2fOD1fL92almKzM1kflSntTMbXri8XHhK9yP4rsiKiu48iiqV6jLAqVr9Ti-3rIpSViqV9VQ7uo88r49TAw7p8aGSm3onMjn9T1bF_a8iq2Vzi9561J0e8WZSx6cuy4KRhjpiqQHJvVKy6vHQcWCX2JU_ws8W6FjhXGEceb0zlapM0v23pBFZD64_Z2Irs_tXHxFo8heMX_XgywB-p_No8SErZ6HwnqVbk5kOccsLPvHQkL74GnE_m4hnLVni6GGLO6QnRsXzKG37w-eWnYa5L_20-3jLXv_Cji-8EPjF3YlaTWlmXgslj0WVkhJutLpPlxoP05uubLwhL6k2mtrpK2b21RBjbqcDboc3mN72RkNvcwVk7LKillMi6Gby8-T1uz8-vpl8-v3N5Ne3v_354c1PfK9RGV0CobSG9LaiFfTz5D3vqDSfvL8U-3QvaSNR3OpRbClpivNye3-4AqAXg9727zkzp5L_PqSVPNMCq2lhaqN1tc7bXVdeiNmDnB9Pc9oY6UHs1BwzclvV-p3egjBaRlGU0Mbjk1vf9Zeud7srw9Wt2KbhrTzXuyotaU1uwo2_iZabJ1Gfw8B9OuloXYKUkrqU2N06FXosL-pU5DhgDm4fPTeIXZ-gTFyKB-XcfaV1XWFxO3cBlVQU6kPxhOPGVUVPM2d3SrN9JenS5xdEiS31kUAtQufOp7lzzmmum-3chfz0u0yPJ4qDx3RPZoc0k7-QV6LyNW1_keayuhIBV2-3fJeuYJPTqfPty7fZy50uiyZQsnRXyWrlJUG8CFZxEo_7JrvOpShLmk9n6LaD-4121bO6erH9IhqmyBS2-fmB73qB562CJKTGh8HiaoLDwvw4cIMkiZael_h-sgiXP0J3Q9_3qG5ZHiRupRAmbhIEC3-1CpbLIIpJMacGCuLoR9KhXUbHIvtePu09JIQ_32ZaDTRndCcXZ9x5YZtckDvqDh3qvbfhvTfjB63PWSlVB_ADA3Upd_T9iFmKXH8WutHMdxczmhSyV0UtgCzcFSHeKJIQEhASWkhMiE9IZCAReQoJtb1FdBJSLJ-8evS5Q9jborEJewh7A2LGWdBpoL2ZcbieNje_h3AGyai3ZRMnHkVadvreFpQpI76BRGSz0EhgeIsoOjLnDPocdOyA6yHiE9J2bsgO-rMkBIwOEdgAQZwhgjjIADbD3GDTstPPgPuDnnqjNmHjLeohHaMrywY9BTsm1123gfQziOgec4DchjZAYGProFWvGYdzg0JMpGPH5ABxFldUFRGCOHYGfSX2Ea4UNrZCIkJQqT1z8NZOVj8DKIoZNW24P209QwQZtHH6ClnQaUAnYwjiIGs7TusNjMYDBBlAidBBn9HhZPXjdDZmf1iJY1xH5KFT7xBBbqjHtEk0gr7CbjHTPxf0Pz-AxnTCKOqKLJR7i67YKLoIDnkLhAYaaxQ7At20bZMG5e4M0ZhOUA3nHBsosgl03qjXM9CY7mNnclzTMxQekFfeQiYbYDGgv9xl03NENuglz4FZUUwIfcETCjZMW_rRRiiyGutC1OTMyjdzjnW-6AJvgCEKW85qrIPY0qiXp9rOCmxc6z5nhUkFV76FIl_YQsNLA-V6228Iu6JQex7XVWcLrgIL5e9EfDONeW7ZGOMqJq_sGTnbKHj2ZlABdr2Jor-IO84V9IzYQE2eeVKgWMS1mWxR1Gvbcge5CzYbyCqhnNFfc1J401_TBmyxNxk1bTvVISvbFh3EhIJnswudJpGVjaJedH9MG4zGjWe7XmxNeMakmB1krmALz6YtTzdvljGeoXZMCu9-E2VtMGp7RvehjTFbnrJrikXneMqQs62Ndk-OMdnuSVYB9SitjmlO_-RnUxYOS2M1BBM6RERMcUCfByA3d0UgSKbRHoKcK7snJvpgQhYAeQkbbnlvo-_QG81XH0yamIg9EhMsRDqmBSaUBBYnrw2DBM42IEuA1PMhiFUChhDTYAi7guuEHo1SuC1ICMQbbpmZJYGISRrtg-0XLmJCjAbYcguGrDohwSXVidgW8TgECeDYcossERMSsxjiPc4lGZY8FJAf3Bp1csw2IQNkDWGcsLaMUmAB3XJMg1vuZ0Buka1liVlqN7gFtsthNCaaja6MSJNjsqj1KhyCbAn3lkwSOuCu4JJFQj-m0TJmiGUy0hVoJ9aWes_1QVaCpxOyWga32Ooc07BEQljqowID4UzfKLeoE5YoyaCP-wlwNGZrOZItz8qVJcUjCGmOirqvIYs-Zoh_7lmWIJ6HdyRmO4KwtPoJmYBbkGC45R9EsEQpBn34f5D_AXHRPHabGQAA)

**Comment by MarcSkovMadsen** [comment]
Ok. I've learned in https://github.com/apache/arrow/issues/34996#issuecomment-2562936085 that pyarrow will be available when Pyodide 0.27.0 is released.
