### ISSUE TITLE
PanicException creating an `Array` of `Decimal`

### ISSUE THREAD

**Issue by cmdlineluser** [pola-rs/polars#20464]
### Checks

- [X] I have checked that this issue has not already been reported.
- [X] I have confirmed this bug exists on the [latest version](https://pypi.org/project/polars/) of Polars.

### Reproducible example

```python
import polars as pl

# panic only happens after "printing"
print(
    pl.select(
        pl.lit([1], dtype=pl.Array(pl.Decimal(scale=20), shape=1))
    )
)
```

### Log output

```shell
thread '<unnamed>' panicked at crates/polars-arrow/src/legacy/array/fixed_size_list.rs:89:12:
called `Result::unwrap()` on an `Err` value: ComputeError(ErrString("FixedSizeListArray's child's DataType must match. However, the expected DataType is Decimal(38, 20) while it got Int128."))
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
Traceback (most recent call last):
  File "/Users/user/repro.py", line 3, in <module>
    print(
  File "/usr/local/lib/python3.13/site-packages/polars/dataframe/frame.py", line 1201, in __str__
    return self._df.as_str()
pyo3_runtime.PanicException: called `Result::unwrap()` on an `Err` value: ComputeError(ErrString("FixedSizeListArray's child's DataType must match. However, the expected DataType is Decimal(38, 20) while it got Int128."))
```

### Issue description

In 1.17.1 it produces

```
shape: (1, 1)
┌──────────────────────────┐
│ literal                  │
│ ---                      │
│ array[decimal[*,20], 1]  │
╞══════════════════════════╡
│ [1.00000000000000000000] │
└──────────────────────────┘
```

### Expected behavior

No panic.

### Installed versions

<details>

```
--------Version info---------
Polars:              1.18.0
Index type:          UInt32
Platform:            macOS-13.6.1-arm64-arm-64bit-Mach-O
Python:              3.13.0 (main, Oct  7 2024, 05:02:14) [Clang 15.0.0 (clang-1500.1.0.2.5)]
LTS CPU:             False

----Optional dependencies----
adbc_driver_manager  <not installed>
altair               <not installed>
boto3                <not installed>
cloudpickle          <not installed>
connectorx           <not installed>
deltalake            <not installed>
fastexcel            0.12.0
fsspec               <not installed>
gevent               <not installed>
google.auth          <not installed>
great_tables         0.14.0
matplotlib           <not installed>
nest_asyncio         <not installed>
numpy                2.1.3
openpyxl             3.1.5
pandas               2.2.3
pyarrow              18.0.0
pydantic             <not installed>
pyiceberg            <not installed>
sqlalchemy           <not installed>
torch                <not installed>
xlsx2csv             <not installed>
xlsxwriter           3.2.0
```

</details>

**Comment by sugibuchi** [comment]
Any update? This problem still persists.

**Comment by freud14-tm** [comment]
Getting similar error when using eval on a decimal list:

```python
import polars as pl

print(
   pl.select(
       pl.lit([1], dtype=pl.List(pl.Decimal(scale=20)))
   ).select(
       b=pl.col("literal").list.eval(pl.element())
   )
)
```

**Comment by cmdlineluser** [comment]
@freud14-tm You can create a new issue for that. 

(It's a much higher priority problem than this.)

**Comment by freud14-tm** [comment]
@cmdlineluser Not sure why my issue would be a higher priority but here we go: https://github.com/pola-rs/polars/issues/23896

**Comment by cmdlineluser** [comment]
@freud14-tm Your code worked on 1.29.0 so it's a recent regression. (and `Array` usage is still relatively uncommon compared to `List`)
