### ISSUE TITLE
Panic crash in Polars 1.18.0 SchemaMismatch

### ISSUE THREAD

**Issue by coby-astsec** [pola-rs/polars#20478]
### Checks

- [X] I have checked that this issue has not already been reported.
- [X] I have confirmed this bug exists on the [latest version](https://pypi.org/project/polars/) of Polars.

### Reproducible example

```python
import polars as pl

def get_num(expr: pl.Expr, index: int) -> pl.Expr:
    #                                                               Removing this "*" causes this to work
    return expr.str.split(".").list.get(index).cast(pl.Int64, strict=False) * pl.lit(2, pl.Int64)


def get_version(pcol: pl.Expr) -> pl.Expr:
    return pl.concat_list([
        # Removing one of these (to only return a single object) works
        # Changing the first to pl.lit(1) works, changing the second one instead does not
        get_num(pcol, 0),
        get_num(pcol, 1)
    ])


# Doesn't matter what is in here
df = pl.DataFrame({"v": [[]]})

# This works!!!
df = df.with_columns(
    get_version(pl.lit("1.1")).alias("B")
)
print(df)

# This does not :(
df = df.with_columns(
    pl.col("v").list.eval(get_version(pl.lit("1.1"))).alias("C")
)
print(df)
```

```
❯ python test.py        
shape: (1, 2)
┌────────────┬───────────┐
│ v          ┆ B         │
│ ---        ┆ ---       │
│ list[null] ┆ list[i64] │
╞════════════╪═══════════╡
│ []         ┆ [2, 2]    │
└────────────┴───────────┘
thread '<unnamed>' panicked at crates/polars-expr/src/expressions/mod.rs:257:14:
impl error, should be a list at this point: SchemaMismatch(ErrString("invalid series dtype: expected `List`, got `i64` for series with name `literal`"))
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
Traceback (most recent call last):
  File "/path/to/test.py", line 28, in <module>
    df = df.with_columns(
        pl.col("v").list.eval(get_version(pl.lit("1.1"))).alias("C")
    )
  File "/path/to/.venv/lib/python3.13/site-packages/polars/dataframe/frame.py", line 9495, in with_columns
    return self.lazy().with_columns(*exprs, **named_exprs).collect(_eager=True)
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^
  File "/path/to/.venv/lib/python3.13/site-packages/polars/lazyframe/frame.py", line 2043, in collect
    return wrap_df(ldf.collect(callback))
                   ~~~~~~~~~~~^^^^^^^^^^
pyo3_runtime.PanicException: impl error, should be a list at this point: SchemaMismatch(ErrString("invalid series dtype: expected `List`, got `i64` for series with name `literal`"))
```

### Log output

```shell
thread '<unnamed>' panicked at crates/polars-expr/src/expressions/mod.rs:257:14:
impl error, should be a list at this point: SchemaMismatch(ErrString("invalid series dtype: expected `List`, got `i64` for series with name `literal`"))
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
Traceback (most recent call last):
  File "/path/to/test.py", line 28, in <module>
    df = df.with_columns(
        pl.col("v").list.eval(get_version(pl.lit("1.1"))).alias("C")
    )
  File "/path/to/.venv/lib/python3.13/site-packages/polars/dataframe/frame.py", line 9495, in with_columns
    return self.lazy().with_columns(*exprs, **named_exprs).collect(_eager=True)
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^
  File "/path/to/.venv/lib/python3.13/site-packages/polars/lazyframe/frame.py", line 2043, in collect
    return wrap_df(ldf.collect(callback))
                   ~~~~~~~~~~~^^^^^^^^^^
pyo3_runtime.PanicException: impl error, should be a list at this point: SchemaMismatch(ErrString("invalid series dtype: expected `List`, got `i64` for series with name `literal`"))
```

### Issue description

I have included comments in the code where slightly changing thing causes them to start working.
This crash only happens in the context of `pl.element()`.
In the original code (I played around a bunch until I got to this reproducible example) the issue was upon running a query on `pl.element()`. I noticed the error happens even when `pl.element()` is not involved, so I made the example without it.

My actual goal is to compute a boolean expression on `pl.element()` and then use `.list.any()`

### Expected behavior

No crash.
```
shape: (1, 3)
┌────────────┬───────────┬───────────┐
│ v          ┆ B         ┆ C         │
│ ---        ┆ ---       ┆ ---       │
│ list[null] ┆ list[i64] ┆ list[i64] │
╞════════════╪═══════════╪═══════════╡
│ []         ┆ [2, 2]    ┆ [2, 2]    │
└────────────┴───────────┴───────────┘
```

### Installed versions

<details>

```
❯ python test.py
--------Version info---------
Polars:              1.18.0
Index type:          UInt32
Platform:            macOS-15.2-arm64-arm-64bit-Mach-O
Python:              3.13.0 (main, Oct  7 2024, 23:47:22) [Clang 18.1.8 ]
LTS CPU:             False

----Optional dependencies----
adbc_driver_manager  <not installed>
altair               <not installed>
azure.identity       <not installed>
boto3                <not installed>
cloudpickle          <not installed>
connectorx           <not installed>
deltalake            <not installed>
fastexcel            <not installed>
fsspec               <not installed>
gevent               <not installed>
google.auth          <not installed>
great_tables         <not installed>
matplotlib           <not installed>
nest_asyncio         <not installed>
numpy                <not installed>
openpyxl             <not installed>
pandas               <not installed>
pyarrow              <not installed>
pydantic             <not installed>
pyiceberg            <not installed>
sqlalchemy           <not installed>
torch                <not installed>
xlsx2csv             <not installed>
xlsxwriter           <not installed>
```

</details>

**Comment by cmdlineluser** [comment]
Attempted minimal repro:

```python
pl.Series([[]]).list.eval(pl.concat_list(pl.lit([1]).list.get(0) * 1, 2))

# thread '<unnamed>' panicked at crates/polars-expr/src/expressions/mod.rs:257:14:
# impl error, should be a list at this point: SchemaMismatch(ErrString("invalid series dtype: expected `List`, got `i64` for series with name `literal`"))
```

Without the multiplication:

```python
pl.Series([[]]).list.eval(pl.concat_list(pl.lit([1]).list.get(0), 2))

# shape: (1,)
# Series: '' [list[i64]]
# [
# 	[1, 2]
# ]
```

**Comment by coby-astsec** [comment]
Hey, any chance this will get looked at soon?

If not, I'd be happy to attempt to investigate and fix this, but I'm not sure where to start.

Do you have any pointers on what went wrong here?
I've already compiled the rust code in debug mode and looked at the call stack, but I don't have enough context to understand what is going on.

**Comment by kdn36** [comment]
I can give this one a look. No promises, new to the code base.

**Comment by kdn36** [comment]
I may have a fix, pending feedback from the core team. The issue is similar to #21610 , where `update_groups` is set in `apply_all_literal()` to an incompatible value.

On the original MRE, would this not be the expected outcome?
```
shape: (1, 3)
┌────────────┬───────────┬─────────────────┐
│ v          ┆ B         ┆ C               │
│ ---        ┆ ---       ┆ ---             │
│ list[null] ┆ list[i64] ┆ list[list[i64]] │
╞════════════╪═══════════╪═════════════════╡
│ []         ┆ [2, 2]    ┆ [[2, 2]]        │
└────────────┴───────────┴─────────────────┘
```

For the MRE:
```
shape: (1,)
Series: '' [list[i64]]
[
        [1, 2]
]
```

PR coming, but not before PR https://github.com/pola-rs/polars/pull/22350 has been approved as a similar solution strategy should be applied.

**Comment by kdn36** [comment]
The nested `list[]` originates in `run_on_group_by_engine()`, where any `AggregatedScalar` is repackaged as a list. A simple fix results in the expected behavior above (no panic, basic list), however this breaks 2 test cases involving `pl.element()` returning a `Scalar`.

Original MRE:
```
shape: (1, 3)
┌────────────┬───────────┬───────────┐
│ v          ┆ B         ┆ C         │
│ ---        ┆ ---       ┆ ---       │
│ list[null] ┆ list[i64] ┆ list[i64] │
╞════════════╪═══════════╪═══════════╡
│ []         ┆ [2, 2]    ┆ [2, 2]    │
└────────────┴───────────┴───────────┘
```
and the short MRE (with multiplication):
```
shape: (1,)
Series: '' [list[i64]]
[
        [1, 2]
]
```

Test cases where this condition applies are as follows:
```
FAILED tests/unit/datatypes/test_struct.py::test_struct_arr_eval - AssertionError
FAILED tests/unit/operations/namespaces/list/test_eval.py::test_list_eval_type_coercion - AssertionError
```

There is more than one way to approach a long-term fix, depending on the contract. To close out, input would be welcomed on the return type definition for expressions such as `list.eval(pl.element().foo())`, where `foo()` may be expected to operate on the list/series rather than the individual element, and returns a `Scalar` (for example `first()`.

Imo (newbie), it would be cleaner if `pl.element()` was reserved for element-wise operations, and list-based operations such as `first()` use a more basic syntax.

To the original submitter, @coby-astsec, can you share your original syntax using `pl.element()`?

I will give it a closer look, and then submit a PR for review and input by the core team for resolution.
