### ISSUE TITLE
groupby_dynamic throws panic expection when you use normal groupby key words

### ISSUE THREAD

**Issue by seb2704** [pola-rs/polars#2104]
#### Are you using Python or Rust?

Python.

#### What version of polars are you using?
0.12.2

#### What operating system are you using polars on?
Ubuntu 20.04

#### Describe your bug.

When I use the groupby_dynamic operation with normal groupby key words, a expection is thrown that the time column need to have a time acending order even if i sorted the dataframe by the time column in a acending order before the groupby_dynamic operation

#### What are the steps to reproduce the behavior?

```python
import polars as pl
import datetime

df = pl.DataFrame(
    {"EVENT_DATE": [datetime.datetime(2021,4,11), datetime.datetime(2021,4,29),datetime.datetime(2021,5,29)],
     "adm1_code": [1, 2,1],
     "FIVE_TYPE": ['a', 'b','a'],
     "actor": ['a','a','a'],
     "admin": ['a','a','a'],
     "FATALITIES": [10,20,30],
    })
#sort by time
df = df.sort(by='EVENT_DATE')
(df.groupby_dynamic(
        time_column="EVENT_DATE",
        every="1mo",
        by=['admin', 'FIVE_TYPE','actor']
    ).agg([
        pl.col('adm1_code').unique(),
        (pl.col('FATALITIES')>0).sum()
    ])
    )
```

#### What is the actual behavior?

```
thread '<unnamed>' panicked at 'boundary start must be smaller than stop; is your time column sorted in ascending order?', /github/workspace/polars/polars-time/src/bounds.rs:33:9
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
Traceback (most recent call last):
  File "actor_data.py", line 373, in <module>
    (df.groupby_dynamic(
  File "/home/sebastian/.local/lib/python3.8/site-packages/polars/internals/frame.py", line 3890, in agg
    self.df.lazy()
  File "/home/sebastian/.local/lib/python3.8/site-packages/polars/internals/lazy_frame.py", line 325, in collect
    return pli.wrap_df(ldf.collect())
pyo3_runtime.PanicException: boundary start must be smaller than stop; is your time column sorted in ascending order?
```

#### What is the expected behavior?
a dataframe, grouped by keywords and date

**Comment by ritchie46** [comment]
Thanks a fix is made :point_up:
