### ISSUE TITLE
Extend any and all to unnamed series

### ISSUE THREAD

**Issue by LiterallyUniqueLogin** [pola-rs/polars#2293]
#### Describe your feature request
I'd like to be able to use the `any` and `all` functions on intermediate result, not just named columns.

Let's say we have
```
>>> pl.DataFrame({'first': [True, False], 'second': [False, True]}) ; df
shape: (2, 2)
┌───────┬────────┐
│ first ┆ second │
│ ---   ┆ ---    │
│ bool  ┆ bool   │
╞═══════╪════════╡
│ true  ┆ false  │
├╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌┤
│ false ┆ true   │
└───────┴────────┘
```

Then I can do
```
>>> df.select(pl.any('first'))
shape: (1, 1)
┌───────┐
│ first │
│ ---   │
│ bool  │
╞═══════╡
│ true  │
└───────┘
```
but not 
```
>>> df.select(pl.any(pl.col('first')))
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/jmargoli/miniconda3/envs/ukb/lib/python3.7/site-packages/polars/internals/lazy_functions.py", line 752, in any
    return col(name).sum() > 0
  File "/home/jmargoli/miniconda3/envs/ukb/lib/python3.7/site-packages/polars/internals/lazy_functions.py", line 143, in col
    return pli.wrap_expr(pycol(name))
TypeError: argument 'name': 'Expr' object cannot be converted to 'PyString'
```
For something simple like this it doesn't matter (though it did make me wonder incorrectly if I was using the wrong function), but for more complicated operations, there's no one step method for this. For example, 
```
>>> df.select(pl.any(pl.col('first') | pl.col('second')))
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/jmargoli/miniconda3/envs/ukb/lib/python3.7/site-packages/polars/internals/lazy_functions.py", line 752, in any
    return col(name).sum() > 0
  File "/home/jmargoli/miniconda3/envs/ukb/lib/python3.7/site-packages/polars/internals/lazy_functions.py", line 143, in col
    return pli.wrap_expr(pycol(name))
TypeError: argument 'name': 'Expr' object cannot be converted to 'PyString'
```
instead needs to be
```
>>> df.with_column((pl.col('first') | pl.col('second')).alias('temp')).select(pl.any('temp'))
shape: (1, 1)
┌──────┐
│ temp │
│ ---  │
│ bool │
╞══════╡
│ true │
└──────┘
```

**Comment by ritchie46** [comment]
I will add an `any` and `all` expression.

So syntax will be `col("foo").any()`
