### ISSUE TITLE
Cannot compare str.extract results

### ISSUE THREAD

**Issue by LiterallyUniqueLogin** [pola-rs/polars#2311]
#### Are you using Python or Rust?

Python

#### What version of polars are you using?

0.12.8

#### What operating system are you using polars on?

CentOS Linux release 8.1.1911 (Core)

#### Describe your bug.

Easiest by visuals:

```
>>> df = pl.DataFrame({'foo': ['a', 'b', 'c', 'd']}) ; df
shape: (4, 1)
┌─────┐
│ foo │
│ --- │
│ str │
╞═════╡
│ a   │
├╌╌╌╌╌┤
│ b   │
├╌╌╌╌╌┤
│ c   │
├╌╌╌╌╌┤
│ d   │
└─────┘
>>> df.filter(pl.col('foo') == 'a')
shape: (1, 1)
┌─────┐
│ foo │
│ --- │
│ str │
╞═════╡
│ a   │
└─────┘
>>> df.filter(pl.col('foo').str.extract('^(.)', 1) == 'a')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/jmargoli/miniconda3/envs/ukb/lib/python3.7/site-packages/polars/internals/frame.py", line 1541, in filter
    .collect(no_optimization=True, string_cache=False)
  File "/home/jmargoli/miniconda3/envs/ukb/lib/python3.7/site-packages/polars/internals/lazy_frame.py", line 327, in collect
    return pli.wrap_df(ldf.collect())
RuntimeError: Any(ArrowError(NotYetImplemented("Casting from LargeUtf8 to Boolean not supported")))
```
This is a dummy case, there's no reason to use `extract` here, but being able to compare could be nice in other circumstances.

**Comment by ritchie46** [comment]
Yes.. this seems like a bug.

**Comment by ritchie46** [comment]
Found it, it is a simple dtype bug. You can temporarily circumvent it by explicitly casting the result to a `pl.Utf8` column.

```python
df = pl.DataFrame({'foo': ['a', 'b', 'c', 'd']})
df.filter(pl.col('foo').str.extract('^(.)', 1).cast(str) == 'a')
```
