### ISSUE TITLE
Expr.clip fails on product of two columns

### ISSUE THREAD

**Issue by zundertj** [pola-rs/polars#2365]
#### Are you using Python or Rust?

Python

#### What version of polars are you using?

0.12.10

#### What operating system are you using polars on?

W10

#### Describe your bug.

```python
import polars as pl

df = pl.DataFrame({"a": [1, 2, 3],
                   "b": [4, 5, 6]})
# this works
df.select((pl.col("a") * pl.col("b")).clip(4.5, 5.5))

# this fails
df.select(pl.col("a").clip(1.5, 2.5) * pl.col("b").clip(4.5, 5.5))
```

Error message:
```
thread '<unnamed>' panicked at '`keep_name`, `suffix`, `prefix` should be last expression', D:\a\polars\polars\polars\polars-lazy\src\logical_plan\projection.rs:51:18
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
Traceback (most recent call last):
    print(df.select(pl.col("a").clip(1.5, 2.5) * pl.col("b").clip(4.5, 5.5)))
  File "xxx\projects\polars\py-polars\polars\internals\frame.py", line 3399, in select
    self.lazy().select(exprs).collect(no_optimization=True, string_cache=False)  # type: ignore
  File "xxx\projects\polars\py-polars\polars\internals\lazy_frame.py", line 499, in select
    return wrap_ldf(self._ldf.select(exprs))
pyo3_runtime.PanicException: `keep_name`, `suffix`, `prefix` should be last expression
```

In the implementation, this seems to be due to the usage of `keep_name` in `clip`:

```python
return (
            pli.when(self < min_val_lit)
            .then(min_val_lit)
            .when(self > max_val_lit)
            .then(max_val_lit)
            .otherwise(self)
        ).keep_name()
```
Dropping `.keep_name()`  returns a column named `literal`, but with the correct values. Why does `keep_name` fail here?

**Comment by ritchie46** [comment]
> pyo3_runtime.PanicException: `keep_name`, `suffix`, `prefix` should be last expression

We implemented `keep_name` to be only used as final expression. And now we use it in composite expressions. Seems like we need to implement `clip` properly.

**Comment by zundertj** [comment]
Ok, so that is why it only fails once I combine columns; stand-alone `clip` does work.

**Comment by ritchie46** [comment]
> Ok, so that is why it only fails when I combine columns; stand-alone `clip` does work.

Yep
