### ISSUE TITLE
Failed join

### ISSUE THREAD

**Issue by LiterallyUniqueLogin** [pola-rs/polars#2470]
#### Are you using Python or Rust?

**Python**

#### What version of polars are you using?

0.12.17

#### What operating system are you using polars on?

CentOS Linux release 8.1.1911 (Core)

#### Describe your bug.

Rows aren't joining that should. I.e. on an inner join, some rows are being omitted from the joined data frame that should be there. On a left join, some of the right columns are filled with null values when they shouldn't be.

#### What are the steps to reproduce the behavior?

Not sure how to reproduce. Here are the optimized plans that do/do not produce the problematic behavior:

Successful join:
```
JOIN
        (MEMTABLE: ["strcol1", "floatcol1", "floatcol2", "intcol1"];
        project */5 columns     |       details: None;
        selection: "None"


WITH COLUMN(S) [CAST col(strcol1).str.exact() TO Int64.alias(intcol2), CAST col(strcol1).str.exact().str.len() TO Int64.alias(strcol2), CAST col(strcol1).str.exact().str.len() TO Int64.alias(strcol3), col(strcol1).str.contains().alias(boolcol1), Utf8(a_text).alias(strcol4), CAST 1i32.alias(intcol6) TO Int64, Utf8(another_text).alias(strcol5)])
WITH
        (SELECT 5 COLUMNS: [Utf8(another_text).alias(strcol5), col(intcol6), col(intcol2), col(floatcol3).alias(floatcol4), [(Utf8(a_third_text)) + (CAST col(intcol2) TO Utf8)].alias(strcol1)]
FROM
CSV SCAN fname.tab; PROJECT 3/27 COLUMNS; SELECTION: None)
ON (left: [col(strcol5), col(intcol6), col(strcol1)] right: [col(strcol5), col(intcol6), col(strcol1)])
```

Unsuccessful join:
```
JOIN
        (MEMTABLE: ["strcol1", "floatcol1", "floatcol2", "intcol1"];
        project */5 columns     |       details: None;
        selection: "None"


WITH COLUMN(S) [CAST col(strcol1).str.exact() TO Int64.alias(intcol2), CAST col(strcol1).str.exact().str.len() TO Int64.alias(strcol2), CAST col(strcol1).str.exact().str.len() TO Int64.alias(strcol3), col(strcol1).str.contains().alias(boolcol1), Utf8(a_text).alias(strcol4), CAST 1i32.alias(intcol6) TO Int64, Utf8(another_text).alias(strcol5)])
WITH
        (SELECT 7 COLUMNS: [Utf8(another_text).alias(strcol5), col(intcol6), col(intcol2), col(floatcol3).alias(floatcol4), true.alias(boolcol1), CAST null TO Int64.alias(strcol2), CAST null TO Int64.alias(strcol3)]
FROM
CSV SCAN fname.tab; PROJECT 3/27 COLUMNS; SELECTION: None)
ON (left: [col(strcol5), col(intcol6), col(boolcol1), col(intcol2), col(strcol2), col(strcol3)] right: [col(strcol5), col(intcol6), col(boolcol1), col(intcol2), col(strcol2), col(strcol3)])
```

It seems to have something to do with the extract -> length columns - including those in the join causes it to fail to produce rows (even though the extraction in this instance always produces null and I'm joining it to nulls), while any combination of join columns without them seems to succeed. I tried and wasn't successful in reproducing this with a smaller example.

**Comment by ritchie46** [comment]
Can you share the code and minimal data that produced this?

**Comment by LiterallyUniqueLogin** [comment]
I cannot share the raw data. Would the code be of use without the data?

**Comment by ritchie46** [comment]
Can you not reproduce it on dummy data?

**Comment by LiterallyUniqueLogin** [comment]
No. I tried a number of different ideas but couldn't get it to reoccur.

**Comment by ritchie46** [comment]
Hmm.. Then could you share at leas the code and the schema of the data?

**Comment by LiterallyUniqueLogin** [comment]
Had time to get to this, I've pinpionted a bug (not sure if it's the only one). The aggregated column isn't showing.

```
#!/usr/bin/env python3

import polars as pl

df = pl.scan_csv(
    'repro_tsv_2.tab',
    sep='\t',
).select([
    'join_col',
    'new_col_from_join',
]).groupby(['join_col']).agg([
    pl.col('new_col_from_join').min().alias('new_col_from_join'),
])
print(df.collect())
```

```
shape: (68, 1)
┌──────────┐
│ join_col │
│ ---      │
│ i64      │
╞══════════╡
│ 22105095 │
├╌╌╌╌╌╌╌╌╌╌┤
│ 23241399 │
├╌╌╌╌╌╌╌╌╌╌┤
│ 44137780 │
├╌╌╌╌╌╌╌╌╌╌┤
│ 30783198 │
├╌╌╌╌╌╌╌╌╌╌┤
│ ...      │
├╌╌╌╌╌╌╌╌╌╌┤
│ 19297783 │
├╌╌╌╌╌╌╌╌╌╌┤
│ 15594556 │
├╌╌╌╌╌╌╌╌╌╌┤
│ 76673911 │
├╌╌╌╌╌╌╌╌╌╌┤
│ 83352262 │
└──────────┘
```

[repro_tsv_2.txt](https://github.com/pola-rs/polars/files/7960511/repro_tsv_2.txt)

**Comment by ghuls** [comment]
This happens because you do an unsupported (or one that returns null) operation on a string column (`min()`, `max()`, `sum()`, ...).
If you use `first()`, `last()`, the columns shows up.

@ritchie46 Minimized example

```python
In [28]: df = pl.DataFrame([
    pl.Series("a", ["a1", "a3", "a2"]),
    pl.Series("b", [5, 9, 1])
])

In [29]: df.with_column(pl.col("a").min())
Out[29]: 
shape: (3, 2)
┌──────┬─────┐
│ a    ┆ b   │
│ ---  ┆ --- │
│ str  ┆ i64 │
╞══════╪═════╡
│ null ┆ 5   │
├╌╌╌╌╌╌┼╌╌╌╌╌┤
│ null ┆ 9   │
├╌╌╌╌╌╌┼╌╌╌╌╌┤
│ null ┆ 1   │
└──────┴─────┘

In [30]: df.groupby("b").agg([pl.col("a").min()])
Out[30]: 
shape: (3, 1)
┌─────┐
│ b   │
│ --- │
│ i64 │
╞═════╡
│ 9   │
├╌╌╌╌╌┤
│ 1   │
├╌╌╌╌╌┤
│ 5   │
└─────┘

In [31]: df.groupby("b").agg([pl.col("a").first()])
Out[31]: 
shape: (3, 2)
┌─────┬─────────┐
│ b   ┆ a_first │
│ --- ┆ ---     │
│ i64 ┆ str     │
╞═════╪═════════╡
│ 1   ┆ a2      │
├╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌┤
│ 9   ┆ a3      │
├╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌┤
│ 5   ┆ a1      │
└─────┴─────────┘
```

**Comment by LiterallyUniqueLogin** [comment]
Ah, thank you. When I munged my example file, I swapped the letter e in 1e-10 to some other letter which changed the column dtype. I'll go fix that and find another example.

Nonetheless - can this throw an error or emit a warning? It's unclear why this is happening if its silently ignored.

**Comment by LiterallyUniqueLogin** [comment]
Okay, this code panics when I try printing a DataFrame. As before, ignore the choice of column names - they were relevant to my downstream usecase but not to this example.

```
#!/usr/bin/env python3

import polars as pl

table1 = pl.scan_csv(
    'repro_tsv_1.txt',
    sep='\t',
).select([
    'join_col',
    'new_col_from_join',
    pl.lit(True).alias('table_1_indicator'),
    pl.lit(None).cast(int).alias('other_join_len'),
])

table2 = pl.scan_csv(
    'repro_tsv_2.txt',
    sep='\t',
).select([
    'join_col',
    'new_col_from_join',
    pl.col('other_join_col').str.lengths().cast(int).alias('other_join_len'),
]).groupby(['join_col', 'other_join_len']).agg([
    pl.col('new_col_from_join').min().alias('new_col_from_join'),
]).with_columns([
    pl.lit(False).alias('table_1_indicator')
]).select([ 'join_col', 'new_col_from_join', 'table_1_indicator', 'other_join_len'])

concat_table= pl.concat([table1, table2])
print(concat_table.filter((pl.col('join_col') == 59546483) & pl.col('other_join_len').is_null()).collect())
```                      
```
thread '<unnamed>' panicked at 'The columns lengths in the DataFrame are not equal.', /github/workspace/polars/polars-core/src/fmt.rs:340:9
stack backtrace:
   0:     0x1555537ec472 - <unknown>
   1:     0x155552b0bbbc - <unknown>
   2:     0x1555537c2804 - <unknown>
   3:     0x1555537ed3a0 - <unknown>
   4:     0x1555537ee0f3 - <unknown>
   5:     0x1555537edc86 - <unknown>
   6:     0x1555537edc26 - <unknown>
   7:     0x1555537edbe2 - <unknown>
   8:     0x1555520da220 - <unknown>
   9:     0x15555335df88 - <unknown>
  10:     0x155552b0bbbc - <unknown>
  11:     0x1555527c8ee3 - <unknown>
  12:     0x15555232d236 - <unknown>
  13:     0x555555691463 - _PyMethodDef_RawFastCallKeywords
                               at /home/conda/feedstock_root/build_artifacts/python_1607545693724/work/Objects/call.c:632
  14:     0x555555691463 - _PyMethodDescr_FastCallKeywords
                               at /home/conda/feedstock_root/build_artifacts/python_1607545693724/work/Objects/descrobject.c:288
  15:     0x5555556919bd - call_function
                               at /home/conda/feedstock_root/build_artifacts/python_1607545693724/work/Python/ceval.c:4593
  16:     0x5555557003a4 - _PyEval_EvalFrameDefault
                               at /home/conda/feedstock_root/build_artifacts/python_1607545693724/work/Python/ceval.c:3110
  17:     0x555555644ced - PyEval_EvalFrameEx
                               at /home/conda/feedstock_root/build_artifacts/python_1607545693724/work/Python/ceval.c:547:12
  18:     0x555555644ced - function_code_fastcall
                               at /home/conda/feedstock_root/build_artifacts/python_1607545693724/work/Objects/call.c:283:14
  19:     0x555555644ced - _PyFunction_FastCallDict
                               at /home/conda/feedstock_root/build_artifacts/python_1607545693724/work/Objects/call.c:322:20
  20:     0x5555556b4d32 - _PyObject_FastCallDict
                               at /home/conda/feedstock_root/build_artifacts/python_1607545693724/work/Objects/call.c:98:16
  21:     0x5555556b4d32 - _PyObject_FastCall_Prepend
                               at /home/conda/feedstock_root/build_artifacts/python_1607545693724/work/Objects/call.c:868
  22:     0x5555556b4d32 - call_unbound
                               at /home/conda/feedstock_root/build_artifacts/python_1607545693724/work/Objects/typeobject.c:1503
  23:     0x5555556b4d32 - call_method
                               at /home/conda/feedstock_root/build_artifacts/python_1607545693724/work/Objects/typeobject.c:1535
  24:     0x555555662b34 - PyObject_Str
                               at /home/conda/feedstock_root/build_artifacts/python_1607545693724/work/Objects/object.c:565:12
  25:     0x555555662b34 - PyObject_Str
                               at /home/conda/feedstock_root/build_artifacts/python_1607545693724/work/Objects/object.c:530:1
  26:     0x555555766a99 - PyFile_WriteObject
                               at /home/conda/feedstock_root/build_artifacts/python_1607545693724/work/Objects/fileobject.c:129
  27:     0x555555766d1d - builtin_print
                               at /home/conda/feedstock_root/build_artifacts/python_1607545693724/work/Python/bltinmodule.c:1905
  28:     0x5555556907f0 - _PyMethodDef_RawFastCallKeywords
                               at /home/conda/feedstock_root/build_artifacts/python_1607545693724/work/Objects/call.c:659
  29:     0x5555556919f8 - _PyCFunction_FastCallKeywords
                               at /home/conda/feedstock_root/build_artifacts/python_1607545693724/work/Objects/call.c:732
  30:     0x5555556919f8 - call_function
                               at /home/conda/feedstock_root/build_artifacts/python_1607545693724/work/Python/ceval.c:4568
  31:     0x55555570030d - _PyEval_EvalFrameDefault
                               at /home/conda/feedstock_root/build_artifacts/python_1607545693724/work/Python/ceval.c:3124
  32:     0x555555643932 - PyEval_EvalFrameEx
                               at /home/conda/feedstock_root/build_artifacts/python_1607545693724/work/Python/ceval.c:547:12
  33:     0x555555643932 - _PyEval_EvalCodeWithName
                               at /home/conda/feedstock_root/build_artifacts/python_1607545693724/work/Python/ceval.c:3930:14
  34:     0x555555644b49 - PyEval_EvalCodeEx
                               at /home/conda/feedstock_root/build_artifacts/python_1607545693724/work/Python/ceval.c:3959:12
  35:     0x555555724c2b - PyEval_EvalCode
                               at /home/conda/feedstock_root/build_artifacts/python_1607545693724/work/Python/ceval.c:524:12
  36:     0x5555557913ff - run_mod
                               at /home/conda/feedstock_root/build_artifacts/python_1607545693724/work/Python/pythonrun.c:1035
  37:     0x55555579b9c7 - PyRun_FileExFlags
                               at /home/conda/feedstock_root/build_artifacts/python_1607545693724/work/Python/pythonrun.c:988
  38:     0x55555579bb9c - PyRun_SimpleFileExFlags
                               at /home/conda/feedstock_root/build_artifacts/python_1607545693724/work/Python/pythonrun.c:429
  39:     0x55555579c129 - pymain_run_file
                               at /home/conda/feedstock_root/build_artifacts/python_1607545693724/work/Modules/main.c:456
  40:     0x55555579c129 - pymain_run_filename
                               at /home/conda/feedstock_root/build_artifacts/python_1607545693724/work/Modules/main.c:1646
  41:     0x55555579c129 - pymain_run_python
                               at /home/conda/feedstock_root/build_artifacts/python_1607545693724/work/Modules/main.c:2907
  42:     0x55555579c129 - pymain_main
                               at /home/conda/feedstock_root/build_artifacts/python_1607545693724/work/Modules/main.c:3068
  43:     0x55555579c27c - _Py_UnixMain
                               at /home/conda/feedstock_root/build_artifacts/python_1607545693724/work/Modules/main.c:3103
  44:     0x1555543d8873 - __libc_start_main
  45:     0x555555710c99 - <unknown>
Traceback (most recent call last):
  File "./simpler_repro.py", line 29, in <module>
    print(concat_table.filter((pl.col('join_col') == 59546483) & pl.col('other_join_len').is_null()).collect())
  File "/home/miniconda3/envs/ukb/lib/python3.7/site-packages/polars/internals/frame.py", line 1214, in __str__
    return self._df.as_str()
pyo3_runtime.PanicException: The columns lengths in the DataFrame are not equal.
```
[repro_tsv_1.txt](https://github.com/pola-rs/polars/files/7962388/repro_tsv_1.txt)
[repro_tsv_2.txt](https://github.com/pola-rs/polars/files/7962390/repro_tsv_2.txt)
