### ISSUE TITLE
merge categoricals has oob index access

### ISSUE THREAD

**Issue by ritchie46** [pola-rs/polars#2475]
See: https://github.com/pola-rs/polars/actions/runs/1755320314

```
---- tests::arity::test_when_then_otherwise_categorical stdout ----
thread 'tests::arity::test_when_then_otherwise_categorical' panicked at 'called `Option::unwrap()` on a `None` value', polars/polars-core/src/chunked_array/categorical/builder.rs:64:42
stack backtrace:
   0: rust_begin_unwind
             at /rustc/5e57faa78aa7661c6000204591558f6665f11abc/library/std/src/panicking.rs:577:5
   1: core::panicking::panic_fmt
             at /rustc/5e57faa78aa7661c6000204591558f6665f11abc/library/core/src/panicking.rs:110:14
   2: core::panicking::panic
             at /rustc/5e57faa78aa7661c6000204591558f6665f11abc/library/core/src/panicking.rs:48:5
   3: core::option::Option<T>::unwrap
             at /rustc/5e57faa78aa7661c6000204591558f6665f11abc/library/core/src/option.rs:752:21
   4: polars_core::chunked_array::categorical::builder::RevMapping::get
             at /home/ritchie46/code/polars/polars/polars-core/src/chunked_array/categorical/builder.rs:64:28
   5: polars_core::fmt::<impl core::fmt::Display for polars_core::datatypes::AnyValue>::fmt
             at /home/ritchie46/code/polars/polars/polars-core/src/fmt.rs:667:25
   6: core::fmt::write
             at /rustc/5e57faa78aa7661c6000204591558f6665f11abc/library/core/src/fmt/mod.rs:1168:17
   7: core::fmt::Formatter::write_fmt
             at /rustc/5e57faa78aa7661c6000204591558f6665f11abc/library/core/src/fmt/mod.rs:1622:9
   8: polars_core::fmt::<impl core::fmt::Debug for polars_core::series::Series>::fmt::{{closure}}
             at /home/ritchie46/code/polars/polars/polars-core/src/fmt.rs:50:17
   9: polars_core::fmt::<impl core::fmt::Debug for polars_core::series::Series>::fmt
             at /home/ritchie46/code/polars/polars/polars-core/src/fmt.rs:281:38
  10: polars_core::fmt::<impl core::fmt::Display for polars_core::series::Series>::fmt
             at /home/ritchie46/code/polars/polars/polars-core/src/fmt.rs:296:9
  11: <&T as core::fmt::Display>::fmt
             at /rustc/5e57faa78aa7661c6000204591558f6665f11abc/library/core/src/fmt/mod.rs:2106:62
  12: core::fmt::write
             at /rustc/5e57faa78aa7661c6000204591558f6665f11abc/library/core/src/fmt/mod.rs:1168:17
  13: core::fmt::Write::write_fmt
             at /rustc/5e57faa78aa7661c6000204591558f6665f11abc/library/core/src/fmt/mod.rs:186:9
  14: alloc::fmt::format
             at /rustc/5e57faa78aa7661c6000204591558f6665f11abc/library/alloc/src/fmt.rs:597:5
  15: polars_lazy::tests::arity::test_when_then_otherwise_categorical
             at ./src/tests/arity.rs:54:13
  16: polars_lazy::tests::arity::test_when_then_otherwise_categorical::{{closure}}
             at ./src/tests/arity.rs:39:1
  17: core::ops::function::FnOnce::call_once
             at /rustc/5e57faa78aa7661c6000204591558f6665f11abc/library/core/src/ops/function.rs:227:5
  18: core::ops::function::FnOnce::call_once
             at /rustc/5e57faa78aa7661c6000204591558f6665f11abc/library/core/src/ops/function.rs:227:5

```

**Comment by ritchie46** [comment]
Fixed earlier
