### ISSUE TITLE
Most numpy numeric types can't be used in expressions

### ISSUE THREAD

**Issue by qiemem** [pola-rs/polars#2513]
#### Are you using Python or Rust?

Python

#### What version of polars are you using?

0.12.19

#### What operating system are you using polars on?

Fedora Linux 35

#### Describe your bug.

If you use a numpy numeric type directly (not in an array) in an expression, you get:

```
thread '<unnamed>' panicked at 'could not convert value 0.0 as a Literal', src/lazy/dsl.rs:1448:9
```

This happens for every numeric type I tried except for `np.float64`. Numeric arrays perform as expected in expressions.

#### What are the steps to reproduce the behavior?

```python
pl.DataFrame({"x": range(10)}).select(pl.col("x") * np.float32(0))
pl.DataFrame({"x": range(10)}).filter(pl.col("x") == np.float32(0))
```

#### What is the actual behavior?

```
thread '<unnamed>' panicked at 'could not convert value 0.0 as a Literal', src/lazy/dsl.rs:1448:9
---------------------------------------------------------------------------
PanicException                            Traceback (most recent call last)
/home/bryan/Development/Models/WSP efficiency/vaextest.ipynb Cell 12' in <module>
----> 1 pl.DataFrame({"x": range(10)}).select(pl.col("x") * np.float32(0))
      2 pl.DataFrame({"x": range(10)}).filter(pl.col("x") == np.float32(0))

File ~/mambaforge/lib/python3.9/site-packages/polars/internals/expr.py:104, in Expr.__mul__(self, other)
    103 def __mul__(self, other: Any) -> "Expr":
--> 104     return wrap_expr(self._pyexpr * self.__to_pyexpr(other))

File ~/mambaforge/lib/python3.9/site-packages/polars/internals/expr.py:57, in Expr.__to_pyexpr(self, other)
     56 def __to_pyexpr(self, other: Any) -> "PyExpr":
---> 57     return self.__to_expr(other)._pyexpr

File ~/mambaforge/lib/python3.9/site-packages/polars/internals/expr.py:62, in Expr.__to_expr(self, other)
     60 if isinstance(other, Expr):
     61     return other
---> 62 return pli.lit(other)

File ~/mambaforge/lib/python3.9/site-packages/polars/internals/lazy_functions.py:564, in lit(value, dtype)
    562 if dtype:
    563     return pli.wrap_expr(pylit(value)).cast(dtype)
--> 564 return pli.wrap_expr(pylit(value))

PanicException: could not convert value 0.0 as a Literal
```

#### What is the expected behavior?

No error. The first expression should produce a dataframe with a column `x` with ten `0`s. The second, the same but with a single 0.

**Comment by qiemem** [comment]
Oh, if anyone else runs into this, the workaround is, of course, to wrap the number in `int` or `float` as appropriate.
