### ISSUE TITLE
Unescaped " produce invalid json

### ISSUE THREAD

**Issue by SimonSchneider** [pola-rs/polars#2548]
#### Are you using Python or Rust?

Rust

#### Which feature gates did you use?

"lazy", "is_in", "parquet", "json", "strings", "sort_multiple", "round_series"

#### What version of polars are you using?

0.19.1

#### What operating system are you using polars on?

macOs Monterey 12.1

#### Describe your bug.

When json encoding a DataFrame with `utf8` columns containing cells with `"` in them it does not escape these and therefore produces invalid json.

#### What are the steps to reproduce the behavior?

```
#[cfg(test)]
mod tests {
    use polars::prelude::*;
    use serde_json::Value;

    #[test]
    fn failing_test_with_non_ok_json() {
        let df = df! {
            "description" => ["2\" steel"]
        }
        .unwrap();
        let mut buf = Vec::new();
        JsonWriter::new(&mut buf)
            .with_json_format(JsonFormat::Json)
            .finish(&df)
            .unwrap();
        let res = String::from_utf8(buf).unwrap();
        let v: Value = serde_json::from_str(&res).unwrap();
        match v {
            Value::Array(arr) => {
                assert_eq!(arr.len(), 1);
                match &arr[0] {
                    Value::Object(entry) => {
                        assert_eq!(entry.len(), 1);
                        let val = entry.get("description").unwrap();
                        assert_eq!(val, "2\" steel")
                    }
                    _ => panic!("should be an object"),
                }
            }
            _ => panic!("data should be an array"),
        }
    }
}
```

#### What is the actual behavior?

Above test case shows the issue. It panics on `let v: Value = serde_json::from_str(&res).unwrap();` with:
```
called `Result::unwrap()` on an `Err` value: Error("expected `,` or `}`", line: 1, column: 21)
thread 'df_encoding::tests::failing_test_with_non_ok_json' panicked at 'called `Result::unwrap()` on an `Err` value: Error("expected `,` or `}`", line: 1, column: 21)', src/df_encoding.rs:86:51
stack backtrace:
   0: rust_begin_unwind
             at /rustc/db9d1b20bba1968c1ec1fc49616d4742c1725b4b/library/std/src/panicking.rs:498:5
   1: core::panicking::panic_fmt
             at /rustc/db9d1b20bba1968c1ec1fc49616d4742c1725b4b/library/core/src/panicking.rs:107:14
   2: core::result::unwrap_failed
             at /rustc/db9d1b20bba1968c1ec1fc49616d4742c1725b4b/library/core/src/result.rs:1613:5
   3: core::result::Result<T,E>::unwrap
             at /rustc/db9d1b20bba1968c1ec1fc49616d4742c1725b4b/library/core/src/result.rs:1295:23
   4: dsr_engine::df_encoding::tests::failing_test_with_non_ok_json
             at ./src/df_encoding.rs:86:24
   5: dsr_engine::df_encoding::tests::failing_test_with_non_ok_json::{{closure}}
             at ./src/df_encoding.rs:75:5
   6: core::ops::function::FnOnce::call_once
             at /rustc/db9d1b20bba1968c1ec1fc49616d4742c1725b4b/library/core/src/ops/function.rs:227:5
   7: core::ops::function::FnOnce::call_once
             at /rustc/db9d1b20bba1968c1ec1fc49616d4742c1725b4b/library/core/src/ops/function.rs:227:5
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```

#### What is the expected behavior?

Any `"` inside a `uft8` cell should be escaped when encoding it to JSON.

What do you think polars should have done?

Expected Behavior.

**Comment by SimonSchneider** [comment]
I'm a little on the edge on this myself honestly. One could argue that the escaping should be done during data cleaning, not by polars. On the other hand, unescaped `"` are valid in other encodings (I think?) and therefore it should be up to the json encoder to take care of this.
Perhaps adding an optional flag to the JSON writer would be an ok option as I'm guessing this would have some performance overhead.

**Comment by ritchie46** [comment]
I am a bit surprised that serde json does not escape these itself as well. So any rust struct holding a atring with quotations would fail?

**Comment by SimonSchneider** [comment]
Actually just rewrote the test to do the same with `serde_json` and compare the produced strings:
```
#[cfg(test)]
mod tests {
    use polars::prelude::*;
    use std::collections::HashMap;

    #[test]
    fn failing_test_with_non_ok_json() {
        let df = df! {
            "description" => ["2\" steel"]
        }
        .unwrap();
        let mut buf = Vec::new();
        JsonWriter::new(&mut buf)
            .with_json_format(JsonFormat::Json)
            .finish(&df)
            .unwrap();
        let encoded_by_polars_json_writer = String::from_utf8(buf).unwrap();
        let mut entr = HashMap::new();
        entr.insert("description", "2\" steel");
        let json_enc = vec![entr];
        let encoded_by_serde_json = serde_json::to_string(&json_enc).unwrap();
        assert_eq!(encoded_by_polars_json_writer, encoded_by_serde_json);
    }
}
```
produces:
```
Left:  [{"description":"2" steel"}]
Right: [{"description":"2\" steel"}]
<Click to see difference>
```
So `serde_json::to_string` does indeed escape the `"` correctly.

**Comment by SimonSchneider** [comment]
digging a little I think the issue is here https://github.com/jorgecarleitao/arrow2/blob/9a8edd06a59d01023ec5a9f7ad1775f7e6c1969c/src/io/json/write/serialize.rs#L141:
```rust
#[inline]
fn utf8_serialize(value: &str, buf: &mut Vec<u8>) {
    if value.as_bytes().is_ascii() {
        buf.reserve(value.len() + 2);
        buf.push(b'"');
        buf.extend_from_slice(value.as_bytes());
        buf.push(b'"');
    } else {
        // it may contain reserved keywords: perform roundtrip for
        // todo: avoid this roundtrip over serde_json
        serde_json::to_writer(buf, &Value::String(value.to_string())).unwrap();
    }
}
```
as `"` is ascii which means it'll not run the normal `serde_json` but rather copy the value as bytes directly.
```
    #[test]
    fn test_2() {
        let tes = "\"".as_bytes().is_ascii();
        assert_eq!(tes, true);
    }
```

**Comment by ritchie46** [comment]
Good catch! Can you make an issue upstream? I can take it up there.

**Comment by SimonSchneider** [comment]
Sure thing, here it is: https://github.com/jorgecarleitao/arrow2/issues/811

Thank you for a really nice project and fast response on this.

**Comment by arlyon** [comment]
I am also experiencing similar issues with newlines as well.

**Comment by SimonSchneider** [comment]
> I am also experiencing similar issues with newlines as well.

If you are using Rust then the fix to this issue has not yet been released and you'll have to use a master build instead of the latest 0.19.1 version.
