### ISSUE TITLE
Reading parquet file with nan values fails using arrow2

### ISSUE THREAD

**Issue by LdRoW** [pola-rs/polars#2646]
#### Are you using Python or Rust?

Python

#### Which feature gates did you use?

This can be ignored by Python users.

#### What version of polars are you using?

0.13.1

#### What operating system are you using polars on?

Ubuntu 20.04.3. Python 3.9.5

#### Describe your bug.

pl.read_parquet throws PanicException using arrow2 parquet reader. Target parquet file was created with pyarrow (6.0.1).

#### What are the steps to reproduce the behavior?

```python
import pandas as pd
import polars as pl
import numpy as np
# Create pandas dataframe
pd_df = pd.DataFrame([[np.nan]], columns=['a'])
pd_df.to_parquet('/tmp/test.parquet',engine='pyarrow')

# Try to read the parquet file
pl_df = pl.read_parquet('/tmp/test.parquet')
```

#### What is the actual behavior?

Reading parquet file crashes with:
```
thread '<unnamed>' panicked at 'assertion failed: `(left == right)`
  left: `0`,
 right: `1`', /github/home/.cargo/git/checkouts/arrow2-8a2ad61d97265680/394a699/src/array/primitive/mutable.rs:67:13
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
Traceback (most recent call last):
  File "/home/ldrow/.pycharm_helpers/pydev/_pydevd_bundle/pydevd_exec2.py", line 3, in Exec
    exec(exp, global_vars, local_vars)
  File "<input>", line 1, in <module>
  File "/usr/local/lib/python3.9/dist-packages/polars/io.py", line 871, in read_parquet
    return DataFrame._read_parquet(
  File "/usr/local/lib/python3.9/dist-packages/polars/internals/frame.py", line 537, in _read_parquet
    self._df = PyDataFrame.read_parquet(
pyo3_runtime.PanicException: assertion failed: `(left == right)`
  left: `0`,
 right: `1`
```

#### What is the expected behavior?

Polars dataframe created with:
```python
┌──────┐
│ a    │
│ ---  │
│ f64  │
╞══════╡
│ null │
└──────┘
```

#### Note

Polars dataframe successfully creates using **use_pyarrow=True** argument in pl.read_parquet

**Comment by ritchie46** [comment]
Thanks.. I will take a look.

**Comment by ritchie46** [comment]
Fixed and released
