### ISSUE TITLE
nodejs import error 'util/types'

### ISSUE THREAD

**Issue by adamgilman** [pola-rs/polars#2671]
#### Are you using Python or Rust?

NodeJS

#### What version of polars are you using?

npm 0.3.0

#### What operating system are you using polars on?

macOS Catalina

#### Describe your bug.

Clean npm install fails to load correctly

#### What are the steps to reproduce the behavior?

```
const pl = require('nodejs-polars');
const fooSeries = pl.Series("foo", [1, 2, 3])
console.log(fooSeries)
```

#### What is the actual behavior?

```
$node main.js
internal/modules/cjs/loader.js:892
  throw err;
  ^

Error: Cannot find module 'util/types'
Require stack:
- /polartest2/node_modules/nodejs-polars/bin/internals/construction.js
- /polartest2/node_modules/nodejs-polars/bin/series/series.js
- /polartest2/node_modules/nodejs-polars/bin/index.js
- /polartest2/main.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:889:15)
    at Function.Module._load (internal/modules/cjs/loader.js:745:27)
    at Module.require (internal/modules/cjs/loader.js:961:19)
    at require (internal/modules/cjs/helpers.js:92:18)
    at Object.<anonymous> (/polartest2/node_modules/nodejs-polars/bin/internals/construction.js:9:17)
    at Module._compile (internal/modules/cjs/loader.js:1072:14)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1101:10)
    at Module.load (internal/modules/cjs/loader.js:937:32)
    at Function.Module._load (internal/modules/cjs/loader.js:778:12)
    at Module.require (internal/modules/cjs/loader.js:961:19) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/polartest2/node_modules/nodejs-polars/bin/internals/construction.js',
    '/polartest2/node_modules/nodejs-polars/bin/series/series.js',
    '/polartest2/node_modules/nodejs-polars/bin/index.js',
    '/polartest2/main.js'
  ]
}
```
#### What is the expected behavior?

Run

**Comment by universalmind303** [comment]
what version of node are you using.

**Comment by adamgilman** [comment]
Apologies! Yes, I'm on `v14.17.6`

**Comment by adamgilman** [comment]
Can confirm, once upgrading to LTS (`16.14.0`) it works as expected.
