### ISSUE TITLE
Polars crashes when reads empty CSV file

### ISSUE THREAD

**Issue by smolcoder** [pola-rs/polars#2796]
#### What language are you using?
**Python**

#### What version of polars are you using?
0.13.7

#### What operating system are you using polars on?
Fedora 28

#### What language version are you using
python 3.7

#### Describe your bug.

Reading an empty CSV file crashes the program.

#### What are the steps to reproduce the behavior?

```python
import io

import polars as pl


pl.read_csv(io.StringIO(""), has_header=False)
```

#### What is the actual behavior?

```
thread '<unnamed>' panicked at 'index out of bounds: the len is 0 but the index is 18446744073709551615', /github/workspace/polars/polars-io/src/csv_core/utils.rs:324:27
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
Traceback (most recent call last):
  File "/data/home/iarbuzo/code/sandbox/play.py", line 6, in <module>
    pl.read_csv(io.StringIO(""), has_header=False)
  File "/data/home/iarbuzo/.conda/envs/sandbox/lib/python3.7/site-packages/polars/io.py", line 417, in read_csv
    row_count_offset=row_count_offset,
  File "/data/home/iarbuzo/.conda/envs/sandbox/lib/python3.7/site-packages/polars/internals/frame.py", line 496, in _read_csv
    _prepare_row_count_args(row_count_name, row_count_offset),
pyo3_runtime.PanicException: index out of bounds: the len is 0 but the index is 18446744073709551615

Process finished with exit code 1
```

#### What is the expected behavior?
raise a meaningful exception e.g. what it was previously raising: `Any(NoData(...))`

**Comment by smolcoder** [comment]
Noting that I also had a problem with reading very large Parquet file written by polars with `use_pyarrow=True`: it crashed with no exception but printed to stderr something like "failed to allocate 18446744073709551615 bytes" or similar (do not remember exact string).
While I could reproduce it, I could not report the bug since the data for reproducing is gigabytes in compressed format. However, I think it makes sense to at least mention it here since I saw the same large integer in the exception text.

**Comment by smolcoder** [comment]
Unfortunately, I can't provide the actual data, and I failed to generate an artificial minimal example, otherwise I would have done it before of course.

**Comment by smolcoder** [comment]
Sorry, I meant `use_pyarrow=False`, edited my comment.

**Comment by ritchie46** [comment]
> Unfortunately, I can't provide the actual data, and I failed to generate an artificial minimal example, otherwise I would have done it before of course.

Could you try it on a debug build? Maybe we can extract a panic due to numeric underflow/overflow

**Comment by smolcoder** [comment]
I can try. Please, provide the minimal set of steps to build python lib in debug mode.

**Comment by ritchie46** [comment]
> I can try. Please, provide the minimal set of steps to build python lib in debug mode, then I will file a separate bug report.

I will prepare a branch fo you. 👍

**Comment by ritchie46** [comment]
@smolcoder could you try this branch? 

https://github.com/pola-rs/polars/compare/panic_branch

Steps:

* install rustup: https://www.rust-lang.org/tools/install

* set nightly compiler as default:  `$ rustup default nightly`

*  `$ cd py-polars && pip install -r build.requirements && maturin develop --release`

This will compile a release build in your current environment. The build will panic on numeric overflows. So if you can set `RUST_BACKTRACE=1` and try to reproduce your error again, we may get a backtrace.

**Comment by smolcoder** [comment]
Getting the following error with running `maturin develop --release`:
```
warning: /data/home/iarbuzo/polars-debug/polars/py-polars/Cargo.toml: unused manifest key: profile.release.target-cpu
   Compiling libz-sys v1.1.3
error: failed to run custom build command for `libz-sys v1.1.3`

Caused by:
  process didn't exit successfully: `/data/home/iarbuzo/polars-debug/polars/py-polars/target/release/build/libz-sys-1233e6c618624ffd/build-script-build` (exit status: 101)
  --- stdout
  cargo:rerun-if-env-changed=LIBZ_SYS_STATIC
  cargo:rerun-if-changed=build.rs
  CMAKE_TOOLCHAIN_FILE_x86_64-unknown-linux-gnu = None
  CMAKE_TOOLCHAIN_FILE_x86_64_unknown_linux_gnu = None
  HOST_CMAKE_TOOLCHAIN_FILE = None
  CMAKE_TOOLCHAIN_FILE = None
  CMAKE_GENERATOR_x86_64-unknown-linux-gnu = None
  CMAKE_GENERATOR_x86_64_unknown_linux_gnu = None
  HOST_CMAKE_GENERATOR = None
  CMAKE_GENERATOR = None
  CMAKE_PREFIX_PATH_x86_64-unknown-linux-gnu = None
  CMAKE_PREFIX_PATH_x86_64_unknown_linux_gnu = None
  HOST_CMAKE_PREFIX_PATH = None
  CMAKE_PREFIX_PATH = None
  CMAKE_x86_64-unknown-linux-gnu = None
  CMAKE_x86_64_unknown_linux_gnu = None
  HOST_CMAKE = None
  CMAKE = None
  running: "cmake" "/data/home/iarbuzo/.cargo/registry/src/github.com-1ecc6299db9ec823/libz-sys-1.1.3/src/zlib-ng" "-DBUILD_SHARED_LIBS=OFF" "-DZLIB_COMPAT=ON" "-DWITH_GZFILEOP=ON" "-DCMAKE_INSTALL_PREFIX=/data/home/iarbuzo/polars-debug/polars/py-polars/target/release/build/libz-sys-47392440c05c9141/out" "-DCMAKE_C_FLAGS= -ffunction-sections -fdata-sections -fPIC -m64" "-DCMAKE_C_COMPILER=/usr/bin/cc" "-DCMAKE_CXX_FLAGS= -ffunction-sections -fdata-sections -fPIC -m64" "-DCMAKE_CXX_COMPILER=/usr/bin/c++" "-DCMAKE_ASM_FLAGS= -ffunction-sections -fdata-sections -fPIC -m64" "-DCMAKE_ASM_COMPILER=/usr/bin/cc" "-DCMAKE_BUILD_TYPE=Release"
  -- Using CMake version 3.11.0
  -- ZLIB_HEADER_VERSION: 1.2.11
  -- ZLIBNG_HEADER_VERSION: 2.0.2
  -- Arch detected: 'x86_64'
  -- Basearch of 'x86_64' has been detected as: 'x86'
  -- Architecture supports unaligned reads
  -- Architecture supports unaligned reads of > 4 bytes
  -- Architecture-specific source files: arch/x86/x86.c;arch/x86/slide_avx.c;arch/x86/chunkset_avx.c;arch/x86/compare258_avx.c;arch/x86/adler32_avx.c;arch/x86/insert_string_sse.c;arch/x86/compare258_sse.c;arch/x86/chunkset_sse.c;arch/x86/slide_sse.c;arch/x86/adler32_ssse3.c;arch/x86/crc_folding.c
  -- The following features have been enabled:

   * CMAKE_BUILD_TYPE, Build type: Release (selected)
   * WITH_GZFILEOP, Compile with support for gzFile related functions
   * ZLIB_COMPAT, Compile with zlib compatible API
   * ZLIB_ENABLE_TESTS, Build test binaries
   * WITH_OPTIM, Build with optimisation
   * WITH_NEW_STRATEGIES, Use new strategies
   * WITH_UNALIGNED, Support unaligned reads on platforms that support it
   * WITH_AVX2, Build with AVX2
   * WITH_SSE2, Build with SSE2
   * WITH_SSSE3, Build with SSSE3
   * WITH_SSE4, Build with SSE4
   * WITH_PCLMULQDQ, Build with PCLMULQDQ
   * AVX2_SLIDEHASH, Support AVX2 optimized slide_hash, using "-mavx2"
   * AVX_CHUNKSET, Support AVX optimized chunkset, using "-mavx2"
   * AVX2_COMPARE258, Support AVX2 optimized compare258, using "-mavx2"
   * AVX2_ADLER32, Support AVX2-accelerated adler32, using "-mavx2"
   * SSE42_CRC, Support SSE4.2 optimized CRC hash generation, using "-msse4"
   * SSE42_COMPARE258, Support SSE4.2 optimized compare258, using "-msse4"
   * SSSE3_ADLER32, Support SSSE3-accelerated adler32, using "-mssse3"
   * PCLMUL_CRC, Support CRC hash generation using PCLMULQDQ, using "-mssse3 -msse4 -mpclmul"

  -- The following features have been disabled:

   * ZLIB_DUAL_LINK, Dual link tests against system zlib
   * WITH_SANITIZER, Build with sanitizer (Memory, Address, Undefined)
   * WITH_FUZZERS, Build test/fuzz
   * WITH_NATIVE_INSTRUCTIONS, Instruct the compiler to use the full instruction set on this host (gcc/clang -march=native)
   * WITH_MAINTAINER_WARNINGS, Build with project maintainer warnings
   * WITH_CODE_COVERAGE, Enable code coverage reporting
   * WITH_INFLATE_STRICT, Build with strict inflate distance checking
   * WITH_INFLATE_ALLOW_INVALID_DIST, Build with zero fill for inflate invalid distances
   * INSTALL_UTILS, Copy minigzip and minideflate during install

  -- Configuring done
  -- Generating done
  -- Build files have been written to: /data/home/iarbuzo/polars-debug/polars/py-polars/target/release/build/libz-sys-47392440c05c9141/out/build
  running: "cmake" "--build" "." "--target" "install" "--config" "Release" "--parallel" "12"

  --- stderr
  Unknown argument --parallel
  Unknown argument 12
  Usage: cmake --build <dir> [options] [-- [native-options]]
  Options:
    <dir>          = Project binary directory to be built.
    --target <tgt> = Build <tgt> instead of default targets.
                     May only be specified once.
    --config <cfg> = For multi-configuration tools, choose <cfg>.
    --clean-first  = Build target 'clean' first, then build.
                     (To clean only, use --target 'clean'.)
  --use-stderr   = Ignored.  Behavior is default in CMake >= 3.0.
    --             = Pass remaining options to the native tool.
  thread 'main' panicked at '
  command did not execute successfully, got: exit status: 1

  build script failed, must exit now', /home/iarbuzo/.cargo/registry/src/github.com-1ecc6299db9ec823/cmake-0.1.48/src/lib.rs:975:5
  note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
💥 maturin failed
  Caused by: Failed to build a native library through cargo
  Caused by: Cargo build finished with "exit status: 101": `cargo rustc --message-format json --manifest-path Cargo.toml --release --lib --`
```

**Comment by ritchie46** [comment]
I think you must remove your `Cargo.lock`

**Comment by smolcoder** [comment]
I tried this before, same result.

**Comment by ghuls** [comment]
You need a newer CMake that supports `--paralllel`

Or if you are lucky, this might work too:
```bash
cd /data/home/iarbuzo/polars-debug/polars/py-polars/target/release/build/libz-sys-47392440c05c9141/out/build
"cmake" "--build" "." "--target" "install" "--config" "Release"
```

**Comment by smolcoder** [comment]
I managed to build and run, but no luck with further debugging:
```
(polars-debug) ➜  py-polars git:(panic_branch) ✗ RUST_BACKTRACE=1 python ~/code/sandbox/memory-allocation-failure.py            
memory allocation of 18446744071841293701 bytes failed
[1]    23343 abort (core dumped)  RUST_BACKTRACE=1 python ~/code/sandbox/memory-allocation-failure.py
```
core dump file is 1.9G so unlikely I can share it.

what else we can do to shed more light on the problem?
