### ISSUE TITLE
any/all expressions yield SchemaMismatch error with list of expressions

### ISSUE THREAD

**Issue by cbilot** [pola-rs/polars#2817]
python 3.10.2
polars 0.13.8
Linux Mint 20.3
#### Describe your bug.
The documentation for `polars.any` expression states the following:
```
polars.any(name: Union[str, List[polars.internals.expr.Expr]]) → polars.internals.expr.Expr
    Evaluate columnwise or elementwise with a bitwise OR operation.
```
My understanding of the argument choices is that:
1. `polars.any(str)` is syntactic sugar for `polars.col(str).any()`
2. `polars.any(List[polars.internals.expr.Expr])` will apply a bitwise OR operation **row-wise** across the expressions in the list.

However, when I attempt to use the second option above, I consistently get a `SchemaMisMatch` error. 
#### What are the steps to reproduce the behavior?
Starting with this data ...
```python
import polars as pl

df = pl.DataFrame(
    [
        [False, False, True],
        [False, False, True],
        [True, False, False],
        [False, None, True],
        [None, None, False],
    ],
    columns=["var1", "var2", "var3"],
)
df
```
```
shape: (5, 3)
┌───────┬───────┬───────┐
│ var1  ┆ var2  ┆ var3  │
│ ---   ┆ ---   ┆ ---   │
│ bool  ┆ bool  ┆ bool  │
╞═══════╪═══════╪═══════╡
│ false ┆ false ┆ true  │
├╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌┤
│ false ┆ false ┆ true  │
├╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌┤
│ true  ┆ false ┆ false │
├╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌┤
│ false ┆ null  ┆ true  │
├╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌┤
│ null  ┆ null  ┆ false │
└───────┴───────┴───────┘
```
#### What is the actual behavior?
Attemping to use a list of expressions to bit-wise OR across the second and third columns:
```python
df.select(pl.any([pl.col("var2"), pl.col("var3")]).alias("result"))
```
```
thread '<unnamed>' panicked at 'custom python function failed: Any(SchemaMisMatch("cannot unpack series shape: (5,)\nSeries: 'var2' [bool]\n[\n\tfalse\n\tfalse\n\tfalse\n\tnull\n\tnull\n] into matching type Int64"))', src/lazy/apply.rs:89:23
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/corey/.virtualenvs/test_project3.10/lib/python3.10/site-packages/polars/internals/frame.py", line 3994, in select
    self.lazy().select(exprs).collect(no_optimization=True, string_cache=False)  # type: ignore
  File "/home/corey/.virtualenvs/test_project3.10/lib/python3.10/site-packages/polars/internals/lazy_frame.py", line 423, in collect
    return pli.wrap_df(ldf.collect())
pyo3_runtime.PanicException: custom python function failed: Any(SchemaMisMatch("cannot unpack series shape: (5,)\nSeries: 'var2' [bool]\n[\n\tfalse\n\tfalse\n\tfalse\n\tnull\n\tnull\n] into matching type Int64"))
```
#### What is the expected behavior?
I expected `polars.any` with a list of expressions to be syntactic sugar for
```python
df.with_column(
    pl.fold(
        acc=pl.lit(False),
        f=lambda x, a: x | a,
        exprs=[pl.col("var2"), pl.col("var3")]
    ).alias("result")
)
```
```
shape: (5, 4)
┌───────┬───────┬───────┬────────┐
│ var1  ┆ var2  ┆ var3  ┆ result │
│ ---   ┆ ---   ┆ ---   ┆ ---    │
│ bool  ┆ bool  ┆ bool  ┆ bool   │
╞═══════╪═══════╪═══════╪════════╡
│ false ┆ false ┆ true  ┆ true   │
├╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌┤
│ false ┆ false ┆ true  ┆ true   │
├╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌┤
│ true  ┆ false ┆ false ┆ false  │
├╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌┤
│ false ┆ null  ┆ true  ┆ true   │
├╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌┤
│ null  ┆ null  ┆ false ┆ null   │
└───────┴───────┴───────┴────────┘
```
#### Other Notes/Thoughts
The same error occurs if I use `polars.all`.

The presence of `null` values does not matter; if all values are `True`/`False`, the error is the same.

My reason for wanting to use the `polars.any` and `polars.all` is simply conciseness and readability.  It's a common situation that comes up in code to say: _if `any` of the following conditions hold_, or _if `all` of these criteria are met_.

I can easily use the `polars.fold` to accomplish the same thing.  It's just less readable (and possibly prone to mistakes as the `acc` argument for bitwise `and` is different than bitwise `or`.

**Comment by ritchie46** [comment]
You are completely right. This is the implementation:

```python
def any(name: Union[str, List["pli.Expr"]]) -> "pli.Expr":
    """
    Evaluate columnwise or elementwise with a bitwise OR operation.
    """
    if isinstance(name, list):
        return fold(lit(0), lambda a, b: a | b, name).alias("any")
    return col(name).any()
```

It seems we start with `lit(0)` where we need to start with `lit(False)`. I will fix it.
