### ISSUE TITLE
pypolars cannot connect to postgresql using pl.read_sql

### ISSUE THREAD

**Issue by hengaini2055** [pola-rs/polars#2889]
I use the simplest code to connect to postgresql as follows:
```
import polars as pl

url = "postgreql://postgres:20182011@127.0.0.1:5432/demo"
query = "select * from bookings.airports_data;"
pl.read_sql(url, query)
```
When I run code using _python main.py_, I get the followings:
```
(venv) E:\bokeh>python hello.py
Traceback (most recent call last):
  File "hello.py", line 10, in <module>
    pl.read_sql(url, query)
  File "E:\bokeh\venv\lib\site-packages\polars\io.py", line 969, in read_sql
    tbl = cx.read_sql(
  File "E:\bokeh\venv\lib\site-packages\connectorx\__init__.py", line 102, in read_sql
    backend, connection_details = conn.split(":", 1) if conn else ("", "")
ValueError: not enough values to unpack (expected 2, got 1)
```
Python is 3.8.10, OS is window 10, and python libraries as follows:
```
polars               0.13.10
prometheus-client    0.13.1
prompt-toolkit       3.0.28
psutil               5.9.0
psycopg2             2.9.3
pure-eval            0.2.2
pyarrow              7.0.0
pycparser            2.21
pyct                 0.4.8
Pygments             2.11.2
pyparsing            3.0.7
pyrsistent           0.18.1
```
Any reply is welcome!

**Comment by hengaini2055** [comment]
The parameters are in the wrong order
