### ISSUE TITLE
polars-u64-idx join produces incorrect results for row indices above 2**32

### ISSUE THREAD

**Issue by cbilot** [pola-rs/polars#3279]
polars-u64-idx 0.13.28
python 3.10.4
Linux Mint 20.3

#### Describe your bug.
When joining to a DataFrame with more than `2**32` rows, the join returns the wrong rows for row indices over `2**32`.  In fact, the row indices seem to roll over (that is, `returned row index == actual matched row index mod 2**32`). 

This was a nasty debug, but I'll structure this MWE so that (hopefully) you will be able to spot the problem without having to create/load large datasets.

#### MWE
We'll create a dataset with just a few more rows than `2**32`, and we'll focus on the last few rows to see what is happening.
```python3
import polars as pl
df = pl.DataFrame(
    {
        "join_col": pl.repeat(False, 2**32 - 3, eager=True).extend_constant(True, 6),
        "row_nr": pl.arange(0, 2**32 + 3, eager=True),
    }
)

df.filter(pl.col("join_col"))
```
```
shape: (6, 2)
┌──────────┬────────────┐
│ join_col ┆ row_nr     │
│ ---      ┆ ---        │
│ bool     ┆ i64        │
╞══════════╪════════════╡
│ true     ┆ 4294967293 │
├╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌┤
│ true     ┆ 4294967294 │
├╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌┤
│ true     ┆ 4294967295 │
├╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌┤
│ true     ┆ 4294967296 │
├╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌┤
│ true     ┆ 4294967297 │
├╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌┤
│ true     ┆ 4294967298 │
└──────────┴────────────┘
```
The `2**32th` row is `row_nr` 4294967295 (since I started `row_nr` at zero).

Now we'll do a join:
```python3
df.join(pl.DataFrame({"join_col": [True]}), on="join_col", how="inner")
```
```
shape: (6, 2)
┌──────────┬────────────┐
│ join_col ┆ row_nr     │
│ ---      ┆ ---        │
│ bool     ┆ i64        │
╞══════════╪════════════╡
│ true     ┆ 4294967293 │
├╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌┤
│ true     ┆ 4294967294 │
├╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌┤
│ true     ┆ 4294967295 │
├╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌┤
│ false    ┆ 0          │
├╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌┤
│ false    ┆ 1          │
├╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌┤
│ false    ┆ 2          │
└──────────┴────────────┘
```
What seems to be happening is that the matched row indices are rolling over to 0 when they reach `2**32`.

#### Other Notes:
* In the queries that I ran against a 5.9 billion record dataset, the join column was an Int64.  So this issue seems unrelated to the dtype of the join column.
* The use of a `filter` showed that I always received the correct *number* of records in my join results.  However, for any row index above `2**32`, the returned row was `row index mod 2**32`.  Once I discovered the pattern, the results were predictable.
* I will be submitting a separate bug report for `with_row_count`.  (This is why I had to create `row_nr` using `arange`.)  That seemed less important, so I'm submitting this bug report first.  (I am still working on MWE's for some others.)
* If you can show me how to alter the compile instructions for `polars-u64-idx`, I can test any fixes.
```cd py-polars && maturin develop --rustc-extra-args="-C target-cpu=native" --release```

**Comment by cbilot** [comment]
I should have noted that I double-checked that I'm actually using polars-u64-idx.  Here's a (truncated) pip listing:
```
(Big_Idx3.10) corey@threadripperpro:/mnt/projects/Big_Idx$ pip list
Package                       Version   Editable project location
----------------------------- --------- -------------------------
polars-u64-idx                0.13.28
pyarrow                       7.0.0
```

**Comment by ritchie46** [comment]
Sorry about that. There might be a bit more of these bugs, as u64 is not yet battle tested.

The hard thing is that these errors only occur at data > 2^32.

I will look into it

**Comment by ritchie46** [comment]
I cannot really find anything with the code. But it seems that we simply did not set the proper feature gate and that you thus are regular polars.

Could you try compiling this branch? https://github.com/pola-rs/polars/tree/test_bigidx

**Comment by cbilot** [comment]
I received the following warnings & errors:
```
   Compiling polars-core v0.21.0 (/mnt/projects/polars/polars/polars-core)
warning: unnecessary lifetime parameter `'de`266: polars-core, arrow2, polars-arrow                                                                                                                                                         
   --> /mnt/projects/polars/polars/polars-core/src/datatypes.rs:842:62
    |
842 | #[cfg_attr(feature = "serde-lazy", serde(bound(deserialize = "'de: 'static")))]
    |                                                              ^^^^^^^^^^^^^^
    |
    = help: you can use the `'static` lifetime directly, in place of `'de`


    Building [=======================> ] 257/266: polars-core, arrow2, polars-arrow                                                                                                                                                         warning: unnecessary lifetime parameter `'de`
  --> /mnt/projects/polars/polars/polars-core/src/frame/asof_join/mod.rs:14:57
   |
14 | #[cfg_attr(feature = "serde", serde(bound(deserialize = "'de: 'static")))]
   |                                                         ^^^^^^^^^^^^^^
   |
   = help: you can use the `'static` lifetime directly, in place of `'de`


warning: unnecessary lifetime parameter `'de`266: polars-core, arrow2, polars-arrow                                                                                                                                                         
  --> /mnt/projects/polars/polars/polars-core/src/schema.rs:12:31
   |
12 |     serde(bound(deserialize = "'de: 'static"))
   |                               ^^^^^^^^^^^^^^
   |
   = help: you can use the `'static` lifetime directly, in place of `'de`
```

```
   Compiling polars-lazy v0.21.0 (/mnt/projects/polars/polars/polars-lazy)
 warning: unnecessary lifetime parameter `'de`
   --> /mnt/projects/polars/polars/polars-lazy/src/dsl/expr.rs:203:57
    |
203 | #[cfg_attr(feature = "serde", serde(bound(deserialize = "'de: 'static")))]
    |                                                         ^^^^^^^^^^^^^^
    |
    = help: you can use the `'static` lifetime directly, in place of `'de`


warning: unnecessary lifetime parameter `'de`266: polars-core, arrow2, polars-time, polars-lazy, polars-io, polars-ops                                                                                                                      
   --> /mnt/projects/polars/polars/polars-lazy/src/dsl/expr.rs:253:31
    |
253 |     serde(bound(deserialize = "'de: 'static"))
    |                               ^^^^^^^^^^^^^^
    |
    = help: you can use the `'static` lifetime directly, in place of `'de`


warning: unnecessary lifetime parameter `'de`266: polars-core, arrow2, polars-time, polars-lazy, polars-io, polars-ops                                                                                                                      
  --> /mnt/projects/polars/polars/polars-lazy/src/logical_plan/lit.rs:11:57
   |
11 | #[cfg_attr(feature = "serde", serde(bound(deserialize = "'de: 'static")))]
   |                                                         ^^^^^^^^^^^^^^
   |
   = help: you can use the `'static` lifetime directly, in place of `'de`


warning: unnecessary lifetime parameter `'de`266: polars-core, arrow2, polars-time, polars-lazy, polars-io, polars-ops                                                                                                                      
  --> /mnt/projects/polars/polars/polars-lazy/src/logical_plan/mod.rs:48:31
   |
48 |     serde(bound(deserialize = "'de: 'static"))
   |                               ^^^^^^^^^^^^^^
   |
   = help: you can use the `'static` lifetime directly, in place of `'de`


error[E0308]: mismatched types=======> ] 259/266: polars-core, arrow2, polars-lazy, polars-io, polars-ops                                                                                                                                   
   --> /mnt/projects/polars/polars/polars-lazy/src/physical_plan/expressions/window.rs:404:56
    |
404 |                 let idx = unsafe { perfect_sort(&POOL, &idx_mapping) };
    |                                    ------------        ^^^^^^^^^^^^ expected slice, found struct `Vec`
    |                                    |
    |                                    arguments to this function are incorrect
    |
    = note: expected reference `&[(u32, u32)]`
               found reference `&Vec<(u64, u64)>`
note: function defined here
   --> /mnt/projects/polars/polars/polars-utils/src/sort.rs:17:15
    |
17  | pub unsafe fn perfect_sort(pool: &ThreadPool, idx: &[(IdxSize, IdxSize)]) -> Vec<IdxSize> {
    |               ^^^^^^^^^^^^


error[E0308]: mismatched types=======> ] 259/266: polars-core, arrow2, polars-lazy, polars-io, polars-ops                                                                                                                                   
   --> /mnt/projects/polars/polars/polars-lazy/src/physical_plan/expressions/window.rs:405:47
    |
405 |                 let idx = IdxCa::from_vec("", idx);
    |                           ---------------     ^^^ expected `u64`, found `u32`
    |                           |
    |                           arguments to this function are incorrect
    |
    = note: expected struct `Vec<u64>`
               found struct `Vec<u32>`
note: associated function defined here
   --> /mnt/projects/polars/polars/polars-core/src/chunked_array/mod.rs:453:12
    |
453 |     pub fn from_vec(name: &str, v: Vec<T::Native>) -> Self {
    |            ^^^^^^^^


   error: aborting due to 2 previous errors; 4 warnings emitted

 
For more information about this error, try `rustc --explain E0308`.polars-lazy, polars-ops                                                                                                                                              

error: could not compile `polars-lazy` due to 3 previous errors; 4 warnings emitted
warning: build failed, waiting for other jobs to finish...
warning: 3 warnings emitted==========> ] 263/266: polars-core                                                                                                                                                                               


💥 maturin failed
  Caused by: Failed to build a native library through cargo
  Caused by: Cargo build finished with "exit status: 101": `cargo rustc --manifest-path Cargo.toml --message-format json --release --lib -- -C target-cpu=native`
```
I tried updating maturin and also `rustup update`, but still receive the errors.
I compiled using:
`cd py-polars && maturin develop --rustc-extra-args="-C target-cpu=native" --release`

Is there something else I should try?

**Comment by cbilot** [comment]
FWIW, there's no hurry on my part.  I'm doing this solely to test polars-u64-idx on some large datasets.  Given my computing platform, I figured it was one way that I can contribute to Polars.

**Comment by cbilot** [comment]
Sorry to report this.  I just downloaded version 0.13.29 of polars-u64-idx and re-ran my test.  It still fails.  
```python3
df.join(pl.DataFrame({"join_col": [True]}), on="join_col", how="inner")
```
```
shape: (6, 2)
┌──────────┬────────────┐
│ join_col ┆ row_nr     │
│ ---      ┆ ---        │
│ bool     ┆ i64        │
╞══════════╪════════════╡
│ true     ┆ 4294967293 │
├╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌┤
│ true     ┆ 4294967294 │
├╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌┤
│ true     ┆ 4294967295 │
├╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌┤
│ false    ┆ 0          │
├╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌┤
│ false    ┆ 1          │
├╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌┤
│ false    ┆ 2          │
└──────────┴────────────┘
```
```
>>> pl.__version__
'0.13.29'
```
I was careful to start with a new temporary virtual environment.
```
corey@threadripperpro:~/.virtualenvs$ mktmpenv -p /usr/bin/python3.10
created virtual environment CPython3.10.4.final.0-64 in 347ms
  creator CPython3Posix(dest=/home/corey/.virtualenvs/tmp-ca55e42c5150a31, clear=False, no_vcs_ignore=False, global=False)
  seeder FromAppData(download=False, pip=bundle, setuptools=bundle, wheel=bundle, via=copy, app_data_dir=/home/corey/.local/share/virtualenv)
    added seed packages: pip==22.0.4, setuptools==62.0.0, wheel==0.37.1
  activators BashActivator,CShellActivator,FishActivator,NushellActivator,PowerShellActivator,PythonActivator
virtualenvwrapper.user_scripts creating /home/corey/.virtualenvs/tmp-ca55e42c5150a31/bin/predeactivate
virtualenvwrapper.user_scripts creating /home/corey/.virtualenvs/tmp-ca55e42c5150a31/bin/postdeactivate
virtualenvwrapper.user_scripts creating /home/corey/.virtualenvs/tmp-ca55e42c5150a31/bin/preactivate
virtualenvwrapper.user_scripts creating /home/corey/.virtualenvs/tmp-ca55e42c5150a31/bin/postactivate
virtualenvwrapper.user_scripts creating /home/corey/.virtualenvs/tmp-ca55e42c5150a31/bin/get_env_details
This is a temporary environment. It will be deleted when you run 'deactivate'.
```
And installed version 0.13.29 of polars-u64-idx.  (I purposely have not yet downloaded version 0.13.29 of regular polars to my machine - just to be absolutely sure that the idx version could not be confused with the regular version.)
```
(tmp-ca55e42c5150a31) corey@threadripperpro:~/.virtualenvs/tmp-ca55e42c5150a31$ pip install polars-u64-idx
Collecting polars-u64-idx
  Using cached polars_u64_idx-0.13.29-cp37-abi3-manylinux_2_12_x86_64.manylinux2010_x86_64.whl (11.3 MB)
Collecting numpy>=1.16.0
  Using cached numpy-1.22.3-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (16.8 MB)
Installing collected packages: numpy, polars-u64-idx
Successfully installed numpy-1.22.3 polars-u64-idx-0.13.29
```
```
(tmp-ca55e42c5150a31) corey@threadripperpro:~/.virtualenvs/tmp-ca55e42c5150a31$ pip list
Package        Version
-------------- -------
numpy          1.22.3
pip            22.0.4
polars-u64-idx 0.13.29
setuptools     62.0.0
wheel          0.37.1
```

**Comment by ritchie46** [comment]
Can you show what dtype row count gives you?

**Comment by cbilot** [comment]
```
>>> df.with_row_count()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/corey/.virtualenvs/tmp-ca55e42c5150a31/lib/python3.10/site-packages/polars/internals/frame.py", line 2710, in with_row_count
    return self._from_pydf(self._df.with_row_count(name, offset))
exceptions.ShapeError: Could not create a new DataFrame from Series. The Series have different lengths
```

**Comment by ritchie46** [comment]
i believe it is regular polars. So the release of bigidx is not working. you can check row count on a small df. If it gived a u32 dtype, we are indeed running regular polars

**Comment by cbilot** [comment]
Indeed.  (The col `row_nr` was generated with `arange`, and I kept it for comparison.) 
```
>>> df.slice(0,100).with_row_count(name='with_row_count')
shape: (100, 3)
┌────────────────┬──────────┬────────┐
│ with_row_count ┆ join_col ┆ row_nr │
│ ---            ┆ ---      ┆ ---    │
│ u32            ┆ bool     ┆ i64    │
╞════════════════╪══════════╪════════╡
│ 0              ┆ false    ┆ 0      │
├╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌┤
│ 1              ┆ false    ┆ 1      │
├╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌┤
│ 2              ┆ false    ┆ 2      │
├╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌┤
│ 3              ┆ false    ┆ 3      │
├╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌┤
│ ...            ┆ ...      ┆ ...    │
├╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌┤
│ 96             ┆ false    ┆ 96     │
├╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌┤
│ 97             ┆ false    ┆ 97     │
├╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌┤
│ 98             ┆ false    ┆ 98     │
├╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌┤
│ 99             ┆ false    ┆ 99     │
└────────────────┴──────────┴────────┘
```

**Comment by ritchie46** [comment]
Ok, then I must double check the build CI. Thanks for notifying.

**Comment by ritchie46** [comment]
@cbilot I believe it should work now.

**Comment by cbilot** [comment]
```
>>> df.join(pl.DataFrame({"join_col": [True]}), on="join_col", how="inner")
shape: (6, 2)
┌──────────┬───────────────┐
│ join_col ┆ row_nr        │
│ ---      ┆ ---           │
│ bool     ┆ i64           │
╞══════════╪═══════════════╡
│ true     ┆ 4294967293    │
├╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┤
│ true     ┆ 4294967294    │
├╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┤
│ true     ┆ 4294967295    │
├╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┤
│ true     ┆ 4294967296    │
├╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┤
│ true     ┆ 4294967297    │
├╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┤
│ true     ┆ 4294967298    │
└──────────┴───────────────┘
```

Indeed it does!
