### ISSUE TITLE
polars-u64-idx: with_row_count errors for DataFrames with height of 2**32 or more

### ISSUE THREAD

**Issue by cbilot** [pola-rs/polars#3280]
polars-u64-idx 0.13.28
python 3.10.4
Linux Mint 20.3

#### Describe your bug.
`with_row_count` gives an error when the number of rows is `2**32` or more.

#### What are the steps to reproduce the behavior?
```python3
import polars as pl

pl.DataFrame(
    {"col1": pl.repeat(False, (2**32), eager=True)}
).with_row_count()
```
```
Traceback (most recent call last):
  File "<stdin>", line 4, in <module>
  File "/home/corey/.virtualenvs/Big_Idx3.10/lib/python3.10/site-packages/polars/internals/frame.py", line 2706, in with_row_count
    return self._from_pydf(self._df.with_row_count(name, offset))
exceptions.ShapeError: Could not create a new DataFrame from Series. The Series have different lengths
```

But for `2**32 - 1` records:
```python3
pl.DataFrame(
    {"col1": pl.repeat(False, (2**32) - 1, eager=True)}
).with_row_count()
```
```
shape: (4294967295, 2)
┌────────────┬───────┐
│ row_nr     ┆ col1  │
│ ---        ┆ ---   │
│ u32        ┆ bool  │
╞════════════╪═══════╡
│ 0          ┆ false │
├╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌┤
│ 1          ┆ false │
├╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌┤
│ 2          ┆ false │
├╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌┤
│ 3          ┆ false │
├╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌┤
│ ...        ┆ ...   │
├╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌┤
│ 4294967291 ┆ false │
├╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌┤
│ 4294967292 ┆ false │
├╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌┤
│ 4294967293 ┆ false │
├╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌┤
│ 4294967294 ┆ false │
└────────────┴───────┘
```

**Comment by cbilot** [comment]
For documentation: this works for polars-u64-idx 0.13.31
```python3
import polars as pl
pl.DataFrame(
    {
        "join_col": pl.repeat(False, 2**32 - 3, eager=True).extend_constant(True, 6),
    }
).with_row_count()
```
```
shape: (4294967299, 2)
┌────────────┬──────────┐
│ row_nr     ┆ join_col │
│ ---        ┆ ---      │
│ u64        ┆ bool     │
╞════════════╪══════════╡
│ 0          ┆ false    │
├╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌┤
│ 1          ┆ false    │
├╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌┤
│ 2          ┆ false    │
├╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌┤
│ 3          ┆ false    │
├╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌┤
│ ...        ┆ ...      │
├╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌┤
│ 4294967295 ┆ true     │
├╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌┤
│ 4294967296 ┆ true     │
├╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌┤
│ 4294967297 ┆ true     │
├╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌┤
│ 4294967298 ┆ true     │
└────────────┴──────────┘
>>> pl.__version__
'0.13.31'
```
