### ISSUE TITLE
Segmentation fault when grouping a wide DataFrame

### ISSUE THREAD

**Issue by crm416** [pola-rs/polars#3287]
#### What language are you using?

**Python**

#### Have you tried latest version of polars?

Yes

#### What version of polars are you using?

`polars==0.13.28`

#### What operating system are you using polars on?

```
root@5393a98160f3:~/spring-experiments# lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 18.04.6 LTS
Release:	18.04
Codename:	bionic
```

#### What language version are you using

root@5393a98160f3:~/spring-experiments# python --version
Python 3.8.12

#### Describe your bug.

Aggregating a wide DataFrame is leading to a segmentation fault.

#### What are the steps to reproduce the behavior?

```py
import random

import polars as pl
import numpy as np


N_ROWS = 1000
N_COLS = 512
N_REPEATS = 3


df = pl.DataFrame(
    [
        pl.Series("plate", ["plate-1" for i in range(N_ROWS)]),
        pl.Series(
            "well",
            [
                random.choice(
                    [
                        "A01",
                        "A02",
                        "A03",
                        "A04",
                        "A05",
                        "A06",
                        "A07",
                        "A08",
                        "A09",
                        "A10",
                        "A11",
                        "A12",
                        "A13",
                        "A14",
                        "A15",
                        "A16",
                        "A17",
                        "A18",
                        "A19",
                        "A20",
                        "A21",
                        "A22",
                        "A23",
                        "A24",
                    ]
                )
                for _ in range(N_ROWS)
            ],
        ),
        pl.Series(
            "field",
            [random.choice(["f01", "f02", "f03", "f04"]) for _ in range(N_ROWS)],
        ),
        pl.Series(
            "row",
            [random.randint(0, 1000) for _ in range(N_ROWS)],
        ),
        pl.Series(
            "column",
            [random.randint(0, 1000) for _ in range(N_ROWS)],
        ),
        *[
            pl.Series(f"Output_{j}_{k}", np.random.random(N_ROWS), dtype=pl.Float32)
            for k in range(N_REPEATS)
            for j in range(N_COLS)
        ],
    ]
)


df.lazy().groupby(["plate", "well"]).agg(pl.all().mean()).collect()
```

#### What is the actual behavior?

At the parameters included above, I get:

```
root@5393a98160f3:~/spring-experiments# python -m main
Segmentation fault (core dumped)
```

If I keep `N_ROWS = 1000`, but `N_REPEATS = 1`, then I get a different error:

```
root@5393a98160f3:~/spring-experiments# python -m main
Traceback (most recent call last):
  File "/root/.pyenv/versions/3.8.12/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/root/.pyenv/versions/3.8.12/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/root/spring-experiments/test.py", line 70, in <module>
    df.lazy().groupby(["plate", "well"]).agg(pl.all().mean()).collect()
  File "/root/.venv/lib/python3.8/site-packages/polars/internals/lazy_frame.py", line 572, in collect
    return self._dataframe_class._from_pydf(ldf.collect())
exceptions.NotFoundError: field
```

(I can resolve _this_ error by changing the expression to: `df.lazy().drop('field').groupby(["plate", "well"]).agg(pl.all().mean()).collect()`. However, that fix doesn't get rid of the segmentation fault for `N_ROWS = 1000`.)

If I change `N_ROWS = 999`, I see no such error, and it runs to completion.

**Comment by crm416** [comment]
(Just want to say: super cool project and really impressed by it thus far! Hoping we can get it working for our production workflows at Spring Discovery.)

**Comment by ritchie46** [comment]
Thanks for the issue. Sorry for this. This was introduced latest release. I've yanked it and will fix it.

**Comment by crm416** [comment]
Thank you for the fast response and turnaround -- hugely appreciated!

**Comment by ritchie46** [comment]
> (Just want to say: super cool project and really impressed by it thus far! Hoping we can get it working for our production workflows at Spring Discovery.)

Let me know how it goes. If you you are willing to not write pandas like polars, you should be fine. ;)

**Comment by crm416** [comment]
Hahaha I'll do my best :)
