### ISSUE TITLE
struct: exception when list (of struct) is empty

### ISSUE THREAD

**Issue by cbilot** [pola-rs/polars#3427]
polars 0.13.37
python 3.10.4
Linux Mint 20.3
#### Describe your bug.
In a column of type list (of struct), attempting to include an empty list generates an error.  This does not occur with lists of other dtypes.

#### What are the steps to reproduce the behavior?
We can generate a column of type `list [struct[2]]` with one or more structs in each list.
```python3
import polars as pl

pl.DataFrame(
    {
        "list_struct": [
            [{"a": 1, "b": 2}, {"a": 3, "b": 4}, {"a": 5, "b": 6}],
            [{"a": 1, "b": 2}, {"a": 3, "b": 4}],
            [{"a": 1, "b": 2}],
        ],
    }
)
```
```
shape: (3, 1)
┌───────────────────────┐
│ list_struct           │
│ ---                   │
│ list [struct[2]]      │
╞═══════════════════════╡
│ [{1,2}, {3,4}, {5,6}] │
├╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┤
│ [{1,2}, {3,4}]        │
├╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┤
│ [{1,2}]               │
└───────────────────────
```
However, taking the next step - an empty list - generates an error.
```python3
pl.DataFrame(
    {
        "list_struct": [
            [{"a": 1, "b": 2}, {"a": 3, "b": 4}, {"a": 5, "b": 6}],
            [{"a": 1, "b": 2}, {"a": 3, "b": 4}],
            [{"a": 1, "b": 2}],
            [],
        ],
    }
)
```
```
thread '<unnamed>' panicked at 'called `Result::unwrap()` on an `Err` value: InvalidArgumentError("It is not possible to concatenate arrays of different data types.")', /github/workspace/polars/polars-core/src/chunked_array/builder/list.rs:464:18
--- PyO3 is resuming a panic after fetching a PanicException from Python. ---
Python stack trace below:
Traceback (most recent call last):
  File "/home/corey/.virtualenvs/PolarsIssue3.10/lib/python3.10/site-packages/polars/internals/series.py", line 227, in __init__
    self._s = sequence_to_pyseries(name, values, dtype=dtype, strict=strict)
  File "/home/corey/.virtualenvs/PolarsIssue3.10/lib/python3.10/site-packages/polars/internals/construction.py", line 224, in sequence_to_pyseries
    return sequence_from_anyvalue_or_object(name, values)
  File "/home/corey/.virtualenvs/PolarsIssue3.10/lib/python3.10/site-packages/polars/internals/construction.py", line 140, in sequence_from_anyvalue_or_object
    return PySeries.new_from_anyvalues(name, values)
pyo3_runtime.PanicException: called `Result::unwrap()` on an `Err` value: InvalidArgumentError("It is not possible to concatenate arrays of different data types.")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/corey/.virtualenvs/PolarsIssue3.10/lib/python3.10/site-packages/polars/internals/frame.py", line 302, in __init__
    self._df = dict_to_pydf(data, columns=columns)
  File "/home/corey/.virtualenvs/PolarsIssue3.10/lib/python3.10/site-packages/polars/internals/construction.py", line 402, in dict_to_pydf
    return PyDataFrame.read_dict(data)
pyo3_runtime.PanicException: Unwrapped panic from Python code
```
#### Other data types
This exception does not occur with other inner dtypes.
```python3
pl.DataFrame(
    {
        "list_int": [
            [1, 2, 3],
            [1, 2],
            [1],
            []
        ],
    }
)
```
```
shape: (4, 1)
┌────────────┐
│ list_int   │
│ ---        │
│ list [i64] │
╞════════════╡
│ [1, 2, 3]  │
├╌╌╌╌╌╌╌╌╌╌╌╌┤
│ [1, 2]     │
├╌╌╌╌╌╌╌╌╌╌╌╌┤
│ [1]        │
├╌╌╌╌╌╌╌╌╌╌╌╌┤
│ []         │
└────────────┘
```
```python3
pl.DataFrame(
    {
        "list_str": [
            ['foo', 'bar', 'baz'],
            ['foo', 'bar'],
            ['foo'],
            []
        ],
    }
)
```
```
shape: (4, 1)
┌───────────────────────┐
│ list_str              │
│ ---                   │
│ list [str]            │
╞═══════════════════════╡
│ ["foo", "bar", "baz"] │
├╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┤
│ ["foo", "bar"]        │
├╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┤
│ ["foo"]               │
├╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┤
│ []                    │
└───────────────────────┘
```

#### Other Notes:
A similar situation is occuring in #3404 when parsing a JSON file with an empty list.  (This is a comment added after the issue was closed.)
> I have one more question. The following code works
> 
> ```python
> import polars as pl
> 
> df = pl.DataFrame(
>     {"text": ['[{"x": 1, "y": 2}]', '[{"x": 1, "y": 2}, {"x": 3, "y": 4}]']}
> )
> df.select(pl.col("text").apply(json.loads))
> ```
> 
> while the following code fails
> 
> ```python
> import polars as pl
> 
> df = pl.DataFrame(
>     {"text": ['[{"x": 1, "y": 2}, {"x": 3, "y": 4}]', "[]"]}
> )
> df.select(pl.col("text").apply(json.loads))
> ```
> 
> Is `[]` not supported?

In this case, the `json.loads` method returns an empty list to `apply`, which then generates an error:
```
thread '<unnamed>' panicked at 'called `Result::unwrap()` on an `Err` value: InvalidArgumentError("It is not possible to concatenate arrays of different data types.")', /github/workspace/polars/polars-core/src/chunked_array/builder/list.rs:517:18
--- PyO3 is resuming a panic after fetching a PanicException from Python. ---
Python stack trace below:
Traceback (most recent call last):
  File "/home/corey/.virtualenvs/PolarsIssue3.10/lib/python3.10/site-packages/polars/internals/expr.py", line 1547, in wrap_f
    return x.apply(f, return_dtype=return_dtype)
  File "/home/corey/.virtualenvs/PolarsIssue3.10/lib/python3.10/site-packages/polars/internals/series.py", line 2619, in apply
    return wrap_s(self._s.apply_lambda(func, pl_return_dtype))
pyo3_runtime.PanicException: called `Result::unwrap()` on an `Err` value: InvalidArgumentError("It is not possible to concatenate arrays of different data types.")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/corey/.virtualenvs/PolarsIssue3.10/lib/python3.10/site-packages/polars/internals/frame.py", line 4479, in select
    self.lazy()
  File "/home/corey/.virtualenvs/PolarsIssue3.10/lib/python3.10/site-packages/polars/internals/lazy_frame.py", line 586, in collect
    return self._dataframe_class._from_pydf(ldf.collect())
pyo3_runtime.PanicException: Unwrapped panic from Python code
```
My hunch is that the underlying cause is the same (or similar to) the issue in this bug report - namely, attempting to include an empty list in a column of dtype `list [struct[2]]`.

**Comment by antonioalegria** [comment]
I'm getting the following error when trying to coalesce a list[struct[n]] column (`df.with_columns(pl.coalesce(pl.col(name), []).alias(name)`). Is it related to this?

polars.exceptions.ComputeError: If then else requires all arguments to have the same length (predicate = 10, lhs = 10, rhs = 1)
