### ISSUE TITLE
struct: is_in and arr.contains raise 'not implemented/valid' Exceptions

### ISSUE THREAD

**Issue by cbilot** [pola-rs/polars#3463]
polars 0.13.37+ (compiled through edc4dbd)
python 3.10.4
Linux Mint 20.3
#### Describe your bug.
The `is_in` and `arr.contains` methods raise an exception when trying to determine whether a list of structs contains a particular instance of a struct.

I'm including both `is_in` and `arr.contains` in the same bug report because the exception generated by `arr.contains` hints that it is wrapping an exception generated by calling `is_in`.
#### What are the steps to reproduce the behavior?
```python3
import polars as pl

df = pl.DataFrame({
    "struct_elem": [{"a": 1, "b": 11}],
    "struct_list": [
        [{"a": 1, "b": 11}, {"a": 2, "b": 12}, {"a": 3, "b": 13}],
    ],
})
df
```
```
shape: (1, 2)
┌─────────────┬──────────────────────────┐
│ struct_elem ┆ struct_list              │
│ ---         ┆ ---                      │
│ struct[2]   ┆ list [struct[2]]         │
╞═════════════╪══════════════════════════╡
│ {1,11}      ┆ [{1,11}, {2,12}, {3,13}] │
└─────────────┴──────────────────────────┘
```
#### `is_in`
```
>>> df.filter(pl.col("struct_elem").is_in('struct_list'))
thread '<unnamed>' panicked at 'this operation is not implemented/valid for this dtype: Struct([Field { name: "a", dtype: Int64 }, Field { name: "b", dtype: Int64 }])', /mnt/projects/polars/polars/polars-core/src/series/series_trait.rs:841:9
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/mnt/projects/polars/py-polars/polars/internals/frame.py", line 1954, in filter
    self.lazy()
  File "/mnt/projects/polars/py-polars/polars/internals/lazy_frame.py", line 586, in collect
    return self._dataframe_class._from_pydf(ldf.collect())
pyo3_runtime.PanicException: this operation is not implemented/valid for this dtype: Struct([Field { name: "a", dtype: Int64 }, Field { name: "b", dtype: Int64 }])
```
#### `arr.contains`
```
>> df.filter(pl.col("struct_list").arr.contains(pl.col('struct_elem')))
thread '<unnamed>' panicked at 'not implemented', /mnt/projects/polars/polars/polars-core/src/series/series_trait.rs:76:13
--- PyO3 is resuming a panic after fetching a PanicException from Python. ---
Python stack trace below:
Traceback (most recent call last):
  File "/mnt/projects/polars/py-polars/polars/internals/expr.py", line 3366, in <lambda>
    return wrap_expr(self._pyexpr).map(lambda s: s.arr.contains(item))
  File "/mnt/projects/polars/py-polars/polars/internals/series.py", line 4325, in contains
    out = s.is_in(s_list)
  File "/mnt/projects/polars/py-polars/polars/internals/series.py", line 1760, in is_in
    return wrap_s(self._s.is_in(other._s))
pyo3_runtime.PanicException: not implemented
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/mnt/projects/polars/py-polars/polars/internals/frame.py", line 1954, in filter
    self.lazy()
  File "/mnt/projects/polars/py-polars/polars/internals/lazy_frame.py", line 586, in collect
    return self._dataframe_class._from_pydf(ldf.collect())
pyo3_runtime.PanicException: Unwrapped panic from Python code
```
#### Other Notes
Presumably, traversing through a recursive data structure might involve searching through a list of structs to find a particular instance of a struct.

I waited to submit this bug until the issues with struct equality were settled.

**Comment by ritchie46** [comment]
Not implemented yet, so I rebrand it as a feature request. :)

**Comment by ritchie46** [comment]
Superseded by #3640
