### ISSUE TITLE
Some expressions fail in `empty_lazyframe.groupby().agg()`

### ISSUE THREAD

**Issue by mutecamel** [pola-rs/polars#3620]
#### What language are you using?

Python

#### What version of polars are you using?

0.13.44

#### What operating system are you using polars on?

macOS

#### What language version are you using

Python 3.10

#### Describe your bug.

Some expressions fail in `empty_lazyframe.groupby().agg()`

#### What are the steps to reproduce the behavior?

```python
import polars as pl


print("Version:", pl.__version__)


def mycalc(ldf: pl.LazyFrame) -> pl.LazyFrame:
    res = ldf.groupby("key").agg([pl.col("val").fill_null("mean").exp().sum()])
    return res


ldf = pl.DataFrame(
    [
        pl.Series("key", ["a", "b", "a"], dtype=pl.Categorical),
        pl.Series("val", [1, 2, 3], dtype=pl.Float64),
    ]
).lazy()
print(mycalc(ldf).collect())

ldf = pl.DataFrame(
    [
        pl.Series("key", [], dtype=pl.Categorical),
        pl.Series("val", [], dtype=pl.Float64),
    ]
).lazy()
print(mycalc(ldf).collect())
```

#### What is the actual behavior?

```
Version: 0.13.44
shape: (2, 2)
┌─────┬───────────┐
│ key ┆ val       │
│ --- ┆ ---       │
│ cat ┆ f64       │
╞═════╪═══════════╡
│ a   ┆ 22.803819 │  # <- correct result for non-empty frame
├╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌┤
│ b   ┆ 7.389056  │  # <- correct result for non-empty frame
└─────┴───────────┘
thread '<unnamed>' panicked at 'python apply failed: ', src/lazy/apply.rs:66:19
stack backtrace:
   0:        0x10ee9d546 - _ffi_select_with_compiled_path
   1:        0x10e1b90db - _BrotliDecoderVersion
   2:        0x10ee71e3c - _ffi_select_with_compiled_path
   3:        0x10ee9e63d - _ffi_select_with_compiled_path
   4:        0x10ee9f618 - _ffi_select_with_compiled_path
   5:        0x10ee9f104 - _ffi_select_with_compiled_path
   6:        0x10ee9f079 - _ffi_select_with_compiled_path
   7:        0x10ee9f035 - _ffi_select_with_compiled_path
   8:        0x10efca213 - _ffi_select_with_compiled_path
   9:        0x10d8a2617 - <unknown>
  10:        0x10d8a3389 - <unknown>
  11:        0x10d6e5a21 - <unknown>
  12:        0x10ebe10cf - _ffi_select_with_compiled_path
  13:        0x10ebc74ba - _ffi_select_with_compiled_path
  14:        0x10ec5d53f - _ffi_select_with_compiled_path
  15:        0x10ec5d0f9 - _ffi_select_with_compiled_path
  16:        0x10ec5cd3d - _ffi_select_with_compiled_path
  17:        0x10f0518b8 - _ffi_select_with_compiled_path
  18:        0x10edfaa3d - _ffi_select_with_compiled_path
  19:        0x10edfa590 - _ffi_select_with_compiled_path
  20:        0x10eea03ea - _ffi_select_with_compiled_path
  21:     0x7ff81bd6c4e1 - __pthread_start
Traceback (most recent call last):
  File "/Users/.../draft.py", line 26, in <module>
    print(mycalc(ldf).collect())
  File "/Users/.../.pyenv/versions/investo/lib/python3.10/site-packages/polars/internals/lazy_frame.py", line 591, in collect
    return self._dataframe_class._from_pydf(ldf.collect())
pyo3_runtime.PanicException: python apply failed:

```

#### What is the expected behavior?

I hope all expressions work for empty lazyframes as well. Thanks!

**Comment by ritchie46** [comment]
That are the numpy `__ufunc__`s. I gues we'd need to add an `expr` expression.
