### ISSUE TITLE
Concatenating two list Series creates a column of a different length

### ISSUE THREAD

**Issue by alecstein** [pola-rs/polars#3631]
#### What language are you using?

python

#### Have you tried latest version of polars?

yes

#### What version of polars are you using?

'0.13.43'

#### What operating system are you using polars on?

macOS Monterey 12.0.1 (21A559)

#### What language version are you using

python 3.9.10

#### Describe your bug.

Concatenating list series creates a new series of a different length

#### What are the steps to reproduce the behavior?

```
import polars as pl

pl.DataFrame({'a': [['a', 'b'], None, ['c', 'd', 'e'], None], 't':['x', 'y', None, None]}).with_column(
    pl.concat_list([col('t').apply(lambda s: [s]), col('a')])
)
```

#### What is the expected behavior?

Polars should just concatenate the two columns together without changing the lengths of the Series.

**Comment by cbilot** [comment]
Here's a temporary workaround.
```python3
(
    df.with_column(pl.col("t").apply(lambda s: [s]).alias("tmp_t"))
    .with_column(
        pl.when(pl.col("t").is_null())
        .then(pl.col("a"))
        .when(pl.col("a").is_null())
        .then(pl.col("tmp_t"))
        .otherwise(pl.col("a").arr.concat(pl.col("t")))
        .alias("result")
    )
    # .drop("tmp_t")
)
```
```
shape: (4, 4)
┌─────────────────┬──────┬───────────┬─────────────────┐
│ a               ┆ t    ┆ tmp_t     ┆ result          │
│ ---             ┆ ---  ┆ ---       ┆ ---             │
│ list[str]       ┆ str  ┆ list[str] ┆ list[str]       │
╞═════════════════╪══════╪═══════════╪═════════════════╡
│ ["a", "b"]      ┆ x    ┆ ["x"]     ┆ ["a", "b", "x"] │
├╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┤
│ null            ┆ y    ┆ ["y"]     ┆ ["y"]           │
├╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┤
│ ["c", "d", "e"] ┆ null ┆ null      ┆ ["c", "d", "e"] │
├╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┤
│ null            ┆ null ┆ null      ┆ null            │
└─────────────────┴──────┴───────────┴─────────────────┘
```
Oddly, the above does not work in lazy mode.
```python3
(
    df
    .lazy()
    .with_column(pl.col("t").apply(lambda s: [s]).alias("tmp_t"))
    .with_column(
        pl.when(pl.col("t").is_null())
        .then(pl.col("a"))
        .when(pl.col("a").is_null())
        .then(pl.col("tmp_t"))
        .otherwise(pl.col("a").arr.concat(pl.col("t")))
        .alias("result")
    )
    # .drop("tmp_t")
    .collect()
)
```
```
Traceback (most recent call last):
  File "<stdin>", line 14, in <module>
  File "/mnt/projects/polars/py-polars/polars/internals/lazy_frame.py", line 600, in collect
    return self._dataframe_class._from_pydf(ldf.collect())
exceptions.ComputeError: Cannot cast list type
```

One elegant solution would to create an empty list of string, and then use a `fold` method (along with `arr.concat`) to concatenate ... but oddly, I do not know how to create a column of empty List of string using `lit`.
