### ISSUE TITLE
[Python] How to properly set-up GraphViz for Mac or Windows?

### ISSUE THREAD

**Issue by jordan-carson** [pola-rs/polars#3692]
Hello, Polars,

I have asked this question on [SO](https://stackoverflow.com/questions/72608809/how-to-properly-set-up-graphviz-for-polars-on-mac-or-windows).

Trying to set-up graphviz for `df.show_graph()` however after adding graphviz and matplotlib locations to my path env var, I receive the follow error. 

```
Traceback (most recent call last):
  File "/Users/jordancarson/Projects/JHU/pract.py", line 24, in <module>
    print(res.show_graph(optimized=True))
  File "/Users/jordancarson/Projects/JHU/.venv/lib/python3.9/site-packages/polars/internals/lazy_frame.py", line 464, in show_graph
    subprocess.run(["dot", "-Nshape=box", "-Tpng", "-O", dot_path])
  File "/opt/homebrew/Cellar/python@3.9/3.9.13_1/Frameworks/Python.framework/Versions/3.9/lib/python3.9/subprocess.py", line 505, in run
    with Popen(*popenargs, **kwargs) as process:
  File "/opt/homebrew/Cellar/python@3.9/3.9.13_1/Frameworks/Python.framework/Versions/3.9/lib/python3.9/subprocess.py", line 951, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/opt/homebrew/Cellar/python@3.9/3.9.13_1/Frameworks/Python.framework/Versions/3.9/lib/python3.9/subprocess.py", line 1821, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'dot'
```

Getting closer, but still no cigar (🚬...).

Any advice or thoughts on how to get this to work? I have tried using [Issue GraphViz](https://github.com/WillKoehrsen/Data-Analysis/issues/36).

**Comment by jordan-carson** [comment]
I have followed this - which mentions to use MacPorts to install graphviz via `sudo apt install...`. The problem here is it installs on a different version of python that I do not use.

**Comment by ritchie46** [comment]
The conda package installer can often help a lot with this.

**Comment by slonik-az** [comment]
If you on Mac M1 try out `mamba` (faster drop-in `conda` replacement). Install `Graphviz` with
```
mamba install graphviz
```
and you well get `dot` and friends installed.

**Comment by jordan-carson** [comment]
👍 
Word. All good on M1 Mac - Conda is the easiest method here. TBD on Windows.
