### ISSUE TITLE
`pl.format` raises exception when frame is empty

### ISSUE THREAD

**Issue by mutecamel** [pola-rs/polars#3708]
#### What language are you using?

Python

#### What version of polars are you using?

0.13.46

#### What operating system are you using polars on?

macOS

#### What language version are you using

Python 3.10

#### Describe your bug.

`pl.format` raises exception when frame is empty

#### What are the steps to reproduce the behavior?

```python
import polars as pl


print("Version:", pl.__version__)


print("This works well:")
df = pl.DataFrame(
    [
        pl.Series("val1", ["a", "b"], dtype=pl.Categorical),
        pl.Series("val2", ["c", "d"], dtype=pl.Categorical),
    ]
).select(
    [
        "val1",
        "val2",
        pl.format("{}:{}", pl.col("val1"), pl.col("val2")).alias("cat"),
    ]
)
print(df)


print("But empty frame raises CumputeError:")
df = pl.DataFrame(
    [
        pl.Series("val1", [], dtype=pl.Categorical),
        pl.Series("val2", [], dtype=pl.Categorical),
    ]
).select(
    [
        "val1",
        "val2",
        pl.format("{}:{}", pl.col("val1"), pl.col("val2")).alias("cat"),
    ]
)
print(df)
```

#### What is the actual behavior?

```
Version: 0.13.46
This works well:
shape: (2, 3)
┌──────┬──────┬─────┐
│ val1 ┆ val2 ┆ cat │
│ ---  ┆ ---  ┆ --- │
│ cat  ┆ cat  ┆ str │
╞══════╪══════╪═════╡
│ a    ┆ c    ┆ a:c │
├╌╌╌╌╌╌┼╌╌╌╌╌╌┼╌╌╌╌╌┤
│ b    ┆ d    ┆ b:d │
└──────┴──────┴─────┘
But empty frame raises CumputeError:
Traceback (most recent call last):
  File "/Users/.../draft.py", line 29, in <module>
    ).select(
  File "/Users/.../.pyenv/versions/.../lib/python3.10/site-packages/polars/internals/frame.py", line 4678, in select
    self.lazy()
  File "/Users/.../.pyenv/versions/.../lib/python3.10/site-packages/polars/internals/lazy_frame.py", line 622, in collect
    return self._dataframe_class._from_pydf(ldf.collect())
exceptions.ComputeError: all series in concat_str function should have equal length or unit length
```

#### What is the expected behavior?

When frame is empty, I hope `pl.format` produce empty str series, instead of an exception. Thanks!

**Comment by Vitotian** [comment]
`[[]]` instead of `[]` 
```python
In [1]: import polars as pl
   ...: 
   ...: df = pl.DataFrame(
   ...:     [
   ...:         pl.Series("val1", [[]], dtype=pl.Categorical),
   ...:         pl.Series("val2", [[]], dtype=pl.Categorical),
   ...:     ]
   ...: ).select(
   ...:     [
   ...:         "val1",
   ...:         "val2",
   ...:         pl.format("{}:{}", pl.col("val1"), pl.col("val2")).alias("cat"),
   ...: 
   ...:     ]
   ...: )
   ...: print(df)
shape: (1, 3)
┌──────┬──────┬──────┐
│ val1 ┆ val2 ┆ cat  │
│ ---  ┆ ---  ┆ ---  │
│ cat  ┆ cat  ┆ str  │
╞══════╪══════╪══════╡
│ null ┆ null ┆ null │
└──────┴──────┴──────┘
```

**Comment by mutecamel** [comment]
I mean the case of an empty dataframe, not a frame of one row of nulls.

**Comment by mutecamel** [comment]
I just expect the same code works for both non-empty and empty frame, rather than raising exception when frame is empty.

Strictly speaking, when frame is empty, we are passing `pl.format` empty series as arguments. Their length are equal in fact, namely zero.
