### ISSUE TITLE
Fail to concat/vstack u16 column

### ISSUE THREAD

**Issue by mutecamel** [pola-rs/polars#3735]
#### What language are you using?

Python

#### Have you tried latest version of polars?

yes

#### What version of polars are you using?

0.13.47

#### What operating system are you using polars on?

macOS

#### What language version are you using

Python 3.10

#### Describe your bug.

Fail to concat/vstack u16 column

#### What are the steps to reproduce the behavior?

```python
import polars as pl


print("Version:", pl.__version__)


d1 = pl.DataFrame(
    [
        pl.Series("key", ["a", "b"], dtype=pl.Categorical),
        pl.Series("val", [1, 2], dtype=pl.UInt16),
    ]
)
d2 = pl.DataFrame(
    [
        pl.Series("key", ["a", "b"], dtype=pl.Categorical),
        pl.Series("val", [3, 4], dtype=pl.UInt16),
    ]
)
df = pl.concat([d1, d2])
print(df)
```

#### What is the actual behavior?

```
Version: 0.13.47
Traceback (most recent call last):
  File "/Users/.../draft.py", line 19, in <module>
    df = pl.concat([d1, d2])
  File "/Users/.../.pyenv/versions/.../lib/python3.10/site-packages/polars/internals/functions.py", line 124, in concat
    out = pli.wrap_df(_concat_df(items))
exceptions.SchemaError: cannot vstack: because column datatypes (dtypes) in the two DataFrames do not match for left.name='val' with left.dtype=i32 != right.dtype=u16 with right.name='val'
```

#### What is the expected behavior?

This is a regression. Above code works well in previous versions.

**Comment by ritchie46** [comment]
Thanks for the report. I will fix it.

**Comment by arturdaraujo** [comment]
I'm still having issue with pl.concat. It's quite often that pl.concat can't combine different dtypes, like float64 and int64. 

```
exceptions.SchemaError: cannot vstack: because column datatypes (dtypes) in the two DataFrames do not match for left.name='PaymentsForRepurchaseOfCommonStock' with left.dtype=f64 != right.dtype=i64 with right.name='PaymentsForRepurchaseOfCommonStock'
```
```
---Version info---
Polars: 0.16.11
Index type: UInt32
Platform: Linux-5.15.90.1-microsoft-standard-WSL2-x86_64-with-glibc2.35
Python: 3.10.8 | packaged by conda-forge | (main, Nov 22 2022, 08:23:14) [GCC 10.4.0]
---Optional dependencies---
pyarrow: 7.0.0
pandas: 1.5.3
numpy: 1.23.5
fsspec: 2023.1.0
connectorx: <not installed>
xlsx2csv: <not installed>
deltalake: <not installed>
matplotlib: 3.6.3
```
