### ISSUE TITLE
Multi-column `is_duplicated` expression

### ISSUE THREAD

**Issue by mutecamel** [pola-rs/polars#3803]
#### Describe your feature request

When I need to filter duplicated (on a subset of columns) rows of a dataframe, I can use the following code

```python
import polars as pl


print("Version:", pl.__version__)


df = pl.DataFrame(
    [
        pl.Series("key1", ["a", "b", "a", "b", "a"], dtype=pl.Categorical),
        pl.Series("key2", [6, 7, 8, 9, 6]),
        pl.Series("val", [1, 2, 3, 4, 5]),
    ]
)
print(df)

df1 = df[df[["key1", "key2"]].is_duplicated()]
print(df1)
```

```
Version: 0.13.49
shape: (5, 3)
┌──────┬──────┬─────┐
│ key1 ┆ key2 ┆ val │
│ ---  ┆ ---  ┆ --- │
│ cat  ┆ i64  ┆ i64 │
╞══════╪══════╪═════╡
│ a    ┆ 6    ┆ 1   │  # <- duplicated in (key1, key2)
├╌╌╌╌╌╌┼╌╌╌╌╌╌┼╌╌╌╌╌┤
│ b    ┆ 7    ┆ 2   │
├╌╌╌╌╌╌┼╌╌╌╌╌╌┼╌╌╌╌╌┤
│ a    ┆ 8    ┆ 3   │
├╌╌╌╌╌╌┼╌╌╌╌╌╌┼╌╌╌╌╌┤
│ b    ┆ 9    ┆ 4   │
├╌╌╌╌╌╌┼╌╌╌╌╌╌┼╌╌╌╌╌┤
│ a    ┆ 6    ┆ 5   │  # <- duplicated in (key1, key2)
└──────┴──────┴─────┘
shape: (2, 3)
┌──────┬──────┬─────┐
│ key1 ┆ key2 ┆ val │
│ ---  ┆ ---  ┆ --- │
│ cat  ┆ i64  ┆ i64 │
╞══════╪══════╪═════╡
│ a    ┆ 6    ┆ 1   │
├╌╌╌╌╌╌┼╌╌╌╌╌╌┼╌╌╌╌╌┤
│ a    ┆ 6    ┆ 5   │
└──────┴──────┴─────┘
```

But for lazyframe, similar computation (using expression) is currently impossible (as far as I know). Though there is an `Expr.is_duplicated()` expression, its scope is only a single column, not allowing for multiple columns.

I tried to pack the two columns into a struct column (not possible to concat to a list, because dtypes are different), then use `.is_duplicated()`, but this is not supported currently.

```python
import polars as pl


ldf = pl.DataFrame(
    [
        pl.Series("key1", ["a", "b", "a", "b", "a"], dtype=pl.Categorical),
        pl.Series("key2", [6, 7, 8, 9, 6]),
        pl.Series("val", [1, 2, 3, 4, 5]),
    ]
).lazy()

ldf1 = ldf.with_column(pl.struct(["key1", "key2"]).alias("mkey"))
print(ldf1.collect())

ldf2 = ldf1.filter(pl.col("mkey").is_duplicated())
print(ldf2.collect())  # <- will raise PanicException
```

```
shape: (5, 4)
┌──────┬──────┬─────┬───────────┐
│ key1 ┆ key2 ┆ val ┆ mkey      │
│ ---  ┆ ---  ┆ --- ┆ ---       │
│ cat  ┆ i64  ┆ i64 ┆ struct[2] │
╞══════╪══════╪═════╪═══════════╡
│ a    ┆ 6    ┆ 1   ┆ {"a",6}   │
├╌╌╌╌╌╌┼╌╌╌╌╌╌┼╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌┤
│ b    ┆ 7    ┆ 2   ┆ {"b",7}   │
├╌╌╌╌╌╌┼╌╌╌╌╌╌┼╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌┤
│ a    ┆ 8    ┆ 3   ┆ {"a",8}   │
├╌╌╌╌╌╌┼╌╌╌╌╌╌┼╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌┤
│ b    ┆ 9    ┆ 4   ┆ {"b",9}   │
├╌╌╌╌╌╌┼╌╌╌╌╌╌┼╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌┤
│ a    ┆ 6    ┆ 5   ┆ {"a",6}   │
└──────┴──────┴─────┴───────────┘
thread '<unnamed>' panicked at 'this operation is not implemented/valid for this dtype: Struct([Field { name: "key1", dtype: Categorical(Some(Local(LargeUtf8Array[a, b]))) }, Field { name: "key2", dtype: Int64 }])', /Users/runner/work/polars/polars/polars/polars-core/src/series/series_trait.rs:484:9
stack backtrace:
   0:        0x10caddbd6 - _ffi_select_with_compiled_path
   1:        0x10bda3b1b - _BrotliDecoderVersion
   2:        0x10cab24cc - _ffi_select_with_compiled_path
   3:        0x10cadeccd - _ffi_select_with_compiled_path
   4:        0x10cadfca8 - _ffi_select_with_compiled_path
   5:        0x10cadf794 - _ffi_select_with_compiled_path
   6:        0x10cadf709 - _ffi_select_with_compiled_path
   7:        0x10cadf6c5 - _ffi_select_with_compiled_path
   8:        0x10cc0c7b3 - _ffi_select_with_compiled_path
   9:        0x10bfb2a0e - _ffi_select_with_compiled_path
  10:        0x10c7c03d1 - _ffi_select_with_compiled_path
  11:        0x10c80f194 - _ffi_select_with_compiled_path
  12:        0x10c836f08 - _ffi_select_with_compiled_path
  13:        0x10c82deb9 - _ffi_select_with_compiled_path
  14:        0x10b7b398a - _PyInit_polars
  15:        0x108a6e22d - _method_vectorcall_VARARGS_KEYWORDS
  16:        0x108b524dc - _call_function
  17:        0x108b4f562 - __PyEval_EvalFrameDefault
  18:        0x108b48721 - __PyEval_Vector
  19:        0x108b524dc - _call_function
  20:        0x108b4f562 - __PyEval_EvalFrameDefault
  21:        0x108b48721 - __PyEval_Vector
  22:        0x108b48671 - _PyEval_EvalCode
  23:        0x108b9baeb - __PyRun_SimpleFileObject
  24:        0x108b9b59e - __PyRun_AnyFileObject
  25:        0x108bbc0db - _Py_RunMain
  26:        0x108bbc5e3 - _pymain_main
  27:        0x108bbc63b - _Py_BytesMain
Traceback (most recent call last):
  File "/Users/.../draft2.py", line 19, in <module>
    print(ldf2.collect())  # <- will raise PanicException
  File "/Users/.../.pyenv/versions/.../lib/python3.10/site-packages/polars/internals/lazy_frame.py", line 622, in collect
    return self._dataframe_class._from_pydf(ldf.collect())
pyo3_runtime.PanicException: this operation is not implemented/valid for this dtype: Struct([Field { name: "key1", dtype: Categorical(Some(Local(LargeUtf8Array[a, b]))) }, Field { name: "key2", dtype: Int64 }])
```

I wish there would be a module level expression `is_duplicated([subset])`

```python
polars.is_duplicated(
    subset: Optional[Union[str, List[polars.internals.expr.Expr]]] = None
) → polars.internals.expr.Expr
```

which will evaluate to true if the `subset` of expressions have duplicate values, or false otherwise. If `subset` is default None, it means all columns in the lazyframe. Then the problem would be solved with following code

```python
import polars as pl


ldf = pl.DataFrame(
    [
        pl.Series("key1", ["a", "b", "a", "b", "a"], dtype=pl.Categorical),
        pl.Series("key2", [6, 7, 8, 9, 6]),
        pl.Series("val", [1, 2, 3, 4, 5]),
    ]
).lazy()

df1 = ldf.filter(pl.is_duplicated(["key1", "key2"])).collect()
print(df1)
```

```
Traceback (most recent call last):
  File "/Users/.../draft.py", line 15, in <module>
    df1 = ldf.filter(pl.is_duplicated(["key1", "key2"])).collect()
AttributeError: module 'polars' has no attribute 'is_duplicated'
```

What do you think? Thanks in advance.

**Comment by ritchie46** [comment]
I believe LazyFrame has a unique method. That also accepts a subset.

**Comment by mutecamel** [comment]
Yes, but how can one use `.unique()` to locate duplicate rows in a lazyframe?

**Comment by ritchie46** [comment]
> Yes, but how can one use `.unique()` to locate duplicate rows in a lazyframe?

You only wanted to filter them right? Unique does that.

**Comment by mutecamel** [comment]
No. I want the the _duplicate_ (on subset of columns) rows, not the unique rows. In above code examples, I think I am clear enough.

**Comment by mutecamel** [comment]
I found a way to solve it! I can count rows over the subset of columns, and filter by the counts.

```python
import polars as pl

ldf = pl.DataFrame(
    [
        pl.Series("key1", ["a", "b", "a", "b", "a"], dtype=pl.Categorical),
        pl.Series("key2", [6, 7, 8, 9, 6]),
        pl.Series("val", [1, 2, 3, 4, 5]),
    ]
).lazy()
print(ldf.collect())

ldf = ldf.filter(pl.count().over(["key1", "key2"]) > 1)
print(ldf.collect())
```

```
shape: (5, 3)
┌──────┬──────┬─────┐
│ key1 ┆ key2 ┆ val │
│ ---  ┆ ---  ┆ --- │
│ cat  ┆ i64  ┆ i64 │
╞══════╪══════╪═════╡
│ a    ┆ 6    ┆ 1   │
├╌╌╌╌╌╌┼╌╌╌╌╌╌┼╌╌╌╌╌┤
│ b    ┆ 7    ┆ 2   │
├╌╌╌╌╌╌┼╌╌╌╌╌╌┼╌╌╌╌╌┤
│ a    ┆ 8    ┆ 3   │
├╌╌╌╌╌╌┼╌╌╌╌╌╌┼╌╌╌╌╌┤
│ b    ┆ 9    ┆ 4   │
├╌╌╌╌╌╌┼╌╌╌╌╌╌┼╌╌╌╌╌┤
│ a    ┆ 6    ┆ 5   │
└──────┴──────┴─────┘
shape: (2, 3)
┌──────┬──────┬─────┐
│ key1 ┆ key2 ┆ val │
│ ---  ┆ ---  ┆ --- │
│ cat  ┆ i64  ┆ i64 │
╞══════╪══════╪═════╡
│ a    ┆ 6    ┆ 1   │
├╌╌╌╌╌╌┼╌╌╌╌╌╌┼╌╌╌╌╌┤
│ a    ┆ 6    ┆ 5   │
└──────┴──────┴─────┘
```

Then no need to add one more API. Current APIs are elegant. Thank you!
