### ISSUE TITLE
Make pl.DataType (and children) not callable

### ISSUE THREAD

**Issue by thomasaarholt** [pola-rs/polars#3819]
I just went down a rabbit hole trying to figure out what I had missed when casting floats to integers. Here's a MWE:

```python
(
    pl.DataFrame(
        {"a":[1.0, 2.0, 3.0]}
        )
        .with_column(
            pl.col('a')
            .cast(
                pl.Int64()
                )
            )
)
```
The above code raises this error::
`thread '<unnamed>' panicked at 'Int64 not expected in Python dtype to Rust dtype conversion', src/conversion.rs:397:17`

This was after using a custom python function via `.map`, so I assumed there was something wrong with the data type returned by my python function. 

Turns out I was _calling_ the `pl.Int64` class... This was caused by VSCode being "helpful" in autocompleting parentheses for me.

Since it panics anyway, it would be nice if we prevented pl.DataType and its children from being callable (at least in this context).

Full panic:

```python
---------------------------------------------------------------------------
PanicException                            Traceback (most recent call last)
/Users/thomas/oda/fabrica/projects/kaggle-amex/amex.ipynb Cell 7' in <cell line: 2>()
      [1](vscode-notebook-cell:/Users/thomas/oda/fabrica/projects/kaggle-amex/amex.ipynb#ch0000037?line=0) (
      [2](vscode-notebook-cell:/Users/thomas/oda/fabrica/projects/kaggle-amex/amex.ipynb#ch0000037?line=1)     pl.DataFrame(
      [3](vscode-notebook-cell:/Users/thomas/oda/fabrica/projects/kaggle-amex/amex.ipynb#ch0000037?line=2)         {"a":[1.0, 2.0, 3.0]}
      [4](vscode-notebook-cell:/Users/thomas/oda/fabrica/projects/kaggle-amex/amex.ipynb#ch0000037?line=3)         )
      [5](vscode-notebook-cell:/Users/thomas/oda/fabrica/projects/kaggle-amex/amex.ipynb#ch0000037?line=4)         .with_column(
      [6](vscode-notebook-cell:/Users/thomas/oda/fabrica/projects/kaggle-amex/amex.ipynb#ch0000037?line=5)             pl.col('a')
----> [7](vscode-notebook-cell:/Users/thomas/oda/fabrica/projects/kaggle-amex/amex.ipynb#ch0000037?line=6)             .cast(
      [8](vscode-notebook-cell:/Users/thomas/oda/fabrica/projects/kaggle-amex/amex.ipynb#ch0000037?line=7)                 pl.Int64()
      [9](vscode-notebook-cell:/Users/thomas/oda/fabrica/projects/kaggle-amex/amex.ipynb#ch0000037?line=8)                 )
     [10](vscode-notebook-cell:/Users/thomas/oda/fabrica/projects/kaggle-amex/amex.ipynb#ch0000037?line=9)             )
     [11](vscode-notebook-cell:/Users/thomas/oda/fabrica/projects/kaggle-amex/amex.ipynb#ch0000037?line=10) )

File ~/mambaforge/envs/kaggle/lib/python3.10/site-packages/polars/internals/expr.py:1013, in Expr.cast(self, dtype, strict)
    978 """
    979 Cast between data types.
    980 
   (...)
   1010 
   1011 """
   1012 dtype = py_type_to_dtype(dtype)
-> 1013 return wrap_expr(self._pyexpr.cast(dtype, strict))

PanicException: Int64 not expected in Python dtype to Rust dtype conversion
```

**Comment by thomasaarholt** [comment]
The error if one calls `pl.Int64` outside of `.cast` is a bit different for reasons I don't understand:

```python
>>> pl.Int64

thread '<unnamed>' panicked at 'Int64 not expected in Python dtype to Rust dtype conversion', src/conversion.rs:397:17
---------------------------------------------------------------------------
PanicException                            Traceback (most recent call last)
/Users/thomas/oda/fabrica/projects/kaggle-amex/amex.ipynb Cell 8' in <cell line: 1>()
----> [1](vscode-notebook-cell:/Users/thomas/oda/fabrica/projects/kaggle-amex/amex.ipynb#ch0000041?line=0) pl.Int64()

File ~/mambaforge/envs/kaggle/lib/python3.10/site-packages/IPython/core/displayhook.py:262, in DisplayHook.__call__(self, result)
    260 self.start_displayhook()
    261 self.write_output_prompt()
--> 262 format_dict, md_dict = self.compute_format_data(result)
    263 self.update_user_ns(result)
    264 self.fill_exec_result(result)

File ~/mambaforge/envs/kaggle/lib/python3.10/site-packages/IPython/core/displayhook.py:151, in DisplayHook.compute_format_data(self, result)
    121 def compute_format_data(self, result):
    122     """Compute format data of the object to be displayed.
    123 
    124     The format data is a generalization of the :func:`repr` of an object.
   (...)
    149 
    150     """
--> 151     return self.shell.display_formatter.format(result)

File ~/mambaforge/envs/kaggle/lib/python3.10/site-packages/IPython/core/formatters.py:178, in DisplayFormatter.format(self, obj, include, exclude)
    176 md = None
    177 try:
--> 178     data = formatter(obj)
    179 except:
    180     # FIXME: log the exception
    181     raise

File ~/mambaforge/envs/kaggle/lib/python3.10/site-packages/decorator.py:232, in decorate.<locals>.fun(*args, **kw)
    230 if not kwsyntax:
    231     args, kw = fix(args, kw, sig)
--> 232 return caller(func, *(extras + args), **kw)

File ~/mambaforge/envs/kaggle/lib/python3.10/site-packages/IPython/core/formatters.py:222, in catch_format_error(method, self, *args, **kwargs)
    220 """show traceback on failed format call"""
    221 try:
--> 222     r = method(self, *args, **kwargs)
    223 except NotImplementedError:
    224     # don't warn on NotImplementedErrors
    225     return self._check_return(None, args[0])

File ~/mambaforge/envs/kaggle/lib/python3.10/site-packages/IPython/core/formatters.py:707, in PlainTextFormatter.__call__(self, obj)
    700 stream = StringIO()
    701 printer = pretty.RepresentationPrinter(stream, self.verbose,
    702     self.max_width, self.newline,
    703     max_seq_length=self.max_seq_length,
    704     singleton_pprinters=self.singleton_printers,
    705     type_pprinters=self.type_printers,
    706     deferred_pprinters=self.deferred_printers)
--> 707 printer.pretty(obj)
    708 printer.flush()
    709 return stream.getvalue()

File ~/mambaforge/envs/kaggle/lib/python3.10/site-packages/IPython/lib/pretty.py:410, in RepresentationPrinter.pretty(self, obj)
    407                         return meth(obj, self, cycle)
    408                 if cls is not object \
    409                         and callable(cls.__dict__.get('__repr__')):
--> 410                     return _repr_pprint(obj, self, cycle)
    412     return _default_pprint(obj, self, cycle)
    413 finally:

File ~/mambaforge/envs/kaggle/lib/python3.10/site-packages/IPython/lib/pretty.py:778, in _repr_pprint(obj, p, cycle)
    776 """A pprint that just redirects to the normal repr function."""
    777 # Find newlines and replace them with p.break_()
--> 778 output = repr(obj)
    779 lines = output.splitlines()
    780 with p.group():

File ~/mambaforge/envs/kaggle/lib/python3.10/site-packages/polars/datatypes.py:31, in DataType.__repr__(self)
     30 def __repr__(self) -> str:
---> 31     return dtype_str_repr(self)

PanicException: Int64 not expected in Python dtype to Rust dtype conversion

``
`

**Comment by ritchie46** [comment]
We could raise an error if you instantiate those objects. That should make the wrong use more clear.

**Comment by thomasaarholt** [comment]
I think that is the easiest way to make it clear to end users :)

**Comment by alexander-beedie** [comment]
Thought about doing something with `__call__` (and deleted the comment), but then realized it was the right idea, but the wrong dunder-method.  The right place is `__new__`... Can make all of the DataType uses behave consistently like so:

```python
class DataType:
    """Base class for all Polars data types"""

    def __new__( cls, *args, **kwargs ):
        if args or kwargs:
            return super().__new__(cls)
        return cls
    //...
```

This means that you will _always_ get the "right" type, whether you think you are initializing or not. It also preserves the behavior of those types that DO require initializing (eg: `Datetime` or `Duration` types with time units).

With the above tweak:
 
```python
pl.Int64    is pl.Int64()        => True    # 'surprise'  ;)
pl.Datetime is pl.Datetime("us") => False
```

In essence you now _can't_ provide the wrong object to downstream function; if you try you just get the right object. 

Thoughts?

**Comment by ghuls** [comment]
I was looking in to it to do the same as I also noticed that some types are initialized.

Support for creating int/float literal of a specific type could be nice too instead of pl.lit: pl.Int32(768)

**Comment by alexander-beedie** [comment]
Hmm, not sure I agree on initialising literals using column/schema typedefs, as it's an odd mix of responsibilities. As they say in Ghostbusters: "you never cross the streams" :)

**Comment by alexander-beedie** [comment]
@thomasaarholt: if https://github.com/pola-rs/polars/pull/3857 is suitable, can close the issue? thx :)

**Comment by thomasaarholt** [comment]
Yes, I think that's a nice solution. Nice handling of the handling of init params!
