### ISSUE TITLE
Unstable computation when combining multiple window expressions

### ISSUE THREAD

**Issue by mutecamel** [pola-rs/polars#3839]
#### What language are you using?

Python

#### What operating system are you using polars on?

macOS

#### What language version are you using

Python 3.10

#### What are the steps to reproduce the behavior?

This is hard to notice, because the error occurs randomly. To reproduce it, I choose to repeat the same code 100 times.

```python
import polars as pl

print(pl.__version__)

ldf = (
    pl.DataFrame(
        [
            pl.Series("key", ["a", "a", "b", "b"]),
            pl.Series("val", [2, 2, 1, 3]),
        ]
    )
    .lazy()
    .filter(
        (pl.col("key").cumcount().over("key") == 0)
        | (pl.col("val").shift(1).over("key").is_not_null())
        | (pl.col("val") != pl.col("val").shift(1).over("key"))
    )
)
for i in range(100):
    print(i)
    print(ldf.collect())
```

Note this is the minimalist example. Removing any one of the three `.over()` window expression, you won't see the error. I don't know the reason, but I relies on window expressions heavily.

#### What is the actual behavior?

```
0.13.50
0  # <- correct
shape: (4, 2)
┌─────┬─────┐
│ key ┆ val │
│ --- ┆ --- │
│ str ┆ i64 │
╞═════╪═════╡
│ a   ┆ 2   │
├╌╌╌╌╌┼╌╌╌╌╌┤
│ a   ┆ 2   │
├╌╌╌╌╌┼╌╌╌╌╌┤
│ b   ┆ 1   │
├╌╌╌╌╌┼╌╌╌╌╌┤
│ b   ┆ 3   │
└─────┴─────┘
1  # <- correct
shape: (4, 2)
┌─────┬─────┐
│ key ┆ val │
│ --- ┆ --- │
│ str ┆ i64 │
╞═════╪═════╡
│ a   ┆ 2   │
├╌╌╌╌╌┼╌╌╌╌╌┤
│ a   ┆ 2   │
├╌╌╌╌╌┼╌╌╌╌╌┤
│ b   ┆ 1   │
├╌╌╌╌╌┼╌╌╌╌╌┤
│ b   ┆ 3   │
└─────┴─────┘
2  # <- correct
shape: (4, 2)
┌─────┬─────┐
│ key ┆ val │
│ --- ┆ --- │
│ str ┆ i64 │
╞═════╪═════╡
│ a   ┆ 2   │
├╌╌╌╌╌┼╌╌╌╌╌┤
│ a   ┆ 2   │
├╌╌╌╌╌┼╌╌╌╌╌┤
│ b   ┆ 1   │
├╌╌╌╌╌┼╌╌╌╌╌┤
│ b   ┆ 3   │
└─────┴─────┘
.
.
.
8  # <- correct
shape: (4, 2)
┌─────┬─────┐
│ key ┆ val │
│ --- ┆ --- │
│ str ┆ i64 │
╞═════╪═════╡
│ a   ┆ 2   │
├╌╌╌╌╌┼╌╌╌╌╌┤
│ a   ┆ 2   │
├╌╌╌╌╌┼╌╌╌╌╌┤
│ b   ┆ 1   │
├╌╌╌╌╌┼╌╌╌╌╌┤
│ b   ┆ 3   │
└─────┴─────┘
9  # <- randomly wrong
Traceback (most recent call last):
  File "/Users/.../draft.py", line 21, in <module>
    print(ldf.collect())
  File "/Users/.../.pyenv/versions/.../lib/python3.10/site-packages/polars/internals/lazy_frame.py", line 622, in collect
    return self._dataframe_class._from_pydf(ldf.collect())
exceptions.ComputeError: the length of the window expression did not match that of the group
```

#### What is the expected behavior?

Stable the window expression calculations. Please! Thank you for your awesome work!

**Comment by mutecamel** [comment]
MacBook Pro (Retina, 13-inch, Early 2015), 2.7 GHz Dual-Core Intel Core i5

**Comment by mutecamel** [comment]
I've just tested the same code on an Ubuntu 20.04 machine with 8 core Intel(R) Xeon(R) W-2123 CPU. It still occurs, randomly.
But on Ubuntu, the process hangs, instead of raising `ComputeError`. I have to manually kill the process.

**Comment by ritchie46** [comment]
Been able to reproduce it on 2 cores. :+1:
