### ISSUE TITLE
Python polars is not support in Pycharm

### ISSUE THREAD

**Issue by josemou8** [pola-rs/polars#3870]
polars version: 0.13.51
python 3.9.1

**Example**

```python
import polars as pl
import pandas as pd
import pyarrow

df = pd.DataFrame({
    "a": [1, 2, 3],
    "b": [4, 5, 6], 
    "c": [7, 8, 9]
})

df.to_excel(r"./test.xlsx", index=False)

df_pl = pl.read_excel(r"./test.xlsx")
```

it reports errors when i read local excelfile,
but it works in jupyter and vscode.

I perfer to use pycharm in my work,so is it possible to fix this error?

```
Traceback (most recent call last):
  File "D:\Python\lib\site-packages\polars\internals\frame.py", line 1585, in __getattr__
    return pli.wrap_s(self._df.column(item))
exceptions.NotFoundError: axes
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "D:\Pycharm\PyCharm Community Edition 2021.3.1\plugins\python-ce\helpers\pydev\_pydev_bundle\pydev_console_utils.py", line 216, in getArray
    return pydevd_thrift.table_like_struct_to_thrift_struct(array, name, roffset, coffset, rows, cols, format)
  File "D:\Pycharm\PyCharm Community Edition 2021.3.1\plugins\python-ce\helpers\pydev\_pydevd_bundle\pydevd_thrift.py", line 625, in table_like_struct_to_thrift_struct
    return TYPE_TO_THRIFT_STRUCT_CONVERTERS[type_name](array, name, roffset, coffset, rows, cols, format)
  File "D:\Pycharm\PyCharm Community Edition 2021.3.1\plugins\python-ce\helpers\pydev\_pydevd_bundle\pydevd_thrift.py", line 496, in dataframe_to_thrift_struct
    dim = len(df.axes)
  File "D:\Python\lib\site-packages\polars\internals\frame.py", line 1587, in __getattr__
    raise AttributeError(item)
AttributeError: axes
```

**Comment by cbilot** [comment]
PyCharm support for Polars has been requested on JetBrains. 

https://youtrack.jetbrains.com/issue/PY-50861

**Comment by ritchie46** [comment]
I will close this as there is not something we can do.
