### ISSUE TITLE
Polars `scan_parquet` panics given a parquet with arrays/lists.

### ISSUE THREAD

**Issue by andrei-ionescu** [pola-rs/polars#3886]
#### What language are you using?

**Rust**

#### Which feature gates did you use?

`"polars-io", "parquet", "lazy"`

#### Have you tried latest version of polars?

- [yes]

#### What version of polars are you using?

`0.22.8`

#### What operating system are you using polars on?

macOS Monterey 12.3.1

#### What language version are you using

```
$ rustc --version
rustc 1.64.0-nightly (495b21669 2022-07-03)

$ cargo --version
cargo 1.64.0-nightly (dbff32b27 2022-06-24)
```

#### Describe your bug.

Polars `scan_parquet` panics given a parquet with arrays/lists.

#### What are the steps to reproduce the behavior?

Given the attached parquet file: [nested_struct.snappy.parquet.zip](https://github.com/pola-rs/polars/files/9038859/nested_struct.snappy.parquet.zip)

That has the following schema as output by `parquet-tools` is:

```
message spark_schema {
  optional group item (LIST) {
    repeated group list {
      optional group element {
        optional binary sku (STRING);
        optional group exp {
          optional group analytics {
            optional group dims {
              optional group vars {
                optional binary v90 (STRING);
                optional binary v91 (STRING);
              }
            }
          }
        }
        optional int32 quantity;
        optional double total;
      }
    }
  }
}
```

The following code:

```
let df = LazyFrame::scan_parquet(
        "nested_struct.snappy.parquet".into(),
        ScanArgsParquet::default(),
    )?
    .select([all()])
    .collect()?;
```

does panic and exits.

#### What is the actual behavior?

It does panic with:

```
thread 'main' panicked at 'Arrow datatype Struct([Field { name: "sku", data_type: Utf8, is_nullable: true, metadata: {} }, 
Field { name: "exp", data_type: Struct([Field { name: "analytics", data_type: Struct([Field { name: "dims", data_type: 
Struct([Field { name: "vars", data_type: Struct([Field { name: "v90", data_type: Utf8, is_nullable: true, metadata: {} }, 
Field { name: "v91", data_type: Utf8, is_nullable: true, metadata: {} }]), is_nullable: true, metadata: {} }]), is_nullable: true, 
metadata: {} }]), is_nullable: true, metadata: {} }]), is_nullable: true, metadata: {} }, Field { name: "quantity", data_type: Int32,
is_nullable: true, metadata: {} }, Field { name: "total", data_type: Float64, is_nullable: true, metadata: {} }]) not supported 
by Polars', /.../.cargo/registry/src/github.com-1ecc6299db9ec823/polars-core-0.22.7/src/datatypes.rs:1033:19
stack backtrace:
   0: rust_begin_unwind
             at /rustc/495b216696ccbc27c73d6bdc486bf4621d610f4b/library/std/src/panicking.rs:584:5
   1: core::panicking::panic_fmt
             at /rustc/495b216696ccbc27c73d6bdc486bf4621d610f4b/library/core/src/panicking.rs:142:14
   2: <polars_core::datatypes::DataType as core::convert::From<&arrow2::datatypes::DataType>>::from
             at /Users/aionescu/.cargo/registry/src/github.com-1ecc6299db9ec823/polars-core-0.22.7/src/datatypes.rs:1033:19
   3: <T as core::convert::Into<U>>::into
             at /rustc/495b216696ccbc27c73d6bdc486bf4621d610f4b/library/core/src/convert/mod.rs:550:9
   4: <polars_core::datatypes::DataType as core::convert::From<&arrow2::datatypes::DataType>>::from
             at /Users/aionescu/.cargo/registry/src/github.com-1ecc6299db9ec823/polars-core-0.22.7/src/datatypes.rs:1008:63
   5: <T as core::convert::Into<U>>::into
             at /rustc/495b216696ccbc27c73d6bdc486bf4621d610f4b/library/core/src/convert/mod.rs:550:9
   6: <polars_core::datatypes::Field as core::convert::From<&arrow2::datatypes::field::Field>>::from
             at /Users/aionescu/.cargo/registry/src/github.com-1ecc6299db9ec823/polars-core-0.22.7/src/datatypes.rs:1040:29
   7: <T as core::convert::Into<U>>::into
             at /rustc/495b216696ccbc27c73d6bdc486bf4621d610f4b/library/core/src/convert/mod.rs:550:9
   8: <polars_core::schema::Schema as core::convert::From<I>>::from
             at /Users/aionescu/.cargo/registry/src/github.com-1ecc6299db9ec823/polars-core-0.22.7/src/schema.rs:38:23
   9: <T as core::convert::Into<U>>::into
             at /rustc/495b216696ccbc27c73d6bdc486bf4621d610f4b/library/core/src/convert/mod.rs:550:9
  10: polars_io::parquet::read::ParquetReader<R>::schema
             at /Users/aionescu/.cargo/registry/src/github.com-1ecc6299db9ec823/polars-io-0.22.7/src/parquet/read.rs:93:12
  11: polars_lazy::logical_plan::builder::LogicalPlanBuilder::scan_parquet
             at /Users/aionescu/.cargo/registry/src/github.com-1ecc6299db9ec823/polars-lazy-0.22.7/src/logical_plan/builder.rs:99:31
  12: polars_lazy::frame::parquet::<impl polars_lazy::frame::LazyFrame>::scan_parquet_impl
             at /Users/aionescu/.cargo/registry/src/github.com-1ecc6299db9ec823/polars-lazy-0.22.7/src/frame/parquet.rs:36:13
  13: polars_lazy::frame::parquet::<impl polars_lazy::frame::LazyFrame>::scan_parquet
             at /Users/aionescu/.cargo/registry/src/github.com-1ecc6299db9ec823/polars-lazy-0.22.7/src/frame/parquet.rs:77:13
  14: gyrfalcon::main
             at ./src/main.rs:6:14
  15: core::ops::function::FnOnce::call_once
             at /rustc/495b216696ccbc27c73d6bdc486bf4621d610f4b/library/core/src/ops/function.rs:248:5
```

#### What is the expected behavior?

Properly support this nested type and return the result. 

What do you think polars should have done?

Use the official Apache Arrow Rust (arrow-rs) implementation for parquet: https://github.com/apache/arrow-rs

This may be related to #2448 but not sure.

**Comment by andrei-ionescu** [comment]
Thanks! It did solve the issue.
