### ISSUE TITLE
[py-polars-0.13.53] ArrowErrorException: NotYetImplemented with LazyFrame on latest version

### ISSUE THREAD

**Issue by pyjamafish** [pola-rs/polars#4021]
#### What language are you using?
Python

#### Have you tried latest version of polars?
Yes, only occurs on the latest version

#### What version of polars are you using?
0.13.53

#### What operating system are you using polars on?
macOS Monterey

#### What language version are you using
Python 3.10

#### Describe your bug.

After building a LazyFrame `lf` using [several functions](https://github.com/pyjamafish/patent-analysis/blob/9640afb/patent_analysis/__main__.py#L42-L63), calling the following results in a `NotYetImplemented`.
```python
lf.with_column(
    pl.when(pl.col("cited_patent_issue_date") > datetime(2016, 12, 31))
    .then(pl.lit(None))
    .otherwise(pl.col("citations_5_years"))
    .alias("citations_5_years")
).collect()
```

#### What are the steps to reproduce the behavior?
Apologies, but I can't seem to get a simple MWE for this issue. To reproduce, you can try cloning https://github.com/pyjamafish/patent-analysis.git and running `python3 -m patent_analysis`.

This is because it *only* occurs when I build the LazyFrame using several functions:
```pycon
# create lf using `scan_csv`, `join`, `groupby`, `agg`, etc.
>>> lf.collect()
shape: (3, 4)
┌──────────────┬─────────────────────────┬───────────────────┬───────────────────┐
│ cited_patent ┆ cited_patent_issue_date ┆ citations_3_years ┆ citations_5_years │
│ ---          ┆ ---                     ┆ ---               ┆ ---               │
│ str          ┆ date                    ┆ u32               ┆ u32               │
╞══════════════╪═════════════════════════╪═══════════════════╪═══════════════════╡
│ B            ┆ 1999-08-04              ┆ 1                 ┆ 2                 │
├╌╌╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┤
│ A            ┆ 2000-10-20              ┆ 1                 ┆ 1                 │
├╌╌╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┤
│ C            ┆ 2018-05-03              ┆ 1                 ┆ 1                 │
└──────────────┴─────────────────────────┴───────────────────┴───────────────────┘
>>> lf.with_column(
...         pl.when(pl.col("cited_patent_issue_date") > datetime(2016, 12, 31))
...         .then(pl.lit(None))
...         .otherwise(pl.col("citations_5_years"))
...         .alias("citations_5_years")
).collect()
Traceback (most recent call last):
  File "/Users/fisher/Library/Application Support/JetBrains/Toolbox/apps/PyCharm-P/ch-0/221.5921.27/PyCharm.app/Contents/plugins/python/helpers/pydev/_pydevd_bundle/pydevd_exec2.py", line 3, in Exec
    exec(exp, global_vars, local_vars)
  File "<string>", line 6, in <module>
  File "/Users/fisher/PycharmProjects/patent-analysis/.venv/lib/python3.10/site-packages/polars/internals/lazy_frame.py", line 631, in collect
    return self._dataframe_class._from_pydf(ldf.collect())
exceptions.ArrowErrorException: NotYetImplemented("Casting from Int32 to LargeList(Field { name: \"item\", data_type: Timestamp(Microsecond, None), is_nullable: true, metadata: {} }) not supported")
```
When I save `lf` to a CSV file and create a new LazyFrame from it, the issue doesn't occur.
```pycon
>>> lf = pl.scan_csv("data.csv", dtypes={"cited_patent_issue_date": pl.Date, "citations_3_years": pl.UInt32, "citations_5_years": pl.UInt32})
>>> lf.collect()
shape: (3, 4)
┌──────────────┬─────────────────────────┬───────────────────┬───────────────────┐
│ cited_patent ┆ cited_patent_issue_date ┆ citations_3_years ┆ citations_5_years │
│ ---          ┆ ---                     ┆ ---               ┆ ---               │
│ str          ┆ date                    ┆ u32               ┆ u32               │
╞══════════════╪═════════════════════════╪═══════════════════╪═══════════════════╡
│ C            ┆ 2018-05-03              ┆ 1                 ┆ 1                 │
├╌╌╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┤
│ B            ┆ 1999-08-04              ┆ 1                 ┆ 2                 │
├╌╌╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┤
│ A            ┆ 2000-10-20              ┆ 1                 ┆ 1                 │
└──────────────┴─────────────────────────┴───────────────────┴───────────────────┘
>>> print(lf.with_column(
...    pl.when(pl.col("cited_patent_issue_date") > datetime(2016, 12, 31))
...    .then(pl.lit(None))
...    .otherwise(pl.col("citations_5_years"))
...    .alias("citations_5_years")
).collect())
shape: (3, 4)
┌──────────────┬─────────────────────────┬───────────────────┬───────────────────┐
│ cited_patent ┆ cited_patent_issue_date ┆ citations_3_years ┆ citations_5_years │
│ ---          ┆ ---                     ┆ ---               ┆ ---               │
│ str          ┆ date                    ┆ u32               ┆ u32               │
╞══════════════╪═════════════════════════╪═══════════════════╪═══════════════════╡
│ C            ┆ 2018-05-03              ┆ 1                 ┆ null              │
├╌╌╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┤
│ B            ┆ 1999-08-04              ┆ 1                 ┆ 2                 │
├╌╌╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┤
│ A            ┆ 2000-10-20              ┆ 1                 ┆ 1                 │
└──────────────┴─────────────────────────┴───────────────────┴───────────────────┘
```

#### What is the actual behavior?
The following exception is raised:
```python
Traceback (most recent call last):
  File "/Users/fisher/Library/Application Support/JetBrains/Toolbox/apps/PyCharm-P/ch-0/221.5921.27/PyCharm.app/Contents/plugins/python/helpers/pydev/_pydevd_bundle/pydevd_exec2.py", line 3, in Exec
    exec(exp, global_vars, local_vars)
  File "<string>", line 6, in <module>
  File "/Users/fisher/PycharmProjects/patent-analysis/.venv/lib/python3.10/site-packages/polars/internals/lazy_frame.py", line 631, in collect
    return self._dataframe_class._from_pydf(ldf.collect())
exceptions.ArrowErrorException: NotYetImplemented("Casting from Int32 to LargeList(Field { name: \"item\", data_type: Timestamp(Microsecond, None), is_nullable: true, metadata: {} }) not supported")
```

#### What is the expected behavior?
This exception should not be raised, because the code worked fine pre-0.13.53.

**Comment by ritchie46** [comment]
Can you try to get the query in a single file? That would save me a lot of time

**Comment by pyjamafish** [comment]
@ritchie46 Thank you so much for your hard work! Sorry that I couldn't get the query in a single file 😅
