### ISSUE TITLE
`arr.contains` not working on columns of type `list[cat]`

### ISSUE THREAD

**Issue by thobai** [pola-rs/polars#4150]
#### What language are you using?

**Python**

#### Have you tried latest version of polars?

- [yes]

#### What version of polars are you using?

0.13.57

#### What operating system are you using polars on?

MacOS 12.4

#### What language version are you using
python 3.10.5

#### Describe your bug.

The function `arr.contains` does not work on columns containing lists of categoricals.

#### What are the steps to reproduce the behavior?

```python
import polars as pl
from polars import col

df = pl.DataFrame(
    {
        "str": ["A", "B", "A", "B", "C"],
        "group": [1,1,2,1,2]
    }
).lazy()
df = df.with_column(pl.col("str").cast(pl.Categorical))

df_groups = df.groupby("group").agg([pl.col("str").list().alias("str_list")])
df_groups.filter(col("str_list").arr.contains("C")).collect()
```

#### What is the actual behavior?

```
thread '<unnamed>' panicked at 'python apply failed: cannot do is_in operation with left a dtype: Utf8 and right a dtype List(Categorical(Some(Local(LargeUtf8Array[A, B, C]))))', src/lazy/apply.rs:66:19
```

#### What is the expected behavior?

```
┌───────┬─────────────────┐
│ group ┆ str_list        │
│ ---   ┆ ---             │
│ i64   ┆ list[str]       │
╞═══════╪═════════════════╡
│ 2     ┆ ["A", "C"]      │
└───────┴─────────────────┘

**Comment by thobai** [comment]
While playing around with this I also recognized that polars behaves strangely when using `pl.Utf8` for the list and checking if a particular item is contained.

```
import polars as pl
from polars import col

df = pl.DataFrame(
    {
        "str": ["A", "B", "A", "B", "C"],
        "group": [1,1,2,1,2]
    }
).lazy()

df_groups = df.groupby("group").agg([pl.col("str").list().alias("str_list")])
df_groups.filter(col("str_list").arr.contains("C")).collect()
```

This throws the error
```
thread '<unnamed>' panicked at 'The columns lengths in the DataFrame are not equal.', /Users/runner/work/polars/polars/polars/polars-core/src/fmt.rs:321:13
```

If I do `arr.contains("A")`, which effectively doesn't filter anything, it works. Am I overlooking something here?
