### ISSUE TITLE
Very Uniformative Error when Flattening Column of Strings Containig Null Values

### ISSUE THREAD

**Issue by AlexanderNenninger** [pola-rs/polars#4166]
## Environment

- Language: Python, `sys.version = '3.10.5 | packaged by conda-forge | (main, Jun 14 2022, 07:05:37) [Clang 13.0.1 ]'`
- Polars Version: 0.13.58
- Sytem: Reproduced on both AmazonLinux2 x86-64 and MacOS Monterey on M1

## Bug Description

In the presence of null values `pl.col("foo").flatten()` throws a `pl.PaniceException`. Additionally, the Error message depends on the string contents in the column.

## How to reproduce

```python
import sys
import traceback

import polars as pl

sys.stdout = open("./out.txt", "w")

print(f"{sys.version = }")
print(f"{pl.__version__=}")

try:
    df = pl.DataFrame({"foo": ["FooBarBaz", None]})
    df.select(pl.col("foo").flatten())
except pl.PanicException as e:
    print(df)
    print(traceback.format_exc())

try:
    df = pl.DataFrame({"foo": ["foo", None]})
    df.select(pl.col("foo").flatten())
except pl.PanicException as e:
    print(df)
    print(traceback.format_exc())
```

Output:
```
sys.version = '3.10.5 | packaged by conda-forge | (main, Jun 14 2022, 07:05:37) [Clang 13.0.1 ]'
pl.__version__='0.13.58'
Traceback (most recent call last):
  File "/Users/NENNIA/Projects/test/polars_flatten_none.py", line 13, in <module>
    df.select(pl.col("foo").flatten())
  File "/Users/NENNIA/mambaforge/envs/test/lib/python3.10/site-packages/polars/internals/frame.py", line 4978, in select
    self.lazy()
  File "/Users/NENNIA/mambaforge/envs/test/lib/python3.10/site-packages/polars/internals/lazy_frame.py", line 647, in collect
    return self._dataframe_class._from_pydf(ldf.collect())
pyo3_runtime.PanicException: index out of bounds: the len is 1 but the index is 1

Traceback (most recent call last):
  File "/Users/NENNIA/Projects/test/polars_flatten_none.py", line 20, in <module>
    df.select(pl.col("foo").flatten())
  File "/Users/NENNIA/mambaforge/envs/test/lib/python3.10/site-packages/polars/internals/frame.py", line 4978, in select
    self.lazy()
  File "/Users/NENNIA/mambaforge/envs/test/lib/python3.10/site-packages/polars/internals/lazy_frame.py", line 647, in collect
    return self._dataframe_class._from_pydf(ldf.collect())
pyo3_runtime.PanicException: called `Result::unwrap()` on an `Err` value: OutOfSpec("validity mask length must match the number of values")
```

## Expected behavior

Either `Null` values are flattened, or a legible error message is being produced.

**Comment by AlexanderNenninger** [comment]
If it's a simple Error, I'd like to try fixing it.
