### ISSUE TITLE
Presumably valid script fails in 23.2, works in 22.0

### ISSUE THREAD

**Issue by AnatolyBug** [pola-rs/polars#4326]
Hi Polars Team,

Using pure rust, this code runs, as I would expect, fine with polars 22.0
```
let df = df![
        "country" => ["uk", "us", "eu", "jp"],
        "id"   => ["a", "b", "c", "c"],
        "month" => ["june", "july", "august", "august"],
        "col1" => [0., 3., 2., 1.],
        "col2" => [0., 0., 1., 1.],
    ].unwrap();

let x = df.lazy().groupby([col("country")])
    .agg([when(
        col("id").eq(lit("c")).and(
            col("month").eq(lit("august")))
                )
            .then(col("col1").fill_null(0.)) 
            .otherwise(lit::<f64>(0.0))])
    .collect()
    .unwrap();
    dbg!(x);
```
Giving result
```
┌─────────┬─┐
│ country ┆ col1      │
│ ---     ┆ ---       │
│ str     ┆ list[f64] │
╞═════════╪═╡
│ jp      ┆ [1.0]     │
├╌╌╌╌╌╌╌╌┤
│ uk      ┆ [0.0]     │
├╌╌╌╌╌╌╌╌┤
│ us      ┆ [0.0]     │
├╌╌╌╌╌╌╌╌┤
│ eu      ┆ [2.0]     │
└─────────┴─┘
```

However, the same script in 23.2 panics on the .unwrap() with the following error:
```
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: ComputeError("Failed to determine supertype of Unknown and Float64")', src\polars2.rs:57:6
stack backtrace:
   0: std::panicking::begin_panic_handler
             at /rustc/a8314ef7d0ec7b75c336af2c9857bfaf43002bfc/library\std\src\panicking.rs:584
   1: core::panicking::panic_fmt
             at /rustc/a8314ef7d0ec7b75c336af2c9857bfaf43002bfc/library\core\src\panicking.rs:142
   2: core::result::unwrap_failed
             at /rustc/a8314ef7d0ec7b75c336af2c9857bfaf43002bfc/library\core\src\result.rs:1785
   3: enum$<core::result::Result<polars_core::frame::DataFrame,enum$<polars_core::error::PolarsError> > >::unwrap<polars_core::frame::DataFrame,enum$<polars_core::error::PolarsError> >
             at /rustc/a8314ef7d0ec7b75c336af2c9857bfaf43002bfc\library\core\src\result.rs:1078
   4: practices::polars2::polarstests
             at .\src\polars2.rs:49
   5: practices::main
             at .\src\main.rs:77
   6: core::ops::function::FnOnce::call_once<void (*)(),tuple$<> >
             at /rustc/a8314ef7d0ec7b75c336af2c9857bfaf43002bfc\library\core\src\ops\function.rs:248
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
error: process didn't exit successfully: `target\debug\practices.exe` (exit code: 101)
```

Thank you!

**Comment by AnatolyBug** [comment]
Or, is this script invalid in the first place because of When Then Otherwise usage within GroupBy?

**Comment by AnatolyBug** [comment]
I think there is some issue with .fill_null(x), because simplifying above example to:
```
let x = df.lazy().with_columns([
        (col("col1").fill_null(0f64)+col("col2"))
    ]).collect().unwrap();
    dbg!(x);
```
Also panics! However, if I call .cast(DataType::Float64) after fill_null() then it goes through.

**Comment by ritchie46** [comment]
Thanks! Fix coming up.
