### ISSUE TITLE
Months cannot be directly converted to Date objects

### ISSUE THREAD

**Issue by parafoxia** [pola-rs/polars#4490]
### Polars version checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pypi.org/project/polars/) of polars.

### Issue Description

Dates which do not contain months (i.e. "2022-01") cannot be converted to Date (or Datetime) objects, even if the format is correct. It instead produces the following error:

```
thread '<unnamed>' panicked at 'invalid or out-of-range date', /github/home/.cargo/registry/src/github.com-1ecc6299db9ec823/chrono-0.4.20/src/naive/date.rs:244:9
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
Traceback (most recent call last):
  File "/home/parafoxia/Programs/Projects/analytix/test.py", line 4, in <module>
    df = df.with_column(pl.col("month").str.strptime(pl.Date, fmt="%Y-%m"))
  File "/home/parafoxia/Programs/Projects/analytix/.venv/lib/python3.10/site-packages/polars/internals/dataframe/frame.py", line 3781, in with_column
    return self.with_columns([column])
  File "/home/parafoxia/Programs/Projects/analytix/.venv/lib/python3.10/site-packages/polars/internals/dataframe/frame.py", line 4894, in with_columns
    self.lazy()
  File "/home/parafoxia/Programs/Projects/analytix/.venv/lib/python3.10/site-packages/polars/internals/lazyframe/frame.py", line 626, in collect
    return pli.wrap_df(ldf.collect())
pyo3_runtime.PanicException: invalid or out-of-range date
```

### Reproducible Example

```python
import polars as pl

df = pl.DataFrame({"month": ["2022-01"]})
df = df.with_column(pl.col("month").str.strptime(pl.Date, fmt="%Y-%m"))
```
Here's a [real-world example](https://github.com/parafoxia/analytix/blob/effea6b479e6bbe6e8dab2ab5e0073fc4336cf8c/analytix/reports.py#L342-L388) where I had to jank my way around the issue.

### Expected Behavior

The column is converted to Date objects.

### Installed Versions

```
---Version info---
Polars: 0.14.2
Index type: UInt32
Platform: Linux-5.10.16.3-microsoft-standard-WSL2-x86_64-with-glibc2.31
Python: 3.10.5 (main, Jul  9 2022, 15:38:19) [GCC 10.2.1 20210110]
---Optional dependencies---
pyarrow: 9.0.0
pandas: 1.4.3
numpy: 1.23.2
fsspec: <not installed>
connectorx: <not installed>
xlsx2csv: <not installed>
```

**Comment by laundmo** [comment]
This is inconsistent with pythons own datetime and the popular arrow datetime modules:

```py
from datetime import datetime
datetime.strptime("2022-01", "%Y-%m")
# datetime.datetime(2022, 1, 1, 0, 0)

import arrow
arrow.get("2021-01")
#<Arrow [2021-01-01T00:00:00+00:00]>
```
