### ISSUE TITLE
Polars fails to import in fresh environment because of missing optional dependencies

### ISSUE THREAD

**Issue by BartHelder** [pola-rs/polars#4644]
### Polars version checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pypi.org/project/polars/) of polars.

### Issue Description

Built and installed Polars on fresh environment (Docker, rust:latest). Attempting to import polars yields NameError because of missing dependency numpy, even though Numpy is listed as an optional dependency. 

### Reproducible Example

```python
# pip list
Package    Version
---------- -------
mercurial  5.6.1
pip        20.3.4
setuptools 52.0.0
wheel      0.34.2

# pip install polars
Collecting polars
  Using cached polars-0.14.6-cp37-abi3-manylinux_2_24_x86_64.whl (12.6 MB)
Collecting typing_extensions>=4.0.0
  Using cached typing_extensions-4.3.0-py3-none-any.whl (25 kB)
Installing collected packages: typing-extensions, polars
Successfully installed polars-0.14.6 typing-extensions-4.3.0

# python3
Python 3.9.2 (default, Feb 28 2021, 17:03:44)
[GCC 10.2.1 20210110] on linux
Type "help", "copyright", "credits" or "license" for more information.

>>> import polars as pl
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.9/dist-packages/polars/__init__.py", line 13, in <module>
    from polars import testing
  File "/usr/local/lib/python3.9/dist-packages/polars/testing.py", line 36, in <module>
    import polars.internals as pli
  File "/usr/local/lib/python3.9/dist-packages/polars/internals/__init__.py", line 38, in <module>
    from polars.internals.series import Series, wrap_s
  File "/usr/local/lib/python3.9/dist-packages/polars/internals/series/__init__.py", line 1, in <module>
    from polars.internals.series.series import Series, wrap_s
  File "/usr/local/lib/python3.9/dist-packages/polars/internals/series/series.py", line 45, in <module>
    from polars.internals.series._numpy import SeriesView, _ptr_to_numpy
  File "/usr/local/lib/python3.9/dist-packages/polars/internals/series/_numpy.py", line 17, in <module>
    class SeriesView(np.ndarray):  # type: ignore[type-arg]
NameError: name 'np' is not defined
```

### Expected Behavior

I can image not all functionality working, such as exporting dataframes to numpy arrays, but the core functionality should be available without optional deps. 

### Installed Versions

Can't import the module so no output here, but using the following wheel: 
0.14.6-cp37-abi3-manylinux_2_24_x86_64.whl

**Comment by BartHelder** [comment]
Maybe related to #4493 ?
