### ISSUE TITLE
Converting Pandas DataFrame with duplicate columns to Polars causes AttributeError in Pandas core

### ISSUE THREAD

**Issue by alexanderkeijser73** [pola-rs/polars#4733]
### Polars version checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pypi.org/project/polars/) of polars.

### Issue Description

I found that when I try to convert a Pandas DataFrame with duplicate columns (caused by concatenation with itself for example), that this results in an AttributeError raised by Pandas. I'm aware that duplicate columns are allowed in Polars, but I think it would be good if it would show a more informative error message

### Reproducible Example

```python
import pandas as pd
import polars as pl
df = pd.DataFrame({'a': [1, 2, 3]})

pl.DataFrame(pd.concat((df, df), axis=0)) # this works

Out[33]: 
shape: (6, 1)
┌─────┐
│ a   │
│ --- │
│ i64 │
╞═════╡
│ 1   │
├╌╌╌╌╌┤
│ 2   │
├╌╌╌╌╌┤
│ 3   │
├╌╌╌╌╌┤
│ 1   │
├╌╌╌╌╌┤
│ 2   │
├╌╌╌╌╌┤
│ 3   │
└─────┘

pl.DataFrame(pd.concat((df, df), axis=1)) # this fails

Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/IPython/core/interactiveshell.py", line 3553, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-34-6de2ec421a71>", line 1, in <module>
    pl.DataFrame(pd.concat((df, df), axis=1))
  File "/usr/local/lib/python3.7/site-packages/polars/internals/dataframe/frame.py", line 308, in __init__
    self._df = pandas_to_pydf(data, columns=columns)
  File "/usr/local/lib/python3.7/site-packages/polars/internals/construction.py", line 736, in pandas_to_pydf
    for col in data.columns
  File "/usr/local/lib/python3.7/site-packages/polars/internals/construction.py", line 736, in <dictcomp>
    for col in data.columns
  File "/usr/local/lib/python3.7/site-packages/polars/internals/construction.py", line 357, in _pandas_series_to_arrow
    dtype = values.dtype
  File "/usr/local/lib/python3.7/site-packages/pandas/core/generic.py", line 5487, in __getattr__
    return object.__getattribute__(self, name)
AttributeError: 'DataFrame' object has no attribute 'dtype'
```

### Expected Behavior

Show an error message like "failed to convert Pandas DataFrame to Polars, due to occurrence of duplicate columns"
or 
let it pass through, drop duplicate columns, and show a warning

### Installed Versions

<details>

>>> pl.show_versions()
---Version info---
Polars: 0.14.9
Index type: UInt32
Platform: Linux-5.10.104-linuxkit-x86_64-with-debian-10.1
Python: 3.7.4 (default, Oct 17 2019, 05:59:21) 
[GCC 8.3.0]
---Optional dependencies---
pyarrow: 8.0.0
pandas: 1.3.5
numpy: 1.21.6
fsspec: 2021.11.1
connectorx: <not installed>
xlsx2csv: <not installed>
pytz: 2022.1

</details>

**Comment by alexanderkeijser73** [comment]
Thanks for the quick fix guys 👍
