### ISSUE TITLE
Cannot concatenate categorical columns when global string cache is set

### ISSUE THREAD

**Issue by abalkin** [pola-rs/polars#4762]
### Polars version checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pypi.org/project/polars/) of polars.

### Issue Description

Using `concat_list` to create a `list[cat]` column works when global string cache is not set, but panics when it is.

### Reproducible Example

```python
>>> import polars as pl
>>> df = pl.DataFrame({'x': 'a'})
>>> pl.Config.set_global_string_cache();
>>> df.select([pl.concat_list([pl.col('x').cast(pl.Categorical)]*2)])
thread '<unnamed>' panicked at 'called `Option::unwrap()` on a `None` value', /Users/runner/work/polars/polars/polars/polars-core/src/chunked_array/logical/categorical/builder.rs:90:28
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "...polars/internals/dataframe/frame.py", line 1094, in __repr__
    return self.__str__()
  File "...polars/internals/dataframe/frame.py", line 1091, in __str__
    return self._df.as_str()
pyo3_runtime.PanicException: called `Option::unwrap()` on a `None` value
```

### Expected Behavior

Expect the same behavior as without global string cache.

```python
>>> df.select([pl.concat_list([pl.col('x').cast(pl.Categorical)]*2)])
shape: (1, 1)
┌────────────┐
│ x          │
│ ---        │
│ list[cat]  │
╞════════════╡
│ ["a", "a"] │
└────────────┘
```

### Installed Versions

<details>

---Version info---
Polars: 0.14.9
Index type: UInt32
Platform: macOS-12.5-arm64-arm-64bit
Python: 3.9.7 (default, Aug 12 2022, 09:02:06)
[Clang 13.1.6 (clang-1316.0.21.2.5)]
---Optional dependencies---
pyarrow: 9.0.0
pandas: 1.4.4
numpy: 1.23.2
fsspec: 2022.7.1
connectorx: 0.3.0
xlsx2csv: <not installed>
pytz: 2022.1

</details>

**Comment by abalkin** [comment]
It turns out that the exception is thrown when the result is printed.

```python
>>> z = df.select([pl.concat_list([pl.col('x').cast(pl.Categorical)]*2)])
```
