### ISSUE TITLE
schema inference doesn't seem to work in from_dicts for nested dicts

### ISSUE THREAD

**Issue by dataDiet** [pola-rs/polars#4904]
In polars 0.14.1 the following worked as is, but doesn't seem to work now in polars 0.14.11.
Is there guidance on how this is expected to be handled now?

```
# test_pl.py

import polars as pl

 

df=pl.from_dicts([
    { "vehicle":
        { "auto": "car" }
    },
    { "vehicle":
        { "auto": None }
    }
])

% python test_pl.py
Traceback (most recent call last):
  File "/Users/akiramadono/jetstream-detect-apps/test_pl.py", line 3, in <module>
    df=pl.from_dicts([
  File "/Users/akiramadono/jetstream-detect-apps/pl11/lib/python3.9/site-packages/polars/convert.py", line 111, in from_dicts
    return DataFrame._from_dicts(dicts, infer_schema_length)
  File "/Users/akiramadono/jetstream-detect-apps/pl11/lib/python3.9/site-packages/polars/internals/dataframe/frame.py", line 330, in _from_dicts
    pydf = PyDataFrame.read_dicts(data, infer_schema_length)
exceptions.ComputeError: Failed to determine supertype of Struct([Field { name: "auto", dtype: Utf8 }]) and Struct([Field { name: "auto", dtype: Null }])

**Comment by physinet** [comment]
To narrow down the version scope, I see this working in 0.14.2 but raising the error in 0.14.4.

**Comment by dataDiet** [comment]
The situation seems to be mitigated by setting `infer_schema_length=1`.  Does not seem like 'schema inference' if the user has to determine how many/which rows to scan.  Wondering what has changed.
