### ISSUE TITLE
Crash when aggregating with iso_year

### ISSUE THREAD

**Issue by SirVer** [pola-rs/polars#5073]
### Polars version checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pypi.org/project/polars/) of Polars.

### Issue description

When using `iso_year` in a statement I see crashes. With `year` is used everything is working. This is the crash I am seeing:

```
thread '<unnamed>' panicked at 'called `Result::unwrap()` on an `Err` value: OutOfSpec("PrimitiveArray can only be initialized with a DataType whose physical type is Primitive")', /Users/runner/.cargo/registry/src/github.com-1ecc6299db9ec823/arrow2-0.14.1/src/array/primitive/mod.rs:420:52
stack backtrace:
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
Traceback (most recent call last):
  File "interactive.py", line 77, in <module>
    crash()
  File "interactive.py", line 74, in crash
    pl.DataFrame({"x_axis": idx}).groupby(groupby).sum()
  File "/Users/hrapp/.local/share/virtualenvs/bizkit-0qjQd64c/lib/python3.8/site-packages/polars/internals/dataframe/groupby.py", line 579, in sum
    return self.agg(pli.all().sum())
  File "/Users/hrapp/.local/share/virtualenvs/bizkit-0qjQd64c/lib/python3.8/site-packages/polars/internals/dataframe/groupby.py", line 295, in agg
    pli.wrap_df(self._df)
  File "/Users/hrapp/.local/share/virtualenvs/bizkit-0qjQd64c/lib/python3.8/site-packages/polars/internals/lazyframe/frame.py", line 858, in collect
    return pli.wrap_df(ldf.collect())
pyo3_runtime.PanicException: called `Result::unwrap()` on an `Err` value: OutOfSpec("PrimitiveArray can only be initialized with a DataType whose physical type is Primitive")
```

### Reproducible example

```python
import datetime
import polars as pl

idx = pl.date_range(datetime.date(2022, 1, 1), datetime.date(2022, 8, 1), "1d").cast(pl.Date)  # type: ignore
groupby = (pl.col("x_axis").dt.iso_year()).alias("foo")
pl.DataFrame({"x_axis": idx}).groupby(groupby).sum()
```

### Expected behavior

This should not crash, should it now :)

### Installed versions

<details>
``` 
---Version info---
Polars: 0.14.15
Index type: UInt32
Platform: macOS-12.4-x86_64-i386-64bit
Python: 3.8.9 (default, May 17 2022, 12:55:41)
[Clang 13.1.6 (clang-1316.0.21.2.5)]
---Optional dependencies---
pyarrow: 9.0.0
pandas: 1.5.0
numpy: 1.23.3
fsspec: <not installed>
connectorx: 0.3.0
xlsx2csv: <not installed>
 ```
</details>

**Comment by SirVer** [comment]
Thank you! :)
