### ISSUE TITLE
pl.Expr.unique_counts() fails with over()

### ISSUE THREAD

**Issue by mcrumiller** [pola-rs/polars#5145]
### Polars version checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pypi.org/project/polars/) of Polars.

### Issue description

The `unique_counts()` function fails when a window is specified.

### Reproducible example

```python
import polars as pl

df = pl.DataFrame({
    'a': [ 1,   1,   1,       2,   2,   3,       4,   5,   6],
    'b': ['a', 'a', 'a',     'b', 'b', 'b',     'c', 'c', 'c']
})

df.select(pl.col('a').max().over('b')) # works
df.select(pl.col('a').unique_counts().over('b')) # fails
```

```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Projects\project-brr\venv_brr\lib\site-packages\polars\internals\dataframe\frame.py", line 5243, in select
    self.lazy()
  File "C:\Projects\project-brr\venv_brr\lib\site-packages\polars\internals\lazyframe\frame.py", line 906, in collect
    return pli.wrap_df(ldf.collect())
exceptions.ComputeError: the length of the window expression did not match that of the group
```

### Expected behavior

```
shape: (9, 1)
┌─────┐
│ a   │
│ --- │
│ i64 │
╞═════╡
│ 1   │
├╌╌╌╌╌┤
│ 1   │
├╌╌╌╌╌┤
│ 1   │
├╌╌╌╌╌┤
│ 2   │
├╌╌╌╌╌┤
│ 2   │
├╌╌╌╌╌┤
│ 2   │
├╌╌╌╌╌┤
│ 3   │
├╌╌╌╌╌┤
│ 3   │
├╌╌╌╌╌┤
│ 3   │
└─────┘
```

### Installed versions

<details>

```
---Version info---
Polars: 0.14.18
Index type: UInt32
Platform: Windows-10-10.0.19044-SP0
Python: 3.9.5 (tags/v3.9.5:0a7dcbd, May  3 2021, 17:27:52) [MSC v.1928 64 bit (AMD64)]
---Optional dependencies---
pyarrow: 8.0.0
pandas: 1.4.3
numpy: 1.23.1
fsspec: <not installed>
connectorx: 0.3.0
xlsx2csv: 0.8
matplotlib: 3.5.2
```

</details>

**Comment by mcrumiller** [comment]
Sorry, I mistook `unique_counts` for `count_unique` (which doesn't exist).
