### ISSUE TITLE
Exception when sorting DataFrame that contains List(Datetime) column

### ISSUE THREAD

**Issue by ronaldrichter** [pola-rs/polars#5268]
### Polars version checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pypi.org/project/polars/) of Polars.

### Issue description

Polars panics when trying to sort (or indexing) a dataframe that contains a column of dtype List(Datetime), i.e. list of timestamps. It works as expected for other list dtypes, e.g. List(Int64).

### Reproducible example

```python
import polars as pl
from datetime import datetime

frame = pl.DataFrame({
    "ix": [2, 1],
    "dt": [[datetime(2001, 1, 1)], [datetime(2001, 1, 2)]],
})

frame.sort(by="ix")  # <-- panics
```

Output:

```
thread '<unnamed>' panicked at 'called `Result::unwrap()` on an `Err` value: OutOfSpec("ListArray's child's DataType must match. However, the expected DataType is Timestamp(Microsecond, None) while it got Int64.")', /Users/runner/miniforge3/conda-bld/polars_1666114591432/_build_env/.cargo/registry/src/github.com-1ecc6299db9ec823/arrow2-0.14.2/src/array/list/mod.rs:202:71
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
Traceback (most recent call last):
  File "/Users/phoni/Projects/scratch/polars_bug.py", line 9, in <module>
    frame.sort(by="ix")
  File "/Users/phoni/Projects/miniconda3/envs/scratch/lib/python3.9/site-packages/polars/internals/dataframe/frame.py", line 2694, in sort
    return self._from_pydf(self._df.sort(by, reverse, nulls_last))
pyo3_runtime.PanicException: called `Result::unwrap()` on an `Err` value: OutOfSpec("ListArray's child's DataType must match. However, the expected DataType is Timestamp(Microsecond, None) while it got Int64.")
```

### Expected behavior

Calling .sort() should not panic

### Installed versions

<details>

```
---Version info---
Polars: 0.14.21
Index type: UInt32
Platform: macOS-12.6-arm64-arm-64bit
Python: 3.9.13 | packaged by conda-forge | (main, May 27 2022, 17:00:33) 
[Clang 13.0.1 ]
---Optional dependencies---
pyarrow: 9.0.0
pandas: <not installed>
numpy: 1.23.4
fsspec: <not installed>
connectorx: <not installed>
xlsx2csv: <not installed>
matplotlib: <not installed>
```

</details>

**Comment by ronaldrichter** [comment]
@ritchie46 Many thanks!
