### ISSUE TITLE
Default `otherwise` for a when-then statement

### ISSUE THREAD

**Issue by physinet** [pola-rs/polars#5357]
### Problem description

When-then statements appear to require an `otherwise`:
```python
>>> import polars as pl
>>> df = pl.DataFrame({"a": [1, 2, 3]})
>>> whenthen = pl.when(pl.col("a") == 1).then(True).when(pl.col("a") == 2).then(False)
>>> df.select(["a", whenthen])
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.9/site-packages/polars/internals/dataframe/frame.py", line 5195, in select
    self.lazy()
  File "/usr/local/lib/python3.9/site-packages/polars/internals/lazyframe/frame.py", line 1018, in select
    exprs = pli.selection_to_pyexpr_list(exprs)
  File "/usr/local/lib/python3.9/site-packages/polars/internals/expr/expr.py", line 57, in selection_to_pyexpr_list
    return [expr_to_lit_or_expr(e, str_to_lit=False)._pyexpr for e in exprs]
  File "/usr/local/lib/python3.9/site-packages/polars/internals/expr/expr.py", line 57, in <listcomp>
    return [expr_to_lit_or_expr(e, str_to_lit=False)._pyexpr for e in exprs]
  File "/usr/local/lib/python3.9/site-packages/polars/internals/expr/expr.py", line 102, in expr_to_lit_or_expr
    raise ValueError(
ValueError: did not expect value <polars.internals.whenthen.WhenThenThen object at 0x110307e50> of type <class 'polars.internals.whenthen.WhenThenThen'>, maybe disambiguate with pl.lit or pl.col
>>> df.select(["a", whenthen.otherwise(None)])
shape: (3, 2)
┌─────┬─────────┐
│ a   ┆ literal │
│ --- ┆ ---     │
│ i64 ┆ bool    │
╞═════╪═════════╡
│ 1   ┆ true    │
├╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌┤
│ 2   ┆ false   │
├╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌┤
│ 3   ┆ null    │
└─────┴─────────┘
```

It would be convenient to have the `otherwise` statement default to return null. This is the case in PySpark:
```python
>>> from pyspark.sql import SparkSession
>>> import pyspark.sql.functions as F
>>> spark = SparkSession.builder.getOrCreate().newSession()
>>> df = spark.createDataFrame([[1], [2], [3]], ["a"])
>>> whenthen = F.when(F.col("a") == 1, True).when(F.col("a") == 2, False)
>>> df.select("a", whenthen).show()
+---+-------------------------------------------------------+
|  a|CASE WHEN (a = 1) THEN true WHEN (a = 2) THEN false END|
+---+-------------------------------------------------------+
|  1|                                                   true|
|  2|                                                  false|
|  3|                                                   null|
+---+-------------------------------------------------------+
```

**Comment by ritchie46** [comment]
We already have this? Have you updated?

**Comment by physinet** [comment]
Argh, I tested with 0.14.21, thought that would have been recent enough. 🤦  Works beautifully as expected, thanks!
