### ISSUE TITLE
boolean comparison of date column diff() to pl.duration fails

### ISSUE THREAD

**Issue by mcrumiller** [pola-rs/polars#5374]
### Polars version checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pypi.org/project/polars/) of Polars.

### Issue description

When using `diff()` on a `pl.Date` or `pl.Datetime` column, a comparison to a `pl.duration` fails.

### Reproducible example

```python
import polars as pl

dates = ["2022-01-01", "2022-01-02", "2022-01-03"]
df = pl.DataFrame({
    "date": pl.Series(dates).str.strptime(pl.Date, "%Y-%m-%d")
})
```
This works:

```python
df_diff = df.select(pl.col("date").diff())
df_diff.select(pl.col("date") < pl.duration(days=1))
```
```
shape: (3, 1)
┌───────┐
│ date  │
│ ---   │
│ bool  │
╞═══════╡
│ null  │
├╌╌╌╌╌╌╌┤
│ false │
├╌╌╌╌╌╌╌┤
│ false │
└───────┘
```
This fails, despite logically being identical:
```python
df.select(pl.col("date").diff() < pl.duration(days=1))
```
```
thread '<unnamed>' panicked at 'called `Result::unwrap()` on an `Err` value: SchemaMisMatch(Owned("Series of dtype: Date != Duration"))', D:\a\polars\polars\polars\polars-core\src\series\comparison.rs:285:23
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\430015439\AppData\Local\Programs\Python\Python39\lib\site-packages\polars\internals\dataframe\frame.py", line 5214, in select
    self.lazy()
  File "C:\Users\430015439\AppData\Local\Programs\Python\Python39\lib\site-packages\polars\internals\lazyframe\frame.py", line 920, in collect
    return pli.wrap_df(ldf.collect())
```

### Installed versions

<details>

```
---Version info---
Polars: 0.14.24
Index type: UInt32
Platform: Windows-10-10.0.19044-SP0
Python: 3.9.13 (tags/v3.9.13:6de2ca5, May 17 2022, 16:36:42) [MSC v.1929 64 bit (AMD64)]
---Optional dependencies---
pyarrow: 9.0.0
pandas: 1.5.1
numpy: 1.23.4
fsspec: None
connectorx: 0.3.0
xlsx2csv: 0.8
matplotlib: 3.6.1
```

</details>

**Comment by ritchie46** [comment]
Seems like you are missing brackets?

**Comment by mcrumiller** [comment]
@ritchie46 sorry, I left them out of my example accidentally, but the problem persists.. It fails even with the brackets. I've updated the example code and exception to reflect the actual error.
```

**Comment by ritchie46** [comment]
That's strange. I cannot reproduce this.

**Comment by mcrumiller** [comment]
@ritchie46 I screwed up my example again, sorry sorry sorry. `-` works but boolean comparison does not. I've updated the example above. This fails. Polars appears to think that `pl.col("date").diff()` is still dtype `pl.Date`.

```python
import polars as pl

dates = ["2022-01-01", "2022-01-02", "2022-01-03"]
df = pl.DataFrame({
    "date": pl.Series(dates).str.strptime(pl.Date, "%Y-%m-%d")
})
df.select(pl.col("date").diff() < pl.duration(days=1))
```
```
thread '<unnamed>' panicked at 'called `Result::unwrap()` on an `Err` value: SchemaMisMatch(Owned("Series of dtype: Date != Duration"))', D:\a\polars\polars\polars\polars-core\src\series\comparison.rs:285:23
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\430015439\AppData\Local\Programs\Python\Python39\lib\site-packages\polars\internals\dataframe\frame.py", line 5214, in select
    self.lazy()
  File "C:\Users\430015439\AppData\Local\Programs\Python\Python39\lib\site-packages\polars\internals\lazyframe\frame.py", line 920, in collect
    return pli.wrap_df(ldf.collect())
```

**Comment by mcrumiller** [comment]
Oh, and it works if you cast the `.diff()` to a `pl.Duration`:

```python
import polars as pl

dates = ["2022-01-01", "2022-01-02", "2022-01-03"]
df = pl.DataFrame({
    "date": pl.Series(dates).str.strptime(pl.Date, "%Y-%m-%d")
})

df.select(pl.col("date").diff().cast(pl.Duration) < pl.duration(days=1)) # succeeds
df.select(pl.col("date").diff() < pl.duration(days=1)) # fails

```
