### ISSUE TITLE
FileCache::assert_empty() fails

### ISSUE THREAD

**Issue by spotys** [pola-rs/polars#5490]
### Polars version checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://crates.io/crates/polars) of Polars.

### Issue description

When using LazyFrame::cache() to avoid multiple reads of the same file, the debug version fails on FileCache::assert_empty()

### Reproducible example

```rust
use polars::prelude::*;

fn main() -> PolarsResult<()> {
    let ba = LazyFrame::scan_parquet("file.parquet", ScanArgsParquet { ..Default::default() })?.cache();
    let lfs = (0..2).into_iter().map(|_| ba.clone()).collect::<Vec<LazyFrame>>();
    let df = concat(lfs, true, true)?.collect()?;

    println!("df: {:#?}", df.head(Some(5)));
    Ok(())
}
```

```bash
> cargo build
   Compiling bug v0.1.0 (/Users/stepan/src/tcli/bug)
    Finished dev [unoptimized + debuginfo] target(s) in 2.97s
> RUST_BACKTRACE=1 target/debug/bug
thread 'main' panicked at 'assertion failed: state.1.is_empty()', /Users/stepan/.cargo/registry/src/github.com-1ecc6299db9ec823/polars-lazy-0.25.1/src/physical_plan/file_cache.rs:35:13
stack backtrace:
   0: rust_begin_unwind
             at /rustc/4b91a6ea7258a947e59c6522cd5898e7c0a6a88f/library/std/src/panicking.rs:584:5
   1: core::panicking::panic_fmt
             at /rustc/4b91a6ea7258a947e59c6522cd5898e7c0a6a88f/library/core/src/panicking.rs:142:14
   2: core::panicking::panic
             at /rustc/4b91a6ea7258a947e59c6522cd5898e7c0a6a88f/library/core/src/panicking.rs:48:5
   3: polars_lazy::physical_plan::file_cache::FileCache::assert_empty
             at /Users/stepan/.cargo/registry/src/github.com-1ecc6299db9ec823/polars-lazy-0.25.1/src/physical_plan/file_cache.rs:35:13
   4: polars_lazy::frame::LazyFrame::collect
             at /Users/stepan/.cargo/registry/src/github.com-1ecc6299db9ec823/polars-lazy-0.25.1/src/frame/mod.rs:587:13
   5: bug::main
             at ./bug/src/main.rs:6:14
   6: core::ops::function::FnOnce::call_once
             at /rustc/4b91a6ea7258a947e59c6522cd5898e7c0a6a88f/library/core/src/ops/function.rs:248:5
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.```

### Expected behavior

debug version runs without errors

### Installed versions

<details>
polars = { version = "0.25.1", features = [ "lazy", "parquet" ] }
</details>

**Comment by spotys** [comment]
Just figured out that a non-parallel `concat` call does not produce the error:
```rust
...
let df = concat(lfs, true, false)?.collect()?;
...
```
