### ISSUE TITLE
Cannot filter for strings

### ISSUE THREAD

**Issue by forgetso** [pola-rs/polars#5527]
### Polars version checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://www.npmjs.com/package/nodejs-polars) of Polars.

### Issue description

I cannot filter for strings in nodejs-polars, receiving a `GenericFailure`.

### Reproducible example

```javascript
> df = pl.DataFrame({"foo": ["a", "b", "c"]})
Proxy [
  shape: (3, 1)
  ┌─────┐
  │ foo │
  │ --- │
  │ str │
  ╞═════╡
  │ a   │
  ├╌╌╌╌╌┤
  │ b   │
  ├╌╌╌╌╌┤
  │ c   │
  └─────┘,
  {
    get: [Function: get],
    set: [Function: set],
    has: [Function: has],
    ownKeys: [Function: ownKeys],
    getOwnPropertyDescriptor: [Function: getOwnPropertyDescriptor]
  }
]
> df.filter(pl.col("foo").eq("b"))
Uncaught Error: Not found: b
    at Object.collectSync (/home/chris/dev/prosopo/workspaces/node_modules/nodejs-polars/bin/lazy/dataframe.js:62:53)
    at Proxy.filter (/home/chris/dev/prosopo/workspaces/node_modules/nodejs-polars/bin/dataframe.js:155:18) {
  code: 'GenericFailure'
}
```

### Expected behavior

The row containing the string value will be found.

**Comment by forgetso** [comment]
This works if you convert the string to a series.

```
> df = pl.DataFrame({"foo": ["a", "b", "c"]})
Proxy [
  shape: (3, 1)
  ┌─────┐
  │ foo │
  │ --- │
  │ str │
  ╞═════╡
  │ a   │
  ├╌╌╌╌╌┤
  │ b   │
  ├╌╌╌╌╌┤
  │ c   │
  └─────┘,
  {
    get: [Function: get],
    set: [Function: set],
    has: [Function: has],
    ownKeys: [Function: ownKeys],
    getOwnPropertyDescriptor: [Function: getOwnPropertyDescriptor]
  }
]
> df.filter(pl.col("foo").eq(pl.Series(["b"])))
Proxy [
  shape: (1, 1)
  ┌─────┐
  │ foo │
  │ --- │
  │ str │
  ╞═════╡
  │ b   │
  └─────┘,
  {
    get: [Function: get],
    set: [Function: set],
    has: [Function: has],
    ownKeys: [Function: ownKeys],
    getOwnPropertyDescriptor: [Function: getOwnPropertyDescriptor]
  }
]
```

**Comment by ritchie46** [comment]
Can you make an issue in the `nodejs-polars` repo?

**Comment by forgetso** [comment]
Done
