### ISSUE TITLE
pl.concat doesn't projection pushdown consistently across child plans, vstack fails

### ISSUE THREAD

**Issue by OneRaynyDay** [pola-rs/polars#5754]
### Polars version checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pypi.org/project/polars/) of Polars.

### Issue description

Similar to the other ticket, I'm using a `join_asof`, trying to add null values after-the-fact like a left/right join. In the example below it tries to mimic a left join:

### Reproducible example

```python
b = list(np.linspace(0, 5, 7))
b[2] = None
b[6] = None
lf1 = pl.DataFrame(
    {
        "l": np.linspace(0, 5, 7),
        "m": np.linspace(0, 5, 7),
        "a": np.linspace(0, 5, 7),
        "b": b,
        "c": ["x" if i < 4 else "y" for i in range(7)],
        "d": np.linspace(0, 5, 7),
    }
).lazy()
lf2 = (
    pl.DataFrame(
        {
            "group": [0, 2, 3, 0, 1, 2, 3],
            "val": [0, 2.5, 2.6, 2.7, 3.4, 4, 5],
            "c": ["x", "x", "x", "y", "y", "y", "y"],
        }
    )
    .with_column(pl.col("val").alias("b"))
    .lazy()
)
# I remove all the nulls so we can join_asof
clean_left = lf1.filter(~(pl.col("b").is_nan() | pl.col("b").is_null())).sort(["b", "c"])
clean_right = lf2.filter(~(pl.col("b").is_nan() | pl.col("b").is_null())).sort(["b", "c"])
joined = clean_left.join_asof(
    clean_right,
    on="b",
    by=["c"],
    strategy="backward",
)
# We will try to reconstruct the slice of left that's null on `b` like a left join with
# null literals on the right columns
expressions = [
    pl.col(col) if col in lf1.columns else pl.lit(None, dtype=joined.schema[col]).alias(col) for col in joined.columns
]
dirty_lf1 = lf1.filter(pl.col("b").is_null()).select(expressions)
concatted = pl.concat([joined, dirty_lf1])
# Select a bunch of columns to trigger the projection pushdown bug
concatted.select(["group", "l", "b", "val", "a"]).collect()

---------------------------------------------------------------------------
ShapeError                                Traceback (most recent call last)
Input In [60], in <cell line: 1>()
----> 1 concatted.select(["group", "l", "b", "val", "a"]).collect()

File /...lib/python3.10/site-packages/polars/internals/lazyframe/frame.py:937, in LazyFrame.collect(self, type_coercion, predicate_pushdown, projection_pushdown, simplify_expression, string_cache, no_optimization, slice_pushdown, common_subplan_elimination, allow_streaming)
    926     common_subplan_elimination = False
    928 ldf = self._ldf.optimization_toggle(
    929     type_coercion,
    930     predicate_pushdown,
   (...)
    935     allow_streaming,
    936 )
--> 937 return pli.wrap_df(ldf.collect())

ShapeError: Could not vertically stack DataFrame. The DataFrames appended width 6 differs from the parent DataFrames width 5
```

Here are some views of the dataframes:

```
lf1 & lf2:

shape: (7, 6)
┌──────────┬──────────┬──────────┬──────────┬─────┬──────────┐
│ l        ┆ m        ┆ a        ┆ b        ┆ c   ┆ d        │
│ ---      ┆ ---      ┆ ---      ┆ ---      ┆ --- ┆ ---      │
│ f64      ┆ f64      ┆ f64      ┆ f64      ┆ str ┆ f64      │
╞══════════╪══════════╪══════════╪══════════╪═════╪══════════╡
│ 0.0      ┆ 0.0      ┆ 0.0      ┆ 0.0      ┆ x   ┆ 0.0      │
├╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌┤
│ 0.833333 ┆ 0.833333 ┆ 0.833333 ┆ 0.833333 ┆ x   ┆ 0.833333 │
├╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌┤
│ 1.666667 ┆ 1.666667 ┆ 1.666667 ┆ null     ┆ x   ┆ 1.666667 │
├╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌┤
│ 2.5      ┆ 2.5      ┆ 2.5      ┆ 2.5      ┆ x   ┆ 2.5      │
├╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌┤
│ 3.333333 ┆ 3.333333 ┆ 3.333333 ┆ 3.333333 ┆ y   ┆ 3.333333 │
├╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌┤
│ 4.166667 ┆ 4.166667 ┆ 4.166667 ┆ 4.166667 ┆ y   ┆ 4.166667 │
├╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌┤
│ 5.0      ┆ 5.0      ┆ 5.0      ┆ null     ┆ y   ┆ 5.0      │
└──────────┴──────────┴──────────┴──────────┴─────┴──────────┘
shape: (7, 4)
┌───────┬─────┬─────┬─────┐
│ group ┆ val ┆ c   ┆ b   │
│ ---   ┆ --- ┆ --- ┆ --- │
│ i64   ┆ f64 ┆ str ┆ f64 │
╞═══════╪═════╪═════╪═════╡
│ 0     ┆ 0.0 ┆ x   ┆ 0.0 │
├╌╌╌╌╌╌╌┼╌╌╌╌╌┼╌╌╌╌╌┼╌╌╌╌╌┤
│ 2     ┆ 2.5 ┆ x   ┆ 2.5 │
├╌╌╌╌╌╌╌┼╌╌╌╌╌┼╌╌╌╌╌┼╌╌╌╌╌┤
│ 3     ┆ 2.6 ┆ x   ┆ 2.6 │
├╌╌╌╌╌╌╌┼╌╌╌╌╌┼╌╌╌╌╌┼╌╌╌╌╌┤
│ 0     ┆ 2.7 ┆ y   ┆ 2.7 │
├╌╌╌╌╌╌╌┼╌╌╌╌╌┼╌╌╌╌╌┼╌╌╌╌╌┤
│ 1     ┆ 3.4 ┆ y   ┆ 3.4 │
├╌╌╌╌╌╌╌┼╌╌╌╌╌┼╌╌╌╌╌┼╌╌╌╌╌┤
│ 2     ┆ 4.0 ┆ y   ┆ 4.0 │
├╌╌╌╌╌╌╌┼╌╌╌╌╌┼╌╌╌╌╌┼╌╌╌╌╌┤
│ 3     ┆ 5.0 ┆ y   ┆ 5.0 │
└───────┴─────┴─────┴─────┘

clean left & clean right:

shape: (5, 6)
┌──────────┬──────────┬──────────┬──────────┬─────┬──────────┐
│ l        ┆ m        ┆ a        ┆ b        ┆ c   ┆ d        │
│ ---      ┆ ---      ┆ ---      ┆ ---      ┆ --- ┆ ---      │
│ f64      ┆ f64      ┆ f64      ┆ f64      ┆ str ┆ f64      │
╞══════════╪══════════╪══════════╪══════════╪═════╪══════════╡
│ 0.0      ┆ 0.0      ┆ 0.0      ┆ 0.0      ┆ x   ┆ 0.0      │
├╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌┤
│ 0.833333 ┆ 0.833333 ┆ 0.833333 ┆ 0.833333 ┆ x   ┆ 0.833333 │
├╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌┤
│ 2.5      ┆ 2.5      ┆ 2.5      ┆ 2.5      ┆ x   ┆ 2.5      │
├╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌┤
│ 3.333333 ┆ 3.333333 ┆ 3.333333 ┆ 3.333333 ┆ y   ┆ 3.333333 │
├╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌┤
│ 4.166667 ┆ 4.166667 ┆ 4.166667 ┆ 4.166667 ┆ y   ┆ 4.166667 │
└──────────┴──────────┴──────────┴──────────┴─────┴──────────┘
shape: (7, 4)
┌───────┬─────┬─────┬─────┐
│ group ┆ val ┆ c   ┆ b   │
│ ---   ┆ --- ┆ --- ┆ --- │
│ i64   ┆ f64 ┆ str ┆ f64 │
╞═══════╪═════╪═════╪═════╡
│ 0     ┆ 0.0 ┆ x   ┆ 0.0 │
├╌╌╌╌╌╌╌┼╌╌╌╌╌┼╌╌╌╌╌┼╌╌╌╌╌┤
│ 2     ┆ 2.5 ┆ x   ┆ 2.5 │
├╌╌╌╌╌╌╌┼╌╌╌╌╌┼╌╌╌╌╌┼╌╌╌╌╌┤
│ 3     ┆ 2.6 ┆ x   ┆ 2.6 │
├╌╌╌╌╌╌╌┼╌╌╌╌╌┼╌╌╌╌╌┼╌╌╌╌╌┤
│ 0     ┆ 2.7 ┆ y   ┆ 2.7 │
├╌╌╌╌╌╌╌┼╌╌╌╌╌┼╌╌╌╌╌┼╌╌╌╌╌┤
│ 1     ┆ 3.4 ┆ y   ┆ 3.4 │
├╌╌╌╌╌╌╌┼╌╌╌╌╌┼╌╌╌╌╌┼╌╌╌╌╌┤
│ 2     ┆ 4.0 ┆ y   ┆ 4.0 │
├╌╌╌╌╌╌╌┼╌╌╌╌╌┼╌╌╌╌╌┼╌╌╌╌╌┤
│ 3     ┆ 5.0 ┆ y   ┆ 5.0 │
└───────┴─────┴─────┴─────┘

joined frame:

shape: (5, 8)
┌──────────┬──────────┬──────────┬──────────┬─────┬──────────┬───────┬─────┐
│ l        ┆ m        ┆ a        ┆ b        ┆ c   ┆ d        ┆ group ┆ val │
│ ---      ┆ ---      ┆ ---      ┆ ---      ┆ --- ┆ ---      ┆ ---   ┆ --- │
│ f64      ┆ f64      ┆ f64      ┆ f64      ┆ str ┆ f64      ┆ i64   ┆ f64 │
╞══════════╪══════════╪══════════╪══════════╪═════╪══════════╪═══════╪═════╡
│ 0.0      ┆ 0.0      ┆ 0.0      ┆ 0.0      ┆ x   ┆ 0.0      ┆ 0     ┆ 0.0 │
├╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌┼╌╌╌╌╌┤
│ 0.833333 ┆ 0.833333 ┆ 0.833333 ┆ 0.833333 ┆ x   ┆ 0.833333 ┆ 0     ┆ 0.0 │
├╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌┼╌╌╌╌╌┤
│ 2.5      ┆ 2.5      ┆ 2.5      ┆ 2.5      ┆ x   ┆ 2.5      ┆ 3     ┆ 2.6 │
├╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌┼╌╌╌╌╌┤
│ 3.333333 ┆ 3.333333 ┆ 3.333333 ┆ 3.333333 ┆ y   ┆ 3.333333 ┆ 1     ┆ 3.4 │
├╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌┼╌╌╌╌╌┤
│ 4.166667 ┆ 4.166667 ┆ 4.166667 ┆ 4.166667 ┆ y   ┆ 4.166667 ┆ 2     ┆ 4.0 │
└──────────┴──────────┴──────────┴──────────┴─────┴──────────┴───────┴─────┘

dirty_lf1:

shape: (2, 8)
┌──────────┬──────────┬──────────┬──────┬─────┬──────────┬───────┬──────┐
│ l        ┆ m        ┆ a        ┆ b    ┆ c   ┆ d        ┆ group ┆ val  │
│ ---      ┆ ---      ┆ ---      ┆ ---  ┆ --- ┆ ---      ┆ ---   ┆ ---  │
│ f64      ┆ f64      ┆ f64      ┆ f64  ┆ str ┆ f64      ┆ i64   ┆ f64  │
╞══════════╪══════════╪══════════╪══════╪═════╪══════════╪═══════╪══════╡
│ 1.666667 ┆ 1.666667 ┆ 1.666667 ┆ null ┆ x   ┆ 1.666667 ┆ null  ┆ null │
├╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌┼╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌┼╌╌╌╌╌╌┤
│ 5.0      ┆ 5.0      ┆ 5.0      ┆ null ┆ y   ┆ 5.0      ┆ null  ┆ null │
└──────────┴──────────┴──────────┴──────┴─────┴──────────┴───────┴──────┘

concatted:

shape: (7, 8)
┌──────────┬──────────┬──────────┬──────────┬─────┬──────────┬───────┬──────┐
│ l        ┆ m        ┆ a        ┆ b        ┆ c   ┆ d        ┆ group ┆ val  │
│ ---      ┆ ---      ┆ ---      ┆ ---      ┆ --- ┆ ---      ┆ ---   ┆ ---  │
│ f64      ┆ f64      ┆ f64      ┆ f64      ┆ str ┆ f64      ┆ i64   ┆ f64  │
╞══════════╪══════════╪══════════╪══════════╪═════╪══════════╪═══════╪══════╡
│ 0.0      ┆ 0.0      ┆ 0.0      ┆ 0.0      ┆ x   ┆ 0.0      ┆ 0     ┆ 0.0  │
├╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌┼╌╌╌╌╌╌┤
│ 0.833333 ┆ 0.833333 ┆ 0.833333 ┆ 0.833333 ┆ x   ┆ 0.833333 ┆ 0     ┆ 0.0  │
├╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌┼╌╌╌╌╌╌┤
│ 2.5      ┆ 2.5      ┆ 2.5      ┆ 2.5      ┆ x   ┆ 2.5      ┆ 3     ┆ 2.6  │
├╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌┼╌╌╌╌╌╌┤
│ 3.333333 ┆ 3.333333 ┆ 3.333333 ┆ 3.333333 ┆ y   ┆ 3.333333 ┆ 1     ┆ 3.4  │
├╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌┼╌╌╌╌╌╌┤
│ 4.166667 ┆ 4.166667 ┆ 4.166667 ┆ 4.166667 ┆ y   ┆ 4.166667 ┆ 2     ┆ 4.0  │
├╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌┼╌╌╌╌╌╌┤
│ 1.666667 ┆ 1.666667 ┆ 1.666667 ┆ null     ┆ x   ┆ 1.666667 ┆ null  ┆ null │
├╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌┼╌╌╌╌╌╌┤
│ 5.0      ┆ 5.0      ┆ 5.0      ┆ null     ┆ y   ┆ 5.0      ┆ null  ┆ null │
└──────────┴──────────┴──────────┴──────────┴─────┴──────────┴───────┴──────┘
```

### Expected behavior

If we set `projection_pushdown=False` on collect, this is what we get:

```
shape: (7, 5)
┌───────┬──────────┬──────────┬──────┬──────────┐
│ group ┆ l        ┆ b        ┆ val  ┆ a        │
│ ---   ┆ ---      ┆ ---      ┆ ---  ┆ ---      │
│ i64   ┆ f64      ┆ f64      ┆ f64  ┆ f64      │
╞═══════╪══════════╪══════════╪══════╪══════════╡
│ 0     ┆ 0.0      ┆ 0.0      ┆ 0.0  ┆ 0.0      │
├╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌┤
│ 0     ┆ 0.833333 ┆ 0.833333 ┆ 0.0  ┆ 0.833333 │
├╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌┤
│ 3     ┆ 2.5      ┆ 2.5      ┆ 2.6  ┆ 2.5      │
├╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌┤
│ 1     ┆ 3.333333 ┆ 3.333333 ┆ 3.4  ┆ 3.333333 │
├╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌┤
│ 2     ┆ 4.166667 ┆ 4.166667 ┆ 4.0  ┆ 4.166667 │
├╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌┤
│ null  ┆ 1.666667 ┆ null     ┆ null ┆ 1.666667 │
├╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌┤
│ null  ┆ 5.0      ┆ null     ┆ null ┆ 5.0      │
└───────┴──────────┴──────────┴──────┴──────────┘
```

### Installed versions

<details>

```
---Version info---
Polars: 0.14.26
Index type: UInt32
Python: 3.10.8 (main, Oct 17 2022, 08:09:04) [GCC 8.3.0]
---Optional dependencies---
pyarrow: 7.0.0
pandas: 1.5.1
numpy: 1.23.2
fsspec: 2022.5.0
connectorx: <not installed>
xlsx2csv: <not installed>
matplotlib: 3.5.2
```

</details>

**Comment by ghuls** [comment]
Can you try with the latest version? There are some releases since the version that you used.

**Comment by OneRaynyDay** [comment]
Yup, tried this earlier today - this also fails on v0.15.2

**Comment by OneRaynyDay** [comment]
```
---Version info---
Polars: 0.15.2
Index type: UInt32
Python: 3.10.8 (main, Oct 17 2022, 08:09:04) [GCC 8.3.0]
---Optional dependencies---
pyarrow: 7.0.0
pandas: 1.5.1
numpy: 1.23.2
fsspec: 2022.5.0
connectorx: <not installed>
xlsx2csv: <not installed>
matplotlib: 3.5.2
Traceback (most recent call last):
  File "/tmp/repro.py", line 46, in <module>
    concatted.select(["group", "l", "b", "val", "a"]).collect()
  File "/usr/scratch/.../lib/python3.10/site-packages/polars/utils.py", line 310, in wrapper
    return fn(*args, **kwargs)
  File "/usr/scratch/.../lib/python3.10/site-packages/polars/internals/lazyframe/frame.py", line 1164, in collect
    return pli.wrap_df(ldf.collect())
exceptions.ShapeError: Could not vertically stack DataFrame. The DataFrames appended width 6 differs from the parent DataFrames width 5
```
