### ISSUE TITLE
Cannot pass out argument to numpy ufunc applied to polars series

### ISSUE THREAD

**Issue by abalkin** [pola-rs/polars#5820]
### Polars version checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pypi.org/project/polars/) of Polars.

### Issue description

A TypeError is triggered when output array is provided to a numpy ufunc applied to polars series.

### Reproducible example

```python
>>> import polars as pl
>>> import numpy as np
>>> x = pl.Series([0.0])
>>> y = np.empty(1)
>>> np.exp(x, out=y)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "polars/internals/series/series.py", line 948, in __array_ufunc__
    series = f(lambda out: ufunc(*args, out=out, dtype=dtype_char, **kwargs))
  File "polars/internals/series/series.py", line 948, in <lambda>
    series = f(lambda out: ufunc(*args, out=out, dtype=dtype_char, **kwargs))
TypeError: <ufunc 'exp'> got multiple values for keyword argument 'out'
```

### Expected behavior

Polars series should behave lik numpy array when passed to a ufunc. 

```python
>>> a = np.array([0.0])
>>> np.exp(a, out=y)
array([1.])
```

### Installed versions

<details>

```
>>> pl.show_versions()
---Version info---
Polars: 0.15.6
Index type: UInt32
Platform: macOS-12.6.1-arm64-arm-64bit
Python: 3.9.7 (default, Dec 10 2022, 12:30:56)
[Clang 13.1.6 (clang-1316.0.21.2.5)]
---Optional dependencies---
pyarrow: 10.0.1
pandas: 1.4.4
numpy: 1.23.5
fsspec: 2022.11.0
connectorx: 0.3.1
xlsx2csv: <not installed>
matplotlib: 3.5.3
```

</details>

**Comment by ghuls** [comment]
`np.expr(a)` returns a Series. If you want to write yourself to a numpy output array, convert your series to numpy: `np.expr(a.to_numpy(), out=y)`

**Comment by abalkin** [comment]
@ghuls - I am actually trying to write back to a series and writing to an array was just a simple way to demonstrate the issue.

At a minimum the error message is wrong. Instead of:

```python
TypeError: <ufunc 'exp'> got multiple values for keyword argument 'out'
```

Something along the lines of "Passing output array to ufunc is not supported when input is a polars series" would be better.
However, why not just support it?

**Comment by ghuls** [comment]
Polars is using the out argument internally to get the numpy array output of the function.

**Comment by abalkin** [comment]
> Polars is using the out argument internally 

@ghuls - I've seen polars code implementing ufunc application.  Your explanation of the current behavior is correct, but it does not make the behavior itself correct.  Fixing this bug will require changing how  Polars is using the out argument internally.

**Comment by ghuls** [comment]
I am not sure this is the correct approach as it creates some inconsistencies.
 - It would allow to write to a preallocated numpy array, when passed `out=some_array`
 - If `out=None` it would return a Series instead of a numpy array.

To be consistent if `out=None` is defined, it should also return a numpy array, and if no `out` argument is provided, it should return a Polars Series, but that seems not be possible as numpy does not seem to pass the out argument from the ufunc when `out=None`.

**Comment by abalkin** [comment]
I don't understand what does not seem possible.  I am proposing to implement the behavior that already exists in numpy. 

```python
In [1]: import numpy as np

In [2]: import numpy.ma as ma

In [3]: a = ma.array([1.0], mask=[1])

In [4]: b = np.empty(1)

In [5]: np.exp(a)                    # return newly allocated masked array
Out[5]:
masked_array(data=[--],
             mask=[ True],
       fill_value=1e+20,
            dtype=float64)

In [6]: np.exp(a, out=b)             # return passed in numpy array
Out[6]: array([2.71828183])

In [7]: _ is b
Out[7]: True
```

**Comment by zundertj** [comment]
The problem is the inconsistency in return type:

```python
>>> type(np.exp(x))
<class 'polars.internals.series.series.Series'>

>>> type(np.exp(x, out=y))  # does not work now, but under your proposal
<class 'numpy.ndarray'>
```

We can add a check on the input argument `out` as you say, but I don't see us supporting the above behaviour, the inconsistency will lead to surprises. Although Polars Series and Numpy arrays go well together, one should not mindlessly mingle the two.
