### ISSUE TITLE
Panic on sorting empty df by object dtype

### ISSUE THREAD

**Issue by dgilman** [pola-rs/polars#5964]
### Polars version checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pypi.org/project/polars/) of Polars.

### Issue description

You can sort on an object dtype with `apply()` and that works fine. But if the dataframe is empty, Polars panics.

```
thread '<unnamed>' panicked at 'this operation is not implemented/valid for this dtype: Object("object")', /Users/runner/work/polars/polars/polars/polars-core/src/series/series_trait.rs:418:9
stack backtrace:
   0:        0x10b6a267a - _ffi_select_with_compiled_path
   1:        0x10a3d877a - _BrotliDecoderVersion
   2:        0x10b678884 - _ffi_select_with_compiled_path
   3:        0x10b6a3d6a - _ffi_select_with_compiled_path
   4:        0x10b6a3993 - _ffi_select_with_compiled_path
   5:        0x10b6a49d5 - _ffi_select_with_compiled_path
   6:        0x10b6a44c5 - _ffi_select_with_compiled_path
   7:        0x10b6a4430 - _ffi_select_with_compiled_path
   8:        0x10b6a4402 - _ffi_select_with_compiled_path
   9:        0x10b7cee63 - _ffi_select_with_compiled_path
  10:        0x10b2d3551 - _ffi_select_with_compiled_path
  11:        0x10ab11afd - _ffi_select_with_compiled_path
  12:        0x10b1e6013 - _ffi_select_with_compiled_path
  13:        0x10b1e5696 - _ffi_select_with_compiled_path
  14:        0x10b189e19 - _ffi_select_with_compiled_path
  15:        0x109ef5169 - _PyInit_polars
  16:        0x10921ee28 - _method_vectorcall_VARARGS_KEYWORDS
  17:        0x10930e031 - _call_function
  18:        0x109305e32 - __PyEval_EvalFrameDefault
  19:        0x109300088 - __PyEval_EvalCode
  20:        0x109213819 - __PyFunction_Vectorcall
  21:        0x10921342f - _PyVectorcall_Call
  22:        0x109306159 - __PyEval_EvalFrameDefault
  23:        0x109300088 - __PyEval_EvalCode
  24:        0x109213819 - __PyFunction_Vectorcall
  25:        0x109216324 - _method_vectorcall
  26:        0x10930e031 - _call_function
  27:        0x109305ecb - __PyEval_EvalFrameDefault
  28:        0x109300088 - __PyEval_EvalCode
  29:        0x109213819 - __PyFunction_Vectorcall
  30:        0x10930e031 - _call_function
  31:        0x109305e32 - __PyEval_EvalFrameDefault
  32:        0x109300088 - __PyEval_EvalCode
  33:        0x10935bcc4 - _run_eval_code_obj
  34:        0x10935bc2a - _run_mod
  35:        0x1093593dd - _pyrun_file
  36:        0x109358dd7 - _pyrun_simple_file
  37:        0x109358ca1 - _PyRun_SimpleFileExFlags
  38:        0x109377ba0 - _pymain_run_file
  39:        0x109377424 - _Py_RunMain
  40:        0x109378511 - _pymain_main
  41:        0x1093787d7 - _Py_BytesMain
Traceback (most recent call last):
  File "polars_test.py", line 21, in <module>
    df_filtered.sort(pl.col('blob').apply(lambda blob: blob['sort_key']))
  File "venv/lib/python3.9/site-packages/polars/internals/dataframe/frame.py", line 2870, in sort
    df = self.lazy().sort(by, reverse, nulls_last).collect(no_optimization=True)
  File "venv/lib/python3.9/site-packages/polars/utils.py", line 337, in wrapper
    return fn(*args, **kwargs)
  File "venv/lib/python3.9/site-packages/polars/internals/lazyframe/frame.py", line 1177, in collect
    return pli.wrap_df(ldf.collect())
pyo3_runtime.PanicException: this operation is not implemented/valid for this dtype: Object("object")
```

### Reproducible example

```python
import polars as pl

df = pl.DataFrame(
        data=[
            ({"name": "bar", "sort_key": 2},),
            ({"name": "foo", "sort_key": 1},),
        ],
        columns=[
            ("blob", pl.Object),
        ],
        orient="row"
)


df_filtered = df.filter(pl.col('blob').apply(lambda blob: blob['name'] == 'baz'))

print('this works')
df.sort(pl.col('blob').apply(lambda blob: blob['sort_key']))
print('this does not')
df_filtered.sort(pl.col('blob').apply(lambda blob: blob['sort_key']))
```

### Expected behavior

no crash, empty df is passed through

### Installed versions

<details>

```
---Version info---
Polars: 0.15.9
Index type: UInt32
Platform: macOS-10.15.7-x86_64-i386-64bit
Python: 3.9.16 (main, Dec  7 2022, 02:40:58)
[Clang 11.0.3 (clang-1103.0.32.62)]
---Optional dependencies---
pyarrow: <not installed>
pandas: <not installed>
numpy: <not installed>
fsspec: <not installed>
connectorx: <not installed>
xlsx2csv: <not installed>
matplotlib: <not installed>```

</details>

**Comment by dgilman** [comment]
I tested this on 0.15.0 and it panicked the same there, this does not appear to be a regression from the other empty dataframe related bug fixed in 0.15.9
