### ISSUE TITLE
Groupby/agg on pl.LazyFrame fails when a column is added using .with_column()

### ISSUE THREAD

**Issue by jkc1** [pola-rs/polars#6054]
### Polars version checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pypi.org/project/polars/) of Polars.

### Issue description

I've got some code that essentially does the following:
  - Reads some data into a pl.LazyFrame
  - Appends a pl.Series to the pl.LazyFrame using pl.LazyFrame.with_column()
  - Does a .groupby().agg().collect()

This code worked fine until I updated my dependencies from 0.14.30 to 0.15. The [documentation](https://pola-rs.github.io/polars/py-polars/html/reference/lazyframe/api/polars.LazyFrame.with_column.html) appears to indicate that this behavior should still work, so I believe this is a bug.

A minimal working example and the traceback is below.

### Reproducible example

```python
import polars as pl

df = pl.DataFrame({"col_1": [0] * 5 + [1] * 5})
ser = pl.Series("col_2", list(range(10)))

# these three lines below work as expected
#df.lazy().groupby("col_1").agg(pl.col("*").count()).collect()
#df.lazy().with_column(ser).collect()
#df.with_column(ser).groupby("col_1").agg(pl.col("*").count())

# this works in <0.15 but raises an exception in >=0.15
df.lazy().with_column(ser).groupby("col_1").agg(pl.col("*").count()).collect()
```

### Expected behavior

Actual output:
```
Traceback (most recent call last):
  File ".../bug_example.py", line 15, in <module>
    df.lazy().with_column(ser).groupby("col_1").agg(pl.col("*").count()).collect()
  File ".../.venv/lib/python3.9/site-packages/polars/utils.py", line 337, in wrapper
    return fn(*args, **kwargs)
  File ".../.venv/lib/python3.9/site-packages/polars/internals/lazyframe/frame.py", line 1154, in collect
    return pli.wrap_df(ldf.collect())
exceptions.ShapeError: Could not add column. The Series length 10 differs from the DataFrame height: 1
```

Expected output: nothing

### Installed versions

<details>

```
---Version info---
Polars: 0.15.11
Index type: UInt32
Platform: macOS-12.6.2-x86_64-i386-64bit
Python: 3.9.16 (main, Dec  8 2022, 10:02:15) 
[Clang 14.0.0 (clang-1400.0.29.202)]
---Optional dependencies---
pyarrow: <not installed>
pandas: <not installed>
numpy: <not installed>
fsspec: <not installed>
connectorx: <not installed>
xlsx2csv: <not installed>
matplotlib: <not installed>
None
```

</details>

**Comment by jkc1** [comment]
Thanks for the extremely quick fix!
