### ISSUE TITLE
reading Binary column fails

### ISSUE THREAD

**Issue by kesavkolla** [pola-rs/polars#6072]
### Polars version checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pypi.org/project/polars/) of Polars.

### Issue description

I have field in my parquet with the following schema:

```
List(Struct([Field('id': Utf8), Field('extension': List(Utf8)), Field('contentType': Utf8), Field('language': Utf8), Field('data': Binary), Field('url': Utf8), Field('size': Int32), Field('hash': Binary), Field('title': Utf8), Field('creation': Datetime(tu='ns', tz=None))]))
```

When I try to read this field I get the following error:

```
thread '<unnamed>' panicked at 'called `Result::unwrap()` on an `Err` value: OutOfSpec("The children DataTypes of a StructArray must equal the children data types. \n                         However, the field 4 has data type LargeBinary but the value has data type Binary")', /root/.cargo/git/checkouts/arrow2-945af624853845da/baa2618/src/array/struct_/mod.rs:120:52
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/kesav/.conda/envs/datalake/lib/python3.9/site-packages/polars/utils.py", line 337, in wrapper
    return fn(*args, **kwargs)
  File "/home/kesav/.conda/envs/datalake/lib/python3.9/site-packages/polars/io.py", line 963, in read_parquet
    return DataFrame._read_parquet(
  File "/home/kesav/.conda/envs/datalake/lib/python3.9/site-packages/polars/internals/dataframe/frame.py", line 674, in _read_parquet
    self._df = PyDataFrame.read_parquet(
pyo3_runtime.PanicException: called `Result::unwrap()` on an `Err` value: OutOfSpec("The children DataTypes of a StructArray must equal the children data types. \n                         However, the field 4 has data type LargeBinary but the value has data type Binary")
```

As far I know this field doesn't have any data at all in the parquet file. All the data is null for this column.

### Reproducible example

```python
import polars as pl
schema = pl.read_parquet_schema('/home/kesav/Downloads/part-00000-46637011-9426-41d3-9988-c00d56007803-c000.snappy.parquet')
schema.get('photo')
df = pl.read_parquet('/home/kesav/Downloads/part-00000-46637011-9426-41d3-9988-c00d56007803-c000.snappy.parquet', ['photo'])
```

### Expected behavior

The data frame should be created.

### Installed versions

<details>

```
---Version info---
Polars: 0.15.11
Index type: UInt32
Platform: Linux-5.15.0-56-generic-x86_64-with-glibc2.35
Python: 3.9.5 | packaged by conda-forge | (default, Jun 19 2021, 00:32:32) 
[GCC 9.3.0]
---Optional dependencies---
pyarrow: 10.0.1
pandas: 1.3.2
numpy: 1.21.2
fsspec: 2022.8.2
connectorx: <not installed>
xlsx2csv: <not installed>
matplotlib: <not installed>

```

</details>

**Comment by ritchie46** [comment]
Can you share the file?

**Comment by kesavkolla** [comment]
Attaching the parquet file.

I had to zip the file as github is not allowing me to upload the actual parquet file as is. You just have to unzip the file to get the actual parquet file.

[part-00000-0c119376-450f-4aa4-8191-6a42b2fe4993-c000.snappy.parquet.zip](https://github.com/pola-rs/polars/files/10363289/part-00000-0c119376-450f-4aa4-8191-6a42b2fe4993-c000.snappy.parquet.zip)

**Comment by ritchie46** [comment]
> part-00000-0c119376-450f-4aa4-8191-6a42b2fe4993-c000.snappy.parquet.zip

I see that the file is incorrectly read by our parquet reader. You can read it when you set `use_pyarrow=True`.

**Comment by ritchie46** [comment]
This has been fixed.
