### ISSUE TITLE
Unable to load Feather v2 files created by pyarrow and pandas.

### ISSUE THREAD

**Issue by ghuls** [pola-rs/polars#623]
#### Are you using Python or Rust?

Python

#### What version of polars are you using?

0.7.14

#### What operating system are you using polars on?
Ubuntu 20.04

#### Describe your bug.

Unable to load Feather v2 files created by pyarrow and pandas.

#### What are the steps to reproduce the behavior?

```
import polars as pl
import pyarrow as pa
import pandas as pd

# Reading Feather file created with Pandas with pyarrow works fine.
df_pa = pa.feather.read_feather('test_pandas.feather')

# Write pyarrow dataframe to Feather file.
df_pa.to_feather('test_arrow.feather')

# Convert pyarrow dataframe to polars dataframe.
df_pl = pl.DataFrame(df_pa)

# Convert polars dataframe to pandas dataframe.
df_pd = df_pl.to_pandas()

# Write pandas dataframe  to feather file.
df_pd.to_feather('test_pandas_from_polars.feather')


In [88]: df_pa
Out[88]: 
   motif1  motif2  motif3  motif4 regions
0     1.2     3.0     0.3     5.6    reg1
1     6.7     3.0     4.3     5.6    reg2
2     3.5     3.0     0.0     0.0    reg3
3     0.0     3.0     0.0     5.6    reg4
4     2.4     3.0     7.8     1.2    reg5
5     2.4     3.0     0.6     0.0    reg6
6     2.4     3.0     7.7     0.0    reg7

In [89]: df_pl
Out[89]: 
shape: (7, 5)
╭────────┬────────┬────────┬────────┬─────────╮
│ motif1 ┆ motif2 ┆ motif3 ┆ motif4 ┆ regions │
│ ---    ┆ ---    ┆ ---    ┆ ---    ┆ ---     │
│ f64    ┆ f64    ┆ f64    ┆ f64    ┆ str     │
╞════════╪════════╪════════╪════════╪═════════╡
│ 1.2    ┆ 3      ┆ 0.3    ┆ 5.6    ┆ "reg1"  │
├╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌┤
│ 6.7    ┆ 3      ┆ 4.3    ┆ 5.6    ┆ "reg2"  │
├╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌┤
│ 3.5    ┆ 3      ┆ 0.0    ┆ 0.0    ┆ "reg3"  │
├╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌┤
│ 0.0    ┆ 3      ┆ 0.0    ┆ 5.6    ┆ "reg4"  │
├╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌┤
│ 2.4    ┆ 3      ┆ 7.8    ┆ 1.2    ┆ "reg5"  │
├╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌┤
│ 2.4    ┆ 3      ┆ 0.6    ┆ 0.0    ┆ "reg6"  │
├╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌┤
│ 2.4    ┆ 3      ┆ 7.7    ┆ 0.0    ┆ "reg7"  │
╰────────┴────────┴────────┴────────┴─────────╯

In [90]: df_pd
Out[90]: 
   motif1  motif2  motif3  motif4 regions
0     1.2     3.0     0.3     5.6    reg1
1     6.7     3.0     4.3     5.6    reg2
2     3.5     3.0     0.0     0.0    reg3
3     0.0     3.0     0.0     5.6    reg4
4     2.4     3.0     7.8     1.2    reg5
5     2.4     3.0     0.6     0.0    reg6
6     2.4     3.0     7.7     0.0    reg7



In [103]: pl.read_ipc('test_polars.feather')
Out[103]: 
shape: (7, 5)
╭────────┬────────┬────────┬────────┬─────────╮
│ motif1 ┆ motif2 ┆ motif3 ┆ motif4 ┆ regions │
│ ---    ┆ ---    ┆ ---    ┆ ---    ┆ ---     │
│ f64    ┆ f64    ┆ f64    ┆ f64    ┆ str     │
╞════════╪════════╪════════╪════════╪═════════╡
│ 1.2    ┆ 3      ┆ 0.3    ┆ 5.6    ┆ "reg1"  │
├╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌┤
│ 6.7    ┆ 3      ┆ 4.3    ┆ 5.6    ┆ "reg2"  │
├╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌┤
│ 3.5    ┆ 3      ┆ 0.0    ┆ 0.0    ┆ "reg3"  │
├╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌┤
│ 0.0    ┆ 3      ┆ 0.0    ┆ 5.6    ┆ "reg4"  │
├╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌┤
│ 2.4    ┆ 3      ┆ 7.8    ┆ 1.2    ┆ "reg5"  │
├╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌┤
│ 2.4    ┆ 3      ┆ 0.6    ┆ 0.0    ┆ "reg6"  │
├╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌┤
│ 2.4    ┆ 3      ┆ 7.7    ┆ 0.0    ┆ "reg7"  │
╰────────┴────────┴────────┴────────┴─────────╯

In [104]: pl.read_ipc('test_arrow.feather')
thread '<unnamed>' panicked at 'assertion failed: prefix.is_empty() && suffix.is_empty()', /github/home/.cargo/git/checkouts/arrow-rs-3b86e19e889d5acc/d008f31/arrow/src/buffer/immutable.rs:179:9
---------------------------------------------------------------------------
PanicException                            Traceback (most recent call last)
<ipython-input-104-f9a22f9a0eb1> in <module>
----> 1 pl.read_ipc('test_arrow.feather')

~/software/anaconda3/envs/create_cistarget_databases/lib/python3.8/site-packages/polars/functions.py in read_ipc(file)
    278     """
    279     file = _prepare_file_arg(file)
--> 280     return DataFrame.read_ipc(file)
    281 
    282 

~/software/anaconda3/envs/create_cistarget_databases/lib/python3.8/site-packages/polars/frame.py in read_ipc(file)
    235         """
    236         self = DataFrame.__new__(DataFrame)
--> 237         self._df = PyDataFrame.read_ipc(file)
    238         return self
    239 

PanicException: assertion failed: prefix.is_empty() && suffix.is_empty()

In [105]: pl.read_ipc('test_pandas.feather')
thread '<unnamed>' panicked at 'assertion failed: prefix.is_empty() && suffix.is_empty()', /github/home/.cargo/git/checkouts/arrow-rs-3b86e19e889d5acc/d008f31/arrow/src/buffer/immutable.rs:179:9
---------------------------------------------------------------------------
PanicException                            Traceback (most recent call last)
<ipython-input-105-35809d9ae65f> in <module>
----> 1 pl.read_ipc('test_pandas.feather')

~/software/anaconda3/envs/create_cistarget_databases/lib/python3.8/site-packages/polars/functions.py in read_ipc(file)
    278     """
    279     file = _prepare_file_arg(file)
--> 280     return DataFrame.read_ipc(file)
    281 
    282 

~/software/anaconda3/envs/create_cistarget_databases/lib/python3.8/site-packages/polars/frame.py in read_ipc(file)
    235         """
    236         self = DataFrame.__new__(DataFrame)
--> 237         self._df = PyDataFrame.read_ipc(file)
    238         return self
    239 

PanicException: assertion failed: prefix.is_empty() && suffix.is_empty()

In [106]: pl.read_ipc('test_pandas_from_polars.feather')
thread '<unnamed>' panicked at 'assertion failed: prefix.is_empty() && suffix.is_empty()', /github/home/.cargo/git/checkouts/arrow-rs-3b86e19e889d5acc/d008f31/arrow/src/buffer/immutable.rs:179:9
---------------------------------------------------------------------------
PanicException                            Traceback (most recent call last)
<ipython-input-107-d0a17f51c6ac> in <module>
----> 1 pl.read_ipc('test_pandas_from_polars.feather')

~/software/anaconda3/envs/create_cistarget_databases/lib/python3.8/site-packages/polars/functions.py in read_ipc(file)
    278     """
    279     file = _prepare_file_arg(file)
--> 280     return DataFrame.read_ipc(file)
    281 
    282 

~/software/anaconda3/envs/create_cistarget_databases/lib/python3.8/site-packages/polars/frame.py in read_ipc(file)
    235         """
    236         self = DataFrame.__new__(DataFrame)
--> 237         self._df = PyDataFrame.read_ipc(file)
    238         return self
    239 

PanicException: assertion failed: prefix.is_empty() && suffix.is_empty()

```

#### What is the expected behavior?

What do you think polars should have done?

Load the feather v2 files created by pyarrow, pandas and not just by polars itself.

**Comment by ghuls** [comment]
[test_feather_file.zip](https://github.com/pola-rs/polars/files/6451392/test_feather_file.zip)

**Comment by ritchie46** [comment]
Right, we could add a `pyarrow` backend for this as well. Thanks for your bug report.

**Comment by ritchie46** [comment]
My bad, I wrongly assumed that it would return a table. Will fix this.
