### ISSUE TITLE
`polars::frame::csv::CsvReader` multiple issues

### ISSUE THREAD

**Issue by Darqon96** [pola-rs/polars#6276]
### Polars version checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://crates.io/crates/polars) of Polars.

### Issue description

I have found multiple issues when trying to read classic [Auto MPG](https://archive.ics.uci.edu/ml/datasets/auto+mpg) dataset from [Tensorflow `Basic regression: Predict fuel efficiency` tutorial](https://www.tensorflow.org/tutorials/keras/regression).

There you can see that this [dataset was nicely loaded with `pandas.read_csv` method](https://colab.research.google.com/github/tensorflow/docs/blob/master/site/en/tutorials/keras/regression.ipynb#scrollTo=CiX2FI4gZtTt&line=5&uniqifier=1)

I was trying to achieve the same behaviour using Rust version of `polars`, but I was blocked by multiple issues:
### 1. Multiple-character delimiters
This dataset file columns are delimited by multiple spaces, I couldn't set multiple spaces as delimiters nor I couldn't find the substitute of pandas `skipinitialspace` argument in `polars  CsvReader`, so I have set single space as a delimiter: `.with_delimiter(b' ')`, but the file wasn't loaded properly, even without schema. 

With schema provided, it doesn't even load at all (which is expected I think).
I thought that feature of multi-length delimiters isn't implemented in `polars`, but I found [this issue on this topic](https://github.com/pola-rs/polars/issues/3147#issuecomment-1100860234), so I think it should work in `polars = "0.26.1"` which I'm using.

---
After pre-parsing the dataset file (which I would want to avoid), changing delimiters to single `,` character, I was able to load the file correctly, but found other issues

### 2. Comment char not working 
Comment char ` .with_comment_char(Some(b'\t'))` seems to be not working with this dataset, but it probably should.

### 3. `UInt8` column type doesn't work
Schema seems to be not working when it comes to `UInt8` values, when the column contains values which should fit in the `UInt8`, e.g. `origin` column no. 7 (counting from 0). It works when `Int64` is specified as the type of this column in the schema, but doesn't work for `UInt8` - a lot of space could be saved if that would work as far as I understand.

Maybe these issues come from my misunderstanding of `polars` usage or my small experience will Rust language. 
I would be thankful if someone from development team would confirm the issues or point me towards the result that I want to achieve.

### Reproducible example

Paste code below into `main.rs` and put alongside the extracted `auto-mpg.data` dataset file, then run `main.rs`.

```rust
use std::path::Path;

use polars::prelude::*;
use polars::datatypes::DataType::{Int64, Float64};


fn main() {
    let dataset_file_path: &Path = Path::new("auto-mpg.data");
    let dataset: DataFrame = read_data_frame_from_csv(dataset_file_path);
    println!("{dataset:#?}");
}


fn read_data_frame_from_csv(
    csv_file_path: &Path,
) -> DataFrame {
    let mut schema: Schema = Schema::new();
    schema.with_column(String::from("MPG"), Float64);
    schema.with_column(String::from("Cylinders"), Int64);
    schema.with_column(String::from("Displacement"), Float64);
    schema.with_column(String::from("Horsepower"), Float64);
    schema.with_column(String::from("Weight"), Float64);
    schema.with_column(String::from("Acceleration"), Float64);
    schema.with_column(String::from("Model Year"), Int64);
    schema.with_column(String::from("Origin"), Int64);

    return CsvReader::from_path(csv_file_path)
        .unwrap()
        .has_header(false)
        .with_delimiter(b' ')
        .with_comment_char(Some(b'\t'))
        .with_null_values(Some(NullValues::AllColumnsSingle(String::from("?"))))
        .with_schema(&schema)
        .finish()
        .unwrap();
}
```
[auto-mpg.zip](https://github.com/pola-rs/polars/files/10429485/auto-mpg.zip)

### Expected behavior

Output of `println!` macro should be similar to the [output of `dataset.tail()` in the Tensorflow tutorial](https://colab.research.google.com/github/tensorflow/docs/blob/master/site/en/tutorials/keras/regression.ipynb#scrollTo=2oY3pMPagJrO&line=1&uniqifier=1)

### Installed versions

<details>
polars = "0.26.1"
</details>

**Comment by kylebarron** [comment]
For uint8 you need to check that you've enabled the rust feature flag for that data type

**Comment by Darqon96** [comment]
Thanks @kylebarron I will check it out, as far as I understand I need to use `dtype-u8` feature flag?
Where can I find documentation about polars feature flags, I was only being able to find the list of all polars feature flags, but without explanation.

Hi @ritchie46, no problem I will check it out, as well as @kylebarron suggestion regarding UInt8 support. 

I will probably do it today at 8 PM, CET, UTC+1.

Thank you both for support

**Comment by Darqon96** [comment]
> For uint8 you need to check that you've enabled the rust feature flag for that data type

Sadly, it still doesn't work even after adding `dtype-u8` feature flag
My `polars` entry in `Cargo.toml` file:
```toml
polars = { version="0.26.1", features=["dtype-u8"] }
```

I have created unit-test to test this behaviour and it fails - now anyone can reproduce it:
```rust
#[cfg(test)]
mod test_polars_csv_reader {
    use std::{
        fs,
        path::Path,
    };

    use polars::{
        prelude::*,
        datatypes::DataType::{UInt8, Float64},
    };


    fn write_file(path: &Path, data: &str) {
        return fs::write(path, data).expect("Unable to write file");
    }


    fn prepare_schema() -> Schema {
        let mut schema: Schema = Schema::new();
        Schema::new();

        schema.with_column(String::from("MPG"), Float64);
        schema.with_column(String::from("Cylinders"), UInt8);
        schema.with_column(String::from("Displacement"), Float64);
        schema.with_column(String::from("Horsepower"), Float64);
        schema.with_column(String::from("Weight"), Float64);
        schema.with_column(String::from("Acceleration"), Float64);
        schema.with_column(String::from("Model Year"), UInt8);
        schema.with_column(String::from("Origin"), UInt8);

        return schema;
    }


    #[test]
    fn test_uint8_fields_are_correctly_loaded() {
        // Arrange
        let data_to_save = "\
            18.0,8,307.0,130.0,3504.,12.0,70,1\n\
            15.0,8,350.0,165.0,3693.,11.5,70,1\n\
        ";
        let dataset_file_path = Path::new("auto-mpg.data");
        write_file(dataset_file_path, data_to_save);

        let schema = prepare_schema();
        let expected_data: DataFrame = df!(
            "MPG" => &[18.0f64, 15.0f64],
            "Cylinders" => &[8u8, 8u8],
            "Displacement" => &[307.0f64, 350.0f64],
            "Horsepower" => &[130.0f64, 165.0f64],
            "Weight" => &[3504.0f64, 3693.0f64],
            "Acceleration" => &[12.0f64, 11.5f64],
            "Model Year" => &[70u8, 70u8],
            "Origin" => &[1u8, 1u8],
        ).unwrap();

        // Act
        let data = CsvReader::from_path(dataset_file_path)
            .unwrap()
            .has_header(false)
            .with_delimiter(b',')
            .with_schema(&schema)
            .finish()
            .unwrap();

        // Assert
        assert_eq!(expected_data, data);
    }
}
```

Now everyone can reproduce the bug, it results in following error logs:
```bash
thread 'test_polars_csv_reader::test_uint8_fields_are_correctly_loaded' panicked at 'called `Result::unwrap()` on an `Err` value: ComputeError(Owned("Unsupported data type UInt8 when reading a csv"))', src/main.rs:69:14
stack backtrace:
   0: rust_begin_unwind
             at /rustc/69f9c33d71c871fc16ac445211281c6e7a340943/library/std/src/panicking.rs:575:5
   1: core::panicking::panic_fmt
             at /rustc/69f9c33d71c871fc16ac445211281c6e7a340943/library/core/src/panicking.rs:65:14
   2: core::result::unwrap_failed
             at /rustc/69f9c33d71c871fc16ac445211281c6e7a340943/library/core/src/result.rs:1791:5
   3: core::result::Result<T,E>::unwrap
             at /rustc/69f9c33d71c871fc16ac445211281c6e7a340943/library/core/src/result.rs:1113:23
   4: fuel_efficiency_predictor::test_polars_csv_reader::test_uint8_fields_are_correctly_loaded
             at ./src/main.rs:62:20
   5: fuel_efficiency_predictor::test_polars_csv_reader::test_uint8_fields_are_correctly_loaded::{{closure}}
             at ./src/main.rs:40:5
   6: core::ops::function::FnOnce::call_once
             at /rustc/69f9c33d71c871fc16ac445211281c6e7a340943/library/core/src/ops/function.rs:251:5
   7: core::ops::function::FnOnce::call_once
             at /rustc/69f9c33d71c871fc16ac445211281c6e7a340943/library/core/src/ops/function.rs:251:5
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
test test_polars_csv_reader::test_uint8_fields_are_correctly_loaded ... FAILED
```

**Comment by cmdlineluser** [comment]
Perhaps this is useful information:

As there is no header in the file - the resulting column names are `column_1` .. `column_8`

Using those names:
```
schema.with_column(String::from("column_1"), Float64);
schema.with_column(String::from("column_2"), UInt8);
schema.with_column(String::from("column_3"), Float64);
schema.with_column(String::from("column_4"), Float64);
schema.with_column(String::from("column_5"), Float64);
schema.with_column(String::from("column_6"), Float64);
schema.with_column(String::from("column_7"), UInt8);
schema.with_column(String::from("column_8"), UInt8);
```

And using `.with_dtypes(Some(&schema))` instead of `.with_schema(&schema)` creates the dataframe without error.

(The `.with_schema()` docs say *"It is recommended to use with_dtypes instead."* - I'm not sure why?)

To rename the columns with `.set_column_names()` I had to make it mutable:
```
let mut data = ...;
data.set_column_names();
```

I tried using `.with_dtypes_slice()` with just the types - it resulted in the same `ComputeError(Owned("Unsupported data type UInt8 when reading a csv"))` error as `.with_schema()` - I guess it hits the same codepath.

In Python `read_csv()` has a `new_columns` parameter to specify new column names which worked.

```
pl.read_csv(io.StringIO(csv), has_header=False, new_columns=list(schema), dtypes=schema)
```

**Comment by cmdlineluser** [comment]
Perhaps this is useful information:

Using `.with_dtypes(Some(&schema))` instead of `.with_schema()` generated a different error:
```
`Err` value: NotFound(Owned("Cylinders"))'
```
(The `.with_schema()` docs say *"It is recommended to use with_dtypes instead."* - I'm not sure why?)

I changed the names to `column_1` .. `column_8`
```
schema.with_column(String::from("column_1"), Float64);
schema.with_column(String::from("column_2"), UInt8);
schema.with_column(String::from("column_3"), Float64);
schema.with_column(String::from("column_4"), Float64);
schema.with_column(String::from("column_5"), Float64);
schema.with_column(String::from("column_6"), Float64);
schema.with_column(String::from("column_7"), UInt8);
schema.with_column(String::from("column_8"), UInt8);
```
And it created the dataframe without error.

To rename the columns with `.set_column_names()` I had to make it mutable:
```
let mut data = ...;
data.set_column_names();
```

Using `.with_dtypes_slice()` resulted in the same `ComputeError(Owned("Unsupported data type UInt8 when reading a csv"))` error as `.with_schema()` - I guess it hits the same codepath.

In Python `read_csv()` has a `new_columns` parameter which also worked:
```
pl.read_csv(io.StringIO(csv), has_header=False, new_columns=list(schema), dtypes=schema)
```

**Comment by dpinol** [comment]
https://github.com/pola-rs/polars/pull/7290 fixed the lack of support for 8 & 16 bytes for normal reader, but it still fails for `read_csv_batched`

**Comment by wtn** [comment]
Points 2 and 3 are fixed.

Point 1 is a feature request, not a bug, as separators are single-byte by design.

So I suggest to close this issue as completed.

**Comment by ritchie46** [comment]
Thanks!
