### ISSUE TITLE
`schema_overrides` in `DataFrame` constructor does not work when `columns` not specified

### ISSUE THREAD

**Issue by stinodego** [pola-rs/polars#6421]
### Polars version checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pypi.org/project/polars/) of Polars.

### Issue description

An issue with the new `schema_overrides` parameter.

### Reproducible example

```python
import polars as pl

records = [
    {"id": 1, "value": 100, "_meta": "a"},
    {"id": 2, "value": 101, "_meta": "b"},
]

# Specify schema, but skip metadata fields
schema = {
    "id": pl.Int64,
    "value": pl.Int64,
}

df = pl.DataFrame(records, schema_overrides=schema, orient="row")
print(df)
```

Results in the following error:

```
Traceback (most recent call last):
  File "/home/stijn/ah/ah-sa-bakplan-calculator/repro.py", line 11, in <module>
    df = pl.DataFrame(records, schema_overrides=schema, orient="row")
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/stijn/.cache/pypoetry/virtualenvs/bakplan-calculator-TjseP0Di-py3.11/lib/python3.11/site-packages/polars/internals/dataframe/frame.py", line 317, in __init__
    self._df = sequence_to_pydf(
               ^^^^^^^^^^^^^^^^^
  File "/home/stijn/.cache/pypoetry/virtualenvs/bakplan-calculator-TjseP0Di-py3.11/lib/python3.11/site-packages/polars/internals/construction.py", line 761, in sequence_to_pydf
    include_unknowns(schema_overrides, column_names)
  File "/home/stijn/.cache/pypoetry/virtualenvs/bakplan-calculator-TjseP0Di-py3.11/lib/python3.11/site-packages/polars/internals/construction.py", line 93, in include_unknowns
    return {col: schema.get(col, Unknown) for col in cols}
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: 'NoneType' object is not iterable
```

### Expected behavior

I expect the dataframe to be created with the dtypes specified.

```
shape: (2, 3)
┌─────┬───────┬───────┐
│ id  ┆ value ┆ _meta │
│ --- ┆ ---   ┆ ---   │
│ i64 ┆ i64   ┆ str   │
╞═════╪═══════╪═══════╡
│ 1   ┆ 100   ┆ a     │
│ 2   ┆ 101   ┆ b     │
└─────┴───────┴───────┘
```

As a sidenote, it will work correctly when providing a columns argument (`columns=["id", "value", "_meta"]`), or when not specifying `schema_overrides` at all.

### Installed versions

<details>

```
---Version info---
Polars: 0.15.16
Index type: UInt32
Platform: Linux-5.10.102.1-microsoft-standard-WSL2-x86_64-with-glibc2.35
Python: 3.11.0 (main, Nov  1 2022, 09:16:00) [GCC 11.2.0]
---Optional dependencies---
pyarrow: 10.0.1
pandas: 1.5.2
numpy: 1.24.0
fsspec: 2022.11.0
connectorx: <not installed>
xlsx2csv: 0.8.1
deltalake: <version not detected>
matplotlib: <not installed>
```

</details>

**Comment by stinodego** [comment]
Calling in @alexander-beedie for this one 😄

**Comment by alexander-beedie** [comment]
You should provide your definition to the `schema` param (formerly knows as `columns` :) here, as `schema_overrides` applies to individual _fields_ of the schema - so your call above enforces the int64 type on the two fields, but won't drop "_meta". 

```python
pl.DataFrame(records, schema=schema)

# shape: (2, 2)
# ┌─────┬───────┐
# │ id  ┆ value │
# │ --- ┆ ---   │
# │ i64 ┆ i64   │
# ╞═════╪═══════╡
# │ 1   ┆ 100   │
# │ 2   ┆ 101   │
# └─────┴───────┘
```
However, it also definitely shouldn't error-out with the above call, so I'll take care of that! ;)

**Comment by alexander-beedie** [comment]
Fixed...

```python
schema = {
    "id": pl.Int16,
    "value": pl.Int32,
}
pl.DataFrame(records, schema_overrides=schema)

# shape: (2, 3)
# ┌─────┬───────┬───────┐
# │ id  ┆ value ┆ _meta │
# │ --- ┆ ---   ┆ ---   │
# │ i16 ┆ i32   ┆ str   │
# ╞═════╪═══════╪═══════╡
# │ 1   ┆ 100   ┆ a     │
# │ 2   ┆ 101   ┆ b     │
# └─────┴───────┴───────┘

```
