### ISSUE TITLE
df.filter(pl.col(pl.Float32)): PanicException: no `dtype-columns` expected at this point

### ISSUE THREAD

**Issue by 2-5** [pola-rs/polars#6476]
### Polars version checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pypi.org/project/polars/) of Polars.

### Issue description

I'm not sure if we're supposed to open issues for Rust panics.

### Reproducible example

```python
import os

import polars as pl

os.environ["RUST_BACKTRACE"] = "full"

df = pl.DataFrame(dict(
    a=[0.1, 0.2],
))

df2 = df.filter(pl.col(pl.Float32).min() < 0.1)
print(df2)
```

Output:

```python
thread '<unnamed>' panicked at 'no `dtype-columns` expected at this point', D:\a\polars\polars\polars\polars-lazy\polars-plan\src\logical_plan\conversion.rs:151:37
stack backtrace:
   0:     0x7ff9989215a0 - ffi_select_with_compiled_path
   1:     0x7ff99711bdbb - BrotliDecoderVersion
   2:     0x7ff99890f1aa - ffi_select_with_compiled_path
   3:     0x7ff99892304b - ffi_select_with_compiled_path
   4:     0x7ff998922c58 - ffi_select_with_compiled_path
   5:     0x7ff998923bc0 - ffi_select_with_compiled_path
   6:     0x7ff9989235e4 - ffi_select_with_compiled_path
   7:     0x7ff99892355f - ffi_select_with_compiled_path
   8:     0x7ff998923534 - ffi_select_with_compiled_path
   9:     0x7ff9989d6415 - ffi_select_with_compiled_path
  10:     0x7ff998542b7b - ffi_select_with_compiled_path
  11:     0x7ff998541d5d - ffi_select_with_compiled_path
  12:     0x7ff9985422e2 - ffi_select_with_compiled_path
  13:     0x7ff998690b57 - ffi_select_with_compiled_path
  14:     0x7ff9986d79d9 - ffi_select_with_compiled_path
  15:     0x7ff9980eb7aa - ffi_select_with_compiled_path
  16:     0x7ff998259c1f - ffi_select_with_compiled_path
  17:     0x7ff9982598e1 - ffi_select_with_compiled_path
  18:     0x7ff996b177ba - PyInit_polars
  19:     0x7ff9fff3c63c - PyMem_RawMalloc
  20:     0x7ff9ffeff040 - PyEval_EvalFrameDefault
  21:     0x7ff9ffefd787 - PyFunction_Vectorcall
  22:     0x7ff9fff29424 - PyVectorcall_Call
  23:     0x7ff9fff2929f - PyObject_Call
  24:     0x7ff9fff045ce - PyEval_EvalFrameDefault
  25:     0x7ff9fff01321 - PyEval_EvalFrameDefault
  26:     0x7ff9ffeff616 - PyEval_EvalFrameDefault
  27:     0x7ff9fff19bad - PyMapping_Check
  28:     0x7ff9fffacdb6 - PyEval_EvalCode
  29:     0x7ff9fffaca7a - PyArena_Free
  30:     0x7ff9fffac9fa - PyArena_Free
  31:     0x7ff9ffee2aec - PyRun_SimpleFileObject
  32:     0x7ff9ffee2811 - PyRun_SimpleFileObject
  33:     0x7ff9fffc729c - PyRun_AnyFileObject
  34:     0x7ff9fffc7717 - PyPreConfig_InitIsolatedConfig
  35:     0x7ff9fffc7833 - PyPreConfig_InitIsolatedConfig
  36:     0x7ff9fffc8914 - Py_RunMain
  37:     0x7ff9fffc87a5 - Py_RunMain
  38:     0x7ff9fffc80f5 - Py_Main
  39:     0x7ff6dfbe1230 - <unknown>
  40:     0x7ffa2eed7614 - BaseThreadInitThunk
  41:     0x7ffa308a26a1 - RtlUserThreadStart
Traceback (most recent call last):
  File "test.py", line 11, in <module>
    df2 = df.filter(pl.col(pl.Float32).min() < 0.1)
  File ".venv\lib\site-packages\polars\internals\dataframe\frame.py", line 2730, in filter
    self.lazy()
  File ".venv\lib\site-packages\polars\utils.py", line 393, in wrapper
    return fn(*args, **kwargs)
  File ".venv\lib\site-packages\polars\internals\lazyframe\frame.py", line 1168, in collect
    return pli.wrap_df(ldf.collect())
pyo3_runtime.PanicException: no `dtype-columns` expected at this point
```

### Expected behavior

I want to find out if any row has any float value below a certain value. So I tried:

```python
df.filter(pl.col(pl.Float32).min() < 0.1)
```

I'm not sure if this scenario is kind of usage is supported or not.

### Installed versions

<details>

```
---Version info---
Polars: 0.15.17
Index type: UInt32
Platform: Windows-10-10.0.19045-SP0
Python: 3.10.8 (tags/v3.10.8:aaaf517, Oct 11 2022, 16:50:30) [MSC v.1933 64 bit (AMD64)]
---Optional dependencies---
pyarrow: 10.0.1
pandas: 1.5.2
numpy: 1.23.5
fsspec: 2022.11.0
connectorx: <not installed>
xlsx2csv: <not installed>
deltalake: <not installed>
matplotlib: 3.6.2
```

</details>

**Comment by ritchie46** [comment]
Your query has a bug. Dtypes expand into multiple expressions. Tgey have to be combined with `and`, `or`, `xor`, to create a boolean
