### ISSUE TITLE
Cannot create DataFrame with categorical nested in struct

### ISSUE THREAD

**Issue by stinodego** [pola-rs/polars#6507]
### Polars version checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pypi.org/project/polars/) of Polars.

### Issue description

Ran into this when updating a test. I believe this is an issue on the Rust side, as the data being passed into `PyDataFrame.read_dicts` seems correct, but it raises a `PanicException`.

### Reproducible example

```python
import polars as pl

df = pl.DataFrame(
    {
        "a": [
            {"value": "foo", "counts": 1},
            {"value": "bar", "counts": 2},
        ]
    },
    schema={"a": pl.Struct({"value": pl.Categorical, "counts": pl.UInt32})},
)

print(df)
# pyo3_runtime.PanicException: Categorical(None) not supported
```

Full traceback:
```
thread '<unnamed>' panicked at 'Categorical(None) not supported', /home/stijn/code/polars/polars/polars-core/src/series/any_value.rs:203:19
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
Traceback (most recent call last):
  File "/home/stijn/code/polars/py-polars/repro.py", line 3, in <module>
    df = pl.DataFrame(
         ^^^^^^^^^^^^^
  File "/home/stijn/code/polars/py-polars/polars/utils.py", line 393, in wrapper
    return fn(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^
  File "/home/stijn/code/polars/py-polars/polars/internals/dataframe/frame.py", line 329, in __init__
    self._df = dict_to_pydf(
               ^^^^^^^^^^^^^
  File "/home/stijn/code/polars/py-polars/polars/internals/construction.py", line 693, in dict_to_pydf
    s._s for s in _expand_dict_scalars(data, schema_overrides).values()
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/stijn/code/polars/py-polars/polars/internals/construction.py", line 636, in _expand_dict_scalars
    updated_data[name] = pli.Series(name=name, values=val, dtype=dtype)
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/stijn/code/polars/py-polars/polars/internals/series/series.py", line 239, in __init__
    self._s = sequence_to_pyseries(
              ^^^^^^^^^^^^^^^^^^^^^
  File "/home/stijn/code/polars/py-polars/polars/internals/construction.py", line 311, in sequence_to_pyseries
    return sequence_to_pydf(
           ^^^^^^^^^^^^^^^^^
  File "/home/stijn/code/polars/py-polars/polars/internals/construction.py", line 772, in sequence_to_pydf
    pydf = PyDataFrame.read_dicts(data, infer_schema_length, dtypes)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
```
Values passed into `PyDataFrame.read_dicts`:
- data: `[{'value': 'foo', 'counts': 1}, {'value': 'bar', 'counts': 2}]`
- infer_schema_length: `100`
- dtypes: `{'value': Categorical, 'counts': UInt32}`

### Expected behavior

I expect the dataframe to be created normally.

### Installed versions

<details>
Master branch

```
---Version info---
Polars: 0.15.18
Index type: UInt32
Platform: Linux-5.10.102.1-microsoft-standard-WSL2-x86_64-with-glibc2.35
Python: 3.11.0 (main, Nov  1 2022, 09:16:00) [GCC 11.2.0]
---Optional dependencies---
pyarrow: 10.0.1
pandas: 1.5.2
numpy: 1.24.1
fsspec: <not installed>
connectorx: <not installed>
xlsx2csv: 0.8
deltalake: <version not detected>
matplotlib: <not installed>
```

</details>

**Comment by ritchie46** [comment]
This is one is not trivial. We cannot create create categoricals on a single value basis. Somehow we first need to rewrite the schema to a `struct<str>` and do the cast to categorical later.

**Comment by ritchie46** [comment]
I take that back. The world looked better than I thought this morning. :)
