### ISSUE TITLE
Conversion from Utf8 to Int64

### ISSUE THREAD

**Issue by gam-phon** [pola-rs/polars#6542]
### Polars version checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pypi.org/project/polars/) of Polars.

### Issue description

I do not know is this an issue or it is the expected behavior, check below code

### Reproducible example

```python
import polars as pl

df = pl.DataFrame([{"a": "3.0"}])

# No issue
df.select(pl.col("a").cast(pl.Float64))

# No issue
df.select(pl.col("a").cast(pl.Float64).cast(pl.Int64))

# Here is the issue
df.select(pl.col("a").cast(pl.Int64))
"""
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File ".../python3.11/site-packages/polars/internals/dataframe/frame.py", line 5630, in select
    self.lazy().select(exprs).collect(no_optimization=True)._df
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File ".../python3.11/site-packages/polars/utils.py", line 393, in wrapper
    return fn(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^
  File ".../python3.11/site-packages/polars/internals/lazyframe/frame.py", line 1182, in collect
    return pli.wrap_df(ldf.collect())
                       ^^^^^^^^^^^^^
exceptions.ComputeError: Strict conversion from Utf8 to Int64 failed for values ["3.0"]. If you were trying to cast Utf8 to Date, Time, or Datetime, consider using `strptime`.
"""
```

### Expected behavior

What do you suggest?

### Installed versions

<details>

```
---Version info---
Polars: 0.15.18
Index type: UInt32
Platform: macOS-13.1-arm64-arm-64bit
Python: 3.11.1 (main, Dec 23 2022, 09:28:24) [Clang 14.0.0 (clang-1400.0.29.202)]
---Optional dependencies---
pyarrow: 10.0.1
pandas: 1.5.3
numpy: 1.24.1
fsspec: <not installed>
connectorx: 0.3.2_alpha.1
xlsx2csv: <not installed>
deltalake: <not installed>
matplotlib: <not installed>
```

</details>

**Comment by ritchie46** [comment]
I am. Not convinced this is a bug. The string is not formatted as integer.
