### ISSUE TITLE
PanicException: assertion failed: `(left == right)`

### ISSUE THREAD

**Issue by 2-5** [pola-rs/polars#6551]
### Polars version checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pypi.org/project/polars/) of Polars.

### Issue description

`PanicException` raised. The test case is most likely an invalid use case, `is_in` needs to be used instead of `==`.

### Reproducible example

```python
import os

import polars as pl

os.environ["RUST_BACKTRACE"] = "full"

df = pl.DataFrame({
    "idx": list(range(10)),
})
print(df)

s = pl.Series([2, 5, 8])
print(df.filter(pl.col("idx") == s))
```

Output:

```python
thread '<unnamed>' panicked at 'assertion failed: `(left == right)`
  left: `10`,
 right: `3`', C:\Users\runneradmin\.cargo\git\checkouts\arrow2-945af624853845da\685cf49\src\compute\comparison\primitive.rs:18:5
stack backtrace:
   0:     0x7ffa54fe5d00 - ffi_select_with_compiled_path
   1:     0x7ffa53791a6b - BrotliDecoderVersion
   2:     0x7ffa54fd3d6a - ffi_select_with_compiled_path
   3:     0x7ffa54fe77ab - ffi_select_with_compiled_path
   4:     0x7ffa54fe73b8 - ffi_select_with_compiled_path
   5:     0x7ffa54fe8320 - ffi_select_with_compiled_path
   6:     0x7ffa54fe7d76 - ffi_select_with_compiled_path
   7:     0x7ffa54fe7cbf - ffi_select_with_compiled_path
   8:     0x7ffa54fe7c94 - ffi_select_with_compiled_path
   9:     0x7ffa55099e15 - ffi_select_with_compiled_path
  10:     0x7ffa5509a06b - ffi_select_with_compiled_path
  11:     0x7ffa55093fd0 - ffi_select_with_compiled_path
  12:     0x7ffa53431048 - PyInit_polars
  13:     0x7ffa539c61ce - ffi_select_with_compiled_path
  14:     0x7ffa539c0245 - ffi_select_with_compiled_path
  15:     0x7ffa54833434 - ffi_select_with_compiled_path
  16:     0x7ffa54828165 - ffi_select_with_compiled_path
  17:     0x7ffa548f7aaf - ffi_select_with_compiled_path
  18:     0x7ffa548e9514 - ffi_select_with_compiled_path
  19:     0x7ffa5318d2ba - PyInit_polars
  20:     0x7ffa6db1c63c - PyMem_RawMalloc
  21:     0x7ffa6dadf040 - PyEval_EvalFrameDefault
  22:     0x7ffa6dae1321 - PyEval_EvalFrameDefault
  23:     0x7ffa6dadc435 - PyObject_Hash
  24:     0x7ffa6dae0018 - PyEval_EvalFrameDefault
  25:     0x7ffa6daf9bad - PyMapping_Check
  26:     0x7ffa6db8cdb6 - PyEval_EvalCode
  27:     0x7ffa6db8ca7a - PyArena_Free
  28:     0x7ffa6db8c9fa - PyArena_Free
  29:     0x7ffa6dac2aec - PyRun_SimpleFileObject
  30:     0x7ffa6dac2811 - PyRun_SimpleFileObject
  31:     0x7ffa6dba729c - PyRun_AnyFileObject
  32:     0x7ffa6dba7717 - PyPreConfig_InitIsolatedConfig
  33:     0x7ffa6dba7833 - PyPreConfig_InitIsolatedConfig
  34:     0x7ffa6dba8914 - Py_RunMain
  35:     0x7ffa6dba87a5 - Py_RunMain
  36:     0x7ffa6dba80f5 - Py_Main
  37:     0x7ff608a61230 - <unknown>
  38:     0x7ffab9a47614 - BaseThreadInitThunk
  39:     0x7ffaba5426a1 - RtlUserThreadStart
Traceback (most recent call last):
  File "H:\Work\issue\polars\test9.py", line 13, in <module>
    print(df.filter(pl.col("idx") == s))
  File "H:\Git\Framework\.venv\lib\site-packages\polars\internals\dataframe\frame.py", line 2702, in filter
    self.lazy()
  File "H:\Git\Framework\.venv\lib\site-packages\polars\internals\lazyframe\frame.py", line 1143, in collect
    return pli.wrap_df(ldf.collect())
pyo3_runtime.PanicException: assertion failed: `(left == right)`
  left: `10`,
 right: `3`
```

### Expected behavior

Better error probably

### Installed versions

<details>

```
---Version info---
Polars: 0.16.1
Index type: UInt32
Platform: Windows-10-10.0.19045-SP0
Python: 3.10.8 (tags/v3.10.8:aaaf517, Oct 11 2022, 16:50:30) [MSC v.1933 64 bit (AMD64)]
---Optional dependencies---
pyarrow: 11.0.0
pandas: 1.5.2
numpy: 1.23.5
fsspec: 2022.11.0
connectorx: <not installed>
xlsx2csv: <not installed>
deltalake: <not installed>
matplotlib: 3.6.2
```

</details>

**Comment by ritchie46** [comment]
We need to raise an error here. 

There is a bug in the query as the series doesn't have tge right length.

**Comment by brent-williams** [comment]
For anyone stumbling on this and waiting on the bug fix I was able to workaround using the following:
```rust
    let temp = &bad_series.take_every(1);
    good_series = &temp;
```
