### ISSUE TITLE
Writing long rows of Chunked Lists as parquet throws runtime error

### ISSUE THREAD

**Issue by stupidanon** [pola-rs/polars#6589]
### Polars version checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://crates.io/crates/polars) of Polars.

### Issue description

I have the following async block of code that runs as part of a larger program, and it runs successfully when the dataframe has a row with length 10, or 30, but when i put it to a larger number like 300, it tries to write the dataframe as parquet and throws a runtime error for each async thread:

Here is an example of the df it tries to write but fails. 
```
df: Ok(shape: (300, 4)
┌───────────────┬─────────┬────────────────────────────────┬───────────────────────────────────────┐
│ timestamp     ┆ ticker  ┆ bids                           ┆ asks                                  │
│ ---           ┆ ---     ┆ ---                            ┆ ---                                   │
│ i64           ┆ str     ┆ list[list[f64]]                ┆ list[list[f64]]                       │
╞═══════════════╪═════════╪════════════════════════════════╪═══════════════════════════════════════╡
│ 1674962575119 ┆ ETHUSDT ┆ [[1589.51, 4.731], [1589.31,   ┆ [[1590.93, 39.234], [1592.1, 51....   │
│               ┆         ┆ 93....                         ┆                                       │
│ 1674962575220 ┆ ETHUSDT ┆ [[1589.51, 22.094], [1589.31,  ┆ [[1590.93, 39.234], [1592.1, 51....   │
│               ┆         ┆ 24...                          ┆                                       │
│ 1674962575319 ┆ ETHUSDT ┆ [[1589.51, 12.324], [1589.31,  ┆ [[1590.93, 39.309], [1592.1, 52....   │
│               ┆         ┆ 24...                          ┆                                       │
│ 1674962575421 ┆ ETHUSDT ┆ [[1589.51, 0.0], [1589.31,     ┆ [[1590.93, 26.735], [1592.1, 52....   │
│               ┆         ┆ 24.26...                       ┆                                       │
│ ...           ┆ ...     ┆ ...                            ┆ ...                                   │
│ 1674962604998 ┆ ETHUSDT ┆ [[1440.0, 5138.446], [1558.38, ┆ [[1617.28, 40.969], [1593.72, 3....   │
│               ┆         ┆ 0...                           ┆                                       │
│ 1674962605101 ┆ ETHUSDT ┆ [[1440.0, 5138.446], [1558.38, ┆ [[1617.28, 40.969], [1593.72, 3....   │
│               ┆         ┆ 0...                           ┆                                       │
│ 1674962605201 ┆ ETHUSDT ┆ [[1440.0, 5138.446], [1558.38, ┆ [[1617.28, 40.969], [1593.72, 3....   │
│               ┆         ┆ 0...                           ┆                                       │
│ 1674962605301 ┆ ETHUSDT ┆ [[1440.0, 5138.446], [1558.38, ┆ [[1617.28, 40.969], [1593.72, 3....   │
│               ┆         ┆ 0...                           ┆                                       │
└───────────────┴─────────┴────────────────────────────────┴───────────────────────────────────────┘)
```
Here is the error.
```
thread '<unnamed>' panicked at 'range end index 131373 out of range for slice of length 301', C:\Users\username\.cargo\git\checkouts\arrow2-945af624853845da\baa2618\src\io\parquet\write\mod.rs:171:37
thread '<unnamed>' panicked at 'range end index 131373 out of range for slice of length 301', C:\Users\username\.cargo\git\checkouts\arrow2-945af624853845da\baa2618\src\io\parquet\write\mod.rs:171:37

```
Here is the code.
```rust
async {
    if main_vec.length() >= ROWS {
        let df = main_vec.to_df();

        let time = std::time::SystemTime::now()
            .duration_since(std::time::UNIX_EPOCH)
            .unwrap()
            .as_secs();

        let file = std::fs::File::create(&(time.to_string().trim() + ".parquet")).unwrap();

        println!("Wrote parquet file: {}", &(time.to_string().trim().to_owned() + ".parquet"));

        //  ERROR OCCURS HERE

        //  ERROR OCCURS HERE

        //  ERROR OCCURS HERE

        ParquetWriter::new(file)
            .with_compression(ParquetCompression::Snappy)
            .with_statistics(true)
            .finish(&mut df.collect().unwrap())
            .expect("Failed to write parquet file");

        main_vec.clear();
    }
}.await;

```

### Reproducible example

**EDIT: CHECK THE COMMENT BELOW FOR EXAMPLE**

I don't have the code to reproduce this since the project is very large and I am new to rust. However, simply make Vec<Vec<Vec<f64>>> using ListChunked as I show above and it will crash given a very long list[list[f64]] in each row, after around 30 rows it will throw runtime error. 

### Expected behavior

Write the parquet file as it would with 30 rows when done with 300 or more. At a minimum, the error should be more detailed instead of just a runtime error. (I can provide a full stack trace if required)

### Installed versions

<details>
polars = { git = "https://github.com/pola-rs/polars", features = ["lazy", "parquet"] }
</details>

**Comment by ritchie46** [comment]
Can you try making an MWE without any async? If we can reproduce it we can fix it.

**Comment by stupidanon** [comment]
@ritchie46 Here is the code:
```rust 
use polars::prelude::*;

#[tokio::main]
async fn main() {
    let mut rows: Vec<Vec<Vec<f64>>> = Vec::new();
    let mut inner_inner_row: Vec<f64> = Vec::new();
    for _ in 0..3 {
        inner_inner_row.push(rand::random::<f64>());
    }
    // println!("inner_inner_row: {:?}", inner_inner_row);

    let mut inner_row: Vec<Vec<f64>> = Vec::new();
    for _ in 0..1000 {
        inner_row.push(inner_inner_row.clone());
    }
    // println!("inner_row: {:?}", inner_row);

    for _ in 0..300 {
        rows.push(inner_row.clone());
    }
    // println!("rows: {:?}", rows);

    let rows = build_column(&rows);

    let mut df = DataFrame::new(vec![rows]).unwrap();
    println!("{:?}", df);

    let time = std::time::SystemTime::now()
        .duration_since(std::time::UNIX_EPOCH)
        .unwrap()
        .as_secs();

    let file = std::fs::File::create(&(time.to_string().trim().to_owned() + ".parquet")).unwrap();

    //  ERROR OCCURS HERE
    //  ERROR OCCURS HERE
    //  ERROR OCCURS HERE

    ParquetWriter::new(file)
        .with_compression(ParquetCompression::Snappy)
        .with_statistics(true)
        .finish(&mut df)
        .expect("Failed to write parquet file");
}

fn build_column(rows: &Vec<Vec<Vec<f64>>>) -> Series {
    ListChunked::from_iter(rows.into_iter().map(|row| {
        ListChunked::from_iter(
            row.into_iter()
                .map(|x| Float64Chunked::from_slice("x", &x).into_series()),
        )
        .into_series()
    }))
    .into_series()
}


```

**Comment by stupidanon** [comment]
Notice that if you change the 0..300 to 0..30, the code works as expected

**Comment by stupidanon** [comment]
Any update on this? :)

**Comment by ritchie46** [comment]
Could you try again on latest master? There have been many parquet fixes upstream.

**Comment by ritchie46** [comment]
Did you remove your lockfile and point to master?

**Comment by stupidanon** [comment]
Sorry, please instruct how to do that. I have deleted the lock file, how do I point to master?

**Comment by stupidanon** [comment]
I had not! Thank you, the issue is solved. 

For those experiencing same, delete lockfile, use latest master branch in cargo.toml.
