### ISSUE TITLE
Add pl.lit(list)

### ISSUE THREAD

**Issue by mcrumiller** [pola-rs/polars#6608]
### Problem description

Stems from #6596. Literal lists would be very useful for series with dtype `pl.List`. Example:

```python
import polars as pl

lit = pl.lit([1, 1])
```
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\430015439\AppData\Local\Programs\Python\Python39\lib\site-packages\polars\internals\lazy_functions.py", line 1176, in lit
    return pli.wrap_expr(pylit(item, allow_object))
ValueError: could not convert value '[1, 1]' as a Literal
```

In a more useful context, it would be inferred, e.g:

```python
df = pl.DataFrame({
    'a': [
        [1, 1],
        [2, 2]
    ]
})
df.filter(pl.col('a') == [1, 1])
```

```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\430015439\AppData\Local\Programs\Python\Python39\lib\site-packages\polars\internals\expr\expr.py", line 251, in __eq__
    return wrap_expr(self._pyexpr.eq(self._to_expr(other)._pyexpr))
  File "C:\Users\430015439\AppData\Local\Programs\Python\Python39\lib\site-packages\polars\internals\expr\expr.py", line 163, in _to_expr
    return pli.lit(other)
  File "C:\Users\430015439\AppData\Local\Programs\Python\Python39\lib\site-packages\polars\internals\lazy_functions.py", line 1176, in lit
    return pli.wrap_expr(pylit(item, allow_object))
```

**Comment by deanm0000** [comment]
The problem is that there aren't literal lists in dataframes

For instance, taking your example `type(df[0,0])` is a `polars.internals.series.series.Series` not a list.

**Comment by mcrumiller** [comment]
@deanm0000 that makes sense, but since a `pl.lit(pl.Series)` is possible, surely this could be hidden from the user and work as intended?

**Comment by deanm0000** [comment]
touche.  

So it seems what you're after is being able to do

```
df.with_columns(pl.Series([1,1]).alias('c')).filter(pl.col('a')==pl.col('c')) 
```

but without the, seemingly, superfluous `with_columns`
makes sense.

**Comment by MarcoGorelli** [comment]
I'd have thought `concat_list` would work here, but it looks like it returns both rows :thinking:
```python

In [1]: df = pl.DataFrame({
   ...:     'a': [
   ...:         [1, 1],
   ...:         [2, 2]
   ...:     ]
   ...: })
   ...: df.filter(pl.col('a') == pl.concat_list([1, 1]))
Out[1]:
shape: (2, 1)
┌───────────┐
│ a         │
│ ---       │
│ list[i64] │
╞═══════════╡
│ [1, 1]    │
│ [2, 2]    │
└───────────┘

In [2]: df = pl.DataFrame({
   ...:     'a': [
   ...:         [1, 1],
   ...:         [2, 2]
   ...:     ]
   ...: })
   ...: df.filter(pl.col('a') == pl.concat_list([1, 9]))
Out[2]:
shape: (0, 1)
┌───────────┐
│ a         │
│ ---       │
│ list[i64] │
╞═══════════╡
└───────────┘
```

**Comment by josh** [comment]
I was looking for something like this as well. I was trying to figure out how to do something like `pl.lit([])` to create an empty list as an expression. You can't seem to use `pl.concat_list([])` either, that just panics. Oddly you can weird filtering hacks as mentioned like `pl.concat_list([pl.lit(None, dtype=pl.Int64)]).arr.eval(pl.element().drop_nulls())` to achieve it.
