### ISSUE TITLE
Applying function to aggregated column fails after groupby_dynamic

### ISSUE THREAD

**Issue by papparapa** [pola-rs/polars#6904]
### Polars version checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pypi.org/project/polars/) of Polars.

### Issue description

Applying function to aggregated column fails after `groupby_dynamic`.

### Reproducible example

In lazy

```python
import polars as pl
from datetime import datetime, timedelta
pl.DataFrame(
    {
        "a": [
            datetime(2021, 1, 1) + timedelta(seconds=2**i)
            for i in range(10)
        ],
        "b": [float(i) for i in range(10)],
    }
).lazy().groupby_dynamic("a", every='10s', period='100s').agg([pl.col("b").mean().sin().alias("c")]).collect()
```

```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/workspaces/Polars/polars/py-polars/polars/internals/lazyframe/frame.py", line 1147, in collect
    return pli.wrap_df(ldf.collect())
exceptions.ComputeError: Cannot aggregate col("b").mean().sin(). The column is already aggregated.

> Error originated in expression: 'col("b").mean().sin()'
```

In eager

```python
import polars as pl
from datetime import datetime, timedelta
pl.DataFrame(
    {
        "a": [
            datetime(2021, 1, 1) + timedelta(seconds=2**i)
            for i in range(10)
        ],
        "b": [float(i) for i in range(10)],
    }
).groupby_dynamic("a", every='10s', period='100s').agg([pl.col("b").mean().sin().alias("c")])
```

```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/workspaces/Polars/polars/py-polars/polars/internals/dataframe/groupby.py", line 887, in agg
    self.df.lazy()
  File "/workspaces/Polars/polars/py-polars/polars/internals/lazyframe/frame.py", line 1147, in collect
    return pli.wrap_df(ldf.collect())
exceptions.ComputeError: Cannot aggregate col("b").mean().sin(). The column is already aggregated.

> Error originated in expression: 'col("b").mean().sin()'
```

### Expected behavior

Expected to succeed

### Installed versions

master branch
<details>

```
---Version info---
Polars: 0.16.5
Index type: UInt32
Platform: Linux-5.15.79.1-microsoft-standard-WSL2-x86_64-with-glibc2.31
Python: 3.9.2 (default, Feb 28 2021, 17:03:44) 
[GCC 10.2.1 20210110]
---Optional dependencies---
pyarrow: 11.0.0
pandas: 1.5.3
numpy: 1.24.1
fsspec: <not installed>
connectorx: <not installed>
xlsx2csv: 0.8.1
deltalake: <version not detected>
matplotlib: <not installed>
```

</details>

**Comment by papparapa** [comment]
https://github.com/pola-rs/polars/blob/515514d1de40f17f7d2aa867c21f67c3a5d5af57/polars/polars-lazy/src/physical_plan/expressions/apply.rs#L153-L162

The error seems to happen here.
`groupby_dynamic` is an overlapping grouping so it goes through here and throwes the error.

Though I'm not sure how to fix it.
