### ISSUE TITLE
pl.reduce panicked at 'this operation is not implemented/valid for this dtype: Boolean 

### ISSUE THREAD

**Issue by romanovacca** [pola-rs/polars#7080]
### Polars version checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pypi.org/project/polars/) of Polars.

### Issue description

The following line does currently not work. The error comes up when in the expressions uses "*" combined with '>'. If we select a specific column, or leave out the '>' it works.

```
df = pl.DataFrame(
    {
        "a": [1, 2, 3],
        "b": [10, 20, 30],
    }
)

df.select(
    pl.reduce(f=lambda acc, x: acc + x, exprs=pl.col("*") > 0).alias("is_above_0"),
)
```
gives
```
thread '<unnamed>' panicked at 'this operation is not implemented/valid for this dtype: Boolean', /Users/runner/work/polars/polars/polars/polars-core/src/series/series_trait.rs:159:13
--- PyO3 is resuming a panic after fetching a PanicException from Python. ---
```

while the equivalent for fold works:

```
df.select(
    pl.fold(acc=pl.lit(0), f=lambda acc, x: acc + x, exprs=pl.col("*") > 0).alias("is_above_0"),
)

is_above_0
--
i32
2
2
2
```

### Reproducible example

```python
df = pl.DataFrame(
    {
        "a": [1, 2, 3],
        "b": [10, 20, 30],
    }
)

df.select(
    pl.reduce(f=lambda acc, x: acc + x, exprs=pl.col("*") > 0).alias("is_above_0"),
)
```

### Expected behavior

Would expect same behaviour as pl.fold

### Installed versions

<details>

```
---Version info---
Polars: 0.16.6
Index type: UInt32
Platform: macOS-10.16-x86_64-i386-64bit
Python: 3.10.9 (main, Jan 11 2023, 09:18:20) [Clang 14.0.6 ]
---Optional dependencies---
pyarrow: 11.0.0
pandas: 1.5.3
numpy: 1.24.1
fsspec: <not installed>
connectorx: <not installed>
xlsx2csv: <not installed>
deltalake: <not installed>
matplotlib: 3.6.3
```

</details>

**Comment by k-nasa** [comment]
Boolean Series cannot be added together, but Integer and Boolean can be added.


```python
>>> s1 = pl.Series([True, True])
>>> s2 = pl.Series([True, True])
>>>
>>> s1 + s2
thread '<unnamed>' panicked at 'this operation is not implemented/valid for this dtype: Boolean', /Users/runner/work/polars/polars/polars/polars-core/src/series/series_trait.rs:159:13
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/asan/.pyenv/versions/3.8.12/lib/python3.8/site-packages/polars/internals/series/series.py", line 554, in __add__
    return self._arithmetic(other, "add", "add_<>")
  File "/Users/asan/.pyenv/versions/3.8.12/lib/python3.8/site-packages/polars/internals/series/series.py", line 519, in _arithmetic
    return wrap_s(getattr(self._s, op_s)(other._s))
pyo3_runtime.PanicException: this operation is not implemented/valid for this dtype: Boolean

>>> s1 = pl.Series([True, False])
>>> s2 = pl.Series([1, 2])
>>> s1 + s2
shape: (2,)
Series: '' [i64]
[
	2
	3
]
```

Since `acc = pl.lit (0)` is specified, `fold` seems to be the addition of integers and boolean values, and `reduce` is the addition of boolean values.
