### ISSUE TITLE
sort() does not recognize descending keyword anymore

### ISSUE THREAD

**Issue by mcrumiller** [pola-rs/polars#7086]
### Polars version checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pypi.org/project/polars/) of Polars.

### Issue description

Not sure why the `descending` keyword is no longer recognized, it's still in the [the API](https://pola-rs.github.io/polars/py-polars/html/reference/dataframe/api/polars.DataFrame.sort.html).

### Reproducible example

```python
import polars as pl

df = pl.DataFrame({'a': [1, 2, 3, 4, 5]})

df.sort(by='a', descending=True)

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: sort() got an unexpected keyword argument 'descending'
```

df = pl.DataFrame({'a': [1, 2, 3, 4 ,5]}).select(col('a').sort(descending=True))
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "c:\Projects\project-brr\.venv_brr\lib\site-packages\polars\utils.py", line 496, in wrapper
    return fn(*args, **kwargs)
TypeError: sort() got an unexpected keyword argument 'descending'
```
```


### Expected behavior

DataFrame should sort in reverse order.

### Installed versions

<details>

```
---Version info---
Polars: 0.16.7
Index type: UInt32
Platform: Windows-10-10.0.19044-SP0
Python: 3.9.13 (tags/v3.9.13:6de2ca5, May 17 2022, 16:36:42) [MSC v.1929 64 bit (AMD64)]
---Optional dependencies---
pyarrow: 9.0.0
pandas: 1.5.3
numpy: 1.24.0
fsspec: <not installed>
connectorx: 0.3.0
xlsx2csv: 0.8
deltalake: <not installed>
matplotlib: 3.6.1
```

</details>

**Comment by ritchie46** [comment]
The docs are based on master. This has not yet been released.

**Comment by stinodego** [comment]
Maybe we should do a release now just to update the docs? This is probably something a lot of people bump into.

**Comment by mcrumiller** [comment]
Is there a reason the docs follow master and not the latest release? I imagine most people install polars via `pip` or `poetry` or something similar, and this indicates that there is no formal documentation for those installations available.

**Comment by stinodego** [comment]
It's a known issue. We've just switched that around in #7068 , and tracking the issue in #6373 .
