### ISSUE TITLE
0.16.8 - parantheses in SQL context don't work anymore

### ISSUE THREAD

**Issue by 2-5** [pola-rs/polars#7111]
### Polars version checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pypi.org/project/polars/) of Polars.

### Issue description

Upgrade to 0.16.8 broke parentheses support in SQL queries.

### Reproducible example

```python
import polars as pl

df = pl.DataFrame({
    "value": list(range(7)),
})

sql_ctx = pl.SQLContext()
sql_ctx.register("df", df.lazy())

df2 = sql_ctx.query("SELECT * FROM df WHERE (value > 3)")
print(df2)
```

Outputs:

```python
Traceback (most recent call last):
  File "test.py", line 13, in <module>
    df3 = sql_ctx.query("SELECT * FROM df WHERE (value > 3)")
  File ".venv\lib\site-packages\polars\internals\sql\context.py", line 50, in query
    return self.execute(query).collect()
  File ".venv\lib\site-packages\polars\internals\sql\context.py", line 47, in execute
    return pli.wrap_ldf(self._ctxt.execute(query))
exceptions.ComputeError: SQL Expr Nested(BinaryOp { left: Identifier(Ident { value: "value", quote_style: None }), op: Gt, right: Value(Number("3", false)) }) was not supported in polars-sql yet!
```

### Expected behavior

Parentheses are supported

### Installed versions

<details>

```
---Version info---
Polars: 0.16.8
Index type: UInt32
Platform: Windows-10-10.0.19045-SP0
Python: 3.10.8 (tags/v3.10.8:aaaf517, Oct 11 2022, 16:50:30) [MSC v.1933 64 bit (AMD64)]
---Optional dependencies---
pyarrow: 11.0.0
pandas: 1.5.3
numpy: 1.23.5
fsspec: 2023.1.0
connectorx: <not installed>
xlsx2csv: <not installed>
deltalake: <not installed>
matplotlib: 3.7.0
```

</details>

**Comment by ritchie46** [comment]
@universalmind303 any idea which current change is the culprit?

**Comment by universalmind303** [comment]
ill take a look.
