### ISSUE TITLE
Better error message when column indexing is out-of-bounds

### ISSUE THREAD

**Issue by CameronBieganek** [pola-rs/polars#7164]
I know that square bracket indexing is generally discouraged, but it would still be nice to have a better error message when column indexing is out-of-bounds. The message we get is `AttributeError: 'NoneType' object has no attribute 'len'`.

Example:

```python
In [23]: df = pl.DataFrame({"a": [1, 2]})

In [24]: df[:, 1]
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
Cell In[24], line 1
----> 1 df[:, 1]

File c:\Users\U216145\AppData\Local\pypoetry\Cache\virtualenvs\tracking-fuel-estimation-wp6-k8kX-py3.9\lib\site-packages\polars\internals\dataframe\frame.py:1567, in DataFrame.__getitem__(self, item)
   1565 if isinstance(col_selection, int):
   1566     series = self.to_series(col_selection)
-> 1567     return series[row_selection]
   1569 if isinstance(col_selection, list):
   1570     # df[:, [1, 2]]
   1571     if is_int_sequence(col_selection):

File c:\Users\U216145\AppData\Local\pypoetry\Cache\virtualenvs\tracking-fuel-estimation-wp6-k8kX-py3.9\lib\site-packages\polars\internals\series\series.py:863, in Series.__getitem__(self, item)
    861 # Slice.
    862 elif isinstance(item, slice):
--> 863     return PolarsSlice(self).apply(item)
    865 # Range.
    866 elif isinstance(item, range):

File c:\Users\U216145\AppData\Local\pypoetry\Cache\virtualenvs\tracking-fuel-estimation-wp6-k8kX-py3.9\lib\site-packages\polars\internals\slice.py:80, in PolarsSlice.apply(self, s)
     78 """Apply a slice operation, taking advantage of any potential fast paths."""
     79 # normalise slice
---> 80 self._slice_setup(s)
     82 # check for fast-paths / single-operation calls
     83 if self.slice_length == 0:

File c:\Users\U216145\AppData\Local\pypoetry\Cache\virtualenvs\tracking-fuel-estimation-wp6-k8kX-py3.9\lib\site-packages\polars\internals\slice.py:51, in PolarsSlice._slice_setup(self, s)
     49 """Normalise slice bounds, identify unbounded and/or zero-length slices."""
     50 # can normalise slice indices as we know object size
---> 51 obj_len = len(self.obj)
     52 start, stop, stride = slice(s.start, s.stop, s.step).indices(obj_len)
     54 # check if slice is actually unbounded

File c:\Users\U216145\AppData\Local\pypoetry\Cache\virtualenvs\tracking-fuel-estimation-wp6-k8kX-py3.9\lib\site-packages\polars\internals\series\series.py:418, in Series.__len__(self)
    417 def __len__(self) -> int:
--> 418     return self.len()

File c:\Users\U216145\AppData\Local\pypoetry\Cache\virtualenvs\tracking-fuel-estimation-wp6-k8kX-py3.9\lib\site-packages\polars\internals\series\series.py:2561, in Series.len(self)
   2550 def len(self) -> int:
   2551     """
   2552     Length of this Series.
   2553
   (...)
   2559
   2560     """
-> 2561     return self._s.len()

AttributeError: 'NoneType' object has no attribute 'len'
```

**Comment by ghuls** [comment]
Fixed in https://github.com/pola-rs/polars/pull/7167

```python
>>> df[:, 1]
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/software/polars/py-polars/polars/internals/dataframe/frame.py", line 1571, in __getitem__
    raise ValueError(f'Column index "{col_selection}" is out of bounds.')
ValueError: Column index "1" is out of bounds.
```
