### ISSUE TITLE
year-month-day can sometimes be parsed as Datetime, sometimes not

### ISSUE THREAD

**Issue by MarcoGorelli** [pola-rs/polars#7371]
### Polars version checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pypi.org/project/polars/) of Polars.

### Issue description

Parsing year-month-day as `Datetime` is allowed if:
1. the format is inferred
2. the format is specified and the fastpath is used

It's not allowed if:
3. the format is specified and the fastpath cannot be used

### Reproducible example

```python
In [2]: pl.Series(['01-02-2000']).str.strptime(pl.Datetime)  # autoinferred: works
Out[2]:
shape: (1,)
Series: '' [datetime[μs]]
[
        2000-02-01 00:00:00
]

In [3]: pl.Series(['13/Dec/2000']).str.strptime(pl.Datetime, '%d/%b/%Y')  # fastpath: works
Out[3]:
shape: (1,)
Series: '' [datetime[μs]]
[
        2000-12-13 00:00:00
]

In [4]: pl.Series(['13/December/2000']).str.strptime(pl.Datetime, '%d/%B/%Y')  # slowpath: fails
---------------------------------------------------------------------------
ComputeError: strict conversion to dates failed, maybe set strict=False
```

### Expected behavior

I think these should either all parse, or all fail?

### Installed versions

<details>

```
---Version info---
Polars: 0.16.11
Index type: UInt32
Platform: Linux-5.10.102.1-microsoft-standard-WSL2-x86_64-with-glibc2.35
Python: 3.8.16 (default, Dec  7 2022, 01:12:06)
[GCC 11.3.0]
---Optional dependencies---
pyarrow: 11.0.0
pandas: 2.0.0rc0
numpy: 1.24.2
fsspec: <not installed>
connectorx: <not installed>
xlsx2csv: <not installed>
deltalake: <not installed>
matplotlib: 3.6.2
```

</details>

**Comment by mcrumiller** [comment]
This looks like it's a simply bug with `%B` not working, no?

```python
import polars as pl

pl.Series(["2000/December/01", "2001/January/01"]).str.strptime(pl.Datetime, "%Y/%B/%d")
```

```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\430015439\AppData\Local\Programs\Python\Python39\lib\site-packages\polars\internals\series\utils.py", line 99, in wrapper
    return s.to_frame().select(f(*args, **kwargs)).to_series()
  File "C:\Users\430015439\AppData\Local\Programs\Python\Python39\lib\site-packages\polars\internals\dataframe\frame.py", line 6387, in select
    self.lazy()
  File "C:\Users\430015439\AppData\Local\Programs\Python\Python39\lib\site-packages\polars\internals\lazyframe\frame.py", line 1430, in collect
    return pli.wrap_df(ldf.collect())
exceptions.ComputeError: strict conversion to dates failed, maybe set strict=False
```
Using `strict=False` just returns a column of `null`s.

**Comment by MarcoGorelli** [comment]
`%B` itself is fine, but (unlike in some other paths) only `NaiveDateTime` is tried - the following for example works
```python
In [78]: pl.Series(["2000/December/01 00:00", "2001/January/01 00:00"]).str.strptime(pl.Datetime, "%Y/%B/%d %H:%M")
Out[78]:
shape: (2,)
Series: '' [datetime[μs]]
[
        2000-12-01 00:00:00
        2001-01-01 00:00:00
]
```
