### ISSUE TITLE
.max().over() may return several rows and subsequent filtering does not work 

### ISSUE THREAD

**Issue by schakalakka** [pola-rs/polars#7392]
### Polars version checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pypi.org/project/polars/) of Polars.

### Issue description

I wanted to get the rows with the maximum value in a specific column througha window function. 
If two rows have same value in the specific column the window functions returns both of them. 

I did not expect that, but fine. I tried to filter afterwards but then I got an error saying that there should not be no nth at this point. 

I do not want to group by because therer are acutally more columns which I want to keep. 

### Reproducible example

```python
df = pl.DataFrame(
    data={"a": [True, False, True, False], "b": [7, 7, 1, 2], "c": [1, 1, 2, 2]}
)

shape: (4, 3)
┌───────┬─────┬─────┐
│ a     ┆ b   ┆ c   │
│ ---   ┆ --- ┆ --- │
│ bool  ┆ i64 ┆ i64 │
╞═══════╪═════╪═════╡
│ true  ┆ 7   ┆ 1   │
│ false ┆ 7   ┆ 1   │
│ true  ┆ 1   ┆ 2   │
│ false ┆ 2   ┆ 2   │

df.filter(pl.col("b") == pl.col("b").max().over(["c"]))
shape: (3, 3)
┌───────┬─────┬─────┐
│ a     ┆ b   ┆ c   │
│ ---   ┆ --- ┆ --- │
│ bool  ┆ i64 ┆ i64 │
╞═══════╪═════╪═════╡
│ true  ┆ 7   ┆ 1   │
│ false ┆ 7   ┆ 1   │
│ false ┆ 2   ┆ 2   │
└───────┴─────┴─────┘

df.filter(pl.col("b") == pl.col("b").max().over(["c"])).filter(
    pl.first().over(["c"])
)

thread '<unnamed>' panicked at 'should be no nth at this point', D:\a\polars\polars\polars\polars-lazy\src\physical_plan\planner\expr.rs:614:19
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
Traceback (most recent call last):
  File "C:\Users\radk_an\.conda\envs\py311\Lib\site-packages\IPython\core\interactiveshell.py", line 3442, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-3-6a5b91b2240e>", line 7, in <module>
    df.filter(pl.col("b") == pl.col("b").max().over(["c"])).filter(pl.first().over(["c"]))
  File "C:\Users\radk_an\.conda\envs\py311\Lib\site-packages\polars\internals\dataframe\frame.py", line 3245, in filter
    .collect(no_optimization=True)
     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\radk_an\.conda\envs\py311\Lib\site-packages\polars\internals\lazyframe\frame.py", line 1430, in collect
    return pli.wrap_df(ldf.collect())
                       ^^^^^^^^^^^^^
pyo3_runtime.PanicException: should be no nth at this point
```

### Expected behavior

shape: (2, 3)
┌───────┬─────┬─────┐
│ a     ┆ b   ┆ c   │
│ ---   ┆ --- ┆ --- │
│ bool  ┆ i64 ┆ i64 │
╞═══════╪═════╪═════╡
│ true  ┆ 7   ┆ 1   │
│ false ┆ 2   ┆ 2   │
└───────┴─────┴─────┘

### Installed versions

<details>

```
pl.show_versions()
---Version info---
Polars: 0.16.11
Index type: UInt32
Platform: Windows-10-10.0.19044-SP0
Python: 3.11.0 | packaged by conda-forge | (main, Oct 25 2022, 06:12:32) [MSC v.1929 64 bit (AMD64)]
---Optional dependencies---
pyarrow: 10.0.1
pandas: 1.5.2
numpy: 1.23.5
fsspec: <not installed>
connectorx: 0.3.2_alpha.2
xlsx2csv: <not installed>
deltalake: <not installed>
matplotlib: 3.6.2
```

</details>

**Comment by cmdlineluser** [comment]
Not that it addresses the bug/exception - but you can still select all columns in `.groupby()`
```
(df
 .groupby("c")
 .agg(
    pl.all().take(
       pl.arg_where(pl.col("b") == pl.max("b"))
         .first()))
```
```
shape: (2, 3)
┌─────┬───────┬─────┐
│ c   ┆ a     ┆ b   │
│ --- ┆ ---   ┆ --- │
│ i64 ┆ bool  ┆ i64 │
╞═════╪═══════╪═════╡
│ 1   ┆ true  ┆ 7   │
│ 2   ┆ false ┆ 2   │
└─────┴───────┴─────┘
```
Or `.unique()`:
```
(df
 .with_columns(d = pl.col("b") == pl.col("b").max().over("c"))
 .unique(subset="c"))
```
```
shape: (2, 4)
┌──────┬─────┬─────┬───────┐
│ a    ┆ b   ┆ c   ┆ d     │
│ ---  ┆ --- ┆ --- ┆ ---   │
│ bool ┆ i64 ┆ i64 ┆ bool  │
╞══════╪═════╪═════╪═══════╡
│ true ┆ 7   ┆ 1   ┆ true  │
│ true ┆ 1   ┆ 2   ┆ false │
└──────┴─────┴─────┴───────┘
```

**Comment by schakalakka** [comment]
Thank you for the solution @cmdlineluser!
I am using the unique() approach right now (because I did not know take and arg_where so far).  

@s-banach: For my use case first is not even necessary. I only wanted to select one of the possible lines. Could have been last() or random too.
