### ISSUE TITLE
Ambiguous time bug

### ISSUE THREAD

**Issue by tim-habitat** [pola-rs/polars#7418]
### Polars version checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pypi.org/project/polars/) of Polars.

### Issue description

In some functions in `polars` certain times with different timezone are considered `ambiguous` (e.g `2021-11-07T01:00:00CDT` and  `2021-11-07T01:00:00CST`) whereas they are not as the timezone is well specified. This happens in the following example but also in `groupby`.
I'm not sure why in some other function they are not considered `amiguous` though, e.g in `convert_time_zone` works fine.

``` python
>>> pl.date_range(datetime(2021,11,7), datetime(2021,11,8), "1h", time_zone="US/Central")
thread '<unnamed>' panicked at 'Ambiguous local time, ranging from 2021-11-07T01:00:00CDT to 2021-11-07T01:00:00CST', /Users/runner/.cargo/registry/src/github.com-1ecc6299db9ec823/chrono-0.4.23/src/offset/mod.rs:189:17
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/***/***/lib/python3.10/site-packages/polars/internals/functions.py", line 497, in date_range
    _py_date_range(start, stop, interval, closed, name, tu, time_zone)
pyo3_runtime.PanicException: Ambiguous local time, ranging from 2021-11-07T01:00:00CDT to 2021-11-07T01:00:00CST
>>> pl.date_range(datetime(2021,11,7), datetime(2021,11,8), "1h", time_zone="UTC").dt.convert_time_zone("US/Central")
shape: (25,)
Series: '' [datetime[μs, US/Central]]
[
	2021-11-06 19:00:00 CDT
	2021-11-06 20:00:00 CDT
	2021-11-06 21:00:00 CDT
	2021-11-06 22:00:00 CDT
	2021-11-06 23:00:00 CDT
	2021-11-07 00:00:00 CDT
	2021-11-07 01:00:00 CDT
	2021-11-07 01:00:00 CST
	2021-11-07 02:00:00 CST
	2021-11-07 03:00:00 CST
	2021-11-07 04:00:00 CST
	2021-11-07 05:00:00 CST
	2021-11-07 06:00:00 CST
	2021-11-07 07:00:00 CST
	2021-11-07 08:00:00 CST
	2021-11-07 09:00:00 CST
	2021-11-07 10:00:00 CST
	2021-11-07 11:00:00 CST
	2021-11-07 12:00:00 CST
	2021-11-07 13:00:00 CST
	2021-11-07 14:00:00 CST
	2021-11-07 15:00:00 CST
	2021-11-07 16:00:00 CST
	2021-11-07 17:00:00 CST
	2021-11-07 18:00:00 CST
]
```

Failure on a `groupby`. The fail on a `groupby` seems to have been introduced in `0.16.10` as on `0.16.9` i don't get that error.
```python
t2 =pl.date_range(datetime(2021,11,7), datetime(2021,11,8), "1m", time_zone="UTC").dt.convert_time_zone("US/Central")
>>> df = pl.DataFrame({"time":t2, "value": range(1441)})
>>> df.groupby_dynamic("time", every="1h").agg(pl.col("value").mean())
thread '<unnamed>' panicked at 'Ambiguous local time, ranging from 2021-11-07T01:00:00CDT to 2021-11-07T01:00:00CST', /Users/runner/.cargo/registry/src/github.com-1ecc6299db9ec823/chrono-0.4.23/src/offset/mod.rs:189:17
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/***/lib/python3.10/site-packages/polars/internals/dataframe/groupby.py", line 929, in agg
    self.df.lazy()
  File "/***/lib/python3.10/site-packages/polars/internals/lazyframe/frame.py", line 1430, in collect
    return pli.wrap_df(ldf.collect())
pyo3_runtime.PanicException: Ambiguous local time, ranging from 2021-11-07T01:00:00CDT to 2021-11-07T01:00:00CST
>>> pl.__version__
'0.16.11'
```

```python
>>> t2 =pl.date_range(datetime(2021,11,7), datetime(2021,11,8), "1m", time_zone="UTC").dt.convert_time_zone("US/Central")
>>> df = pl.DataFrame({"time":t2, "value": range(1441)})
>>> df.groupby_dynamic("time", every="1h").agg(pl.col("value").mean())
shape: (25, 2)
┌──────────────────────────┬────────┐
│ time                     ┆ value  │
│ ---                      ┆ ---    │
│ datetime[μs, US/Central] ┆ f64    │
╞══════════════════════════╪════════╡
│ 2021-11-06 19:00:00 CDT  ┆ 29.5   │
│ 2021-11-06 20:00:00 CDT  ┆ 89.5   │
│ 2021-11-06 21:00:00 CDT  ┆ 149.5  │
│ 2021-11-06 22:00:00 CDT  ┆ 209.5  │
│ ...                      ┆ ...    │
│ 2021-11-07 15:00:00 CST  ┆ 1289.5 │
│ 2021-11-07 16:00:00 CST  ┆ 1349.5 │
│ 2021-11-07 17:00:00 CST  ┆ 1409.5 │
│ 2021-11-07 18:00:00 CST  ┆ 1440.0 │
└──────────────────────────┴────────┘
>>> pl.__version__
'0.16.8'


```

Sorry for the `timezone` pounding ... 

### Reproducible example

```python
from datetime import datetime
import polars as pl
t1 = pl.date_range(datetime(2021,11,7), datetime(2021,11,8), "1h", time_zone="US/Central")  # fails
t2 = pl.date_range(datetime(2021,11,7), datetime(2021,11,8), "1h", time_zone="UTC").dt.convert_time_zone("US/Central") # works as intended

t2 =pl.date_range(datetime(2021,11,7), datetime(2021,11,8), "1m", time_zone="UTC").dt.convert_time_zone("US/Central")
df = pl.DataFrame({"time":t2, "value": range(1441)})
df.groupby_dynamic("time", every="1h").agg(pl.col("value").mean())
```

### Expected behavior

I expect `t1` in the example to works as `t2`.

`2021-11-07T01:00:00CDT` and  `2021-11-07T01:00:00CST` are not ambiguous as they are different times (based on the timezone).

### Installed versions

<details>

```
Polars: 0.16.11
Index type: UInt32
Platform: macOS-13.2.1-x86_64-i386-64bit
Python: 3.10.10 (main, Feb 16 2023, 02:55:02) [Clang 14.0.0 (clang-1400.0.29.202)]
---Optional dependencies---
pyarrow: 10.0.1
pandas: 1.5.0
numpy: 1.23.3
fsspec: <not installed>
connectorx: <not installed>
xlsx2csv: <not installed>
deltalake: <not installed>
matplotlib: 3.7.0
```

</details>

**Comment by MarcoGorelli** [comment]
`2021-11-07T01:00:00` failing looks expected - if you've only given `US/Central`, then how should it know whether to take the `CDT` or the `CST` one?

pandas would also error:
```python
In [10]: pd.Timestamp('2021-11-07T01:00:00').tz_localize('US/Central')
---------------------------------------------------------------------------
AmbiguousTimeError: Cannot infer dst time from 2021-11-07 01:00:00, try using the 'ambiguous' argument
```

The `groupby_dynamic` one looks like it might be a bug though, I'll take look - thanks for reporting!

**Comment by tim-habitat** [comment]
> `2021-11-07T01:00:00` failing looks expected - if you've only given US/Central, then how should it know whether to take the CDT or the CST one?

Well, to me it should output both. Why by doing `UTC` then `convert_time_zone` would work (by duplicating the hour and assigning each a different time zone) and not direct ?

Also, `pandas` doesn't fail on that and works as expected:
```python
>>> import pandas as pd
>>> pd.__version__
'1.5.3'
>>> pd.date_range("2021-11-07", "2021-11-08", freq="H", tz="US/Central")
DatetimeIndex(['2021-11-07 00:00:00-05:00', '2021-11-07 01:00:00-05:00',
               '2021-11-07 01:00:00-06:00', '2021-11-07 02:00:00-06:00',
               '2021-11-07 03:00:00-06:00', '2021-11-07 04:00:00-06:00',
               '2021-11-07 05:00:00-06:00', '2021-11-07 06:00:00-06:00',
               '2021-11-07 07:00:00-06:00', '2021-11-07 08:00:00-06:00',
               '2021-11-07 09:00:00-06:00', '2021-11-07 10:00:00-06:00',
               '2021-11-07 11:00:00-06:00', '2021-11-07 12:00:00-06:00',
               '2021-11-07 13:00:00-06:00', '2021-11-07 14:00:00-06:00',
               '2021-11-07 15:00:00-06:00', '2021-11-07 16:00:00-06:00',
               '2021-11-07 17:00:00-06:00', '2021-11-07 18:00:00-06:00',
               '2021-11-07 19:00:00-06:00', '2021-11-07 20:00:00-06:00',
               '2021-11-07 21:00:00-06:00', '2021-11-07 22:00:00-06:00',
               '2021-11-07 23:00:00-06:00', '2021-11-08 00:00:00-06:00'],
              dtype='datetime64[ns, US/Central]', freq='H')
>>> 
```

**Comment by MarcoGorelli** [comment]
you're right, thanks, it does work within `date_range`. there shouldn't be any ambiguity there, so that should probably work

I'll take a look

**Comment by MarcoGorelli** [comment]
I've opened a PR for the date_range issue ( #7430) - any chance you could open another issue for the `groupby_dynamic` one please? Else I'll do it later, no worries

**Comment by ritchie46** [comment]
@MarcoGorelli FYI
