### ISSUE TITLE
Thread safety bug converting pandas to polars

### ISSUE THREAD

**Issue by grantslatton** [pola-rs/polars#7577]
### Polars version checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pypi.org/project/polars/) of Polars.

### Issue description

I am calling polars from Rust with pyo3. I have multiple Rust threads. When converting a sliced pandas dataframe to polars, I occasionally get unexpected `KeyError`s.

### PyArrow suspicions

I believe it is possible this is actually a bug in pyarrow, but I am not 100% certain.

Specifically, I am suspicious of this line using `with nogil`

https://github.com/apache/arrow/blob/main/python/pyarrow/array.pxi#L38

and then calling out to this function

https://github.com/apache/arrow/blob/main/python/pyarrow/includes/libarrow_python.pxd#L63-L67

which as a comment `TODO Some functions below are not actually "nogil"`

### Notes on repro test below

1. Only happens with multiple threads
2. Was not able to trigger from pure python with the `threading` module, just from Rust with 2 rust threads, but this may be due to my lack of knowledge of python threading
3. Only happens when the pandas dataframe is sliced from a non-zero index, e.g. the example below does `x.iloc[5:10]`. If you change the 5 to 0 the bug doesn't happen.

### Reproducible example

```python
#[test]
    fn pyo3_polars_concurrency_failure() {
        loop {
            let mut handles = vec![];
            for _ in 0..2 {
                let handle = std::thread::spawn(|| {
                    let code = r#"
import pandas
import polars
import traceback
x = pandas.DataFrame(list(range(100)))
y = x.iloc[5:10]
try:
    polars.from_pandas(y)
except Exception as e:
    traceback.print_exc()
    raise e
                    "#;
                    pyo3::Python::with_gil(|py| {
                        py.run(code, None, None).unwrap();
                    });
                });
                handles.push(handle);
            }
            for handle in handles {
                handle.join().unwrap();
            }
        }
    }
```

Error:

```
Traceback (most recent call last):
  File "/opt/homebrew/Cellar/python@3.10/3.10.10_1/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/pandas/core/indexes/range.py", line 391, in get_loc
    return self._range.index(new_key)
ValueError: 0 is not in range

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "<string>", line 8, in <module>
  File "/opt/homebrew/Cellar/python@3.10/3.10.10_1/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/polars/utils.py", line 498, in wrapper
    return function(*args, **kwargs)
  File "/opt/homebrew/Cellar/python@3.10/3.10.10_1/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/polars/utils.py", line 433, in wrapper
    return function(*args, **kwargs)
  File "/opt/homebrew/Cellar/python@3.10/3.10.10_1/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/polars/convert.py", line 486, in from_pandas
    return DataFrame._from_pandas(
  File "/opt/homebrew/Cellar/python@3.10/3.10.10_1/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/polars/utils.py", line 433, in wrapper
    return function(*args, **kwargs)
  File "/opt/homebrew/Cellar/python@3.10/3.10.10_1/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/polars/internals/dataframe/frame.py", line 642, in _from_pandas
    pandas_to_pydf(
  File "/opt/homebrew/Cellar/python@3.10/3.10.10_1/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/polars/utils.py", line 433, in wrapper
    return function(*args, **kwargs)
  File "/opt/homebrew/Cellar/python@3.10/3.10.10_1/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/polars/internals/construction.py", line 1405, in pandas_to_pydf
    arrow_dict[str(col)] = _pandas_series_to_arrow(
  File "/opt/homebrew/Cellar/python@3.10/3.10.10_1/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/polars/utils.py", line 433, in wrapper
    return function(*args, **kwargs)
  File "/opt/homebrew/Cellar/python@3.10/3.10.10_1/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/polars/internals/construction.py", line 494, in _pandas_series_to_arrow
    return pa.array(values, from_pandas=nan_to_null)
  File "pyarrow/array.pxi", line 320, in pyarrow.lib.array
  File "pyarrow/array.pxi", line 39, in pyarrow.lib._sequence_to_array
  File "pyarrow/error.pxi", line 144, in pyarrow.lib.pyarrow_internal_check_status
  File "/opt/homebrew/Cellar/python@3.10/3.10.10_1/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/pandas/core/series.py", line 981, in __getitem__
    return self._get_value(key)
  File "/opt/homebrew/Cellar/python@3.10/3.10.10_1/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/pandas/core/series.py", line 1089, in _get_value
    loc = self.index.get_loc(label)
  File "/opt/homebrew/Cellar/python@3.10/3.10.10_1/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/pandas/core/indexes/range.py", line 393, in get_loc
    raise KeyError(key) from err
KeyError: 0
```
```


### Expected behavior

Expected no error.

### Installed versions

<details>

```
---Version info---
Polars: 0.16.9
Index type: UInt32
Platform: macOS-12.5.1-arm64-arm-64bit
Python: 3.10.10 (main, Feb 16 2023, 02:46:59) [Clang 14.0.0 (clang-1400.0.29.202)]
---Optional dependencies---
pyarrow: 11.0.0
pandas: 1.5.3
numpy: 1.23.3
fsspec: 2022.11.0
connectorx: <not installed>
xlsx2csv: <not installed>
deltalake: <not installed>
matplotlib: 3.6.2
```

</details>

**Comment by zundertj** [comment]
Given you point to PyArrow source code as the potential issue, and your stack trace points to Pandas, is this a Polars bug at all? For example, does this also occur if you use [PyArrow.Table.from_pandas](https://arrow.apache.org/docs/python/generated/pyarrow.Table.html#pyarrow.Table.from_pandas) rather than `Polars.from_pandas`?

**Comment by grantslatton** [comment]
Replacing `polars.from_pandas` with `pyarrow.Table.from_pandas` *does not* encounter the same bug. So `polars` is inducing some different behavior here somehow.
