### ISSUE TITLE
Construction of list-type series fails (regression in 0.16.14)

### ISSUE THREAD

**Issue by martin-wiebusch-thg** [pola-rs/polars#7682]
### Polars version checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pypi.org/project/polars/) of Polars.

### Issue description

In polars 0.16.14 the following code

```python
import polars as pl
import numpy as np
pl.Series('a', [np.arange(2), np.arange(3)], dtype=pl.List(pl.Int64))
```
fails with
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/wiebuschm/.pyenv/versions/recommendations/lib/python3.10/site-packages/polars/series/series.py", line 261, in __init__
    self._s = sequence_to_pyseries(
  File "/Users/wiebuschm/.pyenv/versions/recommendations/lib/python3.10/site-packages/polars/internals/construction.py", line 352, in sequence_to_pyseries
    return sequence_from_anyvalue_or_object(name, values).cast(
exceptions.InvalidOperationError: `cast` operation not supported for dtype `object`
```
The same worked fine in 0.16.13.

Not that the code also works if I omit the `dtype` keyword argument.

### Reproducible example

```python
see above
```

### Expected behavior

It should construct the series.

### Installed versions

<details>

```
---Version info---
Polars: 0.16.14
Index type: UInt32
Platform: macOS-13.2.1-x86_64-i386-64bit
Python: 3.10.7 (main, Nov  3 2022, 15:57:55) [Clang 14.0.0 (clang-1400.0.29.202)]
---Optional dependencies---
numpy: 1.24.2
pandas: 1.5.3
pyarrow: 11.0.0
connectorx: 0.3.1
deltalake: <version not detected>
fsspec: 2023.3.0
matplotlib: 3.7.1
xlsx2csv: 0.8.1
xlsxwriter: 3.0.9
```

</details>

**Comment by alexander-beedie** [comment]
Thanks for the heads-up and the test-case; I was surprised this slipped through as we actually have quite a lot of numpy/series init tests - and now we have one more... ;)
