### ISSUE TITLE
Exception raised in groupby.apply(UDF) causes panic and loses traceback

### ISSUE THREAD

**Issue by 2-5** [pola-rs/polars#7704]
### Polars version checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pypi.org/project/polars/) of Polars.

### Issue description

If a UDF passed to `groupby.apply` throws, the exception traceback is lost. This makes debugging harder.

### Reproducible example

```python
import polars as pl

def func(df):
    assert False
    # raise ValueError("some error")

df = pl.DataFrame({
    "a": [1, 1, 2, 3],
})
df.groupby("a").apply(func)


Outputs:

```python
Traceback (most recent call last):
  File "test.py", line 14, in <module>
    df.groupby("a").apply(func)
  File ".venv\lib\site-packages\polars\utils\decorators.py", line 35, in wrapper
    return function(*args, **kwargs)
  File ".venv\lib\site-packages\polars\dataframe\groupby.py", line 327, in apply
    self.df._df.groupby_apply(by, function, self.maintain_order)
pyo3_runtime.PanicException: UDF failed:
```
```


### Expected behavior

Exception raised in UDF is preserved and shown to the user instead of a `PanicException`.

### Installed versions

<details>

```
---Version info---
Polars: 0.16.14
Index type: UInt32
Platform: Windows-10-10.0.19045-SP0
Python: 3.10.8 (tags/v3.10.8:aaaf517, Oct 11 2022, 16:50:30) [MSC v.1933 64 bit (AMD64)]
---Optional dependencies---
numpy: 1.23.5
pandas: 1.5.3
pyarrow: 11.0.0
connectorx: <not installed>
deltalake: <not installed>
fsspec: 2023.1.0
matplotlib: 3.7.1
xlsx2csv: <not installed>
xlsxwriter: <not installed>
```

</details>

**Comment by stinodego** [comment]
I think this will be extremely hard to add, but it would be nice to have. It's not really a bug though, and the error message is still displayed normally, so it's not all that bad.

**Comment by OWissett** [comment]
I have a work around for this, it isn't too nice but seems to work.

When trying to debug a groupby.map_groups function, I found that I can manually capture the exception and print it to the user,

e.g.

```python
import polars as pl
from traceback import print_exc

def func(df) -> pl.DataFrame:
    try:
         assert False
         # do your real logic here
    except Exception as e:
         print_exc()
         print(f"Error: {e}")
       

df = pl.DataFrame({"a": [1, 2, 3]})
df.groupby("a").map_groups(func)
```

**Comment by OWissett** [comment]
This only provides insights into whats happening inside Python land though, which is fine for debugging your UDF
