### ISSUE TITLE
Head operation lead to Panic Exception after filtering and sorting (LazyFrame)

### ISSUE THREAD

**Issue by LdRoW** [pola-rs/polars#7769]
### Polars version checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pypi.org/project/polars/) of Polars.

### Issue description

Head operation lead to PanicException after filtering and sorting:
```
thread '<unnamed>' panicked at 'partition_at_index index 1 greater than length of slice 1', /rustc/a266f11990d9544ee408e213e1eec8cc9eb032b7/library/core/src/slice/sort.rs:999:9
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
Traceback (most recent call last):
  File "/home/test/test/test1.py", line 11, in <module>
    lf.filter(pl.col("a") == 1).lazy().sort("a").head(1).collect()
  File "/home/test/test/venv/lib/python3.10/site-packages/polars/lazyframe/frame.py", line 1475, in collect
    return wrap_df(ldf.collect())
pyo3_runtime.PanicException: partition_at_index index 1 greater than length of slice 1
```

### Reproducible example

```python
import polars as pl

lf = pl.DataFrame(
    {
        "a": [1, 2, 3, 4, 5],
        "b": [2, 2, 2, 2, 2],
    }
)

lf.lazy().filter(pl.col("a") == 1).sort("a").head(1).collect()
```

### Expected behavior

```python
┌─────┬─────┐
│ a   ┆ b   │
│ --- ┆ --- │
│ i64 ┆ i64 │
╞═════╪═════╡
│ 1   ┆ 2   │
└─────┴─────┘

```

### Installed versions

<details>

```
---Version info---
Polars: 0.16.15
Index type: UInt32
Platform: Linux-5.15.0-53-generic-x86_64-with-glibc2.35
Python: 3.10.6 (main, Jan  8 2023, 09:58:07) [GCC 11.3.0]
---Optional dependencies---
numpy: 1.24.2
pandas: 1.5.3
pyarrow: 11.0.0
connectorx: <not installed>
deltalake: <not installed>
fsspec: <not installed>
matplotlib: <not installed>
xlsx2csv: <not installed>
xlsxwriter: <not installed>
```

</details>

**Comment by ritchie46** [comment]
fixed and released.
