### ISSUE TITLE
limit PanicException in latest polars release 

### ISSUE THREAD

**Issue by marsupialtail** [pola-rs/polars#7776]
### Polars version checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pypi.org/project/polars/) of Polars.

### Issue description

Somewhere between 0.16.13 and 0.16.15, the below code ceased to work: 

### Reproducible example

```python
>>> a
shape: (1, 8)
┌────────────┬────────────┬─────┬────────────┬────────────┬────────────┬─────────┬───────┐
│ source_act ┆ source_cha ┆ seq ┆ target_act ┆ partition_ ┆ target_cha ┆ min_seq ┆ stage │
│ or_id      ┆ nnel_id    ┆ --- ┆ or_id      ┆ fn         ┆ nnel_id    ┆ ---     ┆ ---   │
│ ---        ┆ ---        ┆ i64 ┆ ---        ┆ ---        ┆ ---        ┆ i64     ┆ i64   │
│ i64        ┆ i64        ┆     ┆ i64        ┆ i64        ┆ i64        ┆         ┆       │
╞════════════╪════════════╪═════╪════════════╪════════════╪════════════╪═════════╪═══════╡
│ 0          ┆ 1          ┆ 0   ┆ 1          ┆ 0          ┆ 0          ┆ 0       ┆ 0     │
└────────────┴────────────┴─────┴────────────┴────────────┴────────────┴─────────┴───────┘
>>> a.lazy().filter(polars.col("stage") == 0).sort("seq").limit(30).collect()
thread '<unnamed>' panicked at 'partition_at_index index 30 greater than length of slice 1', /rustc/a266f11990d9544ee408e213e1eec8cc9eb032b7/library/core/src/slice/sort.rs:999:9
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/ziheng/miniconda3/envs/quokka-dev/lib/python3.8/site-packages/polars/lazyframe/frame.py", line 1475, in collect
    return wrap_df(ldf.collect())
pyo3_runtime.PanicException: partition_at_index index 30 greater than length of slice 1
```

### Expected behavior

Not PanicException

### Installed versions

<details>

```
0.16.15
```

</details>

**Comment by ritchie46** [comment]
Can you create a minimal example? E.g. create your dataframe in code.
