### ISSUE TITLE
Excel export cannot handle lists

### ISSUE THREAD

**Issue by Walnut356** [pola-rs/polars#7868]
### Polars version checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pypi.org/project/polars/) of Polars.

### Issue description

Dataframes containing dtypes of list[type] error out the excel writer. It looks like the column type is being assigned incorrectly. Current workaround is to_pandas().to_excel() because pandas handles it alright.

### Reproducible example

```python
import polars as pl

eef = pl.DataFrame({"freef": [[1, 2, 3], [4, 5, 6]]})

eef.write_excel("sbubby.xlsx")

```
Traceback (most recent call last):
  File "C:\Users\Allah\AppData\Local\Programs\Python\Python311\Lib\site-packages\xlsxwriter\worksheet.py", line 523, in _write
    f = float(token)
        ^^^^^^^^^^^^
TypeError: float() argument must be a string or a real number, not 'list'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "f:\Coding and Programming\My Projects\VSC\pyrust-test\main.py", line 5, in <module>
    eef.write_excel("sbubby.xlsx")
  File "C:\Users\Allah\AppData\Local\Programs\Python\Python311\Lib\site-packages\polars\internals\dataframe\frame.py", line 2702, in write_excel
    ws.add_table(
  File "C:\Users\Allah\AppData\Local\Programs\Python\Python311\Lib\site-packages\xlsxwriter\worksheet.py", line 122, in cell_wrapper
    return method(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Allah\AppData\Local\Programs\Python\Python311\Lib\site-packages\xlsxwriter\worksheet.py", line 3295, in add_table
    self._write(row, col, token, col_formats[j])
  File "C:\Users\Allah\AppData\Local\Programs\Python\Python311\Lib\site-packages\xlsxwriter\worksheet.py", line 528, in _write
    raise TypeError("Unsupported type %s in write()" % type(token))
TypeError: Unsupported type <class 'list'> in write()
```
```

### Expected behavior

Exact same data with Pandas handles it properly:

```python
import pandas as pd

eef = pd.DataFrame({"freef": [[1, 2, 3], [4, 5, 6]]})

eef.to_excel("sbubby.xlsx")
```
[sbubby google sheet](https://docs.google.com/spreadsheets/d/1CL52cF65umkVFi5-JswjE3V_vrdkpRjs6kDwk9LD8tg/edit?usp=sharing)

### Installed versions

<details>

```
---Version info---
Polars: 0.16.13   
Index type: UInt32
Platform: Windows-10-10.0.19044-SP0
Python: 3.11.2 (tags/v3.11.2:878ead1, Feb  7 2023, 16:38:35) [MSC v.1934 64 bit (AMD64)]
---Optional dependencies---
numpy: 1.24.1
pandas: 1.5.2
pyarrow: 11.0.0
connectorx: <not installed>
deltalake: <not installed>
fsspec: <not installed>
matplotlib: 3.6.3
xlsx2csv: <not installed>
xlsxwriter: 3.0.7
```

</details>

**Comment by alexander-beedie** [comment]
Hmm... it appears that pandas just cast it to string as Excel doesn't support list/array types; seems like reasonable-enough behaviour - I'll take a look at handling that automatically.
