### ISSUE TITLE
df.sort([]) panics

### ISSUE THREAD

**Issue by H-M-H** [pola-rs/polars#795]
#### Are you using Python or Rust?
Both.

#### Which feature gates did you use?
`features = ["temporal", "lazy", "dtype-full", "ipc", "strings"]`

#### What version of polars are you using?
Rust: 0.14.1
Python: 0.8.5

#### What operating system are you using polars on?
Arch Linux.

#### What are the steps to reproduce the behavior?
```python
#!/usr/bin/env python

import polars as pl

print(pl.version())

df = pl.read_csv("https://j.mp/iriscsv")
print(df.sort([]))

# also panics
print(df.lazy().sort([]).collect())
```
Output:
```
0.8.5
thread '<unnamed>' panicked at 'removal index (is 0) should be < len (is 0)', library/alloc/src/vec/mod.rs:1347:13
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
Traceback (most recent call last):
  File "/home/hmh/test/./polars_error.py", line 8, in <module>
    print(df.sort([]))
  File "/home/hmh/.local/lib/python3.9/site-packages/polars/frame.py", line 1039, in sort
    self.lazy()
  File "/home/hmh/.local/lib/python3.9/site-packages/polars/lazy/__init__.py", line 333, in collect
    return wrap_df(ldf.collect())
pyo3_runtime.PanicException: removal index (is 0) should be < len (is 0)
```

#### What is the expected behavior?
I'd expect this to be a no-op instead of an error.

**Comment by ritchie46** [comment]
Made it a no-op :+1:
