### ISSUE TITLE
Issue printing Series of dtype `Time`

### ISSUE THREAD

**Issue by stinodego** [pola-rs/polars#7971]
### Polars version checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pypi.org/project/polars/) of Polars.

### Issue description

When initializing a `Time` Series with a large integer, the Series initializes fine, but print no longer works.

### Reproducible example

```python
from __future__ import annotations

import polars as pl

s = pl.Series([172000000000000], dtype=pl.Time)
print(s)
```

Results in:

```
thread '<unnamed>' panicked at 'invalid time', /root/.cargo/git/checkouts/arrow2-945af624853845da/dd53a88/src/temporal_conversions.rs:103:6
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
Traceback (most recent call last):
  File "/home/stijn/ah/ah-sa-bakplan-calculator/repro.py", line 6, in <module>
    print(s)
  File "/home/stijn/ah/ah-sa-bakplan-calculator/.venv/lib/python3.11/site-packages/polars/series/series.py", line 418, in __str__
    s_repr: str = self._s.as_str()
                  ^^^^^^^^^^^^^^^^
pyo3_runtime.PanicException: invalid time
```

### Expected behavior

If it's an invalid Time, it should error on initialization.
If it's a valid Time, it should print normally.

### Installed versions

Show versions util is broken for me - `AttributeError: module 'importlib' has no attribute 'metadata'`

**Comment by zundertj** [comment]
> Show versions util is broken for me - AttributeError: module 'importlib' has no attribute 'metadata'

On which Python version is that happening?

**Comment by stinodego** [comment]
Python 3.11.2 right now, but I believe I saw it on earlier 3.11 versions too.

```
Python 3.11.2 (main, Mar 31 2023, 16:17:48) [GCC 11.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import polars as pl
>>> pl.show_versions()
---Version info---
Polars: 0.16.16
Index type: UInt32
Platform: Linux-5.10.102.1-microsoft-standard-WSL2-x86_64-with-glibc2.35
Python: 3.11.2 (main, Mar 31 2023, 16:17:48) [GCC 11.3.0]
---Optional dependencies---
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/stijn/ah/ah-sa-bakplan-calculator/.venv/lib/python3.11/site-packages/polars/utils/show_versions.py", line 44, in show_versions
    deps = _get_dependency_info()
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/home/stijn/ah/ah-sa-bakplan-calculator/.venv/lib/python3.11/site-packages/polars/utils/show_versions.py", line 62, in _get_dependency_info
    return {name: _get_dependency_version(name) for name in opt_deps}
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/stijn/ah/ah-sa-bakplan-calculator/.venv/lib/python3.11/site-packages/polars/utils/show_versions.py", line 62, in <dictcomp>
    return {name: _get_dependency_version(name) for name in opt_deps}
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/stijn/ah/ah-sa-bakplan-calculator/.venv/lib/python3.11/site-packages/polars/utils/show_versions.py", line 75, in _get_dependency_version
    module_version = importlib.metadata.version(dep_name)
                     ^^^^^^^^^^^^^^^^^^
AttributeError: module 'importlib' has no attribute 'metadata'
```

**Comment by ritchie46** [comment]
Fixed in main.
