### ISSUE TITLE
Allow arithmetic between `Time` and `Duration` columns

### ISSUE THREAD

**Issue by stinodego** [pola-rs/polars#7972]
### Problem description

I'd like to be able to do the following:

```python
from datetime import time, timedelta

import polars as pl
from polars.testing import assert_series_equal

s_time = pl.Series([time(8, 0), time(9, 0)])
s_duration = pl.Series([timedelta(hours=3), timedelta(hours=4)])

result = s_time + s_duration

expected = pl.Series([time(11, 0), time(13, 0)])
assert_series_equal(result, expected)
```

Currently, this raises the following error:

```
Traceback (most recent call last):
  File "/home/stijn/ah/ah-sa-bakplan-calculator/repro.py", line 11, in <module>
    result = s_time + s_duration
             ~~~~~~~^~~~~~~~~~~~
  File "/home/stijn/ah/ah-sa-bakplan-calculator/.venv/lib/python3.11/site-packages/polars/series/series.py", line 572, in __add__
    return self._arithmetic(other, "add", "add_<>")
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/stijn/ah/ah-sa-bakplan-calculator/.venv/lib/python3.11/site-packages/polars/series/series.py", line 537, in _arithmetic
    return self._from_pyseries(getattr(self._s, op_s)(other._s))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
exceptions.ComputeError: failed to determine supertype of time and duration[μs]
```

I can work around this by working with a Datetime column with a random date:

```python
from __future__ import annotations

from datetime import datetime, time, timedelta

import polars as pl
from polars.testing import assert_series_equal

s_datetime = pl.Series([datetime(2021, 1, 1, 8, 0), datetime(2021, 1, 1, 9, 0)])
s_duration = pl.Series([timedelta(hours=3), timedelta(hours=4)])

result = (s_datetime + s_duration).dt.time()

expected = pl.Series([time(11, 0), time(13, 0)])
assert_series_equal(result, expected)  # Succeeds!
```

**Comment by ritchie46** [comment]
What should the return type be? I don't  think it should be a `time` as not every duration fits within that.

**Comment by stinodego** [comment]
I would say it should be a `Time` type. Every duration fits that as the clock starts at 00:00 again after 23:59:59.

Basically, it would be exactly the same as my workaround - impact on days is discarded.

**Comment by david-waterworth** [comment]
I need to do this as well (see https://stackoverflow.com/questions/79485612/adding-hours-to-a-polars-time-column-in-python/79487220#79487220)

I see two issues though, first you have to handle over/underflow - i.e. if you subtract 2 hours fro 01:00 do you return 23:00 or 00:00 (probably want a behaviour field here as both are valid in different circumstances)

Second as you mention a duration contains non-time fields. One option is to ignore them as in theory they should roll around to the same time on a different day (i.e. 12:00 - 1w = 12:00, 12:00 - (1w 1h) = 11:00 etc)

**Comment by juanmpga** [comment]
Just wanted to mention it'd be great if this were implemented.

As an alternative approach, two durations can be added/subtracted so if it were possible to cast `Duration` into `Time` (discarding days or weeks as you point out) I think that would do it.
