### ISSUE TITLE
map_dict fails when keys are boolean and values are string

### ISSUE THREAD

**Issue by mcrumiller** [pola-rs/polars#7992]
### Polars version checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pypi.org/project/polars/) of Polars.

### Issue description

When keys are boolean and values are string, an exception is raised

#### Doesn't raise Exception, but doesn't return 1/0
```python
pl.Series([True, False]).map_dict({True: 1, False: 0})
```
```
shape: (2,)
Series: '' [bool]
[
        true
        false
]
```
#### Fails
```python
pl.Series([True, False]).map_dict({True: '1', False: '0'})  # fails
```
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\430015439\AppData\Local\Programs\Python\Python311\Lib\site-packages\polars\series\utils.py", line 102, in wrapper
    return s.to_frame().select(f(*args, **kwargs)).to_series()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\430015439\AppData\Local\Programs\Python\Python311\Lib\site-packages\polars\dataframe\frame.py", line 6643, in select
    .collect(no_optimization=True)
     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\430015439\AppData\Local\Programs\Python\Python311\Lib\site-packages\polars\lazyframe\frame.py", line 1475, in collect
    return wrap_df(ldf.collect())
                   ^^^^^^^^^^^^^
exceptions.ComputeError: ArrowErrorException: NotYetImplemented("Casting from LargeUtf8 to Boolean not supported")
```

### Expected behavior

Should return `pl.Series(['1', '0'])`.

### Installed versions

<details>

```
---Version info---
Polars: 0.16.18
Index type: UInt32
Platform: Windows-10-10.0.19044-SP0
Python: 3.11.2 (tags/v3.11.2:878ead1, Feb  7 2023, 16:38:35) [MSC v.1934 64 bit (AMD64)]
---Optional dependencies---
numpy: 1.24.2
pandas: 1.5.3
pyarrow: 11.0.0
connectorx: 0.3.2_alpha.2
deltalake: <not installed>
fsspec: <not installed>
matplotlib: 3.7.1
xlsx2csv: 0.8.1
xlsxwriter: 3.0.9
```

</details>

**Comment by ghuls** [comment]
Could you also show the full output of both commands?

This should work for now, till I fix this properly:
```python
pl.Series([True, False]).map_dict({True: 1, False: 0}, dtype=pl.Int8)
pl.Series([True, False]).map_dict({True: '1', False: '0'}, dtype=pl.Utf8)
```

**Comment by mcrumiller** [comment]
Hi @ghuls, sorry I should have included that. I've updated the OP with the output from both commands.

**Comment by mcrumiller** [comment]
And after running it, it looks like the "success" version isn't even mapping correctly.

**Comment by ghuls** [comment]
> And after running it, it looks like the "success" version isn't even mapping correctly.

I suspected that already. It is similar to https://github.com/pola-rs/polars/issues/7917

**Comment by zundertj** [comment]
Closing, as the code examples in the OP work on the master branch.
