### ISSUE TITLE
Improve usability of pl.Null Series when doing operations on them with Series with different dtypes.

### ISSUE THREAD

**Issue by ghuls** [pola-rs/polars#8030]
### Problem description

In https://github.com/pola-rs/polars/pull/7136 , `pl.Null` typed Series became slightly more useful, but there is still some work to do.

As suggested in https://github.com/pola-rs/polars/pull/8015, empty Series or Series with lists of only None, should have `pl.Null` as dtype- instead of pl.Float32, but at the moment I wouldn't recommend changing it as it likely will break quite some operations that work at the moment.

```python
# Empty Series.
In [46]: n0 = pl.Series("n0", None, dtype=pl.Null)

# Series with only one null element.
In [47]: n1 = pl.Series("n1", [None], dtype=pl.Null)

# Series with only two null element.
In [48]: n2 = pl.Series("n2", [None, None], dtype=pl.Null)

# Normal series.
In [49]: s = pl.Series("", [5, 3])
```

Printing `pl.Null` Series is suboptimal, but should be worked on in https://github.com/pola-rs/polars/issues/7153
 
```python
In [52]: n0
Out[52]: nullarray

In [53]: n1
Out[53]: nullarray

In [54]: n2
Out[54]: nullarray
```

`pl.Null` Series with `pl.Null` Series operations do not work:
```python
In [56]: n1 + n1
thread '<unnamed>' panicked at '`add` operation not supported for dtype `null`', /home/runner/work/polars/polars/polars/polars-core/src/series/series_trait.rs:149:13
---------------------------------------------------------------------------
PanicException                            Traceback (most recent call last)
Cell In[56], line 1
----> 1 n1 + n1

File ~/software/anaconda3/envs/polars/lib/python3.8/site-packages/polars/series/series.py:578, in Series.__add__(self, other)
    576 elif isinstance(other, pli.DataFrame):
    577     return other + self
--> 578 return self._arithmetic(other, "add", "add_<>")

File ~/software/anaconda3/envs/polars/lib/python3.8/site-packages/polars/series/series.py:543, in Series._arithmetic(self, other, op_s, op_ffi)
    541     other = self.to_frame().select(other).to_series()
    542 if isinstance(other, Series):
--> 543     return self._from_pyseries(getattr(self._s, op_s)(other._s))
    544 if _check_for_numpy(other) and isinstance(other, np.ndarray):
    545     return self._from_pyseries(getattr(self._s, op_s)(Series(other)._s))

PanicException: `add` operation not supported for dtype `null`

In [57]: n1 + s
Out[57]: 
shape: (2,)
Series: 'n1' [i64]
[
	null
	null
]
```

`pl.concat` does not work with `pl.Null` Series (see also https://github.com/pola-rs/polars/issues/7170 to a similar issue with `pl.Struct([pl.Field("a1", pl.Null)])` as dtype):
```python
In [70]: pl.concat([s, s])
Out[70]: 
shape: (4,)
Series: '' [i64]
[
	5
	3
	5
	3
]

In [71]: pl.concat([s, n2])
---------------------------------------------------------------------------
SchemaError                               Traceback (most recent call last)
Cell In[71], line 1
----> 1 pl.concat([s, n2])

File ~/software/anaconda3/envs/polars/lib/python3.8/site-packages/polars/utils/decorators.py:136, in deprecate_nonkeyword_arguments.<locals>.decorate.<locals>.wrapper(*args, **kwargs)
    134 if len(args) > num_allowed_args:
    135     warnings.warn(msg, DeprecationWarning, stacklevel=stacklevel)
--> 136 return function(*args, **kwargs)

File ~/software/anaconda3/envs/polars/lib/python3.8/site-packages/polars/functions/eager.py:279, in concat(items, rechunk, how, parallel)
    277 elif isinstance(first, pli.Series):
    278     if how == "vertical":
--> 279         out = wrap_s(_concat_series(elems))
    280     else:
    281         raise ValueError("'Series' only allows {{'vertical'}} concat strategy.")

SchemaError: cannot append series, data types don't match

In [72]: pl.concat([n2, s])
thread '<unnamed>' panicked at '`clone_inner` operation not supported for dtype `null`', /home/runner/work/polars/polars/polars/polars-core/src/series/series_trait.rs:475:9
---------------------------------------------------------------------------
PanicException                            Traceback (most recent call last)
Cell In[72], line 1
----> 1 pl.concat([n2, s])

File ~/software/anaconda3/envs/polars/lib/python3.8/site-packages/polars/utils/decorators.py:136, in deprecate_nonkeyword_arguments.<locals>.decorate.<locals>.wrapper(*args, **kwargs)
    134 if len(args) > num_allowed_args:
    135     warnings.warn(msg, DeprecationWarning, stacklevel=stacklevel)
--> 136 return function(*args, **kwargs)

File ~/software/anaconda3/envs/polars/lib/python3.8/site-packages/polars/functions/eager.py:279, in concat(items, rechunk, how, parallel)
    277 elif isinstance(first, pli.Series):
    278     if how == "vertical":
--> 279         out = wrap_s(_concat_series(elems))
    280     else:
    281         raise ValueError("'Series' only allows {{'vertical'}} concat strategy.")

PanicException: `clone_inner` operation not supported for dtype `null`


# From: https://github.com/pola-rs/polars/issues/7170

In [74]: schema = {"a": pl.Struct([pl.Field("a1", pl.Null)])}
    ...: 
    ...: df0 = pl.DataFrame(
    ...:     {"a": [{"a1": None}, {"a1": None}]},
    ...:     schema=schema
    ...: )
    ...: 
    ...: df1 = pl.DataFrame(
    ...:     {"a": [{"a1": None}, {"a1": None}]},
    ...:     schema=schema
    ...: )

In [75]: df0
Out[75]: 
shape: (2, 1)
┌───────────┐
│ a         │
│ ---       │
│ struct[1] │
╞═══════════╡
│ {null}    │
│ {null}    │
└───────────┘

In [76]: df1
Out[76]: 
shape: (2, 1)
┌───────────┐
│ a         │
│ ---       │
│ struct[1] │
╞═══════════╡
│ {null}    │
│ {null}    │
└───────────┘

In [77]: df0.dtypes
Out[77]: [Struct([Field('a1', Null)])]

In [78]: df1.dtypes
Out[78]: [Struct([Field('a1', Null)])]

In [79]: print(pl.concat([df0, df1]))
thread '<unnamed>' panicked at '`clone_inner` operation not supported for dtype `null`', /home/runner/work/polars/polars/polars/polars-core/src/series/series_trait.rs:475:9
---------------------------------------------------------------------------
PanicException                            Traceback (most recent call last)
Cell In[79], line 1
----> 1 print(pl.concat([df0, df1]))

File ~/software/anaconda3/envs/polars/lib/python3.8/site-packages/polars/utils/decorators.py:136, in deprecate_nonkeyword_arguments.<locals>.decorate.<locals>.wrapper(*args, **kwargs)
    134 if len(args) > num_allowed_args:
    135     warnings.warn(msg, DeprecationWarning, stacklevel=stacklevel)
--> 136 return function(*args, **kwargs)

File ~/software/anaconda3/envs/polars/lib/python3.8/site-packages/polars/functions/eager.py:258, in concat(items, rechunk, how, parallel)
    256 if isinstance(first, pli.DataFrame):
    257     if how == "vertical":
--> 258         out = wrap_df(_concat_df(elems))
    259     elif how == "diagonal":
    260         out = wrap_df(_diag_concat_df(elems))

PanicException: `clone_inner` operation not supported for dtype `null`
```

**Comment by hkair** [comment]
experiencing the same issue with ```pl.concat does not work with pl.Null Series```

**Comment by legout** [comment]
Same problem with `pl.DataFrame.unique()`

**Comment by stinodego** [comment]
All problems in the original issue are now resolved.

Closing in favor of https://github.com/pola-rs/polars/issues/14100
