### ISSUE TITLE
`show_versions` util not working correctly

### ISSUE THREAD

**Issue by stinodego** [pola-rs/polars#8094]
### Polars version checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pypi.org/project/polars/) of Polars.

### Issue description

Using the util throws an error:

```
Python 3.11.2 (main, Mar 31 2023, 16:17:48) [GCC 11.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import polars as pl
>>> pl.show_versions()
---Version info---
Polars: 0.17.0
Index type: UInt32
Platform: Linux-5.10.102.1-microsoft-standard-WSL2-x86_64-with-glibc2.35
Python: 3.11.2 (main, Mar 31 2023, 16:17:48) [GCC 11.3.0]
---Optional dependencies---
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/stijn/ah/ah-sa-bakplan-calculator/.venv/lib/python3.11/site-packages/polars/utils/show_versions.py", line 44, in show_versions
    deps = _get_dependency_info()
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/home/stijn/ah/ah-sa-bakplan-calculator/.venv/lib/python3.11/site-packages/polars/utils/show_versions.py", line 62, in _get_dependency_info
    return {name: _get_dependency_version(name) for name in opt_deps}
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/stijn/ah/ah-sa-bakplan-calculator/.venv/lib/python3.11/site-packages/polars/utils/show_versions.py", line 62, in <dictcomp>
    return {name: _get_dependency_version(name) for name in opt_deps}
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/stijn/ah/ah-sa-bakplan-calculator/.venv/lib/python3.11/site-packages/polars/utils/show_versions.py", line 75, in _get_dependency_version
    module_version = importlib.metadata.version(dep_name)
                     ^^^^^^^^^^^^^^^^^^
AttributeError: module 'importlib' has no attribute 'metadata'
```

### Expected behavior

Versions should be printed correctly.

**Comment by stinodego** [comment]
Some more info (this is weird):

```
>>> import importlib
>>> importlib.metadata.version("deltalake")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: module 'importlib' has no attribute 'metadata'
>>> importlib.metadata
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: module 'importlib' has no attribute 'metadata'
>>> importlib
<module 'importlib' from '/home/stijn/.pyenv/versions/3.11.2/lib/python3.11/importlib/__init__.py'>
>>> from importlib import metadata
>>> metadata.version("deltalake")
'0.8.1'
```

**Comment by stinodego** [comment]
Looks like a lazyimport kind of issue - I'll make the necessary update.
