### ISSUE TITLE
Cannot initialize DataFrame with rows of dtype `Object`

### ISSUE THREAD

**Issue by stinodego** [pola-rs/polars#8152]
### Polars version checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pypi.org/project/polars/) of Polars.

### Issue description

This works fine when initializing from a dictionary, but when initializing from a sequence-of-sequences this breaks.

### Reproducible example

```python
import polars as pl
from uuid import uuid4

df = pl.DataFrame(
    [
        [uuid4()],
        [uuid4()],
        [uuid4()],
    ],
    orient="row",
)
```
Results in:
```
Traceback (most recent call last):
  File "/home/stijn/ah/ah-sa-bakplan-calculator/check.py", line 30, in <module>
    s = pl.DataFrame(
        ^^^^^^^^^^^^^
  File "/home/stijn/ah/ah-sa-bakplan-calculator/.venv/lib/python3.11/site-packages/polars/utils/decorators.py", line 35, in wrapper
    return function(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/stijn/ah/ah-sa-bakplan-calculator/.venv/lib/python3.11/site-packages/polars/dataframe/frame.py", line 371, in __init__
    self._df = sequence_to_pydf(
               ^^^^^^^^^^^^^^^^^
  File "/home/stijn/ah/ah-sa-bakplan-calculator/.venv/lib/python3.11/site-packages/polars/utils/_construction.py", line 734, in sequence_to_pydf
    return _sequence_to_pydf_dispatcher(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/stijn/.pyenv/versions/3.11.2/lib/python3.11/functools.py", line 909, in wrapper
    return dispatch(args[0].__class__)(*args, **kw)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/stijn/ah/ah-sa-bakplan-calculator/.venv/lib/python3.11/site-packages/polars/utils/_construction.py", line 861, in _sequence_of_sequence_to_pydf
    pydf = PyDataFrame.read_rows(
           ^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: BindingsError: "object type not supported UUID('ac9618a6-60a4-4e16-b45a-1411f08ad1f6')"
```

### Expected behavior

Initialize normally.

### Installed versions

master

**Comment by stinodego** [comment]
Looks like it's similar to #8135

**Comment by ritchie46** [comment]
This seems to fail in pyo3? We don't produce this error.
