### ISSUE TITLE
Support for custom float formatting

### ISSUE THREAD

**Issue by jorisroovers** [pola-rs/polars#8157]
In Pandas, users can set a custom output format for floats like so:

```python
pd.options.display.float_format = '${:,.2f}'.format
```
This makes that a float `1.2304980958725870923` is printed as `$1.23` when formatted as as string. 
The basic use-case is for custom float precision, but ideally this would allow for any custom formatting
(note the dollar sign **$**1.23).

It would be great if Polars could have a similar feature, perhaps by extending the existing `pl.Config.set_fmt_float`
to take a custom format string (example below)?

Note that #4364 added support for `float_precision` in `DataFrame.write_csv`, but this doesn't cover general output
formatting which is often useful when printing DataFrames in a notebook (e.g. Jupyter) context.

Thanks for considering!

```python
Python 3.8.16 (default, Mar  8 2023, 11:43:55)
[Clang 14.0.0 (clang-1400.0.29.202)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import polars as pl
>>> s = pl.Series([1.2304980958725870923])
>>>
>>> print(s)
shape: (1,)
Series: '' [f64]
[
	1.230498
]
>>> pl.Config.set_fmt_float("full")
<class 'polars.config.Config'>
>>> print(s)
shape: (1,)
Series: '' [f64]
[
	1.230498095872587
]
>>> # Following is not supported
>>> pl.Config.set_fmt_float("${:,.2f}")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/jroovers/workspaces/polars-test/.venv/lib/python3.8/site-packages/polars/config.py", line 246, in set_fmt_float
    _set_float_fmt(fmt)
ValueError: fmt must be one of {'full', 'mixed'}, got ${:,.2f}
```

**Comment by cmdlineluser** [comment]
I think this is being done in https://github.com/pola-rs/polars/pull/7475

**Comment by alexanderpils** [comment]
@stinodego I think this ticket has been forgotten. But is solved by #12099

**Comment by stinodego** [comment]
> @stinodego I think this ticket has been forgotten. But is solved by #12099

We have some float formatting options, but not fully custom as is requested here. I think it's a fair request. I'll leave it open for now.
