### ISSUE TITLE
from_chunks_and_dtype_unchecked produces internal error: entered unreachable code for i16

### ISSUE THREAD

**Issue by glennpierce** [pola-rs/polars#8266]
### Polars version checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://crates.io/crates/polars) of Polars.

### Issue description

```
let mut array: Vec<ArrayRef> = vec![];

            array.push(Box::new(Int32Array::from(vec![Some(1i32), Some(1i32)])));

            let s = Series::from_chunks_and_dtype_unchecked(
                "type_id",
                array.to_vec(),
                &polars_core::datatypes::DataType::Int32
            );
```
Works fine. However,

```
            let mut array: Vec<ArrayRef> = vec![];

            array.push(Box::new(Int16Array::from(vec![Some(1i16), Some(1i16)])));

            let s = Series::from_chunks_and_dtype_unchecked(
                "type_id",
                array.to_vec(),
                &polars_core::datatypes::DataType::Int16
            );

```

produces the error

```
panicked at 'internal error: entered unreachable code', /home/glenn/.cargo/registry/src/github.com-1ecc6299db9ec823/polars-core-0.28.0/src/series/from.rs:93:18
stack backtrace:
   0: rust_begin_unwind
             at /rustc/fc594f15669680fa70d255faec3ca3fb507c3405/library/std/src/panicking.rs:575:5
   1: core::panicking::panic_fmt
             at /rustc/fc594f15669680fa70d255faec3ca3fb507c3405/library/core/src/panicking.rs:64:14
   2: core::panicking::panic
             at /rustc/fc594f15669680fa70d255faec3ca3fb507c3405/library/core/src/panicking.rs:111:5
   3: polars_core::series::from::<impl polars_core::series::Series>::from_chunks_and_dtype_unchecked
             at /home/glenn/.cargo/registry/src/github.com-1ecc6299db9ec823/polars-core-0.28.0/src/series/from.rs:93:18
   4: polars_sql::tests::test2::{{closure}}
             at ./src/lib.rs:381:21
   5: <core::pin::Pin<P> as core::future::future::Future>::poll
             at /rustc/fc594f15669680fa70d255faec3ca3fb507c3405/library/core/src/future/future.rs:124:9
   6: <core::pin::Pin<P> as core::future::future::Future>::poll
             at /rustc/fc594f15669680fa70d255faec3ca3fb507c3405/library/core/src/future/future.rs:124:9
   7: tokio::runtime::scheduler::current_thread::CoreGuard::block_on::{{closure}}::{{closure}}::{{closure}}
             at /home/glenn/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.27.0/src/runtime/scheduler/current_thread.rs:541:57
   8: tokio::runtime::coop::with_budget
             at /home/glenn/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.27.0/src/runtime/coop.rs:107:5
   9: tokio::runtime::coop::budget
             at /home/glenn/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.27.0/src/runtime/coop.rs:73:5
  10: tokio::runtime::scheduler::current_thread::CoreGuard::block_on::{{closure}}::{{closure}}
             at /home/glenn/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.27.0/src/runtime/scheduler/current_thread.rs:541:25
  11: tokio::runtime::scheduler::current_thread::Context::enter
             at /home/glenn/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.27.0/src/runtime/scheduler/current_thread.rs:350:19
  12: tokio::runtime::scheduler::current_thread::CoreGuard::block_on::{{closure}}
             at /home/glenn/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.27.0/src/runtime/scheduler/current_thread.rs:540:36
  13: tokio::runtime::scheduler::current_thread::CoreGuard::enter::{{closure}}
             at /home/glenn/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.27.0/src/runtime/scheduler/current_thread.rs:615:57
  14: tokio::macros::scoped_tls::ScopedKey<T>::set
             at /home/glenn/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.27.0/src/macros/scoped_tls.rs:61:9
  15: tokio::runtime::scheduler::current_thread::CoreGuard::enter
             at /home/glenn/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.27.0/src/runtime/scheduler/current_thread.rs:615:27
  16: tokio::runtime::scheduler::current_thread::CoreGuard::block_on
             at /home/glenn/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.27.0/src/runtime/scheduler/current_thread.rs:530:19
  17: tokio::runtime::scheduler::current_thread::CurrentThread::block_on
             at /home/glenn/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.27.0/src/runtime/scheduler/current_thread.rs:154:24
  18: tokio::runtime::runtime::Runtime::block_on
             at /home/glenn/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.27.0/src/runtime/runtime.rs:302:47
  19: polars_sql::tests::test2

```

### Reproducible example

use polars_core::prelude::ArrayRef;
use polars::prelude::*;
use polars_core::datatypes::Int16Array;

let mut array: Vec<ArrayRef> = vec![];

array.push(Box::new(Int16Array::from(vec![Some(1i16), Some(1i16)])));

let s = Series::from_chunks_and_dtype_unchecked(
    "type_id",
    array.to_vec(),
    &polars_core::datatypes::DataType::Int16
);

### Expected behavior

Not entering into unreachable code

### Installed versions

<details>
polars = { version = "0.28.0", features = ["timezones", "csv-file", "fmt", "describe", "temporal", "dtype-date", "dtype-datetime", "lazy", "interpolate", "dynamic_groupby", "diff", "rows"] }
</details>

**Comment by glennpierce** [comment]
Hmm closing as it seems I needed dtype-i16 feature
Not sure that shouldn't be in by default.
