### ISSUE TITLE
`extend_constant()` in expression context fails with ShapeError

### ISSUE THREAD

**Issue by mcrumiller** [pola-rs/polars#8728]
### Polars version checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pypi.org/project/polars/) of Polars.

### Issue description

`extend_constant` is not usable in an expression context, as it fails with a ShapeError.

### Reproducible example

```python
import polars as pl

df = pl.DataFrame({'a': [None]})
df.with_columns(
    pl.col('a').extend_constant(1, 3)
)
```
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/mcrumiller/projects/polars/py-polars/polars/dataframe/frame.py", line 7112, in with_columns
    .collect(no_optimization=True)
     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/mcrumiller/projects/polars/py-polars/polars/lazyframe/frame.py", line 1602, in collect
    return wrap_df(ldf.collect())
                   ^^^^^^^^^^^^^
exceptions.ShapeError: unable to add a column of length 4 to a dataframe of height 1
```

### Expected behavior

```
┌──────┐
│ a    │
╞══════╡
│ null │
│ 1    │
│ 1    │
│ 1    │
└──────┘
```

### Installed versions

<details>

```
--------Version info---------
Polars:      0.17.12
Index type:  UInt32
Platform:    Linux-5.15.90.1-microsoft-standard-WSL2-x86_64-with-glibc2.35
Python:      3.11.3 (main, Apr 15 2023, 14:44:51) [GCC 11.3.0]

----Optional dependencies----
numpy:       1.24.2
pandas:      2.0.0
pyarrow:     11.0.0
connectorx:  <not installed>
deltalake:   0.8.1
fsspec:      2023.4.0
matplotlib:  3.7.1
xlsx2csv:    0.8.1
xlsxwriter:  3.1.0
```

</details>

**Comment by mcrumiller** [comment]
also, `test_exprs.py` is missing a `test_extend_constant`. I was implementing that which is how I found this issue.

**Comment by alexander-beedie** [comment]
It works fine, just not exactly how you wrote it ;)
For instance:
```python
df = pl.DataFrame({'a': [None]})
df.select(
    pl.col('a').extend_constant(1, 3)
)
# shape: (4, 1)
# ┌──────┐
# │ a    │
# │ ---  │
# │ f32  │
# ╞══════╡
# │ null │
# │ 1.0  │
# │ 1.0  │
# │ 1.0  │
# └──────┘
```
...or...
```python
s = pl.Series( "values", [[0],[0,1],[1]] )
s.arr.eval( pl.element().extend_constant(None,3).slice(0,3) )
# shape: (3,)
# Series: 'values' [list[i64]]
# [
# 	[0, null, null]
# 	[0, 1, null]
# 	[1, null, null]
# ]
```

**Comment by mcrumiller** [comment]
Got it. Adding tests now.

**Comment by alexander-beedie** [comment]
> Got it. Adding tests now.

Good stuff; thx.

**Comment by mcrumiller** [comment]
Ahh yikes, it actually doesn't work if the list has a single list with one `None`:

```python
s = pl.Series( 'values', [[None]], dtype=pl.List(pl.UInt8))
s.arr.eval(pl.element().extend_constant(None,3))
```
```
shape: (1,)
Series: 'values' [list[u8]]
[
        null
]
```
