### ISSUE TITLE
polars panic when read compressed multi record arrow file with all null str column

### ISSUE THREAD

**Issue by chuchiy** [pola-rs/polars#8792]
### Polars version checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pypi.org/project/polars/) of Polars.

### Issue description

polars panic when read compressed multi record arrow file with all null str column. polars works fine when arrow file is uncompressed or arrow file has only one record

### Reproducible example

```python
import polars as pl
import pyarrow as pa
df = pl.DataFrame({'null_str': pa.nulls(1000, 'str')})
tab = df.to_arrow()
with pa.ipc.new_file('b.arrow', tab.schema, options=pa.ipc.IpcWriteOptions(compression='lz4')) as aw:
    aw.write_table(tab, max_chunksize=100)
pl.scan_ipc('b.arrow').collect()
```

### Expected behavior

b.arrow can be read by pyarrow properly

### Installed versions

<details>

--------Version info---------
Polars:      0.17.12
Index type:  UInt32
Platform:    Linux-5.15.0-70-generic-x86_64-with-glibc2.35
Python:      3.10.10 | packaged by conda-forge | (main, Mar 24 2023, 20:08:06) [GCC 11.3.0]

----Optional dependencies----
numpy:       1.23.5
pandas:      2.0.1
pyarrow:     11.0.0
connectorx:  <not installed>
deltalake:   <not installed>
fsspec:      2023.4.0
matplotlib:  3.7.1
xlsx2csv:    <not installed>
xlsxwriter:  3.1.0

</details>

**Comment by claudious96** [comment]
I'm seeing the panic error but only if the file was written with pyarrow.

I'm on:
polars latest version `0.20.4`
pyarrow `13.0.0`
python `3.11`

Writing the same data with polars and then reading it back works as expected.
 
Here is another piece of code for reproducing the issue and the stacktrace is the details.

```python
import polars as pl
import pyarrow as pa
import pyarrow.feather as pf


filename = "/tmp/dummy.feather"

data = {"a": [1, 2], "b": ['', '']}

table = pa.table(data)
df = pl.DataFrame(data)

df.write_ipc(filename, compression='zstd')

# no errors
read_df = pl.read_ipc(filename)

pf.write_feather(table, filename, compression='zstd')

# panic
# thread '<unnamed>' panicked at /home/runner/work/polars/polars/crates/polars-arrow/src/io/ipc/read/read_basic.rs:117:50:
# range start index 8 out of range for slice of length 0
read_df = pl.read_ipc(filename)
```

<details>

```python
<In [22]: pl.read_ipc(filename)
Could not mmap compressed IPC file, defaulting to normal read. Toggle off 'memory_map' to silence this warning.
thread '<unnamed>' panicked at /home/runner/work/polars/polars/crates/polars-arrow/src/io/ipc/read/read_basic.rs:117:50:
range start index 8 out of range for slice of length 0
---------------------------------------------------------------------------
PanicException                            Traceback (most recent call last)
<ipython-input-22-18a38c359258> in ?()
----> 1 pl.read_ipc(filename)

~/.cache/pypoetry/virtualenvs/polars-ipc-4Z2l3Kb0-py3.11/lib/python3.11/site-packages/polars/utils/deprecation.py in ?(*args, **kwargs)
    129         def wrapper(*args: P.args, **kwargs: P.kwargs) -> T:
    130             _rename_keyword_argument(
    131                 old_name, new_name, kwargs, function.__name__, version
    132             )
--> 133             return function(*args, **kwargs)

~/.cache/pypoetry/virtualenvs/polars-ipc-4Z2l3Kb0-py3.11/lib/python3.11/site-packages/polars/utils/deprecation.py in ?(*args, **kwargs)
    129         def wrapper(*args: P.args, **kwargs: P.kwargs) -> T:
    130             _rename_keyword_argument(
    131                 old_name, new_name, kwargs, function.__name__, version
    132             )
--> 133             return function(*args, **kwargs)

~/.cache/pypoetry/virtualenvs/polars-ipc-4Z2l3Kb0-py3.11/lib/python3.11/site-packages/polars/io/ipc/functions.py in ?(source, columns, n_rows, use_pyarrow, memory_map, storage_options, row_index_name, row_index_offset, rechunk)
     99             if n_rows is not None:
    100                 df = df.slice(0, n_rows)
    101             return df
    102 
--> 103         return pl.DataFrame._read_ipc(
    104             data,
    105             columns=columns,
    106             n_rows=n_rows,

~/.cache/pypoetry/virtualenvs/polars-ipc-4Z2l3Kb0-py3.11/lib/python3.11/site-packages/polars/dataframe/frame.py in ?(cls, source, columns, n_rows, row_index_name, row_index_offset, rechunk, memory_map)
    986             return cls._from_pydf(df._df)
    987 
    988         projection, columns = handle_projection_columns(columns)
    989         self = cls.__new__(cls)
--> 990         self._df = PyDataFrame.read_ipc(
    991             source,
    992             columns,
    993             projection,

PanicException: range start index 8 out of range for slice of length 0
```
</details>
