### ISSUE TITLE
Bug: Dataclass with InitVar

### ISSUE THREAD

**Issue by gam-phon** [pola-rs/polars#8854]
### Polars version checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pypi.org/project/polars/) of Polars.

### Issue description

I know that polars support python dataclass but if there is an InitVar field in the class this exception will be raised
```
Traceback (most recent call last):
  File "/path_to_file/pl_dataclass.py", line 16, in <module>
    print(pl.DataFrame([a]))
          ^^^^^^^^^^^^^^^^^
  File "/Users/yaser/Library/Caches/pypoetry/virtualenvs/tad-F1P-fY64-py3.11/lib/python3.11/site-packages/polars/dataframe/frame.py", line 362, in __init__
    self._df = sequence_to_pydf(
               ^^^^^^^^^^^^^^^^^
  File "/Users/yaser/Library/Caches/pypoetry/virtualenvs/tad-F1P-fY64-py3.11/lib/python3.11/site-packages/polars/utils/_construction.py", line 768, in sequence_to_pydf
    return _sequence_to_pydf_dispatcher(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/python@3.11/3.11.3/Frameworks/Python.framework/Versions/3.11/lib/python3.11/functools.py", line 909, in wrapper
    return dispatch(args[0].__class__)(*args, **kw)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/yaser/Library/Caches/pypoetry/virtualenvs/tad-F1P-fY64-py3.11/lib/python3.11/site-packages/polars/utils/_construction.py", line 858, in _sequence_to_pydf_dispatcher
    return to_pydf(**common_params)
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/yaser/Library/Caches/pypoetry/virtualenvs/tad-F1P-fY64-py3.11/lib/python3.11/site-packages/polars/utils/_construction.py", line 1106, in _dataclasses_or_models_to_pydf
    pydf = PyDataFrame.read_rows(rows, infer_schema_length, schema_override or None)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
pyo3_runtime.PanicException: Unknown not supported
```

### Reproducible example

```python
import polars as pl
from dataclasses import dataclass, InitVar, asdict

@dataclass
class A:
    b: str
    c: InitVar[str]

    def __post_init__(self, c: str) -> None:
        pass

if __name__ == "__main__":
    a = A(b="b", c="c")
    print(a) # A(b='b')
    print(asdict(a)) # {'b': 'b'}
    print(pl.DataFrame([a]))
```

### Expected behavior

it should work with InitVar. asdict is not causing any issue

### Installed versions

<details>

```
--------Version info---------
Polars:      0.17.12
Index type:  UInt32
Platform:    macOS-13.3.1-arm64-arm-64bit
Python:      3.11.3 (main, Apr  7 2023, 20:13:31) [Clang 14.0.0 (clang-1400.0.29.202)]
                                                                                                                                                                                              
----Optional dependencies----
numpy:       1.24.3
pandas:      1.5.3
pyarrow:     12.0.0
connectorx:  0.3.2_alpha.1
deltalake:   <not installed>
fsspec:      <not installed>
matplotlib:  <not installed>
xlsx2csv:    <not installed>
xlsxwriter:  <not installed>

```

</details>

**Comment by alexander-beedie** [comment]
> @alexander-beedie What do you think?

I think [this](https://github.com/pola-rs/polars/pull/8856) should fix it... thanks ;)

**Comment by gam-phon** [comment]
Thanks @alexander-beedie
