### ISSUE TITLE
Panic on multiplying `decimal.Decimal` column

### ISSUE THREAD

**Issue by jmakov** [pola-rs/polars#8855]
### Polars version checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pypi.org/project/polars/) of Polars.

### Issue description

Trying to parse floats given in strings without introducing FP errors, I use `decimal.Decimal`. However `polars` doesn't like it and has no problems if the strings are first parsed as FLOATs. Which is strange.

### Reproducible example

```python
import decimal

import polars


df = polars.DataFrame({"test": ["1.1", "2"]})

# handle FP errors by parsing string values as decimal.Decimal and do some ops on them e.g. multiply the decimal.Decimal value
df.with_columns(polars.col("test").apply(decimal.Decimal).apply(lambda x: x*2))
thread '<unnamed>' panicked at 'dtype Decimal(None, Some(1)) not supported', src/series.rs:543:32
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
--- PyO3 is resuming a panic after fetching a PanicException from Python. ---
Python stack trace below:
Traceback (most recent call last):
  File "/usr/lib/python3.11/site-packages/polars/expr/expr.py", line 3418, in wrap_f
    return x.apply(
           ^^^^^^^^
  File "/usr/lib/python3.11/site-packages/polars/series/series.py", line 4211, in apply
    self._s.apply_lambda(function, pl_return_dtype, skip_nulls)
pyo3_runtime.PanicException: dtype Decimal(None, Some(1)) not supported
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib/python3.11/site-packages/polars/dataframe/frame.py", line 7111, in with_columns
    .collect(no_optimization=True)
     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/polars/lazyframe/frame.py", line 1602, in collect
    return wrap_df(ldf.collect())
                   ^^^^^^^^^^^^^
pyo3_runtime.PanicException: Unwrapped panic from Python code

# this works but also introduces FP errors
df.with_columns(polars.col("test").apply(float).apply(decimal.Decimal).apply(lambda x: x*2))
```

### Expected behavior

Don't panic?

### Installed versions

<details>

```
0.17.13'
>>> polars.show_versions()
--------Version info---------
Polars:      0.17.13
Index type:  UInt32
Platform:    Linux-6.1.26-1-MANJARO-x86_64-with-glibc2.37
Python:      3.11.2 (main, Mar 28 2023, 14:27:48) [GCC 12.2.1 20230323 releases/gcc-12.2.0-616-g1b6b7f214c]

----Optional dependencies----
numpy:       1.24.3
pandas:      <not installed>
pyarrow:     <not installed>
connectorx:  <not installed>
deltalake:   <not installed>
fsspec:      <not installed>
matplotlib:  <not installed>
xlsx2csv:    <not installed>
xlsxwriter:  <not installed>

```

</details>

**Comment by alexander-beedie** [comment]
As per the error message: `PanicException: dtype Decimal ... not supported`.

Polars is only in the very early stages of adding proper `Decimal` support; you have to explicitly opt-in to it via a `Config` option, and it is currently _very_ limited (eg: no math function support yet).

For example:

```python
from decimal import Decimal

with pl.Config( activate_decimals=True ):
    df = pl.DataFrame( {"test":[Decimal("1.1"), Decimal("2")]} )

# shape: (2, 1)
# ┌────────────┐
# │ test       │
# │ ---        │
# │ decimal[1] │
# ╞════════════╡
# │ 1.1        │
# │ 2          │
# └────────────┘

df * 2
# PanicException: `mul` operation not supported for dtype `decimal[1]`
```

**Comment by jmakov** [comment]
@alexander-beedie thanks for the quick support. What is then the preferred way of loading string based floats to the data frame without introducing FP errors?

**Comment by alexander-beedie** [comment]
>  What is then the preferred way of loading string based floats into the data frame without introducing FP errors?

You can't because, as above, we don't support `Decimal` yet; we have reached the point where (with an experimental opt-in) you can load them, but you can't really _do_ anything with them yet.

> Also your example doesn't explain why my second example just works.

As far as I can tell, it doesn't; I get exactly the same error ;)
`PanicException: dtype Decimal ... not supported`

**Comment by alexander-beedie** [comment]
Ahh; you can do the decimal math in the lambda if you arrange it correctly (I see why mine threw the error now), but all you're really doing then is running it with _Python's_ decimal library (it's not executing polars code at that point), and you will therefore lose parallelism, etc (all the usual significant downsides of `apply`).

So I really wouldn't recommend it, or you'd need a lambda for every decimal math op; aside from being unpleasant to work with, you may tank the performance of anything else that could have been parallelised at the same time.
```python
from decimal import Decimal
import polars as pl

with pl.Config( activate_decimals=True ):
    df = pl.DataFrame( {"txt":["1.1", "2"]} )
    print(
        df.with_columns( pl.col("txt").apply( lambda x: Decimal(x) * 2 ).alias("dec") )
    )
# shape: (2, 2)
# ┌─────┬────────────┐
# │ txt ┆ dec        │
# │ --- ┆ ---        │
# │ str ┆ decimal[1] │
# ╞═════╪════════════╡
# │ 1.1 ┆ 2.2        │
# │ 2   ┆ 4          │
# └─────┴────────────┘

```

**Comment by jmakov** [comment]
Oh, didn't think of that, thanks! Slow perf vs nothing still wins.
