### ISSUE TITLE
Joining on [arr.first(), arr.last()] throws a TypeError

### ISSUE THREAD

**Issue by thomasaarholt** [pola-rs/polars#8872]
### Polars version checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pypi.org/project/polars/) of Polars.

### Issue description

I posted this SO post earlier, and got some great answers. That inspired me to modify one answer to something I believed a bit simpler - joining on the first and last value of a 2-len array, but it panics. 

```python
df = pl.DataFrame({"id": [1, 2.0], "coords": [(1.0, 2.0), (3.0, 4.0)]})
df_allowed = pl.DataFrame(
    {
        "coords": [(1.0, 2.0), (3.0, 4.0), (5.0, 6.0)],
        "people": ["Alice", "Bob", "Charlie"],
    }
)
df.join(
    df_allowed,
    how="left",
    # I would expect that joining on this would work
    on=pl.col("coords").list.first(),
)
```

```python
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
File ~/codes/polars-v1/.venv/lib/python3.11/site-packages/polars/_utils/construction/series.py:299, in _construct_series_with_fallbacks(constructor, name, values, dtype, strict)
    298 try:
--> 299     return constructor(name, values, strict)
    300 except TypeError:

TypeError: 'float' object cannot be interpreted as an integer

During handling of the above exception, another exception occurred:

TypeError                                 Traceback (most recent call last)
Cell In[4], line 1
----> 1 df = pl.DataFrame({"id": [1, 2.0], "coords": [(1.0, 2.0), (3.0, 4.0)]})
      2 df_allowed = pl.DataFrame(
      3     {
      4         "coords": [(1.0, 2.0), (3.0, 4.0), (5.0, 6.0)],
      5         "people": ["Alice", "Bob", "Charlie"],
      6     }
      7 )
      8 df.join(
      9     df_allowed,
     10     how="left",
     11     # I would expect that joining on this would work
     12     on=pl.col("coords").list.first(),
     13 )

File ~/codes/polars-v1/.venv/lib/python3.11/site-packages/polars/dataframe/frame.py:356, in DataFrame.__init__(self, data, schema, schema_overrides, strict, orient, infer_schema_length, nan_to_null)
    351     self._df = dict_to_pydf(
    352         {}, schema=schema, schema_overrides=schema_overrides
    353     )
    355 elif isinstance(data, dict):
--> 356     self._df = dict_to_pydf(
    357         data,
    358         schema=schema,
    359         schema_overrides=schema_overrides,
    360         strict=strict,
    361         nan_to_null=nan_to_null,
    362     )
    364 elif isinstance(data, (list, tuple, Sequence)):
    365     self._df = sequence_to_pydf(
    366         data,
    367         schema=schema,
   (...)
    371         infer_schema_length=infer_schema_length,
    372     )

File ~/codes/polars-v1/.venv/lib/python3.11/site-packages/polars/_utils/construction/dataframe.py:158, in dict_to_pydf(data, schema, schema_overrides, strict, nan_to_null, allow_multithreaded)
    145     data_series = [
    146         pl.Series(
    147             name,
   (...)
    153         for name in column_names
    154     ]
    155 else:
    156     data_series = [
    157         s._s
--> 158         for s in _expand_dict_values(
    159             data,
    160             schema_overrides=schema_overrides,
    161             strict=strict,
    162             nan_to_null=nan_to_null,
    163         ).values()
    164     ]
    166 data_series = _handle_columns_arg(data_series, columns=column_names, from_dict=True)
    167 pydf = PyDataFrame(data_series)

File ~/codes/polars-v1/.venv/lib/python3.11/site-packages/polars/_utils/construction/dataframe.py:387, in _expand_dict_values(data, schema_overrides, strict, order, nan_to_null)
    384     updated_data[name] = s
    386 elif arrlen(val) is not None or _is_generator(val):
--> 387     updated_data[name] = pl.Series(
    388         name=name,
    389         values=val,
    390         dtype=dtype,
    391         strict=strict,
    392         nan_to_null=nan_to_null,
    393     )
    394 elif val is None or isinstance(  # type: ignore[redundant-expr]
    395     val, (int, float, str, bool, date, datetime, time, timedelta)
    396 ):
    397     updated_data[name] = F.repeat(
    398         val, array_len, dtype=dtype, eager=True
    399     ).alias(name)

File ~/codes/polars-v1/.venv/lib/python3.11/site-packages/polars/series/series.py:294, in Series.__init__(self, name, values, dtype, strict, nan_to_null)
    291         raise TypeError(msg)
    293 if isinstance(values, Sequence):
--> 294     self._s = sequence_to_pyseries(
    295         name,
    296         values,
    297         dtype=dtype,
    298         strict=strict,
    299         nan_to_null=nan_to_null,
    300     )
    302 elif values is None:
    303     self._s = sequence_to_pyseries(name, [], dtype=dtype)

File ~/codes/polars-v1/.venv/lib/python3.11/site-packages/polars/_utils/construction/series.py:284, in sequence_to_pyseries(name, values, dtype, strict, nan_to_null)
    281     except RuntimeError:
    282         return PySeries.new_from_any_values(name, values, strict=strict)
--> 284 return _construct_series_with_fallbacks(
    285     constructor, name, values, dtype, strict=strict
    286 )

File ~/codes/polars-v1/.venv/lib/python3.11/site-packages/polars/_utils/construction/series.py:302, in _construct_series_with_fallbacks(constructor, name, values, dtype, strict)
    300 except TypeError:
    301     if dtype is None:
--> 302         return PySeries.new_from_any_values(name, values, strict=strict)
    303     else:
    304         return PySeries.new_from_any_values_and_dtype(
    305             name, values, dtype, strict=strict
    306         )

TypeError: unexpected value while building Series of type Int64; found value of type Float64: 2.0

Hint: Try setting `strict=False` to allow passing data with mixed types.
```

### Expected behavior

I would expect it to join on those two keys.

### Installed versions

<details>

```
--------Version info---------
Polars:      0.17.13
Index type:  UInt32
Platform:    macOS-13.3.1-arm64-arm-64bit
Python:      3.11.1 (main, Mar  2 2023, 10:47:50) [Clang 14.0.0 (clang-1400.0.29.202)]

----Optional dependencies----
numpy:       1.24.2
pandas:      1.5.3
pyarrow:     12.0.0
connectorx:  <not installed>
deltalake:   <not installed>
fsspec:      <not installed>
matplotlib:  3.7.1
xlsx2csv:    <not installed>
xlsxwriter:  <not installed>
```

</details>

**Comment by coastalwhite** [comment]
This now does not panic anymore. Instead it throws a TypeError:

```
Traceback (most recent call last):
  File "/home/johndoe/Projects/polars/py-polars/polars/_utils/construction/series.py", line 299, in _construct_series_with_fallbacks
    return constructor(name, values, strict)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: 'float' object cannot be interpreted as an integer

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/johndoe/Projects/polars/t2.py", line 3, in <module>
    df = pl.DataFrame({"id": [1, 2.0], "coords": [(1.0, 2.0), (3.0, 4.0)]})
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/johndoe/Projects/polars/py-polars/polars/dataframe/frame.py", line 356, in __init__
    self._df = dict_to_pydf(
               ^^^^^^^^^^^^^
  File "/home/johndoe/Projects/polars/py-polars/polars/_utils/construction/dataframe.py", line 158, in dict_to_pydf
    for s in _expand_dict_values(
             ^^^^^^^^^^^^^^^^^^^^
  File "/home/johndoe/Projects/polars/py-polars/polars/_utils/construction/dataframe.py", line 387, in _expand_dict_values
    updated_data[name] = pl.Series(
                         ^^^^^^^^^^
  File "/home/johndoe/Projects/polars/py-polars/polars/series/series.py", line 294, in __init__
    self._s = sequence_to_pyseries(
              ^^^^^^^^^^^^^^^^^^^^^
  File "/home/johndoe/Projects/polars/py-polars/polars/_utils/construction/series.py", line 284, in sequence_to_pyseries
    return _construct_series_with_fallbacks(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/johndoe/Projects/polars/py-polars/polars/_utils/construction/series.py", line 302, in _construct_series_with_fallbacks
    return PySeries.new_from_any_values(name, values, strict=strict)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: unexpected value while building Series of type Int64; found value of type Float64: 2.0

Hint: Try setting `strict=False` to allow passing data with mixed types.
```

**Comment by ritchie46** [comment]
This one runs if you set `strict=False` in the `DataFrame` constructor.
