### ISSUE TITLE
panicked at 'assertion failed: i < (self.bits.len() << 3)

### ISSUE THREAD

**Issue by ritchie46** [pola-rs/polars#888]
```
thread '<unnamed>' panicked at 'assertion failed: i < (self.bits.len() << 3)', /home/ritchie46/.cargo/git/checkouts/arrow-rs-3b86e19e889d5acc/9f56afb/arrow/src/bitmap.rs:56:9
stack backtrace:
   0: rust_begin_unwind
             at /rustc/f586d79d183d144e0cbf519e29247f36670e2076/library/std/src/panicking.rs:515:5
   1: core::panicking::panic_fmt
             at /rustc/f586d79d183d144e0cbf519e29247f36670e2076/library/core/src/panicking.rs:92:14
   2: core::panicking::panic
             at /rustc/f586d79d183d144e0cbf519e29247f36670e2076/library/core/src/panicking.rs:50:5
   3: arrow::bitmap::Bitmap::is_set
             at /home/ritchie46/.cargo/git/checkouts/arrow-rs-3b86e19e889d5acc/9f56afb/arrow/src/bitmap.rs:56:9
   4: arrow::array::data::ArrayData::is_valid
             at /home/ritchie46/.cargo/git/checkouts/arrow-rs-3b86e19e889d5acc/9f56afb/arrow/src/array/data.rs:311:20
   5: arrow::array::array::Array::is_valid
             at /home/ritchie46/.cargo/git/checkouts/arrow-rs-3b86e19e889d5acc/9f56afb/arrow/src/array/array.rs:181:9
   6: <polars_core::chunked_array::builder::ListPrimitiveChunkedBuilder<T> as polars_core::chunked_array::builder::ListBuilderTrait>::append_series::{{closure}}
             at /home/ritchie46/code/polars/polars/polars-core/src/chunked_array/builder/mod.rs:429:24
   7: core::iter::traits::iterator::Iterator::for_each::call::{{closure}}
             at /rustc/f586d79d183d144e0cbf519e29247f36670e2076/library/core/src/iter/traits/iterator.rs:733:29
   8: <core::iter::adapters::enumerate::Enumerate<I> as core::iter::traits::iterator::Iterator>::fold::enumerate::{{closure}}
             at /rustc/f586d79d183d144e0cbf519e29247f36670e2076/library/core/src/iter/adapters/enumerate.rs:104:27
   9: core::iter::traits::iterator::Iterator::fold
             at /rustc/f586d79d183d144e0cbf519e29247f36670e2076/library/core/src/iter/traits/iterator.rs:2112:21
  10: <core::iter::adapters::enumerate::Enumerate<I> as core::iter::traits::iterator::Iterator>::fold
             at /rustc/f586d79d183d144e0cbf519e29247f36670e2076/library/core/src/iter/adapters/enumerate.rs:110:9
  11: core::iter::traits::iterator::Iterator::for_each
             at /rustc/f586d79d183d144e0cbf519e29247f36670e2076/library/core/src/iter/traits/iterator.rs:736:9
  12: <polars_core::chunked_array::builder::ListPrimitiveChunkedBuilder<T> as polars_core::chunked_array::builder::ListBuilderTrait>::append_series
             at /home/ritchie46/code/polars/polars/polars-core/src/chunked_array/builder/mod.rs:428:17
  13: <polars_lazy::physical_plan::expressions::aggregation::AggregationExpr as polars_lazy::physical_plan::expressions::PhysicalAggregation>::evaluate_partitioned_final
             at /home/ritchie46/code/polars/polars/polars-lazy/src/physical_plan/expressions/aggregation.rs:207:21
  14: <polars_lazy::physical_plan::executors::groupby::PartitionGroupByExec as polars_lazy::physical_plan::Executor>::execute::{{closure}}::{{closure}}
             at /home/ritchie46/code/polars/polars/polars-lazy/src/physical_plan/executors/groupby.rs:282:35
  15: <rayon::iter::filter_map::FilterMapFolder<C,P> as rayon::iter::plumbing::Folder<T>>::consume
             at /home/ritchie46/.cargo/registry/src/github.com-1ecc6299db9ec823/rayon-1.5.1/src/iter/filter_map.rs:123:36
  16: rayon::iter::plumbing::Folder::consume_iter
             at /home/ritchie46/.cargo/registry/src/github.com-1ecc6299db9ec823/rayon-1.5.1/src/iter/plumbing/mod.rs:179:20
  17: rayon::iter::plumbing::Producer::fold_with
             at /home/ritchie46/.cargo/registry/src/github.com-1ecc6299db9ec823/rayon-1.5.1/src/iter/plumbing/mod.rs:110:9
  18: rayon::iter::plumbing::bridge_producer_consumer::helper
             at /home/ritchie46/.cargo/registry/src/github.com-1ecc6299db9ec823/rayon-1.5.1/src/iter/plumbing/mod.rs:438:13
  19: rayon::iter::plumbing::bridge_producer_consumer
             at /home/ritchie46/.cargo/registry/src/github.com-1ecc6299db9ec823/rayon-1.5.1/src/iter/plumbing/mod.rs:397:12
  20: <rayon::iter::plumbing::bridge::Callback<C> as rayon::iter::plumbing::ProducerCallback<I>>::callback
             at /home/ritchie46/.cargo/registry/src/github.com-1ecc6299db9ec823/rayon-1.5.1/src/iter/plumbing/mod.rs:373:13
  21: <<rayon::iter::zip::Zip<A,B> as rayon::iter::IndexedParallelIterator>::with_producer::CallbackB<CB,A> as rayon::iter::plumbing::ProducerCallback<ITEM>>::callback
             at /home/ritchie46/.cargo/registry/src/github.com-1ecc6299db9ec823/rayon-1.5.1/src/iter/zip.rs:113:17
  22: <<rayon::iter::map::Map<I,F> as rayon::iter::IndexedParallelIterator>::with_producer::Callback<CB,F> as rayon::iter::plumbing::ProducerCallback<T>>::callback
             at /home/ritchie46/.cargo/registry/src/github.com-1ecc6299db9ec823/rayon-1.5.1/src/iter/map.rs:105:17
  23: <rayon::slice::Iter<T> as rayon::iter::IndexedParallelIterator>::with_producer
             at /home/ritchie46/.cargo/registry/src/github.com-1ecc6299db9ec823/rayon-1.5.1/src/slice/mod.rs:525:9
  24: <rayon::iter::map::Map<I,F> as rayon::iter::IndexedParallelIterator>::with_producer
             at /home/ritchie46/.cargo/registry/src/github.com-1ecc6299db9ec823/rayon-1.5.1/src/iter/map.rs:79:16
  25: <<rayon::iter::zip::Zip<A,B> as rayon::iter::IndexedParallelIterator>::with_producer::CallbackA<CB,B> as rayon::iter::plumbing::ProducerCallback<ITEM>>::callback
             at /home/ritchie46/.cargo/registry/src/github.com-1ecc6299db9ec823/rayon-1.5.1/src/iter/zip.rs:90:17
  26: <rayon::slice::Iter<T> as rayon::iter::IndexedParallelIterator>::with_producer
             at /home/ritchie46/.cargo/registry/src/github.com-1ecc6299db9ec823/rayon-1.5.1/src/slice/mod.rs:525:9
  27: <rayon::iter::zip::Zip<A,B> as rayon::iter::IndexedParallelIterator>::with_producer
             at /home/ritchie46/.cargo/registry/src/github.com-1ecc6299db9ec823/rayon-1.5.1/src/iter/zip.rs:69:16
  28: rayon::iter::plumbing::bridge
             at /home/ritchie46/.cargo/registry/src/github.com-1ecc6299db9ec823/rayon-1.5.1/src/iter/plumbing/mod.rs:357:12
  29: <rayon::iter::zip::Zip<A,B> as rayon::iter::ParallelIterator>::drive_unindexed
             at /home/ritchie46/.cargo/registry/src/github.com-1ecc6299db9ec823/rayon-1.5.1/src/iter/zip.rs:41:9
  30: <rayon::iter::filter_map::FilterMap<I,P> as rayon::iter::ParallelIterator>::drive_unindexed
             at /home/ritchie46/.cargo/registry/src/github.com-1ecc6299db9ec823/rayon-1.5.1/src/iter/filter_map.rs:46:9
  31: <rayon::iter::flatten::Flatten<I> as rayon::iter::ParallelIterator>::drive_unindexed
             at /home/ritchie46/.cargo/registry/src/github.com-1ecc6299db9ec823/rayon-1.5.1/src/iter/flatten.rs:38:9
  32: <rayon::iter::fold::Fold<I,ID,F> as rayon::iter::ParallelIterator>::drive_unindexed
             at /home/ritchie46/.cargo/registry/src/github.com-1ecc6299db9ec823/rayon-1.5.1/src/iter/fold.rs:59:9
  33: <rayon::iter::map::Map<I,F> as rayon::iter::ParallelIterator>::drive_unindexed
             at /home/ritchie46/.cargo/registry/src/github.com-1ecc6299db9ec823/rayon-1.5.1/src/iter/map.rs:49:9
  34: rayon::iter::reduce::reduce
             at /home/ritchie46/.cargo/registry/src/github.com-1ecc6299db9ec823/rayon-1.5.1/src/iter/reduce.rs:15:5
  35: rayon::iter::ParallelIterator::reduce
             at /home/ritchie46/.cargo/registry/src/github.com-1ecc6299db9ec823/rayon-1.5.1/src/iter/mod.rs:981:9
  36: rayon::iter::extend::collect
             at /home/ritchie46/.cargo/registry/src/github.com-1ecc6299db9ec823/rayon-1.5.1/src/iter/extend.rs:29:5
  37: rayon::iter::collect::<impl rayon::iter::ParallelExtend<T> for alloc::vec::Vec<T>>::par_extend
             at /home/ritchie46/.cargo/registry/src/github.com-1ecc6299db9ec823/rayon-1.5.1/src/iter/collect/mod.rs:165:28
  38: rayon::iter::from_par_iter::collect_extended
             at /home/ritchie46/.cargo/registry/src/github.com-1ecc6299db9ec823/rayon-1.5.1/src/iter/from_par_iter.rs:17:5
  39: rayon::iter::from_par_iter::<impl rayon::iter::FromParallelIterator<T> for alloc::vec::Vec<T>>::from_par_iter
             at /home/ritchie46/.cargo/registry/src/github.com-1ecc6299db9ec823/rayon-1.5.1/src/iter/from_par_iter.rs:30:9
  40: rayon::iter::ParallelIterator::collect
             at /home/ritchie46/.cargo/registry/src/github.com-1ecc6299db9ec823/rayon-1.5.1/src/iter/mod.rs:2046:9
  41: <polars_lazy::physical_plan::executors::groupby::PartitionGroupByExec as polars_lazy::physical_plan::Executor>::execute::{{closure}}
             at /home/ritchie46/code/polars/polars/polars-lazy/src/physical_plan/executors/groupby.rs:275:13
  42: core::ops::function::FnOnce::call_once
             at /rustc/f586d79d183d144e0cbf519e29247f36670e2076/library/core/src/ops/function.rs:227:5
  43: rayon_core::join::join::call::{{closure}}
             at /home/ritchie46/.cargo/registry/src/github.com-1ecc6299db9ec823/rayon-core-1.9.1/src/join/mod.rs:102:18
  44: rayon_core::join::join_context::call_b::{{closure}}
             at /home/ritchie46/.cargo/registry/src/github.com-1ecc6299db9ec823/rayon-core-1.9.1/src/join/mod.rs:129:25
  45: <rayon_core::job::StackJob<L,F,R> as rayon_core::job::Job>::execute::call::{{closure}}
             at /home/ritchie46/.cargo/registry/src/github.com-1ecc6299db9ec823/rayon-core-1.9.1/src/job.rs:113:21
  46: <std::panic::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once
             at /rustc/f586d79d183d144e0cbf519e29247f36670e2076/library/std/src/panic.rs:347:9
  47: std::panicking::try::do_call
             at /rustc/f586d79d183d144e0cbf519e29247f36670e2076/library/std/src/panicking.rs:401:40
  48: __rust_try
  49: std::panicking::try
             at /rustc/f586d79d183d144e0cbf519e29247f36670e2076/library/std/src/panicking.rs:365:19
  50: std::panic::catch_unwind
             at /rustc/f586d79d183d144e0cbf519e29247f36670e2076/library/std/src/panic.rs:434:14
  51: rayon_core::unwind::halt_unwinding
             at /home/ritchie46/.cargo/registry/src/github.com-1ecc6299db9ec823/rayon-core-1.9.1/src/unwind.rs:17:5
  52: <rayon_core::job::StackJob<L,F,R> as rayon_core::job::Job>::execute
             at /home/ritchie46/.cargo/registry/src/github.com-1ecc6299db9ec823/rayon-core-1.9.1/src/job.rs:119:38
  53: rayon_core::job::JobRef::execute
             at /home/ritchie46/.cargo/registry/src/github.com-1ecc6299db9ec823/rayon-core-1.9.1/src/job.rs:59:9
  54: rayon_core::registry::WorkerThread::execute
             at /home/ritchie46/.cargo/registry/src/github.com-1ecc6299db9ec823/rayon-core-1.9.1/src/registry.rs:749:9
  55: rayon_core::registry::WorkerThread::wait_until_cold
             at /home/ritchie46/.cargo/registry/src/github.com-1ecc6299db9ec823/rayon-core-1.9.1/src/registry.rs:726:17
  56: rayon_core::registry::WorkerThread::wait_until
             at /home/ritchie46/.cargo/registry/src/github.com-1ecc6299db9ec823/rayon-core-1.9.1/src/registry.rs:700:13
  57: rayon_core::registry::main_loop
             at /home/ritchie46/.cargo/registry/src/github.com-1ecc6299db9ec823/rayon-core-1.9.1/src/registry.rs:833:5
  58: rayon_core::registry::ThreadBuilder::run
             at /home/ritchie46/.cargo/registry/src/github.com-1ecc6299db9ec823/rayon-core-1.9.1/src/registry.rs:55:18
  59: <rayon_core::registry::DefaultSpawn as rayon_core::registry::ThreadSpawn>::spawn::{{closure}}
             at /home/ritchie46/.cargo/registry/src/github.com-1ecc6299db9ec823/rayon-core-1.9.1/src/registry.rs:100:20
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
thread '<unnamed>' panicked at 'assertion failed: i < (self.bits.len() << 3)', /home/ritchie46/.cargo/git/checkouts/arrow-rs-3b86e19e889d5acc/9f56afb/arrow/src/bitmap.rs:56:9
stack backtrace:
   0: rust_begin_unwind
             at /rustc/f586d79d183d144e0cbf519e29247f36670e2076/library/std/src/panicking.rs:515:5
   1: core::panicking::panic_fmt
             at /rustc/f586d79d183d144e0cbf519e29247f36670e2076/library/core/src/panicking.rs:92:14
   2: core::panicking::panic
             at /rustc/f586d79d183d144e0cbf519e29247f36670e2076/library/core/src/panicking.rs:50:5
   3: arrow::bitmap::Bitmap::is_set
             at /home/ritchie46/.cargo/git/checkouts/arrow-rs-3b86e19e889d5acc/9f56afb/arrow/src/bitmap.rs:56:9
   4: arrow::array::data::ArrayData::is_valid
             at /home/ritchie46/.cargo/git/checkouts/arrow-rs-3b86e19e889d5acc/9f56afb/arrow/src/array/data.rs:311:20
   5: arrow::array::array::Array::is_valid
             at /home/ritchie46/.cargo/git/checkouts/arrow-rs-3b86e19e889d5acc/9f56afb/arrow/src/array/array.rs:181:9
   6: <polars_core::chunked_array::builder::ListPrimitiveChunkedBuilder<T> as polars_core::chunked_array::builder::ListBuilderTrait>::append_series::{{closure}}
             at /home/ritchie46/code/polars/polars/polars-core/src/chunked_array/builder/mod.rs:429:24
   7: core::iter::traits::iterator::Iterator::for_each::call::{{closure}}
             at /rustc/f586d79d183d144e0cbf519e29247f36670e2076/library/core/src/iter/traits/iterator.rs:733:29
   8: <core::iter::adapters::enumerate::Enumerate<I> as core::iter::traits::iterator::Iterator>::fold::enumerate::{{closure}}
             at /rustc/f586d79d183d144e0cbf519e29247f36670e2076/library/core/src/iter/adapters/enumerate.rs:104:27
   9: core::iter::traits::iterator::Iterator::fold
             at /rustc/f586d79d183d144e0cbf519e29247f36670e2076/library/core/src/iter/traits/iterator.rs:2112:21
  10: <core::iter::adapters::enumerate::Enumerate<I> as core::iter::traits::iterator::Iterator>::fold
             at /rustc/f586d79d183d144e0cbf519e29247f36670e2076/library/core/src/iter/adapters/enumerate.rs:110:9
  11: core::iter::traits::iterator::Iterator::for_each
             at /rustc/f586d79d183d144e0cbf519e29247f36670e2076/library/core/src/iter/traits/iterator.rs:736:9
  12: <polars_core::chunked_array::builder::ListPrimitiveChunkedBuilder<T> as polars_core::chunked_array::builder::ListBuilderTrait>::append_series
             at /home/ritchie46/code/polars/polars/polars-core/src/chunked_array/builder/mod.rs:428:17
  13: <polars_lazy::physical_plan::expressions::aggregation::AggregationExpr as polars_lazy::physical_plan::expressions::PhysicalAggregation>::evaluate_partitioned_final
             at /home/ritchie46/code/polars/polars/polars-lazy/src/physical_plan/expressions/aggregation.rs:207:21
  14: <polars_lazy::physical_plan::executors::groupby::PartitionGroupByExec as polars_lazy::physical_plan::Executor>::execute::{{closure}}::{{closure}}
             at /home/ritchie46/code/polars/polars/polars-lazy/src/physical_plan/executors/groupby.rs:282:35
  15: <rayon::iter::filter_map::FilterMapFolder<C,P> as rayon::iter::plumbing::Folder<T>>::consume
             at /home/ritchie46/.cargo/registry/src/github.com-1ecc6299db9ec823/rayon-1.5.1/src/iter/filter_map.rs:123:36
  16: rayon::iter::plumbing::Folder::consume_iter
             at /home/ritchie46/.cargo/registry/src/github.com-1ecc6299db9ec823/rayon-1.5.1/src/iter/plumbing/mod.rs:179:20
  17: rayon::iter::plumbing::Producer::fold_with
             at /home/ritchie46/.cargo/registry/src/github.com-1ecc6299db9ec823/rayon-1.5.1/src/iter/plumbing/mod.rs:110:9
  18: rayon::iter::plumbing::bridge_producer_consumer::helper
             at /home/ritchie46/.cargo/registry/src/github.com-1ecc6299db9ec823/rayon-1.5.1/src/iter/plumbing/mod.rs:438:13
  19: rayon::iter::plumbing::bridge_producer_consumer
             at /home/ritchie46/.cargo/registry/src/github.com-1ecc6299db9ec823/rayon-1.5.1/src/iter/plumbing/mod.rs:397:12
  20: <rayon::iter::plumbing::bridge::Callback<C> as rayon::iter::plumbing::ProducerCallback<I>>::callback
             at /home/ritchie46/.cargo/registry/src/github.com-1ecc6299db9ec823/rayon-1.5.1/src/iter/plumbing/mod.rs:373:13
  21: <<rayon::iter::zip::Zip<A,B> as rayon::iter::IndexedParallelIterator>::with_producer::CallbackB<CB,A> as rayon::iter::plumbing::ProducerCallback<ITEM>>::callback
             at /home/ritchie46/.cargo/registry/src/github.com-1ecc6299db9ec823/rayon-1.5.1/src/iter/zip.rs:113:17
  22: <<rayon::iter::map::Map<I,F> as rayon::iter::IndexedParallelIterator>::with_producer::Callback<CB,F> as rayon::iter::plumbing::ProducerCallback<T>>::callback
             at /home/ritchie46/.cargo/registry/src/github.com-1ecc6299db9ec823/rayon-1.5.1/src/iter/map.rs:105:17
  23: <rayon::slice::Iter<T> as rayon::iter::IndexedParallelIterator>::with_producer
             at /home/ritchie46/.cargo/registry/src/github.com-1ecc6299db9ec823/rayon-1.5.1/src/slice/mod.rs:525:9
  24: <rayon::iter::map::Map<I,F> as rayon::iter::IndexedParallelIterator>::with_producer
             at /home/ritchie46/.cargo/registry/src/github.com-1ecc6299db9ec823/rayon-1.5.1/src/iter/map.rs:79:16
  25: <<rayon::iter::zip::Zip<A,B> as rayon::iter::IndexedParallelIterator>::with_producer::CallbackA<CB,B> as rayon::iter::plumbing::ProducerCallback<ITEM>>::callback
             at /home/ritchie46/.cargo/registry/src/github.com-1ecc6299db9ec823/rayon-1.5.1/src/iter/zip.rs:90:17
  26: <rayon::slice::Iter<T> as rayon::iter::IndexedParallelIterator>::with_producer
             at /home/ritchie46/.cargo/registry/src/github.com-1ecc6299db9ec823/rayon-1.5.1/src/slice/mod.rs:525:9
  27: <rayon::iter::zip::Zip<A,B> as rayon::iter::IndexedParallelIterator>::with_producer
             at /home/ritchie46/.cargo/registry/src/github.com-1ecc6299db9ec823/rayon-1.5.1/src/iter/zip.rs:69:16
  28: rayon::iter::plumbing::bridge
             at /home/ritchie46/.cargo/registry/src/github.com-1ecc6299db9ec823/rayon-1.5.1/src/iter/plumbing/mod.rs:357:12
  29: <rayon::iter::zip::Zip<A,B> as rayon::iter::ParallelIterator>::drive_unindexed
             at /home/ritchie46/.cargo/registry/src/github.com-1ecc6299db9ec823/rayon-1.5.1/src/iter/zip.rs:41:9
  30: <rayon::iter::filter_map::FilterMap<I,P> as rayon::iter::ParallelIterator>::drive_unindexed
             at /home/ritchie46/.cargo/registry/src/github.com-1ecc6299db9ec823/rayon-1.5.1/src/iter/filter_map.rs:46:9
  31: <rayon::iter::flatten::Flatten<I> as rayon::iter::ParallelIterator>::drive_unindexed
             at /home/ritchie46/.cargo/registry/src/github.com-1ecc6299db9ec823/rayon-1.5.1/src/iter/flatten.rs:38:9
  32: <rayon::iter::fold::Fold<I,ID,F> as rayon::iter::ParallelIterator>::drive_unindexed
             at /home/ritchie46/.cargo/registry/src/github.com-1ecc6299db9ec823/rayon-1.5.1/src/iter/fold.rs:59:9
  33: <rayon::iter::map::Map<I,F> as rayon::iter::ParallelIterator>::drive_unindexed
             at /home/ritchie46/.cargo/registry/src/github.com-1ecc6299db9ec823/rayon-1.5.1/src/iter/map.rs:49:9
  34: rayon::iter::reduce::reduce
             at /home/ritchie46/.cargo/registry/src/github.com-1ecc6299db9ec823/rayon-1.5.1/src/iter/reduce.rs:15:5
  35: rayon::iter::ParallelIterator::reduce
             at /home/ritchie46/.cargo/registry/src/github.com-1ecc6299db9ec823/rayon-1.5.1/src/iter/mod.rs:981:9
  36: rayon::iter::extend::collect
             at /home/ritchie46/.cargo/registry/src/github.com-1ecc6299db9ec823/rayon-1.5.1/src/iter/extend.rs:29:5
  37: rayon::iter::collect::<impl rayon::iter::ParallelExtend<T> for alloc::vec::Vec<T>>::par_extend
             at /home/ritchie46/.cargo/registry/src/github.com-1ecc6299db9ec823/rayon-1.5.1/src/iter/collect/mod.rs:165:28
  38: rayon::iter::from_par_iter::collect_extended
             at /home/ritchie46/.cargo/registry/src/github.com-1ecc6299db9ec823/rayon-1.5.1/src/iter/from_par_iter.rs:17:5
  39: rayon::iter::from_par_iter::<impl rayon::iter::FromParallelIterator<T> for alloc::vec::Vec<T>>::from_par_iter
             at /home/ritchie46/.cargo/registry/src/github.com-1ecc6299db9ec823/rayon-1.5.1/src/iter/from_par_iter.rs:30:9
  40: rayon::iter::ParallelIterator::collect
             at /home/ritchie46/.cargo/registry/src/github.com-1ecc6299db9ec823/rayon-1.5.1/src/iter/mod.rs:2046:9
  41: <polars_lazy::physical_plan::executors::groupby::PartitionGroupByExec as polars_lazy::physical_plan::Executor>::execute::{{closure}}
             at /home/ritchie46/code/polars/polars/polars-lazy/src/physical_plan/executors/groupby.rs:275:13
  42: core::ops::function::FnOnce::call_once
             at /rustc/f586d79d183d144e0cbf519e29247f36670e2076/library/core/src/ops/function.rs:227:5
  43: rayon_core::join::join::call::{{closure}}
             at /home/ritchie46/.cargo/registry/src/github.com-1ecc6299db9ec823/rayon-core-1.9.1/src/join/mod.rs:102:18
  44: rayon_core::join::join_context::call_b::{{closure}}
             at /home/ritchie46/.cargo/registry/src/github.com-1ecc6299db9ec823/rayon-core-1.9.1/src/join/mod.rs:129:25
  45: <rayon_core::job::StackJob<L,F,R> as rayon_core::job::Job>::execute::call::{{closure}}
             at /home/ritchie46/.cargo/registry/src/github.com-1ecc6299db9ec823/rayon-core-1.9.1/src/job.rs:113:21
  46: <std::panic::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once
             at /rustc/f586d79d183d144e0cbf519e29247f36670e2076/library/std/src/panic.rs:347:9
  47: std::panicking::try::do_call
             at /rustc/f586d79d183d144e0cbf519e29247f36670e2076/library/std/src/panicking.rs:401:40
  48: __rust_try
  49: std::panicking::try
             at /rustc/f586d79d183d144e0cbf519e29247f36670e2076/library/std/src/panicking.rs:365:19
  50: std::panic::catch_unwind
             at /rustc/f586d79d183d144e0cbf519e29247f36670e2076/library/std/src/panic.rs:434:14
  51: rayon_core::unwind::halt_unwinding
             at /home/ritchie46/.cargo/registry/src/github.com-1ecc6299db9ec823/rayon-core-1.9.1/src/unwind.rs:17:5
  52: <rayon_core::job::StackJob<L,F,R> as rayon_core::job::Job>::execute
             at /home/ritchie46/.cargo/registry/src/github.com-1ecc6299db9ec823/rayon-core-1.9.1/src/job.rs:119:38
  53: rayon_core::job::JobRef::execute
             at /home/ritchie46/.cargo/registry/src/github.com-1ecc6299db9ec823/rayon-core-1.9.1/src/job.rs:59:9
  54: rayon_core::registry::WorkerThread::execute
             at /home/ritchie46/.cargo/registry/src/github.com-1ecc6299db9ec823/rayon-core-1.9.1/src/registry.rs:749:9
  55: rayon_core::registry::WorkerThread::wait_until_cold
             at /home/ritchie46/.cargo/registry/src/github.com-1ecc6299db9ec823/rayon-core-1.9.1/src/registry.rs:726:17
  56: rayon_core::registry::WorkerThread::wait_until
             at /home/ritchie46/.cargo/registry/src/github.com-1ecc6299db9ec823/rayon-core-1.9.1/src/registry.rs:700:13
  57: rayon_core::registry::main_loop
             at /home/ritchie46/.cargo/registry/src/github.com-1ecc6299db9ec823/rayon-core-1.9.1/src/registry.rs:833:5
  58: rayon_core::registry::ThreadBuilder::run
             at /home/ritchie46/.cargo/registry/src/github.com-1ecc6299db9ec823/rayon-core-1.9.1/src/registry.rs:55:18
  59: <rayon_core::registry::DefaultSpawn as rayon_core::registry::ThreadSpawn>::spawn::{{closure}}
             at /home/ritchie46/.cargo/registry/src/github.com-1ecc6299db9ec823/rayon-core-1.9.1/src/registry.rs:100:20
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.


````

```
import polars as pl
import numpy as np
import pandas as pd
import pyarrow as pa

np.random.seed(42)

# Maybe a date_range like function in Polars could also be nice. Now using pandas for this
date_times = pd.date_range('2021-06-24 00:00:00', '2021-06-24 5:00:00', freq='30min', closed='left')
dts = pl.from_pandas(date_times).apply(lambda x: x + np.random.randint(1_000*60, 60_000*60)).cast(pl.Date64)

# some df with sensor id, (randomish) datetime and some value
df = pl.DataFrame(
    {
        'sensor': ['a', 'b', 'a', 'b', 'a', 'b', 'a', 'b', 'a', 'b'],
        'datetime': dts,
        'value': [2, 3, 4, 1, 2 ,3, 5, 1, 2, 3]
    }
)

# creating some irregular measurements over time by skipping a few rows
df = df.sample(8)
print("Original DataFrame -", df)

# The downsample (resample) is already there:

print(
    "Downsample, take first per sensor per hour -",
    df.groupby('sensor').apply(lambda df: df.downsample(by='datetime', rule='hour', n=1).first())
)

# let's say you want to reindex to whole hours, you can:

# round to hours
hour_ms = 3_600_000
df['datetime'] = df['datetime'].apply(lambda x: x // hour_ms * hour_ms).cast(pl.Date64)

# the "index" you want to "reindex" with, since we want both senors for all hourly intervals
all_hours = pl.DataFrame({'datetime': pa.array(date_times.tolist()*2), 'sensor':['a']*10 + ['b']*10})

df_per_hour = (all_hours
               .join(df, on=['sensor', 'datetime'], how='left'))
print("Both sensors have all (hourly) intervals -", df_per_hour)
df_per_hour.groupby("sensor").agg(pl.col("value").list())
```

**Comment by ritchie46** [comment]
Probably again offsets and null buffers.
