### ISSUE TITLE
Sortby raise PanicException if is called in grouping context and len of sorted by column == 0

### ISSUE THREAD

**Issue by LdRoW** [pola-rs/polars#8940]
### Polars version checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pypi.org/project/polars/) of Polars.

### Issue description

If length of column and length of sorted by column is equal zero, polars raises panic exception:
```python
thread '<unnamed>' panicked at 'index out of bounds: the len is 0 but the index is 0', /home/runner/work/polars/polars/polars/polars-lazy/src/physical_plan/expressions/sortby.rs:thread '201<unnamed>:' panicked at '30index out of bounds: the len is 0 but the index is 0', 
/home/runner/work/polars/polars/polars/polars-lazy/src/physical_plan/expressions/sortby.rsnote: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
:201:30
Traceback (most recent call last):
  File "/home/test/test_project/test3.py", line 10, in <module>
    ).collect()
      ^^^^^^^^^
  File "/home/test/test_project/venv/lib/python3.11/site-packages/polars/lazyframe/frame.py", line 1602, in collect
    return wrap_df(ldf.collect())
                   ^^^^^^^^^^^^^
pyo3_runtime.PanicException: index out of bounds: the len is 0 but the index is 0

```

### Reproducible example

```python
import polars as pl

with pl.StringCache():
    df = pl.DataFrame(
        {"a": [1, 1, 1], "b": [3, 2, 1], "c": [1, 1, 2]}, schema={"a": pl.Float32, "b": pl.Float32, "c": pl.Float32}
    )

    df.lazy().groupby("c").agg(
        [pl.col("a").filter(pl.col("b") > 100).sort_by(pl.col("b").filter(pl.col("b") > 100)).sum()]
    ).collect()
```

### Expected behavior

Same as in  not grouping context - return empty series

### Installed versions

<details>

```
--------Version info---------
Polars:      0.17.14
Index type:  UInt32
Platform:    Linux-5.15.0-53-generic-x86_64-with-glibc2.35
Python:      3.11.3 (main, Apr  7 2023, 16:20:28) [GCC 11.3.0]

----Optional dependencies----
numpy:       1.24.3
pandas:      2.0.1
pyarrow:     11.0.0
connectorx:  <not installed>
deltalake:   <not installed>
fsspec:      <not installed>
matplotlib:  <not installed>
xlsx2csv:    <not installed>
xlsxwriter:  <not installed>
```

</details>

**Comment by cmdlineluser** [comment]
Perhaps these are useful test-cases:
```python
df = pl.DataFrame([1, 2, 3])

df.select(pl.all().sort_by([]).over(True))

# PanicException: index out of bounds: the len is 0 but the index is 0
#
# thread '<unnamed>' panicked at 'index out of bounds: the len is 0 but the index is 0', 
# /Users/user/git/polars/polars/polars-lazy/src/physical_plan/expressions/sortby.rs:233:21
### 

df.select(pl.all().sort_by([]))

# PanicException: range start index 1 out of range for slice of length 0
#
# thread '<unnamed>' panicked at 'range start index 1 out of range for slice of length 0', 
# /Users/user/git/polars/polars/polars-lazy/src/physical_plan/expressions/sortby.rs:78:28
###
```
