### ISSUE TITLE
`.list.tail(n)` returns empty list when `n` is of type `UInt32`

### ISSUE THREAD

**Issue by cmdlineluser** [pola-rs/polars#9087]
### Polars version checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pypi.org/project/polars/) of Polars.

### Issue description

I noticed this when attempting to use the result of `.list.lengths()` as head/slice/tail index.

I narrowed it down to being the fact that the result is of type `u32`.

head works, it seems to be specific to tail.

### Reproducible example

```python
import polars as pl

pl.Series([["a", "b", "c"]]).list.head(pl.lit(1, pl.UInt32))

# shape: (1,)
# Series: '' [list[str]]
# [
# 	["a"]
# ]

pl.Series([["a", "b", "c"]]).list.tail(pl.lit(1, pl.UInt32))

# shape: (1,)
# Series: '' [list[str]]
# [
# 	[]
# ]
```

### Expected behavior

`tail` should return `["c"]`

### Installed versions

<details>

```
Latest commit from `main`
```

</details>

**Comment by ritchie46** [comment]
Constant folding optimization being to trigger happy.

```
thread '<unnamed>' panicked at 'attempt to subtract with overflow', /rustc/a77c552485a19245a266bc03c450676c666b605f/library/core/src/ops/arith.rs:217:1
stack backtrace:
   0: rust_begin_unwind
             at /rustc/a77c552485a19245a266bc03c450676c666b605f/library/std/src/panicking.rs:578:5
   1: core::panicking::panic_fmt
             at /rustc/a77c552485a19245a266bc03c450676c666b605f/library/core/src/panicking.rs:67:14
   2: core::panicking::panic
             at /rustc/a77c552485a19245a266bc03c450676c666b605f/library/core/src/panicking.rs:117:5
   3: <u32 as core::ops::arith::Sub>::sub
             at /rustc/a77c552485a19245a266bc03c450676c666b605f/library/core/src/ops/arith.rs:210:45
   4: <&u32 as core::ops::arith::Sub<&u32>>::sub
             at /rustc/a77c552485a19245a266bc03c450676c666b605f/library/core/src/internal_macros.rs:55:17
   5: <polars_plan::logical_plan::optimizer::simplify_expr::SimplifyExprRule as polars_plan::logical_plan::optimizer::stack_opt::OptimizationRule>::optimize_expr
             at /home/ritchie46/code/polars/polars/polars-lazy/polars-plan/src/logical_plan/optimizer/simplify_expr.rs:485:30
   6: polars_plan::logical_plan::optimizer::stack_opt::StackOptimizer::optimize_loop
             at /home/ritchie46/code/polars/polars/polars-lazy/polars-plan/src/logical_plan/optimizer/stack_opt.rs:71:45
   7: polars_plan::logical_plan::optimizer::optimize
             at /home/ritchie46/code/polars/polars/polars-lazy/polars-plan/src/logical_plan/optimizer/mod.rs:178:14
   8: polars_lazy::frame::LazyFrame::optimize_with_scratch
             at /home/ritchie46/code/polars/polars/polars-lazy/src/frame/mod.rs:477:22
   9: polars_lazy::frame::LazyFrame::prepare_collect
             at /home/ritchie46/code/polars/polars/polars-lazy/src/frame/mod.rs:502:13
  10: polars_lazy::frame::LazyFrame::collect
             at /home/ritchie46/code/polars/polars/polars-lazy/src/frame/mod.rs:548:49
  11: polars::lazyframe::PyLazyFrame::collect::{{closure}}
             at /home/ritchie46/code/polars/py-polars/src/lazyframe.rs:415:13
  12: pyo3::marker::Python::allow_threads
             at /home/ritchie46/.cargo/registry/src/index.crates.io-6f17d22bba15001f/pyo3-0.18.3/src/marker.rs:473:9
  13: polars::lazyframe::PyLazyFrame::collect
             at /home/ritchie46/code/polars/py-polars/src/lazyframe.rs:413:18
  14: polars::lazyframe::_::<impl polars::lazyframe::PyLazyFrame>::__pymethod_collect__
             at /home/ritchie46/code/polars/py-polars/src/lazyframe.rs:62:1
  15: pyo3::impl_::trampoline::noargs::{{closure}}
             at /home/ritchie46/.cargo/registry/src/index.crates.io-6f17d22bba15001f/pyo3-0.18.3/src/impl_/trampoline.rs:31:27
  16: pyo3::impl_::trampoline::trampoline_inner::{{closure}}
             at /home/ritchie46/.cargo/registry/src/index.crates.io-6f17d22bba15001f/pyo3-0.18.3/src/impl_/trampoline.rs:204:54
  17: std::panicking::try::do_call
             at /rustc/a77c552485a19245a266bc03c450676c666b605f/library/std/src/panicking.rs:485:40
  18: __rust_try
  19: std::panicking::try
```
