### ISSUE TITLE
OutOfSpec("An ArrowArray of type Decimal(36, 6)\n            must have buffer 1 aligned to type i128")

### ISSUE THREAD

**Issue by thomasaarholt** [pola-rs/polars#9184]
### Polars version checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pypi.org/project/polars/) of Polars.

### Issue description

We've been getting this error for certain rows (!) in our data. We have a pipeline that queries data from Snowflake and gets it as a pyarrow Table, which is then read into polars via `pl.from_table`. 

I'd provide an dataset, but when I save the table with arrow and read it back in, the error is gone. This might imply a bug with pyarrow, but I'd like to check with polars since this is where I trigger an error. Is there any chance this is a mistake on polars part?

Full error:
```python
Traceback (most recent call last):
  File "/fabrica/projects/adivino/thomas-test.py", line 37, in <module>
    pl.from_arrow(t_last_row) # same error as above
  File "/usr/local/lib/python3.10/site-packages/polars/convert.py", line 599, in from_arrow
    return pl.DataFrame._from_arrow(
  File "/usr/local/lib/python3.10/site-packages/polars/dataframe/frame.py", line 612, in _from_arrow
    arrow_to_pydf(
  File "/usr/local/lib/python3.10/site-packages/polars/utils/_construction.py", line 1338, in arrow_to_pydf
    pydf = PyDataFrame.from_arrow_record_batches(tbl.to_batches())
exceptions.ArrowErrorException: OutOfSpec("An ArrowArray of type Decimal(36, 6)\n            must have buffer 1 aligned to type i128")
```

**Example with interesting cases:**

```python

# table is a pyarrow.Table with the following schema:
# year is int64, average_number_of_days is Decimal(36, 6)
table = table.select(["year", "average_number_of_days"])

# pl.from_arrow(table) # this triggers an error
    # Traceback (most recent call last):
    # File "/fabrica/projects/adivino/thomas-test.py", line 16, in <module>
    #     pl.from_arrow(table) # this triggers an error
    # File "/usr/local/lib/python3.10/site-packages/polars/convert.py", line 599, in from_arrow
    #     return pl.DataFrame._from_arrow(
    # File "/usr/local/lib/python3.10/site-packages/polars/dataframe/frame.py", line 612, in _from_arrow
    #     arrow_to_pydf(
    # File "/usr/local/lib/python3.10/site-packages/polars/utils/_construction.py", line 1323, in arrow_to_pydf
    #     pydf = PyDataFrame.from_arrow_record_batches(tbl.to_batches())
    # exceptions.ArrowErrorException: OutOfSpec("An ArrowArray of type Decimal(36, 6)\n            must have buffer 1 aligned to type i128")

# This triggers an error
t_last_row = table[-1:]
print(t_last_row)
    # pyarrow.Table
    # year: int64
    # average_number_of_days: decimal128(36, 6)
    # ----
    # year: [[2023]]
    # average_number_of_days: [[2.000000]]
pl.from_arrow(t_last_row) # same error as above

# This doesn't trigger an error
t_last_row = table[:1]
print(t_last_row)
    # pyarrow.Table
    # year: int64
    # average_number_of_days: decimal128(36, 6)
    # ----
    # year: [[2023]]
    # average_number_of_days: [[2.000000]]
pl.from_arrow(t_last_row) # no error

# Saving and re-reading the table, and then pl.from_arrow doesn't trigger an error
import pyarrow.parquet as pq
pq.write_table(table, 'example.parquet')
table2 = pq.read_table("example.parquet")
pl.from_arrow(table2)
```

### Reproducible example

```python
*
```

### Expected behavior

Should be read in without error

### Installed versions

<details>

```
--------Version info---------
Polars:      0.18.0
Index type:  UInt32
Platform:    Linux-5.15.49-linuxkit-aarch64-with-glibc2.31
Python:      3.10.11 (main, May  3 2023, 08:40:14) [GCC 10.2.1 20210110]

----Optional dependencies----
numpy:       1.24.3
pandas:      1.5.3
pyarrow:     10.0.1
connectorx:  <not installed>
deltalake:   <not installed>
fsspec:      2023.5.0
matplotlib:  3.7.1
xlsx2csv:    <not installed>
xlsxwriter:  <not installed>
```

</details>

**Comment by ritchie46** [comment]
Might be similar to this: https://github.com/pola-rs/polars/issues/6315#issuecomment-1411611105

Does the data come via IPC?

**Comment by thomasaarholt** [comment]
No, I don't think so. It's coming in via the snowflake-connector-python.

**Comment by ritchie46** [comment]
> No, I don't think so. It's coming in via the snowflake-connector-python.

I think that uses IPC. IPC is used when you send arrow over the wire.

**Comment by thomasaarholt** [comment]
Ah, then yes. I'll report it over at pyarrow.

**Comment by ngriffiths13** [comment]
@thomasaarholt did you open an issue with pyarrow somewhere that I can follow?

**Comment by thomasaarholt** [comment]
I haven’t had time. Do you mind opening one instead?
