### ISSUE TITLE
Reading avro file returns ComputeError: OutOfSpec in both Rust and Python

### ISSUE THREAD

**Issue by rogerjbos** [pola-rs/polars#9249]
### Polars version checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://crates.io/crates/polars) of Polars.

### Issue description

Here is the error I am getting: 

thread 'main' panicked at 'file not read: ComputeError(ErrString("OutOfSpec"))', src/main.rs:29:50
stack backtrace:
   0: rust_begin_unwind
             at /rustc/9eb3afe9ebe9c7d2b84b71002d44f4a0edac95e0/library/std/src/panicking.rs:575:5
   1: core::panicking::panic_fmt
             at /rustc/9eb3afe9ebe9c7d2b84b71002d44f4a0edac95e0/library/core/src/panicking.rs:64:14
   2: core::result::unwrap_failed
             at /rustc/9eb3afe9ebe9c7d2b84b71002d44f4a0edac95e0/library/core/src/result.rs:1790:5
   3: core::result::Result<T,E>::expect
             at /rustc/9eb3afe9ebe9c7d2b84b71002d44f4a0edac95e0/library/core/src/result.rs:1069:23
   4: westend_example::main
             at ./src/main.rs:29:19
   5: core::ops::function::FnOnce::call_once
             at /rustc/9eb3afe9ebe9c7d2b84b71002d44f4a0edac95e0/library/core/src/ops/function.rs:250:5

### Reproducible example

    let fname = "westend_westend_20230411_westend_blocks.avro";
    let file = File::open(fname).expect("file not found");
    println!("file found! {:?}", file);

    let df_avro = AvroReader::new(file).finish().expect("file not read");
    println!("df_avro: {:?}", df_avro);

### Expected behavior

The same file was read in just fine using pandas.
[westend_westend_20230411_westend_blocks.txt](https://github.com/pola-rs/polars/files/11659328/westend_westend_20230411_westend_blocks.txt)
Rename the .txt file to .avro.  For some reason Github wouldn't allow me to upload an avro file.

### Installed versions

<details>
polars-io = { version = "0.30.0", features = ["avro"]}
</details>

**Comment by ritchie46** [comment]
Are you 100% certain the file is correct?

**Comment by cjackal** [comment]
At least I can confirm that the attachment can be open with `fastavro`. Have no domain on AVRO file spec tho

**Comment by vertexclique** [comment]
This keeps happening. Fyi ^^^.

**Comment by mangoleaf** [comment]
Can confirm this is a valid issue. From my investigation it appears to be the fault of the code that writes the avro file.

Reading an avro that was written from 0.35 crashed when reading in 0.33.
Reading an avro in 0.33 that was written on 0.33 worked.
Reading an avro in 0.35 that was written in 0.35 worked.

**Comment by musa-karimli-m10** [comment]
I have this error too, some avro files can be read but some cannot be read despite all of them read by spark without any issue, I don't see any pattern yet.

**Comment by itamarst** [comment]
Not sure if this covers all cases, since there are no reproducers, but here's one reproducer:

```python
import sys
import polars as pl

file_path = "test.avro"
df = pl.DataFrame({"a": list(range(int(sys.argv[1])))})

df.write_avro(file_path)

# This fails:
pl.read_avro(file_path)
print("Success!")
```

If the number of items is smaller than 262,144, this works fine. Larger sizes break. Demonstration:

```
$ python 9249.py 262143
Success!
$ python 9249.py 262144
Traceback (most recent call last):
  File "/home/itamarst/devel/polars/py-polars/9249.py", line 14, in <module>
    pl.read_avro(file_path)
  File "/home/itamarst/devel/polars/py-polars/polars/io/avro.py", line 38, in read_avro
    return pl.DataFrame._read_avro(source, n_rows=n_rows, columns=columns)
  File "/home/itamarst/devel/polars/py-polars/polars/dataframe/frame.py", line 782, in _read_avro
    self._df = PyDataFrame.read_avro(source, columns, projection, n_rows)
polars.exceptions.ComputeError: avro-error: OutOfSpec
```

I believe this has something to do with block size logic, because if you have multiple chunks in the DataFrame, it gets written as corresponding Avro blocks, and if you have two blocks you get this error on much smaller block size threshold.

**Comment by itamarst** [comment]
Not going to look into this any more.

Investigation didn't lead anywhere obvious, and I got deep enough I'd have to dig into `avro-schema` to see if there are bugs there. E.g. it's possible the zig decoding isn't quite implemented right. Unfortunately it seems pretty moribund as a project... https://docs.rs/apache-avro/ seems a lot better maintained.

**Comment by buzzware** [comment]
I am trying to load files following the BigQuery avro convention of loading stringified json columns with `type: {type: "string", sqlType: "JSON"}` as a column of type JSON. 
I am using nodejs-polars.
I have attached a zip file containing generation js files and timeseries.avro and timeseries_nested.avro.
`pl.readAvro(thisDir+'/timeseries.avro')` succeeds, while `pl.readAvro(thisDir+'/timeseries_nested.avro')` fails with `Error: OutOfSpec`
The only difference is that timeseries_nested has an added column defined by `{ name: 'attributes', type: {type: "string", sqlType: "JSON"}, default: "{}"}`
While I would like polars to load this column as an object, and I understand why it doesn't, I believe it should at least load the file with attributes as a string column.
[avro files.zip](https://github.com/user-attachments/files/17942365/avro.files.zip)

**Comment by snorochevskiy** [comment]
I have the same error when I try to read Avro file using Polars.
The error comes from `avro-schema` library, and is caused by the "default" value for a avro record field.

In this library, "default" value is mistakenly de-serialized into `avro_schema::schema::Schema` object, which obviously won't work.
https://github.com/DataEngineeringLabs/avro-schema/blob/main/src/schema/mod.rs#L61

To reproduce:
```rust
#[test]
fn test_avro_schema_fails_of_default_field() {
    let json = r#"
        {
            "type":"record",
            "name":"MyEntity",
            "namespace":"com.company.department.schema.avro.myentity",
            "fields":[
                {
                    "name":"schemaVersion",
                    "type":"string",
                    "default":"1.0.0"
                }
            ]
        }"#;
    // Fails because avro-schema cannot parse fields.default
    let schema: avro_schema::schema::Schema = serde_json::from_str(json).unwrap();
}
```

**Comment by erikbrinkman** [comment]
It's come up in other places, but avro support isn't planned to be maintained in polars core. As a result I wrote [polars-avro](https://pypi.org/project/polars-avro/) and [polars-fastavro](https://pypi.org/project/polars-fastavro/), which both use the polars io-plugin support to read/write/scan avro files. The former uses the rust interface, is faster, supports more avro types and cloud files, but only has wheels for mac-arm and many-linux. The latter is just a wrapper around fastavro, so it works in all environments fastavro does, but is slower, doesn't support cloud files, and only works with types that can be cast directly from fastavro serialization.

Both of these libraries can read and write the files listed here, so hopefully they'll be of some use.
