### ISSUE TITLE
read_csv with accents and uncommon characters (cp1252 encoding)

### ISSUE THREAD

**Issue by set92** [pola-rs/polars#9280]
### Polars version checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pypi.org/project/polars/) of Polars.

### Issue description

I didn't know how to do a simple csv file without uploading a file because the problem happens when loading the file. But I'm working with CSV with encoding "cp1252", and pandas loads it correctly, but polars no.

The minimal content of file would be:
```
Código Cliente;Dirección;Población;Código Postal
1234;PºDUQUE JOSÉ,12,1ºA;IRÚN;1234
```

### Reproducible example

```python
pl.read_csv("test.CSV", separator=";", encoding="cp1252")



Error 1 --> If I pass him "test.csv" it interprets it as a python file object?
```python
Polars found a filename. Ensure you pass a path to the file instead of a python file object when possible for best performance.
```

Error 2 --> And the big problem, it fails when reading the file.
```python
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/stobal/.pyenv/versions/3.9.13/lib/python3.9/site-packages/polars/io/csv/functions.py", line 355, in read_csv
    df = pl.DataFrame._read_csv(
  File "/home/stobal/.pyenv/versions/3.9.13/lib/python3.9/site-packages/polars/dataframe/frame.py", line 780, in _read_csv
    self._df = PyDataFrame.read_csv(
exceptions.ComputeError: invalid utf-8 sequence in csv
```
```


### Expected behavior

Same as in pandas, that loads correctly, I suppose the problem is the encoding?

```python
pd.read_csv("test.CSV", sep=";", encoding="cp1252")
```
	Código Cliente	Dirección	Población	Código Postal
	0	1234	PºDUQUE JOSÉ,12,1ºA	IRÚN	1234

### Installed versions

<details>

```
--------Version info---------
Polars:      0.18.0
Index type:  UInt32
Platform:    Linux-5.19.0-42-generic-x86_64-with-glibc2.36
Python:      3.9.13 (main, Aug 12 2022, 11:17:47) 
[GCC 9.4.0]

----Optional dependencies----
numpy:       1.23.4
pandas:      1.5.1
pyarrow:     11.0.0
connectorx:  0.3.1
deltalake:   <not installed>
fsspec:      2023.3.0
matplotlib:  <not installed>
xlsx2csv:    <not installed>
xlsxwriter:  <not installed>
```

</details>

**Comment by cmdlineluser** [comment]
The example works for me:
```python
import polars as pl

data = """
Código Cliente;Dirección;Población;Código Postal
1234;PºDUQUE JOSÉ,12,1ºA;IRÚN;1234
""".strip().encode("cp1252")

# ComputeError: invalid utf-8 sequence in csv
try:
   pl.read_csv(data, separator=";")
except Exception as e:
   print(f"{e=}")

# OK
pl.read_csv(data, separator=";", encoding="cp1252")

# shape: (1, 4)
# ┌────────────────┬─────────────────────┬───────────┬───────────────┐
# │ Código Cliente ┆ Dirección           ┆ Población ┆ Código Postal │
# │ ---            ┆ ---                 ┆ ---       ┆ ---           │
# │ i64            ┆ str                 ┆ str       ┆ i64           │
# ╞════════════════╪═════════════════════╪═══════════╪═══════════════╡
# │ 1234           ┆ PºDUQUE JOSÉ,12,1ºA ┆ IRÚN      ┆ 1234          │
# └────────────────┴─────────────────────┴───────────┴───────────────┘
```
I'm not sure if the fact I copied the text from my browser changed anything, but these are the bytes used:
```python
import io
import polars as pl

data = bytearray(
   [
      67, 243, 100, 105, 103, 111, 32, 67, 108, 105, 101, 110, 116, 101, 59,
      68, 105, 114, 101, 99, 99, 105, 243, 110, 59, 80, 111, 98, 108, 97, 99,
      105, 243, 110, 59, 67, 243, 100, 105, 103, 111, 32, 80, 111, 115, 116, 97,
      108, 10, 49, 50, 51, 52, 59, 80, 186, 68, 85, 81, 85, 69, 32, 74, 79, 83, 
      201, 44, 49, 50, 44, 49, 186, 65, 59, 73, 82, 218, 78, 59, 49, 50, 51, 52,
   ]
)

pl.read_csv(io.BytesIO(data), separator=";", encoding="cp1252")

# shape: (1, 4)
# ┌────────────────┬─────────────────────┬───────────┬───────────────┐
# │ Código Cliente ┆ Dirección           ┆ Población ┆ Código Postal │
# │ ---            ┆ ---                 ┆ ---       ┆ ---           │
# │ i64            ┆ str                 ┆ str       ┆ i64           │
# ╞════════════════╪═════════════════════╪═══════════╪═══════════════╡
# │ 1234           ┆ PºDUQUE JOSÉ,12,1ºA ┆ IRÚN      ┆ 1234          │
# └────────────────┴─────────────────────┴───────────┴───────────────┘
```
