### ISSUE TITLE
Unable to infer datatime schema from pydantic models

### ISSUE THREAD

**Issue by samuelcolvin** [pola-rs/polars#9282]
### Polars version checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pypi.org/project/polars/) of Polars.

### Issue description

The following code is resulting in an error:

```
exceptions.ComputeError: could not append value: 2021-01-01 00:00:00 of type: datetime[μs] to the builder; make sure that all rows have the same schema or consider increasing `schema_inference_length`

it might also be that a value overflows the data-type's capacity
```

Full trace below

### Reproducible example

```python
from datetime import datetime
from pathlib import Path
from typing import Literal

import polars as pl

from pydantic import BaseModel, Field, TypeAdapter, __version__ as pydantic_version
from devtools import debug

pl.show_versions()
print(f'pydantic version: {pydantic_version}')

class PageView(BaseModel):
    user_id: str
    ts: datetime = Field(alias=['ts', '$date'])
    path: str = Field('?', alias=['url', 'path'])
    referer: str = Field('?', alias='referer')
    event: Literal['leave', 'enter'] = Field('enter')
    time_on_page: int = Field(0, serialization_alias='top')


# with debug.timer('read files'):
#     data_json = Path('pydantic_dev.json').read_bytes()
#     data_json = b'[' + data_json.replace(b'\n', b',\n')
#     data_json = data_json[:-2] + b']'

data_json = '[{"user_id": "x", "ts": {"$date": "2021-01-01T00:00:00.000Z"}, "url": "/latest/foobar", "referer": "https://google.com", "event": "enter", "top": 123}]'

with debug.timer('load data'):
    at = TypeAdapter(list[PageView])
    models = at.validate_json(data_json)

with debug.timer('create df'):
    df = pl.DataFrame(models)
print(df)
df.write_parquet('site_traffic.parquet')
```

### Expected behavior

should be able to use use datetimes from around now

### Installed versions

<details>

<summary>Version and traceback</summary>

```
--------Version info---------
Polars:      0.18.0
Index type:  UInt32
Platform:    Linux-5.19.0-43-generic-x86_64-with-glibc2.35
Python:      3.10.6 (main, May 29 2023, 11:10:38) [GCC 11.3.0]

----Optional dependencies----
numpy:       1.24.2
pandas:      2.0.0
pyarrow:     11.0.0
connectorx:  <not installed>
deltalake:   <not installed>
fsspec:      <not installed>
matplotlib:  <not installed>
xlsx2csv:    <not installed>
xlsxwriter:  <not installed>
pydantic version: 2.0b2
load data: 0.001s elapsed
create df: 0.000s elapsed
Traceback (most recent call last):
  File "/home/samuel/code/pydantic-analytics/site_read_traffic.py", line 34, in <module>
    df = pl.DataFrame(models)
  File "/home/samuel/code/pydantic-analytics/env310/lib/python3.10/site-packages/polars/dataframe/frame.py", line 368, in __init__
    self._df = sequence_to_pydf(
  File "/home/samuel/code/pydantic-analytics/env310/lib/python3.10/site-packages/polars/utils/_construction.py", line 820, in sequence_to_pydf
    return _sequence_to_pydf_dispatcher(
  File "/usr/lib/python3.10/functools.py", line 889, in wrapper
    return dispatch(args[0].__class__)(*args, **kw)
  File "/home/samuel/code/pydantic-analytics/env310/lib/python3.10/site-packages/polars/utils/_construction.py", line 910, in _sequence_to_pydf_dispatcher
    return to_pydf(**common_params)
  File "/home/samuel/code/pydantic-analytics/env310/lib/python3.10/site-packages/polars/utils/_construction.py", line 1166, in _dataclasses_or_models_to_pydf
    pydf = PyDataFrame.read_rows(rows, infer_schema_length, schema_override or None)
exceptions.ComputeError: could not append value: 2021-01-01 00:00:00 of type: datetime[μs] to the builder; make sure that all rows have the same schema or consider increasing `schema_inference_length`

it might also be that a value overflows the data-type's capacity
```

</details>

**Comment by ritchie46** [comment]
Thanks for the issue report. @alexander-beedie can you take this one?

**Comment by alexander-beedie** [comment]
> Thanks for the issue report. @alexander-beedie can you take this one?

No problem; just brewed a coffee, so will dive right in ☕

**Comment by alexander-beedie** [comment]
Fixed. @samuelcolvin, let me know if you spot any other issues with 2.x and polars interop; will be good to have full support on day one when it releases 👍
