### ISSUE TITLE
eq/ne_missing() does not work in conjunction with other boolean operators

### ISSUE THREAD

**Issue by mcrumiller** [pola-rs/polars#9291]
### Polars version checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pypi.org/project/polars/) of Polars.

### Issue description

When `ne_missing()` or `eq_missing()` is used as an expression, it cannot be chained with other logical operators.

### Reproducible example

```python
import polars as pl
from polars import col

df = pl.DataFrame({
    'a': [1, None, 3],
    'b': [1, 2, 3],
})

# works
df.select(
    pl.col('a').eq_missing(1)
)

# fails
df.select(
    pl.col('a').eq_missing(1) & True
)

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Projects\project-slim\.venv_slim\Lib\site-packages\polars\dataframe\frame.py", line 7105, in select
    .collect(no_optimization=True)
     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Projects\project-slim\.venv_slim\Lib\site-packages\polars\lazyframe\frame.py", line 1501, in collect
    return wrap_df(ldf.collect())
                   ^^^^^^^^^^^^^
exceptions.SchemaError: cannot unpack series of type `i64` into `bool`
```
```


### Expected behavior

Should return boolean series.

### Installed versions

<details>

```
--------Version info---------
Polars:      0.18.0
Index type:  UInt32
Platform:    Windows-10-10.0.19045-SP0
Python:      3.11.2 (tags/v3.11.2:878ead1, Feb  7 2023, 16:38:35) [MSC v.1934 64 bit (AMD64)]

----Optional dependencies----
numpy:       1.24.3
pandas:      2.0.1
pyarrow:     11.0.0
connectorx:  0.3.2a5
deltalake:   <not installed>
fsspec:      <not installed>
matplotlib:  3.7.1
xlsx2csv:    0.8.1
xlsxwriter:  3.0.9
```

</details>

**Comment by ritchie46** [comment]
Try updating. I believe it's fixed.

**Comment by mcrumiller** [comment]
Thanks @ritchie46!
