### ISSUE TITLE
`read_parquet` PanicException when cat column above 600_000 rows saved with`write_parquet` since`0.17.13`

### ISSUE THREAD

**Issue by StevenLi-DS** [pola-rs/polars#9349]
### Polars version checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pypi.org/project/polars/) of Polars.

### Issue description

I have a parquet file I saved with `write_parquet` in `0.17.12` and could read it back in with `read_parquet` with no issue. After updating to `0.18.2` I re-run the code to save the file, but got the following error msg when trying to load it back with `read_parquet`.

```
PanicException: should not fail: ComputeError(ErrString("cannot concat categoricals coming from a different source; consider setting a global StringCache"))
```

I tested a few versions, it seems like the problem was introduced right after `0.17.12` since I got the same exception with `0.17.13`. I also tried to read the file saved in`0.17.12` using `read_parquet` in `0.18.2`, which worked fine. In other words, it has something to do with the file it saved.

All my Categorical columns were created with `cut` method. Eventually, I realized that it has something to do with df size.

### Reproducible example

```python
import polars as pl
import numpy as np
from polars import PolarsPanicError

for n in range(100_000, 1_000_000, 100_000):
    df = pl.DataFrame({'num': np.random.randint(0, 100, n)})
    df = df.with_columns(
        df.get_column('num')
        .cut(bins=[0, 50], labels=['Zero', '0-50', '>50'])
        .get_column('category')
    ).write_parquet(
        './example.parquet'
    )

    try:
        df = pl.read_parquet('./example.parquet')
    except PolarsPanicError:
        print(f'PanicException when df size = {n:_}')
```
```
PanicException when df size = 600_000
PanicException when df size = 700_000
PanicException when df size = 800_000
PanicException when df size = 900_000
thread '<unnamed>' panicked at 'should not fail: ComputeError(ErrString("cannot concat categoricals coming from a different source; consider setting a global StringCache"))', local_dependencies/polars-core/src/frame/mod.rs:922:36
thread '<unnamed>' panicked at 'should not fail: ComputeError(ErrString("cannot concat categoricals coming from a different source; consider setting a global StringCache"))', local_dependencies/polars-core/src/frame/mod.rs:922:36
thread '<unnamed>' panicked at 'should not fail: ComputeError(ErrString("cannot concat categoricals coming from a different source; consider setting a global StringCache"))', local_dependencies/polars-core/src/frame/mod.rs:922:36
thread '<unnamed>' panicked at 'should not fail: ComputeError(ErrString("cannot concat categoricals coming from a different source; consider setting a global StringCache"))', local_dependencies/polars-core/src/frame/mod.rs:922:36
```

### Expected behavior

-

### Installed versions

<details>

```
--------Version info---------
Polars:      0.18.2
Index type:  UInt32
Platform:    macOS-13.4-arm64-arm-64bit
Python:      3.10.11 | packaged by conda-forge | (main, May 10 2023, 19:01:19) [Clang 14.0.6 ]

----Optional dependencies----
numpy:       1.22.4
pandas:      2.0.2
pyarrow:     11.0.0
connectorx:  <not installed>
deltalake:   <not installed>
fsspec:      <not installed>
matplotlib:  3.7.1
xlsx2csv:    0.8.1
xlsxwriter:  <not installed>```

</details>

**Comment by ritchie46** [comment]
You should follow the error message and set a string cache

**Comment by StevenLi-DS** [comment]
@ritchie46 After trying with different way to isolate the issue, it turns out it has something to do with df size. I just updated it above.
