### ISSUE TITLE
Issue with calling collect_all

### ISSUE THREAD

**Issue by ankit-kothari** [pola-rs/polars#9668]
### Polars version checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pypi.org/project/polars/) of Polars.

### Issue description

I am getting error while executing this statement in the most latest version of polars where dfs is a list of lazy polars frames. This statement used to work fine in polars==0.18.2. Any thoughts suggestions why would this be happening and any methods to avoid this?

data_train = pl.concat(pl.collect_all(dfs,streaming=True))

I am getting
File "/opt/conda/lib/python3.7/site-packages/polars/functions/lazy.py", line 2345, in collect_all

out = plr.collect_all(prepared)

exceptions.ComputeError: TypeError: 'bytes' object is not callable

Thanks again for all the help.

### Reproducible example

```python
import polars as pl

loop through parquet files using scan_cv and store the dataframe in a list dfs
Then using
data_train = pl.concat(pl.collect_all(dfs,streaming=True))

This is producing an error
```

### Expected behavior

It should concat all the dataframes in list name dfs and make it a single polars dataframe . It used to work fine in 0.18.2

### Installed versions

<details>

```
0.18.4
```

</details>

**Comment by aersam** [comment]
we have the same error on a simple `LazyFrame.collect()` in combination with sql context.

**Comment by Simon-Will** [comment]
I'm also seeing this error when using the `polars.LazyFrame._scan_python_function`. The following script fails for me in polars 0.18.4 and also the latest version (0.18.8), but succeeds (and prints the dataframe) in polars 0.18.3:

```python
import pickle
import polars as pl

SCHEMA = {"foo": pl.Int64, "bar": pl.Utf8}

def _pseudo_scan(*args, **kwargs):
    return pl.DataFrame(
        {"foo": [1, 2], "bar": ["a", "b"]},
        schema=SCHEMA
    )

def pseudo_scan():
    return pl.LazyFrame._scan_python_function(SCHEMA, pickle.dumps(_pseudo_scan))


print(pseudo_scan().collect())
```

Traceback with polars 0.18.8:

```
Traceback (most recent call last):
  File "//stream_polars.py", line 16, in <module>
    print(pseudo_scan().collect())
          ^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/polars/lazyframe/frame.py", line 1530, in collect
    return wrap_df(ldf.collect())
                   ^^^^^^^^^^^^^
exceptions.ComputeError: TypeError: 'bytes' object is not callable
```

I saw this originally with Python3.9, but also confirmed that it is happening with Python 3.11.4.

**Comment by ankit-kothari** [comment]
@Simon-Will  could you please help/suggest how can i fix the use case,
I am using, pl.read_parquet("test.parquet") and I am getting an empty dataframe.

**Comment by ankit-kothari** [comment]
Hey @ritchie46  I am still seeing this issue, in 0.18.12 , Thanks

**Comment by ritchie46** [comment]
Have you got a repro?

**Comment by coastalwhite** [comment]
Closing for now.
