### ISSUE TITLE
panic when optimizing LazyFrame after join+groupby

### ISSUE THREAD

**Issue by nivkner** [pola-rs/polars#9711]
### Polars version checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pypi.org/project/polars/) of Polars.

### Issue description

when optimizing a lazyframe (either by `explain(optimized=True)` or using `collect`) created by joining two lazyframes on `1` (to simulate a cross-join, tried joining on one of the fields instead, didn't have the same effect) and then doing `groupby` aggregation on the result, i get a panic.

### Reproducible example

```python
import polars as pl

one_df = pl.LazyFrame({}, schema={"C": pl.Int64})

two_df = pl.LazyFrame({}, schema={"b": pl.Utf8})


two_with_misses_df = two_df.join(one_df, on=1)
final_df = two_with_misses_df.groupby("b").sum()
final_df.explain(optimized=True)

```

this produces the panic with the following error:
```
thread '<unnamed>' panicked at 'called `Option::unwrap()` on a `None` value', /home/user/Downloads/polars/polars/polars-lazy/polars-plan/src/utils.rs:358:50
stack backtrace:
   0: rust_begin_unwind
             at /rustc/04075b32021932e3e8f6ab55d519b3b3494b6ef9/library/std/src/panicking.rs:593:5
   1: core::panicking::panic_fmt
             at /rustc/04075b32021932e3e8f6ab55d519b3b3494b6ef9/library/core/src/panicking.rs:67:14
   2: core::panicking::panic
             at /rustc/04075b32021932e3e8f6ab55d519b3b3494b6ef9/library/core/src/panicking.rs:117:5
   3: core::option::Option<T>::unwrap
             at /rustc/04075b32021932e3e8f6ab55d519b3b3494b6ef9/library/core/src/option.rs:935:21
   4: polars_plan::utils::aexpr_to_leaf_name
             at /home/user/Downloads/polars/polars/polars-lazy/polars-plan/src/utils.rs:358:5
   5: polars_plan::logical_plan::optimizer::projection_pushdown::joins::add_keys_to_accumulated_state
             at /home/user/Downloads/polars/polars/polars-lazy/polars-plan/src/logical_plan/optimizer/projection_pushdown/joins.rs:22:20
   6: polars_plan::logical_plan::optimizer::projection_pushdown::joins::process_join
             at /home/user/Downloads/polars/polars/polars-lazy/polars-plan/src/logical_plan/optimizer/projection_pushdown/joins.rs:250:30
   7: polars_plan::logical_plan::optimizer::projection_pushdown::ProjectionPushDown::push_down
             at /home/user/Downloads/polars/polars/polars-lazy/polars-plan/src/logical_plan/optimizer/projection_pushdown/mod.rs:665:22
   8: polars_plan::logical_plan::optimizer::projection_pushdown::ProjectionPushDown::pushdown_and_assign
             at /home/user/Downloads/polars/polars/polars-lazy/polars-plan/src/logical_plan/optimizer/projection_pushdown/mod.rs:251:18
   9: polars_plan::logical_plan::optimizer::projection_pushdown::groupby::process_groupby
             at /home/user/Downloads/polars/polars/polars-lazy/polars-plan/src/logical_plan/optimizer/projection_pushdown/groupby.rs:81:9
  10: polars_plan::logical_plan::optimizer::projection_pushdown::ProjectionPushDown::push_down
             at /home/user/Downloads/polars/polars/polars-lazy/polars-plan/src/logical_plan/optimizer/projection_pushdown/mod.rs:628:18
  11: polars_plan::logical_plan::optimizer::projection_pushdown::ProjectionPushDown::optimize
             at /home/user/Downloads/polars/polars/polars-lazy/polars-plan/src/logical_plan/optimizer/projection_pushdown/mod.rs:787:9
  12: polars_plan::logical_plan::optimizer::optimize
             at /home/user/Downloads/polars/polars/polars-lazy/polars-plan/src/logical_plan/optimizer/mod.rs:104:19
  13: polars_lazy::frame::LazyFrame::optimize_with_scratch
             at /home/user/Downloads/polars/polars/polars-lazy/src/frame/mod.rs:477:22
  14: polars_lazy::frame::LazyFrame::describe_optimized_plan
             at /home/user/Downloads/polars/polars/polars-lazy/src/frame/mod.rs:185:22
  15: polars::lazyframe::PyLazyFrame::describe_optimized_plan
             at /home/user/Downloads/polars/py-polars/src/lazyframe.rs:318:22
  16: polars::lazyframe::_::<impl polars::lazyframe::PyLazyFrame>::__pymethod_describe_optimized_plan__
             at /home/user/Downloads/polars/py-polars/src/lazyframe.rs:61:1
  17: pyo3::impl_::trampoline::noargs::{{closure}}
             at /home/user/.local/share/cargo/registry/src/index.crates.io-6f17d22bba15001f/pyo3-0.19.0/src/impl_/trampoline.rs:31:27
  18: pyo3::impl_::trampoline::trampoline_inner::{{closure}}
             at /home/user/.local/share/cargo/registry/src/index.crates.io-6f17d22bba15001f/pyo3-0.19.0/src/impl_/trampoline.rs:181:54
  19: std::panicking::try::do_call
             at /rustc/04075b32021932e3e8f6ab55d519b3b3494b6ef9/library/std/src/panicking.rs:500:40
  20: __rust_try
  21: std::panicking::try
             at /rustc/04075b32021932e3e8f6ab55d519b3b3494b6ef9/library/std/src/panicking.rs:464:19
  22: std::panic::catch_unwind
             at /rustc/04075b32021932e3e8f6ab55d519b3b3494b6ef9/library/std/src/panic.rs:142:14
  23: pyo3::impl_::trampoline::trampoline_inner
             at /home/user/.local/share/cargo/registry/src/index.crates.io-6f17d22bba15001f/pyo3-0.19.0/src/impl_/trampoline.rs:181:9
  24: pyo3::impl_::trampoline::noargs
             at /home/user/.local/share/cargo/registry/src/index.crates.io-6f17d22bba15001f/pyo3-0.19.0/src/impl_/trampoline.rs:31:5
  25: polars::lazyframe::_::_::__INVENTORY::trampoline
             at /home/user/Downloads/polars/py-polars/src/lazyframe.rs:61:1
  26: <unknown>
  27: PyObject_Vectorcall
  28: _PyEval_EvalFrameDefault
  29: <unknown>
  30: PyEval_EvalCode
  31: <unknown>
  32: <unknown>
  33: <unknown>
  34: _PyRun_SimpleFileObject
  35: _PyRun_AnyFileObject
  36: Py_RunMain
  37: Py_BytesMain
  38: <unknown>
  39: __libc_start_main
  40: _start
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
Traceback (most recent call last):
  File "/home/user/Documents/for bug report/./rankAllocations.py", line 12, in <module>
    final_df.explain(optimized=True)
  File "/home/user/Downloads/polars/py-polars/polars/lazyframe/frame.py", line 889, in explain
    return ldf.describe_optimized_plan()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
pyo3_runtime.PanicException: called `Option::unwrap()` on a `None` value
```

### Expected behavior

the script runs successfully without printing anything.

### Installed versions

<details>

```
--------Version info---------
Polars:              0.18.4
Index type:          UInt32
Platform:            Linux-6.3.9-arch1-1-x86_64-with-glibc2.37
Python:              3.11.3 (main, Jun  5 2023, 09:32:32) [GCC 13.1.1 20230429]

----Optional dependencies----
adbc_driver_sqlite:  <not installed>
connectorx:          <not installed>
deltalake:           <not installed>
fsspec:              <not installed>
matplotlib:          <not installed>
numpy:               <not installed>
pandas:              <not installed>
pyarrow:             <not installed>
pydantic:            <not installed>
sqlalchemy:          <not installed>
xlsx2csv:            <not installed>
xlsxwriter:          <not installed>
```

</details>

**Comment by xyk2000** [comment]
I have also encountered this bug. And I can only run my code in streaming mode for now.

**Comment by ritchie46** [comment]
You can use cross_join directly right?

**Comment by nivkner** [comment]
yes i can. didn't realize there was a cross join before, thanks.

so i guess this has to do with the join on literal? the same operations work when using the eager API, you just get an extra literal column.

**Comment by lukemanley** [comment]
The example in the OP no longer panics
