### ISSUE TITLE
Creating dataframe with Uint64 values fails

### ISSUE THREAD

**Issue by isaacnfairplay** [pola-rs/polars#9748]
### Polars version checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pypi.org/project/polars/) of Polars.

### Issue description

When creating data frames from values in the Uint64 range I get an OverflowError
This code can be tested easily for any integer range
I saw this issue both on polars 0.18.4 and 0.18.6

### Reproducible example

```python
import polars as pl
import traceback
    min_value = 0 # min value for UInt64
    max_value = 2**64-1 # max value for UInt64
    values = list( range(min_value, max_value, (max_value-min_value)//10))
    try:
        df = pl.DataFrame({
            "test":  
                values
                })
        print(df.dtypes)
    except OverflowError as e:
        #print traceback for exception
        traceback.print_exc(limit=10)
        print(e)
```
    

### Traceback

<details>

```python-traceback
Traceback (most recent call last):
  File "C:\Users\imoor\repositories\polars-types\integers.py", line 102, in min_reproducable_example
    df = pl.DataFrame({
         ^^^^^^^^^^^^^^
  File "c:\Users\imoor\repositories\polars-types\env\Lib\site-packages\polars\dataframe\frame.py", line 353, in __init__
    self._df = dict_to_pydf(
               ^^^^^^^^^^^^^
  File "c:\Users\imoor\repositories\polars-types\env\Lib\site-packages\polars\utils\_construction.py", line 820, in dict_to_pydf
    for s in _expand_dict_scalars(
             ^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\imoor\repositories\polars-types\env\Lib\site-packages\polars\utils\_construction.py", line 729, in _expand_dict_scalars
    updated_data[name] = pl.Series(
                         ^^^^^^^^^^
  File "c:\Users\imoor\repositories\polars-types\env\Lib\site-packages\polars\series\series.py", line 276, in __init__
    self._s = sequence_to_pyseries(
              ^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\imoor\repositories\polars-types\env\Lib\site-packages\polars\utils\_construction.py", line 517, in sequence_to_pyseries
    return _construct_series_with_fallbacks(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\imoor\repositories\polars-types\env\Lib\site-packages\polars\utils\_construction.py", line 312, in _construct_series_with_fallbacks
    return constructor(name, values, strict)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^```

```
</details>

### Expected behavior
```
[UInt64]
```

### Installed versions

<details>

```
--------Version info---------
Polars:              0.18.6
Index type:          UInt32
Platform:            Windows-10-10.0.19044-SP0
Python:              3.11.1 (tags/v3.11.1:a7a450f, Dec  6 2022, 19:58:39) [MSC v.1934 64 bit (AMD64)]

----Optional dependencies----
adbc_driver_sqlite:  <not installed>
connectorx:          <not installed>
deltalake:           <not installed>
fsspec:              <not installed>
matplotlib:          <not installed>
numpy:               1.25.0
pandas:              <not installed>
pyarrow:             <not installed>
pydantic:            <not installed>
sqlalchemy:          <not installed>
xlsx2csv:            <not installed>
xlsxwriter:          <not installed>
Python polars version 0.18.6
```

</details>

**Comment by avimallu** [comment]
It looks like this is a Python error, and not an Polars error. It happens even for numpy:

```py
import polars as pl
import numpy as np
min_value = 0 # min value for UInt64
max_value = 2**64-1 # max value for UInt64
values = list( range(min_value, max_value, (max_value-min_value)//10))
np.array(values, dtype=np.int64)
```

Python doesn't seem to be able to convert this integer to a C long, which is probably a per-requisite to convert it to a Rust type that Polars will use. You might be better off directly initializing a `Series` instead of using a `dict`, which seems to bypass this requirement:

```py
import polars as pl
import numpy as np
min_value = 0 # min value for UInt64
max_value = 2**64-1 # max value for UInt64
values = list( range(min_value, max_value, (max_value-min_value)//10))
pl.Series("a", values, dtype=pl.UInt64)
```

Or, if you want a DataFrame:

```py
import polars as pl
import numpy as np
min_value = 0 # min value for UInt64
max_value = 2**64-1 # max value for UInt64
values = list( range(min_value, max_value, (max_value-min_value)//10))
pl.DataFrame({"a": pl.Series("a", values, dtype=pl.UInt64)})
```

**Comment by isaacnfairplay** [comment]
Thanks!

I was able to avoid the error by creating a numpy unit64 array instead of a python list

```python
def min_reproducable_example():
    import polars as pl
    import traceback
    import numpy as np
    pl.show_versions()
    min_value = 0 # min value for UInt64
    max_value = 2**64-1 # max value for UInt64
    print(f"Python polars version {pl.__version__}")
    values = np.random.randint(min_value, max_value, 100, dtype=np.uint64 )
    print(f"the max test value is less than the max datatype storage value = {max_value > max(values)}")
    print({type(value) for value in values})
    try:
        df = pl.DataFrame({
            "test":  
                values
                })
        print(df.dtypes)
    except OverflowError as e:
        #print traceback for exception
        traceback.print_exc(limit=10)
        print(e)
    print(df.dtypes)
```

#Version info

<details>

--------Version info---------
Polars:              0.18.6
Index type:          UInt32
Platform:            Windows-10-10.0.19044-SP0
Python:              3.11.1 (tags/v3.11.1:a7a450f, Dec  6 2022, 19:58:39) [MSC v.1934 64 bit (AMD64)]

----Optional dependencies----
adbc_driver_sqlite:  <not installed>
connectorx:          <not installed>
deltalake:           <not installed>
fsspec:              <not installed>
matplotlib:          <not installed>
numpy:               1.25.0
pandas:              <not installed>
pyarrow:             <not installed>
pydantic:            <not installed>
sqlalchemy:          <not installed>
xlsx2csv:            <not installed>
xlsxwriter:          <not installed>

</details>

###Output

> Python polars version 0.18.6
> the max test value is less than the max datatype storage value = True
> {<class 'numpy.uint64'>}
> [UInt64]
>
