### ISSUE TITLE
shrink_dtype crash if  dtype is pl.Int and all None

### ISSUE THREAD

**Issue by wukan1986** [pola-rs/polars#9809]
### Checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pypi.org/project/polars/) of Polars.

### Reproducible example

```python
import polars as pl
import polars.selectors as cs

df = pl.DataFrame({
    'a': [None, None, None],
}, schema={'a': pl.Float64})
df = df.select(cs.all().shrink_dtype())
print(df)
"""
shape: (3, 1)
┌──────┐
│ a    │
│ ---  │
│ f32  │
╞══════╡
│ null │
│ null │
│ null │
└──────┘
"""

df = pl.DataFrame({
    'a': [None, None, 1],
}, schema={'a': pl.Int16})
df = df.select(cs.all().shrink_dtype())
print(df)
"""
shape: (3, 1)
┌──────┐
│ a    │
│ ---  │
│ i8   │
╞══════╡
│ null │
│ null │
│ 1    │
└──────┘
"""

df = pl.DataFrame({
    'a': [None, None, None],  # all None
}, schema={'a': pl.Int16})  # type is int
df = df.select(cs.all().shrink_dtype())
print(df)
r"""
thread '<unnamed>' panicked at 'called `Option::unwrap()` on a `None` value', D:\a\polars\polars\polars\polars-lazy\polars-plan\src\dsl\function_expr\shrink_type.rs:19:74
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
Traceback (most recent call last):
  File "D:\GitHub\sympy_polars\examples\x.py", line 22, in <module>
    df = df.select(cs.all().shrink_dtype())
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Users\Kan\miniconda3\envs\py311_1\Lib\site-packages\polars\dataframe\frame.py", line 7134, in select
    return self.lazy().select(*exprs, **named_exprs).collect(no_optimization=True)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Users\Kan\miniconda3\envs\py311_1\Lib\site-packages\polars\lazyframe\frame.py", line 1508, in collect
    return wrap_df(ldf.collect())
                   ^^^^^^^^^^^^^
pyo3_runtime.PanicException: called `Option::unwrap()` on a `None` value
"""

```

### Issue description

if a Series is all None, and the dtype is pl.Int will crash

pyo3_runtime.PanicException: called `Option::unwrap()` on a `None` value

### Expected behavior

```python
shape: (3, 1)
┌──────┐
│ a    │
│ ---  │
│ i8   │
╞══════╡
│ null │
│ null │
│ null │
└──────┘
```

### Installed versions

<details>

```
--------Version info---------
Polars:              0.18.6
Index type:          UInt32
Platform:            Windows-10-10.0.22621-SP0
Python:              3.11.3 | packaged by Anaconda, Inc. | (main, Apr 19 2023, 23:46:34) [MSC v.1916 64 bit (AMD64)]

----Optional dependencies----
adbc_driver_sqlite:  <not installed>
connectorx:          <not installed>
deltalake:           <not installed>
fsspec:              <not installed>
matplotlib:          3.7.1
numpy:               1.24.3
pandas:              2.0.1
pyarrow:             12.0.0
pydantic:            1.10.7
sqlalchemy:          2.0.13
xlsx2csv:            <not installed>
xlsxwriter:          <not installed>
```

</details>

**Comment by mcrumiller** [comment]
What are the rules for shrinking all null values? Just use the smallest possible? Or no change? i.e. a Column of `i64` with all `None` values...should this just be cast to `i8`?
